### ISSUE TITLE
Zeugnisdruck

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#10]
Wnn ein Zeugnis aus einem vergangenem Jahr/Halbjahr gedruckt werden soll, kann zwar das Jahr im Druckreport ausgewählt werden, aber das Zeugnis wird vom aktuellen Halbjahr inkl. Daten gedruckt.

**Comment by JuergenRichter** [comment]
Ist korrigiert.

**Comment by me-rfb2000** [comment]
Kann man eine neue Schild3.0 Version erhalten, wo diese Korrektur enthalten ist?

**Comment by FPfotenhauer** [comment]
In der FB-Cloud liegt auch immer ein ZIP mit der lezten Version, die ich habe.
Das einfach in das Installationsverzcihnis kopieren.

Ansonsten bitte auch etwas Geduld haben.

**Comment by me-rfb2000** [comment]
Das habe ich ins Arbeitsverzeichnis kopiert und es ging. Nach dem Windows-update gehts wieder nicht. Verwirrend

**Comment by FPfotenhauer** [comment]
??? Arbeitsverzeichnis

Bitte ins Installationsverzeichnis kopieren.

**Comment by me-rfb2000** [comment]
ja, meine ich doch 😄

**Comment by FPfotenhauer** [comment]
Ist in Version 3.0.5.2 korrigiert.
(Bitte in Zukunft die Version dazu schreiben, in der das korrigiert ist.
Die Tester können sonst nicht entscheiden, ob sie diese Version schon haben.)
