### ISSUE TITLE
Kennwort bei einer anonymisierten Datenbank

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#100]
Das ist sicher ein außergewöhnlicher Fall: 
Bei einer anonymisierten Datenbank, die ich erstellt habe, lief alles perfekt durch. Aber der Anmeldungsdialog erscheint nicht, sondern direkt die Meldung Kennwort ungültig. Eine Eingabe wird auch danach nicht mehr angeboten, sondern nach drei Mal wird wie gewohnt bei einem falschen Kennwort das Programm beendet.

**Comment by FPfotenhauer** [comment]
Kann es sein, dass nicht die Meldung "Kennwort ungültig" kam, sondern "Es lliegt kein gültiges Kennwort vor" oder so ähnlich.

Die Prüfung auf ein Kennwort wurde in der Beta-Test-Phase erstmal wieder abgeschaltet.

**Comment by hagege** [comment]
naja, das ist schon etwas her. Da kann ich mich beim besten Willen nicht mehr dran erinnern.
