### ISSUE TITLE
Schüler mit Blockung werden beim Schuljahreswechsel nicht in neue Klasse übertragen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1001]
Ich habe eine DB im Admin-Tool dupliziert. 
Für die Original-DB habe ich eine Blockung für den JG 10 angelegt.
Anschließend habe ich diese DB hochgeschult (Ergebnis links)
Das Duplikat ohne Blockung habe ich ebenfalls hochgeschult (Ergebnis rechts)
Die Schüler bei denen eine Blockung hinterlegt ist, bleiben in ihren Jahrgängen.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/0ac5ec9d-87c7-4286-afbc-00acf8c38419)

Im Client sind die Schüler in den richtigen Jahrgängen.

**Comment by JuergenRichter** [comment]
Was heißt konkret "eine Blockung angelegt"? Wurden Kurse fü die betreffenden SuS angelegt?
Wäre es möglich, die Datenbank mit der Blockung (vor dem Hochschulen) zu bekommen (als SQLite)?

**Comment by AnneSchueller** [comment]
Ich glaube, dass es an der DB liegt. Mit zwei weiteren DBs konnte ich das nun nicht reproduzieren.
Es kam bei der Hochschulung auch diese Fehlermeldung für jeden Schüler der JG10

#23000Duplicate entry '5081-36-0' for key 'SchuelerLernabschnittsdaten_UC1': insert into SchuelerLernabschnittsdaten (Schueler_ID,Schuljahresabschnitts_ID,Wiederholung,Schulbesuchsjahre,Jahrgang_ID,ASDJahrgang,Klassen_ID,Folgeklasse_ID,Klassenart,OrgFormKrz,Hochrechnung,SemesterWertung,WechselNr,PruefOrdnung,ASDSchulgliederung,Schwerbehinderung,ID) values (5081,36,'-',11,10,'EF',1443,1442,'RK','1',0,'+',0,'APO-GOSt(B)10/G8','GY9','-',22884)

 G8 vs G9 habe ich nun schon mehrfach kontrolliert. Ich suche nochmal weiter.

**Comment by JuergenRichter** [comment]
Wäre trotzdem interessant, die Datenbank zu bekommen, um herauszubekommen, wo das Problem liegt. Dann könnte man das möglicherweise abfangen.

**Comment by AnneSchueller** [comment]
Fehler zurückzuführen auf Inkonsistenzen in der DB
