### ISSUE TITLE
Note NB, NT, AT usw. fehlen bei Teilleistungen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1002]
m.E. wäre es sinnvoll die Notenauswahl bei den Teilleistungen zu erweitern, sodass alle Kürzel, die auch bei den Noten hinterlegt sind, ausgewählt werden können.

**Comment by JuergenRichter** [comment]
Ich habe im Hauptfenster bei den Teilleistungen (zu einem einem Fach der Leistungsdaten) die Auswahlliste jetzt mal frei gelassen. das ist beim Gruppenprozess "Teilleistungsnoten eingeben" auch nicht anders. Es wird in beiden Fällen aber vor dem Speichern aber geprüft, ob die Eingabe korrekt ist.

**Comment by AnneSchueller** [comment]
Das wäre dann quasi wie auch in SchILD2. Können wir so lassen.
Diese hier fehlen noch bei der Verifikation:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/3f702bd5-f7a1-42fe-b8f9-52be564ad19c)

**Comment by JuergenRichter** [comment]
Habe ich ergänzt

**Comment by JuergenRichter** [comment]
Bei AT ist übrigens ein Schreibfehler "ärtzliches Attest". Kommt vermutl. vom SVWS-Server.

**Comment by AnneSchueller** [comment]
Tatsache... Das ist in Schild2 schon. Oder Steht AT für Attest?

**Comment by JuergenRichter** [comment]
Ja, AT sthet für "ärztliches Attest" (und nicht "**ärtzliches** Attest")
