### ISSUE TITLE
Fehleintrag bei Neu einsetzender Fremdsprache

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1003]
In der Tabelle eigeneSchule-Faecher muss der Eintrag in der Spalte AlsNeueFSInSII mit einem + belegt werden, falls abJahrgang=EF oder abJahrgang=11

Bei migrierten Fächern, die neu in der EF einsetzen ist das korrekt.
Beim Ergänzen von Fächern, die ab EF neu einsetzen, bleibt der Eintrag auf -.

**Comment by JuergenRichter** [comment]
In SchILD3 gibt es aber gar keine Funktion "Fächer der Oberstufe bearbeiten", wo in SchILD2 dieses Merkmal gsetzt werden kann. Die Oberstufenfächer werden meines Wissens im Webclient bearbeitet. Falls das Feld in SchILD3 verfügbar sein sollte, müsste man es in die "normale" Fächerbearbeitung integrieren.

**Comment by AnneSchueller** [comment]
Der Eintrag müsste beim Hinzufügen von einem Fach gesetzt werden. Unabhängig davon, ob das Fach als Fach der Oberstufe definiert wird. Im Client kann man das nicht anpassen.

**Comment by JuergenRichter** [comment]
Ich habe das jetzt in die Fächerbearbeitung integriert:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/e9478ec1-ab2a-4761-a836-83e908b343c2)

**Comment by AnneSchueller** [comment]
Könnte man die Information "Neu einsetzende Fremdsprache" nicht aus der Tabelle fachkatalog rausziehen und den Flag automatisch setzen?
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/15d2fb5f-1b9a-4834-87d2-7e348a4b73da)
