### ISSUE TITLE
Quartalsnote

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1004]
Mir ist aufgefallen, dass die Sichtbarkeit der Quartalsnote im aktuellen HJ standardmäßig deaktiviert.
Ich fände es sinnvoll, dass die anfangs immer sichtbar ist.
Weiter sollte diese anfangs links von der Note erscheinen, auch wenn man diese händisch verschieben kann.

**Comment by JuergenRichter** [comment]
Das wird doch über Einstellungen geregelt:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/f74e2a55-57f7-4388-bd44-1b1a5e3a23c6)

**Comment by Raffenberg** [comment]
Ich würde das aus dem bauch so lassen. Ist ja nur ein Klick, der dauerhaft wirkt.

**Comment by AnneSchueller** [comment]
Ich vermute, dass das anfangs zur Verwirrung führen könnte, wenn keine Quartalnoten abgebildet werden; zumal diese im Client dauerhaft sichtbar sind.  Wir können aber auch mal abwarten, wie Schulen damit zurecht kommen. Ich schließe das Issue dann erstmal.
