### ISSUE TITLE
Auswahlhäkchen gehen verloren, wenn die Auf- Abwärts-Pfeiltasten betätigt werden.

### ISSUE THREAD

**Issue by Alexander271161** [SVWS-NRW/Schild3-BetaTest#1005]
Leider entfällt ja in Schild 3.0 die Möglichkeit, SuS durch einen Doppelklick dauerhaft zu markieren. (Schade, warum eigentlich?). Dafür kann man jetzt SuS über das Auswahlhäkchen markieren und den Container auf diese Gruppe einschränken.
Wenn eine Auswahl von SuS angeklickt wurde (Häkchen gesetzt) verschwinden leider alle Häkchen wieder, sobald eine Pfeiltaste gedrückt wird. Das finde ich ungünstig, weil das im Schulalltag sicher häufiger passiert und  dann die Auswahl von Neuem begonnen werden muss.

(Ich fand die Methode aus Schild 2.0 mit den Auswahlhäkchen und dazu parallel möglichen Markierungen durch Doppeklick eigentlich extrem praktisch.)

**Comment by AnneSchueller** [comment]
Die Option, Schüler zu markieren oder auszuwählen hat bei vielen SchILD Nutzern zur Verwirrung geführt. Die Auswahl mit dem Haken soll nun die Auswahl und Markierung vereinen. Die markierten SuS können auch nach einem Neustart erhalten bleiben. Man kann die markierten Schüler filtern und nur für diese Gruppenprozesse ausführen/ Reports drucken. Somit haben wir m.E. alles wichtige abgedeckt.


@JuergenRichter : Der Bug mit dem Pfeil sollte behoben werden.  Dass alle Markierungen verloren gehen passiert Drücken der Pfeiltaste nach oben und nach unten.

**Comment by Alexander271161** [comment]
Schade, ich fand die beiden Optionen aus Schild 2.0 sehr gut.

 

Die Häkchen gehen übrigens auch verloren, wenn ich SuS markiert habe danach auf einen Kurs selektiere.

 

 

Von: AnneSchueller ***@***.***> 
Gesendet: Samstag, 27. April 2024 20:33
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Alexander271161 ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Auswahlhäkchen gehen verloren, wenn die Auf- Abwärts-Pfeiltasten betätigt werden. (Issue #1005)

 

Die Option, Schüler zu markieren oder auszuwählen hat bei vielen SchILD Nutzern zur Verwirrung geführt. Die Auswahl mit dem Haken soll nun die Auswahl und Markierung vereinen. Die markierten SuS können auch nach einem Neustart erhalten bleiben. Man kann die markierten Schüler filtern und nur für diese Gruppenprozesse ausführen/ Reports drucken. Somit haben wir m.E. alles wichtige abgedeckt.

@JuergenRichter <https://github.com/JuergenRichter>  : Der Bug mit dem Pfeil sollte behoben werden. Dass alle Markierungen verloren gehen passiert Drücken der Pfeiltaste nach oben und nach unten.

**Comment by JuergenRichter** [comment]
Der Verlust der Markierungshäkchen bei Verwendung der Pfeiltasten (inkl. "Bild hoch", "Bild runter") ist behoben.
