### ISSUE TITLE
Anzeige des Fotos nur noch auf der Startseite?

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1006]
In Konferenzen nutzen wir aktuell das schwebende Fenster zur Anzeige der Schüler. Für mich als Schulleitung ein mega Feature. Wir gehen bei Zeugniskonferenzen und BB-Konferenzen immer durch die Leistungsdaten und ich habe immer ein Bild des Schülers in der Ansicht. Das schwebende Fenster (oder die Position des Bilder wie in den letzten Versionen) sollte wählbar sein.

**Comment by AnneSchueller** [comment]
Das schwebende Fenster kann durch Klick auf "Foto zeigen" aktiviert werden und bleibt auch im aktuellen HJ sichtbar. Klappt das?
Eine permanenten Anzeige in anderen Reitern (außer Individualdaten I) haben wir aus Platzgründen weggelassen. Ansonsten gab es für bestimmt Bildschirmauflösungen Skalierungsprobleme.
