### ISSUE TITLE
Zeugniskonferenzen: Leistungsdaten und Bemerkungen auf den Zeugnissen

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1008]
Wir haben in den Zeugniskonferenzen immer die individuellen Leistungsdaten in der Ansicht. In Schild 2 können die Bemerkungen durch ein "schwebendes Fenster" angezeigt werden bzw. man erkennt, dass Bemerkungen eingetragen wurden (FETTDRUCK). Jetzt muss immer zwischen Karteireitern Leistungsdaten und Bemerkungen  gewechselt werden, um die Eingaben zu überprüfen.

**Comment by AnneSchueller** [comment]
Auf welche Bemerkungen beziehst du dich? Auf die Zeugnisbemerkungen oder die Fachbezogenen Bemerkungen? 
Die Ansicht hier hat den Vorteil, dass direkt alle Bemerkungen sichtbar sind und man hier nicht zwischen ASV, ZB usw. hin und her switchen muss. Weiter kann man die Teilleistungen aufklappen.

Ich würde hier eher keine großen Umstellungen vornehmen.

**Comment by Kluesenerm** [comment]
Auf die Zeugnisbemerkungen. In Schild 2.0 war die Übersicht in Zeugniskonferenzen sehr gut.

**Comment by AnneSchueller** [comment]
An dem Layout der Bemerkungen wird sich erstmal nichts ändern, sodass ich das Issue schließe. Vielleicht bietet der Client später eine für Euch geeignetere Visualisierung.
