### ISSUE TITLE
Filter "Vermerke" nicht nutzbar bei mehreren Vermerken (nur "oder" Filterung)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1009]
Der Filter Vermerke Filter nur noch "oder" bei zwei oder mehr Vermerken. Es gibt aber auch die Anforderung, dass beide Eintragungen vorhanden sein müssen. Z.B. "Teilnahmen am Mittagessen" und "Lebensmittelunverträglichkeit" bzw. "Allergien"
Die gute Funktion des "Negierens" durch Doppelklick verliert dadurch leider auch die Wirkung.

**Comment by JuergenRichter** [comment]
Behoben.
Wenn aber mehr als eine Vermerkart eingetragen ist, werden Einträge bei "Teil des Vermerk-Textes", "Von Vermerkdatum" und "Bis Vermerkdatum" ignoriert.

**Comment by AnneSchueller** [comment]
Das war wahrscheinlich bei Schild2 auch schon so mit dem ignorieren?
Kann man die Eingabe "Teil des Vermerk-Textes", "Von Vermerkdatum" und "Bis Vermerkdatum" sperren für den Fall, dass mehr Vermerke ausgewählt sind?

**Comment by JuergenRichter** [comment]
Sperren ist nicht ganz so einfach, da ja zuerst ein Datum oder ein Textinhalt gewählt werden kann und dann die Vermerke. Derzeit werden evtl. vorhandene Inhalte gelsöcht, wenn mehr als eine Vermerkart ausgewählt wird.

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue.
