### ISSUE TITLE
Bei Vorauswahl eines Jahrgangs werden im Auswahlfeld "Kurse" trotzdem alle Kurse der Schule angezeigt

### ISSUE THREAD

**Issue by Alexander271161** [SVWS-NRW/Schild3-BetaTest#1010]
Wenn in der aktuelle Schülerauswahl auf einen Jahrgang selektiert wird, wurden bei Schild 2.0 beim Anklicken der Kursauswahl nur noch die Kurse des Jahrgangs angezeigt. Bei Schild 3.0 werden aktuell alle Kurse der Schule angezeigt.  Das Lehrerkürzel wird nicht angezeigt. Da fällt es schwer, den richtigen Kurs zu finden, da es z.B. KR-1 in mehreren Jahrgängen geben kann.

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Gemeint ist dieses hier?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/200feee5-a4bf-4e64-ac84-eb7acd7c2dde)

Hier sollten nur die 9 er Kurse erscheinen.

**Comment by Alexander271161** [comment]
Ja, genau.

 

Von: AnneSchueller ***@***.***> 
Gesendet: Samstag, 27. April 2024 21:27
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Alexander271161 ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Bei Vorauswahl eines Jahrgangs werden im Auswahlfeld "Kurse" trotzdem alle Kurse der Schule angezeigt (Issue #1010)

 

Das kann ich reproduzieren. Gemeint ist dieses hier?

image.png (view on web) <https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/200feee5-a4bf-4e64-ac84-eb7acd7c2dde> 

Hier sollten nur die 9 er Kurse erscheinen.

**Comment by JuergenRichter** [comment]
Filterung der Kurse auf Jahrgang ist umgesetzt
