### ISSUE TITLE
Hochschulung für Grundschulen fehlerhaft

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1014]
Beim Schuljahreswechsel landen alle SuS im Abschluss. Für die Schulform Gy und Ge klappt der Schuljahreswechsel. Mein Vorgehen:

1) Eintragungen in der Klassentabelle kontrollieren:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/2a06dcdb-79fb-47e1-adb6-bcb21d5cd126)

2. Folgeklassen automatisch eintragen:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/af3e6d44-9c86-4215-ae73-08cf25767528)

3. Hochschulung
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/de1fa2a1-f924-46f5-b887-a9cf4f848073)

4. Alle SuS im Abschluss...
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/696e5074-b0ed-4b80-9c44-b078648da88d)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Mit meiner Test-Grundschule klappt das ohne Probleme. Ich bin genauso vorgegangen wie oben beschrieben:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/f139132d-8f1d-47d7-9f10-5ba04577f5d8)

**Comment by JuergenRichter** [comment]
Gibt es neue Erkenntnisse?

**Comment by AnneSchueller** [comment]
Noch nicht. 
Ich habe das einmal mit einer Original-DB getestet. Hier hat alles geklappt wie es sein sollte.
Ich warte zwar noch auf einer weitere Original-DB, schließe aber schonmal das Issue. Ich gehe davon aus, dass der Fehler aufgrund von Anonymisierungen/Hochschreibungen stammt.
