### ISSUE TITLE
Reporting - Pipeline Lernabschnitte liefert Halbjahr-Text nicht - Pipeline intern umbenannt!

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1015]
Release 3.0.85

Der MailMerge in Richtext-Feldern ist nicht korrekt in Abhängigkeit der Schreibweise:
Der folgende Code steht in einem Richtext-Feld. Bei A und C sind die Pipelines mit kleinem a und bei B und D mit großem A geschrieben. Bei A wird nichts ausgegeben bei B aber schon, Beim folgenden C wird der letzte gefundene Wert ausgegeben und bei D ist wieder alles richtig!
`A=<dbtext datapipeline='plLernabschnitte'>SchuljahrTextOhneAbschnitt</dbtext> B=<dbtext datapipeline='plLernAbschnitte'>SchuljahrTextOhneAbschnitt</dbtext> C=<dbtext datapipeline='plLernabschnitte'>Klasse</dbtext> D=<dbtext datapipeline='plLernAbschnitte'>Klasse</dbtext>`
Ergebnis sieht so aus:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/5d7d8db0-c16c-4a4b-aa25-1e997efa7d27)

Wenn alle Pipelines mit großem A geschrieben werden sieht es korrekt aus:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/e37da938-e4cf-4803-b604-dfd601ddf602)

Schlussfolgerung:
Wenn die Pipeline plxxx nicht existiert, scheint immer der letzte gefundene Wert eingesetzt zu werden, unabhängig davon ob das angegebene Feld überhaupt existiert. Existiert die Pipeline das Feld aber nicht wird immer mit einem leeren String ersetzt.

Behebung:
a) In den alten Reports wird die Pipeline Lernabschnitte immer mit kleinem a geschrieben, weswegen alle Reports angepasst werden müssten. Hier sollte darauf geachtet werden, dass entweder zwischen Groß-Kleinschreibung nicht unterschieden wird, oder dass die Pipelines den gleichen Namen haben wie in der Schild2-Version.
b) Wenn Pipelines/Datenfelder nicht gefunden werden im MailMerge wäre es schön, wenn eine Fehlermeldung angezeigt würde.
Direkt beim Speichern des Inhaltes eines RichText-Feldes mit MailMerge.

**Comment by JuergenRichter** [comment]
Die Schreibweise wurde angepasst
