### ISSUE TITLE
Report-Designer: RAP-Code nicht mehr einsehbar

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1018]
Version 3.0.87

Mit dem neuen Reportdesigner wird die Programmierung weiterhin als BASE64-Stream codiert:
  object raCodeModule29: TraCodeModule
    ProgramStream = {
      01060F547261436F6E737450726F6772616D094368696C645479706502120B50
      726F6772616D4E616D650609436F6E7374616E74730B50726F6772616D547970

Früher konnte man mit der RAP-Funktion den Quelltext der Programmierung aufrufen.
Das scheint jetzt nicht mehr möglich zu sein.
Ich dachte auch, dass die Programmierung im Klartext in der RTM-Datei steht. 
War das nicht so gedacht?

**Comment by Raffenberg** [comment]
Der Programm-Stream als Klartext war nicht lesbar, da wild unterbrochen. Deshalb sind wir wieder auf BASE64 zurückgegangen. Das erhöht die Kompatibilität zwischen Schild2 und Schild3 in der Übergangszeit (so die Theorie).

Im Kontextmenü fehlt tatsächlich der Aufruf zur Anzeige des RAP-Codes. Das ist tatsächlich sehr misslich.

**Comment by JuergenRichter** [comment]
"Im Kontextmenü fehlt tatsächlich der Aufruf zur Anzeige des RAP-Codes. Das ist tatsächlich sehr misslich."
Das ist eine Folge der ursprünglichen Umstellung auf Klartext, da war der Menüpunkt überflüssig. Wird aber wieder aktiviert.

**Comment by JuergenRichter** [comment]
Ist wieder aktiviert. Im Fenster zur Anzeige des Quelltextes gibt es derzeit einen Schalter "Bearbeiten", diese macht aber keinen Sinn mehr, da über das Anzeigefenster gar keine Speicherung der Änderung im rtm-Dokument möglich ist. Der Schalter wurde daher entfernt.
