### ISSUE TITLE
GP Ankreuzkompetenzen löschen/aktualisieren

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1019]
es kam im Forum in letzter Zeit vermehrt Fragen zum Löschen von bereits eingegeben Ankreuzfloskeln. Aktuell müssen die Anwender diese für jeden Schüler einzeln löschen. 

Könnte man im GP/Noten eine Option "Ankreuzkompetenzen löschen" ergänzen?
Ebenso wäre es m.E, sinnvoll einen GP "Ankreuzkompetenzen aktualisieren" zu implementieren. Dieser sollte dann Kompetenzen, die  nach dem Holen der Kompetenzen auf unsichtbar gestellt wurden, aus der Lister bei den Schülern entfernen.

**Comment by JuergenRichter** [comment]
Umgesetzt.
