### ISSUE TITLE
Noten und Fehlstunden

### ISSUE THREAD

**Issue by Witterschlick59** [SVWS-NRW/Schild3-BetaTest#102]
Wenn man unter Gruppenprozesse versucht, Noten und Fehlstunden einzugeben, erfolgt die Meldung "bei geschlossener Datenmenge nicht möglich".

**Comment by JuergenRichter** [comment]
Ich werde das noch korrigieren und die Version 3.0.12, die ich soeben ins Repository gelegt habe, aktualisieren

**Comment by Witterschlick59** [comment]
Perfekt, in der neuen Version tritt das Problem nicht mehr auf.
