### ISSUE TITLE
Gruppenprozess Abitur-> Prüfungsergebnisse eingeben -> Noteneingabe fehlerhaft

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild3-BetaTest#1022]
Wenn die Eingabeeistellung auf: "Noten" eingestellt wird können nicht bei allen SuS innerhalb eines Kurses Noten eingegeben werden. Wenn sie als Punkte eingegeben wurden  und man auf Noten umschaltet werden auch bei den selben SuS die Noten nicht angezeigt. Die angezeigten Noten können geändert werden, die nicht angezeigten Noten aber nicht eingetragen oder geändert werden. Außerdem stimmen die angezeigten Noten nicht.

![NotenPunkte](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/50887283/3cce6902-82b3-4383-9d5d-2900a85a40a3)

**Comment by JuergenRichter** [comment]
Die Eingabe wurde überarbeitet
