### ISSUE TITLE
Gruppenprozess Abitur -> Prüfungsergebnisse eingeben -> Eingabe von einem Punkt nur umständlich möglich

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild3-BetaTest#1024]
Die schnelle Eingabe über Tastatur ist bei einem Punkt nicht möglich, da nur zweistellige Werte akzeptiert werden. Man muss dann über das Aufklappmenü gehen. Einfaches Tippen der "Entf"-Taste nach Eingabe von 1 wäre da hilfreich.

**Comment by AnneSchueller** [comment]
Ich habe im Kopf, dass wir das schonmal diskutiert haben und keine einfach umsetzbare Lösung gefunden wurde.

Oder wäre das hier realisierbar?

**Comment by JuergenRichter** [comment]
Wir können die Liste auch einfach deaktivieren und die Eingabe rein über die Tastatur machen. Beim Speichern wird dann geprüft, ob die Eingabe eine korrekte Note bzw. Punktzahl ist.

**Comment by Raffenberg** [comment]
Anscheinend ist die Liste ja Case-Sensitiv, was sie in Schild2 nicht war. Kann man das nicht abschalten, um beides zu behalten. Ansonsten plädiere ich stark dafür, die Vorschlagliste auszuschalten.

Das Case-Sensitive Verhalten ist in mehrerlei Hinsicht kontraproduktiv:
1. Ich kann mit ENTF keine Note löschen
2. Bei Eingabe von 1 wird immer 15 angeboten (Punktemodus)
3. Bei Eingabe von 1 wird eine 1+ angeboten (Notenmodus). Ich weiß gar nicht, wie man daraus mit der Tastatur eine 1 machen kann.
4. Beim Umschalten zwischen Punkte und Notenmodus werden mir teilweise 15 Punkte im Punktemodus angeboten, während im Notenmodus keine Note steht.

**Comment by JuergenRichter** [comment]
Es gibt jetzt keine Auswahlliste mehr, das mach die Eingab sehr viel einfacher. Mit der Liste kam es nämlich immer auf die Reihenfolge an, bei einer Punkteanzeige stand da die 15 vor der 1, also wurde die 15 gewählt, obwohl 1 eingetragen werden sollte.

**Comment by HHayen** [comment]
Ist dann auch wieder möglich, Einträge zu löschen? Im GP geht das mit "Noten", mit Punkten aber weder im GP noch im Abiturreiter. Das wäre aber sehr wichtig.

**Comment by AnneSchueller** [comment]
Wenn man die Punkte markiert kann man auf entfernen klicken.
Könnte man hier noch einbauen, dass die Punkte auch gelöscht werden, wenn der Curser in dem Punktefeld drin ist und man auch entf. klickt?

**Comment by JuergenRichter** [comment]
Habe ich für das Grid der Abiturfächer und beim Gruppenprozess für die Noteneingabe umgesetzt.
