### ISSUE TITLE
Leistungsdaten holen für ZP10 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1025]
Beim Holen der ZP10 Leistungsdaten erfolgt stets eine Abfrage, welche Daten man holen möchte. Die meisten Schulen wollen nur die Fächer selbst in den Reiter holen. Könnte dieses Fenster ergänzt werden um "ZP10 Fächer holen" 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/5ede8750-070b-451a-a15f-9e167e1d9f7c)

**Comment by AnneSchueller** [comment]
Alternativ könnte man auch einen weiteren Unterreiter anlegen "Fächer holen"
(zwischen "Alle Fächer löschen" und "Leistungsdaten holen"

**Comment by JuergenRichter** [comment]
Es gibt jetzt eine zusätzliche Option:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/e4a61c16-9f73-4331-b41e-a2d5b5d88d73)

**Comment by AnneSchueller** [comment]
Wäre es vom Platz her ausreichend, wenn der Button umbenannt wird zu 
"Fächer-/Leistungsdaten holen"

**Comment by JuergenRichter** [comment]
Ist umgesetzt
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/bcb7cb9f-de02-466d-8578-70882b4cea08)
