### ISSUE TITLE
Fehlermeldung beim Filtern auf Mahungen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1029]
Nach Klick auf Testen im Schuelerfilter mit Angabe Mahnung =ja erhalte ich eine Fehlermedlung:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/fce75ab9-b7ce-433f-978e-4fd612c44d06)

[mahnung.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/15481760/mahnung.txt)

**Comment by JuergenRichter** [comment]
Behoben
