### ISSUE TITLE
Deinstallation SchILD3.0 und SVWS-Server

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#103]
Bei der Deinstallation wird der Ordner von SchILD3.0 nicht komplett gelöscht. Es bleibt auf jeden Fall bei mir der Ordner "sdbcfg" erhalten, so dass der SchILD3.0-Ordner noch manuell gelöscht werden muss.

**Comment by FPfotenhauer** [comment]
Das ist ganz normal, weil diese Dateien ja nicht vom Inno-Setup erstellt werden.
Ich denke auch, das man mit einer Deinstallation nicht die Datenbanken löschen sollte.
Macht der SVWS-Server im übrigen auch nicht.

**Comment by hagege** [comment]
ah, wusste ich nicht.
