### ISSUE TITLE
FHR-Algorithmus arbeitet nicht korrekt

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1033]
Bei der SchülerID 40705 aus der Testdatenbank:

Der FHR-Algorithmus ermittelt folgendes und vergisst den 2. LK zu markieren:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/b0460e11-8a7d-412b-a05e-c7b36e733094)

Markiert man die von Hand nach ist das Ergebnis auch schlechter als das Ergebnis aus 12.1+12.2:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/a2b2e05d-25b5-42da-802c-1b605b882337)

Manuell markierte Kurse führen zur FHR:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/49098f4e-3545-4054-b368-b751557df173)

**Comment by AnneSchueller** [comment]
Hallo Ewalt,
Du beziehst dich hier auf die BK-DB aus dem Github richtig?
Ich finde irgendwie die SchülerIDs nicht, die du angegeben hast.
Hast du mal einen Namen für mich?

**Comment by beaumart** [comment]
Ich habe in unserer DB drei Notenbilder gefunden, bei denen Schild3 zu einem schlechteren FHR kommt als Schild2. Siehe Anlagen. Hier sind die Notenbilder je eines Schülers jeweils in Schild3 und Schild2 nebeneinander dargestellt und die Unterschiede markiert.
![FehlerFHR2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/50887283/c1fafe1a-54f1-47aa-99a4-f367b5e896bd)

![FehlerFHR3](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/50887283/c7c2c131-97e8-4ec6-9278-d95552127bd7)

![FehlerFHR1](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/50887283/e08c0aed-d104-4ee3-ac7f-ff924f138ca3)

**Comment by EwaldReinhardt** [comment]
> Hallo Ewald, Du beziehst dich hier auf die BK-DB aus dem Github richtig? Ich finde irgendwie die SchülerIDs nicht, die du angegeben hast. Hast du mal einen Namen für mich?

Ich beziehe mich auf die Datenbank: https://github.com/SVWS-NRW/SVWS-TestMDBs/blob/main/Berufskolleg/BK-Test-Daten-04/BK-Test-Daten-04.mdb

**Comment by EwaldReinhardt** [comment]
> Ich habe in unserer DB drei Notenbilder gefunden, bei denen Schild3 zu einem schlechteren FHR kommt als Schild2. Siehe Anlagen. Hier sind die Notenbilder je eines Schülers jeweils in Schild3 und Schild2 nebeneinander dargestellt und die Unterschiede markiert.

Es sieht so aus, dass der Fehler dann auftritt, wenn der bessere Kurs im zweiten der beiden Halbjahre ist und im ersten kein Kurs vorliegt.
Hartmut, kannst du mal versuchen z.B. im ersten Fall die Note von SW ins Halbjahr 22/23#2 zu verschieben und schauen ob es dann richtig ist.

**Comment by beaumart** [comment]
Hallo Ewald,
ich hab die SW Noten um ein Halbjahr verschoben und dann wird die FHR korrekt berechnet. Deine Vermutung scheint zu stimmen.
![FHR](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/50887283/a881eb04-84d4-499b-a534-615348ef9117)

**Comment by JuergenRichter** [comment]
Ich habe mir das mal angeschaut. Dazu erst mal folgende Informationen:
-Der Algorithmus wurde ursprünglich für allgemein-bildende Schule erstellt
-Intern verwendet der Algorithmus die "ASD-Kürzel" der Fächer, nur darüber kann eindeutig erkannt werden, dass ein Fach z.B. "Mathematik" ist (die schulinternen Kürzel sind ja frei vergebar)

Das Problem liegt nun darin, dass im konkreten Fall ein ASD-Kürzel doppelt vorkommt (Fach MAT und MbT, beide haben das ASD-Kürzel "FB"), ein solcher Fall kommt an allgemein-bildenden Schulen nicht vor.
Im Algorithmus muss ein Fach an manchen Stellen in der Fächerliste gefunden werden (anhand des ASD-Kürzels), wenn das ASD-Kürzel aber (wie im konkreten Fall) mehrfach vorkommt, ist es reiner Zufall (bzw. hängt von der Reihenfolge ab, wie die Fächerliste befüllt wird), welcher Eintrag verwendet wird. Dass das Verhalten in SchILD2 anders ist, liegt daran, dass die Reihenfolge dort anders ist (weil es dort ein Reihenfolgenfeld gibt, das in SchILD3 weggefallen ist).

Ich habe nun folgende Lösung gefunden:
Bei der Befüllung der Liste wird geprüft, ob ein Fach (als ASD-Kürzel) schon in der Liste enthalten ist. Wenn dem so ist, wird das Kürzel um eine Zahl ergänzt (FB1). Das ist dann zwar kein "richtiges ASD-Kürzel" mehr, das ist aber für den Algorithmus egal.

Damit bekomme ich nun folgendes Ergebnis:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/4d5286fc-7476-40e8-b102-20ae6e77e3ca)

Das ist auch das Ergebnis, dass über die manuelle Markierung erreicht wird.

**Comment by JuergenRichter** [comment]
Das zweite beschriebene Problem (Markierung von Fächern, die nicht durchgehend belegt sind) ist auch behoben.

**Comment by EwaldReinhardt** [comment]
Test mit 3.0.89/0.8.16

meine Tests werden jetzt richtig abgearbeitet.
@beaumart teste bitte deine Beispiele auch nochmal durch.
