### ISSUE TITLE
BK Fachklassen: Feld über "DQR-Niveau" ist nicht beschriftet, was ist das?

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#1034]
Siehe Titel, das Feld über "DQR-Niveau" und rechts von "Bezeichnung" ist nicht beschriftet.

**Comment by EwaldReinhardt** [comment]
Das ist der Fachklassenschlüssel, der für die Statistik ausgegeben wird.

Die Überschrift sollte ergänzt werden.

**Comment by AnneSchueller** [comment]
Unter Kataloge/Fachklassen

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/608a0aad-b2fb-49de-a319-b88a88f75533)

**Comment by JuergenRichter** [comment]
Behoben, da steht jetzt "Fachklassenschlüssel"
