### ISSUE TITLE
Schule > Schulleitung: Error LeitungsfunktionID

### ISSUE THREAD

**Issue by KaBe47Du** [SVWS-NRW/Schild3-BetaTest#1036]
Verwaltung > Schule > Allgemeine Angaben > Schulleitung:
Hinzufügen mit +, Interne Bezeichnung eingeben und Häkchen zur Bestätigung führt zum Fehler

#HY000Field 'LeitungsfunktionID' doesn't have a default value.

**Comment by kroerig** [comment]
Ja, kann ich ebenfalls bestätigen.
[stack-trace.txt](https://github.com/user-attachments/files/15853500/stack-trace.txt)

**Comment by JuergenRichter** [comment]
Behoben

**Comment by JuergenRichter** [comment]
Es wird jetzt eine Meldung ausgegeben, wenn die Angaben nicht vollständig sind (das führte im beschriebenen Fall zu dem Fehler):

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/f8c054da-f370-4b79-bf32-c9c80d84ecba)
