### ISSUE TITLE
Import Informationstexte Korrektur

### ISSUE THREAD

**Issue by KaBe47Du** [SVWS-NRW/Schild3-BetaTest#1037]
Verwaltung > Import > Unterrichts-Daten (als Excel-Datei): Informationen anzeigen

- Hier können Sie Unterrichtsdaten, in Form von Excel-Dateien importieren. (Komma weg)
- Der Eintrag muss in Kombination mit, Jahr, Abschnitt und Jahrgang eindeutig sein! (1. Komma weg)
- Die Klassenbezeichnung, muss in der Klassen-/Versetzungstabelle vorhanden sein. (Komma weg oder - falls stichwortartig gewünscht, "Die" weg)
- Folgende Kombinationen mit der Kursbezeichnung sind möglich: (Leerezeile davor)
- Spalte 5: Jahrgang (Frage: Wie wird ein Unterricht für mehrere aber nicht alle Jgst eingetragen?))
- Die Fachbezeichnung, muss in der Fächertabelle vorhanden sein. (Komma weg)
- Die allgemeine Kursart, muss in der Tabelle der allg. Kursarten in SchILD vorhanden sein. (Komma weg)
- Anz. Wochenstunden, die vom Kursleiter gehalten werden, falls leer, wird Gesamt-Wochenstd. (Spalte 8) angenommen Wird (Punkt vor "Wird")
- Kursleiter bzw.  Fachlehrer (Leerzeich vor Fachlehrer zu viel)
- Die Wochenstunden einer Zusatzkraft, wird bei Klassenunterricht (Spalte 2 nicht leer) als  (Wie geht der Satz weiter?)

**Comment by JuergenRichter** [comment]
Korrigiert. Der Text steht in einer externen Datei (Excel_Unterrichtsimport.txt), die sich im Programmverzeichnis befinden muss (nur wenn diese existiert, ist der Schalter "Informationen anzeigen" aktiv). Ich habe die Datei beigefügt.
Wichtig: Bitte in das Setup übernehmen.
[Excel_Unterrichtsimport.txt](https://github.com/user-attachments/files/16079449/Excel_Unterrichtsimport.txt)

**Comment by JuergenRichter** [comment]
Hier nochmal aktualisierte Datei. In der vorhandenen stand noch "Halbjahr bzw. Quartal". Quartale gibt es aber jetzt nicht mehr.
[Excel_Unterrichtsimport.txt](https://github.com/user-attachments/files/16079866/Excel_Unterrichtsimport.txt)

**Comment by AnneSchueller** [comment]
Noch zwei Kleinigkeiten:

Spalte 8: Wochenstunden
Gesamt-**Wochendstunden,** so wie sie bei den Schüler-Leistungsdaten eingetragen werden. --> Wochenstunden

Beispiel 1: 2 Std. Sport als Klassenunterricht in Klasse 06A im 2. Hj. 2024/25 bei Lehrer "BO", kein **Epochen unterricht** --> Epochenunterricht

**Comment by JuergenRichter** [comment]
Hier die korrigierte Datei, bitte in das Programmverzeichnis kopieren.
[Excel_Unterrichtsimport.txt](https://github.com/user-attachments/files/16358803/Excel_Unterrichtsimport.txt)
