### ISSUE TITLE
Aufräumen unvollständiger Text

### ISSUE THREAD

**Issue by KaBe47Du** [SVWS-NRW/Schild3-BetaTest#1038]
Verwaltung > Werkzeuge > Aufräumen:
Erläuternder Text ist nicht vollständig zu sehen.

**Comment by AnneSchueller** [comment]
Hallo Kai,

erstmal vielen Dan fürs Testen und für das Melden sämtlicher Fehler.
In meiner Ansicht sieht hier alles gut aus. Welche Auflösung/wieviel Zoll hat dein Monitor?

**Comment by FrodBRA** [comment]
Weiterhin ist hier oft auch die Skalierung in MS Windows hilfreich.

**Comment by JuergenRichter** [comment]
Habe jetzt etwas mehr Platz zur Verfügung gestellt.

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue mal. Sollte hier weiterhin Text abgeschnitten sein, kann das Issue nochmal geöffnet werden.
