### ISSUE TITLE
Wechsel des Reiters im Bereich Schüler nicht möglich

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1039]
3.0.88.15/0.8.15
Verwendete Datenbank: https://github.com/SVWS-NRW/SVWS-TestMDBs/blob/main/Berufskolleg/BK-Test-Daten-03/BK-Test-Daten-03.mdb
SchülerID: 31635

Schüler 31635 auswählen
BK-Abschluss Reiter auswählen
Leistungsdaten holen (akt. Halbjahr oder Abitur)
Wechsel zu Akt. Halbjahr -> Dialognachfrage ...Trotzdem fortfahren? -> JA -> !!kein Wechsel des Reiters.

(Wenn man auf Markierte (im Ribbon) klickt, wird zum Reiter IndividualDaten I gewechselt.

**Comment by AnneSchueller** [comment]
Hallo Ewald,
kannst du nochmal nach der Schülerid schauen oder den Schülernamen dazuschreiben? 31635 finde ich in der DB nicht.

**Comment by EwaldReinhardt** [comment]
Es ist die BK-Test-03 Datenbank.

**Comment by EwaldReinhardt** [comment]
Ergänzung:
Wenn man auf die Reportverwaltung wechsel möchte kommt folgende Fehlermeldung:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/5fe63a5b-7386-44dc-b25f-dbd11dcb74c1)

Die Oberfläche sieht dann so aus (Der Menupunkt Reportverwaltung ist aktiv, aber der Bereich nicht):
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/ce14064d-076a-4261-90de-00aa64c8d580)

**Comment by JuergenRichter** [comment]
Behoben, siehe auch https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1045
