### ISSUE TITLE
Anlegen einer DSGVO-Einwilligung

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#104]
Beim Anlegen eines neuen Eintrags kommt momentan noch ein Fehler.
Das werden wi rim Schema korrigieren, es wurde vergessen die ID als AutoIncrement anzulegen.

Allerdings fehlt im neuen Design das Schließen des Fensters. Somit läuft der Prozess des Anlegens der Einträge bei den Schülern nicht ab.

**Comment by JuergenRichter** [comment]
In 3.0.13.3 behoben
