### ISSUE TITLE
Anlage D01 - Abiturreiter anzeigen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1042]
In der Anlage D01 werden in den StatistikJahrgängen die Einträge SII-1, SII-2, SII-3 und SII-BK eingetragen.
Dann wird im Jahrgang 04 der Gliederung der Reiter Abitur nicht mehr angezeigt. 
Es wäre schön, wenn hier der Reiter zumindest angezeigt wird, da ja die schriftlichen Arbeiten im Abschlussjahr im 
Reiter BK-Abschluss für die Abschlussberechnung eingetragen sein müssen.
(Solange Issue #1041 nicht erledigt ist).
Aber auch sonst sollten die Daten zumindest eingesehen werden können.

**Comment by JuergenRichter** [comment]
Es gibt jetzt am BK eine weitere Option für die "Sek.-Stufe"
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/88b48405-4519-46a5-bc02-d88d4b1ccc84)
Wenn ein Schüler sich in einem solchen Jahrgang befindet, wird der Abiturreiter angezeigt, ist aber nicht bearbeitbar.
