### ISSUE TITLE
Fehlermeldung nach Klick auf Leistungsdaten holen im Reiter BK Abschluss

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1044]
Nach dem Klicken auf Leistungsdaten holen im BK Anschluss erscheinen zwar die geholten Fächer. Klickt man anschließend auf einen andren Schüler/Reiter kommt folgende Fehlermeldung:

[BK_Abschluss_LDHolen.txt](https://github.com/user-attachments/files/15867009/BK_Abschluss_LDHolen.txt)

**Comment by JuergenRichter** [comment]
Behoben, siehe auch #1045
