### ISSUE TITLE
Fehler bei Bestätigung „Art des Abschlusses“ unter dem Reiter Schulbesuch

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild3-BetaTest#1045]
Wenn unter  dem ReiterSchulbesuch die „Art des Abschlusses“ bestätig werden soll tritt eine Fehlermeldung auf und Schild3 muss beendet werden. (Siehe Screenshot)
![FehlerSchulbesuchArtDesAbschlusses](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/50887283/d5d2caf4-59ff-4add-bf37-fa3ca6a0a67d)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Hier auch der vollständige log:

[ArtDesAbschlusses.txt](https://github.com/user-attachments/files/15883061/ArtDesAbschlusses.txt)

**Comment by beaumart** [comment]
Ich merke gerade, dass jeder beliebige Eintrag unter „Entlassung von eigener Schule“ die Fehlermeldung hervorruft!

**Comment by AnneSchueller** [comment]
Ich öffne das Issue nochmal. Der Fehler sollte ja definitiv behoben werden.

**Comment by beaumart** [comment]
Hallo Anne,Ich habe gerade versehentlich mein letztes Issue geschlossen, ich wollte aber nur eine Ergänzung eintragen. Ich bekomme es nicht mehr geöffnet😳Von meinem iPad gesendetAm 18.06.2024 um 10:47 schrieb AnneSchueller ***@***.***>:﻿
Das kann ich reproduzieren. Hier auch der vollständige log:
ArtDesAbschlusses.txt

**Comment by AnneSchueller** [comment]
Hallo Hartmut
Ich hatte das Issue wieder geöffnet.
VG

**Comment by JuergenRichter** [comment]
Ist behoben, da war noch das Feld "Bemerkungen" (das es jetzt nicht mehr gibt) im Update-Befehl der Tabelle "Schueler".
