### ISSUE TITLE
Verhalten Gruppenprozess „Entlassung von eigener Schule“ nach Ausführung

### ISSUE THREAD

**Issue by beaumart** [SVWS-NRW/Schild3-BetaTest#1047]
Beim Gruppenprozess „Entlassung von eigener Schule“ bleibt nach der Ausführung das Datum in der Anzeige stehen, alle anderen Einträge werden gelöscht. Es sollten entweder alle Einträge erhalten bleiben oder kein Eintrag!

**Comment by AnneSchueller** [comment]
Stimmt, bei den anderen Feldern verschwindet der Eintrag in dem GP-Fenster nach Ausführen.
Analog bleibt das Datum auch in dem oberen Entlassdatum:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/600a95c4-674e-4385-b50f-b141e5fee5a4)

**Comment by AnneSchueller** [comment]
Ergänzung: Das Verhalten zeigt sich bei allen Eingaben mit Datum

**Comment by JuergenRichter** [comment]
Behoben, Datumsfelder werden nun geleert
