### ISSUE TITLE
WBK: FHR-Algorithmus starten

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1048]
Wir erhalten bei der FHR-Berechnung bzw. speziell unter dem Punkt "FHR-Algorithmus starten" folgenden Fehler:
(hier noch die Ansicht nach der Migration aus Schild 2 mit richtiger Fächerreihenfolge):
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/f70e6037-4ea1-4b02-9002-c1bfda0bea2c)

Außerdem werden die Fächer in Schild 3.0 unter "Leistungsdaten holen" in falscher Reihenfolge geladen:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/1a7a1d4d-0eb7-40b6-a60e-a6ed8ff1ac35)

**Comment by AnneSchueller** [comment]
Das kann ich für WBKs reproduzieren. Am Gym klappt das.

[fhr_wbk.txt](https://github.com/user-attachments/files/15892046/fhr_wbk.txt)
