### ISSUE TITLE
Fehlermeldung von Datenbank irreführend

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1049]
Wenn eine Datenbank nicht mehr existiert, die im Connectionfile eingetragen ist,
wird folgendes ausgegeben:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/02db746f-2ca3-4500-ba39-deecbd83ff23)

CrystalReports zeigt aber richtigerweise an:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/e222d956-7a02-49ee-a781-3fb2b6660243)

Diese Meldung hilft viel eher weiter als die obere.

**Comment by JuergenRichter** [comment]
Es wird jetzt eine "sprechendere" Meldung ausgegeben
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cccf6dcf-a4c1-4c7a-a159-758a0ae4f727)
