### ISSUE TITLE
Export über Schnittstelle SchILD-NRW funktioniert nicht

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1050]
Version 3.0.88.15/0.8.15

Wenn man zum Export die  Schnittstelle SchILD-NRW nutzt
bekommt man den folgenden Fehler und es werden nur 4 Dateien erzeugt:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/a8a90fad-09d4-4015-8cb3-5c9b5ae0ecd4)
dann:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/41cee43b-6931-4474-aabc-dce509fd66c5)
[FehlerExportSchnittstelleSchILD-NRW.txt](https://github.com/user-attachments/files/15924992/FehlerExportSchnittstelleSchILD-NRW.txt)

Diese vier Dateien werden erzeugt:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/fd5fa585-e7c9-4c2a-82af-8c5f68460565)

**Comment by JuergenRichter** [comment]
Ist behoben
