### ISSUE TITLE
Berechnung des Referenzniveaus 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1052]
Wird das Referenzniveau in SchILD3 berechnet oder läuft das über den SVWS-Server?
Aktuell werden nach der Berechnung die falschen Werte eingetragen.
Neu für die jetzigen 10 er am GY und ab SJ 24/25 auch für weitere Schulformen ist der Eintrag B1+ statt B1 in JG10:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/239b3847-0bd4-41d0-8f50-bb96bc2bb497)

**Comment by JuergenRichter** [comment]
Das erfolgt in SchILD, werde ich anpassen.

**Comment by JuergenRichter** [comment]
Ist umgesetzt

**Comment by AnneSchueller** [comment]
Die Berechnung der Referenzniveaus funktioniert noch nicht:
![image](https://github.com/user-attachments/assets/cc6282f7-2b16-4025-b65e-d1a267e8c22b)


![image](https://github.com/user-attachments/assets/ce095e9c-481f-4599-b3b7-20cd2a50287a)
