### ISSUE TITLE
Gliederung bei Förderschulen fehlt nach Migration

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1053]
In Schild 2 und im Client ist "Standard für diese Schulform vermerkt. 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/dc0f5f5e-f01d-4018-84b8-419e8ba5c69f)

**Comment by JuergenRichter** [comment]
Ist denn bei den Schuldaten die Gliederung vorhanden?

**Comment by AnneSchueller** [comment]
Unter Verwaltung/Schule/Gliederung ist der Eintrag da analog wie auch in SchILD2

Im Client stehen seltsamerweise auch die ***- mit im Eintrag:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/282a9b8f-3f2f-4877-b59b-25907bc021d7)

**Comment by JuergenRichter** [comment]
Können Sie mir mal die MDB zur Verfügung stellen?

**Comment by AnneSchueller** [comment]
Ich schicke Ihnen einen Downloadlink.

**Comment by JuergenRichter** [comment]
Bei den drei Schülern, die in der obigen Abfrage angezeigt werden, erscheint die Angabe zur Gliederung auch korrekt:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/0a1f8495-24bc-4a01-a071-e4f55536ea2e)

**Comment by ThomasBachran** [comment]
Hier lag ein Problem bei der Migration vor. Die Schulgliederung wurde hier nicht als der Schulform S zugehörig erkannt. Das Problem ist jetzt behoben.

@JuergenRichter : Ich habe bei der Schulgliederung schon öfters Einträge mit null gehabt, wo eigentlich ein gültiger Wert stehen sollte. Daher geht der SVWS-Client bei NULL von einer Schulform-abhängigen Default-Wert aus (siehe Code-Ausschnitt):
```
		if ((sf == Schulform.GY) || (sf == Schulform.SK) || (sf == Schulform.GM) || (sf == Schulform.G)
				|| (sf == Schulform.S) || (sf == Schulform.PS) || (sf == Schulform.V) || (sf == Schulform.FW)
				|| (sf == Schulform.H) || (sf == Schulform.R) || (sf == Schulform.GE) || (sf == Schulform.SR)
				|| (sf == Schulform.SG))
			return Schulgliederung.DEFAULT;
```
Dies sollte man mMn auch für Schild 3 entsprechend handhaben.
