### ISSUE TITLE
Fehlermeldung bei Aktivierung von "Neu zugewandert"

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1054]
Beim Aktivieren von "Neu Zugewandert" erscheint eine Fehlermeldung. 

[NeuZugewandert.txt](https://github.com/user-attachments/files/16026284/NeuZugewandert.txt)

**Comment by JuergenRichter** [comment]
Der Fehler erscheint bei allen Änderungen von Stammdaten, weil im Update-Befehl noch ein Verweis auf das nun weggefallene Feld "Bemerkungen" drin steht. Das ist schon korrigiert. Ich werde am Nachmittag mal eine aktuelle Programmversion bereitstellen, dann kann dieses (und andere Issues mit gleicher Ursache) geschlossen werden.
