### ISSUE TITLE
Telefonnummersuche

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1056]
Ein Wunsch, den ich nachvollziehen kann:

Eine Suche nach einer Telefonnummer im Schülerfilter.  Dabei wäre es sinnvoll, auch bei den Erziehungsberechtigten nach dieser Nummer zu suchen und den entsprechenden Schüler im Container anzuzeigen.
Ich kann das nicht einschätzen, wie hoch der Implementieraufwand ist. Daher gerne das Issue in die Diskussion für später mal verschieben.

**Comment by JuergenRichter** [comment]
Das Problem dürfte sein, dass die Suche dann genauso eingegeben werden muss, wie sie auch bei den Telefonnummern hinterlegt ist.
Beispiel 
0221-123456 ist bei den Nummern eingetragen
Bei der Suche wird 0221123456 eingegeben >> Nummer wird nicht gefunden

Lösung: Einheitliche "Maske" für die Telefonnummer derart, dass z.B. nur Ziffern eingegeben werden dürfen. Dann müsste das aber auch schon bei der Migration umgeändert werden (also aus 0221-123456 wird 0221123456)

**Comment by JuergenRichter** [comment]
Ich habe das mal ausprobiert, man kann auch eine Maske setzen, so dass nur numerische Zeichen eingegeben werden können, vorhandene Werte mit nicht-numerischen Zeichen werden trotzdem korrekt angezeigt. Eine Eingabe ist aber nur mit Ziffern möglich.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/49d7433b-3c75-46c5-9384-f03b6f3f18ec)

Darüber könnte man erreichen, dass neu eingegebene Telefonnummern nur noch Ziffern enthalten können.

**Comment by JuergenRichter** [comment]
Ich habe die Maske jetzt mal in den Telefonnummernfeldern umgesetzt, bitte mal im nächsten Update testen.

**Comment by JuergenRichter** [comment]
Frage: Geht es darum, einen Schülerdatensatz anhand einer Telefonnummer zu finden 
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/98ea1065-35d7-47e2-b2fe-0f02808a6daf)
oder zu filtern (Schülerfilter, ehemals Filter I).

**Comment by AnneSchueller** [comment]
An die Suchfunktion hatte ich gar nicht gedacht. Das wäre wahrscheinlich noch eleganter.
Im Prinzip soll anhand einer Telefonnummer im Display (egal ob vom Schüler oder von den Eltern o.ä) der zugehörige Schüler ermittelt werden.

**Comment by kroerig** [comment]
Und am besten noch direkt per TAPI

**Comment by FrodBRA** [comment]
Die Telefonnummernsuche muss noch intelligenter werden, ansonsten ist sie nutzlos.

1. Unabhängig davon, was eingetragen ist, reduziert die Suchfunktion die Zieldaten und auch den Suchstring auf reine numerische Folgen. D.h. 0123 - 32 1242 212 wird zu "0123321242212", Leerzeichen und Sonderzeichen und sonstige Zeichen werden ignoriert.
2. Gleichzeitig werden eine führende "0", "049", "+49" und "++49" als identische Folgen behandelt (der Nutzer bekommt auch hiervon nichts mit).

Alles, was weniger vollständig ist, kann meiner Meinung nach direkt deaktiviert werden.

**Comment by kroerig** [comment]
Diese Funktion sollte dann auch im SVWS Client parallel umgesetzt werden.

**Comment by JuergenRichter** [comment]
Die Telefonnummernsuche ist im nächsten Update umgesetzt

![image](https://github.com/user-attachments/assets/07f3aa24-0994-410e-aa57-b0ea30042046)
