### ISSUE TITLE
Fehlermeldung bei Berechnung des Referenzniveaus

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1059]
Nach Klick auf "Referenzniveau berechnen" im Reiter Laufbahninfo erscheint eine Fehlermeldung:

[sprachenfolge.txt](https://github.com/user-attachments/files/16097737/sprachenfolge.txt)

Version 3.0.89.15

**Comment by JuergenRichter** [comment]
Behoben
