### ISSUE TITLE
Fenster in der Vertikalen nicht vollständig sichtbar bzw. nur mit Rollbalken sichtbar

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#106]
Version 3.0.12.3
Bei einer Auflösung von 1360x768 Bildpunkten werden die Fenster in der Höhe nicht vollständig dargestellt. Bei der Seite Individualdaten I sieht man bis zur zeile "Staatsangehörigkeit".
Ein Ändern der Skalierung auf z.B. 80% liefert keine Änderung.

**Comment by JuergenRichter** [comment]
Eigentlich sollte in solchen Fällen ja eine "Scrollbox" aktiv werden, mit der man den Ausschnitt hin- und herschieben kann. Erscheinen denn im vorliegenden Fall keine "Scrollbars"?

**Comment by WLey-49** [comment]
Es ist ein Rollbalken vorhanden, aber die Bedienung ist dann lästig und man sieht nicht alles auf einen Blick.
Die Fenstergröße müsste an die Bildschirmgröße angepasst sein.

**Comment by JuergenRichter** [comment]
Wir haben das jetzt so angepasst, dass die "Schüler-Info-Leiste" (wo auch das Bild dargestellt wird, sofern vorhanden) nur dann angezeigt wird, wenn die Fenstergröße das hergibt. Dadurch ist dann Platz für die nicht direkt angezeigten Bereiche vorhanden.
