### ISSUE TITLE
Fehlermeldung beim Anlegen eines Schülers

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1060]
Beim Klick auf "übernehmen" nach dem Anlegen eines Schülers erscheint folgende Fehlermeldung:

[NeuerSchueler.txt](https://github.com/user-attachments/files/16097756/NeuerSchueler.txt)

Version 3.0.89.15

**Comment by JuergenRichter** [comment]
Behoben
