### ISSUE TITLE
Semesterwechsel für WBKs (Anzeige unter Verwaltung)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1062]
In der Anzeige für den Schuljahreswechsel unter Verwaltung Schule steht bei den WBKs "Halbjahreswechsel". Hier sollte Semesterwechsel stehen:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/ba176817-1e3e-4777-af8d-1ed54a677c6a)

**Comment by JuergenRichter** [comment]
Ist umgesetzt
