### ISSUE TITLE
Schild3 Zugriff auf Debian

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#1063]
Ich habe auf einer Debian-Installation den SVWS-Server (Version 0.8.15) installiert. Ich kann von meinem Windows-Rechner aus auf den SVWS-Server auf dem Debian zugreifen. Wenn ich das von meinem Windows-Rechner aus per Schild3 (3.0.88.15) versuche, bekomme ich immer die folgende Fehlermeldung. Die Datenbank habe ich auf dem Linux-Rechner nicht migriert, sondern per Backup aus einer SQLLite-Datenbank wiederhergestellt.
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/3e83b2b4-8b15-4f42-9151-b33331f0f2fe)

**Comment by kroerig** [comment]
Ist der Datenbankname bei beiden Servern gleich?
Ich hatte das auch mal, dass ich - in dem Fall aber per MariaDB-Dump - eine DB in eine neue DB geklont hatte und dann war SchILD auch beleidigt und fand die Tabellen nicht mehr.

Schauen Sie doch mal in die DB rein, ob die genannte Tabelle wirklich nicht existiert. Und ob die Schreibweise stimmt.

**Comment by FPfotenhauer** [comment]
Da ist anscheinend etwas beim einspielen des Backups schief gegangen.
Wie alt war das Backup? Wie wurde das Backup eingespielt? Mit dem Admin-Client?

**Comment by JeVaske** [comment]
Es lag daran, dass noch ein altes Schema im Admin-Client vorhanden war. Das hatte ich dann verwechselt. Jetzt läuft alles perfekt. Issue kann geschlossen werden.

**Comment by FPfotenhauer** [comment]
Kann man das nicht selbst schließen, wenn man der Eröffner war? Hätte ich gedacht ...
