### ISSUE TITLE
Schnittstelle-NRW - EXPORT : fehlendes Leerzeichen zwischen Straße und Hausnummer

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1064]
Beim Export über die Schnittstelle SchILD-NRW fehlt in der Datei **Adressen.dat** ein Leerzeichen zwischen Straße und Hausnummer im Feld Straße.

**Comment by JuergenRichter** [comment]
Behoben, galt im übrigen für alle Adress-Exporte
