### ISSUE TITLE
Fehlende Toolbar im Dialog "Allgemeine Adressdaten bearbeiten"

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1066]
Den Dialog kann man unter dem Reiter Schüler/Adressen_Betriebe aufrufen.
Im Dialog fehlt die Toolbar 
![grafik](https://github.com/user-attachments/assets/0525ef9a-0e16-40db-8c6f-61eae182b5a4)
um Änderungen verwerfen zu können.

![grafik](https://github.com/user-attachments/assets/76d757d2-0ea2-4018-a5c2-dc85e12fc365)

**Comment by AnneSchueller** [comment]
@EwaldReinhardt :  
Das Löschen und Hinzufügen von Einträgen wird über die vorangehende Seite getätigt (Schueler/Betriebe). Daher fände ich das an dieser Stelle überflüssig. 
Änderungen werden unmittelbar übernommen. Hier wäre nur die Frage ob der Anwender ein Häkchen benötigt, um die Eingabe abzuschließen

**Comment by EwaldReinhardt** [comment]
Das Verwerfen von Änderungen ist dann aber nicht mehr möglich

**Comment by JuergenRichter** [comment]
Der Schalter ist ein Relikt aus SchILd2 und passt m.E. nicht mehr in die überarbeitete Benutzeroberfläche. Ich würde vorschlagen, ihm zu deaktivieren.

**Comment by EwaldReinhardt** [comment]
Ansprechpartner können ja über das "+" beim Schüler direkt ergänzt werden.
Daher kann ich damit leben, wenn die Schaltfläche "Adressdaten bearbeiten" verschwindet.
