### ISSUE TITLE
Feld "Ersetzte Sprache" wurde nicht gefunden

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1067]
Server: Release v0.9.0
Nach Klick auf die Laufbahninfo erscheint folgende Fehlermeldung:
![image](https://github.com/user-attachments/assets/db569a1c-e264-4ca6-9640-4127455472af)

[Sprachenfolge.txt](https://github.com/user-attachments/files/16329311/Sprachenfolge.txt)

**Comment by JuergenRichter** [comment]
Hier ist wohl mit der Version 0.9.0 des SVWS-Servers ein Feld weggefallen.
