### ISSUE TITLE
Schüler/Adressen_Betriebe - Hausnummer bei Anschrift ergänzen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1068]
Auf dem Tab Adressen/Betriebe wird die Hausnummer der Betriebeadresse nicht ausgegeben.
Bitte ergänzen.

![grafik](https://github.com/user-attachments/assets/8aef533f-8a78-4d2a-9dde-2f22aabbe78c)

**Comment by JuergenRichter** [comment]
Ist umgesetzt
