### ISSUE TITLE
Schüleraufruf aus Suche in falschem Reiter

### ISSUE THREAD

**Issue by KaBe47Du** [SVWS-NRW/Schild3-BetaTest#1069]
Über Strg+F kann der Suchen-Dialog "Schüler suchen" aufgerufen werden, dies gelingt sinnvollerweise aus allen Ribbons.
Wenn ich jedoch durch Doppelklick auf einen Schülernamen diesen Schüler aufrufen möchte, und ich befinde mich nicht im Reiter "Schüler", erscheint die Fehlermeldung:

> Deaktiviertes oder unsichtbares Fenster kann den Fokus nicht erhalten.

Hier müsste vermutlich zuunächst der Fokus auf das Schüler-Fenster gelegt werden, um dann den Schüler korrekt anzuzeigen.

**Comment by JuergenRichter** [comment]
Korrigiert, es wird jetzt vor dem Erscheinen des Such-Fensters in die Schüleransicht gewechselt, sofern diese nicht die aktuelle Ansicht ist.
