### ISSUE TITLE
Ungültiger Wert Haltestelle

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#107]
Beim Eintragen der Haltestelle kommt eine Fehlermeldung.
Wurde hie rnoch nicht auf ID umgestellt?

![SNAG_2021_03_16_14 14 23](https://user-images.githubusercontent.com/34127980/111314902-24f6c080-8662-11eb-9dcb-3e76db0d215d.png)
[Errorlog.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6149190/Errorlog.txt)

**Comment by JuergenRichter** [comment]
In 3.0.13.3 behoben
