### ISSUE TITLE
Import Lehrerdaten (StammschulNr nicht gefunden)

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1070]
1. beim Import "**Lehrkraefte.dat**" erscheint die Fehlermeldung "**Stammschulnr nicht gefunden**"
Die Lehrkraefte.dat wurde zuvor mit Schild3 erzeugt und nicht geändert.
2. Änderungen habe ich nur in der beim Export der Lehrerdaten erzeugten Datei "**Lehrersonderzeiten.dat**" vorgenommen. Ist es nicht möglich, **nur diese Datei zu importieren**??? Für die Statistik wäre das eine große Erleichterung. (Oder den Fehler aus 1. beheben, damit alle Lehrerdateien importiert werden können)

**Comment by JuergenRichter** [comment]
1. Behoben
