### ISSUE TITLE
Lehrkräfte->Zeitabh. Daten->Stammschule

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1071]
Der Eintrag einer Stammschule (andere Schule außer der eigenen) bleibt nicht erhalten:
![grafik](https://github.com/user-attachments/assets/7c7f99b0-e282-45f9-98ef-b45823a4b997)
In der Lehrkräfte.dat wird dann auch nur die eigene Schulnummer angezeigt. Bei allen anderen Lehrkräften erscheint keine Nummer.

**Comment by JuergenRichter** [comment]
Behoben
