### ISSUE TITLE
Email-Versand an DQ Kurse

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1073]
gem. dieser Anleitung ist es möglich, Formulare als pdf-Anhang per Email an bestimmte Gruppen - die Kurslehrer - zu senden:

https://wiki.svws.nrw.de/mediawiki/index.php?title=Mailversand_aus_der_Reporting#Versand_eines_Serienbriefs_als_PDF-Anhang

Ich halte es für Schild3 notwendig, dass die **Datenquelle "Kurse"** mit aufgenommen wird.
So können z.B. **Kurslisten an die Fachlehrer der jeweiligen Kurse** versendet werden. Bisher war dies aus kurs42 für die Oberstufe möglich, diese Möglichkeit ist dort aber nicht so einfach vorhanden (von einzelnen vorgefertigten Reports abgesehen).

**Comment by HHayen** [comment]
In die DQ Kurse sollte dann auch die "LehrerEmail" aufgenommen werden.

**Comment by JuergenRichter** [comment]
Werde ich berücksichtigen

**Comment by HHayen** [comment]
Ist das schon umgesetzt worden?

**Comment by JuergenRichter** [comment]
Noch nicht, mache ich aber kurzfristig

**Comment by HHayen** [comment]
Vielen Dank!!!

**Comment by JuergenRichter** [comment]
Ist umgesetzt, die DQ ist nun auch in die Liste der für Serien-Email nutzbaren Datenquellen aufgenommen worden. Voraussetzung ist, dass "Kurse" die Hauptdatenquelle eines Reportes ist, es eine Gruppierung auf die Kurs-ID gibt und dass bei den Gruppeneigenschaften die Option "Bei Gruppenwechsel neue Datei als E-Mail versenden" aktiviert ist.

![image](https://github.com/user-attachments/assets/9d818d2c-1079-46d5-950c-91b9f1811316)

**Comment by NielsWL** [comment]
Hallo Hauke,

hast du schon bzw. hast du dann demnächst ein Formular (z.B. Kursliste) fertig für den EMail-Versand, was du dann zur Verfügung stellen könntest? Oder wird das evt sogar in die Basic-Sammlung integriert?

**Comment by JuergenRichter** [comment]
Einen speziellen Report braucht man eigentlich nicht. Ich habe zum Testen einfach die Datei "Kursliste Klassen Namen.rtm" genommen und die oben gezeigte Änderung gemacht.
