### ISSUE TITLE
Datenquellen für Reporting GOST

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1074]
Werden die Tabellen gost_xxx noch als Datenquellen für die Reporting aufbereitet? Es wird ja notwendig sein, auch Formulare für die Oberstufe zu erstellen.
Unabhängig von den "Basic-Formularen", die im svws-Client zur Verfügung gestellt werden.

**Comment by AnneSchueller** [comment]
Ich glaube die sind nur für den SVWS-Server und werden nicht in die Reporting implementiert.
@FPfotenhauer : korrekt?

**Comment by JuergenRichter** [comment]
SchILD hat derzeit keinen Zugriff auf die genannten Tabellen

**Comment by HHayen** [comment]
Aber sie werden doch angezeigt?
![grafik](https://github.com/user-attachments/assets/0534eabf-b1c2-4451-b220-358b0e2093f5)

**Comment by JuergenRichter** [comment]
Die Definitionen dieser DQs werden über den SVWS-Server an die Reporting "geliefert", SchILD hat aber (im Programm) derzeit keinen Zugriff auf die dahinter liegenden Tabellen.

**Comment by HHayen** [comment]
Verstanden. Dann müssen für den Oberstufenbereich andere "Formularlösungen" her. Wichtig wäre #1073 , damit wir z.B. bei Kurslisten nicht in die Steinzeit (Papierlisten in Lehrerfächer verteilen) zurückfallen :-)

**Comment by JuergenRichter** [comment]
Da habe ich mich etwas missverständlich ausgedrückt:
Die Definitionen und Daten **können im Prinzip** über den SVWS-Server an die Reporting "geliefert" werden, die entsprechenden Strukturen sind vorhanden. Dann könnten Reports "ganz normal entworfen" werden. Inwieweit das geplant ist, weiß ich aber nicht.

**Comment by M-Plu** [comment]
Da diese Erweiterung aktuell ruht, schließe ich das Issue hier.
