### ISSUE TITLE
Laufbahninfo-Feld "ErsetzeSprache" nicht gefunden

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1075]
Schild 3.0.89.15, svws 0.9.0:
![grafik](https://github.com/user-attachments/assets/7b7a3fe4-25f6-4fdc-bd35-ed1993df6e04)
Bei Schülerwechsel im Reiter Laufbahninfo erscheint diese Fehlermeldung in allen Jahrgangsstufen.

**Comment by AnneSchueller** [comment]
Ist mittlerweile behoben.
