### ISSUE TITLE
Noten aus der Datenquelle BKAbschlussFaecher fehlen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1076]
Bei den Zeugnissen am BK fehlen die Noten aus dem Reiter BKAbschluss:

![image](https://github.com/user-attachments/assets/bf7ec098-c4f6-4dba-bdee-b29a45422dc5)

Diese waren in SchILD2 in der Datenquelle BKAbschlussFaecher_DIFF, BKAbschlussFaecher_BUE und BKAbschlussFaecher_BB:

![image](https://github.com/user-attachments/assets/7de5f06f-0d7f-46b5-8217-2d8d3127896e)

Die Noten werden nicht ausgegeben. 

Hier: Gliederung C06; JG FOS; Zeugnis ASZ (Anlage10)

**Comment by JuergenRichter** [comment]
Werden denn nur die Noten nicht ausgegeben oder erscheinen auch die Fachbezeichnungen nicht?

**Comment by JuergenRichter** [comment]
Behoben
