### ISSUE TITLE
Gliederungsbezogene Einstellungen der Fächer werden bei der Migration nur teilweise übernommen

### ISSUE THREAD

**Issue by JTorspecken** [SVWS-NRW/Schild3-BetaTest#1077]
Bei der Migration einer BK-Datenbank wurde nur die erste gliederungsbezogene Einstellung der Fächer übernommen.
![grafik](https://github.com/user-attachments/assets/d2c1bab5-df37-4ddf-a993-ffd34f69a7b6)

Die Fachgruppe und die Fachklasse werden nicht korrekt dargestellt.

Im SVWS-Server gibt es die gliederungsbezogenen Einstellungen bisher gar nicht.

**Comment by AnneSchueller** [comment]
Hallo Jochen, Danke fürs Testen :-)

Das kann ich reproduzieren. Die Einstellungen fehlen auch bereits in der MariaDB:
![image](https://github.com/user-attachments/assets/6aff06e3-be0b-43b6-9755-b8849253d1ee)

**Comment by AnneSchueller** [comment]
Funktioniert ab der nächsten Version
