### ISSUE TITLE
Ungewünschter Ansichtenwechsel in "Akt. HJ"

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1078]
Ist im Reiter "Akt. HJ",, "allg. Angaben" ein anderes als das aktuelle HJ gewählt wie hier:
![grafik](https://github.com/user-attachments/assets/d3247cd5-b5c4-4e30-84d3-94232c71358f)
so springt beim Wechsel zu "Leistungsdaten" die Anzeige wieder in den aktuellen Abschnitt. Ich finde das störend, es kann auch zu Fehleinträgen führen.
![grafik](https://github.com/user-attachments/assets/fcef3c48-723d-4b96-a05b-8a89f3341a12)

**Comment by AnneSchueller** [comment]
Dem würde ich mich anschließen. In Schild2 blieb der aktuelle Abschnitt gleich beim Switch innerhalb des Reiters "akt. HJ"

**Comment by JuergenRichter** [comment]
Ist umgesetzt
