### ISSUE TITLE
Unvollständige Änderung der Daten bei Nachprüfungen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1079]
Ein Schüler hat durch NP die Versetzung erhalten. Die automatische Änderung der Eintragungen ist unvollständig:

Zunächst wird keine Änderung im 1. Abschnitt angezeigt:
![grafik](https://github.com/user-attachments/assets/03c87f31-9d65-468e-9e4e-b61c41749170)
diese folgt erst nach Wechsel des Datensatzes (nicht schlimm, das ist unproblematisch).

Jedoch bleibt der Schüler in seiner  ursprünglichen Klasse und wechselt nicht von 10 in EF.
Der Haken "2. Durchgang" wird auch nicht entfernt.
Mögliche Ursache: Bei niemandem ist die Folgeklasse eingetragen. Diese ist in der Klassen und Versetzungstabelle aber hinterlegt. Ist diese beim Import/Migration nicht mitgekommen?
Edit: Ein Eintrag bei "Folgeklasse" ändert aber auch nichts am Verhalten.

**Comment by AnneSchueller** [comment]
Das kann ich mit meiner SpielDB für JG 08 bestätigen.
Folgeklassen und Folgejahrgänge sind korrekt eingetragen. Nach Eintrag der Nachpfüfung bleibe der Schüler in JG 08 (automatische Prozesse 
Mit der analogen DB in Schild2 funktioniert es nach Eintrag der Nachprüfung.

**Comment by JuergenRichter** [comment]
Ich würde diesen Punkt erst mal so lange zurücksetzen, bis die Interpretation der Folgeklasse geklärt ist (genauer gesagt, ob die Folgeklasse_ID aus der Klassenliste des aktuellen oder des nächsten Schuljahresabschnittes zu entnehmen ist).

**Comment by JuergenRichter** [comment]
Siehe #1081

**Comment by AnneSchueller** [comment]
Funktioniert nun
