### ISSUE TITLE
Abituralgorithmus

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#108]
Der Abi-Algorithmus meldet Fehler bei Schülern, die komplett zugelassen sind.
Datenbank GymAbi.mdb JG Q2.

![SNAG_2021_03_16_14 23 23](https://user-images.githubusercontent.com/34127980/111316141-4ad09500-8663-11eb-9041-c8a0ea295815.png)

**Comment by JuergenRichter** [comment]
In 3.0.13.3 behoben
