### ISSUE TITLE
Folgeklasse fehlt nach Migration

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1080]
Die Folgeklasse wird im akt. HJ nicht eingetragen:

![image](https://github.com/user-attachments/assets/e2f5904f-e380-4eda-a856-7ee5dba0dad7)

**Comment by JuergenRichter** [comment]
Die Folgeklasse wird ja als "Folgeklasse_ID" in der Tabelle "SchuelerLernabschnittsdaten" verwaltet. Ist in diesem Feld denn bei den aktuellen Lernabschnittsdaten überhaupt was eingetragen?

**Comment by JuergenRichter** [comment]
Hier gibt es möglicherweise einen "Interpretationsunterschied" zwischen dem SVWS-Server und SchILD3.

Interpretation der Folgeklasse (bzw. SchuelerLernabschnittsdaten.Folgeklasse_ID) im SVWS-Server:
Der SVWS-Server (bzw. die Migration) interpretiert die Folgeklasse offensichtlich so, dass sich die Folgeklasse (mit der zugehörigen IFD) auch im folgenden "Schuljahresabschnitt" befinden muss. 
Beispiel aus meiner Test-DB: 
Feldinhalt von "Schuljahresabschnitts_ID" in "SchuelerLernabschnittsdaten" ist 4 (was 2021 1. Hj. entspricht). Das Feld Folgeklasse_ID" hat dort den Wert 109, was aber auf eine Klasse mit "Schuljahresabschnitts_ID=2" verweist (was 2021 2. Hj.) entspricht.
Diese Interpretation sucht die Folgeklasse also im folgenden Schuljahresabschnitt. Das setzt aber voraus, dass es den folgenden Schuljahresabschnitt auch schon gibt. Das ist bei vergangenen Schuljahresabschnitten der Fall, bei zukünfigen aber nicht unbedingt.

In SchILD3 bezieht sich das Feld Folgeklasse_ID aber derzeit auf eine Klasse im gleichen Schuljahresabschnitt wie der Datensatz in "SchuelerLernabschnittsdaten". Daher kann in SchILD3 auch schon eine Folgeklasse eingetragen werden, wenn der folgende Schuljahresabschnitt noch gar nicht existiert. Bei einem Abschnittswechsel werden die Klasseneinträge für den neuen Schuljahresabschnitt angelegt (wenn noch nicht geschehen), anhand der Folgeklassen_ID (im derzeitigen Schuljahresabschnitt) und der Klassenbezeichnung wird dann die neue Klassen-ID (im neuen Schuljahresabschnitt) ermittelt.

Hier sollte nochmal diskutiert werden, welche Interpretation verwendet werden soll. Wenn die "SVWS-Server-Interpretation" gelten soll, müssen in SchILD3 noch einige Anpassungen gemacht werden.

**Comment by AnneSchueller** [comment]
Ich nehme das Thema mit in die nächste Besprechung mit Herrn Raffenberg und Herrn Pfotenhauer.

**Comment by JuergenRichter** [comment]
Das können wir gerne so machen, es ging mir nur um die Interpretation der Folgeklasse_ID (in der Tabelle "SchuelerLernabschnittsdaten"), bzw. welchem Schuljahresabschnitt diese zugeordnet sein soll. Ich verstehe das nun so, das diese sich auf die Klassen im Folge-Schuljahresabschnitt beziehen soll. Ich würde das in SchILD entsprechend anpassen, damit hier keine "Interpretationsdifferenzen" zwischen SchILD3 und z.B. dem Web-Client entstehen.

**Comment by JuergenRichter** [comment]
Ich habe die "Folgeklasse-Interpretation" nun so angepasst, dass bei der Auswahl derselben die Klassen des nächstfolgenden Schuljahresabschnittes zur Verfügung stehen. Wenn da noch keine Einträge vorhanden  sind, werden die auf Basis der vorhandenen angelegt.

**Comment by JuergenRichter** [comment]
Wenn keine individuelle Folgeklasse eingetragen ist, wird nun die "Standard-Folgeklasse" der aktuellen Klassen angezeigt. Das erfolgt mit kursiver Schriftart, daran kann man sehen, dass es keine individuelle Folgeklasse ist:

![image](https://github.com/user-attachments/assets/400c3c1a-c438-4aa8-8b0f-92411c0621f3)
