### ISSUE TITLE
Import von Notendateien

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1082]
Der Import der Notendateien, die mit dem NM3 bearbeitet werden, fehlt unter Verwaltung/Import.

Die Entwicklung vom NM3-Modul ist nun so weit fortgeschritten, dass der Import auch getestet werden kann.

**Comment by JuergenRichter** [comment]
Eine Frage dazu noch zum Export:

Es gibt ja derzeit verschiedene Optionen, die aber derzeit keine Auswirkungen haben:
![image](https://github.com/user-attachments/assets/c041ce6c-1602-488e-8774-979c4e13f407)

Welche davon wird es auch in Zukunft geben?

**Comment by JuergenRichter** [comment]
Ist jetzt umgesetzt, werde heute ein Update bereitstellen. Bitte damit mal testen.

**Comment by FPfotenhauer** [comment]
Komplette Klassenlehrerdatei und Fachlehrer-Fächer gibt es nicht mehr.

Wie wäre es, wenn Sie für die anderen Einstellungen ein eigenes Json erstellen mit eine Abteilung "Konfiguration".
In dieses Json kann dann das LehrerJson von uns eingebettet werden.
Dann wären Sie, was das angeht, unabhängig vom SVWS-Server und wir müssten unser Json-Format nicht ändern, weil wir diese Werte in unseren Programmen nicht benötigen?

Über die Verwendung des Passwort-Hashes würde ich gerne einmal sprechen.
Dort müssen wir uns nur einig sein, was wir nun verwenden wollen und wie der Ablauf ist.
Aus unserer Sicht gerne das Verfahren so ähnlich nutzen, wie das Initialkennwort des GS-Moduls.

**Comment by JuergenRichter** [comment]
Siehe auch #1086
