### ISSUE TITLE
Auswahl-Filter Fehler

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1083]
In dieser Einstellung:
![image](https://github.com/user-attachments/assets/ad4f88e3-bbf5-4c6a-b43a-6b0b9a72bd1d)

folgt diese Fehlermeldung:
![image](https://github.com/user-attachments/assets/5268a89a-1cf5-435b-83bb-53fda9b0b81f)

**Comment by AnneSchueller** [comment]
[Log_filter.txt](https://github.com/user-attachments/files/16638178/Log_filter.txt)

**Comment by JuergenRichter** [comment]
Behoben
