### ISSUE TITLE
Wiedervorlage für Lehrkräfte

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#1084]
In SchILD2 ist die Wiedervorlage ja sowohl für SuS als auch für Lehrkräfte nutzbar. In SchILD3 ist das derzeit nur für die SuS umgesetzt. Grund ist, dass die Tabelle "SchuelerWiedervorlage" heißt, die Wiedervorlagen für die Lehrkräfte wurde in SchILD2 nachträglich eingerichtet, wird aber auch in diese Tabelle gespeichert, was aber unschön ist. Ich kann mich erinnern, dass es mal im Raume stand, für SchILD3 eine eigene "Lehrer-Wiedervorlage" zu schaffen. Ist das noch angedacht?

**Comment by FPfotenhauer** [comment]
Ich kann mich daran zwar nicht erinnern.
Wie ist das denn momenatn in Schild2 für die Lehrer umgesetzt?
Wenn wir so eine Tabelle "LehrerWiedervorlage" erstellen, dann müssten ja auch die Einträge migriert werden...

**Comment by JuergenRichter** [comment]
In SchILD2 wurde die Wiedervorlage zuerst nur für die SuS eingeführt. Daher heißt die Tabelle auch "SchuelerWiedervorlage", darin gibt es das Feld Schueler_ID. Schnell kam da aber auch der Wunsch aus den Sekretariaten auf, die Wiedervorlage auch für Lehrkräfte nutzen zu können (einer unserer Dozententen hat mir dazu berichtet, dass das laut Aussagen mehrerer Sekretärinnen "für Lehrer viel wichtiger sei als für Schüler"). Daher wurde die Wiedervorlage "aufgebohrt" und ein Feld "Typ" eingeführt. Je nachdem, ob dieses Feld den Wert "S" oder "L" hat, bezieht sich "Schueler_ID" auf einen Datensatz aus Tabelle "Schueler" oder "K_Lehrer".
Ich kann mich erinnern, dass Herr Bachran erwähnt hat, das dieses Konstrukt aber die Formulierung eines ForeignKey-Constraints (der SchILD3 benötigt wird) verhindert und daher eine separate Lehrer-Wiedervorlage notwendig sei. Ich wollte daher dieses Thema nochmal zur Diskussion stellen, auch weil einige unserer Dozenten danach gefragt haben (die die Bedürfnisse der Klienten recht gut kennen). Ob aber Lehrer-Wiedervorlagedaten unbedingt migriert werden müssen, sei mal dahingestellt.

**Comment by JuergenRichter** [comment]
Man könnte die Tabelle natürlich auch in "Wiedervorlage" ändern und ein Feld Lehrer_ID einfügen. Dann wäre sowohl ein ForeignKey auf "Schueler" (Feld Schueler_ID gefüllt, Lehrer_ID leer) als auch auf K_Lehrer (Feld Lehrer_ID gefüllt, Schueler_ID leer) möglich. Ähnlich wird das ja auch in der Tabelle "Benutzer" gemacht (Felder Allgemein_ID, Lehrer_ID, Schueler_ID, Erzieher_ID).

**Comment by ThomasBachran** [comment]
@JuergenRichter : Wir überarbeiten die Tabelle und benennen sie auch um. Dabei werden wir die Möglichkeiten auch auf Erzieher-IDs ausweiten. Der Zugriff soll dann aber nicht mehr direkt über die DB erfolgen, sondern über API-Methoden. Wir lassen Ihnen in den nächsten Tagen einen Snapshot-Installer zukommen, so dass sie Schild 3 darauf anpassen können.

**Comment by FPfotenhauer** [comment]
Die Endpunkte stehen ab der SVWS-Server Version 0.9.2 zur Verfügung.
