### ISSUE TITLE
Fehler bei ENM-Export

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#1086]
Ich bekomme bei einer Datenbank (eine Test-Gesamtschuldatenbank von Frau Schüller) in SchILD3 beim ENM-Export bei allen Lehrkräften eine Fehlermeldung 500 (Server error) vom SVWS-Server. Der gleiche Fehler kommt auch, wenn ich den Export in der SwaggerUI anstoße. Bei anderen Datenbanken klappt es ohne Probleme, es muss also speziell was mit dieser Datenbank zu tun haben.
Soll ich einen SQlite-Export hier mal zur Verfügung stellen?

**Comment by AnneSchueller** [comment]
ich kann das mit der DB reproduzieren. Das Seltsame dabei:
Ich habe diese DB zweimal migriert. Bei der letzten Version vom 24.6.24 bekommen ich ebenfalls eine Fehlermeldung beim Export für enm.

**Comment by AnneSchueller** [comment]
Ich nehme mit Herrn Bachran Kontakt auf diesbezüglich.

**Comment by ThomasBachran** [comment]
Hierbei handelte es sich um einen Fehler im SVWS-Server. Im nächsten Pre-Release wird dieses Problem nicht mehr auftauchen.
