### ISSUE TITLE
Kataloge (z.B. Fächer): Im Katalog kann auf "nur sichtbare" gefiltert werden, es steht aber keine Option zur Verfügung, ein Fach "Sichtbar" oder "Unsichtbar" zu stellen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#1087]
Siehe Titel. 

Neben "Sichtbar" fehlt bei Fächern auch "Auf Zeugnis".

Bitte "Sichtbar" und "Unsichtbar" für alle relevanten Kataloge prüfen.
1. Besteht die Auswahl auf sichtbare/unsichtbare?
2. Besteht die Möglichkeit, einen Eintrag tatsächlich sichtbar/unsichtbar zu stellen.

**Comment by AnneSchueller** [comment]
Man kann die Checkboxen direkt im Fächerkatalog (de-)aktivieren.
