### ISSUE TITLE
Auswahl: Es kann nicht auf Lernplattformen gefiltert werden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#1088]
Es kann nur auf Einwilligungen gefiltert werden, nicht auf eventuelle Lernplattformen und deren Einwilligungen

**Comment by AnneSchueller** [comment]
Nach dieser Option wurde auch für SchILD2 gefragt. 
Es wäre sinnvoll, wenn das über den Schülerfilter funktionieren würde.

**Comment by FrodBRA** [comment]
Nicht "sinnvoll", sondern "absolut notwendig". ;)

Außer die Daten passiv mit einem Report auszugeben könnte man sonst ja nichts damit machen, z.B. prüfen, wer sich noch nicht zurückgemeldet hat.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
