### ISSUE TITLE
"DSGVO-Einwilligungen" sollte wie in SchILD2 nur "Einwilligungen" heißen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#1089]
Siehe Titel.
Das betrifft den Katalog wie auch den Filter in Auswahl.

Er dient für viel mehr als nur DSGVO-vorgesehenes zu erfassen.

**Comment by FPfotenhauer** [comment]
DAs haben wi rim WebClient auch so umgesetzt, weil es hier ja auch Einwilligungen geben kann, die nicht zu DSGVO gehören.

**Comment by FrodBRA** [comment]
Die hießen in einer früheren Version in SchILD3 auch schon mal "Einwilligungen"!

Hießen erst DSGVO-Einwilligungen, dann wurde das umbenannt (die Screenshots im Wiki zeigen hier "Einwilligungen"), dann heißt das nun wieder "DSGVO-Einwilligungen".

An dieser Stelle frage ich mich: Ist das Absicht - oder wurde irgendwann zwischendurch wieder aus Versehen eine alte Version eingespielt?

**Comment by JuergenRichter** [comment]
Die Anzeige "DSGVO-Einwilligungen" erscheint beim "Schüler-Filter" (vormals "Filter I"), im Hauptfenster sollte das schon geändert sein (da steht allerdings "Einwilligung", habe das auf "Einwilligungen" geändert). Ist nun auch beim Schülerfilter angepasst.
