### ISSUE TITLE
Alle zuletzt besuchten Schulen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#109]
Es werden keine Schulen angezeigt.
Wenn man eine übernehmen will, kommt diese Meldung...

![SNAG_2021_03_16_14 36 48](https://user-images.githubusercontent.com/34127980/111318273-2d9cc600-8665-11eb-8223-e71a75d24b3a.png)

**Comment by JuergenRichter** [comment]
In 3.0.13.2 behoben
