### ISSUE TITLE
Die Pipeline Informatik ist kaputt

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#1092]
Version 3.0.91.15
Unter der Pipeline Informatik werden im Reportexplorer überhaupt keine Felder angezeigt.
![grafik](https://github.com/user-attachments/assets/fb2b9cb3-ac37-45d7-97a4-21d84bf013c2)

Auch in der Ansicht "Informationen zu Datenquellen" gibt es nur die Eigenschaft AbiErgebnis.
![grafik](https://github.com/user-attachments/assets/73722b3c-002e-4da5-b1a7-f9b67977f385)

**Comment by AnneSchueller** [comment]
In Schild2 finde ich das Fach gar nicht bei den Pipelines. Läuft das mit unter Naturwissenschaften?

**Comment by JuergenRichter** [comment]
Es gab mal eine DQ "Informatik" auch in SchILD2, es hat sich aber nachträglich herausgestellt, dass diese doch nicht benötigt wird. Daher wurde sie wieder entfernt. In SchILD3 war das wohl noch nicht erfolgt, ist nun aber geschehen.
