### ISSUE TITLE
SVWS-Server erzeugt unterschiedliche Schreibweisen der Tabellennamen unter Windows/Linux

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#1094]
Wir sind gerade dabei, eine größere Testumgebung für SchILD3 einzurichten.

- Applikationsserver für SchILD3 unter Windows
- Datenbankserver unter Linux
- Derzeit 20 Schulen, für jede ein eigener Docker-Container (auf dem Linux-Server)

Ursprünglich lagen die MariaDB-Datenbanken auf einem Windows-Server. Über MariaDB-Backups wurden die Datenbanken dann auf dem Linux-Server übertragen. Beim Start von SchILD3 gab es dann aber Fehlermeldungen, weil die Schreibweise der Tabellen nicht passte. In den (auf dem Windows-Server) erzeugten Backups waren die Tabellennamen grundsätzlich klein geschrieben, unter Linux wird aber die genaue Groß-Kleinschreibung erwartet. Wir haben dann die Datenbanken auf dem Linux-Server nochmal neu aufgesetzt und aus MDBs migriert. Dabei wurden die Tabellen in Groß-/Kleinschreibung angelegt, SchILD3 ließ sich dann ohne Fehler starten.
Gibt es einen Grund, warum der SVWS-Server die Tabellennamen unter Windows mit Kleinschreibung anlegt?
Ich könnte mir vorstellen, dass das in Zukunft mal zu den gleichen Probleme führen wird, die wir festgestellt haben, wenn z.B. ein IT-Dienstleister die Datenbanken von einem Windows-Server über Backup-Dateien auf einen Linux-Server übertragen will.

**Comment by Tkyzxim** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by FPfotenhauer** [comment]
MariaDB legt unter Windows leider alles in Kleinschreibung an.

**Comment by JuergenRichter** [comment]
Hängt das nicht von "lower_case_table_names" ab?

https://mariadb.com/docs/server/ref/mdb/system-variables/lower_case_table_names/

**Comment by kroerig** [comment]
> On Unix, the default value of lower_case_table_names is 0. On Windows, the default value is 1. On macOS, the default value is 2.

Windows kennt im Dateisystem keine wirkliche Groß-/ Kleinschreibung. Das wird über MetaDaten in NTFS bzw. ReFS gelöst.
Das Thema hatten wir doch schon mal. https://github.com/SVWS-NRW/Schild3-BetaTest/issues/809

**Comment by FrodBRA** [comment]
Was ich hier mitnehme: Über Betriebssystemgrenzen hinweg ist UNBEDINGT die Migration über sqlite-Backups und nicht ein DB-Dump zu nutzen.

Korrekt?

**Comment by AnneSchueller** [comment]
So hat @FPfotenhauer das auch vorgeschlagen:
> Übertragungen können mit den SQLite-Backups gemacht werden.
Das ist ja immer eine neue Migration, da wird immer das richtig für das entsprechende System angelegt...

Ich schließe das Issue mal.
