### ISSUE TITLE
Sonderpädagogen beim Notenexport

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1099]
Aktuell werden Schüler nur für diejenigen LuL in eine Notendatei exportiert, die auch ein Fach bei den Schülern unterrichten.

Dabei werden die eingetragenen Sonderpädagogen nicht berücksichtigt. 
Ist es Voraussetzung, dass diese auch ein Fach bei den Schülern unterrichten, die sie sonderpädagogisch betreuen?

**Comment by kroerig** [comment]
vergeben die denn Noten? Wie ist das aktuell in SchILD2?

**Comment by AnneSchueller** [comment]
Die Sonderpädagogen vergeben schonmal Textfloskeln oder schreiben teilweise Fördermaßnahmen. 
Ob das immer über ein Facheintrag in Schild läuft, wäre die Frage.
