### ISSUE TITLE
Fächergruppen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#110]
Das ist ein Issue, über das man etwas diskutieren kann.

Woher nimmt Schild3 die Fächergruppen aus den Unterrichtsfächern?
Es gibt eine Tabelle in der Schildintern_Fachgruppen.
Dort kommen auch noch alte Fachgruppen vor Aufgabenbereiche I, II und III.1-3.

Wir haben in der Statkue eine neue Tabelle Statkue_SVWS_Fachgruppen erstellt.
Dort sind die Altlasten raus. Außerdem sind die IDs der FAchgruppen identtisch mit denen von Lupo.

Soll man ggf. darauf umstellen?

**Comment by ThomasBachran** [comment]
Ich persönlich bin immer für eine Umstellung auf die neuen Tabellen. Wie groß ist denn der Aufwand in Schild3 dafür? In der Tabelle sind auch Standard-Werte für die Farben der Fachgruppen enthalten. Diese könnte man dann auch als Default verwenden...

**Comment by JuergenRichter** [comment]
Ja, das sollten wir umstellen

**Comment by FrodBRA** [comment]
Wurde nach dem erreichten Konsens die Umstellung vorgenommen?
