### ISSUE TITLE
Klickreduzierung beim Generieren von Statistikdateien 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#1102]
Beim Export der Statistikdateiten lehrer.txt, Sim.txt usw. sollte mit so wenig Klicks wie möglich gearbeitet werden, d.h. nur eine Ordnerwahl für alle angewählten Dateitypen etc.

**Comment by AnneSchueller** [comment]
Dem möchte ich zustimmen. Aktuell wird man 4 mal nach dem Speicherort gefragt.

**Comment by JuergenRichter** [comment]
Das kommt aus der ASDStatistik.dll, da haben wir keinen Einfluss drauf.
