### ISSUE TITLE
Zwei-Faktor-Authentisierung

### ISSUE THREAD

**Issue by paulprima78** [SVWS-NRW/Schild3-BetaTest#1103]
Besteht die Möglichkeit eine Zwei-Faktor-Authentisierung für die Anmeldung am SVWS-Server zu implementieren um eine höhere Sicherheit zu erreichen?

**Comment by FPfotenhauer** [comment]
Die Möglichkeit word definitiv kommen. Wird aber zu einem späteren Zeitpunkt umgesetzt.
Momenatn laufen die SVWS-Server ja noch immer in abgetrennten Verwaltungsnetzen, so dass hier eine zusätzliche Sicherheit gegeben ist.

**Comment by paulprima78** [comment]
Vielen Dank für die schnelle Rückmeldung, für die dezentrale Noteneingabe der KuK ist aber ein Zugriff auch von außerhalb der Verwaltungsnetze erforderlich, dafür ist die Zwei-Faktor-Authentisierung erforderlich.

**Comment by kroerig** [comment]
Für die Noteneingabe gibt es ein gesondertes Programm. Dafür ist kein SVWS Zugriff erforderlich.

**Comment by T-Hagel-SK** [comment]
> Für die Noteneingabe gibt es ein gesondertes Programm. Dafür ist kein SVWS Zugriff erforderlich.

Wann wird es für dieses Programm denn endlich mal etwas zu lesen geben, wie es funktionieren soll ?
Im IT-NRW-Forum komm ich mit der Frage auch nicht weiter, im Wiki zu WeNoM steht dazu noch nichts. 

Ich würde gerne wissen, ob es eine Alternative zu SchildWeb ist, ob man beide Varianten nutzen kann oder nur eine. Sowie wie das Programm oder der Server aufzusetzen sind ??

Wenn es für das Programm keinen SVWS-Zugriff benötigt, wie kommen dann die Daten in die Datenbank ?
