### ISSUE TITLE
SVWS Installation unter Ubuntu/Linux

### ISSUE THREAD

**Issue by CDittich** [SVWS-NRW/Schild3-BetaTest#1104]
Das Installationsscript verläuft problemlos und auch die Einstellungen sind gut machbar.
Auf Ubuntu Server 22 läuft im Anschluss die MariaDB und der SVWS.service.

Aber ich kann nicht von extern auf die Weboberfläche zugreifen.
https://meinelocation ist nicht errreichbar.

MariaDB ist aber von extern erreichbar. Dieses habe ich getestet. Leider habe ich nur sehr beschränkte Kenntnisse mit Linux, daher habe ich nicht herausfinden können, mit welchem Webserver gearbeitet wird und wo eventuell noch Beschränkungen liegen.

Selbst unter Ubuntu mit Oberfläche kann ich mich nicht einwählen, da die Webseite nicht erreicht werden kann.

Habe ich irgendwo etwas übersehen?

Beste Grüße
Carsten

**Comment by AnneSchueller** [comment]
Ist denn der Rechner, mit dem auf die Weboberfläche zugegriffen werden soll, im gleichen Netzwerk?
Evtl. noch den Port ergänzen in der Adresse: https://meinelocation:8443

**Comment by CDittich** [comment]
Ja, das ist er.
Ich teste sowohl mit 2 Rechnern im gleichen netzt als auch mit einer Virtualisierungssoftware.
Den Port habe ich ergänzt aber das hilft auch nichts.

Meine Gedanken gingen in die Richtung, dass der lokale Webserver nicht von außen erreichbar ist (ähnlich wie bei der MAriaDB, welche noch extra in einer conf-Datei den externen Zugriff freigeben musste). Die IP kann ich anpingen, aber mehr geht auch nicht.
________________________________

**Comment by hmt** [comment]
@familie-klein idee?

**Comment by kroerig** [comment]
was gibt ein `netstat -tpln `zurück? 
Da sollte ein Java-Prozess auftauchen.

Oder auch mal mit `ps fax | grep svws` schauen, ob da überhaupt ein Prozess läuft.

Eleganter ist es aber den SVWS als Docker Container zu betreiben, da muss man sich dann nicht mit Abhängigkeiten rumschlagen.

**Comment by CDittich** [comment]
Werde das später mal prüfen und dann schau ich mir mal den Docker Container an.
