### ISSUE TITLE
Zugriff auf SVWS-Server (Windows)

### ISSUE THREAD

**Issue by CDittich** [SVWS-NRW/Schild3-BetaTest#1105]
Bei allen Testinstallationen auf vernetzten Rechnern im gleichen Netzwerk bekomme ich immer folgende Meldung, sobald ich von einem Netzwerkrechner auf den SVWS-Server zugreifen möchte (lokal funktioniert der Zugriff)

![svws_login_problem2](https://github.com/user-attachments/assets/1590795a-8fad-4907-8665-e43fb0769142)

Hat jemand spontan eine Idee, wo ich im Netzwerk ein Häkchen vergessen habe? Die Netzwerkfreigabe ist aktiviert.

Grüße
Carsten

**Comment by CDittich** [comment]
Bitte vergesst diese Anfrage (löschen). Dies geht auf meine eigene Inkompetenz zurück und vielleicht den seit Stunden nervenaufreibenden Krieg mit Ubuntu und dem SVWS-Server.

Die DB war nicht komplett ordentlich geladen und die USER waren nicht korrekt. Jetzt läuft alles.

**Comment by hmt** [comment]
So ganz richtig ist das hier trotzdem nicht. Die Schemata wurden angezeigt, also gab es eine Verbindung zum Server. Soweit so gut. Warum kommt aber die Passwortanfrage als Browseralert? Hatte der Server eine Basic Auth dazwischen?

**Comment by kroerig** [comment]
Da müsste man mal über die Dev-Tools schauen, welcher Endpunkt hier angesprochen wird und die Basic Auth auslöst.

**Comment by CDittich** [comment]
Habe nochmal nachgeschaut. Kurz gesat liegt es daran, dass auf dem SVWS-Server der Login CaseSensitiv ist und das in Schild2 noch nicht so war. Dort war man immer schnell dabei die Logindaten einzutippen und alles in Kleinbuchstaben. In der DB sind die Zugangsdaten aber nicht nur in Kleinbuchstaben.
Schild2 hat das nicht interessiert.
Somit wurde der Benutzer nicht gefunden und es kam zu der besagten Fehlermeldung/Abfrage.

Jetzt bin ich schlauer. So ein kleiner Fehler hat mich wirklich sehr viel Zeit gekostet. Aber danke für den schnellen Support. Ich werde jetzt mal in die Mysterien von Schild3 eintauchen.

Carsten

**Comment by kroerig** [comment]
Ok. In die Falle bin ich hier noch nicht getappt, weil hier alle Benutzer mit Kleinbuchstaben angelegt sind.

Aber das ist defenitiv ein Fall für die Entwickler. Vielleicht sollte man bei der Migration einfach alle Benutzernamen in die Kleinschreibung umwandeln. Und dann auch egal, wie der Benutzername später bei neuen Benutzer im Feld eingetragen wird, immer in Kleinschreibung in der DB eintragen.

 Es wird vermutlich kein Benutzer auf die Idee kommen, dass er sich jetzt mit `Mueller` statt vorher `mueller` anmelden muss.

**Comment by AnneSchueller** [comment]
Das sollte man auf jeden Fall mal im Hinterkopf behalten als mögliche Fehlerquelle bei der Anmeldung. Bisher ist mir die Problematik tatsächlich noch nicht aufgefallen. 

Es gibt aber sicherlich auch Benutzer, die vorher immer ihren Anmeldenamen groß geschrieben haben und wahrscheinlich auch nicht wussten, dass man den auch bei der Anmeldung klein schreiben kann. Daher wäre eine Migration auf Kleinbuchstaben m.E. nicht optimal.

**Comment by kroerig** [comment]
Dann vllt. beides. Beim Migrieren anpassen und zusätzlich in der Programmlogik vor dem Absenden auch umwandeln.
Dann kann man es schreiben wie man will.

Wobei: Ich habe es gerade mal mit der 0.9.2 ausprobiert. Bei mir mit Firefox ist es egal, ob ich meinen Benutzernamen groß, klein oder gemischt schreibe.
