### ISSUE TITLE
Einträge löschen per Gruppenprozess

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1106]
Könnte man einen Gruppenprozess implementieren, der das Entlassdatum bei Schülern löscht?
Dies ist insbesondere für BKs relevant, wenn man Schüler als Duplikate führt und diese miteinander verschmelzt. 

Auch bei anderen Felder kommen schonmal Nachfragen, ob per GP Daten gelöscht werden können. Beispielsweise bei den Einträgen nach der Versetzungsberechnung.

Um die Auswahl Individualdaten ändern bei den GP nicht noch komplexer zu gestalten, wäre es evtl eine Möglichkeit, das hier zu implementieren?
Dann anstatt Vermerke löschen den Unterreiter "Daten löschen" zu bezeichnen und dort das Entlassdatum, sowie die Abschlussdaten vom aktuellen HJ zum Löschen anbieten. 
@Raffenberg , @FrodBRA Wie sind die Meinungen hierzu?

![image](https://github.com/user-attachments/assets/f5bdea6d-7265-4631-9d7f-3b45aa1fa305)

**Comment by Raffenberg** [comment]
Löschprozesse in den Gruppenprozessen werden vielfach gewünscht. Hier ein Vorschlag:

Ich fände es deshalb nicht schlecht, wenn wir Schrittweise eine solche Löschfunktion einführen:

Zunächst Löschen von Datumsangaben durch Eingabe von 00.00.0000. Löschen von Texteingaben durch -1, löschen von Auswahlfeldern durch hinzufügen einer Auswahl 'Einträge löschen'

Diese Möglichkeiten könnten nach und nach in Schild Einzug halten. Wir könnten mit den angesprochenen Feldern anfangen.

**Comment by AnneSchueller** [comment]
Aktuell steht in den Datumsangaben/Texteingaben, die leer sind, kein Eintrag. Gäbe es hier bei anderen Abfrageroutinen keine Probleme, wenn dort dann 00.00.000/-1 steht?

**Comment by JuergenRichter** [comment]
Man könnte das auch so ähnlich machen wie bei dem "Filter auf fehlende Einträge", d.h. es steht eine Anzahl von Feldern zur Verfügung, die geleert werden können (welche das sein sollen, müsste man festlegen). Aus dieser Liste wählt man dann das zu leerende Feld aus. Das wäre m.E. intuitiver als irgendwelche Spezialeinträge zu machen.

**Comment by AnneSchueller** [comment]
Gemeint ist ein neuer Unterreiter "Löschen von Einträgen" oder sollte die Löschmöglichkeit in die Reiter "Allgemein", "Fächer", usw. integriert werden?
An einigen Stellen gibt es ja schon die Möglichkeit,etwas zu löschen. Beispielsweise Vermerke, Fotos...
Das sollte m.E. einheitlich realisiert werden.

**Comment by JuergenRichter** [comment]
Man muss hier aber unterscheiden zwischen "Löschen" und "Leeren":
Löschen bedeutet (aus Sicht der Datenbank), dass ein Datensatz entfernt wird (z.B. ein Vermerk oder ein Foto)
Leeren bedeutet, dass ein Feldinhalt "gelöscht" (=geleert) wird (also z.B. das Entlassdatum)

**Comment by kroerig** [comment]
> Leeren bedeutet, dass ein Feldinhalt "gelöscht" (=geleert) wird (also z.B. das Entlassdatum)

Dann aber bitte nicht einfach nur den Wert löschen, sondern auf `NULL` setzen. Dann weiß man auch, dass es absichtlicht leer ist und nicht nur einfach der Inhalt entfernt wurde.

**Comment by JuergenRichter** [comment]
> Dann aber bitte nicht einfach nur den Wert löschen, sondern auf `NULL` setzen. 

Das meinte ich auch.

**Comment by Raffenberg** [comment]
Bitte lassen Sie uns das Thema erst einmal schieben. da wir es zunächst in einer größeren Runde diskutieren wollen.
