### ISSUE TITLE
Auswahl der Noten ZP 10 (Tendenzen gibt es nicht) 

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1107]
Die Eingabe der ZP10 Noten lässt Tendenzen zu. Die sind allerdings laut Prüfungsordnungen nicht vorgesehen. Auch funktionieren meine ZP-10-Formulare nicht mit "Tendenzen". Obwohl Kolleginnen das vielleicht gerne möchten, zugelassen ist es nicht. Beim Eingeben der Noten nervt es nämlich, dass z.B. beim Tippen der Note 2 eine 2+ eingetragen wird:
![image](https://github.com/user-attachments/assets/b94d6232-2f99-4480-8eeb-b294e9055b3e)

Beim Schülerkarteireiter ZP10 fehlen auch die Tendenzen, was korrekt ist:
![image](https://github.com/user-attachments/assets/3e3a14e2-fd49-4d7e-86a9-477809a00e7a)

Der Berechnungsbogen von  der Ministeriumsseite:
![image](https://github.com/user-attachments/assets/1be9a5f1-4551-4a2b-850e-f82c86ec052c)

**Comment by AnneSchueller** [comment]
@JuergenRichter : Kann man das ändern?
Wenn Schulen mit Teilleistungen für die ZP10-Noten arbeiten, kann es natürlich sein, dass die Kollegen hier Tendenzen angeben. Das sollte man für Teilleistungen auch zulassen, da ggf auch Klausuren darüber erfasst werden. Die Tendenzen könnte man dann beim GP holen für ZP10 abgeschneiden.
Was meinst du dazu @FrodBRA : Wäre das rechtlich ok?
Ich würde sagen ja.

**Comment by Kluesenerm** [comment]
Genau das macht mich wahnsinnig. Bei uns geben die Kolleginnen über Schild-Web die Noten über Teilleistungen für die ZP10 ein. Trotz mehrere Mails und Hinweise in der Dienstbesprechung geben immer wieder Kolleginnen Tendenznoten ein. Das führt dazu, dass ich händisch in Schild die Noten anpassen muss.

**Comment by AnneSchueller** [comment]
Also sollte man beim Übertrag der Teilleistungen in das Feld der ZP Noten die Tendenzen automatisch rauslöschen. Da im ZP-10 Reite so oder so nur ganze Noten eingegeben werden können, macht das definitiv Sinn. 

Zusätzlich sollte man im GP für die ZP10 Noten ebenfalls nur ganze Noten eingeben können:
![image](https://github.com/user-attachments/assets/d38a704f-6544-40c0-a3a6-6d12e538ba2d)
