### ISSUE TITLE
Anzeige von Grundschuldaten am WBK-> Verwaltung -> Schule -> Allgemeine Angaben 

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1109]
Bei mir am WBK überlagern die Verbleiber der Grundschulen (die es am WBK nicht gibt) die Anzeige:
![image](https://github.com/user-attachments/assets/9f8991da-bb6f-4253-82ed-be6735be58e7)

**Comment by AnneSchueller** [comment]
Das ist an anderen Schulformen auch so. In den Screenshots im Wiki war das noch nicht.

**Comment by JuergenRichter** [comment]
Behoben
