### ISSUE TITLE
Export SchuelerleistungsDaten

### ISSUE THREAD

**Issue by CDittich** [SVWS-NRW/Schild3-BetaTest#1110]
Der Export der SchuelerLeistungsdaten beinhaltet nach aktuellem Eindruck 2 Fehler.
Das Anhängen des Klassenkürzels an den Namen durch setzen des Häkchens "Klasse als zusätzliches...." funktioniert nicht.
Die Checkbox "Nur aktuellen Abschnitt exportieren" exportiert dennoch sämtliche Daten.

Beste Grüße
Carsten

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren im Unter Verwaltung/Export/Schnittstelle-Schild-NRW

![image](https://github.com/user-attachments/assets/d2312602-1063-4d78-a368-39fbc080ac80)

**Comment by JuergenRichter** [comment]
Beide Fehler behoben

**Comment by CDittich** [comment]
Ich habe gerade nochmal ein Post in den schon geschlossenen Thread geschickt, da der Fehler nicht korrekt behoben wurde. Soll ich dann einen neuen Beitrag eröffnen oder ist das hier dann noch korrekt?

Verwaltung Export Lernplattform Logineo LMS (CSV) - Daten nicht komplett · Issue #1116 · SVWS-NRW/Schild3-BetaTest (github.com)<https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1116>
[https://opengraph.githubassets.com/72868d1ec20589a082b87d61832fc1c28be1300ae7b810e9febd58bf16f940c5/SVWS-NRW/Schild3-BetaTest/issues/1116]<https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1116>
Verwaltung Export Lernplattform Logineo LMS (CSV) - Daten nicht komplett · Issue #1116 · SVWS-NRW/Schild3-BetaTest<https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1116>
Die Ausgabe der Lehrerkräfte beinhaltet in der Spalte profile_field_Klasse lediglich einen Wert. Hier sollten sämtliche Kurse mit einem | getrennt angegeben werden (zumindest in der Version von Sch...
github.com


Mit besten Grüßen
Carsten Dittich
________________________________
