### ISSUE TITLE
Import von Schülerdaten / Lehrerdaten

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1111]
Hallo zusammen,
ich vermisse die Möglichkeit bei Schülern, Individualdaten frei per csv zu importieren. Wir erzeugen z.B. in IServ die E-Mail-Adressen und in WinBook die Leihausweisdaten. Diese möchte ich dann gerne über die interne ID der Schüler wieder einlesen. Im alten Schild ging das dann über Vorname / Nachname und Klasse, was schon blöd war, da die ID mit Klasse eindeutiger gewesen wäre, ging aber immerhin.

Und für die Lehrer möchte ich auch gerne die Anrechnungen importieren können, am besten direkt aus der Ausgabe von Untis, aber das ist dabei eher schwierig, da es kein guter Export ist. Allerdings eine CSV, die ich dann selbst erzeuge, wäre gut einzulesen. Ebenso hier auch die Dienst-E-Mail-Adressen und etwaige Korrekturen.

Also insgesamt ein gutes CSV-Importmodul für Lehrer und Schüler wäre hilfreich.
LG
Raphael

**Comment by Raphael-Kemna** [comment]
Ich habe vergessen zu erwähnen: Schild V3.0.91 , SVWS V0.9.2.

**Comment by Raphael-Kemna** [comment]
Okay, wird es denn etwas vergleichbares geben, evtl. sogar besser über einen Import bezogen auf die ID (UID)?

 

Von: AnneSchueller ***@***.***> 
Gesendet: Montag, 30. September 2024 14:35
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Raphael-Kemna ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Import von Schülerdaten / Lehrerdaten (Issue #1111)

 

Ist diese Option gemeint?
image.png (view on web) <https://github.com/user-attachments/assets/e2490016-1938-40ee-85af-07b44e1c5558> 

Das läuft in SchILD2 über ein Externes Programm und ist in Schild3 nicht mehr anwendbar.
@JuergenRichter <https://github.com/JuergenRichter>  Oder habe ich das falsch im Kopf?

**Comment by Raphael-Kemna** [comment]
Ich habe gesehen, dass man die von mir gewünschten Aktualisierungen alle über die Schild-NRW-Schnittstelle realisieren kann.

**Comment by Raphael-Kemna** [comment]
Nun habe ich aber ein weiteres, wirklich wichtiges Problem.
Es scheint der Export der Zeugnisdaten nicht zu funktionieren.
Ich habe einmal alle Felder angewählt und es wird zum aktuellen schuljahr nichts exportiert außer den Individualdaten.
Zudem habe ich folgenden Fehler, wenn ich ein vergangenes Schuljahr auswähle:
![grafik](https://github.com/user-attachments/assets/1508e943-5c34-4688-8dd9-2847df428d34)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Hier der entsprechende Fehlerlog:

[zeugnisdatenExport.txt](https://github.com/user-attachments/files/17617331/zeugnisdatenExport.txt)

**Comment by JuergenRichter** [comment]
Behoben
