### ISSUE TITLE
SMTP-Einstellungen nach Migration

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#1112]
Bei der Migration werden die Einstellungen in den Eintrag schild2/Einstellungen in der Tabelle Client_Konfiguration_Global.
Schild3 legt sich dann die Einstellungen mit Schild3000 dort selbst an.

Die Maileinstellungen zum SMTP-Server werden aber bei der Migration in die Tabelle EigeneSchule_Mail migriert, weil diese Einstellungen auch vom SVWS-Server genutzt werden.

Schild3 sollte darauf umgestellt werden.

PS: Wir haben da auch noch einen Bug gefunden, dass der SMTP-Server in "" in der Datenbank ankommt. Dies wird aber behoben.

**Comment by kroerig** [comment]
Das hatte ich ja in https://github.com/SVWS-NRW/Schild3-BetaTest/issues/851 auch schon gemeldet. Und auch ein paar andere Einstellungen kommen nicht (mehr) an.

**Comment by kroerig** [comment]
Ich habe gerade die Datenbank in Version 3.1.0.28 frisch migriert und nachgeschaut. Die Einstellungen werden nicht übernommen.
![grafik](https://github.com/user-attachments/assets/3e15c25e-5f63-44e6-816d-cb7bd948cf2b)

**Comment by JuergenRichter** [comment]
Behoben
