### ISSUE TITLE
Export/Import der Kindergärten

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1113]
Aktuell werden die Kindergärten über die Schild-NRW-Schnittstelle weder exportiert noch importiert.
Könnte man das Feld in die SchulerZusatzdaten mit aufnehmen?

**Comment by FPfotenhauer** [comment]
Ich würde an der Schnittstelle nichts mehr ändern.
Schulbewerbungen.de kann solche Sachen später über die API bekommen...

**Comment by AnneSchueller** [comment]
Der Export ist doch vorhanden (über den Excel Export). Das habe ich übersehen.
Allerdings kann man Kindergärten nicht importieren. Alle Daten müssen bei den Schulen händisch eingegeben werden.
