### ISSUE TITLE
Basisdaten Export/Import: Schüler Vermerke (Importfehler)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1115]
Ich habe einen Export der Basisdaten: Schüler Vermerke durchgeführt und wollte zum Test die gleiche Datei wieder importieren. 
Bei zwei von 300 Schülern war der direkte Import scheinbar nicht mehr möglich. Der Fehler ist mir noch unklar.

![image](https://github.com/user-attachments/assets/edfe3ded-7666-4bc6-b025-e8fd2c885219)

**Comment by AnneSchueller** [comment]
Das ist etwas schwierig nachzustellen. Bei meiner Beispieldatenbank habe ich keine Fehler: Allerdings hat die auch nur ein paar Vermerke, die ich auf die schnelle eingefügt habe.
Entsteht der Fehler auch, wenn neue Vermerke für die besagten Schüler importiert werden?

**Comment by JuergenRichter** [comment]
Bitte mal prüfen, ob es die betreffenden Schüler mehrfach in der Datenbank gibt (Name, Vorname und Geburtsdatum gleich), evtl. durch Duplikate. Dann kann der Importprozess nicht "entschieden", zu welchem Datensatz der Vermerk gehören soll.

**Comment by JuergenRichter** [comment]
Gibt es hier neue Erkenntnisse?

**Comment by JuergenRichter** [comment]
Besteht das Problem noch (bzw. ist es überhaupt ein Problem)?

**Comment by Raffenberg** [comment]
Das Problem scheint eher auf ein Duplikat in der Datenbank zurückzuführen zu sein. Ich schließe das Issue mal. Bei Bedarf bitte wieder öffnen.
