### ISSUE TITLE
Verwaltung Export Lernplattform Logineo LMS (CSV) - Daten nicht komplett

### ISSUE THREAD

**Issue by CDittich** [SVWS-NRW/Schild3-BetaTest#1116]
Die Ausgabe der Lehrerkräfte beinhaltet in der Spalte profile_field_Klasse lediglich einen Wert. Hier sollten sämtliche Kurse mit einem | getrennt angegeben werden (zumindest in der Version von Schild2).

**Comment by AnneSchueller** [comment]
Bei meiner Spieldatenbank klappt das. Daher zwei Nachfragen:
1. War die Lernplattform in Schild2 bereits vorhanden und wurde dann entsprechend mit migriert. Oder wurde diese  erst mit SchILD3 angelegt?
2. War ein Häkchen bei anzulegende Gruppen gesetzt? In Schild2 ist das anfangs auf "Klassenunterrichte" gesetzt. in schild3 muss das noch aktiv gesetzt werden.

**Comment by CDittich** [comment]
Die Daten waren in Schild2 bereits vorhanden und wurden entsprechend migriert. Die Migration war etwas kniffelig, da Schild2 auf einer MySQL-DB läuft. Ich konnte die sql-Datei nicht direkt nach Schild3 migrieren, da diese so nicht angenommen wurde.
Somit habe ich das Migrationsmodul genutzt und die MySQL-DB in eine MSAccess überführt, welche dann in Schild3 eingepflegt wurde. Es wurden keine Fehler angezeigt.

Das Häkchen wurde in Schild3 gesetzt.

**Comment by kroerig** [comment]
> Auch der Zugriff direkt auf die MySQL-DB als Migration ergab Fehler.

Hier wären die Fehler in einem neuen Issue interessant.

**Comment by FPfotenhauer** [comment]
Zum Thema MySQL migreirt nicht gerne auch direkt bei uns:
https://github.com/SVWS-NRW/SVWS-Server/issues

Das wird eher ein Bug im SVWS-Server sein. Dankefür die Meldungen!

**Comment by CDittich** [comment]
Ich habe nochmal eine Migration komplett neu durchgeführt. Diesesmal mit direktem Zugriff auf die MySQL. Die Migration lief diesmal durch. Etwaige kleine Fehler mit alten Zuordnungen (ungültige Datensätze, etc.) wurden korrigiert.

Dennoch bleibt leider die Tatsache bestehen, dass beim Export für Logineo LMS der Lehrer das Feld profile_field_Klasse mit nur dem ersten Wert (zumeist die Klasse oder Stufe) versehen wird.

**Comment by AnneSchueller** [comment]
Ich habe das nun einmal getestet: Lernplattform in schild2 angelegt und dann migriert.
Die Logineo Exporte aus schild2 und schild3 heraus sind identisch.
Ich konnte allerdings nur mit einer Access-DB testen.

Könnte das an Groß-/Kleinschreibung liegen?

**Comment by FPfotenhauer** [comment]
Da die Migration in MySQL jetzt klappt, ist das ja nicht das Thema dieses Issues.

Frage:
Ist das im XML Export in Schild2 auch schon so, dass nicht alle Klassen und Kurse in dieses Feld kommen?
Wenn ja, wäre das eine uralte Sache und hier ist ja das Beta-Test-Forum für Schild3.

Zur Info: Die Schnittstelle für Logineo hat vor Jahren einmal die Medienberatung gemacht.

**Comment by CDittich** [comment]
;-) Die Migration war eigentlich auch nicht das Problem. Allerdings weiß ich nicht genau, wo ich das Problem packen kann. Ich habe lediglich die beiden Programme Schild2 und Schild3 und die Export-Tabellen. Diese unterscheiden sich.

Ob jetzt das Problem in der DB liegt, weiß ich nicht. Die DB von Schild 3 wird wohl soweit in Ordnung sein. Die Schild2-DB habe ich selber nicht angelegt. 
Dort habe ich ein Schema latin1_swedish_ci
Habe überlegt, dieses mal zum Test ind UTF8 zu konvertieren und dann nochmal zu migrieren.

Wenn also in Schild3 der Export bei den anderen läuft, dann liegt es ja definitiv nicht daran. Ich werde mal schauen, ob ich eine Beispieldatenbank bekomme und die in Schild3 migriere. Dann kann ich die Export-Dateien mir nochmal anschauen. Sollten die dann korrekt sein, liegt es an meiner DB. Und wenn dann keine Ausgaben kommen, werde ich nochmal eine Installation auf ein neues Betriebssystem ausprobieren.
Falls aber jemand noch eine Idee hat, würde ich mich darüber freuen.

Danke schon einmal.

**Comment by CDittich** [comment]
Welche Zustimmungen genau?

**Comment by AnneSchueller** [comment]
Zum einen die bei den Schülern:

![image](https://github.com/user-attachments/assets/0cf30d6a-9f13-46ac-8e51-02356434ccb7)


Zum anderen die bei den Lehrern:

![image](https://github.com/user-attachments/assets/7591b864-98cc-4156-bb53-705cf48a3e85)

**Comment by CDittich** [comment]
Ja, die sind gesetzt. Bei den Schülern über einen Gruppenprozess, die Lehrer manuell.

**Comment by AnneSchueller** [comment]
Sind die Unterrichte auch korrekt angekommen?
Sind alle Lehrer im Aktuellen HJ bei den Schülerkursen und Fächern hinterlegt?

**Comment by CDittich** [comment]
Ja, die Daten sind eigentlich alle korrekt. Bin mir da ziemlich sicher, weil ich mehrere große Exporte nutze um CVS-Dateien für LogineoNRW-LMS zu erzeugen.
Mir sind bisher keine Fehler innerhalb von Schild3 aufgefallen.
Nur der Export macht Probleme. Wenn man zumindest die SQL-Abfrage hätte, könnte man ja mal schauen, wie die Abfrage aufgebaut ist und wo dort letztendlich der Fehlerteufel steckt.

**Comment by CDittich** [comment]
Kurzes Update:
Ich habe über das Wochenende alle möglichen Dinge mit der Datenbank von Schild2 unternommen und diese dann anschließend nach Schild3 migriert. Leider ohne den benötigten Erfolg.
Die Daten sind in der Datenbank enthalten, die Kurszuteilungen sind korrekt und auch die Zuordnung von Schülern und Lehrern ist ok.
Ich habe jetzt keine Ahnung mehr, woran es noch liegen kann. Sicher ist nur, dass wir diesen Export benötigen um LogineoNRW-LMS zu pflegen. Noch hilft mir der Export von Schild2.

Wenn es eine Adresse gibt, bei der ich mich melden kann, auch gerne mit der entsprechenden Datenbank, wäre ich sehr dankbar.

Beste Grüße,
Carsten

**Comment by AnneSchueller** [comment]
Man könnte auch nochmal testen, was passiert, wenn man über Schild3 eine neue Lernplattform anlegt, diese den Schülern zuweist und den Export erstellt.

@JuergenRichter: Könnte das am Exportprozess liegen?

**Comment by JuergenRichter** [comment]
> Man könnte auch nochmal testen, was passiert, wenn man über Schild3 eine neue Lernplattform anlegt, diese den Schülern zuweist und den Export erstellt.
> 
> @JuergenRichter: Könnte das am Exportprozess liegen?

Es wäre hilfreich, wenn ich mal die zugehörige Datenbank bekommen könnte.

**Comment by AnneSchueller** [comment]
Als SQLite oder ein SQL-Dump der Schild2 DB?

**Comment by JuergenRichter** [comment]
SQlite sollte erst mal reichen.

**Comment by CDittich** [comment]
Das mit der Datenbank weitergeben ist nicht so einfach, da dort unsere Schülerdaten drin sind. Offiziell darf das nur innerhalb des Verwaltungsnetztes bearbeitet werden.
Ich probiere heute Nachmittag mal noch aus, die Beispieldatenbank von Schild2 in Schild3 zu überführen. Wenn dann der Fehler immer noch besteht, kann ich die DB ohne Probleme weitergeben. Ansonsten würde das auch einen Hausbesuch herauslaufen (also dann würde ich irgendwo vorbeikommen)

**Comment by kroerig** [comment]
@CDittich ggf. vorher mit https://www.svws.nrw.de/system/files/zip_und_exe/2024-04/anonymisierung_2024_04_19.zip bearbeiten.

**Comment by FPfotenhauer** [comment]
Ansonsten können wir gerne per Mail Kontakt aufnehmen.
Es gibt da sicherlich eine Lösung.

**Comment by CDittich** [comment]
Danke dafür. Ich check das Anonymisierungstool mal aus. Das kannte ich bisher noch nicht. Womöglich kann ich dann die DB ohne Probleme hier weitergeben.

**Comment by FPfotenhauer** [comment]
Bitte keine Datenbanken hier weitergeben, auch keine anonymisierten.
Wir stellen gerne per PM einen Upload-Link zu einer verschlüsselten Plattform zur Verfügung.

**Comment by CDittich** [comment]
Also jetzt wird es etwas "verwirrend".
Ich habe mit dem Anonymisierungstool die Datenbank (Schild2) bearbeitet und diese anschließend noch einmal dann in Schild3 migriert.
Nach dem neuen Login (mit dem Admin Konto, da ja alle anderen entfernt wurden) sind sowohl die Schüler als auch die Lehrer mit Fakenamen versehen.

Wenn ich nun den Logineo LMS für die Lehrer durchführe, bleibt der Fehler bestehen, dass nur ein Kurs angezeigt wird. ABER, die Lehrerdaten sind immer noch die alten Daten. Und auch bei den Schülern sind die alten Daten vorhanden.

Ich frage mich nun, wo Schild3 die Daten hernimmt?

**Comment by kroerig** [comment]
Was meinen Sie mit "alte Daten"? Die Benutzernamen? Das könnte daran liegen, das das Tool zu alt ist und die Tabellen für die Lernplattformen nicht kennt.

Aber für die Fehlersuche sollten Sie Herrn @FPfotenhauer die unveränderte Datenbank zu Verfügung stellen. Schreiben Sie ihn per Mail an, er schickt Ihnen dann einen Uploadlink.

**Comment by CDittich** [comment]
Unter anderem werden Daten bei den Einwilligungen zur Lernplattform behalten. Weitere habe ich jetzt noch nicht gefunden.

> Bitte keine Datenbanken hier weitergeben, auch keine anonymisierten. Wir stellen gerne per PM einen Upload-Link zu einer verschlüsselten Plattform zur Verfügung.

@FPfotenhauer Ich würde gerne auf diese Möglichkeit zurückkommen. Wie können wir uns denn kurzfristig austauschen?

**Comment by AnneSchueller** [comment]
Ich könnte mir vorstellen, dass das Anonymisierungstool aufgrund des DB-Formats nicht alles anonymisiert. Das Tool wurde -soweit ich weiß- nur mit Access-DBs getestet. Evtl. gibt es hier Probleme mit der Groß- und Kleinschreibung?

**Comment by AnneSchueller** [comment]
Bei meinem o.g. Test hatte ich die Schülerdaten exportiert. Beim Logineo-Export für Lehrerdaten kann ich das Problem der fehlenden Klassen in der Spalte "profile_field_Klasse"  auch mit meiner Spieldatenbank reproduzieren.

**Comment by JuergenRichter** [comment]
Behoben

**Comment by CDittich** [comment]
Leider ist der Fehler nicht gänzlich behoben. Ich habe gerade einen Export-Test mit der neuen Version von Schild3 gemacht und es wurden zwar jetzt mehrere Kurse bei den Lehren angezeigt, aber nicht alle.
Auf dem Ausschnitt kann man es recht deutlich erkennen, dass die Lehrer einer Klasse (und nicht der Stufe), z.B. 6a keine Kurse in dieser Klasse aufgelistet bekommen. Lediglich bei gemeinsamen Kursen z.B. 6-eR oder 6-PP, wo sowohl Schüler der Klasse 6a, 6b,... drin sind, werden gelistet. (Ich hoffe, meine Erklärungen sind nachvollziehbar).

![zugeordnete_kurse_LuL](https://github.com/user-attachments/assets/19dc3af7-51da-499c-91e1-05c761ca339a)

**Comment by CDittich** [comment]
Ich habe gerade noch an Herrn Richter geschrieben, dass der Fehler mit dem Export der LMS-CSV Daten der Lehrer zwar angegangen worden ist, aber immer noch nicht korrekt ist. Der Beitrag ist zwar geschlossen, ich habe dennoch einen weiteren Eintrag dort angehangen (ich weiß leider nicht, wie in diesem Fall verfahren werden sollte).

Verwaltung Export Lernplattform Logineo LMS (CSV) - Daten nicht komplett · Issue #1116 · SVWS-NRW/Schild3-BetaTest (github.com)<https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1116>

Mit freundlichen Grüßen
Carsten Dittich
________________________________

**Comment by CDittich** [comment]
Die Daten in meinem Screenshot sind korrekt, aber nicht vollständig.

Ich habe einmal einen Export von Schild2 und Schild3 mit einem Datensatz hier abgebildet. Dann kann man sehen, dass in Schild3 einige Kurse nicht mit aufgeführt werden. Und diese Kurse sind definitiv mit Leistungsdaten (also zumindest am Ende des Halbjahres).

![LMS-Export_LuL_S2vsS3](https://github.com/user-attachments/assets/070cc408-1ea4-49f4-ab30-49edac009404)

**Comment by JuergenRichter** [comment]
Ursache gefunden und behoben
