### ISSUE TITLE
Verwaltung Datenbank

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1117]
1. Die Einstellung des Sicherungsverzeichnisses gehört m.E. in den Bereich "Datenbank", nicht in allgemeine Einstellungen, da der Bezug zu "Datenbank" ja offentsichtlich ist.
2. "Datenbank sichern" sollte 
a. eine Abfrage auslösen, dass in das eingestellte Verzeichnis gesichert wird
b. die Info anzeigen, dass der Vorgang einige Minuten dauern wird
c. einen Prozessbalken anzeigen, der Fortschritt anzeigt.

**Comment by AnneSchueller** [comment]
Auf c. könnte man meiner Meinung nach verzichten...

**Comment by JuergenRichter** [comment]
Punkt c wird ja vom VWS-Server erledigt, da "weiß" SchILD ja nicht, wie weit der Vorgangs schon ist.

**Comment by FPfotenhauer** [comment]
Das wird schwierig. Dann müssten wir den Fortschritt "nach außen" streamen.
Momentan können wi das nicht umsetzen, da das sehr viel Aufwand erzeugen würde,

**Comment by HHayen** [comment]
c.) ist auch nicht superwichtig. a und b fände ich aber gut, wenn das umgesetzt werden könnte.

**Comment by JuergenRichter** [comment]
Es erscheint nun der folgende Hinweis:
![image](https://github.com/user-attachments/assets/2f0f0f33-5648-4b1b-9cdc-475a2633bc1a)

Zur Einstellung für das Sicherungsverzeichnis: Dies würde ich bei "Einstellungen" belassen (es ist schließlich eine Einstellung). Bei "Datenbank" sind nur "Aktionen" hinterlegt (z.B. die Sicherung), keine Eingaben. Wenn man hier noch einen Punkt "Sicherungsverzeichnis" hinzufügen würde, würde das Eingabefeld "allein auf weiter Flur" stehen.

**Comment by HHayen** [comment]
Einverstanden. Hinweis ist auch gut, Vielen Dank!!!
