### ISSUE TITLE
Muss-Kind bei Filter I herausnehmen

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#112]
Im Bereich Auswahl >Individualseite II ist unter Einschulungsart die Aussage "Muss-Kind".... voreingestellt. Dadurch wird das Filterergebnis beeinflusst, da nicht nur Muss-Kinder in der Schule sind. Das Feld sollte also leer bleiben.

**Comment by JuergenRichter** [comment]
In 3.0.13.3 behoben
