### ISSUE TITLE
Filter in Version 3.1.0

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#1124]
Wenn man im Filter auf testen geht kommt immer folgende Fehlermeldung:

![SNAG_2024_10_18_10 18 15](https://github.com/user-attachments/assets/f4369329-3269-4cb2-9b3e-c206b737a174)

Datenbank GymAbi

**Comment by FPfotenhauer** [comment]
Es sind aber bei mir fast alle DBs betroffen.

**Comment by JuergenRichter** [comment]
Schaue ich mir sofort an.

**Comment by JuergenRichter** [comment]
Behoben
