### ISSUE TITLE
Export Initialkennwort

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1125]
Habe ich das richtig verstanden, dass das Initialkennwort gleich dem Password-Hash-Wert für Lehrkräfte ist, das nun auch bei allen Schulformen vor dem Notenexport angelegt werden muss?

In Schild2 konnte man hier das Initialkennwort der Lehrkräfte exportieren:

![image](https://github.com/user-attachments/assets/b62879d8-f7c2-4f47-b24c-4be1ef81b173)

Diese Option fehlt in Schild3

**Comment by AnneSchueller** [comment]
Ergänzung:
Nach Initialkennwort generieren ist in der Tabelle kein Eintrag:

![image](https://github.com/user-attachments/assets/25aea569-8d5b-4144-bd94-51c5ad9ea8e5)

**Comment by FPfotenhauer** [comment]
Wir haben dazu m.W. einen API Endpunkt gebeut.
Dieser sollte genutzt werden. Das Initialkennwort wird in der Lehrkräfte Tabelle per Mail versendet oder sollte auch mit der Reporting gedruckt werden können.

**Comment by AnneSchueller** [comment]
Sollte das Passwort dann vergeben werden durch Mausklick auf die Lehrkraft und "Initialkennwort setzen" mit Ändern des Passwortes beim Einspielen der Notendatei oder bleibt das Passwort leer und wird beim ersten Einspielen der Notendatei gesetzt?
m.E. wäre die erste Variante besser, die in Schild2 auch bereits bei den Grundschulen angewendet wird.
Dies funktioniert in Schild3 aktuell nicht.

**Comment by JuergenRichter** [comment]
Für die verfügbaren Felder beim Export ist ja jetzt der SVWS-Server zuständig. Ich werde den notwendigen SQL-Befehl erstellen und zusenden.

**Comment by JuergenRichter** [comment]
Ich habe mal das Setzen eines Initialkennwortes über den SVWS-Server umgesetzt, über 
https://localhost/db/svwsdb-ge/enm/credentials/reset/{id}
Die Beschreibung in der SwaggerUI sagt dazu: "Setzt das Kennwort des Lehrers für das externe Notenmodul auf das Initial-Kennwort zurück. Ist noch kein Initialkennwort gesetzt, so wird ein neues erzeugt."

Leider passiert das so nicht. In meiner Testdatenbank gibt es in der Tabelle "K_Lehrer" bei meiner "Test-Lehrer-ID" einen Eintrag im Feld "CredentialID". Im zugehörigen Datensatz in der Tabelle "Credentials" ist das Initialkennwort leer. Wenn ich den o.a. API-Befehl aufrufe (egal ob in SchILD3 oder in der SwaggerUI) ist das Feld danach auch noch leer, d.h. es wird kein Initialkennwort erzeugt. Ich habe dann testweise den Datensatz in "Credentials" gelöscht (das Feld K_Lehrer.CredentialID wurde dabei geleert) und den API-Aufruf nochmals gestartet. Es wurde aber kein neuer Eintrag in "Credentials" erzeugt, das Feld CredentialID bleibt leer.
Mache ich etwas falsch?

**Comment by AnneSchueller** [comment]
Ich habe diese Methode einmal getestet:
/db/{schema}/enm/credentials/generate

Damit erhalte ich Initialkennwörter in dieser Tabelle:
![image](https://github.com/user-attachments/assets/68fce5db-1db0-4482-a39d-8acb13a276dc)


Durch die "reset" Methode ändert sich das Datum in der Tabelle timestampslehrernotenmodulcredentials:

![image](https://github.com/user-attachments/assets/942e8885-670c-4eee-9951-8531d3400e32)

**Comment by JuergenRichter** [comment]
Ich habe diese Methode einmal getestet:
/db/{schema}/enm/credentials/generate

Das erzeugt Initialkennworte für alle Lehrkräfte. Ich wollte das aber eigentlich gezielt auf ausgewählte Datensätze machen. daher die Verwendung von /db/{schema}/enm/credentials/reset/{id}

Andere Frage: Das Initialkennwort wird ja jetzt wohl auch beim ENM-Export in die Exportdatei geschrieben. Wie erkennt das ENM dann, dass es sich um ein Initialkennwort handelt, das dann im ENM geändert werden muss. Und wer "kümmert" sich darum, dass das geänderte Kennwort zurück in die Datenbank kommt? Die Importfunktion im SVWS-Server?

**Comment by JuergenRichter** [comment]
Ich habe /db/{schema}/enm/credentials/generate mal in meiner Testdatenbank wie folgt getestet:
-Tabelle "Credentials" geleert, bis auf den Eintrag für den Admin
-Dann "/db/{schema}/enm/credentials/generate" ausgeführt. Danach enthält die Tabelle "Credentials" weiterhin nur einen Datensatz:
![image](https://github.com/user-attachments/assets/c5d7777f-af77-4379-b1d7-f63150ba4e6a)

Kann es sein, dass der Befehl  "/db/{schema}/enm/credentials/generate"  nur "Benutzer im engeren Sinne" berücksichtigt, also Personen, die in der Benutzerverwaltung eingetragen sind? Nicht aber "normale" Lehrkräfte, die keine "SchILD-Benutzer" sind?

**Comment by JuergenRichter** [comment]
Ich habe jetzt in zwei meiner Testdatenbanken den Befehl "/db/{schema}/enm/credentials/generate " ausgeführt. In beiden Fällen wurde kein Eintrag in "Credentials" erzeugt, demzufolge ist auch das Feld K_Lehrer.CredentialID leer.

**Comment by FPfotenhauer** [comment]
Wir schauen uns das einmal an. Danke!

**Comment by ThomasBachran** [comment]
@JuergenRichter : Die Tabelle `Credentials` ist für das externe Notenmodul der falsche Ort. Die Tabelle `LehrerNotenmodulCredentials` ist hier der korrekte Ort, wo die speziellen Credentials für das Notenmodul abgelegt sind. Da es sich um ein (externes) Modul handelt, sind diese hier bewusst getrennt von den sonstigen Credentials.

**Comment by JuergenRichter** [comment]
Danke, dann habe ich nur an der falschen Stelle geschaut, ob der Befehl auch funktioniert hat. In "LehrerNotenModulCredentials" ist jetzt tatsächlich was drin.

**Comment by JuergenRichter** [comment]
Jetzt funktioniert auch die Erzeugung der Initialkennworte aus SchILD3 heraus.
Damit das Initialkennwort auch beim Excel-/Text-Export der Lehrerdaten zur Verfügung steht, muss eine Ergänzung im SVWS-Server gemacht werden, Ich habe die Liste der verfügbaren Exportfelder ergänzt,  die Datei ist angefügt.
[TextExportNeu.csv](https://github.com/user-attachments/files/17495283/TextExportNeu.csv)

**Comment by ThomasBachran** [comment]
Die Datei ist jetzt bei uns integriert und wird dann in dem nächsten Release enthalten sein.
