### ISSUE TITLE
Darstellung von Pfaden

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#1126]
Wenn man in der Reportverwaltung auf Standardformulare klickt, erscheint folgendes Fenster:
![grafik](https://github.com/user-attachments/assets/ade86c60-9802-4345-8835-84c615bd1c17)

Da fehlen ein paar Backslashes, damit mit die Pfade auch lesen kann.

Der Pfad selbst stimmt auch nicht. Der müsste mit `P:\SVWS-Arbeitsverzeichnis` beginnen. Ich finde aber im Programm keine Einstellungen dazu.

Version: 3.1.0.28

**Comment by EwaldReinhardt** [comment]
In meiner DB war kein Standard hinterlegt.
Habe ich dann über Rechtsklick/Standardbescheinigung gesetzt.
![grafik](https://github.com/user-attachments/assets/487f722b-1eea-4af4-a23f-dd49c81526aa)
Dann wird der Pfad korrekt angezeigt:
![grafik](https://github.com/user-attachments/assets/d991ebb1-fb1d-4e29-8363-cca91209c6c2)

**Comment by kroerig** [comment]
Dann sollten diese Werte bei der Migration geleert werden, damit man sie wieder neu setzt.

**Comment by AnneSchueller** [comment]
@ThomasBachran: Was meinst du dazu? 
Das leeren fände ich grundsätzlich sinnvoll, da die Reports ja nun auch im Arbeitsverzeichnis liegen sollten.

**Comment by ThomasBachran** [comment]
@AnneSchueller : Das ist mMn keine Aufräumarbeit, die in der Migration des Servers erfolgen sollte. Vielleicht sollte Schild 3 hier den Wert verwerfen, wenn er fehlerhaft ist und auch einen Default probieren. Solche Probleme können ja durchaus auch noch nach einem Migrationsprozess stattfinden...

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue wieder.
Wenn man beispielsweise die Standardbescheinigung drucken möchte und das Verzeichnis fehlerhaft ist, wird ja eine entsprechende Fehlermeldung in Schild3 ausgegebene

**Comment by kroerig** [comment]
> @AnneSchueller : Das ist mMn keine Aufräumarbeit, die in der Migration des Servers erfolgen sollte. Vielleicht sollte Schild 3 hier den Wert verwerfen, wenn er fehlerhaft ist und auch einen Default probieren. Solche Probleme können ja durchaus auch noch nach einem Migrationsprozess stattfinden...

Ja, wenn man die Vorlagen verschiebt, dann macht man das aber mit dem entsprechenden Wissen. Fängt man bei Null ein, dann sie die Werte klassischerweise leer. Wenn man aber migriert und die Report 1:1 übernimmt (was wohl die meisten machen werden), dann sollte SchILD3 solche Einstellungen beim ersten Start prüfen (und anmeckern und ggf. korrigieren) oder bei der Migration wird der Wert gelöscht und SchILD3 meckert dann, dass er nicht gesetzt ist.

Wenn es nicht nicht fett im Migrationshandbuch steht, wird da automatisch wohl niemand nach schauen, bis dann das erste Mal jemand schreit.

**Comment by ThomasBachran** [comment]
Schild 3 kopiert nach der Migration die alten Schild 2 - Einstellungen und passt diese an. Im Rahmen dieses Vorgangs könnte man ggf. die vorgeschlagene Funktionalität einbauen. Mein Kommentar weiter oben bezog sich in erster Linie auf den Migrationsprozess der SVWS-DB, wo ich es nicht sehen würde.

**Comment by JuergenRichter** [comment]
Ich habe das Problem mal bei mir nachgestellt:

1. In SchILD2 ein Standard-Stammblatt und eine Standard-Schulbescheinigung zugewiesen, diese werden mit Pfadangaben in der MDB gespeichert:
![image](https://github.com/user-attachments/assets/416cade7-6c16-4f32-9c69-10462dfa1960)

2. Dann nach SchILD3 migriert, in der MariaDB stehen die Angaben auch korrekt drin:

**Comment by kroerig** [comment]
In meinem Fall migriere ich aus einer bestehenden MariaDB. Die Schild2 Reports liegen unter LW:\SchILD-NRW\SchILD-Reports.
Für SchILD3 (weil ggf. angepasst.) liegen Sie unter LW:\SVWS-Arbeitsverzeichnis.
Und das ist dann auch der Pfad, der für später bleibt.

So kommen die beiden sich nicht in die Quere.

**Comment by JuergenRichter** [comment]
Kann es sein, dass der Migrationsprozess mit einer MariaDB als Ursprungsdatenbank bei Pfadangaben Probleme hat?

**Comment by kroerig** [comment]
Möglich. In der Schild2DB.Schild_Verwaltung steht:
```
BackupDatum;AutoBerechnung;DatumStatkue;DatumSchildIntern;Bescheinigung;Stammblatt;DatenGeprueft;FaecherUebernehmen;Version;GU_ID;StatistikJahr;SchulnrEigner;LD_Datentyp;DatumLoeschfristHinweisDeaktiviert;DatumLoeschfristHinweisDeaktiviertUserID;DatumDatenGeloescht
2016-07-01 07:26:08;2024-11-12 07:41:16;2013-01-28 12:01:16;2011-07-07 21:27:54;P:SchILD-NRWSchILD-ReportsStandardBescheinigungenSchulbescheinigung Leibniz.rtm;P:SchILD-NRWSchILD-ReportsStandardListen - SekretariatAnwesenheitsliste - klassensortiert.rtm;+;+;30.07.2024;{E490ED42-97A9-11D8-A846-002018BA160F};2013;165256;I;2023-12-18 00:00:00;38;\N
```

In der Schild3.Schild_Verwaltung kommt es genauso an:
```
BackupDatum;AutoBerechnung;DatumStatkue;DatumSchildIntern;Bescheinigung;Stammblatt;DatenGeprueft;Version;GU_ID;DatumLoeschfristHinweisDeaktiviert;DatumLoeschfristHinweisDeaktiviertUserID;DatumDatenGeloescht
2016-07-01 07:26:08;2024-11-08 10:04:05;2013-01-28 12:01:16;2011-07-07 21:27:54;P:SchILD-NRWSchILD-ReportsStandardBescheinigungenSchulbescheinigung Leibniz.rtm;P:SchILD-NRWSchILD-ReportsStandardListen - SekretariatAnwesenheitsliste - klassensortiert.rtm;+;30.07.2024;{E490ED42-97A9-11D8-A846-002018BA160F};\N;\N;2024-10-19 00:00:00
```

Könnte auch sein, das das eine Altlast aus Access-Zeiten ist und diese Einträge nie genutzt wurden. Denn ohne Backslashes können die ja nie funktioniert haben, oder?

**Comment by JuergenRichter** [comment]
> Denn ohne Backslashes können die ja nie funktioniert haben, oder?

Stimmt, ohne Backslashes hätte es auch in SchILD2 eine Fehlermeldung geben müssen
