### ISSUE TITLE
vereinfachte Zuwanderungsgeschichte

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1127]
Diese Möglichkeit aus Schild2:
![grafik](https://github.com/user-attachments/assets/0e8dad16-078d-477e-84d4-5b929d5da5bc)

finde ich nicht in Schild3:

![grafik](https://github.com/user-attachments/assets/8e0434f1-8771-44c4-b464-e90f1a77d061)

Kann das bei Schulen, die das schon länger verwenden, zu Migrationsproblemen führen, da Daten fehlen? Ich kann das selber nicht schnell testen.

**Comment by FPfotenhauer** [comment]
Das wurde abgeschafft.
Es wird nun immer die ausführliche Variante genutzt.
Die Daten werden mit "Sonstiges" migriert. Es gehen also keine Daten verloren.
Die Option des vereinfachten Hintergrund war damals eine schlechte Idee.

**Comment by HHayen** [comment]
Ok, danke. Sehe gerade, dass das auch im Forum schon gefragt wurde.

**Comment by AnneSchueller** [comment]
Kann es denn sein, dass früher einmal mit der erweiterten Zuwanderungsgeschichte gearbeitet wurde und das Geburtsland "Deutschland" bei der Mutter eingetragen war? Die Daten bleiben in der Datenbank erhalten?

**Comment by AnneSchueller** [comment]
Ich sehe gerade, dass bei SChild3 kein Geburtsland steht...
Das ist seltsam.

Ich lasse das Issue hier geschlossen und verlinke nach hier: https://github.com/SVWS-NRW/SVWS-Server/issues/290
