### ISSUE TITLE
Feld "Weitere Adressangaben"

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1129]
Problem 1:
Sobald man im Feld "Weitere Adressangaben" etwas einträgt und den Schüler wechselt kommt die Abfrage "Sollen die geänderten Adressangaben auch bei den Erziehungsberechtigten aktualisiert werden?" 
Ein "ja" hat keine Auswirkungen auf den Erziehereintrag

Problem 2:
Es wird nur das erste Zeichen der Eingabe im Feld "Weitere Adressangaben" gespeichert. In der DB ist das Feld mit 30 Zeichen ausgewiesen.

**Comment by JuergenRichter** [comment]
Beider behoben
