### ISSUE TITLE
Login-Session nach Aktualisieren der Seite im Webclient weg

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/Schild3-BetaTest#1130]
Hallo zusammen,
ich habe einen kleinen Bug / Usability Issue gefunden: Wenn ich die Seite im Chrome Browser neu lade, dann verliere ich meine Session und muss mich neu anmelden. Das passiert sowohl im normalen Client als auch im Admin Client.

**Comment by AnneSchueller** [comment]
Das ist m.E. kein Bug.
Da die Daten unmittelbar nach Änderungen in der Datenbank sind, braucht man den Button "Neu Laden" aus dem Browser nicht, um Daten zu aktualisieren.

**Comment by SimonFrank14** [comment]
@AnneSchueller 
Ich verstehe Ihren Punkt und vielleicht ist es dann nicht direkt ein Bug, aber ich würde es dennoch als Usability Issue sehen. Sie haben gesagt, dass die Daten im Normalfall direkt in die DB geschrieben werden. Das ist erst so aus der UI nicht ersichtlich. Möglicherweise könnte man hier noch einen Hinweis auf das automatische Speichern bzw. den Zustand des Speicherns tracken.

Aber zurück zum Thema:
Eins der Potenziale vom Browser ist ja, dass ich beliebig viele Tabs nebeneinander öffnen kann und so Informationen abgeglichen kann. Mit der aktuellen Implementierung des Logins, muss ich mich in jedem Tab wieder neu anmelden, weil die Session nicht in einem Cookie oder im local Storage gespeichert wird.

Außerdem fällt mir gerade auch auf, dass die Liste mit den Schülern im linken Bereich auch keine Links enthält, sodass ich auch von hieraus nicht schnell den Schüler in einem neuen Tab öffnen kann.

Das sind wie gesagt keine Bugs, aber vielleicht kann man dies für zukünftige Verbesserungen mal im Hinterkopf behalten.

**Comment by FPfotenhauer** [comment]
Issues zum WebClient und zu SVWS-Server gerne auch hier:
https://github.com/SVWS-NRW/SVWS-Server/issues

Da hier einfach zwei verschiedene Teams arbeiten, dann erreicht uns das einfach schneller.
Vielen Dank! Momentan arbeitet der Client aus verschiedenen Gründen nicht mit Cookies.
Das Thema haben wir aber auf dem Schirm und diskutieren das später nochmal!
