### ISSUE TITLE
Erziehungsberechtigte/Telefonnummern

### ISSUE THREAD

**Issue by j-john-de** [SVWS-NRW/Schild3-BetaTest#1134]
Kleines Problem!
Wenn bei Erziehungsberechtigten nur eine Telefonnummer eingetragen ist poppt immer das Fenster zur Übernahme der geänderten Telefonnummer in die Stammdaten auf. Die Telefonnummern wurden aber aus der Datenbank übernommen und nicht geändert.
Es wird auch nicht ganz klar, was passiert. Ich nehme an, dass die Nummer der Erziehungsberechtigten in die Individualdaten I übernommen wird.
Vielleicht könnte beim Import gleich einen Abgleich gemacht werden, wenn die Nummer identisch ist?
Oder man könnte den Text im Fenster ändern (z.B. "Soll die eingetragene Telefonnummer in die Individualdaten I übernommen werden?") 
![Screenshot 2024-10-23 113348](https://github.com/user-attachments/assets/7dc4a9c3-b38f-4105-b03a-5a84b45111a6)
Liebe Grüße

**Comment by AnneSchueller** [comment]
Können Sie den Workflow nochmal beschreiben.
Wenn ich bei den Erziehungsberechtigten eines Schülers, der keinen Telefonnummereintrag hat, hin und her klicke, erhalte ich nicht diesen Hinweis. 
Erst wenn ich bei den Erz. eine neue Nummer hinzufüge, erscheint dieses Fenster.

**Comment by j-john-de** [comment]
Die Datenbank ist importiert mit Schülertelefonnummern. Wenn unter Erziehungsberechtigte/Telefonnummern nur eine Nummer hinterlegt ist, kommt beim Klicken auf den Reiter "Erziehungsberechtigte/Telefonnummern" sofort obiges Fenster. LG

**Comment by j-john-de** [comment]
Lieben Dank! Ich probiere es sobald wie möglich aus. Liebe Grüße Jens

**Comment by j-john-de** [comment]
Prima. Das hat das Problem gelöst.
