### ISSUE TITLE
Verbindung zu Schildweb

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/Schild3-BetaTest#1135]
Hallo zusammen,

gibt es schon Erahrungen / Tests bzgl. der Verbindung zu Schildweb? Wie ist da der Stand. Denn solange diese Verbidnung nicht einwandfrei funktioniert, könnten wir natürlich nicht umstellen.

Gruß aus Münster...

**Comment by AnneSchueller** [comment]
Hallo Niels,

Nachfragen zum Entwicklungsstand von Schildweb müssten an Ribeka gerichtet werden. 
Für Schild-NRW3 wird aktuell an einem Webnotenmodul gearbeitet. Über den Entwicklungsstand wird am Fachberatertreffen berichtet.
