### ISSUE TITLE
Nach Update auf Schild 3.1.28 Fehlermeldung beim Start (WBK)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1136]
Nach dem Update auf Version 3.1.28 erhalte ich folgende Fehlermeldung beim Start:
<img width="233" alt="image" src="https://github.com/user-attachments/assets/fd10fb52-58f6-4850-bfb5-1740a5034f18">
Danach bricht Schild ab.
SVWS-Server: 0.9.2 
Ich werde am Montag auf den aktuellen Server updaten. Habe mich nur gewundert, weil eigentlich keine großen Änderungen im Server mehr vorgenommen werden sollten.

**Comment by FPfotenhauer** [comment]
Schild-NRW 3.1.0 benötigt zwingend den Server 1.0.0
