### ISSUE TITLE
Verbindung zu Schild-Foto (von Ribeka)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1137]
Wir nutzen das Tool von Ribeka Schild-Foto. Auch hier (siehe Schild-Web) würde mich die Anbindung interessieren.

**Comment by kroerig** [comment]
Das sind ja beides kommerzielle Module von Ribeka. Die Frage müssen Sie also an die stellen.

Braucht es diese Programme überhaupt noch? Was können die, was nicht bereits im SVWS Client enthalten ist?

**Comment by Kluesenerm** [comment]
Aktuell wird das Programm noch von einigen Schulen eingesetzt. Der SVWS-Server kann nur einzelne Bilder hochladen und aktuell klappt es noch nicht (wir werden natürlich perspektivisch auf das Fotomodul von Ribeka verzichten ;).

**Comment by AnneSchueller** [comment]
Hier müsste man einmal bei Ribeka nachfragen, ob ein analoges Foto-Programm unter Schild3 angeboten wird.
Daher schließe ich das Issue.
