### ISSUE TITLE
Filter II kann nicht aufgerufen werden

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#114]
Wenn ich den Filter II aufrufe kommt folgende Fehlermeldung:
[Filter II.pdf](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6156527/Filter.II.pdf)
Wenn ich dann die zweite Fehlermeldung auch mit ok bestätige, gelange ich auf das Auswahlfenster für den Filter II. Dort kann ich dann aber keine Auswahl treffen.

**Comment by FPfotenhauer** [comment]
Es fehl das Präfix Schildintern_ bei dem Aufruf.

**Comment by JuergenRichter** [comment]
In 3.0.13.3 behoben
