### ISSUE TITLE
Netzlaufwerke in der Installation nicht auswählbar

### ISSUE THREAD

**Issue by ThomasPaul78** [SVWS-NRW/Schild3-BetaTest#1141]
Bei der Installation vom SVWS Server ist eine Installation auf ein Netzlaufwerk und das Öffnen zur Migration einer SchILD2 DB aus einem Netzlaufwerk nicht möglich!
Die Laufwerke werden nicht angezeigt und über den Pfad kann ich nicht ändern.

**Comment by kroerig** [comment]
Für eine Netzlaufwerksinstallation würde dich die ZIP-Datei nehmen.
Das Verhalten ist normal unter Windows, wenn der Installer als Benutzer gestartet wird und dann Admin-Rechte anfordert.

Abhilfe: eine CMD als Administrator starten, dort mit `net use LW: \\UNC\Pfad` das Laufwerk verbinden und anschließend wieder trennen. Dann ist es auch für den Installer verfügbar.

Alternativ kann man unter `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System` den Wert `EnableLinkedConnections` als DWORD=1 setzten, dann übernimmt Windows Netzlaufwerke aus Benutzersitzungen. Aus Sicherheitsgründen ist das aber nicht zu empfehlen.
