### ISSUE TITLE
Installation SVWS-Server nach Abbruch nicht mehr möglich

### ISSUE THREAD

**Issue by ThomasPaul78** [SVWS-NRW/Schild3-BetaTest#1142]
Wenn eine Installation vom SVWS-Server abgebrochen wurde, ist eine neue Installation oder die Fortführung nicht möglich.
S. Screenshot
"Es muss ein gültiges Daten-Verzeichnis angegeben werden"-
![1](https://github.com/user-attachments/assets/9f0ffd65-c066-4910-a851-5a2820d9af0c)

**Comment by AnneSchueller** [comment]
Bitte einmal testen, ob in den Verzeichnissen c/ProgrammData oder c/Programme noch Reste (SVWS-Server-Ordner) von der SVWS-Serverinstallation liegen.

**Comment by ThomasPaul78** [comment]
Beide Verzeichnisse sind leer.
Ich musste SVWS im Registrierungseditor suchen und die Einträge per Hand löschen. Dann konnte ich installieren.

**Comment by AnneSchueller** [comment]
Ah ok. Danke für den Hinweis und das Testen.

Ich leite die Problematik mal an die SVWS-Abteilung weiter und schließe hier das Issue.
Bugs, die den SVWS-Server betreffen, zukünftig besser direkt hier erstellen:
https://github.com/SVWS-NRW/SVWS-Server/issues

Falls man sich unsicher ist, ob es sich wirklich um einen Bug handelt kann man alternativ auch erstmal im Forum schreiben. Da gibt es nun einen speziellen Bereich für Schild3 und den SVWS-Server:
https://schulverwaltungsinfos.nrw.de/svws/forum/viewforum.php?f=87&sid=4f8987a63a5f1f43d18c24fc68128696

**Comment by FPfotenhauer** [comment]
Wieso wurde denn die Installation abgebrochen.
Wir haben da gar nicht so viel Einfluss drauf, das macht InnoSetup.

**Comment by ThomasPaul78** [comment]
Ernsthaft?
1. weil es einen guten Grund dafür gab.
2. weil es einen "Abbrechen"-Button gibt
3. weil ein Beta-Test ja das Wort "Test" beinhaltet!

Es scheint hier aber dennoch ein Programmierfehler vorzuliegen.
