### ISSUE TITLE
neuer Benutzer: mtblLaender, das Feld "gueltigVon" wurde nicht gefunden.

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1145]
Nach Anlegen eines neuen Benutzers in Schild3, der keine Adminrechte hat (Standard-Lehrergruppe) erscheint der auch hier (https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=7192&start=10) beschriebene Fehler:
mtblLaender, das Feld "gueltig Von" wurde nicht gefunden.

Unabhängig, ob eine bestehender Lehrernutzer oder eine allg. Nutzer.
Fehler auch, wenn Nutzer über svws-Admin angelegt wird.
Fehler triit in Schulungsdatenbank einer GE aus der Fachberatercloud auf, diese wurde neu migriert. In "Echt"-DB habe ich den Fehler nicht nachstellen können.

**Comment by AnneSchueller** [comment]
Ich habe das mit zwei TestDBs getestet und kann das nicht reproduzieren.
Hattest du die Schild2 DB vorab mit schild2 einmal geöffnet um fehlende Tabellen anzulegen?

**Comment by AnneSchueller** [comment]
Weißt du, in welchem Ordner deine  getestete GE-DB liegt?

**Comment by HHayen** [comment]
Ja, die DB lief zuvor unter Schild2.
DB aus der Fachberatercloud->Schild2-Schulungsdatenbanken->Schulungsdatenbanken_2024_Neu.7z
Daraus die GE_2025_24_1

**Comment by AnneSchueller** [comment]
Mit der DB kann ich das reproduzieren. 
Hier hatten wir bei der Anonymisierung so viele Infos rausgeschmissen, dass ich das jetzt erstmal ignorieren würde. Bei anderen DBs habe ich das noch nicht beobachtet. 
Für den Fall, dass das später nochmal relevant ist, hänge ich den Log noch an:

[NeuerBenutzerFehlerlog.txt](https://github.com/user-attachments/files/17630137/NeuerBenutzerFehlerlog.txt)
