### ISSUE TITLE
Teilleistungseingabe Fehler

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1146]
Eintragen neuer Teilleistungen liefert diesen Fehler:
![grafik](https://github.com/user-attachments/assets/0558e34d-cffd-4fcb-a09b-8743aadfbdd3)

**Comment by HHayen** [comment]
Ergänzung: **Wechselt man nach Anlegen des neuen Datensatzes den Schüler** und dann zurück, lässt sich die Note eintragen. Wen das so notwendig ist, muss ein Hinweis dazu erscheinen, besser wäre, dass das nicht notwendig ist.
Anmerkung: Wechselt man auf **"Punkte", wird das nicht berücksichtigt**.

**Comment by AnneSchueller** [comment]
[Teilleistungen.txt](https://github.com/user-attachments/files/17617614/Teilleistungen.txt)

**Comment by JuergenRichter** [comment]
Der Fehler bei der Eingabe ist behoben, werde nun auch die Punkteingabe ermöglichen

**Comment by JuergenRichter** [comment]
Punkteingabe ist auch umgesetzt (wenn bei den Leistungsdaten die Option "Punkte" gewählt ist).

**Comment by AnneSchueller** [comment]
Beim Testen ist mir aufgefallen, dass nach dem Zuweisen von Teilleistungen über einen GP für jeden Schüler die Information kommt:
![image](https://github.com/user-attachments/assets/246a9d94-6fb6-4d5c-a3b3-07ea9ab5ce3b)
Diese erscheint, sobald man auf "aktuelles HJ" klickt

**Comment by AnneSchueller** [comment]
Der Fehler erübrigt sich nach einem Neustart von Schild3.
d.h. nach dem Anlegen der Teilleistung für ein Fach muss Schild einmal neu gestartet werden.
Ursprüngliche Fehlermeldung ist nun weg: Punkteeingabe funktioniert.
