### ISSUE TITLE
Dateiformate Grafikdateien (Schullogo)

### ISSUE THREAD

**Issue by JKleine-svws** [SVWS-NRW/Schild3-BetaTest#1147]
Während der Report-Builder in den Reports beim Einbinden von Grafiken verschiedene Formate, darunter sowohl Pixel- als auch Vektorgrafikformate, unterstützt, kann in SchILD 3 das Schullogo in der Verwaltung nur in den Pixelformaten .jpg, .bmp, .gif oder .png hochgeladen werden.
Das war allerdings auch schon in SchILD 2 so, trotzdem arbeiten viele Schulen wegen der Darstellbarkeit gern mit Vektorgrafiken.

**Comment by JKleine-svws** [comment]
Ich wurde darauf aufmerksam gemacht: In Schild 2 ließen sich DOCH Vektorgrafiken (zumindest im EML-Format) als Schullogo verwenden - durch Eingabe des * bei der Dateiauswahl. In Schild 3 ist das nicht möglich.

**Comment by JuergenRichter** [comment]
In SchILD2 werden die Grafiken im "Original-Format" gespeichert, in SchILD3 werden die Grafiken aber Base64-kodiert gespeichert. Ich muss prüfen, ob das Auswirkungen bei Vektorgrafiken hat.

**Comment by HHayen** [comment]
Ergänzung: Die Reporting verweigerte auch jpeg bei uns (Einstellungen im Report waren natürlich Grafikart->AutoDetect)
Erst bmp-Logo wurde dann verarbeitet.

**Comment by JuergenRichter** [comment]
Es können jetzt auch SVG-Dateien als Schullogo verwendet werden. Die Daten werden dann aber im Orginalformat (SVG ist Textformat) in der Datenbank gespeichert.
![image](https://github.com/user-attachments/assets/ddf5e051-eacf-4964-88a9-956a9c4e8a19)
![image](https://github.com/user-attachments/assets/feb6983f-daa7-4ec7-8ed3-fa2dd497a89a)

**Comment by JKleine-svws** [comment]
Prima, vielen Dank! Werden in Zukunft auch .eml und andere Vektorformate möglich sein?

**Comment by Raffenberg** [comment]
Ich würde auch für das SVG Format plädieren.
SVG ist die vom World Wide Web Consortium (W3C) empfohlene Spezifikation zur Beschreibung zweidimensionaler Vektorgrafiken und am meisten verbreitet im Web.

**Comment by JuergenRichter** [comment]
Es gibt wohl auch ein Grafik-Format, das die gleiche Endung hat. Habe da auf die Schnelle aber nicht viel zu gefunden.

**Comment by JKleine-svws** [comment]
Tippfehler... Es geht um das EMF-Format. Entschuldigung. Wurde von einer Schule angefragt.
Ich schicke Ihnen mal eine Datei zu.

**Comment by Raffenberg** [comment]
Normalerweise kann jedes vektorprogramm eine SVG Datei erstellen. Ich würde hier mich lieber auf den Standard konzentrieren, als Einzelwünsche von Schulen zu erfüllen.

**Comment by AnneSchueller** [comment]
Ich würde das ebenfalls so unterstützen und das Issue damit schließen.

**Comment by JuergenRichter** [comment]
In anderem Zusammenhang habe ich mit dem Windows-eigenen EMF-Format schlechte Erfahrungen gesammelt. Daher plädiere ich auch dafür, nur SVG zu unterstützen.
