### ISSUE TITLE
Unterschiedliche Arbeitsverzeichnisse

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/Schild3-BetaTest#1148]
Hallo,
wenn man den SVWS-Server und Schild3 lokal installiert, sind unterschiedliche Standardwerte für das Arbeitsverzeichnis gesetzt. Der SVWS-Server verwendet c:\ProgramData\SVWS-Server, Schild3 verwendet C:\SVWS-Arbeitsverzeichnis.
Mit meinem laienhaften Verständnis scheint mir der erste Pfad konform zu Windows zu sein.
Um auch bei Netzwerkinstallationen klar zu machen, dass es sich um den gleichen Pfad handelt, sollten diese Pfade gleich lauten.
Auch bei lokaler Installation führt ein einfaches Durchklicken dazu, dass Schild3 nicht mit der Datenbank verbunden werden kann.
Tester werden somit abgeschreckt.
Gruß,
Uli

**Comment by JuergenRichter** [comment]
Das sind zwei unterschiedliche Dinge: Das "Arbeitsverzeichnis" ist ein Verzeichnis, in dem z.B. Dateien, die von SchILD3 erzeugt, gelesen und verändert werden, gespeichert werden. Das können z.B. die Report-Vorlagen sein (im Verzeichnis \SchILD-Reports unterhalb des Arbeitsverzeichnisses). Auf diese Verzeichnis benötigen alle Anwender, die mit SchILD3 arbeiten (und z.B. Reports verändern sollen) mindestens Leseberechtigung, i.d.R. aber auch Berechtigung zum Bearbeiten.
Im Verzeichnis  C:\ProgramData\SVWS-Server stehen dagegen "SVWS-Server-interne Informationen", u.a. auch die Zugangsparameter zur Datenbank. Diese Angaben sollten keinesfalls allen SchILD3-Benutzern zugänglich sein!

**Comment by kroerig** [comment]
aber für das Arbeitsverzeichnis von SchILD3 wäre `%ProgramData%` eigentlich auch der richtige Pfad. Oder unter `C:\Users\Public\Documents`. Von Netzwerkinstallationen mal abgesehen. Denn auf C:\ direkt soll eigentlich keine Software Datenverzeichnisse anlegen. Das ist W95 Style.

**Comment by FPfotenhauer** [comment]
Wir haben mit %ProgramData% hier schlechte Erfahrungen gemacht, weil das ein versteckter Ordner ist.

Da im Arbeitsverzeichnis aber auch Reports gespeichert werden sollen, und dieses Arbeitsverzeichnis oft auch auf Netzlaufwerken liegt, haben wir uns für diesen Default entschieden. Auch mit den Rechten haben wir in den verschiedensten Umgebungen unter C: bisher die besten Erfahrungen gemacht.

Wir kämpfen hier unglaublich mit der Veränderungs-Verweigerung der alten Systeme. Deshalb wollen wir nicht alles auf einmal verändern...
