### ISSUE TITLE
Reihenfolge im Suchdialog

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/Schild3-BetaTest#1149]
Hallo,
ich wollte im Dialog "Schüler suchen" nach dem Vornamen suchen. Standardmäßig steht der Cursor im Feld "Name". 
Ich erwarte, durch Drücken der TAB-Taste in das Feld "Vorname" zu springen.
Tatsächlich wird das Feld "Vorname" als Letztes ausgewählt.
Ich bitte um Änderung.
Gruß,
Ulrich Kloppenburg

**Comment by JuergenRichter** [comment]
Behoben
