### ISSUE TITLE
Filter: Schüler mit Geschwistern ohne die Möglichkeit zurück zu gelangen

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#115]
Wenn ich im Bereich Auswahl den Filter >Schüler mit Geschwister< anwähle, wechselt der Bildschirm in den Bereich Schüler. Ich komme von dort nicht wieder in eine andere Ansicht -  auch nicht über die Button >Aktualisieren, >Übernehmen oder >Abbrechen.
Ich muss dann erst wieder in den Bereich Auswahl wechseln und dort den Button >Standard-Auswahl betätigen.

**Comment by FPfotenhauer** [comment]
Geht nicht Doppelklick auf das rote Filtersymbol?

**Comment by ADV-Fendel** [comment]
Das rote Filtersymbol (Trichter) ist nicht zu sehen!

**Comment by FPfotenhauer** [comment]
???

![SNAG_2021_03_18_15 42 44](https://user-images.githubusercontent.com/34127980/111645010-a71ceb80-8800-11eb-8914-2ccde8d4f2a8.png)

**Comment by ADV-Fendel** [comment]
So sieht es bei mir aus!
[Schüler mit Geschwister.pdf](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6165284/Schuler.mit.Geschwister.pdf)

**Comment by ADV-Fendel** [comment]
Siehe auch issue #111

**Comment by JuergenRichter** [comment]
Es gibt in 3.0.13.3 auf dem "Schüler-Ribbon-Page" bei "Suchen und filtern" eine Schaltfläche "Standard-Filter", damit kann man (ohne auf "Auswahl" wechslen zu müssen) wieder die Standard-Auswahl (Status=Aktiv) anzeigen lassen.

**Comment by ADV-Fendel** [comment]
Es ist nicht nachvollziehbar, dass es zwei Möglichkeiten gibt, zum Standard-Bildschirm mit den aktiven Schülern zu wechseln. Außerdem ist für mich nicht direkt ersichtlich, dass die Schaltfläche Standard-Auswahl heißt, dass ich zum Bildschirm mit den aktiven Schülern wechseln kann. Ein immer sichtbarer Trichter (in den verschiedenen Farben) zeigt mir stets an, ob ich in einer Filterung bin oder bei den aktiven Schülern. Es wäre also schön, wenn der Trichter in allen Bildschirmen zu sehen wäre.
