### ISSUE TITLE
BK: Gruppenprozess "Stundentafel" bei Fachklassen 

### ISSUE THREAD

**Issue by JKleine-svws** [SVWS-NRW/Schild3-BetaTest#1150]
Betrifft BK-Datenbanken:
Während in Schild 2 nach Auswahl einer **Fach**klasse und Zuweisung der Stundentafel per Gruppenprozess auch nur die zugehörige Stundentafel zur Auswahl angeboten wird, erscheinen in Schild 3 alle Stundentafeln der zugehörigen Gliederung. 
Das sorgt zumindest für eine gewisse Fehleranfälligkeit.

**Comment by AnneSchueller** [comment]
Könntest du mal prüfen, ob in der ausgewählten Schülermenge bei allen auch die richtige Gliederung eingetragen ist? Sind alle in der gleichen Klasse?
Wenn ich die bei einem Schüler die Gliederung ändere, erhalte ich auch alle Stundentafeln als Auswahl. 
Ansonsten werden nur die möglichen Stundentafeln angezeigt.

**Comment by JKleine-svws** [comment]
Die Gliedrerung ist bei allen SuS gleich.
Ich habe dieselbe Schulungsdatenbank des BK einmal in Schild 2 und dann migriert in Schild 3 benutzt und mir dort dieselbe Fachklasse angeschaut, mit dem unterschiedlichen Ergebnis, siehe Screenshots.
![Stundentafel_Schild2](https://github.com/user-attachments/assets/239307d4-2849-49e0-9d4f-82cc866863db)
![Stundentafel_Schild3](https://github.com/user-attachments/assets/be91f505-b777-4a58-9734-ac6025068e59)

**Comment by JuergenRichter** [comment]
> @JuergenRichter könnte das auf die Fachklasse für BKs angepasst werden?

Ist umgesetzt
