### ISSUE TITLE
Vereinfachte Eingabe der Zuwanderungsgeschichte 

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1151]
Ich mache die Meldung zur Vereinfachten Zuwanderungsgeschichte noch einmal auf. 

Beim Import kommt es leider zu Problemen. Ich habe es auch im SVWS-Server dokumentiert:
Schild 2:
![image](https://github.com/user-attachments/assets/f96a0607-da91-4ebf-8a79-f9fea11118cf)

Schild 3: Scheinbar "fehlen" Daten, so dass die Sekretariate evtl. unnötigerweise angeregt werden, diese zu befüllen (insbesondere verleitet das "*" zu einer verpflichtenden Eingabe):
![image](https://github.com/user-attachments/assets/f243207b-ceff-477c-adec-8b510d83a560)

SVWS-Server: Die Mütter sind alle in Deutschland geboren:
![image](https://github.com/user-attachments/assets/d7b6fa1a-1450-4597-a797-d37b4a898d08)

**Comment by AnneSchueller** [comment]
Wenn zuvor mit der vereinfachten Zuwanderungsgeschichte gearbeitet wurde, fehlen ohnehin die Angaben in der Datenbank, sodass die Sekretariate nacharbeiten müssen.
Das hier der SVWS-Client und Schild3 unterschiedliche Ergebnisse liefern ist dennoch seltsam.
Was steht denn in der Datenbank bei dem Geburtsland der Mutter?
