### ISSUE TITLE
Gruppenprozesse / Vermerke eintragen

### ISSUE THREAD

**Issue by jwae** [SVWS-NRW/Schild3-BetaTest#1152]
Bei den Individualdaten stehen die Vermerke im Reiter "Vermerke" . 
Bei den Gruppenprozessen trage ich Vermerke über den Reiter "Weitere Daten" ein. Scheint mir etwas unlogisch.

**Comment by AnneSchueller** [comment]
Da unter weitere Daten nur Vermerke angepasst werden, könnte man den Reiter m.E. umbenennen in Vermerke.

**Comment by JuergenRichter** [comment]
Karteireiter ist umbenannt ("Vermerke").
