### ISSUE TITLE
Gruppenprozesse / Vermerke eintragen

### ISSUE THREAD

**Issue by jwae** [SVWS-NRW/Schild3-BetaTest#1153]
Wenn ich Vermerke für mehrere SuS eintragen möchte, dann:
1. erscheint dieses Fenster zwei Mal
2. hat dieses Fenster den unscheinbaren Titel "SChild-NRW 3". Verständlicher wäre "Vermerke ändern ..." (o.ä.)
3. Welche Eingabe zählt? Das Ja / Nein aus dem 1. Fenster oder die Eingabe im 2. Fenster?
Bsp.: Eingabereihenfolge: 1. x Ja /2. Nein Es werden keine Vermerke gespeichert
![04-1](https://github.com/user-attachments/assets/cc7f3eed-6ea1-45e7-aaed-69a5c991b709)

**Comment by AnneSchueller** [comment]
Das Fenster sollte definitiv nur einmal erscheinen.
Die Überschriften in den Fenstern heißen derzeit alle Schild-NRW 3. 
Das könnte m.E. irgendwann für alle angepasst werden.

**Comment by JuergenRichter** [comment]
Die doppelte Meldung ist abgestellt. Der Titeltext bei den Meldungsfenstern kann leider nicht individuell gestaltet werden, der wird durch die Eigenschaft "Application.Title" geregelt, und diese Eigenschaft hat derzeit "SchILD-NRW 3"
