### ISSUE TITLE
Ansprechpartner

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1154]
Hallo zusammen,

wenn ich bei den Katalogen die "Telef. Ansprechpartner" abwähle (Sichtbar kein Haken), tauchen diese dennoch in der Auswahl unter Schüler -> "Erziehungsberechtigte/Telefonnummern" ganz unten bei den "Telefonnummern" als "Ansprechpartner" auf.
Da hier in der Vergangenheit unnötig viele Einträge angelegt wurden, haben wir über 100 Einträge, die nicht sichtbar sein sollen.

![grafik](https://github.com/user-attachments/assets/feecec2a-a461-4eec-89e6-ea72839491e0)

![grafik](https://github.com/user-attachments/assets/ea337073-fb18-4714-adfb-9f252154d6c5)

**Comment by jwae** [comment]
Gilt auch für den Katalog Konfessionen.
