### ISSUE TITLE
Absturz bei Anmeldung ohne Passwort

### ISSUE THREAD

**Issue by derDezi** [SVWS-NRW/Schild3-BetaTest#1156]
Ein Anmeldeversuch ohne die Eingabe eines Kennwortes führt zum Absturz der Software.

Version: 3.1.0.28

![image](https://github.com/user-attachments/assets/caaf3fe4-a896-4ebd-be8f-8c78a25c44c6)
![image](https://github.com/user-attachments/assets/b1d45577-8ae8-4101-96de-46cbe7a211b1)

**Comment by AnneSchueller** [comment]
Das heißt, der Benutzer hat eigentlich ein Passwort, aber lässt die Eingabe des Passwortes leer?

Ich kann das nicht reproduzieren.

**Comment by AnneSchueller** [comment]
Wäre es möglich, einmal den kompletten Log mit anzuhängen.
Unter Regel 2 ist eine Kurzanleitung:
https://github.com/SVWS-NRW/Schild3-BetaTest/wiki

**Comment by JuergenRichter** [comment]
Gibt es hier Erkenntnisse?

**Comment by AnneSchueller** [comment]
Hier gab es ein ähnliches Problem:
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=7231

**Comment by JuergenRichter** [comment]
Da wäre es natürlich hilfreich, wenn man mal eine Datenbank bekommen könnte, bei der das Problem auftritt. Am fehlenden Kennwort kann es m.E. nicht liegen, da ich hier diverse Datenbanken habe, wo das auch so ist und die keine Probleme erzeugen.

**Comment by AnneSchueller** [comment]
@derDezi Wäre es möglich, dass ich Ihnen einen Upload-Link zukommen lasse, sodass wir das Problem einmal testen könnten - sofern es noch besteht?

**Comment by JuergenRichter** [comment]
Natürlich, falls per E-Mail:
juergen.richter@ribeka.com

**Comment by mueller-falko** [comment]
Ich hatte das gleiche Problem bei einer anonymisierten mdb, in der standardmäßig nur ein Admin ohne Passwort existiert. Nach der Migration erscheint beim Login die Fehlermeldung. Wenn ich in der gleichen DB vorher in Schild2 ein Passwort für den Admin eingebe, funktioniert alles reibungslos.

**Comment by JuergenRichter** [comment]
Das ist merkwürdig, ich habe in den meisten Testdatenbanken auch nur einen Benutzer "Admin" ohne Kennwort. Daher wäre es schon hilfreich, mal eine solche MDB zu bekommen, um das nachspielen zu können.

**Comment by AnneSchueller** [comment]
@mueller-falko 
Weißt du noch, welche DB das war? War die in unserer Cloud?

**Comment by mueller-falko** [comment]
Es war keine DB aus der Cloud, sondern eine, die ich selbst anonymisiert hatte. Ich kann den Fehler aber jetzt nicht mehr reproduzieren. Möglicherweise hatte ich da noch das alte Anonymisierungstool benutzt oder die DB war aus anderen Gründen defekt.

**Comment by Raffenberg** [comment]
Das Anonymisierungstool entfernt zwar alle Benutzer und hinterlässt nur den Admin und entfernt auch dessen Kennwort, es bleibt allerdings der Kennworthash in der Datenbank, der ich immer manuell raus löschen muss. Dies verhindert bei mir bei einer anonymisierten Datenbank auch in Schild 2 die Anmeldung ohne Kennwort. Vielleicht liegt das Problem ja genau hier.
