### ISSUE TITLE
Voreinstellung der Standardsortierung der SuS (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by JKleine-svws** [SVWS-NRW/Schild3-BetaTest#1157]
Ich wurde datauf aufmerksam gemacht, das bei der Neuinstallation von Schild 3 - wie übrigens bei Schild 2 auch - die voreingestellte Sortierreihenfolge für dire SuS "Klasse - Name" ist. Erst durch Klicken des Buttons "Standard-Sortierung wählen" wird die Sortierung zu "Klasse - Name - Vorname".
Die so gewählte Sortierung wird auch nicht in der Datenbank, sondern in der Registry des gerade benutzten Computers hinterlegt (bin auch nicht ich drauf gekommen, sondern hat mir ein schlauer Mensch zugeschickt):
Computer\HKEY_CURRENT_USER\Software\Schild3000\Sortierung
Computer\HKEY_CURRENT_USER\Software\Schild3000\SortierungText
Das bedeutet, dass z.B. in einem Server-Terminal-System JEDER Nutzer an JEDEM benutzten Rechner die Sortierung "Klasse - Name - Vorname" wieder neu herstellen muss - ist zwar nur ein Klick, bei weniger affinen Nutzern ist das aber eine Fehlerquelle.
Ich glaube, die Kolleg:innen kennen die Listen mit nachnamensgleichen SuS einer Klasse, die ständig in unterschiedlicher Reihenfolge auftauchen. ;-) Und tatsächlich wissen viele User nicht, wie sie das hinkriegen.
Wäre es nicht möglich, die Standard-Einstellung von vorneherein auf "Klasse - Name - Vorname" zu setzen?
![grafik](https://github.com/user-attachments/assets/f29cab75-2801-4bca-8e21-8ac5f817fb53)

**Comment by kroerig** [comment]
Wenn man die Einstellungen in der Registry kennt, kann man sie ja per Gruppenrichtlinie verteilen.

**Comment by AnneSchueller** [comment]
m.E. könnte die Standardsortierung um den Vornamen ergänzt werden.

**Comment by JuergenRichter** [comment]
Ja, da werden ja auch schon andere Einstellungen gespeichert. Es handelt sich um die Tabelle "client_configuration_benutzer", die wird über Funktionen des SVWS-Servers angesprochen (wie die genau heißen, müsste ich nachschauen).

**Comment by AnneSchueller** [comment]
Wenn es den SVWS-Client nicht stört, wäre es wahrscheinlich sinnvoll, die Einstellung hier zu speichern und die Standardeinstellung auf 
Klasse,Name,Vorname zu setzen

**Comment by Raffenberg** [comment]
Könnte man dann nicht generell eher weg von Registryeinträgen hin zu benutzerindividuellen Datenbankeinträge , dort wo es möglich ist? Oder geht das nur für Elemente, die in Schild und den SVWS Server genutzt werden?

**Comment by kroerig** [comment]
Wobei Registry-Werte den Vorteil haben, dass man sie global verteilen und damit Einstellungen "erzwingen" bzw. dafür sorgen kann, dass Änderungen nicht lange Bestand haben. Das hilft ungemein für alle Benutzer einheitliche Einstellungen zu haben und sucht nicht ewig, warum das bei dem einen so ist und bei einem anderen Benutzer so.

**Comment by JKleine-svws** [comment]
Vielleicht nochmal der Hinweis, dass es unabhängig von der Art der Umsetzung (Datenbank oder Registry) die Standardeinstellung der Sortierung bereits bei der Installation "Klasse - Name - Vorname" sein sollte - aus dem Alltag weiß ich, dass das nicht alle Benutzer hinbekommen und auch nicht alle Schulen in der Lage sind, die Registry entsprechend für alle Nutzer zu ändern.

**Comment by JuergenRichter** [comment]
> Vielleicht nochmal der Hinweis, dass es unabhängig von der Art der Umsetzung (Datenbank oder Registry) die Standardeinstellung der Sortierung bereits bei der Installation "Klasse - Name - Vorname" sein sollte - aus dem Alltag weiß ich, dass das nicht alle Benutzer hinbekommen und auch nicht alle Schulen in der Lage sind, die Registry entsprechend für alle Nutzer zu ändern.

So wird es auch sein.

**Comment by JuergenRichter** [comment]
> Könnte man dann nicht generell eher weg von Registryeinträgen hin zu benutzerindividuellen Datenbankeinträge , dort wo es möglich ist? Oder geht das nur für Elemente, die in Schild und den SVWS Server genutzt werden?

Das hängt vom Einzelfall ab. Einstellungen, die von bestimmten Eigenschaften des jeweiligen Rechners abhängen (z.B. Spaltenbreiten in den Tabellendarstellungen) sollten m.E. auch weiter in der Registry gespeichert werden, Einstellungen, die davon unabhängig sind (z.B. die Sortierung der Schülerliste) können in der Datenbank verwaltet werden.

**Comment by JuergenRichter** [comment]
Die Schüler-Sortierung wird nun in der Datenbank gespeichert
