### ISSUE TITLE
Übernahme der Erzieherdaten bei vollj. Schülern bei Nutzung des Rufnamens

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#1158]
Bei vollj. Schülern wird bei den Erzieherdaten der Schüler automatisch angelegt. Dieses ist natürlich wünschenswert ;) Allerdings wird nur der Rufname übertragen. Wir würden gerne das Feld "Alle Vornamen" als Vornamen in die Adresse übernehmen. So ist eine korrekte Zustellung der Post garantiert. Möglich wäre auch eine Auswahloption in Schild (bzw. auch im SVWS-Server), damit die Schulen flexibler agieren können.

**Comment by Raffenberg** [comment]
Ich würde dies unterstützen, da der Rufname ggf. von den offiziellen Vornamen abweichen kann.

**Comment by JuergenRichter** [comment]
Das Programm geht nun wie folgt vor:

- Prüft, ob weitere Vornamen vorhanden sind
- Wenn ja: Kommt der Rufname darin vor?
- Wenn ja: Es werden nur die weiteren Vornamen verwendet
- Wenn nein: Es wird der Rufname mit den weiteren Vornamen verbunden
