### ISSUE TITLE
Update prüfen: Fehlermeldung

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#116]
Bei Klick auf "Hilfe" und anschließend "Update prüfen" erfolgt eine Fehlermeldung:
![2021-03-18 14_43_09-Error occurred](https://user-images.githubusercontent.com/27292550/111636621-f2cb9700-87f8-11eb-8e81-afe1e6ddc9d1.png).
SchILD 3.0 kann anschließend nur noch neu gestartet werden (Restart)

**Comment by FPfotenhauer** [comment]
Ja. In der Alpha-Phase stehen die Dateien zum Update ja auch noch gar nicht zur Verfügung.

@Herrn Richter:
Wir könnten das natürlich einrichten, dann könnte man sogar einfach auf "Update" klicken.
Sollen wir das schon machen?

**Comment by hagege** [comment]
ah, ok

**Comment by JuergenRichter** [comment]
Vorschlag: Ich werde das erst mal "abklemmen"
