### ISSUE TITLE
Zeugnisvorlagen zuordnen

### ISSUE THREAD

**Issue by jwae** [SVWS-NRW/Schild3-BetaTest#1160]
Eine Möglichkeit den SuS eine bestimmte Zeugnisvorlage zuzuordnen fände ich gut. Und zwar mit Hilfe der Gruppenprozesse:
1. SuS Gruppe filtern + Zeugnisvorlage (= ein bestimmter Zeugnisreport) zuweisen
   Damit weise ich 90% meiner SuS ein bestimmte vorlage zu. Die anderen 10 % trage ich evtl. per Hand ein, weil es Spezialfälle sind.
2. Dazu muss es auch einen Gruppenprozess zum Löschen der Zeugnisvorlage geben.
3. Außerdem ein Filter nach Zeugnisvorlage (Teil des Dateinamens).
4. Und ein Gruppenprozess "Zugeordnete Zeugnisse drucken".

Im Feld Zeugnisvorlage (je Abschnitt) muss der Pfad und die Zeugnisdatei zu sehen sein.

Die Variante aus Schild 2, die nach Abschlussart + Jg. funktionierte bei uns nicht wirklich. Zu viele verschiedene Abschlussarten und Zeugnisvarianten waren vorhanden. Hj-Zeugnisse konnten damit nicht gedruckt weden.
Bsp.:  SuS im RS / HS -Bildungsgang,  SuS in EF oder mit Förderbedarf und/oder zieldifferent

**Comment by AnneSchueller** [comment]
Welche Einstellungsmöglichkeit fehlt denn bei der Zuordnung der Zeugnisvorlage, damit es auch für die genannten Fällt funktioniert?
Ich würde hier nicht von dem aktuellen Workflow abweichen.

**Comment by JuergenRichter** [comment]
Hierzu wären auch Änderungen in der Datenbankstruktur notwendig (irgendwo muss ja der Pfad zur Zeugnisvorlage gespeichert werden).

**Comment by jwae** [comment]
Es ist ja nur ein Wunsch / Idee:
Aktuell kann ich je nach Jg., Abschlussart und Abschluss eine Zeugnisvorlage zuweisen:
![05](https://github.com/user-attachments/assets/3335462e-406d-4d35-9b64-ddc39cbc83fb)
Nachteil: 
- Selbst an einer RS mit HS-Bildungsgang und Inklusion habe ich viele verscheidene Abschlüsse und Varianten -> wir nutzen es nicht
- Beim Druck werden die Zeugnisse nach Abschluss sortiert ( Ich habe dann 12x FOR, 10xHS, 3 x Ohne). Diese muss ich dann wieder alphabetisch sortieren, weil:
- die KL müssen prüfen 
- die Kinder auf der Abschlußfeier nach dem Alphabet aufgerufen weden

Ich stelle mir das ganze Proceder einfacher vor:
- Ich weise, über einen Gruppenprozess oder per Hand, jedem Kind eine passende Zeugnisdatei zu.
- Diese wird im Gruppenprozess "Zeugnisdruck" automatisch verwendet  und gedruckt.
- Es wird ein neues DB-Feld benötigt
- Wenn dieses Feld im Abschnitt des Kindes gespeichert wird, dann weiß ich bei einem Nachdruck u.a. auch nach Jahren, welches Formular für das Abschlusszeugnis damals verwendet wurde.

**Comment by AnneSchueller** [comment]
Wenn man die Regeln (Prüfungsordnung, Abschluss...) korrekt bei den Zeugnisvorlagen hinterlegt und korrekt bei den Schülern einträgt, werden diese doch automatisch zugeordnet und dann auch alphabetisch ausgedruckt.
Ich würde den Workflow so belassen. Ich schiebe das Issue mal in die Diskussion.
