### ISSUE TITLE
Darstellungs- und Bearbeitungsproblem Gliderungsbezogene Einstellungen

### ISSUE THREAD

**Issue by JTorspecken** [SVWS-NRW/Schild3-BetaTest#1161]
![grafik](https://github.com/user-attachments/assets/9d3ec12a-b2d1-4097-9686-bfcc720bc4de)
Bei den gliederugnsbezogenen Einstellungen der Fächer wird die Fächergruppe nur als Zahl angezeigt und aknn nicht bearbeitet oder ausgewählt werden..
Änderungen und Ergänzungen der Liste werden nicht gespeichert.

Getestet nach "frischer" Migration mit den Versionen vom 18.10.24

**Comment by JuergenRichter** [comment]
Behoben
