### ISSUE TITLE
Leistungsdaten Zuweisung Kurs

### ISSUE THREAD

**Issue by SebSchraufBRA** [SVWS-NRW/Schild3-BetaTest#1162]
Bei der Kurszuweisung für einen Schüler unter Akt. Halbjahr -> Leistungsdaten wird in der Auswahltabelle der Kursleiter nicht angezeigt. Bei Übernehmen des Kurses wird er letztlich aber richtig eingetragen.

![Bug_1](https://github.com/user-attachments/assets/f0ae38f6-7ed1-4775-bc76-b8f2d50b7d63)

**Comment by JuergenRichter** [comment]
Behoben
