### ISSUE TITLE
Filter Klassenart

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1164]
Gibt es keinen Filter nach Klassenart? Finde ich ihn nur nicht?
Wird benötigt z.B. zum Filtern von Regelklasse vs Deutschförderung vs Profilklasse (z.B. u.a. Sportschulen...)

**Comment by AnneSchueller** [comment]
In Schild2 war der unter Filter I Lernabschnitt...
Ich finde ihn auch nicht.

**Comment by JuergenRichter** [comment]
Ist jetzt vorhanden:
![image](https://github.com/user-attachments/assets/9e07dccb-842b-4af7-b41e-920c29e93ba2)
