### ISSUE TITLE
Noteneingabe im Gruppenprozess: NB, NE etc. nicht vorgesehen

### ISSUE THREAD

**Issue by JKleine-svws** [SVWS-NRW/Schild3-BetaTest#1165]
Ist es Absicht, dass bei der Noteneingabe über den Gruppenprozess die Notenstufen, nicht aber - wie bei den Leistungsdaten - die Kommentierungen, also AM, AT, NB usw. zu Auswahl stehen und eingegeben werden können?

Gruppenprozess:
![grafik](https://github.com/user-attachments/assets/76d11aa6-2005-40f9-b1c8-6dccc8986e98)
Leistungsdaten:
![grafik](https://github.com/user-attachments/assets/4dc73253-9c83-4d95-9f24-50fd37237dc8)

**Comment by AnneSchueller** [comment]
Das sollte auch mit dem GP möglich sein.

**Comment by JuergenRichter** [comment]
Ist keine Absicht, wird korrigiert

**Comment by JuergenRichter** [comment]
Ist behoben
