### ISSUE TITLE
Fehler bei Statistik für it.nrw (Hilfe bei Problemen)

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#117]
Bei Klick auf Statistik für IT.NRW  > Hilfe bei Problemen und Klick auf den Button "Dateien registrieren" erscheint die folgende Fehlermeldung mit mehreren Fehlerfenstern:
![2021-03-18 14_53_23-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2019_2020, 2  Hj, Ben](https://user-images.githubusercontent.com/27292550/111637772-09beb900-87fa-11eb-889f-81d830385880.png)

**Comment by JuergenRichter** [comment]
Sollte in 3.0.13.3 behoben sein. Es wird nun ein anderes Verfahren verwendet, um festzustellen, ob der Benutzer tatsächlich Admin-Berechtigungen hat. Bei dem bisherigen Verfahren hat das nicht immer korrekt funktioniert.
