### ISSUE TITLE
Schüler - Vermerke - Eingabe des Datums

### ISSUE THREAD

**Issue by SebSchraufBRA** [SVWS-NRW/Schild3-BetaTest#1170]
Bei Anlage eines neuen Vermerks wird bei Eingabe des Datums (unter Windows 10) zusätzlich die Uhrzeit mit abgefragt. Das ist wohl nicht beabsichtigt und führt auch zu einem Fehler, wenn eine andere Uhrzeit als 0:00 Uhr ausgewählt wird.
![Bug_4](https://github.com/user-attachments/assets/6600cb35-3bcf-4745-a8e3-2afd3312a6ad)
![Bug_5](https://github.com/user-attachments/assets/71dcc534-5861-4644-b68f-724cf7be3e80)
[Fehlerdetails.txt](https://github.com/user-attachments/files/17745985/Fehlerdetails.txt)

**Comment by AnneSchueller** [comment]
@JuergenRichter: Kann man die Uhrzeitabfrage ausschalten wie bei den Abfragen des Datums auf der Individualseite?

**Comment by JuergenRichter** [comment]
Dürfte kein Problem sein

**Comment by JuergenRichter** [comment]
Behoben, gilt für alle Datumseingaben
