### ISSUE TITLE
Schüler - Erziehungsberechtigte - Darstellung der Adresse

### ISSUE THREAD

**Issue by SebSchraufBRA** [SVWS-NRW/Schild3-BetaTest#1171]
Vielleicht nur eine kosmetische Sache: In SchILD3 sind ja nun Straße und Hausnummer getrennt. Bei der Auflistung der Erziehungsberechtigten scheint die Hausnummer nicht übernommen zu werden.
![Bug_3](https://github.com/user-attachments/assets/4fbbf7e1-a5f9-4a89-9baa-efafe9658023)

**Comment by JuergenRichter** [comment]
Behoben
