### ISSUE TITLE
Zusätzliche Felder in Lehrer-Kontaktdaten

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/Schild3-BetaTest#1173]
Guten Abend,

in den Lehrer-Basisdaten -> Kontaktdaten gibt es nur die Möglichkeit, eine Festnetz und eine Mobilfunknummer anzugeben. Aus diesem Grund wurden bisland diverse andere Felder in den Individualdaten missbraucht, um weitere Kontaktinformationen abzuspeichern - z.B. Fax (ja, tatsächlich...) oder in Sonderfällen eine ausländische Festnetznummer, da die Kollegin zwischen ihrer Wohnung am Dienstort und ihrer Familie im Ausland pendelt. 

Ich bitte daher die Möglichkeit, weitere Felder mit Kontaktdaten zu ergänzen. Einen Widerspruch zur VO-DV II sehe ich hier nicht, da hier für im Abschnitt "Erreichbarkeit privat: Anschrift Wohnsitz, Anschrift Postzustellung, Telefon, Fax*, E-Mail*" keine Beschränkung der Anzahl der Telefonnummern gegeben ist.

**Comment by AnneSchueller** [comment]
Anpassungen folgen später
