### ISSUE TITLE
Leistungsdaten funktionsbezogen ändern fehlerhaft

### ISSUE THREAD

**Issue by mueller-falko** [SVWS-NRW/Schild3-BetaTest#1174]
Wenn bei einem User nur die Berechtigung "Schüler Leistungsdaten funktionsbezogen ändern" eingestellt ist, kann dieser User trotzdem im aktuellen Abschnitt alle Noten bei allen Schülern eingeben und ändern.

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren.
Anpassungen für die Benutzergruppen werden aber korrekt im SVWS übertragen.
Dort funktioniert die Einstellung

**Comment by JuergenRichter** [comment]
Prüfe ich

**Comment by JuergenRichter** [comment]
Behoben
