### ISSUE TITLE
Excel-Export TSO

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1175]
Einige Schulen benötigen für die Schulentwicklungsplanung die Info des TSO, der in der jeweiligen Klasse des Schülers hinterlegt ist.
Könnte dies mit in den Excelexport übernommen werden?

**Comment by JuergenRichter** [comment]
Ich stelle den SQL-Befehl zusammen

**Comment by JuergenRichter** [comment]
Folgende Angaben müssten beim SVWS-Server hinzugefügte werden:
DatenartKrz: Schueler
Feldname: ID
AnzeigeText: Teilstandort
Feldtyp: S
LookupFeldname: AdrMerkmal
LookupSQLText: SELECT K.AdrMerkmal FROM SchuelerLernabschnittsdaten LA, Schueler S, Klassen K WHERE S.ID=% and LA.Schueler_ID=S.ID AND LA.Schuljahresabschnitts_ID=S.Schuljahresabschnitts_ID and LA.WechselNr=0 AND K.ID=LA.Klassen_ID

**Comment by AnneSchueller** [comment]
Der Export funktioniert. Die Ergänzung ist im nächsten Update vom SVWS-Server verfügbar.
