### ISSUE TITLE
svws-Client: Kurse bearbeiten - Auswahl eines Jahrgangsstufe

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1178]
Hallo zusammen,

in Schild3 habe ich einen Kurs für die EF angelegt.
Im svws-Client ist bei diesem jedoch die Jahrgangsstufe 05 zugeordnet.
Als ich das ändern wollte im Client, kam folgende Meldung, egal welchen Jahrgang ich auswählen wollte:
![grafik](https://github.com/user-attachments/assets/2c6578e2-7312-4650-ac2d-dee05fd86cd9)

Der Kurs taucht nun in Schild3 aber gar nicht mehr auf.

Kann man da was machen?

Generell wird bei allen Kursen immer der Jahrgang 05 angezeigt.
LG
Raphael

**Comment by AnneSchueller** [comment]
Ich kann das reproduzieren. Ich vermute, dass dies im SVWS-Client korrigiert werden muss. Ich leite das entsprechend weiter.
