### ISSUE TITLE
Bei Plugins werden (z. Zt. noch?) keine Plugins gezeigt

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#118]
Bei Einstellungen > Plugins werden (z. Zt. noch?) keine Plugins gezeigt, insofern ist die Meldung zur Auswahl der Plugins irritierend:
![2021-03-18 15_09_01-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2020_2021, 1  Hj, Ben](https://user-images.githubusercontent.com/27292550/111640290-586d5280-87fc-11eb-9afd-d646693224d5.png)

**Comment by FPfotenhauer** [comment]
Bei mir werden jetzt PlugIns angezeigt.
Der LogineoExport sollte dort entfernt werden.

Insgesamt stellt sich die Frage, ob man nicht von den PlugIns weg geht?
Ich hatte das vor vielen Jahren sogar schon mal beauftragt.

**Comment by FPfotenhauer** [comment]
PlugIns wird es zukünftig nicht mehr geben.
Die DLLs werden in das Programm integriert.
Die Steuerung der Sichbarkeit wird unter "Ansicht" erfolgen....
