### ISSUE TITLE
Verzeichnisse Datensicherung Connection-Files werden nicht angelegt.

### ISSUE THREAD

**Issue by S-Schiffelmann** [SVWS-NRW/Schild3-BetaTest#1181]
Bei der Installation von Schild 3.0 muss ich die Verzeichnisse Connection-Files und Sicherungen per Hand anlegen.
Dann läuft Schild 3.0 zunächst stabil, lediglich beim Versuch die Datenbank zu sichern erscheint die Fehlermeldung: "kein Zugriff auf eine sqlite-Datei."
Ich habe verschiedene Installationen ausprobiert, einmal habe ich MariaDB komplett mitinstallieren lassen, einmal eine bereits bestehende MariaDB-Installation integriert. Bei beiden Versuchen das gleiche Ergebnis.
![Fehlermeldung sqlite](https://github.com/user-attachments/assets/f4d5ddc9-3ba7-42a1-8498-534aaf15c823)

**Comment by FPfotenhauer** [comment]
Der Ordner Programme(x86) ist ein SystemOrdner und benötigt Admin Rechte. Die hat Schild3 aber zur Laufzeit nicht.

**Comment by kroerig** [comment]
Da muss aber schon bei der Installation was schiefgelaufen sein, denn der Installer schlägt als Arbeitsverzeichnis `C:\SVWS-Arbeitsverzeichnis` vor.
