### ISSUE TITLE
SVWS-Client Oberstufe-Kursplanung: Synchronisieren nicht auswählber 

### ISSUE THREAD

**Issue by S-Schiffelmann** [SVWS-NRW/Schild3-BetaTest#1182]
Ich habe aus dem aktuellen Halbjahr der Q2 im SVWS-Client Bereich Oberstufe/ Kursplanung "Erstellung einer Blockung aus der Persistierung der Leistungsdaten" gewählt. Die Daten werden korrekt gelaqden und die Blockung wird dargestellt (s. Foto).
Auch nach Verschiebung eines Kurses in ein anderes Rasters oder nach Verschiebung eines einzelnen Schülers in einen anderen Kurs bleibt der Button "Synchronieren" nicht anwählbar.
![Client 1](https://github.com/user-attachments/assets/888d7f85-e5a8-4633-8d0d-1984bfb7edfd)

**Comment by AnneSchueller** [comment]
Eine Synchronisation ist nur möglich, solange noch keine Leistungsdaten hinterlegt sind.
