### ISSUE TITLE
Schüler - Weitere Adressen - Neue Adresse - Filter Namenssuche ist case sensitive

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1185]
Hallo zusammen,

wie der Titel schon sagt:
Schüler - Weitere Adressen - Neue Adresse - Filter Namenssuche ist case sensitive.
Kann hier eine Suche ohne Groß-/Kleinschreibung erfolgen? Z.B. haben wir eine Firma "GIRA ...", da gibt man natürlich nur "Gira" ein.

LG
Raphael

**Comment by JuergenRichter** [comment]
Auf welchem Betriebssytem läuft der MariaDB-Server?
Unter Windows ist die Suche nicht case-sensitive:
![image](https://github.com/user-attachments/assets/ac8faeba-170e-461f-a62e-5c2e4ba5d8cd)

**Comment by JuergenRichter** [comment]
Sorry, habe gerade gesehen, dass es um die Betriebssuche geht.

**Comment by JuergenRichter** [comment]
Bei der Betriebssuche werden jetzt die Abfragebefehle wie folgt formuliert:
LOWER(<Feldname>) LIKE "%' + LowerCase( <Eingabe> ) + '"%'

**Comment by JuergenRichter** [comment]
Bei der Schülersuche ist das schon so umgesetzt, sofern das Häkchen bei "Groß-Kleinschreibung ignorieren" gesetzt ist.
![image](https://github.com/user-attachments/assets/f6eeac6c-8395-419d-acd4-796ee287e3cf)
