### ISSUE TITLE
Fehlerhafte Zeichenkodierung im Installer

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#1188]
Ist zwar nur Optik, sieht aber dennoch merkwürdig aus:
![grafik](https://github.com/user-attachments/assets/9f4d3865-bb2f-4fa0-a0d2-7f8c1cf1696d)

**Comment by JuergenRichter** [comment]
Der Installer ist aber nicht meine "Baustelle".

**Comment by FPfotenhauer** [comment]
Bei mir sind aber alle Zeichen korrekt kodiert.
Wie alt ist denn der Installer? Das hatten wir vor ewigen Zeiten schon mal, wurde aber abgestellt.

**Comment by kroerig** [comment]
Das ist aktuelle Version von Github.
