### ISSUE TITLE
Text abgeschnitten

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#1189]
In der Standardfenstergröße ist der Text abgeschnitten:
![grafik](https://github.com/user-attachments/assets/fab02a6d-dfa1-454b-8112-c0b3dae767ef)

**Comment by AnneSchueller** [comment]
Das müsste anfangs einmal händisch angepasst werden. Die Einstellung bleibt dann auch nach Updates erhalten.

**Comment by kroerig** [comment]
äh, nein.
Das muss im Default so gestaltet sein, dass es passt.
