### ISSUE TITLE
Fehler bei Erfassung eines neuen Schülers

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#119]
Bei Erfassung eines neuen Schülers erscheint die folgende Fehlermeldung nach Klick auf "Übernehmen" - der Schüler wurde aber trotz des Fehlers gespeichert:
![2021-03-18 15_26_12-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2020_2021, 1  Hj, Ben](https://user-images.githubusercontent.com/27292550/111642528-750a8a00-87fe-11eb-86c8-c355030ab39e.png)

Danach fehlen allerdings Reiter wie z. B. "Akt. Halbjahr", etc.:
![2021-03-18 15_38_30-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2020_2021, 1  Hj, Ben](https://user-images.githubusercontent.com/27292550/111644406-18a86a00-8800-11eb-9a14-4efda47c9242.png)

**Comment by hagege** [comment]
Sorry, der Fehler mit den fehlenden Register hat sich erledigt: Ich hatte übersehen, dass ich den Status noch nicht auf "Aktiv" geändert hatte.

**Comment by JuergenRichter** [comment]
Den Fehler "Operation bei geschlossener Datenmenge..." kann ich nicht reproduzieren. Bitte mal das Fehlerprotokoll zur Verfügung stellen:
-Copy to Clipboard aktivieren
-Schater "Details" anklicken
-Inhalt der Zwischenablage hier einfügen oder als Datei anhängen

**Comment by FPfotenhauer** [comment]
Wenn hier keine weitere Rückmeldung erfolgt, würde ich das Ticket gerne schließen.
