### ISSUE TITLE
Aufruf der Werkzeuge dauert 9 Sekunden

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#1193]
Schild 3.1.0 + SVWS-Server 1.0.0: Mir ist aufgefallen, dass es ca. 9 Sekunden dauert, die Werkzeuge unter Verwaltung zu starten, wenn ich vorher auf Verwaltung/Einstellungen war. Für mein Gefühl dauert das viel zu lange.

**Comment by JuergenRichter** [comment]
Beim Verlassen der Einstellungen werden diese gespeichert (über Funktionen des SVWS-Servers). Das dürfte wohl die Ursache sein. Man könnte das vermutl. verkürzen, wenn nur Einstellungen gespeichert werden, die auch geändert wurden. Das schaue ich mir an.

**Comment by JeVaske** [comment]
@AnneSchueller: Tatsächlich, Hauke beschreibt dieselbe Klickreihenfolge. Der Server ist lokal auf meinem Notebook (16,0 GB RAM, i5) installiert.

**Comment by JuergenRichter** [comment]
Das 

> @JeVaske : Wo liegt denn der SVWS-Server?
> 
> Das Problem geht sicherlich auch hiermit einher: #1100

Das sind aber ganz verschiedene Situationen. Bei dem hier beschriebenen Problem liegt es mit großer Wahrscheinlichkeit am Speichervorgang in die Tabellen "client_konfiguration_global" und "client_konfiguration_benutzer" über entsprechende Funktionen des SVWS-Servers. Ich werde da mal intern die Zeit stoppen. Bei dem Issue #1100 ist der SVWS-Server derzeit aber gar nicht involviert.

**Comment by JuergenRichter** [comment]
Man könnte das dauerhafte Speichern beim Schließen des Einstellungsfensters auch deaktivieren und erst beim Programmende durchführen, dann dauert das halt etwas länger.

**Comment by JuergenRichter** [comment]
Nein, die Änderungen sind sofort wirksam, nur die Speicherung erfolgt am Ende (was natürlich bedeutet, dass bei einem Programmabsturz oder Systemausfall, die zwischen Änderung und Beendigung des Programmes stattfinden, die Änderungen verloren sind).

**Comment by JuergenRichter** [comment]
> dass es ca. 9 Sekunden dauert, die Werkzeuge unter Verwaltung zu starten, wenn ich vorher auf Verwaltung/Einstellungen war

Ich habe jetzt mal das Speichern wie beschrieben deaktiviert. Nun geht das natürlich deutlich schneller. Bei Beendigung erscheint der Hinweis "Einstellungen werden gespeichert..."
