### ISSUE TITLE
Schüler -> Weitere Adressen -> Rechtschreibfehler bei "Beschäftigung" im Feld: "Beschäfigungsart" statt "Beschäftigungsart"

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1194]
Hallo zusammen,

der Titel sagt es schon:
Schüler -> Weitere Adressen -> Rechtschreibfehler bei "Beschäftigung" im Feld: "Beschäfigungsart" statt "Beschäftigungsart"
Das Feld taucht nur auf, wenn z.B. "Bietet Praktikumsplätze" bei den Katalogen "Allgemeine Adressen" bei dem Betrieb angehakt ist.
Hier ein Screenshot: Feld unten rechts
![grafik](https://github.com/user-attachments/assets/78fb3dd4-d948-41a2-8fdb-d60db8ee2bb9)

LG
Raphael

**Comment by JuergenRichter** [comment]
Behoben
