### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by kleino23** [SVWS-NRW/Schild3-BetaTest#1195]
Hallo zusammen,  

nach der Installation, sowie Migration der DB bekommen wir immer folgende FM:

#42S02Table 'svwsdb.v_benutzerdetails' doesn't exist.

**Comment by FPfotenhauer** [comment]
Mit welchem Tool wurde denn migriert?
Mit dem SVWS-Server-Installer?

Die Logs liegen unter ProgrammData/SVWS-Server/logs.
Wenn es eine Windows-Installation ist.

Läuft der Web-Client?

**Comment by AnneSchueller** [comment]
Vor kurzem hatte ich genau die gleiche Fehlermeldung. Es stellte sich heraus, dass die Access-Schild2 Datenbank kaputt war und vor der Migration repariert werden musste.

@kleino23: Hier kann evtl. Ihr Fachberater helfen und die Datenbank diesbezüglich sichten. Alternativ könnte ich Ihnen einen Uploadlink per Mail zukommen lassen.

**Comment by kleino23** [comment]
Hallo,

vielen Dank für die Info.
Laut den Logs liegt es auch an der alten DB. Wir werden die alte DB jetzt reparieren und es erneut testen.

Von: AnneSchueller ***@***.***>
Gesendet: Mittwoch, 20. November 2024 16:09
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Klein, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Fehlermeldung (Issue #1195)


Vor kurzem hatte ich genau die gleiche Fehlermeldung. Es stellte sich heraus, dass die Access-Schild2 Datenbank kaputt war und vor der Migration repariert werden musste.

@kleino23<https://github.com/kleino23>: Hier kann evtl. Ihr Fachberater helfen und die Datenbank diesbezüglich sichten. Alternativ könnte ich Ihnen einen Uploadlink per Mail zukommen lassen.

**Comment by kleino23** [comment]
Hallo,

vielen Dank für die Info.
Laut den Logs liegt es auch an der alten DB. Wir werden die alte DB jetzt reparieren und es erneut testen.

Von: Frank Pfotenhauer ***@***.***>
Gesendet: Mittwoch, 20. November 2024 14:54
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Klein, Oliver ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Fehlermeldung (Issue #1195)


Mit welchem Tool wurde denn migriert?
Mit dem SVWS-Server-Installer?

Die Logs liegen unter ProgrammData/SVWS-Server/logs.
Wenn es eine Windows-Installation ist.

Läuft der Web-Client?

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue vorerst. Sollte es nach der DB-Reparatur nach wie vor zu Problemen kommen, dann gerne nochmal melden.

**Comment by kleino23** [comment]
Alles klar, so machen wir das.

Von: AnneSchueller ***@***.***>
Gesendet: Freitag, 22. November 2024 11:20
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Klein, Oliver ***@***.***>; Mention ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Fehlermeldung (Issue #1195)


Dann schließe ich das Issue vorerst. Sollte es nach der DB-Reparatur nach wie vor zu Problemen kommen, dann gerne nochmal melden.
