### ISSUE TITLE
Organisationsform nicht sichtbar oder nicht migriert

### ISSUE THREAD

**Issue by JTorspecken** [SVWS-NRW/Schild3-BetaTest#1196]
Zumindest beim BK ist das Feld "Organisationsform" weder bei Individualdaten I noch im Akt. Halbj. mit Inhalt gefüllt, obwohl dies in der Original-DB (SchILD2) drin ist.

**Comment by JTorspecken** [comment]
Im SVWS-Server ist die Organisationsform gefüllt (im Akt. Halbj.). Es scheint also ein Darstellungsproblem zu sein.

**Comment by AnneSchueller** [comment]
Ergänzung: Auch das Nachtragen in den Klassentabellen und anschließendes "bei Schülerdaten übernehmen" hat keine Auswirkungen für die Organisationsform beim jeweiligen Schüler

**Comment by JuergenRichter** [comment]
Da hat es eine "Begriffsverwirrung" gegeben. Der SVWS-Server liefert zu den Organisationsformen zwei Informationen: "schluessel" und "kuerzel", diese sind bei allen Schulen außer den BKs gleich, bei den BKs aber unterschiedlich. Das Eingabefeld greift aber derzeit auf "schluessel" zu, was aber bei BKs nicht dem Inhalt des entsprechenden Datenbankfeldes entspricht. Ich habe das nun auf "kuerzel" geändert, nun passt es.
