### ISSUE TITLE
mtblLaender-Fehler beim Starten

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1198]
Ohne hier viele Worte zu verlieren, verweise ich auf diese Forumsbeiträge.

https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=7192

Der Fehler ist damit mehrfach unabhängig voneinander aufgetreten.

**Comment by JeVaske** [comment]
![grafik](https://github.com/user-attachments/assets/ba60f1e3-cb9f-4f1f-8225-836cf9b2d46e)
Mir ist das auch gerade aufgefallen. Ich habe Schild (3.1.0) mit dem passenden SVWS-Server (1.0.0) in der Schule im Netzwerk installiert. Wenn ich mich bei einem Client als Admin anmelde, funktioniert alles. Wenn ich mich als Lehrer mit geringen Rechten anmelde, kommt die Meldung.

**Comment by AnneSchueller** [comment]
Seltsam ist aber, dass @JeVaske sich auf dem gleichen Rechner einmal als Admin anmelden kann aber als Lehrer nicht (oder habe ich das falsch verstanden?) 
Da wird doch die gleich con-Datei mit den gleichen Verbindungsinfos aufgerufen.

**Comment by JuergenRichter** [comment]
>  einmal als Admin anmelden kann aber als Lehrer nicht 
Mit dem gleichen Systembenutzer?

**Comment by JeVaske** [comment]
Ich hatte mich auf dem Rechner eines Kollegen bei Schild mit meinem Admin-Zugang angemeldet und alles hat funktioniert. Als mein Kollege sich bei Schild mit dem Lehrer-Account (eingeschränkte Rechte) angemeldet hat, kam die Fehlermeldung. In beiden Fällen haben wir denselben Systembenutzer verwendet.

**Comment by FPfotenhauer** [comment]
Es liegt an der Berechtigung "Katalogeinträge ansehen".
Wenn das nicht gesetzt ist, dann verweigert der SVWS-Server den Zugriff.

Das macht natürlich wenig Sinn, dass Schild3 dann nicht starten kann.
Das gleiche gilt für den SVWS-Server.

Ich mache dafür im SVWS-Server ein Issue auf.
