### ISSUE TITLE
FHR-Algorithmus funktioniert nicht

### ISSUE THREAD

**Issue by Gerritzma** [SVWS-NRW/Schild3-BetaTest#12]
Die FHR-Berechnung funktioniert nicht. Hier bei einer Schülerin mit fast durchgängig zweistelligen Punktzahlen und keiner Wiederholung. 
![FHR-Berechnungfalsch](https://user-images.githubusercontent.com/75031535/100252868-ad7d1400-2f40-11eb-9ac4-416c956f1ce4.png)

Ich habe das bei anderen getestet, welche von Schild2 noch richtig berechnet waren. Der FHR-Algorithmus spuckt auch da aus, dass die FHR nicht erreicht wurde.

Zudem:  Schreibfehler in der Ausgabe in Zeile 3: ermit**T**eln

**Comment by JuergenRichter** [comment]
Ist behoben.

**Comment by FPfotenhauer** [comment]
Bitte in Version 3.0.6 einmal testen und ggf. das Issue schließen.

**Comment by WLey-49** [comment]
Es scheint zu funktionieren, aber ich kann bei Wiederholern nicht testen, weil die Wertungs-/Wiederholungshaken auf der Karteikarte "Übersicht" nicht gesetzt bzw. geändert werden können.
![Wertungshaken](https://user-images.githubusercontent.com/62895389/100916014-77f2a080-34d5-11eb-9cec-46a53db5cbf8.JPG)

**Comment by Gerritzma** [comment]
@WLey-49 Das Problem hatte ich auch gerade. Das lässt sich im Moment scheinbar nur im aktuellen Abschnitt ändern. Das war früher auch komfortabler.

Ich habe gerade verschiedene Fälle getestet, jetzt scheint es zu funktionieren.

**Comment by JuergenRichter** [comment]
Wir können das in der Übersicht wieder änderbar machen.
