### ISSUE TITLE
Tippfehler bei Gruppenprozesse

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#120]
Tippfehler bei Gruppenprozesse:
![2021-03-18 15_51_27-Aktuelle Datenbank_ GY_2020_21, Schuljahr 2020_2021, 1  Hj , Benutzer_ Admin](https://user-images.githubusercontent.com/27292550/111646484-fc0d3180-8801-11eb-9fbe-807f65a41efd.png)

**Comment by JuergenRichter** [comment]
Erledigt
