### ISSUE TITLE
Anzeige der Adresse unter "Erziehungsberechtigte/Telefonnummern"

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1200]
Hallo zusammen,

unter Schüler - "Erziehungsberechtigte/Telefonnummern" -> "Erziehungsberechtigte" wird Art, Name, Adresse und Anschreiben angezeigt.
Bei der Adresse fehlt jedoch die weiter unten eingetragene Hausnummer. Hier wurde also nur der Straßenname und nicht beides abgerufen, was für die Sekretärinnen hinderlich ist.

Liebe Grüße
Raphael

**Comment by AnneSchueller** [comment]
Hallo Raphael,

Danke für den Hinweis. Im nächsten Update ist das korrigiert. 
LG
