### ISSUE TITLE
BK: Auswahl der Fachklassen auf in der Klasse vorhandene Fachklassen beschränken (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by JKleine-svws** [SVWS-NRW/Schild3-BetaTest#1201]
Bei Berufskollegs ist es mühsam, die SuS einer Klasse auf die zugehörige Fachklasse zu filtern.
In einer Klasse kommen erfahrungsgemäß plus/minus drei verschiedene Fachklassen vor.
Möchte man auf die SuS einer Fachklase filtern, muss man sich durch ein Dropdown-Menü mit allen vorhandenen Fachklassen arbeiten, das sind bis an die hundert, siehe Screenshot. Eine Tastatureingabe der Fachklasse ist nicht möglich. Das war auch schon in Schild2 so.
Es wäre schön, wenn nur die in der Klasse tatsächlich vorhandenen Fachklassen zur Auswahl angeboten würden.
![grafik](https://github.com/user-attachments/assets/b35dcff8-dc97-4316-9dd2-8e1304d8d859)

**Comment by JuergenRichter** [comment]
Umgesetzt
![image](https://github.com/user-attachments/assets/7b6af147-3ff4-4336-847a-d834035ac997)
