### ISSUE TITLE
Fehlermeldung bei Änderungen in Schule -> Allgemeine Angaben

### ISSUE THREAD

**Issue by SebSchraufBRA** [SVWS-NRW/Schild3-BetaTest#1202]
Bei Änderung irgendeines Feldes in den allgemeinen Angaben zur Schule außer Gliederungen und Schulleitung (also die Felder mit Möglichkeit, mit einem Haken zu bestätigen) erscheint die gezeigte Meldung bei Wechsel zu einem anderen Menü.
Übernommen werden die geänderten Angaben aber anscheinend.

![Bug](https://github.com/user-attachments/assets/6defb6ee-9059-4513-a82a-901668a6ca9b)

**Comment by JuergenRichter** [comment]
Behoben
