### ISSUE TITLE
Schulpflicht erfüllt - Prüfung fehlerhaft?

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1205]
Hallo zusammen,

bei der Schulpflicht-Überprüfung haben wir einige 16- oder 17-Jährige, die angeblich die Schulpflicht erfüllt haben. Diese haben gemein, dass sie schon 10 Schulbesuchsjahre haben, da sie einmal eine Klasse wiederholt haben. Aber die Schulpflicht ist ja erst mit der Vollendung des 18. Lebensjahres am Ende des Schuljahres erfüllt, oder?

Liebe Grüße

Raphael

**Comment by AnneSchueller** [comment]
Nach meinen Recherchen gilt die Schulpflicht für die Sek1 als erfüllt, wenn der Schüler 10 Schulbesuchsjahre absolviert hat.
Daher würde ich die Berechnung als korrekt werten.
@Raffenberg Siehst du das anders?

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue mal. Falls hier noch Unstimmigkeiten auftreten, gerne nochmal rückmelden.
