### ISSUE TITLE
Verwaltung -> Import -> Schnittstelle SchILD-NRW -> Schüler: Zusatzdaten -> Fehlermeldung // -> Schüler: Individualdaten und Erzieherdaten: Ortsteile

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1206]
Beim obigen Import tritt folgende Fehlermeldung auf, nachdem der Hinweis auf einen Neustart von SchILD kommt:

![grafik](https://github.com/user-attachments/assets/51c2375b-30ba-4913-b3ae-c7ecc93290ef)

Der Import funktioniert nicht.

LG
Raphael Kemna

**Comment by Raphael-Kemna** [comment]
Ich habe die Datei einzeln importiert, also die "SchuelerZusatzdaten.dat". Ich habe das aber auch mit der zuvor selbst ausgegebenen .dat-Dastei gemacht, also ohne Änderung an der Datei. Oder kann es sein, dass wir einen Falscheintrag im System haben, der an einer Stelle den Import sprengt?

**Comment by Raphael-Kemna** [comment]
Wenn ich das zusammen mit der Basis-Datei importiere, dann erhalte ich zusätzlich 895 Fehler in der Verkehrssprache. Z.B. ist bei einigen Schülern auch Deutsch eingetragen, was in der Basis-Ausgabe dann mit "de" abgekürzt wird und als Fehler angezeigt wird. Gilt aber auch für andere Sprachen:
Schüler-Basisdaten (für ...): Falsche Verkehrssprache (fa) in Zeile 2
Schüler-Basisdaten (für ...): Falsche Verkehrssprache (de) in Zeile 11
Schüler-Basisdaten (für ...): Falsche Verkehrssprache (uk) in Zeile 13
Schüler-Basisdaten (für ...): Falsche Verkehrssprache (de) in Zeile 14
Schüler-Basisdaten (für ...): Falsche Verkehrssprache (ru) in Zeile 19
Schüler-Basisdaten (für ...): Falsche Verkehrssprache (de) in Zeile 25

usw.
Eigenes Issue?
LG

**Comment by Raphael-Kemna** [comment]
Diese Fehlermeldung tritt wirklich nur beim Import der Zusatzdaten auf, obwohl in diesen keine PLZ vorkommt.
Hier noch einmal die direkte Meldung ohne Details:
![grafik](https://github.com/user-attachments/assets/4873baea-a220-4734-8c3c-04d3c3241184)

**Comment by AnneSchueller** [comment]
Das Problem mit der Verkehrssprache hatte ich ebenfalls. 
(Issue ist bereits erstellt: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1207)

Bezüglich der Übernahme der Erzieherdaten bei Änderung der Schüleradresse: Hier muss die Erzieheradresse einmal aktualisiert werden, dann klappt es. Alternativ hilft ein Neustart.

Für den Bug mit den Ortsteilen/Kreis erstelle ich nochmal ein separates Issue.
