### ISSUE TITLE
Import Basisdaten -> Fehlerhafte Verkehrssprache

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1207]
Ein Import der Schülerbasisdaten (unmittelbar nach einem analogen Export) über die Schnittstelle-Schild-NRW führt zu folgender Fehlermeldung:

![image](https://github.com/user-attachments/assets/21dad159-21f0-4bd3-baff-9bf3a80dcae3)

**Comment by JuergenRichter** [comment]
Behoben
