### ISSUE TITLE
Schild 3 öffnet nicht man erhält diese Fehlermeldung.

### ISSUE THREAD

**Issue by Sabanovic-Stadt-Gevelsberg** [SVWS-NRW/Schild3-BetaTest#1209]
![Screenshot 2024-11-29 065503](https://github.com/user-attachments/assets/d51db27e-25d9-476a-ab53-ad95e26880df)

🤷🏼‍♂️🤷🏽‍♂️🤷‍♀️🤷‍♂️

**Comment by AnneSchueller** [comment]
Lief die Schild3-Installation komplett durch? 
Wurde bei der Installation des SVWS-Servers eine Datenbank mit migriert? 
Wenn ja: Gibt es eine Connection-Datei zur dem DB-Schema?
Kann die Datenbank über den Browser-Client gesichtet werden?

Ich verschiebe das Issue in die Diskussion.

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Hallo,

die Installation lief ganz normal durch.

Ja die Datenbank wurde migriert.

Verbindung zur Datenbank ist auch Vorhanden.
***@***.***
***@***.***

Kann die Datenbank über den Browser-Client gesichtet werden?

Was meinen Sie damit??

Also ich kann mit dem Webbrowser den Server erreichen und kann mir da die Lehrer, Schüler usw. anschauen.

Am besten melden Sie sich telefonisch bei mir.





Mit freundlichem Gruß
Im Auftrag



Dennis Ibrahim Šabanović



Stadt Gevelsberg
Der Bürgermeister
Zentraler Service, Bürger- und Ordnungsdienste
Digitales Management
Rathausplatz 1
58285 Gevelsberg
Deutschland
        [cid:LogoStadtGevelsberg_6f69c4fb-2dd1-435e-9095-364cb034210e.jpg]



Telefon:        02332 771-143
Fax:    02332 771-843
E-Mail: ***@***.***



Von: AnneSchueller ***@***.***>
Gesendet: Freitag, 29. November 2024 08:40
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Šabanović Dennis Ibrahim ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Schild 3 öffnet nicht man erhält diese Fehlermeldung. (Issue #1209)

INFO: Diese E-Mail stammt von einem externen Absender. Bitte seien Sie vorsichtig beim Öffnen von Anhängen oder externen Links.


Lief die Schild3-Installation komplett durch?
Wurde bei der Installation des SVWS-Servers eine Datenbank mit migriert?
Wenn ja: Gibt es eine Connection-Datei zur dem DB-Schema?
Kann die Datenbank über den Browser-Client gesichtet werden?

Ich verschiebe das Issue in die Diskussion.

**Comment by AnneSchueller** [comment]
Den Screenshots nach, liegt das Arbeitsverzeichnis im Ordner Programme.
Das gibt wahrscheinlich Probleme mit der Zugriffs-Berechtigung auf die con-Datei.

Testen Sie mal, ob das funktioniert, wenn der Ordner SVWS-Arbeitsverzeichnis direkt auf D liegt. 
Damit Schild3 den Ordner findet, muss dann noch die Admin.ini im Schild-NRW3 Ordner angepasst werden.

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Gleiche Fehlermeldung wie Oben.

**Comment by AnneSchueller** [comment]
Könnten Sie die Fehlermeldung einmal hochladen?
Eine Anleitung ist hier unter Regel 2:
https://github.com/SVWS-NRW/Schild3-BetaTest/wiki

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
[Fehlermeldung_Schild_3.txt](https://github.com/user-attachments/files/17956886/Fehlermeldung_Schild_3.txt)

**Comment by FPfotenhauer** [comment]
Ist das wieder so eine Terminal-Server-Umgebung?

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Nein aktuell als Einzelplatzinstallation auf dem Schulserver.

**Comment by FPfotenhauer** [comment]
Ok. Kann ich mir das irgendwie mal ansehen?
@JuergenRichter Wir sollten das langsam mal eingrenzen, was das ist, das ist jetzt bestimmt das 10. Mal, dass wir diese Meldung bekommen.

Bisher waren das aber alles Terminal-Server-Umgebungen und wir hatten das auf die MAX_APPLICATION_SIZE geschoben.

In dieser Fehlermeldung sind allerdings die Delphi.pas angegeben. Vielleicht hilft da sja bei der Eingrenzung.

**Comment by JuergenRichter** [comment]
Laut Fehlerprotokoll tritt das Problem auf, wenn über den SVWS-Server die Programmeinstellungen geladen werden sollen. Ich verweise hier mal auf die nächste Version, wo hier eine detailliertere Prüfung stattfindet und bei einem Problem auch eine verständlichere Meldung kommt.

**Comment by JuergenRichter** [comment]
Ich kann eine aktuelle Version kurzfristig bereitstellen.

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Nur mal so zur Information, bin heute nur bis 12:30 im Dienst.
Nicht, dass Sie sich wundern, wenn ich nicht antworte.

**Comment by T-Hagel-SK** [comment]
> Ist das wieder so eine Terminal-Server-Umgebung?

Was soll das denn heißen ?
Gibt es diesbezüglich (bekannte) Einschränkungen ?

**Comment by T-Hagel-SK** [comment]
Die Fehlermeldung aus dem Fehlertext "Application made attempt to free invalid or unknown memory block." ist mir aus der Kölner Testumgebung auch vertraut. Aus dem Fehlertext geht aber auch hervor, dass da die Version 3.1.0.28 zum Einsatz kommt. 

Aktuell ist doch aber die Version 3.1.1.29, oder nicht ? 

Schöne Grüße aus Köln
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung / Schild3-Koordination

**Comment by kroerig** [comment]
Für SchILD3 NRW ist es 3.1.0.28.

SchildZentral kann hier durchaus abweichen.

**Comment by T-Hagel-SK** [comment]
> Für SchILD3 NRW ist es 3.1.0.28.
> 
> SchildZentral kann hier durchaus abweichen.

Ok, das war mir nicht bewusst.

**Comment by JuergenRichter** [comment]
Bei Herrn Hagel kam die Fehlermeldung aber in einem ganz anderen Kontext.

**Comment by FPfotenhauer** [comment]
Bitte einmal auf die kommende Version von Schild-NRW3 warten.

**Comment by betaprinz** [comment]
Ist in der Umgebung ein Proxy-Server vorhanden?
Bei uns waren es die Einträge in der ProxyAusnahmenListe.
Meine Vermutung: Diese werden nicht korrekt ausgelesen/ausgewertet.
Bitte mit ausgeschaltetem Proxy testen.

Die Meldung lautet "Application made attempt to freeinvalid or unknown memory block" 

ClientOS: Win11 24H2
Client: 3.1.0 und 3.1.2
Server 1.0.1 Linux installer
MariaDB auf Ubuntu 24.04

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Hallo,

wir haben Proxy zwang also ohne Proxy geht bei uns nichts.

Wir nutzen zum Testen schon einen Proxy der sozusagen alles durchlässt für den Test.

Gruß
Sabanovic

**Comment by betaprinz** [comment]
Proxyzwang ist wohl keine Seltenheit der Verwaltung.
Steht der Server/DB-Server im LAN?
Ist es  ein Squid-Proxy?
Evtl. lässt sich als Notlösung auf dem Proxy-Server mit ACL-Rules lösen.

https://linuxwiki.de/Squid/ACL
oder 
https://wiki.squid-cache.org/SquidFaq/SquidAcl

etwas mit dst / dstdomain und always_direct

Ich kann mich nicht mehr erinnern.

Ist nur eine Idee, evtl auch eine Zeitverschwendung.

**Comment by AnneSchueller** [comment]
Es gibt nun auch ein Update von Schild3.
Evtl. auch damit einmal testen, ob der Fehler noch auftritt.
https://github.com/SVWS-NRW/Schild3-BetaTest/releases/tag/v3.1.2

**Comment by betaprinz** [comment]
Version 3.1.2 führt zu der selben Exception/App-Crash. ("Application made attempt to free invalid or unknown memory block.")

Die Exception entsteht (hier) beim gesetztem "System-Proxy" und/oder ignorierten "ProxyAusnahmenListe".

Ohne "System-Proxy" läuft/startet das Programm.  Ursache kennt wohl nur der/die Entwickler.

**Comment by FPfotenhauer** [comment]
Ok. danke für die Rückmeldung.
Dann wären wir einen Schritt weiter.
Grundsätzlich muss eine HTTPS-Verbindung zum SVWS-Server bestehen.
Wenn ein proxy das verhindert, dann kann Schild-NRW3 nicht starten.

Wie sieht es denn mit dem Web-Client aus? Startet der?

Ist der System-Proxy in Windows in den Proxy-Einstellungen hinterlegt?
Oder ist das ein Transparent-Proxy?

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Hallo,

es ist schon richtig, dass, wenn ich auf dem Gerät, also unserem Virtuellen Windows Server 2022 den Proxy deaktiviere, das Schild 3 ohne Probleme startet.

Jetzt wäre es nur wissenswert, was ich beim Proxy als Ausnahme hinzufügen muss, damit die Verbindung hergestellt werden kann.

Es ist ein Proxy, der unter Windows eingetragen ist.

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Web-Client läuft.

**Comment by FPfotenhauer** [comment]
Die Browser beachten die Proxy-Einstellungen von Windows halt automatisch.

@JuergenRichter Kann es sein, dass wir die Proxy-Einstellungen in die Connection-Datei (oder besser die Admin.ini) aufnehmen müssen und diese müssen dann irgendwie im REST-request hinterlegt werden?

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Also die Weboberfläche lässt sich aufrufen.

Was Sie mit Admin-WEBGUI meinen sagt mir nichts.

Bei uns im Proxy sind diverse freigaben hinterlegt.


172.27.*;192.168.*;10.1.21.83;10.1.21.16;10.1.27.*;localhost;broker.ggrz-hagen.nrw.de;*.witten.local;lv.kommunen.nrw.testa-de.net;*.stadtgevelsberg.de;online-erhebung.nrw.testa-de.net;lv.vergabeanzeige.nrw.testa-de.net






Mit freundlichem Gruß
Im Auftrag



Dennis Ibrahim Šabanović



Stadt Gevelsberg
Der Bürgermeister
Zentraler Service, Bürger- und Ordnungsdienste
Digitales Management
Rathausplatz 1
58285 Gevelsberg
Deutschland
        [cid:LogoStadtGevelsberg_6f69c4fb-2dd1-435e-9095-364cb034210e.jpg]



Telefon:        02332 771-143
Fax:    02332 771-843
E-Mail: ***@***.***



Von: betaprinz ***@***.***>
Gesendet: Montag, 9. Dezember 2024 13:48
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Šabanović Dennis Ibrahim ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Schild 3 öffnet nicht man erhält diese Fehlermeldung. (Issue #1209)

INFO: Diese E-Mail stammt von einem externen Absender. Bitte seien Sie vorsichtig beim Öffnen von Anhängen oder externen Links.


Wie sieht es denn mit dem Web-Client aus? Startet der?
Client startet, auch die Admin-WEBGUI.

Proxy ist unter Win 11 hier hierterlegt (Systemsteuerung->Netzwerk und Internet -> Proxy -> Proxy verwenden -> einrichten)
Kein Transparenter Proxy. Statische IP mit Port und paar Ausnahmen

Folgende Kombinationen funktionieren NICHT für Schild3-3.1.2-"DesktopClient"
Für "Windows" sind diese Einträge kein Prob.

sieht ähnlich aus.

  *   192.168.XX.0/24;
  *   192.168.XX.*;
  *   192.168.XX.254; <- IP des Servers

Der Traffic soll nicht über Proxy laufen, der Client soll die Ausnahmenliste "akzeptieren/lesen".

**Comment by betaprinz** [comment]
> Was Sie mit Admin-WEBGUI meinen sagt mir nichts.

Ich meine diese hier (einfach "/admin"  dranhängen)

https://192.168.XX.254:8443/admin

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Ja komme in die Admin-WEBGUI.

**Comment by JuergenRichter** [comment]
> Kann es sein, dass wir die Proxy-Einstellungen in die Connection-Datei (oder besser die Admin.ini) aufnehmen müssen und diese müssen dann irgendwie im REST-request hinterlegt werden?

Vermutlich. Ich habe mal beim nachgeschaut, beim RESTClient-Objekt gibt es die Eigenschaft ProxyServer. Es ist auch jetzt schon möglich, in der Admin.ini die Proxy-Angaben zu hinterlegen (ursprünglich für die SMTP-EMail-Versand verwendet). Nur wird diese Angabe derzeit nicht für dem RESTClient zugewiesen. Das ist aber kein Problem, das könnte ich kurzfristig mal umsetzen.

**Comment by JuergenRichter** [comment]
Ich habe festgestellt, dass die Proxy-Einstellungen von Windows auch schon jetzt gelesen werden (die Einstellung in der Admin.ini ist als eine zusätzliche Option), es muss nur die Übergabe an den RESTClient umgesetzt werden.

**Comment by JuergenRichter** [comment]
Ich habe das mal umgesetzt und könnte morgen mal eine Version zur Verfügung stellen, damit man testen kann, ob das Problem damit behoben ist.

**Comment by FPfotenhauer** [comment]
Wir könnten das als ZIP hier als Zwischenrelease mit der Versionsnummer 3.1.3 zur Verfügung stellen.
Es wäre gut, wenn die exe dann ausnahmsweise signiert wäre.

**Comment by betaprinz** [comment]
Wofür steht eigentlich `Direct=1` in der con-Datei?

**Comment by JuergenRichter** [comment]
Hallo Herr Pfotenhauer,

kommt im Laufe des Tages.

Mit freundlichen Grüßen aus Bornheim
Jürgen Richter


[ribeka]
Wasser und Umwelt
ribeka GmbH
Johann-Philipp-Reis-Str. 9
53332 Bornheim
Tel.: +49(0)2222-990600
Fax: +49(0)2222-990601
www.ribeka.com<http://www.ribeka.com/>

Geschäftsführer: Dr. Jürgen Richter, Erich Berger
Amtsgericht Bonn HRB 8423



Von: Frank Pfotenhauer ***@***.***>
Gesendet: Dienstag, 10. Dezember 2024 09:14
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Dr. Jürgen Richter ***@***.***>; Mention ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Schild 3 öffnet nicht man erhält diese Fehlermeldung. (Issue #1209)




[ Vorsicht - externe E-Mail! ]
Klicken Sie nicht auf Links oder Anhänge, wenn Sie nicht von der Echtheit der Nachricht überzeugt sind. Kontaktieren Sie bei geringstem Zweifel den Support der HeiTech IT Solutions GmbH.



Wir könnten das als ZIP hier als Zwischenrelease mit der Versionsnummer 3.1.3 zur Verfügung stellen.
Es wäre gut, wenn die exe dann ausnahmsweise signiert wäre.

**Comment by JuergenRichter** [comment]
> Wofür steht eigentlich `Direct=1` in der con-Datei?

Das bedeutet, dass der Zugriff auf die Datenbank auch ohne eine externe DLL (libmariadb.dll) funktioniert, d.h. alle Funktionalitäten zum Datenbankzugriff sind in der Exe integriert. Es ist auf dem ausführenden Rechner also keine "MariaDB-Client-Installation" notwendig.

**Comment by JuergenRichter** [comment]
Ich werde heute Nachmittag eine Programmversion bereitstellen, mit der die Proxy-Einstellungen wie folgt gemacht vwerden können:

1. Über den folgenden Eintrag in der Datei ADMIN.INI

[Proxy]
Server=
Port=

2. Auslesen der Systemeinstellungen
Falls kein Eintrag in der Admin.ini vorhanden ist, wird versucht, die Systemeinstellungen auszulesen.

Ob die Einstellungen korrekt übernommen worden, kann getestet werden, indem SchILD3 mit dem Programmparameter 
-SHOWPROXY (mit Minuszeichn am Anfang) aufgerufen wird. Dann werden beim Start die verwendeten Proxy-Einstellungen angezeigt.

**Comment by kroerig** [comment]
Es sollte auch eine Möglichkeit geben Benutzerdaten für den Proxy hinterlegen zu können. Oder geht das in der klassischen Form
`http://benutzer:passwort@proxy.server:port` ?

Was ist mit Proxys, die z.B. Kerberos/NTLM für die Authentifizierung nutzen? Kann SchILD3 damit umgehen?

**Comment by JuergenRichter** [comment]
Wegen eines Proxy-Kennwortes: Das müsste natürlich verschlüsselt gespeichert werden, da müsste man mal drüber nachdenken, wie das geschehen soll. Über den SVWS-Server? Mit der in Kürze veröffentlichten Version soll erst mal getestet werden können, ob das "allgemeine Prox-Problem" gelöst werden kann.

**Comment by JuergenRichter** [comment]
@FPfotenhauer: Die aktualisierte Programmdatei (zertifiziert) liegt als Zip auf unserem Server

**Comment by FPfotenhauer** [comment]
Ist hier online:
https://github.com/SVWS-NRW/Schild3-BetaTest/releases/tag/v3.1.3

**Comment by JuergenRichter** [comment]
Nur aus Interesse: Haben Sie einen Eintrag in der ADMIN.INI gemacht? WEnn nicht, hat das Programm wohl korrekt die Systemangaben gelesen.

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
Hab nichts in der ADMIN.INI eingetragen.

**Comment by Sabanovic-Stadt-Gevelsberg** [comment]
![image](https://github.com/user-attachments/assets/19834002-f51c-4a8e-bcc5-76ba4fc9bdf1)

**Comment by JuergenRichter** [comment]
Da sollte aber eigentlich der Proxyserver angezeigt werden, der bei den Systemeinstellungen eingetragen ist.

**Comment by betaprinz** [comment]
Funktioniert auch hier:

Folgende Ausnahmen werden akzeptiert:
192.168.*
192.168.10.0/24

Vielen Dank.


Bei mir sieht es genauso aus(wie screenshot oben).

**Comment by FPfotenhauer** [comment]
Danke! Die schnelle Unterstützung hat sehr geholfen.
Ich würde das Issue jetzt schließen.

Über Passwort und korrekte Anzeige/Einstellungen kann man sich ja noch austauschen.
Da mach eich ein neues Issue auf.
Danke auch an @JuergenRichter

**Comment by JuergenRichter** [comment]
Ich habe festgestellt, das in der Identifizierung des Servernamens und des Ports (aus der Windows-Recordstruktur der Prxydaten) noch ein Fehler drin war. Aber scheinbar hilft wohl allein der Aufruf der betreffenden Windowsfunktion. Eine korrigierte Version (mit korrekter Anzeige der Daten) stelle ich noch zur Verfügung.

**Comment by T-Hagel-SK** [comment]
Bei aller Proxy-"Fummelei" ... 
Bei uns haben wir immer noch Probleme mit dem PC-Client, auch mit der neuen DB-Config.exe (2.1.2.2). Aber doktort man da nicht einfach an der falschen Stelle herum ?
So ein Proxy hat ja so sein Aufgabengebiet. Ihn jetzt über Ausnahmen zu deaktivieren, nur damit der PC-Client nicht in einen "invalid memory"-Fehler stolpert ... ich weiß nicht. 
Zumal die Proxyeinstellungen ein weites Feld sind. Dien einen können es über den Windows-Client in den Systemeinstellungen lösen, andere fügen Proxydaten nun in die CON-Datei hinzu. Andere müssen dann -wohl wie wir- Ausnahmeregeln in der Firewall hinterlegen. Dann war noch die Rede von Kerberos und anderen Dingen bei denen mir Detailwissen fehlt. Proxy und Passwörter in INI- oder JSON-Dateien hinterlegen ?

Was ist denn die Ursache im Quelltext ? Wir hier alles blockiert oder nur Teilbereiche der Anwendung ?
Warum geht der PC-Client an welchen Stellen in Fehler ? Warum behebt man den Fehler nicht im Programmquelltext, statt Workarounds drumherum zu basteln ?

Dass sich der PC-Client nun an Proxyumgebungen aufhängt, tritt erst jetzt auf ? Oder liegt es daran, dass nun auch erste Kommunen Schild3 testen, in denen Proxysysteme nunmal vorgegeben sind ? Die ja auch ihren Zweck und ihre Daseinsberechtigung haben. Die Systeme hier sind nun mal komplexer als ein PC oder kleiner Server im Schulgebäude.
