### ISSUE TITLE
Fehlende Schaltfläche "Fächer kopieren" und "Fächer einfügen"

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#121]
In der aktuellen SchILD-Version (2.0.x) besteht die Möglichkeit, bei einem Schüler unter Akt. Halbjahr > Leistungsdaten die Fächer zu kopieren und bei einem anderen Schüler einzufügen. Diese Schaltflächen scheinen nicht mehr zur Verfügung zu stehen.

**Comment by JuergenRichter** [comment]
Die Funktion gibt es weiterhin, ist nun über die rechte Maustaste verfügbar. Da ist auch eine gewisse Logig dahinter:
Funktionen, die sich auf ein oder mehrere Fächer beziehen (also nicht zwingend auf alle), werden über das Popup-menü bereitgestellt.

**Comment by Kluesenerm** [comment]
In der Regel werden aber alle Fächer kopiert. Ich habe auch schon nach dem Schalter gesucht.

**Comment by hagege** [comment]
In der Tat: Insbesondere dann, wenn während des Schuljahres ein Schüler neu an die Schule kommt und/oder ein Schüler aus einer Klasse aus welchen Gründen auch immer in eine anderen Klasse wechselt.

**Comment by JuergenRichter** [comment]
OK, wir werden wieder einen separaten Schalter  schaffen

**Comment by JuergenRichter** [comment]
Ist in 3.0.13.3 umgesetzt
