### ISSUE TITLE
Verwaltung -> Import - SchILD-NRW -> Schüler: Zusatzdaten: HaltestellenAbk  = Unkown column

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1210]
Hallo zusammen,

wenn bei den Schülern eine Haltestelle eingetragen ist, kommt es beim Import zu dem Fehler:
Schüler-Zusatzdaten (für ...): #42S22**Unknown column 'HaltestelleAbk'** in 'field list':
update Schueler set Geburtsort='Leverkusen',Telefon='...',EMail='-',IDext='3653',Fahrschueler_ID=1,Haltestelle_ID=9,**HaltestelleAbk='Dabringhausen'**,EinschulungsartASD='51',Anmeldedatum='2020-01-30',Bafoeg='-',EPJahre=2,Fax='...',Ausweisnummer='L06152',SchulEmail='...@sgw-schule.de',MasernImpfnachweis='+' where ID=3653

LG
Raphael

**Comment by AnneSchueller** [comment]
Wurde denn der Katalog entsprechend der Haltestelle angepasst?

**Comment by JuergenRichter** [comment]
Behoben
