### ISSUE TITLE
Kreis nicht auswählbar (Schüleradresse)

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1211]
Auch nach dem Eintrage des Kreises im Katalog (dieser ist maximal dreistellig, soll das so sein?) lässt sich dieser nicht für den Adresseintrag auswählen.

**Comment by JuergenRichter** [comment]
Der Kreis soll auch gar nicht auswählbar sein, da dieser ja am Ortsnamen "hängt". Es handelt sich um ein "berechnetes" Feld, dass anhand von Schueler.Ort_ID den Kreis aus der Tabelle K_Ort holen soll. Ich habe aber festgestellt, dass die Berechnung (also das "Holen") bisher nicht durchgeführt wird. Habe ich nun korrigiert
