### ISSUE TITLE
Login-Namen lowercase

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#1213]
Ich kann in Schild2 Benutzernamen case-sensitive anlegen.
In der Benutzerverwaltung habe ich einen "Admin" und habe dazu einen "admin" mit sehr wenig Rechten angelegt.
Beim Einloggen ist aber der Benutzername case-insensitive und man wir immer mit den "Admin" angemeldet.
Wahrscheinlich weil der die kleiner ID hat.

Könnte man bitte in Schild2 eine Warnung herausgeben, dass gleiche Benutzernamen mit unterschiedliche Klein-/Großschreibung bereinigt werden müssen?

**Comment by JuergenRichter** [comment]
ich habe das mal in SchILD2 getestet, indem ich mit verschiedenen Datenbanken einen neuen Benutzer mit einem bereits existierenden Loginnamen, aber in anderer Schreibweise anlegen wollte.

![image](https://github.com/user-attachments/assets/a6bfa8b2-b6be-4d7c-bb0d-523e839dfc12)

Access-Datenbank
Beim Speichern kommt folgende Fehlermeldung, der Benutzer lässt sich nicht speichern.
![image](https://github.com/user-attachments/assets/49346caf-b9d2-46ee-a981-22ff61af0d13)

MSSQL-Datenbank
Auch hier kommt eine Fehlermeldung:
![image](https://github.com/user-attachments/assets/ccf0f7ce-3b9f-419f-9780-2c04a77cab1f)

MySQL auf Windows-Server
Auch hier kommt eine Fehlermeldung, kann sie hier aber nicht posten, da das auf einem anderen Rechner läuft

Die Option "MySQL auf Linux-Server" habe ich nicht testen können. Daher die Frage: Mit welcher Konstellation ist denn das beschriebene Problem aufgetreten?

**Comment by FPfotenhauer** [comment]
In Access konnte ich das problemlos anlegen.

**Comment by FPfotenhauer** [comment]
Ok, sorry ich habe hier eine Schid2-Version von 2021 neben der aktuellen Version gehabt.
Darin funktioniert es nach wie vor problemlos.

Mit der aktuellen Version bekomme ich die selben Meldungen, wie Sie.

**Comment by JuergenRichter** [comment]
Das ist merkwürdig, da die Fehlermeldungen ja nicht von SchILD2, sondern von jeweiligen Datenbanktreiber verursacht werden (Index-Verletzungen). Entweder ist da in einer der Datenbanken ein Index defekt oder der betreffende Index ist erst nachträglich (nach 2021) angelegt worden. Wenn letzteres zutrifft, kann es sein, dass vor 2021 solche doppelten Benutzer angelegt wurden. Dann kann aber der Index auch nicht angelegt worden sein. Ich werde das mal prüfen.

**Comment by kroerig** [comment]
Das bedeutet dann aber ggf., dass es doppelte Benutzernamen in Bestandsdatenbanken geben könnte.
Die würden dann vermutlich bei der Migration gegen die Wand laufen.

Das sollte vllt. auch auf die Liste der Aufräumarbeiten vor einer Migration.
