### ISSUE TITLE
DSGVO-Einwilligungen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1214]
Beim Erstellen einer DSGVO-Einwilligung innerhalb einer DB auf einem Linux-Server (Docker)  kommt es zu einer Fehlermeldung:

[log.txt](https://github.com/user-attachments/files/18038238/log.txt)

Mit einer Windows-Installation konnte ich das nicht reproduzieren.

Hier heißt die Tabelle: k_datenschutz
In Linux heißt sie: k_Datenschutz

**Comment by JuergenRichter** [comment]
Korrigiere ich kurzfristig, der korrekte Name ist K_Datenschutz

**Comment by JuergenRichter** [comment]
Behoben
