### ISSUE TITLE
Aktivierreihenfolge in der Maske "Schüler suchen"

### ISSUE THREAD

**Issue by stbaeumer** [SVWS-NRW/Schild3-BetaTest#1218]
In der Maske "Schüler suchen" steht der Fokus zunächst auf dem Nachnamen. Mit TAB springt der Fokus danach auf Straße, Geburtsdatum usw. Der Vorname kommt erst an Position 5 oder 6.

Vorschlag: Nachname -> Vorname -> Straße -> Geburtsdatum-> ...

**Comment by AnneSchueller** [comment]
Danke für die Rückmeldung.
Das ist in der aktuellen Schild3-Version bereits behoben (Version 3.1.2)
