### ISSUE TITLE
Report-Schnellzugriff

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#122]
Kleiner Tippfehler im Report-Schnellzugriff (das O wurde groß geschrieben)
![image](https://user-images.githubusercontent.com/75179015/111923431-7ad2ca80-8a9f-11eb-8021-d9f8ac1531a8.png)
Es wäre gerade für größere Systeme mit Abteilungen wünschenswert, wenn es globale und individuelle Reports im Schnellzugriff geben würden. Ansonsten sollte die Anzahl der Reports im Schnellzugriff (evtl. durch Option) erweiterbar sein.

**Comment by FPfotenhauer** [comment]
Eine kleine Anmerkung:
Bitte in den Issues keine Fehlermeldung und Feature-Wünsche vermischen.
Es wird sonst schwer, die Tickets richtig zu bearbeiten und zu schließen.

**Comment by FrodBRA** [comment]
Der Tippfehler ist behoben.

Der Verbesserungsvorschlag sollte in einem neuen Issue klar benannt erneut gewünscht werden, so dass hier geschlossen werden kann bzw. es sollte dieses Issue umbannt und mit einem passen Flag versehen werden. 

@AnneSchueller

**Comment by JuergenRichter** [comment]
Der Report-Schnellzugriff wird schon seit einiger Zeit benutzer-bezogen verwaltet.

**Comment by FrodBRA** [comment]
@AnneSchueller 

Damit kann das Issue abgeschlossen werden.

Sollte der Schnellzugriff einen globalen und einen individuellen Teil beinhalten sollen, wäre das - zu einem späteren Zeitpunkt - über ein eigenes Issue zu wünschen.

**Comment by AnneSchueller** [comment]
Den Individuellen Schnellzugriff würde ich bevorzugen. Hat ja jede Abteilung andere Reports, die oft gedruckt werden.
