### ISSUE TITLE
Reports enthalten keine Daten mehr 3.1.2

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#1220]
In der neuen Version 3.1.2 fehlen bei sehr vielen Reports die Daten (mal Namen, mal Adressen,...).
Später mehr, aber den Fehler wollte ich mal schnell melden.

**Comment by SebSchraufBRA** [comment]
Vielleicht hilft dies:
Sowohl in Klassenlisten als auch in mehreren Einzelreports, die hintereinander für eine Gruppe erzeugt werden, betrifft dies augenscheinlich nur den ersten Schüler.

**Comment by JuergenRichter** [comment]
Ist behoben, hängt auch mit #1222 zusammen
