### ISSUE TITLE
Weitere Adressen wird nichts angezeigt, obwohl EIntragungen vorgenommen wurden

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1222]
Hallo zusammen,

bei "Weitere Adressen" wurden von uns Praktikumsbetriebe eingetragen. Die Ansprechpartner werden auch noch als einziges angezeigt, alles andere ist leer in der Ansicht. Exportiert man die Daten, ist alles da.
Das war jetzt nach dem Update so von 3.0.0 updated.
Wenn ich "Bearbeiten" anwähle, dann wird alles sichtbar. Klicke ich auf Speichern und dann auf einen anderen Schüler und zurück, ist wieder alles unsichtbar.

LG
Raphael

**Comment by Raphael-Kemna** [comment]
![grafik](https://github.com/user-attachments/assets/a0cc1517-e74d-4c7d-a54d-73b1d2f20991)
![grafik](https://github.com/user-attachments/assets/7c56ea6d-b1c4-4290-9ff9-025a760b80e6)

**Comment by JuergenRichter** [comment]
Ist behoben, hängt auch mit #1220 zusammen
