### ISSUE TITLE
ProxyEinstellungen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#1225]
Schild-NRW3 liest nun die Proxy-Einstellungen des Systems aus.
Folgende Konfigurationen sollten nun noch bedacht werden:

1. Es wird ein Benutzername und Passwort benötigt.
Das kann eigentlich nicht vom SVWS-Server abgerufen werden, das muss ja vorher bekannt sein.
Das Passwort muss verschlüsselt werden.
Wäre die CON-Datei dafür geeignet? Dann müsste das DBConfig.exe angepasst werden.
Aber es wäre schön, wenn alte CON-Dateien weiterhin funktionieren würden!

2. Was passiert, wenn ein Systemproxy eingetragen ist, aber der SVWS-Server nicht über diesen Proxy angesprochen werden soll? Hier könnte man sicherlich auch zunächst auf Fehlermeldungen warten, falls so eine Konstellation wirklich auftritt.

3. Die Anzeige mit dem Fenster des Proxy-Servers könnte ggf. noch korrigiert werden, allerdings wird dieses Fenster auch nicht mehr benötigt, wenn jetzt keine Fehlermeldungen mehr dazu kommen.

**Comment by JuergenRichter** [comment]
Das würde man am besten in der CON-Datei speichern, da dort schon eine Verschlüsselung vorhanden ist. Vorhandene Con-Dateien bleiben davon unberührt. Wenn man die Proxy-Daten in der Admin.ini speichern würde (was grundsätzlich gewisse Vorteile hätte) müsste man aber wieder ein weiteres Programm haben, das nur das Proxy-Kennwort verschlüsselt.

**Comment by JuergenRichter** [comment]
Zum Fall 2: Das könnte man so lösen, dass zuerst nach Proxy-Angaben in der Con-Datei gesucht wird, nur wenn da nichts gefunden wird, wird zusätzlich auch im System nachgeschaut.

**Comment by kroerig** [comment]
Ich würde es so angehen, dass man in der admini.ini einen Abschnitt 
```
[proxy]
enabled=1|true
auth=config|domain
proxy="http://proxy.server:port"
```
anlegt (das geht dann auch wunderbar über GPP) Wenn SchILD3 in diesem Abschnitt ein `auth=config` findet, dann schaut es in der CON Datei nach globalen Anmeldedaten.

Elegent wäre natürlich, wenn der Proxy automatisch erkannt würde und SchILD bei einem "407" die Domänenanmeldung des Benutzers nimmt bzw. könnte man das noch über die admin.ini steuern.

Von anderer Software kenne ich es, dass der Benutzer seine Proxy-Anmeldung selbst beim ersten Start eintragen muss. Die werden dann in der Reg [HKCU] verschlüsselt abgelegt.

**Comment by JuergenRichter** [comment]
> Von anderer Software kenne ich es, dass der Benutzer seine Proxy-Anmeldung selbst beim ersten Start eintragen muss. Die werden dann in der Reg [HKCU] verschlüsselt abgelegt

Ich stelle mir gerade vor, wie wohl eine Grundschulsekretärin reagieren würde, wenn sie nach dem Kennwort für den Proxy-Server gefragt wird ;)

**Comment by kroerig** [comment]
> > Von anderer Software kenne ich es, dass der Benutzer seine Proxy-Anmeldung selbst beim ersten Start eintragen muss. Die werden dann in der Reg [HKCU] verschlüsselt abgelegt
> 
> Ich stelle mir gerade vor, wie wohl eine Grundschulsekretärin reagieren würde, wenn sie nach dem Kennwort für den Proxy-Server gefragt wird ;)

Naja, wenn es personalisierte Anmeldungen am Proxy sind, z.B. mit Kerberos, dann fällt das im Brower nicht auf. Aber dann gibt es ja ggf. keine generischen Anmeldedaten.

**Comment by JuergenRichter** [comment]
Die Proxy-Einstellungen können nun im Programm für die Konfiguration der CON-Dateien gemacht werden.
![image](https://github.com/user-attachments/assets/adbdeff3-c05c-4a73-89d7-cd554a09f476)

**Comment by FPfotenhauer** [comment]
Danke.

Ich schließe das Issue mal, bei Fehlern oder Problemen bitte ein neues Issue aufmachen.
