### ISSUE TITLE
Statuszeile "letzte Änderung" bleibt auch ber Verlassen der Schüleransicht stehen

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/Schild3-BetaTest#1226]
Guten Abend,

der Eintrag in der Statuszeile "letzte Änderung durch..." bleibt auch beim Verlassen der Schüleransicht, also z.B. in der Lehreransicht, auf dem letzten Eintrag stehen. Das sieht nun so aus, als sei beim entsprechenden Kollegen etwas geändert worden.

![grafik](https://github.com/user-attachments/assets/21330f34-cf24-49e6-af50-2d03eaa59f07)

Version: 3.1.2.30

**Comment by AnneSchueller** [comment]
Der Hinweis dient nur dazu, wann das letzte mal in der Datenbank etwas geändert wurde (analog zum Hinweis in Schild2)
Das zu differenzieren, in welchem Reiter etwas geändert wurde würde ich jetzt erstmal zurückstellen.
Das wäre etwas, was man später mal angehen könnte.

**Comment by WJohannsen** [comment]
Hallo Frau Schüller, 

wnen der Hinweis generell zur Anzeige dient, wann IN DER DATENBANK etwas geändert wurde, verhält er sich auch falsch, denn diese Anzeige springt von Schüler zu Schüler um - eben auf die letzte Änderung BEI DIESEM SCHÜLER. 

Sie bleibt dann aber auch bestehen, wenn ich auf die Anzeige eines Lehrers oder anderer Elemente wechsele und zeigt damit definitiv etwas falsches an.

**Comment by AnneSchueller** [comment]
Ach tatsächlich. Ich sehe gerade, dass das auch in Schild2 so war.
@JuergenRichter : evtl. sollte die Information dann einfach ausgeblendet werden, wenn man den Reiter wechselt?
