### ISSUE TITLE
Fehler nach Anmeldung mit korrektem Passwort

### ISSUE THREAD

**Issue by Dpropach** [SVWS-NRW/Schild3-BetaTest#1227]
Angehängte Fehlermeldung tritt bei einer Schule (Berufskolleg) auf, wenn man versucht sich mit dem korrekten Passwort anzumelden.

**Interessant:**
Gibt man einmal ein falsches Passwort ein und bestätigt dann die Fehlermeldung "Ungültiges Kennwort" startet SchILD 3.0 anschließend nach Eingabe des richtigen Passworts ohne Mucken. Dies verhält sich bei allen Benutzern so. 

[SchILD30.txt](https://github.com/user-attachments/files/18092150/SchILD30.txt)

**Comment by Dpropach** [comment]
Beim Web-Client klappt die Anmeldung auf Anhieb, Beim Win-Client wie beschrieben nur über den Umweg "falsches Kennwort"

**Comment by JuergenRichter** [comment]
Wird ein Proxyserver verwendet?

**Comment by Dpropach** [comment]
Ja, für den externen Verkehr

**Comment by JuergenRichter** [comment]
OK, dann könnet das die Ursache sein. Es gibt in der Zwischenzeit eine neue Version, die auch einen Proxyeintrag berücksichtigt. Warum das aber funktioniert, wenn man erst mal ein falsches Kennwort und dann das richtige eingibt, ist mir ehrlich gesagt noch nicht klar.

**Comment by Dpropach** [comment]
Ja, mit Version 3.1.3 funktioniert es.
