### ISSUE TITLE
Filter "Schulgliederung" kann bei mir nicht aufgerufen werden (roter Haken fehlt)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#123]
Der Filter "Schulgliederung" kann bei mir (WBK) nicht gewählt werden. Der Haken für die Auswahl bleibt grau:
![image](https://user-images.githubusercontent.com/75179015/111923633-63e0a800-8aa0-11eb-94f1-de156ab9650a.png)

**Comment by JuergenRichter** [comment]
In 3.0.13.3 behoben
