### ISSUE TITLE
Export zum externen Notenmodul: Eingabe von Mahnungen sperren

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/Schild3-BetaTest#1230]
Hallo nochmals,

ich hätte einen weiteren Wunsch im Zusammenhang mit dem Export zum externen Notenmodul: Bitte (wie in SchILD 2 vorhanden) die Möglichkeit einbauen, die Eingabe von Mahnungen zu verhindern. Bei uns entscheiden nicht die Fachlehrer, ob gemahnt wird, sondern die Stufen-/Schulleitung in der Gesamtschau des Notenbildes.

**Comment by FPfotenhauer** [comment]
Solche Features können später gerne kommen.
Momentan müssen wir erst schauen, dass wir das Grundkonstrukt vernünftig zum Laufen bekommen.
An den Exportdateien "hängt" auch der Webnotenmanager. Deshalb müssen Veränderungen an den Exportdateien hier zwischen mehreren Teams abgestimmt werden. Momentan ist das alles ein Frage der Ressourcen.
