### ISSUE TITLE
Telefonnummerneingabe in Schild mit Trennzeichen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#1234]
In der neusten Version können in SchILD3 keine Trennzeichen in Telefonnummernfeldern eingetragen werden (- /). In der Vorgängerversion und im Client ist das noch möglich. Durch die Migration bei der Installation kommen solche Sonderzeichen aber an.
Zudem scheinen die Felder jetzt plötzlich eine "vorausgefüllte" Größe zu haben. Klickt man in ein solches Feld, landet der Cursor weit hinter den Telefonnummern, so als wären viele Leerzeichen dahinter.
![image](https://github.com/user-attachments/assets/65af2968-3542-438b-8321-6e29dbbd38e8)

**Comment by JuergenRichter** [comment]
Das ist indirekt eine Folge der neuen Suchmöglichkeit für Telefonnummern. Diese funktioniert in folgendem Fall nicht:

Eintrag in Datenbank 0221-24 43 46
Sucheingabe (da z.B. so in der Anzeige am Telefondisplay) 0221243446

Durch die Änderung wird der Benutzer nun "gezwungen", die Telefonnummer in einem rein numerischen Format einzugeben, die "alte" Schreibweise wird für die Anzeige aber weiter unterstützt. Ich stelle das mal zur Diskussion, ob das so bleiben soll. Wir können die rein numerische Eingabe auch wieder deaktivieren. Wenn es so bleiben soll, wäre zu überlegen, ob bei der Migration die Telefonnummern entsprechend angepasst werden.

**Comment by kroerig** [comment]
Ich bin mir nicht sicher, ob das mit automatisch konvertieren bei der Migration ohne große Fehler funktionieren wird. Bisher war das Feld ein Freitextfeld und neben der Runfnummer in div. Formaten konnte man noch alles mögliche eintragen.

Nur auf Zahlen zu beschränken wäre auch zu streng, denn eine Landesvorwahl sollte möglich sein, und dazu ist das '+' erforderlich. Das ist insb. dann erforderlich, wenn die Daten aus SchILD auch noch in anderen Programmen verarbeitet werden.

Outlook z.B. legt Rufnummern in Kontakten i.d.R. in der Form +49 (1234) 567-890 (sofern es sich z.B. um eine Rufnummer mit Stammnummer und Durchwahl handelt), sonst lässt man die Durchwahl halt frei.
![grafik](https://github.com/user-attachments/assets/9b22e83a-9e0b-4c78-8cd7-a5c9ca9c2cad)

In SchILD habe ich schon viele Schreibweisen von Rufnummern gesehen: Mit Klammern um die Ortsvorwahl, getrennt mit Leerzeichen und/oder Schrägstrich

Und Kommentare wie "(nicht herausgeben)" hinter der Rufnummer.

**Comment by WJohannsen** [comment]
... und Angabe weiterer Telefonnummern von KuK, die neben Festnetz und Mobil noch eine Festnetznummer an ihrem ausländischen Wohnsitz haben, für die nun kein Feld mehr zur Verfügung stehen wird (siehe https://github.com/SVWS-NRW/SVWS-Server/issues/299)

**Comment by AnneSchueller** [comment]
Ich würde an dieser Stelle ebenfalls nicht numerische Werte zulassen.

Könnte man denn bei der Telefonnummer-Suche nicht nummerische Werte ignorieren? Also beim Suchstring und in der Datenbank?

Also Suche nach 12-345 67 findet auch den Eintrag 012/34567

**Comment by JuergenRichter** [comment]
Es wird ja jetzt schon eine LIKE-Abfrage ausgeführt, d.h. bei Eingabe von 345 würde auch die Nummer 012/34567 gefunden und auch 12-345 67, letzteres würde aber nicht gefunden werden, wenn 34567 eingegeben wird (wegen des Leerzeichens). Eine allgemein-gültige Lösung würde auch am besten z.B. über eine stored procedure o.ä. in der Datenbank abgebildet, die dann sowohl vom SchILD3 als auch vom Webclient genutzt werden könnte.

**Comment by JuergenRichter** [comment]
Ich werde dann erst mal die Formatierung auf rein numerische Werte bei der Eingabe rausnehmen.

**Comment by Raffenberg** [comment]
Das hört sich sinnvoll an.
