### ISSUE TITLE
Ansicht "Auswahl" könnte breiter sein

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#124]
Das Auswahlfenster könnte meiner Ansicht nach verbreitert oder "dynamisch" gestaltet werden. Das Weiterklicken durch die Karteireiter könnte bei größeren Bildschirmen entfallen:
![image](https://user-images.githubusercontent.com/75179015/111923732-d6518800-8aa0-11eb-8674-85e9cccb2ec0.png)

**Comment by FrodBRA** [comment]
Das Fenster sieht bei mir nicht mehr so aus, das Problem tritt hier nicht mehr auf.

Ist das Issue damit noch aktuell?
