### ISSUE TITLE
DB-Migration: Falsch eingetragene Klassenleitung wird bei der Migration allen Schülern zugewiesen

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/Schild3-BetaTest#1240]
Guten Abend,

bei der unterjährigen Aufnahme einer Schülerin wurde versehentlich eine falsche Klassenleitung eingetragen. Bei der Migration wurde diese Klassenleitung nun zusätzlich allen anderen SuS der Klasse zugewiesen, diese haben nun also drei Klassenlehrer:innen. 

SchILD2, Eintragung bei fast allen SuS:
![grafik](https://github.com/user-attachments/assets/0a27a402-fa53-4f46-a119-5f80e52f6ac4)

SchILD2, Eintragung bei einer S':
![grafik](https://github.com/user-attachments/assets/499d40c3-9ff8-4e30-b7a4-c2a8be73986f)

SchILD3, Anzeige bei allen SuS der Klasse:
![grafik](https://github.com/user-attachments/assets/12581dc0-afd0-45f0-9d68-602bc50f2dfb)

**Comment by AnneSchueller** [comment]
Dies ist wahrscheinlich ein Resultat daraus, dass die Klassenlehrerliste in Schild3 anders abgespeichert wird als in Schild2. Die Klassenlehrer können nun auch nicht mehr im aktuellen HJ der Schüler geändert werden, sondern nur noch klassenweise.
@ThomasBachran : sollte das bei der Migration abgefangen werden?

**Comment by FPfotenhauer** [comment]
Das ist bei der Migration so gewollt.
Wenn ein Schüler einen Klassenlehrer im aktuellen Abschnitt eingestellt hat, wird der in die Liste der Klassenlehrer in dem Abschnitt aufgenommen.
Wir können bei der Migration nicht entscheiden, ob ausgerechnet diese Lehrerin nicht gewollt ist.

Man kann das vor (oder such nach) der Migration selbst korrigieren.
