### ISSUE TITLE
Telefonnummern

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#1242]
Hallo zusammen,

bei den Telefonnummern sind nur Zahlen, kein Leerzeichen, - oder / erlaubt, was aber die Lesbarkeit deutlich erhöhen würde (Anmerkung unserer Sekretärin).

Liebe Grüße
Raphael

**Comment by WJohannsen** [comment]
Siehe https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1234
