### ISSUE TITLE
SchuelerZusatzdaten.dat Feld Bemerkungen 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1245]
In Schild2 wurden bisher beim Export der SchuelerZusatzdaten.dat in der Spalte Bemerkungen die Bemerkungen von Individualdaten I mit übernommen. Dieses Feld gibt es nun nicht mehr.
SchuelerOnline nutzt das aber, damit Schulen und/oder Betriebe dort Informationen hinterlegen können.

Wie gehen wir damit um? Soll das nun aus den Vermerken gezogen werden für die Vermerkart "Bemerkungen"?
Aktuell ist die Spalte immer leer.

**Comment by kroerig** [comment]
Ich bin ja nicht so tief in der Anwendung drin, aber wenn in den Vermerken jetzt mehrere alte Felder zusammengelegt wurden, besteht dann jetzt nicht die Gefahr, dass beim Export Daten rausgehen, die eigentlich nicht die Schule verlassen sollten?

**Comment by AnneSchueller** [comment]
Definitiv.
Die alten Einträge bei Bemerkungen werden migriert nach Vermerke mit der Vermerkart "Bemerkungen".
Wenn eine Schule vorher bereits die Vermerkart "Bemerkungen" definiert hat und dort Daten drin stehen, die nicht weiter gegeben werden sollen, wäre das fatal, wenn man diese Daten nun in dem Export entsprechend ersetzt.

**Comment by kroerig** [comment]
Dann sollte man vielleicht eine neue Vermerkart "SchülerOnline" anlegen, damit dann auch nur Einträge für diesen Zweck exportiert werden können. Oder kann hier mit Tags gearbeitet werden?

**Comment by JTorspecken** [comment]
Achtung Missverständnis!
Es geht nicht um den Export der Schulen nach SchülerOnline. (Allerdings werden hier die Zusatzdaten wegen der Mailadressen auch übertragen.)
Vielmehr geht es um den Import der Daten aus SchülerOnline an die Schulen. In SchülerOnline könne die Betriebe, aber auch die eigene Schule Notizen machen ("soll in die gleiche Klasse, wie..." usw.). Diese landen beim Import der SchuelerZusatzdaten.dat in SchILD2 in den Bemerkungen. Bei SchILD3 ist das für mich noch unklar.

Vor allem muss hier überlegt werden, ob die Schnittstelle geändert werden muss, was bestimmt eine Menge Folgeprobleme mit sich bringt. Wenn hier keine Änderung erfolgt, müsste man eine automatische Vermerkart vorsehen, unter der die Daten für die Schnittstelle ex- und importiert werden.

**Comment by FPfotenhauer** [comment]
An der Schnittstelle Schild-NRW2 und 3 werden wir nichts ändern.
Der Austausch der Daten wird auf die API umgestellt. Dazu wurden auch schon erste Gespräche mit Schulbewerbungen.de geführt. Wir warten hier noch auf Rückmeldung.

Das Feld Bemerkungen müssen wir in der Schnittstelle als "deprecated" vermerken.
