### ISSUE TITLE
Fehlermeldung beim Klick auf Verwaltung/Schule/weitere Angaben

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#1246]
Gelegentlich (ich kann keine Logik erkennen) erscheint beim Klick auf Verwaltung/Schule/weitere Angaben folgende Fehlermeldung:
Element 'layMain' hat kein übergeordnetes Fenster. 

[log.txt](https://github.com/user-attachments/files/18210505/log.txt)

**Comment by JuergenRichter** [comment]
Ist mir auch schon aufgefallen, ist auch schon behoben.
