### ISSUE TITLE
Schild3 unter MSSQL

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#125]
In der aktuellen Version startet das Programm nicht mit der Fehlermeldung im Screenshot.
In dem Feldbezeichner ist ein kleines "n" es muss aber "SchulNrEigner" heißen.

![SNAG_2021_03_23_11 54 15](https://user-images.githubusercontent.com/34127980/112135983-ae604280-8bce-11eb-80ff-0a757576ad88.png)

**Comment by JuergenRichter** [comment]
Wäre es möglich, mal das aktuelle Skript für MSSQL zu bekommen? Oder geht das schon über den svws-Server?

**Comment by FPfotenhauer** [comment]
Das geht immer über den SVWS-Server, wenn man eine Migration macht oder den SQLGenerator benutzt.
Ich aktualisiere immer mal wieder hier:
https://github.com/SVWS-NRW/SVWS-DB-Scripte
Ich werde das morgen mal aktualisieren.
