### ISSUE TITLE
Suchfunktion beachtet Groß- und Kleinschreibung

### ISSUE THREAD

**Issue by Gerritzma** [SVWS-NRW/Schild3-BetaTest#13]
Die Suchfunktion (Fernglas) beachtet Groß- und Kleinschreibung, das ist im Alltag unpraktisch. 

Man neigt dazu, die Namen der Schüler in dem Suchfeld klein zu schreiben, weil es schneller geht.

**Comment by JuergenRichter** [comment]
Mann kann das im SQL-Befehl über UPPER() (bzw. LOWER() ) umsetzen (Syntax ist zum Glück für MariaDB, MSSQK und SQlite gleich), das würde dann aber den Fall, wo man explizit nach Groß- und Kleinschreibung unterscheiden möchte, aushebeln. Alternativ könnte man auch eine Option "Groß-/Kleinschreibung ignorieren" o.ä. schaffen.

Ich stelle das mal zur Diskussion.

**Comment by FPfotenhauer** [comment]
Ich würde bevorzugen, dass das Verhalten wie in Schild2.0 ist, da wird kann man einfach Kleinbuchstaben tippen.

**Comment by WLey-49** [comment]
Sehe ich genauso wie Frank. Eine Unterscheidung nach groß/Kleinbuchstaben ist mir in der Praxis noch nicht aufgetaucht.

**Comment by AlexanderDedy** [comment]
ich habe mich gerade beim testen auch gewundert das niemand gefunden wird.... bitte mindestens wählbar, ansonsten ohne Großschreibung.

**Comment by Kluesenerm** [comment]
Es sollte wie in Schild 2.0 funktionieren. Ich bin auch von einem BUG ausgegangen.

**Comment by JuergenRichter** [comment]
Es gibt jetzt bei der Suche eine (standardmäßig aktivierte) Option "Groß-/Klein-Schreibung ignorieren"
