### ISSUE TITLE
Report umbenennen, kopieren, ausschneiden über Buttons funktioniert nicht

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#130]
Wenn man einen Report über die Buttons im oberen Bereich umbenennen, kopieren oder ausschneiden möchte, passiert nichts.

**Comment by JuergenRichter** [comment]
In 3.0.14 behoben, die Option Umbenennen wurde aber aus der Ribbon-Leiste entfernt, das funktioniert nur, wenn die Report-Liste den Fokus hat.
