### ISSUE TITLE
Änderungen durch User werden (zunächst) nicht dokumentiert

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#132]
Wenn ich als Admin bei einem Schüler beispielsweise das Zuzugsjahr ändere, dann sollte im oberen Bereich bei "letzte Änderung" auch ersichtlich sein, dass ich diese Änderung mit dem heutigen Tag durchgeführt habe. Das ist allerdings nicht der Fall.
Erst nach Klick auf "Aktualisieren" bei Bearbeitung erscheint die korrekte Änderungsmeldung.

**Comment by JuergenRichter** [comment]
In 3.0.14 behoben
