### ISSUE TITLE
Fehler unter Verwaltung > Werkzeuge > Transaktionsprokolle

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#133]
Bei Klick auf "Transaktionsprotokoll verwenden" und "Transaktionsprotokoll zeigen" erscheint eine Fehlermeldung.
![2021-03-25 15_50_16-Error occurred](https://user-images.githubusercontent.com/27292550/112492828-e5c32080-8d81-11eb-90cc-9b554680331c.png)

**Comment by JuergenRichter** [comment]
In 3.0.14 behoben
