### ISSUE TITLE
Kurs neu einrichten: Lehrernummer statt Kürzel

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#136]
Beim Anlegen eines neuen Kurses wird bei Auswahl eines Lehrers nicht der Name, sondern eine Zahl als Kursleiter übernommen. Bei Übernahme fehlt in der Spalte Lehrkraft der Eintrag.

**Comment by JuergenRichter** [comment]
In 3.0.14 behoben
