### ISSUE TITLE
Eintrag in Leistungsdaten bei einem Schüler: Kurs wird nicht übernommen

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#137]
Wenn man unter Leistungsdaten einen Kurs in der Spalte "Kurs" ausgewählt hat, werden die Daten des Kurses (Lehrkraft, WZE, etc.) nicht übernommen.

**Comment by FPfotenhauer** [comment]
Wird korrigiert.

**Comment by JuergenRichter** [comment]
Ist korrigiert
