### ISSUE TITLE
"Stil" und "Symbole" funktionieren nicht

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#138]
Die individuellen Einstellungen "Benutzeroberfläche-> Stil und Symbole" werden bei jedem Neustart auf "Luna" und "Blue" zurückgestellt.

![Bild1](https://user-images.githubusercontent.com/79116896/114087646-6c185000-98b4-11eb-9df6-33214e367ed3.png)

**Comment by FPfotenhauer** [comment]
Hat der Rechner irgendwie eine Wächter-Karte oder sowas?

**Comment by AnneSchueller** [comment]
Ich habe das jetzt nochmal auf einem anderen Rechner getestet und da funktioniert alles. Es scheint also tatsächlich an meinem Rechner zu liegen. Ein PC-Wächter ist allerdings nicht installiert.
