### ISSUE TITLE
Tippfehler

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#139]
![Bild2](https://user-images.githubusercontent.com/79116896/114094950-30ce4f00-98bd-11eb-9fa1-b14d8bb3618f.png)
![Bild3](https://user-images.githubusercontent.com/79116896/114094965-34fa6c80-98bd-11eb-9e71-175b5604f334.png)
![Bild4](https://user-images.githubusercontent.com/79116896/114094978-375cc680-98bd-11eb-9b87-e2e8f1caaa38.png)
![Bild5](https://user-images.githubusercontent.com/79116896/114094987-39268a00-98bd-11eb-9236-43404e3d71a4.png)

**Comment by FPfotenhauer** [comment]
Danke!

**Comment by JuergenRichter** [comment]
Alles korrigiert
