### ISSUE TITLE
Menüs in Verwaltung -Version 3.0.5.1

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#14]
Bei Anwahl der "Verwaltung" stehen mehrere Menüs zur Auswahl. Bei Anwahl eines dieser Menüs entstehen im mittleren Fenster weitere Untermenüs mit einem Rollbalken an der rechten Seite. Diesen kann man nicht betätigen. Auch bei Betätigung des Rollrades der Maus keine Reaktion. 
Daher sind manche Untermenüs (z.B. bei Werkzeuge) nicht sichtbar.

**Comment by FPfotenhauer** [comment]
Der Scrollbalken funktioniert nur mit dem Scrollrad, mit der Maus kann man ihn nicht "anfassen".

**Comment by me-rfb2000** [comment]
Man sollte aber den Rollbalken mit der Maus anfassen können-> ist ein Windows-Standard!

**Comment by ADV-Fendel** [comment]
Wenn ich unter "Verwaltung">"Einstellungen" Veränderungen im Bereich Interface vornehme und dann in das Menu "Schüler" wechsel, bleibt ein Rollbalken, der sich mitten durchs Bild zieht und erst dann wieder weg geht, wenn ich das Programm neu starte.

**Comment by WLey-49** [comment]
In Version 3.0.8.1 heißt dieser Bereich jetzt "Benutzeroberfläche".
Das Problem "senkrechter Rollbalken in der Bildmitte" ist aber nach wie vor da.

**Comment by WLey-49** [comment]
Auch in der Version 3.0.10.3 gibt es immer noc h den Rollbalken im mittleren Bereich.

![Rollbalken](https://user-images.githubusercontent.com/62895389/107145096-afe7eb00-693f-11eb-92b2-15399b75a45b.JPG)

**Comment by FPfotenhauer** [comment]
Bei mnir tritt da simme rdann auf, wenn Theme und Icons gewechselt wurde.
Nach einem Neustart ist das dann weg.
Bei Wechsel des Themes kann meinetwegen auch nach einem Neustart gefrat werden...

**Comment by WLey-49** [comment]
Bei mir erscheint der Rollbalken bei mehreren Aktionen im Einstellungsmenü. Jetzt gerade z.B. bei
"Verwaltung --> Einstellungen --> Fächer/Noten" und von dort Rücksprung auf den Menüpunkt "Schüler".
