### ISSUE TITLE
Unterrichtsdaten als Excel-Datei importieren

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#141]
Unter Verwaltung/Import/Unterrichtsdaten (als Excel-Datei) fehlt die Verlinkung der Schaltflächen "Informationen anzeigen" und "Beispieldatei ansehen".

**Comment by FPfotenhauer** [comment]
Ist bei mir alles zu sehen?

**Comment by JeVaske** [comment]
Bei mir sind die Buttons nicht aktiv. Ich nutze Version 3.0.14.3 vom 21.4.21)
![schildfehlerunterrichtsimport](https://user-images.githubusercontent.com/78501680/115596514-7c7af280-a2d8-11eb-92bb-0889b67ba472.jpg)
:

**Comment by FPfotenhauer** [comment]
Ich weiß nicht, ob es da eine Bedingung gibt, aber bei mir sind die nicht ausgegraut.

**Comment by JuergenRichter** [comment]
Das wird durch das Vorhandensein der Dateien "Excel_Unterrichtsimport.txt" und "Beispiel_Unterrichtsimport.xls" (im Programmverzeichnis) gesteuert. Diese sind wohl im Setup vergessen worden. Wenn man die aus einer SchILD2-Installation kopiert, sollten die Schalter aktvierbar sein.

Vielleicht wäre zu überlegen, ein separates Verzeichnis für solche Art von Dateien zu verwenden. Alles wird sich nicht im Programmcode unterbringen lassen.

**Comment by FPfotenhauer** [comment]
Ich habe die Dateien jetzt in den Installer gepackt.
