### ISSUE TITLE
Lehrkräfte "Sichtbare Datensätze zeigen" "Alle zeigen"

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#142]
Die Filtermöglichkeit "Sichtbare Datensätze zeigen" "Alle zeigen" unter dem Reiter "Lehrkräfte" funktioniert bei mir nicht ordentlich. Lehrer, die sich in meiner DB befinden kann ich nicht reaktivieren, wenn auf den Leuchtturm klicke. Die Lehrer, die ich vor 3 Minuten unsichtbar gemacht habe, lassen sich auch nicht mehr reaktivieren. Nur der Lehrer, den ich zum Schluss unsichtbar gemacht habe, lässt sich reaktivieren.

**Comment by JuergenRichter** [comment]
In Version 3.0.15 behoben
