### ISSUE TITLE
Fehler bei Gruppenprozesse: Details zu Fächern ändern

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#144]
Bei Filter auf eine Klasse und Gruppenprozesse "Fächer" > "Details zu Fächern bei Schülern ändern" kann ich in der Fächerliste keine Fächer wählen (siehe Screenshot):
![2021-04-15 15_49_06-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2020_2021, 2  Hj, Ben](https://user-images.githubusercontent.com/27292550/114881529-6619f600-9e03-11eb-9b14-575d5f93ecad.png)
Nachdem ich ein Fach und ein Lehrerkürzel für die Änderung in den entsprechenden Feldern eingegeben habe, fehlt mir ein Button, mit dem ich die Änderung bestätigen kann.
Wenn ich dann noch mal auf den Button "Details zu Fächern bei Schülern ändern" klicke, erscheint die folgende Fehlermeldung:
![2021-04-15 16_00_06-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2020_2021, 2  Hj, Ben](https://user-images.githubusercontent.com/27292550/114881959-c1e47f00-9e03-11eb-8b30-ec458c151099.png)

**Comment by JuergenRichter** [comment]
In 3.0.14.3 behoben
