### ISSUE TITLE
Fehlermeldung bei Gruppenprozesse "Lernbereichsnoten eingeben"

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#145]
Bei Auswahl des Gruppenprozesses "Noten, Zeugnisvorbereitung" > "Lernbereichsnoten eingeben" erscheint die folgende Fehlermeldung:
![2021-04-15 16_03_05-Aktuelle Datenbank_ SCHILD2000n_GE_anonymisiert, Schuljahr 2020_2021, 2  Hj, Ben](https://user-images.githubusercontent.com/27292550/114882603-68c91b00-9e04-11eb-890a-44a0da6d387f.png)

**Comment by JuergenRichter** [comment]
In Version 3.0.14 behoben
