### ISSUE TITLE
Eingabe Erzieherdaten

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#15]
Ein sehr alter Wunsch bzgl. der Eingabe der Erzieherdaten ist folgender:
Bei Anwahl von Mutter oder Vater sollte unbedingt die Eingabe der 2. person gesperrt werden. Grund: Es ist immer wieder festzustellen, dass Serienbriefe nicht funktionieren, wenn die Erzieherdaten fehlerhaft eingetragen  wurden.
Besser noch: Im Katalog "Erzieherarten" eine Spalte mit der Möglichkeit des Eintrages "1 Person"/"2 Personen". Diese ggf. durch Admin ausführen lassen.

**Comment by WLey-49** [comment]
Gibt es hierzu neue Informationen?

**Comment by JuergenRichter** [comment]
Das ist jetzt so gelöst:
Beim Speichern wird geprüft ob "Mutter" oder "Vater" in der Erzieherart vorkommt. Wenn dann ein Eintrag bei der 2. Person vorhanden ist, wird eine Meldung ausgegeben "Bei der Erzieherart "Mutter" sollte keine 2. Person eingetragen werden, da dies zu Problemen z.B. bei Serienbriefen führen kann. Trotzdem speichern?"
(beim Vater kommt natürlich "Vater" als Erzieherart). Das ist nicht ganz so "radikal" wie die komplette Sperrung.

**Comment by JuergenRichter** [comment]
Frage dazu: Soll die Meldung grundsätzlich beim Speichern kommen oder nur, wenn ein Erzieherdatensatz neu eingegeben wurde?
