### ISSUE TITLE
Indioviduelle Einstellungen zurücksetzen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#150]
Dieses Feature sollte darauf geprüft werden, welche Fenster und Einstellungen noch zurückgesetzt werden müssen.
Die Reporting ist ja z.B. kein Fenster mehr.

**Comment by JuergenRichter** [comment]
Die Breiten der Spalten im Reportexplorer werden jetzt begrenzt (in Abhängigkeit von der Bildschirmbreite), dass eine Spalte den gesamten Platz ausfüllt, sollte nicht mehr vorkommen.
