### ISSUE TITLE
Problem bei Migration mit MigrateDB.exe

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#151]
Bei der Wahl des Pfades zur Datenbank innerhalb des Ordners "Dokumente" kommt die im angegeben Fenster dargestellte Fehlermeldung. Es ist dabei gleichgültig, ob der Pfad direkt (E:\Dokumente/....) oder über (C:\users\Name\Dokumente/....) angegeben ist. Offensichtlich muss die Datenbank in einem Ordner unterhalb von X:\SchILD-NRW liegen.
![Fehler bei Migration](https://user-images.githubusercontent.com/62895389/115541756-cbf0fc80-a29f-11eb-8876-e9f9985ccae9.JPG)
![Fehler bei Migration-2](https://user-images.githubusercontent.com/62895389/115541782-d0b5b080-a29f-11eb-91bf-6db5331d2907.JPG)

**Comment by FPfotenhauer** [comment]
Es könnte an den Anführungszeichen liegen. Prüfen wir nochmals.

**Comment by GerhardHordt** [comment]
Könnte es vielleicht auch daran liegen, dass der Ordner "Documents" ein Windows-Systemordner ist?

**Comment by JuergenRichter** [comment]
Das Problem trat dann auf, wenn im Pfadnamen Leerzeichen vorkamen. Ist nun behoben.
