### ISSUE TITLE
FHR-Algorithmus liefert Zugriffsverletzung

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#154]
Bei mir (WBK) funktioniert der FHR-Algorithums leider nicht:
![image](https://user-images.githubusercontent.com/75179015/115995498-d67eff00-a5db-11eb-89d2-e2890df8b324.png)

**Comment by Kluesenerm** [comment]
Fehler besteht in der aktuellsten Version immer noch.

**Comment by WLey-49** [comment]
In der Version 3.0.15.3 vom 22.5.21 klappt bei mir jetzt die FHR-Berchnung.

**Comment by JuergenRichter** [comment]
Ich kann das Problem mit meiner Testdatenbank ebenfalls nicht reproduzieren. Bitte mal ein Fehlerprotokoll zur Verfügung stellen.

**Comment by JuergenRichter** [comment]
Scheint ein WBK-Problem zu sein. Ich muss mal eine WBK-DB nach SchILD3 migrieren.

**Comment by JuergenRichter** [comment]
Habe nun eine WBK-DB migriert, Fehler tritt nun auch bei mir auf. Das Fehlerprotokoll wird also nicht benötigt.

**Comment by JuergenRichter** [comment]
Behoben.
