### ISSUE TITLE
Felder für Bemerkungen Größe und Position

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#155]
Wenn ich  beim Schüler im Bereich Aktuelles Halbjahr den Reiter Bemerkungen aufrufe, ist das Feld für das Arbeits- und Sozialverhalten zu klein - im Vergleich zu den anderen Feldern.

**Comment by FPfotenhauer** [comment]
Hier wäre ein Screenshot hilfreich.

**Comment by ADV-Fendel** [comment]
[Feld Arbeits- und Sozialverhalten.pdf](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6392043/Feld.Arbeits-.und.Sozialverhalten.pdf)

**Comment by FPfotenhauer** [comment]
Sollte behoben sein.
ggf. werden die Felder noch anders positioniert.
Das Ein-/Ausblenden funktioniert momentan noch nicht.

**Comment by FPfotenhauer** [comment]
Ein Vorschlag wäre auch, die Bemerkungen auszugrauen, wenn nicht beim Schüler einzugeben.

**Comment by FrodBRA** [comment]
Das Fenster sieht so nicht mehr aus. ASV erscheint wie alle anderen Bemerkungen und wirkt nutzbar.

Ist das Issue damit noch aktuell?

**Comment by AnneSchueller** [comment]
Danke für das Nachsehen! Die Ansicht ist tatsächlich veraltet
