### ISSUE TITLE
Felder für Mehr- oder Minderleistungen bei Lehrkräften zu groß

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#156]
Wenn ich bei den Lehrkräften im Bereich Zeitabhängige Daten die Reiter Mehrleistung oder Minderleistung aufrufe sind die Spalten der nachfolgenden Tabelle zu groß, sodass die letzte Spalte nicht mehr zu sehen ist und nur durch den Schieberegler zu erreichen sind. Unter dem Reiter Nichtunterrichtliche Tätigkeiten ist die Aufteilung besser. In alle Tabellen ist die erste Spalte auch nicht beschriftet, beinhaltet aber die Kürzel der ASDPC.

**Comment by FPfotenhauer** [comment]
Können wir momentan nicht mehr nachvollziehen.
Ggf. nochmal wieder aufmachen und dann bitte einen Screenshot posten.
