### ISSUE TITLE
Bei Fensterskalierung passiert nichts

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#157]
Wenn ich in Verwaltung den Bereich Einstellungen wähle und in den individuellen Einstellungen die Prozentangaben zur Skalierung der Fenstergröße verändere passiert nicht, auch nicht, wenn ich das Programm mit den Veränderungen neu starte.

**Comment by FPfotenhauer** [comment]
Ich kann das Verhalten bestätigen.

**Comment by FPfotenhauer** [comment]
Hat sich erledigt.
