### ISSUE TITLE
Nur zuletzt migrierte Datenbank wird aufgerufen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#158]
Wenn mehrere Datenbanken migriert werden, so werden diese auch als Auswahl angezeigt wie bei Schild 2.0 gewohnt.
Allerdings wird immer die zuletzt migrierte Datenbank aufgerufen!
![grafik](https://user-images.githubusercontent.com/44644567/116827080-a0232000-ab97-11eb-8df6-8eeaa479a269.png)

Aus den sdbcfg Dateien geht hervor, dass diese identisch sind.
Muss für jede Datenbank ein eigenes Schema angelegt werden oder ist die Datenbank wie bei Schild-Zentral mandantenfähig??
Wenn ein vorhandenes Schema überschrieben wird, müsste zumindest gewarnt werden, wenn bei der Migration bestehende Daten gelöscht werden.

**Comment by FPfotenhauer** [comment]
Es muss für jede Datenbank ein neues Schema angelegt werden.
Der SVWS-Server ist dadurch mandantenfähig! Und zwar datenschutzkonform!
