### ISSUE TITLE
Zugriffsverletzung nach Umstellung  der Windowsskalierung

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#159]
Wenn unter Windows Einstellungen/Anzeige die Skalierung umgestellt wird,
wirft Schild 3.0 eine Zugriffsverletzung.
![grafik](https://user-images.githubusercontent.com/44644567/116936761-91586e00-ac68-11eb-9119-c3b95bae9089.png)
![grafik](https://user-images.githubusercontent.com/44644567/116936780-95848b80-ac68-11eb-8f97-bf2b570277e9.png)

**Comment by FPfotenhauer** [comment]
Prüfen wir nochmal.
Bitte auch einmal das Fehlerprotokoll senden.

https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=26&t=89

**Comment by EwaldReinhardt** [comment]
Der Fehler tritt immer noch auf.
[FehlerProtokollSkalierung.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6900651/FehlerProtokollSkalierung.txt)

**Comment by JuergenRichter** [comment]
Wir haben eine Anpassung gemacht, bitte im nächsten Update nochmal testetn (kann es selbst nicht reproduzieren).
