### ISSUE TITLE
Erzieher Anrede

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#161]
![SNAG_2021_05_06_16 38 49](https://user-images.githubusercontent.com/34127980/117317260-a52eea80-ae89-11eb-90dc-680cd3559e34.png)

Auch schon in Schild2.0 kann man bei den ErzieherAnreden einfach etwas tippen, was dann gespeichert wird.
Ist das so gewollt?

Häufig führt das dazu, dass in der Reporting oder in WordSerienbriefen die Anrede nicht klappt, weil z.B. ein Leerzeichen hiert "Frau " ist.

**Comment by JuergenRichter** [comment]
Das war so gedacht, dass man da in Spezialfällen auch andere Einträge als die in der Auswahlliste machen kann. Kann man aber auch auf die Liste begrenzen, dann sollte man aber überlegen, was da rein soll (divers?).

**Comment by FPfotenhauer** [comment]
Dann lassen wir das zunächst einmal, wie es ist.
