### ISSUE TITLE
Kreuztabellen Statistik

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#162]
In der Basissammlung sind einige Kreuztabellen für Statistiken drin.
Die liefern in der Schild3.0 Reporting immer nur einen Wert für den markierten Schüler!

![SNAG_2021_05_06_16 46 48](https://user-images.githubusercontent.com/34127980/117318555-d22fcd00-ae8a-11eb-908c-423de81a1b2d.png)

**Comment by FPfotenhauer** [comment]
Wird nochmal geprüft.

**Comment by JuergenRichter** [comment]
Ich kann das Problem nicht reproduzieren. habe es mit dem Report "Statistik Kreuztabelle Klassen.rtm" (Dateidateum 22.11.2020) gestestet, da funktioniert es m.E. einwandfrei.
