### ISSUE TITLE
Fehlermeldung nach Klick auf alle Reiter

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#163]
Ich habe mal einen Kurs gefiltert.
Dann bin auch auf alle Reiter gegangen Gruppenprozesse, Auswahl, Reporting, zurück auf Auswahl, zurück auf Gruppenprozesse...

![SNAG_2021_05_22_12 21 05](https://user-images.githubusercontent.com/34127980/119223210-67bc9500-baf8-11eb-8388-efcdab67ad09.png)
[Errorlog.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6526220/Errorlog.txt)

**Comment by FPfotenhauer** [comment]
Nachtrag:
Wenn ich keinen Kurs filtere, dann kommt der Fehler nicht.

**Comment by JuergenRichter** [comment]
In 3.0.16 behoben
