### ISSUE TITLE
Menü/Funktionen in FHR und Abitur

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#164]
![grafik](https://user-images.githubusercontent.com/84628225/119234787-ed0f6c00-bb2f-11eb-96a3-8d19f86d7dfb.png)

![grafik](https://user-images.githubusercontent.com/84628225/119234916-5d1df200-bb30-11eb-8e5d-435de7f54ae6.png)

In den Reitern FHR und Abitur sind die "Untermenüpunkte" wie z.B. "Leistungsdaten holen" schwarz oder nur nach Überstreichen mit dem Mauszeiger zu erkennen, dann überschneiden sich die Texte aber oft.

**Comment by FPfotenhauer** [comment]
Sollte mit der neuen Skalierung behoben sein.
