### ISSUE TITLE
Schülerfotos werden nach wie vor nicht angezeigt (s. Issue #61)

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#166]
Bei mir werden die Schülerfotos noch immer nicht angezeigt (jpg). Bei den Schülern werden identische Fotos angezeigt.

**Comment by JuergenRichter** [comment]
Auf meinem (schnellen) Entwicklungsrechner kann ich das nicht reproduzieren. Ich habe mir aber heute alles mal auf einem ziemlich normalen Notebook installiert. Werde mir da mal eine Klasse mit Fotos einrichten.

**Comment by JuergenRichter** [comment]
Habe jetzt mal eine Klasse mit Fotos versehen, Anzeige ist immer korrekt. Frage:
Wie große (in Pixel) sind die verwendeten Fotos?

**Comment by Raffenberg** [comment]
Hallo Herr Richter,
ich hatte Ihnen ja ein Video zu dem Phänomen zugesendet. Die Fotos liegen mir hochaufgelöst als jpg vor, werden von einem Programm im Batch-Prozess auf 276x414px skaliert und als .jpg gespeichert und mit Schild-Foto nach Schild eingelesen.
Ich hatte diese Originaldatenbank für Schild3 verwendet (normaler Importvorgang in die SQL-Datenbank über das Installationstool).

**Comment by Raffenberg** [comment]
Eionzelplatzrechnerinstallation, i5 CDU, Windows 10, Full HD Monitor, nichts besonderes für die Darstellung.

**Comment by JeVaske** [comment]
Die Fotos werden bei mir auch nicht immer aktualisiert, wenn ich verschiedene SuS durcheinander anklicke. An der Größe der Fotos kann es bei mir auch nicht liegen. Bei Schild 2.0 funktioniert es einwandfrei.

**Comment by FPfotenhauer** [comment]
Prüfen wir nochmals.

**Comment by JuergenRichter** [comment]
Ursache ist gefunden, Lösung in Arbeit.

**Comment by JuergenRichter** [comment]
Problem sollte in Version 3.0.19.5 behoben sein.
