### ISSUE TITLE
Aufruf schwebendes Fotofenster verscheibt Hauptfenster

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#167]
Ich öffne Schild und maximiere das Fenster. Wenn ich das schwebende Schülerfenster öffneun den Schüler wechsel, verschiebt sich das Hauptfenster so, dass der linke Teil nicht mehr zu erkennen ist.

**Comment by JuergenRichter** [comment]
Ich kann die genannten Foto-Probleme nicht reproduzieren. Ich habe bei mir eine alte Datenbank gefunden, in der fast alle SuS auch Fotos haben. Da funktioniert alles wie es soll.

**Comment by Raffenberg** [comment]
https://user-images.githubusercontent.com/48889965/124836562-73b6c600-df83-11eb-861b-486c44d908ef.mp4

**Comment by FPfotenhauer** [comment]
Das könnte damit zusammenhängen, dass dem Hauptfenster die Eigenschaft "maximieren" genommen wird.

**Comment by Raffenberg** [comment]
Ein Klick auf Schüler -> Individualdaten I -> Bemerkungen hat den gleichen Effekt (v. 3.0.32.7)

**Comment by Raffenberg** [comment]
Mir ist aufgefallen, dass dieses Phänomen immer auftritt, wenn man von einem schwebenden Fenster oberhalb des Hauptfensters zurückkehrt. Auch nach dem Start von Schild 3 ist das Programm immer im nicht maximierten Modus und nach links verrückt.
