### ISSUE TITLE
Verschwenderische Katalogansicht

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#168]
Ich finde, dass die Kataloge nicht effizient angezeigt werden. Im Anzeigebereich ist so viel Platz, dass es eigentlich effizienter wäre, die Kataloge links in einem Übersichtsmenü anzuzeigen, so wie im Menüpunkt Verwaltung.

![kataloge](https://user-images.githubusercontent.com/48889965/119264852-0aead880-bbe5-11eb-8522-05550ff43ade.png)

**Comment by JuergenRichter** [comment]
Wir haben das jetzt testweise mal wie folgt geändert:
Am linken Rand erscheint ein "Backstage-Menü" (ähnlich wie bei "Verwaltung"). Darin werden die "Katalogarten" angezeigt (siehe Screenshot). Diese werden derzeit aber weiterhin nach den Rubriken "Allgemeine Kataloge", "Schulbezogene Kataloge" und "Andere Schulen" aufteilt, d.h. diese Icons im Ribbonband sind weiterhin vorhanden (die daran "hängenden" Untereinträge" könnten dann aber weg). Ich stelle das makzur Diskussion

**Comment by JuergenRichter** [comment]
![Kataloge](https://user-images.githubusercontent.com/61280188/122222837-ef58b200-ceb2-11eb-872c-214ddb1d5644.png)

**Comment by Raffenberg** [comment]
Klappt tadellos und sieht viel besser aus.
