### ISSUE TITLE
Gruppenprozesse aufrufen extrem langsam

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#169]
Das Aufrufen der Gruppenprozesse und das Wechseln zwischen den Reitern der Gruppenprozesse dauert je 8-10 Sekunden.

**Comment by JuergenRichter** [comment]
Es wurden noch einige Optimierungen durchgeführt. Ich habe zum Testen mal SchILD3 auf einem nicht besonders leistungsfähigen Notebook installiert, da läuft es m.E. jetzt recht flüssig.
