### ISSUE TITLE
Abitur-Leistungsübersicht

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#17]
Auf der Karteikarte "Abitur" sehe ich keine Leistungsübersicht (einschließlich Abiturfächer, Durchschnitt usw.) und somit auch keine Markierungen der algorithmisch markierten Kurse.

**Comment by FPfotenhauer** [comment]
![SNAG_2020_12_01_17 12 53](https://user-images.githubusercontent.com/34127980/100766049-7dc68400-33f8-11eb-8122-d2c42d1b30c2.png)

**Comment by WLey-49** [comment]
Ich stelle gerade fest, dass ich das Bild jetzt auch sehe, aber nur dann, wenn ich auf Vollbild schalte (Auflösung am Laptop: 1366x768). Ich kann dann aber noch nicht einmal eine Zeile lesen, weil alle Zeilen nur halb zu sehen sind.
Ich würde gerne das entsprechende Bild anhängen, finde aber hier keine Möglichkeit des Einfügens.

Die Darstellung der Abiturseite ist insgesamt leider unbrauchbar, weil das schmale Fenster in der Mitte keine Übersicht über alle Fächer liefert. Das Fenster kann man aber nicht vergrößern. Die Benutzung des Rollbalkens ist nicht sinnvoll möglich.
Hier muss meiner Meinung nach unbedingt eine andere Fensteranordnung gefunden werden. Das mittlere Fenster muss vollständig sichtbar sein.

**Comment by JuergenRichter** [comment]
Wir werden das überarbeiten.

**Comment by FPfotenhauer** [comment]
Ich habe gerade die Version 3.0.6 in die FBCloud hochgeladen.
Darin sieht der Abiturreiter m.M. nach sehr gut aus.
@Wolfgang: Bitte einmal testen und ggf. das Issue schließen.

**Comment by WLey-49** [comment]
Die Seite sieht jetzt gut aus. Leider sind aber die Fenstergrößen nicht änderbar, so dass auf meinen Bildschirm die unteren Fenster "Weitere Angaben" und "Auswertung" nur sichtbar sind, wenn ich mit der Maus nach unten rolle.
Es müssten aber zur Übersicht alle Fenster komplett zu sehen sein.

![Abimaske](https://user-images.githubusercontent.com/62895389/100915021-24338780-34d4-11eb-8203-1a160106c08f.JPG)

**Comment by JuergenRichter** [comment]
Wir werden noch einen "Splitter" einbauen, mit dem man die Bereiche vertikal in der Größe anpassen kann

**Comment by FPfotenhauer** [comment]
Aus dem FHR ISSUE hierher kopiert:
Stimmt. Sorry! Aber jetzt sind die Ergebnisse in der Gesamtschau nicht sichtbar. Ich muss scrollen. Kann das Feld nicht nach rechts vergrößert werden? So ist es ganz ungünstig.
![image](https://user-images.githubusercontent.com/75179015/101259187-a4056000-3727-11eb-9ebd-3ddb1d38afb6.png)

**Comment by JuergenRichter** [comment]
Das liegt im konkreten Fall an der Einstellung der Spaltenbreiten. Wenn man die schmaler macht, sieht man alle Spalten. Die eingestellte Spaltenbreite "merkt" sich das Programm beim Beenden, bei Neustart wird das dann aus der Registry geladen.

**Comment by FPfotenhauer** [comment]
Die Spalte für die Facharbeit (nur BK) wird auch bei GE und GY eingeblendet.

**Comment by JuergenRichter** [comment]
In Version 3.0.8 behoben
