### ISSUE TITLE
Verwaltung Schriftgröße

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#170]
Der Menüpunkt Verwaltung sitzt sehr weit links. Innerhalb der Verwaltung sind die Menüpunkte so weit auseinander, dass man ausladende Mausbewegungen machen muss, was die Treffsicherheit verringert. Ich würde mir hier die gleichen Abstände und Schriftarten wünschen, wie überall im Rest des Programms auch.

**Comment by JuergenRichter** [comment]
Im Rahmen der vorgeschlagenen Anpassung für die Kataloge haben wir auch das Erscheinungsbild des Backstage-Menüs für die Verwaltung angepasst.
![Verwaltung](https://user-images.githubusercontent.com/61280188/122233902-b7566c80-cebc-11eb-97ae-67666a0635bd.png)

**Comment by Raffenberg** [comment]
Ich finde es viel besser.
