### ISSUE TITLE
Gitternetzlinien in tabellarischen Ansichten

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#172]
Ich würde mir in tabellarischen Ansichten Gitternetzlinien wünschen. Es fällt in der Gitterlosen Ansicht schwer, die Übersicht zu behalten. Zudem würde ich mir wünschen, wenn man in der Leistungsübersicht der Schüler alle Angaben ändern könnte.

**Comment by JuergenRichter** [comment]
Die Gitterlinien können doch über die Programmeinstellungen festgelegt werden. Funktioniert das nicht?

**Comment by Raffenberg** [comment]
Die Einstellung hatte ich gesucht und nicht gefunden. Ich werde nochmals suchen und dann testen.

**Comment by Raffenberg** [comment]
In Version 3.0.16.3 habe ich das Phänomen immer noch. Ich habe Schild 3.0 neu installiert, eine DB migriert und dann aufgerufen. Die Gitterlinien werden nicht angezeigt, obwohl diese in den Einstellungen aktiviert sind. Erst nach dem Deaktivieren und Aktivieren werden die Gitternetzlinien angezeigt.

**Comment by FPfotenhauer** [comment]
Es sieht so aus, als ob sich beim Start nicht die korrekten Einstellungen für diese Parameter geholt werden.
Wenn man die Einstellungen aufruft, danach erscheinen die Linien.

**Comment by JuergenRichter** [comment]
Ist nun korrigiert. Das kam daher, dass vorher die Einträge in der Registry gespeichert wurden (und daher schon vor Auswahl einer Datenbank gelesen werden konnten), nun aber in der Datenbank. Das Auslesen der Einstellung darf jetzt erst nach Auswahl der DB erfolgen (was nun geschehen ist).
