### ISSUE TITLE
Infofenster in den Werkzeugen der Verwaltung

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#173]
Ich würde mir schwebende Informationsfenster am Mauszeiger wünschen, welche einem verraten, was für eine Funktion hinter den Werkzeugen steckt. Die Begriffe sind selten selbsterklärend.

**Comment by FPfotenhauer** [comment]
Informationen werden noch verbessert.

**Comment by JuergenRichter** [comment]
Bitte mal in der Version 3.0.18.5 anschauen
