### ISSUE TITLE
Fensteraufteilungen unnötig aufgespalten

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#174]
Ich finde die Karten, auf denen sich die Informationen befinden sehr übersichtlich. Allerdings finde ich, dass es viel zu viele leere, ungenutzte Flächen gibt, welche man effizienter nutzen könnte, um Reiterwechsel zu vermeiden und den Überblick zu erhöhen. Während die Reiter in der alten Version wegen der kleinen Monitore notwendig waren, sollte man in der neuen Version dazu übergehen, diese zusammenzuführen. Dank der großen Monitore sind Unterreiter oftmals obsolet, werden aber immer noch verwendet. Mir fallen z.B. ad hoc folgende Punkte auf
- In der Verwaltung finden sich die Informationen zur Schule in vier Untermenüs, welche man locker zusammenfassen könnte Allgemeine Angaben, Gliederung, Teilstandorte und Merkmale). Warum es eine Vorschau gibt, erschließt sich mir nicht.
-  Bei den Lehrkräften würden die Basisdaten und die Schulbezogenen Daten auf einen Reiter passen.
- Bei den Lehrkräften wäre ein direkter Zugriff auf die zeitabhängigen Daten "Mehrleistung", " Minderleistung" etc. ohne Reiter leicht möglich, so wie in ASDPC. Das würde auch die Übersicht erhöhen.
- Bei den Lehrkräften wäre eine Asnicht der Zeitabhängigen Daten wie bei den zeitabhängigen Daten der Schüler unter akt. Halbjahr (wo links die Halbjahre angezeigt wäre) sinnvoll.
- Man könnte manche Schülerreiter zusammenfassen. Viele sind sehr leer, oder es ist genug Platz (Individualdaten I und II, Fördermaßnahmen zum akt. Halbjahr, DSGVO und Laufbahninfo zusammenlegen)
- Insbesondere auf dem Reiter akt. Halbjahr liegen die Informationen jetzt noch verstreuter, statt dass sie zusammengelegt werden (z.B. Leistungsdaten, Bemerkungen, Abschlussberechung)
- manchmal sind die Fenster viel zu breit für den Inhalt (Laufbahninfo, DSGVO
- auf dem Reiter Schüler-Auswahl muss man zur Auswahl der Unterreiter (z.B. Individualdaten I, Individualdaten II etc.) die Schaltfläche nach rechts anklicken, da nicht alle sichtbar sind.

**Comment by JuergenRichter** [comment]
Das möchte ich jetzt nicht allein entscheiden. Manche Punkte sind sicher berechtigt, allerdings muss man auch bedenken, dass der Platz, der bei der einen Schulform leer erscheint, bei einer anderen Schulform Angaben enthält.
