### ISSUE TITLE
Reiter Auswahl - Ribbon verwirrend

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#175]
Auf dem Reiter Auswahl sind die Ribbonmenüpunkte nicht benannt und verwirrend angeordnet. Teilweise kann man nicht erkennen, was sich hinter den Schaltflächen versteckt, weil die Schaltflächennamen unkenntlich gekürzt wurden (Abschnitt (Aktiv, Extern). Hier müsste besser gruppiert und getrennt werden.

Man befindet sich in Filter I nach dem Aufruf. Das entsprechende Element im Ribbon wird aber nicht hervorgehoben. Klicke ich auf Filter II, so kommt doch ein Schwebefenster, anstatt dass der Inhalt in der Freifläche angezeigt wird.

**Comment by FrodBRA** [comment]
Ist das Issue noch aktuell? Der Filter II scheint gar nicht mehr vorgesehen zu sein, die übrigen Schaltflächen wirken in der aktuellen Version in Ordnung.
