### ISSUE TITLE
Verwaltung - zu viele schwebende Fenster

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#176]
Überall sind die schwebenden Fenster in die Oberfläche integriert worden. Insbesondere in der Verwaltung kommen sie jedoch noch andauern vor. So z.B. beim Export für das externe Notenmodul. Hier würde ich mir überall eine Integration in die Schild-Oberfläche wünschen.

**Comment by JuergenRichter** [comment]
Wir haben nun weitere "schwebende" Fenster in die Programmoberfläche integriert (Notenexport, Schnittstellenexport, Filter II usw.), weiter kommen kurzfristig dazu. Das macht m.E. aber nur Sinn, wenn das Fenster eine bestimmte Größe hat, bei Fenstern, die eher Dialogcharakter haben oder nur wenige Eingabeoptionen haben, sieht das etwas komisch aus, wenn die verloren auf der großen Fläche rumliegen.

**Comment by FrodBRA** [comment]
Das Issue scheint nicht mehr aktuell, nahezu alles in Verwaltung ist in die Oberfläche integriert.

**Comment by AnneSchueller** [comment]
Ich schließe das mal. Evtl. könnte man noch das ein oder andere schwebende Fenster reduzieren, wenn mal alles soweit läuft.
