### ISSUE TITLE
Durchdachterer Export für die Schulstatistik

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#177]
In der Verwaltung kann man auf die Statistik für IT.NRW klicken. Ich würde mir wünschen, dass der Export der Sim.txt, der LID.txt, der UVD.txt und der ABI.txt in einem Rutsch erledigt werden kann, indem einfach im rechten Fenster Auswahlfelder angezeigt werden, welche dauerhaft gespeichert werden und dann die Dateien in einem Rutsch erzeugen.

**Comment by JuergenRichter** [comment]
Das ist jetzt wie in den Screenshots geregelt:
![statistik_export1](https://user-images.githubusercontent.com/61280188/122404689-b9353400-cf7f-11eb-8fa0-b9e7f00716d7.png)
![statistik_export2](https://user-images.githubusercontent.com/61280188/122404711-bdf9e800-cf7f-11eb-91f1-1ac2c59ee458.png)

**Comment by JuergenRichter** [comment]
Zur Erläuterung: Wenn "Datenexportieren" aktiviert wird, erscheint das Fenster mit den Optionen separat (wie bisher), mit der Ergänzung, dass dort die Dateiarten gewählt werden können.
