### ISSUE TITLE
Position der Abiturfächerspalte auf der Karteikarte Abitur

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#178]
Die mittige Position der Abiturfächer halte ich mitten zwischen den Punktzahlen) für unglücklich (Grund: Mir ist es passiert, dass ich auf die Schnelle bei einer Kontrolle die Nummer des Abiturfaches als Punktzahl mitgezählt hatte).
In der alten Schildversion kann man die Spalten verschieben. Dies sollte auch hier so sein oder es sollte die Spalte mit den Abiturfachnummern an die erste Position.
![Spalten Abiturkarten](https://user-images.githubusercontent.com/62895389/119662072-437ef200-be31-11eb-975f-80902022a757.JPG)

**Comment by FPfotenhauer** [comment]
Wird wieder kommen.

**Comment by JuergenRichter** [comment]
Spalten Im Abiturgrid können wieder verschoben werden
