### ISSUE TITLE
Hochrechnung Abitur

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#179]
Es gibt (neuerdings in Version 3.0.15.3?) einen Gruppenprozess "Hochrechnung durchführen und Speichern". Der wurde aus gutem Grund seinerzeit aus Schild2 entfernt. Ich plädiere dafür, eine Hochrechnung nicht in der aktuellen Datenbank vorzunehmen, da dies im Abitur selbst zu fehlerhaften Einträgen führt, wenn unklar ist, ob Einträge durch Hochrechnung oder korrekte Eingaben erfolgten.
Wenn dies tatsächlich bleiben soll (muss?), sollte eine eigene Karteikarte für die Hochrechnung vorhanden sein, damit auf der Original-Abiturseite Fehleingaben vermieden werden.

**Comment by JuergenRichter** [comment]
Ist versehentlich reingerutscht. Der Gruppenprozess wird aber beim BK noch benötigt, da es dort keine LuPO mit der Möglichkeit, das Abitur zu simulieren gibt.
In Version 3.0.16 behoben.
