### ISSUE TITLE
Hochrechnung Abitur

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#18]
Im Gruppenprozess gibt es den Menüpunkt "Hochrechnung durchführen und speichern". Früher gab es den auch mal in Schild-2. Ich meine, dass wir damals zu dem Schluss gekommen sind, eine Hochrechnung nicht an einer Produktivdatenbank durchzuführen. Daher wurde dieser Punkt in Schild-2 herausgenommen.
Sollte das hier nicht auch so sein?

**Comment by FPfotenhauer** [comment]
Anscheindend wurde das in Schild3.0 noch nicht so angepasst.
Das wird nur bei BKs eingeblendet, weil die ja kein Lupo haben.

**Comment by JuergenRichter** [comment]
Ist behoben
