### ISSUE TITLE
Benutzerwechsel: Fehlermeldung

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#180]
Bei Klick auf Benutzer > Benutzer wechseln erscheint die folgende Fehlermeldung
![Benutzer_wechseln-Erro_occurred](https://user-images.githubusercontent.com/27292550/119835961-9de78380-bf01-11eb-8817-511f02a3e35c.png)
Wenn man danach auf Lehrkräfte und anschließend wieder auf Verwaltung klickt, erscheint (offensichtlich) ein Folgefehler:
![2021-05-27 15_40_19-Window](https://user-images.githubusercontent.com/27292550/119836998-7c3acc00-bf02-11eb-85ba-879750d4eab0.png)
Dieser Fehler erscheint aber nur dann, wenn der vorherige Fehler erfolgt ist.

**Comment by JuergenRichter** [comment]
In 3.0.16 behoben
