### ISSUE TITLE
ZP 10 - Gruppenprozesse

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#183]
Kein Fehler, aber eine Anregung: 
Erst nach längerer Suche habe ich die für die ZP 10 notwendigen Gruppenprozesse unter "BK-Abschluss" gefunden. Hier wäre m. E. eine deutlichere Benennung sinnvoll.

**Comment by JuergenRichter** [comment]
Wird korrigiert, die Beschriftung kommt daher, dass die Vorgänge am BK sehr ähnlich sind.

**Comment by JuergenRichter** [comment]
Ist behoben.
