### ISSUE TITLE
Import über die Schnittstelle funktioniert nicht

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#184]
Ich wollte gerade über die Schnittstelle (SchuelerZusatzdaten.dat) die schulischen E-Mail-Adressen der Schülerinnen und Schüler ergänzen und bekomme die folgende Fehlermeldung:
![Schnittstellenimport](https://user-images.githubusercontent.com/78501680/120117028-6be95200-c18b-11eb-86bf-f7e20f533fa5.jpg)

**Comment by JuergenRichter** [comment]
Ich kann das Problem nicht reproduzieren. Bitte bei Problemen immer angeben, welcher Datenbanktyp verwendet wurde. Bitte auch ein Fehlerprotokoll zur Verfügung stellen:
-Copy to Clipboard in Fehlermeldung aktivieren
-Schalter "Details" aktivieren
-Es wird dann das Fehlerprotokoll in die Zwischenablage kopiert, diese per Strg-V in eine Datei kopieren und hier hochladen

**Comment by JeVaske** [comment]
[SchILD30.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6618876/SchILD30.zip)

**Comment by JuergenRichter** [comment]
Danke, Problem ist behoben.
