### ISSUE TITLE
Darstellungsfehler in der Schülerauswahl

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#185]
Wenn ich mit dem Mauszeiger in der "Aktuellen Schülerauswahl" über die Namen fahre, wird ein schwarze Balken über die Namen und Klassenbezeichnung gelegt. Bei manchen SuS ist das auch nur bei der Klassenbezeichnung der Fall. Jedenfalls kann man den Text dann nicht lesen (Die Namen und Klassenbezeichnungen habe ich anonymisiert):
![schwarzer Balken](https://user-images.githubusercontent.com/78501680/120117266-9982cb00-c18c-11eb-865a-82ef6e994e6d.jpg)

**Comment by JuergenRichter** [comment]
Ich konnte das Problem reprodizieren. Habe heute aber eine neue Version der "Grid-Komponente" installiert, dami schient das Problem weg zu sein.

**Comment by FPfotenhauer** [comment]
Sollte behoben sein.
