### ISSUE TITLE
Statistikjahrgänge können nicht bearbeitet werden.

### ISSUE THREAD

**Issue by GHordt** [SVWS-NRW/Schild3-BetaTest#186]
Ich habe eine leere SchILD2.0 Standarddatenbank in SchILD3.0 migriert und gestartet. Bei der Ersteinrichtung werden mir zwar die Statistikjahrgänge angezeigt. Ein Löschen nicht benötigter Jahrgänge ist nicht möglich - sie können nur unsichtbar geschaltet werden.

**Comment by FPfotenhauer** [comment]
Es fehlt schlicht die DB-bavigationsleiste.
Über die Optik der Menüfenster könnte man auch noch reden.
Das Neueinrichten funktioniert aber soweit, wie gehabt.

![SNAG-0001](https://user-images.githubusercontent.com/34127980/127487805-8e2fb13a-9597-4d1e-a0dc-5c77f54b24db.png)

**Comment by FPfotenhauer** [comment]
Ist behoben.
