### ISSUE TITLE
Fehlermeldung beim Ausdruck eines Abschlusszeugnisses

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#187]
Beim Ausdruck eines Abschlusszeugnisses (Gesamtschule - Report ist ziemlich aktuell) erscheint folgende Fehlermeldung. Es kann natürlich sein, dass die (aktuellen) Reports insgesamt noch nicht in SchILD 3.x funktionieren.
![ausdruck_abschlusszeugnis](https://user-images.githubusercontent.com/27292550/121537663-65b56a00-ca04-11eb-82b3-49d8e3296a67.png)

**Comment by FPfotenhauer** [comment]
Hier müssen noch alle Reports auf Schild3.0 angepasst werden.....
