### ISSUE TITLE
FHR Berechnung WBK funktioniert nicht

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#188]
In Schild 2.0 Funktioniert die FHR Berechnung am WBK. In Schild 3.0 nicht. Die Ergebnisse wurden richtig übertragen, aber wenn ich den Algorithmus laufen lassen wird entweder nur jede zweite Zeile ausgewählt und mit Doppelklick lassen sich keine Semester auswählen.

Schild 2.0 (alt):
![image](https://user-images.githubusercontent.com/75179015/123555563-cecc0a00-d786-11eb-8e85-e17ff969f70d.png)

Schild 3.0 (neu mit Absturzfehlermeldung):
![image](https://user-images.githubusercontent.com/75179015/123555579-e4d9ca80-d786-11eb-9155-471203569083.png)

**Comment by FPfotenhauer** [comment]
Bitte nochmals testen, sollte aber behoben sein.
