### ISSUE TITLE
Fehler beim Ausdruck eines Reports

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#189]
Die folgende Fehlermeldung habe ich erhalten (wie bei der Videokonferenz besprochen):
![Fehler_report_01072021](https://user-images.githubusercontent.com/27292550/124127451-03d4a700-da7c-11eb-8060-166004ef76dd.png)
Der Fehler ist bei Ausführung des nachfolgenden Reports aufgetreten:
[Zuweisungen_D_M_E_PH_3.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6748228/Zuweisungen_D_M_E_PH_3.zip)
SchILD 3.0.16.3 vom 25,6,2021

**Comment by JuergenRichter** [comment]
Das Problem sollte in der aktuellen Version 3.0.18.5 behoben sein.
