### ISSUE TITLE
Latinum

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#19]
Bei den Schulungen kommt immer wieder die Bitte der Teilnehmer, (kleines) Latinum durch das Programm analog zur Bestimmung der Sprachenfolge berechnen zu lassen. 
Ist das für Schild-3 geplant?

**Comment by FPfotenhauer** [comment]
Das ist schon seit 4 Jahren beauftragt.

**Comment by FPfotenhauer** [comment]
Wir arbeiten momentan an Bugs, nicht an Erweiterungerungen.
