### ISSUE TITLE
Fehler bei Reports mit eigenen Datenquellen

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#190]
Die folgenden Leistungsübersichten verwenden eigene Datenquellen und erzeugen den im Vortrag vorhergesagten Fehler (Klasse TdaQueryDataView nicht gefunden)

Die Reports stehen den Schulen auch über SVWS Webseite zur Verfügung und dürften daher an diversen Schulen Verwendung finden.

[Leistungsübersichten-mit-eigenen-Quellen.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6748593/Leistungsubersichten-mit-eigenen-Quellen.zip)

**Comment by FPfotenhauer** [comment]
Das wird das Problem mit den ADo > Uni sein.
Ich gucke mir das mal an....

**Comment by FPfotenhauer** [comment]
Ggf. kann man das automatisiert ändern lassen.
Kann Herr Richter bitte einmal testen.

**Comment by FPfotenhauer** [comment]
Alle Reports mit eigenen Datenquellen müssen überarbeitet werden.
Man sollte mal einen einfachen Report mit eigener datenquelle anlegen.
Dann ggf. neuere Reprots erstellen und nach und nach testen.
Deshalb schließe ich dieses Issue erst einmal.
