### ISSUE TITLE
Export LuPO-Initial-Datei

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#191]
Beim Export einer Initialdatei wird die zusätzlich erzeugte ldb-Datei (auch nach Schließen von SchILD) nicht gelöscht.

**Comment by FPfotenhauer** [comment]
Könnte daran liegen, dass die Connection nicht geschlossen wird.

**Comment by JuergenRichter** [comment]
War tatsächlich so.
