### ISSUE TITLE
Migration Access-Datenbanken: Der Teufel steckt im Detail

### ISSUE THREAD

**Issue by GerhardHordt** [SVWS-NRW/Schild3-BetaTest#193]
Als Vorbereitung auf den offiziellen Start von SchILD3.0 und dem damit wahrscheinlich verbundenen erhöhten Bedarf an Fortbildungen und FB-Support habe ich die in der BRA verwendeten Schulungsdatenbanken nach SchILD3.0 migriert, um die bisherigen Schulungskonzepte unter SchILD3.0 testen zu können.
 
Bei vielen Schulungsdatenbanken war die Migration erstaunlicherweise nach ca. 15 Sekunden beendet. Die übliche Meldung am Ende der Migration erschien nicht.
Beim Start dieser Datenbanken (sk126) unter Schild3.0 erschienen diese Fehlermeldungen:
#42S02Table 'sk126.users' doesn't exist
#42S02Table 'sk126.eigeneschule' doesn't exist
Nach Bestätigung der Meldungen wurde SchILD3.0 beendet.

Fehlersuche:
Beim Öffnen der Access-Datenbank mit Access365 und Eingabe des bekannten FB-Kennworts erschien eine Meldung Datenverbesserung:
"Diese Datenbank wurde mit einer früheren Version von Microsoft Access erstellt. Access aktualisiert Ihre Datenbank, damit neue Verbesserungen aktiviert werden und Ihnen die Verwendung erleichtert wird ..."
Ja/Nein/Abbrechen

"Ja" führte zu der Meldung "Sie versuchen, eine kennwortgeschützte Datenbank zu konvertieren. Entfernen Sie das Kennwort, und versuchen Sie es dann erneut..."
"Nein" führte zum Absturz von Access, was daran erkennbar war, dass die temporäre Datei *.ldb nicht gelöscht wurde.

Ein erneuter Start der Datenbank ohne Löschen der *.ldb-Datei, und Access öffnete die Datenbank. Der Fehler war schnell gefunden: In der Tabelle "EigeneSchule" waren mehrere Schulen oder die gleiche Schule mehrfach eingetragen oder die ID war nicht 1. 
Nach einer Korrektur des Fehlers, beenden der Bearbeitung, schließen der Tabelle EigeneSchule und beenden von Access ließen sich die entsprechenden Datenbanken problemlos migrieren.

Ja, es sind "antike" Schulungsdatenbanken.
Ja, da hat jemand unter SchILD2.0 mit der Schulnummer gespielt.

Das Ändern der Schulnummer kann aber im realen Schulbetrieb auch erfolgen. Ich hatte vor den Ferien eine lange Diskussion mit einem Schulleiter, dessen Sekundarschule in eine Gesamtschule "umgewandelt wurde. Es hat lange gedauert, bis er verstanden hat, das die Sekundarschule zum Schuljahresende aufgelöst wurde und am gleichen Ort unter seiner Leitung eine neue Gesamtschule gegründet wurde. Ohne meine Intervention hätte er in SchILD2.0 unter Schulverwaltung einfach die neue Schulnummer eingetragen.

Vielleicht gibt es ja Möglichkeiten, o.g. Problem bei der Migration abzufangen, indem der Inhalt der Tabelle "EigeneSchule" geprüft wird, fehlerhafte Einträge gelöscht werden und der User zur erneuten Eingabe der Schulnummer aufgefordert wird - entweder schon während der Migration oder beim Start der Datenbank unter SchILD3.0.

**Comment by FPfotenhauer** [comment]
Hallo Gerhard.

Das liegt daran, dass man in Schild2.0 die Schulnummer ändern kann, aber dieser Prozess eigentlich gar nicht richtig funktioniert.
Ist schon seit 20 Jahren so, leider. 

Letztendlich sollte man darüber nachdenken, dass doch noch in einem der nächsten Updates "abzuklemmen".
Wenn eine Schule mir die DB sendet, dann kann ich in Access die Schulnummer ändern und auch so, dass es funktioniert.

Bei den Schulungsdatenbanken liegt das auch oft daran, dass die ständig mit "Schuljahr erhöhen" behandelt wurden, was in der Praxis nicht vorkommen sollte.

Du kannst aber ja mal ein oder zwei Beispiele senden. Wir können dann mal schauen, ob man etwas abfangen kann.

Das Öffnen der Access98 Datenbanken in den neuen Access-Versionen macht m.E. auch keinen Sinn, weil die Umwandlung fast immer nicht funktioniert. Ich migriere diese Datenbanken immer in eine frische Access-Datenbank aus dem Ordner "vorlagen".
Aber natürlich mit dem alten Tool von Herrn Richter!

**Comment by GerhardHordt** [comment]
Moin. Ich habe nun den Hinweis eines Moderators bekommen, der Schulleiter einer Grundschule ist, dass das gleiche Problem bei seinem Versuch, für Testzwecke (natürlich auf einen Testrechner) die reale Datenbank seiner Schule in SchILD3.0 zu migrieren, ebenfalls aufgetreten ist. Nach einer Korrektur der Tabelle "EigeneSchule" hat die Migration problemlos funktioniert.

**Comment by FPfotenhauer** [comment]
Die Migration versucht mittlerweile den Fehler zu beheben, ansonsten kommt eine Meldung "Bitte wenden Sie sich an Ihren Fachberater....".
