### ISSUE TITLE
Schild

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#194]
Version vom 26.07.21
Der Import über die Schnittstelle Schild-NRW funktioniert nicht.
Ich wollte ein Problem (falsche Reihenfolge der Klassen) des Imports von Schülerlaufbahnen mit Klassenwechsel
innerhalb eines Halbjahres unter 3.0 verifizieren. 
Der angehängte Schüler kann nicht ordentlich importiert werden. Das Fehlerprotokoll ist enthalten. 
Der Import der Lernabschnitte funktioniert nicht. Der Fehler tritt auf, wenn die Anwendung nach dem
Import neu gestartet wird und auf den Reiter Akt. Halbjahr gewechselt wird.

[Schueler.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/6900619/Schueler.zip)

**Comment by FPfotenhauer** [comment]
Nun ja. Auf den Lernabschnittsdaten liegt folgender Unique-Contsraint:

![image](https://user-images.githubusercontent.com/34127980/127498787-acc223b2-6581-49b7-953a-369299b611e2.png)

**Comment by FPfotenhauer** [comment]
Es kann nicht zweimal der gleiche Abschnitt importiert werden, wenn die WechselNr gleich ist.
Das müsste beim Import abgefangen werden.

**Comment by EwaldReinhardt** [comment]
Es ist aber so, dass die Abschnitte so aus Schild exportiert wurden.
Wenn ich die Schnittstelle zum Portieren von Daten nutze, kann das so nicht funktionieren.
![grafik](https://user-images.githubusercontent.com/44644567/127508601-ffe52707-cd01-4fcd-8f7e-e73086cbe9b0.png)
Die Liste aus der Datenbank:
![grafik](https://user-images.githubusercontent.com/44644567/127508838-017698eb-05f8-4a48-9d28-8c957b5c9a9c.png)
Das Problem mit dem Import der Lernabschnitte war bei der Migration der Datenbanken aufgefallen, bei der verschiedentlich
die Reihenfolge der Lernabschnitte bzw. die richtige Zuordnung der Klasse nicht korrekt eingelesen wurde.

Ich habe die Dateien gerade in Schild2 eingelesen. Hier gibt es keine Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/44644567/127509571-e38f6b7d-133b-4f98-86ec-ded9a19ca65c.png)
Hier ist der Rückimport auch korrekt. Ich hatte es aber auch schon so:
![grafik](https://user-images.githubusercontent.com/44644567/127509776-fad8e7e6-22fb-41b5-8beb-065a67646037.png)

**Comment by JuergenRichter** [comment]
Danke für den Hinweis.
Das Problem ist behoben. Die Möglichkeit, wiederholte Abschnitt zu importieren (mit autoamtischer Vergabe der "Wechselnummer") wurde erst vor relativ kurzer Zeit in SchILD2 eingeführt und hatte noch nicht den "Weg nach SchILD3" gefunden. Ist nun aber umgesetzt., ich mache das Thema daher zu.

**Comment by JuergenRichter** [comment]
Korrektur: Statt "wiederholte" muss es heißen "gewechselte"
