### ISSUE TITLE
Versionsgeschichte zeigen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#195]
Wenn ich unter Verwaltung/Hilfe auf "Versionsgeschichte zeigen" klicke, meldet Schild, dass die PDF-Datei nicht richtig verlinkt ist. Jedenfalls fehlt in meiner Installation der komplette Ordner "Dokumentationen".

**Comment by FPfotenhauer** [comment]
Die Versionsgeschichte wird momentan in einer txt gepflegt und im Repo abgelegt.
Für den Echtbetrieb müssen wir uns noch eine Variante überlegen, wie man das am besten handhabt.

**Comment by FPfotenhauer** [comment]
Wurde auf das neue Verfahren im WIKI umgestellt.
