### ISSUE TITLE
Unterrichtsfächer

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#196]
Es dauert sehr lange, in den "Schulbezogenen Katalogen" die Unterrichtsfächer anzeigen zu lassen, wenn man vorher die Klassen/Versetzungstabelle angeklickt hat. Bei mir ploppt dann die Sanduhr fünfmal auf und das Fenster wird verzerrt dargestellt.

**Comment by JuergenRichter** [comment]
Wird geprüft.

**Comment by JuergenRichter** [comment]
Kann ich auf meinem recht schnellen Rechner nicht reproduzieren, werde das aber mal auf einem einfachen Laptop testen.

**Comment by JeVaske** [comment]
In 3.0.18.5 läuft es gut.
