### ISSUE TITLE
Stil

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#197]
Wenn ich unter "Individuelle Einstellungen" den Stil auf "Luna" ändere ist das Programm kurz weg. Muss das so sein? Danach wird vorgeschlagen das Programm neu zu starten. Wenn ich das mit "Ja" bestätige, wird das Proramm aber nicht neu gestartet, sondern nur geschlossen. Das könnte zu Irritationen führen. Wenn ich Schild dann neu starte, ist der Stil aber nicht mehr "Luna", sondern wieder "Silver". Meiner Meinung nach sollte Luna standardmäßig eingestellt werden. Grau in grau (silver) ist nicht sehr ansprechend.

**Comment by JuergenRichter** [comment]
Sollte in 3.0.18.5. behoben sein.
