### ISSUE TITLE
Schaltfläche Bemerkungen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#198]
Wenn ich Schild auf meinem zweiten Monitor platziere und unter "Individualdaten I" die Schaltfläche "Bemerkungen" aktiviere, öffnet sich das kleine Fenster. Wenn ich dieses schließe (egal ob über die Schaltfläche "schließen" oder das Kreuzchen), wird Schild auf den anderen Monitor verschoben.

**Comment by FrodBRA** [comment]
3.0.71.9: Das Problem tritt nicht mehr auf.
