### ISSUE TITLE
Button Nachprüfungen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#199]
Der Button "Nachprüfungen" fehlt oder er liegt nicht mehr unter dem Reiter "Akt. Halbjahr".

**Comment by JuergenRichter** [comment]
Schalter befindet sich auf Karteireiter "Akt. Halbjahe" unten im Bereich "Zeugnis/Abschluss" (über "Konferenzdatum").

**Comment by JuergenRichter** [comment]
Hinweis: In Version 3.0.19.5 sind die Schalter mit Fettschrift versehen, da sieht man es besser.
