### ISSUE TITLE
Absturz beim Benutzerwechsel

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#2]
Wenn der Benutzer gewechselt werden soll, aber man sich doch dagegen entscheidet und auf "abrechen" klickt, stürzt Schild3 ab.

**Comment by me-rfb2000** [comment]
Auch mit der neuen SCHILD3.exe passiert der Absturz.

**Comment by JuergenRichter** [comment]
Kommt denn eine Fehlermeldung?

Wenn nicht, so ist das Verhalten so gewünscht: Der aktuelle Benutzer ist ja schon abgemeldet, wenn dann auf Abbrechen geklickt wirdf, ist das vergleichbar mit der Situation beim Programmstart, wenn man da bei der Anmeldung auf "Abbrechen" klickt, wird das Programm auch beendet.

**Comment by FPfotenhauer** [comment]
Wenn es kein Aufwand ist, würde ich an dieser Stelle auf ein "echtes" Abbrechen gehen.

**Comment by JuergenRichter** [comment]
Ich sehe da aber eventuelle Sicherheitsprobleme. Folgende Situation:
-Admin ist angemeldet
-Danach will ein anderer Benutzer mit SchILD arbeiten
-Admin klickt auf "Benutzerwechsel", dabei wir er ausgeloggt und geht dann
-Neuer Benutzer meldet sich aber nicht mit seinem eigenen Benutzernamen an, sondern klickt auf "Abbrechen"
-Wenn dann die Abmeldung abgebrochen wird und der Admin weiter angemeldet ist, hat der neue Benutzer volle Admin-Rechteund könnte z.b. sich selbst zum Admin machen 
-

**Comment by FPfotenhauer** [comment]
Wir können das gerne so lassen, die Funktion zu nutzen und dann den Rechner zu verlassen hatte ich jetzt nicht bedacht.
