### ISSUE TITLE
Einstellungen zum Reportsverzeichnis fehlt

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#20]
Wie kann man Schild3.0 zeigen, wo das Reports-Verzeichnis ist? Auf beiden Bildern sieht man, das es keine Einstellmöglichkeit gibt.
![grafik](https://user-images.githubusercontent.com/73750717/100758325-ab5aff80-33ef-11eb-9beb-b47f0da322bb.png)
![grafik](https://user-images.githubusercontent.com/73750717/100758392-c2015680-33ef-11eb-8458-1e0852f66bbf.png)

**Comment by FPfotenhauer** [comment]
Das Reportverzeichnis ist im Arbeitsverzeichnis. (Denke ich zumindest.)

**Comment by me-rfb2000** [comment]
auf dem laptop in c:\SVWS-Arbeitsverzeichnis\
und auf dem PC in d:\SchILD3.0\

**Comment by FPfotenhauer** [comment]
Das sind dann jetzt die Pfade zur Reporting.

**Comment by me-rfb2000** [comment]
ok
