### ISSUE TITLE
Fehler bei Statistik

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#200]
Bei Klick auf Statistik > Gesamtprüfung erscheint ein Fehler beim Aufruf der statistik.dll:
SchILD 3.0.18.5 vom 15.8.2021
![gesamtpruefung_statistik](https://user-images.githubusercontent.com/27292550/130085611-758ac209-0584-43e2-b0f8-b034bca03be7.png)

**Comment by FPfotenhauer** [comment]
Dann ist das eine alte DLL.
Nimm mal bitte die aus dem aktuellen Update von Schild2.
Ist das dann weg? Dann tausche ich die aus....

**Comment by hagege** [comment]
Ich habe das gerade gemacht, scheint aber nicht daran zu liegen:
C:\Betatest_schild_30\screenshots\ASDstatistik.png

**Comment by hagege** [comment]
Jetzt klappt es: Im root war auch noch die ASDStatistik.dll, die ich jetzt ersetzt habe:
![Uploading ASDstatistik_2.png…]()
