### ISSUE TITLE
Problem beim Jahrgangswechsel

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#201]
Wenn ich einen Jahrgangswechsel durchführen möchte und dieser Jahrgangswechsel wegen fehlender Jahrgänge bei einigen SuS nicht möglich war, dann bleibt der Button "Weiter" nach Korrektur der Fehler bei den SuS nach erneutem Aufruf dieser Option disabled:

![jahrgangswechsel](https://user-images.githubusercontent.com/27292550/130088390-3df39597-acdc-4057-8b5b-9fc9838e7cfb.png)

Erst nach einem Neustart des Programms ist der Button wieder aktiviert.

**Comment by FrodBRA** [comment]
Ist das nicht ein normales Verhalten, da SchILD die Kataloge (Großteils?) nur bei einem Neustart komplett einliest? 

Sollte dem so sein, wäre ein Kopf "Kataloge neu einlesen" in SchILD sinnvoll, bzw. zumindest eine Textanzeige in "Kataloge", dass nach dem Ändern ein Neustart empfehlenswert wäre.

Ebenfalls könnte dieses Issue geschlossen werden.

**Comment by AnneSchueller** [comment]
Bei der aktuellen Version erfolgt trotz fehlender Jahrgänge ein Schuljahreswechsel. Ich schließe das Issue mal.
