### ISSUE TITLE
Neueintrag DSGVO-Einwilligungen fehlerhaft

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#202]
Guten Tag,

nach einem Neueintrag in den Katalog "DSGVO-Einwilligungen" folgte folgende Fehlermeldung:

![DSGVO](https://user-images.githubusercontent.com/79116896/130367541-2af27c16-10f1-4520-8455-ab977c2a796a.png)

Die gleiche Fehlermeldung erhalte ich nun bei jedem Neustart von Schild3 unabhängig welche DB ich auswähle. 

Viele Grüße Anne Schüller

**Comment by FPfotenhauer** [comment]
Ist die Datenbank mit der aktuellen SVWS-Server-Version migriert worden?

**Comment by AnneSchueller** [comment]
Danke für den Hinweis. Es war tatsächlich noch eine DB, die mit einer alten SVWS-Server-Version migriert wurde.
Jetzt klappt es wieder.
