### ISSUE TITLE
Gruppenprozess DSGVO-Einwilligungen funktioniert nicht

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#203]
Das "Zustimmen" beim Gruppenprozess DSGVO-Einwilligungen hat keinen Effekt auf die DSGVO-Einwilligungen der ausgewählten Schüler.

Auch mit dem Katalog "DSGVO-Einwilligungen" habe ich Probleme: Nach dem Hinzufügen erhalte ich zunächst die Fehlermeldung, dass das Programm nicht reagiert. Um den hinzugefügten Katalogeintrag bei den Schülern sichtbar zu machen muss ich nun entweder das Programm neu starten (was bei den anderen Katalogen nicht der Fall ist) oder die Fehlermeldung wegklicken und einmal zwischen Schüler <->Katalogen hin und her switchen.

**Comment by FPfotenhauer** [comment]
Das mit dem Neustart kann ich nachvollziehen.
Ansonsten dauert das hinzufügen der Merkmale einfach etwas länger.
