### ISSUE TITLE
Katalog Erzieherart fehlt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#204]
Ich finde den Katalog "Erzieherart" nicht. Wurde der weggelassen oder ist der Button evtl. überdeckt?
Kann man die Schriftgröße irgendwo skalieren, wie in Schild2 unter individuellen Einstellungen?

**Comment by JuergenRichter** [comment]
Ist wohl durch die Umstrukturierung der katalogverwaltung "unter den Tisch gefallen". Wird umgehend behoben.
