### ISSUE TITLE
Zu kleine Anzeige: Schule/Allgemeine Angaben

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#206]
Hier fehlt ein Stück bei der offiziellen Bezeichnung.
![Bildschirmfoto 2021-09-22 um 13 21 13](https://user-images.githubusercontent.com/75326793/134335312-21d00cc0-bbf0-4201-9387-e5ebf0368711.png)
![Bildschirmfoto 2021-09-22 um 13 20 52](https://user-images.githubusercontent.com/75326793/134335318-0512b0ac-83d6-47d3-b393-247b57ebcb46.png)
..

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Welche Version wird denn benutzt? Welche Bildschirmauflösung (Windows-Einstellungen)?

**Comment by AlexanderDedy** [comment]
Ich hatte folgende Einstellungen verwendet...
Mit der Textgröße 125% ist das Problem behoben. Mit 100% passen dann auch alle Individualdaten I auf die Anzeige - allerdings wird es dann etwas klein...
Gibt es eine optimale Einstellung für WIN? Die individuelle Skalierung wie in S2 habe ich nicht gefunden bei Einstellungen..

![Bildschirmfoto 2021-09-29 um 11 28 02](https://user-images.githubusercontent.com/75326793/135243201-b4471b5d-2260-4105-aaf6-f66f9b2b8d69.png)

**Comment by FPfotenhauer** [comment]
Weiter Skalierungen gibt es leider unter Windows nicht.

**Comment by FrodBRA** [comment]
3.0.71.9: Das Problem scheint bei mir nicht mehr aufzutreten; es dürfte sich zusammen mit der Überarbeitung der UI-Skalierung für hohe Auflösungen mit erledigt haben?
