### ISSUE TITLE
Sprachenfolge lädt nicht und erzeugt Fehler beim Schülerwechsel

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#207]
Befindet man sich in der Version 3.0.18.5 auf der Registerkarte Laufbahninfo, so löst ein Schülerwechsel den Fehler 

42S22 Unknown column Reihenfolge in order clause.

Das dürfte daran liegen, dass der SVWS-Server die Spalte in ReihenfolgeNr geändert hat.

**Comment by FPfotenhauer** [comment]
Sprachenfolge wurde ja grundlegend geändet.
