### ISSUE TITLE
Filterprobleme

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#208]
Wenn ich mit dem Auswahlfilter arbeite und danach die Standard-Auswahl aktiviere, stürzt Schild (3.0.18.5) ab.

**Comment by JuergenRichter** [comment]
Kann ich so nicht reproduzieren, bitte mal die einzelnen Schritte erläutern, die zum Problem führen.

**Comment by FPfotenhauer** [comment]
Filter wurde komplett überarbeitet.
Bitte erneut testen. Hier funktioniert das jetzt.
