### ISSUE TITLE
Ansicht "Fächer, Noten" fehlerhaft

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#21]
Die Ansicht bei "Eingabemodus" überlappt.

![grafik](https://user-images.githubusercontent.com/73750717/100758723-1efd0c80-33f0-11eb-9ded-b5e3a3357fcd.png)

**Comment by FPfotenhauer** [comment]
Welche Skalierung ist eingestellt.
Ist das auch nach einen Neustart noc da?
Welche Auflösung hat der Moenitor?

**Comment by FPfotenhauer** [comment]
Wenn es auf die letzten Fragen keine Antwort gibt, würde ich das Ticket schließen.
