### ISSUE TITLE
Filter auf markierte Schüler

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#213]
Wenn ich auf das Filtersymbol klicke, kommt eine Zugriffsverletzung.

**Comment by GerhardHordt** [comment]
Die Datenbank ist vom Schuljahr 2018/2019, 2. Hj. Gibt es für dieses Schuljahr/Halbjahr in der DB Lernabschnittsdaten? Bei unseren Schulungsdatenbanken hat der Filter I nicht funktioniert, wenn keine Lernabschnittsdaten für das Schul-/Halbjahr vorhanden waren. Allerdings ist SchILD nicht abgestürzt, aber es war bei einer deutlich älteren SchILD-Version.

**Comment by FrodBRA** [comment]
Der Fehler ist bei mir in diversen Versionen und DBs nicht aufgetaucht.

Hat jemand eine DB, mit der er sich reproduzieren lässt, ansonsten könnte das Issue erst einmal geschlossen werden.

@AnneSchueller

**Comment by AnneSchueller** [comment]
Bei mir klappt diesbezüglich auch alles. Ich schließe das mal
