### ISSUE TITLE
immer noch Filterprobleme

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#214]
Ich teste gerade die neue Version Schild 3.0.21.5 mit SVWS Server 0.0.54. Wenn ich unter dem Reiter Schüler auf Suchen klicke, kommt die folgende Fehlermeldung:
![fehler01](https://user-images.githubusercontent.com/78501680/141367095-9e400276-541d-4e55-b024-d677a9cbd600.jpg)
.

**Comment by FPfotenhauer** [comment]
Wurde behoben.
