### ISSUE TITLE
Leistungsdaten

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#216]
Unter Akt. Halbjahr/ Leistungsdaten lassen sich mit "+" die Teilleistungen nicht aufklappen.
![fehler3](https://user-images.githubusercontent.com/78501680/141368815-b3981c9f-e13c-41d9-baa7-16bd15cce03e.jpg)
.

**Comment by FrodBRA** [comment]
3.0.71.9: Das kann ich nicht reproduzieren; auch in vielen vorherigen Versionen nicht. Hier müsste im Detail mit konkreten Datenbanken, mit denen der Fehler auftritt, weiter untersucht werden.
