### ISSUE TITLE
Änderung des Kennworts funktioniert nicht bei Benutzerverwaltung

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#217]
Ich hatte das Kennwort für den Admin vergessen und habe daher mittels eines SQL-Scripts einen neuen Admin2 über DBeaver angelegt, mit dem ich mich als Admin2 anmelden konnte. 
Danach habe ich über die Benutzerverwaltung das Kennwort von Admin geändert und wollte mich über "Benutzer wechseln" als Admin anmelden. Trotzdem bekam ich immer die Meldung "Ungültiges Kennwort". Die Prozedur habe ich mehrfach getestet.
Das gleiche Problem hatte ich auch, wenn ich mich nach Neustart von SchILD als Admin mit dem neuen Kennwort anmelden wollte.
Vorher habe ich den SVWSServer komplett deinstalliert und neu installiert (v0.0.54) und SchILD ebenfalls komplett deinstalliert und neu installiert (v0.0.27)

**Comment by FPfotenhauer** [comment]
![SNAG_2022_04_02_12 45 53](https://user-images.githubusercontent.com/34127980/161379696-72317f17-a59e-4212-bf93-7f907706f15e.png)

Dieser Fehler kommt bei mir, wenn ich das Kennwort eines Users wechseln will.
