### ISSUE TITLE
Unterrichtsfächer

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#219]
Es fehlt der Menüpunkt "Fächer der Oberstufe vearbeiten".

**Comment by FPfotenhauer** [comment]
Fehlt in 3.0.29 immernoch.

**Comment by FrodBRA** [comment]
Fehlt in 3.0.73.10 soweit ich sehen konnte ebenfalls.

Ich schlage vor, das Issue auf "Hohe Priorität" zu setzen.

@AnneSchueller

**Comment by JuergenRichter** [comment]
Da dise Funktion nur in Verbindung mit LuPO benötigt wird (und im Web-.Client meines Wissens auch angeboten wird) war ich davon ausgegangen, dass diese Option in SchILD3 nicht benötigt wird (auch um Inkonsitenzen zwischen dem WebClient und SchILd3 zu vermeiden).

**Comment by FrodBRA** [comment]
Falls dem so ist, wäre die Funktion in SchILD3 in der Tat nicht weiter benötigt und das Issue kann geschlossen werden.

Den Sachverhalt müsste @FPfotenhauer abschließend kommentieren.

**Comment by AnneSchueller** [comment]
Aktuell kann man über den Client keine Fächer der Oberstufe definieren oder habe ich da etwas übersehen?
Wird das noch vor Februar umgesetzt?

**Comment by AnneSchueller** [comment]
Ach doch. Klappt alles mit dem Client. Der Schild2-Reiter  "Fächer der Oberstufe" bezieht sich ja nur auf die Fächerkombis und die Zuordnung zu den Jahrgängen....
Die Zuordnung, dass ein Fach auch Oberstufenfach ist,  kann mit Schild3 umgesetzt werden.
