### ISSUE TITLE
Kleinere Tippfehler

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#22]
Hallo,
mir fallen immer mal wieder kleinere Tippfehler auf. Ich mache einfach mal eine Issues auf, wo man ggf. nur ein Bild senden braucht....
![Bildschirmfoto 2020-12-01 um 18 13 33](https://user-images.githubusercontent.com/75326793/100773449-30024980-3401-11eb-8312-fe8e135b2eaa.png)

**Comment by AlexanderDedy** [comment]
Schule - Vorschau
![Bildschirmfoto 2020-12-01 um 18 18 34](https://user-images.githubusercontent.com/75326793/100773836-af901880-3401-11eb-8fd1-04a749bc6660.png)

**Comment by JTorspecken** [comment]
![grafik](https://user-images.githubusercontent.com/61317409/102377988-94a6d200-3fc5-11eb-9c1e-62f3b8c3a840.png)
Da fehlt ein i bei Webseite

**Comment by JuergenRichter** [comment]
In 3.0.8 behoben
