### ISSUE TITLE
Probleme nach Migration von Testdatenbanken

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#224]
Ich habe heute die aktuellen Versionen vom SVWS-Server und SchILD 3.0 runtergeladen und getestet.
Nach Anonymisierung einer "echten" Datenbank und Migration in SchILD 3.0 habe ich zunächst keine Möglichkeit, mich mit den mir bekannten Anmeldedaten anzumelden. Das Problem habe ich bei beiden Datenbanken, die migriert wurden.
Über DBeaver habe ich dann per SQL-Script einen neuen Benutzer mit Admin-Rechten angelegt. 
Ich kann mich auch anmelden (Benutzername und leeres Kennwort):
![auswahl_db](https://user-images.githubusercontent.com/27292550/154503470-39ceb362-468c-4b28-859d-39dbe49f40ac.png)
... aber dann erfolgt sofort die folgende Fehlermeldung:
![nach_auswahl_db_fehler](https://user-images.githubusercontent.com/27292550/154503462-2ef5196f-94a3-4db7-8fec-0cfd16f1f975.png)

**Comment by FPfotenhauer** [comment]
Ist behoben.
