### ISSUE TITLE
Schuljahr Abschnitt anzeigen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#226]
Ich fände es gut, wenn in der Kopfzeile permanent das aktuelle Schuljar/Abschnitt angezeigt wird.
In der Verwaltung wird es komisch dargestellt: "2. 2. Abschnitt", also eine 2. zu viel.
![grafik](https://user-images.githubusercontent.com/84628225/161384020-94606027-be82-41af-b0ec-7441ecf7d490.png)

**Comment by JuergenRichter** [comment]
Was ist mit "Kopfzeile" konkret gemeint? Die Zeile im Hauptfenster ganz oben? Da wird bei mir das Schuljahr angezeigt:

![2022-06-15 14_38_16-Aktuelle Datenbank_ Gesamtschule_Pfotenhauer, Schuljahr 2019_2020, 4  Qu, Benutz](https://user-images.githubusercontent.com/61280188/173829164-58331b37-23e7-4b50-b6ce-4a7c67984b5e.png)

**Comment by JuergenRichter** [comment]
In der Verwaltung sollte es auch korrekt angezeigt werden:
![image](https://user-images.githubusercontent.com/61280188/173829503-124866bf-5777-45e7-b3e9-3c2efb8f8f58.png)

**Comment by AnneSchueller** [comment]
Ach jetzt sehe ich es... Beim Neustart wird ebenfalls das Schuljahr oben sichtbar. Allerdings wenn ich die Reiter switche, fehlt es irgendwann. Dann steht da nur noch der aktuelle Unterreitername. Vielleicht liegt das auch an der Schriftgröße? Wenn das bestehen bleibt, kann ich das nächste Woche mal an meinem Rechner zeigen. Hier schonmal ein Screenshot 

![Schild3_Schrift](https://user-images.githubusercontent.com/79116896/173830854-bb0e0606-79a2-4fa7-9133-a4eb2f36cfb1.png)



In der Verwaltung ist das bei mir auch richtig.

**Comment by JuergenRichter** [comment]
Das hängt davon ab, was gerade gemacht wird. Wenn die Katalog-Bearbeitung aktiviert wird, steht da, welcher Katalog gerade im Zugriff ist. Wenn man aber in die Schülerbearbeitung wechselt, stehen da u.a. die Angaben zum Schuljahr. 

 

Ich persönlich finde es nicht schlecht, dass da z.B. der Katalog erscheint, man könnte das aber kombinieren (in der Form, dass da z.B. das Schuljahr in Klammern steht. Bin aber für Vorschläge offen.

 

 

Mit freundlichen Grüßen aus Bornheim

Jürgen Richter

 

 




Wasser und Umwelt

ribeka GmbH

Johann-Philipp-Reis-Str. 9
53332 Bornheim
Tel.: +49(0)2222-990600
Fax: +49(0)2222-990601
 <http://www.ribeka.com/> www.ribeka.com



Geschäftsführer: Dr. Jürgen Richter, Erich Berger
Amtsgericht Bonn HRB 8423

 

Von: AnneSchueller <> 
Gesendet: Mittwoch, 15. Juni 2022 14:50
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: JuergenRichter ***@***.***>; Assign ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Schuljahr Abschnitt anzeigen (Issue #226)

 

Ach jetzt sehe ich es... Beim Neustart wird ebenfalls das Schuljahr oben sichtbar. Allerdings wenn ich die Reiter switche, fehlt es irgendwann. Dann steht da nur noch der aktuelle Unterreitername. Vielleicht liegt das auch an der Schriftgröße? Wenn das bestehen bleibt, kann ich das nächste Woche mal an meinem Rechner zeigen. Hier schonmal ein Screenshot

 <https://user-images.githubusercontent.com/79116896/173830854-bb0e0606-79a2-4fa7-9133-a4eb2f36cfb1.png> 

In der Verwaltung ist das bei mir auch richtig.

**Comment by AnneSchueller** [comment]
Ich mache mir nochmal Gedanken dazu.
@HHayen Was meinst du dazu?

**Comment by FrodBRA** [comment]
Ist das Issue noch aktuell? Derzeit wird in SchILD3 der aktuelle Abschnitt der Schule wie in SchILD2 in der Kopfzeile angezeigt.
