### ISSUE TITLE
Fehlende Prüfungsordnungen

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#23]
Es fehlt Ausbildungsvorbereitung - getestet mit  SGL A012
![Bildschirmfoto 2020-12-01 um 18 24 43](https://user-images.githubusercontent.com/75326793/100775444-98522a80-3403-11eb-8d37-bb5ea1f6f8dc.png)

**Comment by FPfotenhauer** [comment]
Hier grieft Schild3 wahrscheinlich noch auf die alte MDB zu, oder das Präfix Schildinter_ fehlt.

**Comment by JuergenRichter** [comment]
In Version 3.0.6 behoben
