### ISSUE TITLE
Reiter Kataloge und Verwaltung

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#230]
Wenn die Reiter "Kataloge" und "Verwaltung" angeklickt werden, bleiben sie nicht farblich hervorgehoben.

**Comment by JuergenRichter** [comment]
Das liegt wohl daran, dass es bei den genannten Funktionen keine Einträge auf der "Ribbon-Leiste" gibt, dann wird diese eingeklappt. Dann wird auch der "Reiter" nicht hervorgehoben. Ich muss mal prüfen, ob ich dieses Verhalten abstellen kann.

**Comment by JuergenRichter** [comment]
Ich hab da nun etwas recherchiert. Bei der ganzen "Ribbon-Technik" gibt es von Microsoft einige Vorgaben, die mit der Arbeitsweise in SchILD in gewisser Weise kollidieren. Dazu gehört auch die Möglichkeit, die Ribbon-Leiste zu minimieren. Das wird in SchILD3 z.B. bei den Katalogen verwendet, da dort derzeit keine Funktionen auf der Ribbon-Leiste liegen. Dabei wird dann der entsprechende Reiter ("Kataloge") nicht optisch hervorgehoben, da ja dort nichts zu aktivieren ist. Ich vermute, dass das auch eine Vorgabe von Microsoft ist. Es gibt nun mehrere Optionen:

- Man lässt es so wie es ist
- Man minimiert die Ribbonleiste nicht, dann bleibt die Ribbonleiste sichtbar, es sind aber keine Funktionen da. Sieht aber nicht so schön aus:
![image](https://user-images.githubusercontent.com/61280188/174736728-69c49a24-adf8-4325-a061-a529e55f5a98.png) 

- Man setzt Funktionen (bei den Katalogen) auf die Ribbonleiste

![image](https://user-images.githubusercontent.com/61280188/174738041-de2a2d99-2535-40e7-bd1b-60ba9be64045.png)
Das sieht dann einheitlicher zur Darstellung z.B. bei den Schülern aus, macht aber die "Mauswege" länger (die Funktionen direkt über den Katalogtabellen werden natürlich wegfallen).
Die Frage ist dann aber, was man beim REeter "Verwaltung macht", da gibt es derzeit keine Funktionen, die man sinnvollerweise auf die Ribbon-Leiste legen könnte.

**Comment by AnneSchueller** [comment]
Könnte man in der Ribbonleiste als Funktion auch ein "unauffälliges" Label einfügen?
