### ISSUE TITLE
Migration Datenbank

### ISSUE THREAD

**Issue by RitaKoch** [SVWS-NRW/Schild3-BetaTest#232]
In der Schulungsversion (Gerhardt Hordt) konnten die Schulungsdatenbanken und die schuleigene Datenbank migriert werden. Nach dem Update (3.0.29.7) funktioniertnichts mehr.

**Comment by FPfotenhauer** [comment]
Die Schulungsdatenbanken sind oft nicht ganz intakt.
Das Log der Echtdatenbank würd emich interessieren.
Da dort aber Daten drin stehen können, bitte per Mail.

**Comment by JOverhoff** [comment]
Migration erfolgreich:
SVWS-Server-Version: 0.2.5
SchILD-Version: 0.0.32
Schulnummer: 147709 (freiwlllig)
Schulform: HS
Datenbankformat: Access
Datenbankgröße: 15MB
Datenbankalter: ca. 12 Jahre

**Comment by FPfotenhauer** [comment]
Ich schließe dieses Issue mal.
Bitte ein neues öffnen, wenn wieder Probleme auftreten.
