### ISSUE TITLE
EigeneSchule_Abteilungen : Datenbankabfrage fehlerhaft

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#233]
SVWS: 0.2.8  Schild: 3.0.30.7
Änderungen in EigeneSchule_Abteilungen führt zu:
![grafik](https://user-images.githubusercontent.com/44644567/163944117-1915337e-47b1-4c9a-a939-bc9bb74202cc.png)

Grund: 
In der Tabelle ist nicht mehr das Kürzel sondern die Abteilungsleiter_ID angegeben, die
einen Lehrer in K_Lehrer referenziert.

**Comment by EwaldReinhardt** [comment]
SVWS: 0.2.8 Schild: 3.0.30.7
**qrySchueler: fas Feld OrgFormKrz fehlt.**
![grafik](https://user-images.githubusercontent.com/44644567/163944526-bad6ad72-06d4-4aad-81cf-8409e7f41e02.png)

Hinweis: Die Tabelle Schueler enthält nicht mehr die Spalte OrgFormKrz, die SchILD30 noch benötigt?

**Fehlerlog:**
EurekaLog 7.10.0.0 8BD69D43571B8C48A2404FB6F3744F60 F9BE341166997E408AEB0DB6FDE4CE49 DA39A3EE5E6B4B0D3255BFEF95601890AFD80709 A8F1DD3F222D9242AF8F10EA42852C0F

Application:
-------------------------------------------------------------------
  1.1 Start Date      : Tue, 12 Apr 2022 12:03:54 +0200
  1.2 Name/Description: SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  1.3 Version Number  : 3.0.29.7
  1.4 Parameters      : 
  1.5 Compilation Date: Fri, 1 Apr 2022 09:22:34 +0200
  1.6 Up Time         : 6 hour(s), 42 minute(s), 51 second(s)

Exception:
------------------------------------------------------------------------------
  2.1 Date          : Tue, 12 Apr 2022 18:46:45 +0200
  2.2 Address       : 0264B457
  2.3 Module Name   : SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  2.4 Module Version: 3.0.29.7
  2.5 Type          : EEurekaLogGeneralError
  2.6 Message       : qrySchueler: Das Feld 'OrgFormKrz' wurde nicht gefunden.
  2.7 ID            : 25D14A42
  2.8 Count         : 1
  2.9 Status        : New
  2.10 Note         : 
  2.11 Sent         : 0

User:
----------------------------------------------------------------
  3.1 ID        : EwaldReinhardt
  3.2 Name      : Ewald Reinhardt
  3.3 Email     : 
  3.4 Company   : 
  3.5 Privileges: SeShutdownPrivilege             - OFF
                  SeChangeNotifyPrivilege         - ON (default)
                  SeUndockPrivilege               - OFF
                  SeIncreaseWorkingSetPrivilege   - OFF
                  SeTimeZonePrivilege             - OFF

Active Controls:
-------------------------------
  4.1 Form Class   : TFrm_Info
  4.2 Form Text    : SchILD-NRW
  4.3 Control Class: TFrm_Info
  4.4 Control Text : SchILD-NRW

Computer:
--------------------------------------------
  5.1 Name        : BKT-R910VLZD
  5.2 Total Memory: 8286826496 (7,72 Gb)
  5.3 Free Memory : 2471452672 (2,30 Gb)
  5.4 Total Disk  : 999533830144 (930,89 Gb)
  5.5 Free Disk   : 557774069760 (519,47 Gb)
  5.9 Display DPI : 96

Operating System:
-----------------------------------------------
  6.1 Type    : Microsoft Windows 10 (64 bit)
  6.2 Build # : 2009 (10.0.19044.1586)
  6.3 Update  : Authum 2021 Update [21H2] #1586
  6.4 Language: German (0407)
  6.5 Charset : 0/1252


Call Stack Information:
-----------------------------------------------------------------------------------------------------------------------------------------------------
|Methods |Details|Stack   |Address |Module      |Offset  |Source                |Unit              |Class             |Procedure/Method  |Line      |
-----------------------------------------------------------------------------------------------------------------------------------------------------
|*Exception Thread: ID=0; Parent=0; Priority=0                                                                                                      |
|Class=; Name=MAIN                                                                                                                                  |
|DeadLock=0; Wait Chain=                                                                                                                            |
|Comment=                                                                                                                                           |
|---------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|04     |00000000|0264B45C|SchILD30.exe|0224B45C|Unit_Schueler.pas     |Unit_Schueler     |                  |Setze_SQL         |3296[66]  |
|00000040|04     |0019F84C|0264C5AA|SchILD30.exe|0224C5AA|Unit_Schueler.pas     |Unit_Schueler     |TSchueler         |Lese_Daten        |3376[40]  |
|00000040|04     |0019F89C|0279FE68|SchILD30.exe|0239FE68|Form_Hauptformular.pas|Form_Hauptformular|Tfrm_Hauptformular|FormShowSchildNrW |22382[188]|
|00000040|04     |0019F908|0277022C|SchILD30.exe|0237022C|Form_Hauptformular.pas|Form_Hauptformular|Tfrm_Hauptformular|FormShow          |10454[18] |
|00000040|03     |0019F990|009B91C0|SchILD30.exe|005B91C0|JvFormPlacement.pas   |JvFormPlacement   |TJvFormPlacement  |FormShow          |          |
|00000040|04     |0019F9AC|007B5E55|SchILD30.exe|003B5E55|Vcl.Forms.pas         |Vcl.Forms         |TCustomForm       |DoShow            |4231[1]   |
|00000040|04     |0019FA40|0069497E|SchILD30.exe|0029497E|Vcl.Controls.pas      |Vcl.Controls      |TControl          |WndProc           |7420[91]  |
|00000040|04     |0019FB6C|00699433|SchILD30.exe|00299433|Vcl.Controls.pas      |Vcl.Controls      |TWinControl       |WndProc           |10278[166]|
|00000040|04     |0019FBB8|007B6925|SchILD30.exe|003B6925|Vcl.Forms.pas         |Vcl.Forms         |TCustomForm       |WndProc           |4652[209] |
|00000040|04     |0019FBE4|0107470E|SchILD30.exe|00C7470E|Vcl.Ribbon.pas        |Vcl.Ribbon        |TCustomRibbon     |CallParentWndProc |4685[2]   |
|00000040|04     |0019FBF8|01072B27|SchILD30.exe|00C72B27|Vcl.Ribbon.pas        |Vcl.Ribbon        |TCustomRibbon     |CustomFrameWndProc|4006[81]  |
|00000040|04     |0019FC64|006945B8|SchILD30.exe|002945B8|Vcl.Controls.pas      |Vcl.Controls      |TControl          |Perform           |7198[10]  |
|00000040|04     |0019FC80|006987A9|SchILD30.exe|002987A9|Vcl.Controls.pas      |Vcl.Controls      |TWinControl       |UpdateShowing     |9900[19]  |
|00000040|04     |0019FCB8|006988B8|SchILD30.exe|002988B8|Vcl.Controls.pas      |Vcl.Controls      |TWinControl       |UpdateControlState|9935[21]  |
|00000040|04     |0019FCCC|0069B5AA|SchILD30.exe|0029B5AA|Vcl.Controls.pas      |Vcl.Controls      |TWinControl       |CMVisibleChanged  |11726[3]  |
|00000040|04     |0019FE00|00699433|SchILD30.exe|00299433|Vcl.Controls.pas      |Vcl.Controls      |TWinControl       |WndProc           |10278[166]|
|00000040|04     |0019FE4C|007B6925|SchILD30.exe|003B6925|Vcl.Forms.pas         |Vcl.Forms         |TCustomForm       |WndProc           |4652[209] |
|00000040|04     |0019FE78|0107470E|SchILD30.exe|00C7470E|Vcl.Ribbon.pas        |Vcl.Ribbon        |TCustomRibbon     |CallParentWndProc |4685[2]   |
|00000040|04     |0019FE8C|01072B27|SchILD30.exe|00C72B27|Vcl.Ribbon.pas        |Vcl.Ribbon        |TCustomRibbon     |CustomFrameWndProc|4006[81]  |
|00000040|04     |0019FEF8|006945B8|SchILD30.exe|002945B8|Vcl.Controls.pas      |Vcl.Controls      |TControl          |Perform           |7198[10]  |
|00000040|04     |0019FF14|00692FEE|SchILD30.exe|00292FEE|Vcl.Controls.pas      |Vcl.Controls      |TControl          |SetVisible        |6224[5]   |
|00000040|04     |0019FF5C|0282DAE6|SchILD30.exe|0242DAE6|SchILD30.dpr          |SchILD30          |                  |initialization    |304[49]   |
-----------------------------------------------------------------------------------------------------------------------------------------------------

Modules Information:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|Handle  |Name                       |Description                                           |Version            |Size    |Modified           |Path                                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|00400000|SchILD30.exe               |SchILD 3.0 von ribeka GmbH                            |3.0.29.7           |54837816|2022-04-01 17:19:30|C:\Program Files (x86)\SchILD3.0\                                                                             |
|04330000|ChilkatDelphi32.dll        |Chilkat Delphi DLL 32-bit                             |9.5.0.82           |10655936|2022-04-01 17:19:28|C:\Program Files (x86)\SchILD3.0\                                                                             |

**Comment by EwaldReinhardt** [comment]
SVWS: 0.2.8 Schild: 3.0.30.7
3.	Aktuelle Schülerauswahl 
-	Der obere Bereich muss wohl noch entfernt werden
-	Wird es wieder die Möglichkeit geben eine Auswahl mit Jokerzeichen zu versehen?
Das im unteren Bild funktioniert nicht.
![grafik](https://user-images.githubusercontent.com/44644567/163944978-6aeda24b-6014-46c8-81c1-e2a9e88b24f6.png)
![grafik](https://user-images.githubusercontent.com/44644567/163944992-645e6d8b-a990-4c2e-a7de-cf05c70dd58f.png)

**Comment by FrodBRA** [comment]
Lässt sich der Fehler noch reproduzieren bzw. gibt es eine DB mit der er auftritt?

Ich konnte Abteilungen ändern/hinzufügen und entfernen, ohne dass es einen Fehler gab.

Kann das Issue geschlossen werden?

@AnneSchueller
