### ISSUE TITLE
Aktuelle Schülerauswahl mit Jokerzeichen?

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#235]
SVWS: 0.2.8 Schild: 3.0.30.7
Aktuelle Schülerauswahl

    Der obere Bereich muss wohl noch entfernt werden
    Wird es wieder die Möglichkeit geben eine Auswahl mit Jokerzeichen zu versehen?
    Das im unteren Bild funktioniert nicht.
![grafik](https://user-images.githubusercontent.com/44644567/163945821-7d52c41b-9508-45ac-9b1e-7682acef9962.png)
![grafik](https://user-images.githubusercontent.com/44644567/163945838-0f7ece3c-4a38-49e0-ac8a-e46c44baa463.png)

**Comment by JuergenRichter** [comment]
Die Joker-Zeichen funktionieren grundsätzlich nur beim "Schnellfilter SchILD2". Dass dabei der Bereich "Klassen..." verschoben wird, konnte ich bei mir nicht reproduzieren. Welche Schulform?

**Comment by FPfotenhauer** [comment]
Das kann ich hier mit allen BK-Datenbanken reproduzieren.

**Comment by JuergenRichter** [comment]
Die falsche Darstellung war eine Folge von Fehlermeldungen bei Verwendung einer BK-Datenbank, nun behoben
