### ISSUE TITLE
Reiter/Tabs beim Schueler nicht dynamisch ein-/ausgeblendet

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#237]
SVWS: 0.2.8 Schild: 3.0.30.7
**Reiter/Tabs nicht dynamisch ein-/ausgeblendet**
tsZP10 dürfte es in einer BK-Datenbank nicht geben
Der angezeigte Schüler macht eine A01-Ausbildung; daher müssten die Reiter FHR und Abitur ausgeblendet sein.
BK-Abschluss fehlt hingegen. 
Hinweis: Die angezeigten Reiter ändern sich nicht, wenn zu einem D01-Schüler gewechselt wird.
![grafik](https://user-images.githubusercontent.com/44644567/163948145-4a4cb659-cb28-4124-9438-540722b8bd96.png)

**Comment by JuergenRichter** [comment]
Behoben
