### ISSUE TITLE
Leistungsdaten - Darstellungsfehler / Spaltenbreiten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#239]
SVWS: 0.2.8 Schild: 3.0.30.7
**Reiter Leistungsdaten**
- Hier wäre es schön, wenn die Spaltenbreiten automatisch optimiert werden, sodass nicht unbedingt gescrollt werden muss um die rechten Spalten sichtbar zu machen. WZE, Kursart, AufZeugnis, etc, könnten schmaler sein. Lehrkraft hingegen breiter!
- Die Boxen Zeugnis/Abschluss sind mehrfach vorhanden und liegen über der Fächerliste. Sie sind auch auf jedem Tab zu sehen
![grafik](https://user-images.githubusercontent.com/44644567/163948782-376f6099-1bc8-4dba-bf4d-7365160a3adf.png)

**Comment by JuergenRichter** [comment]
Spaltenbreiten werden benutzerbezogen gespeichert. Dass der Bereich Zeugnis/Abschluss immer sichtbar sein soll, war eine Forderung eines anderen Testers.

**Comment by JuergenRichter** [comment]
Die Hölhe des Bereiches Zeugnis/Abschluss wird noch optimiert

**Comment by JuergenRichter** [comment]
"Benutzerbezogen gespeichert" bedeutet, dass die Spaltenbreite, die einmal von einem Benutzer eingestellt witrd, für diesen gespeichert wird.
