### ISSUE TITLE
Folgeklasse in akt. HJ

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#24]
Ich vermisse die Angabe zur Folgeklasse im akt. HJ (Allg. Angaben) - verschoben??

**Comment by FPfotenhauer** [comment]
Bei mir ist der da:

![SNAG_2020_12_04_17 36 43](https://user-images.githubusercontent.com/34127980/101189433-56212700-3657-11eb-9dbe-77d4605c3066.png)

**Comment by AlexanderDedy** [comment]
Ok, war vermutlich ein Darstellungsproblem
