### ISSUE TITLE
Verwaltung/Schule überflüssiger Scrollbar?

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#240]
SVWS: 0.2.8 Schild: 3.0.30.7
![grafik](https://user-images.githubusercontent.com/44644567/163949267-1d1118d0-f3fb-4219-940e-ec694cf571da.png)
![grafik](https://user-images.githubusercontent.com/44644567/163949282-45767847-03f3-45af-8a60-c968ed222a5b.png)

**Comment by JuergenRichter** [comment]
Wird geprüft

**Comment by JuergenRichter** [comment]
Kann ich hier nicht reproduzieren. Ich schließe den Vorgang, falls das immer noch auftreten sollte, bitte erneut öffnen
