### ISSUE TITLE
Liste der Abschnitte unter akt. Abschnitt

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#241]
SVWS: 0.2.8 Schild: 3.0.30.7
**Zum Reiter Akt. Abschnitt**
-	Ist die Überschrift dynamisch für den Fall, dass unter Schule/organisatorische Angaben die Bezeichnung anders ist und 4 Abschnitte gewählt werden können?
-	Es wäre komfortabel, wenn die Haken bei gewertet auch in dieser Ansicht geändert werden könnten.
-	Der vertikale Skrollbalken sollte nur angezeigt werden, wenn nicht sichtbare Einträge vorhanden sind.
-	Die Abschnittsbezeichnung könnte platzsparender sein:
Aus 
2018/19, 1.Hj., Jahrgang A01_7-1, Kl. KFZ82  könnte 
2018/19#1, J:A01_7-1, K:KFZ82 werden. Das spart ein wenig Platz.
J: und K: wegzulassen ist in anderen Schulformen wahrscheinlich eher ungünstig.
![grafik](https://user-images.githubusercontent.com/44644567/163950010-5596691a-72d1-4ecc-8f84-4e2af5e16f7a.png)

![grafik](https://user-images.githubusercontent.com/44644567/163949504-005d3a6f-d236-4ca8-86eb-db6a77c23a35.png)

**Comment by FrodBRA** [comment]
Dies ist ein Mischissue:
1. Hinfällig, da es keine Quartale mehr gibt. Die Bezeichnung wird dynamisch gesetzt. Dies ist nach m.E. der wichtigste Aspekt in diesem Issue.
2. Nach wie vor nicht möglich, sollte aber als eigenes Issue eingereicht werden.
3. Könnte in der Tat ausgeblendet werden; sollte ein eigenes Issue sein. Minimale Änderung.
4. Ebenfalls ein kosmetischer Vorschlag, der in einem eigenen Issue diskutiert werden kann.

Mein Vorschlag ist, das Issue vorerst zu schließen und welche mit höherer Priorität abzuschließen.

@AnneSchueller

**Comment by EwaldReinhardt** [comment]
@AnneSchueller @FrodBRA 
Anstatt zu schließen wäre ein entsprechendes Label vielleicht besser: zurückgestellt

**Comment by AnneSchueller** [comment]
Ich verschiebe das in den Milestone "Nice to have"

**Comment by AnneSchueller** [comment]
Ich schließe das mal.
Das mit dem Wertungshaken ist noch wie 2021. Ist sicherlich nur eine Umgewöhnung, dass man den Haken hier nicht einfach umstellen kann (ist evtl auch ein Schutz, man liest ja immer mal wieder im Forum, dass hier Haken fehlen oder zu viel sind und keiner ist es gewesen)

Der Scrollbalken bindet man auch an anderen Stellen; Das würde ich jetzt erstmal so hinnehmen. (Ansonsten gerne nochmal in einem separaten Issue öffnen)

Die Anpassung der Überschrift funktioniert.
