### ISSUE TITLE
Abfragefehler bei Auswahl der bisher besuchten Schule

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#242]
SVWS: 0.2.8 Schild: 3.0.30.7

-	Wenn auf die Tilde links vom Plus-Button geklickt wird gibt es einen SQL-Fehler:
Die dazugehörigen Abfragen waren:
-	SELECT  *   FROM K_Schule   WHERE Sichtbar='+'   ORDER BY Name
select SchulNr, Kuerzel, KurzBez from K_Schule   where Kuerzel <> ''   order by Kuerzel
-	Der Dialog Schule auswählen (3. Bild) muss noch angepasst werden.
-	Im letzten dargestellten Bild (Dialog Schulanschrift) muss das S klein sein in der Fensterüberschrift.

![grafik](https://user-images.githubusercontent.com/44644567/163950615-34f0c288-cb4a-435f-814c-37b318f6bde0.png)
![grafik](https://user-images.githubusercontent.com/44644567/163950727-f7728554-9773-4563-b896-0b0897b9a393.png)
![grafik](https://user-images.githubusercontent.com/44644567/163950743-2122db28-0a18-40e8-b33e-a8efad4f1922.png)
![grafik](https://user-images.githubusercontent.com/44644567/163950758-da4cae22-9ba4-4867-83c3-abc22eef330f.png)

**Comment by AnneSchueller** [comment]
Schüler->Schulbesuch->Alle bisher besuchten Schulen -> +

![2023-02-08_115119](https://user-images.githubusercontent.com/79116896/217509621-e8274c29-2837-4980-91a5-bf4b0dc3887e.png)

**Comment by FrodBRA** [comment]
Ist das Issue noch aktuell? Ich konnte es nicht reproduzieren.

**Comment by AnneSchueller** [comment]
@JuergenRichter Nur noch der Rechtschreibfehler wenn man unter Schulbesuch auf das Briefsymbol klickt

**Comment by JuergenRichter** [comment]
Behoben
