### ISSUE TITLE
Auswahl / Filter I

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#243]
SVWS: 0.2.8 Schild: 3.0.30.7
-	Wenn ein gewählter Eintrag gelöscht werden soll, kann die Entf.-Taste nicht verwendet werden, sondern nur die Backspace Taste. Bei Entf. Kommt:
![grafik](https://user-images.githubusercontent.com/44644567/163951955-ce46cad4-232d-4f27-a9fc-1982a7747e10.png)

 
-	Die Tabs/Reiter könnten alle sichtbar sein, wenn der Platz genutzt würde.
-	Grundsätzlich sollte in allen Feldern auch die Möglichkeit bestehen auf _null_ abzufragen, da es so möglich wäre auch fehlende Einträge mit den Werten anderer Einträge bei der Auswahl zu verknüpfen.  
(Könnte z.B. mit einem Optionskästchen neben der Überschrift realisiert werden. Wenn das Kreuzchen gesetzt ist wird auf null geprüft. Wird der Haken gesetzt, wird der Wert in der Auswahl entfernt, wird ein Wert ausgewählt, wird die Null-Abfrage gelöscht. Damit die Datumsfelder auch entsprechend abgefragt werden können.
![grafik](https://user-images.githubusercontent.com/44644567/163951681-bdfb6517-9007-43ed-9b07-048f4a6fe7e8.png)

![grafik](https://user-images.githubusercontent.com/44644567/163952061-3e3fc30e-5a37-4d6e-8dd1-1e2ce6dab230.png)

**Comment by FrodBRA** [comment]
3.0.71.9

Die ersten beiden Punkte sind gelöst beziehungsweise gegenstandslos, da über Checkboxen im Dropdown-Men an- und abgewählt wird.

Es bleibt die Anfrage, nach "null" - also _ungesetzt_ - zu filtern.

**Comment by AnneSchueller** [comment]
Hier wäre die Frage, bei welchen Datenfeldern das sinnvoll ist.
Als Beispiel fällt mir hier ein, in vorangegangenen Abschnitten nach fehlenden Daten zu suchen. Für das aktuelle HJ und allgemeine Angaben ist ja über die Option "nach fehlenden Einträgen filtern" bereits das meiste abgedeckt (u.a. auch das Einschulungsjahr wie im obigen Beispiel).
@EwaldReinhardt : hattest du hier konkrete Situationen, bei denen man das braucht?

**Comment by EwaldReinhardt** [comment]
@AnneSchueller 
Man benötigt die Abfrage auf <null>, wenn nach fehlenden Einträgen in Kombination mit
anderen Werten gesucht wird, oder dass zwei Einträge gleichzeitig fehlen.
Das leistet der "Filter auf fehlende Einträge" nicht. 

Eine Situation, die mir sofort einfällt ist, das bei Schülern mit dem Status
Abgang oder Abschluss geschaut wird, ob der Eintrag Abgangsart fehlt.

Auf Nicht kann man nur in den Feldern testen, die eine Liste von
Elementen hat und diese durch Doppelklick kursiv werden.
(hier könnten dann alle Einträge gewählt werden und diese negiert werden,
sodass _wahrscheinlich_ nur leere Einträge gefunden werden)
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/d4c3489a-dd0f-4845-9ebe-43cbdbc01bcb)

Ich hätte also gerne: "(Status == Abgang OR Status == Abschluss) AND AbschlussArt is null"

Da gibt es noch mehr Abfragen, die sinnvoll anzuwenden wären, wenn man auf null testen könnte.

**Comment by AnneSchueller** [comment]
Das wäre tatsächlich ein Feld, bei dem das sinnvoll wäre. 
Also bei Abschlussart und Abschluss. Ich fände es für den Anwender hilfreich, dies dann "ohne Eintrag" oder "leer" oder so zu nennen anstatt "null"
@JuergenRichter wäre das realisierbar?

Zum Dropdownmenu: 
Das Menu mit Optionskästchen bleibt ja erstmal geöffnet, damit man ggf. noch weitere Optionen auswählen kann. Oder meinst du was anderes?

**Comment by EwaldReinhardt** [comment]
Man kann das natürlich auch als Auswahl machen. "ohne Eintrag" finde ich auch passend. 
Wenn der cursor das Dropdown verlässt gibt es einen Event, der genutzt werden könnte, damit nicht ein Klick auf ein anderes Feld "verloren" geht. 
Oder erwartest du dieses unterschiedliche Verhalten nur weil Boxen im Dropdown enthalten sind? 


⁣Ewald Reinhardt
Bereichleiter Metall
IT-Koordinator

Raithelplatz 5
58509 Lüdenscheid
mobil +49 1577 5171570
fon +49 2351 966 3128​

**Comment by AnneSchueller** [comment]
Ah jetzt weiß ich was du meinst.
Das Dropdown Menu bleibt geöffnet, bis der User in die Oberfläche klickt; dieser Klick soll dann bereits berücksichtigt werden und es ggf. eine entsprechende Aktion ausgeführt werden... 
Ja das wäre konstanter. Würde ich aber von der Priorität erstmal hintenan stellen.

**Comment by FrodBRA** [comment]
@AnneSchueller 

Ich schlage vor, ein neues Issue mit der null-Filterung zu erstellen und dieses Sammelissue, bei dem die anderen Punkte abgearbeitet sind, zu schließen.

**Comment by EwaldReinhardt** [comment]
Ja, das ist bestimmt sinnvoll.

**Comment by AnneSchueller** [comment]
Schließe ich:
Weiteres siehe hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/779
