### ISSUE TITLE
Auswahl Klasse

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#244]
3.0.31.7 und ältere: Wählt man in der Auswahl z.B. die Q1, setzt sich der Haken immer bei 08A, also in einer ganz anderen Klasse. Erst ein zweiter Versuch wählt die gewünschte Klasse.

**Comment by AnneSchueller** [comment]
Mit der neuen Version 3.0.32.7 tritt das Problem (bei meiner Datenbank) nicht auf. 
Bitte nochmal rückmelden, falls der Filter auf Jahrgang/Klassen mit der aktuellen Schild3 Version falsche Klassen auswählt.

**Comment by HHayen** [comment]
Beim ERSTEN Filtern besteht der Fehler noch. Wurde einmal eine Klasse gewählt, funktioniert es.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AnneSchueller ***@***.***> Datum: 02.05.22  18:42  (GMT+01:00) An: SVWS-NRW/Schild3-BetaTest ***@***.***> Cc: HHayen ***@***.***>, Author ***@***.***> Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Auswahl Klasse (Issue #244) 

Mit der neuen Version 3.0.32.7 tritt das Problem (bei meiner Datenbank) nicht auf.

Bitte nochmal rückmelden, falls der Filter auf Jahrgang/Klassen mit der aktuellen Schild3 Version falsche Klassen auswählt.

**Comment by AnneSchueller** [comment]
Bei mir läuft der Filter gut (bis auf lange Wartezeiten).
Neustart von Schild --> Aktuelle Schülerauswahl --> Kasse Q1 klappt
Neustart --> Aktuelle Schülerauswahl --> Jahrgang Q1 klappt.
Neustart --> Filter I --> Klasse Q1 klappt

Hast du das mal mit der aktuellen Version getestet?

**Comment by HHayen** [comment]
Ich schwöre, ich habe auf Q2 geklickt.

Version 3.0.32.7


Das Phänomen taucht nur nach Neustart beim allerersten Filtern auf, 
danach nie wieder. Aber reproduzierbar nach jedem Neustart, wenn das die 
erste Aktion ist. Scrollt man in der Filterleiste vorher etwas hin und 
her passiert das nicht.

Daher ist das vielleicht jetzt nicht die größte Baustelle, nervt halt 
nur ganz leicht ;-)




Am 02.05.2022 um 21:44 schrieb AnneSchueller:

**Comment by AnneSchueller** [comment]
Tatsache... mit Auswahl Q2 habe ich das gleiche Problem.
