### ISSUE TITLE
Scrollen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#245]
Das Scrollen des Namenscontainers ist viel zu  langsam und ruckelig.

**Comment by AnneSchueller** [comment]
Das kann ich bestätigen. Ebenso kommt es bei Betätigung des Scroll Balkens im Schülercontainer zu langen Wartezeiten.

**Comment by AnneSchueller** [comment]
Mit der neuen Version von Schild3 läuft das scrollen bereits schneller.
Wäre es eine Option, beim Scroll-Vorgang mit dem Mausrad die Schülerdaten gar nicht zu laden und erst wenn ein neuer Schüler mit Mausklick ausgewählt wird die entsprechenden Daten zu laden?

**Comment by JuergenRichter** [comment]
Werde ich mal prüfen, im Prinzip müsste man das aber genauso machen können wie bei Scrollen mittels Schieberegler, man muss nur abfragen, ob das Mausrad bedient wird.

**Comment by AnneSchueller** [comment]
Beim Schieberegler könnte man das evtl. auch integrieren, dass Daten erst nach der Auswahl eines konkreten Schülers geladen werden.

**Comment by JuergenRichter** [comment]
Die Ursache ist eher eine andere. In SchILD wird im Prinzip folgende Haup-Abfrage ausgeführt:
select <feldliste> from Schueler where <bedingung> order by <sortierung>
D.h. das alle "Stammdatenfelder" gelade werden und in einem Query-Objekt im Speicher zur Verfügung stehen, d.h. die Daten sind schon da. Allerdings hat sich gegenüber ScHILD2 eine Änderung ergeben:
Die aktuellen "Laufbahndaten" sind jetzt nicht mehr in den Stammdaten enthalten (wie in SchILd3), sondern müssen aus den "Lernabschnittsdaten" (mit gleicher Schuljahresabschnitts_ID wie beim Schülerdatensatz) geholt werden (z.B. die aktuelle Klasse).Das hat zur Folge, dass bei jedem Schülerwechsel immer eine weitere Abfrage auf die aktuellen Lernabschnittsdaten ausgeführt werden muss. 
Eine mögliche Alternative wäre, alle benötigten "Stammdaten" (zu denen dann z.B. auch die aktuelle Klasse gehört) in Form eines JOIN Befehles direkt in die Hauptabfrage zu integrieren, dann wären weniger Unterabfragen beim Schülerwechsel notwendig. Das habe ich bisher vermieden, da man dann Abfragefelder aus mehreren Tabelle hat, was beim Speichern von Änderungen des Query-Objektes Probleme geben kann. Ich habe aber nun einen Weg gefunden, den Speichervorgang nur auf die Tabelle "Schueler" zu beschränken. Ich werde das mal testen.

**Comment by JuergenRichter** [comment]
Da hat github wohl einige Infos gekappt. Eigenlich sollte die Pseudoabfrage so aussehen

select "feldliste" from Schueler where "bedingung" order by "sortierung"

Ursprünglich war das, was in " eingeschlossen ist, mit spitzen Klammern versehen, das scheint github aber nicht zu mögen

**Comment by JuergenRichter** [comment]
Ersetze " (wie in SchILd3)" durch " (wie in SchILD2)",

**Comment by AnneSchueller** [comment]
Muss der Select-Befehl denn zwingen beim Scroll-Vorgang bzw. beim Verschieben des Schieberegler durchgeführt werden? Oder könnte man ihn evtl. auch erst dann anstoßen, sobald man nach dem Scrollen einen konkreten Schüler ausgewählt hat?

**Comment by JuergenRichter** [comment]
Ich habe heute eine neue Version auf Github hochgeladen, bitte damit mal testen.

**Comment by FPfotenhauer** [comment]
FB-Cloud muss ich machen. Habe ich gerade :-)

Bei mir scrollt das jetzt wie der Blitz!

**Comment by HHayen** [comment]
Flutscht bei allen aktiven Reitern. Selbst bei "Aktuellem HJ" schneller als in Schild2. TOP!!!

**Comment by AnneSchueller** [comment]
Das kann ich auch nochmal bestätigen. Scrollen klappt super.

**Comment by JuergenRichter** [comment]
Bitte auch mal einige Reports (Schülerlisten) testen, da wird jetzt die gleiche Technik verwendet.

**Comment by AnneSchueller** [comment]
Ich habe aus der Basissammlung stichprobenartig Schülerlisten, Klassenlisten und Kurslisten getestet. 
Alle Reports funktionieren.
