### ISSUE TITLE
Schuljahreswechsel

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#246]
3.0.31.7: Fehlermeldung bei "Verwaltung"-> "Schuljahreswechsel", ähnliche Meldungen beim Gruppenprozess Abschnittswechsel:

EurekaLog 7.10.0.0 8BD69D43571B8C48A2404FB6F3744F60 6D78869ABE41B443BAE2395668CA46EA DA39A3EE5E6B4B0D3255BFEF95601890AFD80709 E1A640CFECB9B04DA32A65024F886529

Application:
-------------------------------------------------------------------
  1.1 Start Date      : Thu, 28 Apr 2022 21:40:14 +0200
  1.2 Name/Description: SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  1.3 Version Number  : 3.0.31.7
  1.4 Parameters      : 
  1.5 Compilation Date: Fri, 22 Apr 2022 17:30:05 +0200
  1.6 Up Time         : 2 minute(s), 40 second(s)

Exception:
---------------------------------------------------------------------------
  2.1 Date          : Thu, 28 Apr 2022 21:42:55 +0200
  2.2 Address       : 00E075BD
  2.3 Module Name   : SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  2.4 Module Version: 3.0.31.7
  2.5 Type          : EMyError
  2.6 Message       ** #42S22Unknown column 'ASDJahrgang' in 'where clause'.**
  2.7 ID            : B878FAB1
  2.8 Count         : 1
  2.9 Status        : New
  2.10 Note         : 
  2.11 Sent         : 0

User:
----------------------------------------------------------------
  3.1 ID        : 
  3.2 Name      : H. Hayen
  3.3 Email     : 
  3.4 Company   : 
  3.5 Privileges: SeShutdownPrivilege             - OFF
                  SeChangeNotifyPrivilege         - ON (default)
                  SeUndockPrivilege               - OFF
                  SeIncreaseWorkingSetPrivilege   - OFF
                  SeTimeZonePrivilege             - OFF

Active Controls:
---------------------------------------------------------------------------------------------------------------------------------------------------------------
  4.1 Form Class   : Tfrm_Hauptformular
  4.2 Form Text    : Aktuelle Datenbank: SchILD2000n_eickel, Schuljahr 2021/2022, 2. Hj., Benutzer: hayen (keine Verbindung zum SVWS-Server: Status-Code = 404)
  4.3 Control Class: Tfrm_Hauptformular
  4.4 Control Text : Aktuelle Datenbank: SchILD2000n_eickel, Schuljahr 2021/2022, 2. Hj., Benutzer: hayen (keine Verbindung zum SVWS-Server: Status-Code = 404)

Computer:
--------------------------------------------
  5.1 Name        : DESKTOP-N1xxxxx
  5.2 Total Memory: 8502935552 (7,92 Gb)
  5.3 Free Memory : 1084739584 (1,01 Gb)
  5.4 Total Disk  : 125593186304 (116,97 Gb)
  5.5 Free Disk   : 10250690560 (9,55 Gb)
  5.9 Display DPI : 96

Operating System:
---------------------------------------------
  6.1 Type    : Microsoft Windows 10 (64 bit)
  6.2 Build # : 2009 (10.0.19043.1645)
  6.3 Update  : May 2021 Update [21H1] #1645
  6.4 Language: German (0407)
  6.5 Charset : 0/1252

Call Stack Information:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|Methods |Details|Stack   |Address |Module      |Offset  |Source                |Unit              |Class               |Procedure/Method                            |Line           |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|*Exception Thread: ID=6852; Parent=0; Priority=0                                                                                                                                    |
|Class=; Name=MAIN                                                                                                                                                                   |
|DeadLock=0; Wait Chain=                                                                                                                                                             |
|Comment=                                                                                                                                                                            |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|03     |00000000|00E075BD|SchILD30.exe|00A075BD|MyClassesUni.pas      |MyClassesUni      |TMySQLConnection    |MySQLError                                  |               |
|00000040|03     |0019F6A0|00E0B0EE|SchILD30.exe|00A0B0EE|MyClassesUni.pas      |MyClassesUni      |TMySQLCommand       |Check                                       |               |
|00000040|03     |0019F6F0|00E0FC0D|SchILD30.exe|00A0FC0D|MyClassesUni.pas      |MyClassesUni      |TMySQLCommand       |InternalExecute                             |               |
|00000040|03     |0019F710|00E0FD35|SchILD30.exe|00A0FD35|MyClassesUni.pas      |MyClassesUni      |TMySQLCommand       |Execute                                     |               |
|00000040|03     |0019F758|00B14A19|SchILD30.exe|00714A19|CRAccess.pas          |CRAccess          |TCRRecordSet        |ExecCommand                                 |               |
|00000040|03     |0019F79C|00E10D3B|SchILD30.exe|00A10D3B|MyClassesUni.pas      |MyClassesUni      |TMySQLRecordSet     |ExecCommand                                 |               |
|00000040|03     |0019F7CC|00B16E79|SchILD30.exe|00716E79|CRAccess.pas          |CRAccess          |TCRRecordSet        |ExecFetch                                   |               |
|00000040|03     |0019F7E4|00B14623|SchILD30.exe|00714623|CRAccess.pas          |CRAccess          |TCRRecordSet        |InternalOpen                                |               |
|00000040|03     |0019F808|00E1189F|SchILD30.exe|00A1189F|MyClassesUni.pas      |MyClassesUni      |TMySQLRecordSet     |InternalOpen                                |               |
|00000040|03     |0019F82C|00A3DCFC|SchILD30.exe|0063DCFC|MemData.pas           |MemData           |TData               |Open                                        |               |
|00000040|03     |0019F850|00AA9520|SchILD30.exe|006A9520|MemDS.pas             |MemDS             |TMemDataSet         |InternalOpen                                |               |
|00000040|04     |0019F8A0|00A071BE|SchILD30.exe|006071BE|Data.DB.pas           |Data.DB           |TDataSet            |DoInternalOpen                              |12630[2]       |
|00000040|03     |0019F918|00B396CF|SchILD30.exe|007396CF|Uni.pas               |Uni               |TCustomUniDataSet   |OpenCursor                                  |               |
|00000040|04     |0019F938|00A07125|SchILD30.exe|00607125|Data.DB.pas           |Data.DB           |TDataSet            |SetActive                                   |12611[12]      |
|00000040|03     |0019F954|00ADB873|SchILD30.exe|006DB873|DBAccess.pas          |DBAccess          |TCustomDADataSet    |SetActive                                   |               |
|00000040|04     |0019FA14|025C73DB|SchILD30.exe|021C73DB|Unit_ModeSwitcher.pas |Unit_ModeSwitcher |TModeSwitcher       |CheckForms                                  |939[490]       |
|00000040|04     |0019FA58|025C83C8|SchILD30.exe|021C83C8|Unit_ModeSwitcher.pas |Unit_ModeSwitcher |TModeSwitcher       |SetFormMode                                 |1043[15]       |
|00000040|04     |0019FA74|0275B731|SchILD30.exe|0235B731|Form_Hauptformular.pas|Form_Hauptformular|Tfrm_Hauptformular  |Act_Schulverwaltung_AbschnittWechselnExecute|4951[2]        |
|00000040|04     |0019FA84|0055BD87|SchILD30.exe|0015BD87|System.Classes.pas    |System.Classes    |TBasicAction        |Execute                                     |17452[3]       |
|00000040|04     |0019FAC4|026C9B13|SchILD30.exe|022C9B13|uBackstageMenu.pas    |uBackStageMenu    |TCustomBackstageMenu|InternalMouseUp                             |905[22]        |
|00000040|04     |0019FAE0|006952C8|SchILD30.exe|002952C8|Vcl.Controls.pas      |Vcl.Controls      |TControl            |MouseUp                                     |7658[1]        |
|00000040|04     |0019FAFC|00695308|SchILD30.exe|00295308|Vcl.Controls.pas      |Vcl.Controls      |TControl            |DoMouseUp                                   |7664[2]        |
|00000040|04     |0019FC7C|006945B8|SchILD30.exe|002945B8|Vcl.Controls.pas      |Vcl.Controls      |TControl            |Perform                                     |7198[10]       |
|00000040|04     |0019FC98|00698C8C|SchILD30.exe|00298C8C|Vcl.Controls.pas      |Vcl.Controls      |TWinControl         |IsControlMouseMsg                           |10047[15]      |
|00000040|04     |0019FD14|00698A00|SchILD30.exe|00298A00|Vcl.Controls.pas      |Vcl.Controls      |TWinControl         |MainWndProc                                 |9977[3]        |
|00000040|04     |0019FD44|0055CADC|SchILD30.exe|0015CADC|System.Classes.pas    |System.Classes    |                    |StdWndProc                                  |17956[8]       |
|00000040|04     |0019FEEC|007C0313|SchILD30.exe|003C0313|Vcl.Forms.pas         |Vcl.Forms         |TApplication        |ProcessMessage                              |10747[23]      |
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Modules Information:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|Handle  |Name                       |Description                                           |Version            |Size    |Modified           |Path                                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|00400000|SchILD30.exe               |SchILD 3.0 von ribeka GmbH                            |3.0.31.7           |54848056|2022-04-26 17:15:26|C:\Program Files (x86)\SchILD3.0\                                                                             |
|042E0000|ChilkatDelphi32.dll        |Chilkat Delphi DLL 32-bit                             |9.5.0.82           |10655936|2022-04-01 17:19:28|C:\Program Files (x86)\SchILD3.0\                                                                             |
|07EB0000|crypt32.dll                |Krypto-API32                                          |10.0.19041.1320    |1013344 |2021-11-13 16:38:54|C:\Windows\System32\                                                                                          |
|10000000|lz32.dll                   |LZ Expand/Compress API DLL                            |5.0.1.1            |2560    |2019-12-07 11:09:26|C:\Windows\System32\                                                                                          |
|50030000|borlndmm.dll               |Embarcadero Memory Manager                            |25.0.29899.2631    |70000   |2022-04-01 17:19:30|C:\Program Files (x86)\SchILD3.0\                                                                             |
|590F0000|ieframe.dll                |Internet Browser                                      |11.0.19041.1620    |6488064 |2022-04-13 19:37:35|C:\Windows\System32\                                                                                          |
|59B00000|hhctrl.ocx                 |Steuerelement für Microsoft® HTML-Hilfe               |10.0.19041.746     |575488  |2021-01-13 06:11:36|C:\Windows\System32\                                                                                          |
|59BA0000|url.dll                    |Internet Shortcut Shell Extension DLL                 |11.0.19041.1       |233472  |2019-12-07 11:10:00|C:\Windows\System32\                                                                                          |
|59BE0000|osbaseln.dll               |Service Reporting API                                 |10.0.19041.1       |21504   |2019-12-07 11:09:13|C:\Windows\System32\                                                                                          |
|59BF0000|duser.dll                  |Windows DirectUser Engine                             |10.0.19041.546     |470528  |2020-10-14 07:41:45|C:\Windows\System32\                                                                                          |
|59C70000|appwiz.cpl                 |Shellanwendungs-Manager                               |10.0.19041.746     |469504  |2021-01-13 06:11:36|C:\Windows\System32\                                                                                          |
|59CF0000|msls31.dll                 |Microsoft Line Services library file                  |3.10.349.0         |183808  |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|59D30000|riched20.dll               |Rich Text Edit Control, v3.1                          |5.31.23.1231       |487424  |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|59DB0000|wer.dll                    |Windows-Fehlerbericht-DLL                             |10.0.19041.1620    |706592  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|59E60000|Faultrep.dll               |Windows-Benutzermodus-Absturzberichterstattungs-DLL   |10.0.19041.1566    |416816  |2022-03-09 03:47:06|C:\Windows\System32\                                                                                          |
|59ED0000|winmmbase.dll              |API für die Basissystemverlängerung                   |10.0.19041.1       |110720  |2019-12-07 11:09:11|C:\Windows\System32\                                                                                          |
|59EF0000|msacm32.dll                |Microsoft ACM-Audiofilter                             |10.0.19041.1       |93472   |2019-12-07 11:09:11|C:\Windows\System32\                                                                                          |
|59F10000|tapi32.dll                 |Microsoft® Windows(TM) Telefonie-API-Client-DLL       |10.0.19041.423     |193536  |2020-10-10 12:54:20|C:\Windows\System32\                                                                                          |
|59F50000|fontsub.dll                |Font Subsetting DLL                                   |10.0.19041.1620    |99328   |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|59F70000|shdocvw.dll                |Shelldokumentobjekt und Steuerungsbibliothek          |10.0.19041.746     |218112  |2021-01-13 06:11:13|C:\Windows\System32\                                                                                          |
|5A070000|wsock32.dll                |Windows Socket 32-Bit DLL                             |10.0.19041.1       |16384   |2019-12-07 11:09:15|C:\Windows\System32\                                                                                          |
|5A080000|shfolder.dll               |Shell Folder Service                                  |10.0.19041.1       |8704    |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|5A090000|msvfw32.dll                |DLL für Microsoft Video für Windows                   |10.0.19041.1       |124416  |2019-12-07 11:10:04|C:\Windows\System32\                                                                                          |
|5A0C0000|avifil32.dll               |Microsoft AVI-Dateiunterstützungs-Bibliothek          |10.0.19041.1       |95744   |2019-12-07 11:10:04|C:\Windows\System32\                                                                                          |
|5A0E0000|oledlg.dll                 |OLE-Benutzerschnittstellen-Unterstützung              |10.0.19041.746     |163328  |2021-01-13 06:11:07|C:\Windows\System32\                                                                                          |
|5A110000|olepro32.dll               |OLEPRO32.DLL                                          |10.0.19041.84      |88576   |2020-10-10 12:54:02|C:\Windows\System32\                                                                                          |
|5A1A0000|usp10.dll                  |Uniscribe Unicode script processor                    |10.0.19041.546     |77824   |2020-10-14 07:41:45|C:\Windows\System32\                                                                                          |
|5F6D0000|ncryptsslp.dll             |Microsoft SChannel Provider                           |10.0.19041.546     |117216  |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|5FC50000|mskeyprotect.dll           |Microsoft-Schlüsselschutzanbieter                     |10.0.19041.1202    |49664   |2021-09-16 18:29:02|C:\Windows\System32\                                                                                          |
|60040000|schannel.dll               |TLS/ SSL-Sicherheitsanbieter                          |10.0.19041.1645    |468992  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|63280000|windowscodecs.dll          |Microsoft Windows Codecs Library                      |10.0.19041.1151    |1510296 |2021-08-10 22:37:18|C:\Windows\System32\                                                                                          |
|6A2E0000|ntasn1.dll                 |Microsoft ASN.1 API                                   |10.0.19041.546     |161608  |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|6A310000|ncrypt.dll                 |Windows NCrypt-Router                                 |10.0.19041.546     |130128  |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|6BC20000|dcomp.dll                  |Microsoft DirectComposition Library                   |10.0.19041.1566    |1448744 |2022-03-09 03:47:06|C:\Windows\System32\                                                                                          |
|6BD90000|d3d11.dll                  |Direct3D 11 Runtime                                   |10.0.19041.1620    |1964240 |2022-04-13 19:37:22|C:\Windows\System32\                                                                                          |
|6D030000|FWPUCLNT.DLL               |FWP/IPsec Benutzermodus-API                           |10.0.19041.1526    |341504  |2022-02-09 13:14:29|C:\Windows\System32\                                                                                          |
|6D730000|dhcpcsvc6.DLL              |DHCPv6-Client                                         |10.0.19041.546     |61440   |2020-10-14 07:41:43|C:\Windows\System32\                                                                                          |
|6D750000|dataexchange.dll           |Data exchange                                         |10.0.19041.1387    |183808  |2021-12-16 18:26:07|C:\Windows\System32\                                                                                          |
|6DAF0000|mscms.dll                  |Microsoft-Farbabstimmungssystem-DLL                   |10.0.19041.746     |594464  |2021-01-13 06:10:58|C:\Windows\System32\                                                                                          |
|6E010000|CoreUIComponents.dll       |Microsoft Core UI Components Dll                      |10.0.19041.546     |2621720 |2020-10-14 07:41:36|C:\Windows\System32\                                                                                          |
|6E290000|secur32.dll                |Security Support Provider Interface                   |10.0.19041.546     |23040   |2020-10-14 07:41:46|C:\Windows\System32\                                                                                          |
|6E2D0000|dxgi.dll                   |DirectX Graphics Infrastructure                       |10.0.19041.1566    |785064  |2022-03-09 03:47:02|C:\Windows\System32\                                                                                          |
|6E4B0000|dhcpcsvc.dll               |DHCP Clientdienst                                     |10.0.19041.546     |73728   |2020-10-14 07:41:43|C:\Windows\System32\                                                                                          |
|6E530000|CoreMessaging.dll          |Microsoft CoreMessaging Dll                           |10.0.19041.867     |630592  |2021-03-10 03:46:25|C:\Windows\System32\                                                                                          |
|6E5D0000|textinputframework.dll     |"TextInputFramework.DYNLINK"                          |10.0.19041.1503    |753072  |2022-02-09 13:14:29|C:\Windows\System32\                                                                                          |
|6F0C0000|rasadhlp.dll               |Remote Access AutoDial Helper                         |10.0.19041.546     |12800   |2020-10-14 07:41:48|C:\Windows\System32\                                                                                          |
|6F0D0000|dwmapi.dll                 |Microsoft Desktopfenster-Manager-API                  |10.0.19041.746     |138936  |2021-01-13 06:11:07|C:\Windows\System32\                                                                                          |
|6F4C0000|twinapi.appcore.dll        |twinapi.appcore                                       |10.0.19041.746     |1634208 |2021-01-13 06:11:03|C:\Windows\System32\                                                                                          |
|6F650000|winnsi.dll                 |Network Store Information RPC interface               |10.0.19041.546     |28360   |2020-10-14 07:41:23|C:\Windows\System32\                                                                                          |
|70410000|msi.dll                    |Windows Installer                                     |5.0.19041.1645     |2692608 |2022-04-13 19:37:35|C:\Windows\System32\                                                                                          |
|706C0000|oleacc.dll                 |Active Accessibility Core Component                   |7.2.19041.746      |321024  |2021-01-13 06:11:12|C:\Windows\System32\                                                                                          |
|70790000|WinTypes.dll               |Windows-Basistypen-DLL                                |10.0.19041.1348    |896088  |2021-11-13 16:38:54|C:\Windows\System32\                                                                                          |
|70EB0000|TextShaping.dll            |                                                      |                   |611960  |2021-10-13 11:12:42|C:\Windows\System32\                                                                                          |
|71000000|powrprof.dll               |Power Profile Helper DLL                              |10.0.19041.546     |268080  |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|710E0000|webio.dll                  |API für Webtransferprotokolle                         |10.0.19041.1620    |452096  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|71220000|ondemandconnroutehelper.dll|On Demand Connctiond Route Helper                     |10.0.19041.546     |56832   |2020-10-14 07:41:35|C:\Windows\System32\                                                                                          |
|71270000|ColorAdapterClient.dll     |Microsoft Color Adapter Client                        |10.0.19041.546     |45904   |2020-10-14 07:41:37|C:\Windows\System32\                                                                                          |
|71280000|winmm.dll                  |MCI API-DLL                                           |10.0.19041.546     |149272  |2020-10-14 07:41:32|C:\Windows\System32\                                                                                          |
|71420000|ntmarta.dll                |Windows NT MARTA-Anbieter                             |10.0.19041.546     |152904  |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|71470000|umpdc.dll                  |                                                      |                   |47472   |2020-10-14 07:41:40|C:\Windows\System32\                                                                                          |
|72720000|winsta.dll                 |Winstation Library                                    |10.0.19041.546     |270640  |2020-10-14 07:41:34|C:\Windows\System32\                                                                                          |
|72770000|srvcli.dll                 |Server Service Client DLL                             |10.0.19041.1645    |78016   |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|72790000|urlmon.dll                 |OLE32-Erweiterung für Win32                           |11.0.19041.1566    |1679872 |2022-03-09 03:47:07|C:\Windows\System32\                                                                                          |
|72940000|iertutil.dll               |Laufzeit-Hilfsprogramm für Internet Explorer          |11.0.19041.1586    |2271560 |2022-03-09 03:47:07|C:\Windows\System32\                                                                                          |
|72CC0000|sspicli.dll                |Security Support Provider Interface                   |10.0.19041.1586    |123984  |2022-03-09 03:46:59|C:\Windows\System32\                                                                                          |
|72CF0000|propsys.dll                |Microsoft-Eigenschaftensystem                         |7.0.19041.1023     |791808  |2021-06-11 21:39:31|C:\Windows\System32\                                                                                          |
|72DC0000|wkscli.dll                 |Workstation Service Client DLL                        |10.0.19041.1645    |64552   |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|732F0000|wininet.dll                |Interneterweiterungen für Win32                       |11.0.19041.1566    |4509696 |2022-03-09 03:47:06|C:\Windows\System32\                                                                                          |
|73A60000|mpr.dll                    |Router-DLL für Mehrfachanbieter                       |10.0.19041.1566    |96080   |2022-03-09 03:47:06|C:\Windows\System32\                                                                                          |
|74340000|dnsapi.dll                 |DNS-Client-API-DLL                                    |10.0.19041.1620    |586768  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|745D0000|gpapi.dll                  |Gruppenrichtlinienclient-API                          |10.0.19041.572     |111024  |2020-10-14 07:41:45|C:\Windows\System32\                                                                                          |
|745F0000|CRYPTBASE.dll              |Base cryptographic API DLL                            |10.0.19041.546     |31528   |2020-10-14 07:41:32|C:\Windows\System32\                                                                                          |
|74600000|rsaenh.dll                 |Microsoft Enhanced Cryptographic Provider             |10.0.19041.1052    |184888  |2021-06-11 21:39:33|C:\Windows\System32\                                                                                          |
|74630000|cryptsp.dll                |Cryptographic Service Provider API                    |10.0.19041.546     |68192   |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|74780000|dpapi.dll                  |Data Protection API                                   |10.0.19041.546     |13312   |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|74C00000|profapi.dll                |User Profile Basic API                                |10.0.19041.844     |89360   |2021-03-10 03:46:19|C:\Windows\System32\                                                                                          |
|74C20000|wldp.dll                   |Windows-Sperrungsrichtlinie                           |10.0.19041.1566    |140472  |2022-03-09 03:47:06|C:\Windows\System32\                                                                                          |
|74C50000|windows.storage.dll        |Microsoft WinRT Storage-API                           |10.0.19041.1566    |6371544 |2022-03-09 03:47:04|C:\Windows\System32\                                                                                          |
|75280000|netutils.dll               |Net Win32 API Helpers DLL                             |10.0.19041.1466    |38232   |2022-01-12 20:53:32|C:\Windows\System32\                                                                                          |
|75290000|IPHLPAPI.DLL               |IP-Hilfs-API                                          |10.0.19041.546     |196784  |2020-10-14 07:41:43|C:\Windows\System32\                                                                                          |
|75310000|mswsock.dll                |Microsoft Windows Sockets 2.0-Dienstanbieter          |10.0.19041.546     |324416  |2020-10-14 07:41:43|C:\Windows\System32\                                                                                          |
|75370000|netapi32.dll               |Net Win32 API DLL                                     |10.0.19041.1645    |78016   |2022-04-13 19:37:21|C:\Windows\System32\                                                                                          |
|75390000|winhttp.dll                |Windows HTTP-Dienste                                  |10.0.19041.1620    |823256  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|75460000|version.dll                |Version Checking and File Installation Libraries      |10.0.19041.546     |27320   |2020-10-14 07:41:48|C:\Windows\System32\                                                                                          |
|75470000|wtsapi32.dll               |Windows Remote Desktop Session Host Server SDK APIs   |10.0.19041.546     |52664   |2020-10-14 07:41:34|C:\Windows\System32\                                                                                          |
|754F0000|msimg32.dll                |GDIEXT Client DLL                                     |10.0.19041.1466    |7168    |2022-01-12 20:53:32|C:\Windows\System32\                                                                                          |
|75520000|uxtheme.dll                |Microsoft UxTheme-Bibliothek                          |10.0.19041.1620    |454656  |2022-04-13 19:37:21|C:\Windows\System32\                                                                                          |
|75610000|comctl32.dll               |Bibliothek für Steuerelemente                         |6.10.19041.1110    |2152264 |2021-07-09 08:47:26|C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\|
|75820000|winspool.drv               |Windows-Spoolertreiber                                |10.0.19041.1566    |445952  |2022-03-09 03:46:59|C:\Windows\System32\                                                                                          |
|75930000|msasn1.dll                 |ASN.1 Runtime APIs                                    |10.0.19041.546     |50616   |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|75940000|GdiPlus.dll                |Microsoft GDI+                                        |10.0.19041.1645    |1448448 |2022-04-02 11:20:54|C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1645_none_d94fdd3fe105c111\        |
|75AC0000|kernel.appcore.dll         |AppModel API Host                                     |10.0.19041.546     |52672   |2020-10-14 07:41:40|C:\Windows\System32\                                                                                          |
|75AD0000|dbgcore.dll                |Windows Core Debugging Helpers                        |10.0.19041.546     |138752  |2020-10-14 07:41:45|C:\Windows\System32\                                                                                          |
|75B00000|dbghelp.dll                |Windows Image Helper                                  |10.0.19041.1052    |1494016 |2021-06-11 21:39:33|C:\Windows\System32\                                                                                          |
|75C90000|userenv.dll                |Userenv                                               |10.0.19041.572     |141008  |2020-10-14 07:41:44|C:\Windows\System32\                                                                                          |
|75D10000|comdlg32.dll               |DLL für gemeinsame Dialoge                            |10.0.19041.1566    |689152  |2022-03-09 03:47:08|C:\Windows\System32\                                                                                          |
|75E60000|shlwapi.dll                |Shell Light-weight-Hilfsprogrammbibliothek            |10.0.19041.1023    |275808  |2021-06-11 21:39:34|C:\Windows\System32\                                                                                          |
|75EB0000|msvcp_win.dll              |Microsoft® C Runtime Library                          |10.0.19041.789     |495840  |2021-02-13 15:38:39|C:\Windows\System32\                                                                                          |
|75F30000|user32.dll                 |Client-DLL für Windows USER-API (mehrere Benutzer)    |10.0.19041.1645    |1679160 |2022-04-13 19:37:24|C:\Windows\System32\                                                                                          |
|760D0000|nsi.dll                    |NSI User-mode interface DLL                           |10.0.19041.610     |20144   |2020-11-15 11:11:41|C:\Windows\System32\                                                                                          |
|760E0000|advapi32.dll               |Erweiterte Windows 32 Base-API                        |10.0.19041.1466    |495312  |2022-01-12 20:53:28|C:\Windows\System32\                                                                                          |
|765A0000|SHCore.dll                 |SHCORE                                                |10.0.19041.1645    |545984  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|76670000|ucrtbase.dll               |Microsoft® C Runtime Library                          |10.0.19041.789     |1181208 |2021-02-13 15:38:39|C:\Windows\System32\                                                                                          |
|76900000|KERNELBASE.dll             |Client-DLL für Windows NT-Basis-API                   |10.0.19041.1645    |2182216 |2022-04-13 19:37:19|C:\Windows\System32\                                                                                          |
|76B20000|bcryptPrimitives.dll       |Windows Cryptographic Primitives Library              |10.0.19041.1415    |383264  |2021-12-16 18:26:01|C:\Windows\System32\                                                                                          |
|76C40000|clbcatq.dll                |COM+ Configuration Catalog                            |2001.12.10941.16384|504552  |2020-10-14 07:41:42|C:\Windows\System32\                                                                                          |
|76CC0000|ws2_32.dll                 |Windows Socket 2.0-32-Bit-DLL                         |10.0.19041.546     |397728  |2020-10-14 07:41:32|C:\Windows\System32\                                                                                          |
|76D30000|shell32.dll                |Allgemeine Windows-Shell-DLL                          |10.0.19041.1566    |6012560 |2022-03-09 03:47:08|C:\Windows\System32\                                                                                          |
|772F0000|msvcrt.dll                 |Windows NT CRT DLL                                    |7.0.19041.546      |775256  |2020-10-14 07:41:32|C:\Windows\System32\                                                                                          |
|773B0000|sechost.dll                |Host for SCM/SDDL/LSA Lookup APIs                     |10.0.19041.1586    |477824  |2022-03-09 03:46:59|C:\Windows\System32\                                                                                          |
|77430000|ole32.dll                  |Microsoft OLE für Windows                             |10.0.19041.1202    |926560  |2021-09-16 18:29:03|C:\Windows\System32\                                                                                          |
|77520000|psapi.dll                  |Process Status Helper                                 |10.0.19041.546     |17016   |2020-10-14 07:41:42|C:\Windows\System32\                                                                                          |
|77530000|combase.dll                |Microsoft COM für Windows                             |10.0.19041.1566    |2634592 |2022-03-09 03:47:06|C:\Windows\System32\                                                                                          |
|777B0000|oleaut32.dll               |OLEAUT32.DLL                                          |10.0.19041.985     |606888  |2021-05-12 08:24:09|C:\Windows\System32\                                                                                          |
|77850000|imagehlp.dll               |Windows NT Image Helper                               |10.0.19041.1415    |95496   |2021-12-16 18:26:01|C:\Windows\System32\                                                                                          |
|77870000|win32u.dll                 |Win32u                                                |10.0.19041.1645    |94000   |2022-04-13 19:37:24|C:\Windows\System32\                                                                                          |
|77890000|gdi32.dll                  |GDI Client DLL                                        |10.0.19041.1620    |136336  |2022-04-13 19:37:22|C:\Windows\System32\                                                                                          |
|778C0000|imm32.dll                  |Multi-User Windows IMM32 API Client DLL               |10.0.19041.546     |143056  |2020-10-14 07:41:45|C:\Windows\System32\                                                                                          |
|778F0000|rpcrt4.dll                 |Remoteprozeduraufruf-Laufzeitumgebung                 |10.0.19041.1645    |776824  |2022-04-13 19:37:21|C:\Windows\System32\                                                                                          |
|779B0000|msctf.dll                  |MSCTF-Server-DLL                                      |10.0.19041.1620    |862528  |2022-04-13 19:37:21|C:\Windows\System32\                                                                                          |
|77A90000|gdi32full.dll              |GDI Client DLL                                        |10.0.19041.1645    |896104  |2022-04-13 19:37:25|C:\Windows\System32\                                                                                          |
|77BD0000|bcrypt.dll                 |Bibliothek mit kryptografischen Primitiven von Windows|10.0.19041.1023    |96032   |2021-06-11 21:39:33|C:\Windows\System32\                                                                                          |
|77BF0000|kernel32.dll               |Client-DLL für Windows NT-Basis-API                   |10.0.19041.1645    |641848  |2022-04-13 19:37:21|C:\Windows\System32\                                                                                          |
|77DF0000|ntdll.dll                  |DLL für NT-Layer                                      |10.0.19041.1566    |1697784 |2022-03-09 03:46:59|C:\Windows\System32\                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Processes Information:
----------------------

Assembler Information:
----------------------

Registers:
----------

**Comment by AnneSchueller** [comment]
Der Schuljahreswechsel wird aktuell in Schild3 eingepflegt.
