### ISSUE TITLE
Sprachenfolge Latinum

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#25]
Die Auswahlboxen für Latinum, Hebraecum und Graecum erzeugen bei mir eine Zugriffsverletzung und sind auch m.M. nach falsch dargestellt.

Version: 3.0.5.2

![SNAG_2020_12_02_13 17 05](https://user-images.githubusercontent.com/34127980/100871865-38aa5c80-34a1-11eb-97b2-a79d1f2bb164.png)

**Comment by JuergenRichter** [comment]
In Version 3.0.6 behoben.
