### ISSUE TITLE
Erneute DB Migration mit Schild 0.0.34 & SVWS 0.2.10

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#250]
Nach erneuter Migration der DB unter Schild 0.0.34 u SVWS 0.2.10 treten die folgenden Hinweise/Fehler beim Start auf:
Die folgenden Angaben fehlen: Sortierung (3x hintereinander):

![Fehler Sortierung](https://user-images.githubusercontent.com/96472913/166138003-3823c076-44c7-4771-95ea-1595c295d7c4.jpg)

Anschließend folgt der Fehler: qryEigeneSchule: Das Feld "BezAbschnitt0" wurde nicht gefunden:

![Fehler Eigene Schule](https://user-images.githubusercontent.com/96472913/166138012-432d656b-4e41-401a-a57f-941d0cd6e3ea.jpg)

Nach Bestätigung des Fehlers mit "Ja" startet Schild zwar, zeigt jedoch oben im "Kopf" "(keine Verbindung zum SVWS-Server: Status Code = 404)" an. Bei "Nein" erfolgt kein Start.

Nutbarkeit kaum möglich, da beispielsweise die Funktion der Klassenauswahl nicht gegeben ist. Hier wird lediglich eine Klasse mehrfach angezeigt.

Die Migration selbst klappte problemlos. Ein Fehler wurde nicht angezeigt.

**Comment by FPfotenhauer** [comment]
Anscheinend funktioniert die Abschnittsbetimmung in der DB nicht.
Es wäre vielleicht gut, die DB mal selbst zu untersuchen.
Auch das Migrationslog wäre insteressant.
Wir hatten so einen Fall schon einmal.

**Comment by spechtg** [comment]
Migrationslog und DB kann ich dir gerne hochladen. Gilt der Link zur membox noch?

**Comment by FPfotenhauer** [comment]
Ich glaube ja.

**Comment by spechtg** [comment]
Erledigt.

**Comment by FPfotenhauer** [comment]
@JuergenRichter 
Ich kann das reproduzieren, die Schule arbeitet mit Quartalen und ist im dritten Quartal.
Sollen wir uns das einmal gemeinsam anschauen?

**Comment by JuergenRichter** [comment]
Welche Version wird denn verwendet? 0.34 gibt es doch noch gar nicht.
Kommt die Meldung wegen der Sortierung auch in der aktuellen Version? Wir haben nämlich seit einiger Zeit beim Speichern von Datensätzen jetzt eine Prüfung drin, ob alle "Muss-Angaben" vorhanden sind (z.B. Name bei Personen). Da war aber bei machen Datenarten auch die Sortierung als "Muss-Feld" drin (obwohl der Anwender darauf bei der Eingabe gar keinen Zugriff hatte). Das ist dann auch bei der autom. Analge von Datensätzen angesprungen und führt zu den Meldungen. Falls das in der aktuellen Version immer noch vorkommt, wäre es günstig, mal die DB zu bekommen.

Die Fehlermeldung wegen des Feldes "BezAbschnitt0" deutet auf ein Problem in der Tabelle "Schuljahresabschnitte" hin, In der im Programm verwendeten Abfrage wird das nun abgefangen (kam da früher auch), ich habe aber festgestellt, dass das in der Reporting (woher der Fehler kommt) noch nicht geschehen ist. Es deutet aber auf ein DB-Problem hin, daher wäre es auch hier günstig, die DB zu bekommen.

**Comment by spechtg** [comment]
Es wird die Version 0.0.34 verwendet. Dieser Fehler tritt bei SVWS 0.2.8 und Schild 0.0.33 nicht auf. Die mir vorliegende neuste Version 0.0.35 werde ich es heute Abend einmal testen und melde mich. DB liegt Fran vor.

**Comment by spechtg** [comment]
Erneute Migration der DB mit Schild 0.0.35 und SVWS 0.2.10 brachte keine Verbesserung.

**Comment by FPfotenhauer** [comment]
Der Fehler ist gefunden. Jahr 0 und Abschnitt 0 in den SchuelerLernabschnitssdaten.
Wir brauchen aber auch mal 2Tage um das zu beheben...😀

**Comment by spechtg** [comment]
Liegt jetzt aber nicht an der mir vorliegenden DB, sondern wird durch die Migration erzeugt oder? Konnte dort gerade kein Jahr 0 und Abschnitt 0 finden (zumindest nicht bei der stichpunktartigen Kontrolle).

**Comment by FPfotenhauer** [comment]
In der Tabelle SchülerLeistungsdaten oder Kernabschnitte sind ungültige Einträge mit 0.

**Comment by spechtg** [comment]
Ok habe ich gefunden und entfernt. Nach erneuter Migration ist zwar der Abschnitt0-Fehler weg. Die Sortierung ist geblieben. Ebenso die fehlende Verbindung zum SVWS Server.

**Comment by FPfotenhauer** [comment]
Ja. Das mit der Verbindung ist auch ein ganz anderer Fehler.
