### ISSUE TITLE
Keine Verbindung zum SVWS-Server (404)

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#251]
Ich beobachte es in der letzen Zeit bei vielen Usern.
Auf meinen virtuellen Maschinen und in der Entwicklungsumgebung bekomme ich auch die Meldung.

Schild3 meldet oben im Fenster, dass keine Verbindung zum SVWS-Server besteht, dieser läuft aber und das Migrationstool stellt auch eine Verbindung her!

**Comment by JuergenRichter** [comment]
Merkwürdig, an der Stelle ist in SchILD3 nichts geändert worden. Werde das mal prüfen.

**Comment by JuergenRichter** [comment]
Ich hatte bisher immer folgende Adresse in die für das TNetHTTPClient-Objekt verwendet:
https://localhost/config/alive
Das hatte früher auch funktioniert. Ich habe das jetzt mal direkt im Browser eingegeben, da kommt dann auch der 404-Fehler.
Wenn ich stattdessen "https://localhost" verwendet, funktioniert die Verbindung. 
Frage: Ist da was am Server geändert worden? Ist die URL https://localhost richtig?

**Comment by JuergenRichter** [comment]
Frage: Muss die SVWS-Server-URL irgendwo eintragbar sein (wenn der Server z.B. nicht auf localhost läuft)?

**Comment by JuergenRichter** [comment]
Ich habe das jetzt in der aktuellen Programmversion geändert, bei mir funktioniert es jetzt wieder (mit der geänderten URL).

**Comment by FPfotenhauer** [comment]
curl -X 'GET' \
  'https://svws-nrw.de/status/alive' \
  -H 'accept: application/json'

Das ist jetzt der korrekte Aufruf.
Die Struktur der API-Calls wurde noch etwas vereinheitlicht.

https://svws-nrw.de/debug/index.html#/Server/isAlive

**Comment by FPfotenhauer** [comment]
Der Server kann auch irgendwo im Verwaltungsnetz laufen, daher muss die Adresse änderbar sein.

**Comment by JuergenRichter** [comment]
Ich werde das unter "Verwaltung" eingebbar machen.

**Comment by FPfotenhauer** [comment]
Die Frage ist auch, wo das dann gespeichert wird?
Im Migrationstool wird das ja schon abgefragt.
Ist das dann in der SDBCFG-Datei hinterlegt?

**Comment by JuergenRichter** [comment]
Stimmt, hatte ich ganz vergessen. Dann können wir die Information ja auslesen.

**Comment by JuergenRichter** [comment]
Wird jetzt aus der sdbcfg-Datei ausgelesen.
