### ISSUE TITLE
Fehlermeldung Reportgenerator

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#254]
Ich habe nach der durchgeführten Migration mal versucht einen Report zu drucken und bekomme imm diese Fehlermeldung? Hat sich eine Feldbezeichnung geändert?

![Fehler_Report](https://user-images.githubusercontent.com/75326793/166231810-a05c58b7-79bd-413b-af6c-9b7560b9dae0.JPG)

Ich hänge die Beschreibung mal an.

EurekaLog 7.10.0.0 8BD69D43571B8C48A2404FB6F3744F60 AE9A00FCA3E06D4BBF2855B5A0B147FA DA39A3EE5E6B4B0D3255BFEF95601890AFD80709 3D06BF8E3F81CB469361FDE4736702C8

Application:
-------------------------------------------------------------------
  1.1 Start Date      : Mon, 2 May 2022 11:55:53 +0200
  1.2 Name/Description: SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  1.3 Version Number  : 3.0.32.7
  1.4 Parameters      : 
  1.5 Compilation Date: Fri, 29 Apr 2022 16:33:00 +0200
  1.6 Up Time         : 1 hour(s), 4 minute(s), 32 second(s)

Exception:
-----------------------------------------------------------------------------------
  2.1 Date          : Mon, 2 May 2022 13:00:25 +0200
  2.2 Address       : 009F1CB1
  2.3 Module Name   : SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  2.4 Module Version: 3.0.32.7
  2.5 Type          : EDatabaseError
  2.6 Message       : qrySchuelerAktLA: Das Feld 'Fachklasse' wurde nicht gefunden.
  2.7 ID            : F6809B23
  2.8 Count         : 1
  2.9 Status        : New
  2.10 Note         : 
  2.11 Sent         : 0

User:
----------------------------------------------------------------
  3.1 ID        : alexanderdedy
  3.2 Name      : Alexander Dedy
  3.3 Email     : 
  3.4 Company   : 
  3.5 Privileges: SeShutdownPrivilege             - OFF
                  SeChangeNotifyPrivilege         - ON (default)
                  SeUndockPrivilege               - OFF
                  SeIncreaseWorkingSetPrivilege   - OFF
                  SeTimeZonePrivilege             - OFF

Active Controls:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  4.1 Form Class   : TppDesignerWindow
  4.2 Form Text    : Formulardesigner: C:\SVWS-Arbeitsverzeichnis\SchILD-Reports\SchILD-Reports\JDBK-Reports\1 Zeugnisse 2018\Anlage A-AV (AV & IFK)\1-AGZ-2016- AV (Anl A2.3) -JDBK 2018-01.rtm
  4.3 Control Class: TppWorkspace
  4.4 Control Text : 

Computer:
--------------------------------------------
  5.1 Name        : ALEXANDERDEE97C
  5.2 Total Memory: 4271198208 (3,98 Gb)
  5.3 Free Memory : 1869836288 (1,74 Gb)
  5.4 Total Disk  : 274322157568 (255,48 Gb)
  5.5 Free Disk   : 240851558400 (224,31 Gb)
  5.9 Display DPI : 120

Operating System:
------------------------------------------------
  6.1 Type    : Microsoft Windows 10 (64 bit)
  6.2 Build # : 2009 (10.0.19042.1586)
  6.3 Update  : October 2020 Update [20H2] #1586
  6.4 Language: German (0407)
  6.5 Charset : 0/1252

Call Stack Information:
----------------------------------------------------------------------------------------------------------------------------
|Methods |Details|Stack   |Address |Module      |Offset  |Source      |Unit    |Class      |Procedure/Method     |Line     |
----------------------------------------------------------------------------------------------------------------------------
|*Exception Thread: ID=3412; Parent=0; Priority=0                                                                          |
|Class=; Name=MAIN                                                                                                         |
|DeadLock=0; Wait Chain=                                                                                                   |
|Comment=                                                                                                                  |
|--------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|04     |00000000|009F1CB1|SchILD30.exe|005F1CB1|Data.DB.pas |Data.DB |           |DatabaseError        |3229[7]  |
|00000040|04     |0019EED8|009F1D65|SchILD30.exe|005F1D65|Data.DB.pas |Data.DB |           |DatabaseErrorFmt     |3238[1]  |
|00000040|04     |0019EEFC|00A0889C|SchILD30.exe|0060889C|Data.DB.pas |Data.DB |           |Error                |13229[1] |
|00000040|04     |0019EF20|00A088E3|SchILD30.exe|006088E3|Data.DB.pas |Data.DB |TDataSet   |FieldByName          |13234[2] |
|00000040|04     |0019EF38|02265ED2|SchILD30.exe|01E65ED2|dmReport.pas|dmRepOrt|TdmReports |qrySchuelerCalcFields|6172[78] |
|00000040|04     |0019F2B4|00A0BB99|SchILD30.exe|0060BB99|Data.DB.pas |Data.DB |TDataSet   |DoOnCalcFields       |15184[1] |
|00000040|04     |0019F2E8|00A0A0E2|SchILD30.exe|0060A0E2|Data.DB.pas |Data.DB |TDataSet   |GetCalcFields        |14132[0] |
|00000040|03     |0019F304|00AAC3AC|SchILD30.exe|006AC3AC|MemDS.pas   |MemDS   |TMemDataSet|GetRecord            |         |
|00000040|04     |0019F31C|00A09CBC|SchILD30.exe|00609CBC|Data.DB.pas |Data.DB |TDataSet   |GetNextRecord        |13935[9] |
|00000040|04     |0019F364|00A09B93|SchILD30.exe|00609B93|Data.DB.pas |Data.DB |TDataSet   |UpdateBufferCount    |13889[14]|
----------------------------------------------------------------------------------------------------------------------------

Modules Information:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|Handle  |Name                       |Description                                           |Version            |Size    |Modified           |Path                                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|00400000|SchILD30.exe               |SchILD 3.0 von ribeka GmbH                            |3.0.32.7           |54847032|2022-05-01 12:46:58|C:\Program Files (x86)\SchILD3.0\                                                                             |
|041C0000|ChilkatDelphi32.dll        |Chilkat Delphi DLL 32-bit                             |9.5.0.82           |10655936|2022-05-01 12:46:56|C:\Program Files (x86)\SchILD3.0\                                                                             |
|085D0000|cfgmgr32.dll               |Configuration Manager DLL                             |10.0.19041.1151    |236536  |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|10000000|lz32.dll                   |LZ Expand/Compress API DLL                            |5.0.1.1            |2560    |2019-12-07 11:09:26|C:\Windows\System32\                                                                                          |
|50030000|borlndmm.dll               |Embarcadero Memory Manager                            |25.0.29899.2631    |70000   |2022-05-01 12:46:58|C:\Program Files (x86)\SchILD3.0\                                                                             |
|71A60000|NetworkExplorer.dll        |Netzwerk-Explorer                                     |10.0.19041.1       |64512   |2019-12-07 11:09:27|C:\Windows\System32\                                                                                          |
|71A80000|apphelp.dll                |Clientbibliothek für Anwendungskompatibilität         |10.0.19041.1320    |639488  |2022-01-24 18:12:39|C:\Windows\System32\                                                                                          |
|71B20000|dpapi.dll                  |Data Protection API                                   |10.0.19041.546     |13312   |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|71B30000|gpapi.dll                  |Gruppenrichtlinienclient-API                          |10.0.19041.572     |111024  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|71B50000|CRYPTBASE.dll              |Base cryptographic API DLL                            |10.0.19041.546     |31528   |2020-11-19 04:49:22|C:\Windows\System32\                                                                                          |
|71B60000|rsaenh.dll                 |Microsoft Enhanced Cryptographic Provider             |10.0.19041.1052    |184888  |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|71B90000|cryptsp.dll                |Cryptographic Service Provider API                    |10.0.19041.546     |68192   |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|71BB0000|msasn1.dll                 |ASN.1 Runtime APIs                                    |10.0.19041.546     |50616   |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|71BC0000|ncryptsslp.dll             |Microsoft SChannel Provider                           |10.0.19041.546     |117216  |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|71BE0000|ncrypt.dll                 |Windows NCrypt-Router                                 |10.0.19041.546     |130128  |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|71C10000|ntasn1.dll                 |Microsoft ASN.1 API                                   |10.0.19041.546     |161608  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|71C40000|mskeyprotect.dll           |Microsoft-Schlüsselschutzanbieter                     |10.0.19041.1202    |49664   |2021-09-22 11:36:24|C:\Windows\System32\                                                                                          |
|71C50000|schannel.dll               |TLS/ SSL-Sicherheitsanbieter                          |10.0.19041.1586    |468992  |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|71CD0000|webio.dll                  |API für Webtransferprotokolle                         |10.0.19041.1320    |456704  |2022-01-24 18:12:40|C:\Windows\System32\                                                                                          |
|71D50000|rasadhlp.dll               |Remote Access AutoDial Helper                         |10.0.19041.546     |12800   |2020-11-19 04:49:37|C:\Windows\System32\                                                                                          |
|71D60000|FWPUCLNT.DLL               |FWP/IPsec Benutzermodus-API                           |10.0.19041.1526    |341504  |2022-04-05 14:29:31|C:\Windows\System32\                                                                                          |
|71DC0000|ColorAdapterClient.dll     |Microsoft Color Adapter Client                        |10.0.19041.546     |45904   |2020-11-19 04:49:26|C:\Windows\System32\                                                                                          |
|71DD0000|mscms.dll                  |Microsoft-Farbabstimmungssystem-DLL                   |10.0.19041.746     |594464  |2021-09-22 11:36:17|C:\Windows\System32\                                                                                          |
|71E70000|twinapi.appcore.dll        |twinapi.appcore                                       |10.0.19041.746     |1634208 |2021-09-22 11:36:24|C:\Windows\System32\                                                                                          |
|72000000|dxgi.dll                   |DirectX Graphics Infrastructure                       |10.0.19041.1566    |785064  |2022-04-05 14:29:29|C:\Windows\System32\                                                                                          |
|720D0000|dcomp.dll                  |Microsoft DirectComposition Library                   |10.0.19041.1566    |1448744 |2022-04-05 14:29:33|C:\Windows\System32\                                                                                          |
|72240000|d3d11.dll                  |Direct3D 11 Runtime                                   |10.0.19041.1202    |1963712 |2021-09-22 11:36:17|C:\Windows\System32\                                                                                          |
|72420000|dataexchange.dll           |Data exchange                                         |10.0.19041.1387    |183808  |2022-01-24 18:12:32|C:\Windows\System32\                                                                                          |
|72460000|WinTypes.dll               |Windows-Basistypen-DLL                                |10.0.19041.1348    |896088  |2022-01-24 18:12:40|C:\Windows\System32\                                                                                          |
|72540000|ntmarta.dll                |Windows NT MARTA-Anbieter                             |10.0.19041.546     |152904  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|72570000|CoreMessaging.dll          |Microsoft CoreMessaging Dll                           |10.0.19041.867     |630592  |2021-09-22 11:36:29|C:\Windows\System32\                                                                                          |
|72610000|CoreUIComponents.dll       |Microsoft Core UI Components Dll                      |10.0.19041.546     |2621720 |2020-11-19 04:49:26|C:\Windows\System32\                                                                                          |
|72890000|textinputframework.dll     |"TextInputFramework.DYNLINK"                          |10.0.19041.1503    |753072  |2022-04-05 14:29:29|C:\Windows\System32\                                                                                          |
|72950000|TextShaping.dll            |                                                      |                   |611960  |2022-01-24 18:12:36|C:\Windows\System32\                                                                                          |
|729F0000|hhctrl.ocx                 |Steuerelement für Microsoft® HTML-Hilfe               |10.0.19041.746     |575488  |2021-09-22 11:37:16|C:\Windows\System32\                                                                                          |
|72A90000|dnsapi.dll                 |DNS-Client-API-DLL                                    |10.0.19041.1566    |581568  |2022-04-05 14:29:33|C:\Windows\System32\                                                                                          |
|72B20000|dhcpcsvc.dll               |DHCP Clientdienst                                     |10.0.19041.546     |73728   |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|72B40000|dhcpcsvc6.DLL              |DHCPv6-Client                                         |10.0.19041.546     |61440   |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|72B60000|npmproxy.dll               |Network List Manager Proxy                            |10.0.19041.546     |26112   |2020-11-19 04:49:36|C:\Windows\System32\                                                                                          |
|72B70000|netprofm.dll               |Network List Manager                                  |10.0.19041.746     |182784  |2021-09-22 11:36:40|C:\Windows\System32\                                                                                          |
|72BB0000|shdocvw.dll                |Shelldokumentobjekt und Steuerungsbibliothek          |10.0.19041.746     |218112  |2021-09-22 11:36:41|C:\Windows\System32\                                                                                          |
|72BF0000|wkscli.dll                 |Workstation Service Client DLL                        |10.0.19041.1466    |63488   |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|72C10000|userenv.dll                |Userenv                                               |10.0.19041.572     |141008  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|72C40000|ieframe.dll                |Internet Browser                                      |11.0.19041.1566    |6488064 |2022-04-05 14:29:57|C:\Windows\System32\                                                                                          |
|73280000|url.dll                    |Internet Shortcut Shell Extension DLL                 |11.0.19041.1       |233472  |2019-12-07 11:10:00|C:\Windows\System32\                                                                                          |
|732C0000|duser.dll                  |Windows DirectUser Engine                             |10.0.19041.546     |470528  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|73340000|msi.dll                    |Windows Installer                                     |5.0.19041.1586     |2695680 |2022-04-05 14:29:57|C:\Windows\System32\                                                                                          |
|735E0000|propsys.dll                |Microsoft-Eigenschaftensystem                         |7.0.19041.1023     |791808  |2021-09-22 11:36:20|C:\Windows\System32\                                                                                          |
|736B0000|osbaseln.dll               |Service Reporting API                                 |10.0.19041.1       |21504   |2019-12-07 11:09:13|C:\Windows\System32\                                                                                          |
|736C0000|appwiz.cpl                 |Shellanwendungs-Manager                               |10.0.19041.746     |469504  |2021-09-22 11:37:15|C:\Windows\System32\                                                                                          |
|73740000|msimg32.dll                |GDIEXT Client DLL                                     |10.0.19041.1466    |7168    |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|73750000|msls31.dll                 |Microsoft Line Services library file                  |3.10.349.0         |183808  |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|73790000|riched20.dll               |Rich Text Edit Control, v3.1                          |5.31.23.1231       |487424  |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|73810000|windowscodecs.dll          |Microsoft Windows Codecs Library                      |10.0.19041.1151    |1510296 |2021-09-22 11:36:17|C:\Windows\System32\                                                                                          |
|73990000|winnsi.dll                 |Network Store Information RPC interface               |10.0.19041.546     |28360   |2020-11-19 04:49:11|C:\Windows\System32\                                                                                          |
|739A0000|mswsock.dll                |Microsoft Windows Sockets 2.0-Dienstanbieter          |10.0.19041.546     |324416  |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|73A00000|ondemandconnroutehelper.dll|On Demand Connctiond Route Helper                     |10.0.19041.546     |56832   |2020-11-19 04:49:25|C:\Windows\System32\                                                                                          |
|73A20000|profapi.dll                |User Profile Basic API                                |10.0.19041.844     |89360   |2021-09-22 11:36:06|C:\Windows\System32\                                                                                          |
|73A40000|wldp.dll                   |Windows-Sperrungsrichtlinie                           |10.0.19041.1566    |140472  |2022-04-05 14:29:33|C:\Windows\System32\                                                                                          |
|73A70000|windows.storage.dll        |Microsoft WinRT Storage-API                           |10.0.19041.1566    |6371544 |2022-04-05 14:29:31|C:\Windows\System32\                                                                                          |
|74080000|winsta.dll                 |Winstation Library                                    |10.0.19041.546     |270640  |2020-11-19 04:49:23|C:\Windows\System32\                                                                                          |
|740D0000|kernel.appcore.dll         |AppModel API Host                                     |10.0.19041.546     |52672   |2020-11-19 04:49:29|C:\Windows\System32\                                                                                          |
|740E0000|sspicli.dll                |Security Support Provider Interface                   |10.0.19041.1586    |123984  |2022-04-05 14:29:24|C:\Windows\System32\                                                                                          |
|74110000|uxtheme.dll                |Microsoft UxTheme-Bibliothek                          |10.0.19041.1566    |455168  |2022-04-05 14:29:25|C:\Windows\System32\                                                                                          |
|74190000|secur32.dll                |Security Support Provider Interface                   |10.0.19041.546     |23040   |2020-11-19 04:49:36|C:\Windows\System32\                                                                                          |
|741A0000|IPHLPAPI.DLL               |IP-Hilfs-API                                          |10.0.19041.546     |196784  |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|741E0000|wer.dll                    |Windows-Fehlerbericht-DLL                             |10.0.19041.1566    |708656  |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|742A0000|Faultrep.dll               |Windows-Benutzermodus-Absturzberichterstattungs-DLL   |10.0.19041.1566    |416816  |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|74310000|umpdc.dll                  |                                                      |                   |47472   |2020-11-19 04:49:29|C:\Windows\System32\                                                                                          |
|74320000|powrprof.dll               |Power Profile Helper DLL                              |10.0.19041.546     |268080  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|74370000|wtsapi32.dll               |Windows Remote Desktop Session Host Server SDK APIs   |10.0.19041.546     |52664   |2020-11-19 04:49:23|C:\Windows\System32\                                                                                          |
|74380000|iertutil.dll               |Laufzeit-Hilfsprogramm für Internet Explorer          |11.0.19041.1586    |2271560 |2022-04-05 14:29:36|C:\Windows\System32\                                                                                          |
|745B0000|winmmbase.dll              |API für die Basissystemverlängerung                   |10.0.19041.1       |110720  |2019-12-07 11:09:11|C:\Windows\System32\                                                                                          |
|745D0000|netutils.dll               |Net Win32 API Helpers DLL                             |10.0.19041.1466    |38232   |2022-04-05 14:29:33|C:\Windows\System32\                                                                                          |
|745E0000|srvcli.dll                 |Server Service Client DLL                             |10.0.19041.1466    |76944   |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|74600000|msacm32.dll                |Microsoft ACM-Audiofilter                             |10.0.19041.1       |93472   |2019-12-07 11:09:11|C:\Windows\System32\                                                                                          |
|74620000|tapi32.dll                 |Microsoft® Windows(TM) Telefonie-API-Client-DLL       |10.0.19041.423     |193536  |2020-11-19 04:49:53|C:\Windows\System32\                                                                                          |
|74660000|urlmon.dll                 |OLE32-Erweiterung für Win32                           |11.0.19041.1566    |1679872 |2022-04-05 14:29:36|C:\Windows\System32\                                                                                          |
|74810000|comctl32.dll               |Bibliothek für Steuerelemente                         |6.10.19041.1110    |2152264 |2021-09-12 16:38:08|C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\|
|74A20000|winspool.drv               |Windows-Spoolertreiber                                |10.0.19041.1566    |445952  |2022-04-05 14:29:24|C:\Windows\System32\                                                                                          |
|74AA0000|fontsub.dll                |Font Subsetting DLL                                   |10.0.19041.1387    |99328   |2022-01-24 18:12:40|C:\Windows\System32\                                                                                          |
|74AC0000|wininet.dll                |Interneterweiterungen für Win32                       |11.0.19041.1566    |4509696 |2022-04-05 14:29:36|C:\Windows\System32\                                                                                          |
|74F20000|oleacc.dll                 |Active Accessibility Core Component                   |7.2.19041.746      |321024  |2021-09-22 11:36:40|C:\Windows\System32\                                                                                          |
|74F80000|winmm.dll                  |MCI API-DLL                                           |10.0.19041.546     |149272  |2020-11-19 04:49:22|C:\Windows\System32\                                                                                          |
|74FB0000|mpr.dll                    |Router-DLL für Mehrfachanbieter                       |10.0.19041.1566    |96080   |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|74FD0000|usp10.dll                  |Uniscribe Unicode script processor                    |10.0.19041.546     |77824   |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|74FF0000|GdiPlus.dll                |Microsoft GDI+                                        |10.0.19041.1566    |1448448 |2022-03-02 22:38:46|C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1566_none_d951c72fe1040d0f\        |
|75160000|wsock32.dll                |Windows Socket 32-Bit DLL                             |10.0.19041.1       |16384   |2019-12-07 11:09:15|C:\Windows\System32\                                                                                          |
|75170000|msvfw32.dll                |DLL für Microsoft Video für Windows                   |10.0.19041.1       |124416  |2019-12-07 11:10:04|C:\Windows\System32\                                                                                          |
|751A0000|shfolder.dll               |Shell Folder Service                                  |10.0.19041.1       |8704    |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|751B0000|avifil32.dll               |Microsoft AVI-Dateiunterstützungs-Bibliothek          |10.0.19041.1       |95744   |2019-12-07 11:10:04|C:\Windows\System32\                                                                                          |
|751D0000|winhttp.dll                |Windows HTTP-Dienste                                  |10.0.19041.1566    |822728  |2022-04-05 14:29:34|C:\Windows\System32\                                                                                          |
|752A0000|netapi32.dll               |Net Win32 API DLL                                     |10.0.19041.1586    |76960   |2022-04-05 14:29:25|C:\Windows\System32\                                                                                          |
|752C0000|oledlg.dll                 |OLE-Benutzerschnittstellen-Unterstützung              |10.0.19041.746     |163328  |2021-09-22 11:36:29|C:\Windows\System32\                                                                                          |
|752F0000|olepro32.dll               |OLEPRO32.DLL                                          |10.0.19041.84      |88576   |2020-11-19 04:49:36|C:\Windows\System32\                                                                                          |
|75310000|version.dll                |Version Checking and File Installation Libraries      |10.0.19041.546     |27320   |2020-11-19 04:49:37|C:\Windows\System32\                                                                                          |
|75320000|dwmapi.dll                 |Microsoft Desktopfenster-Manager-API                  |10.0.19041.746     |138936  |2021-09-22 11:36:29|C:\Windows\System32\                                                                                          |
|75350000|dbgcore.dll                |Windows Core Debugging Helpers                        |10.0.19041.546     |138752  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|75380000|dbghelp.dll                |Windows Image Helper                                  |10.0.19041.1052    |1494016 |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|75580000|ws2_32.dll                 |Windows Socket 2.0-32-Bit-DLL                         |10.0.19041.546     |397728  |2020-11-19 04:49:22|C:\Windows\System32\                                                                                          |
|755F0000|ucrtbase.dll               |Microsoft® C Runtime Library                          |10.0.19041.789     |1181208 |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|75710000|clbcatq.dll                |COM+ Configuration Catalog                            |2001.12.10941.16384|504552  |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|75960000|win32u.dll                 |Win32u                                                |10.0.19041.1586    |94024   |2022-04-05 14:29:32|C:\Windows\System32\                                                                                          |
|75980000|sechost.dll                |Host for SCM/SDDL/LSA Lookup APIs                     |10.0.19041.1586    |477824  |2022-04-05 14:29:24|C:\Windows\System32\                                                                                          |
|75A00000|nsi.dll                    |NSI User-mode interface DLL                           |10.0.19041.610     |20144   |2020-11-19 04:49:11|C:\Windows\System32\                                                                                          |
|75A10000|psapi.dll                  |Process Status Helper                                 |10.0.19041.546     |17016   |2020-11-19 04:49:32|C:\Windows\System32\                                                                                          |
|75A20000|SHCore.dll                 |SHCORE                                                |10.0.19041.1566    |545968  |2022-04-05 14:29:33|C:\Windows\System32\                                                                                          |
|75AB0000|ole32.dll                  |Microsoft OLE für Windows                             |10.0.19041.1202    |926560  |2021-09-22 11:36:29|C:\Windows\System32\                                                                                          |
|75BA0000|crypt32.dll                |Krypto-API32                                          |10.0.19041.1320    |1013344 |2022-01-24 18:12:40|C:\Windows\System32\                                                                                          |
|75CA0000|imm32.dll                  |Multi-User Windows IMM32 API Client DLL               |10.0.19041.546     |143056  |2020-11-19 04:49:34|C:\Windows\System32\                                                                                          |
|75CD0000|kernel32.dll               |Client-DLL für Windows NT-Basis-API                   |10.0.19041.1566    |641848  |2022-04-05 14:29:25|C:\Windows\System32\                                                                                          |
|75DC0000|msctf.dll                  |MSCTF-Server-DLL                                      |10.0.19041.1566    |862000  |2022-04-05 14:29:25|C:\Windows\System32\                                                                                          |
|75EA0000|msvcrt.dll                 |Windows NT CRT DLL                                    |7.0.19041.546      |775256  |2020-11-19 04:49:22|C:\Windows\System32\                                                                                          |
|75F60000|bcryptPrimitives.dll       |Windows Cryptographic Primitives Library              |10.0.19041.1415    |383264  |2022-01-24 18:12:19|C:\Windows\System32\                                                                                          |
|75FC0000|rpcrt4.dll                 |Remoteprozeduraufruf-Laufzeitumgebung                 |10.0.19041.1466    |776328  |2022-04-05 14:29:24|C:\Windows\System32\                                                                                          |
|760C0000|imagehlp.dll               |Windows NT Image Helper                               |10.0.19041.1415    |95496   |2022-01-24 18:12:19|C:\Windows\System32\                                                                                          |
|76140000|advapi32.dll               |Erweiterte Windows 32 Base-API                        |10.0.19041.1466    |495312  |2022-04-05 14:29:24|C:\Windows\System32\                                                                                          |
|761C0000|combase.dll                |Microsoft COM für Windows                             |10.0.19041.1566    |2634592 |2022-04-05 14:29:33|C:\Windows\System32\                                                                                          |
|76440000|comdlg32.dll               |DLL für gemeinsame Dialoge                            |10.0.19041.1566    |689152  |2022-04-05 14:29:38|C:\Windows\System32\                                                                                          |
|764F0000|gdi32.dll                  |GDI Client DLL                                        |10.0.19041.1202    |140976  |2021-09-22 11:36:17|C:\Windows\System32\                                                                                          |
|76530000|gdi32full.dll              |GDI Client DLL                                        |10.0.19041.1566    |896120  |2022-04-05 14:29:36|C:\Windows\System32\                                                                                          |
|76610000|bcrypt.dll                 |Bibliothek mit kryptografischen Primitiven von Windows|10.0.19041.1023    |96032   |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|76630000|shell32.dll                |Allgemeine Windows-Shell-DLL                          |10.0.19041.1566    |6012560 |2022-04-05 14:29:38|C:\Windows\System32\                                                                                          |
|76C80000|shlwapi.dll                |Shell Light-weight-Hilfsprogrammbibliothek            |10.0.19041.1023    |275808  |2021-09-22 11:36:41|C:\Windows\System32\                                                                                          |
|76CD0000|user32.dll                 |Client-DLL für Windows USER-API (mehrere Benutzer)    |10.0.19041.1586    |1680720 |2022-04-05 14:29:32|C:\Windows\System32\                                                                                          |
|76E70000|oleaut32.dll               |OLEAUT32.DLL                                          |10.0.19041.985     |606888  |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|77350000|msvcp_win.dll              |Microsoft® C Runtime Library                          |10.0.19041.789     |495840  |2021-09-22 11:36:30|C:\Windows\System32\                                                                                          |
|773D0000|KERNELBASE.dll             |Client-DLL für Windows NT-Basis-API                   |10.0.19041.1586    |2181160 |2022-04-05 14:29:12|C:\Windows\System32\                                                                                          |
|77650000|ntdll.dll                  |DLL für NT-Layer                                      |10.0.19041.1566    |1697784 |2022-04-05 14:29:24|C:\Windows\System32\                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Processes Information:
----------------------

Assembler Information:
----------------------

Registers:
----------

**Comment by AnneSchueller** [comment]
Hallo,

da sich die Tabellenstruktur an einigen Stellen geändert hat, funktionieren nicht mehr alle Reports. Jens Raffenberg hat bereits einige Reports angepasst (Siehe Basisreport-Sammlung: https://www.svws.nrw.de/download/schild-reports/basis-reportsammlung). Diese sollten funktionieren. 
Viele Grüße

**Comment by AlexanderDedy** [comment]
Hatte ich auch bereits versucht. Leider das gleiche Ergebnis. Selbst eine einfache Schülerliste macht immer den Fehler "Fachklasse" - deswegen meine Vermutung....


![Fehler_Report3](https://user-images.githubusercontent.com/75326793/166237190-6f80ad64-a80c-499d-afdf-13dcfd28d0d1.JPG)
![Fehler_Report2](https://user-images.githubusercontent.com/75326793/166237196-f9c22292-e1c0-4e67-a680-86b893fb404a.JPG)

**Comment by FPfotenhauer** [comment]
Hallo.

Wenn es geht, bitte die EurekaLogs als txt anfügen...

**Comment by JuergenRichter** [comment]
Ist behoben
