### ISSUE TITLE
Schülername über Reiter?!

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#256]
Mir ist gerade eine Sache aufgefallen, die vermutlich so gewollt ist, aber bei meinen KuK zu Problemen führt.
=> in SchiLD 2 stehen über den einzelnen Reitern immer nochmal der Name und KL der SuS. In SchiLD 3 nur bei Individual-Daten I & II. Leider kommt es öfters vor, dass durch klicken der Schüler unbewusst gewechselt wird - hier sieht man das zwar auf der linken Seite, aber im Alltag, hat mir und meinen KuK der Schülername über dem Reiter schon so manchen Fehler erspart. 

![Übersicht 2 0t](https://user-images.githubusercontent.com/75326793/166240683-36ab4524-af94-4001-ad62-7e16adadc316.PNG)

Ohne Schülername in 3.0

![Übersicht 3 0](https://user-images.githubusercontent.com/75326793/166240718-dbc6d795-e037-4c3f-8501-76ae4a40d09c.JPG)

**Comment by HHayen** [comment]
Möchte ich unterstützen.

**Comment by JuergenRichter** [comment]
Das ist umgesetzt, zumindest was den Namen betrifft. Wird mehr gewünscht?
![image](https://user-images.githubusercontent.com/61280188/173830006-280c2bd2-7510-46b5-8683-5549a05fcd9a.png)

**Comment by AnneSchueller** [comment]
Schön wäre es, wenn der Klassenlehrer hier direkt ersichtlich ist.

**Comment by JuergenRichter** [comment]
Kein Problem, setze ich um.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
![image](https://user-images.githubusercontent.com/61280188/174570321-1f1f1992-53f1-4f8d-b75b-79396314b84f.png)
