### ISSUE TITLE
Sprachenfolge aus Leistungsdaten ermitteln Schild 0.0.35

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#257]
Das Ermitteln der Sprachenfolge aus den Leistungsdaten bricht mit folgender Fehlermeldung ab:

![Fehler Sprachniveau](https://user-images.githubusercontent.com/96472913/166317185-697722dd-1f31-4eab-9cd8-b8adf8b908e1.jpg)

Details zum Fehler:

![Fehler Sprachniveau details](https://user-images.githubusercontent.com/96472913/166317242-85d3814d-08c6-4031-9a67-a9f001bb37c2.jpg)

**Comment by FrodBRA** [comment]
3.0.71.9

Ist das Issue noch aktuell? Ich konnte es in dieser und vorherigen Versionen nicht reproduzieren.

**Comment by AnneSchueller** [comment]
Mit meiner DB läuft das ebenfalls durch.
