### ISSUE TITLE
Kennwort für Migration wird bei Installation nicht angezeigt

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#26]
Wenn ich bei der Installation des SVWS-Servers unter Migration einen anderen Ordner für die Datenbank auswähle, erscheint anschließend nicht mehr das Eingabefeld für das Kennwort.
Danach habe ich den Vorgang abgebrochen und die Installation erneut gestartet. Aber auch dann wird das Eingabefeld nicht angezeigt, obwohl ich in diesem Fall den Ordner nicht geändert habe.

**Comment by FPfotenhauer** [comment]
Was bedeutet "unter Migration"?
Welches Format soll migriert werden? Access?
Wenn das Access-Kennwort gemeint ist, wir haben einen Weg gefunden, das in den Installer einzubauen.

**Comment by hagege** [comment]
Ich meinte den Dialog "Migration", Seite 4 in der Anleitung (FB_Infos_Schild3-Installer.pdf2). Das ist eine Access-Datenbank. Allerdings kam zumindest bei mir bei der Installation beim ersten Aufruf des Dialogs das Eingabefeld für das Kennwort.
Die Migration wurde dann mit der Meldung, dass sie erfolgreich abgeschlossen wurde, beendet.
Allerdings konnte ich SchILD 3.0 dann nicht starten, weil die folgende Fehlermeldung erscheint: Das Verzeichnis .../SDBCFG existiert nicht oder enthält keine Datenbank-Konfigurationsdateien. Soll ich dazu einen neuen Issue erstellen?

**Comment by FPfotenhauer** [comment]
Welche Installer Version?

Wenn man die Mgration über den SVWS-Installer macht, dann muss man die SDBCFG selber erstellen, weil ja noch keine Schld-Installation vorliegt.

In der neuesten Version ist wie gesagt das Access Kennwort nicht mehr nötig.

**Comment by hagege** [comment]
Das ist die Version 0.0.33 und da wurde aber beim ersten Mal das Eingabefeld für das Kennwort angezeigt.
Bezogen auf die SDBCFG-Datei teste ich das weiter.

**Comment by hagege** [comment]
Irritierend ist allerdings, dass in der Anleitung auf Seite 7 unten steht: "Zum Schluss wird eine SDBCFG-Datei in der Schild3-Installation angelegt. Schild3 kann nun gestartet werden."

**Comment by FPfotenhauer** [comment]
Das steht aber im PDF vom Installer von Schild3, da stimmt das auch.
Wir sprechen ja jetzt hier über den SVWS-Server-Installer.
