### ISSUE TITLE
Noten in den vorherigen Halbjahren fehlen teilweise

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#260]
Schild 3.0.32.7, SVWS-Server: 0.2.10
Migration von MSSQL --> MariaDB
Mir ist gerade aufgefallen, dass Noten in den vorherigen Halbjahren in Schild3 teilweise Noten fehlen. Das geht ziemlich durcheinander, ein Muster ist nicht erkennbar. Da ich nicht sicher bin, ob das nur bei meiner Migration (MSSQL --> MariaDB) passiert ist oder ob jeder den Fehler reproduzieren kann, habe ich bei meinem Eintrag der erfolgreichen Migration noch nichts geändert. Teilleistungen sind da. Hier das Beweisfoto:
![schildfehler5](https://user-images.githubusercontent.com/78501680/167265572-34b798e9-ef70-456d-97ba-7fc2f7a7a38b.jpg)

**Comment by AnneSchueller** [comment]
Es scheint, dass Noten mit Tendenzen nicht richtig übernommen werden. Das gleiche kann ich auch mit der Note "NT" reproduzieren.

**Comment by FPfotenhauer** [comment]
@ThomasBachran:
Ich teste das mal, ob das ein Migrationsproblem ist.

**Comment by FPfotenhauer** [comment]
Das ist so gesehen kein Fehler.
Die Einstellungen von Schild2 werden nicht mit migriert.
Also einfach die Tendenznoten wieder einschalten!

@JuergenRichter: Könnte man das so regeln, dass die NOten angezeigt werden, aber nicht auswählbar sind?

**Comment by JuergenRichter** [comment]
Geht vermutlich. Man braucht dann zwei "Datenquellen", eine komplette (für die Anzeige) und eine für die Auswahl (evtl. ohne Tendenzen). Wird bei den Lehrkräften auch so verwendet (damit Lehrkräfte, die nicht mehr "sichtbar" sind, angezeigt werden, aber nicht auswählbar sind).

**Comment by FPfotenhauer** [comment]
Können wir mit niedriger Priorität ja mal im Auge behalten.
