### ISSUE TITLE
Fehlermeldung Reportgenerator (-> immer noch)

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#261]
Ich habe gerade noch einmal die Version 0.36 über 0.35 installiert und leider kommt im Reportgenerator immer noch der Fehler "Feld Fachklasse nicht gefunden. 
[Fachklassen_Fehler.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8649640/Fachklassen_Fehler.txt)
"

**Comment by FPfotenhauer** [comment]
Die Version in der das behoben wurde kommt noch.
Außerdem wäre es gut, nicht noch ein Issue zu öffnen, sondern das alte Issue dann wieder auf zu machen.

**Comment by AlexanderDedy** [comment]
Hi Frank,

Sorry, ich hatte versucht wieder zu öffnen, hatte aber irgendwie nicht
funktioniert. Ich bin nach dem close und einer neuen Version in der Cloud
davon ausgegangen, dass das schon integriert ist.

Grüße Alex

Frank Pfotenhauer ***@***.***> schrieb am Mo. 9. Mai 2022 um
11:06:
