### ISSUE TITLE
Darstellung/Fehler Katalog Klassengruppen/Abteilungen

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#263]
Der Katalog wurde nicht richtig migriert oder wird falsch dargestellt. Vergleich: SchiLDzentral vs. Schild 3.

![Bildschirmfoto 2022-05-09 um 09 54 12](https://user-images.githubusercontent.com/75326793/167366000-ef83a7a0-004c-4c08-98a3-cf1ccce381c5.png)

![Fehler_Gruppen_Abteilungen](https://user-images.githubusercontent.com/75326793/167365923-9d08963e-9bfb-490e-8337-83c499d9bc6b.JPG)
0

**Comment by AnneSchueller** [comment]
Bei Schild2 sind bei den Abteilungsleitern auch die als "nicht sichtbare" eingestellten  Klassen sichtbar.
Bei Schild3 sieht man nur die sichtbaren Klassen (m.E. sollten hier auch die Nicht sichtbaren Klassen auftauchen):

@JuergenRichter: Das ist wahrscheinlich "einfach" zu beheben oder?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/74a65546-c401-4d15-9b63-c349173967f3)

**Comment by FrodBRA** [comment]
Das ist in 3.0.85.10 noch immer so.

Blendet man eine Klasse aus, die in den Abteilungen enthalten ist, existiert der Eintrag noch, nur der Text wird ausgeblendet (siehe Annes rechten Screenshot).

**Comment by AnneSchueller** [comment]
Immer noch in 3.0.86.10

**Comment by JuergenRichter** [comment]
Behoben.
Dazu aber eine Frage: Wird die Eigenschaft "Sichtbar" bei den Klassen in SchILD3 überhaupt noch benötigt? In SchILD2 gar es ja nur eine "globale" Klassentabelle, da war "Sichtbar" die einzige Möglichkeit, eine Klasse auszublenden, wenn sie aktuell nicht benötigt wurde (wohl aber in vergangenen Schuljahren.). Nun werden die Klassen aber abschnittsweise verwaltet, im Prinzip wie die Kurse. Dort gibt es aber auch keine "Sichtbarkeit", wenn ein Kurs nicht benötigt wird, löscht man ihn einfach. Könnte man bei den Klassen genauso machen.

**Comment by FPfotenhauer** [comment]
Wir haben letzte Woche auch über die Sichtbarkeit bei Klassen gesprochen.
Es wird im SVWS-Server eine Funktion geben, mit der die Schulen leere Klassen löschen können.
Das Merkmal "sichtbar" werden wir dann einfach ignorieren.
