### ISSUE TITLE
Fehlermeldung: Gruppenprozess Noteneingabe

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#264]
Ich habe beim Versuch der Noteneingabe über Gruppenprozess folgende Fehlermeldung erhalten:

[Gruppenprozess_Noteneingabe.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8649829/Gruppenprozess_Noteneingabe.txt)

![Fehler_Gruppenprozess_Noteneingabe](https://user-images.githubusercontent.com/75326793/167367752-dea4d96a-f5cd-4435-b6d1-b794dabd30a0.JPG)

**Comment by JuergenRichter** [comment]
Die Gruppenprozesse nach "Teilleistungen" sind noch nicht angepasst
