### ISSUE TITLE
Benutzerverwaltung => Benutzer löschen fehlt?

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#265]
In der Benutzerverwaltung habe ich gerade versucht einen pensionierten Kollegen zu löschen. Leider gibt es kein - wie in SchiLD 2 und auch bei Bearbeiten oder rechte Maustaste ist nur neuen Benutzer anlegen möglich. Löschen fehlt?!

**Comment by JuergenRichter** [comment]
Stimmt, wird nachgeholt

**Comment by JuergenRichter** [comment]
Frage an die Datenbankler: Gibt es Automatismen für das Löschen der "abhängigen Tabellen"? Es ist ja so, dass derzeit ein Benutzer entweder
1. eine Lehrkraft sein kann 
2. oder eine "Allgemeinperson" ( z.B. Sekretariat)

Im Fall 1. soll ja wohl nur der Eintrag aus der Benutzertabelle (und den Credentials) entfernt werden, die "Person an sich" (also die Lehrkraft selbst) aber wohl nicht. Im Fall 2. gehe ich davon aus, dass die Person "komplett" gelöscht werden soll. 
Wird das über die Datenbank geregelt oder soll das übers Programm  erfolgen?

**Comment by FPfotenhauer** [comment]
Wenn ich das richtig im Kopf habe, werden die Felder, die mit einer LehrerID verknüpft sind kaskadierend gelöscht.
@ThomasBachran Oder irre ich mich?

**Comment by JuergenRichter** [comment]
Das bedeutet doch aber, dass beim Löschen eines Lehrers auch dessen Benutzerdaten entfernt werden. Aber wie ist es umgekehrt?

**Comment by AlexanderDedy** [comment]
In der Regel löschen wir keine Lehrer sondern setzen sie nur auf unsichtbar. Allerdings sollte dann der Zugang zum System von aussen eingeschränkt werden.

**Comment by FPfotenhauer** [comment]
Umgekehr passiert m.W. nichts automatisch.

**Comment by JuergenRichter** [comment]
OK, dann müssen wir das im Programm abbilden.

**Comment by FPfotenhauer** [comment]
Aus unserer Sicht kann das Issue dann geschlossen werden.

**Comment by JuergenRichter** [comment]
Ist jetzt umgesetzt
