### ISSUE TITLE
Fehler bei Gruppenprozess Fächer

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#266]
Scheinbar funktioniert der Filter beim GP Fächer nicht. Ich habe eine Klasse ausgewählt, aber es werden in der Auswahl immer alle Klassen mit jedem Unterricht angezeigt.

![Fehler_Gruppenprozess_Fächer](https://user-images.githubusercontent.com/75326793/167374482-b71a654d-a985-4853-b72f-9a531cf904b7.JPG)
.

**Comment by JuergenRichter** [comment]
Ja, wird gemacht

**Comment by JuergenRichter** [comment]
Ist umgesetzt

**Comment by JuergenRichter** [comment]
Hierzu folgende Information:
Im Progrmm wird jetzt bei den Gruppenprozessen folgende "Philosophie" angewandt:
-Wenn in einem Gruppenprozess keine individuelle Anzeige der jeweligen "Zielgruppe" (von einzelnen SuS, aber auch einzelnen Klassen, Kursen usw.) vorhanden ist, so werden die entsprechenden Eingabefenster in die Programmoberfläche integrieren. Dann ist es auch möglich, einzelne SuS in der Hauptansicht anzuklicken, auch wenn die Eingabeoberfläche des Gruppenprozesses schon sichtbar ist.
Beispiel: Details zu Fächern bei Schülern ändern, hier wird die Zielgruppe (die ausgewählten SuS) nicht nochmal separat angezeigt

-Gruppenprozesse, die eine individuelle Bearbeitung für die jeweilige Zielgruppe ermögliche, werden in separaten (modalen) Fenstern angezeigt. 
Beispiel: Kurse zuweisen (weil individuelle Bearbeitung der Zielgruppe=SuS), aber auch der hier angesprochene GP "Klassenunterichte bearbeiten", hier ist die Zielgruppe die Klassen der ausgewählten SuS.

**Comment by AnneSchueller** [comment]
Bei den Gruppenprozessen, die eine individuelle Bearbeitung für die jeweilige Zielgruppe ermöglichen, ist ein Wechsel der Zielgruppe nicht wirksam. 
Filtert  man erst Klasse 7a und ändert das dann auf Klasse 8a, so wird der Gruppenprozess für die 7a durchgeführt, obwohl im Schülercontainer bereits die Schüler der Klasse 8a aufgelistet sind.
![GP_KlassenunterrichtBearbeiten](https://user-images.githubusercontent.com/79116896/168984420-d86de183-5d79-43fc-b4f6-8d8e240e3429.png)
![GP_KurseZuweisen](https://user-images.githubusercontent.com/79116896/168984423-9ebf0b42-eae5-4530-868f-f28d5e032fee.png)

**Comment by JuergenRichter** [comment]
Ist behoben
