### ISSUE TITLE
Fächer: Gliederungsbezogene Einstellungen

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#267]
Bei den Fächern gibt es eine Fehlermeldung und die Gliederungsbezogenen Einstellungen sind nicht übernommen worden

[Fächer.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8650361/Facher.txt)

![Bildschirmfoto 2022-05-09 um 11 22 24](https://user-images.githubusercontent.com/75326793/167381504-57892f6b-1ce0-4a47-9d30-0b7d131c833b.png)

![Fächerkatalog](https://user-images.githubusercontent.com/75326793/167381341-89322f71-8423-4fb8-9b04-2aec05b33ed3.JPG)

![Fächerkatalog2](https://user-images.githubusercontent.com/75326793/167381350-56e144c5-af37-45ea-b20b-f858fac110ac.JPG)
.

**Comment by JuergenRichter** [comment]
Behoben
