### ISSUE TITLE
einfacher Klassenwechsel in Individualdaten I ??

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#268]
Am Anfang des SJ kommt es sehr häufig vor, das SuS die Klasse wechseln. Bisher konnte man bei Individualdaten I einfach die neue Klasse auswählen/eingeben - die Angaben aus der Klassentabelle ggf. übernehmen und fertig.

=> Hier ist die Klasse nur zur Ansicht und ich muss (für einzelne SuS sehr umständlich) über den GP Individualdaten gehen (oder gibt es eine andere Möglichkeit)?

==> Bitte den "alten Weg" wieder möglich machen - über den GP dauert es erheblich länger und birgt die Gefahr, zu viele SuS umzusetzen wenn die Auswahl nicht korrekt war.

==> Die weiteren Angaben überdecken die Fachklasse. Hab verschiedene ZoomStufen getestet.

==> Frage: wäre es möglich beim umsetzten eines S in eine andere Klasse automatisch den Klassenunterricht zu übernehmen? ggf. auch mit Abfrage wie bei der Klassendefinition. Das passiert bei uns laufend und ist beim Import von Nachzüglern auch immer sehr lästig... Klassenunterricht kopieren und beim S. wieder einfügen....

![Klassenwechsel](https://user-images.githubusercontent.com/75326793/167427760-27f3788a-44f9-4dba-a3cd-24138c1273c5.JPG)

**Comment by AnneSchueller** [comment]
Schüler kann man auch unter aktuelles Halbjahr -> Allgemeine Angaben in eine andere Klasse schieben. Klassenlehrer werden übernommen.
Das "Problem", dass der Klassenunterricht noch angepasst werden muss bleibt.

**Comment by AlexanderDedy** [comment]
Habe ich mal getestet. Das umsetzen so ist aus meiner Sicht recht umständlich.

1. man kann die neue Klasse nicht eigenständig eingeben - nur drop down ist möglich
2. es werden ALLE Klassen angeboten (auch ausgeblendete) das sind am BK hunderte aufgrund der weit verbreiteten Klassenbezeichnung mit Einschulungsjahr 
3. Um einen Schüler zu versetzen benötigt man jetzt deutlich länger Zeit - ich würde die "alte" Methode über Individualdaten I bevorzugen

![Bildschirmfoto 2022-05-11 um 09 26 12](https://user-images.githubusercontent.com/75326793/167793533-2c566c5d-f5ff-42ce-9873-c1f6758ccbd3.png)

=> Beim Klassenwechsel hat SchiLD nicht sofort reagiert - ich hatte die S umgesetzt und mit dem Haken bestätigt, in der Liste war sie aber noch in der alten Klasse. Erst nach dem "aktualisieren" war sie in der richtigen Klasse. Das ist in SchiLD 2 anders und führt (wenn so gewollt) sicherlich zu Fragen..

![Klassenwechsel2](https://user-images.githubusercontent.com/75326793/167794191-a95cace6-6d8a-4958-a033-6ce258de3aa8.png)

**Comment by FrodBRA** [comment]
Die alte Methode geht nicht mehr, da die Klasse nicht mehr im Schüler gelesen wird, sondern nur passiv aus dem aktuellen Lernabschnitt ausgelesen wird.

Wenn die Wahl im aktuellen Halbjahr für BKs/große Systeme zu aufwendig ist, sollte eine Erleichterung geschaffen werden, die Klasse zu wählen. Die alte - und von Windows gewohnte - Option, im Feld händisch etwas einzugeben und das Dropdown-Menü springt dann auf den ersten für die getippten Zeichen passenden Eintrag wäre vermutlich eine ausreichende Hilfe.

Diese Hilfe sollte nach m.E. ohnehin ausnahmslos für alle Dropdown-Menüs gelten. Lässt sich diese Hilfe vielleicht generell implementieren?

**Comment by AnneSchueller** [comment]
Änderungen bezüglich der Klassen werden mittlerweile unmittelbar übernommen; nur sichtbare Klassen können ausgewählt werden. Eingabe über Tastatur ist möglich.
