### ISSUE TITLE
Keine Eingabe von Ziffern bei "Fenster skalieren auf %)" möglich

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#27]
Eine Eingabe von %-Zahlen im Feld Verwaltung-> Einstellungen -> "Fenster skalieren auf %)" ist nicht sinnvoll über den Ziffernblock möglich.

**Comment by FPfotenhauer** [comment]
Skalierung wurde entfernt.
