### ISSUE TITLE
Einstellungen/ Tabellenkalkulationsprogramm öffnen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#271]
Ich habe das Häkchen bei "Nach Excel-Export Tabellenkalkulationsprogramm starten" in den individuellen Einstellungen gesetzt. Es öffnet sich aber Excel nach dem Export nicht. Bei Schild 2 funktioniert das auch nicht. Muss noch zusätzlich irgendwo eingestellt werden, welches Tabellenkalkulationsprogramm gestartet werden soll? Das Format für die Excel-Dateien habe ich richtig eingestellt. In der Doku im Netz steht nur: Bewirkt einen Autostart von z.B. Excel, wenn exportiert wurde. Bin irritiert, weil mir die Funktion noch nie aufgefallen ist.

**Comment by FrodBRA** [comment]
3.0.71.9: Das kann ich reproduzieren. Der Haken in den IE ist gesetzt, Export läuft, Excel wird nicht gestartet.

**Comment by AnneSchueller** [comment]
Vorschlag: 
Wenn das auch in SChild2 noch nie funktioniert hat...

Sollen wir die Option nicht einfach rausschmeißen?

**Comment by FrodBRA** [comment]
Ich bin dafür. Diese Option ist ein kleines Komfortfeature, ob es aber da ist oder nicht erscheint mir für die tägliche Arbeit wenig relevant. Wenn das Feature Probleme macht, steht der Zeitaufwand, das zu beheben und testen für mich in einer ungenügenden Relation zum späteren Wert.

**Comment by AnneSchueller** [comment]
Dann schließe ich das mal.

**Comment by FrodBRA** [comment]
Ist der Haken denn raus aus der aktuellen Version?

**Comment by AnneSchueller** [comment]
Danke für den Hinweis. Da war ich zu voreilig mit dem Schließen des Issues.

@JuergenRichter : Könnten Sie das anpassen, dass die folgende Option entfernt wird:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/28d18ef8-6e53-4246-b225-6fcf08beabe5)

**Comment by JuergenRichter** [comment]
Ist entfernt
