### ISSUE TITLE
Auswahl -> Schülergruppen bearbeiten

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#273]
Das Klicken des Button "Schülergruppen bearbeiten" führt zur Fehlermeldung (siehe Bild). Anschließend werden die Gruppen zwar angezeigt, lassen sich durch einen Absturz von Schild nicht bearbeiten.

![Fehler Schülergruppe bearbeiten](https://user-images.githubusercontent.com/96472913/167787230-5471459d-249f-4154-8e29-9b9d2475a4c9.jpg)

**Comment by AnneSchueller** [comment]
Dasselbe gilt auch für Abschnitt (Aktiv,Extern), Abschnitt (Abgang,Abschluss) und meine vordefinierten Filter

**Comment by JuergenRichter** [comment]
"Dasselbe gilt auch für Abschnitt (Aktiv,Extern), Abschnitt (Abgang,Abschluss) und meine vordefinierten Filter"

Was ist damit gemeint?
