### ISSUE TITLE
Gruppenprozess -> Noten, Mahnungen und Fehlstd. eingeben

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#274]
Trotz der Vorauswahl einer Klasse führt der Versuch über den Button "Noten, Mahnungen und Fehlstd. eingeben" zu langer Wartezeit die in einem Absturz mündet.

**Comment by AnneSchueller** [comment]
Da das Issue zur Noteneingabe bereits vorhanden ist, schließe ich dieses um Doppelungen zu vermeiden.
