### ISSUE TITLE
Migration über MigrateDB erfolgreich aber ...

### ISSUE THREAD

**Issue by ADV-Burmeister** [SVWS-NRW/Schild3-BetaTest#276]
Hallo zusammen!

Es war etwas umständlich die Datenbank aus Schildzentral in den Testbereich zu bekommen.
Habe die 44 MB große Datenbank exportiert (MDB-Access) und mit 7z gezippt und an mich verschickt. 
(Es gibt ja für Dateien keine andere Schnittstelle zu CDESK der Stadt Köln). Dann wieder entpackt.

Habe danach die Schuldatenbank als zusätzliche Datenbank über den Weg mit MigrateDB (Schild3.0) migriert.

Migration: erfolgreich, jedoch kam zu Beginn des Prozesses folgende Meldung:

"...Verbindung zum SVWS-Server konnte nicht hergestellt werden: 
Fehlermeldung: Winsock - Connection refused (Error #10061) to [::1]:443

SVWS-Server erfolgreich neu gestartet..."

Dann lief alles zunächst wie erwartet. Aber bei der Testung von Schild gab es einige Probleme.
(s. unten "Test Schuldatenbank.docx"

Schild-Zentral: v2.0.27.8
Schild3.0: v0.0.36
SVWS: v0.2.10
Schulnummer: 188165
Datenbank: älter als 10 jahre
Betriebssystem: Windows10
PC: alte Acer-Maschine für Testzwecke
Schulform: GE

[Test Schuldatenbank.docx](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8668906/Test.Schuldatenbank.docx)

Schöne Grüße

Holger Burmeister

**Comment by FPfotenhauer** [comment]
Hier wäre zuerst mal das Log der Migration interessant.
Nicht, dass es dort einen Fehler gab, der jetzt einfach dazu führt, dass die DB "korrupt" ist.

Läuft denn der SVWS-Client unter Localhost im Browser?

**Comment by ADV-Burmeister** [comment]
Ich schaue es mir in den nächsten Tagen mal  im Browser an.

Aber hier schon mal das Protokoll der Migration:
[Protokoll Datenmigration.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8669706/Protokoll.Datenmigration.txt)

**Comment by ADV-Burmeister** [comment]
Habe alles noch einmal frisch neuinstalliert, direkt mit meiner Schuldatenbank:

Schild-Zentral: v2.0.27.8


Schild3.0: v0.0.37
SVWS: v0.2.10
Schulnummer: 188165
Datenbank: älter als 10 jahre
Schulform: GE


Die Schritte der Installation schienen gut durchzulaufen.

Aber wieder dieselbe Programmreaktion unter Kurse (so. Test Schuldatenbank.docx).

Im Browser unter localhost erscheint unter Kurse gar nichts, nur die Fehlermeldung "kein Lehrer festgelegt" und beim Drücken auf den "Daten"-Button passiert auch nichts.

![grafik](https://user-images.githubusercontent.com/75778386/169059523-de4b50df-ee9a-47b8-bbe7-b5e658e64cb2.png)


[Fehlerdetails bei Aufruf von Katalog Kurse.docx](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8716837/Fehlerdetails.bei.Aufruf.von.Katalog.Kurse.docx)

[Protokoll Migration 18.5..txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8716839/Protokoll.Migration.18.5.txt)

**Comment by FPfotenhauer** [comment]
Nun ja, der Webclient ist noch sowas von Alpha, da benötigen wir momentan keine Fehlermeldungen.

**Comment by FPfotenhauer** [comment]
Die KAOA-Meldungen sind nicht so schlimm.
Auf den Fehler müssten wir ggf. mal mit Herrn Richter zusammen schauen.
Vielleicht kann ich die DB mal bekommen?
Dann aber weiteres per Mail ....
SchildZentral-DBs werden ja auch bei uns nicht migriert, die Probleme sind aber trotzdem sehr interessant für uns!

**Comment by JuergenRichter** [comment]
Konnte denn überhaupt eine Verbindung zum SVWS-Server hergestellt werden? Ich lese im Eurekalo.txt:

Aktuelle Datenbank: MariaDB-problem, Schuljahr 2021/2022, 3. Qu, Benutzer: Admin (keine Verbindung zum SVWS-Server: Fehler = Fehler beim Senden der Daten: (12029) Die Serververbindung konnte nicht hergestellt werden)

**Comment by FPfotenhauer** [comment]
Ich hatte den Server nicht laufen. Das sollte aber ja im Moment noch keine Rolle spielen oder?
Migriert hatte ich aus der Entwicklungsumgebung.

**Comment by JuergenRichter** [comment]
Ich habe heute die Access-DB mal über den Installer für den svws-Server migriert. Beim Start von SchILD3 mit der migrierten Datenbank gab es einen Fehler bei der Volljährigkeitsberechnung der SuS, da wurde noch ein falscher Feldname für die Ortsangabe verwendet. Nachdem das korrigiert wurde, ließ sich die DB einwandfrei öffnen.
Ich werde in Kürze eine aktualisierte Version bereitstellen, bitte damit mal ausprobieren.

**Comment by FPfotenhauer** [comment]
Können wir das Issue schließen?
Bitte mal mit dem aktuellen Installer testen und ggf. wieder öffnen.
