### ISSUE TITLE
Migration hat nicht funktioniert

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#277]
Ich habe den SVWS-Server komplett neu eingerichtet (Version 0.2.10) und habe nach der Installation von SchILD (Version 0.0.37) die Migration einer anonymisierten DB getestet.

Hier das Protokoll:
Verbindung zur Datenbank auf Server "localhost:3306" erfolgreich hergestellt.

Anmeldung mit Benutzer "svwsadmin" erfolgreich durchgeführt.

Verbindung zum SVWS-Server erfolgreich hergestellt.
Datei "C:\Betatest_schild_30\SCHILD2000n_GE_sgs_anonym.mdb" wurde nach "C:\Betatest_schild_30\SCHILD2000n_GE_sgs_anonym_Temp.mdb" kopiert.
Datei "C:\Betatest_schild_30\SCHILD2000n_GE_sgs_anonym_Temp.mdb" wird nun komprimiert und repariert.
Komprimierung erfolgreich

Starte Migrationsservice auf SVWS-Server.

Verbindung zur Quell-Datenbank erfolgreich hergestellt.

Die Datenbankmigration wird nun gestartet. Dies kann längere Zeit dauern, bitte schalten Sie den Rechner nicht aus!

Bei der Datenbankmigration traten Fehler auf:
{"success":false,"log":["Erstelle eine temporäre Access-Datenbank unter dem Namen \"C:\\ProgramData\\SVWS-Server/temp/svwsdb_GefJXSxE0WYYQqyJLBWyOIj8C1sFeItae09bDS1g.mdb\"","Migriere in die MARIA_DB-Datenbank unter localhost:3306:","  - verwende den root-benutzer: root","  - erstelle das DB-Schema: svwsdb","  - erstelle den Benutzer \"svwsadmin\" für den administrativen Zugriff auf das DB-Schema.","Migriere von MDB (C:\\ProgramData\\SVWS-Server/temp/svwsdb_GefJXSxE0WYYQqyJLBWyOIj8C1sFeItae09bDS1g.mdb/PUBLIC) nach MARIA_DB (localhost:3306/svwsdb)","  -> Migration fehlgeschlagen! (Ziel-Schema ist aktuell gesperrt und kann daher nicht überschrieben werden)","  Fehler bei der Migration (driver='MARIA_DB', location='localhost:3306', user='svwsadmin')"]}

Ich hatte vorher SchILD 3.0 deinstalliert und alle entsprechenden Ordner gelöscht.
Den Vorgang habe ich mehrfach wiederholt. Vermutlich gibt es irgendeine Datei, die von der alten Installation noch exisitiert und zusätzlich noch gelöscht werden muss. Ich konnte da aber nichts finden.

**Comment by hagege** [comment]
Bei einem weiteren Versuch mit einer anderen DB erhalte ich die folgende Fehlermeldung:
![fehler_beim_erstmaligen_start](https://user-images.githubusercontent.com/27292550/168051985-6c406d8e-1743-4f28-9ba4-71e839f8e705.png)

**Comment by FPfotenhauer** [comment]
Wenn die Migration scheitert, dann kommt natürlich dieser Fehler in Schild3, weil Schild3 als allererstes auf die Benutzertabellen zugreifen will, um die Berechtigungen zu prüfen.

Die erste Fehlermeldung sagt, dass das Schema gesperrt ist. Dies deutet daraufhin, dass auf diesem Datenbankschema gerade ein Updateprozess läuft. Wurde da irgendwas doppelt gestartet?

Wenn man den SVWS-Server komplett "rasiert" und dann installiert, dann sollte das nicht auftreten.

**Comment by hagege** [comment]
Ich hatte den SVWS-Server komplett gelöscht.
Gerade teste ich noch, ob ich andere Datenbanken migrieren kann. Ich melde mich.

**Comment by hagege** [comment]
Nachdem ich jetzt mehrmals den SVWS-Server und SchILD installiert und deinstalliert habe und dabei zwischendurch den Rechner teilweise auch neu gestartet habe, gibt es jetzt ein Problem mit dem Datenbankschema, siehe Screenshot:
![kein_datenbankschema](https://user-images.githubusercontent.com/27292550/168096736-a41bd0d7-8ec2-4a65-89b0-75373eee07f6.png)
Auch die Stapeldatei _delete_services_ habe ich jeweils vor einer Neuinstallation ausgeführt.
Es wäre m. E. sinnvoll, wenn eine kleine Anleitung zum manuellen Anlegen eines Datenbankschemas erstellt würde, damit man in solch einem Fall weiterkommt. Zumindest habe ich nichts dergleichen in den Dokus gefunden.

**Comment by hagege** [comment]
Danach erfolgte eine Fehlermeldung bei der Migration. Nur zur Klärung: Hinter "Bei der Datenbankmigration traten Fehler auf:" kam nichts mehr.


Verbindung zur Datenbank auf Server "localhost" erfolgreich hergestellt.

Verbindung zum SVWS-Server konnte nicht hergestellt werden: 
Fehlermeldung: Winsock - Connection refused (Error #10061) to [::1]:443

SVWS-Server erfolgreich neu gestartet.
Datei "C:\SchILD-NRW_Test\DB\SchILD_GE_Stolberg_2018.mdb" wurde nach "C:\SchILD-NRW_Test\DB\SchILD_GE_Stolberg_2018_Temp.mdb" kopiert.
Datei "C:\SchILD-NRW_Test\DB\SchILD_GE_Stolberg_2018_Temp.mdb" wird nun komprimiert und repariert.
Komprimierung erfolgreich

Starte Migrationsservice auf SVWS-Server.

Verbindung zur Quell-Datenbank erfolgreich hergestellt.

Die Datenbankmigration wird nun gestartet. Dies kann längere Zeit dauern, bitte schalten Sie den Rechner nicht aus!

Bei der Datenbankmigration traten Fehler auf:

**Comment by FPfotenhauer** [comment]
Wenn der Server nicht läuft, dann kann man eigentlich auch sofort aufhören und dort nach der Ursache suchen.

Was sagen die LOG-Dateien des Servers?
Ist das wieder so ein Rechner wo was anderes auf Port 443 läuft?
Ist im TaskManager der Serverdienst und die MariaDB gestartet?

Man soll ja kein Schema selbst anlegen, das soll ja der Server machen, sonst hat man keine svwsconfig.json und dann findet der Server die DBs nicht und kann auch keine Updates fahren.

**Comment by hagege** [comment]
> Wurde die Delete_Services.bat als Admin ausgeführt?
Nein, das hatte ich nicht explizit als Admin ausgeführt. Könnte ich noch mal machen

> Man soll ja kein Schema selbst anlegen, das soll ja der Server machen, sonst hat man keine svwsconfig.json und dann findet der Server die DBs nicht und kann auch keine Updates fahren.
Die Meldung lässt allerdings vermuten, dass man das manuell machen kann. Insofern wäre es vermutlich günstig, den Text im Info-Fenster zu ändern.

> Ist das wieder so ein Rechner wo was anderes auf Port 443 läuft?
Nein, ich habe hier extra einen Rechner, auf dem mir Laragon nicht zerschossen wird ;-)

> Was sagen die LOG-Dateien des Servers?
Wo genau finde ich die?

**Comment by hagege** [comment]
Ich habe die ganze Prozedur jetzt noch mal durchgeführt (auch Delete_Services.bat als Admin ausgeführt) und habe bewusst bei der Installation des SVWS-Servers "Erstelle ein neues Schema" angegeben. Leider ohne Erfolg.
![datenbankschema_fehlt](https://user-images.githubusercontent.com/27292550/168110241-c40db9ad-8355-4f86-8b0a-1a4d4e21050a.gif)

**Comment by FPfotenhauer** [comment]
![grafik](https://user-images.githubusercontent.com/34127980/168113206-a2e817b0-1b68-447d-9380-80a7290b503e.png)

**Comment by hagege** [comment]
Der Ordner ist bei mir nicht da. Danach hatte ich natürlich schon geschaut.
Seltsamerweise hatte das ja vorher bei mir alles mit den alten Betaversionen funktioniert, bis ich aufgrund der neuen Versionen alles komplett neu erstellt habe.
![ordnerstruktur_2](https://user-images.githubusercontent.com/27292550/168113802-93bcd83f-d615-4938-9e5f-a8c756d47cc7.png)

**Comment by FPfotenhauer** [comment]
Das ist ein Systemordner, der ist u.U. unsichtbar.
Vielleicht mal den Pfad manuell eintippen?

**Comment by hagege** [comment]
ok, das schaue ich mir später an.

**Comment by hagege** [comment]
Danke für den Hinweis. Hier die Dateien aus dem Ordner
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8681145/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8681146/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8681149/svws_server_service.wrapper.log)

**Comment by hagege** [comment]
Du hast geschrieben:
_Man soll ja kein Schema selbst anlegen, das soll ja der Server machen, sonst hat man keine svwsconfig.json und dann findet der Server die DBs nicht und kann auch keine Updates fahren._
und später:
_Wenn kein Schema gefunden wird, dann eins anlegen!_

Da bin ich jetzt ein wenig irritiert, weil ich in den beiden Aussagen einen Widerspruch sehe.

**Comment by FPfotenhauer** [comment]
OK. Der Server startet gar nicht .
So kann das nicht gehen.
Ich schau mir das morgen in Ruhe an.

**Comment by FPfotenhauer** [comment]
Ich meinte nicht manuell anlegen... Nur mit unseren Tools. Das Tool von Herrn Richter ruft ja auch nur den Svws Server auf....

**Comment by hagege** [comment]
_Ich schau mir das morgen in Ruhe an._
Hattest Du Dir das mal angesehen?

**Comment by FPfotenhauer** [comment]
Ja. Er findet den Keystore nicht, dann kann der Server nicht starten.
Ich würde alles mal komplett löschen und nochmal probieren.
Wenn es dann noch auftritt, dann würde ich mir da sauch gerne mal ansehen.

**Comment by FPfotenhauer** [comment]
Bitte mal testen, ob das Problem mit dem aktuellen Installer gelöst ist.

**Comment by hagege** [comment]
Das steht allerdings noch aus: 
**Seltsam war die doppelte Abfrage der DB (SchILD 2.x DB). Da habe ich noch mal die gleiche DB angegeben.**

**Comment by AnneSchueller** [comment]
Es gibt nochmal eine neuere SetupSVWSServer-Version in der Fachberater-Cloud. Da wurde bei der DB-Auswahl nochmal was geändert.

**Comment by hagege** [comment]
ok, danke für die Info.
Ich habe das heute Nachmittag mit der SetupSVWSServer-Version 0.2.16 getestet, die ich da als Beta-Version aus der Cloud runtergeladen habe. Ich sehe gerade in der Cloud, dass vor 9 Stunden die SetupSVWSServer_v0.2.18.exe hochgeladen wurde. Scheint sich überschnitten zu haben.
