### ISSUE TITLE
Migration von MSSQL zu MariaDB 

### ISSUE THREAD

**Issue by legolas410** [SVWS-NRW/Schild3-BetaTest#278]
Leider funktioniert die Migration eines bestehenden Schild2.0 System mit einer MSSQL-Datenbank auf
ein Schild3.0 System mit MariaDB nicht. 

Voraussetzungen: 
Für die Schild3.0 MariaDB haben wir einen eigenen physikalischen Rechner bereitgestellt. Der Rechner läuft in einer Windows Domäne.
Angemeldet sind wir aber als lokaler Administrator auf dem Rechner. 

1. Wir starten die Installation SetupSVWSServer_v0.2.10.exe als Administrator.
2. Wir geben alle nötigen Informationen ein und klicken uns durch die Abfolge. (siehe Bilder) 
![image](https://user-images.githubusercontent.com/21102176/168253964-6e0e4e0c-4167-4a7c-9b19-230691abea15.png)
![image](https://user-images.githubusercontent.com/21102176/168254136-fa2f0adc-4778-4572-8220-1c5ad9cb2d85.png)
![image](https://user-images.githubusercontent.com/21102176/168254360-d16fbf82-8af7-4b9b-b41e-7edff58c6f35.png)
![image](https://user-images.githubusercontent.com/21102176/168254853-9e38dc7e-547b-4a3d-9e59-3b568175475a.png)

Die Erstellung der Datenbank dauerte ungefähr 5 Sekunden.
Ein Blick mit HeidiSQL zeigt leider, dass keine Datenbank/Schema bzw. kein Benutzer erstellt worden ist. (siehe Sreenshot)

![image](https://user-images.githubusercontent.com/21102176/168255446-bb674a31-ed0a-4541-b0b7-4c1e7a6a266b.png)
![image](https://user-images.githubusercontent.com/21102176/168256663-6e6dd4f7-f21f-449a-bc88-cc4f67645ea3.png)

Die entstandenen Logfiles: 

[Setup Log 2022-05-13 #002.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8685912/Setup.Log.2022-05-13.002.txt)

Der Ordner `C:\ProgramData\SVWS-Server\logs  ` gibt es leider noch nicht. 

Was machen wir falsch?
Funktioniert die Migration von MSSQL überhaupt schon? 
Wenn wir bei der Installation des SVWS-Server ein neues Schema erstellen und dann später mit dem Tool MigrateDB.exe aus dem Schild3.0 Installationsverzeichnis unsere MSSQL Datenbank migrieren wollen, dann erscheint dafür gar keine Option.

**Comment by FPfotenhauer** [comment]
M;an sieht ja, dass der Server ewig braucht um zu Starten.
Da stimmt was nicht. Ist da noch was anderes auf Port 443?
Sonst mal den SVWS-Server komplett mit delete_services.bat löschen.

Da muss ja auch noch das Fenster kommen, wo alle Dateien installiert werden ....
Wird der Server unter "Dienste" angezeigt? Ich vermute nein.

**Comment by legolas410** [comment]
> M;an sieht ja, dass der Server ewig braucht um zu Starten. Da stimmt was nicht. Ist da noch was anderes auf Port 443? Sonst mal den SVWS-Server komplett mit delete_services.bat löschen.
> 
Kein anderer Dienst/Programm ist auf dem Rechner installiert bzw. der SWVS-Server ist das einzige Programm welches nach einer frischen Windows-Installation installiert wurde. 
Delete_services.bat haben wir immer mit Administrator-Rechten ausgeführt. 
Alle vorherigen Installationen des SWVS-Server haben wir sauber durch den Uninstaller entfernt. 

> Da muss ja auch noch das Fenster kommen, wo alle Dateien installiert werden .... Wird der Server unter "Dienste" angezeigt? Ich vermute nein.
>
Ja das Fenster wird auch angezeigt. Wenn es um die Erstellung der Datenbank/Schema geht dann springt es halt nach ein paar Sekunden zum letzten Fenster. Zeigt auch keine Fehlermeldung oder ähnliches an. 
Ob der Server unter Dienste angezeigt wird muss nochmal überprüfen. 

Wenn wir allerdings eine neues Schema erstellen, also den Haken bei der Installtion setzten, (keine Migration von einer bestehenden Datenbank) wird ein Schema/Datenbank erstellt und auch in HeidiSQL angezeigt. 

Soll ich von dem ganzen Prozess mal ein Video aufnehmen?

**Comment by FPfotenhauer** [comment]
Ich kann nächste Woche auch mal draufschauen... Interessiert mich sehr....

**Comment by legolas410** [comment]
Gerne. Evtl. können Sie sich ja per Teamviewer/Anydesk draufschalten und den Prozess live beobachten (wenn unsere Firewall in  der Schule das aufschalten per Teamviewer/Anydesk zulässt xD)

**Comment by JeVaske** [comment]
Bei mir gibt es seit dem letzten Update des SVWS-Servers keine Probleme mehr mit der Migration von MSSQL (Schild2) nach MariaDB (Schild3). (SetupSVWSServer_v0.2.10 und Setup_SchILD3_v0.0.37). Kann es sein, dass beim DB-Schema oder dem Ort die Bezeichnung nicht stimmt? Ich verwende die Anmeldedaten, die ich auch im SQL Server-Managment-Studio benutze:
![SchildMigration](https://user-images.githubusercontent.com/78501680/168424321-7e67abdf-0260-44e3-9fcb-27bb13f3c46d.jpg)

**Comment by legolas410** [comment]
@JeVaske: Habe unsere Einstellungen nochmal überprüft und tatsächlich einen Fehler gefunden. Unser Schema in MSSQL ist `schildnrw` und nicht wie auf dem Screenshot zu sehen `schild_nrw`. 
Nach der Korrektur und erneuter Intallation kommt leider das gleiche Ergebnis wie im oben beschrieben. 
Hier dazu nochmal das Installationslog:
[Setup Log 2022-05-16 #001.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8698063/Setup.Log.2022-05-16.001.txt)
![image](https://user-images.githubusercontent.com/21102176/168542866-9c600f86-38bc-46d7-b673-e14c408ca13f.png)
Auch hier geht der Installer bei der Meldung `Migriere Datenbank....` nach ein paar Sekunden direkt zum Abschlussfenster. 
Keine Fehlermeldung. 
Die Datenbankverbindung kann hergestellt werden, jedoch wurde wieder kein Schema angelegt. 

Die anderen Anmerkungen treffen auf unsere Infrastruktur nicht zu. 
Die Authentifizierung ist bei uns über die Domäne geregelt. Einen Login SA für den MSSQL-Server ist mir nicht bekannt. 
![image](https://user-images.githubusercontent.com/21102176/168543243-fcf07cdd-383e-4d29-8da8-399669839ed1.png)

Gibt es eine Möglichkeit an erweiterte Logdaten zu kommen? Sowas wie ein Debug-Mode?

**Comment by FPfotenhauer** [comment]
Hallo.

Windows-Authentifizierung ist mit unserem Treiber eher nicht möglich.
Läuft denn der SVWS-Server? (https://localhost/debug auf dem Server.)

Wenn ja, dann nochmal in das ErrorLog schauen....

**Comment by legolas410** [comment]
> Hallo.
> 
> Windows-Authentifizierung ist mit unserem Treiber eher nicht möglich. Läuft denn der SVWS-Server? (https://localhost/debug auf dem Server.)

![image](https://user-images.githubusercontent.com/21102176/168549337-e9fab2f5-3df3-472f-b1da-a3475a2ab392.png)
![image](https://user-images.githubusercontent.com/21102176/168549483-b6810f5a-d8b9-4bb1-9d5c-eb1c2adab9fa.png)

> 
> Wenn ja, dann nochmal in das ErrorLog schauen....

Leider gibt es kein Ordner `Logs` im `C:\ProgramData\SVWS-Server` Verzeichnis.

**Comment by FPfotenhauer** [comment]
Wenn man die SwaggerUI sehen kann, dann läuft der SVWS-Server!
Ist das hier der gleiche Server wie in Issue 279?
Denn dort sagt das ErrorLog eigentlich, dass der Server nicht läuft.

**Comment by legolas410** [comment]
> Wenn man die SwaggerUI sehen kann, dann läuft der SVWS-Server! Ist das hier der gleiche Server wie in Issue 279? Denn dort sagt das ErrorLog eigentlich, dass der Server nicht läuft.

Das ist die gleiche physikalische Maschine jedoch wurde vorher alles nach Anleitung deinstalliert. In diesem Issue geht es ja um die Migration von MSSQL zu MariaDB. Installtion des SWVS-Server als loker Administrator. 

Issue 279 beschreibt die Installation mit der Erstellung eines neuen Schema (keine Migration) als Domänenadministrator.

**Comment by FPfotenhauer** [comment]
Dann ist hier aber nicht das SetupLOG relevant, sondern die Log-Dateien des SVWS-Server.
Da könnte man dann sehen, warum er nicht migriert.

**Comment by legolas410** [comment]
> Dann ist hier aber nicht das SetupLOG relevant, sondern die Log-Dateien des SVWS-Server. Da könnte man dann sehen, warum er nicht migriert.

Warum nicht migriert wird wissen wir ja jetzt: 
> Windows-Authentifizierung ist mit unserem Treiber eher nicht möglich.

Wir müssen dann warten bis die Windows-Authentifizierung an dem MSSQL-Server vom SVWS-Server bei der Migration unterstützt wird.

**Comment by FPfotenhauer** [comment]
Steht denn im LOG, dass der Zugang verweigert wurde?
Wir werden das nicht aktivieren können.
Man kann aber im SQL-Server die SQL-Server-Authentifizierung einschalten.
Kann man nach der Migration ja auch wieder abschalten.

**Comment by legolas410** [comment]
Haben jetzt einen MSSQL-Server aufgesetzt der die SQL-Server-Authentifizierung benutzt und außerhalb der Domäne ist. Dort haben wir unsere bestehende Datenbank eingefügt. 
Haben die Verbindung zum MSSQL-Server vorher mit HeidiSQL getestet und können erfolgreich drauf zugreifen. 
Danach nochmal den SVWS-Server installiert und im Installer die Zugangsdaten für die Migration eingegeben. 
Ganz geklappt hat es nicht. Der Installer hat zwar die MariaDB mit dem entsprechnedem Schema erstellt und mit den Standarttabellen gefüllt, jedoch nicht die Daten aus der MSSQL-Datenbank eingefügt.  
SVWS-Server läuft und `https://localhost/debug/index.html` kann aufgerufen werden.

[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8708596/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8708597/svws_server_service.out.log)
[2022_05_17.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8708598/2022_05_17.request.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8708599/svws_server_service.wrapper.log)
[Setup Log 2022-05-17 #004.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8708612/Setup.Log.2022-05-17.004.txt)

**Comment by FPfotenhauer** [comment]
OK. Aber jetzt kann man sehen, der SVWS-Server läuft und die Migration startet.
Das Schema wurde angelegt und auch die Verbindung zur Quelldatenbank hat geklappt.

Beim kopieren der Tabelle Eigene Schule_KAOADaten knallt es dann.
Dort wird ein Primärschlüssel doppelt vergeben.
Das ist ein Fehler in der Schild2-DB.
Kann ich mir die Tabelle mal irgendwie ansehen?

**Comment by FPfotenhauer** [comment]
Nachtrag: Es könnte auch die Tabelle EigeneSchule sein.
Sind dort zwei Einträge? Mit gleicher Schulnummer?

**Comment by legolas410** [comment]
Wir haben mit HeidiSQL die entsprechenden Tabellen als SQL-Befehl exportiert. Ich hoffe Sie können damit was anfangen.
[EigeneSchule_KAoADaten.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8713581/EigeneSchule_KAoADaten.txt)
[EigeneSchule.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8713582/EigeneSchule.txt)

**Comment by FPfotenhauer** [comment]
Wenn das weiterhin auftritt, müsste ich mir das einmal mit Fernwartung ansehen.
Da kann ich keine ungültigen Einträge erkennen.

**Comment by legolas410** [comment]
Das können wir einrichten. Bitte teilen Sie uns dazu einen passenden Termin mit.

**Comment by FPfotenhauer** [comment]
Bitte einmal eine Mail senden.

**Comment by FPfotenhauer** [comment]
Es gabe doppelte Tabellennamen in der DB mit verschiedenen Präfixen.
Das wird nun abgefangen...

**Comment by legolas410** [comment]
Wir haben die doppelten Tabellennamen mit dem falschen Präfixen gelöscht und den Installer erneut gestartet. 
Folgende Logs wurden produziert und beim Starten von Schild3 kommt folgender Fehler: 
![image](https://user-images.githubusercontent.com/21102176/170012482-8d83740e-9eb1-45fd-bf3a-10c4e16d8051.png)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8761855/svws_server_service.out.log)
[2022_05_24.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8761856/2022_05_24.request.log)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8761857/svws_server_service.err.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8761858/svws_server_service.wrapper.log)
[Setup Log 2022-05-24 #001.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8761860/Setup.Log.2022-05-24.001.txt)

**Comment by FPfotenhauer** [comment]
Da sind Fremdschlüsselverletzungen in der Tabelle Benutzerkompetenzen.
Hat da zwischenzeitlich einer was verändert?

**Comment by legolas410** [comment]
Nein. 
Das ist die gleiche Datenbank die wir dir geschickt haben. 
Haben nur mit dem Microsoft MSSQL Manager die entsprechenden Tabellen gelöscht.

**Comment by FPfotenhauer** [comment]
Ach, kann sein, ich habe hier ja die Entwicklungsumgebung.
Das sollte in der nächsten Version des SVWS-Servers behoben sein.
