### ISSUE TITLE
Probleme mit der SVWS-Server Installation als Domänenadministrator

### ISSUE THREAD

**Issue by legolas410** [SVWS-NRW/Schild3-BetaTest#279]
Unsere IT-Infrastruktur ist in einer Windows-Domäne organisiert. 
Für den Schild3.0 Testbetrieb haben wir einen eigenen physikalischen Rechner bereitgestellt auf dem der SVWS-Server installiert wird.
Dieser Rechner hat den Hostnamen `Schild3` und ist Mitglied in der Domäne `HGE.local`
Folgende Optionen haben wir bei der Installation angewählt. 
![Screenshot2](https://user-images.githubusercontent.com/21102176/168545742-6423ad04-5907-4d54-8a98-c5ebbf9ccf64.jpg)

Bei der Installation von dem SVWS-Server als Domänenadministrator haben wir Probleme entdeckt die bei der Installtion als Lokaler Administrator nicht auftreten. 

### **Installation des SVWS-Server als **Domänenadministrator****
1. Es wurde kein Datenbankschema in der installieten Datenbankinstanz erstellt.
![Screenshot1](https://user-images.githubusercontent.com/21102176/168546098-240461fe-447a-4f29-8baa-33e132f83af1.jpg)

2. SVWS-Zertifikat ist nicht im angegebenen Ordner erstellt worden

Logdaten: 
[Setup Log 2022-05-06 #002.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8698208/Setup.Log.2022-05-06.002.txt)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8698209/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8698210/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/8698213/svws_server_service.wrapper.log)

### **Installation des SVWS-Server als **Lokaler Administrator****

Die Installation funktioniert ohne Probleme. Datenbank wird installiert und mit den Standart-Tabellen gefüllt. 
Auch das Zertifikat liegt an der angegebenen Stelle.

**Comment by FPfotenhauer** [comment]
[main] INFO org.eclipse.jetty.server.RequestLogWriter - Opened C:\ProgramData\SVWS-Server\logs\2022_05_06.request.log
Exception in thread "main" java.lang.IllegalStateException: C:\ProgramData\SVWS-Server\res\keystore is not a valid keystore
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:45)
	at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1111)

**Comment by legolas410** [comment]
> Ich gehe davon aus, dass hier andere Berechtigungen gesetzt werden müssen. Es kann auch sein, dass der DomainAdmin kein Documents-Ordner hat. Was spricht denn dagegen, den lokalen Admin zu nehmen?

Unsere Server werden auf kurz oder lang zentral in einem Rechenzentrum als VM laufen. Da ist kein lokaler Administrator mehr vorgesehen. 
Evtl. sollte das Verzeichnis für die Zertifikate bei der Installations auszuwählen sein. 

Welche Rechte, die über die Rechte eines Domänenadministrator hinausgehen, werden für die Erstellung der Datenbank/schema benötigt. 
Meiner Meinung nach sollte korrekte Funktion und Installation des SWVS-Server in einer Domäne als Normalfall gelten. 
Gibt es noch ein Log wo man sehen kann warum das Dantenbankschema nicht angelegt wird?

**Comment by FPfotenhauer** [comment]
Wir können das Zerifikat mal an eine andere Stelle legen.
Im InstallerLÖog sieht es aber so aus, als würde ein Update gefahren und keine neue Installation?
Dann wird auch kein neues Zertifikat erstellt, weil er ja denkt, es wäre schon eins da.

Ja, ich weiß, im Installerfenster steht es würde ein Zertifikat angelegt ....
Bitte mal alles rasieren und als Domainadmin neu installieren.

**Comment by legolas410** [comment]
Wir werden alles nochmal auf dem Test-Rechner rassieren und dann von der Installation ein Video machen. 
Noch was: 
Findet die Installations als Domänenadministrator statt dann steht im Setup Log:
`-> SVWS-Zertifikat erfolgreich extrahiert. (Datei="C:\Users\Administrator.HGE\Documents/SVWS.cer"; ResultCode=1)`
Jedoch wurde kein Zertifikat erstellt. 

Wenn die Installation als Lokaler Administrator durchgeführt wird steht im Setup Log so was: 
`-> SVWS-Zertifikat erfolgreich extrahiert. (Datei="C:\Users\admin\Documents/SVWS.cer"; ResultCode=0)`
Hier wurde das Zertifikat erfolgreich erstellt.

In beiden Fällen meldet das Setup Log zwar das ein Zertifikat erstellt worden ist aber der `ResultCode` ist ein unterschiedlicher. 
0 = Zertifikat wurde tatsächlich erstellt ?
1 = Fehler beim erstellen ?

**Comment by FPfotenhauer** [comment]
> 0 = Zertifikat wurde tatsächlich erstellt ?
> 1 = Fehler beim erstellen ?

Das ist korrekt, der Text ist fehlerhaft.
Die Ursache wird aber wahrscheinlich darin liegen, dass mit dem lokalen Admin installiert wurde und dann mit Domainadmin upgedatet wurde.

**Comment by FPfotenhauer** [comment]
Ich bringe das Thema hier nochmals hoch, weil ein ähnliches Problem auf einem anderen Rechner aufgetreten ist.
Dort haben wir im SVWS-Installer zwei Sachen geändert: 
1. Die Wartezeit, bis der Server wurde verlängert.
2. Es wurde ein Kestore.Log eingerichtet.

Bitte mal mit dem aktuellen Installer testen.

**Comment by Raffenberg** [comment]
Beim jetzigen Installer funktioniert bei mir die Zertifikatserstellung und die Installation auf dem Domänen-Client reibungsfrei.

**Comment by FPfotenhauer** [comment]
Nach dieser Zeit keine Rückmeldung. Ich schließe das Issue.
