### ISSUE TITLE
Individualdaten I lässt sich bei skalierten Schriftarten von 120% schon nicht mehr vollständig anzeigen.

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#28]
Viele Nutzerinnen (im höheren Alter) haben die Schriftart auf 120% skaliert. Leider ist der Karteireiter I dann schon nicht mehr vollständig sichtbar. In der Regel sind die Bildschirme breiter als hoch. Daher sollte es vom Layout keine Probleme geben.

**Comment by FPfotenhauer** [comment]
Man kann dan in Schild-NRW auch etwas unter 100% skalieren in den Einstellunegn.
Was passiert dann?

**Comment by Kluesenerm** [comment]
Hier werden die Ribbons teilweise unvollständig angezeigt.
![image](https://user-images.githubusercontent.com/75179015/101245949-837ddb80-3710-11eb-91b8-93901c555f77.png)

**Comment by Kluesenerm** [comment]
Es werden nicht alle Teilbereiche vergrößert. Bei den Lehrkräften bleibt der Faktor bei 100.

**Comment by FPfotenhauer** [comment]
Bitte auch in das 120% Issue aufnehmen.
