### ISSUE TITLE
Halbjahreswechsel

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#281]
Beim Halbjahreswechsel wird nur die Schule ins neue Halbjahr versetzt und die Lernabschnitte werden angelegt.
Die Schüler werden allerdings nicht mit versetzt und werden dementsprechend lila.

**Comment by JuergenRichter** [comment]
Bei meiner Testdatenbank (Gesamtschule) hat das definitiv funktioniert. Welche Schulform haben Sie denn benutzt?

**Comment by AnneSchueller** [comment]
Eine Gymnasialdatenbank.

**Comment by AnneSchueller** [comment]
Schuljahreswechsel funktioniert mit der Gymnasialdatenbank

**Comment by spechtg** [comment]
Ich hänge mich hier mal ran:  Schild v0.0.38; DB Gesamtschule
Der Abschnittswechsel wird ordnungsgemäß durchgeführt. Das Fenster (zur Prüfung und Durchführung des Wechsels) verschwindet nach Ausführung jedoch nicht automatisch. Unten rechts ist nur die Eingabe "Abbrechen" möglich. Es ist ein manuelles Schließen des Fensters erforderlich.

**Comment by JuergenRichter** [comment]
Der Schuljahres-/Abschnittswechsle wurde noch etwas ergänzt/korrigiert. Sollte jetzt funktionieren, auch sollten nun alle "abschnittsbezogenen" Daten (z.B. Zuordnung der Klassenlehrer, Lehrer-Abschnittsdaten) autom. angelegt werden. Ich werde in Kürze nochmal ein Update berietstellen.
