### ISSUE TITLE
Kursanzeige reduzieren bei Jahrgangsauswahl

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#282]
![grafik](https://user-images.githubusercontent.com/84628225/169217908-0da99ff4-bc30-49dc-9399-ad914d9110a7.png)
Ist es möglich, nachdem eine Jahrgangsstufe im Container gewählt wurde, dass dann unter Kurse nur noch die Kurse des selektierten Jahrgangs angezeigt werden?
Ist kein dringendes Muss, wäre aber erheblich praktischer.

**Comment by JuergenRichter** [comment]
Bei "Schnellfilter SchILD2" wird bei Auswahl eines Jahrganges auf die zugehörigen Kurse gefiltert. Wir werden das auch hier in Kürze umsetzen.

**Comment by JuergenRichter** [comment]
Bei der "Schnellfilterung SchILD2" ist das umgesetzt, nun auch hier bei der Baumansicht.
Wichtig: Wenn mehr als ein Jahrgang ausgewählt wird, wird auf die Kurse gefiltert, bei denen beide Jahrgänge (als "mehrere Jahrgänge") eingetragen sind. Es wird nicht auf die Jahrgänge gefiltert, die entweder dem einen oder dem anderen Jahrgang zugeordnet sind!
