### ISSUE TITLE
FHR-Berechnung Leistungsdaten holen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#283]
![grafik](https://user-images.githubusercontent.com/84628225/169218812-2aed0b41-7e87-4a58-9d3d-ec7c69ecd42f.png)
Fehlermeldung beim Holen der Leistungsdaten FHR-Berechnung.
DB Gymnasium
Schild 3.0.34.7

**Comment by HHayen** [comment]
![grafik](https://user-images.githubusercontent.com/84628225/169219226-2ec12663-3927-4d43-96b9-de9d225bdbdc.png)
Diese Meldung kommt bei Schülern, die noch gar keine Leistungsdaten im FHR haben (Q1)
Sieht nach Tippfehler aus? "SChuelelr_ID" soll vielleicht "Schueler_ID" heißen?

**Comment by JuergenRichter** [comment]
Behoben
