### ISSUE TITLE
Gruppenprozess -> Noten,Mahnungen und Fehlstunden eingeben

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#284]
Beim Versuch die Noten einer vorgefilterten Klasse unter Gruppenprozess -> Noten, Mahnungen und Fehlstd. einzugeben reagiert Schild nicht und hängt sich auf. 
Schildversion: v0.0.34

**Comment by AnneSchueller** [comment]
Den gleichen Bug habe ich auch. Zusätzlich erhalte ich eine Fehlermeldung "Operation bei geschlossener Datenmenge nicht ausführbar"

**Comment by JuergenRichter** [comment]
Der Gruppenprozess ist noch nicht an die neue DB_Struktur angepasst, kommt in Kürze
