### ISSUE TITLE
Gruppenprozess --> Zeugnisbemerkung eintragen 

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#286]
Schild stürzt bei der Aktion eine Zeugnisbemerkung bei einer Schülergruppe zu setzen ab. 
Bis zur Wahl der gewünschten Zeugnisbemerkung funktioniert alles problemlos. Beim Ausführen der Zuweisung hängt sich Schild nach einer Zeit auf.

**Comment by JuergenRichter** [comment]
Behoben
