### ISSUE TITLE
weitere Exporte und MNS-Pro-Export fehlen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#289]
Ich kann die weiteren Exporte (JaNa, Abitur, ZK, Wohnortdaten) nicht finden. Der MNS-Pro-Export bei den Lernplattformen scheint auch noch zu fehlen.

**Comment by AnneSchueller** [comment]
Den Export ZK finde ich auch nicht. Lernplattformen müssen noch komplett neu eingepflegt werden.
Der Export JaNa ist unter Verwaltung Export aufgelistet.
Wohnortdaten kann man theoretisch auch mit dem Export "als Excel Datei exportieren" realisieren. Da wäre die Frage, ob man das nochmal separat auflistet?

**Comment by JuergenRichter** [comment]
Einige Export wurden bisher über externe Programme (DLLs) geregelt. Diese funktionieren nun wegen der geänderten Datenbankstruktur aber nicht mehr, außerdem sollen die Funktionen ins Programm integriert werden. Ich will aber erst mal die bisherigen "Kernfunktionen" fehlerfrei zum Laufen bekommen, dann werden die Exporte angegangen.

**Comment by AnneSchueller** [comment]
Vielen Dank für den Hinweis; Dann warte ich mit weiteren Tests zum Exportieren.

**Comment by JuergenRichter** [comment]
Ist jetzt umgesetzt
