### ISSUE TITLE
Die Grundeinstellungen der Reports werden nicht angezeigt

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#29]
Ich kann den Speicherort der Reports nicht anpassen:

![Reporta](https://user-images.githubusercontent.com/75179015/101026043-b1c7b380-3576-11eb-87b3-17115c6dabf8.jpg)

**Comment by FPfotenhauer** [comment]
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/20
