### ISSUE TITLE
Export Externes Notenmodul

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#290]
![schildfehler11](https://user-images.githubusercontent.com/78501680/171259554-ec21a44c-78dd-4019-b5d0-6760cfb28178.jpg)

**Comment by FrodBRA** [comment]
3.0.71.9

@AnneSchueller 

Der Export funktionierte gerade. Ist das Issue noch aktuell? Müsste eventuell mit konkreten Datenbanken getestet werden, bei denen das Problem auftritt.

**Comment by AnneSchueller** [comment]
Der oben genannte Fehler tritt nicht mehr auf, daher schließe ich das Issue. 
Notenexport/Import funktioniert allerdings noch nicht.
