### ISSUE TITLE
Logineo-Export

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#291]
![schildfehler12](https://user-images.githubusercontent.com/78501680/171259759-64a9b3d0-e05b-410f-8d3a-7d268f31420a.jpg)

**Comment by HHayen** [comment]
![grafik](https://user-images.githubusercontent.com/84628225/177334704-ea6a4bdc-0c0e-4044-8753-06c71bf701c6.png)

**Comment by JuergenRichter** [comment]
Logineo ist noch nicht agepasst, z.Zt. wird der Statistik-Export überarbeitet

**Comment by HHayen** [comment]
Ok, danke.

**Comment by JuergenRichter** [comment]
Logineo-Export nun umgesetzt

**Comment by KaBe47Du** [comment]
Beim Versuch, einen Logineo-LMS-Export durchzuführen, erscheint die Fehlermeldung "#42S22Unknown column 'S.Klasse' in 'where clause'.". Dies geschieht sowohl beim Klick "Benutzernamen und Kennworte erzeugen (ohne Export)" als auch auf "Export starten". 
![Schild3_Issue_Logineo_Export](https://user-images.githubusercontent.com/73294213/205446881-15ff6504-7a9e-4c2e-b948-3bcc1fd38842.jpg)
![Schild3_Issue_Logineo_Export_Fehler](https://user-images.githubusercontent.com/73294213/205446884-6c69f54e-568d-4e28-b27f-87bb8e38a7b3.jpg)
Einmal hat es funktioniert, dies lässt sich aber nicht zuverlässig reproduzieren. (Vers. 3.0.50.8)

**Comment by KaBe47Du** [comment]
Obwohl ich Lehrer- und Schülerdatenexport ausgewählt habe, sind in der csv nur Lehrerdaten.

**Comment by JuergenRichter** [comment]
Behoben
