### ISSUE TITLE
Export für IServ

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#292]
![schildfehler13](https://user-images.githubusercontent.com/78501680/171259922-7b438ee0-aa8c-4f0a-9ebb-2dfec3df43d1.jpg)

**Comment by KayBerger** [comment]
![IServ-Export_Fehlermeldung](https://user-images.githubusercontent.com/111630806/185740695-860c44ae-c637-42ef-b589-77651b907fa8.jpg)
