### ISSUE TITLE
Schüler einfügen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#295]
Wenn ich im Reiter Schüler auf "Einfügen" klicke und dann auf "Abbrechen" kommt die Fehlermeldung
![schildfehler16](https://user-images.githubusercontent.com/78501680/171437951-fa061d0d-f20a-4642-a65d-518cfd459cdd.jpg)
:

**Comment by JuergenRichter** [comment]
Behoben
