### ISSUE TITLE
Bearbeitsungswerkzeuge der Lehrerfotos funktionieren nicht

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#296]
Sobald ein Regler betätigt wird, kommt die Meldung:
![schildfehler17](https://user-images.githubusercontent.com/78501680/171440282-667a71a3-9de3-40d4-ab9a-aa5534deee0a.jpg)

**Comment by JuergenRichter** [comment]
Behoben
