### ISSUE TITLE
Darstellungsfehler Scroll-Balken

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#298]
Ich rufe Akt. Halbjahr/Leistungsdaten auf:
![schildfehler19](https://user-images.githubusercontent.com/78501680/171476877-876dc367-c7fe-456f-9982-cae64075a08a.jpg)

Wenn ich danach auf Verwaltung/Einstellungen/Fächer klicke und dann wieder auf den Reiter "Schüler", taucht dort ein Scroll-Balken auf, der da nicht hingehört:
![schildfehler20](https://user-images.githubusercontent.com/78501680/171477678-c5822fe4-44a8-4987-b4eb-131c5f9a7012.jpg)

**Comment by FrodBRA** [comment]
@AnneSchueller 

Der Scrollbalken taucht bei mir nicht mehr auf, der Fehler hatte sich mit der UI-Überarbeitung mit gelöst.
