### ISSUE TITLE
Schriftbild in verschiedenen Reitern

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#299]
Je nach Bildschirm sieht die Schrift sehr unschön aus (siehe Bild)
![Schild3_Schrift](https://user-images.githubusercontent.com/79116896/173785077-d07ab9e3-d429-4ab3-991e-e4c9f91c1c85.png)

**Comment by JuergenRichter** [comment]
Können Sie mir mal die Auflösung des Bildschirmes mitteilen?

**Comment by AnneSchueller** [comment]
Getestet mit 
1920 x 1080 und
2736 x 1824

**Comment by JuergenRichter** [comment]
Die Ursaceh ist vermutl. folgende:
Die "Itemheight" (Zeilenhöhe) beim Backstage-Menu wird in Pixeln angegeben, die "FontSize" aber in Punkt. Da natürlich alles auf dem Bildschirm schließendlich in Pixeln dargstellt wird, muss auch die Punktgröße (über Systemroutinen) irgendwann in Pixeln umgerechnet werden. Das heißt, dass die Pixelgröße der Schrift dynamisch ist, die Zeilenhöhe aber (derzeit) statisch. Ich habe das nun so umgestellt (erst mal testweise für die Kataloge), dass die Zeilenhöhe sich aus der (in Pixel umgerechnten) Punktgröße der Schrift ergibt. Ich lade das nachher mal auf Github hoch, bitte mal mit verschiedenen Auflösungen testen.
WICHTIG. Bisher nur für die Katalog-Einträge umgesetzt.

**Comment by AnneSchueller** [comment]
Die Schrift sieht schon viel besser aus. Keine Überschneidungen mehr. Verhältnismäßig ist sie sehr groß. Gäbe es die Möglichkeit, die Größe über Strg +/- zu steuern?

Unter Verwaltung kann man das linke Fenster nicht weiter aufziehen; hier sieht man nicht den gesamten Text.

![Ansicht_Verwaltung](https://user-images.githubusercontent.com/79116896/174814244-e8fca7cf-85e1-4726-8f20-e5ad53161eb1.png)

**Comment by AnneSchueller** [comment]
![Kataloge](https://user-images.githubusercontent.com/79116896/175117677-96204348-9538-4fcc-a94d-36c64d09b382.png)

**Comment by FrodBRA** [comment]
@AnneSchueller 

Das Issue hatte sich mit der UI-Überarbeitung gelöst.

Die einzigen Fehler die mir noch bekannt sind, finden sich in der Benutzerverwaltung und dies ist als eigenes Issue eigenständig offen.
