### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#3]
Wenn irgendetwas gedruckt werden soll, kommt diese Fehlermeldung:

"SELECT*FROM SchuelerADR WHERE Schueler_ID=: ORDER BY Sortierung: qrySchErzAdr: Das Feld 'ErzBemerkung' wurde nicht gefunden"

**Comment by FPfotenhauer** [comment]
Das sollte in der Schild3.exe, die neben dem Installer liegt beseitigt sein.
Einfach im Installationverzeichnis die Datei tauschen.
