### ISSUE TITLE
Installation SVWS-Server: Schema kann nicht angelegt werden

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#30]
Bei einer erneuten Installation nach Deinstallation vom SVWS-Server und SchILD bekomme ich nachfolgende Meldung:
![fehlermeldung_schema](https://user-images.githubusercontent.com/27292550/101072859-ee0f0a00-359e-11eb-887b-154f038c2c21.jpg)

**Comment by FPfotenhauer** [comment]
Welche Version?
Was steht im Installer LOG?
Was steht in den Server-Logs?
Wurde der MariDB-Server korrekt installiert und gestartet?

**Comment by hagege** [comment]
Das ist die Version 0.0.33
Im Ordner C:\Program Files\SVWS-Server gibt es bei mir keinen Ordner log wie in der Doku angegeben ist.
Wo finde ich die Installer Log?
Wie kann ich feststellen, ob der MariaDB-Server korrekt installiert und gestartet ist. In der Doku konnte ich dazu nichts finden.
Ich habe den SVWS-Server jetzt noch mal deinstalliert (über Einstellungen bei Windows) und anschließend delete_services zusätzlich gestartet.
Im Anhang sende ich das Protokoll mit den Screenshots
[protokoll_4_12_2020.docx](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5642519/protokoll_4_12_2020.docx)

**Comment by FPfotenhauer** [comment]
In meiner Dokumentation steht auf Seite 6 unten, dass die Logs unter C:\ProgramData\SVWS-Server\logs liegen.
Auch das Verzeichnis für das Installer log ist dort auf Seite 7 oben beschrieben.

Den MariaDB-Server kann man in der Windows Computerverwaltung unter den Diensten kontrollieren.

**Comment by FPfotenhauer** [comment]
Hat der Installer nach den Programmpfaden zu Beginn gefragt?
Wenn nein, bitte mal das aktuelle delete_services.bat verwenden. Dort ist noch ein RegKey vom uninstaller hinzugekommen.

**Comment by hagege** [comment]
ah, sorry, ich hatte den Ordner unter C:\Program Files\SVWS-Server gesucht. 
Der Installer hat nach den Programmpfaden gefragt. Die neue delete_services.bat hole ich mir später und teste das dann noch mal. Ich sende Dir die Dateien aus C:\ProgramData\SVWS-Server\logs.
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5642845/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5642846/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5642847/svws_server_service.wrapper.log)
[2020_12_03.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5642848/2020_12_03.request.log)

**Comment by hagege** [comment]
Im Taskmanager unter dem Reiter "Dienste" ist MariaDB-Server nicht genannt.

**Comment by ThomasBachran** [comment]
Beim Starten des Dienstes tritt eine NullPointerException auf. Ich habe diese mal zurückverfolgt und werde einen Patch zu dem Fehler erstellen. Das sollte dann nicht mehr zum Beenden des SVWS-Servers führen und nur noch eine Warn-Meldung im Log erzeugen. Die Null-Pointer-Exception tritt dann auf, wenn in der SVWS-Konfiguration ein Schema eingetragen ist, was nicht erreicht werden kann. Der SVWS-Server prüft nämlich zu Beginn, ob alle konfigurierten Schemata auch erreichbar sind und aktualsisiert diese gegebenenfalls...

**Comment by FPfotenhauer** [comment]
Aber dennoch. Kann es sein, dass in dieser Laragon-Unmgebung irgendein Dienst auf Port 3306 gestartet war und auch läuft?
Wenn ja, dann ist ja klar, warum unser MariaDB-Server nicht gestaret werden konnte und auch das Schema dann nicht erreichbar war. Wenn das der FAll war, bitte dieses Issue schließen.

Und an alle, die hier mit lesen, wenn Echtdatenbanken im Spiel sind, dann bitte auf keinen Fall die LOGs hier posten, sondern per Mail senden. Es kann Exceprions geben, in denen dann Daten stehen!

**Comment by hagege** [comment]
Nein, ich habe gerade mit netstat -an eine Ausgabe der Ports angesehen. Laragon wird (zumindest in meiner Testumgebung) nicht automatisch gestartet. Allerdings habe ich auf jedem Rechner bis dato immer Probleme mit meiner Laragon-Testumgebung gehabt, wenn ich den SVWS-Server auch mit unterschiedlichen Ports installiert habe.
Ich sende Dir gleich per Mail die Datei mit der o. g. Ausgabe.
