### ISSUE TITLE
Aktuelle Schülerauswahl - Filter Fachklasse

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#300]
Bei dem Filter Fachklasse wird jetzt zwar die Fachklassenbezeichung angezeigt, allerdings fehlt die SGL (wie in SchILD2) bei uns gibt es die gleichen Fachklassen in verschieden SGL was zu Verwechslungen führen könnte - eine extra Auswahl der SGL über den Filter halte ich für wenig pragmatisch.

![SGL Filter Fachklassen](https://user-images.githubusercontent.com/75326793/174483647-8945fa78-20e1-41c0-9ccd-e6df59938541.jpg)

**Comment by AlexanderDedy** [comment]
Eine zweite Sache, die mir beim Filtern aufgefallen ist, hänge ich hier mal an.
==> Ich vermisse bereits jetzt die Filtermöglichkeit mit "Doppelklick" SuS markieren und mit STRG-M als Auswahl. Auch wenn es die Möglichkeit mit Haken und Filter auf markierte SuS - so brauche ich oft beide Filter gemeinsam! In verschieden Klassen bekommen SuS oft sehr unterschiedliche Reports und ich muss zuerst eine Teilgruppe bilden (Fett markiert + Auswahl) und anschließend von denen mit Haken über explizit ausgewählt im Gruppenprozess.....
Es ist für größere Schulen sehr hilfreich mehrere Filter gleichzeitig zu haben!

**Comment by AnneSchueller** [comment]
Das mit den markierten SuS wurde absichtlich erstmal außenvor gelassen, da es bei Schild 2 immer zur Verwirrung kam, was nun "markiert" und was "ausgewählt" bedeutet. Ich nehme das aber gerne mit in unsere Diskussionsrunde.

**Comment by JuergenRichter** [comment]
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/300#event-6847839218

**Comment by JuergenRichter** [comment]
![image](https://user-images.githubusercontent.com/61280188/174833755-4ea4ff4f-d24b-49bc-b7ab-c70e6163f91b.png)
