### ISSUE TITLE
Teilleistungen kopieren / an Stundentafeln koppeln

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#301]
Mir ist gerade folgendes aufgefallen: Wenn ich bei einem S im aktuellen HJ / Leistungsdaten die Fächer kopiere, werden die zugewiesenen Teilleistung nicht mit kopiert. Am BK werden viele SuS verspätet angemeldet und dann die Fächer von einem anderen S in der Klasse kopiert und eingefügt. Die bereits zugewiesenen Teilleistungen leider nicht, was bei der Eingabe kurz vor der ZK zu vielen Mails führt. ich würde mir folgendes wünschen:
1. Die TL werden mit den Fächern kopiert
2. Man kann individuelle TL bei den Stundentafeln definieren. - bei den Fächern (wie bisher) nützt es nicht viel (am BK) weil jeder Bildungsgang unabhängig voneinander "seine" Teilleistungen beschließt und es so zu unterschieden kommt. 
3. Es wäre schön wenn ein S, der in eine neue Klasse gesetzt wird mit Abfrage den aktuellen Klassenunterricht zugewiesen bekommen könnte... oder eben nicht..

**Comment by AnneSchueller** [comment]
Das hat in Schild2 auch nicht funktioniert. Hier musste man auch erst nochmal nach dem Kopieren der Fächer über Gruppenprozesse -> Teilleistungsarten aus Vorlage zuweisen oder gibt es da einen Trick, den ich noch nicht kenne?
Ich leite das aber mal weiter als Verbesserungsvorschlag.

Zu 2: Da weiß ich gerade nicht, ob das so einfach umzusetzen ist. Du meinst, dass z.B. Mathe in dem Bildungsgang x andere Teilleistungen abspeichert als Mathe im Bildungsgang y? Ich verstehe aber, dass es ansonsten für das BK sehr unschön ist, wenn da sämtliche Teilleistungen für ein Fach definiert werden und man die meisten für den entsprechenden Bildungsgang gar nicht braucht.

**Comment by AnneSchueller** [comment]
Da sämtliche Anforderungen der BK aktuell überarbeitet und im SVWS-Server eingepflegt werden, schließe ich das Issue mal.  Die Teilleistungen sind hierbei mit im Blick
