### ISSUE TITLE
Klassenauswahl fehlt seit Update

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#302]
Bei der aktuellen Schülerauswahl fehlt seit dem Update die Möglichkeit auf Klassen und Kurse  zu filtern

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren:
![image](https://user-images.githubusercontent.com/61280188/174834529-93b8bea5-4f6c-4a0d-8e52-106518e06d36.png)

![image](https://user-images.githubusercontent.com/61280188/174834596-752a51e7-56db-4755-a5b5-b6aba77f945b.png)

**Comment by AnneSchueller** [comment]
Nach einer Neuinstallation klappt es wieder.
