### ISSUE TITLE
Wiedervorlage anzeigen führt zu Abfragefehler

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#304]
### SVWS: 0.2.12 SchILD3: 0.0.43
Ruft man die Wiedervorlage auf 
![grafik](https://user-images.githubusercontent.com/44644567/180647934-231cacd6-48ab-4cad-9577-61ad73f0a5cd.png)
erscheint der Fehler:
![grafik](https://user-images.githubusercontent.com/44644567/180647950-25aff213-757e-4f0e-92f8-5c4e0054ddc0.png)

### Log-Info:
[FehlerWiedervorlage.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9175826/FehlerWiedervorlage.txt)

**Comment by AnneSchueller** [comment]
Bei mir funktioniert das Anzeigen der Wiedervorlage. Das liegt aber vielleicht an der Version (3.0.40.7) Allerdings das Eintragen in die Wiedervorlage funktioniert  nicht.

**Comment by JuergenRichter** [comment]
Der Eintrag wird in der Datenbank gespiechert, das Fenster schließ sich aber dann nicht. Ist jetzt korrgiert.

**Comment by JuergenRichter** [comment]
Auch der Fehler mit dem Feld "Klasse" bei Anzeige der Wiedervorlage ist korrigiert.
