### ISSUE TITLE
Aktuelle Datenbanknutzer zeigen -> Error

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#305]
### Verwaltung/Benutzer/Aktuelle Datenbanknutzer zeigen
Aufruf führt zu Fehler:
![grafik](https://user-images.githubusercontent.com/44644567/180648533-f278d50b-5c40-4fbc-8f07-67c39201c72b.png)

###Log-Info
[FehlerDatenbanknutzer.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9175844/FehlerDatenbanknutzer.txt)

**Comment by JuergenRichter** [comment]
Behoben
