### ISSUE TITLE
Schnittstelle Schild-NRW Export bei Wechsel im Halbjahr mit Problem

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#306]
### SchILDversion: 3.0.39.7
Schild-NRW-Schnittstelle Export mit Fehlern, die beim Export aus Schild2 nicht auftreten.
Folgender Fehler tritt auf:
![grafik](https://user-images.githubusercontent.com/44644567/180649470-6dcbc901-f40d-4bfe-a6c6-3ad65bcad806.png)
Das passiert bei Schülern, die eine Klassenwechsel innerhalb eines Schuljahres haben.
![grafik](https://user-images.githubusercontent.com/44644567/180651938-014d31fc-2fb1-4261-bc21-5c57234d0f0c.png)
#### Auch zu beheben:
Hier sieht man auch, dass die Reihenfolge der Abschnitte falsch ist. Die beiden letzten Abschnitte sind in der falschen Reihenfolge angezeigt. Kann natürlich durch die Migration bedingt sein.

**Comment by JuergenRichter** [comment]
Reihenfolge ist korrigiert, bei welcher Datenart tritt denn der Exportfehler auf?

**Comment by FrodBRA** [comment]
Ist das Issue noch aktuell?

@EwaldReinhardt
