### ISSUE TITLE
Migrationsfehler Adressen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#307]
##MigrateDB Version: 1.0.8 (1.0.13.7)

Bei den Adressen wird die Hausnummer nicht richtig migriert:
Es werden die Buchstaben nicht übernommern, die Teil der Hausnummer sind:
Beispiele: 
1. „Versestr. 26 a“ wird zu Straße „Versestr." und Hausnr.  „26“
2. „Hösinghausen 1+ 22“ wird zu Straße „Hösinghausen 1+" und Hausnr.  „22“ .
Hier der Screenhot der Betriebsadresse:
![grafik](https://user-images.githubusercontent.com/44644567/181042647-f3600fe3-eb5f-4250-b5d3-34b0b23933a1.png)

Dies gilt für alle Datensätze mit Adressen: Schueler, Allgemeine Adressen, Erziehungsberechtigte, Lehrer

**Comment by FPfotenhauer** [comment]
Wir haben dafür nun eine andere Art der "Spaltung" mit eigenen Tests eingeführt.
Ich schließe das Ticket mal. Allerdings wird das erst in der nächsten Version des SVWS-Server behoben sein!

**Comment by FPfotenhauer** [comment]
Ach so. Nur zur Info 26 a ist nicht Standardkonform. Es sollte 26a (ohne Leerzeichen) sein.
