### ISSUE TITLE
Migrationsfehler Schülerleistungsdaten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#308]
##MigrateDB Version: 1.0.8 (1.0.13.7)

Schild2.0 erlaubt die Angabe der Sondernoten nicht case-sensitiv:
![grafik](https://user-images.githubusercontent.com/44644567/181044186-1af61c4b-2344-4ad8-8ec6-00b8a72fa3d8.png)

Bei der Migration werden aber nur die Werte migriert, die komplett in Großbuchstaben in der Datenbank stehen.
Bei den (teilweise) kleingeschriebenen Werten bleibt das Feld in der Zieldatenbank leer!

Wenn in der Quelldatenbank keine Kurzsart angegeben ist, wird automatisch PUK vergeben. Sollte nicht automatisch ergänzt werden.

**Comment by FPfotenhauer** [comment]
Aber wir stehen hier auf dem Standpunkt, dass es keine leere Kursart geben darf.
Das würde bei der kommenden Statistik (keine Angst in 4 Jahren oder so) aufschlagen.

**Comment by FPfotenhauer** [comment]
Wir würden die Kleinbuchstaben in Großbuchstaben wandeln.
Aber dann muss Schild3 auch nur noch Großbuchstaben eintragen!

**Comment by FPfotenhauer** [comment]
Hier müsste Herr Richter die Eingabe von Kleinbuchsteben sprerren.

**Comment by EwaldReinhardt** [comment]
> Aber wir stehen hier auf dem Standpunkt, dass es keine leere Kursart geben darf. Das würde bei der kommenden Statistik (keine Angst in 4 Jahren oder so) aufschlagen.

Sollte das dann auch im Programm ohne Angabe nicht möglich sein?

**Comment by FPfotenhauer** [comment]
Auch hier wäre es sinnvoll das "mal so und mal so" zu vereinheitlichen.
Dieses ständige "jeder kann machen, was er will" führt dazu, dass einheitliche Umsetzungen in der Logik sehr schwer zu programmieren sind.

Wir korrigieren jetzt die Kleinbuchstaben bei der Migration.

@JuergenRichter Soll ich das Issue schließen? Oder machen Sie das, wenn die Kleinschreibung gesperrt wurde?

**Comment by EwaldReinhardt** [comment]
Die Eingabe in Kleinbuchstaben könnte auch direkt in Großbuchstaben gewandelt werden.
Fände ich etwas nutzerfreundlicher.

**Comment by JuergenRichter** [comment]
Vielleicht sollte auch mal definiert werden, an welche Stellen im Programm überhaupt "Textnoten" (also z.B. NE, NT, AT, E1, E2, E3 usw.) vorkommen sollen. Es gibt sicher Stellen, wo das nicht sinnvoll ist (z.B. BK-Abschlussnoten). 

Bei der Noteneingabe im Hauptfenster (Akt. Halbjahr) wird übrigens jetzt schon bei Eingabe von z.B. "ne" automatsich "NE" ausgewählt. Ob das in anderen Fenstern, wo Noteneingaben möglich sind, auch so ist, muss ich prüfen. In diesem Zusammenhang wäre daher sinnvoll zu definieren, wo überhaupt Textnoten eingebbar sein sollen.

**Comment by FPfotenhauer** [comment]
@EwaldReinhardt kannst du evtl. nochmal migrieren und mir eine Rückmeldung geben, ob das Problem noch besteht?

**Comment by EwaldReinhardt** [comment]
Habe gerade nochmal mit der aktuellsten Version migriert.
Die Textnoten werden jetzt auch migriert und in Großbuchstaben gewandelt.
Bei unbekannte Notenwerten wird das Fach ohne Notenwert übernommen.
Das sieht jetzt alles richtig aus.

Ein Punkte könnte verbessert werden:
Beim Import über die SCHILD-NRW-Schnittstelle wird kein toUpper aufgerufen, sodass Textnoten
wie "ne", "nb" nicht zu "NE" bzw "NB" werden.

**Comment by AnneSchueller** [comment]
@JuergenRichter Geht die Anpassung für den Import (Textnoten auch ne ==> NE usw.) schnell?
Dann bräuchte man kein separates Issue.

**Comment by JuergenRichter** [comment]
Ja, das sollte kein großer Aufwand sein

**Comment by JuergenRichter** [comment]
Habe ich umgesetzt
