### ISSUE TITLE
Migrationsfehler Verkehrssprache

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#309]
##MigrateDB Version: 1.0.8 (1.0.13.7)

Wenn bei einem Schüler die Verkehrsprache nicht angegeben ist, wird automatisch deutsch eingetragen.
Das Feld sollte leer bleiben und nicht automatisch belegt werden.

SchILD2: 
![grafik](https://user-images.githubusercontent.com/44644567/181045806-64e2e72e-6425-4af9-b941-e15e4bf494ec.png)
SchILD3:
![grafik](https://user-images.githubusercontent.com/44644567/181046009-4bc9f93a-b698-4b3e-a654-9cb10135cce9.png)

**Comment by FPfotenhauer** [comment]
Ist das im Webclient auch zu sehen?

**Comment by EwaldReinhardt** [comment]
Leider kann ich den Webclient nicht nutzen:
doch vorab noch der Hinweis, dass der Wert deutsch auch über die Schnittstelle exportiert wird und in der Datenbank steht:
![grafik](https://user-images.githubusercontent.com/44644567/181202980-14bd9ab7-c2f4-4e16-8fa4-d3e2c07b0ba1.png)

## Fehler Webclient
Nach der Installation lief der Dienst svws_server_service und die Seite wurde im Browser angezeigt.
Das Anmelden hat auch funktioniert, aber die Einstiegsseite wurde dann nicht mehr angezeigt und im Chrome und Opera
kommt der Dialog zum Anmelden an der Webseite als ob diese über .htaccess geschützt wäre:
Da der Dienst gerade nicht gestartet werden kann der Dialog einer anderen Webseite (oben steht dann nur localhost):
![grafik](https://user-images.githubusercontent.com/44644567/181201382-5b3ce710-b542-4ecd-b5e3-175bb6b8e7cf.png)

## Dienst svws_server_service startet nicht mehr:
die Logdateien aus ProgramData/SVWS-Server habe ich angehängt.
![grafik](https://user-images.githubusercontent.com/44644567/181200429-743eb439-6d79-4a16-a266-d8ed94b5045e.png)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9196554/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9196555/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9196556/svws_server_service.wrapper.log)

**Comment by FPfotenhauer** [comment]
Hat sich erledigt. Wir kümmern uns um die Verkehrssprache.
Fehglernder Webclient ist ein anderes Issue, das würd eich hier ungern weiter vertiefen.

**Comment by EwaldReinhardt** [comment]
In welchem Bereich können wir das denn diskutieren?
