### ISSUE TITLE
Schüler suchen funktioniert nur mit Groß-/Kleinschreibung

### ISSUE THREAD

**Issue by ukloppenburg** [SVWS-NRW/Schild3-BetaTest#31]
Hallo,
wenn man in Schild 3 einen Schüler sucht, ist die Suche noch case-sensitive. Der Schüler "meier" wird nicht gefunden, "Meier" hingegen schon.
Menüpunkt Schüler, dann "Suchen" (Fernglas) anklicken.
Schild 3.0.5.2
SVWS-Server 0.0.33

**Comment by FPfotenhauer** [comment]
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/13
