### ISSUE TITLE
Migrationsfehler Sprachenfolgen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#310]
##MigrateDB Version: 1.0.8 (1.0.13.7)

Die Sprachenfolge wird nicht richtig migriert.
VonJahrgang und BisJahrgang werden nicht richtig übernommen:

Die Exporte aus SchuelerSprachenfolgen.dat:
2.0:	<BLOCKQUOTE>|E|1|5|1|12|2|B2
	|F|2|11|1|11|2|A2</BLOCKQUOTE>
3.0:	<BLOCKQUOTE>|E|1|05|1|02|2|B2
	|F|2|01|1|01|2|A2</BLOCKQUOTE>
Screenshots aus den Programmen:
![grafik](https://user-images.githubusercontent.com/44644567/181048511-5881f63c-b308-4faa-ac54-9c42b7ffe70c.png)
![grafik](https://user-images.githubusercontent.com/44644567/181048653-7f254657-9516-4822-8b95-8b743158e3e3.png)

**Comment by FPfotenhauer** [comment]
Die Jahrgänge werden korrigiert.
An BKs gibt es keikne Jahrgänge 12 und 13. (Siehe Schlüsselverzeichnis).

**Comment by EwaldReinhardt** [comment]
Ich möchte dem widersprechen.
Die APO-BK nennt sehrwohl entsprechende Jahrgangsstufen:
![grafik](https://user-images.githubusercontent.com/44644567/181197411-33b4acf7-8c2f-4fed-9b0d-833841953be9.png)
Auf dem Abizeugnis sollte auch sicherlich 11,12,13 stehen und nicht 01,02,03.
Ich denke in den Sprachenfolgen sollten die wirklichen Jahrgänge eingetragen werden können und nicht
die Werte, die in der Statistik bei ASDPC verwendet werden

**Comment by FPfotenhauer** [comment]
Das wird in den Zeugnissen auch abgefangen.
Wir wollen aber keine Statistikjahrgänge in der Datenbank stehen haben, die nicht zulässig sind.
Die Eintragung kann so jetzt auch schon in Schild2 gemacht werden.

**Comment by FPfotenhauer** [comment]
In Schild3 sollte dann aber auch geregelt sein, dass keine ungültigen Jahrgänge mehr eingetragen werden können.

**Comment by EwaldReinhardt** [comment]
Aber ich muss doch aus den Zubringerschulen den Jahrgang 5 aufwärts eintragen. Die gibts (noch) nicht am BK. Wenn es die geben sollte sind wir nicht mehr eindeutig. Diese Jahrgänge wären doch auch nicht gültig.
Das sieht ja auch komisch aus von Jahrgang 05 bis Jahrgang 02:
![grafik](https://user-images.githubusercontent.com/44644567/181568576-55a89519-b2be-46ed-9158-c8370eb55484.png)

Vielleicht sollte das in der Tabelle der Statistikjahrgänge hinterlegt werden können. 
![grafik](https://user-images.githubusercontent.com/44644567/181519926-eeffcf5c-5acb-4e6a-aecc-13859e67e449.png)

Das könnte dann auch beim erzeugen des Versetzungsvermerks auf Abschnitt C Zeugnissen verwendet werden.

**Comment by FPfotenhauer** [comment]
Sieht komisch aus, ist aber für das Datenbankschema besser.
Wir würde an dieser Stelle gerne eine Vereinheitlichung durchführen.
Der neue Sprachenmanager im SVWS-Server wird das alles korrekt berücksichtigen.
