### ISSUE TITLE
Export Schnittstelle SchILD-NRW - Änderungen Schnittstellendateien

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#311]
##SchILDversion: 3.0.39.7

### Dateiabgänge - werden in SchILD3 nicht erzeugt
1. LehrkraefteLernplattformen.dat
2. SchuelerLernplattformen.dat

### Dateizugänge - werden zusätzlich in SchILD3 erzeugt
1. SchuelerAUE.dat
2. LehrkraefteFachrichtungen.dat
3. LehrkraefteLehrbefaehigungen.dat

### Strukturänderungen in den Dateien
1. LehrkraefteLehraemter.dat ist um die Fachrichtungen und Lehrbefähigungen erleichtert worden, die jetzt in die neuen Dateien LehrkraefteFachrichtungen.dat und LehrkraefteLehrbefaehigungen.dat geschrieben werden.
2. SchuelerSELS.dat ist laut Schnittstellenbeschreibung für das außerunterrichtliche Engagement vorgesehen. Dies wird nun in SchuelerAUE.dat exportiert. Die Datei SchuelerSELS.dat wird aber auch noch in SchILD3 erzeugt!?
3. Ausgabe von Infos mehrerer Halbjahre in der Datei Lehrkraefte.dat 
Alt: 	|L|V|*|25,5||J|181043
Neu:	|L-L--L|V-V--V|*-*--*|25,5-25,5--||J|181043
Wie wird der Zeitraum beim Export definiert und wie wird das beim Import den Schulhalbjahren zugeordnet?

Wird das ggfs. auch auf https://wiki.svws.nrw.de/mediawiki/index.php?title=Schnittstellenbeschreibung
dokumentiert.

**Comment by AnneSchueller** [comment]
Die Lernplattformen inklusive Einwilligungen fehlen noch komplett in Schild3. Ich öffne dazu nochmal ein separates Issue.
Die Struktur der beim Export erzeugten Dateien wurde in Schild3 etwas geändert. In der Datei SchuelerSELS.dat wird nun der Lern- und Leistungsfortschritt gespeichert. Mit der Zeit soll auch ein neues Wiki aufgesetzt und gefüllt werden.

In der Datei Lehrkraefte.dat hat sich eigentlich nichts geändert.

**Comment by EwaldReinhardt** [comment]
Doch,  Lehrkraefte.dat hat sich geändert:
![grafik](https://user-images.githubusercontent.com/44644567/181518765-0ab442f5-b151-4bb5-ad04-730e509381bb.png)

**Comment by AnneSchueller** [comment]
Hm bei meiner Gymnasialdatenbank nicht, beide Exporte sind in dem Format wie bei Dir in Schild2
@FPfotenhauer: Was könnte hier schief gelaufen sein?
![Bild3](https://user-images.githubusercontent.com/79116896/181704740-1b5ffc8e-10dd-4ff9-8bf2-9e771b78a153.png)

**Comment by FPfotenhauer** [comment]
Herr Richter ist doch momentan an der Anpassung der Schnittstelle.
Vielleicht kann er das prüfen, ob das ein Bug ist.

**Comment by JuergenRichter** [comment]
Prüfe ich

**Comment by JuergenRichter** [comment]
Ist behoben, es lag daran, dass versehentlich bei den Lehrkräften (je nach Einstellung beim Export) auch z.B. die Rechtsverhälnisse mehrerer Lernabschnitte ausgegeben wurden. Jetzt werden nur die Daten des aktuellen Abschnittes berücksichtigt.
