### ISSUE TITLE
Export Schnittstelle SchILD-NRW - Fehler SchuelerBasisdaten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#312]
##SchILDversion: 3.0.39.7

1. In der Titelzeile wird jetzt Organisationsform statt OrgForm angegeben (weiß nicht, ob das überlesen wird)
2. In den Spalten Schwerstbehinderung, Autist und LS Reformpädagogik wird in 3.0 ein - statt ein N und ein + statt ein J ausgegeben.
3. Die Werte für Schwerstbehinderung und Autist werden aus dem akt. Halbjahr / Allgemeine Angaben I entnommen. Dieses Daten müssten doch über die Datei SchuelerLernabschnittsdaten exportiert werden, da im Programm das für jedes Halbjahr abweichend eingetragen werden kann. 
![grafik](https://user-images.githubusercontent.com/44644567/181077244-cb816753-fb89-46a0-af81-5ea9819b9fde.png)

**Comment by FPfotenhauer** [comment]
Die Schnittstelle können wir eher nicht anpassen.
Das andere kann korrigiert werden.

**Comment by JuergenRichter** [comment]
Die Ausgabe von + und -  (statt J und N) ist korrigiert. Beim Export in die Basisdaten wird bei den genannten Feldern immer der aktuelle Zustand (also aktueller Lernabschnitt) berücksichtigt. Umgekehrt werden beim Import der Basisdaten die betreffenden Felder im aktuellen Abschnitt befüllt.
