### ISSUE TITLE
Export Schnittstelle SchILD-NRW - Fehler SchuelerLernabschnittsdaten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#313]
##SchILDversion: 3.0.39.7

Der Klassenlehrer wird nur im aktuellen Halbjahr exportiert. In seltenen Fällen auch in vergangenen Halbjahren. In 2.0 werden Klassenlehrer für alle Halbjahre exportiert!

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Das liegt an dieser Stelle nicht am Export, sondern daran, dass die Klassenlehrer der vergangenen Abschnitte fehlen. 
![Bild2](https://user-images.githubusercontent.com/79116896/181459421-30bbea34-9a22-404f-ad68-4849e33922db.png)

**Comment by EwaldReinhardt** [comment]
Stimmt, das ist bei der Migration verloren gegangen!

**Comment by FPfotenhauer** [comment]
Die Klassenlehrer werden nun in der KLassen-Tabelle historisch gespeichert und müssten von dort angezeigt werden.
