### ISSUE TITLE
Export Schnittstelle SchILD-NRW - Fehler SchuelerTeilleistungsdaten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#314]
##SchILDversion: 3.0.39.7

###SchuelerTeilleistungsdaten.dat werden nicht vollständig exportiert:
Wenn ein Wechsel im Halbjahr stattfindet, weil z.B. die FHR Prüfung nicht bestanden wurde und der Schüler sich dazu entscheidet zu wiederholen setzt er den Unterricht in der jahrgangstieferen Klasse fort. 
![grafik](https://user-images.githubusercontent.com/44644567/181078566-93542cba-d62b-4622-a77b-ef5bde88a4bd.png)
Für diesen Abschnitt werden die Daten nicht in die Datei SchuelerTeilleistungsdaten.dat exportiert.

**Comment by AnneSchueller** [comment]
Beim Testen ist mir aufgefallen, dass die Zeigehand zum Rücktritt im laufenden Schuljahr bei mir gar nicht funktioniert. Daher kann ich das nicht reproduzieren. 
Wie wurde denn der Schüler zurückgesetzt?
Wenn ich "manuell" ohne Zeigefinder den Schüler zurückversetze habe ich im Export die vorangegangenen Teilleistungen noch mit drin.

**Comment by EwaldReinhardt** [comment]
Der Schüler wurde wohl mit Wechsel in der eigenen Schule  in der Version 2.0 bzw. SchILDzentral versetzt. 

![grafik](https://user-images.githubusercontent.com/44644567/181514053-84862c22-312a-4eef-879e-a9885156911b.png)

Ich habe die Datenbank aus SchILDzentral in eine MDB-Datei exportiert und dann migriert.
Anschließend aus beiden Versionen die Export-Schnittstelle SchILD-NRW bemüht und die Ergebnisse systematisch verglichen.

**Comment by AnneSchueller** [comment]
@FPfotenhauer: kann das an der Migration liegen?

**Comment by EwaldReinhardt** [comment]
Die Daten sind in der Datenbank vorhanden.
![grafik](https://user-images.githubusercontent.com/44644567/181516737-ddc3184c-491e-4bd3-a677-134bbb3c25e8.png)

**Comment by AnneSchueller** [comment]
Sind die Teilleistungen ebenfalls in dem Abschnitt ...(vor 1. Wechsel) bei den Fächern vorhanden?

**Comment by EwaldReinhardt** [comment]
Ja sind sie:
![grafik](https://user-images.githubusercontent.com/44644567/181718273-f61c5c67-1d1e-4f49-90fd-e46cf115e8ac.png)
Die Teilleistungen sind also richtig migriert worden.

**Comment by JuergenRichter** [comment]
In der Definition der Schnittstellendaten für die Teilleistungen gibt es nur die Angaben zu Schuljahr und Abschnitt, aber keine Angaben zum "Wechsel innerhalb des Abschnittes". Beim Import ist es daher nicht möglich zu entscheiden, ob die Teilleistungen zu einem Datensatz vor oder nach einem Wechsel (innerhalb eines Abschnittes) gehören. Daher werden beim Export auch nur die Teilleistungen des jeweils "aktiven" Abschnittsdatensatzes exporiert.

**Comment by EwaldReinhardt** [comment]
Ich habe die Abschnittsliste mal vollständig aufgenommen:
![grafik](https://user-images.githubusercontent.com/44644567/182256737-138092f5-daa4-42c1-bf0d-423f15431cfe.png)
Dananch ist ja der Abschnitt vor dem Wechsel als gewertet gekennzeichnet und der andere nicht. (Wohl um das Zeugnis
nochmal zu erzeugen). 
Es ist so, dass in 2.0 und 3.0 die gleichen Daten zu den Abschnitten vorliegen und die Exporte aber unterschiedlich sind wie oben beschrieben. Ist die Änderung so beabsichtigt? Ist mit "aktiv" gemeint, dass der Abschnitt gewertet ist oder der, der bei gleichem Abschnitt die höhere ID hat  (was gefährlich wäre)?

**Comment by JuergenRichter** [comment]
Es werden nur Teilleistungen exportiert, die zu Lernabschnitten gehören, bei denen kein "(vor...Wechsel)" steht.

**Comment by FPfotenhauer** [comment]
Ich schließe das Ticket mal.
Die Schnittstelle Schild-NRW wurde vor 15 Jahren für den Import der Statistikdaten von Fremdherstellern geschaffen.
Ein Universal Import/Export war eigentlich nie beabsichtigt.

Wir können die Problematik bei den Teilleistungen später noch einmal aufnehmen, wenn das Thema wichtig sein sollte.
