### ISSUE TITLE
Export Schnittstelle SchILD-NRW - Fehler SchuelerAbiFaecher.dat und SchuelerAbitur.dat

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#315]
# SchILDversion: 3.0.39.7

### Grundkurs
2.0: |WL|GK||||||13|+|S|11|+|S|11|+|M|12|+|M|47||||-|-||||-|0|0|2|0|**198**||-
3.0: |WL|GK|||**-**||**-**|13|+|S|11|+|S|11|+|M|12|+|M|47||||-|-||||-|0|0|2|0|||-
### Und bei den LKs:
2.0: |MBT|LK|2|||||11|+|**L**|10|+|**L**|07|+|**L**|09|+|**L**|74|9,25|15|75|-|-|||75|-|0|0|5|0|**102**||-
3.0: |MBT|LK|2||**-**||**-**|11|+|**S**|10|+|**S**|07|+|**S**|09|+|**S**|74|9,25|15|75|-|-|||75|-|0|0|5|0|||-
### weniger Schüler in 2.0 als in 3.0
In 2.0 werden nicht alle Schüler mit Abi-Biga exportiert, wohl nur die, die Abitur gemacht haben als für alle Halbjahre Noten vorliegen.

## Die Dateien **SchuelerAbitur.dat** unterscheiden sich auch in 2.0 und 3.0
2.0: |J|J|3,2|2021|2|256|116||438|445|7|**16**|**30**|||-|-|-|-|K||-|115|1|1|||323|1|38|||0|8,09
3.0: |J|J|3,2|2021|2|256|116||438|445|7|||||-|-|-|-|K||-|115|1|1|||323|1|38|||0|8,09
### weniger Schüler in 2.0 als in 3.0
Anzahl der Schüler unterscheidet sich wie bei SchuelerAbiFaecher.dat.

**Comment by JuergenRichter** [comment]
Zu der Datei SchuelerAbitur.dat:
die fehlenden Angaben "16" und "30" sind die Anzahlen der "relevanten" Leistungs- bzw. Grundkurse. Diese sind in der DB von Schild2 vorhanden, nicht aber in der DB von SchILD3 (zumindet in meinen Test-DBs sind die entsprechenden Spalten alle leer). Ich vermute, dass die Angaben bei der Migration nicht übernommen wurden.

Zu der Datei SchuelerAbiFaecher.dat: 
Grundkurse: Die in SchILD3 fehlende Zahl "198" ist die Fachsortierung (Feld FSortierung in SchuelerAbiFacher). Dieses Feld ist in meiner DB leer, wurde wohl bei der Migration nicht übernommen.

Leistungskurse: Die Information über die Schriftlichkeit ("L" in SchILD2) wird in SchILD3 nun anders verschlüsselt, daher die Abweichung

**Comment by FPfotenhauer** [comment]
Das mit der Migration werde ich prüfen.

**Comment by ThomasBachran** [comment]
@EwaldReinhardt : Interessant wäre hier zu wissen, ob sich die Anzahl der Datensätze in den DB-Tabellen unterscheidet. Sind hier Unterschiede, so sollten diese anhand des Migrationslogs nachvollziehbar sein. Ist dies nicht der Fall, dann müssten wir uns die Migration an dieser Stelle genauer anschauen.

Die zweite mögliche Fehlerquelle ist dann der Export in die DAT-Datei. Hier kann es sein, dass durch die Anpassungen der Daten, die Herr Richter oben beschrieben hat, und ggf. auch durch weitere Anpassungen, der Export-Prozess verändert wurde und ggf. noch angepasst werden sollte.

@EwaldReinhardt : Für welchen Zweck wird die exportierte DAT-Datei denn eingesetzt? Wird sie oft eingesetzt? Oder nur bei einzelnen wenigen Schulen? Sind die Unterschiede, die bei dir aufgetreten sind, relevant?

**Comment by EwaldReinhardt** [comment]
Die Anzahl der Datensätze in der Tabelle SchuelerAbiFaecher ist identisch ebenso wie in der Tabelle SchuelerAbitur.
Hier sieht alles richtig aus. Und die Unterschiede in den DAT-Dateien hat Herr Richter erläutert.
Die Migration ist in den folgenden Punkten nicht vollständig:
- FSortierung wird in der Tabelle SchuelerAbiFaecher nicht migriert.
- AnzRelLK und AnzRelGK werden in der Tabelle SchuelerAbitur nicht migriert

Ich hatte die Schnittstelle verwendet um die Migration systematisch zu testen, indem ich die selben Daten in 2.0 und 3.0 über die Schnittstelle exportiert habe und dann die Unterschiede untersucht habe. 

Die Schnittstelle verwende ich vorzugsweise für die Migration von anderen Schulverwaltungsprogrammen. 
Ob die SchuelerAbi*.dat Dateien von anderen Anwendung genutzt werden, weiß ich nicht.

**Comment by FPfotenhauer** [comment]
Die DAten die nicht migriert werden, sind überflüssig, weil Sie für die ApoGoSt02 waren.
Deshalb schließe ich das Issue.
