### ISSUE TITLE
Anzeige der Passbilder manchmal mit Störungen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#316]
## SchILDversion: 3.0.39.7

Manchmal erscheinen die Fotos mit Störungen (weiße Stippen)
Lehrerfoto:
![grafik](https://user-images.githubusercontent.com/44644567/181082173-7767d80f-8756-426b-aa3d-d95004d9af4a.png)

oder hier im kleinen Bild im Gegensatz zum Bild in dem schwebenden Fenster.
![grafik](https://user-images.githubusercontent.com/44644567/181083629-6b6ff11d-74bf-437a-b8d9-e836268fca52.png)

**Comment by AnneSchueller** [comment]
Ich habe bei mir zusätzlich das Problem, dass ich bei Schülern zwar ein Foto hochladen kann, dieses wird allerdings anschließend nicht angezeigt.

**Comment by JuergenRichter** [comment]
@AnneSchueller: Kann ich mal ein solches Foto haben?

**Comment by AnneSchueller** [comment]
Das mit dem fehlenden Foto funktioniert nun doch, wenn man nach dem Hinzufügen zwischen zwei Schülern hin und her switcht. Ein Skalierungsproblem konnte ich bei mir nicht feststellen. 
Vielleicht könnte Herr Reinhardt ein entsprechendes Bild schicken?

**Comment by EwaldReinhardt** [comment]
Ich habe mein Foto angehängt.
Zudem habe ich gerade festgestellt:

1. dass die Bildanzeige nicht aktualisiert wird, wenn das Foto gelöscht wird mit dem Radiergummi. Das Bild wird weiterhin angezeigt und es gibt kein Feedback, dass das Bild wirklich weg ist.
2. Das Radiergummi nicht aktiv wird, wenn ein Foto eingelesen worden ist. 
![grafik](https://user-images.githubusercontent.com/44644567/182248766-98f92d74-965f-4ede-bf6a-3d31ad8acdb9.png)
3. Das Bearbeitungswerkzeug nicht mit dem Bild versorgt wird und der Editor leer bleibt. Beim Verändern der Helligkeit gab es zusätzlich eine Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/44644567/182249024-97a37cd8-89ad-4267-aa8f-f5a009593197.png)
![Passfoto](https://user-images.githubusercontent.com/44644567/182249372-96174d4c-9698-46b7-b603-ad10550e16f8.jpg)

**Comment by FPfotenhauer** [comment]
Kann das mit der BASE64-Kodierung zu tun haben?
Wie sehen die Bilder im SVWS-Client aus?

**Comment by EwaldReinhardt** [comment]
In Schild2 und im SVWS-Client sieht alles normal aus:
In der Reihenfolge Schild3, SVWS, Schild2
![grafik](https://user-images.githubusercontent.com/44644567/188110502-b08b75df-ecb8-4072-89f0-e4e811470225.png)

**Comment by JuergenRichter** [comment]
Bitte mit der nächsten Version 3.0.76 nochmal testen.

**Comment by FrodBRA** [comment]
Der Fehler tritt mit dem von Ewald hochgeladenen Bild bei mir in SchILD 3.0.76.11 auf. In der Anzeige kommt es zu den weißen Flecken.

Klicke ich dort im Fotobereich aber auf "Bearbeiten", wird das Bild im "Bearbeiten-Modus" korrekt angezeigt. Dies deutet für mich darauf hin, dass irgendwas mit dem Encoding im Hauptbereich nicht oder fehlerhaft konfiguriert ist und kein generelles Problem von SchILD3 bei der Verarbeitung dieses Bildes darstellt.

Mir fällt weiterhin auf, dass das Bild relativ zur Größe des bereitgestellten Bereichs sehr klein angezeigt wird (sieht man hier auch auf den Screenshots). Das Originalbild ist ja ausreißend dimensioniert, ist diese kleine Anzeige gewollt?

**Comment by AnneSchueller** [comment]
Mit dem Bild kann ich das auch reproduzieren. Die Größe im Bearbeitungsmodus finde ich nicht störend.
Beim Drucken über Reports wird das Bild richtig dargestellt.

**Comment by JuergenRichter** [comment]
" Das Originalbild ist ja ausreißend dimensioniert, ist diese kleine Anzeige gewollt?"
Beim Speichern werden Bilder auf eine bei den Einstellungen definierbare Größe reduziert.

**Comment by AnneSchueller** [comment]
Ist denn der "Größen-Reduzierungsalgo" in Schild3 ein anderer als der in Schild2?

Dieser ist ja dann wahrscheinlich auch für die fehlenden Pixel in der Kleinansicht verantwortlich.

**Comment by JuergenRichter** [comment]
Nein, das ist kein anderer. Allerdings haben wir festgestellt, dass es beim Laden der (reduzierten) Bilder, genauer gesagt bei der Base64-Umwandlung, noch ein Problem gab, das jetzt aber im aktuellen Update behoben sein sollte. Bitte mal testen, ich konnte das Problem mit meinen Testbildern nicht reproduzieren.

**Comment by AnneSchueller** [comment]
Ich teste das mit der neuen Version und schließe dann das Issue.

**Comment by FrodBRA** [comment]
Test: Die Artefakte sind in 3.0.77.13 weiterhin vorhanden.

An dieser Stelle sollten wir nach m.E. einmal schauen, ob das Problem auch bei einer großen Datenbasis im systematischen Realbetrieb auftaucht oder nur bei (seltenen) Encodierungsproblemen/Einstellungen bei einzelnen .jpgs auftritt.

Diese Lehrer-jpgs werden voraussichtlich ohnehin alle Paar Jahre neu erstellt.

Ergo: An dieser Stelle und auch mit Blick auf die zur Verfügung stehenden Ressourcen könnte das Issue geschlossen werden - und sollte es systematisch auftreten müsste es erneut reportet werden.
