### ISSUE TITLE
Sortierung der Allgemeinen Adressen sollte nicht Case-sensitive sein.

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#317]
## SchILDversion: 3.0.39.7

Die Sortierung der Allgemeinen Adressen ist Case-sensitiv.
Die Sortierung sollte nicht case-sensitiv sein so wie in 2.0
![grafik](https://user-images.githubusercontent.com/44644567/181084782-574b0228-246a-434e-8619-635c5cc3848f.png)

**Comment by JuergenRichter** [comment]
Darauf hat SchILD keinen Einfluss. Das Programm schickt ja nur eine Abfrage der Art "select <Feldliste> from <Tabelle> order by <Sortierung>" an den Datenbankserver (also z.B. "select * from K_AllgAdresse order by AllgAdrName1"). Wie dabei die Groß- und Kleinschreibung interpretiert wird, ist dann Sache des DB-Servers (über die Collation der entsprechenden Tabelle).

Mir ist aber noch etwas aufgefallen: Wenn man zwei Schüler mit Nachnamen "Oestergard" und "Östergard" hat, so werden diese in Schild2 (mit Access-DB) in folgender Reihenfolge dargestellt:
Oestergard
Östergard

In SchILD3 wird "Oestergard" an der erwarteten Stelle (z.B. vor "Pollmann") sortiert, "Östergard" aber ganz am Ende (noch nach z.B. Zylkowski). Dies liegt vermutl. auch an der Collaton der Tabelle "Schueler".

**Comment by JuergenRichter** [comment]
![image](https://user-images.githubusercontent.com/61280188/182104852-8b42a593-8193-4894-b1e9-6d8b66c67ca5.png)

**Comment by EwaldReinhardt** [comment]
Doch hat Schild3. mit dieser Abfrage:
SELECT * FROM bktl.k_allgadresse
order by AllgAdrName1 COLLATE utf8mb4_general_ci;
werden die Adressen CaseInsensitiv _ci sortiert.

**Comment by EwaldReinhardt** [comment]
Das funktioniert auch für die Einsortierung der Umlaute.
![grafik](https://user-images.githubusercontent.com/44644567/182111733-621313a2-b2dd-4b2b-b983-49176cbc00d5.png)

**Comment by JuergenRichter** [comment]
Das würde aber bedeuten, dass alle Abfragen, bei denen nach Textfeldern (z.B. Namen) sortiert wird, im Programm entsprechend angepasst werden müsten. Wäre es da nicht besser, in der Schema-Definition die "natürliche" Sortiereihenfolge einzustellen. Bei Schild2 (mit Access-DB) ist das ja auch nicht anders.

**Comment by EwaldReinhardt** [comment]
Dem Anwender ist das sicherlich egal. 
Ich befürchte nur, dass es viele Beschwerden geben
wird, wenn sich Schild3 anders verhält als Schild2.
Den Zeichensatz in der Datenbankdefinition anzupassen
ist wohl der schnellere und sicherere Weg das Verhalten
anzupassen.

**Comment by AnneSchueller** [comment]
Danke für den Hinweis,
Ich habe mir das notiert, damit wir das im neuen Wiki als Hinweis vermerken.

**Comment by FPfotenhauer** [comment]
Wir stehen hier grundsätzlich auf dem Standpunkt, dass die Binary-Collation (auch aus Performance-Gründen) die richtige Wahl ist. Die jeweiligen Applikationen müssen sich dann intern um die Sortierung kümmern.
Das wird später, wenn alles über die API geht so oder so so sein.

Mein Vorschlag: Anpassung der Abfragen an wenigen zentralen stellen. Und dann kann man das nach und nach umstellen, wenn wir User-Beschwerden bekommen.

**Comment by EwaldReinhardt** [comment]
Wenn man sich die Seite https://mariadb.com/kb/en/setting-character-sets-and-collations/ anschaut, sieht man, dass die default collations im _ci CaseInsensitiv sind. Ich glaube auch nicht, dass das ein Performanceproblem darstellt.
Nach Norm https://de.wikipedia.org/wiki/Alphabetische_Sortierung sind die Umlaute auch einzusortieren und nicht am Ende des Alphabets, was mit den _ci collations erreicht wird. 
In der Datenbankdefinition ist schon für die Datenbank die Sortierreihenfolge _bin eingestellt und zusätzlich auch in den Tabellen selbst und den einzelnen Spalten, was nur nötig wäre, wenn es von der übergeordneten Reihenfolge abweichen würde.
Wenn in einer Spalte die default collation eingestellt ist, wird die von der Tabelle verwendet, wenn dort default steht, die von der Datenbank. Da die Befehle show create table .. aber das COLLATE auswerfen steht das auch im Befehl für die Erzeugung der Tabellen. Das macht Änderungen natürlich sehr aufwendig.

Hier die entsprechenden Ausgaben vom DB-Server:
Datenbank: CREATE DATABASE `bktl` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin */;
Tabelle k_allgadressen:
CREATE TABLE `k_allgadresse` (
  `ID` bigint(20) NOT NULL DEFAULT -1,
  `AllgAdrName1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `AllgAdrName2` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
...
  PRIMARY KEY (`ID`),
  KEY `K_AllgAdresse_Ort_FK` (`AllgAdrOrt_ID`),
  KEY `K_AllgAdresse_K_Adressart_FK` (`AdressArt_ID`),
  CONSTRAINT `K_AllgAdresse_K_Adressart_FK` FOREIGN KEY (`AdressArt_ID`) REFERENCES `k_adressart` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `K_AllgAdresse_Ort_FK` FOREIGN KEY (`AllgAdrOrt_ID`) REFERENCES `k_ort` (`ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

**Comment by FPfotenhauer** [comment]
Wie gesagt: Es spricht auch nichts gegen eine CI Collation, nur sollte sich die Client-Anwendung darum kümmern.

**Comment by FPfotenhauer** [comment]
Ich gehe jetzt davon aus, das Schild3 nach und nach an die gewünschte Collation angepasst wird.
Das muss ja nicht sofort erfolgen und nur an den wichtigsten Stellen.
In Zukunft sollen Applikationen so oder so nicht mehr auf die Datenbank zugreifen können und nur noch über die API gehen.

**Comment by JuergenRichter** [comment]
Für die Betriebe ist das umgesetzt, werde das auch noch für die SuS und die Lehrkräfte machen.
