### ISSUE TITLE
Lehrerverwaltung - Keine LBV-Nummer und Vergütungsschlüssel mehr vorhanden

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#318]
## SchILDversion: 3.0.39.7

1. Ich kann das Feld LBV-Nummer nicht mehr in der Verwaltung der Lehrer finden.
2. In 2.0 gibt es auch noch das Feld Vergütungsschlüssel.
3. Den Reiter Einwilligungen scheint es in 3.0 nicht mehr zu geben
![grafik](https://user-images.githubusercontent.com/44644567/181086138-ef8f4d30-d65c-4450-948f-a47b9bb19f43.png)
4. Eine Erweiterung um die Felder Diensttelefon (mobil oder Festnetz(i.d.Schule für Sekretärinnen (evtl. Fax)) wünsche ich mir
5. Es wird ein komischer Strich dargestellt bei den schulbezogenen Daten.
Das passiert wenn man die Unterbereiche Allge. Daten/Lehrämter .. größer und kleiner macht.
![grafik](https://user-images.githubusercontent.com/44644567/181087025-de47c449-5693-4010-9c09-cfcbd8edefe9.png)

**Comment by JuergenRichter** [comment]
Behoben
