### ISSUE TITLE
Spaltenbreite einstellen im Reiter Übersicht unter Schüler ist eigenwillig

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#319]
## SchILDversion: 3.0.39.7

Die Spalten im Reiter Übersicht für die Noten eines Schülers ist sehr zufällig.
Stellt man die Breite der Spalte 1 ein und wiederholt das für andere Spalten
ändern sich die Spaltenbreiten beliebig.

Hier wäre es wünschenswert das alle Breiten gemeinsam verstellt werden könnnen bzw
das die optimale Breite automatisch eingestellt wird.

Habe das jetzt zufällig herausgefunden, das man mit Klick auf eine Spalte, diese Breite auf alle Spalten überträgt.
Das ist nicht intuitiv. Dann kann man doch gleich alle Spalten in der Breite gleichzeitig ändern.

Die Darstellung ist in 2.0 deutlich besser gelungen. Dort wird zentriert etc. Bitte mal vergleichen.

**Comment by AnneSchueller** [comment]
Dem stimme ich zu. Der Trick mit dem Doppelklick funktioniert auch in Schild2. Vielleicht kann man hierzu einen Hinweis notieren oder alternativ die Möglichkeit anbieten die Spalten simultan zu verändern.

**Comment by JuergenRichter** [comment]
Hinweis wir nun angezeigt.
