### ISSUE TITLE
Datensicherung

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#32]
Jetzt kann ich diese DB nicht sichern. 😄
![grafik](https://user-images.githubusercontent.com/73750717/101078139-06365780-35a6-11eb-9e30-f69dc8a4a8cb.png)

**Comment by FPfotenhauer** [comment]
Die Funktion ist noch im "Access-Modus".

Hier muss auf den Service "migrateToSqlite" umgestellt werden.

**Comment by JuergenRichter** [comment]
Die Datensicherung ist erst mal deaktiviert (Menüpunkt nicht sichtbar)
