### ISSUE TITLE
Reiter Abitur bei Schülern - keine Anzeige wegen fehlerhafter Query

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#320]
## SchILDversion: 3.0.39.7

Die Daten im Reiter Abitur werden nicht angezeigt, da das Select dazu nicht in Ordnung ist: 
![grafik](https://user-images.githubusercontent.com/44644567/181089614-13a9b6c6-9f4c-4288-994f-96f74614e8a0.png)

**Comment by AnneSchueller** [comment]
Das kann ich nicht reproduzieren. Tritt der Fehler direkt auf, nachdem auf den Reiter "Abitur" gewechselt wird?

**Comment by EwaldReinhardt** [comment]
Ich habe mir D0x Schüler in den Container gefiltert (entsprechende Klasse). Nun auf den Reiter Abitur wechseln. Nichts passiert aber auch die Anzeige ist leer (obwohl die Export Schnittstelle SchILD-NRW Daten liefert) und die Datenbank die Daten enthält:
![grafik](https://user-images.githubusercontent.com/44644567/181511860-1a09c3bc-541f-429d-ae82-9886bfc827b1.png)
Wenn man jetzt bei aktiven Reiter Abitur den Schüler wechselt kommt die Fehlermeldung.

**Comment by AnneSchueller** [comment]
Vielen Dank für die Rückmeldung. Ich leite das Problem weiter. 
@JuergenRichter: Mit der Gymnasialdatenbank funktioniert der Reiter Abitur.

**Comment by JuergenRichter** [comment]
Behoben
