### ISSUE TITLE
Lernplattformen fehlen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#321]
Die Angabe der Lernplattformen fehlen noch 
- bei den Katalogen
- bei den Schülern im Reiter Einwilligungen
- bei den Lehrkräften 
- Exporten

**Comment by JuergenRichter** [comment]
Eintrag bei Katalogen ist umgesetzt, Rest wird zügig bearbeitet

**Comment by JuergenRichter** [comment]
Bis auf den Export sind Lernplattform-bezogenen Funktionen nun umgesetzt, Export kommt in Kürze.

**Comment by JuergenRichter** [comment]
Ist jetzt umgesetzt
