### ISSUE TITLE
Wechsel des Halbjahres unter akt. Halbjahr reagiert nicht bei ...

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#322]
Die Anzeige im rechten Bereich wird nicht aktualisiert, wenn das Halbjahr mit Klick auf die Pfeile gewechselt wird.
![grafik](https://user-images.githubusercontent.com/44644567/181517333-9b59f60f-fcb2-4569-a07c-800a22f5681d.png)
Das funktioniert nur, wenn auf den Abschnitt geklickt wird.

**Comment by JuergenRichter** [comment]
Behoben
