### ISSUE TITLE
Schülerauswahl mit verschiedenen Unschönheiten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#323]
Ich finde die Auswahl in Schild2.0 deutlich einfacher und schneller.
Doch folgendes ist mir aufgefallen:

1. DIe Auswahl muss erst aktualisiert werden, wenn das Fenster verlassen wird. Man sieht die angezeigten Schüler ja nicht.
Es wird auch aktualisiert, obwohl nichts geändert ist: Zeile Klasse anwählen, dann auf den Namen einer Klasse klicken (führt nicht zur Auswahl der Klasse s. 4.) führt zur Aktualisierung der ausgewählten Schüler.
2. Es erscheint (Vorher einmal auf einen Klassennamen klicken) bei Auswahl der Zeile Klasse ein Eingabefeld, das nur den Nutzen hat, dass die Klassen in Fett dargestellt werden, wenn dort was eingetragen wird.
![grafik](https://user-images.githubusercontent.com/44644567/181521580-281608ab-943f-4c69-b66d-69e13f0f4344.png)
3. Es ist sehr Umständlich eine Klasse zu wechseln, da auch immer die alte Klasse erst abgewählt werden muss. Bei mehreren Klassen ist das nicht schön. Früher konnte man einfach mit der Tastatur ITA9* tippen. Es wäre schön wenn das Eingabefeld unter 1 das umsetzen würde. Wenn hier z.B. GOST9*,ITA9* eingetragen wird, werden alle Klassen abgewählt und die Klassen GOST91, GOST92 und ITA91 und ITA92 angewählt, wenn das Fenster verlassen wird.
![grafik](https://user-images.githubusercontent.com/44644567/181530332-fe83b342-f63d-4f96-9409-5f2af9dc5a1a.png)

4. Wenn die Maus über eine Klasse bewegt wird, wird das Kästchen hervorgehoben, aber beim Klick wird der Zustand des Kästchens nicht gewechselt. Man muss unbedingt auf das kleine Kästchen klicken. 
-> Zustandwechsel auch bei Klick auf den Klassennamen.
5. Dann ist folgendes bei den Screenshots mit Greenshot aufgefallen:
Wenn die Bildschirmaufnahme mit **Escape** abgebrochen wird, dann ändert sich die Darstellung gegenüber dem Screenshot unter 3. so:
![grafik](https://user-images.githubusercontent.com/44644567/181532928-696afd90-5996-4baf-9e23-17003daf18f0.png)
Die Klasse BFS1 ist noch angehakt aber oben neben dem Filtersymbol verschwunden. Die Schülerauswahl ist noch nicht aktualisiert. Beim Schuss des Bildes hier unter 5. wurde dann die Auswahl aktualisert und auch der Haken bei BFS weggenommen obwohl das nie angeklickt wurde.
Wieso interagiert das so mit anderen Programmen?
6. Verbesserungsvorschlag:
Man könnte bei der Erzeugung der Klassenliste auch abfragen welche verschiedenen Stati die Schüler in der Klasse haben und das hinter der Klasse angeben. (NWABXSE) Das hilft zu erkennen, ob Schüler fehlen in einer Klassenliste, da die Karteikästen nicht aktiv sind)

**Comment by FPfotenhauer** [comment]
Man kann in den Einstellungen auch auf die "alte Variante" umstellen.

**Comment by Kluesenerm** [comment]
Die alte Variante würde ich auf Standard stellen und die neue als Option. Das Vereinfacht massiv den Umstieg.

**Comment by JuergenRichter** [comment]
Sehen das alle so? Dann können wir das so umsetzen?

**Comment by AnneSchueller** [comment]
Ich persönlich habe mich an die alten Eingabe sehr gewöhnt und meine, dass man hier schneller filtert.
Daher gerne die alte als Standard von meiner Seite aus.
Die neue Variante hat dagegen den Vorteil, dass man mehrere Klassen/Jahrgänge per Maus auswählen kann. Das bemängeln aktuell schonmal Schulen bei Schild2.

**Comment by EwaldReinhardt** [comment]
Die alte Auswahl als Standard setzen ist für den Umstieg sicherlich besser.
Die neue ist im derzeitigen Zustand sehr langsam (wegen der Aktualisierung
nach jedem Klick) und für ein BK mit 150 Klassen ist die Tastatur schneller als 
Häkchen in einer langen Liste zu setzen.
Viele Schulen kennen auch nicht die Möglichkeit in Schild2, dass mehrere Klassen
mit * oder einer Liste angegeben werden können.
Vielleicht könnte man auch eine Eingabe 
08*,09*,10a,11a
=> 
where Klasse IN ('10a','11a') OR Klasse like '08*' OR Klasse like '09*'
übersetzen.

**Comment by JuergenRichter** [comment]
Altes Verfahren ist jetzt bei Neuinstallation der Default.
