### ISSUE TITLE
Neue Klasse anlegen im Katalog Klassen/Versetzungstabelle funktioniert nicht

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#324]
# nicht eingebbare Angabe fehlt:
Die verlangte ID kann im Dialog nicht eingegeben werden.
![grafik](https://user-images.githubusercontent.com/44644567/181573207-bdfa6446-8c37-43f5-ac69-906f8dbb625f.png)
# Jahrgänge bitte sortieren:
![grafik](https://user-images.githubusercontent.com/44644567/181574033-c5e4dc27-71a3-4d9d-ab08-bd90aa760605.png)
# Fehler kommt wenn der Screenshot mit Greenshot gemacht wird 
(Exception-Doku angehängt)
![grafik](https://user-images.githubusercontent.com/44644567/181573493-2a705a4a-e36f-43e4-9878-10e3fce12310.png)
[Schild3Exception.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9211983/Schild3Exception.txt)

**Comment by AnneSchueller** [comment]
Zur Sortierung der Jahrgänge: Bleibt die Sortierung so "ungeordnet" wenn im Reiter Kataloge->Statistik-Jahrgänge die Sortierung der Jahrgänge umgestellt wird?
Das Problem mit der Schuljahresabschnitts_ID habe ich auch

**Comment by EwaldReinhardt** [comment]
Die Sortierung der Jahrgänge ändert sich mit der Umstellung der Sortierung im Katalog.
In Schild2.0 war es allerdings so, dass hier automatisch auf ein Art sortiert wurde, die jetzt nicht mehr einstellbar ist.
Es wurde nach Jahrgängen,Gliederung sortiert (keine Umstellung möglich in 2.0)
![grafik](https://user-images.githubusercontent.com/44644567/181716330-15386bca-26a1-4f28-901e-ca6bcecec7ae.png)

**Comment by EwaldReinhardt** [comment]
Der Fehler mit dem ungültigen Integerwert kommt auch, wenn das Dropdown für den Jahrgang geöffnet wird und dann in das leere Feld geklickt wird, sodass kein Wert ausgewählt ist.

**Comment by JuergenRichter** [comment]
Der Fehler mit dem fehlenden Feld "Schuljahresabschnitts_ID" ist behoben. Jahrgangsliste jetzt bei der Klassenbearbeitung wird jetzt nach Gliederung und interner Bezeichnung sortiert.
