### ISSUE TITLE
Lernabschnitt ergänzen funktioniert nicht

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#325]
Ich wollte einer Problematik nachgehen, die in SchILDzentral vorhanden ist:
Ich musste für einen Schüler der Technikerschule, der den Bildungsgang für 3 Jahre unterbrochen hatte, Halbjahre ergänzen, da diese Halbjahre bei der Migration von Magellan nicht erfasst wurden. Es waren die Schuljahre 2014/15 bis 2016/17.
Hier wurden die im Dialog eingetragenen Daten für Statistikjahrgang nicht übernommen, sondern der Wert aus der Tabelle Klassen/Versetzungstabelle verwendet. 

Dabei ist folgender Fehler aufgetreten:
![grafik](https://user-images.githubusercontent.com/44644567/181576876-2c652cb7-7ba8-4e59-8555-e9092cbb6eb2.png)
![grafik](https://user-images.githubusercontent.com/44644567/181577175-c7fed5fb-4e5e-4238-b58c-3036cfad6dc9.png)

# welche Jahrgänge werden angeboten
Außerdem hätte ich die Abschnitte gar nicht ergänzen können, da die Schuljahre nicht angeboten wurden:
In SchILDzentral war das möglich.
![grafik](https://user-images.githubusercontent.com/44644567/181577772-fde032ba-14b5-4395-9926-c1be0b240f56.png)

**Comment by FPfotenhauer** [comment]
Ich bin mir nicht sicher, warum das Issue mir zugewiesen wurde.

**Comment by AnneSchueller** [comment]
Zitat: "Außerdem hätte ich die Abschnitte gar nicht ergänzen können, da die Schuljahre nicht angeboten wurden:"
Liegt das nicht an der Migration?

**Comment by FPfotenhauer** [comment]
Gab es diese Abschnitte denn in der Datenbank?

**Comment by EwaldReinhardt** [comment]
Nein, diese Abschnitte gab es nicht. 


Am 2. Aug. 2022, 11:00, um 11:00, Frank Pfotenhauer ***@***.***> schrieb:
>Gab es diese Abschnitte denn in der Datenbank?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/SVWS-NRW/Schild3-BetaTest/issues/325#issuecomment-1202213359
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by JuergenRichter** [comment]
Ein neuer Lernabschnitt lässt sich nun auch individuell bei den SuS anlegen, dabei stehen aber derzeit nur die vorhandenen "Schuljahresabschnitte" (in gleichnamiger Tabelle) zur Verfügung. Die Frage ist nun, ob die Möglichkeit geschaffen werden soll, neue Schuljahresabschnitte beliebig anzulegen zu können. Derzeit wird ein neuer Datensatz automatisch beim Schuljahres- oder Halbjahreswechsel erzeugt, also immer "in die Zukunft".

**Comment by FPfotenhauer** [comment]
Gab es denn diesen Abschnitt noch gar nicht in der DB?
Dann ist das doch eher ein Mega Sonderfall.
Schüler können eigentlich keinen Abschnitt haben, den die gesamte Schule noch nicht erlebt hat.

**Comment by EwaldReinhardt** [comment]
Ja, das ist ein Sonderfall. WIr hatten ja zum 2.HJ 20/21 umgestellt von Magellan auf Schild.
Wir haben nur die Daten der Schüler migriert, die im 1.HJ 20/21 Schüler waren inkl. der Historie.
Da war er nicht dabei. Für einen kompletten Personalbogen mit allen Laufbahndaten hatte ich
das dann in SchILDzentral ergänzt. (s.o.).

## Dialog nach Klassenwahl füllen:
Ich glaube ich bin darüber gestolpert, dass der Dialog den eingetragenen Jahrgang überschreibt, wenn
die Klasse ausgewählt wird. Den Eintrag hatte ich aber vorher ausgewählt, da er oberhalb steht.
Dagegen werden die darunter liegenden Felder, die auch über die Klasse definiert sind nicht ausgefüllt.

Schön wäre Schuljahr und Klasse auswählen zu können und das die Felder dann entsprechend vorbelegt
werden, die unterhalb stehen.

Hinweis:
Wir, wie auch andere Schulen, halten den Klassennamen über den ganzen Bildungsgang, so dass eine Klassenbezeichnung verschiedene Jahrgänge haben kann. 

![grafik](https://user-images.githubusercontent.com/44644567/182409477-26b2e96d-bc2d-4066-9450-4cc40bac8a03.png)

**Comment by EwaldReinhardt** [comment]
ich vergaß einzufügen:
Man könnte auch den Wert aus den Einstellungen verwenden:
![grafik](https://user-images.githubusercontent.com/44644567/182410040-3fa389e9-2d4a-403c-b983-4b616a2ea5eb.png)

**Comment by JuergenRichter** [comment]
Dieses Feld ist m.E. nun überflüssig, ich werde es rausnehmen

**Comment by JuergenRichter** [comment]
"Schön wäre Schuljahr und Klasse auswählen zu können und dass die Felder dann entsprechend vorbelegt
werden, die unterhalb stehen."
Ist jetzt so umgesetzt
