### ISSUE TITLE
Request Prüfungsordnungen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#326]
Die Prüfungsordnung ergibt sich meiner Kenntnis nach aus dem Bildungsgang und dessen Beginn, den ein Schüler am BK belegt.
Daher sollte die Zuordnung einer PO im Lernabschnitt nícht erforderlich sein, wenn dem Bildungsgang die Prüfungsordnung schon
in der hinterlegten Datenbank zugeordnet ist. (Das dürfte für den Anwender gar nicht erforderlich sein). 
Diese interne Zuordnung ist ohne Jahrgang der PO. Im Beispiel Berufl. Gymn. also nur APO-BK-**/D-BAB
![grafik](https://user-images.githubusercontent.com/44644567/181580303-911b3179-e179-4326-8281-33860f7cf6be.png)

Man sieht ja schon an dem Bild, dass Schild automatisch die PO filtert bis aus das Jahr.

**Comment by FPfotenhauer** [comment]
Das wird der SVWS-Server tatsächlich können.
Eine Änderung in Schild-NRW ist nicht geplant.
