### ISSUE TITLE
Einstellungen: interne Texte darf nicht leer bleiben

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#327]
Unter Einstellungen  auf den Bereich interne Texte wechseln 
und dann auf einen anderen Bereich.
![grafik](https://user-images.githubusercontent.com/44644567/181704183-d868ba46-ce3b-4968-8aee-37bef4cba011.png)

Dann wird dieser Fehler angezeigt.
![grafik](https://user-images.githubusercontent.com/44644567/181704071-eeeb61f6-0427-469b-9443-b882d95af94f.png)

Wenn dann auf Ja geklickt wird bei Auswahl eines anderen Bereichs rechts auch nicht mehr aktualisiert und der Curser bleibt im
Feld Emailversand stehen.:
![grafik](https://user-images.githubusercontent.com/44644567/181704825-5778f7ff-f27b-4011-8f06-4c4c2b7e9bd3.png)

**Comment by KayBerger** [comment]
- Bei Verneinung wird der Dialog weitere 2x angezeigt.
- Für Laien ist die Angabe Text_Body unverständlich

**Comment by JuergenRichter** [comment]
Behoben
