### ISSUE TITLE
Passwort ändern nicht möglich

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#328]
## Version 3.0.93.7

Unter Einstellungen/Benutzer/Kennwort ändern kann das Passwort nicht geändert werden.
Das alte Kennwort wird erkannt -> Haken wird grün.

![grafik](https://user-images.githubusercontent.com/44644567/182422327-37930a2c-771d-4875-a73c-9893e43b742e.png)

Aber nach dem Klick auf OK kommt ein unspezifischer Hinweis, das was nicht geklappt hat.
Schön wäre eine detailiertere Fehlermeldung.
Kennwörter nicht identisch / zu kurz / zu lang / zu einfach etc.

![grafik](https://user-images.githubusercontent.com/44644567/182422216-e4ee0372-89d7-4603-b37a-d3bd47bec143.png)
Das gleiche Passwort kann ohne Probleme in der Benutzerverwaltung gesetzt werden.

**Comment by JuergenRichter** [comment]
Behoben
