### ISSUE TITLE
Statistik für IT.NRW/Gesamtprüfung der Daten : Fehlerhafte Abfrage

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#329]
### Version 3.0.39.7
Die Gesamtprüfung kann nicht gestartet werden:

![grafik](https://user-images.githubusercontent.com/44644567/182662674-b8f426eb-a52b-4fa3-87d7-6c113aa21d63.png)

Fehlerbericht:
[Gesamtprüfung.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9253479/Gesamtprufung.txt)

Wenn der obige Dialog weggeklickt wird, bleibt diese Box stehen:
![grafik](https://user-images.githubusercontent.com/44644567/182665111-8e58b3ba-487d-4d0e-a14b-c5710290a408.png)

Hier kann man zwar auf Abbrechen klicken, geschlossen wird die Box aber nur, wenn ober rechts
das rote Kreuz geklick wird.

### Der gleiche Fehler tritt auch beim Unterpunkt _**Daten exportieren**_ auf.

Anschließend, wenn das Programm beendet wird, kommt noch folgender Fehler:
![grafik](https://user-images.githubusercontent.com/44644567/182688361-7af0388b-ca8f-434d-9e09-cb6a3a1f1d8e.png)
(Hatte vorher Daten exportieren versucht aufzurufen mit dem Fehler oben)
[BeendenNachDatenExportieren.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9254298/BeendenNachDatenExportieren.txt)

**Comment by FPfotenhauer** [comment]
Um die Statistik kümmern wir uns etwas später, das ist noch nicht angepasst.
Ich schließe des Issue mal und eröffne ein neues, wenn daran gearbeitet wird.
