### ISSUE TITLE
FHR-Karteikarte und Abitur-Karteikarte

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#33]
Zur gleichartigen Bedienung der Vorgänge sollten die Fenster einheitlich sein und eine einheitliche Bedienoberfläche haben. Im Moment sind diese in FHR und Abitur unterschiedlich (siehe Bilder).

![FHR-Karteikarte](https://user-images.githubusercontent.com/62895389/101158605-4809e100-362c-11eb-90c1-e8dd8d79d5e6.JPG)
![Abitur-Karteikarte](https://user-images.githubusercontent.com/62895389/101158612-4b9d6800-362c-11eb-9c23-4b3d63c9bf1a.JPG)

**Comment by Kluesenerm** [comment]
Bei mir sieht das Layout anders aus. Bei mehreren Kursen würden nicht mehr alle Kurse gleichzeitig angezeigt. Sehr ungünstig. (Skalierung 120%)
![image](https://user-images.githubusercontent.com/75179015/101246756-9646df00-3715-11eb-9f16-7f4770f0888b.png)

**Comment by FPfotenhauer** [comment]
Das ist aber nicht die letzte Version 3.0.6.

**Comment by Kluesenerm** [comment]
Stimmt. Sorry! Aber jetzt sind die Ergebnisse in der Gesamtschau nicht sichtbar. Ich muss scrollen. Kann das Feld nicht nach rechts vergrößert werden? So ist es ganz ungünstig.
![image](https://user-images.githubusercontent.com/75179015/101259187-a4056000-3727-11eb-9ebd-3ddb1d38afb6.png)

**Comment by WLey-49** [comment]
In der version 3.0.7.1 ist an der menüdarstellung etwas geändert worden. Das FHR-Menü ist ungünstig angelegt. Man muss zur Auswahl eines Punktes immer zweimal klicken. Es sollt so wie das Abiturmenü sein (siehe Bilder).

Hier erster Klick:
![FHR-Menü-1](https://user-images.githubusercontent.com/62895389/101656555-22714300-3a43-11eb-9577-f828443e9b3b.JPG)
Hier zweiter Klick:
![FHR-Menü-2](https://user-images.githubusercontent.com/62895389/101656577-27ce8d80-3a43-11eb-9a9a-705218eeb830.JPG)
Hier reicht ein Klick:
![Abi-Menü](https://user-images.githubusercontent.com/62895389/101656588-2b621480-3a43-11eb-9b9e-c31684bb305a.JPG)

**Comment by Kluesenerm** [comment]
Die Karteikarte Abiturberechnung bleibt bei mir stehen, wenn diese einmal angewählt wurde. Der Karteireiter FHR ist bei mir (WBK) leer. (Schild 3.0.7.1)

**Comment by JuergenRichter** [comment]
Das Layout alle "RibbonGroups" für die verschiedenene Abschlussberechnungen ist in der Folgeversion 3.0.8 vereinheitlicht.

**Comment by WLey-49** [comment]
Könnte diese Version 3.0.8 für uns zum Testen bereitgestellt werden?

**Comment by JuergenRichter** [comment]
Kommt heute
