### ISSUE TITLE
Migration: manche Einstellungen werden nicht übernommen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#330]
### Version 3.0.39.7

Die folgenden Programm-Einstellungen werden bei der Migration nicht übernommen:
(Ich vermute, dass nur die Standardeinstellungen eingetragen sind.)
Es wäre aber schön, wenn die Einstellungen möglichst komplett übernommen werden könnten.
Habe trotzdem die Unterschiede aufgezeigt.

#### Unterschiede im Bereich Ansicht:
![grafik](https://user-images.githubusercontent.com/44644567/182695893-906caf7b-ff0f-409e-a9af-d2dfb74fd5c2.png)

#### Unterschiede im Bereich Wiedervorlage:
![grafik](https://user-images.githubusercontent.com/44644567/182696299-472b83ff-ef08-4791-8126-89eece650478.png)

#### Unterschied im Bereich Fächer, Noten:
![grafik](https://user-images.githubusercontent.com/44644567/182696766-24f97761-1d14-4226-bc39-813f6948123b.png)

#### Unterschied im Bereich Dokumentenverwaltung
![grafik](https://user-images.githubusercontent.com/44644567/182697056-f3caff2e-f54f-41fb-a879-f5cf8cde0b44.png)

#### Unterschied im Bereich Reporteinstellungen:
![grafik](https://user-images.githubusercontent.com/44644567/182697616-e3046562-825e-4be4-91a8-8cf8cb4d3b18.png)

**Comment by FPfotenhauer** [comment]
So weit ich das sehen kann, migrieren wir die Einstellungen aus der Tabelle EigeneSchule.
Wie das dann in Schild3 ausgewertet wird, kann ich nicht sagen.

**Comment by EwaldReinhardt** [comment]
Ich habe gerade nochmal neu migriert. 
Wenn die Tabellen 
![grafik](https://user-images.githubusercontent.com/44644567/182839238-73b0fb40-b006-47f2-a7b7-3abe0396ac01.png)
sind, dann wird leider keine der Einstellungen migriert.

![grafik](https://user-images.githubusercontent.com/44644567/182839554-ac3aa235-2161-44a1-9f3f-aa8d1b70e261.png)

![grafik](https://user-images.githubusercontent.com/44644567/182839450-a1ba5c8b-060e-45b1-950f-aad5c2220ddc.png)

**Comment by FPfotenhauer** [comment]
Die Tabellen sind für den SVWS-Client.
Könnten aber auch von Schild3 genutzt werden, was momentan noch nicht der Fall ist.
Die Einstellungen sind momentan in EigeneSchule > Einstellungen.

**Comment by JuergenRichter** [comment]
In SchILD werden benutzer-bezogenen Einstellungen in svws_client_konfiguration_benutzer gespeichert

**Comment by FPfotenhauer** [comment]
Ich stehe auf dem Standpunkt, dass man die Eintsellungen in Schild3 einmal neu setzen muss.

**Comment by FPfotenhauer** [comment]
Es wird nötig sein, die Einstellungen neu zu setzen.
Alles andere ist zu fehleranfällig.
