### ISSUE TITLE
Wo werden die Reportverzeichnisse eingegeben?

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#331]
Ich konnte unter den Einstellungen keine Möglichkeit finden die Reportverzeichnisse
anzugeben.
Ich nutze nicht die Standard-Verzeichnisstruktur, da ich für Berichtsköpfe und -füße das
gleiche Verzeichnis verwende wie bei nachladbaren Subreports. Teilweise muss man 
sonst gleiche Köpfe mehrfach ablegen, da sie einmal im Kopf oder Fuß und das andere Mal
im Gruppenkopf verwendet werden. 

Fehlt der Dialog aus 2.0 noch?
![grafik](https://user-images.githubusercontent.com/44644567/182703114-7fe8e50b-f2cd-4319-8974-e567a4902b70.png)

**Comment by JuergenRichter** [comment]
Die Einstellungsoptionen gibt es nicht mehr. Es wird nun eine Standardverzeichnisstruktur verwendet. In SchILD2 wird aber schon seit längerer Zeit nachladbaren Subreports wie folgt vorgegangen
Köpfe/Füße: Es wird zuerst im Header_Footer-Verzeichnis nachgesehen, wenn der Subreport da nicht gefunden wird, wird im Subreports-Verzeichnis gesucht
Subreports: Umgekehrte Suchreihenfolge
Ich muss mal prüfen, ob das auch schon in SchILD3 so umgesetzt ist.

**Comment by JuergenRichter** [comment]
Sollte auch in SchILD3 so funktionieren

**Comment by EwaldReinhardt** [comment]
Im Reportexplorer ist es wohl so, dass der komplette absolute Pfad abgelegt wird, wenn ich nicht aus dem Standardverzeichnis
den Report auswähle:

**Comment by JuergenRichter** [comment]
Die Subreports werden vom Reportbuilde immer mit absoluten Pfaden gespeichrt, das zu ändern, würde Eingriffe in den Quellcode bedeuten, was wir nicht wollen. Ich habe aber die (eigene) Routine, die das Laden der nachladbaren Subreports regelt, nun so angpasst, dass Subreports, die im Kopf-/Fußbereich liegen (und normalerweise im Ordner "Header_Footer" gespeichert werden) und "andere" Subreports (die normalerweise im Ordner "Subreports" liegen), so wie beschrieben behandelt werden:
Köpfe/Füße werden zuerst im Ordner "Header_Footer" gesucht, wenn sie da nicht gefunden werden, wird in "Subreports" gesucht, bei "anderen" Subreports ist es umgekehrt. Im Prinzip wird dabei der absolute Pfad in einen realtiven Pfad umgesetzt. Kappt bei mir einwandfrei, kann ich beim Fachberatertreffen demonstrieren.

**Comment by EwaldReinhardt** [comment]
Ich habe das nachgeschaut. In der RTM-Datei wird der Pfad zum dynamischen Report nicht absolut abgelegt:
![grafik](https://user-images.githubusercontent.com/44644567/183465480-d09901ed-5e75-4bf2-938a-ee4c4272bade.png)

Und das ganze verhält sich wie oben beschrieben. Wir können das gerne in 14 Tagen besprechen.

**Comment by JuergenRichter** [comment]
Ich habe hier ein Beisspiel, wo der Pfad in der rtm-Datei absolut drin steht:

object myDynamicLoadingSubRepOrt2: TmyDynamicLoadingSubRepOrt
      DesignLayer = ppDesignLayer1
      UserName = 'DynamicLoadingSubRepOrt2'
      ExpandAll = False
      NewPrintJob = False
      OutlineSettings.CreateNode = True
      TraverseAllData = False
      FileName = 
        'D:\SVWS-Arbeitsverzeichnis\Schild-Reports\Subreports\Subreport_T' +
        'est.rtm'
      mmHeight = 5027
