### ISSUE TITLE
Anzeige der Schülerinfos unterhalb der Reiter bei den Schülerdaten mal da mal weg

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#332]
### Version 3.0.39.7

Der Bereich aktueller Schüler wird mal angezeigt mal nicht.
![grafik](https://user-images.githubusercontent.com/44644567/182816132-37b7fe46-840e-443a-9aa4-e486363a5904.png)

Ich habe mal ein kurzes Video dazu gedreht, da Erklärungen und nachmachen sonst schwierig wird.
Die Anzeige des Videos im Browser funktioniert nicht, es ist nur der Ton zu hören?
Im Firefox kann man es auch nicht herunterladen, in chrome schon. 

https://user-images.githubusercontent.com/44644567/182830106-120cf097-4e00-4a1b-9242-846cf2d0994b.mp4

Hier nochmal zur Sicherheit als ZIP:
[VerhaltenBildanzeige.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9259031/VerhaltenBildanzeige.zip)

**Comment by AnneSchueller** [comment]
Mit der Zip-Datei funktioniert der Download...
Wenn ich das richtig im Video erkenne, wird die Ansicht "aktueller Schüler" nicht richtig angezeigt, sobald man die Fenstergröße von Schild verändert. Es liegt nicht an den Fotos; Auch ohne Fotos kann ich das reproduzieren, wenn ich die Fentergröße von Schild maximiere.

**Comment by FrodBRA** [comment]
@AnneSchueller 

Ist das Issue noch aktuell? Ich konnte "Aktueller Schüler" in den ID-I und ID-II nicht verschwinden lassen (3.0.71.9). In allen Reitern wird "Aktueller Schüler" nicht angezeigt.

**Comment by AnneSchueller** [comment]
Ich kann das immer noch reproduzieren, 
Erst auf Individualdaten I klicken.
Dann das Fenster von der Höhe her verkleinern.
Dann auf Individualdaten II und das Fenster zu "aktueller Schüler" verschwindet.

Gleichzeitig rutscht das Fenster "weitere Angaben" nach unten:

![2023-08-21_233259](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/2ed14da1-343e-4d25-93d5-bd8e8d7c6d4c)

Manchmal siehts auch so aus:
![2023-08-21_233603](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/44b06ffd-d8e1-448e-89ad-253a4c0ee967)



Wenn man das Fenster wieder größer zieht und anschließend den Reiter wechselt ist alles wieder richtig.

Die Frage wäre, ob man das nicht auch als Anwendungsfehler  sehen kann? Wir fordern ja nicht umsonst eine bestimmte Monitorgröße.

**Comment by AnneSchueller** [comment]
Ich schließe das Issue mal.
Wenn der User das Fenster zu klein macht, verschwinden die Schülerfotos. Macht er es wieder größer, sind sie wieder da.

**Comment by JuergenRichter** [comment]
Ich prüfe das trotzdem mal

**Comment by EwaldReinhardt** [comment]
Das Foto verschwindet erst, wenn der Reiter gewechselt wird.
Wird das Fenster erst kleiner gezogen, bleibt das Foto sichtbar auch bei Schülerwechsel.
Wechselt man den Reiter z.B. auf Individual II wird der Infobereich zum Schüler nicht mehr dargestellt
bis das Fenster größer gezogen wurde und der Reiter gewechselt wurde.

**Comment by AnneSchueller** [comment]
aber es taucht ja wieder auf, wenn man das Fenster größer macht und den Reiter wechselt.
