### ISSUE TITLE
ReportExplorer/Bericht/Gruppen -> Exception beim Scrollen des Gruppierungsfeldes

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#335]
### Version 3.0.39.7

Wenn in dem unten dargestellten Dropdown-Element mit dem Mausrad gescrollt wird, gibt es eine Ausnahme:
![grafik](https://user-images.githubusercontent.com/44644567/182876506-2765fa2f-dc90-459b-9219-7d07a3c5053e.png)

Das Scrollen mit Klicks auf den Scrollbalken funktioniert.

![grafik](https://user-images.githubusercontent.com/44644567/182876074-b1099387-32ac-4d6d-94a5-b2997194da93.png)

Exception-Infos:
[ReportexplorerGruppen.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9260694/ReportexplorerGruppen.txt)

**Comment by JuergenRichter** [comment]
Kann ich reproduzieren, ist aber tief im Programmcode des Reportexplorers drin. Wir werden demnächst die Version 21instllieren, vieleicht ist das Problem da behoben.

**Comment by FrodBRA** [comment]
3.0.71.9

Der Absturz des Fensters beim Scrollen im Menü tritt noch immer auf.

SchILD3 stürzt nicht ab, nach der Zugriffsverletzung beendet sich lediglich das Fenster "Bericht".

**Comment by AnneSchueller** [comment]
@JuergenRichter  Kann man da was gegen machen?

[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12402790/SchILD30.txt)

**Comment by AnneSchueller** [comment]
Funktioniert jetzt
