### ISSUE TITLE
Test SVWS-Server 0.2.12 mit SchILD3.0 0.0.43 - Test 1: neues Schema

### ISSUE THREAD

**Issue by GerhardHordt** [SVWS-NRW/Schild3-BetaTest#336]
Beim Start konnte keine Schule eingerichtet werden.

![capture_001_09082022_181754](https://user-images.githubusercontent.com/81526810/183710958-be9476de-e54d-4a39-b186-beb6ce63bfd0.jpg)

Nach dem Abbruch erschien diese kuriose Darstellung:
![capture_002_09082022_181843](https://user-images.githubusercontent.com/81526810/183711343-bbc65f56-00ce-438b-b320-121105a4db08.jpg)

**Comment by JuergenRichter** [comment]
Enthält das Schema Daten? Oder anders gefragt: Wurde eine Migtation durchgeführt?
Bitte auch mal das Fehlerprotokoll anhängen ("Copy to clipboard" aktivieren, "Details" anklicken, dabei wird Protokoll in Zwischenablage kopiert, Inhalt derselben in Datei speichern, Datei hier hochladen).

**Comment by GerhardHordt** [comment]
Das Schema enthält keine Daten, da keine Migration durchgeführt wurde. Hier ist die Protokolldatei:

[Protokoll.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9299970/Protokoll.txt)

**Comment by JuergenRichter** [comment]
Der Fehler wird behoben.
Aber: Wie sieht es dann mit einem Eintrag in der Tabelle "Schuljahresabschnitte" aus. Hier wird ja mindestens ein Eintrag benötigt. Es gibt folgende Optionen:

- Es wird ein Eintrag auf Basis des aktuellen Datums angelegt

- Es wird abgefragt, welcher der erste Eintrag in der Tabelle sein soll, die übrigen (bis zum aktuellen Schuljahr) werden automatisch angelegt

**Comment by GerhardHordt** [comment]
Eine Bearbeitung ist nicht möglich.

**Comment by JuergenRichter** [comment]
Das ist schon klar, dazu muss erste der beschriebene Fehler korrigiert werden.

**Comment by JuergenRichter** [comment]
Der Fehler bei Start mit einem leeren Schema ist nun behoben

**Comment by JuergenRichter** [comment]
Der Fehler bei Start mit einem leeren Schema ist nun behoben
