### ISSUE TITLE
Test SVWS-Server 0.2.12 mit SchILD3.0 0.0.43 - Test 2: Migration einer SchILD2.0-Datenbank. Zugriff über Localhost

### ISSUE THREAD

**Issue by GerhardHordt** [SVWS-NRW/Schild3-BetaTest#337]
Die Migration der Datenbank einer "echten" Schule (also keine Schulungsdatenbank) war erfolgreich: Der Zugriff über Localhost schien zunächst problemlos zu funktionieren:

![capture_003_09082022_183617](https://user-images.githubusercontent.com/81526810/183711975-3460baa7-4317-4c4e-b5e1-8f22772463b8.jpg)

Nach der Eingabe des Kennwortes sah es dann so aus:

![capture_004_09082022_184023](https://user-images.githubusercontent.com/81526810/183712147-b462dcd0-7323-448e-b0ad-d38eae2228a3.jpg)

![capture_005_09082022_184137](https://user-images.githubusercontent.com/81526810/183712215-8efdc085-b65a-4f6b-aca2-816342a22c98.jpg)

**Comment by FPfotenhauer** [comment]
Dazu kann man ohne die Datenbank zu sehen, schwer etwas sagen.
Hier soll auch nicht der WebClient getestet werden. Das ist ja noch eine sehr frühe Entwicklungsphase.
