### ISSUE TITLE
Schüler/Reports: Abschnittsauswahl einblenden

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#339]
### Schildversi:on 3.0.39.7

Im Bereich Schüler / Reports ist die Abschnittsauswahl nicht vorhanden. Die gibt es nur in der Reportverwaltung.
![grafik](https://user-images.githubusercontent.com/44644567/184472000-b39f0862-5e19-415c-97c7-fe46105be905.png)

![grafik](https://user-images.githubusercontent.com/44644567/184472096-3c8fb197-184a-4039-8f0b-84be45816708.png)
Wäre auch im Bereich Schüler hilfreich. Sichtbar, wenn die Reportübersicht angezeigt wird.

**Comment by FrodBRA** [comment]
3.0.71.9: Der Abschnitt wird bei mir angezeigt. 

Das Issue ist erledigt.

@AnneSchueller

**Comment by AnneSchueller** [comment]
Gemeint ist hier wahrscheinlich im Reiter Schüler die Auswahl zum "Drucken"?
Hier sollen ja nur Standard-Dokumente mal schnell gedruckt werden. Für spezielle Reports vorangegangener Abschnitte muss man dann halt in den Reiter "Reportverwaltung" wechseln.
