### ISSUE TITLE
Reihenfolge der Felder in den Basisdaten unlogisch

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#34]
Meineserachtens ist die Reihenfolge und Sortierung der Felder bei den Basisdaten unter Individual-Daten I unlogisch.
Logischer wäre:
Name, Vorname, Alle Vornamen, Geschlecht, Geburtsdatum, Geburtsort, Straße, PLZ, Ort, Ortsteil, Kreis und aus den Zusatzdaten Telefon, Fax, Schulinterne E-Mail-Adresse und private E-Mail-Adresse unter Basisdaten zusammenfassen.
Die Felder Status, Konfession und Staatsangehörigkeiten in die Zusatzdaten verschieben.
Bei einer derartigen Sortierung sind die Daten für den alltäglichen Gebrauch übersichtlich in den Basisdaten zusammendefasst.

**Comment by FPfotenhauer** [comment]
Ich würde auf jeden Fall das Feld Status in der Card"Basisdaten" ganz nach oben holen.
Außerdem würd eich die Sportbefreiung, Fahrschüler und Haltestelle etwas nach oben holen, so dass die Lücke bei der Telefonnummer entsteht.

Außerdem fehlt die Beschriftung der Schulischen Mailadresse.

**Comment by ADV-Fendel** [comment]
Wenn ich mir vorstelle, welche Daten im Alltag am Wichtigsten sind, so sind es doch neben Name, Geschlecht und Geburtsdatum die Adressdaten und die Erreichbarkeitsdatern (Telefon, e-Mail)
Ich finde, dass diese gut im Bereich Basisdaten zusammengefasst dargestellt werden könnten.
Das Feld Status ist für den Alltagsgebrauch nicht wichtig und könnte auch im Bereich Zusatzdaten an oberster Stelle untergebracht werden.

**Comment by Kluesenerm** [comment]
Auf jeden Fall ist der Status zwischen Geburtsname und Geburtsort unlogisch. Auch würde ich auf jeden Fall Straße, PLZ, Ort bevorzugen. Viele Schulen verwalten den Ortsteil und den Kreis nicht. Die Staatsangehörigkeiten gehören vor die Ortsangaben.
Kann das Feld Online-Anmeldung für alle Schulformen aktiviert werden (oder als Option)?

**Comment by WLey-49** [comment]
Bei Eingabe und Verlassen mit der TAB-Taste springt der Cursor (auch in Version 3.0.10.4) in völlig falscher Reihenfolge durch die Eingabefelder.

**Comment by ADV-Fendel** [comment]
Das Feld Status lässt sich nicht anwählen und steht immer noch an einer unlogischen Stelle der Basisdaten.

**Comment by JuergenRichter** [comment]
Die Anordnung der Felder wurde nochmals überarbeitet (auch die Tab-Reihenfolge), aktualisierte Version kommt in Kürze.

**Comment by ADV-Fendel** [comment]
Aus einer alltäglichen Sicht gehören für mich die Felder Telefon, Fax/mobil und emails zu den Basisdaten. In den meisten Fällen such ich danach, wenn ich den Schüler aufrufe. Die Felder Gebortsort, Konfession und Staatsangehörigkeit sind zweitrangig und könnten in den Bereich Zusatzdaten verschoben werden.

**Comment by WLey-49** [comment]
Die Tab-Reihenfolge auf den Individualseiten ist OK.
