### ISSUE TITLE
Drucken in das Zeugnisarchiv: Dateiname nicht korrekt

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#341]
## Aufbau der Dateinamen:
Der Aufbau der Dateinamen beim Druck in das Zeugnisarchiv enthalten in Schild3 nicht mehr das Geburtsdatum.
Und genau wie in Schild2 wird immer die aktuelle Klasse des Schülers in den Dateinamen codiert. Das ist aber nicht
sinnvoll, wenn aus einem früheren Abschnitt gedruckt wird. Es sollte immer die Klasse in den Dateinamen geschrieben werden,
die auch im Zeugnis aufgeführt ist. 

Es wäre auch schön, wenn der Aufbau des Dateinamens in den Einstellungen konfigurierbar wäre, wie beim Druck in die Dokumentenverwaltung.

Ein weiterer Wunsch wäre, dass es beim Druck auch die Option gibt, den Dateinamen zu konfigurieren:
![grafik](https://user-images.githubusercontent.com/44644567/184473031-dcad0399-e2e7-4f60-96cc-523829fc6e54.png)

**Comment by FrodBRA** [comment]
> Und genau wie in Schild2 wird immer die aktuelle Klasse des Schülers in den Dateinamen codiert. Das ist aber nicht sinnvoll, wenn aus einem früheren Abschnitt gedruckt wird. Es sollte immer die Klasse in den Dateinamen geschrieben werden, die auch im Zeugnis aufgeführt ist.

Ich hatte immer angenommen, dass das aufgrund der implizit beabsichtigten Verwendung des Verzeichnisses so ist: Das "Zeugnisverzeichnis" ist für Abschluss- und Abgangszeugnisse, enthält damit immer nur das letzte, höchste ausgestellte Zeugnis, dass dem Schüler beim Abgang von der Schule mitgegeben wird. Damit wäre eine explizitere Benennung nicht notwendig.

Die übrigen Zeugnisse landen im Dokumentenverzeichnis, wo sie dann auch nach Ablauf der allgemeinen Löschfrist rigoros zusammen mit der übrigen Schülerkarriere getilgt werden.

Wäre die Verwendung so beabsichtigt, macht die nicht-konfigurierbare Dateinamensgebung durchaus Sinn und ich würde das so lassen - nur deutlicher dokumentieren, was in welches Verzeichnis gehört.

Oder habe ich die Verwendung der Verzeichnisse überhaupt korrekt verstanden? Sofern "alle" Zeugnisse im "Zeugnisverzeichnis" landen sollen, müsste der Dateiname in der Tat ausdifferenziert werden können.

**Comment by JuergenRichter** [comment]
Die Ausgabe in das "Zeugnisverzeichnis"  war durch folgende Anforderung entstanden:
-Bei Grundschulen werden verstärkt Zeugnisse verwendet, die als "Broschürendruck" ausgegeben werden sollen (da u.U. viele Seiten, z.B. bei Ankreuzzeugnissen).
-Einen Broschürendruck unterstützt der ReportBuilder aber nicht (zumindst in der in SchILD2 verwendeten Version)
-Es gibt aber PDF-Reader (z.B. FoxIt) die eine "normale" PDF-Datei in eine Datei im "Broschürenformat" umwandeln können. Das geht z.T. auch als "Batch-Prozess", dafür müssen die einzelnen PDF (der einzelnen Kinder) aber in einem Verzeichnis liegen
-Dafür wurde das "Zeugnisverzeichnis" geschaffen.

**Comment by AnneSchueller** [comment]
@JuergenRichter : Wäre denn der Wunsch realisierbar, in der Dateimaske für die Dokumentenverwaltung noch den Dateinamen  mit aufzunehmen? Auch hinsichtlich vom  Zeit-Nutzenfaktor.

Ansonsten könnte das Issue geschlossen werden.

**Comment by EwaldReinhardt** [comment]
Es gibt Bildungsgänge im BK, die bekommen zwei Abschlusszeugnisse. Die Informationstechnischen Assistenten bekommen ein FHR-Zeugnis und ein Berufsabschlusszeugnis. Hier können sich sogar aufgrund der unterschiedlichen Abschlussprüfungsfächer unterschiedliche Noten im gleichen Fach ergeben.
Daher ist eine Aufnahme des Formularnamens sinnvoll.

**Comment by JuergenRichter** [comment]
> @JuergenRichter : Wäre denn der Wunsch realisierbar, in der Dateimaske für die Dokumentenverwaltung noch den Dateinamen mit aufzunehmen? Auch hinsichtlich vom Zeit-Nutzenfaktor.
> 
> Ansonsten könnte das Issue geschlossen werden.

Der Dateiname kann doch jetzt schon in die Dateimaske der Dokumentenverwaltung aufgenommen werden. Oder ist die Ausgabe in das "Zeugnisverzeichnis" gemeint?

**Comment by JuergenRichter** [comment]
Das lässt sich umsetzen. Welche Reihenfolge wäre denn günstiger
Angaben zum Schüler, Dateiname
oder
Dateiname, Angaben zum Schüler

**Comment by EwaldReinhardt** [comment]
Es muss Nachname, Vorname Dateiname sein, da man ja alphabetisch nach Schülern drucken möchte.

**Comment by FrodBRA** [comment]
Wie verhält sich das Zeugnisverzeichnis, wenn sich dort über Jahre Zeugnisse sammeln? 

Wäre es sinnvoll, die Dateien nach Schuljahr in jeweils passenden und automatisch angelegten Unterordnern "SJ_HJ" zu sortieren?

**Comment by EwaldReinhardt** [comment]
Man trägt das Verzeichnis ja in Einstellungen ein.
Das einmal anzupassen, wenn man Halbjahre will wäre kein Problem.

**Comment by JuergenRichter** [comment]
Wir werden den Dateinamen so umsetzen:
Name, Vorname, Geb.-Datum, Name der Reportvorlage.pdf

**Comment by JuergenRichter** [comment]
Ist jetzt so umgesetzt:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/bc6bcd0f-2b2d-43c1-b029-d7ad97a6ade9)

Die Klassenbezeichnung wie wie folgt ermittelt:
Wenn die Datenquelle "Lernabschnitte" geöffnet ist, wird die Klassenbezeichnung daraus genommen. Wenn man also z.B. ein Zeugnis für einen vergangenen Abschnitt druckt, wird die Klasse aus dem vergangenen Abschnitt geholt.

Wenn die  Datenquelle "Lernabschnitte" nicht geöffnet ist, wird die Klassenbezeichnung aus der Datenquelle "Schueler" geholt (was bedeutet, dass sie aus dem aktuellen Abschnitt geholt wird)

Das gilt auch für das Drucken in die Dokumentenverwaltung.
