### ISSUE TITLE
Bereich Schüler: Von Reportanzeige zu Datentabs zurück nicht möglich

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#342]
### SchildVersion 3.0.39.7

Wie kann man jetzt wieder auf die Datentabs wechseln, ohne dass in einen anderen Bereich gewechselt werden muss z.B. Kataloge.

![grafik](https://user-images.githubusercontent.com/44644567/184473723-3fe7cd2c-4d94-4c6c-8e83-adb552d88c83.png)

**Comment by JuergenRichter** [comment]
Kann ich bei mir nicht reproduzieren. Bitte mal die genaue "Klickfolge" beschreiben, die zu dem Problem führt

**Comment by AnneSchueller** [comment]
Wenn man die Auswahl "Schüler" angeklickt hat und dann auf Schüler->Drucken geht, dann erscheint die Ansicht wie im Bild oben. 
Von da aus kommt man aber nicht mehr auf die Individualdaten der Schüler. Man muss dann erstmal auf eine andere Kategorie klicken und dann wieder auf Schüler.
Vielleicht kann man das so anpassen, dass man beim Klick auf "Schüler" wieder zu den Individualdaten gelangt oder links neben "Bearbeitung" noch einen zusätzlichen Button.

**Comment by JuergenRichter** [comment]
Kann ich immer noch nicht reproduzieren. Wenn ich "Drucken" aktiviere, erscheint nur der Drucker-Auswahldialog 
![image](https://user-images.githubusercontent.com/61280188/184654859-93b5c129-57a4-46d3-8747-0b23881700d0.png)
Derr Schalter bewirkt ja auch nur, dass ein Screenshot der aktuell dargestellten Schülerdaten ausgedruckt wird .

**Comment by JuergenRichter** [comment]
Oder ist die Darstellung in Verbindung mit den Standard-Formularen gemeint, da ist das Verhalten tatsächlich wie beschrieben. Werde ich mir anschauen

**Comment by AnneSchueller** [comment]
Ja genau, da hatte ich mich falsch ausgedrückt: Drucken->Reports meinte ich.

**Comment by JuergenRichter** [comment]
Ich hab das jetzt erst mal so gelöst, dass bei Klick auf das Symbol "Reports" (auf dem Schüler-Reiter)  das Programm (je nach Berechtigung) die gesamte Reportsammlung zeigt oder nur den Ordner "Standard". Bei erneutem Klick werden wieder die Schüler-Detaildaten gezeigt.
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/342#event-7186441266

**Comment by JuergenRichter** [comment]
![image](https://user-images.githubusercontent.com/61280188/184869630-d966e815-9171-4a3d-b982-09e9f7bb1899.png)
