### ISSUE TITLE
Optionen im Druckdialog

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#343]
## Schildversion 3.0.39.7

Kann der Druckdialog auch so gestaltet werden, dass keine Radiobuttons verwendet werden sondern 
Optionskästchen. So können alle gewünschten Ausgaben in einem Rutsch erzeugt werden, ohne dass der Report weitere Male augerufen werden muss und ggfs. Ausgaben zu machen. Die gewählten Optionen sollten für den nächsten Aufruf erhalten bleiben.

Nach dem Schließen der Vorschau könnte der Dialog auch noch aktiv sein, so dass darin auf "Ausgabe" geklickt werden kann.
Ggfs. in den individuellen Einstellungen einstellbar.

![grafik](https://user-images.githubusercontent.com/44644567/184473559-e001889e-0029-4a9d-b89e-726880439aaf.png)
==>
![grafik](https://user-images.githubusercontent.com/44644567/184474601-382ea5d7-3953-4c13-88a2-a5a28e710700.png)

**Comment by AnneSchueller** [comment]
Eine Umstellung von Radiobutton auf Optionskästchen erspart sicherlich ein paar Klicks. Das ist ein guter Hinweis, den wir nochmal betrachten sollten, wenn sämtliche andere Bugs behoben wurden.

**Comment by EwaldReinhardt** [comment]
Es wäre IMHO auch gut, wenn die Auswahl des Schulhalbjahres mit im Dialog
dargestellt wird, weil es einfach zu oft übersehen wird, dass aus dem falschen Halbjahr
gedruckt wird.
Diese Einstellung ist ja nur für das Drucken da.
