### ISSUE TITLE
Dateimaske "Klasse" in Dokumentenverwaltung fehlerhaft

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#344]
Das Feld "Klasse" aus der Dateimaske der Dokumentenverwaltung führt zu einer Fehlermeldung

![Bild2](https://user-images.githubusercontent.com/79116896/184588786-e59a0fed-1f5f-4f5f-8fc7-7e2efe6cbb81.png)

**Comment by JuergenRichter** [comment]
Behoben
