### ISSUE TITLE
Datenquelle "KlassenSchueler"

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#345]
Ich bin gerade auf ein Problem mit der Datenquelle "KlassenSchueler" gestoßen. Diese enthält bestimmte Stammdaten der Schüler einer Klasse (ähnlich wie die DQ KursSchueler die Daten einer Klasse enthält). InSchILD2 war die Abfrage relativ einfach:

SELECT * FROM Schueler WHERE Schueler.Status = 2 AND Schueler.Geloescht=''-'' AND Schueler.Klasse=:Klasse

Wegen der Änderung in der Datenbankstruktur geht das aber nicht mehr so einfach, da ja viele Angaben gar nicht mehr im "Klartext" in der Tabelle "Schueler" stehen. Daher muss die Abfrage "zielgerichteter" formuliert werden, dazu müsste ich aber wissen, welche Informationen der SuS denn in dieser Datenquelle zur Verfügung stehen sollen.

**Comment by JuergenRichter** [comment]
Es muss natürlich heißen "(ähnlich wie die DQ KursSchueler die Daten des SuS eines Kurses enthält)

**Comment by FPfotenhauer** [comment]
Kann man hier evtl. den Weg gehen, das alle Daten zum Schüler aus der Datequelle Schueler zur Verfügung stehen?

**Comment by JuergenRichter** [comment]
Das wäre natürlich der eleganteste Weg. Das würde dann so ähnlich sein wie bei den Erziehungsberechtigten. Wenn die Datenquelle "Erzieher" die Hauptdatenquelle eines Reports ist, ordnet sich die Datenquelle "Schueler" dieser unter.
Das würde aber bedeuten, dass die Datenquelle KlassenSchueler wegfallen würde.

**Comment by JuergenRichter** [comment]
Ich schaue mir das mal an, ich vermute, dass der Aufwand überschaubar ist (da das ja schon bei den Erziehern umgesetzt ist). Wenn das sich einfach umsetzen, würde ich auch vorschlagen, das auch bei der Datenquelle KursSchueler so zu machen.

**Comment by FPfotenhauer** [comment]
Ja, ich fände so eine Lösung gut.
Wir müssten dann nur ggf. die Basisreports anpassen.

**Comment by JuergenRichter** [comment]
Habe ich jetzt mal für die Haupdatenquelle "Klassen" umgesetzt. Ist tatsächlich deulich weniger Aufwand als die Datenquelle KlassenSchueler anzupassen. Einziger Nachteil: Die vorhandenen Reportvorlagen müssen geändert werden, ist aber nicht so viel Aufwand.
Vorteil: Es stehen nun bei Reports, die die Datenquelle "Klassen" als Haupt-Datenquelle verwenden, im Prinzip nun alle Datenfelder der Datenquelle "Schueler" zur Verfügung. Außerdem können weitere "schüler_abhängige" Datenquellen angesprochen werden (sofer es Sinn macht).

Ich erde nachher mal eine aktualisierte Version zur Verfügung stellen.

**Comment by JuergenRichter** [comment]
Auch das hat mit mit geringem Aufwand funktioniert. Man muss in den Kurslisten nur die Datenquelle "KursSchueler" durch "Schueler " ersetzen und evtl. ein paar Felder anpassen.
