### ISSUE TITLE
Frage zu Tabelle "Benutzerkompetenzen"

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#346]
Ich war bisher davon ausgegangen, dass die Berechtigungen für Benutzer über die Tabelle "BenutergruppenKompetenzen" geregelt werden, d.h. die Berechtigungen eines konkreten Benutzers hängen nur von den Berechtigungen der Gruppen, zu denen dieser gehört ab.
Daneben gibt es ja auch noch die Tabelle "BenutzerKompetenzen". Aufgrund eines vergangenen Postings von Herrn Bachran war ich davon ausgegangen, dass diese Tabelle nur für "Sonderberechtigungen" (abweichend von den Gruppenberechtigungen) verwendet werden soll, daher wird sie derzeit in SchILD3 auch nicht aktualisiert. Ich habe nun aber gesehen, dass die Tabelle (wohl durch die Migration) sehr wohl befüllt wird. Das führt dazu, dass bei Änderungen der Gruppenberechtigungen zwar die Einträge in  "BenutzergruppenKompetenzen" angepasst werden, nicht aber die vorhandenen in "BenutzerKompetenzen". Da der View "V_Benutzerkompetenzen" (aus dem sich SchILD3 die Berechtigungen eines Benutzers holt) aber sowohl die Tabelle "BenutzergruppenKompetenzen" als auch  "BenutzerKompetenzen" ausliest, führt das dazu, dass Benutzer andere Berechtigungen im Programm haben als eigentlich gedacht.

Das könnte man umgehen, indem in SchILD3 auch die Einträge "BenutzerKompetenzen" (und nicht nur in in  "BenutzergruppenKompetenzen") aktualisiert werden. Soll das so geschehen, falls nicht, müsste bei der Migration die Befüllung von in  "BenutzerKompetenzen" rausgenommen werden.

**Comment by JuergenRichter** [comment]
Ich habe das jetzt erts mal so gelöst, dass die Berechtigungen nicht aus "V_Benutzerkompetenzen" (View) sondern aus "BenutzerGruppenkompetenzen" (Tabelle) geholt werden. Ob das so bleiben soll, können wir noch klären.

**Comment by FPfotenhauer** [comment]
Die Berechtigungen bei den einzelnen Benutzern wurden falsch migriert.
Das wurde jetzt behoben. Die Redundanz der Gruppenberechtigungen aus Schild2.0 wird somit aufgelöst.

Die Benutzerberechtigungen müssen in Schild3 aus der View V_Benutzerkompetenzen geholt werden.

**Comment by FPfotenhauer** [comment]
Bitte die Änderung an Schild3 rückgängig machen.

**Comment by JuergenRichter** [comment]
Ist rückgängig gemacht
