### ISSUE TITLE
Klassen-Versetzungstabelle : Aktuelle Angaben in Schülerdaten übernehmen : Fehlermeldung

### ISSUE THREAD

**Issue by MichaelPeters1983** [SVWS-NRW/Schild3-BetaTest#347]
Wenn man bei einer Klasse die Gliederung ändert und diese dann in die Schülerdaten übernehmen will entsteht die folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/111509114/185604522-eb5d5b63-ceb5-41d6-9345-58617db7bbc2.png)
Die Gliederung wird zwar übernommen, dennoch entwas verwirrend.

**Comment by AnneSchueller** [comment]
Die gleiche Fehlermeldung erhalte ich auch. Bei den Schülerdaten wird die neu eingestellte Gliederung nicht übernommen. Lediglich bei den Katalogen "Klassentabellen" bleibt die entsprechende Änderung der Gliederung.

**Comment by JuergenRichter** [comment]
Behoben

**Comment by JuergenRichter** [comment]
Behoben
