### ISSUE TITLE
Schaltlfäche Neuer Benutzer

### ISSUE THREAD

**Issue by KayBerger** [SVWS-NRW/Schild3-BetaTest#349]
Verwaltung > Benutzer > Benutzerverwaltung
Es gibt keine (offensichtliche?) Schaltfläche für das Anlegen eines neuen Benutzers. Dies geht lediglich über einen Rechtsklick.
Meine Befürchtung: Es werden "einfach" alle Lehrkräfte übernommen - um dann ggf. die unerwünschten EInträge anschließend zu löschen (und dann erst durch einen Rechtsklick zu merken, dass man so auch einzelne Nutzer hätte anlegen können.)

**Comment by AnneSchueller** [comment]
Vielen Dank für den Hinweis. Bisher geht es tatsächlich nur über die rechte Maustaste.

**Comment by JuergenRichter** [comment]
Ich hatte mir eigentlich folgende "Philosophie" überlegt: Alle Funktionen, die eine Einzelperson betreffen (und das ist ja auch eine Neuanlage) sind auf das Popup-Menü gelegt. Wir können natürlich für die Neuanlage auch eine Ausnahme machen oder einen Hinweis im Fenster anzeigen: "Optionen für Datenbearbeitung (z.B. Neueingabe) über rechte Maustaste aufrufen"

**Comment by JuergenRichter** [comment]
Ich habe jetzt erst mal den Hinweis umgesetzt

**Comment by AnneSchueller** [comment]
Mit Hinweis finde ich gut
