### ISSUE TITLE
Proportionale Verkleinerung der Unterfenster (z.B. Basisdaten,Zusatzdaten, Aktuelle Laufbahn)

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#35]
Wenn ich das Programmfenster verkleiner oder den Container-Bereich vergrößer, werden die Unterfenster im rechten Bereich proportional verkleiner, sodass der Inhalt z.T. nicht mehr zu lesen ist. Neben den 3 Unterfenstern ist ein großer leerer Bereich, der meineserachtens vollkommen überflüssig ist.
Gibt es eine Möglichkeit, dass durch die Veränderung der Fenstergröße nicht die anderen Fenster verkleinert werden, sondern der Fensterinhalt zugeschnitten wird?

**Comment by FPfotenhauer** [comment]
Wir hatten da auch schon diskutiert und es wurde vorgeschlagen, so etwas wie eine Begrenzung einzuführen.
