### ISSUE TITLE
Import Externes Notenmodul

### ISSUE THREAD

**Issue by KayBerger** [SVWS-NRW/Schild3-BetaTest#350]
Verwaltung > Import > Externes Notenmodul
Bei der Auswahl einer mit SchILD2 erstellten enm-Datei erscheint die Fehlermeldung.
(Ok, sollte man vielleicht auch nicht machen, aber ist in der Praxis evtl. nicht ganz unwahrscheinlich.)
Da ein Export für enm noch nicht möglich ist (Fehlermeldung [https://github.com/SVWS-NRW/Schild3-BetaTest/issues/290#issue-1254263438](url)), konnte ich das Verhalten bei korrekten Dateien nicht prüfen.
![SchILD3b_Fehlermeldung_Import_ExtNotMod](https://user-images.githubusercontent.com/111630806/185741737-27ff8be4-60e3-4c7f-9625-df00a11f1920.jpg)

**Comment by AnneSchueller** [comment]
Hier klappt auch der Export noch nicht.
Ich gehe davon aus, dass das Noten-Einlesen von Schild2 erzeugten enm-Dateien nicht unterstützt wird.
@FPfotenhauer : soll die Notenabgabe weiterhin über ein externes Notenmodul laufen?

**Comment by JuergenRichter** [comment]
Hier muss mit Herrn Blomeyer noch geklärt werden, welches Datenformat für den Export/Import zukünftig verwendet werden soll.

**Comment by FPfotenhauer** [comment]
Wir können gerne auf SQLite umstellen.
Der SVWS-Server hat bereits eine Json-Schnittstelle!

**Comment by FrodBRA** [comment]
Da das ENM noch nicht supportet ist, schlage ich vor, dieses Issue erst einmal zu schließen. Der Ex- und Import dürfte ja bei einem Anlauf des Supports hinreichend getestet werden, so dass grundsätzliche Probleme korrigiert werden bzw. dann aktuelle auffallen.

Ich würde dann als aktuellen Stand im Wiki anmerken, dass von einer Kompatibilität "SchILD2-enm" -> "Einlesen in SchILD3" nicht auszugehen ist.

**Comment by AnneSchueller** [comment]
Ich schließe das Issue. Herr Blomeyer ist aktuell bei der Anpassung vom ENM.
