### ISSUE TITLE
Fenster Halbjahr auswählen

### ISSUE THREAD

**Issue by KayBerger** [SVWS-NRW/Schild3-BetaTest#351]
Schüler > Akt. Halbjahr
Das Fenster Halbjahr auswählen ist sicherlich etwas übersichtlicher als die Zeile mit Dropdown in Schild2. (Gibt es weitere Vorteile?)
Es wird allerdings viel Platz auf dem Bildschirm "verschenkt", denn in vielen Fällen bleibt ein großer Teil des Fensters leer. Auf kleinen Bildschirmen könnte der Platz anders besser gefüllt werden.
Gefahr: Fenster wird ganz schmal gemacht, dann erkennt man nicht mehr sofort, in welchem halbjahr man arbeitet und ob es ein gewertetes ist.

**Comment by AnneSchueller** [comment]
Da gebe ich Dir Recht. Hier könnte man ggf. die Fenster etwas dynamischer gestalten und ggf. die Standardbreite von Spalten größer definieren. Ich notiere das auf meiner Verbesserungs-Liste, sodass man das ggf. nach Abarbeitung der Bugs anpasst.
