### ISSUE TITLE
Dropdown aktuelle Schülerauswahl

### ISSUE THREAD

**Issue by KayBerger** [SVWS-NRW/Schild3-BetaTest#352]
Normalerweise ist im Schülercontainer über der Liste das Drowdown-Feld für den Filter etc. zu sehen:
![SchILD3b_Schülerkontainer_Filterdropdown_ja](https://user-images.githubusercontent.com/111630806/185742876-d8d45dbb-7d80-4f71-9c36-9479fbfba8e2.jpg)
Nach einer Auswahl über Filter I ist es nicht mehr zu sehen:
![SchILD3b_Schülerkontainer_Filterdropdown_nein](https://user-images.githubusercontent.com/111630806/185742889-89f83750-b186-489b-b0b5-ac963d540bfd.jpg)
Ist das so gewollt? Man kann dann nicht mehr auf den ersten Blick die Farbe des Filtersymbols erkennen. (Dass über Filter I ausgewählt wurde ist dann natürlich dennoch über das fehlende Feld erkennbar...)

**Comment by AnneSchueller** [comment]
Das wurde aus Schild2 übernommen. Da muss man ja auch nach der Filter I Auswahl erstmal auf die Standardauswahl bzw. den roten Punkt klicken, sodass man wieder über die Schnellfilter filtern kann. 
Ich notiere mir das aber mal als Verbesserungsvorschlag wenn alle wichtigen Komponenten fehlerfrei laufen.

**Comment by KayBerger** [comment]
Dass die Schülerauswahl nicht mehr zu sehen ist, entspricht ja tatsächlich Schild2 - ist m. E. auch nicht schlimm. Im Unterschied zu Schild2 ist aber bei Schild3 die rote Warnfarbe ("Achtung, Spezialauswahl") direkt dort verortet und daher nach Anwendung von Filter I auch nicht mehr zu sehen (und damit auch nicht mehr anklickbar). Es machte schon Sinn, durch eine auffällige Farbe auf die besondere Filterung hinzuweisen - das ist nun aber nicht mehr so.

**Comment by AnneSchueller** [comment]
Ich notiere das als Verbesserungsvorschlag und schließe das Issue erstmal. Ich kann mir vorstellen, dass man nach einer gewissen Gewöhnungsphase das nicht mehr als störend empfindet. Evtl. könnt man den Button "Standard-Auswahl" bei Aktivierung eines Filters etwas farblich hervorheben.
