### ISSUE TITLE
Login Schild 4.0 - Sprachliche Verbesserung 

### ISSUE THREAD

**Issue by MichaelPeters1983** [SVWS-NRW/Schild3-BetaTest#353]
Beim Login für SchILD 4.0 steht der folgende Hinweis:
"Hinweis: Um eine gute Lesbarkeit zu erzeugen, wird bei SVWS-NRW möglichst auf geschlechtsneutrale Begriffe wie Lehrkräfte, Klassenleitung, Erzieher usw. zurückgegriffen. An Stellen, wo das nicht möglich ist, wird versucht alle Geschlechter gleichermaßen zu verwenden."
Als Deutschlehrer muss ich mir leider den Hinweis erlauben, dass der zweite Satz so komisch klingt ... "Geschlecher verwenden"?!? Könnten wir da besser schreiben: "An Stellen, wo das nicht möglich ist, sind natürlich alle Geschlechter gleichermaßen gemeint."

Nur als kleiner Vorschlag ;)

**Comment by FPfotenhauer** [comment]
Wir werden das noch ändern.
Bitte zum SVWS-Server hier nur Issues zur Installation und Migration melden.
