### ISSUE TITLE
Verwaltung Lehrkräfte - zwang zum Kürzel

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#354]
Ich habe eine externe MA angelegt und konnte den Datensatz ohne Kürzel nicht speichern. Bei uns haben Hausmeister, Sekretariat, Kioskmitarbeiter etc. keine Kürzel. 

![Mitarbeiter ohne Kürzel](https://user-images.githubusercontent.com/75326793/185983256-0680a957-593f-4570-8c91-dc4ee97519ea.JPG)

**Comment by AnneSchueller** [comment]
Ich habe das gerade mal in Schild2 getestet. Da klappt es auch nicht ohne ein Internes Kürzel. Da die Felder in Schild2 auch gelb hinterlegt sind, brauch man diese Angaben zum Speichern. Oder gibt es da noch irgendwo einen Haken, den ich übersehen habe?

**Comment by AlexanderDedy** [comment]
Sorry war etwas zu knapp beschrieben. Stimmt, bisher müssen wir das auch. Das führt aber dazu, dass wir in der Datenbank etwa 80 ausgeblendete (ehem. Referendare) haben, die alle ein Kürzel belegen. Die SL möchte die auch nicht löschen so das es immer Probleme gibt mit neuen.

**Comment by AnneSchueller** [comment]
Vielleicht kann man bei den ehemaligen Kollegen-Kürzel/Externen ein X1, X2,... vorschreiben. z.B. X1AB, X2HU, X3TE, usw.
