### ISSUE TITLE
Lehrerfilter in Leistungsdaten aktuelles HJ geht nicht

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#355]
In den Leistungsdaten werden alle Einträge (ausgeblendet oder Extern) angezeigt zu Auswahl. Im GP Klassenuntericht bearbeiten funktioniert es.

![Versteckte Lehrer und sonstige](https://user-images.githubusercontent.com/75326793/185984739-c2bfdb7c-33b3-4994-a88b-41e8ac17f837.JPG)

**Comment by JuergenRichter** [comment]
Ich verstehe das Problem nicht ganz. Können Sie das etwas detaillierterer beschreiben?

Oder ist mit "Alle Einträge" gemeint, dass da auch "unsichtbare" Lehrkräfte erscheinen?

**Comment by JuergenRichter** [comment]
Es werdn tatsächlich auch die auf "nicht sichtbar" gestellen Lehrkräfte in der Auswahl angezeigt. Wird korrigiert.

**Comment by JuergenRichter** [comment]
Ist behoben
