### ISSUE TITLE
Noten aus altem Abschnitt übernehmen

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#357]
Beim durchspielen eines ASZ ist mir gerade ein großer Unterschied zu 2.0 aufgefallen. Jetzt muss scheinbar genau das/die HJ ausgewählt werden, aus dem die alte Note übernommen werden soll. Das wäre für uns als BK eine deutliche Mehrarbeit! Es kommt sehr oft vor, dass Noten aus mind. 3 verschiedenen Abschnitten geholt werden müssen. Bisher hat der GP immer die letzte Note geholt, egal in welchem Abschnitt. Das bitte wieder möglich machen!

![Fächer zum holen](https://user-images.githubusercontent.com/75326793/185998343-f7f81acd-2eb0-4896-9239-bb9c9df5143a.JPG)

![Fächer übernehmen](https://user-images.githubusercontent.com/75326793/185998361-db214938-6493-45f0-910d-0422f47e0d7d.JPG)

**Comment by AnneSchueller** [comment]
Meinst du evtl. den Gruppenprozess "Noten, Zeugnisvorbereitung --> Abgeschlossene Fächer holen" ? 
Der Gruppenprozess Fächer -> Fächer aus vergangenem Abschnitt holen ist ja ebenfalls mit einer Auswahl bezüglich des Jahres und des Abschnitts.  Oder funktioniert der GP nicht wie erwartet? Bei meiner Gymnasialdatenbank klappt der GP. Es werden alle Fächer aus dem letzten Abschnitt übernommen.
