### ISSUE TITLE
Bildungsgang-Beginn fehlt in der Auswahl (Filter I) 

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#36]
Ich finde den Bildungsgang Beginn aus den Individual-Daten I nicht in der Auswahl (Filter). 
![image](https://user-images.githubusercontent.com/75179015/101260203-766fe500-372e-11eb-9f21-7307fc432bb3.png)

Dieses Feld fehlt im Filter:
![image](https://user-images.githubusercontent.com/75179015/101260258-eaaa8880-372e-11eb-9d70-f1a1e3ef362f.png)

Tippfehler (Individual-Daten I):
![image](https://user-images.githubusercontent.com/75179015/101260231-b33bdc00-372e-11eb-9520-fc9e9c059d1c.png)

**Comment by JuergenRichter** [comment]
Wird in Version 3.0.9 korrigiert

**Comment by JuergenRichter** [comment]
Kommt in 3.0.19.5

**Comment by FrodBRA** [comment]
In 3.0.73.10 finde ich das Feld nicht. Weder bei den Individualdaten noch im Reiter "Berufskolleg". Ich hoffe, ich habe es nicht einfach übersehen.

**Comment by AnneSchueller** [comment]
Die Dauer steht im Filter1/Berufskollleg, die An- und Abmeldung in Filter1/Individualdaten (analog zu Schild2).
Somit ist m.E. alles richtig drin im Filter. 
Falls ich da was übersehen habe, gerne nochmal das Issue öffnen.
