### ISSUE TITLE
Duplikate abgleichen

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#362]
Verwaltung/Werkzeuge/Duplikate abgleichen erhalte ich diese Fehlermeldung.

![Duplikate abgleichen](https://user-images.githubusercontent.com/75326793/187022354-cba65987-0fa2-48fd-81c1-63c17249eb3e.JPG)
[Duplikate abgleichen.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9437579/Duplikate.abgleichen.txt)

**Comment by AnneSchueller** [comment]
Die Auswahl Verwaltung->Werkzeuge->Duplikate abgleichen habe ich in der neuen Version gar nicht.
@JuergenRichter : Ich finde die Option "Duplikate abgleichen in der aktuellen Version gar nicht. Wurde sie rausgenommen?
@AlexanderDedy : testest du mit der Version 3.0.41.7?

**Comment by JuergenRichter** [comment]
Die Option gibt es (auch in SchILD2) nur bei einer BK-Datenbank

**Comment by AnneSchueller** [comment]
Danke für die Info. Ich hatte eine Gym-DB.

**Comment by JuergenRichter** [comment]
Ich habe gerade festgestellt, dass meine Ausage falsch war, die Option "Verwaltung>>Wekzeuge>>Duplikate abgleichen" sthet auch bei "Nicht-BKs" zur Verfügung. Daher stelle ich mal die Frage: Soll das so sein? Werden auch an "Nicht-BKs" Dupliakte verwendet mit dem Zweck, damit eine Vorplanung für das nächste Schuljahr zu machen?
Beispiel: Schüler schließt den Bildungsgang A im aktuellen Schuljahr ab, will aber im nächsten Schuljahr im Bildungsgand B eine weitere Ausbildung machen. Dann kann man ihn als Duplikat anlegen (mit Status "Neuaufnahme") und doert dann schon die ganzen Vorbereitungen machen.

**Comment by AnneSchueller** [comment]
Mir ist nur bekannt, dass gelegentlich bei Zwillingen mit Duplikaten gearbeitet wird.
@Raffenberg : Was meinst du zu der Option "Duplikate abgleichen"?

**Comment by JuergenRichter** [comment]
Bei Zwillingen braucht man aber keinen Abgleich. Der Abgleich ist ja für folgende Situation gedacht:

- Es wird ein Duplikat angelegt mit den aktuellen Daten, aber Status "Neuaufnahme"
- Das Duplikat ist ja dafür gedacht, damit schon Vorbereitungen für das nächsten Schuljahr zu machen (z.B. andere Klasse, Gliederung usw.). Daher wird i.d.R. beim Duplikat das Folgeschuljahr eingetragen (siehe dazu Anmerkung unten)
- Nach dem Schuljahreswechsel hat man dann das "Original" mit dem Status "Abschluss", das Duplikat den Status "Neuaufnahme" (oder "Aktiv")
- Der Vorgang "Duplikate abgleichen" führt dann wieder die beiden Datensätze zu einem zusammen, bei Abweichungen einzelner Daten (z.B. geänderte Adresse) kann der Benutzer entscheiden, von welcher "Version" (Original oder Duplikat) diese genommen werden sollen. Grundsätzlich bleibt das "Original" erhalten (mit den vom Duplikat übernommenen Änderungen), das Duplikat wird gelöscht.

Dazu aber eine Anmerkung: In SchILD3 soll es ja möglich sein (ist schon in Arbeit) Vorbereitungen für das neue Schuljahr bereits im laufenden Schuljahr zu machen. Damit ist die Verwendung von Duplikaten m.E. überflüssig. Es werden dann ja Lernabschnitt des neuen Schuljahres angelegt, in denen z.B. eine andere Klasse oder Gliederung eingetragen werden kann. Allerdings können die BKs zur Zeit mit den Duplikaten recht einfach auf die "zukünftigen SuS" filtern (da Status "Neuaufnahme"). Es werden dann alle "echten" Neuaufnahmen (die neu an der Schule sind) und die Duplikate (die ja auch den Status "Neuaufnahme") angezeigt. Es wäre zu überlegen, wie das dann in SchILD3 umgesetzt werden kann 

Meine Frage daher: Soll der Duplikatsabgleich überhaupt erhalten bleiben?

**Comment by JuergenRichter** [comment]
Noch ein Hinweis dazu:
Falls der Duplikatsabgleich wegfallen sollte, muss überlegt werden, wie dann der Import über die Schnittstelle SchILD-NRW ablaufen soll, der derzeit ja z.B. von SchülerOnline benutzt wird. Und da melden sich ja auch SuS an, die aktuell ein BK besuchen, aber im nächsten Schuljahr einen Bildungsgangwechsel anstreben.

**Comment by AnneSchueller** [comment]
Vielen Dank für die detaillierten Infos. 

@FPfotenhauer : Soll der Duplikatsabgleich überhaupt erhalten bleiben? Das hätte sicherlich auch Auswirkungen auf die Migration.

**Comment by FPfotenhauer** [comment]
Der Duplikatsabgelich sollte bei BKs auf jeden Fall erhalten bleiben.
Die Planung für das kommende Schuljahr ist ja noch nicht voll umgesetzt.

Wir können später darüber reden, ob die Schnittstelle in ein Planungs-Schuljahr importiert, statt Duplikate anzulegen.

**Comment by JuergenRichter** [comment]
Wegen der geänderten Datenbankstruktur musste auch die Erzeugung der Duplikate überabeitet werden, da ja jetzt zwingend ein Eintrag in "SchuelerLernabschnittsdaten" gemacht werden muss, ansonsten ist kein "Abschnittsbezug" möglich. Dabei wird jetzt wie folgt vorgegangen

- Wenn kein "echtes Duplikat" angelegt wird (die Abfrage "Soll der neu angelegte Schüler als Duplikat markiert werden" wird verneint)  oder der Status der "Kopiervorlage" den Status "Neuaifnahme" der "Warteliste" hat, so wird in dem Lernabschnittsdatensatz die Schuljahresabschnitts_ID der Kopiervorlage eingetragen.
Beispiel wäre die Eingabe eines Zwillingskindes, Kopiervorlage ist das schon eingegebene Geschwisterkind, dann erhält der kopierte Datensatz die gleiche Schuljahresabschnitts_ID wie dieses.

- Ansonsten liegt ein "echtes Duplikat" vor (beide Datensätze sind die gleiche Person), dann wird die "zukünftige" Schuljahresabschnitts_ID (bezogen auf den aktuellen Eintrag bei der Schule) ermittelt und eingetragen. Falls notwendig, wird ein entsprechender Datensatz in "Schuljahresabschnitte"  erzeugt

**Comment by JuergenRichter** [comment]
Beim Testen ist mir gerade was aufgefallen: Ich hatte mir gedacht, dass es sinnvoll ist, bei einem "echten" Duplikat die GUID der Kopiervorlage zu übernehmen (da es sich dann ja um identische Personen handelt). Das funktioniert aber nicht, da auf der GUID ein eindeutiger Index liegt. Beim Duplikatsabgleich wäre es aber von Vorteil, dass Duplikate die gleiche GUID wir die Kopiervorlagen haben.
Frage: Wäre es möglich, die Eindeutigkeit der GUI wieder rauszunehmen?

**Comment by AnneSchueller** [comment]
@FPfotenhauer :Frage: Wäre es möglich, die Eindeutigkeit der GUI wieder rauszunehmen?

**Comment by FPfotenhauer** [comment]
Können wir ggf. ein Feld einführen "duplikatVonID" statt IstDuplikat?
Nicht eindeutige GUIDs würden wir auf jeden Fall vermeiden wollen.
Langfristig würde wir auch von den Duplikten weggehen wollen.

Wird die GUID bei der Erkennung der Duplikate in Schild2 überhaupt genutzt?

**Comment by JuergenRichter** [comment]
In Schild2 wird Name, Vorname und Geburtsdatum verglichen. Ich dachte nur, dass es ja einfacher wäre, wenn man das in SchILD3 über die GUID machen könnte (die ja vom Benutzer nicht verändert werde kann). Ich hab das jetzt aber so wie in SchILD2 umgesetzt, funktoniert auch. Über die anderen Vorschläge kann man sich ja später Gedanken machen.

**Comment by JuergenRichter** [comment]
Duplikatsabgleich funktioniert jetzt
