### ISSUE TITLE
Katalog Personengruppen

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#363]
Beim aufrufen und arbeiten in dem Katalog erhalte ich immer diese Fehlermeldung

![Katalog Personengruppen](https://user-images.githubusercontent.com/75326793/187022767-56ae7cb2-4ab1-40db-b3b6-d3735b1800b6.JPG)

**Comment by JuergenRichter** [comment]
Behoben
