### ISSUE TITLE
Abschnitts- bzw. Schuljahreswechsel

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#364]
Ich habe mir mal Gedanken über die ganzen Vorgänge in Zusammenhang mit dem Abschnitts- bzw. Schuljahreswechsel gemacht. Hier mal ein Vorschlag für einen entsprechenden "Wizard".
![image](https://user-images.githubusercontent.com/61280188/187877285-0d9c370b-f8db-4462-8ddd-468d7408835d.png)

Dazu einige Anmerkungen:

Die Wahlmöglichkeit der einzelnen Optionen wird von einigen Bedingungen abhängen:

- Punkt 1 kann nur gewählt werden, wenn dieser Vorgang bisher noch nicht ausgeführt wurde (d.h. noch kein "zukünftiger" Eintrag in der Tabelle "Schuljahresabschnitte" existiert)
- Punkt 2 kann nur gewählt werden, wenn entweder Punkt 1 aktiviert ist oder Punkt 1 bereits zuvor ausgeführt wurde. Außerdem darf es für die "Zielmenge" (der Punkt kann auch als Gruppenprozess für eine Teilmenge der SuS ausgeführt werden) noch keine Lernabschnitte für den neuen Abschnitt geben (dann ist der Vorgang ja schon ausgeführt worden)
- Punkt 3 kann nur ausgewählt werden, wenn Punkt 2 aktiviert wurde oder für alle SuS in der Zielgruppe ein Lernabschnitt für das zukünftige Halbjahr existiert
- Punkt 4 kann nur gewählt werden, wenn Punkt2 und Punkt 3 aktiviert wurde oder alle aktiven SuS (aktiv im neuen Abschnitt!, hier keine "Teilmengenbearbeitung möglich) den neuen Schuljahresabschnitt eingetragen haben

Bitte schauen Sie sich das Konzept mal an

**Comment by JuergenRichter** [comment]
Wenn man alle Punkte ankreuzt, entspricht das dem Vorgang "Schuljahreswechsel durchführen" in SchILD2

**Comment by Raffenberg** [comment]
Hallo Herr Richter,
Ich finde die Übersicht sehr transparent.

Was passiert, wenn der Punkt 1 und 2 zwecks Vorplanungen schon ausgeführt wurden, einige Zeit später der Punkt 3 ausgeführt werden soll, sich aber der zukünftige Status einzelner Schüler geändert hat. Hier wäre ein Automatismus gut, der zukünftige Lernabschnitte löschen würde, sofern der Schüler die Schule verlässt, bzw. zukünftige Lernabschnitte automatisch gesetzt würden, wenn der Schüler doch an der Schule verbleibt. Abgänger mit überflüssigem Lernabschnitt verursachen probleme bei der Statistik.

Ich würde dann auch vorschlagen, dass alle Häkchen standardmäßig gesetzt werden, da dies zumindest Momentan der Normalfall ist.

**Comment by JuergenRichter** [comment]
Darüber hab ich mir auch schon Gedanken gemacht, dass sollte natürlich so sein, wie Sie es beschrieben haben, d.h. überflüssige Lernabschnitte sollten gelöscht, fehlende mit Standardangaben ergänzt werden

**Comment by FPfotenhauer** [comment]
Hier muss man sicherlich auch darüber reden, wie das im SVWS-Server gehandhabt werden soll.
Die beiden Systeme dürfe hier nicht gegeneinander arbeiten.

**Comment by JuergenRichter** [comment]
Im Prinzip macht der Wizard ja nichts anderes als das, was bisher beim Schuljahres-/Abschnittswechsel stattgefunden hat, nur wird der Benutzer nun ein bisschen besser "geführt"

**Comment by JuergenRichter** [comment]
Der Wizard sieht jetzt so aus:
![image](https://user-images.githubusercontent.com/61280188/190983629-5a9f6dd2-5328-405c-bbca-3b05d457b5c7.png)

Ich stelle in Kürze eine aktualisierte Programmversion zur Verfügung
