### ISSUE TITLE
Word-Seriendruck weiter unterstützen?

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#365]
Ich werfe mal eine Frage in den Raum:
Soll der Word-Seriendruck (z.B. in die "Datentra.txt" oder aber auch in die Word-Zeugnisvorlagen für Grundschulen) weiter unterstütz werden? Meines Erachtens sind die Seriendruckvorlagen für den ReportExplorer viel einfacher zu verwenden als Word-Serienbriefe, auch die Grundschulzeugnisse sind jetzt schon so ausgereift, dass man m.E. keine Word-Formulare mehr benötigt (abgesehen von den damit verbundenen Datenschutz-Problemen).

**Comment by FPfotenhauer** [comment]
Ich bin jetzt mal ganz mutig:
Von mir aus können wir den Word-Serienbriefdruck abschalten.
Man kann sich Daten auch aus der Text/Excel-Schnittstelle bereitstellen.
Wir müssten das dann nicht mehr supporten.
Im SVWS-Server wird es auch definitiv keinen Word-Druck geben...

**Comment by Raffenberg** [comment]
Ich sehe das genauso, zumal der Prozess in gewisser Weise auch immer eine Black-Box war.

**Comment by AnneSchueller** [comment]
Ich denke auch, dass die neuen Serienbriefe so anwenderfreundlich sind, dass man den Word Seriendruck rausschmeißen kann

**Comment by EwaldReinhardt** [comment]
Sehe ich auch so.

**Comment by FPfotenhauer** [comment]
OK, bitte "abklemmen."
