### ISSUE TITLE
Katalogauswahl verschwindet, wenn Katalog Berufe ausgewählt wird.

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#366]
## Version 3.0.41.7
Klickt man im Bereich Kataloge auf Berufe, so verschwindet der linke Bereich mit den Katalogen.
![grafik](https://user-images.githubusercontent.com/44644567/188111429-55030f7c-96c0-4913-8868-c660bba8bfcc.png)

**Comment by JuergenRichter** [comment]
Behoben
