### ISSUE TITLE
Abfragefehler bei Kataloge/Personengruppen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#367]
## Version 3.0.41.7

Bei Personengruppen ist die SQL-Abfrage noch fehlerhaft:
![grafik](https://user-images.githubusercontent.com/44644567/188112025-80ee05ec-cccd-4620-9b55-6aa900fd8a85.png)

**Comment by JuergenRichter** [comment]
Behoben
