### ISSUE TITLE
Fachklassen Dropdown Gliederung deaktivieren

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#368]
### Version 3.0.41.7

Ich denke, dass die Gliederung einer Fachklasse nicht editierbar sein sollte. Falsche Fachklassen sollten gelöscht und die richtige
angelegt werden.
Daher sollte das Dropdownfeld nicht verfügbar sein.
Damit das deutlich wird könnte man unten einfach Fachklasse: A01 101-02 ohne Eingabefeldcharakter anzeigen z.B.
als Überschriftbalken.
Man kann in diesem Dropdown auch keinen anderen Wert auswählen, daher auch nicht anzeigen.
![grafik](https://user-images.githubusercontent.com/44644567/188112804-31ae4fad-3073-45f5-a66c-b92ab19665c1.png)

**Comment by AnneSchueller** [comment]
Die Dropdown-Option bei Gliederung sollte rausgenommen werden. 
Die Fachklassen 101-02 usw. werden ja unter dem sichtbar-Button angezeigt. Meiner Meinung nach hat man dann alle wichtigen Infos übersichtlich vorliegen.

**Comment by JuergenRichter** [comment]
Änderungsmöglichkeit der Gliederung beim Fachklassenkatalog ist raus genommen
