### ISSUE TITLE
Filter auf markiert Schüler

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#369]
### Version 3.0.41.7

Der Sinn und Zweck des Buttons "Filter auf markiert Schüler" ist mir nicht klar:
Gefiltert werden die 'angehakten' Schüler. Das wählt man beim Gruppenprozess
ja aus. Dass der Filter gesetzt ist, spiegelt der Button nicht wider, sondern nur die fehlende Filterzeile oberhalb der Schülerliste. 
Wenn der Button dann das zweite Mal betätigt wird wieder die Standardauswahl
eingestellt und vorher ausgewählte Klassen, etc gehen verloren. 
Das heißt, dass die beiden Funktionen "Filter auf markierte Schüler" und "Standard-Auswahl"
dasselbe Verhalten haben. 
Es wäre schön, wenn die alte Filtereinstellung wieder hergestellt würde.
Andererseits ist zu überlegen, ob diese Funktion ohne die "Markierungseigenschaft" aus Schild2 (Fette Einträge)
überhaupt sinnvoll ist.
![grafik](https://user-images.githubusercontent.com/44644567/188120430-c926c14b-7409-4d4b-b32b-38c96030898f.png)

**Comment by AnneSchueller** [comment]
Vielleicht kann man hier den Text ändern in "Filter auf ausgewählte Schüler", sodass es nicht zur Verwirrung kommt, da die Filteroption in Schild2 nur für fett-gedruckte SuS eine Auswirkung hat. 
Dennoch ist diese Filteroption hilfreich um beispielsweise eine bessere Übersicht über die Auswahl zu erlangen  oder falls man z.B. eine Excel-Liste von dem Schülercontainer exportieren möchte. 

Das Verhalten bei zweiten Klick auf den Button sollte angepasst werden. Wenn man die Auswahl dann nochmal korrigiert und erneut auf den Filter klickt erscheinen aktuell alle Schüler im Container.
