### ISSUE TITLE
Sprachenfolge

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#37]
Die Spalteneinträge bei der Sprachenfolge sind falsch (siehe Bild). Außerdem kann man in der Spalte Abschnitt nichts eintragen.
![Sprachenfolge](https://user-images.githubusercontent.com/62895389/101279202-eaf36400-37c0-11eb-9b95-f22c3775323c.JPG)

**Comment by JuergenRichter** [comment]
In Folgeversion korrigiert
