### ISSUE TITLE
Fehlende Einstellung der Sortierreihenfolge für die Schülerliste

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#370]
### Version 3.0.41.7

Mir fehlt die Möglichkeit die Sortierreihenfolge der Schülerliste zu beeinflussen.
Ist die ersatzlos gestrichen?

**Comment by AnneSchueller** [comment]
Wo kann man dies denn in Schild2 (ich glaube, diese Option kenne ich gar nicht)

**Comment by EwaldReinhardt** [comment]
Das kann man hier machen:
![grafik](https://user-images.githubusercontent.com/44644567/188412845-ac9d7ab2-5697-446a-8cba-17ad4d022587.png)
![grafik](https://user-images.githubusercontent.com/44644567/188412908-954ff4be-155a-4e34-bfb7-cd02a8bb2837.png)

**Comment by AnneSchueller** [comment]
Die Option kannte ich tatsächlich noch nicht. 
@JuergenRichter: Wurde die Option absichtlich weggelassen?

**Comment by JuergenRichter** [comment]
@JuergenRichter: Wurde die Option absichtlich weggelassen?
Ja, da durch die Änderungen in der Datenbank die "Abfrage-Strategie" komplett geändert werden musste, wurde die individuelle Sortierung erst mal rausgenommen, kommt aber wieder

**Comment by JuergenRichter** [comment]
Ist nun umgesetzt
