### ISSUE TITLE
SQL-Fehler beim Anlegen eines Fachs unter Leistungsdaten

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#371]
### Version 3.0.41.7
Beim Versuch im Reiter Leistungsdaten ein Fach zu ergänzen kommt die folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/44644567/188123711-372b9a3a-01f9-40ab-a559-77fbadf0773e.png)

Ablauf: Im Reiter Leistungsdaten auf + klicken um eine neue Zeile zu erzeugen:
Alle benötigten Daten eintragen und auf √ klicken.

[FehlerDumpFacheinfügen.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9477248/FehlerDumpFacheinfugen.txt)

**Comment by AnneSchueller** [comment]
Ich kann das leider nicht reproduzieren. Bei mir klappt alles, sowohl bei vollständiger Angabe aller Spalten als auch wenn ich Spalten teilweise leer lasse. 
Ich habe auch mit einer BK-DB getestet.

**Comment by AnneSchueller** [comment]
Ich habe das gerade mal für einen vergangenen Lernabschnitt getestet. Da funktioniert es tatsächlich nicht. Im aktuellen Lernabschnitt klappt das bei mir.

**Comment by JuergenRichter** [comment]
Behoben
