### ISSUE TITLE
Doppeltes Fach in Leistungsdaten fehlt in der Übersicht

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#372]
### Version 3.0.41.7

Die Noten unter Akt. Halbjahr/Leistungsdaten:
![grafik](https://user-images.githubusercontent.com/44644567/188125663-b92c6cb1-615a-44d6-9ec1-88b59cab26d7.png)

Das wird in der Übersicht angezeigt:
![grafik](https://user-images.githubusercontent.com/44644567/188125964-a4b04e15-e848-4c05-87de-0bc49785ef40.png)

**Comment by AnneSchueller** [comment]
Ich habe das gerade mal in Schild2 getestet. Da funktioniert das auch nicht. Es wird in der Übersicht nur das erste Fach der Liste angezeigt (Test nur mit einer Gym-DB). Die Frage wäre hier, ob es zweimal das gleiche Fach mit Kursbezeichnung PUK geben darf? Am Gymnasium fällt mir kein Spezialfall ein. 
Wie ist das am BK?

**Comment by EwaldReinhardt** [comment]
Das Problem ist, dass es auf dem Zeugnis doppelt erscheint, wenn es unter Leistungsdaten 2x steht.
So könnte es wenigstens auch in der Übersicht auffallen, wenn es dort auch doppelt gelistet ist.

Ein Fach nur einmal zulassen unter Leistungsdaten könnte für manche Datenbanken bei der Migration zu Datenverlust
führen, wenn das BKs genutzt haben um (Bündel-)Fächer, die im Klassenverband von **mehreren** Lehrern unterrichtet wurden, zum erfassen von Leistungsdaten (über SchILDweb) genutzt haben.

**Comment by JuergenRichter** [comment]
Auf den Leistungsdaten ist ja folgender Index drauf:
![image](https://user-images.githubusercontent.com/61280188/191001303-1c2cd04d-3a33-4b6d-a87e-09a4a8474477.png)

Der sollte eigentlich verhindern, dass z.B. der Fall "Fach kommt bei einem Schüler in einem Abschnitt mit gleicher Lehrkraft, Kursart und Kurs mehrfach vor" nicht möglich ist.

In SchILD2 enthielt dieser Index aber nicht die Lehrkraft:
![image](https://user-images.githubusercontent.com/61280188/191004596-c873b62e-3a28-4ecf-b4a7-873033889cef.png)
Weshalb ein solcher Fall in der Übersicht auch (noch) nicht berücksichtigt ist (kommt aber).

Es scheint aber auch so zu sein, dass die verschiedenen Datenbanksystem die Definition des Index etwas unterschiedlich "verstehen", wenn einige Felder, die im Index enthalten sind, einen NULL-Wert haben. 

Beispiel MSSQL:
Doppeltes Fach (mit NULL-Wert in Lehrkraft, Kursart und Kurs) wird nicht akzeptiert:
![image](https://user-images.githubusercontent.com/61280188/191005300-1a9e2cf5-828c-40e3-95f3-8e79ebf3a676.png)

MariaDB (abr auch Access verhält sich so)
Gleicher Fall wird akzeptiert
![image](https://user-images.githubusercontent.com/61280188/191005463-817fd0e6-fb54-4ba0-b12a-b418e1b00eaa.png)

**Comment by JuergenRichter** [comment]
Korrektur:
Statt "Doppeltes Fach (mit NULL-Wert in Lehrkraft, Kursart und Kurs) wird nicht akzeptiert" muss es heißen:
Doppeltes Fach (mit NULL-Wert in Lehrkraft und Kurs) wird nicht akzeptiert.

Man kann in SchILD3 auch ein Fach ohne Angaben zu Lehrkraft, Kursart und Kurs beliebig oft anlegen
![image](https://user-images.githubusercontent.com/61280188/191006277-a16408c4-fe1a-4716-aafc-c2a9234aecfd.png)
Ob das sinnvoll ist, stelle ich mal dahin.
Bei einer MSSQL-DB in SchILD2 ist das nicht möglich.

**Comment by JuergenRichter** [comment]
In der Übersicht werden die Fächer nun auch als getrennte Teilen ausgegeben, wenn die Lehrkraft unterschiedlich ist

**Comment by FrodBRA** [comment]
@EwaldReinhardt Besteht das Problem noch oder wurde es gelöst?

**Comment by EwaldReinhardt** [comment]
Es ist auf jeden Fall kein kritisches Problem, da das eher nicht vorkommen sollte
ein Fach doppelt auf dem Zeugnis zu haben. 
Bei unterschiedlichen Lehrern wird ja jetzt auch eine Ausgabe gemacht.
Daher könnte man das schließen.

**Comment by FrodBRA** [comment]
@AnneSchueller Siehe oben, bitte schließen.
