### ISSUE TITLE
Anzeige akt.Halbjahr nicht immer passend zum ausgewählten Abschnitt

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#373]
### Version 3.0.41.7
1. Die Daten im aktuellen Halbjahr sind leer!
![grafik](https://user-images.githubusercontent.com/44644567/188126941-546fad67-912b-4045-b8ce-8bcd0b26a6e6.png)

2. Wähle einen alten Abschnitt mit Leistungsdaten:
![grafik](https://user-images.githubusercontent.com/44644567/188126847-e36fe608-2390-4a41-8b01-d3edc6160d49.png)

3. Wechsle z.B. auf Übersicht
![grafik](https://user-images.githubusercontent.com/44644567/188127437-4ad0c389-cd27-4c82-8af7-9a9423145044.png)

4. Wechsle zurück auf Akt. Halbjahr: Jetzt ist der akt. Abschnitt gewählt, aber der rechte Bereich ist nicht aktualisiert
![grafik](https://user-images.githubusercontent.com/44644567/188126977-dc6b6632-cbac-4f69-b99d-b08aa2bc39bb.png)

**Comment by AnneSchueller** [comment]
Weißt du noch, wie du auf die Ansicht des leeren aktuellen Halbjahres gekommen bist? 
Ich hab das bei mir jetzt mehrfach versucht zu reproduzieren, indem ich von einem Schüler auf den anderen, von einem Lernabschnitt zum anderen oder bei den Reitern hin und her geswitcht habe, aber bei mir stehen dort immer die Leistungsdaten drin.

**Comment by EwaldReinhardt** [comment]
Ja.
Im aktuellen Halbjahr 22/23#1 habe ich noch keine Fächer zugewiesen. Das Halbjahr wähle ich aus, dann sieht es so aus
wie unter 1. 
Dann zum Abschnitt 21/22#2 wechseln, der die Noten vom letzten Zeugnis enthält. Dargestellt in 2.
Jetzt auf einen anderen Tab wechsel.
Beim Zurückwechseln auf den Tab Akt. Halbjahr wird jetzt in der Abschnittsliste der akt. Abschnitt entsprechend ID1 angezeigt aber eben immer noch die Noten aus dem letzten Halbjahr. Zu sehen in 4.

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Erst nach einem Neustart sind die Fächer wieder weg.

**Comment by JuergenRichter** [comment]
Behoben
