### ISSUE TITLE
Anzuzeigenden Abschnitt in Akt. Halbjahr unabhängig von ID 1 festlegen

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#374]
### Version 3.0.41.7

bisher wird beim Wechsel auf den Tab. Akt. Halbjahr immer der Abschnitt ausgewählt,
der beim Schüler unter Individualdaten I eingestellt ist. 
Das passiert auch, wenn der Reiter Akt. Halbjahr aktiv ist und der Schüler gewechselt wird.

Der Wechsel auf das akt. Halbjahr sollte IMHO unterbleiben, wenn die Reiter gewechselt werden.

Hierüber kann man sicherlich diskutieren:
Beim Wechsel des Schülers würde ich mir die Möglichkeit wünschen, dass man das Verhalten
so einstellen kann, dass ein Halbjahr vorgegeben wird. Wenn dieses beim Schüler nicht vorhanden
ist, wird das unter ID1 eingetragene angezeigt.

**Comment by AnneSchueller** [comment]
Ich kann den Wunsch gut nachempfinden. Vor allem wenn man mal schnell mit den Pfeiltasten ein paar ausgewählte Schüler durchgehen möchte und sich Einträge aus vergangenen Anschnitten anschauen möchte ist das sehr lästig immer wieder den entsprechenden Abschnitt auszuwählen.
Auf der anderen Seite empfinde ich das auch als Schutz. Normalerweise trägt man ja Daten vom aktuellen Abschnitt ein. Wenn man vergisst den Abschnitt wieder auf das Aktuelle zu stellen (und ich könnte mir vorstellen, dass das recht häufig der Fall wäre) trägt man an der falschen Stelle Daten ein.
Ich notiere mir das aber auf jeden Fall auf meine "Nice to Have-" Liste, die ich abarbeite, sobald alle störenden Bugs beseitigt sind.

**Comment by EwaldReinhardt** [comment]
Der Wechsel sollte aber nur passieren, wenn der Schüler gewechselt wird und nicht, wenn ich nur die Reiter bei einem Schüler kurz hin und her wechsele.

**Der Wechsel auf das akt. Halbjahr sollte IMHO unterbleiben, wenn die Reiter gewechselt werden.** (ohne Schülerwechsel)
