### ISSUE TITLE
SchILD 3.0 V0.45 Gliederungsbezeichnungen beim Gymnasium

### ISSUE THREAD

**Issue by MichaelPeters1983** [SVWS-NRW/Schild3-BetaTest#375]
Bei Verwaltung > Schule >Allgemeine Angaben lässt sich die Gliederung beim Gymnasium zwar mit G8 und G9 anzeigen. EIne BEzeichnung wird nicht angezeigt. Wenn man es ändern will, werden die vier Änderungsmöglichkeiten alle zusammen angesprochen und eine Änderung ist unmöglich. (Alles in V. 0.45) 
![grafik](https://user-images.githubusercontent.com/111509114/188680756-6a43beaf-4108-4dbf-b684-98021e715937.png)

**Comment by AnneSchueller** [comment]
Bei mir sieht es ebenfalls so aus wie bei Herrn Peters. Ich arbeite mit der Server-Version 0.2.13.
Ich kann bei mir gar keine Gliederung auswählen. Das Feld ist leer. Daher hab ich auch nichts zum löschen. Ich kann dort einen Doppelklick drauf machen. Dann steht dort Aufbaugymnasium aber ohne das Kürzel. Daher wird die Bezeichnung "Aufbaugymnasium" auch wieder automatisch gelöscht

**Comment by JuergenRichter** [comment]
Ich habe die Version 0.2.10, ich vermute, dass da bei der Migration nun etwas anders läuft. Können Sie mir nochmal den Link für das aktuelle Setup für den SVWS-Server geben?

**Comment by FPfotenhauer** [comment]
0.2.13 liegt auf dem Server.
Wenn Sie eine aktuelle Schild3 machen, dann mach eich auch nochmals eine aktuelle SVWS-Version.

**Comment by JuergenRichter** [comment]
Da scheint ein Fehler im SVWS-Server 0.2.13 zu sein. Wenn ich da in der Tabelle "Statkue_Gliederung" auf die Schulfom GY filtere, erhalte ich folgende Einträge:

![image](https://user-images.githubusercontent.com/61280188/191236383-a23f403d-1aa8-4c07-9fa7-09d2d7a45f0c.png)

Zum Vergleich das gleiche aus der Statkue.mdb für SchILD2:
![image](https://user-images.githubusercontent.com/61280188/191236519-32ab4ac7-1e2c-4bcc-905e-c9f228bc99e4.png)

**Comment by JuergenRichter** [comment]
In SchILD werden derzeit auch die Felder "BKAnlage" und "BKTyp" verwendet, daraus wird das Kürzel gebildet
Beispiel:
BKAnlage=G
BKTyp=Y9

ergibt GY9

**Comment by MichaelPeters1983** [comment]
Mit den neuesten Versionen von SVWS-Server (0.2.14) und Schild 3.0 (0.0.46) ist das Problem weiterhin da.

**Comment by JuergenRichter** [comment]
Haben Sie mal neu migriert? Ich vermute, dass das Problem bei der Migration auftritt.

**Comment by ThomasBachran** [comment]
Das Problem ist bei Anpassungen der Statkue-Tabellen zustande gekommen. In den neueren Versionen des SVWS-Servers sind die alten Statkue-Tabellen durch Views für die Kompatibilität ersetzt worden. Bei der View für die Gliederungen ist mit für die nicht-BK-Schulformen ein Fehler für die Spalten BKAnlage und BKTyp unterlaufen, so dass dies derzeit nicht ganz kompatibel ist. Das wird mit der nächsten Version des SVWS-Servers dann behoben sein.

**Comment by JuergenRichter** [comment]
Wie heißt denn der View? Im Prinzip könnte man auch direkt auf die neue tabellenstruktur zugreifen. Wie sieht die denn aus?

**Comment by FPfotenhauer** [comment]
Die Views heißen genau wie die alten Tabellen, damit Schild gar nicht merkt, dass sich im Hintergrund was geändert hat.
Wir haben fast alle StatkueTabellen in CoreTypes gewandelt damit wir die besser an die WepApp übergeben können.

**Comment by FPfotenhauer** [comment]
Sollte im nächten Update behoben sein.

**Comment by JuergenRichter** [comment]
Ich habe heute mit Herrn Bachran abgesprochen, dass wir das Laden der zu einer Schulform gehörenden Gliederungen mal als erste Anwendung für die Nutzung der API umsetzen werden. Ich muss mich da etwas einarbeiten, denke aber, dass wir Ende nächster Woche ein erstes Ergebnis haben werden.

**Comment by FPfotenhauer** [comment]
Es wird ja beim Start auf eine Verbindung geprüft.
Bei fehlender Verbindung, sollte eine entsprechende Meldung kommen.
Ist es denkbar, dann in einen "Nur-Lese-Modus" zu schalten? Oder soll Schild3 dann gestoppt werden?
Die Verbindung zum SVWS-Server benötigen wir ja in jedem Fall!

Wir würden dann einen SVWS-Server bauen, der möglichst viele Kataloge schon über die API anbietet.
Diese würden wir dann zunächst nur Herrn Richter zur Verfügung stellen, als "Arbeitsversion", um Kataloge umzustellen.

**Comment by JuergenRichter** [comment]
"Oder soll Schild3 dann gestoppt werden?"
Im Moment ist das m.E. noch nicht notwendig. Auf die Tabelle (bzw. View) der Gliederungen wird ja explizit nur beim Hinzufügen einer Gliederung bei den Schuldaten zugegriffen. Bei anderen Tabellen ist das aber anders, z.B. Statkue_Nationalitaeten. Bei den Schülerdaten wird ja nur das Kürzel gespeichert, zum Ermitteln des Klartextes wird auf die Tabelle (bzw. den View) zugegriffen. Wenn das durch einen API-Aufruf ersetzt wird, dieser aber nicht funktioniert, werden keine Klartexte bei den Staatsangehörigkeiten angezeigt.

**Comment by JuergenRichter** [comment]
Frage: Wäre es möglich, den API-Aufruf etwas zu ändern? Derzeit lautet dieser die Schulgiederungen ja
https://localhost/db/{schema}/schule/schulformen
Dabei wird aber nicht der Katalog der Schulgliederungen der Schule geliefert (was der Tabelle EigeneSchule_Schulformen entsprechen würde), sondern im Prinzip der Inhalt der Tabelle "Statkue_Gliederungen". 

Bei anderen Aufrufen ist es so, dass ein "statistik" am Ende steht, wenn im Prinzip der Inhalt der "Statkue"-Tabelle geliefert wird, z.B.
https://localhost/db/{schema}/schule/foerderschwerpunkte/statistik
Der "schuleigene Katalog" hat dagegen keine /statistik-Endung
https://localhost/db/{schema}/schule/foerderschwerpunkte

**Comment by ThomasBachran** [comment]
Beim SVWS-Client werden die Pfade direkt in der Client-Bibliothek gesetzt, so dass wir bisher auf einen komplett sinnvollen Namensraum für die Pfade nicht wirklich geachtet haben. Es macht sicherlich Sinn Daten, die allgemein und damit "schul-unabhängig" sind, von den "schul-spezifischen" Daten zu trennen. Der Begriff "statistik", der bisher verwendet wurde, ist hier aber etwas ungünstig gewählt. Wir planen daher folgende Benennungen:
- Allgemeine Daten enthalten in dem jeweiligen Bereich ein Pfad-Elemente ".../allgemein/...", so dass die Daten als "schul-unabhängig" zu erkennen sind.
- Bei "schul-spezifischen" Daten fehlt dann dieses Pfad-Element.

Spricht aus Ihrer Sicht etwas gegen eine solche Benennung oder haben Sie einen Verbesserungsvorschlag? Wenn nicht würde ich für die nächste Version des SVWS-Servers die Umbenennung der Pfade entsprechend vornehmen.

**Comment by JuergenRichter** [comment]
Kein Problem. Wann ist die nächste Version des SVWS-Servers denn geplant?

**Comment by ThomasBachran** [comment]
Soll das zum Testen zeitnah erfolgen?

**Comment by JuergenRichter** [comment]
Ist nicht notwendig, die Änderung betrifft ja nur eine Zeile im Programmcode, das kann dann auch schnell gemacht werden, wenn es soweit ist.

**Comment by ThomasBachran** [comment]
In der nächste Version wird die Schnittstellen-Defintion wie folgt angepasst:
https://github.com/SVWS-NRW/SVWS-Server/blob/dev/svws-openapi/src/main/java/de/nrw/schule/svws/api/server/APISchule.java

Die dort angegenen Kataloge unter dem Pfad ".../allgemein/...", können gerne schon über die API genutzt werden.

**Comment by JuergenRichter** [comment]
Ich habe jetzt noch weitere "ASD-Kataloge" auf API-Aufrufe umgesetzt. Dabei ist mir aufgefallen, dass folgende Aufrufe m.E. inkonsistent sind:

https://localhost/db/svwsdb-gs/kataloge/faecher
Das ist ja im Prinzip der Inhalt von ZulFächer aus der Statkue, müsste m.E. also auch über /allgemein aufgerufen werden

Gleiches gilt für
https://localhost/db/svwsdb-gs/kataloge/jahrgaenge
https://localhost/db/svwsdb-gs/kataloge/klassenarten
https://localhost/db/svwsdb-gs/kataloge/kursarten
https://localhost/db/svwsdb-gs/kataloge/organisationsformen

**Comment by JuergenRichter** [comment]
In der neuen Version fehlt ja in der Datenbank die Tabelle "Statkue_Strassen", ich kann diese auch mal durch einen API-Aufruf ersetzen (mal sehen, wie da das Geschwindigkeitsverhalten ist). Da ist m.E. der API-Aufruf aber auch inskonsistent.
https://localhost/db/svwsdb-gs/kataloge/strassen

**Comment by ThomasBachran** [comment]
Bisher habe ich nur die Pfade unterhalb der Pfadelements "schule" an die neue Benennung angepasst. Die anderen werden nach und nach folgen. 
Das Pfadelement "kataloge" wird auch perspektivisch ausgedünnt, da einige der Enpdunkte unter andere Pfadelemente gehören (z.B. klassenarten, kursarten, jahrgaenge, ...). Hier wäre eine Umbenennung des Pfadelements "kataloge" nach "allgemein" auch sinnvoll.
Mein Vorschlag: Bereiten Sie die Umstellung vor und schreiben sie mir, welche Kataloge Sie bereits umsetzen wollen. Ich würde dann jeweils den Pfad anpassen, eine Folgeversion erstellen und diese Ihnen dann mit den angepassten Pfade zukommen lassen. Ist die Vorgehensweise für Sie so in Ordnung?

**Comment by JuergenRichter** [comment]
Ich schlage vor, dass ich erst mal eine Reihe von API-Umstellungen mache (mit den bisherigen Aufrufkonventionen), die Umstellung auf neue URLs ist danach recht schnell gemacht. Ich werde dann ca. Mitte nächster Woche mal eine Liste der Änderungen hier einstellen, dann kann man nachfolgend diese im SVWS-Server ändern.

**Comment by JuergenRichter** [comment]
Ich schlage vor, dass ich erst mal eine Reihe von API-Umstellungen mache (mit den bisherigen Aufrufkonventionen), die Umstellung auf neue URLs ist danach recht schnell gemacht. Ich werde dann ca. Mitte nächster Woche mal eine Liste der Änderungen hier einstellen, dann kann man nachfolgend diese im SVWS-Server ändern.

**Comment by ThomasBachran** [comment]
Ok... Ich kann die Umstellung dann aber auch schon parallel vorbereiten...

**Comment by ThomasBachran** [comment]
In der nächsten Version des SVWS-Servers der zusammengestellt wird sind dann die folgenden Anpassungen bereits enthalten:
- die Namenskonvention für die Pfade wurde angepasst
- Viele der Schild-Intern-Daten stehen für die API unter dem Pfadelement "schild" zur Verfügung. 
- Andere Schild-Intern-Kataloge sind im SVWS-Servers bereits integriert und brauchen daher nicht als Schild-Intern zur Verfügung gestellt werden, da sie auch noch mehr Informationen beinhalten bzw. zusammenführen.
- (Die KAoA-Daten werden später von mir umgesetzt und direkt in Datenstrukturen für den SVWS-Server integriert. Anschließend werde ich dort auch noch eigene API-Endpunkte erzeugen.)
- Die Schild-Intern-Tabellen "VerfImportTabellen", "VerfImportFelder" und "ZusatzInfos" habe ich erstmal nicht über die API zur Verfügung gestellt. Werden die in Schild 3 überhaupt noch benötigt? Sollten die zum Winschild-Import gehören könnte man diesen nach meiner Einschätzung aus Schild 3 entfernen...

**Comment by JuergenRichter** [comment]
Die Tabellen "VerfImportTabellen" und "VerfImportFelder" werden von dem Zusatzprogramm "EXternImport.exe" verwenden, mit dem man aus Textdateien Daten importieren kann (allerdings nur Schüler-Stammdaten und Daten der Erziehungsberechtigten) . Die Tabellen enthalten die Tabellennamen und Feldnamen, die grundsätzlich für den Import zur Verfügung stehen. Es ist die Frage, ob dieses Programm erhalten bleiben soll (das dann an die neue Datenbankstruktur angepasst werden müsste) oder ob man sich auf den Standpunkt stellt, dass das nicht schon durch die Schnittstellen-Dateien abgedeckt wird (mit denen man fast alles importieren kann, nicht nur Stamm- und Erzieherdaten).

Die Tabelle "ZusatzInfos" wird nicht mehr benötigt. Da wurde mal gspeichert, in welchen BK-Gliederungen welche Jahrgäng die Abschlussjahrgänge sind.

Ich habe übrigens jetzt auch das Laden der Straßen über einen API-Aufruf umgesetzt, geht erstaunlich schnell, auch der Filtervorgang im Programm (es sollen ja nur die Straßen des Wohnortes angezeigt werden).

**Comment by FPfotenhauer** [comment]
> Ich habe übrigens jetzt auch das Laden der Straßen über einen API-Aufruf umgesetzt, geht erstaunlich schnell, auch der Filtervorgang im Programm (es sollen ja nur die Straßen des Wohnortes angezeigt werden).

Sehr gut, da bin ich gespannt.



> Es ist die Frage, ob dieses Programm erhalten bleiben soll (das dann an die neue Datenbankstruktur angepasst werden müsste) oder ob man sich auf den Standpunkt stellt, dass das nicht schon durch die Schnittstellen-Dateien abgedeckt wird

Das Programm ist schon sehr nützlich, aber ich würde es bevorzugen, wenn wir das zunächst nicht mehr anbieten und dann ggf. gemeinsam über eine Importmöglichkeit beraten, die diese Funktionalität ersetzen kann. Die Schnittstelle Schild-NRW ist ja erstmal da...

**Comment by JuergenRichter** [comment]
Mir ist in Verbindung mit den "REST-Tests" ein Fehler in der Tabelle  "SchuelerMerkmale" aufgefallen. Dort ist derzeit der Primärschlüssel auf "Schueler_ID", das verhindert aber, dass zu einem Schüler mehrere Merkmale hinterlegt werden können (was vorkommt). Der Primärschlüssel müsste m.E. auf "ID" liegen und ein Unique-Index auf "Schueler_ID, Kurztext"

**Comment by JuergenRichter** [comment]
Ich könnte jetzt mal eine Version bereitstellen, bei der die folgenden "ASD-Kataloge" auf API-Aufrufe geändert wurden
-Schulgliederungen
-Förderschwerpunkte
-Verkehrssprachen
-Nationalitäten
-Straßen
-Konfessionen
-allgem. Merkmale

Es werden dabei aber die API-Aufrufkonventionen der Vers. 0.2.17 des SVWS-Servers verwendet. Falls in Kürze eine neuere Version kommen sollte, würde ich vorschlagen, die Aufrufe vorher entsprechend im Programm anzupassen.

**Comment by ThomasBachran** [comment]
> Mir ist in Verbindung mit den "REST-Tests" ein Fehler in der Tabelle "SchuelerMerkmale" aufgefallen. Dort ist derzeit der Primärschlüssel auf "Schueler_ID", das verhindert aber, dass zu einem Schüler mehrere Merkmale hinterlegt werden können (was vorkommt). Der Primärschlüssel müsste m.E. auf "ID" liegen und ein Unique-Index auf "Schueler_ID, Kurztext"

Ich werde das entsprechend anpassen. Eine Frage noch dazu: Ist Kurztext eine Fremdschlüssel auf EigeneSchule_Merkmale.Kurztext? Falls ja, dann könnte man den Kurztext hier auch austauschen gegen die entsprechende ID des Katalogs und darauf den Fremschdschlüssen setzen...

**Comment by ThomasBachran** [comment]
> Ich könnte jetzt mal eine Version bereitstellen, bei der die folgenden "ASD-Kataloge" auf API-Aufrufe geändert wurden -Schulgliederungen -Förderschwerpunkte -Verkehrssprachen -Nationalitäten -Straßen -Konfessionen -allgem. Merkmale
> 
> Es werden dabei aber die API-Aufrufkonventionen der Vers. 0.2.17 des SVWS-Servers verwendet. Falls in Kürze eine neuere Version kommen sollte, würde ich vorschlagen, die Aufrufe vorher entsprechend im Programm anzupassen.

Eine neue Version wird in Kürze kommen. Daher lohnt es sich diese abzuwarten...

**Comment by FPfotenhauer** [comment]
0.2.18 liegt auf dem FTP-Server.
Wenn es eine Schild3-Version gibt, die damit funktioniert, kann ich das für alle zur Verfügung stellen.

**Comment by JuergenRichter** [comment]
"Ist Kurztext eine Fremdschlüssel auf EigeneSchule_Merkmale.Kurztext?"
So ist es. Kann man natürlich auch auf die ID des Merkmals umstellen. Der Kurztext ist halt damals gewählt worden, weil der auch so in der Statkue-Tabelle enthalten ist (vergleichbar mit den Kürzeln der Staatsangehörigkeit, Verkehrsprachen usw.). Allerdings wird bei Umstellung auf die Merkmal-ID die Aufbereitung der Statistik etwas aufwändiger, da in bestimmten Fällen Prüfungen notwendig sind (z.B OFFGANZ in Vergleich mit der Klassenorganisationsform).

**Comment by ThomasBachran** [comment]
> Noch ein Hinweis: Bei "ein Unique-Index auf "Schueler_ID, Kurztext" war ich etwas vorschnell, eigentlich müsste das m.E. "und ein Unique-Index auf "Schueler_ID, Kurztext,DatumVon" heißen. Es kann ja auch sein, dass ein Schüler z.B. in der Übermittagsbetreuung war, dann abgemeldet wurde (DatumVon und DatumBis gefüllt) und dann nach einer gewissen Zeit wieder angemeldet wurde (mit neuem Datensatz und gleichem Merkmal).

Dann lohnt sich hier keine Unique-Constraint. Also lasse ich diese dann weg...
