### ISSUE TITLE
Export ENM Fehlermeldung (V.0.45)

### ISSUE THREAD

**Issue by MichaelPeters1983** [SVWS-NRW/Schild3-BetaTest#376]
Bei KLicken auf Verwaltung > Export > Externes Notenmodul erscheint 
![grafik](https://user-images.githubusercontent.com/111509114/188682077-c1e0933b-dc50-47b6-8a63-ab8754483bc8.png)

**Comment by AnneSchueller** [comment]
@JuergenRichter : Dieser Export ist noch nicht implementiert oder?

**Comment by FrodBRA** [comment]
@AnneSchueller

Entsprechend der Diskussion zu https://github.com/SVWS-NRW/Schild3-BetaTest/issues/350 schlage ich vor, dieses Issue ebenfalls zu schließen. 

Das ENM wird bei Erscheinen des ENM getestet.

**Comment by AnneSchueller** [comment]
Danke für den Hinweis. Schließe ich
