### ISSUE TITLE
Fehler beim Start - #42S02Table 'svwsdb. v_benutzerdetails' doesn't exist.

### ISSUE THREAD

**Issue by JanLindnerWKPB** [SVWS-NRW/Schild3-BetaTest#377]

**Comment by JanLindnerWKPB** [comment]
Hallo,
ich habe eine Schild3.0 und SVWS normal ans Laufen bekommen (ohne Datenbank).
Wenn ich (bei einer KOMPLETTEN Neuinstallation) unsere Datenbank migriere, bekomme ich die im Titel genannte Fehlermeldung.

![grafik](https://user-images.githubusercontent.com/113019686/188841706-2c87c683-c459-4af5-ae6e-3fa0a42366d5.png)

**Comment by JanLindnerWKPB** [comment]
Schulform ist Weiterbildungskolleg

**Comment by AnneSchueller** [comment]
Hallo Jan,

Hattest du während der Installation bereits eine Migration durchgeführt?
Hast du nach der Installation als Administrator das Migrationstool aus dem Ordner Schild3 gestartet?
Wenn du noch keine Migration während der Installation durchgeführt hast musst du hier den Expertenmodus wählen. Bist du soweit gekommen wie auf dem Bild hier und konntest die Migration "Fertigstellen"? 

![Bild2](https://user-images.githubusercontent.com/79116896/189123509-bc6351e4-8b7f-4c9d-939f-127c874abef9.png)

**Comment by JanLindnerWKPB** [comment]
Hallo,
ich habe während der Installation bereits eine Migration durchgeführt.
Nach der Installation habe ich keine Migration durchgeführt.

**Comment by AnneSchueller** [comment]
War diese Installation erfolgreich? Wenn nicht: Hast du das Migrationsprotokoll noch?
Ansonsten muss noch die sdbcfg-Datei angelegt werden. Also wurde auch dieser Schritt hier nach der Installation durchgeführt?
![Bild1](https://user-images.githubusercontent.com/79116896/189365370-3c21e3b2-c8c3-4f78-92de-bce2c9447f5c.png)

War danach der Verbindungstest erfolgreich?

**Comment by JanLindnerWKPB** [comment]
Bei der SVWS-Installation stand zum Schluss Folgendes:
![Bild1](https://user-images.githubusercontent.com/113019686/189366990-010481fd-3411-4c0d-9512-b4d67197f934.png)

Die sdbcfg-Datei wurde angelegt, der beschriebene Schritt also durchgeführt.

**Comment by JanLindnerWKPB** [comment]
Ich habe das Gefühl, dass bei der SVWS-Installation (samt Migration) zum Schluss noch ein paar Schritte fehlen, weiß aber nicht, warum diese nicht durchgeführt werden.

**Comment by JanLindnerWKPB** [comment]
![Bild4](https://user-images.githubusercontent.com/113019686/189369667-c7ec6690-7396-4ac6-8a84-5dc52d863fea.png)

**Comment by JanLindnerWKPB** [comment]
![Bild5](https://user-images.githubusercontent.com/113019686/189369690-6e1d7d2c-3cd1-4239-be6e-97659f69bb79.png)

**Comment by JanLindnerWKPB** [comment]
![Bild3](https://user-images.githubusercontent.com/113019686/189369750-0c1d4379-20f6-4ade-a2dd-02135d2072e2.png)

**Comment by FPfotenhauer** [comment]
Bitte mal die Log-Dateien von der Migration zur Verfügung stellen.
Nicht hier! Da können u.U. sensible Daten drin sein!

**Comment by ThomasBachran** [comment]
Das Problem ist hier die Groß- und Kleinschreibung bei der Datenbank-View. Diese heißt korrekt `V_BenutzerDetails` und wird auch korrekt erstellt. Ich vermute mal, dass der Datenbank-Server auf einem Linux-System läuft.

@JanLindnerWKPB : Ist das korrekt?

Für den SVWS-Server habe ich die Große- und Kleinschreibung geprüft und keinen Fehler gefunden. Das Problem mit der Groß- und Kleinschreibung entsteht dadurch, dass unter Windows alle Tabellennamen - unabhängig von den SQL-Datenbank-Befehlen - in Kleinschreibung angelegt und genutzt werden. Hier treten dann also keine Fehler auf. Bei Linux ist die Groß- und Kleinschreibung jedoch wichtig und es kommt zu Fehlern.

@JuergenRichter: Können Sie bitte prüfen, ob die Schreibweise im Schild3-Client in dem obigen Fall korrekt ist?

**Comment by JanLindnerWKPB** [comment]
@ThomasBachran : Die Migration wurde an einem Einzelplatzrechner mit Windows10 durchgeführt.

@FPfotenhauer : Wo finde ich die LogDatei der Migration?

**Comment by FPfotenhauer** [comment]
User/ProgrammData/SVWS-Server/logs

**Comment by JanLindnerWKPB** [comment]
@FPfotenhauer : Soll ich die an support@schild.nrw.de schicken?

**Comment by FPfotenhauer** [comment]
Einfach an mich bitte.

**Comment by JanLindnerWKPB** [comment]
@FPfotenhauer : Habe es an  frank.pfotenhauer@msb.nrw.de gesendet.

**Comment by JuergenRichter** [comment]
Der in SchILD3 verwendete SQL-Befehl lautet:
select * from V_BenutzerDetails where Typ in (0,1)

**Comment by FPfotenhauer** [comment]
Im LoG sieht man, dass die MDB überhaupt nicht migriert wird.
Ich vermute, dass das noch gar keine Access2000-MDB ist.
Der Fehler kommt einfach, weil die Tabelle nicht da ist und das die erste Tabelle ist, die aufgerufen wird.

**Comment by JanLindnerWKPB** [comment]
Die Tabelle wurde mit einem MigrationTool (SchildMigTool) aus unserer Datenbank erstellt.

**Comment by FPfotenhauer** [comment]
???
Das SchildMIgTool ist doch für Schild2.0 ???

**Comment by JanLindnerWKPB** [comment]
Damit wurde eine Access-Datenbank aus der Schild2.0-Datenbank (die im Format sdbcfg ist) generiert, um sie auf den Einzelplatz-Rechner zu bekommen.

**Comment by FPfotenhauer** [comment]
Bitte die Begriffe nicht durcheinander werfen und auch die Anleitung im FB-Bereich beachten.
Das Tool für Schild3.0 heißt MigrateDB.exe und wurde auch verwendet.
MigrateDB ruft auch nur den SVWS-Server zur Migration auf!
In dem Log-File sieht man, dass die AccessDB nicht geöffnet werden konnte.
Alles Weitere kann nur durch Untersuchung der AccessDB erfolgen.

**Comment by JanLindnerWKPB** [comment]
Nein, ich werfe die Begriffe nicht durcheinander.
Das Tool wurde durch unseren IT-Mann wirklich verwendet, um unsere Schild-2.0-Datenbank in das Access-Format zu bringen. Die Datei heißt SchildMigTool.
Danach habe ich MigrateDB.exe verwendet, um die Access-Datenbank auf dem Einzelplatzrechner zu SVWS zu migrieren.

**Comment by FPfotenhauer** [comment]
Wie gesagt. Die AccesDB ist defekt.
Warum wurde nicht direkt aus der bestehenden DB migriert?

**Comment by JanLindnerWKPB** [comment]
Weil der Einzeplatzrechner keinen Server-Zugang hat und mir nur diese Datei zur Verfügung gestellt wurde.
