### ISSUE TITLE
Sichtbare Spalten auswählen kann nicht ausgewählt werden

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#378]
Die Option, sichtbare Spalten im Schülercontainer auszuwählen wird nicht angezeigt, obwohl bei den Einstellungen das Häkchen gesetzt ist (Individuelle Gestaltung der Schüler-Übersichtstabelle ermöglichen)

**Comment by JuergenRichter** [comment]
Welche Spalten angezeigt werden sollen, wird jetzt bei den individuellen Einstellungen konfiguriert (unter "Verwaltung")

**Comment by AnneSchueller** [comment]
Danke, das hat funktioniert.
