### ISSUE TITLE
Karteikarte "Laufbahninfo"

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#38]
Bei Auswahl dieser Karteikarte kommt bei Blättern in der Schülerliste immer der Fehler

![Argument außerhalb des Bereiches](https://user-images.githubusercontent.com/62895389/101279309-b92ecd00-37c1-11eb-9c1d-c4148a04e2cd.JPG)

Hier die gespeicherte Detaibeschreibung des Fehlers:
[Argument außerhalb des Bereiches.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5648699/Argument.ausserhalb.des.Bereiches.txt)

**Comment by JuergenRichter** [comment]
Ich kann das Problem mit mehreren Datenbanken nicht reproduzieren. Wäre es möglich, mal eine zu bekommen, wo das Problem auftritt?

**Comment by FPfotenhauer** [comment]
Ich habe Ihnen eine GymAbi.zip auf den Server gelegt.
Die ist bei mir nach MariaDB migriert worde und zeigt auch das Problem.

**Comment by JuergenRichter** [comment]
Tritt bei mir mit Version 3.0.8 nicht mehr auf
