### ISSUE TITLE
Ansprechpartner der Telefonnummer taucht unter Individualdaten I nicht auf

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/Schild3-BetaTest#382]
Unter "Erz.Berechtigte/Telefonnummern" kann man mehrere Telefonnummern für einen Schüler angeben:
![Screenshot 2022-09-15 145223](https://user-images.githubusercontent.com/99047051/190414537-d1e3b312-7957-4c61-8312-2f449bbc5268.png)

Der Ansprechpartner ist nicht zu sehen, wenn man die gleiche Liste unter Individualdaten I - Zusatzdaten - Weitere Funktionen - Telefonnummern zeigen klickt:
![Screenshot 2022-09-15 145332](https://user-images.githubusercontent.com/99047051/190414837-05c226a7-2177-48f6-8136-247fe98165c4.png)
Bemerkungen kommen an.

**Comment by JuergenRichter** [comment]
Behoben
