### ISSUE TITLE
DSGVO-Einwilligungen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#383]
Version 3.0.42.7: Wenn ich unter Kataloge eine neue DSGVO-Einwilligung eingebe, dauert die Aktualisierung eine Eingabe 30 Sekunden und der Lüfter meines Laptops fängt zu laufen! Außerdem werden alle anderen Eingaben, die ich kurz vorher eingegeben hatte. erneut aktualisiert. Bei Schild2 läuft das viel schneller.

**Comment by JuergenRichter** [comment]
Korrigiert
