### ISSUE TITLE
Scrollen im Schülercontainer 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#384]
Scrollt man im Schülercontainer während das aktuelle Halbjahr ausgewählt ist, geht das sehr langsam und stockend. Schön wäre es, wenn man die Daten nur dann lädt, wenn man fertig ist mit Scrollen. So wie das auch bei den Individualdaten realisiert wird. Da klappt das Scrollen super.

**Comment by JuergenRichter** [comment]
Bei den Individualdaten ist das durch eine optimierte Abfrage geregelt. Es ist nämlich gar nicht so einfach, festzustellen, "wenn man mit scrollen fertig ist". Was die "abhängigen Daten" betrifft, so wurde bisher so vorgegangen
-Schülerdatensatz wird gewechselt
-Ist Karteireiter "Akt. Hj." ausgewählt?
-Wenn ja:
  - Lade alle Abschnittsdaten (Halbjahre) des Schülers
  - Gehe zum letzten Datensatz (akt. Halbjahr)
  - Lade die Leistungsdaten und Bemerkungen

D.h. die Leistungsdaten wurden beim Scrollen geladen (wenn "Akt. Halbjahr" ausgewählt ist), auch wenn möglicherweise der Unterkarteireiter "Allgemeine Angaben" ausgewählt war (die Leistungsdaten also nicht gezeigt wurden).

Das ist nun wie folgt geändert:
-Schülerdatensatz wird gewechselt
-Ist Karteireiter "Akt. Hj." ausgewählt?
-Wenn ja:
  - Lade alle Abschnittsdaten (Halbjahre) des Schülers
  - Gehe zum letzten Datensatz (akt. Halbjahr)
  - Ist Karteireiter "Leistungsdaten" ausgewählt?
  - Wenn Ja: Lade die Leistungsdaten 
  - Ist Karteireiter "Bemerkungen" ausgewählt?
  - Wenn Ja: Lade die Bemerkungen

Ich hoffe, dass das den Vorgang etwas beschleunigt, erfordert aber größeren "Prüfaufwand" im Programm, wenn die Karteireiter bei einem Schüler gewechselt werden. Der Fall "Karteireiter "Leistungsdaten" ist ausgewählt und durch die Schülermenge hin- und herscrollen" ist aber immer noch mit einem Zeitaufwand verbunden.
