### ISSUE TITLE
Aktuelle Schülerauswahl (Schnellfilter)

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#385]
Wenn man bei der aktuellen Schülerauswahl mehrere Klassen oder Jahrgangsstufen auswählt, muss man nach jeder Auswahl warten mit die Daten fertig geladen sind. Wäre es möglich, die Daten erst zu laden, wenn man mit der Auswahl fertig ist? Dann könnte man schnell mehrere Klassen auswählen und muss am Ende nur einmal warten bis die Daten geladen sind. 
An dieser Stelle vermisse ich auch manchmal einen "OK"-Button, aber das ist sicherlich Geschmackssache.

**Comment by EwaldReinhardt** [comment]
Siehe auch [#323](https://github.com/SVWS-NRW/Schild3-BetaTest/issues/323)

**Comment by JuergenRichter** [comment]
"An dieser Stelle vermisse ich auch manchmal einen "OK"-Button, aber das ist sicherlich Geschmackssache."
Ich habe da jetzt einen "Häkchen-Schalter" (wie bei der "SchILD2-Methode") umgesetzt, d.h. der Filter wird nicht mehr sofort ausgeführt, sondern erst wenn der Schalter betätigt wird
