### ISSUE TITLE
Benutzergruppe bearbeiten

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#386]
Hier fehlt die "Speichern-Schaltfläche". Wenn ich eine neue Gruppe anlege funktioniert das. Sobald ich die Berechtigungen (Status) anpasse, werden die Häkchen nicht gespeichert.

**Comment by AnneSchueller** [comment]
Ergänzung: Schließt man das Fenster "Benutzergruppe bearbeiten", öffnet es anschließend wieder und wählt Häkchen im Status aus, so werden diese auch gespeichert. Das sollte natürlich auch ohne schließen und öffnen funktionieren.

**Comment by JuergenRichter** [comment]
Ich kann das nicht reproduzieren, bei mir werden die Häkchen (auch bei nachträglicher Bearbeitung) gespeichert. Bitte noch mal Schritt für Schritt beschreiben, vielleicht habe ich es ja auch falsch verstanden.

**Comment by AnneSchueller** [comment]
Benutzer -> Benutzerverwaltung -> Benutzergruppen bearbeiten
Neue Gruppe -> Namen vergeben und auf ok
Häkchen bei Status anklicken
Fenster schließen
Wieder auf Benutzergruppe bearbeiten
Nun sind die Häkchen bei Status weg

**Comment by FPfotenhauer** [comment]
Wir können auch (bevor Sie da viel Arbeit investieren) über die Benutzerverwaltung reden.
Wir würden die sehr gerne schon zu uns in den SVWS-Server holen.
Dann ggf. einen Link für den Browser in Schild3 positionieren.
Vielleicht können wir das einmal diskutieren.

**Comment by JuergenRichter** [comment]
Ist schon behoben.
