### ISSUE TITLE
Benutzerverwaltung

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#387]
1. Ist es bewusst so realisiert, dass man DB-User nur mit der rechten Maustaste anlegen kann? Das könnte zu Irritationen führen. 
2. Die "Zurück-Schaltfläche" rechts unten finde ich bezüglich der Navigation inkonsequent, weil sie auf keiner anderen Seite zu finden ist. Man kommt ja auch so aus dem Fenster heraus. Insofern kann man darauf verzichten.
3. Bei meinen Benutzern steht bei allen der Benutzertyp "Allgemein", obwohl es alles Lehrer sind. Die Art kann ich im Nachhinein nicht mehr ändern. Wäre gut, wenn das beim Migrationsprozess noch optimiert wird.

**Comment by AnneSchueller** [comment]
Zu 1: Ja; Es wird noch ein Hinweis dazu erscheinen (im nächsten Update); Nähere Infos auch hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/349

Zu 2; Ich glaube der Button hängt damit zusammen, dass man für die Benutzerverwaltung nochmal explizit das Passwort angeben muss. Der "Zurück"- Button ist quasi eine Art "Ausloggen";  Der Text "Benutzerverwaltung abmelden" ist was lang. Vielleicht fällt jemandem noch was passenderes ein.


Zu 3: Wenn der Benutzername über "Lehrer übernehmen" eingepflegt wurde und der Benutzername dem Kürzel entspricht, sollte dort Lehrer stehen. Ansonsten allgemein. Zumindest würde das an meinen Beispieldatenbanken so passen. 
@JuergenRichter Es wäre gut wenn man das im Nachgang noch ändern könnte. Wir haben auch Lehrer eingepflegt die einen anderen Benutzernamen haben als ihr Kürzel.
