### ISSUE TITLE
Filterdefinition bearbeiten

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#388]
Wenn ich einen vorhandenen Filter unter "Filterdefinition bearbeiten" lösche und mit Ja bestätige, schließt sich das Fenster  "Filterdefinition bearbeiten". Wäre praktikabel, wenn das nach dem Löschen für weitere Löschungen offen bliebe.

**Comment by FPfotenhauer** [comment]
Bitte später nochmals öffnen.
