### ISSUE TITLE
Frame "Auswahl" zu klein

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#389]
Den Platz unter "Auswahl" im Frame rechts unten könnte man besser nutzen.
![schild_100](https://user-images.githubusercontent.com/78501680/190455965-ff93b085-4123-4ea3-a2af-6d8911b24dff.jpg)

**Comment by JeVaske** [comment]
Außerdem frage ich mich, warum sich das Fenster "Fehlende Abschnitte zeigen" nicht schließt.

**Comment by JuergenRichter** [comment]
Das Layout des Filterfensters wurde nochmal überarbeitet

**Comment by JuergenRichter** [comment]
"Außerdem frage ich mich, warum sich das Fenster "Fehlende Abschnitte zeigen" nicht schließt."

Welches Fenster ist da genau gemeint?
