### ISSUE TITLE
Erzieherdaten: Feld Erzieherart an einer ungünstigen Stelle im Adressbereich

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#39]
Ich habe gerade suchen müssen, um bei den Erziehern die Erzieherart zu finden. Die Erzieherart ist im Adressfeld untergebracht. Dass ist sehr verwirrend und überhaupt nicht intuitiv bei der Eingabe. Normalerweise müsste wie in Schild 2.0 erst eine Erzieherart eingetragen werden, sonst gibt es nur Probleme.
![image](https://user-images.githubusercontent.com/75179015/101290531-329adf80-3803-11eb-9f76-c17a69a3015d.png)

**Comment by JuergenRichter** [comment]
Ist in Folgeversion ander angeordnet
