### ISSUE TITLE
Filter II und Attributsfilter verschwunden

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#391]
Ich kann mich erinnern, dass Filter II und Attributsfilter ursprünglich in Schild3 vorhanden waren. Jetzt sind sie nicht mehr da. Falls darauf verzichtet wurde, ist die Schaltfläche "Filter I" überflüssig:
![Schild101](https://user-images.githubusercontent.com/78501680/190476074-92c10458-1a58-4f2a-b5e8-44f16bab4262.jpg)

**Comment by AnneSchueller** [comment]
Filter II und der Attributsfilter werden in Schild3 nicht mehr zur Verfügung stehen. Filter I wird jedoch um spezielle Suchanfrage erweitert. 
Die Schaltfläche "Filter I" wird daher nur benötigt, um von Schülergruppen zurück zum Filter zu springen.
