### ISSUE TITLE
SVWS Server Installation: Schema-Erstellung schlägt fehl.

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#392]
Leider ist es mir mit der aktuellen SVWS Version nicht möglich ein neues Schema bei der Installation anzulegen. Es tritt immer ein Fehler mit dem Hinweis auf, dass das Schema später angelegt werden sollte.

Das Problem habe ich sowohl auf meinem Stand-PC als auch auf dem Surface 8. Beides mit Win11. 

_Folgendes habe ich bereits versucht:_
- Mehrfache Installation als "Clean Install" nach Ausführung der delete_service.bat. Ergänzend habe ich die mir bekannten Registry-
  Einträge und alle noch vorhandenen Ordner entfernt. 
- Wahl mehrerer verschiedener Ports
- Ausstellen der Firewall

Langsam gehen mir die Ideen aus. Es ist mir auch nicht möglich mit Hilfe der migratedb.exe eine Migration durchzuführen, da auch diese mit dem Fehler "WSAECONNREFUSED (10061) Connection refused" abbricht.  

Hier mal ein Link zum Video der Deinstallation und Installation mit den beschriebenen Fehlern:
https://1drv.ms/u/s!AhXBnUC2fVl1wUSId-vmQgvlAYJS?e=lT96cH

_Bild vom Fehler bei der Installation von SVWS:_
[Fehler installation SVWS Server.pdf](https://github.com/SVWS-NRW/Schild3

_Logs aus ProgrammData:_
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9594984/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9594985/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9594986/svws_server_service.wrapper.log)
[2022_09_18.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9594987/2022_09_18.request.log)
-BetaTest/files/9594976/Fehler.installation.SVWS.Server.pdf)

**Comment by AnneSchueller** [comment]
Kannst du  mal prüfen, ob die Berechtigungen im Ordner ProgrammData->SVWS-Server und in den Unterordnern die Optionen "Ändern, Lesen, Ausführen, Schreiben" zugelassen sind?

**Comment by spechtg** [comment]
Erledigt. Alle Hacken gesetzt. Auch für die Unterordner.

**Comment by AnneSchueller** [comment]
@FPfotenhauer : Ich habe keine Idee mehr. Ich habe alle Schritte wie im Video von Gregor auf meinem Rechner durchgeführt (von der Deinstallation bis zur Installation) und es hat geklappt.

**Comment by FPfotenhauer** [comment]
Interessant ist, dass nach ausführen des DeleteServices.bat noch Dateien da sind un die Reg-Einträge.
Das wird offensichtlich nicht korrekt ausgeführt.

Es sieht m.E. so aus, als ob der MariaDB-Server nicht läuft. Ist Port 3306 überhaupt frei?

**Comment by FPfotenhauer** [comment]
Im Errorlog sieht man auch, dass der SVWS-Server mindestens einmal gekillt wird.
Ist denn der Webclient unter http://localhost/debug erreichbar ?

**Comment by spechtg** [comment]
Leider nein. Kommt nur ERR_CONNECTION_REFUSED

**Comment by FPfotenhauer** [comment]
https://localhost/debug

Sorry.

Aber dann läuft der SVWS-Server nicht.

**Comment by spechtg** [comment]
Port 443 wird aktuell nicht genutzt:

![Screenshot 2022-09-19 091857](https://user-images.githubusercontent.com/96472913/190967551-c4e1a3e0-93a5-4613-a46e-450f2ee8bcfd.jpg)

**Comment by FPfotenhauer** [comment]
Kommt man denn mit DBeaver auf die MariaDB?

**Comment by spechtg** [comment]
Die App habe ich aktuell nicht. Lade diese eben und schaue, ob es klappt

**Comment by AnneSchueller** [comment]
Hier mal eine Kurzanleitung zu DBeaver
[DBeaver_Howto.pdf](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9596867/DBeaver_Howto.pdf)

**Comment by FPfotenhauer** [comment]
Was steht in der svwsconfig.json?

Vorsicht, da stehen die Kennwörter drin! Wenn da etwa Geheimes drin ist, nicht hier posten.

**Comment by FPfotenhauer** [comment]
svws_server_service.err.log

Wird das voller oder bleibt das bei Zeile 19 stehen?

**Comment by spechtg** [comment]
Gib mir bitte ein Tipp, wo die svwsconfig liegt. Habe es auch mit der Suche nicht gefunden. 

Ich meine, dass Log wird voller: 
![Screenshot SVWS Err](https://user-images.githubusercontent.com/96472913/190973002-c5bca3fa-1f5e-45d2-b3ef-a301d6b5abfd.jpg)

**Comment by FPfotenhauer** [comment]
Im Ordner res, da wo auch die logs liegen.

Aber die wird wahrscheinlich nicht erzeugt.
Hier sieht man, dass der Keystore nicht erkannt wird.
Wurde der Ordner SVWS-Server unter ProgramData auch vor der Installation gelöscht?
Der muss unbedingt auch weg.

**Comment by spechtg** [comment]
Ja. Das hat die delete_service.bat erledigt. Rückstände gab es nicht.
Hier die svwsconfig: 
![svwsconfig](https://user-images.githubusercontent.com/96472913/190974098-b2d15cf2-b6ce-443d-824a-197d386f8733.jpg)

Mich irritiert dort das eingetragene TLS-Passwort. Habe ich nicht vergeben. Ist es durch das System gesetzt?

**Comment by FPfotenhauer** [comment]
Irgendwas klappt beim Erstellen des Keystore nicht.
Ich müsste mir das mal ansehen.

**Comment by spechtg** [comment]
Kein Problem. Bin jetzt gleich  bis heute Abend in einer Sitzung gebunden. Könnte dir morgen den Zugriff auf meinen Rechner geben. Willst du über Fast Viewer zugreifen?

**Comment by AnneSchueller** [comment]
Mir ist gerade noch aufgefallen, dass beim Ausführen der delete-services Datei der Ordner Programme/SVWS-Server nicht gefunden wird und somit auch nicht gelöscht wird. Daher musstest du ihn anschließend auch noch manuell löschen. Könntest du evtl. nochmal versuchen, alles zu löschen. Also nicht nur den Ordner Programme/SVWS-Server sondern auch den versteckten Ordner  ProgramData/SVWS-Server.

Allerdings ist mir ein Rätsel, warum die Ordner nicht gefunden werden.

**Comment by spechtg** [comment]
Das habe ich gestern Abend tatsächlich nochmal so versucht und explizit nach dem versteckten Ordner gesehen. Dieser war aber durch den delete_service entfernt worden.

**Comment by FPfotenhauer** [comment]
Dann wäre jetzt auch mal die Installer-Logs interessant.
Es scheint irgendwas beim anlegen , des Keystores zu sein.

**Comment by spechtg** [comment]
Ich habe nun ein neues Video erstellt und dort das Entfernen aller mir bekannten Daten und die Neuinstallation auf meinem großen Windows-PC durchgeführt. Wie ihr seht, hat sich am Fehler nichts geändert.
Ich bekomme die aktuellen Versionen einfach nicht ans laufen…

https://1drv.ms/v/s!AhXBnUC2fVl1wVNQpNxDIn76ZLBo?e=JhHUlL

@Frank: Wo genau liegt die Installationslog?

LG

**Comment by FPfotenhauer** [comment]
C:\Users\{Username}\AppData\Local\Temp

**Comment by spechtg** [comment]
[Setup Log 2022-09-19 #001.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9608989/Setup.Log.2022-09-19.001.txt)
[Setup Log 2022-09-19 #002.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9608990/Setup.Log.2022-09-19.002.txt)

**Comment by AnneSchueller** [comment]
Kannst du mal testen, was passiert, wenn du bei der Installation vom SVWS-Server bei den Zertifikatsinformationen die Leerzeichen weglässt.

**Comment by spechtg** [comment]
Habs soeben versucht. Keine Änderung. Fehler tritt auch hier auf.

**Comment by FPfotenhauer** [comment]
Es sieht aber tatsächlich so aus, als ob das Zertifikat nicht korrekt erstellt wird.
Dann kann es natürlich nicht aus dem Keystor extrahiert werden.
Thomas hat einen Installer gebaut, der ein Keystore.log erstellt.
Ich werde versuchen, den heute Abend hochzuladen ....

**Comment by FPfotenhauer** [comment]
Ich habe gerade zwei neue Installer in die Cloud gelegt.
Bitte einmal ausprobieren.

**Comment by spechtg** [comment]
Leider keine Besserung. Es treten die gleichen Fehler erneut auf.

**Comment by FPfotenhauer** [comment]
Ja. Das war ja klar. Aber gibt es das Keystore.log?

**Comment by spechtg** [comment]
Leider auch nicht.

**Comment by ThomasBachran** [comment]
Könnte wir nochmal die Installations-Logs haben? Hieraus sollte man jetzt erkennen können, ob beim Erstellen des Keystores - wie vermutet - Probleme aufgetreten sind.

**Comment by ThomasBachran** [comment]
Bei der Eingabe aus dem Video würde ich im Keystore.log die folgende Fehlermeldung vermuten:  
`keytool error: java.lang.RuntimeException: java.io.IOException: DNSName with blank components is not permitted`.
Das Problem ist, dass Leerzeichen im Hostname nicht zulässig sind. Daher ist "LTS Test" hier nicht sinnvoll. Kannst du das bitte einmal Ohne Leerzeichen probieren?

**Comment by spechtg** [comment]
Die Installation ohne Leerzeichen ändert nicht. Hier die Install-Logs: 
[Setup Log 2022-09-24 #001.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638050/Setup.Log.2022-09-24.001.txt)
[Setup Log 2022-09-24 #002.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638051/Setup.Log.2022-09-24.002.txt)

**Comment by spechtg** [comment]
Jetzt ist es mir allerdings möglich mit der neuen Schild-Version ein Schema manuell zu erzeugen und eine Datenbank zu migrieren. Damit habe ich Schild wieder lauffähig. Das ist auf jeden Fall ein großer Fortschritt.

**Comment by ThomasBachran** [comment]
Der keystore wird jetzt angelegt (siehe Installer-Log):
```
2022-09-24 08:04:48.548     -> SVWS-Keystore erfolgreich erzeugt. (Datei="C:\ProgramData\SVWS-Server/res/keystore"; ResultCode=0)
2022-09-24 08:04:48.844     -> SVWS-Zertifikat erfolgreich extrahiert. (Datei="C:\Users\Grego\OneDrive\Dokumente/SVWS.cer"; ResultCode=0)
```
Dadurch startet des SVWS-Server.

**Comment by ThomasBachran** [comment]
Die nächste Version des Installers wird dann auf Leerzeichen im Hostname prüfen.
Was den übriggebliebenen Fehler angeht, so ist dann wieder das Log des SVWS-Servers interessant und nicht mehr das Installer-Log...

**Comment by spechtg** [comment]
Bitte sehr: 
[2022_09_24.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638138/2022_09_24.request.log)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638139/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638140/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638141/svws_server_service.wrapper.log)

**Comment by ThomasBachran** [comment]
In den Logs kann ich auch keinen Fehler mehr erkennen. Hier würden mich die frischen Logs interessieren.

**Comment by spechtg** [comment]
Bitte sehr:
[2022_09_24.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638189/2022_09_24.request.log)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638190/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638191/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9638192/svws_server_service.wrapper.log)

**Comment by ThomasBachran** [comment]
Aus den Logs kann ich leider nicht direkt etwas erkennen. Allerdings ist mir im Installer-Log aufgefallen, das ungewöhnlich lang die Überprüfung auf 443 fehlschlägt, ob der Server bereits aktiv ist:
```
...
2022-09-24 08:05:06.660   Prüfe, ob Port 443 in Nutzung ist...
2022-09-24 08:05:06.714     -> Port ist ungenutzt.
2022-09-24 08:05:06.818     -> Schema konnte nicht angelegt werden.
```
Insgesamt wird derzeit 100 mal alle 100ms geprüft, ob der Server bereits aktiv ist. Nach dieser Zeit schlägt das Erstellen des Schemas fehl.
Eventuell gibt es Probleme bei dieser Überprüfung unter Windows 11, weshalb die manuelle Einrichtung später - ohne Überprüfung - erfolgreich ist?!

Kannst du mal bei laufendem Server (a) und bei nicht laufendem Server (b) die folgendenden Befehlskombinationen in der Kommandozeile (cmd.exe) ausprobieren und schreiben, was jeweils die Ausgabe ist? 

1. `netstat -p TCP -an | findstr "0.0:443"` und danach `echo %errorlevel%`
2. `netstat -p TCP -an | findstr "0.0:443"` und danach `echo $LastExitCode`
3. `@netstat -p TCP -an | findstr "0.0:443"` und danach `echo %errorlevel%`
4. `@netstat -p TCP -an | findstr "0.0:443"` und danach `echo $LastExitCode`

**Comment by spechtg** [comment]
Der oberer Teil ist mit laufendem SVWS Server. Der untere Teil mit beendetem Service. Habe den Server mit dem Task Manager Beendet. Alternativ kann ich diesen auch deinstallieren und dann die Befehle eingeben. Musst kurz sagen, wie du es benötigst. 

![Screenshot 2022-09-24 114200](https://user-images.githubusercontent.com/96472913/192091393-6c82d973-e990-41df-a067-ed0ce5ec4eda.jpg)

**Comment by FPfotenhauer** [comment]
Ich habe soeben einen SVWS-Installer in die FB-Cloud geladen.
Bitte nicht wundern, die Versionsnummer ist nicht geändert, weil am Server ja nichts geändert wurde, nur am Installer-Script.

@spechtg : Kannst du den bitte mal ausprobieren?

**Comment by spechtg** [comment]
Perfekt. Es funktioniert. Die von Thomas beschriebene Abfrage kommt. Dadurch verlängert sich die Installation, läuft aber ohne weitere Fehler durch.
