### ISSUE TITLE
Tabelle schueler doesn't exist

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#393]
Beim Speichern von Daten, ziemlich egal was, kommt die o.g. Fehlermeldung.
MariaDB auf einem Debian-Server, also Case-Sensitiv.
Wahrscheinlich das kleine 's' bei der Tabelle Schueler.

**Comment by JuergenRichter** [comment]
Sollte behoben sein, bitte mit dem nächsten Update mal prüfen (habe selbst keinen Linux-Server)

**Comment by FPfotenhauer** [comment]
Der Fehler bleibt leider.

EurekaLog 7.10.0.0 8BD69D43571B8C48A2404FB6F3744F60 8F7A41A5D4255B46AA5481D36B4EB209 DA39A3EE5E6B4B0D3255BFEF95601890AFD80709 F323436E1BD9B249934DCCC0B9F0D7EE

Application:
-------------------------------------------------------------------
  1.1 Start Date      : Fri, 23 Sep 2022 15:59:12 +0200
  1.2 Name/Description: SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  1.3 Version Number  : 3.0.43.7
  1.4 Parameters      : 
  1.5 Compilation Date: Wed, 21 Sep 2022 15:58:37 +0200
  1.6 Up Time         : 29 second(s)

Exception:
------------------------------------------------------------------
  2.1 Date          : Fri, 23 Sep 2022 15:59:42 +0200
  2.2 Address       : 00E225CD
  2.3 Module Name   : SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  2.4 Module Version: 3.0.43.7
  2.5 Type          : EMyError
  2.6 Message       : #42S02Table 'svwsdb.schueler' doesn't exist.
  2.7 ID            : 2383C534
  2.8 Count         : 1
  2.9 Status        : New
  2.10 Note         : 
  2.11 Sent         : 0

User:
----------------------------------------------------------------
  3.1 ID        : Pfotenhauer
  3.2 Name      : Pfotenhauer
  3.3 Email     : 
  3.4 Company   : 
  3.5 Privileges: SeShutdownPrivilege             - OFF
                  SeChangeNotifyPrivilege         - ON (default)
                  SeUndockPrivilege               - OFF
                  SeIncreaseWorkingSetPrivilege   - OFF
                  SeTimeZonePrivilege             - OFF

Active Controls:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  4.1 Form Class   : Tfrm_Hauptformular
  4.2 Form Text    : Aktuelle Datenbank: Debian-MariaDB, Schuljahr 2018/2019, 2. Hj., Benutzer: Admin (keine Verbindung zum SVWS-Server: Fehler = Fehler beim Senden der Daten: (12029) Die Serververbindung konnte nicht hergestellt werden)
  4.3 Control Class: TDBEditEh
  4.4 Control Text : 

Computer:
--------------------------------------------
  5.1 Name        : ABRAHAM
  5.2 Total Memory: 137107312640 (127,69 Gb)
  5.3 Free Memory : 107630264320 (100,24 Gb)
  5.4 Total Disk  : 999541858304 (930,90 Gb)
  5.5 Free Disk   : 760927965184 (708,67 Gb)
  5.9 Display DPI : 96

Operating System:
-----------------------------------------------
  6.1 Type    : Microsoft Windows 10 (64 bit)
  6.2 Build # : 2009 (10.0.19044.2006)
  6.3 Update  : Authum 2021 Update [21H2] #2006
  6.4 Language: German (0407)
  6.5 Charset : 0/1252


Call Stack Information:
--------------------------------------------------------------------------------------------------------------------------------------------------
|Methods |Details|Stack   |Address |Module      |Offset  |Source          |Unit        |Class            |Procedure/Method   |Line               |
--------------------------------------------------------------------------------------------------------------------------------------------------
|*Exception Thread: ID=8120; Parent=0; Priority=0                                                                                                |
|Class=; Name=MAIN                                                                                                                               |
|DeadLock=0; Wait Chain=                                                                                                                         |
|Comment=                                                                                                                                        |
|------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|03     |00000000|00E225CD|SchILD30.exe|00A225CD|MyClassesUni.pas|MyClassesUni|TMySQLConnection |MySQLError         |                   |
|00000040|03     |0019F558|00E264CA|SchILD30.exe|00A264CA|MyClassesUni.pas|MyClassesUni|TMySQLCommand    |Check              |                   |
|00000040|03     |0019F59C|00E2B059|SchILD30.exe|00A2B059|MyClassesUni.pas|MyClassesUni|TMySQLCommand    |InternalExecute    |                   |
|00000040|03     |0019F5BC|00E2B181|SchILD30.exe|00A2B181|MyClassesUni.pas|MyClassesUni|TMySQLCommand    |Execute            |                   |
|00000040|03     |0019F60C|00B1FF51|SchILD30.exe|0071FF51|CRAccess.pas    |CRAccess    |TCRRecordSet     |ExecCommand        |                   |
|00000040|03     |0019F650|00E2C25B|SchILD30.exe|00A2C25B|MyClassesUni.pas|MyClassesUni|TMySQLRecordSet  |ExecCommand        |                   |
|00000040|03     |0019F680|00AE6DFD|SchILD30.exe|006E6DFD|DBAccess.pas    |DBAccess    |TCustomDADataSet |InternalExecute    |                   |
|00000040|03     |0019F6A8|00AE71CF|SchILD30.exe|006E71CF|DBAccess.pas    |DBAccess    |TCustomDADataSet |Execute            |                   |
|00000040|03     |0019F71C|00AE6F4A|SchILD30.exe|006E6F4A|DBAccess.pas    |DBAccess    |TCustomDADataSet |Execute            |                   |
|00000040|03     |0019F744|00AF1353|SchILD30.exe|006F1353|DBAccess.pas    |DBAccess    |TDADataSetUpdater|UpdateExecute      |                   |
|00000040|03     |0019F784|00AF3405|SchILD30.exe|006F3405|DBAccess.pas    |DBAccess    |TDADataSetUpdater|PerformSQL         |                   |
|00000040|03     |0019F7E8|00AF4262|SchILD30.exe|006F4262|DBAccess.pas    |DBAccess    |TDADataSetUpdater|PerformUpdateDelete|                   |
|00000040|03     |0019F820|00AF43C8|SchILD30.exe|006F43C8|DBAccess.pas    |DBAccess    |TDADataSetUpdater|PerformUpdate      |                   |
|00000040|03     |0019F840|00AB939B|SchILD30.exe|006B939B|MemDS.pas       |MemDS       |TMemDataSet      |DoPerformUpdate    |                   |
|00000040|03     |0019F8A8|00A48FAF|SchILD30.exe|00648FAF|MemData.pas     |MemData     |TMemData         |PostRecord         |                   |
|00000040|03     |0019F8D8|00AB89E2|SchILD30.exe|006B89E2|MemDS.pas       |MemDS       |TMemDataSet      |InternalPost       |                   |
--------------------------------------------------------------------------------------------------------------------------------------------------

Modules Information:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|Handle  |Name                       |Description                                           |Version            |Size    |Modified           |Path                                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|00400000|SchILD30.exe               |SchILD 3.0 von ribeka GmbH                            |3.0.43.7           |54625336|2022-09-23 14:49:37|C:\Schild-NRW-30\                                                                                             |
|04340000|ChilkatDelphi32.dll        |Chilkat Delphi DLL 32-bit                             |9.5.0.82           |10648576|2020-02-26 13:37:26|C:\Schild-NRW-30\                                                                                             |
|10000000|lz32.dll                   |LZ Expand/Compress API DLL                            |5.0.1.1            |2560    |2019-12-07 11:09:26|C:\Windows\System32\                                                                                          |
|50030000|borlndmm.dll               |Embarcadero Memory Manager                            |25.0.29899.2631    |70000   |2020-10-13 14:44:51|C:\Schild-NRW-30\                                                                                             |
|61AB0000|webio.dll                  |API für Webtransferprotokolle                         |10.0.19041.1620    |452096  |2022-04-25 07:48:46|C:\Windows\System32\                                                                                          |
|61B30000|hhctrl.ocx                 |Steuerelement für Microsoft® HTML-Hilfe               |10.0.19041.746     |575488  |2021-01-15 11:24:37|C:\Windows\System32\                                                                                          |
|61BD0000|shdocvw.dll                |Shelldokumentobjekt und Steuerungsbibliothek          |10.0.19041.746     |218112  |2021-01-15 11:24:28|C:\Windows\System32\                                                                                          |
|61C10000|ieframe.dll                |Internet Browser                                      |11.0.19041.1949    |6500352 |2022-09-16 16:53:56|C:\Windows\System32\                                                                                          |
|62340000|url.dll                    |Internet Shortcut Shell Extension DLL                 |11.0.19041.1       |233472  |2019-12-07 11:10:00|C:\Windows\System32\                                                                                          |
|62380000|duser.dll                  |Windows DirectUser Engine                             |10.0.19041.546     |470528  |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|62400000|osbaseln.dll               |Service Reporting API                                 |10.0.19041.1       |21504   |2019-12-07 11:09:13|C:\Windows\System32\                                                                                          |
|62410000|appwiz.cpl                 |Shellanwendungs-Manager                               |10.0.19041.746     |469504  |2021-01-15 11:24:37|C:\Windows\System32\                                                                                          |
|62490000|msls31.dll                 |Microsoft Line Services library file                  |3.10.349.0         |183808  |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|624D0000|riched20.dll               |Rich Text Edit Control, v3.1                          |5.31.23.1231       |487424  |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|62550000|secur32.dll                |Security Support Provider Interface                   |10.0.19041.546     |23040   |2020-11-10 14:54:37|C:\Windows\System32\                                                                                          |
|62560000|wer.dll                    |Windows-Fehlerbericht-DLL                             |10.0.19041.1949    |701424  |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|62610000|Faultrep.dll               |Windows-Benutzermodus-Absturzberichterstattungs-DLL   |10.0.19041.1949    |411112  |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|62680000|tapi32.dll                 |Microsoft® Windows(TM) Telefonie-API-Client-DLL       |10.0.19041.423     |193536  |2020-09-27 21:58:08|C:\Windows\System32\                                                                                          |
|626C0000|fontsub.dll                |Font Subsetting DLL                                   |10.0.19041.1620    |99328   |2022-04-25 07:48:46|C:\Windows\System32\                                                                                          |
|626E0000|msvfw32.dll                |DLL für Microsoft Video für Windows                   |10.0.19041.1       |124416  |2019-12-07 11:10:04|C:\Windows\System32\                                                                                          |
|62820000|TextShaping.dll            |                                                      |                   |611960  |2021-10-20 08:23:09|C:\Windows\System32\                                                                                          |
|62900000|windowscodecs.dll          |Microsoft Windows Codecs Library                      |10.0.19041.1706    |1511344 |2022-05-16 08:39:03|C:\Windows\System32\                                                                                          |
|62A90000|msacm32.dll                |Microsoft ACM-Audiofilter                             |10.0.19041.1       |93472   |2019-12-07 11:09:11|C:\Windows\System32\                                                                                          |
|62CE0000|winmmbase.dll              |API für die Basissystemverlängerung                   |10.0.19041.1       |110720  |2019-12-07 11:09:11|C:\Windows\System32\                                                                                          |
|62D00000|avifil32.dll               |Microsoft AVI-Dateiunterstützungs-Bibliothek          |10.0.19041.1       |95744   |2019-12-07 11:10:04|C:\Windows\System32\                                                                                          |
|62D20000|olepro32.dll               |OLEPRO32.DLL                                          |10.0.19041.84      |88576   |2020-09-27 21:57:53|C:\Windows\System32\                                                                                          |
|63740000|dataexchange.dll           |Data exchange                                         |10.0.19041.1387    |183808  |2021-12-17 10:37:37|C:\Windows\System32\                                                                                          |
|63780000|winhttp.dll                |Windows HTTP-Dienste                                  |10.0.19041.1682    |822224  |2022-05-16 08:39:04|C:\Windows\System32\                                                                                          |
|63850000|ondemandconnroutehelper.dll|On Demand Connctiond Route Helper                     |10.0.19041.546     |56832   |2020-11-10 14:54:32|C:\Windows\System32\                                                                                          |
|67BA0000|d3d11.dll                  |Direct3D 11 Runtime                                   |10.0.19041.1865    |1965288 |2022-08-11 19:22:15|C:\Windows\System32\                                                                                          |
|67D80000|twinapi.appcore.dll        |twinapi.appcore                                       |10.0.19041.1865    |1635248 |2022-08-11 19:22:16|C:\Windows\System32\                                                                                          |
|68450000|ColorAdapterClient.dll     |Microsoft Color Adapter Client                        |10.0.19041.546     |45904   |2020-11-10 14:54:32|C:\Windows\System32\                                                                                          |
|68460000|mscms.dll                  |Microsoft-Farbabstimmungssystem-DLL                   |10.0.19041.746     |594464  |2021-01-15 11:24:22|C:\Windows\System32\                                                                                          |
|68500000|dcomp.dll                  |Microsoft DirectComposition Library                   |10.0.19041.1741    |1450328 |2022-06-17 12:37:10|C:\Windows\System32\                                                                                          |
|68670000|dxgi.dll                   |DirectX Graphics Infrastructure                       |10.0.19041.1806    |786624  |2022-07-18 07:43:53|C:\Windows\System32\                                                                                          |
|6FCC0000|dbgcore.dll                |Windows Core Debugging Helpers                        |10.0.19041.546     |138752  |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|6FCF0000|dbghelp.dll                |Windows Image Helper                                  |10.0.19041.1052    |1494016 |2021-06-09 12:28:10|C:\Windows\System32\                                                                                          |
|700C0000|comctl32.dll               |Bibliothek für Steuerelemente                         |6.10.19041.1110    |2152264 |2021-07-09 08:47:26|C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\|
|702F0000|dwmapi.dll                 |Microsoft Desktopfenster-Manager-API                  |10.0.19041.746     |138936  |2021-01-15 11:24:26|C:\Windows\System32\                                                                                          |
|70430000|CoreUIComponents.dll       |Microsoft Core UI Components Dll                      |10.0.19041.546     |2621720 |2020-11-10 14:54:32|C:\Windows\System32\                                                                                          |
|707F0000|wkscli.dll                 |Workstation Service Client DLL                        |10.0.19041.1645    |64552   |2022-04-25 07:48:46|C:\Windows\System32\                                                                                          |
|70810000|netapi32.dll               |Net Win32 API DLL                                     |10.0.19041.1949    |73864   |2022-09-16 16:53:49|C:\Windows\System32\                                                                                          |
|70830000|winsta.dll                 |Winstation Library                                    |10.0.19041.546     |270640  |2020-11-10 14:54:31|C:\Windows\System32\                                                                                          |
|708C0000|FWPUCLNT.DLL               |FWP/IPsec Benutzermodus-API                           |10.0.19041.1682    |347648  |2022-05-16 08:39:04|C:\Windows\System32\                                                                                          |
|709B0000|usp10.dll                  |Uniscribe Unicode script processor                    |10.0.19041.546     |77824   |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|709F0000|WinTypes.dll               |Windows-Basistypen-DLL                                |10.0.19041.1949    |897120  |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|70AF0000|winnsi.dll                 |Network Store Information RPC interface               |10.0.19041.546     |28360   |2020-11-10 14:54:26|C:\Windows\System32\                                                                                          |
|70B00000|umpdc.dll                  |                                                      |                   |47472   |2020-11-10 14:54:34|C:\Windows\System32\                                                                                          |
|70B10000|wtsapi32.dll               |Windows Remote Desktop Session Host Server SDK APIs   |10.0.19041.546     |52664   |2020-11-10 14:54:31|C:\Windows\System32\                                                                                          |
|70B30000|rasadhlp.dll               |Remote Access AutoDial Helper                         |10.0.19041.546     |12800   |2020-11-10 14:54:37|C:\Windows\System32\                                                                                          |
|70B60000|dnsapi.dll                 |DNS-Client-API-DLL                                    |10.0.19041.1865    |583144  |2022-08-11 19:22:16|C:\Windows\System32\                                                                                          |
|70BF0000|powrprof.dll               |Power Profile Helper DLL                              |10.0.19041.546     |268080  |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|70D10000|dhcpcsvc6.DLL              |DHCPv6-Client                                         |10.0.19041.1949    |61440   |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|70D30000|dhcpcsvc.dll               |DHCP Clientdienst                                     |10.0.19041.1949    |73728   |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|70D60000|mswsock.dll                |Microsoft Windows Sockets 2.0-Dienstanbieter          |10.0.19041.546     |324416  |2020-11-10 14:54:35|C:\Windows\System32\                                                                                          |
|70E20000|IPHLPAPI.DLL               |IP-Hilfs-API                                          |10.0.19041.546     |196784  |2020-11-10 14:54:35|C:\Windows\System32\                                                                                          |
|70E90000|mpr.dll                    |Router-DLL für Mehrfachanbieter                       |10.0.19041.1806    |94536   |2022-07-18 07:44:00|C:\Windows\System32\                                                                                          |
|70ED0000|wsock32.dll                |Windows Socket 32-Bit DLL                             |10.0.19041.1       |16384   |2019-12-07 11:09:15|C:\Windows\System32\                                                                                          |
|70F40000|userenv.dll                |Userenv                                               |10.0.19041.572     |141008  |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|70F70000|CoreMessaging.dll          |Microsoft CoreMessaging Dll                           |10.0.19041.867     |630592  |2021-03-13 12:42:37|C:\Windows\System32\                                                                                          |
|71A70000|textinputframework.dll     |"TextInputFramework.DYNLINK"                          |10.0.19041.1741    |754104  |2022-06-17 12:37:09|C:\Windows\System32\                                                                                          |
|71C10000|sspicli.dll                |Security Support Provider Interface                   |10.0.19041.1586    |123984  |2022-03-10 18:15:31|C:\Windows\System32\                                                                                          |
|71C50000|shfolder.dll               |Shell Folder Service                                  |10.0.19041.1       |8704    |2019-12-07 11:09:32|C:\Windows\System32\                                                                                          |
|71D40000|ntmarta.dll                |Windows NT MARTA-Anbieter                             |10.0.19041.546     |152904  |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|71D70000|srvcli.dll                 |Server Service Client DLL                             |10.0.19041.1645    |78016   |2022-04-25 07:48:46|C:\Windows\System32\                                                                                          |
|71D90000|netutils.dll               |Net Win32 API Helpers DLL                             |10.0.19041.1466    |38232   |2022-01-12 15:23:46|C:\Windows\System32\                                                                                          |
|71DA0000|urlmon.dll                 |OLE32-Erweiterung für Win32                           |11.0.19041.1949    |1679872 |2022-09-16 16:53:51|C:\Windows\System32\                                                                                          |
|71F70000|iertutil.dll               |Laufzeit-Hilfsprogramm für Internet Explorer          |11.0.19041.1949    |2273144 |2022-09-16 16:53:51|C:\Windows\System32\                                                                                          |
|721A0000|msi.dll                    |Windows Installer                                     |5.0.19041.1766     |2692096 |2022-06-17 12:37:16|C:\Windows\System32\                                                                                          |
|72490000|profapi.dll                |User Profile Basic API                                |10.0.19041.844     |89360   |2021-03-13 12:42:35|C:\Windows\System32\                                                                                          |
|724B0000|propsys.dll                |Microsoft-Eigenschaftensystem                         |7.0.19041.1741     |792832  |2022-06-17 12:37:09|C:\Windows\System32\                                                                                          |
|73990000|wldp.dll                   |Windows-Sperrungsrichtlinie                           |10.0.19041.1949    |154432  |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|739C0000|windows.storage.dll        |Microsoft WinRT Storage-API                           |10.0.19041.1949    |6377736 |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|748F0000|kernel.appcore.dll         |AppModel API Host                                     |10.0.19041.546     |52672   |2020-11-10 14:54:34|C:\Windows\System32\                                                                                          |
|74990000|winspool.drv               |Windows-Spoolertreiber                                |10.0.19041.1865    |449536  |2022-08-11 19:22:15|C:\Windows\System32\                                                                                          |
|74A10000|winmm.dll                  |MCI API-DLL                                           |10.0.19041.546     |149272  |2020-11-10 14:54:30|C:\Windows\System32\                                                                                          |
|74A40000|GdiPlus.dll                |Microsoft GDI+                                        |10.0.19041.2006    |1449984 |2022-09-07 02:59:08|C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2006_none_d94bc80de1097097\        |
|74BB0000|oleacc.dll                 |Active Accessibility Core Component                   |7.2.19041.746      |321024  |2021-01-15 11:24:28|C:\Windows\System32\                                                                                          |
|74C10000|oledlg.dll                 |OLE-Benutzerschnittstellen-Unterstützung              |10.0.19041.746     |163328  |2021-01-15 11:24:26|C:\Windows\System32\                                                                                          |
|74C40000|uxtheme.dll                |Microsoft UxTheme-Bibliothek                          |10.0.19041.1620    |454656  |2022-04-25 07:48:44|C:\Windows\System32\                                                                                          |
|74CC0000|version.dll                |Version Checking and File Installation Libraries      |10.0.19041.546     |27320   |2020-11-10 14:54:37|C:\Windows\System32\                                                                                          |
|74CD0000|msimg32.dll                |GDIEXT Client DLL                                     |10.0.19041.1466    |7168    |2022-01-12 15:23:46|C:\Windows\System32\                                                                                          |
|74D40000|wininet.dll                |Interneterweiterungen für Win32                       |11.0.19041.1566    |4509696 |2022-03-10 18:15:35|C:\Windows\System32\                                                                                          |
|751A0000|kernel32.dll               |Client-DLL für Windows NT-Basis-API                   |10.0.19041.1889    |637712  |2022-08-11 19:22:15|C:\Windows\System32\                                                                                          |
|75400000|nsi.dll                    |NSI User-mode interface DLL                           |10.0.19041.610     |20144   |2020-11-10 15:16:00|C:\Windows\System32\                                                                                          |
|75410000|SHCore.dll                 |SHCORE                                                |10.0.19041.1645    |545984  |2022-04-25 07:48:46|C:\Windows\System32\                                                                                          |
|75500000|gdi32full.dll              |GDI Client DLL                                        |10.0.19041.2006    |897688  |2022-09-16 16:53:51|C:\Windows\System32\                                                                                          |
|755E0000|crypt32.dll                |Krypto-API32                                          |10.0.19041.1889    |1014368 |2022-08-11 19:22:16|C:\Windows\System32\                                                                                          |
|75B60000|msvcp_win.dll              |Microsoft® C Runtime Library                          |10.0.19041.789     |495840  |2021-02-14 13:40:01|C:\Windows\System32\                                                                                          |
|75C40000|ws2_32.dll                 |Windows Socket 2.0-32-Bit-DLL                         |10.0.19041.546     |397728  |2020-11-10 14:54:30|C:\Windows\System32\                                                                                          |
|75CB0000|msvcrt.dll                 |Windows NT CRT DLL                                    |7.0.19041.546      |775256  |2020-11-10 14:54:30|C:\Windows\System32\                                                                                          |
|75D70000|comdlg32.dll               |DLL für gemeinsame Dialoge                            |10.0.19041.1806    |688128  |2022-07-18 07:44:01|C:\Windows\System32\                                                                                          |
|75E20000|advapi32.dll               |Erweiterte Windows 32 Base-API                        |10.0.19041.1682    |496360  |2022-05-16 08:39:03|C:\Windows\System32\                                                                                          |
|75EA0000|imm32.dll                  |Multi-User Windows IMM32 API Client DLL               |10.0.19041.546     |143056  |2020-11-10 14:54:36|C:\Windows\System32\                                                                                          |
|75ED0000|shell32.dll                |Allgemeine Windows-Shell-DLL                          |10.0.19041.1949    |6013592 |2022-09-16 16:53:51|C:\Windows\System32\                                                                                          |
|76490000|sechost.dll                |Host for SCM/SDDL/LSA Lookup APIs                     |10.0.19041.1865    |477808  |2022-08-11 19:22:15|C:\Windows\System32\                                                                                          |
|76510000|shlwapi.dll                |Shell Light-weight-Hilfsprogrammbibliothek            |10.0.19041.1706    |276864  |2022-05-16 08:39:05|C:\Windows\System32\                                                                                          |
|76560000|win32u.dll                 |Win32u                                                |10.0.19041.2006    |94008   |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|76580000|bcryptPrimitives.dll       |Windows Cryptographic Primitives Library              |10.0.19041.1415    |383264  |2021-12-17 10:37:33|C:\Windows\System32\                                                                                          |
|76640000|clbcatq.dll                |COM+ Configuration Catalog                            |2001.12.10941.16384|504552  |2020-11-10 14:54:35|C:\Windows\System32\                                                                                          |
|766C0000|psapi.dll                  |Process Status Helper                                 |10.0.19041.546     |17016   |2020-11-10 14:54:35|C:\Windows\System32\                                                                                          |
|766D0000|KERNELBASE.dll             |Client-DLL für Windows NT-Basis-API                   |10.0.19041.2006    |2203392 |2022-09-16 16:53:47|C:\Windows\System32\                                                                                          |
|768F0000|ole32.dll                  |Microsoft OLE für Windows                             |10.0.19041.1202    |926560  |2021-09-17 18:30:20|C:\Windows\System32\                                                                                          |
|769E0000|rpcrt4.dll                 |Remoteprozeduraufruf-Laufzeitumgebung                 |10.0.19041.1806    |776824  |2022-07-18 07:43:52|C:\Windows\System32\                                                                                          |
|76AA0000|gdi32.dll                  |GDI Client DLL                                        |10.0.19041.1620    |136336  |2022-04-25 07:48:45|C:\Windows\System32\                                                                                          |
|76B70000|ucrtbase.dll               |Microsoft® C Runtime Library                          |10.0.19041.789     |1181208 |2021-02-14 13:40:01|C:\Windows\System32\                                                                                          |
|76CE0000|combase.dll                |Microsoft COM für Windows                             |10.0.19041.1949    |2633080 |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|76F60000|bcrypt.dll                 |Bibliothek mit kryptografischen Primitiven von Windows|10.0.19041.1023    |96032   |2021-06-09 12:28:10|C:\Windows\System32\                                                                                          |
|76F80000|imagehlp.dll               |Windows NT Image Helper                               |10.0.19041.1415    |95496   |2021-12-17 10:37:33|C:\Windows\System32\                                                                                          |
|76FA0000|msctf.dll                  |MSCTF-Server-DLL                                      |10.0.19041.1949    |863048  |2022-09-16 16:53:49|C:\Windows\System32\                                                                                          |
|77080000|user32.dll                 |Client-DLL für Windows USER-API (mehrere Benutzer)    |10.0.19041.2006    |1679648 |2022-09-16 16:53:50|C:\Windows\System32\                                                                                          |
|77220000|oleaut32.dll               |OLEAUT32.DLL                                          |10.0.19041.985     |606888  |2021-05-12 17:04:58|C:\Windows\System32\                                                                                          |
|772D0000|ntdll.dll                  |DLL für NT-Layer                                      |10.0.19041.1949    |1699896 |2022-09-16 16:53:49|C:\Windows\System32\                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Processes Information:
----------------------


Assembler Information:
----------------------


Registers:
----------

**Comment by JuergenRichter** [comment]
Sollte jetzt endgültig behoben sein

**Comment by FPfotenhauer** [comment]
Ich kann das leider erst nach dem urlaub testen, weil ich hier keine Linux-Maschine habe.
