### ISSUE TITLE
Neues Feld gewünscht: Religionsunterrichtswahl (etwas für Später)

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#396]
Zitat aus 
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=6&t=5028&sid=7a8e4bafd33d72f10f1b817243fc1dd6

"Seitdem an den meisten Schulen flächendeckend neben KR und ER auch PP parallel angeboten wird und jeder auch (unabhängig von der eigenen Konfession) das Recht hat, jedes der drei Fächer für sich zu wählen, wäre es für die Kurseinteilungen extrem praktisch, ein zusätzliches Feld "Religionswahl" (oder wie auch immer) unter Individualdaten I einzuführen, am besten direkt unter "Religionsabwahl/anwahl" (falls das überhaupt noch Sinn macht).

Bisher wird von vielen Schulen irgendein anderes Feld (wie etwa "Haltestelle") dafür fremdgenutzt..."

**Comment by JuergenRichter** [comment]
Das muss ja wohl zuerst von der "Datenbankabteilung" geprüft und umgesetzt werden

**Comment by AnneSchueller** [comment]
Das Issue hat erstmal keine Priorität. Ich habe das nur schonmal geöffnet, damit ich das nicht vergesse. Ich weise das mal mir zu. Das passt wahrscheinlich besser.

**Comment by JuergenRichter** [comment]
Für so was gibt es doch aber andere Möglichkeiten
-Schülergruppen
-Vermerke
Kann man das nicht damit abdecken?

**Comment by JeVaske** [comment]
Ich habe es im Forum auch gelesen. Mir ist überhaupt nicht klar, was daran "extrem praktisch" sein soll. Meiner Meinung nach ist das extrem überflüssig.

**Comment by JuergenRichter** [comment]
Wenn man das umsetzen würde, käme sicher bald der nächste, der ein ähnliches Feld z.B. für das Fach des E- oder G-Kurses, die gewählte Fremdsprache usw. haben will.

**Comment by MichaelPeters1983** [comment]
Mal davon abgesehen, dass ein lustiges Wechselspiel der Konfessionalität nicht durch das Schulgesetz abgedeckt ist (https://bass.schul-welt.de/5125.htm) wäre es auch nicht praktikabel. Schüler nehmen entweder am RU ihrer Konfession teil oder an PPL. EIn Recht auf Teilname am RU der anderen Konfession ist im Schulgesetz so nicht vorgesehen. Daher wäre das Feld nicht rechtens....

**Comment by AnneSchueller** [comment]
Ich stimme vollkommen zu, dass ein derartiges Feld aus Sicht einer weiterführenden Schule als Überflüssig erscheint. Aus Sicht einer Grundschule würde ich einem solchen Feld eine Berechtigung zusprechen. In der Praxis deckt sich der Religionsunterricht eben nicht immer mit der Konfession der Schüler, was auch nach dem Schulgesetzt nicht untersagt wird.

Ich würde jetzt mal die Meinungen aus dem Forum abwarten und nicht an dieser Stelle eine zweite Diskussion führen.  Dann beratschlage ich nochmal mit Jens Raffenberg.

**Comment by Raffenberg** [comment]
Wir sollten das jetzt nicht hier in aller Länge diskutieren. Das frist momentan zu viel Zeit und ist ein Thema für sehr viel später, wenn Schild3 fehlerfrei läuft.

Nur kurz: Alles was oben steht, haben Frau Schüller und ich bereits durchdiskutiert. Am Ende bleibt für die Religionen im Gegensatz zu anderen Fächern aber ein Sonderstatus, den man auch rechtfertigen kann.
