### ISSUE TITLE
Suche nach Schülern mit nicht ausgewähltem Status schlägt fehl.

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#397]
Sie Suche nach Schüler/-innen, die nicht unter dem vorher ausgewähltem Status "Aktiv" zu finden sind, sondern sich beispielweise unter Abgänger befinden, klappt trotz der Abfrage nach Anpassung der aktuellen Auswahl nicht.

**Comment by JuergenRichter** [comment]
Behoben
