### ISSUE TITLE
Akt. Abschnitt -> Leistungsdaten -> Folgeklasse nicht wählbar 

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#398]
Trotz korrekt gesetzter Statistikjahrgänge ist die Folgeklasse nicht wählbar.

**Comment by JuergenRichter** [comment]
Wo?

**Comment by AnneSchueller** [comment]
![2022-09-27_135051](https://user-images.githubusercontent.com/79116896/192518013-8be66f7f-00a5-44ff-9594-097ccb5cf996.png)

**Comment by JuergenRichter** [comment]
Behoben
