### ISSUE TITLE
Report Pipeline Lehrer - Unterbericht Kursunterricht Fehlermeldung

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#399]
Ein Report mit Hauptdatenpipeline 'Lehrer' und Unterpipeline 'Kursunterricht' erzeugt beim Aufruf folgende Fehlermeldung:
Unknown Column 'A.Klasse' in 'field list.

[Lehrer - Kursunterricht.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9659923/Lehrer.-.Kursunterricht.zip)
[ErrorLog.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9659924/ErrorLog.txt)

**Comment by JuergenRichter** [comment]
Behoben
