### ISSUE TITLE
Anzeige der Versetzungsvermerke im Feld Leistungsdaten

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#40]
Im Feld der Leistungsdaten sollten meiner Ansicht nach (siehe Bild) auch die Versetzungsvermerke mit aufgenommen werden. Für Schulen, die in Konferenzen direkt mit Schild arbeiten bzw. zur Eintragung und Kontrolle der Versetzungsvermerke erspart man sich extrem viel Zeit, weil nicht bei jedem Schüler zwischen den Karteireitern "Allgemeine Angaben" und "Leistungsdaten" gewechselt werden muss. 
![image](https://user-images.githubusercontent.com/75179015/101290904-40516480-3805-11eb-8296-456062ba97f5.png)

**Comment by FPfotenhauer** [comment]
Ich frage mal ganz neutral.
Wozu gibt es denn das konferenzmodul?

**Comment by Kluesenerm** [comment]
Das frage ich mich auch. Ich kenne viele Schulen, die das Konferenzmodul nicht einsetzen. Wir arbeiten direkt in Schild, weil wir auch über die Laufbahnen und Entwicklungen beraten und umblättern. Ich finde persönlich das Konferenzmodul vollkommen unübersichtlich. Außerdem vergeben wir als WBK jedes Halbjahr in verschiedenen Semestern Abschlüsse und müssen daher in den Laufbahninfos nachschauen. Die Ansicht über Leistungsdaten fokussiert den Blick auf den einzelnen Schüler.

**Comment by FPfotenhauer** [comment]
KM2 hat eine SchülerLupe mit der Laufbahn!

Bitte nicht falsch verstehen, abe rwir verstricken uns hier in so vielen Modulen, dass ich schon gerne eine gewisse Konsolidierung der Programme erreichen möchte.

**Comment by Kluesenerm** [comment]
Hallo Frank, 
klar. Aber bisher wurden die Versetzungsvermerke auch angezeigt und die Schulen in meinem Dunstkreis nutzen nicht das Konferenzmodul. Der Platz wäre auch vollkommen ausreichend.  Denk bitte auch an die Nutzung außerhalb von Konferenzen. Im Alltag und für die Konferenzvor- und nachbereitung der Koordinatoren und Schulleitungen wird keiner das Konferenzmodul öffnen, sondern es wird individuell bei Schülern nachgeschaut: Welche Noten und Mahnungen liegen vor und welcher Versetzungsvermerk ist gesetzt. Ein Blättern in den Karteireitern wäre in meinem Alltag ein unnötiger Zeitfresser und würde die Übersicht unnötig verschlechtern.

**Comment by Kluesenerm** [comment]
Hallo Herr Richter,
auch bei einem virtuellen Treffen mit mehreren Fachberatern und Frank wurde festgestellt, dass die alte Ansicht mit der Anzeige der Versetzungsvermerke und Abschlüsse auf jeden Fall erhalten bleiben muss (siehe oben). Können Sie es in einem der nächsten Updates zum Test einbauen?

**Comment by JuergenRichter** [comment]
Ist bereits in Version 3.0.9 umgesetzt, mache daher erst mal zu.
