### ISSUE TITLE
Auswahl Filter

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#400]
Aktuelle Version: Es gelingt mir nicht, mit dem Auswahl-Filter SuS des letzten Abiturjahrgangs zu filtern. Ich habe Folgendes getestet: Individualdaten I: Status: Abschluss und Lernabschnitt,Leistungsdaten: Zu betrachtender Abschnitt: 2021/22 2. Hj., Fach Bi Kursart: LK. Ergebnis: Kein Schüler wird angezeigt. Auch wenn ich vorher bei der Schülerauswahl das Häkchen bei "Abschluss" setze, wird mir nur ein Wiederholer, der also "aktueller Schüler" ist, angezeigt.
Das Pulldownmenü vom Status ist sehr ungewöhnlich angeordnet. Eventuell wäre die Position rechts neben Masernschutz-Nachweis geeigneter, weil man es von Schild 2 gewohnt ist, dass das Feld an exponierter Stelle steht. Außerdem fällt mir bei diesem Pulldownmenü ein Grafikfehler in Form eines schwarzen Balkens unterhalb der Bezeichnung "Ehemalige" auf (s. unten).
![Schild Fehler 10](https://user-images.githubusercontent.com/78501680/192866965-191efc73-cdb3-4b49-bf78-4f34b71ad4a7.jpg)

**Comment by JuergenRichter** [comment]
Ich habe das getestet, das liegt daran, dass im Filterfenster standardmäßig auf dem Karteireiter "Individualdaten I" bei "Daten des aktuellen oder zuletzt besuchten Abschnittes" der jeweils aktuelle Abschnitt der Schule voreingestellt ist (in meiner Beispiel-DB 2019/20 3. Q.).

![image](https://user-images.githubusercontent.com/61280188/192968725-eb8db0a3-f026-485e-859f-297519c08ac7.png)

Die Abfrage lautet dann also: Suche die SuS mit Status Abschluss, die derzeit in 2019/20 3. Q sind und für die es in einem vergangenen Abschnitt (auf "Lernabschnitt/Leistungsdaten" eingetragen) irgendwelche Angaben gibt. 
Wenn man auf  "Individualdaten I" das Schuljahr entsprechend anpasst, funktioniert es.

Die Ursache für das Verhalten ist folgende: Da ja die "aktuellen Laufbahndaten" werden ja jetzt in der neuen Datenbankstruktur nicht mehr bei den Stammdaten der SuS gespeichert, daher ist für eine Filterung auf diese Daten zwingend die Angabe eines "Schuljahresabschnittes" notwendig. Dieser ist standardmäßig mit dem aktuellen Abschnitt vorbelegt. Es gibt folgende Alternativen

1. Das Feld bleibt erst mal leer. Wenn dann aber z.B. auf die Klasse gefiltert wird, ohne dass ein Abschnitt ausgewählt ist, funktioniert die Filterung auf die Klasse nicht. Man könnte dann aber einen Hinweis ausgeben: "Bitte wählen Sie ein Schuljahr bei "Daten des aktuellen oder zuletzt besuchten Abschnittes" aus", wenn in diesem Bereich eine Filterbedingung eingetragen ist. 
2. Das Feld wird vorbelegt, wird aber nur verwendet, wenn auch ein zusätzliches Kriterium für die "aktuellen Laufbahndaten" ausgewählt ist (z.B. Klasse). Dann würde aber eine Filterung auf "Zeige alle SuS, die aktuell in ausgewählten Abschnitt sind" nicht funktionieren (weil da ja keine weiteren Angaben gemacht werden)
3. Es bleibt wie es ist, das Programm macht halt das, was eingetragen ist.

Ich würde Version 1 empfehlen, wie wird das von anderer Seite gesehen.

**Comment by FPfotenhauer** [comment]
Ich gehe auch mit 1.

**Comment by AnneSchueller** [comment]
Ich schließe mich der 1 an.

**Comment by JeVaske** [comment]
1 finde ich auch gut. Wichtig wäre meiner Meinung nach aber, dass das Pulldownmenü "Status" anders positioniert wird. Ich habe gerade schon wieder vergessen, die "Abschluss-Schüler" auszuwählen. Bei Schild 2 passiert mir das nicht.
![Schild_anordnung](https://user-images.githubusercontent.com/78501680/193098785-11a835fb-29bf-45d8-9969-166ba9fbe7be.jpg)

**Comment by JuergenRichter** [comment]
Ich habe das Fenster jetzt etwas umstrukturiert, die Statuseingabe ist jetzt ganz oben
![image](https://user-images.githubusercontent.com/61280188/193225176-28761f80-0335-48ae-a82b-0118f4c1b477.png)

Das Feld für das Schuljahr bleibt jetzt erst mal leer, wenn in dem Bereich was eingetragen wird (z.B. Klasse), ohne dass das Schuljahr gefüllt ist, kommt eine Meldung

![image](https://user-images.githubusercontent.com/61280188/193225612-8b8e9d25-0de5-4f41-a9da-131bbc95e939.png)

Da in den meisten Fällen vermutl. das aktuelle Halbjahr gemeint ist, gibt es dafür nun einen eigenen Schlater, damit man nicht lange in der List scrollen muss:

![image](https://user-images.githubusercontent.com/61280188/193225416-c7e414de-1e16-4681-b930-ececc092a137.png)

**Comment by FPfotenhauer** [comment]
Bitte neu erstellen oder wieder öffnen, wenn weiter Probleme auftreten.
