### ISSUE TITLE
Darstellungsfehler bei 13,3-Zoll-Display

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#401]
Wenn ich Schild auf meinem 13,3-Zoll-Notebook starte, erscheint es wie unten dargestellt. Ich habe keine Möglichkeit, es im Vollbild darzustellen.
![schildfehler23](https://user-images.githubusercontent.com/78501680/193121586-d816d8cb-dd5a-45e4-a2b5-5f896d893cf1.jpg)

**Comment by AnneSchueller** [comment]
Als Monitor-Standard für Schild3 wird Full HD  vorausgesetzt. Eine Übersicht zu Systemanforderungen wird bald veröffentlicht.
