### ISSUE TITLE
Darstellungsfehler Datumsfeld bei 13,3-Zoll-Notebook

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#402]
Das Datumsfeld unter Gruppenprozesse/ Versetzung erscheint auf meinem 13,3-Zoll-Notebook verzerrt.
![schildfehler24](https://user-images.githubusercontent.com/78501680/193122888-1067c0a0-59af-4059-9ae4-07fd96d7b660.jpg)

**Comment by AnneSchueller** [comment]
Als Monitor-Standard für Schild3 wird Full HD  vorausgesetzt. Eine Übersicht zu Systemanforderungen wird bald veröffentlicht.
