### ISSUE TITLE
Umschalten von 13,3 Zoll auf 25 Zoll

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#403]
Wenn ich bei geöffnetem Schild an meinem Notebook die Docking-Station einstecke und vom 13,3-Zoll-Notebook auf den 25-Zoll-Monitor umschalte, kommt ca 25 Sekunden die Uhr und danach folgende Fehlermeldung:
![schildfehler25](https://user-images.githubusercontent.com/78501680/193124113-631a9c3b-dfcf-4ca1-8cea-65cd8fecad87.jpg)

**Comment by AnneSchueller** [comment]
Ich habe ebenfalls Schwierigkeiten beim Anklemmen von meinem Surface über die Docking-Station. Nachdem ebenfalls lange das Ladesymbol erscheint, schließt Schild einfach.

**Comment by JuergenRichter** [comment]
Bitte mal das Fehlerprotokoll posten

**Comment by AnneSchueller** [comment]
Bisher ist das Problem bei mir kein weiteres Mal aufgetreten, sodass ich kein Fehlerprotokoll posten konnte. Ich schließe das Issue jetzt mal und würde es ggf. erneut öffnen.
