### ISSUE TITLE
Restore in leeres Schema

### ISSUE THREAD

**Issue by GerhardHordt** [SVWS-NRW/Schild3-BetaTest#404]
Ich teste z.Zt. einige Tools zur Datensicherung und Wiederherstellung von SchILD3-Datenbanken (DBeaver, HeidiSQL, SQLBackupAndFTP). 
Problemlos ist es, wenn jemand per Gruppenprozess alle 900 SuS eines Gymnasiums in die Klasse 5a versetzt hat. Hier können die Daten einfach durch ein Backup überschrieben werden.
Ist der Zugriff auf die Datenbank fehlerhaft, wird ein neues Schema benötigt, in das dann die Wiederherstellung durchgeführt werden kann. Ich sehe im Moment zwei Möglichkeiten:
- SVWS-Server deinstallieren und mit einem neuen Schema neu installieren.
- Eine leere SchILD2 Standarddatenbank in SchILD3 migrieren.
Hilfreich wäre es sicherlich, könnte man mit dem SVWS-Server-Setup ein leeres Schema erstellen ohne Neuinstallation des SVWS-Servers.

**Comment by FPfotenhauer** [comment]
Das geht bereits. Muss nur noch in der Oberfläche integriert werden.

**Comment by GerhardHordt** [comment]
Super
