### ISSUE TITLE
SchildZentral-Installationen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#405]
In diesem Issue sollen verschiedene Varianten diskutiert werden, wie Schild3 und der SVWS-Server in einer Zentralen Umgebung installiert werden können.

Dabei sollte bedacht werden, dass es in den Kommunen sowohl Terminalserver, Citrix-Lösungen und dezentrale Installationen (Verwaltungsnetz) geben kann.

Grundsätzlich muss hier bei den Kommunen auch abgefragt werden, ob eher Windows- oder Linux-Server gewünscht sind.

**Comment by FPfotenhauer** [comment]
Installationsvariante aus Sicht des SVWS-Server 1:
(kleine Kommune mit wenigen Schulen)

- 1 Debian-Linux-Server mit dem SVWS-Server
- darauf eine Dateifreigabe für die Programmdatei und das Arbeitsverzeichnis für die einzelne Schule
- wahlweise kann auch Schild3 über ein verteilbares Setup auf den Clients installiert werden (Programme x86)
- Schulen haben in ihrem Arbeitsverzeichnis eine SDBCFG-Datei
- In der svwsconfig.json sind alle Schulen enthalten (daran müsste man ggf. etwas ändern)

**Comment by FPfotenhauer** [comment]
Herr Richter schrieb:

Die Situation in Siegburg ist ja relativ einfach, da vermutlich nur ein Citrix-Server zum Einsatz kommt (genaueres werde ich aber noch erfahren). In Köln ist es aber deutlich komplexer, nach meinem Kenntnisstand gibt es da folgende Fälle:

-SchILDzentral ist auf diversen Citrix-Servern installiert, die Schulen, die sich über cdesk (https://cdesk.stadt-koeln.de/vpn/index.html) anmelden, werden irgendeinem Citrix-Server, der am wenigsten ausgelastet ist, zugewiesen (load balancing). Der Zugriff auf die Datenbank (auf einem separaten Datenbankserver) erfolgt über das interne Netzwerk.

-Es gibt aber auch Schulen, bei denen SchILDzentral auf lokalen Rechnern installiert ist, der Zugriff auf den Datenbankserver erfolgt dann über VPN.

In einer solchen Konstellation wäre es m.E. wichtig, die Zugangsparameter zu den einzelnen SchILD-Schemas (z.B. svwsconfig.json) nur an einer Stelle zu verwalten, da es sonst vermutlich sehr unübersichtlich wird.

**Comment by FPfotenhauer** [comment]
In der gestrigen Mail hatte ich ja am Beispiel von Städten beschrieben, dass es recht komplexe Installationsszenarien geben kann. Wenn es dabei auf jedem Rechner, auf dem SchILD3 laufen soll, eine Datei „C:\ProgramData\SVWS-Server\res\svwsconfig.json“ geben muss, wird das vermutl. irgendwann zu Problemen führen, da es schwierig sein wird, die Dateiinhalte synchron zu halten. Meine Überlegung ist folgende:

-In den Verzeichnissen „C:\ProgramData\SVWS-Server\res\svwsconfig.json“ der einzelnen Rechner kann optional eine Datei „svwsconfig_redirect.json“ (o.ä.) liegen, die die Angabe zu einem Verzeichnis auf einem Fileserver enthält. Wenn diese Datei gefunden wird, wird die Datei „svwsconfig.json“ nicht aus „C:\ProgramData\SVWS-Server\res“, sondern aus dem dort eingetragenen Verzeichnis geladen. Die „svwsconfig.json“ wird somit an einer zentralen Stelle gespeichert, Änderungen in brauchen nur einmal gemacht werden. Die „Redirekt-Datei“ wird manuell vom jeweiligen IT-Dienstleister bearbeitet, dieser muss sich auch darum kümmern, dass sie auf die einzelnen Rechnern verteilt wird.
Falls die Datei „Redirect-Datei“ fehlt, ist das Verhalten wie bisher. 
Evtl. könnte SchILD3 dann auch auf die .sdbcfg-Dateien verzichten und die Verbindungsparameter direkt aus der „svwsconfig.json“ lesen.
Obwohl: Ganz wird man darauf vermutl. doch nicht verzichten können, da für Schulungszwecke ja auch auf SQLite zugegriffen werden soll.

Noch eine Überlegung: Ich könnte mir vorstellen, dass bei einer größeren Anzahl von Schulen, die ein IT-Dienstleister verwaltet, es nötig sein könnte, mehrere MariaDB-Server zu betreiben. Derzeit wird die Angabe zum Datenbankserver in der „svwsconfig.json“ ja übergeordnet zu den einzelnen Schemas verwaltet, da kann nur ein Server stehen.

  "SchemaKonfiguration" : [ {
      "name" : "svwsdb",
      "svwslogin" : false,
      "username" : "svwsadmin",
      "password" : "svwsadmin"
    }, {

Könnte man das auch (optional) in den Schemaangaben speichern?
  "SchemaKonfiguration" : [ {
     "location": "192.168.1.1",
      "name" : "svwsdb",
      "svwslogin" : false,
      "username" : "svwsadmin",
      "password" : "svwsadmin"
    }, {

**Comment by FPfotenhauer** [comment]
Installationsvariante 2 aus Sicht des SVWS-Servers:

- große Virtualisierungslösung (z.B. Proxmox, KVM, ESXi, HyperV)
- jede Schule bekommt einen eigenen Container oder eine VM
- hier läuft ein Debian mit einer MariaDB und einem SVWS-Server für jede Schule
- jede Schule hat ihre eigene svwsconfig.json
- Dateifreigabe für Schild3 oder verteites Setup in Programme X86

Dockercontainer vom SVWS-Server sind in Arbeit.

**Comment by JuergenRichter** [comment]
Ich habe zu den Docker-Containern mal eine Frage: 
Wie erfolgt die Verbindung von SchILD3 (befindet sich ja wohl "außerhalb" des Docker-Containers, oder?) zu der MariaDB bzw. zum SVWS-Server (im Docker-Container). Auch z.B. über eine IP-Adresse?

**Comment by FPfotenhauer** [comment]
> Auch z.B. über eine IP-Adresse?

Ja. Da kann man mehrere Wege gehen. Wir haben hier eine Virtualisierungsumgebung, wo wir über einen Reverse-Proxy die verschiedenen IPs und dazu gehörige Subdomains an Container (in diesem Fall LXC) durchreichen können.
Jede Schule wäre dann z.B. über 123456.meinedomain.de erreichtbar. In dem Container kann man auch ein Volume einbinden mit Freigabe der Schild3-Dateien. Das geht aber auch anderns. Z.B. Schild3-Dateien in einem übergeordneten Netzwerkspeicher. Dann nur das Arbeitsverzeichnis der Schule im Container-Volume.

Am besten wäre es ja auch, das Schild3-Setup an die Clients zu verteilen. Bei Terminallösungen (auch cirtrix) wäre das ja auch so machbar.

**Comment by JuergenRichter** [comment]
Danke, ich habe aus folgendem Grund (in Verbindung mit dem "Schulträgermodul" in SchILDzentral:
Für bestimmte Auswertungen (z.B. aktuelle Schülerzahlen pro Schule) muss der Schulträger ja auf die aktuellen Daten der einzelnen Schulen zugreifen können. Wir hatten urspünglich geplant, das über "schemaübergreifede" Views zu lösen. Bei meinen Recherchen im Internet habe ich aber bisher noch keine Lösung für den Fall gefunden, dass die Schulschemas auf verschiedenen MariaDB-Servern liegen (was bei Docker-Containern ja dann wohl auf jeden Fall so wäre). Damit würde die "View-Lösung" wegfallen. Als Alternative käme dann eine "Replikationslösung" in Frage: Die relevanten Daten (das sind ja nur einige Stammdaten, und auch die nur von SuS mit Status "Neuaufnahme", "Warteliste" und "Aktiv") würden dann (z.B. automatisch gesteuert) aus den Schulschemas in das Schulträgerschema übertragen, dort kann der Schulträger dann seine Auswertungen machen.

**Comment by FPfotenhauer** [comment]
Ich schließe das Issue hier einmal. Die verschiedenen Möglichkeiten mit Windows-Install, Linux-Installer und Docker stehen ja mittlerweile zur Verfügung.

**Comment by T-Hagel-SK** [comment]
Bin gerade eher zufällig (bei der Suche nach Proxy-Meldungen) hierüber gestolpert ...
Das waren doch nicht alle Überlegungen, wie man Schild3 in Rechenzentren in den Betrieb nehmen kann, oder ?

Mich würde bei den im Netz verfügbaren Schaubildern interessieren, an welchen Rechenzentren Sie die Konzepte / Vorstellungen konkret festgemacht haben ?

Ich störe mich bis heute weiterhin hartnäckig daran, künftig über 500 Einzeldatenbanken und eine undefinierten Anzahl von 
 50 - 150 Webervern technisch betreuen zu müssen und Updates zu koordinieren. Der Schulträger weigert sich zu akzeptieren, dass ihn die Einführung und der Betrieb von Schild3 nach gegenwärtigem Stand jährlich künftig mehrere 100.000 Euro kosten soll, statt bislang SchildZentral mit rund 3.000 Euro.

Juni 2023, da waren wir doch schon in Kontakt gewesen ... 

Die Angabe oben mit Schulen die über cDesk zugreifen würden, bezieht sich nur auf Köln. Es gibt aber freilich noch weitere Kommunen, die die schulischen Fachanwendungen zentral über Terminalserver bereitstellen.
