### ISSUE TITLE
Probleme mit der Bildschirmauflösung

### ISSUE THREAD

**Issue by GerhardHordt** [SVWS-NRW/Schild3-BetaTest#407]
Ich habe einen Monitor mit einer max. Auflösung von 
![1920x1200](https://user-images.githubusercontent.com/81526810/195812760-f2ee70ec-909b-412c-967f-9ca0e088f24d.jpg)
![1920x1080](https://user-images.githubusercontent.com/81526810/195812919-932d365e-10a7-4278-94d3-4056749530fe.jpg)
1920x1200 Pixeln. In dieser Auflösung befindet sich das SchILD-Fenster an der Oberkante des Bildschirms. Arbeite ich an dem Monitor aber mit einer Auflösung von 1920x1080 ist der obere Teil des Fensters abgeschnitten und man kann das Fenster auch nicht verschieben.

**Comment by GerhardHordt** [comment]
Sorry, ich war zu blöd, die Bilder verkleinert unten anzuhängen.

**Comment by FPfotenhauer** [comment]
Das Problem habe ich auch ab und zu.
Schild3 heftet sich dann oben am Bildschirmrand an, aber der Balken oben ist abgeschnitten...

**Comment by JuergenRichter** [comment]
Das Programm "merkt" sich beim Schließen die Position des Fenster (auf Basis der aktuellen Auflösung). Wenn die Auflösung dann geändert wird, "beißt" sich das evtl. Ich werde mal eine Prüfung einbauen der Art: Wenn obere linke Ecke des Fenster außerhalb des sichtbaren Bereiches, dann z.B. Top=10, left=10

**Comment by JuergenRichter** [comment]
Ist jetzt wie beschrieben umgesetzt

**Comment by JuergenRichter** [comment]
Durch die Deaktivierung der "dpi-awareness" in der neuen Version sollte das Problem eigentlich behoben sein. Ich schließe das Issue daher mal, falls es weiterhin auftreten sollte, bitte wieder öffnen.
