### ISSUE TITLE
Wunsch für neues Feld in Tabelle "Benutzer"

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#409]
Wäre es möglich, in der Tabelle "Benutzer" ein Feld für den "Windows-Benutzernamen" anzulegen. Das könnte den Einlog-Vorgang erleichern, da das Programm dann automatsich den "SchILD-Benutzer" ermitteln könnte, der (als Windows-Benutzer) sich im System angemeldet hat.
Das wird derzeit schon in SchILDzentral so gehandhabt und hat sich da bewährt.

**Comment by FPfotenhauer** [comment]
Laut BSI (wir haben das zufällig heute machen müssen) ist das aber eigentlich nicht zulässig, da die Useer sich dann hat nicht mehr ausloggen können. 

Ist das von den It Abteilungen so zulässig?

**Comment by JuergenRichter** [comment]
"da die User sich dann nicht mehr ausloggen können."
Das verstehe ich nicht ganz. Warum ist dann kein Ausloggen möglich?

"Ist das von den It Abteilungen so zulässig?"
Da haben wir bisher noch keine Probleme gemeldet bekommen. Den Eintrag machen ja i.d.R. die Schulen, wenn sie einen neuen SchILD-Benutzer anlegen.

**Comment by FPfotenhauer** [comment]
Wenn ich das richtig verstehe, startet der User Schild-Zentral und ist sofort angemeldet.
Also kann er sich aus Schild-Zentral nicht ausloggen/abmelden.

Wissen die IT-Sicherheitsleute denn überhaupt davon?

**Comment by JuergenRichter** [comment]
"Wenn ich das richtig verstehe, startet der User Schild-Zentral und ist sofort angemeldet."
Nein, das Progrmm kann dann nur ermitteln, zu welcher Schule der Benutzer gehört und es erscheint der Anmeldedialog der betreffenden Schule (wo man sich aber weiterhin wie üblich anmelden muss).

**Comment by JuergenRichter** [comment]
Ich schließe das Thema, wir werden das für SchILDzentral anders lösen.
