### ISSUE TITLE
Abschnittswechsel unter Werkzeuge

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#41]
Ist der Punkt Abschnittswechsel unter Werkzeuge logisch? Ich würde dort nicht unbedingt nachschauen.

**Comment by Kluesenerm** [comment]
Ich habe mir jetzt die Felder noch einmal genauer angesehen und finden den Punkt Abschnittswechsel unter Werkzeuge extrem bedenklich. Intuitiv werden viele Anwender auf "Allgemeine Angaben" gehen und dort evtl. den Fehler begehen, dort die neuen Schuljahre einzugeben. Ich würden den Schalter zum Abschnittswechsel dort belassen oder einen Hinweis zum Abschnittswechsel anzeigen.
![image](https://user-images.githubusercontent.com/75179015/101702175-a8f84580-3a80-11eb-9432-eb00b082eef5.png)

**Comment by FPfotenhauer** [comment]
Der müsste m.M. nach zu den Gruppenprozessen.
Denn auch die alte Stelle unter Schule bearbeiten fand ich immer unlogisch.

**Comment by JuergenRichter** [comment]
Unter Gruppenprozesse passt das aber auch nicht, da der Schuljahres/Abschnittswechsel ja nichts mit einer Gruppe zu tun hat, sondern die ganze Schule betrifft. So gesehen ist er m.E. doch bei der Schule selbst am besten aufgehoben.
Stelle ich zur Diskussion

**Comment by FPfotenhauer** [comment]
Die ganze Gruppe ist auch eine Gruppe.
Wir sagen schon seit Jahren, dass der Button, so wie er in Schild2.0 angebracht ist, zu sehr vielen Missverständnissen führt.

Es gibt ja auch Gruppenprozesse für die Versetzung. Viele User verstehen einfach nicht, warum das mal da und mal dort ist!
Ich würde das alles an eine Stelle holen.

**Comment by FPfotenhauer** [comment]
Ist jetzt unter Verwaltung Schule.
