### ISSUE TITLE
Tabelle Lehrer nicht mal anwählbar 

### ISSUE THREAD

**Issue by MichaelPeters1983** [SVWS-NRW/Schild3-BetaTest#410]
Sobald man in V. 3.0.46.8 auf Lehrer klickt kommt diese Fehlermeldung
![grafik](https://user-images.githubusercontent.com/111509114/196541329-23b5bc71-47e1-4b97-9cbf-f1bb905b491c.png)

Über den SVWS-Server direkt im Browser ist es kein Problem...

**Comment by JuergenRichter** [comment]
Das ist bei der Umstellung auf API-Aufrufe übersehen worden. Kann ich kurzfristig korrigieren

**Comment by JuergenRichter** [comment]
Ich habe festgestellt, dass das auch bei der Reportausgabe noch nicht korrekt umgesetzt wurde, wird auch kurzfristig korrigiert.
