### ISSUE TITLE
Deinstallieren des Zertifikats

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#412]
Durch Ausführen der delete_services.bat-Datei wird das Zertifikat im Dokumentenordner nicht gelöscht. 
Wäre es evtl. sinnvoll, dass die delete_services das Zertifikat direkt mit deinstallieret?

**Comment by FPfotenhauer** [comment]
Im Testbetrieb braucht man das ja gar nicht immer installieren...

**Comment by AnneSchueller** [comment]
Da ich die Zertifikate nach der Deinstallation nie gelöscht hatte, waren bei mir ziemlich viele Zertifikate für localhost gespeichert. Man kann diese natürlich dann auch "per Hand" wieder löschen.
