### ISSUE TITLE
Version des Servers in log-Datei

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#415]
Wo kann man die aktuelle Version des installierten SVWS-Servers auslesen?
Macht es Sinn, die Versionsnummer mit in die log-Datei zu schreiben?

**Comment by FPfotenhauer** [comment]
Die Version steht in der Registry.
Außerdem kann man die Version im Webclient in der Fußzeile sehen.
Das aber erst seit kurzem, kann sein, dass das in der letzten Version noch nicht drin ist.

**Comment by AnneSchueller** [comment]
Die Versionsnummer zusätzlich im out.log-File hätte den Vorteil, dass man die Versionsnummer kennt, wenn eine Schule Probleme mit dem Client hat und erstmal nur die log-Datei verschickt. Man müsste dann nicht nochmal nachfragen und erklären, wie sie an die Registry-Einträge kommen, sofern sie Zugriff darauf haben.

**Comment by FPfotenhauer** [comment]
Is in der nächsten Version drin.
