### ISSUE TITLE
Verknüpfung mit KM2/Prognos etc.

### ISSUE THREAD

**Issue by MichaelPeters1983** [SVWS-NRW/Schild3-BetaTest#416]
Wir haben uns im Moderatorenteam der BezReg Köln gefragt, wie SchILD 3.0 an externe Programme wie bspw Prognos angebunden werden soll? Hier kann man ja nur über eine udl oder direkt über die mdb anbinden. Ist hier schon eine Lösung angedacht?

**Comment by FPfotenhauer** [comment]
Ist in Arbeit.
