### ISSUE TITLE
Fehler beim Öffnen von BK-Datenbanken mit Schild3

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#417]
Beim Öffnen von BK-Datenbanken mit Schild3 bekomme ich folgenden Fehler:
#42S02Table 'bk.schildintern_zusatzinfos' doesn't exist.

Die Migration ist durchgelaufen. Ich kann die DB sowohl im SVWS-Client öffnen als auch im DBeaver.
Bei Datenbanken anderer Schulformen (Gym, Grundschule, Gesamtschule ung Hauptschule getestet) gibt es beim Öffnen mit Schild3 keine Probleme.
Nur bei den drei getesteten BK-Datenbanken

[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9859576/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Da ist wohl noch ein Verweis auf die Tabelle drin, der aber eigentlich nicht mehr benötigt wird. Korrigiere ich.

**Comment by EwaldReinhardt** [comment]
Dann kann der [Issue 414](https://github.com/SVWS-NRW/Schild3-BetaTest/issues/414) gelöscht werden.

**Comment by AnneSchueller** [comment]
Danke für den Hinweis. Ich hab das Issue geschlossen
