### ISSUE TITLE
Reporteinstellung werden nicht beachtet

### ISSUE THREAD

**Issue by TorstenEngelke** [SVWS-NRW/Schild3-BetaTest#418]
Die Globale Einstellung: "Religion immer aufs Zeugnis" bzw. "auch Leistungsdaten ohne Noten laden" werden vom Programm nicht beachtet. Bei Drucken eines Zeugnisse erscheint dennoch das Fach Religionslehre, auch wenn "Religionslehre immer aufs Zeugnis" nicht angehakt ist. Ebenso werden keine Fächer gezeigt, die keine Noten haben, obwohl der Haken bei "Auch Leistungsdaten ohne Noten laden" gesetzt ist.

**Comment by AnneSchueller** [comment]
Hallo Torsten,
erstmal vielen Dank fürs Testen :-)
Welche DB benutzt du (Grundschule?) und welche Zeugnisversion.
Hat das mit dem gleichen Zeugnisformular unter Schild2 funktioniert?
VG

**Comment by TorstenEngelke** [comment]
Hallo Anne,

ich habe es unter Schild 2.0 mit der Datenbank meiner Schule (HS) ausprobiert und den neuesten Zeugnisreports für die HS. Da passt alles, Religionslehre erscheint nicht auf dem Zeugnis (weil unter Reporteinstellungen nicht angehakt). Fächer ohne Noten erscheinen mit Strich - statt Note - auf dem Zeugnis (weil angehakt ist: "auch Leistungsdaten ohne Noten laden".
Bei Schild 3.0 habe ich unsere Datenbank migriert, hat auch alles geklappt und die Schüler werden richtig angezeigt etc.! Erzeuge ich da ein Zeugnis, auch die neueste Version des Zeugnisreports der HS, dann wird - trotz gleicher Einstellung unter Extras/Programm-Einstellungen/Globale Einstellungen/Reporteinstellungen - Religionslehre immer gedruckt und Fächer ohne Noten erscheinen nicht.
Dasselbe habe ich z.B. auch für eine Realschuldatenbank und dem entsprechenden Report ausprobiert, auch dort zeigt sich dasselbe Bild. Scheinbar werden in 3.0 die entsprechenden Einstellungen nicht berücksichtigt, bzw. verhalten sich genau anders herum als gedacht, wobei ein verändern der Ankreuzhaken unter Einstellungen auch keine Veränderung bringt.

VG, Torsten

> -----Original Message-----
> From: "AnneSchueller" ***@***.***>
> Sent: 25.10.2022 21:51
> To: "SVWS-NRW/Schild3-BetaTest" ***@***.***>
> Cc: "TorstenEngelke" ***@***.***>
>  "State change" ***@***.***>
> Subject: Re: [SVWS-NRW/Schild3-BetaTest] Reporteinstellung werden nicht beachtet (Issue #418)
> 
> 
> Hallo Torsten,
> erstmal vielen Dank fürs Testen :-)
> Welche DB benutzt du (Grundschule?) und welche Zeugnisversion.
> Hat das mit dem gleichen Zeugnisformular unter Schild2 funktioniert?
> VG
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/SVWS-NRW/Schild3-BetaTest/issues/418#issuecomment-1291059816
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***>

-- 
Mit freundlichen Grüßen,
Torsten Engelke

0152/28572080

**Comment by JuergenRichter** [comment]
Ist behoben
