### ISSUE TITLE
Sonderzeichen bei Zertifikatsangaben

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#419]
Gibt man bei der Installation vom SVWS-Server bei den Zertifikatsangaben ein Leerzeichen ein, so wird der User unmittelbar gewarnt, dass dies kein zulässiges Zeichen ist.
Bei Sonderzeichen fehlt die Warnung. Erst später kommt eine Fehlermeldung, der man nicht entnehmen kann, warum die Installation nicht geklappt hat.  Aus dem log-File ist es zwar ersichtlich, aber wünschenswert wäre es, wenn auch beim Sonderzeichen unmittelbar ein Hinweis erscheint.

**Comment by ThomasBachran** [comment]
@AnneSchueller : Welche Sonderzeichen sind denn nicht erlaubt?

**Comment by AnneSchueller** [comment]
Bisher habe ich nur + und _ getestet.
Im Keystore.log kommt dann auch die Fehlermeldung dass nur Ziffern, Buchstaben und Bindestrich erlaubt sind:

"keytool error: java.lang.RuntimeException: java.io.IOException: DNSName components must consist of letters, digits, and hyphens"

**Comment by FPfotenhauer** [comment]
Ist im Installer umgesetzt.
