### ISSUE TITLE
DropDown Felder mit Lehrern

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#42]
Mir ist aufgefallen, dass in vielen DropDown Felder mit Lehrern die Eingabe des Anfangsbuchstaben nicht funktioniert. Z.B. Klassen/Versetzungstabelle, Schüler/akt.HJ/allg. Angaben. .... aber: bei Leistungsdaten/Lehrkraft funktioniert es noch

**Comment by JuergenRichter** [comment]
In Version 3.0.8 behoben
