### ISSUE TITLE
Fehler beim Starten der DB (SVWS-Server)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#420]
Version 0.2.18

Die vorherige Installation wurde deinstalliert, dann wurde die .bat ausgeführt.

![Fehler 1](https://user-images.githubusercontent.com/116796098/198231309-32e2ce71-3053-4afb-9983-6ac1c63143b1.png)

**Comment by FPfotenhauer** [comment]
Ist das Windows 11?
Wenn man die delete_services.bat ausführt, dann braucht man vorher nicht deinstallieren.

**Comment by AnneSchueller** [comment]
Hattest du bei der Deinstallation noch eine log-Datei oder so geöffnet?
Ich hatte die gleiche Fehlermeldung als im Ordner ProgramData noch Inhalte waren. Im Log-File stand am Ende sowas:

(Eclipse Persistence Services - 3.1.0-M1.v202108080909): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Socket fail to connect to host:localhost, port:3306. Connection refused: no further information
**Error Code: -1**

**Comment by FrodBRA** [comment]
Lösung des Problems: Der Zugriff auf den **existierenden** Data-Pfad war in Windows zusätzlich durch Administrationsrechte gesichert; eine Löschung des Pfades (welcher voller Altlasten war) löste das Problem, dass der DB-Server nicht gestartet werden konnte und auch dass der Data-Pfad nicht vom Standard weg umbenannt werden konnte.
