### ISSUE TITLE
Pfade bei SVWS-Installation können nicht (frei?) geändert werden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#421]
Bei der Installation des SVWS-Servers traten Probleme bei der Änderung der Pfade auf.
 
Teils funktioniert eine Änderung, so lief etwa die Installation mit den Standardpfaden oder nur D:\SVWS-Server normal an, eine weitere Änderung (siehe Bild) erzeugt jedoch den folgenden Fehler:

![Fehler 2](https://user-images.githubusercontent.com/116796098/198234065-e6c13290-66d2-4d51-8934-ab6ade278041.png)

**Comment by MichaelPeters1983** [comment]
Ich hatte ein ähnliches Problem bei der Neuinstallation. Schau mal nach, ob in Windows_Old noch Reste des SVWS Servers rumgeistern und dann nochmal die deleteservice.bat als Admin ausführen. Danach lief es bei mir.

**Comment by FrodBRA** [comment]
Lösung des Problems: Der Zugriff auf den **existierenden** Data-Pfad war in Windows zusätzlich durch Administrationsrechte gesichert; eine Löschung des Pfades (welcher voller Altlasten war) löste das Problem, dass der DB-Server nicht gestartet werden konnte und auch dass der Data-Pfad nicht vom Standard weg umbenannt werden konnte.
