### ISSUE TITLE
Bezeichnung der verfügbaren Datenbanken beim Starten von Schild

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#422]
Die Namensgebung der Datenbanken, die man auswählen kann, ist nicht konsistent:
Im SVWS-Server wird immer der DB-Schemaname gewählt.
In Schild3 wird für die Bezeichnung

- der Schemaname der Anfangsmigration gewählt oder
- der Name der ausgewählten UDL-Datei (Bei Auswahl "4. Expertenmodus") oder
- der Name der ausgewählte DB, falls man diese manuell auswählt.

Das ist etwas verwirrend
![Bild1](https://user-images.githubusercontent.com/79116896/198609270-c9ac0be2-6a2f-4f92-84f4-c8812fe71194.png)

**Comment by JuergenRichter** [comment]
Beim Start werden die Namen der .sdbcfg-Dateien aufgelistet (ohne die Dateierweiterungen), die sich im Verzeichnis \sdbcfg unterhalb des Arbeitsverzeichnisses befinden. Es hängt dann davon ab, wie diese entstanden sind:

1. Wenn in MigrateDB.exe der "Expertenmodus" (4) verwendet wird und dabei der Zugriff auf eine SchILD2-Datenbank über die UDL-Datei von SchILD2 erfolgt, so bekommt die sdbcfg-Datei den gleichen Namen wie die UDL-Datei.

2. Wenn im Expertenmodus die Schild2-Datenbank manuell ausgewählt wird, so bekommt die sdbcfg-Datei den Namen der gewählten mdb.

3. Wenn die Optionen 1 bis 3 (in MigrateDB.exe) verwendet werden, ist ja schon eine Migration durchgeführt worden, dann wird der Name des gewählten Datenbankschemas für die sdbcfg-Datei vorgeschlagen, der kann dann aber auch geändert werden.

Man könnte überlegen, dass beim Expertenmodus auch die Möglichkeit geschaffen wird, den Namen der sdbcfg-Datei festlegen zu können.

**Comment by JuergenRichter** [comment]
Ich habe das in MigrateDB nun so geändert, dass im Expertenmodus für den amen der SDBCFG-Datei auch der Name des betreffenden Schemas vorgeschlagen wird, der Benutzer kann das aber auch ändern.

**Comment by JuergenRichter** [comment]
Ich schließe das mal, ist umgesetzt
