### ISSUE TITLE
neue Benutzerkompetenzen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#423]
- Für neue Teile, wie 
  - [x] Laufbahnplanung und 
  - [x] Kursverwaltung, 
  - [x] Klausurplanung 
  - [x] Notenmodul (Administration, Nutzung)
  - [x] SQLite Backup (Bitte mit der vorhandenen prüfen.)
werden neue Kompetenzen und -gruppen benötigt

Ich muss ehrlich gestehen, dass ich bei den Kompetenzgruppen diese 100er Nummerierung nicht verstehe.
Aber sollen wir einfach weiter in 100er-Schritten hochzählen?

Was ist mit den Kurs42-Kompetenzen?
Sollen wir das Backup aus Extras herausholen? Datenbankadministration? (Schemaverwaltung?

Gibt es noch andere Vorschläge für Kompetenzen und -gruppen?

Wichtig! Schild3 darf keine Kompetenzen oder Gruppen mehr einfach anlegen. Das muss der SVWS-Server machen.

**Comment by FPfotenhauer** [comment]
Vorschlag Backup und Schemaverwaltung:

Kompetenzgruppe 800
Kompetenzen:
- 71 auf 800 Backup durchführen
- 72 auf 800 Backup wieder herstellen
- 96 Backup wieder herstellen
- 97 neues Schema erstellen und löschen
- 98 Migration durchführen

**Comment by JuergenRichter** [comment]
Die 100er-Teilung war deshalb gewählt worden, weil man dann noch zusätzliche Gruppen an der entsprechenden Stelle einsortieren konnte (die Sortierung erfolgt nach der KG_ID).
Ansonsten können wir das so wie vorgeschlagen übernehmen, einige der genannten Punkt gibt es ja noch nicht (z.B. Backups), da kann man das dann gleich berücksichtigen.
rage zu SQLite-Backup: Ist das im SVWS-Server schon umgesetzt? Ich habe das nämlich mal in der Swagger UI ausprobiert, da kommt aber eine Fehlermeldung:
Error: response status is 406
Welcher Benutzer muss denn da verwendet werden?

**Comment by FPfotenhauer** [comment]
> Frage zu SQLite-Backup: Ist das im SVWS-Server schon umgesetzt? Ich habe das nämlich mal in der Swagger UI ausprobiert, da kommt aber eine Fehlermeldung:
> Error: response status is 406
> Welcher Benutzer muss denn da verwendet werden?

Der GET Befehl kann mit dem Schild-Benutzer ausgeführt werden.
Für den POST-Befehl benötigt man den MariaDB-Root Zugang.

Der Service funktioniert momentan nicht, weil das noch nicht angepasst wurde.
Wir reparieren das, wenn alle Tabellen die nicht mehr notwendig sind, aus dem Schema entfernt wurden.

**Comment by ThomasBachran** [comment]
Der Dienst wird vermutlich wieder funktionieren, wenn ich die ganzen Views zur Emulation der Schild-Intern und Statkue-Tabellen entfernen konnte. Ich habe geplant das zu überprüfen, wenn wir die Umstellungen dort abgeschlossen haben...

**Comment by FPfotenhauer** [comment]
@JuergenRichter 

Die Benutzerkompetenzen müssten jetzt auch in der API zur Verfügung stehen.
Frage ist hier, ob Sie die alle so unterstützen wollen, wie wir das auch im SVWS-Server machen?
Ishak B. ist gerade dabei das im Client umzusetzen, wir könnten das gemeisam parallel umsetzen oder in Schild3 die neuen Kompetenzen ignorieren.

**Comment by FPfotenhauer** [comment]
Die Benutzerkompetenzen stehen alle in der API zur Verfügung und können auch im WebClient angesehen werden.
