### ISSUE TITLE
Fehlermeldung Start Schild3 keine Verbindung zum SVWS-Server

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#424]
Die Exception sollte abgefangen werden und es sollte eine Meldung gegeben werden, dass der Server nicht erreichbar ist.
Außerdem sollte dort so etwas stehen wie "Bitte wenden Sie sich an Ihren Administrator.".
Dann sollten die Optionen "Erneut versuchen" und "Programm beenden" zur Verfügung stehen.

**Comment by JuergenRichter** [comment]
Um welche Exception geht es?

**Comment by FPfotenhauer** [comment]
![SNAG_2022_10_31_12 42 08](https://user-images.githubusercontent.com/34127980/199000045-1bad41bc-768f-4936-8e01-5fc6d6eaf5a5.png)

**Comment by JuergenRichter** [comment]
Eigentlich habe ich einen "Exception-Abfanger" beim Lesen der Kataloge eingebaut, habe aber gerade gesehen, dass der bei den Fachklassen nicht aufgerufen wird, weil für diese eine eigene Leseroutine existiert. Setze ich kurzfristig um.
