### ISSUE TITLE
Filter 1 im Reiter Schüler

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#426]
Es kommt der Wunsch auf, dass ein Icon "Filter 1" im Reiter Schüler unter "Suchen, Filtern und sortieren" hinzugefügt wird.
Da Filter 1 sehr oft genutzt wird und aktuell die Schulen auch meistens über das Icon Filter 1 aufrufen, finde ich den Vorschlag gut. 
Also hier irgendwo:
![2022-11-04_130540](https://user-images.githubusercontent.com/79116896/199969413-ce3efcb5-ad3f-4374-92d0-c65fa0cfcbe3.png)

Wie sehen das die anderen?

**Comment by FPfotenhauer** [comment]
Wenn man einfach auf Auswahl klickt, dann hat man Filter I.
Wozu dann noch ein weiteres Icon?

**Comment by Raffenberg** [comment]
Ich möchte hier Frank beipflichten. Aber vielleicht könnte man noch einmal über die Reihenfolge der Karteireiter sprechen. Nach meinem Empfinden sollte die Auswahl neben den Schülern plaziert werden und die Kataloge an das Ende.

**Comment by AnneSchueller** [comment]
Das sehe ich auch so mit der Reihenfolge

**Comment by FPfotenhauer** [comment]
Das ist mir vollkommen egal. Ich halte aber nichts davon Issues zu vermischen.
