### ISSUE TITLE
Export Text Excel Dateien

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#429]
![SNAG_2022_11_05_11 58 28](https://user-images.githubusercontent.com/34127980/200116614-e4289281-e980-43a0-9d7c-f85b1e898302.png)

**Comment by JuergenRichter** [comment]
Ich habe festgestellt, dass der API-Aufruf "https://localhost/db/{schema}/schild3/export/csv" (der die Felder bereitstellt, die für den Export genutzt werden können) noch eine größere Anzahl von Einträgen bei "LookupSQLText" enthält, die noch auf die alte Datenbankstruktur zugreifen. Ich kann das anpassen aund als Json-Datei bereitstellen.

**Comment by FPfotenhauer** [comment]
Für was wird denn die Tabelle schildintern_schuelerimpexp genutzt? Für des externe Importprogramm?

**Comment by JuergenRichter** [comment]
Ja, sonst nicht

**Comment by FPfotenhauer** [comment]
> Ich kann das anpassen aund als Json-Datei bereitstellen.

[TextExport.csv](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10041384/TextExport.csv)

Wenn wir das in dieser CSV aktualisiert bekommen, wäre das perfekt.

**Comment by FPfotenhauer** [comment]
> Ja, sonst nicht

Dann nehmen wir die raus und beraten 2023 darüber, ob wir den externen Import noch benötigen.

**Comment by JuergenRichter** [comment]
OK

**Comment by FPfotenhauer** [comment]
SchildIntern_FaecherSortierung

Das ist uns auch nicht ganz klar, wir haben die mal gelöscht und es funktioniert alles, bei den Fächern.
Oder wird die woander verwendet?

**Comment by JuergenRichter** [comment]
Die Tabelle ist schon auf REST-Abfrage umgestellt, könnte rausgenommen werden.

**Comment by FPfotenhauer** [comment]
👍

**Comment by JuergenRichter** [comment]
Ich habe mal eine erste angepasste Version der Tabelle "TextExport" beigefügt. Weil nun einige Daten, die bisher aus "echten" Katalogtabellen per SQL geholt werden konnten, über die API bereitgestellt werden (z.B. Nationalitäten, Verkehrssprachen) mussten einige technische Änderungen gemacht werden, die ich gerne testen möchte. Da es die Tabelle "TextExport" nicht mehr gibt (die ich selbst befüllen könnte), wäre es günstig, kurzfristig eine Version des SVWS-Servers zu bekommen, der die für den Text-/Excel-Export verfügbaren Felder (aus der beigefügten Datei) zur Verfügung stellt.
[TextExportNeu.csv](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10507470/TextExportNeu.csv)

**Comment by FPfotenhauer** [comment]
Ich tausche gerade die Daten aus und baue den Server neu.
Kann ich das vorab irgendwie testen?

**Comment by JuergenRichter** [comment]
Im Prinzip reicht es, wenn man mal den Datenexport aufruft und "Schüler" als Datenart wählt
C:\Users\juerg\Desktop\2023-02-01 16_21_09-Aktuelle Datenbank_ svwsdb-gy, Schuljahr 2018_2019, 4. Qu., Benutzer_ Admin (Ver.png
Dann "Ortsname" wählen und exportieren.
![image](https://user-images.githubusercontent.com/61280188/216084450-1d58975b-e7f0-4f0f-a829-e83ae6709d08.png)

Wenn das korrekt in der Exportdatei ankommt (und ich mich bei der Formulierung des entsprechenden SQL-Befehles nicht vertan habe), sind die Angaben im SVWS-Server korrekt enthalten.

**Comment by FPfotenhauer** [comment]
Eine angepasste SVWS-Server Version lade ich gerade hoch, bei mir funktioniert der Export.
