### ISSUE TITLE
Schüler & Lehrerfotos

### ISSUE THREAD

**Issue by AlexanderDedy** [SVWS-NRW/Schild3-BetaTest#43]
Es wäre für das Sekretariat hilfreich, wenn vorhandene Fotos zumindest klein bei Individualdaten angezeigt werden. Bei Lehrern gibt es ein größeres Symbol, aber es wird kein vorhandenes Bild angezeigt... Irgendwo freigeben?

**Comment by FPfotenhauer** [comment]
Das Schülerfoto wird doch oben in der Leiste angezeigt? Oder verstehe ich etwas nicht.
Die Lehrerfotos müssen noch auf Base64 umgestellt werden, dann werden die auch angezeigt.

![SNAG_2020_12_11_11 26 33](https://user-images.githubusercontent.com/34127980/101892491-bd812e80-3ba3-11eb-9255-0f7b9a47e514.png)

**Comment by AlexanderDedy** [comment]
Ich hatte noch keine Fotos geladen, da sah es dann so wie wie SchiLD 2 aus.... Deshalb die Meldung...

![Bildschirmfoto 2020-12-11 um 11 50 12](https://user-images.githubusercontent.com/75326793/101895450-d68bde80-3ba7-11eb-8d68-ee6828407824.png)

**Comment by JuergenRichter** [comment]
In 3.0.8 sind alle Foto-Funktionen auf die neuen Base64-Felder umgestellt.
