### ISSUE TITLE
Reporting: NULL-Einträge in Sprachenfolge werden als große Integer-Werte ausgegeben

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#430]
In Schild Ver. 3.0.48.8 werden NULL-Einträge in Feldern der Sprachenfolge bei der Ausgabe in der Reporting durch große Integer-Werte ausgeben.

Das gilt sowohl bei der Verwendung von Feldern im Designer als auch im RAP Code wie diesem hier: ShowMessage(IntToStr(Sprachenfolge['JahrgangBis']));

Schild 2 gibt hier 0 aus. Das macht die Entwicklung der Reports deutlich berechenbarer.

**Comment by JuergenRichter** [comment]
Behoben
