### ISSUE TITLE
Transparentes PNG-Schullogo verhindert Start von Schild 3

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#431]
Löscht man in Schild 3.0.48.8 ein vorhandenes Schullogo und lädt dann ein neues Logo in Form eines PNG mit transparentem Hintergrund, so stützt Schild 3 beim nächsten Start mit der Meldung "" ist kein gültiger Integer ab.

Edit: Log-Datei unten eingefügt.

**Comment by JuergenRichter** [comment]
Ausgerechnet der wichtigste Teil des Protokolls ("Call stck") wird leider nicht korrekt angezeit. Wäre es möglich, das Protokoll als Text-Datei zu bekommen ("Copy to clipboard" aktivieren, dann Editor starten und Inhalt der Zwischenablage per Strg-V einfügen, dann Datei speichern und hier hochladen)

**Comment by M-Plu** [comment]
[PNG-Start-Error.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/9959309/PNG-Start-Error.txt)

Ich hoffe, dass ist nun lesbarer. Und noch eine Ergänzung. Ist das gleiche Logo in der Schild 2 DB gewesen und wurde migriert, dann startet Schild 3 auch mit der DB (es wird dann aber mit schwarzem Hintergrund angezeigt, siehe #432 ). Evtl. liegt daher der Fehler auch beim Laden des Bildes in die DB.

**Comment by JuergenRichter** [comment]
Danke, ist nun lesbar.

**Comment by JuergenRichter** [comment]
Kann ich mal die png-Datei haben?

**Comment by M-Plu** [comment]
Ist per E-Mail zu ihnen auf dem Weg.

**Comment by JuergenRichter** [comment]
Ich habe nun die aktuellste Version des ReportBuilders installiert. Damit funktioniert die Darstellung, wenn man folgende Einstellungen beim DBImage macht:
-Als Grafikart muss explizit PNG zugewiesen werden
-Es muss die Option "Durchsichtig" aktiviert werden

**Comment by JuergenRichter** [comment]
Die genannte Fehlermeldung beim Start hat übrigens nichts mit dem Logo zu tun, sondern trat bei  Laden der Farbeinstellungen für die Fächergruppen auf, und zwar dann, wenn zu einer Gruppe keine Einstellung gefunden wurde. Das ist jetzt aber abgefangen.
