### ISSUE TITLE
Reporting: DB-Image in Form eines transparenten PNG-Logos wird immer mit schwarzen Hintergrund angezeigt

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#432]
Ein Schullogo mit transparenten Hintergrund wir in der Reporting mit schwarzem Hintergrund angezeigt während es in Schild 2 korrekt angezeigt wird. Lädt man das Bild über die normale Image-Komponente in den Report, wird der Hintergrund transparent angezeigt.

**Comment by JuergenRichter** [comment]
Siehe #431
