### ISSUE TITLE
Anordnung der Reiter in Schild-NRW3

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#433]
Aufgrund der Nutzungshäufigkeit von Filtern (und auch in Absprache mit Herrn Raffenberg und Herrn Pfotenhauer) wäre es sinnvoll, wenn rechts neben dem Reiter "Schüler" erst der Reiter "Auswahl", dann "Gruppenprozesse" und rechts daneben erst "Kataloge" aufgelistet werden. Könnte das in Schild3 so umgesetzt werden?

**Comment by JuergenRichter** [comment]
Sollte kein Problem sein

**Comment by JuergenRichter** [comment]
ist umgesetzt
