### ISSUE TITLE
Namenskonvention SchILD-NRW 3

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#434]
Zur Verdeutlichung, dass es sich bei dem Programm um ein Schulverwaltungsprogramm aus NRW handelt, haben wir uns auf folgende Namenskonvention geeinigt:
"SchILD-NRW 3"
An einigen Stellen taucht der Name "Schild3" o.ä. auf. Könnte dies angepasst werden? 
Beispielsweise oben in der Leiste von dem Hinweistext zu personenbezogenen Daten.

**Comment by JuergenRichter** [comment]
Ich mache das Thema mal zu, bei Bedarf wieder öffnen.
