### ISSUE TITLE
Erstellung von neuen dynamischen Datenquellen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#436]
Dies ist ein Folge-Issue von #413.

Dort wurde mehrere Diskussionen vermischt, hier soll die dynamische Reporting weiter entwickelt werden.

**Comment by M-Plu** [comment]
Ich habe mir die Version 3.0.51.8 diesbezüglich angesehen. Dabei galt mein erster Augenmerk der Schaltfläche "Info über Datenquellen". Dort habe ich zwei Fehler festgestellt.

Noch bevor das Fenster erscheint, erhalte ich folgende Meldung, wobei es sich dabei anscheinend um einen Tippfehler im Abfragestring handelt:

![image](https://user-images.githubusercontent.com/48728275/210451462-1f11348c-56de-430e-8f4c-9db637ad0ee7.png)

Der zweite Punkte ist die dann erzeugte Ansicht.

![image](https://user-images.githubusercontent.com/48728275/210451735-c95701ef-3bff-48c1-8c54-22a3cd1f308a.png)

Die beiden dyn-Datenquellen haben die Masterdatenquelle Schueler und müssten daher im Baum unter Schüler einsortiert werden.

**Comment by M-Plu** [comment]
Der angehängte Beispiel-Report mit dieser Struktur 

![image](https://user-images.githubusercontent.com/48728275/210452245-02824a8f-c62c-4cc8-b0fa-eeaceecdc4c4.png)

liefert pro Schüler alle belegten Halbjahre, aber die Leistungsdaten pro Halbjahr werden nicht ausgegeben. Leider sind die Halbjahre unsortiert.

[Report_mit_dyn_Datenquellen.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10340222/Report_mit_dyn_Datenquellen.zip)

**Comment by ThomasBachran** [comment]
> Der angehängte Beispiel-Report mit dieser Struktur
> 
> ![image](https://user-images.githubusercontent.com/48728275/210452245-02824a8f-c62c-4cc8-b0fa-eeaceecdc4c4.png)
> 
> liefert pro Schüler alle belegten Halbjahre, aber die Leistungsdaten pro Halbjahr werden nicht ausgegeben. Leider sind die Halbjahre unsortiert.
> 
> [Report_mit_dyn_Datenquellen.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10340222/Report_mit_dyn_Datenquellen.zip)

Eine Vorsortierung sollte durch die dynamische Datenquelle selbst erfolgen. Für eine spätere Sortierung muss sichergestellt sein, dass die RAP-Funktion setzeSortierung auch mit dynamischen Datenquellen zurechtkommt.

**Comment by JuergenRichter** [comment]
Sortieroption ist umgesetzt

**Comment by JuergenRichter** [comment]
Beispielreport funktioniert jetzt auch. Ich werde morgen eine neue Programmversion zur Verfügung stellen.

**Comment by JuergenRichter** [comment]
Die dynamischen datenquellen erscheinen jetzt auch bei den Infos zu den Datenquellen

![image](https://user-images.githubusercontent.com/61280188/218087285-08c527d1-064b-4a30-b4f3-a4fda9f57997.png)

**Comment by JuergenRichter** [comment]
Die obige Abbildung impliziert, dass die DQ dynSchuelerleistungsdaten immer abhängig ist von der DQ dynSchuelerlernabschnitte. Das ist aber nicht der Fall, im Prinzip kann dynSchuelerleistungsdaten auch als Subrrport zu jeder anderen "Lernabschnittsdatenquelle" verwendet werden. Die Abhängigkeiten werden also durch die Architektur des jeweiligen Reports bestimmt, nicht durch die Einordnung bei "Infos zu Datenquellen".

Beigefügt ist ein Report, bei dem "dynSchuelerleistungsdaten" als Subreport zu "dynSchuelerlernabschnitte" verwendet wird, aber auch als Subreport zu "Lernabschnitte". Diese DQ liefert aber im Gegensatz zu "dynSchuelerlernabschnitte" nur die Angaben zum aktuellen Halbjahr, damit gibr "dynSchuelerleistungsdaten" dort auch nur die aktuellen Leistungsdaten.

Der Report funktioniert natürlich nur mit der Version 3.0.0.55.9, die in Kürze bereitgestellt wird.
[Report_mit_dyn_Datenquellen_JR.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10707317/Report_mit_dyn_Datenquellen_JR.zip)

**Comment by JuergenRichter** [comment]
Zur Sortierung von dynamischen Datenquellen:
Hier kann auch "SetzeSortierung" verwendet werden, optional auch mit "desc" bei den betreffenden Feldern (um eine absteigende Sortierung bewirken)
 SetzeSortierung( dynSchuelerlernabschnitte, 'schuljahr desc,abschnitt desc' );

**Comment by JuergenRichter** [comment]
Noch ein Hinweis: In der derzeitigen Version werden die Daten der dyn. Datenquellen "on demand" geladen, d.h. die Leistungsdaten in "dynSchuelerLeistungsdaten" werden beim Datensatzwechsel z.B. in "dynSchuelerLernabschnitte" zum jeweiligen Hauptdatenatz (=Lernabschitt) über einen REST-Befehl vom SVWS-Server angefordert, was sehr viele "kleine" Serverabfragen zur Folge hat. Das soll aber demnächst so umgestellt werden, dass die Daten über eine "groß" Abfragen "in einem Rutsch" geholt werden, beim Datensatzwechsel erfolgt dann nur eine passende Filterung in der "virtuellen" Tabelle, in der die Daten gehalten werden. Das hat dann weniger Server-Anfragen zur Folge.

**Comment by JuergenRichter** [comment]
Noch ein Hinweis: Bei, "on demand"-Verfahren für die Leistungsdaten ist das Problem "Fehlermeldung des SVWS-Servers, wenn zum Lernabschnitt keine Leistungsdaten vorhanden sind" nicht so schlimm, (der Fehler wird intern abgefangen), das Ergebnis ist halt leer, beim nächsten Lernabschnitt kommt dann wieder was. Wenn man das aber "auf einen Rutsch" holt, ist das natürlich problematischer, da gar nichts ankommt (auch für die Lernabschnitte, wo Leistungsdaten vorhanden sind).

**Comment by ThomasBachran** [comment]
@JuergenRichter : Zu den beschriebenen Fehlern: Die Fehler sind zum Teil so beabsichtigt und zum Teil waren die Datenquellen bisher nur zum grundlegenden Testen des Funktionsprinzip implementiert. Eine inhaltlich komplett korrekte Erstellung der Daten war bisher noch nicht beabsichtigt. Ich habe dennoch in der aktuellen SVWS-Server (Installer folgt später) ein paar Anpassungen vorgenommen. Das Verhalten ist jetzt - in Bezug auf die Datenquelle für die Leistungsdaten - wie folgt:

- Die Angabe einer fehlerhaften Lernabschnitts-ID führt jetzt zu einer HTTP-Response 404-NOT_FOUND (vorher fehlerhaft 409-CONFLICT). Schild3 sollte in diesem Fall einfach die Fehlermeldung `Parameter der Abfrage ungültig: Ein Schülerlernabschnitt mit der ID 12 existiert nicht.` an den Anwender weiterreichen. Dieser Fehler sollte doch eigentlich nur bei inskonsistenten Daten in der DB auftreten, oder?
- Allgemeine Reaktion bei HTTP-Responses 4XX und 5XX sollten eskaliert und an den Anwender weitergemeldet werden. Das betrifft auch die Fehlermeldung mit dem fehlenden Fachlehrer-Eintrag (auch wenn es sich hier inhaltlich um einen Fehler in der Datenquelle handelt, der in der neuen Version des SVWS-Servers behoben ist). Das Eskalieren der Fehlermeldung ist aus mehreren Gründen wichtig:
  - Bei getesteten Datenquellen: Den Benutzer auf falsche bzw. inkonsistente Daten hinzuweisen. Der Anwender soll - wenn es sich um erwartete Fehler handelt - (halbwegs) verständliche Rückmeldungen zu dem Fehler erhalten.
  - Bei fehlerhaften Datenquellen: Die Fehlermeldungen sind dann für uns interessant, um die Datenquellen korrigieren zu können. In der neuen Version der Datenquelle werden jetzt beim Fachlehrer null-Werte geliefert, so dass der Fehler nicht mehr auftritt

Eine Rückmeldung sollte auf jeden Fall erfolgen. Man könnte jedoch einen Fallback einbauen, falls die 404-NOT_FOUND Antwort kommt. Hier könnte Schild3 auf Nachfrage beim Benutzer vom "auf einen Rutsch"-Verfahren auf Einzelabfragen ausweichen.

**Comment by JuergenRichter** [comment]
@ThomasBachran
"Dieser Fehler sollte doch eigentlich nur bei inskonsistenten Daten in der DB auftreten, oder?"
Der kann eigentlich nicht (oder nur unter sehr exotischen Bedingungen) auftreten. Es werden ja im Programm die Lernabschnitts-IDs der jeweiligen Schülerauswahl ermittelt und dann an den SVWS-Server übergeben. D.h. die IDs existieren zu diesem Zeitpunkt auch. Nur für den (sehr theoretischen Fall), dass zwischen dem Holen der IDs und dem Aufruf der API-Funktion (mit den ermittelten IDs) ein betreffender Lernabschnittsdatensatz gelöscht wird, könnte es zu einem Fehler kommen.

**Comment by JuergenRichter** [comment]
@M-Plu 
2Was jedoch komisch ist, dass in der aktuellen Version (Schild 3 und Server) alle Datenfeld der dynamischen Quellen als String angezeigt werden (Info zu Datenquellen, Feldassistent im Designer). Ich mir ziemlich sicher, dass das mal anders war. Im JSON sind die Datentypen korrekt."
Ich habe festgestellt, dass zwei Datentypen ("date" und "memo") nicht explizit berückischtigt wurden (ist nun aber umgesetzt), in solchen Fällen wurde bisher "WideString" gesetzt. Integer-Typen sollten aber auch als "integer" angezeigt werden.
Hinweis: Alle String-Felder bekommen den Datentyp "WideMemo", da es wohl schwierig ist, vom SVWS-Server die Feldlänge (die bei "String" oder "WideString" benötigt wird) zu liefern. WideMemo ist da flexibler, und kann in den virtuellen Tabellen (im Gegensatz zu "richtigen" Datenbankabfragen) auch zum Sortieren verwendet werden.

**Comment by JuergenRichter** [comment]
Ich habe jetzt eine Prozedur "JsonFehlerZeigen" geschaffen, die im "AfterPrint"-Ereignis aufgerufen werden kann. Wenn es bei der Ausgabe Fehler gegeben hat, werden diese in einem separaten Fenster ausgelistet. Aktualisierte Version stelle ich heute zur Verfügung.

**Comment by JuergenRichter** [comment]
Noch ein Hinweis: Es gibt jetzt auch für die vom SVWS-Server gelieferten Datenquellen eine Möglichkeit zu filtern. Beispiel:
  SetzeFilter( dynSchuelerlernabschnitte, 'schuljahr>2020' ); 

Streng genommen gibt es zwei Filterdefinitionen: 
Eine "interne" Filterung, die dafür sorgt, dass aus der Gesamtmenge der Daten (z.B. alle Lernabschnitte der ausgewählten Schüler) nur die für den jeweils aktuellen Datensatz (in der Hauptdatenquelle) benötigten Lernabschnitte angezeigt werden

Und eine benutzerbezogene Filterung (siehe obiges Beispiel), über die die interne Filterung noch weiter eingeschränkt werden kann.

Mit anderen Worten: Die interne Filterung erfolgt automatisch, darum muss man sich im Report nicht kümmern.

**Comment by M-Plu** [comment]
Bzgl. der WideString Felder. Die haben aber den Nachteil, dass sie beim Drag&Drop im Designer aus der Feldliste als Memo statt als DBText umgesetzt werden. Eine Unterscheidung wäre daher gut.
Denn wenn es den Type Memo schon gibt, dann würde ich Memo als Type für die Memo-Felder verwenden, der Rest wäre dann DBText.
@ThomasBachran Oder spricht da intern was gegen?

**Comment by ThomasBachran** [comment]
@M-Plu : Wenn ich es richtig verstanden habe, dann müsste man für DBText, die "String" der "WideString" nutzen die max. Länge des String spezifizieren. Da müssten wir auch serverseitig einige Anpassungen vornehmen. Spricht denn etwas gegen die Nutzung einen Memo?

**Comment by M-Plu** [comment]
@ThomasBachran Memos werden in den Reports selten genutzt, eigentlich nur bei mehrzeiligen Inhalten. Sie sind etwas "sperriger" als die normalen Textfelder (DBText), was die Programmierung und Formatierung betrifft. Außerdem wurden sie in der bestehenden Reports selten genutzt, weil die zusätzliche Funktionalität nicht benötigt wird (vieles ist halt einfacher Text in der DB).Daher würde ich eher bei den DBText-Felder bleiben. 

Zudem gibt es bspw. in den drei Tabellen Schueler, SchuelerLernabschnitte, SchuelerLeistungsdaten kein VARCHAR-Feld, dass länger als 255 Zeichen ist. Einige wenige Felder sind als LONGTEXT definiert und nur diese müssten meiner Meinung nach als WIDESTRING in einem MEMO-Feld dargestellt werden.

Wir haben ja auf dem Server, wenn ich das richtig lesen,  schon die folgenden Typen definiert.

```
private void addAttribute(Class<?> clazz) {
        for (Field field : clazz.getFields()) {
            SchildReportingAttributTyp typ = switch(field.getType().getSimpleName()) {
                case "long", "int", "short", "byte", "Long", "Integer", "Short", "Byte" -> SchildReportingAttributTyp.INT;
                case "float", "double", "Float", "Double" -> SchildReportingAttributTyp.NUMBER;
                case "boolean", "Boolean" -> SchildReportingAttributTyp.BOOLEAN;
                default -> {
                	if (field.getAnnotation(SchildReportingDate.class) != null)
                		yield SchildReportingAttributTyp.DATE;
                	if (field.getAnnotation(SchildReportingMemo.class) != null)
                		yield SchildReportingAttributTyp.MEMO;
                	yield SchildReportingAttributTyp.STRING;
                }
            };
            Schema schema = field.getAnnotation(Schema.class);
            if ((schema == null) || (schema.description() == null))
                throw new NullPointerException("Im Core-DTO musse eine Schema-Definition mit einer 'description' vorhanden sein");
            addAttribut(field.getName(), typ, schema.description());
        }
    }
```

D. h. wir können in den Datenquellen direkt die Felder annotieren, die wirklich MEMO sein sollten (das wären die LONGTEXT Felder). Der Rest wird als String interpretiert. 

Wobei mir dabei jetzt auffällt, dass wir statt MEMO vielleicht WIDESTRING nehmen sollten (der Rest sind ja auch Typen und keine Darstellungselemente des Desigerns).

**Comment by M-Plu** [comment]
**@JuergenRichter** : 
Leider kann ich die neue Version von gestern (Freitag) nicht testen, weil Schild 3 beim Starten den Ordner Connections-Files sucht und entsprechende Dateien nicht findet. Hat es da eine Änderung gegeben?

**Comment by JeVaske** [comment]
Ist mir auch passiert. Sie müssen den Ordner SVWS-Arbeitsverzeichnis in Laufwerk c von Hand löschen und dann Schild3 deinstallieren und neu installieren.

**Comment by AnneSchueller** [comment]
@M-Plu:
Hier gab es folgende Änderung:
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/490#issuecomment-1427949491

**Comment by M-Plu** [comment]
OK, danke. Probiere ich später Mal aus.

**Comment by ThomasBachran** [comment]
@JuergenRichter , @M-Plu : Der SVWS-Server unterscheidet im JSON bei der Definition der Datenquellen zwischen langen Texten (SchildReportingAttributTyp.MEMO) und kurzen Texten (SchildReportingAttributTyp.STRING). Mein Vorschlag zur Lösung des Problems wäre, dass wir für den Typ SchildReportingAttributTyp.STRING eine maximale Länge des DB-Type varchar(255) annehmen. Alle String, die länger sind dann bei den Datenquellen des SVWS-Servers als SchildReportingAttributTyp.MEMO zu kennzeichnen. Spricht etwas gegen diese Lösung?

**Comment by M-Plu** [comment]
Das wäre für mich OK (sieht oben). Ich würde nur statt MEMO die Bezeichnung LONGTEXT oder WIDESTRING verwenden, das wäre näher an den Datenbankentypen.

**Comment by ThomasBachran** [comment]
Dann setzen wir meinen Vorschlag, sofern @JuergenRichter einverstanden ist, um. Bei der Bezeichnung würde ich mich aber eher an der Bezeichnung orientieren, die in Schild für den Report-Designer üblich ist, da hier eine Schild-Schnittstelle vorliegt. 

@JuergenRichter: Sind String und Memo dafür die geeigneten Bezeichnungen oder sollten wir die ändern?

**Comment by M-Plu** [comment]
@JuergenRichter Ergänzende Frage: Aktuell gibt es nur den Typ Date. In Schild gibt es aktuell noch DateTime. Wird der Typ auch benötigt?

**Comment by M-Plu** [comment]
@JuergenRichter 
Auch in der neuen Schild-3-Version sind alle Felder unter Infos über Datenquellen als WideString angezeigt. Im Feldassistenten im Designer werden dagegen die richtigen Datentypen angezeigt.

[23-02-19-DynDQ-Leistungsdaten.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10777799/23-02-19-DynDQ-Leistungsdaten.zip)

Der neue Report soll die Schülerleistungsdaten sortiert nach der Fachsortierung Sek-II ausgeben (ACHTUNG: Benötigt eine SVWS-Server-Version mit Datum ab 19.02.2023). Das funktioniert aber leider nicht richtig, weil die Sortierung anscheinend String basiert erfolgt. D. h.  die Sortierung ist bspw. 1.10, 14, 100, 140, 30, 41. Dabei ist das Sortierungsfeld ein Integer.

**Comment by JuergenRichter** [comment]
Derzeit werden die vom SVWS-Server kommenden Feldtypen (übergabe als String) wie folgt in die internen Feldtypen umgewandelt:

function GetFieldType( const ft: string ): TFieldType;
begin
  if ft = 'string' then
    Result := ftWideMemo
  else if ft = 'memo' then
    Result := ftWideMemo
  else if ft = 'integer' then
    Result := ftInteger
  else if ft = 'boolean' then
    Result := ftBoolean
  else if ft = 'date' then
    Result := ftDateTime
  else
    Result := ftWideString;
end;
 
d.h. 'memo' und 'string' werden derzeit gleich behandelt, Wir können das ändern in:

function GetFieldType( const ft: string ): TFieldType;
begin
  if ft = 'string' then
    **Result := ftWideString**
  else if ft = 'memo' then
    Result := ftWideMemo
  else if ft = 'integer' then
    Result := ftInteger
  else if ft = 'boolean' then
    Result := ftBoolean
  else if ft = 'date' then
    Result := ftDateTime
  else
    Result := ftWideString;
end;

Dann müssen intern alle als ftWideString deklarierten Felder eine Länge von 255 bekommen. Ich habe gerade gesehen, dass wir  den Type "float" noch nicht berücksichtigt haben, wird dieser auch als "float" vom SVWS-Server geliefert?

**Comment by JuergenRichter** [comment]
> @JuergenRichter Ergänzende Frage: Aktuell gibt es nur den Typ Date. In Schild gibt es aktuell noch DateTime. Wird der Typ auch benötigt?
Nein, intern wird "date" als ftDateTime behandelt.

**Comment by JuergenRichter** [comment]
> @JuergenRichter Auch in der neuen Schild-3-Version sind alle Felder unter Infos über Datenquellen als WideString angezeigt. Im Feldassistenten im Designer werden dagegen die richtigen Datentypen angezeigt.
> 
> [23-02-19-DynDQ-Leistungsdaten.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10777799/23-02-19-DynDQ-Leistungsdaten.zip)
> 
> Der neue Report soll die Schülerleistungsdaten sortiert nach der Fachsortierung Sek-II ausgeben (ACHTUNG: Benötigt eine SVWS-Server-Version mit Datum ab 19.02.2023). Das funktioniert aber leider nicht richtig, weil die Sortierung anscheinend String basiert erfolgt. D. h. die Sortierung ist bspw. 1.10, 14, 100, 140, 30, 41. Dabei ist das Sortierungsfeld ein Integer.

Kann ich nicht reproduzieren, bei mir funktioniert z.B. einwandfrei
SetzeSortierung( dynSchuelerlernabschnitte, 'schuljahr,abschnitt' );

![image](https://user-images.githubusercontent.com/61280188/220292083-2c301f95-d373-4dd2-a544-93b1a938cb75.png)

**Comment by JuergenRichter** [comment]
"ACHTUNG: Benötigt eine SVWS-Server-Version mit Datum ab 19.02.2023"
Kann ich die Version mal bekommen?

**Comment by M-Plu** [comment]
**Sortierung der Fächer in den Leistungsdaten:**
Bzgl. der Sortierung im aktuellen Report geht es um die SchuelerLeistungsdaten, nicht die Lernabschnitte. Nehmen Sie sich bitte mal eine Testdatenbank mit Leistungsdaten, bei der in der Sek-II Fachsortierungen vorhanden sind mir den obigen Nummern (1, 10, 14, 100, 140, 30, 41). 

Intern müssten Sie mal schauen, ob SetzeSortierung nicht aus den Integer-Werten Strings macht.

Mit aktueller Version meine ich den DEV-Branch, also keine Installer-Version. Verwenden Sie diesen nicht?

**Comment by M-Plu** [comment]
**Zu den Datentypen:**

Diese Typen werden aktuell übermittelt:

```
 /** Boolean */
    BOOLEAN("boolean"),
    /** Ganzzahl */
    INT("integer"),
    /** Zahl, auch Kommazahlen */
    NUMBER("number"),
    /** Zeichenkette */
    STRING("string"),
    /** Mehrzeilige Zeichenkette */
    MEMO("memo"),
    /** Datumsangabe */
    DATE("date");
```

number ist also float und bereits vorhanden. Das fehlt oben in ihrer Liste aktuell noch. 

So wie es @ThomasBachran vorgeschlagen hat, würden wir alle Strings bis 255 Zeichen (gemäß DB) als string übergeben und die anderen (größer 255 Zeichen, bzw. Longtext/Memo) als Memo. Wäre das OK?

**Comment by FPfotenhauer** [comment]
> "ACHTUNG: Benötigt eine SVWS-Server-Version mit Datum ab 19.02.2023"
> Kann ich die Version mal bekommen?

Wie dringend ist es denn?
Ich könnte das heute Nachmittag machen.
Lege den SVWS-Installer dann auf den Server.

**Comment by JuergenRichter** [comment]
Ist nicht so dringend, habe die Ursache für die falsche Sortierung auch so gefunden.

**Comment by JuergenRichter** [comment]
Noch eine Frage: 
In welchem Format werden  "number"-Felder übergeben: Mit Dezimalpunkt oder -komma?

**Comment by JuergenRichter** [comment]
Habe dien Fehler gefunden, der dazu führt, dass die Felder als String deklariert werden (was dann wieder zu den falschen Sortierungen führt)

**Comment by M-Plu** [comment]
Bzgl. des Formats müsste @ThomasBachran eine Information geben.

**Comment by M-Plu** [comment]
Ich habe mit Schild 3.0.58 getestet. Die Filter-Funktion scheint soweit zu funktionieren, die Sortierungsfunktion funktioniert bei mir  nur aus der Vorschau heraus, nicht beim direkten starten des Reports.
[23-03-08-DynDQ-Leistungsdaten.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10943349/23-03-08-DynDQ-Leistungsdaten.zip)

**Comment by M-Plu** [comment]
@JuergenRichter Ich erstelle gerade weiteren Datenquellen für die ehemaligen Reports aus LuPO. Dabei sind mir zwei Dinge aufgefallen:

Zum einen werden im Report keine Kommazahlen ausgegeben. Das JSON des Servers liefert bspw. den Wert 36.25 und das zugehörige Feld im Datenquellendefinition-JSON ist als number definiert, d. h. der Server liefert richtig. In Schild 3.0.58 wird unter "Infos zu Datenquellen" für das Feld float angezeigt, im Feldassistenten innerhalb des Designers ist das Feld vom Typ Double. D. h. grundsätzlich scheint überall anzukommen, dass es sich um eine Kommazahl handelt (wenn auch immer anders beannt). Trotzdem bleibt bei der Anzeige in der Vorschau aber das Feld leer, so als ob keine Daten enthalten sind.

Zum anderen kann ich die Reports mit der neuen Datenquelle mit 3.0.58 nicht für mehrere Schüler drucken. Das löst im Server einen Fehler aus. Ich kann nur einen einzelnen Schüler drucken. Wenn ich aber über die Swagger-UI Daten für mehrere Schüler gleichzeitig abrufe, wird das JSON richtig erzeugt.

**Comment by M-Plu** [comment]
Danke. Gibt es evtl. eine Möglichkeit, wie ich dann immer zeitnah eine neue Version von Schild 3 erhalten kann?

**Comment by JuergenRichter** [comment]
Das Problem "Zum anderen kann ich die Reports mit der neuen Datenquelle mit 3.0.58 nicht für mehrere Schüler drucken" kann ich übrigens bei mir nicht reproduzieren (habe den Report "23-03-08-DynDQ-Leistungsdaten.rtm" verwendet. Habe das mit einer ganzen Jahrgangsstufe ausprobiert.

**Comment by M-Plu** [comment]
Eine Rückmeldung zur mir zur Verfügung stehenden Version 3.0.60. Der Typ number wird jetzt korrekt unterstützt. Und die ersten Datenquellen zur GOST-Laufbahnplanung für den Schüler-Wahlbogen funktionieren soweit (sollten im nächsten SVWS-Server-Update enthalten sein).

Was ich jedoch, wenn auch nicht reproduzierbar, immer wieder feststelle ist, dass der Wechsel aus der Editierung in die Vorschau nicht korrekt funktioniert. Mal wird nur der erste Schüler korrekt angezeigt und beim weiter klicken der nächste nicht mehr gefüllt, mal nicht. Ob das evtl. etwas mit vorherigen Aufrufen des Reports zu tun hat, kann ich nicht genau sagen. Vielleicht könnten Sie da noch mal reinschauen, ob alle Bereiche der Reporting korrekt gefüllt werden.

Zudem wäre es gut, wenn die Schaltflächen im Report-Explorer, die die Daten und Datenquellen neu einliest, auch die dyn. Quellen und ihre Daten neu einlesen würde.

**Comment by M-Plu** [comment]
Hier mal drei Reports, die mind. Schild 3.0.64 zusammen mit einem SVWS-Server ab dem 23.04.2023 benötigen. 

1. Obiger Leistungsdatenreport mit ergänzter Gruppierung
2. Wahlbogen für die Laufbahnwahlen der Schüler (ehemaliger LuPO-Wahlbogen)
3. Gesamtübersicht der Laufbahnprüfungsergebnisse für den Beratungslehrer.

Würde mich freuen, wenn die mal mit verschiedenen Datenquellen getestet werden können.

[23-04-23-DynDQ-Schild-Reports.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11305065/23-04-23-DynDQ-Schild-Reports.zip)

**Comment by FPfotenhauer** [comment]
Der SVWS-Server 0.6.2, der diese Datenquellen unterstützt, steht nun zur Verfügung.

**Comment by M-Plu** [comment]
[23-09-13-DynDQ-Laufbahnplanung-Wahlbogen-Schüler.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12596989/23-09-13-DynDQ-Laufbahnplanung-Wahlbogen-Schuler.zip)

Ein aktualisierter Wahlbogen für SVWS-Server ab Version 0.7.3 (evtl. auch schon 0.7.2)
