### ISSUE TITLE
Fehler mit Datenbankmigration: Katalog Reformpädagogik fehle

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#438]
Installation von SVWS-Server und Schild3 laufen durch.
Migration von Datenbank (Standard GY_2022_23b) wurde bei der Installation des Servers durchgeführt.
Schild3-Installation wurde mit Migration gestartet -> Lokaler Server und lokale DB gewählt.
Das Migrationstool gibt an, die Verbindungen zur DB und zum Server bestünden.

Es kommt zu folgendem Fehler:

![FehlerDBS3Reformp](https://user-images.githubusercontent.com/116796098/202843361-4f18e8b7-3d88-4b81-9709-a6b0c45035a9.png)

Schild 2 startet problemfrei mit der DB, Schild 3 startet nicht.

**Comment by FrodBRA** [comment]
Klicke ich auf Abbrechen, startet Schild weiter, jedoch ist keine Schule angelegt. Die Datenbankmigration scheint vollkommen schiefgelaufen zu sein?

**Comment by FrodBRA** [comment]
Testweise SVWS-Server neu installiert, GE_2022_23b neu migriert. Gleicher Fehler:
Reformpädagigk fehle, "ignorieren" und dann stellt das Programm fest, es sei keine Schule vorhanden.

**Comment by FPfotenhauer** [comment]
Mit der SVWS-Server 0.3.1 sollte das eigentlich klappen.
Der Katalog Reformpädagogik wurde vor kurzem auf API umgestellt.

**Comment by FrodBRA** [comment]
Ich installiere mit 0.3.1, gerade heute runtergeladen. Ich hatte aber auch nur über die vorhandene Installation drüber installiert.

Jetzt habe ich noch einmal den alten Server und Schild3 komplett entfernt, inklusive Ausführung der .bat, und mit einer frischen Installation läuft nun alles.

**Comment by FPfotenhauer** [comment]
"Schild 2 startet problemfrei mit der DB, Schild 3 startet nicht."
Diese Aussage versteh ich nicht die DBs haben gar nichts mehr miteinander zu tun.

Außerdem wiederhole ich mich gerne:
Versionsnummern (SVWS-Server) und Logs würden helfen.

**Comment by FrodBRA** [comment]
> "Schild 2 startet problemfrei mit der DB, Schild 3 startet nicht."
Was ich sagen wollte: Die Datenbank ist vor der Migration definitiv in Ordnung, nach der Migration gab es einen Fehler.

Die SVWS-Version war 0.2.18, über diese hatte ich 0.3.1 drüber installiert. Dann kam es zum Fehler (SchiILD 3.0.48.8)

Nachdem ich die alte SVWS-Installation und SchILD3 deinstalliert hatte und 0.3.1 und Schild neu aufgespielt habe, ist der Fehler weg und die Datenbank funktioniert.

Die Logs habe ich mit gelöscht.

**Comment by FPfotenhauer** [comment]
Bei der 0.3.1 musste neu migriert werden. Damit de CoreTypes für die Kataloge angelegt werden.
