### ISSUE TITLE
Uneindeutige Benennung der Funktionen: SVWS-Server, SchILD3-Installation, MigrateDB.exe

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#439]
* Der SWVW-Installer bietet eine Option, die "migrieren" heißt und hier kann eine eine Datenbank migriert werden. 

* Während der SchILD-3-Installation gibt es eine Option, die "migrieren" heißt, diese startet aber lediglich die "MigrateDB.exe", ohne dass eine Option zum migrieren einer DB besteht.

* Die MigrateDB.exe ist ein Konfigurationstool für den Zugriff auf eine bereits migrierte DB, das keine offensichtliche Option zur Datenbankmigration anbietet. 
Für die lokale Installation wird explizit eine migrierte DB vorausgesetzt, auch der freie Expertenmodus lässt lediglich eine Konfiguration einstellen.

Hier könnten wir noch mal über eine klare Benennung der Optionen nachdenken und die MigrateDB.exe sollte eine Option bereitstellen, eine reine Migration vorzunehmen.

Die Option in der Server-Installation sollte weiterhin "Datenbankschema migrieren" heißen, da die Option genau dies tut. Die Option in der Schild-Installation sollte in "DB-Konfigurationstool starten" umbenannt werden. Und die MigrateDB.exe sollte die Option zur Migration in einen existieren DB-Server anbieten (oder deutlicher kenntlich machen, wo dies wie anzustoßen ist).

**Comment by AnneSchueller** [comment]
Wenn ich das jetzt nochmal so durchlese ist das auch irreführend mit Punkt 3...

**Comment by Raffenberg** [comment]
Ich finde, dass hier zwei Dinge nicht berücksichtigt werden:
1. wird die Standardinstallation eine Serverinstallation mit Notwendigkeit einer Migration sein.
2. muss die nicht Informatik-Studierte Person verstehen, was gemacht wird

Wenn ich einen Toaster kaufe, steht in der Beschreibung auch nicht, dass "der Stromfluss die keramikummantelten Glühwendel aufheizt um den Luftspalt auf Temperatur zu bringen". Dort steht, dass ich "den Toaster einschalten muss um das Toast zu rösten". Sicherlich ist die erste Sprechweise präziser, aber für den Endanwender nicht Umgangssprachlich.

Insofern würde ich hier vielmehr Endanwendersprache benutzen. Der Endanwender muss über bestimmte Prozesse nicht informiert werden. Dass z.B. ein Datenbank-Schema migriert wird ist meiner Meinung nach fürchterlich ausgedrückt.

Ich schlage deshalb folgendes vor:
1. Nur der SVWS-Server sollte sich darum kümmern, Datenbanken mit Schema anzulegen und alte Datenbanken zu migrieren.
2. SchILD-NRW 3 sollte nur eine Installation auf einem beliebigen Laufwerk anbieten und nach der Installation fragen, wo sich die Datenbank befindet.
3. Die Sprechweise sollte meiner Meinung nach in der Form erfolgen, dass eine SchILD-NRW 2 - Datenbank "importiert" wird. Das hierzu ein Schema angelegt wird etc. sind unausgesprochene Prozesse, die nur im Hintergrund geschehen sollten.

**Comment by JuergenRichter** [comment]
> 1. Nur der SVWS-Server sollte sich darum kümmern, Datenbanken mit Schema anzulegen und alte Datenbanken zu migrieren.

Das ist ja auch in MigrateDB.exe der Fall, es wird ja nur eine API-Funktion des SVWS-Servers aufgerufen.

**Comment by kroerig** [comment]
Ich kann mich hier nur anschließen. Insb. wenn man die Installation nicht mit dem Assistenen unter Windows macht, sondern die Komponenten aufteilt.
