### ISSUE TITLE
Hintergrundfarbe bei Luna-Thema

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#440]
Ich stelle mal die Hintergrundfarb bei den "GroupBoxen" zur Diskussion. Bisher war das auf "clBtnFace" gstellt, was sich aber mit dem Hintergrund bei den Tabellen "beißt".
Farbe = clBtnFace
![image](https://user-images.githubusercontent.com/61280188/203362932-d3d68f10-1907-428f-82df-ae7c3a1590ea.png)

Man könnte es auch auf "weiß" stellen
Farbe= clWhite
![image](https://user-images.githubusercontent.com/61280188/203363055-45a7c13f-c256-47d2-bb2d-47ee34054794.png)

**Comment by AnneSchueller** [comment]
Das weiß finde ich tatsächlich schöner.
Das wäre dann relevant für Schüler und Lehrkräfte?
Bei Gruppenprozesse ist die Hintergrundfarbe der Tabellen analog zu den GroupBoxen. Bei der Auswahl ist es mal so mal so. Je nachdem auf welchem Unterreiter man sich befindet. 
Das sollte evtl auch vereinheitlicht werden?

**Comment by JuergenRichter** [comment]
Das wird dann alle Stellen betreffen, wo "Boxen" der folgenden Art angezeigt werden:
![image](https://user-images.githubusercontent.com/61280188/203501988-036555f6-d51c-4719-ba60-9255c340ffac.png)

Es mag noch Stellen im Programm geben, wo noch andere GroupBoxen verwendet werden, das wird aber noch angepasst, bei den Gruppenprozessen ist das schon erfolgt:
![image](https://user-images.githubusercontent.com/61280188/203504266-fc2a5093-fcce-4d49-a8cc-9ae5a6742119.png)

**Comment by Raffenberg** [comment]
Weiß finde ich auch schicker. Im Screenshot zu allgemeine Angaben sieht man, dass die Rahmen um die Datenfelder unterschiedlich dick sind. Hier würde ich die ganz dünne Variante bevorzugen, so wie es im Schülerkontainer auch zu sehen ist.

**Comment by AnneSchueller** [comment]
Das sehe ich genauso.... die dünneren Umrandungen
