### ISSUE TITLE
Layout der neuen Themes

### ISSUE THREAD

**Issue by jwae** [SVWS-NRW/Schild3-BetaTest#441]
Ich finde die Layout nicht gut lesbar, weil:
- Die Feldbeschreibungen dominieren das Layout und überlagern optisch die Informationen, die in den Datenfeldern (Name, Gebdatum, ...) stehen. Sie sind fett und schwarz. Die Informationen dagegen sind heller und leichter.
- Die Umrandungen um die Felder erzeugen viele weiße Kästchen, in denen in dünner Schrift eine Information steht. 
- Die Informationen sind vor lauter (fetter) Feldbeschribungen schlecht wahrnembar.
- Ich würde die Informationen stärker hervorheben und die Feldbeschreibung etwas neutraler gestalten.
- Die Umrandungen um die Felder könnten entweder ganz wegfallen (siehe Beispiel) oder nur 1 Pixel breit sein.
- Und warum nicht eine Punktgröße mehr? Die vielen User werden es euch danken.

Mein Vorschlag:
![Layout](https://user-images.githubusercontent.com/16616572/203433829-d4445540-e52f-4c08-9a55-edc075624062.jpg)

MfG
J. Waedt

**Comment by AnneSchueller** [comment]
Lieber Jürgen,
vielen Dank für die detaillierte Rückmeldung. Ich selbst habe mich sehr an das aktuelle Schriftbild gewöhnt.
Ich nehme deinen Vergleich heute mit in die Fortbildung und lasse mir diesbezüglich eine Rückmeldung geben.
Ich werde berichten....

**Comment by Raffenberg** [comment]
Das Issue doppelt sich ein wenig mit Issue #440

**Comment by AnneSchueller** [comment]
Die Meinungen waren sehr unterschiedlich. Weitere Vorschläge waren die Variation von Schriftgröße (Eintragungen größer als die Überschrift) und beide Textfelder in normaler Schrift (also nicht fett)
Ich bin unschlüssig.

**Comment by jwae** [comment]
Die Eintragungen bzw. die Feldinhalte sind doch für den täglichen User wichtig und sollten schnell zu erfassen sein. Die Feldbezeichnungen und die Rahmen müssten deshalb eher im Hintergrund (sichtbar) bleiben und nicht noch das suchende Auge ablenken. Immer an den Benutzer denken ... :-)

**Comment by FrodBRA** [comment]
Ich möchte mich hier beteiligen. Im Grundsatz sieht das neue SchILD voll ok aus, einige Felder sind aber noch unbedingt zu überarbeiten, hier ein Beispiel, das besonders "beta" ist: 

Die Schrift links in der Übersicht ist viel zu groß und passt nicht zum Rest von SchILD.

Die Überschiften der Spalten viel dann noch einmal viel größer und mit den Abkürzungen gar nicht schön. Hier muss die Schrift kleiner werden und es sollten Zeilenbrüche eingebracht werden.

![SchILD_Kataloge_Kurse_1](https://user-images.githubusercontent.com/116796098/206757507-5c4ae2b6-f48c-438e-b779-2472ce0bd6e6.png)
