### ISSUE TITLE
Kataloge / Kurse

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#442]
Wenn ich unter Kataloge / Kurse in der Spalte Zeugnisbezeichnung einen Eintrag mache, kommt die Fehlermeldung. Meiner Meinung nach ist die komplette Spalte überflüssig, weil die Daten ja eigentlich aus der Tabelle "Unterrichtsfächer" kommen. Vielleicht kann man Schild hier noch vereinfachen.
![schild_100a](https://user-images.githubusercontent.com/78501680/204156784-490979a2-197c-4f8c-8583-952e534de057.jpg)

**Comment by AnneSchueller** [comment]
Danke für das Testen und für die Rückmeldung!
Den Fehler kann ich reproduzieren.
Die Spalte würde ich allerdings lassen. Viele Schulen tragen insbesondere bei AGGT und ZUV-Kursen hier eine andere Zeugnisbezeichnung ein als im zugehörigen Unterrichtsfach.

**Comment by JuergenRichter** [comment]
Prüfe ich, die Spalte "Zeugnisbezeichnung" ist ja optional, wenn da nichts sthet, wird bei der Zeugnisausgabe die Fachbezeichnung genommen.

**Comment by JuergenRichter** [comment]
Behoben
