### ISSUE TITLE
Kurse / Weitere Lehrkraft

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#443]
Wenn ich im Katalog Kurse mit der rechten Maustaste eine weitere Lehrkraft zuweisen will, bekomme ich eine Fehlermeldung.
![Zwischenablage111a](https://user-images.githubusercontent.com/78501680/204157434-b4597e3e-a458-4585-970b-6a6a7df561bd.jpg)

**Comment by JuergenRichter** [comment]
Behoben
