### ISSUE TITLE
Lupo Import/Export

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#444]
Bitte die Export "abklemmen", da dies ja nun alles vom SVWS-Server gemacht wird.
Wenn jemand den Webclient zum Blocken nimmt, ist dort alles vorhanden.

**Comment by JuergenRichter** [comment]
Sollte eigentlich schon lange abgeklemmt sein.

**Comment by FPfotenhauer** [comment]
Super!
