### ISSUE TITLE
Pflichtstunden bei Lehrkraft eintragen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#445]
Wenn ich das pflichtstundensoll bei einer Lehrkraft eintrage kommt:
"Error. Found 0 records."

![SNAG_2022_12_04_15 28 34](https://user-images.githubusercontent.com/34127980/205496510-0b9aa86f-327b-4a4b-89c3-b66238e9ff2b.png)

**Comment by FPfotenhauer** [comment]
Nachtrag:

Bei den anderen Eintragungsmöglichkeiten auch....

**Comment by JuergenRichter** [comment]
ich kann das bei mir nur zum Teil reproduzieren, bei manchen datensätzen funktioniert es einwandfrei, bei anderen bekomme ich die gleiche Fehlermeldung. Ich werde da sprüfen.

**Comment by JuergenRichter** [comment]
Habe die Ursache gefunden und behoben
