### ISSUE TITLE
Theme Klassengruppen/Abteilungen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#446]
Der Menüpunkt reagiert nicht auf die Theme-Einstellung:

![SNAG_2022_12_04_16 36 41](https://user-images.githubusercontent.com/34127980/205499948-c297a1b0-2659-4c0d-9d04-da0476cab8d1.png)

**Comment by JuergenRichter** [comment]
Behoben
