### ISSUE TITLE
Gruppenprozess Klassenunterrichte bearbeiten

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#448]
Wenn ich im Gruppenprozess "Klassenunterrichte bearbeiten" eine Änderung vornehme und diese mit Ja bestätige, kommt die Fehlermeldung:
![Schildfehler100](https://user-images.githubusercontent.com/78501680/206840116-c8919988-4e7f-4e8c-a2bf-060d28bda2b0.gif)

**Comment by JuergenRichter** [comment]
Behoben
