### ISSUE TITLE
Schriftgrößen zu groß (Kataloge; besonders Kopfzeile Kurse); teils auch unpassende Einstellungen zu Spaltenbreiten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#449]
Die Schriftgröße wirkt an vielen Stellen zu groß, besonders deutlich wird dies in den "Katalogen". Die Schrift der angebotenen Kataloge in der Auswahlliste links wirkt nicht passend.

Besonders in de Katalog "Kurse" ist die Schrift in der Kopfzeile viel zu groß. Ebenso sind die "Statistik-Jahrgänge", der linke Container bei "Klassen/Versetzungstabelle", "Unterrichtsfächer", "Stundentafeln" und "Schülergruppe bearbeiten" betroffen.

Teils passen die Spaltenbreiten auch nicht, sie sind etwa unnötig breit oder zu schmal für die große Schrift darin.

Schlussendlich: quer durch die Kataloge fallen uneinheitliche Beschriftungen der Spaltenköpfe auf bzw. diverse Rechtschreib- und Tippfehler. Besonders manche Verwendung von Bindestrichen wäre teils noch einmal zu überdenken. Auch einige der Abkürzungen sollten so nicht stehenbleiben.

Ist zum derzeitigen Zeitpunkt eine Meldung von solcherlei Details schon gewünscht? 

![SchILD_Kataloge_Kurse_GIT](https://user-images.githubusercontent.com/116796098/206849026-0fdcd646-8ae9-49ae-abfe-79d599165f33.png)

Die Schriften im Punkt "Verwaltung" sind ebenso betroffen.

Eventuell sind manche Formatprobleme auch auf eine höhere Auflösung zurückzuführen (3840 * 2160; aber auch auf dem FullHD-Monitor fällt noch einiges als unpassend auf).

**Comment by FrodBRA** [comment]
Jetzt ist in der Tat etwas seltsames passiert: Ohne dass ich etwas verändert hatte, sieht SchILD nun beim Start so aus wie noch nie: Die Schriftgrößen in der Übersicht sind kleiner, dafür passen die Zeilen nicht mehr und schneiden die Buchstaben unten ab:

![SchILD_Kataloge_Kurse_GIT2](https://user-images.githubusercontent.com/116796098/206850631-88fe35ba-e811-48fb-a710-fd458e6d8d3c.png)

Die Kopfzeilen in "Kurse" sind nach wie vor so riesig wie im ersten Screenshot.

Die Schrift des linken Containers in "Verwaltung" ist nach wie vor so, wie sie war.

Nachdem ich das Programm von 4k-Monitor auf den FullHD-Monitor und wieder zurück verschoben habe, waren die Schriftarten in der Katalogübersicht auch wieder so groß wie im ersten Screenshot. Während das Fenster auf dem FullHD-Monitor war, waren die Schriftarten alle übergroß, so dass sie teilweise nicht mehr in die Fenster passten (im Standardfenster, wenn man "Verwaltung" angeklickt hat).

SchILD startet bei mir auch auf dem 4k-Monitor mit einem viel zu großen Fenster (breiter als die 3840 Pixel), definitiv nicht die Größe, mit der ich beendet habe.

Zum Setup: Ich habe einen 4K-Monitor und einen FullHD-Monitor nebeneinander. 

Letzte Anmerkung zu Multimonitor-Setups: Wenn man SchILD auf dem zweiten Desktop startet, gehen die ersten Fenster auch dort auf - bis zur Passworteingabe und Prüfung der abgelaufenen Löschfristen. Wird dann weitergeklickt, öffnet sich das eigene Programm auf dem anderen, wohl primären, Monitor. Das ist soweit kein Problem, aber vielleicht ein Hinweis darauf, dass bei mehreren Monitoren das gewünschte Verhalten noch nicht alles klar definiert ist.

(Machst du kein Wochenende, Frank? ;))

**Comment by FrodBRA** [comment]
Was das "zu breite Fenster" angeht: es scheint gerade so, als würde sich SchILD mit der **Gesamtbreite** des Setups auf dem rechten Monitor öffnen, so dass sich ein Fenster mit 3840 + 1980 Pixeln öffnet. Es startet auf dem rechten Monitor, so dass eben auf der rechten Seite das SchILD-Fenster noch über den Desktop hinaus ragt.

**Comment by JuergenRichter** [comment]
Sollte jetzt behoben sein. Das Speichern der Spaltenbreiten wurde auch nochmal überarbeitet
