### ISSUE TITLE
Noteneingaben von Teilleistungen werden immer mit "+" versehen

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#45]
Beim Eingeben von Noten in den Teilleistungen wird aus einer 4 immer eine 4+ u.s.w.

**Comment by FPfotenhauer** [comment]
Das Programm springt zunächst imme rauf die Note mit dem Plus. Man kann das Plus aber weglöschen, dann wird die Note auch ohne gespeichert.

**Comment by FPfotenhauer** [comment]
Insgesamt stimmt die Darstellung des Grids mit den Teilleistungen auch nicht so ganz.

![SNAG_2020_12_09_13 43 16](https://user-images.githubusercontent.com/34127980/101631417-95b78c80-3a24-11eb-8277-2fc7618f1603.png)

**Comment by JuergenRichter** [comment]
Bei mir sieht die Ansicht korrekt aus. Bitte mal folgendes probieren:
"Verwaltung>>Einstellungen>>Individuelle Einstellungen" aufrufen, dort den Schalter "Individuelle Einstellungen...zurücksetzen" aktivieren, dann neu starten. Dabei werden u.a. die Breiten der Tabellenspalten auf Default-Werte zurückgesetzt.

**Comment by JuergenRichter** [comment]
Wir können die Sortierung auch anders mache, so dass zuerst z.B. die "4" genommen wird

**Comment by Kluesenerm** [comment]
Ich würde es auf jeden Fall dringend empfehlen. Bei den Zeugnisnoten ist es auch so, dass zuerst die volle Note (4 ohne +) erscheint.

**Comment by JuergenRichter** [comment]
Wird in der nächtsten Version umgesetzt

**Comment by JuergenRichter** [comment]
Ist in 3.0.8 umgesetzt
