### ISSUE TITLE
Korrekturlesen (etc.): Verwaltung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#450]
Oben links
- Online-Documentation -> Online-Dokumentation

Export -> Als Excel-/Ttect-Dateien unter Export-Optionen:
- das "für" sollte ausgeschrieben werden

Für Logineo -> Optionen
- "Ausgabe-Verzeichnis" -> "Ausgabeverzeichnis"

Falls "Ausgabewert für logisches "Ja"" nicht passt, schlage ich vor "Ausgabewert für logisch "Ja"".

Einstellungen -> Fächer, Noten
"Beim Holen Abgeschlossener Fächer" -> "beim "Holen abgeschlossener Fächer"  (eventuell sollte der Gruppenprozess auch in "Holen abgeschlossener Fächer" umbenannt werden). 

Werkzeuge -> Fotos neu skalieren:
- Es werden alle Fotos, deren Höhe [...] als 160 Pixel, neu skaliert. .-> "Es werden alle Fotos neu skaliert, deren Höhe und Breite [....].

**Comment by FrodBRA** [comment]
Ein Verwaltung -> Einstellungen -> Globale Einstellungen -> Sonstiges

"Beginn Nummernbereich" wirkt unvollständig, so dass die Bedeutung des Feldes unklar ist.

Unter Kennwortregeln 
"Komplexität (Anzahl" wirkt unvollständig. Was bedeutet das Feld?

Weiterhin: Mir ist nicht klar, ob "Minimale Länge" korrekt funktioniert. Es steht dort als String "8 Zeichen". Müsste dort nicht nur eine Int stehen? Ändere ich den Wert, springt der Eintrag wieder auf das Default von "8 Zeichen" als Text. Bei Bedarf öffne ich ein eigenes Issue.

**Comment by AnneSchueller** [comment]
Wenn ich das richtig getestet habe, gibt es als Zeichenart Großbuchstaben, Kleinbuchstaben Zeichen und Ziffern. Bei Komplexität von 3 muss man 3 verschiedene Zeichenarten nutzen (das klappt auch soweit bei meinen Tests). 

Die Änderung der minimale Länge wird bei mir zwar gespeichert (bei Eingabe von "9 **Zeichen"**, allerdings bei der Vergabe des Passwortes nicht berücksichtigt.
Hier fände ich es auch passender, wenn nur die Zahl eingetragen werden kann. Das Wort "Zeichen" kann man ja trotzdem als Label stehen lassen.

**Comment by FPfotenhauer** [comment]
Wenn man es in 60s nicht klar erklären kann, dann ist es ....

**Comment by FrodBRA** [comment]
Das Feld, mit dem sich die Pixelgröße ändern lässt, funktioniert analog - dort aber auch  korrekt.

D.h. wenn ich das komplette Feld lösche und ein Int (z.B. 180 Pixel) eintrage, wird "180 Pixel" in das Feld geschrieben und auch übernommen.

Bei dem Passwort wird auf den Default "8", ausgegeben als "8 Zeichen" resettet. 

Der Eingabewert sollte rein auf die Zahl reduziert werden; das Feld mit der Passwortlänge scheint nicht korrekt zu speichern.

Die "Komplexität" ist technisch ok, für den Endnutzer aber nicht geeignet, hier müssten verständliche Fehlermeldungen bei der Passwortvergabe her und hier im Feld wäre ein Dropdown-Menü mit einer sprechenden Bezeichnung der Auswahloptionen sinnvoll. Im Wiki steht die Funktionalität nun jedenfalls erklärt.
