### ISSUE TITLE
Korrekturlesen (etc.): Schüler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#451]
"aktueller Schüler" -> "Aktueller Schüler"

Reiter "Erz.-Berechtigte/Telefonnummern" -> "Erziehungsberechtigte"

Individualdaten I -> Zusatzdaten
"schulische Email [...]" -> "Schulische"

Individualdaten II 
- "aktuelle Förderung (nur Ansicht)" -> "Aktuelle Förderung (nur Ansicht)"

Erz.-Berechtigte
- "erhält Anschreiben" -> "Erhält Anschreiben" (evtl. den Kopf zweizeilig ausführen)
- auch unter "Adresse" "erhält Anschreiben" -> "Erhält Anschreiben"

Schulbesuch: 
- "Vor der Aufnahme besuchte Schule /Einrichtung /Sonstige" -> "Vor der Aufnahme besuchte Schule/Einrichtung/Sonstige"
Der Eintrag passt auch nicht in das Feld, eventuell zweizeilig ausführen

Alle bisher besuchten Schulen
-> "Schulform" und mehr passen nicht in die Standardbreite der Kopfzeile.

Akt. Halbjahr -> Leistungsdaten
- "info" -> "Info"

Kopfzeile "Auf Zeugnis", "Kursart", "Lehrkraft", "WZE*", "Epochenunterricht" und "Unterricht in ext.. Schule*" passen nicht in die eingestellte Breite (zumindest bei mir). 

Ebenso auch bei "Fehlzeiten": Kopfzeilentitel passen nicht in die Breite der Spalten. 

Laufbahninfo
"Angelegt von" und "Geändert von": Spalten zu schmal

Sprachenfolge
- Diverse Spalten zu schmal für die Kopfzeileninhalte. 

Sprachprüfungen
- Diverse Spalten zu schmal für Kopfzeileninhalte

Ebenso für "Jahrgang" in "Erreichte Abschlüsse und Berechtigungen"

Ebenso in "Fördermaßnahmen" für "Überprüfung bis" und "Abgeschlossen"

Reiter "Einwilligung" -> "Einwilligungen"
-> hier auch bei beiden Infotexten "Hier können [...]. Die Bearbeitung erfolgt über den Menüpunkt" -> Welcher Menüpunkt?

"Abgefragt" und "Nutzung" passen nicht in die Kopfzeile.

**Comment by AnneSchueller** [comment]
Erstmal herzlichen Dank für das genaue und umfangreiche Korrekturlesen und produktive Testen hier und auch in den anderen Issues! 

Die Anmerkungen zur Schreibweise (Groß/Kleinschreibweise/ Einwilligung -> Einwilligungen) würde ich so übernehmen.

@JuergenRichter : Wäre es möglich die Default-Spaltenbreite anzupassen? Ich weiß, dass man sie nur anfangs einmal verstellen muss und die Breite dann so bleibt. Dennoch wirkt das anfängliche Erscheinungsbild an einigen Stellen erstmal seltsam. 
Zum Beispiel hier:
![2022-12-12_095145](https://user-images.githubusercontent.com/79116896/207002170-26005824-8f71-4b71-b9c4-5ace2b52e034.png)

@FrodBRA Noch eine Nachfrage zu den Einwilligungstexten: 
"hier auch bei beiden Infotexten "Hier können [...]. Die Bearbeitung erfolgt über den Menüpunkt" -> Welcher Menüpunkt?"
In meiner Version ist das genau angegeben wie auch in Schild2:
![2022-12-12_095529](https://user-images.githubusercontent.com/79116896/207002877-ebe71878-0427-4aa4-b411-325acb395bc5.png)
Oder einst du etwas anderes?

**Comment by JuergenRichter** [comment]
Weitgehend umgesetzt. Was die Spaltbreiten betrifft: Wenn die ziemlich "krude" aussehen, bitte mal bei den individuellen Einstellungen den folgenden Schalter betätige,
![image](https://user-images.githubusercontent.com/61280188/223978705-c8c28ce6-c543-4603-a9f3-dca581210bc7.png)
