### ISSUE TITLE
Ansicht Schüler/Individualdaten verschwunden

### ISSUE THREAD

**Issue by jwae** [SVWS-NRW/Schild3-BetaTest#453]
Wenn ich in der Standard-Ansicht (Menü "Schüler", die  Reiter Individualdaten I, ..., sind sichtbar) in der Symbolleiste auf "Reports" klicke, dann wird mir die Reportverwaltung angezeigt.  

Danach komme ich aber nicht mehr zurück auf die Schülerseite. Das Menü Schüler ist ja noch aktiviert. Wenn ich darauf klicke tut sich nichts. 

Tipp: 
1. Noch einmal auf das Symbol Reports klicken -> dann erscheinen wieder die Reiter Individualdaten I, etc.)   - finde ich unlogisch
2. "Doppelklick" auf das Menü Schüler  -> dann erscheinen wieder die Reiter Individualdaten I, etc.)    - Ein Menü sollte nicht doppelt geklickt werden müssen

**Comment by AnneSchueller** [comment]
Ergänzung: Beim Doppelklick auf Schüler wechselt Schild3 in den Reiter Verwaltung aber mit einem Mix aus Schüleransicht und Verwaltungsansicht:
![2022-12-11_211445](https://user-images.githubusercontent.com/79116896/206926586-0ce1ceab-d303-4598-9157-2e59540f2cd2.png)

**Comment by JuergenRichter** [comment]
behoben
