### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jwae** [SVWS-NRW/Schild3-BetaTest#454]
Ich habe Schild 3.0.50.8 installiert.
Wenn ich die neueste Version 3.0.53 installieren möchte, läuft diese relativ zügig durch. Mein Schild hat nach der Installation aber immer noch die Version 3.0.50.8

Muss ich die alte Version vorher deinstallieren?

**Comment by FrodBRA** [comment]
Das ist mir auch passiert - ich habe kürzlich 3.0.53 drüber installiert, es lief alles durch. Mein SchILD steht aber laut Version noch auf 3.0.50.8.

**Comment by FPfotenhauer** [comment]
Ich würde mal deinstallieren oder vorher mal in der Registry schauen, was da für ein Pfad hinterlegt ist.
Der Installer schaut dort nach und instelliert einfach.
Beim vielen Testen kann da schon mal was schief laufen.

**Comment by FPfotenhauer** [comment]
Oh, ok ich verstehe jetzt.

Die Versionsnummern vom Installer und von der Programmversion sind nicht gleichzusetzen.
Ich baue die Installer und versioniere die. Herr Richter macht die Programmversionen.
