### ISSUE TITLE
Korrekturlesen (etc.): Kataloge (Allgemein)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#456]
Ich schlage vor, bei den Einträgen links wegen besserer Lesbarkeit so viele Bindestriche wie möglich zu entfernen.
-> Erzieherarten
-> Fahrschülerarten
-> Entlassungsbemerkungen
-> Adressarten
-> Statistikjahrgänge
-> Teilleistungsarten
-> Vermerkarten

Fehler:
- "Klassen/Versetzungstabelle" -> "Klassen-/Versetzungstabelle" 

In diversen Katalogen passen Titel in Kopfzeilen nicht in die per Standard gesetzte Spaltenbreite. 

Besonders trifft dies "Sichtbar" und "Sortierung".
- Erzieher-Art
- In Konfessionen sind die Spalten per Standard viel zu breit, besonders, aber nicht nur, trifft dies auf "Sichtbar" und "Sortierung" zu.

Förderschwerpunkte
- "interne Bezeichnung" -> "Interne Bezeichnung" 

Allgemeine Adressen
- Titel in der Kopfteile im Hauptcontainer hat eine zu kleine Schriftart

Allgemeine Adressen -> Aktuelle Adresse
- "Belehrung nach [...] das "nach" kann ausgeschrieben werden

Schulen in NRW
- "offizielle Bezeichnung" -> "Offizielle Bezeichnung"
- Spalte "Schulform" zu schmal

Wie oben auch in "Andere Schulen  und Schulnummern"

**Comment by JuergenRichter** [comment]
Weitgehend umgesetzt
