### ISSUE TITLE
Korrekturlesen (etc.): Kataloge (schulbezogene Kataloge)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#457]
Statistik Jahrgänge

- Die Spalten sind oft zu breit für den Inhalt und passen nicht auf einen Bildschirm.
- Bindestriche können entfernt werden: "Statistikkürzel", "Statistikbezeichnung"
- "Kurzbez." -> "Kurzbezeichnung"
- "Chronolog." -> "Chronologie"
- "Sort." ist im Gegensatz zur üblichen Verwendung  "Abgekürzt". 

Klassen/Versetzungstabelle 
Unter "Sortierung": "interne Bezeichnung" -> "Interne Bezeichnung"

Aktuell ausgewählte Klasse
- "Schul-interne Bez." -> "Schulinterne Bez." 
- "Statistikbezeichnung" kann ausgeschrieben werden.
- "Vorgängerklasse" ohne Bindestrich
- "Folgeklasse" ohne Bindestrich

Unterrichtsfächer
- "interne Kurzform" -> "Interne Kurzform"

in Details: 
- bilinguale Sachfachssprache -> "Bilinguale [...]" 

in Sonstige Einstellungen
- "Schriftliches Fach für ZK" kann ausgeschrieben werden 

Fächer der Oberstufe
- "Fachkürzel" ohne Bindestrich
- "1. Leitfach für Projektkurs/Vertiefungsfach" sollte gleich geschrieben sein wie in "2. Leitfach [...]", in "2. Leitfach steht "ProjektKurs" -> "Projektkurs". 

Stundentafeln
- "Sichtb." und "Sort." sind abgekürzt, was sonst nicht so ist.
- Die Spaltenbreiten sind sehr breit... 

Kurse
- "Filter auf Schuljahr und Absc" passt nichts in Feld. 
- "mehrere Jahrgänge" -> "Mehrere Jahrgänge"
- "Kurs-Bezeichnung" kann zweizeilig passen
- Spalte zu schmal für "ZE/Woche insges."
- Spalte zu schmal für "ZE/Woche Kursleiter"
- Spalte zu schmal für "Anz. zus. Lehrkäfte" -> Umbenennen zu "Zusätzliche Lehrkräfte" und zweizelig?
- Spalte zu schmal für "Sortierung"?

**Comment by AnneSchueller** [comment]
Ggf. könnte man statt Abkürzungen auch 2 Zeilen verwenden. Beispielsweise ist die Kopfzeile bei den Statistik-Jahrgängen bereits jetzt schon 2-zeilig. Dann kann man problemlos auch andere Überschriften ausschreiben und dafür 2 Zeilen verwenden (falls notwendig)

**Comment by JuergenRichter** [comment]
Weitgehend umgesetzt. Ausnahme:
Die Spaltenbreiten können ja vom Anwender eingstellt werde, das "merkt" sich das Programm auch.
