### ISSUE TITLE
Vorschlag: Verwendung eines Icons für Spaltenkopfeinträge "Sichtbar" und "Sortierung"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#458]
"Sichtbar" und "Sortierung" passen als Titelüberschriften oft nicht in das Feld der Kopfspalte und der Eintrag ist ohnehin nur eine Checkbox.

Mein Vorschlag wäre, statt der geschrieben Worte ein Icon zu nutzen und beim Mouseover über das Icon wird "Sichtbar" bzw. "Sortierung" eingeblendet.

**Comment by FrodBRA** [comment]
Das Problem hier ist: "Sortierung" und "Sichtbar" sind viel breiter als ☑ und erzeugt oft komisches Format, egal wie man die Spalten verzieht.

Man könnte auch ein Auge nehmen, das ist in Unicode enthalten: 👁 oder 👁️‍🗨️oder 👀. Das Mausover würde "Sichtbar?" sagen, das wäre verständlich?

Für Hochrunter-Pfeile gibt es sowas: ⇅ oder ⬍ oder ⇳. Beim Mouseover würde "Sortierung" erscheinen.

**Comment by AnneSchueller** [comment]
Jens, Frank und ich haben heute nochmal über die Icons diskutiert: Die Idee mit dem Mouseover finde ich tatsächlich sehr charmant. Allerdings haben wir uns aus folgenden Gründen gegen die Icons entschieden: Das Auge kennen die meisten, um beispielsweise ein Passwort sichtbar zu machen. Hier hat das Icon dann eine andere Funktion: Klickt man drauf wird das Passwort entweder sichtbar oder nicht. In einer Spaltenüberschrift würde die Bedeutung von der gewohnten Handhabung abweichen.
Zudem fanden wir die Spaltenüberschriften durch das Ausschreiben von "Sichtbar" und "Sortierung" eindeutiger und von der Breite her angemessen.
