### ISSUE TITLE
Kurse -> "Mehrere Jahrgänge zuweisen" funktioniert nicht.

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#459]
In Kurse mit der rechten Maustaste auf einen Kurs klicken und "mehrere Jahrgänge zuweisen" anwählen, dann mehrere Kurse anklicken und mit "ok" zu bestätigen führt zu keiner sichtbaren Änderung im Feld "Jahrgänge".

**Comment by JeVaske** [comment]
Funktioniert bei mir

**Comment by AnneSchueller** [comment]
Es erscheint zwar keine Fehlermeldung, allerdings ändert sich der Eintrag unter "mehrere Jahrgänge"  nicht. Der Kurs ist auch anschließend nicht sichtbar in den vorab ausgewählten Jahrgängen unter Gruppenprozess ➜ Kurse zuweisen

**Comment by JuergenRichter** [comment]
Behoben
