### ISSUE TITLE
Spaltenbreite in Leistungsdaten / Laufbahninfo u.s.w. automatisch anpassen

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#46]
Bei mir sind die Spaltenbreiten (120% Skalierung) viel zu breit. Können die Spalten automatisch angepasst werden? Es ist immer ein immenser Aufwand, alle Spalten auf eine erträgliche Größe umzustellen.
![image](https://user-images.githubusercontent.com/75179015/101410512-c215c080-38df-11eb-8da8-01cfdb36e48c.png)

**Comment by JuergenRichter** [comment]
In Version 3.0.8 behoben
