### ISSUE TITLE
Kurse -> Doppelklick auf das Feld "Unterricht in ex. Schule" führt zu Fehlermeldung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#460]
Siehe Titel: Ein Doppelklick führt zu Fehlermeldung des Screenshots.

Ein Klick auf die Dropdown-Liste öffnet (korrekterweise?) eine leere Dropdownliste. 

Vermutung: Der Fehler wird durch einen unerwarteten leeren String erzeugt?

![Bug Kurs](https://user-images.githubusercontent.com/116796098/206869140-eaf4e49e-c4f8-47dc-8f3d-864540cc7efc.png)

![Bug Kurs2](https://user-images.githubusercontent.com/116796098/206869274-f8dd6d14-3a14-4911-b4e6-c3ae6a7e6cfe.png)

EurekaLog 7.10.0.0 8BD69D43571B8C48A2404FB6F3744F60 F34D760C4145464594300FC53126F404 DA39A3EE5E6B4B0D3255BFEF95601890AFD80709 3C702BDD906110449BC988E5F9B7C874

Application:
-------------------------------------------------------------------
  1.1 Start Date      : Sat, 10 Dec 2022 17:50:43 +0100
  1.2 Name/Description: SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  1.3 Version Number  : 3.0.50.8
  1.4 Parameters      : 
  1.5 Compilation Date: Thu, 1 Dec 2022 14:47:34 +0100
  1.6 Up Time         : 1 hour(s), 11 minute(s), 29 second(s)

Exception:
----------------------------------------------------------------------------
  2.1 Date          : Sat, 10 Dec 2022 19:02:12 +0100
  2.2 Address       : 009EE925
  2.3 Module Name   : SchILD30.exe - (SchILD 3.0 von ribeka GmbH)
  2.4 Module Version: 3.0.50.8
  2.5 Type          : EDatabaseError
  2.6 Message       : qrySchuleMitKuerzel: Das Feld '' wurde nicht gefunden.
  2.7 ID            : 6FCAF096
  2.8 Count         : 1
  2.9 Status        : New
  2.10 Note         : 
  2.11 Sent         : 0

User:
----------------------------------------------------------------
  3.1 ID        : Drache
  3.2 Name      : Drache
  3.3 Email     : 
  3.4 Company   : 
  3.5 Privileges: SeShutdownPrivilege             - OFF
                  SeChangeNotifyPrivilege         - ON (default)
                  SeUndockPrivilege               - OFF
                  SeIncreaseWorkingSetPrivilege   - OFF
                  SeTimeZonePrivilege             - OFF

Active Controls:
------------------------------------------------------------------------------------------------------------------------------------
  4.1 Form Class   : Tfrm_Hauptformular
  4.2 Form Text    : Aktuelle Datenbank: svwsdb, Schuljahr 2022/2023, 1. Hj., Benutzer: Admin (Verbindung zum SVWS-Server vorhanden)
  4.3 Control Class: TDBAxisGridnplaceEditCoreControl
  4.4 Control Text : 

Computer:
--------------------------------------------
  5.1 Name        : DESKTOP-6720GUC
  5.2 Total Memory: 17125748736 (15,95 Gb)
  5.3 Free Memory : 9029853184 (8,41 Gb)
  5.4 Total Disk  : 250056011776 (232,88 Gb)
  5.5 Free Disk   : 60294586368 (56,15 Gb)
  5.9 Display DPI : 144

Operating System:
---------------------------------------------
  6.1 Type    : Microsoft Windows 10 (64 bit)
  6.2 Build # : 2009 (10.0.19045.2311)
  6.3 Update  : Build 19045 #2311
  6.4 Language: German (0407)
  6.5 Charset : 0/1252

Call Stack Information:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
|Methods |Details|Stack   |Address |Module      |Offset  |Source            |Unit          |Class                           |Procedure/Method |Line             |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
|*Exception Thread: ID=11368; Parent=0; Priority=0                                                                                                              |
|Class=; Name=MAIN                                                                                                                                              |
|DeadLock=0; Wait Chain=                                                                                                                                        |
|Comment=                                                                                                                                                       |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
|7FFFFFFE|04     |00000000|009EE925|SchILD30.exe|005EE925|Data.DB.pas       |Data.DB       |                                |DatabaseError    |3229[7]          |
|00000040|04     |0019F910|009EE9D9|SchILD30.exe|005EE9D9|Data.DB.pas       |Data.DB       |                                |DatabaseErrorFmt |3238[1]          |
|00000040|04     |0019F934|00A05408|SchILD30.exe|00605408|Data.DB.pas       |Data.DB       |                                |Error            |13229[1]         |
|00000040|04     |0019F958|00A0544F|SchILD30.exe|0060544F|Data.DB.pas       |Data.DB       |TDataSet                        |FieldByName      |13234[2]         |
|00000040|04     |0019F970|00A05264|SchILD30.exe|00605264|Data.DB.pas       |Data.DB       |TDataSet                        |GetFieldValue    |13202[13]        |
|00000040|03     |0019F9B0|00BD0DC8|SchILD30.exe|007D0DC8|DBAxisGridsEh.pas |DBAxisGridsEh |TAxisBarEh                      |SetNextFieldValue|                 |
|00000040|03     |0019FADC|00BC63E3|SchILD30.exe|007C63E3|DBAxisGridsEh.pas |DBAxisGridsEh |TDBAxisGridnplaceEditCoreControl|MouseDown        |                 |
|00000040|04     |0019FAF8|0069391C|SchILD30.exe|0029391C|Vcl.Controls.pas  |Vcl.Controls  |TControl                        |DoMouseDown      |7559[7]          |
|00000040|04     |0019FB1C|006939DB|SchILD30.exe|002939DB|Vcl.Controls.pas  |Vcl.Controls  |TControl                        |WMLButtonDblClk  |7585[5]          |
|00000040|04     |0019FC5C|00697D8F|SchILD30.exe|00297D8F|Vcl.Controls.pas  |Vcl.Controls  |TWinControl                     |WndProc          |10278[166]       |
|00000040|03     |0019FCA8|00CEE0BE|SchILD30.exe|008EE0BE|GridsEh.pas       |GridsEh       |TInplaceEditCoreControl         |WndProc          |                 |
|00000040|04     |0019FD14|0069735C|SchILD30.exe|0029735C|Vcl.Controls.pas  |Vcl.Controls  |TWinControl                     |MainWndProc      |9977[3]          |
|00000040|04     |0019FD44|0055B5B4|SchILD30.exe|0015B5B4|System.Classes.pas|System.Classes|                                |StdWndProc       |17956[8]         |
|00000040|04     |0019FEEC|007BD0CB|SchILD30.exe|003BD0CB|Vcl.Forms.pas     |Vcl.Forms     |TApplication                    |ProcessMessage   |10747[23]        |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

Modules Information:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|Handle  |Name                       |Description                                           |Version            |Size    |Modified           |Path                                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|00400000|SchILD30.exe               |SchILD 3.0 von ribeka GmbH                            |3.0.50.8           |54630984|2022-12-01 17:57:06|D:\SchILD3.0\                                                                                                 |
|04300000|ChilkatDelphi32.dll        |Chilkat Delphi DLL 32-bit                             |9.5.0.82           |10655936|2022-11-15 09:10:16|D:\SchILD3.0\                                                                                                 |
|50030000|borlndmm.dll               |Embarcadero Memory Manager                            |25.0.29899.2631    |70000   |2022-11-15 09:10:18|D:\SchILD3.0\                                                                                                 |
|5E300000|ieframe.dll                |Internet Browser                                      |11.0.19041.2311    |6502400 |2022-12-03 19:16:36|C:\Windows\System32\                                                                                          |
|5EE60000|webio.dll                  |API für Webtransferprotokolle                         |10.0.19041.2075    |456704  |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|5EEE0000|netprofm.dll               |Network List Manager                                  |10.0.19041.2311    |184832  |2022-12-03 19:16:31|C:\Windows\System32\                                                                                          |
|5EF20000|shdocvw.dll                |Shelldokumentobjekt und Steuerungsbibliothek          |10.0.19041.746     |218112  |2021-03-11 16:37:13|C:\Windows\System32\                                                                                          |
|5EF60000|duser.dll                  |Windows DirectUser Engine                             |10.0.19041.546     |470528  |2021-03-11 16:37:10|C:\Windows\System32\                                                                                          |
|5EFE0000|appwiz.cpl                 |Shellanwendungs-Manager                               |10.0.19041.746     |469504  |2021-03-11 16:37:24|C:\Windows\System32\                                                                                          |
|5F060000|riched20.dll               |Rich Text Edit Control, v3.1                          |5.31.23.1231       |487424  |2019-12-07 10:09:32|C:\Windows\System32\                                                                                          |
|5F0E0000|wer.dll                    |Windows-Fehlerbericht-DLL                             |10.0.19041.1949    |701424  |2022-09-14 18:10:55|C:\Windows\System32\                                                                                          |
|5F310000|urlmon.dll                 |OLE32-Erweiterung für Win32                           |11.0.19041.2251    |1683456 |2022-11-09 16:11:08|C:\Windows\System32\                                                                                          |
|5F5D0000|url.dll                    |Internet Shortcut Shell Extension DLL                 |11.0.19041.1       |233472  |2019-12-07 10:10:00|C:\Windows\System32\                                                                                          |
|5F610000|ncrypt.dll                 |Windows NCrypt-Router                                 |10.0.19041.546     |130128  |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|5F640000|schannel.dll               |TLS/ SSL-Sicherheitsanbieter                          |10.0.19041.2194    |487936  |2022-11-09 16:11:07|C:\Windows\System32\                                                                                          |
|5F6C0000|iertutil.dll               |Laufzeit-Hilfsprogramm für Internet Explorer          |11.0.19041.2130    |2273656 |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|62E40000|msls31.dll                 |Microsoft Line Services library file                  |3.10.349.0         |183808  |2019-12-07 10:09:32|C:\Windows\System32\                                                                                          |
|630B0000|ntasn1.dll                 |Microsoft ASN.1 API                                   |10.0.19041.546     |161608  |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|630E0000|dbghelp.dll                |Windows Image Helper                                  |10.0.19041.1052    |1494016 |2021-06-09 16:33:19|C:\Windows\System32\                                                                                          |
|64140000|ncryptsslp.dll             |Microsoft SChannel Provider                           |10.0.19041.546     |117216  |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|64160000|ondemandconnroutehelper.dll|On Demand Connctiond Route Helper                     |10.0.19041.2311    |56832   |2022-12-03 19:16:29|C:\Windows\System32\                                                                                          |
|657F0000|windowscodecs.dll          |Microsoft Windows Codecs Library                      |10.0.19041.1706    |1511344 |2022-05-12 21:13:17|C:\Windows\System32\                                                                                          |
|65FD0000|gpapi.dll                  |Gruppenrichtlinienclient-API                          |10.0.19041.572     |111024  |2021-03-11 16:37:10|C:\Windows\System32\                                                                                          |
|660F0000|mscms.dll                  |Microsoft-Farbabstimmungssystem-DLL                   |10.0.19041.746     |594464  |2021-03-11 16:37:03|C:\Windows\System32\                                                                                          |
|672D0000|dpapi.dll                  |Data Protection API                                   |10.0.19041.546     |13312   |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|679F0000|TextShaping.dll            |                                                      |                   |611960  |2021-10-20 07:04:41|C:\Windows\System32\                                                                                          |
|67C00000|msi.dll                    |Windows Installer                                     |5.0.19041.2251     |2691584 |2022-11-09 16:11:14|C:\Windows\System32\                                                                                          |
|67F30000|winhttp.dll                |Windows HTTP-Dienste                                  |10.0.19041.2193    |830024  |2022-11-09 16:11:07|C:\Windows\System32\                                                                                          |
|68130000|mskeyprotect.dll           |Microsoft-Schlüsselschutzanbieter                     |10.0.19041.1202    |49664   |2021-09-15 15:18:48|C:\Windows\System32\                                                                                          |
|68A80000|winnsi.dll                 |Network Store Information RPC interface               |10.0.19041.546     |28360   |2021-03-11 16:36:51|C:\Windows\System32\                                                                                          |
|68A90000|dhcpcsvc.dll               |DHCP Clientdienst                                     |10.0.19041.2130    |73728   |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|68AB0000|dhcpcsvc6.DLL              |DHCPv6-Client                                         |10.0.19041.2130    |61440   |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|68AD0000|winsta.dll                 |Winstation Library                                    |10.0.19041.2075    |300624  |2022-10-12 11:59:27|C:\Windows\System32\                                                                                          |
|68CE0000|hhctrl.ocx                 |Steuerelement für Microsoft® HTML-Hilfe               |10.0.19041.746     |575488  |2021-03-11 16:37:24|C:\Windows\System32\                                                                                          |
|68D80000|CoreMessaging.dll          |Microsoft CoreMessaging Dll                           |10.0.19041.2193    |631648  |2022-11-09 16:11:07|C:\Windows\System32\                                                                                          |
|68E20000|CoreUIComponents.dll       |Microsoft Core UI Components Dll                      |10.0.19041.546     |2621720 |2021-03-11 16:37:03|C:\Windows\System32\                                                                                          |
|690A0000|textinputframework.dll     |"TextInputFramework.DYNLINK"                          |10.0.19041.2075    |754104  |2022-10-12 11:59:28|C:\Windows\System32\                                                                                          |
|69550000|ntmarta.dll                |Windows NT MARTA-Anbieter                             |10.0.19041.546     |152904  |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|69920000|dwmapi.dll                 |Microsoft Desktopfenster-Manager-API                  |10.0.19041.746     |138936  |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|69950000|oledlg.dll                 |OLE-Benutzerschnittstellen-Unterstützung              |10.0.19041.746     |163328  |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|6A2F0000|powrprof.dll               |Power Profile Helper DLL                              |10.0.19041.546     |268080  |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|6A550000|twinapi.appcore.dll        |twinapi.appcore                                       |10.0.19041.1865    |1635248 |2022-08-10 16:57:17|C:\Windows\System32\                                                                                          |
|6A6E0000|dxgi.dll                   |DirectX Graphics Infrastructure                       |10.0.19041.2311    |785056  |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|6A7B0000|sspicli.dll                |Security Support Provider Interface                   |10.0.19041.2130    |125056  |2022-10-12 11:59:26|C:\Windows\System32\                                                                                          |
|6A7F0000|d3d11.dll                  |Direct3D 11 Runtime                                   |10.0.19041.2075    |1964760 |2022-10-12 11:59:28|C:\Windows\System32\                                                                                          |
|6A9D0000|WinTypes.dll               |Windows-Basistypen-DLL                                |10.0.19041.2311    |897160  |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|6B920000|propsys.dll                |Microsoft-Eigenschaftensystem                         |7.0.19041.1741     |792832  |2022-06-15 11:14:24|C:\Windows\System32\                                                                                          |
|6B9F0000|ColorAdapterClient.dll     |Microsoft Color Adapter Client                        |10.0.19041.546     |45904   |2021-03-11 16:37:03|C:\Windows\System32\                                                                                          |
|6BBB0000|umpdc.dll                  |                                                      |                   |47472   |2021-03-11 16:37:05|C:\Windows\System32\                                                                                          |
|6BBC0000|secur32.dll                |Security Support Provider Interface                   |10.0.19041.546     |23040   |2021-03-11 16:37:11|C:\Windows\System32\                                                                                          |
|6BBE0000|dcomp.dll                  |Microsoft DirectComposition Library                   |10.0.19041.2075    |1448784 |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|6BD50000|dataexchange.dll           |Data exchange                                         |10.0.19041.1387    |183808  |2021-12-17 17:33:33|C:\Windows\System32\                                                                                          |
|6BE40000|srvcli.dll                 |Server Service Client DLL                             |10.0.19041.1645    |78016   |2022-04-20 17:12:56|C:\Windows\System32\                                                                                          |
|6BE60000|netutils.dll               |Net Win32 API Helpers DLL                             |10.0.19041.1466    |38232   |2022-01-14 22:35:29|C:\Windows\System32\                                                                                          |
|6BE70000|netapi32.dll               |Net Win32 API DLL                                     |10.0.19041.2130    |73864   |2022-10-12 11:59:27|C:\Windows\System32\                                                                                          |
|6BE90000|mpr.dll                    |Router-DLL für Mehrfachanbieter                       |10.0.19041.1806    |94536   |2022-07-29 16:11:07|C:\Windows\System32\                                                                                          |
|6BEC0000|wsock32.dll                |Windows Socket 32-Bit DLL                             |10.0.19041.1       |16384   |2019-12-07 10:09:15|C:\Windows\System32\                                                                                          |
|6BED0000|comctl32.dll               |Bibliothek für Steuerelemente                         |6.10.19041.1110    |2152264 |2021-07-09 07:47:26|C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984\|
|6CD20000|wkscli.dll                 |Workstation Service Client DLL                        |10.0.19041.1645    |64552   |2022-04-20 17:12:56|C:\Windows\System32\                                                                                          |
|6CE50000|dbgcore.dll                |Windows Core Debugging Helpers                        |10.0.19041.2311    |162816  |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|6DCF0000|npmproxy.dll               |Network List Manager Proxy                            |10.0.19041.2311    |26624   |2022-12-03 19:16:31|C:\Windows\System32\                                                                                          |
|6DD00000|osbaseln.dll               |Service Reporting API                                 |10.0.19041.1       |21504   |2019-12-07 10:09:13|C:\Windows\System32\                                                                                          |
|6DD10000|Faultrep.dll               |Windows-Benutzermodus-Absturzberichterstattungs-DLL   |10.0.19041.1949    |411112  |2022-09-14 18:10:55|C:\Windows\System32\                                                                                          |
|6DD80000|winmmbase.dll              |API für die Basissystemverlängerung                   |10.0.19041.1       |110720  |2019-12-07 10:09:11|C:\Windows\System32\                                                                                          |
|6DDA0000|tapi32.dll                 |Microsoft® Windows(TM) Telefonie-API-Client-DLL       |10.0.19041.423     |193536  |2021-03-11 16:37:27|C:\Windows\System32\                                                                                          |
|6F1F0000|msacm32.dll                |Microsoft ACM-Audiofilter                             |10.0.19041.1       |93472   |2019-12-07 10:09:11|C:\Windows\System32\                                                                                          |
|6F210000|fontsub.dll                |Font Subsetting DLL                                   |10.0.19041.2075    |99328   |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|6F230000|usp10.dll                  |Uniscribe Unicode script processor                    |10.0.19041.546     |77824   |2021-03-11 16:37:10|C:\Windows\System32\                                                                                          |
|6F250000|msvfw32.dll                |DLL für Microsoft Video für Windows                   |10.0.19041.1       |124416  |2019-12-07 10:10:04|C:\Windows\System32\                                                                                          |
|6F280000|avifil32.dll               |Microsoft AVI-Dateiunterstützungs-Bibliothek          |10.0.19041.1       |95744   |2019-12-07 10:10:04|C:\Windows\System32\                                                                                          |
|6F2A0000|olepro32.dll               |OLEPRO32.DLL                                          |10.0.19041.84      |88576   |2020-05-11 06:40:16|C:\Windows\System32\                                                                                          |
|6F380000|shfolder.dll               |Shell Folder Service                                  |10.0.19041.1       |8704    |2019-12-07 10:09:32|C:\Windows\System32\                                                                                          |
|6FD80000|rasadhlp.dll               |Remote Access AutoDial Helper                         |10.0.19041.546     |12800   |2021-03-11 16:37:12|C:\Windows\System32\                                                                                          |
|6FD90000|FWPUCLNT.DLL               |FWP/IPsec Benutzermodus-API                           |10.0.19041.1682    |347648  |2022-05-12 21:13:17|C:\Windows\System32\                                                                                          |
|6FE20000|mdnsNSP.dll                |Bonjour Namespace Provider                            |3.1.0.1            |122128  |2015-08-12 15:03:38|C:\Program Files (x86)\Bonjour\                                                                               |
|6FE70000|dnsapi.dll                 |DNS-Client-API-DLL                                    |10.0.19041.1865    |583144  |2022-08-10 16:57:17|C:\Windows\System32\                                                                                          |
|6FF70000|mswsock.dll                |Microsoft Windows Sockets 2.0-Dienstanbieter          |10.0.19041.546     |324416  |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|71280000|IPHLPAPI.DLL               |IP-Hilfs-API                                          |10.0.19041.546     |196784  |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|71540000|rsaenh.dll                 |Microsoft Enhanced Cryptographic Provider             |10.0.19041.1052    |184888  |2021-06-09 16:33:19|C:\Windows\System32\                                                                                          |
|71570000|cryptsp.dll                |Cryptographic Service Provider API                    |10.0.19041.546     |68192   |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|71590000|CRYPTBASE.dll              |Base cryptographic API DLL                            |10.0.19041.546     |31528   |2021-03-11 16:36:59|C:\Windows\System32\                                                                                          |
|716A0000|msasn1.dll                 |ASN.1 Runtime APIs                                    |10.0.19041.2251    |51664   |2022-11-09 16:11:07|C:\Windows\System32\                                                                                          |
|72EB0000|profapi.dll                |User Profile Basic API                                |10.0.19041.844     |89360   |2021-03-11 16:36:59|C:\Windows\System32\                                                                                          |
|72ED0000|GdiPlus.dll                |Microsoft GDI+                                        |10.0.19041.2251    |1449984 |2022-11-04 03:25:18|C:\Windows\WinSxS\x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_d9513b1fe1046fc7\        |
|73040000|msimg32.dll                |GDIEXT Client DLL                                     |10.0.19041.1466    |7168    |2022-01-14 22:35:29|C:\Windows\System32\                                                                                          |
|73260000|wldp.dll                   |Windows-Sperrungsrichtlinie                           |10.0.19041.2311    |154944  |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|73290000|windows.storage.dll        |Microsoft WinRT Storage-API                           |10.0.19041.2311    |6373648 |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|73900000|winmm.dll                  |MCI API-DLL                                           |10.0.19041.546     |149272  |2021-03-11 16:36:59|C:\Windows\System32\                                                                                          |
|74720000|uxtheme.dll                |Microsoft UxTheme-Bibliothek                          |10.0.19041.2193    |454144  |2022-11-09 16:11:05|C:\Windows\System32\                                                                                          |
|747A0000|kernel.appcore.dll         |AppModel API Host                                     |10.0.19041.546     |52672   |2021-03-11 16:37:05|C:\Windows\System32\                                                                                          |
|74D00000|userenv.dll                |Userenv                                               |10.0.19041.572     |141008  |2021-03-11 16:37:09|C:\Windows\System32\                                                                                          |
|74D50000|version.dll                |Version Checking and File Installation Libraries      |10.0.19041.546     |27320   |2021-03-11 16:37:12|C:\Windows\System32\                                                                                          |
|74D60000|wininet.dll                |Interneterweiterungen für Win32                       |11.0.19041.2193    |4516864 |2022-11-09 16:11:08|C:\Windows\System32\                                                                                          |
|75250000|wtsapi32.dll               |Windows Remote Desktop Session Host Server SDK APIs   |10.0.19041.546     |52664   |2021-03-11 16:37:00|C:\Windows\System32\                                                                                          |
|752D0000|oleacc.dll                 |Active Accessibility Core Component                   |7.2.19041.746      |321024  |2021-03-11 16:37:11|C:\Windows\System32\                                                                                          |
|753A0000|winspool.drv               |Windows-Spoolertreiber                                |10.0.19041.2311    |452608  |2022-12-03 19:16:29|C:\Windows\System32\                                                                                          |
|75480000|shlwapi.dll                |Shell Light-weight-Hilfsprogrammbibliothek            |10.0.19041.2075    |276840  |2022-10-12 11:59:30|C:\Windows\System32\                                                                                          |
|754D0000|ws2_32.dll                 |Windows Socket 2.0-32-Bit-DLL                         |10.0.19041.546     |397728  |2021-03-11 16:36:59|C:\Windows\System32\                                                                                          |
|75540000|rpcrt4.dll                 |Remoteprozeduraufruf-Laufzeitumgebung                 |10.0.19041.1806    |776824  |2022-07-29 16:11:04|C:\Windows\System32\                                                                                          |
|75B30000|nsi.dll                    |NSI User-mode interface DLL                           |10.0.19041.610     |20144   |2021-03-11 16:36:51|C:\Windows\System32\                                                                                          |
|75B80000|user32.dll                 |Client-DLL für Windows USER-API (mehrere Benutzer)    |10.0.19041.2311    |1686376 |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|75D70000|gdi32.dll                  |GDI Client DLL                                        |10.0.19041.2130    |139432  |2022-10-12 11:59:28|C:\Windows\System32\                                                                                          |
|75DA0000|KERNELBASE.dll             |Client-DLL für Windows NT-Basis-API                   |10.0.19041.2311    |2213712 |2022-12-03 19:16:26|C:\Windows\System32\                                                                                          |
|75FD0000|SHCore.dll                 |SHCORE                                                |10.0.19041.1645    |545984  |2022-04-20 17:12:56|C:\Windows\System32\                                                                                          |
|760C0000|imm32.dll                  |Multi-User Windows IMM32 API Client DLL               |10.0.19041.2193    |147736  |2022-11-09 16:11:07|C:\Windows\System32\                                                                                          |
|760F0000|shell32.dll                |Allgemeine Windows-Shell-DLL                          |10.0.19041.2311    |6017256 |2022-12-03 19:16:31|C:\Windows\System32\                                                                                          |
|766B0000|msvcp_win.dll              |Microsoft® C Runtime Library                          |10.0.19041.789     |495840  |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|76730000|oleaut32.dll               |OLEAUT32.DLL                                          |10.0.19041.985     |606888  |2021-05-13 10:47:51|C:\Windows\System32\                                                                                          |
|767D0000|msvcrt.dll                 |Windows NT CRT DLL                                    |7.0.19041.546      |775256  |2021-03-11 16:36:59|C:\Windows\System32\                                                                                          |
|76890000|ucrtbase.dll               |Microsoft® C Runtime Library                          |10.0.19041.789     |1181208 |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|769B0000|ole32.dll                  |Microsoft OLE für Windows                             |10.0.19041.1202    |926560  |2021-09-15 15:18:49|C:\Windows\System32\                                                                                          |
|76AA0000|bcrypt.dll                 |Bibliothek mit kryptografischen Primitiven von Windows|10.0.19041.1023    |96032   |2021-06-09 16:33:19|C:\Windows\System32\                                                                                          |
|76AC0000|clbcatq.dll                |COM+ Configuration Catalog                            |2001.12.10941.16384|526288  |2022-10-12 11:59:29|C:\Windows\System32\                                                                                          |
|76B50000|crypt32.dll                |Krypto-API32                                          |10.0.19041.1889    |1014368 |2022-08-10 16:57:17|C:\Windows\System32\                                                                                          |
|76C50000|advapi32.dll               |Erweiterte Windows 32 Base-API                        |10.0.19041.2130    |496392  |2022-10-12 11:59:26|C:\Windows\System32\                                                                                          |
|76CD0000|kernel32.dll               |Client-DLL für Windows NT-Basis-API                   |10.0.19041.2251    |646024  |2022-11-09 16:11:05|C:\Windows\System32\                                                                                          |
|76DC0000|gdi32full.dll              |GDI Client DLL                                        |10.0.19041.2311    |907000  |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|76EA0000|bcryptPrimitives.dll       |Windows Cryptographic Primitives Library              |10.0.19041.1415    |383264  |2021-12-17 17:33:29|C:\Windows\System32\                                                                                          |
|76F00000|win32u.dll                 |Win32u                                                |10.0.19041.2311    |94040   |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|76F20000|msctf.dll                  |MSCTF-Server-DLL                                      |10.0.19041.2193    |862536  |2022-11-09 16:11:05|C:\Windows\System32\                                                                                          |
|77000000|sechost.dll                |Host for SCM/SDDL/LSA Lookup APIs                     |10.0.19041.1865    |477808  |2022-08-10 16:57:15|C:\Windows\System32\                                                                                          |
|77080000|comdlg32.dll               |DLL für gemeinsame Dialoge                            |10.0.19041.1806    |688128  |2022-07-29 16:11:07|C:\Windows\System32\                                                                                          |
|77130000|psapi.dll                  |Process Status Helper                                 |10.0.19041.546     |17016   |2021-03-11 16:37:08|C:\Windows\System32\                                                                                          |
|77140000|imagehlp.dll               |Windows NT Image Helper                               |10.0.19041.1415    |95496   |2021-12-17 17:33:29|C:\Windows\System32\                                                                                          |
|77330000|combase.dll                |Microsoft COM für Windows                             |10.0.19041.2311    |2636184 |2022-12-03 19:16:30|C:\Windows\System32\                                                                                          |
|775C0000|ntdll.dll                  |DLL für NT-Layer                                      |10.0.19041.2193    |1700440 |2022-11-09 16:11:05|C:\Windows\System32\                                                                                          |
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Processes Information:
----------------------

Assembler Information:
----------------------

Registers:
----------

**Comment by JeVaske** [comment]
Bei mir funktioniert es. Es öffnet sich dasslbe Fenster wie in Schild2.

**Comment by AnneSchueller** [comment]
Wenn die externen Schulen ein Kürzel haben, funktioniert das bei mir. Die Fehlermeldung kam auch schon bei Schild2, wenn keine Schule mit eingetragenem Kürzel vorhanden war.  Evtl. könnte man statt der Fehlermeldung ein Hinweisfenster erscheinen lassen?

**Comment by FrodBRA** [comment]
Das wäre gut, ein Fehlschlag mit einer "technischen Fehlermeldung" ist kritisch, den technischen Fehler mit einer "erklärenden Textbox" abzufangen ist die bessere Lösung.

**Comment by JuergenRichter** [comment]
Behoben
