### ISSUE TITLE
Datenaustausch / Unterrichtsdaten (als Excel-Dateien) importieren funktioniert nicht

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#461]
Wenn ich Unterrichtsdateien per Excel-Import importiere, die ich in Schild 2 importieren kann, nämlich nach diesem Format
![Schildfehler200](https://user-images.githubusercontent.com/78501680/206878299-88b9a019-2f2e-4e7f-aa0e-5417ef6caee3.jpg)

kommt diese Fehlermeldung, die keinen Sinn ergibt, denn die Kursbezeichnung muss nicht eingetragen sein und das Jahr ist nicht falsch. In Schild 2 wird die Datei anstandslos importiert. Die Datenbank ist im Grunde dieselbe.

![Schildfehler201](https://user-images.githubusercontent.com/78501680/206878380-c49c3af2-4138-4095-840d-7508facf9e2f.jpg)

**Comment by NielsWL** [comment]
Kann ich auch reproduzieren. Gibt es dazu Neuigkeiten?

**Comment by FrodBRA** [comment]
Dieser Fehler sollte vor Release behoben sein, mit Excel wird recht viel gearbeitet.

@AnneSchueller Kannst du das als wichtigen Milestone aufnehmen?

**Comment by JuergenRichter** [comment]
Behoben
