### ISSUE TITLE
Unterrichtsdateien importieren Dateityp

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#462]
In Schild2 wird mir als Dateityp für den Unterrichtsimport folgende Auswahl gezeigt:
![Schildfehler 202](https://user-images.githubusercontent.com/78501680/206878506-5fa30f4d-470f-468e-9bdd-1bb5f89e81a2.jpg)

In Schild3 diese:
![Schildfehler203](https://user-images.githubusercontent.com/78501680/206878534-72cac689-a54a-4df6-aae8-258f73bfc0d9.jpg)

Bei den ersten Importversuchen wurde mir nur die Datei vom Typ 97-2003 angezeigt. Nach dem 5. Versuch wird jetzt auch die .xlsx angezeigt. Das ist auch nach dem Neustart der Fall. Schön wäre es, wenn direkt beide Dateien angezeigt werden.

**Comment by JeVaske** [comment]
[IMPORT2.xls](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10201131/IMPORT2.xls)
[IMPORT2.xlsx](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10201132/IMPORT2.xlsx)

**Comment by JuergenRichter** [comment]
Behoben
