### ISSUE TITLE
Anlegen von einem "Neueintrag" einer neuen Adresse in "Weitere Adressen" schlägt fehl

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#463]
Versuche Adresse mit Ansprechpartner anzulegen:

![WeitereAdressen](https://user-images.githubusercontent.com/116796098/206913039-2da15569-6053-4adc-a49e-83f7dbc2eddd.png)

Der Name des Betriebs war leer. Nachdem ein Name eingetragen war, ließ sich die Adresse auch mit Ansprechpartner anlegen.

**Comment by AnneSchueller** [comment]
Ich habe gerade auch nochmal verschiedene Kombinationen getestet. Die Fehlermeldung erscheint immer dann, wenn man den Ansprechpartner eingibt und bestätigt bevor man die aktuelle Adresse des neuen Betriebs links oben mit dem Haken bestätigt hat. Evtl. weil die Betrieb dann noch nicht in der DB steht?

**Comment by JuergenRichter** [comment]
Behoben
