### ISSUE TITLE
DB-Auswahl nach Migration im Expertenmodus doppelt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#464]
Wählt man einen anderen Namen für die config Datei bei der Migration im Expertenmodus, so erhält man anschließend 2 DBs zur Auswahl beim Starten von Schild3 (beide funktionieren; hier: BK ist der Name der mdb und BK_22_23_Name ist der Name der bei der Migration für die config-Datei angegeben wurde):
![2022-12-15_125337](https://user-images.githubusercontent.com/79116896/207854229-8f32757f-7819-40b2-842d-63b8761e99b9.png)

**Comment by JuergenRichter** [comment]
Behoben
