### ISSUE TITLE
"Akt. Halbjahr" -> "Fehlzeiten" Wahl eines Datums/einer Uhrzeit führt zu Fehler "Integerüberlauf" und Abbruch

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#465]
Anwahl eines Datums in "Fehlzeiten", das Datum öffnet sich, dann öffnet sich das Fenster zur Uhrzeitwahl.

Eine Bestätigung mit "Ok" führt zum Fehler "Integerüberlauf". Ein Datum kann nicht gesetzt werden.

**Comment by JuergenRichter** [comment]
Welche Version?

**Comment by AnneSchueller** [comment]
Ich konnte das mit der Version 0.0.54 vom 15.12.22 reproduzieren.
Ich musste allerdings ein bisschen hin und her Klicken, bis die Fehlermeldung kam.

**Comment by FrodBRA** [comment]
3.0.50.8 vom 1.12.2022
