### ISSUE TITLE
"Akt. Halbjahr" -> "Fehlzeiten" "Update failed. Found 0 records."

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#467]
Wenn man in den Fehlstunden herumklickt, siehe Screenshot, lässt sich ein nicht zu folgender Fehler provozieren:

![Fehlstunden](https://user-images.githubusercontent.com/116796098/208150694-55509a47-802f-455a-ba89-ad9460f85d09.png)

ESC beendet den Fehler, Veränderungen der ersten Zeile führen zu einer erneuten Fehlermeldung, das Fenster kann nicht verlassen werden und die Daten sind leer.

Nach einem Restart von SchILD ist der Fehler weg und die Datumsfelder sind tatsächlich ausgefüllt.

Anmerkung: eine Erfassung der Uhrzeit bei der **_Datums_**auswahl erscheint nicht sinnvoll.

Der Standardwert für die Fehlstunden sollte ("Bis Stunde" - "Von Stunde") sein, dieser Standard kann dann von Hand verändert werden.

**Comment by JuergenRichter** [comment]
Behoben
