### ISSUE TITLE
Schild3-Installer-Setup

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#468]
Ich würde hier gerne einige Dinge im Schild3-Setup-Installer angehen und bis zum 10.1.2023 klären.
Haupsächlich betrigff das das Programm MigrateDB.exe

![SNAG_2022_12_24_12 41 47](https://user-images.githubusercontent.com/34127980/209434406-64641a71-2b8a-41f8-b735-9750d69927f1.png)

Ich finde dies für normale User verwirrend und nicht anwendbar.
Folgende Punkte würde ich gerne angehen:

- [ ] Trennung in ein eigenes Programm, welches nur die SDBCFG-Datei anlegt
- [ ] Abschaltungsmöglichkeit der Datenabkreparaturen in MigrateDB, da dies bei der Migration gemacht wird
- [ ] Abschaltung der Migrationsmöglichkeit im Schid3-Setup (machen wir)
- [ ] Aufruf des kleinen SDBCFG-Programms
- [ ] Das kleine Programm liefert die Daten zum SVWS-Server, wenn diese gefunden werden, sonst muss manuell eingegeben werden.
- [ ] MigrateDB.exe wird so wie es ist natürlich trotzdem ausgeliefert.

**Comment by JuergenRichter** [comment]
"Trennung in ein eigenes Programm, welches nur die SDBCFG-Datei anlegt"
Das gibt es eigentlich schon: SchILD_DBConfig.exe

Können wir natürlich etwas anpassen, z.B. die Auswahl des Datenbankformates unterbinden
![image](https://user-images.githubusercontent.com/61280188/210236967-d1a7f6de-1d16-4bc6-b30a-476e525e48e9.png)


"Abschaltungsmöglichkeit der Datenabkreparaturen in MigrateDB, da dies bei der Migration gemacht wird"
Das ist schon raus, es wird nur eine Kopie der MDB angelegt und diese mit der Access-Funktion "Reparieren und Komprimieren" bearbeitet

"Das kleine Programm liefert die Daten zum SVWS-Server, wenn diese gefunden werden, sonst muss manuell eingegeben werden."
Werde ich ergänzen

**Comment by JuergenRichter** [comment]
Noch eine Ergänzung:
Ich würde vorschlagen, die Auswahl des Datenbankformates beizubehalten, mit folgenden Einschränkungen:
-Es wird nur noch MARIADB und SQLITE angeboten 
-MARIADB ist Default

![image](https://user-images.githubusercontent.com/61280188/210237447-4b873128-a981-4124-9264-29a0f8bb5e27.png)

**Comment by JuergenRichter** [comment]
Frage: Man kann ja wohl den Port für den SVWS-Server in der svwsconfig.json einstellen. Welcher Eintrag ist das denn?

**Comment by JuergenRichter** [comment]
Ich habe jetzt das Programm  SchILD_DBConfig.exe überarbeitet

![image](https://user-images.githubusercontent.com/61280188/210336225-5ea51fc1-8e7f-4cfd-ab57-78863ff4f3f4.png)

Beim Start werden die Datenbank-Parameter aus der svwsconfig.json (sofern vorhanden) geladen. Falls dort bei "DBKonfiguration.location" der Eintrag "localhost" sthet, wird dieser für das Programm durch den jeweiligen Computernamen ersetzt (siehe Screenshot). Das hat den Vorteil, dass keine Unterscheidung der beiden folgenden Fälle gemacht werden muss:

- Installation auf Einzelplatzrechner (wo "localhost" zutreffen würde)
- Installation auf einem Server der Schule (wo "localhost" falsch wäre, da die Clients, die das Programm über das Netzwerk starten, ja keinen lokal installierten MariaDB-Server haben).

Wenn die svwsconfig.json nicht gefunden wird oder das Programm auf einem Client ausgeführt wird (ohne MariaDB-Installation) muss alles manuell eingetragen werden

**Comment by FPfotenhauer** [comment]
Der Port wird über "PortHTTPS" : null, eingetragen.
Wenn dieser null ist, dann wird default 443 genommen.

**Comment by FPfotenhauer** [comment]
MariDB und SQLite reichen aus! Danke.

**Comment by JuergenRichter** [comment]
Erfüllt die aktuelle Version von SchILD_DBConfig.exe die Wünsche?

**Comment by FPfotenhauer** [comment]
Ich glaube ja, wir müssen das noch einbauen.
Das Issue schließe ich dann... danke.

**Comment by FPfotenhauer** [comment]
Habe den Installer angepasst. Liegt in der Cloud und auf dem FTP-Server.
