### ISSUE TITLE
SVWS-Server 0.5.0

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#469]
Ich wollte gerade mit der aktuellen Version erneut migrieren, um die Erklärvideos zu produzieren. Leider kommt die Fehlermeldung:
![Schildfehler300](https://user-images.githubusercontent.com/78501680/209998612-5903f6b3-3690-47e5-863c-3ef710dd3699.jpg)

**Comment by FPfotenhauer** [comment]
Bitte mir die Logs einmal per Mail senden.

**Comment by JeVaske** [comment]
Kann ignoriert werden. Es funktioniert!
