### ISSUE TITLE
Doppelklick zum festen Markieren von Schülern funktioniert nicht bzw. Filter ist nicht mehr vorhanden.

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#47]
Ich kann die Schüler nicht mit Doppelklick markieren, um die Schüler fest auszuwählen. Oder gibt es diese Art der Markierung nicht mehr? Ich finde sie extrem praktisch und sicher.

**Comment by FPfotenhauer** [comment]
Das wurde bewusst entfernt.

**Comment by Kluesenerm** [comment]
Das finde ich schwer nachvollziehbar. Gerade bei kritischen Gruppenprozessen war die Doppelklickmarkierung wirklich sicher und hilfreich.

**Comment by FPfotenhauer** [comment]
Es sollte beim Doppelklich auf einen Schüler, das Häkchen vorne im Kasten gesetzt werden.
Außerdem sollte bei Setzen des Hakens das Feld Schueler.Markiert auf "+" gesetzt werden.
Dann ist die alte Funktionalität wieder voll vorhanden.

**Comment by JuergenRichter** [comment]
Kommt in Version 3.0.9
