### ISSUE TITLE
Stundentafeln

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#471]
Ich verwende die die aktuelle Version (3.0.51.8) und vermisse die "kleinen Plus-Smbole" im Katalog Stundentafeln. Jedenfalls habe ich es von der vorherigen Version so in Erinnerung, dass man über das große Plus oben für einen Jahrgang zunächst eine Stundentafel anlegt und danach mit dem kleinen Plus-Symbol ähnlich wie bei den Leistungsdaten die Detailansicht aufklappt. Darüber hinaus fehlt auch das Pulldownmenü, um den jeweiligen Jahrgang auszuwählen.

**Comment by JeVaske** [comment]
Ich habe ajtuell eine Gesamtschul-Schulungsdatenbank migriert (S3-Schulung: DB GE-240). Da sie aber in einem alten Access-Format war, musst ich die erst mit dem herkömmlichen Migrationstool migrieren, damit das neue Schild-3-Migrationstool arbeiten kann.

**Comment by FPfotenhauer** [comment]
Können wir leider nicht ändern. Kann der JDBC Treiber nicht. Sorry.

**Comment by JeVaske** [comment]
Darum ging es mir auch nicht. Dachte nur, dass das wichtig sein könnte. Jedenfalls lässt sich da bei mir nichts mit Plus nichts aufklappen.

**Comment by JuergenRichter** [comment]
Sind denn in der Tabelle "stundentafel_faecher" auch Datensätze vorhanden? Kann man in ScHILD über die SQL-Abfrage 
select * from stundentafel_faecher
ermitteln.

**Comment by JeVaske** [comment]
Nein.

**Comment by JuergenRichter** [comment]
Dann kann natürlich auch nichts angezeigt werden. 
Sind denn in der Original-MDB (alten Access-Format) Einträge vorhanden?

**Comment by JuergenRichter** [comment]
Oder habe ich das falsch verstanden, dass das "Plus"-Symbol gar nicht angezeigt wird (auch wenn gar keine Fächer in der Stundentafel sind)?
![image](https://user-images.githubusercontent.com/61280188/210961680-c46bcee4-c348-4691-8947-4bac969a5a6d.png)
![image](https://user-images.githubusercontent.com/61280188/210961852-708e8fee-ec00-48e0-b96e-8c45d5505742.png)

**Comment by JeVaske** [comment]
Ganz genau. Das "Plus-Symbol" wird nicht angezeigt. Ich migriere morgen nochmal meine Produktiv-DB. Vielleicht stimmt mit der Schulungsdatenbank irgendetwas nicht. So sieht das jedenfalls aus: 
![schild_100s](https://user-images.githubusercontent.com/78501680/211157455-f1e0f0af-c07b-40dc-8945-40d4ecb3ce27.jpg)

**Comment by JuergenRichter** [comment]
Ich kann das Problem nicht reproduzieren. Was mich wundert ist, dass einige Spalten gar nicht angezeigt werden. Bitte mal den folgenden Schalter betätigen, danach neu starten.
![image](https://user-images.githubusercontent.com/61280188/211295826-5f11f01c-e58c-402a-a3d3-3f0f31a9c37c.png)

**Comment by AnneSchueller** [comment]
Ich habe jetzt auch nochmal mit einer Gesamtschul-DB getestet. Ich kann das Problem ebenfalls nicht reproduzieren.

**Comment by JeVaske** [comment]
Keine Veränderung.

**Comment by JuergenRichter** [comment]
Bitte nochmal mit der aktuellen Version 3.0.53.9 probieren.

**Comment by JeVaske** [comment]
Jetzt funktioniert es!
