### ISSUE TITLE
Kurse zuweisen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#472]
Den Gruppenprozess "Kurse zuweisen (Einzelkurs)" finde ich nicht. Darauf kann man auch verzichten. Wenn bewusst darauf verzichtet wurde, würde ich vorschlagen, den Zusatz "(mehrere)" auf der Schaltfläche des Gruppenprozesses "Kurse zuordnen (mehrere)" zu entfernen.

**Comment by AnneSchueller** [comment]
Das ist ein guter Hinweis. Auf die Option wurde bewusst verzichtet; daher sollte das "mehrere" entfernt werden.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
