### ISSUE TITLE
Katalog Kurse Lehrer anlegen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#473]
Wenn ich im Katalog Kurse einen neue Kurs anlege und dann einen Lehrer auswähle, kommt die folgende Fehlermeldung:
![Schildfehler 003](https://user-images.githubusercontent.com/78501680/210617913-6d7d454c-4449-441a-bc84-da9bfee746c3.jpg)

**Comment by JuergenRichter** [comment]
Behoben
