### ISSUE TITLE
Zugriffsverletzung bei Auswahl

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#475]
Wen ich mit der heutigen Version von Schild3 auf Auswahl klicke, gibt es eine Zugriffsverletzung.

[EurekaLog.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10417891/EurekaLog.txt)

**Comment by JuergenRichter** [comment]
Da scheint wohl was bei der Umstellung auf die neue IDE nicht korrekt gelaufen zu sein. Prüfe ich kurtfristig

**Comment by JuergenRichter** [comment]
Sollte behoben sein, ich schließe das Ticket mal
