### ISSUE TITLE
Fehlende Scrollbalken

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#476]
Unter Individualdaten I findet man einen Scrollbalken, wenn nicht alle Angaben in das aktuelle Fenster passen.

Bei allen anderen Karteireitern fehlt der Scrollbalken.

![2023-01-27_092801](https://user-images.githubusercontent.com/79116896/215042268-98d2da39-8b30-4562-87cf-379054d15515.png)
![2023-01-27_092919](https://user-images.githubusercontent.com/79116896/215042300-014471ef-ff7a-4231-a351-1e2a58779f8e.png)

**Comment by JuergenRichter** [comment]
Behoben
