### ISSUE TITLE
Zoom-Faktor

### ISSUE THREAD

**Issue by ThomasBartelworth** [SVWS-NRW/Schild3-BetaTest#478]
Es hat sich in vielen Schulen bislang bewährt, den Zoom-Faktor in der Darstellung von SchILD (Fenster-Skalieren) an den jeweiligen Monitor anzupassen. Bitte prüfen, ob dies auch umgesetzt werden kann.

![Unbenannt](https://user-images.githubusercontent.com/123943765/215452824-0ab0a83c-cdc5-4f49-9e73-949968d2f20d.jpg)

**Comment by JuergenRichter** [comment]
Das wird nicht gehen, da SchILD dann für alle "Darstellungsobjekte" eine eigene Skalierungsberechnung haben müsste. Wir haben schon genug Probleme, die Darstellung z.B. für hochauflösende Monitore anzupassen.

**Comment by JuergenRichter** [comment]
Nachtrag: Ich muss mal prüfen, ob man die Eigenschaft "Monitor.PixelsPerInch" (die normalerweise nur gelesen wird) auch programmtechnisch setzen kann. Dann könnet es u.U. funktionieren.

**Comment by pemichalski** [comment]
@JuergenRichter : die Skalierung auf einem Surface Pro 6 (2736 x 1824, Seitenverhältnis:  3:2) ist bei einer empfohlenen Skalierung von 200% viel zu klein. Die Kalenderfenster sind so weit ineinandergeschoben, dass sie nicht mehr ablesbar sind (einen Screenshot kann ich auf Wunsch nachliefern).

![S3_Menü_Surface](https://user-images.githubusercontent.com/130543126/231522500-09135ca8-c3ac-4635-adb2-e2dc45343064.png)

**Comment by AnneSchueller** [comment]
Hallo Pit,
die Skalierungsprobleme werden aktuell überarbeitet. Insbesondere beim Arbeiten mit zwei Monitoren kommt es bei der aktuellen Version noch zu ungewollten Seiteneffekten.

**Comment by FrodBRA** [comment]
@pemichalski @AnneSchueller 

Die Skalierungsprobleme sollten sich mit der UI-Überarbeitung erledigt haben. Mir sind keine mehr aufgefallen. 

Der Wunsch, nach der alten Zoom-Einstellung aus SchILD2 kann ja nicht umgesetzt werden. Sofern also keine neuen Darstellungsfehler beim Test mit ungewöhnlichen Auflösungen auftauchen, sollte das Issue bis zum Auftreten von weiteren Fehlern erledigt sein.

Eventuell wäre ein Hinweis auf die Barrierefreiheits-Optionen und Zoom-Möglichkeiten von Windows auf Betriebssystemebene sinnvoll (in SchILD oder im Wiki).

**Comment by AnneSchueller** [comment]
Ich schließe das Issue mal. Bezüglich der Hinweise: In Schild würde ich davon absehen. Der User ändert ja nicht die Bildschirmeinstellungen immer wenn er mit Schild arbeitet. Ggf. kann man das im Wiki an passender Stelle erwähnen.
