### ISSUE TITLE
SchILD 3 (3.0.53.9) startet nicht (SVWS Server 0.51)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#479]
Habe heute den aktuellen SVWS-Server (0.51) und SchILD (3.0.53.9) über die existierende Installation geschrieben.

Der Start von SchILD 3 schlägt folgend fehl:

![Startup0](https://user-images.githubusercontent.com/116796098/215514843-9adb7775-8c2c-4482-9478-a0dd276aa0df.jpg)

![Startup](https://user-images.githubusercontent.com/116796098/215514889-f835a60f-da1d-405b-94f4-ac02f702426b.jpg)

[Nebenbemerkung: Der Server ist über https://localhost auch nicht erreichbar, obwohl der Service svws_server_mariadb laut Windows läuft; hängt das zusammen?]

**Comment by AnneSchueller** [comment]
Hallo Felix, 

Hast du die Programme als Admin installiert? Hast du entsprechende Zugriffsrechte auf die Ordner "ProgrammData", "Programme" und "Programme x86?
Könntest du mal die log-Files reinstellen oder schicken? 
Unter ProgrammData/SVWS-Server/logs

Da Schild3 mittlerweile über die API auf beispielweise die Kataloge zugreift, muss der Server laufen, um Schild3 zu nutzen. 
Die Fehlermeldung ist allerdings dann eine andere: 
" Cannot connect to server on host 'localhost':
                      Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
                      Socket Error Code:_10061($274D).
"

**Comment by Raffenberg** [comment]
Hallo Felix,
Du benutzt die Schild-Installation aus der Fachberater-Cloud, richtig? Die ist fehlerhaft. Ich habe eine SchILD30.zip in die Fachberatercloud geladen. Entpacke die Daten in den Installationsordner von Schild3. Dann sollte Schild3 starten.

**Comment by AnneSchueller** [comment]
Welche Fehlermeldung hattest du denn bei der Setup_schild3_v..56.exe Datei? Bei mir hat es damit geklappt... Allerdings wurde nun nicht die migrate.exe automatisch aufgerufen. Diese musste ich vorab schon vorher einmal ausführen.

**Comment by Raffenberg** [comment]
Exakt die gleiche.

**Comment by Raffenberg** [comment]
Ach so. Ich erhalte die Fehlermeldung nicht bei der Installation, sondern beim Start.

**Comment by AnneSchueller** [comment]
Hast du denn eine Verbindung zum Server über localhost?
Und migrate.exe wurde ausgeführt?

**Comment by AnneSchueller** [comment]
Wenn man Schild3 drüber installiert und die DB nicht neu migriert erhält man die Fehlermeldung.
Die DB muss dann nochmal mit migrate.exe migriert werden, Am besten löscht man die altern sdbcfg Dateien aus dem Arbeitsverzeichnis

**Comment by Raffenberg** [comment]
Ich habe alles neu installiert. Keine Reste auf dem PC. SVWS-Server mit Migration. Dann Schild3, dann sdbcfg-Datei erstellt. Server läuft. Datenbank ist erreichbar. Schild startet und wirft die Fehlermeldung raus. Zip-Dateien aus dem Fachberaterordner (die sind aus dem FTP-Ordner von Ribeka) entpackt und in das Schild-Verzeichnis geschoben. Schild starten und alles läuft.

Ich meine, Frank hätte auch berichtet, dass die letzte Version bei ihm ebenfalls den fehler produzierte.

**Comment by Raffenberg** [comment]
Ich nutze Windows 11 (unseren MSB-Rechner). Habs auch in Hyper-V getestet, ebenfalls Windows 11. Das gleiche Problem.

Einzige Besonderheit: Ich habe Port 3406 benutzt. Aber wie gesagt: Nach Austausch der Schild-Dateien läuft ja alles. Es muss ein Problem mit den Installationsdateien sein.

**Comment by Raffenberg** [comment]
Ach so: Ich installiere Schild3 immer drüber, oder schiebe nur die ZIP-Daten in das Verzeichnis. Das hat keine Auswirkungen auf die DB. Neu migriert habe ich da noch nie. Schild3 kann eigentlich dauerhaft installiert bleiben, auch wenn ich den SVWS-Server deinstalliere und neu aufsetze.

**Comment by AnneSchueller** [comment]
Ich kann mich auch dunkel daran erinnern, dass es mit der .exe Probleme gab. 
Ich habe jetzt nochmal alles gelöscht (auch schild3) und neu installiert. Auf meinem Arbeitsrechner klappt es.
Seltsam...

**Comment by FPfotenhauer** [comment]
> [Nebenbemerkung: Der Server ist über https://localhost auch nicht erreichbar, obwohl der Service svws_server_mariadb laut Windows läuft; hängt das zusammen?]

Das ist nur der MariaDB-Service es muss auch der svws_server Dienst laufen!

**Comment by Raffenberg** [comment]
Das hatte ich bisher übersehen. Das ist schon seltsam.

**Comment by FPfotenhauer** [comment]
Ich habe hier die Schild3-Version_3-0-53 aus dem Installer_v.0.0.56 mit dem aktuellen SVWS-Server laufen.
Die sollte auch mit dem SVWS-Server_v0.5.1 laufen.

**Comment by Raffenberg** [comment]
Vielleicht sollten wir nochmal die allerneuste Schild3-Version mit dem neusten SVWS-Server in die Cloud legen und damit testen. Ggf. dann rückmelden, wenn es Probleme gibt. Das wirkt mir momentan zu undurchsichtig.

**Comment by FPfotenhauer** [comment]
Welche Version soll denn die neue Schild3-Version sein?
Bitte mal Versionsnummern angeben. Für mich ist die Version im Repository für die Binaries maßgeblich.
Dort ist die Version 3.0.53 als aktuell drin. Falls das nicht die in der Fachberatercloud ist, bitte eine Rückmeldung.

**Comment by FrodBRA** [comment]
> Hast du die Programme als Admin installiert? Hast du entsprechende Zugriffsrechte auf die Ordner "ProgrammData", "Programme" und "Programme x86?

Erstinstallation ja, es lief.
Nach dem Update nicht. Es lief im Anschluss nicht.
Update noch mal als "Als Admin ausführen" angestoßen. Es lief im Anschluss nicht. 

Weiter siehe Kommentar in der Antwort zu Jens.

[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10549288/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10549289/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10549290/svws_server_service.wrapper.log)

**Comment by FrodBRA** [comment]
> Hallo Felix, Du benutzt die Schild-Installation aus der Fachberater-Cloud, richtig?

Korrekt. 

> Ich habe eine SchILD30.zip in die Fachberatercloud geladen. Entpacke die Daten in den Installationsordner von Schild3. Dann sollte Schild3 starten.

Das ist aber eine ältere Version von SchILD 3. 

Starte ich nun, komme ich in die Nutzerauswahl, dann heißt es "mtblLaender: Das Feld 'gueltigVon' wurde nicht gefunden."

**Comment by FrodBRA** [comment]
> Vielleicht sollten wir nochmal die allerneuste Schild3-Version mit dem neusten SVWS-Server in die Cloud legen und damit testen. Ggf. dann rückmelden, wenn es Probleme gibt. Das wirkt mir momentan zu undurchsichtig.

Bitte das.

**Comment by FPfotenhauer** [comment]
Allerneuerste ist wie gesagt keine vernünftige Versionsangabe.

Im Log sehe ich, dass der Server in einem ständigen Kampfmodus ist, weil die Datenbank nicht aktuell ist. Bitte alles rasieren und neu installieren und migrieren. Wir haben die Updatefähigkeit noch nicht freigegeben!

Hattest du das gemacht?

**Comment by FPfotenhauer** [comment]
Die Schild3.zip habe ich nicht in die Cloud gelegt. Ich hatte die ZIP mit Versions Nummer 0.0.56 eingestellt. Die ist.E. aktuell.

**Comment by FrodBRA** [comment]
> Hattest du das gemacht?

Natürlich nicht ;)

Dass die Updatefähigkeit (gar) nicht gegeben ist, war mir nicht klar. Wolltet ihr nicht schon in den tatsächlichen Einsatz damit? Genug Gerede:

Nach einer kompletten Neuinstallation von SWVS 0.51 ist der SVWS-Server über Localhost erreichbar. 

SchILD 3 habe ich neu installiert (mit der defekten Setup 0.0.56) - > Identischer Fehler wie im ersten Post
Die Installation mit der Version aus der 0.0.56.zip überspielt -> identischer Fehler.
Die 0.0.56 einfach direkt aus der entpackten .zip gestartet -> identischer Fehler.

**Comment by FPfotenhauer** [comment]
Wenn Schild3 eine Exception macht, dann nützen mir die Server.logs leider wenig.

Hier wäre das komplette Eureka.log interessant und da müsste dann vielleicht Herr Richter etwas sagen.

**Comment by AnneSchueller** [comment]
Meinst du das Setup-log in Benutzer->AppData->Local->temp?

**Comment by FPfotenhauer** [comment]
Eureka Log... Copy to Clipboard....

**Comment by Raffenberg** [comment]
[Log.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10554859/Log.txt)
Ich habe das auf zwei unterschiedlichen Servern getestet.
Es ist die Schild3-Version 3.0.53.9 vom 18.01.2023

In dem Zusammenhang wäre es hilfreicher, wenn die Versionsnummer der Schild-Datei der versionsnummer beim Start entsprechend würde.

**Comment by Raffenberg** [comment]
Ich habe die Schild3-Version 3.0.51.8 drübergebügelt (schild.exe). Das Programm startet zunächst ohne Fehlermeldung. Auf dem einen PC startete gestern Schild durch. Auf meinem Laptop erhalte ich die Fehlermeldung mtblLaender: Das Feld gueltigVon wurde nicht gefunden. Log anbei.
[Log-ltblLaender.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10554999/Log-ltblLaender.txt)

**Comment by AnneSchueller** [comment]
@JuergenRichter
Könnten Sie evtl. mal eine Blick in die logs werfen, woran es beim Start von Schild3 Version 3.0.53.9 (das ist die aktuelle Version aus dem GitHub) zu einem Fehler kommt?
Auf meinem Arbeitsrechner hatte ich keine Fehlermeldung; allerdings auf meinem privaten Rechner.
Herr Frodermann und Herr Raffenberg haben jeweils ein log hochgeladen.

**Comment by JuergenRichter** [comment]
@AnneSchueller
ich kann das Problem (Zugriffsverletzung in 3.0.53.9) nicht reproduzieren, habe aber an der betreffenden Stelle (laut Log) mal eine „Sicherung“ eingebaut. Ich habe eine aktuelle Programmdatei auf unseren Server gelegt (nicht Github). Könnten Sie diese mal auf Ihrem privaten Rechner (da wo der Fehler auftritt) testen?

**Comment by AnneSchueller** [comment]
[log.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10556940/log.txt)

**Comment by JuergenRichter** [comment]
Das Problem hängt mit der Bildschirmauflösung zusammen, an meinem "normalen" Monitor (1980 x 1080) tritt das Problem nicht auf, wenn ich das Programm aber auf einem Monitor 3840 x 2160 starte, kann ich es reproduzieren. Zumindest weiß ich jetzt, wo zu suchen ist.

**Comment by JuergenRichter** [comment]
Frage: Läuft das Programm denn nach der Fehlermeldung weiter oder stürzt es komplett ab. Bei mir kommt zwar die Meldung, danach kann man aber mit dem Programm arbeiten.

**Comment by Raffenberg** [comment]
Bei mir läuft das Programm nicht weiter. Ich nutze Schild2 momentan in Hyper-V, wo man beim start die Monitorauflösung wählen kann. In dieser Umgebung kommt bei höheren Auflösungen keine Fehlermeldung. An den realen PCs ist die Auflösung allerdings auch immer höher als FullHD.

**Comment by JuergenRichter** [comment]
Ich glaube, ich habe das Problem gefunden und behoben. Zumindest tritt es nun in einer Umgebung, wo ich es vorher reproduzieren konnte, nicht mehr auf. Ich werde heute Nachmittag mal eine Testversion bereitstellen, bitte damit mal ausprobieren.

**Comment by FPfotenhauer** [comment]
Schild3-Installer liegt in der Cloud.

**Comment by FrodBRA** [comment]
Die Version, 3.0.54.9, lässt sich installieren und SchILD startet nun wieder korrekt. 

[Hinweis: Ich nutze 4k als Hauptmonitor und FullHD auf dem zweiten daneben.]
