### ISSUE TITLE
Katalogdarstellung (optische Anpassung)

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#48]
Ruft man den Karteikartenreiter "Kataloge" auf, wird sofort über die gesamte Bildschirmbreite der Katalog der Staatsangehörigkeit angezeigt. Hier sollte ein Auswahlfenster vorgeschaltet sein. 
![Katalogdarstellung](https://user-images.githubusercontent.com/62895389/101606991-56794380-3a04-11eb-9e4d-9b36b654488d.JPG)
Alle Kataloge nehmen die gesemte Bildschirmbreite ein. Die Katalogfenster sollten deutlich kleiner dargestellt werden bzw. vom Benutzer einstellbar sein.

**Comment by FPfotenhauer** [comment]
Ich weiß nicht, ob das geht. Frage ist auch, ob wir momentan nicht genug Baustellen haben.
Gesagt und angefragt habe ich dieses Thema schon oft.

**Comment by FPfotenhauer** [comment]
Was ist bitte mit Auswahlfenster gemeint?
Das Konzept sieht ja gerade vor, dass möglichst wenig modale Fenster genutzt werden.

**Comment by WLey-49** [comment]
Frank, du hast Recht. Ein zusätzliches Auswahlfenster mit Anklickmöglichkeiten ist schlecht. Mich stört nur die "Breite" der Darstellung, bei der man über eine ganze Seite "lesen" muss. Hier würde ein kleinerer Fensterbereich alles besser lesbar machen.

**Comment by WLey-49** [comment]
Wir können das Thema später ggf. noch einmal aufgreifen.

**Comment by JuergenRichter** [comment]
In Version 3.0.8 wird sich das Programm die vom Benutzer eingestellten Spaltenbreiten "merken", dann braucht man die Einstellung nur einmal zu machen (pro Katalog)
