### ISSUE TITLE
SVWS Server erstellt kein Zertifikat und migriert keine Datenbank

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#480]
Ich installiere wie gewohnt den SVWS-Server. Eine Fehlermeldung gibt den Hinweis, dass die Zertifikatsdatei nicht erstellt werden kann. Eine Migration der angegebenen Datenbank findet offensichtlich nicht statt.

Wissenswertes:
- Ich installiere auf dem Client in der Schule. Dieser gehört zur Domäne Verwaltung.local
- Auf unserem Server läuft eine MariaDB mit UntisMultiuser auf Port 3306, weshaln ich Port 3307 nutze
- Gruppenrichtlinien verschieben die meisten Erdner aus dem Ordner Users\Benutzername in einen Ordner auf dem Server, auf den der User zugriff hatt, damit die Dateien nachts gesichert werden können
- Vor der gezeigten Installation wurde der SVWS-Server deinstalliert, der SVWS-Ordner unter ProgramData gelöscht und die delete_services.bat ausgeführt
- Mit DBeaver kann auf localhost kein Zugriff erfolgen
- Mit dem Browser kann auf localhost kein Zugriff erfolgen
- Anbei die Logs und ein Video der Installation
- SVWS-Server 0.5.1

[Logs und Video.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10554284/Logs.und.Video.zip)

**Comment by Raffenberg** [comment]
Bei dem "Computernamen" handelt es sich auch nicht um den Namen des Computers, sondern der Domäne.

**Comment by FPfotenhauer** [comment]
Wir sollten mal einen Teamviewer Termin machen. Wir wissen nicht genau wie dieser Name in das Zertifikat kommt. Bei den anderen Angaben fangen wir das schon ab.

**Comment by FPfotenhauer** [comment]
Interessant zu wissen wäre in der Zwischenzeit, ob das auf dem DomainController auch passiert. (Ich vermute aber ja.)
Die Installation auf einem Arbeitsplatz macht hier ja gar keinen Sinn, auch wenn der Fehler interessant ist.

**Comment by FPfotenhauer** [comment]
Können wir die Installer-Logs zu dem Fehler auch einmal bekommen?

**Comment by FPfotenhauer** [comment]
Ich habe garade den SVWS-Installer ausgetausch. Versionsnummer ist noch gleich.
Bitt einmal testen, wir haben die Fehler wahrscheinlich gefunden.

**Comment by FPfotenhauer** [comment]
Ich schließe das mal. Bei Bedarf wieder öffnen.
