### ISSUE TITLE
Speicherung der Spaltenbreiten von Grid-Komponenten

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#481]
Beim Beenden des Programmes wir für die "Grid-Komponenten" (zur Tabellendarstellung) die Breite der einzelnen Spalten gespeichert. Zur Zeit wird dabei die Breite in Pixel genommen. Das führt aber bei folgender Konstellation  zu Problemen:
-Das Programm wird auf einem Monitor mit "normaler" Auflösung gestartet
-Anschließend wird das Hauptfenster z.B. auf einen Monitor mit hoher Auflösung gezogen und die Spaltenbreiten angepasst
-Wenn das Programm beendet wird, werden die Spaltenbreiten als Pixel-Werte gespeichert, da mit hoher Auflösung gearbeitet wird, sind das dann auch entsprechend hohe Werte
-Beim nächsten Start (wieder auf einem Monitor mit geringer Auflösung) werden die Spalten dort viel zu breit angezeigt (da ja die hohen Werte geladen werden)

Insgesamt ist also das Speichern der Pixel-Werte bei dieser Konstellation ungünstig. Ich würde daher vorschlagen, dass die Werte in Zukunft als Prozentwerte (in Bezug auf die Breite der betreffenden Grid-Komponente) gespeichert werden. Beim Verschieben auf einen anderen Monitor (dafür gibt es ein Ereignis, damit das Programm das auch "merkt") müsste dann aber die Berechnung der Spaltenbreite erneut erfolgen. Eine Reaktion auf den Monitorwechsle ist aber sowieso notwendig, damit die Zeilen- und Texthöhe in den der "Backstage-Menüs" (z.B. Kataloge) angepasst wird.

**Comment by FPfotenhauer** [comment]
Kann man das mal an einer Komponente testen?

**Comment by JuergenRichter** [comment]
Ist noch nicht umgesetzt, werde ich aber kurzfristig mal machen.

**Comment by JuergenRichter** [comment]
Eine andere Option wäre es, die Spaltenbreiten immer normiert auf einen Standard-DPI-Wert von 96 zu speichern und diesen dann bei der Darstellung auf den tatsächlichen DPI-Wert umzurechnen.

**Comment by JuergenRichter** [comment]
Das Speichern mit dem normierten Wert scheint bei ersten Test ganz gut zu funktionieren. Ich werde das aber weiter beobachten.

**Comment by AnneSchueller** [comment]
Den Status Quo können wir am Freitag mal mit verschiedenen Konstellationen testen.

**Comment by JuergenRichter** [comment]
Durch die Deaktivierung der "dpi-awareness" in der neuen Version sollte das Problem eigentlich behoben sein. Ich schließe das Issue daher mal, falls es weiterhin auftreten sollte, bitte wieder öffnen.
