### ISSUE TITLE
Schuljahr korrekt? fehlt

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#482]
Ich habe gerade mit der heute veröffentlichten Version eine Datenbank aus dem ersten Halbjahr komplett neu migriert. Ich vermisste die Erinnerung "Schuljahr korrekt?", die in Schild2 oben rechts immer eingeblendet wird.

**Comment by AnneSchueller** [comment]
Das kann ich bestätigen. Auch wenn unter Einstellungen -> globale Einstellungen die Auswahl "Warnung Schuljahr korrekt" ausgewählt ist, fehlt die Anzeige.

**Comment by JuergenRichter** [comment]
Das tritt nur auf, wenn man den "Schnellfilter SchILD2" aktiviert hat, wenn das Häkchen deaktiviert ist, wird die neue Schnellfilterung verwendet, da wird das als "Verkehrszeichen" angezeigt. Wir müssen mal schauen, wo wir das beim Schnellfilter SchILD2 anzeigen lassen können,
![image](https://user-images.githubusercontent.com/61280188/216926895-86005a57-2d97-43a3-94ef-931881409867.png)
