### ISSUE TITLE
Noten fehlen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#483]
Ich habe die aktuelle Version (Schild + Server) vom heutigen Tage komplett neu migriert (MSSQL-->Maria). Leider fehlen nach der Migration vereinzelte Noten! Ich meine, dass das vor ein paar Monaten schon einmal der Fall war.
![Schildfehler3000](https://user-images.githubusercontent.com/78501680/216782040-096e95b8-1ba9-4d59-91b2-7dd3a4045fc0.jpg)

**Comment by AnneSchueller** [comment]
Hallo Jens,
Ich kann das nicht reproduzieren. Allerdings migriere ich von Access nach MariaDB.
Sind das immer die gleichen Fächer?
Vielleicht hilft die log-Datei hier weiter? Könntest du diese  mal anhängen? (im Ordner C:\ProgramData\SVWS-Server\logs)

**Comment by JeVaske** [comment]
Bei der ersten Installation ist es mir aufgefallen, nachdem ich den Abschnittswechsel durchgeführt hatte. Ich wollte ausschließen, dass es am Abschnittswechsel liegt und habe erneut alles restlos deinstalliert und dann neu installiert. Es liegt an der Migration. Ein einheitliches Muster sehe ich nicht. Beim ersten Schüler der Klasse 5c fehlen die Noten der Fächer D,E,Ku,M,PK, beim zweiten Schüler kommt Bio dazu, Er hat aber die Note im Fach E. Dem 5. Schüler derselben Klasse fehlen Bio,D,E,KU,M. Dem 6. Schüler fehlen nur die Niten der Fächer Bio,KU,PK,PP
[2023_02_04.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10610308/2023_02_04.request.log)
[keystore.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10610309/keystore.log)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10610310/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10610311/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10610312/svws_server_service.wrapper.log)

**Comment by FPfotenhauer** [comment]
Es fehlen die Noten mit Tendenz.
Die Logs nützen da nichts, weil es an der Migration liegt.
Hatte die Access Db auch Tendenznoten?

**Comment by FPfotenhauer** [comment]
Das passiert auch bei Access Datenbanken und muss dringend behoben werden.

**Comment by Raffenberg** [comment]
Was würde bei der Migration passieren, wenn ein Primärschlüssel in der AccessDB fehlen würde und z.B. doppelt besetzt wäre. Wäre das Phänomen dann ggf.  das gleiche? Die User bemerken fehlende Primärschlüssel ja nicht immer...

**Comment by FPfotenhauer** [comment]
Der PK bezieht sich ja nur auf die ID des Leistungsdatensatzes, wieso bei dessen Fehlen nur die Tendenznoten nicht migriert werden sollten, erschließt sich mir nicht.

**Comment by FPfotenhauer** [comment]
Die Tendenznoten kommen in der ZielDB an, sie werden aber in Schild3 nicht angezeigt, weil die Option "Tendennoten in der Sek1 zulassen" nicht aktiv ist. Diese Option kann leider nicht mitmigriert werden.
Allerdings wäre es gut, wenn Schild3 die Noten anzeigen könnte, auch wenn die Option deaktiviert ist.

**Comment by FPfotenhauer** [comment]
Geht das, das die Noten angezeigt werden?

**Comment by JuergenRichter** [comment]
Ja, das geht. Wir brauchen dann nur zwei Datenquellen, einmal für die Anzeige (mit allen Noten), einmal für die Auswahl (mit den Noten, die sich durch die Einstellung ergeben, z.B. Tendenznote in Sek1)

**Comment by JuergenRichter** [comment]
Ist nun umgesetzt.
