### ISSUE TITLE
Anmeldung über Client funktioniert nicht

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#484]
SVWS-Version: 0.5.2
Schild3-Version 0.0.5.7

Schild3 lässt sich nun wieder problemlos installieren und öffnen. Schülerdaten und co sind vorhanden. Verbindung zum Server ist vorhanden. 
Nach Eingabe von localhost im Browser öffnet sich das gewohnte Anmeldefenster vom SVWS-Server.

Ich kann mich aber nicht anmelden.

[2023_02_04.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10609470/2023_02_04.request.log)
[keystore.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10609471/keystore.log)
[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10609472/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10609473/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10609474/svws_server_service.wrapper.log)

**Comment by FPfotenhauer** [comment]
Ist  ein Fehler im Client. Ist schon behoben.

**Comment by AnneSchueller** [comment]
Funktioniert bei mir immer noch nicht. Muss ich noch irgendwas löschen? Ich habe nur vor der Neuinstallation die delete_services.bat ausgeführt und sdbcfg-Dateien aus dem Arbeitsverzeichnis gelöscht.
SVWS-Version vom 07.02.23

**Comment by FPfotenhauer** [comment]
Hat irgendjemand gesagt, das da ein neuer Client im Installer ist?
