### ISSUE TITLE
Fehlermeldung bei Server nicht erreichbar

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#485]
Es kommt folgende Fehlermeldnung, wenn der SVWS-Server nicht erreichbar ist.

![SNAG_2023_02_05_13 40 56](https://user-images.githubusercontent.com/34127980/216819297-2ce0c3a9-b900-4e55-8306-30ecde5246d0.png)

Es sollte aber eine sprechende Nachricht erscheinen, das war auch schon einmal so.
Vermutlich muss die Prüfung nach vorne "geschoben" werden.

**Comment by JuergenRichter** [comment]
Behoben
