### ISSUE TITLE
Gesamtprüfung und Erstellung Dateien für ASDPC - Fehlermeldung

### ISSUE THREAD

**Issue by TorstenEngelke** [SVWS-NRW/Schild3-BetaTest#486]
Die Durchführung einer Gesamtprüfung führt zu einer Fehlermeldung. Auch das Erstellen der Dateien für ASDPC (sim.txt, lid.txt, uvd.txt) führen zu einer Fehlermeldung und können nicht abgespeichert werden.

**Comment by JuergenRichter** [comment]
Behoben
