### ISSUE TITLE
Fehler beim Schuljahreswechsel

### ISSUE THREAD

**Issue by NBerkenheide** [SVWS-NRW/Schild3-BetaTest#487]
Ich möchte einen Schuljahreswechsel durchführen.
Daraufhin erscheint immer die Fehlermeldung:
Lookup-Information für Feld 'OrganisationSForm' ist unvollständig.

**Comment by JuergenRichter** [comment]
Wie wird das konkret ausgeführt?

**Comment by NBerkenheide** [comment]
![Schuljahreswechsel-n](https://user-images.githubusercontent.com/124572460/216974123-ede002a2-44a1-4ca3-8b78-19291ce57c56.png)

**Comment by NBerkenheide** [comment]
Es ist dabei egal, was ich anklicke. Es erscheint immer die Fehlermeldung.
Ein Halbjahreswechsel funktioniert.

**Comment by JuergenRichter** [comment]
Behoben
