### ISSUE TITLE
Testinstallation auf Windows Server 2012 scheitert

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#488]
Beim Versuch der Installation des SVWS-Servers auf einem Windows-Server 2012 R2 kommt unmittelbar die Fehlermeldung "Dieses Programm unterstützt die auf Ihrem Computer installierte Windows-Version nicht".

Windows Server 2012 R2 erhält noch Sicherheitsupdates bis zum 10. Oktober 2023.

**Comment by FPfotenhauer** [comment]
Ist das ein 32 BiT?
Ehrlich gesagt, würde ich den dann schon mal gerne aus den Requierements herausnehmen.

**Comment by FPfotenhauer** [comment]
Wir unterstützen erst ab Version 10:


6.0.6000 | Windows Vista
-- | --
6.0.6001 | Windows Vista with Service Pack 1or Windows Server 2008
6.1.7600 | Windows 7or Windows Server 2008 R2
6.1.7601 | Windows 7 with Service Pack 1or Windows Server 2008 R2 with Service Pack 1
6.2.9200 | Windows 8or Windows Server 2012
6.3.9200 | Windows 8.1or Windows Server 2012 R2
6.3.9600 | Windows 8.1 with Update 1
10.0.10240 | Windows 10 Version 1507
10.0.10586 | Windows 10 Version 1511 (November Update)
10.0.14393 | Windows 10 Version 1607 (Anniversary Update)or Windows Server 2016
10.0.15063 | Windows 10 Version 1703 (Creators Update)
10.0.16299 | Windows 10 Version 1709 (Fall Creators Update)
10.0.17134 | Windows 10 Version 1803 (April 2018 Update)
10.0.17763 | Windows 10 Version 1809 (October 2018 Update)or Windows Server 2019
10.0.18362 | Windows 10 Version 1903 (May 2019 Update)
10.0.18363 | Windows 10 Version 1909 (November 2019 Update)
10.0.19041 | Windows 10 Version 2004 (May 2020 Update)
10.0.19042 | Windows 10 Version 20H2 (October 2020 Update)
10.0.19043 | Windows 10 Version 21H1 (May 2021 Update)
10.0.19044 | Windows 10 Version 21H2 (November 2021 Update)
10.0.20348 | Windows Server 2022 Version 21H2
10.0.22000 | Windows 11 Version 21H2 (N/A)

**Comment by Raffenberg** [comment]
Ich habe das Issue nochmals kurz geöffnet.

Nur zur Ergänzung für Mitleser. Windows Server 2016 und 2019 basieren auf Windows 10. Dort klappt dann die Installation vom SVWS-Server. Die beiden Betriebssysteme fehlen oben in der Liste. Windows Server 2016 läuft auch erst 2027 aus. Das dürften noch viele Schulen benutzen.

Unser Windows Server 2022 kommt im März. Puh ;-)
