### ISSUE TITLE
sdbcfg-Ordner

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#489]
Bei der Installation von Schild3 wird ein sdbcfg-Ordner angelegt. Das sollte nicht mehr geschehen.

Beim erstellen der Konfigurationsdatei wird ein Unterverzeichnis sdbcfg im Arbeitsverzeichnis von Schild vorausdgesetzt. Dies wird beim Anlegen des Arbeitsverzeichnisses nicht angelegt, so dass es beim Speicherversuch der sdbcfg-Datei zu einer Fehlermeldung kommt. Entweder sollte der Unterordner sofort oder spätestens beim Absoeichern der sdbcfg-Datei angelegt werden.

**Comment by JuergenRichter** [comment]
Wir machen das Setup aber nicht, das muss an Herr Pfotenhauer gehen.

**Comment by FPfotenhauer** [comment]
Das habe ich am Wochenende doch korrigiert.
Das hat bei mir einwandfrei geklappt.
In dem Installer vorher war das noch so. Bitte mit dem aktuelle nochmal testen. Der war von Sonntag-Mittag.

**Comment by Raffenberg** [comment]
Sorry. Kann sein, dass ich nicht genau genug hingesehen habe. Ich schaue mir das später nochmal an.
