### ISSUE TITLE
Exportinformation

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#49]
Wenn man über Verwaltung den Punkt Export aufruft, hat man keine Informationen über die Exportdaten, genauer über die Schüler, deren Daten exportiert werden. man kann natürlich auf Schüler zurückschalten, um zu sehen, welche Daten gefiltert und exportiert werden.
Kann eine entsprechende Information über den gewählten Filter nicht angezeigt werden? Platz genug ist da:
![Exportinformation](https://user-images.githubusercontent.com/62895389/101607871-5cbbef80-3a05-11eb-9860-1d1454b6624c.JPG)

**Comment by JuergenRichter** [comment]
Die Exporte haben je nach gewählter "Export-Option" unterschiedlichen Inhalt. So wird z.B. bei Verwendung der Schnittstelle SchILD-NRW immer die aktuell ausgewählte Schülermenge berücksichtigt, bei anderen Exporten nur eine bestimmte Teilgruppe (unabhängig von der aktuellen Auswahl), z.B. beim Abiturexport. Die Frage ist nun:
1) Sollen immer konkret die Namen der SuS angezeigt werden, die berücksichtigt werden?
2) Oder soll nur eine allgemeine Beschreibung ausgegeben werden, z.B. "Export der aktuelle ausgewählten SuS", "Auswahl der Abiturdaten für das Jahr XY"
Was ist mit "Nicht-Schülerdaten"?

**Comment by WLey-49** [comment]
Ich sehe, dass dies schwierig ist. Bei einer Schülermenge wäre es hilfreich, wenn zumindest eine Beschreibung der ausgewählten Menge vorliegen würde. Vielleicht hat hier jemand eine viel bessere Idee.

**Comment by JuergenRichter** [comment]
Wird in Version 3.0.9 angegangen

**Comment by FPfotenhauer** [comment]
Gibt es hier eine Entwicklung?

**Comment by FPfotenhauer** [comment]
Ist in der 3.0.17 in den Exporten, wo es um ausgewählte Gruppen geht, mit angezeigt.
