### ISSUE TITLE
Diskussion: Namensgebung sdbcfg

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#490]
Ich weiß gar nicht, wie lange es gedauert hat, bis mir der Zungenbrecher überhaupt eingefallen ist und dann flott von den Lippen ging. Ich habe wahrgenommen, dass es vielen anderen ebenso geht, wie mir. Deshalb hier ein Vorschlag, bevor wir SchILD-NRW 3 auf den Markt bringen:

Wäre es nicht viel griffiger und sprechender, wenn wir die Dateiendung .con nennen würden und den entsprechenden Ordner "Connection-Dateien" nennen würden, um den fachberatern und Usern das gleiche Leid zu ersparen? Eine kurze Recherche zeigte mir, das die Dateiendung anscheinend nicht gebräuchlich und damit frei zu sein scheint.

**Comment by AnneSchueller** [comment]
Ich würde eine Namensänderung ebenfalls begrüßen.

**Comment by JuergenRichter** [comment]
Soll ich das so umsetzen?

**Comment by AnneSchueller** [comment]
@Raffenberg ; @FPfotenhauer 
Ich schlage vor, dass wir das am Montag nochmal im Team besprechen, sodass wir dann eine finale Rückmeldung geben.

**Comment by Raffenberg** [comment]
Hallo Herr Richter,
bitte setzen Sie das folgendermaßen um:

Dateiendung ".sdbcfg" wird zu ".con"

Ordner "sdbcfg" wird zu "Connection-Files"

**Comment by FPfotenhauer** [comment]
Ich mache das, wenn ich die entsprechenden Versionen habe.

**Comment by JuergenRichter** [comment]
Ist in den Programmen Schild3.exe, MigrateDB.exe und Schild_DBConfig.exe umgesetzt

**Comment by FPfotenhauer** [comment]
Installer steht zur Verfügung, bei mir hat alles geklappt.
Schild3 muss natürlich dann einmal komplett neu installiert werden.
