### ISSUE TITLE
Klick auf das Filtersymbol lässt Auswahlkästchen verschwinden

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#491]
https://user-images.githubusercontent.com/48889965/216983155-f6a63c04-c375-4309-88f8-ea4bde72be0a.mp4

Wenn ich auf das Filtersymbol innerhalb der Schülerauswahl klicke, verschwindet der untere Teil des Auswahlberechs und kehrt bis zum Neustart auch nicht wieder (s. Video). Das bleibt dann für alle Reiter so.

Systemschriftgröße 125% (das ist bei unseren Sekretärinnen und Abteilungsleitungen eigentlich der Standard), Monitorauflösung 1920x1080

**Comment by JuergenRichter** [comment]
Behoben
