### ISSUE TITLE
Aktuelles Halbjahr - Teilleistungen: Doppelklick wirkt sich auf andere Spalten aus

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#493]
Wenn ich zunächst in eine Zelle mit Auswahlfeld (Häkchenfeld) klicke, so dass dieses Unterlegt erscheint und dann auf das Plussymbol klicke, so erscheinen die Teilleistungen. Wenn ich zu schnell klicke (Doppelklick), so wird das Asuwahlfeld aktiviert/deaktiviert (s. Video). Das wirkt ein wenig gestellt, ist mir jedoch mehrfach beim Arbeiten mit den Daten passiert, ohne dass ich dies zunächst realisiert habe. Da alle Auswahlfelder recht sensibel sind, ist das nicht ungefährlich.

https://user-images.githubusercontent.com/48889965/216985806-7deaa14c-224e-4510-a569-26891a1266e2.mp4

**Comment by JuergenRichter** [comment]
behoben
