### ISSUE TITLE
Schriftgröße 125%

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#494]
Bei den unterschiedlichen Monitorgrößen in Kombination mit deren Auflösung empfiehlt Windows 10 automatisch bestimmte Skalierungsstufen, damit die Schriften nicht zu klein wirken. Bei einem kleinen Monitor mit hoher Auflösung wird z.B. die Skalierung 150% empfohlen, damit alles lesbar bleibt. Bei großen Arbeitsplatzmonitoren liegt die Empfehlung in der Regel bei 100% oder 125% (getestet mit unseren 22", 24" und 27" Monitoren in FullHD, 2560x1440). Bei einem 32" UltraHD-Monitor sind es auch gerne 150% , 3840x2160 Pixel).

Insbesondere in den Ribbons werden die Schaltflächen nicht skaliert. Hier wird dann Schrift an den Buttons und in der Beschriftungszeile abgeschnitten. Aber auch die Überschriften der Felder werden teilweise unten abgeschnitten, teilweise nicht. Teile des Buchstabens g verschwinden, oder nicht. Die Schriften unter Verwaltung und Kataloge überlappen schon bei 100% stark. Auch hier wird der Abstand bei größeren Einstellungen nicht korrigiert.

125%
![Abgeschnittene Buttons](https://user-images.githubusercontent.com/48889965/216990483-e5bd1b90-2ba1-4d5e-9c11-3423472be25d.png)

![abgeschnittene Buchstaben](https://user-images.githubusercontent.com/48889965/216993601-9598fc8e-f054-495c-af0a-076d5b756ffc.png)

Überlappungen auch bei 100%
![Überlappende Zeilen](https://user-images.githubusercontent.com/48889965/216991063-efcf3750-9f64-4478-8d6c-a3d5fe8a9a26.png)

**Comment by Raffenberg** [comment]
Ursprünglich habe ich Schriftgröße geschrieben. Die Funktion heißt aber in Windows 10 und 11 "Skalierung"

**Comment by JuergenRichter** [comment]
Behoben, die Höhe der Label-Komponente wird jetzt programmtechnisch angepasst.
