### ISSUE TITLE
Aktivieren von Katalogen und dann Reportverwaltung verändert die Schülerauswahl

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#495]
Wenn man zuerst den Reiter Kataloge aktiviert und dann den Reiter Reportverwaltung, dann wird die Schüleruaswahl schmal (nur der bereich der Klassenfilter, s. Video)

https://user-images.githubusercontent.com/48889965/216994332-bb5c9884-7418-4493-b905-5b269aac95dd.mp4

**Comment by JuergenRichter** [comment]
Behoben
