### ISSUE TITLE
Unbekannte Kompetenzgruppen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#497]
Wofür stehen die Kompetenzgruppen alles und keine?

![Unbekannte Kompetenzgruppen](https://user-images.githubusercontent.com/48889965/217200133-1b713117-1576-4752-8b6d-936458d56fb3.png)

**Comment by FPfotenhauer** [comment]
Kann sein, dass das unsere neuen sind.
Die Kennt Schild3 noch nicht. 
Kann man sich im Client anschauen

**Comment by FPfotenhauer** [comment]
Wollen wir die in Schild3 ergänzen?

**Comment by JuergenRichter** [comment]
Was sollen die bedeuten?

**Comment by FPfotenhauer** [comment]
Vielleicht schauen Sie einmal in den Client, wenn ich eine neue Version gemacht habe, da sind alle aufgeführt.

**Comment by FPfotenhauer** [comment]
Alle Einträge mit einer negativen ID sind Pseudokompentenzen, die nicht dargestellt werden sollen.
Bitte ignorieren. Wir werden die aus der API auch entfernen, aber Schild3 geht wahrscheinlich auf die DB.

**Comment by JuergenRichter** [comment]
Ich stelle das auch auf API-Aufruf um

**Comment by JuergenRichter** [comment]
Noch ein Hinweis: Die Felder "splate" und "zeile" beiden Kompetenzgruppen können entfernt werden. Werden nicht mehr benötigt

**Comment by JuergenRichter** [comment]
Ist auf API-Aufrufe umgesetzt (Kompetenzen und Kompetenzgruppen)

**Comment by FrodBRA** [comment]
Ich weiß nicht, was dies für das Issue bedeutet, aber "keine" und "admin" sind weiterhin in SchILD3 gelistet (3.0.71.9).

@Raffenberg

**Comment by FPfotenhauer** [comment]
Ist in der 3.0.78 auch immernoch zu sehen.

**Comment by AnneSchueller** [comment]
@JuergenRichter 
Hier nochmal eine kurze Erinnerung das "keine" und "admin" aus der Benutzerverwaltung entfernt werden soll.

**Comment by JuergenRichter** [comment]
Werden jetzt entfernt
