### ISSUE TITLE
Spaltenbeschriftung SchulnrEigner fehlerhaft

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#5]
Ausgangslage: SVWS Server 0.0.30 installiert und damit bestehende Schild 2.0 von MS-SQL nach MS-SQL migriert. Schild 3.0.4.3 installiert OHNE Migration. Mit DB-Config-Tool sdbcfg erzeugt und SchILD gestartet.

Fehler: Nach der Anmeldung an Schild kommt die Meldung, dass die Spalte SchulnrEigner nicht gefunden wird.

Ursache: Die Sortierung der SVWS-Server-DB ist Latin1_General_Bin2_UTF und die Spalte ist dort mit Schul**N**rEigner beschriftet. Aufgrund der fehlerhaften Groß- und Kleinschreibung wird die Spalte nicht gefunden.

**Comment by FPfotenhauer** [comment]
![SNAG_2020_11_25_15 14 43](https://user-images.githubusercontent.com/34127980/100238893-05ac1a00-2f31-11eb-909b-f287e0daebe4.png)

**Comment by FPfotenhauer** [comment]
Unter MariaDB auf einem Linux-Server kommt folgender Fehler:

![SNAG_2020_12_05_18 00 37](https://user-images.githubusercontent.com/34127980/101258618-f04ea100-3723-11eb-8213-63032ee26b9e.png)

Die Tabelle heißt "K_FahrschuelerArt"

**Comment by JuergenRichter** [comment]
In 3.0.7 behoben
