### ISSUE TITLE
Update Server

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#50]
Kann die Update-Funktion nicht aktiviert werden? Dann fällt es leichter, auf einem neuen Stand zu bleiben. (Ich weiß, wir sind noch im BETA-Status) Wahrscheinlich wird es am Anfang doch eine Übergangszeit von Schild 2.0 zu Schild 3.0 geben und daher müsste es auch verschiedene Updatedateien geben.

**Comment by FPfotenhauer** [comment]
Wenn mir jemand ein vernünftiges Konzept für das Update-Deployment schreibt, dann kann man das sicherlich wieder aktivieren.
Momentan kann ich dies nicht auch noch für Schild3.0 übernehmen, weil es einfach für mich nochmals Mehraufwand bedeutet.

Ein Update von Schild2.0 auf 3.0 muss IMMER manuell ausgeführt werden. Das ist im Grunde ja auch kein Update, sondern eine Neuinstallation.

**Comment by Kluesenerm** [comment]
Hallo Frank,
ich dachte, dass es nicht so kompliziert ist. Ich wollte nur vorschlagen, dass die aus Schild 2.0 vorhandene Update-Funktion auch in Schild 3.0 schon gepflegt werden kann.

**Comment by FPfotenhauer** [comment]
Ich muss jedesmal einen Installer bauen. Die Pakete nach IT.NRW hochladen. Die INF-dateien anpassen und muss aufpassen, dass mir die Pakete auf GITHub nicht zu groß werden, weil wir da im Speicherplatz begrenzt sind.

Das möchte ich in der Beta-Test-Phase bitte nicht machen müssen...
