### ISSUE TITLE
Bereich "Aktueller Schüler" ercheint

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#500]
Wenn ich Schild starte (Skalierungsfaktor 100%), sehe ich keinen Bereich ""aktueller Schüler". Wenn ich filtere, erscheint dieser plötzlich. Starte ich Schild mit einem Skalierungsfaktor von 125%, ist der Bereich sofort sichtbar.

https://user-images.githubusercontent.com/48889965/217204859-22290bd8-e914-4139-bb8d-1076c65ffa78.mp4

**Comment by JuergenRichter** [comment]
Der Bereich wird jetzt immer angezeigt
