### ISSUE TITLE
Keine Gliederung wählbar, Gliederungsbereich zu breit

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#501]
Unter Verwaltung möchte ich eine Gliederung hinzufügen. In der Auswahl wird mir keine Gliederung angeboten.
Das Fenster hat sehr lange horizontale Scrollbalken, so dass der Bereich bei Auswahl oft nach rechts verspringt und die linke Spalte nicht mehr sichtbar ist. Vorschlag: Scrollbalken entfernen und die Ansicht passgenau machen.

https://user-images.githubusercontent.com/48889965/217205450-c4478db8-5b9b-4225-8d7c-8b4c99689a0b.mp4

**Comment by JuergenRichter** [comment]
Behoben
