### ISSUE TITLE
Akt. Halbjahr Klassen und Klassenleitung werden nicht angezeigt

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#502]
Die Klassen, Klassenleitungen und stv. Klassenleitungen vergangener Halbjahre werden nicht angezeigt. In der Datenbank scheinen Sie vorhanden zu sein. Es können ebenso keine Klassenleitungen und stv. Klassenleitungen dort hinterlegt werden, so dass ein Eingriff oder eine Korrektur unmöglich sind. Es fehlt das Ausklappzeichen rechts.

Wofür stehen eigentlich die Sternchen neben den Feldüberschriften?

Die "herrenlose" Nummer sollte vielleicht die Beschriftung "Lernabschnitts-ID" erhalten.

https://user-images.githubusercontent.com/48889965/217484592-1109b6c5-a8c8-4ac3-ae8c-ac39ea168cd7.mp4

![SchuelerLernabschnittsdaten Feldinhalte fehlen](https://user-images.githubusercontent.com/48889965/217484866-19de932c-4dbc-4d66-ba49-f98b7f902470.png)

**Comment by AnneSchueller** [comment]
In welcher Tabelle wird denn der ehemalige Klassenlehrer gespeichert?
In der Tabelle Klassenlehrer werden die Klassenlehrer der aktuellen KlassenID aus der Tabelle Klassen zugeordnet. Also werden hier nur die aktuellen Klassenlehrer der jeweiligen Klassen gespeichert.

**Comment by JuergenRichter** [comment]
Das ist jetzt etwas komplizierter:
-In der Tabelle SchulerLernabschnittsdaten steht die "Klassen_ID" des betreffenden Abschnitts, 
-Die zugehörige Klassenbezeichnung ist dann in der Tabelle "Klassen" zu finden
-Dort ist auch ein Feld "Schuljahresabschnitts_ID", welches wiederum auf die Tabelle "Schuljahresabschnitte" verweist (wo das Jahr und der Abschnittsteht)
-Wer wann in welcher Klasse in der Klassenleitung war, wird in der Tabelle "Klassenlehrer" verwaltet. Dort wird wieder über "Klassen_ID" auf die Tabelle "Klassen" verwiesen, dort kann man über "Schuljahresabschnitts_ID" das Schuljahr (aus Schuljahresabschnitte) ermitteln

Zu prüfen wäre also in der Datenbank, wie vollständig die Tabelle "Klassenlehrer" ist. Ich habe hier eine Gesamtschuldatenbank mit 2989 Zeilen in der Tabelle "Klassen" gibt, aber nur 118 Zeilen in der tabelle "Klassenlehrer". Ich vermute, dass bei der Migration nur aktuelle Klassenleitungen übernommen wurden.

Eine Änderung der Klassenleitung bei den SuS ist nicht möglich, da es keine "individuellen" Felder mehr in der Tabelle "Schuelerlernabschnittdaten" mehr gibt, das läuft alles über die Berabeitung der Klassen.

Die * bedeuten, dass das Feld statistik-relevant ist

Die ID ist derzeit für Kontrollzwecke da, kommt später wieder weg.

**Comment by JuergenRichter** [comment]
Nachtrag: Die bei den SuS angezeigten Klassenlehrer werden mit den o.a. Angaben "berechnet", stehen also nicht als eigene Felder in der Tabelle "SchuelerLernabschnittsdaten", in der entsprechenden Datenquelle für die Reportausgabe ist das auch so.

**Comment by AnneSchueller** [comment]
> Zu prüfen wäre also in der Datenbank, wie vollständig die Tabelle "Klassenlehrer" ist. Ich habe hier eine Gesamtschuldatenbank mit 2989 Zeilen in der Tabelle "Klassen", es gibt aber nur 118 Zeilen in der Tabelle "Klassenlehrer". Ich vermute, dass bei der Migration nur aktuelle Klassenleitungen übernommen wurden.

Das ist bei mir ebenfalls so. In der Tabelle _Klassenlehrer_ stehen nur die aktuellen KL drin:

Also insgesamt 48 Einträge mit ID 
1 = 5a;
2 = 5b; usw.

Ist das denn so vorgesehen, dass in der Tabelle _Klassenlehrer_ auch die vorangegangenen KL gespeichert werden sollen?

**Comment by JuergenRichter** [comment]
Grundsätzlich geht das natürlich.

**Comment by JuergenRichter** [comment]
Um die "historischen" Daten bei der Migration zu befüllen, müsste man aber die Einträge in der Tabelle SchuelerLernabschnittsdaten auswerten. Da diese aber individuelle Einträge enthalten, dürfte das schwiereig werden, wenn eine Schule z.B. in der Oberstufe für eine "Klasse" (EF, Q1..) bei den SuS unterschiedliche "Klassenlehrer" eingetragen hat (als Mentoren). Wie soll dann entschieden werden, wer in "Klassenlehrer" eingetragen wird. Die Information bei den SuS gehen ja verloren.

**Comment by Raffenberg** [comment]
Verstehe. Dann ist das Datenbanktechnisch konsequent das die Angaben dort nicht mehr nachjustiertvwerden dürfen sondern nur angezeigt werden. Ist das Fazit, dass dann die Migration noch nicht stimmt?

**Comment by JuergenRichter** [comment]
Das will ich nicht sagen, es dürfet halt schwierig sein, die Daten korrekt zu ermitteln.

**Comment by FPfotenhauer** [comment]
Das werden wir durch das neue Design der Tabellen in Kauf nehmen müssen.
Die Historie baut sich dann ja wieder auf.

**Comment by FPfotenhauer** [comment]
Mir hat das keine Ruhe gelassen.
Wir haben seh rwohl in der Klassentabelle eine Historie aufgebaut.
Hier müssten auch Klassenlehrer zugeordnet sein.

**Comment by Raffenberg** [comment]
Wenn ich das richtig interpretiert habe, werden in MariaDB für jeden Schuljahresabschnitt in der Tabelle Klassen sämtliche Klassen angelegt. Meine Tabelle enthält auf diese Weise 1030 Klassen. Ich gehe davon aus, dass diese Information Distinct aus den SchuelerLernabschnittsdaten der Access-Datenbank gewonnen wurden. Daneben gibt es in der MariaDB eine Tabelle Klassenlehrer, die dann ja eigentlich ebenfalls um die 1030 Datensätze enthalten müsste. 

Die Tabelle Klassenlehrer enthält aber nur die Klassenlehrer des aktuellen Abschnitts, da diese anscheinend leicht aus Access ausgelesen werden können. Von den zurückliegenden Abschnitten gibt es ebenfalls sehr wenige Einträge, so dass ich in der Summe auf 51 Eintragungen komme (Wir haben 38 KL und COs. Hinzu kommen ein paar Einträge aus älteren Abschnitten).

Die Zuordnung der Klassenlehrer zu den Klassen ist ungleich schwerer, wenn diese aus den Lernabschnittsdaten gewonnen werden sollen. Diese liegen in der Access-Datenbank dort nur mit den Kürzeln vor. Bei der Migration müsste man ja schauen, welches Kürzel in einer Klasse am häufigsten genannt wird und dieses dann der vergangenen Klasse zuordnen. Anscheinend gibt es hier einen Prozess, der aber nur sehr wenige Einträge generiert.

**Comment by Raffenberg** [comment]
Wie wird denn diese Tabellenstruktur in Schild3 abgebildet? Im Katalog Klassen-/Versetzungstabelle müsste dann ja auch für jeden Abschnitt eine abschnittsabhängige Anzeige aufgebaut werden. Wenn ich das Schuljahr in der Verwaltung ändere, werden mir dort aber immer die gleichen Klassen und Klassenlehrer angezeigt, also unabhängig vom eingestellten Abschnitt. Das müsste dann dort ja ebenfalls abschnittsindividuell angezeigt werden, damit ich Fehleinträge aus vergangenen Halbjahren korrigieren kann.

**Comment by FPfotenhauer** [comment]
Wir haben einen ersten Fehler gefunden. Jetzt kommen viel mehr Klassenlehrer an. Ist aber noch nicht ganz fehlerfrei.

**Comment by JuergenRichter** [comment]
Es gibt jetzt auch bei der Bearbeitung der Klassen die Option, auf ein vergangenes Halbjahr umzuschalten, um dort z.B. die Klassenleitungen einzutragen. das wird dann auch bei den entsprechenden Lernabschnitten der SuS angezeigt.

![image](https://user-images.githubusercontent.com/61280188/217801232-fd1c363e-8301-4565-acf2-7259d1389e23.png)

**Comment by FPfotenhauer** [comment]
Wir sind auch dabei, die HIstorie zu befüllen, das klappt schon ganz gut, ist aber noch nicht perfekt.

**Comment by FPfotenhauer** [comment]
Das sollte mit den aktuellen Versiopnen behoben sein. Bitte wieder öffnen oder neues Issue, wenn nicht.
