### ISSUE TITLE
Klassenlehrer in Lernabschnittsdaten

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#504]
Es wäre aus meiner Sicht praktisch, wenn die Klassenlehrer bei den Lernabschnittsdaten in einer Tabelle dargestellt würden, so wie es nun auch im Klassendialog ist.

Dabei sollte die Sortierung mit 1. und 2. ... angezeit werden, so kann man Klassenlehrer und Stellv. "managen".

**Comment by JuergenRichter** [comment]
Das wird aber nur zur Anzeige sein, die Bearbeitung (jetzt ach für vergangene Abschnitte) erfolgt im Klassenkatalog.

**Comment by JuergenRichter** [comment]
Ist jetzt umgesetzt:

![image](https://user-images.githubusercontent.com/61280188/217815010-ded0af0b-d162-4988-8cde-456557b1efa5.png)
