### ISSUE TITLE
Schulnummer ändern unter Verwaltung

### ISSUE THREAD

**Issue by NBerkenheide** [SVWS-NRW/Schild3-BetaTest#505]
Hallo, 

ich arbeite gerade mit einer Testdatenbank.
Kann es sein, dass unter Verwaltung ->Schule-> Allgemeine Angaben
die Schulnummer nicht ändern lässt?
Ich wollte gerade einmal einen Statistiklauf durchführen und eine existierende Schulnummer auswählen.

**Comment by AnneSchueller** [comment]
Hallo Nils, 
erstmal vielen Dank fürs Testen.

@JuergenRichter : Das Nichteingreifen in die Schulnummer ist so gewollt oder habe ich das falsch im Kopf?

Man könnte die Schulnummer in der Datei schulver im Ordner Schild3->keytabs anpassen. Dazu in der Tabelle DBS einfach die Schulnummer 123456 irgendwo ersetzten. So kann man die Statistikprüfung dennoch erstmal mit Schild3 durchführen.

Ich habe das gerade getestet. Leider kam es zu einer Fehlermeldung. Das Fehlerprotokoll und die anschließend erzeugten Export-Dateien werden nicht abgespeichert.

**Comment by JuergenRichter** [comment]
Zu welcher Fehlermeldung kommt es? 

Ich stelle das mal zur Diskussion: Soll die Schulnr. in SchILD3 änderbar sein?. In Prinzip ist das keine Problem, da sie ja nur in der Tabelle EigeneSchule verwendet wird.

**Comment by FPfotenhauer** [comment]
Schulnummer auf keinen Fall änderbar machen!

**Comment by AnneSchueller** [comment]
Nach dem Klicken auf "Protokolldatei ansehen":
![2023-02-14_081208](https://user-images.githubusercontent.com/79116896/218665214-35dec28b-d644-44e8-afb2-5e01b20fd1ee.png)


Erscheint diese Fehlermeldung:
[Fehlermeldung_Protokollaufruf.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10729720/Fehlermeldung_Protokollaufruf.txt)

**Comment by AnneSchueller** [comment]
Das Fehlerprotokoll ist auch nicht vorhanden im Arbeitsverzeichnis.
Ein weiterer Fehler taucht auf, wenn man auf "Daten exportieren" klickt. Nach dem Bestätigen von "Daten erfolgreich für die Statistik bereitgestellt" erfolgt folgender Fehler:
[Fehlermeldung_Datenexport.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10729763/Fehlermeldung_Datenexport.txt)

**Comment by FPfotenhauer** [comment]
Alle Fachberater können mit DBeaver in die Tabelle EigeneSchule gehen und dort die Schulnummer ändern.
Das sollte machbar sein.

**Comment by JuergenRichter** [comment]
Wegen der Fehlermeldung: Die kommt aus der ASdStatistik.dll. Sind denn auf dem Rechner alle anderen "Statistik-Dlls" registriert?

**Comment by JuergenRichter** [comment]
Vermutlich sind die Dateien vsprin8.ocx und vspdf8.ocx nicht registriert.

**Comment by AnneSchueller** [comment]
Die Dateien sind in dem Ordner C/ASDPC32

**Comment by AnneSchueller** [comment]
"Wegen der Fehlermeldung: Die kommt aus der ASdStatistik.dll. Sind denn auf dem Rechner alle anderen "Statistik-Dlls" registriert?"

Wo kann ich das nachsehen?
