### ISSUE TITLE
Statistik mit Schild3.0

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#508]
[Errorlog.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10732379/Errorlog.txt)

Bei mir funktioniert die Statistik bis zum Aufruf des PDF.
Wenn ich mir das PDF ansehen will stürzt alles ab, auch Schild3.
Wenn ich mir das Errorlog ansehen, vermute ich aber eher einen Fehler in der Statistik.dll.

Wir können in diesem Issue aber mal die Statistik mit Schild3.0 generell durchgehen.
Ich vermute schon, dass einige Daten in der StatistikDB.mdb noch angepasst übertragen werden müssen. Oder?

**Comment by JuergenRichter** [comment]
Eigentlich sollte der Export schon angepasst sein.

**Comment by JuergenRichter** [comment]
Ich vermute ein Problem mit den Dateien vsprint8.ocx und vspdf8.ocx, die m.E. für die PDF-Ausgabe verwendet werden.

**Comment by FPfotenhauer** [comment]
Wenn ich das gleiche in Schild2.0 mache, dann klappt alles.
Auf dem Rechner habe ich die DLLs mit Schild2.0 registiriert.
Macht das einen Unterschied?

**Comment by JuergenRichter** [comment]
Sollte eigentlich nicht so sein. Ich prüfe das mal auf meinem System

**Comment by FPfotenhauer** [comment]
@AnneSchueller und @Raffenberg könntet ihr mal die alte Statistik aus 2022 machen? Also txts erzeugen, in ASDPC32 einlesen und mal schauen, ob es gut aussieht?

**Comment by AnneSchueller** [comment]
Beim Erzeugen der .txt Dateien erhalte ich eine Fehlermeldung.

**Comment by JuergenRichter** [comment]
Ich habe die "Typbibliothek" für die ASDStatistik.dll nochmal neu erstellt. Folgendes fällt auf:
-Der Export der Daten aus SchILD funktioniert einwandfrei
-Wenn dann die DLL aufgerufen wird, werden von der DLL bei der Gesamtprüfung jede Menge "silent exceptions" der Art "Invalid floating point operation" ausgegeben. Die sieht der Benutzer nicht  (sind wohl abgefangen), erscheinen aber im Debugger
-Die Prüfung läuft dann durch, es kommt auch der Hinweis "Prüfung beendet.....Protokolldatei C:\SVWS-Arbeitsverzeichnis\Statistik\Fehler.pdf ansehen? Wenn man da aber auf Ja klickt, kommt eine Fehlermeldung "Access violation". Das gleiche passiert aber auch, wenn man auf "Nein" klickt. Die PDF-Datei wird gar nicht erzeugt.

Das ganze läuft in der DLL ab, ScbILD "empfängt" als Anwendung, die die DLL aufgerufen hat, nur die Fehlermeldungen. Ich kann daher nicht sagen, warum das in SchILD3 nicht funktioniert (im Gegensatz zu SchILD2). Folgende Optionen gibt es meines Erachtens:
-IT.NRW prüft im Debugger, was da konkret passiert (beim Aufruf aus SchILD3)
-Oder die COM-Server-Technik wird abgestellt und entweder in eine "klassische" DLL  oder eine Exe umgewandelt, wobei man sich bei der Exe-Lösung eine Übergabe der Parameter überlegen müsste. Das sind aber nicht viele:
-Modus (z.B. "Gesamtprüfung", "SIM.TXT erzeugen"...)
-Connectionstring zur StatistikDB.mdb
-Connectionstring zur ASDTabs.mdb
-Connectionstring zur Schulver.mdb

**Comment by JuergenRichter** [comment]
Ich habe mal eine kleine Test-Anwendung geschrieben, die im Prinzip die vier oben angegebenen Funktionen bereitstellt und eine Gesamtprüfung anstößt. Wenn ich die Anwendung mit der bisherigen Entwicklungsumgebung compiliere, funktioniert alles wie gewünscht, u.a. wird von der ASDStatistik.dll auch die PDF-Datei mit den Statistik-Fehlern erzeugt und angezeigt.
Wenn ich das dann mit der Entwicklungsumgebung von SchILD3 compiliere, funktioniert die Gesamtprüfung auch, beim Erzeugen der PDF-Datei (was ja innerhalb der ASDStatistik.dll stattfindet) passiert gar nichts, nach einer Zeit bricht die Anwendung ab. Was hier genau passiert, müsste durch IT.NRW geklärt werden, ich kann die Bespielanwendung (die ohne SchILD3 gestartet werden kann) gerne zur Verfügung stellen.

**Comment by FPfotenhauer** [comment]
Antwort von Herrn Mörs:

```
ich habe eine leise Vermutung, warum kein Fehler-PDF erzeugt wird.

In einem Beitrag auf GitHub spricht Herr Richter von 4 Parametern, welche an die ASDStatistik.dll übergeben werden müssen. 
Falls dies eine vollständige Aufzählung ist, fehlt hier noch ein 5. Parameter. Für die Fehler-PDF muss nämlich auch ein Speicherpfad über die Funktion "StatistikPfadUebergeben" übergeben werden.
Beim Test mit einem neu geschriebenen Testprogramm sind wir darüber gestolpert. Es gibt keinen gültigen default Speicherort für die Fehler-PDF.
```

**Comment by JuergenRichter** [comment]
Ich hab mich wohl nicht korrekt ausgedrückt:

Ich mache in der Testumgebung folgende Aufrufe:
FStatistik.SchulnummerUebergeben( <Schulnr> ); );
FStatistik.ASDTABSConnectionStringUebergeben(  <Pfad zur ASDTabs.mdb> );
FStatistik.SCHULVERConnectionStringUebergeben( <Pfad zur Schulver.mdb> );
 FStatistik.STATISTIKDBConnectionStringUebergeben( <Pfad zur StatistikDB.mbd> );
FStatistik.StatistikpfadUebergeben( <Statistik-Pfad, bei mir Verzeichnis der StatustistikDB.mdb> );
FStatistik.StatistikMain( 4 ); // Gesamtprüfung

Statt der Parameter in spitzen Klammern werden natürlich existierende Angaben und Pfade übergeben. FStatistik ist das COM-Server-Objekt, was den Zugriff auf die ASDStatistik.dll kapselt. In der alten Entwicklungsumgebung funktioniert die Erstellung der PDF-Datei mit diesen Angaben ja auch einwandfrei, Wenn ich den gleichen Code mit der neuen Entwicklungsumgebung kompiliere, läuft die Gesamtprüfung ja auch durch. Es wird auch die gleiche Fehlerzahl gemeldet, nur beim Erstellen der PDF-Datei (deren Pfad korrekt im Fenster erscheint) stürzt die Anwendung mit einer Fehlermeldung "system exception (code 0xc000041d) at 0x007fcba8" ab. Das gleiche passiert übrigens auch, wenn man bei der Abfrage, ob man die PDF-Datei ansehen will, die Option "Nein" wählt.

**Comment by JuergenRichter** [comment]
Noch ein Hinweis: Die Fehlermeldung "system exception (code 0xc000041d) at 0x007fcba8" kommt nur dann, wenn ich die Anwendung innerhalb der Entwicklungsumgebung aufrufe. Wenn ich das über den Windows-Explorer starte, friert die Anwendung für ca. 10 Sekunden ein (wenn man die PDF-Ausgabe aktiviert) und wird dann ohne Meldung beendet.

**Comment by JuergenRichter** [comment]
Ich habe mal die Testanwendung bereitgestellt. Die Zip-Datei enthält folgendes:
StatistikTestD2009.exe: Testanwendung mit alter Entwicklungsumgebung kompiliert
StatistikTestDXE11.exe: Testanwendung mit neuer Entwicklungsumgebung kompiliert
StatistikTest.ini: Konfigurationsdatei für die Pfade zu den verwendeten Dateien (z.B. ASDTabs.mdb usw.)
StatistikDB.mdb: Aus SchILD erzeugte Statistik-DB zum Testen

Voraussetzung ist aber, dass die ASDStatistik.dll und die anderen für die Statistik benötigten Dateien auf dem System registreirt sind.

[StatistikTest.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10758254/StatistikTest.zip)

**Comment by JuergenRichter** [comment]
Noch ein Hinweis: An die ASDStatistik.dll wird als Ausgabepfad für die PDF intern das Verzeichnis übergeben, in der die StatistikDB.mdb liegt, d.h. dafür gibt es keine eigene Einstelloption.

**Comment by JuergenRichter** [comment]
Nach Neucompilierung von SchILD3 mit dem von Herrn Mörs beschriebenen Compilerschalter funktioniert jetzt die PDF-Ausgabe aus der ASDStatistik.dll. Ich schließe das Ticket erst mal.

Trotzdem wäre es interressant zu wissen, warum aus der ASDStatistk.dll viele "silent" Exceptions der folgenden Art erzeugt werden (fallen nur auf, wenn das innerhalb der IDE ausgeführt wird).
---------------------------
GExperts Debugger Exception Notification
---------------------------
Project SchILD30.exe raised exception class EInvalidOp with message 'Invalid floating point operation at address 770B78A2'.
---------------------------
[&Filter ...] [Ignore &All this Session] [Break] [Additional &Info] [Continue]
---------------------------
ThreadId=13176
ProcessId=2
ThreadName="Main thread"
ExceptionMessage="Invalid floating point operation at address 770B78A2"
ExceptionName="EInvalidOp"
ExceptionDisplayName="$C000008F"
ExceptionAddress=770B78A2
FileName=<not available>
LineNumber=<not available>

---------------------------
