### ISSUE TITLE
Reportexplorer sollte .pdf ausblenden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#509]
Werden die .pdf zusammen mit den .rtf im Reportexplorer eingeblendet, wird dies zu Fehlbedienungen führen.

![pdfausblenden](https://user-images.githubusercontent.com/116796098/219374373-514a469c-0cd7-4622-8d93-cc2dee036114.png)

**Comment by Raffenberg** [comment]
Hallo,
bisher werden ebenfalls PDF-Dokumente angezeigt, damit man z.B. auf Versionshistorien und Anleitungen klicken kann. Bei Doppelklick öffnet sich der hinterlegte PDF-Reader das Betriebssystems.
Ich halte das ausdrücklich für eine sinnvolle Anzeige.

**Comment by FPfotenhauer** [comment]
Bitte nicht ändern.
