### ISSUE TITLE
Basisreports - Ausdruck von SuS erfolgt nicht

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#51]
SchILD-Version 3.0.7.1 vom 8.12.2020:
In der Vorschau wird bei verschiedenen Basisreports (z. B. bei Klassenliste_Adresse.rtm) bei Auswahl aller Klassen nur die Überschrift, aber keine Schüler ausgedruckt. Die Ausgabe von Kurslisten funktioniert.

**Comment by FPfotenhauer** [comment]
Ich bekomme sogar eine Fehlermeldung.
Report Klassenliste Kästchen aus der neuen Reportsammlung:

![SNAG_2020_12_11_11 20 29](https://user-images.githubusercontent.com/34127980/101891933-fec50e80-3ba2-11eb-8335-36ea53cc4411.png)

**Comment by JuergenRichter** [comment]
In Version 3.0.8 behoben
