### ISSUE TITLE
Vorschau im Reportexplorer zeigt das Dokument mitunter nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#510]
Öffnet sich die Vorschau im Reportexplorer und ist das Fenster zu klein, ist der gerenderte Report nicht zu sehen. 

![reportfalsch1](https://user-images.githubusercontent.com/116796098/219405724-3148ce8f-06d1-43ed-8b45-ff0564fafcaf.png)

Ziehe ich das Fenster größter, taucht der Report entsprechend in Teilen auf. In der Höhe kann ich das Fenster nicht groß genug ziehen, um genug von einem A4-Report zu sehen; die volle Fensterhöhe lässt mich bei einem Zoom von 100%. ca. die Hälfte der Seite sehen.

![reportfalsch2](https://user-images.githubusercontent.com/116796098/219406096-5474f341-2b40-4f02-b72d-c7e414bb645b.png)

Möglicherweise hat dies wieder mit hohen Auflösungen (FullHD links, 4K rechts) bzw. einen Multimonitor-Setup zu tun.

Zuerst funktionierte die Vorschau eines Reports normal, nun taucht das Verhalten bei mehreren Reports auch nach einem Neustart von SchILD dauerhaft auf.

SchILD-Version: 3.0.54.9

**Comment by AnneSchueller** [comment]
Hallo Felix,
ich habe ein ähnliches Phänomen:
![2023-02-16_170010](https://user-images.githubusercontent.com/79116896/219420446-0ed48932-f80a-4620-aebf-2b837b8b0b2a.png)

Das tritt bei mir allerdings nur auf, wenn ich Schild im kleineren Bildschirm öffne und das Programm dann in einen größeren Bildschirm ziehe. 
Arbeite ich mit nur einem Bildschirm oder nur in dem Bildschirm, indem ich Schild geöffnet habe, sieht alles gut aus.
Interessant wäre die Frage, ob ähnliche Seiteneffekte auftreten wenn man zwei gleiche Monitore hat. Wahrscheinlich eher nicht. Das kann ich allerdings hier nicht testen.

Das Problem, dass die Darstellung teilweise etwas unschön ist, wenn die Bildschirm unterschiedlich groß sind, haben wir leider auch an anderen Stellen.

**Comment by FrodBRA** [comment]
Ich kann das bestätigen:
* Öffne ich SchILD auf dem kleinen Bildschirm und ziehe es auf den großen, tritt der Fehler auf.
* Öffne ich SchILD auf dem kleinen und lasse SchILD auf dem kleinen, gibt es keinen Fehler.
* Öffne ich SchILD auf dem großen Monitor, tritt der Fehler ebenfalls nicht auf. 

Weiterhin öffnet sich das Vorschaufenster immer auf dem Monitor, auf dem das Vorschaufenster zuletzt geöffnet wurde, egal, von wo SchILD gestartet wurde (der Ort der Verknüpfung bestimmt, wo sich SchILD öffnet). Der Fehler tritt aber in der Tat nur auf, wenn SchILD nach dem Öffnen von einem auf den anderen Monitor bewegt wurde.

**Comment by AnneSchueller** [comment]
Ich teste das morgen mal an unserem Schulungsbeamer.

**Comment by JuergenRichter** [comment]
Durch die Deaktivierung der "dpi-awareness" in der neuen Version sollte das Problem eigentlich behoben sein. Ich schließe das Issue daher mal, falls es weiterhin auftreten sollte, bitte wieder öffnen.

**Comment by AnneSchueller** [comment]
Funktioniert einwandfrei.
