### ISSUE TITLE
Con-Files werden nicht angelegt

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#511]
![schildfehler400](https://user-images.githubusercontent.com/78501680/219699122-f151b088-b6b1-40ab-8c3b-d4aca74e61d5.jpg)

**Comment by FPfotenhauer** [comment]
Schild3 muss komplett neu neu installiert werden.

**Comment by JeVaske** [comment]
Hatte ich getan. Habe danach den Ordner SVWS-Arbeitsverzeichnis von Hand gelöscht. Dann funktionierte es.

**Comment by FPfotenhauer** [comment]
Bitte auch Issues schließen.
Der Installer löscht nur Ordner in denen nichts ist, was nicht von ihm angelegt wurde.
