### ISSUE TITLE
Klassenleitung

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#512]
Mir ist aufgefallen, dass bei denjenigen Klassen, in denen fälschlicherweise **bei einem einzigen Schüler** ein falscher stellv. Klassenlehrer eingetragen wurde, nach Migration in Schild3 insgesamt 3 Klassenlehrer **bei allen SuS der Klasse** angezeigt werden.

**Comment by FPfotenhauer** [comment]
Die Klassenlehrer werden in einem Ranking bestimmt.
Wenn der Klassenlehrer "fälschlicherweise" eingetragen ist, dann sollte der wohl entfernt werden.

**Comment by JeVaske** [comment]
Ich muss wahrscheinlich etwas ausholen, damit besser nachvollziehbar ist, dass mit der Darstellung der Klassenlehrer in den vergangenen Halbjahren etwas seltsam zu sein scheint:
Die jetzige Klasse 9c (Aktive SuS) hatte im Schuljahr 2019/2020.1 (damals 6c) die Klassenlehrer Ö. und K in Schild 2.0.
Laut Schild 3.0 hatten diese SuS im Schuljahr 2019/2020.1 (damals 6c) die Klassenlehrer 1. Ö, 2. K, 3.S 4. L
Ich konnte mir nicht erklären, warum Frau S. und Frau L. dort auftauchen, weil beide bei den aktiven SuS in diesem vergangenen Schuljahr nicht vorkommen. Bei den Abgängern fand ich bei einer Schülerin, die die 6c wiederholt hatte, aber offensichtlich nicht mehr gekommen war, die Klassenlehrerin Frau S. und bei einem anderen Schüler die stellv. Klassenlehrerin Frau L.
Ein äquivalentes Verhalten kann ich an einem weiteren Beispiel nachvollziehen. Es kommt mir so vor, dass bei der Erstellung des „Klassenlehrerrankings“ auch die Abgängerdaten berücksichtigt werden, was bei mir mindestens an zwei Stellen zu seltsamen Kombinationen zu führen scheint.

**Comment by FPfotenhauer** [comment]
Wenn ein Abgänger den Abschnitt hat, dann wird der auch ausgewertet.

**Comment by JeVaske** [comment]
Optimal finde ich das an dieser Stelle nicht. Bei mir treten jedenfalls viel zu viele Fehler auf. Ungünstig ist auch, dass man per Gruppenprozess im Nachhinein nichts mehr korrigieren kann.

**Comment by FPfotenhauer** [comment]
Klasse Versetzungstabelle ... Falsche Klassenlehrerin entfernen... In dem Abschnitt...

**Comment by JeVaske** [comment]
OK, das sieht gut aus, ich hatte das bei den Gruppenprozessen gesucht. Die Schaltflächen sind aber noch nicht aktiviert:
![Schildfehler02](https://user-images.githubusercontent.com/78501680/220177270-e9a4ec29-4a19-47d2-8d0c-335b9ecc775b.jpg)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren.
Ich habe das mal in ein anderes Issue geschoben:
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/517
