### ISSUE TITLE
Schaltflächen inaktiv

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#513]
![schildfehler401](https://user-images.githubusercontent.com/78501680/219963096-5eb91f9c-7ed0-425a-83af-0bba188cd916.jpg)

**Comment by JeVaske** [comment]
Heute sind die Schaltflächen aktiv!?

**Comment by AnneSchueller** [comment]
Bei mir sind die Schaltflächen auch aktiv. Ich schließe das Issue mal; sollte der Fehler nochmal auftreten, dann gerne nochmal das Issue reopen.

**Comment by Raffenberg** [comment]
Ich habe leider das gleiche Problem. Es sind nicht nur die oben abgebildeten Schaltflächen ausgegraut, sondern auch die Schaltflächen der Gruppenprozesse. Ich habe daraufhin in die Benutzerverwaltung geschaut, um mir die Berechtigungen anzusehen. Dort werden die Berechtigungen ebenfalls ausgegraut angezeigt und ich kann dort nichts ändern, obwohl der Benutzer, unter dem ich angemeldet bin, ein Admin ist. 

Ich habe jetzt mehrfach komplett neu installiert. Mit anonymisierter und mit Originaldatenbank. Das Problem bleibt bestehen. Ich bin ratlos.

![benutzer](https://user-images.githubusercontent.com/48889965/220990164-cd94f570-e580-4d81-8989-65d4ec49e650.png)

**Comment by Raffenberg** [comment]
Anscheinend hat das Phänomen mit der Monitorskalierung zu tun. Ich habe das Phänomen bei einer Skalierung von 125% beobachtet. Wenn ich die Skalierung auf 100% stelle, sind alle Schaltflächen aktiv und benutzbar. Bei mir ist das reproduzierbar (Windows 11).

![125](https://user-images.githubusercontent.com/48889965/220997328-4cedccf3-0894-4824-8f24-143b8c3df0ca.png)
![100](https://user-images.githubusercontent.com/48889965/220997325-a49fd07f-808a-49a5-bc25-436f31f19182.png)

![125-2](https://user-images.githubusercontent.com/48889965/220997334-ec700817-db2e-41e7-8cf2-d0710962fb24.png)
![100-2](https://user-images.githubusercontent.com/48889965/220997332-d139b8bd-30d7-4f81-9f6b-07633a027971.png)

**Comment by Raffenberg** [comment]
Nachtrag: Ich weiß nicht genau wie ich das hinbekommen habe, aber momentan jetzt habe ich das Phänomen genau umgekehrt. Bei 100% sind die Schaltflächen inaktiv, bei 125% aktiv.

**Comment by AnneSchueller** [comment]
Das kann ich ebenfalls reproduzieren:
Bei 125 % sind die Schaltflächen bei mir auch ausgegraut.

**Comment by FrodBRA** [comment]
Ich kann das reproduzieren:
* Skalierung 150%: Die Flächen sind grau.
* Skalierung 100%: Die Flächen sind aktiv.

**Comment by JuergenRichter** [comment]
Das liegt wohl an der Einstellung für die Icons der Schaltflächen. Da gibt es die Eigenschaft "ButtonSize" mit den Optionen "Small" and "Large". Das Problem schient nur bei den Schaltflächen mit der Option "large" aufzutreten, und nur, wenn Skalierung nicht 100% ist. Ich habe das jetzt erst mal überall auf "small" umgestellt, dann funktioniert es.

![image](https://user-images.githubusercontent.com/61280188/221217694-16aaecd5-08b5-422c-aa04-113b4d4fb27f.png)

**Comment by JuergenRichter** [comment]
Durch die Deaktivierung der "dpi-awareness" in der neuen Version und der Verwendung einer anderen Komponenten für das Ribbon-Band sollte das Problem eigentlich behoben sein. Ich schließe das Issue daher mal, falls es weiterhin auftreten sollte, bitte wieder öffnen.
