### ISSUE TITLE
Lernplattformen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#514]
Unter Lehrkräfte/ Einwilligungen/ Lernplattformen tritt noch eine Fehlermeldug auf:
![Schildfehler004](https://user-images.githubusercontent.com/78501680/220178304-7349f7a6-6cfe-4133-8207-9e4487b00f81.jpg)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Welche Version, welche Schulform? Bei welcher Aktion genau tritt der Fehler auf?

**Comment by AnneSchueller** [comment]
Das Problem tritt bei mir auf, wenn man auf das "+" bei den Lernplattformen klickt.
Version: 3.0.56.9

**Comment by JuergenRichter** [comment]
behoben
