### ISSUE TITLE
Sortierungsnummer im Fächerkatalog nicht änderbar

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#515]
Ist es beabsichtigt, dass man die Nummerierung im Fächerkatalog nicht anpassen kann? 
Ich kann die Fächernummerierung, wie Herr Plümper sie zum Testen der dynamischen Datenquelle vorgeschlagen hat nicht einstellen.

**Comment by JuergenRichter** [comment]
Man kann die Sortierung derzeit wie folgt ändern:
-Die Sortierung "Benutzerdefiniert" oder "Benutzerdefiniert SII" wählen
-Dann sind die roten Pfeile links aktiv, mit denen kann man dann die Sortierung ändern

Wir können aber auch die Splaten in der Tabelle freigene, dann kann man da manuell was eintragen

**Comment by AnneSchueller** [comment]
Bei den Fächern fände ich es aufgrund der Vielzahl von Einträgen ganz gut, wenn man da auch manuell Nummern eintragen kann und dann mit reorganisieren wieder Standardnummern in Zehnerschritten verteilt.

Mir fällt gerade auf, dass der Reorganisierungsbutton bei den anderen Katalogen fehlt.

**Comment by JuergenRichter** [comment]
Die Spalten für die Sortierung sind nun  bearbeitbar (wenn man die Berechtigung hat)
