### ISSUE TITLE
Installation SchILD 3: DB-Konfiguator ruft als Default für "Connection-Files" das SchILD-Installationsverzeichnis auf, nicht das SVWS-Arbeitsverzeichnis

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#516]
Installer v.3.0.56

Habe SchILD3 in D:\SchILD3, dieses Verzeichnis wird auch dem Konfigurationstool übergeben. Hier die Variante, die mit dem FB-Newsletter vom 19.02.2023 übereinstimmt:

![FalschesVerzeichnis](https://user-images.githubusercontent.com/116796098/220324686-309c012f-4458-433f-a2a0-e2ab18de32f4.png)

**Comment by FPfotenhauer** [comment]
DAs ist auch korrekt so.
