### ISSUE TITLE
Archivierung in Dokumentenverwaltung funktioniert nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#519]
Version: 3.0.56.9

Klicke ich "Drucken mit Archivierung" oder "Nur Archivierung" wird kein Dokument in der Dokumentenverwaltung angelegt.

Es ist unerheblich, ob der Ordner für den Schüler existiert oder nicht. Über die Einstellungen alle Ordner anzulegen hat funktioniert. 

Existiert der Ordner nicht (testweise gelöscht), wird bei der (Nicht-)Generation des Reports auch kein Ordner angelegt. 

(Das Archivieren in die Zeugnisverwaltung funktioniert)

**Comment by AnneSchueller** [comment]
Werden beim Erstellen der Dokumentenverwaltung die Ordner im Unterverzeichnis SVWS-Arbeitsverzeichnis/Dokumentenverwaltung angelegt?
Bei mir wurden die Ordner einfach in C angelegt, obwohl ich das bei der Erstellung anders angegeben habe.
Die Archivierung klappt dann aber. Könntest du mal nachsehen, ob die Dokumente evtl. ebenfalls unter C angelegt und gespeichert wurden?

Mir ist auch aufgefallen, dass man unabhängig vom Report immer "mit Archivierung" auswählen kann. Also auch beispielsweise bei Klassenlisten, in denen gar keine Gruppe nach SchülerID vorhanden ist. Ist das gewollt?

**Comment by FrodBRA** [comment]
Wenn ich auf "Dokumentenverzeichnisse für alle Schüler anlegen" klicke, werden diese Verzeichnisse korrekt im gewählten Ordner erzeugt. Nur Dokumente werden nicht in diese Ordner archiviert.

Auf Laufwerk C: (oder auch im Root auf D:) wird nichts erzeugt.

**Comment by AnneSchueller** [comment]
Ich habe das jetzt auch nochmal mit meinem Windows 10 Rechner getestet. Da habe ich das gleiche Problem:
Die Ordner werden hier zwar richtig angelegt, aber es werden keine Dokumente archiviert. 
Welches Betriebssystem nutzt du?

**Comment by FrodBRA** [comment]
Windows 10, Home

**Comment by JuergenRichter** [comment]
Fehler gefunden und behoben.
