### ISSUE TITLE
Keine Minderleistungen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#520]
Unter Lehrkräfte - Zeitabhängige Daten - Minderleistung werden keine Kürzel und Entlastungsgründe angezeigt. Als Nummern werden keine dreistelligen Nummern angezeigt. Die importierten Wochenstunden hingegen werden angezeigt.

![minderleistung](https://user-images.githubusercontent.com/48889965/220469134-44344003-2887-40ca-979d-370b061b4ce3.png)

**Comment by JuergenRichter** [comment]
Behoben
