### ISSUE TITLE
Schriftgröße wird größer nach Aktivierung des Reiters

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#521]
Unter Lehrkräfte - Zeitabhängige Daten - Nichtunterrichtliche Tätigkeiten ist die Schriftgröße der Tabellenüberschriften größer als auf den anderen.

![taetigkeit](https://user-images.githubusercontent.com/48889965/220469745-3ea1309b-4a35-440f-b561-f8208559b7a7.png)

**Comment by JuergenRichter** [comment]
Das Problem tritt auch bei anderen Grid-Komponenten auf (z.B. Kurse). Ich habe jetzt endlich die Ursache gefunden.
