### ISSUE TITLE
Tabelle SchildFilter

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#522]
In der Tabelle können ja eigene Abfragen (als SQL-Befehle) gespeichert werden. Bei der Übernahme aus SchILD2 tritt nun häufig das Problem auf, dass die SQL-Befehle nicht mehr gültig sind, da sich ja die Datenbankstruktur geändert hat. Wäre es da nicht besser, die Tabelle bei der Migration zu ignorieren?

**Comment by FPfotenhauer** [comment]
Ist in der nächsten Version des SVWS-Servers umgesetzt. Der Inhalt der Tabelle wird ignoriert.
Das Anlegen eines gespeicherten Filters erzeugt bei mir allerdings Fehlermeldungen.

**Comment by JuergenRichter** [comment]
Fehler behoben
