### ISSUE TITLE
Neue Schulleitung mit Zeitraumangabe: falscher Schulleiter wird ausgewählt

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#523]
Wenn ich  eine neue Schulleitung o.ä. eintrage und unmittelbar einen Zeitraum eintragen möchte, verspringt das Programm zu einer anderen Schulleitung.

Offenbar verursacht ein Klick auf das Plus-Symbol ein Speichern und Neuanordnen der bisher eingegebenen Datensätze. Erst dann wird der Klick ausgewertet und durch die Neuanordnung die falsche Schulleitung ausgewählt.

https://user-images.githubusercontent.com/48889965/220851294-abc2a28a-09fa-44d9-a40e-284badde9a2b.mp4

**Comment by JuergenRichter** [comment]
behoben
