### ISSUE TITLE
Umstellung auf Quartale: Fehlerhafte Angabe im Dialog

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#524]
Wenn sich die Schule im 1. Halbjahr befindet und auf den Quartalsbetrieb wechseln möchte, erscheint eine fehlerhafte Angabe im Dialog. Dort muss der 2. Auswahlpunkt: "1. Halbjahr wird zum 2. Quartal" heißen.

![quartalsbetrieb](https://user-images.githubusercontent.com/48889965/220852956-aff40dd2-58d9-4eeb-bf18-96257a2bd5dd.png)

**Comment by JuergenRichter** [comment]
Behoben
