### ISSUE TITLE
Leeres Datenbankschema - Fehlermeldung beim Start von SchILD3

### ISSUE THREAD

**Issue by GHordt** [SVWS-NRW/Schild3-BetaTest#525]
Wenn eine leere Datenbank geöffnet werden soll, erscheint beim Start von SchILd3 die angehängte Fehlermeldung:
![Bild_001](https://user-images.githubusercontent.com/84896101/220974999-094c4cdf-7580-435f-8e37-e86c3317eb92.jpg)
[Fehlermeldung.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/10816126/Fehlermeldung.txt)

**Comment by FPfotenhauer** [comment]
Da läuft der Server nicht! Ist das die aktuelle Version?

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren: Wenn ich bei der Installation vom SVWS-Server die Option "Erstelle ein neues Schema" auswähle, muss anschließend erst mit migrateDB eine DB migriert werden, um Schild3 zu öffnen bzw. um eine Verbindung zum Server herstellen zu können.

**Comment by GHordt** [comment]
SchILD3 und SVWS-Server sind aktuell. (SetupSVWSServer_v0.5.5.exe und Setup_SchILD3_3.0.56.exe)

**Comment by FPfotenhauer** [comment]
Dann macht doch bitte Mal ein Konzept, was in das neue DBSchema alles geschrieben werden muss. Wir würden das dann umsetzen.

**Comment by GHordt** [comment]
Ich nehme an, du meinst Anne  und nicht mich.

**Comment by FPfotenhauer** [comment]
Ich glaube, das ist nicht so schwer. Man müsste sich Mal die alte schild2000n Vorlage ansehen und die Abfragen, die bei der Ersteinrichtung kommen. Können wir hier gerne diskutieren.

**Comment by AnneSchueller** [comment]
Die Auswahl "Erstelle ein neues Schema" ist doch sicherlich für Schulen, die neu in Schild einsteigen?

Möglichkeit 1 wäre dann, dass man diese Option auswählt und analog, wie es aktuell in Schild2 auch der Fall ist nach Schulnummer und co gefragt wird. 

Möglichkeit 2 wäre man migriert die schild2000n-Vorlage, die vorab mit Schild2 geöffnet wurde. (naja, wäre evtl. was umständlich)

Eine Alternative gibt es aktuell nicht oder?

**Comment by FPfotenhauer** [comment]
Naja. In der Vorlage fehlt primär der Eintrag in EigeneSchule. Frage ist, wer macht diesen Eintrag. API oder Schild3? Über Jahrgänge und Fächer und Gliederungen kann man sicherlich diskutieren. Ich würde gerne Herrn Richter morgen Mal in das Issue mit aufnehmen.

**Comment by FPfotenhauer** [comment]
Wir würden einen API-Aufruf machen, der das leere Schema befüllt.
Folgende Schritte sind m.E. wichtig:

- [ ] Schulnummer und Schuldaten eintragen
- [ ] Liste der Gliederungen abfragen
- [ ] Liste der Jahrgänge abfragen
- [ ] sehr übersichtlichen Fächerkatalog anlegen

Wass müsste noch ergänzt werden?

**Comment by GHordt** [comment]
Da es auch nicht möglich war, eine leere Datenbank in SchILD3 durch Migration einer jungfräulichen SchILD2000n zu erzeugen, habe ich eine Basisinstallation SchILD2 mit der Version 2.0.29.10 vom 20.01.2023 durchgeführt und die Grundeinrichtung vorgenommen. Ich habe hier die Kataloge aufgeführt, die bereits Listen direkt enthielten oder in denen bei der Erstellung eines neuen Datensatzes auf eine Auswahlliste zugegriffen wird (z.B. Schulen in NRW):
- Konfessionen
- Erzieherarten
- Orte
- Schulen in NRW
- Andere Schulen und Schulnummern (hinterlegt sind die Statistikschulnummer der anderen Bundesländer u.ä.)
- Schülerspezifische Kursarten (Statistikrelevant)

Ich weiß nicht, was davon möglicherweise schon mit der Installation von SchILD3 bereits bereitgestellt wird.

**Comment by FPfotenhauer** [comment]
Konfessionen und Erzieherarten habe ich ergänzt.

Den Rest würden wir mal ausprobieren und dann gemeinsam schauen.

**Comment by AnneSchueller** [comment]
@FPfotenhauer : Die Auswahl finde ich super. Mehr fällt mir auch nicht ein.

**Comment by FPfotenhauer** [comment]
Wie haben das jetzt zum Teil umgesetzt,

Mit dem Endpunkt [/api/schema/root/create/{schema}] kann man ja ein Schema anlegen. (root-Rechte!)
Dazu gibt es jetzt den Endpunkt [/db/{schema}/schule/init/{schulnummer}] (Admin ohne Passwort)

Hier kann das Schema eingerichtet werden. Wir befüllen die Tabellen dann so, wie in der Vorlage.
Schild3 meldet aber einen Fehler beim Start in der Klassentabelle. Auch wenn wir noch nicht fertig sind, sollte Schild3 starten.
Ich stelle am Wochenende mal eine SVWS-Server-Version zum testen zur Verfügung.

**Comment by FPfotenhauer** [comment]
Die Version SVWS-Server 0.5.6 liegt jetzt auf den Servern.
Schild3 startet aber mit der Meldung nicht:
![SNAG_2023_02_26_12 58 47](https://user-images.githubusercontent.com/34127980/221409087-6b49219f-f0d8-4552-8502-1c686c667965.png)

Ich werde nächste woche die zulässigen Jahrgänge für die Schulformen mal eintragen.
Frage wäre allerdings, ob Schild3 nicht trotzdem starten sollte.

// TODO Grundlegende Fächer - je nach Schulform - einrichten
// TODO Kursarten - je nach Schulform - einrichten
// TODO Jahrgänge - je nach Schulform - einrichten
// TODO K_Addressart mit Betrieb füllen
// TODO K_Beschaeftigungsart mit Ausbildung und Praktikum füllen
// TODO K_Datenschutz mit Verwendung Foto
// TODO K_EinschulgungsArt normal, vorzeitig und zurückgestellt
// TODO K_Entlassgrund mit "Schulpflicht endet", "Normales Abschluss", "Ohne Angabe" und "Wechsel zu anderer Schule"
 // TODO K-Ort aus der Default-Daten-Tabelle befüllen
 // TODO K_Religion aus dem Core-Type befüllen
 // TODO K_Schule mit Schulen aus dem sonstigen Ausland, den Bundesländern und Nachbarländern, Keine Schul und der eigenen Schule befüllen (Core-Type)

**Comment by JuergenRichter** [comment]
"Frage wäre allerdings, ob Schild3 nicht trotzdem starten sollte."
Sollte es jetzt auch tun, ich lege morgen mal eine entsprechende Datei ins Github.

**Comment by GHordt** [comment]
Ich habe heute die Konstellation SVWS-Server 0.5.6 und SchILD3 3.0.59.9 getestet. Die mit der SVWS-Server-Version erstellte leere Datenbank konnte mit SchILD3 problemlos gestartet und dann eingerichtet werden. 
Etwas ungewohnt ist für mich, dass im Bereich Kataloge -> Schulbezogene Kataloge -> Statistikjahrgänge die Gliederung "Standard für diese Schulform" manuell eingetragen werden muss.

**Comment by GHordt** [comment]
Die Migration einer leeren SchILD2000n.mdb vom 12.09.2022 mit migrateDB.exe vom 11.03.2023 funktionierte nicht. 

Fehlermeldung: "Kopiere die Daten aus der Quell-DB in die Ziel-DB...","    Bestimme die Schulnummer aus EigeneSchule:","      Kein Eintrag in der Tabelle EigeneSchule gefunden. Datenbank kann nicht migriert werden.","   [Fehler]","  -> Migration fehlgeschlagen! (Fehler beim Kopieren der zu migrierenden Daten)","  Fehler bei der Migration (driver='MARIA_DB', location='localhost:3306', user='svwsadmin')"]}"

**Comment by JuergenRichter** [comment]
Macht es Sinn, eine leere SchILD2000n.mdb zu migrieren?

**Comment by GHordt** [comment]
Jaein. Wenn im laufenden Betrieb ein leeres Datenbankschema erstellt werden soll/muss, geht das z.Zt. mittels SVWS-Server nur über eine Neuinstallation des SVWS-Servers, da der Menüpunkt "Erstelle ein neues Schema" nur anwählbar ist, wenn auch der Menüpunkt "Installiere SVWS-Server x.x.x (bereits installiert: x.x.x)" angewählt wird. 
Somit kann z.Zt. ein weiteres leeres Schema nur über die "Krücke" Migration einer leeren SchILD2000n.mdb erstellt werden. Wenn das ohne Neuinstallation des SVWS-Servers möglich ist, wird diese "Krücke" nicht benötigt.
Im schulischen Alltag gibt es durchaus Situationen, in denen Schulen mit mehreren Datenbanken in SchILD arbeiten, was in SchILD2 ja problemlos möglich ist.

**Comment by Raffenberg** [comment]
Der SVWS-Server bietet Möglichkeiten zum Anlegen und Migrieren weiterer Datenbanken, ohne diese Krücke. Hier muss nur ein entsprechender Menüpunkt angeboten werden. 
@Richter: Dies wäre ein Thema für Freitag.

**Comment by FPfotenhauer** [comment]
Da wir in der API nun einen Endpunkt "Create Schema" und "Init Schema" haben, macht es nun keinen Sinn mehr eine leere Schild2DB zu migrieren.

Mir fehlen noch folgende Tabellen, aber das hole ich nach und nach rein, Schild3 startet ja:
// TODO Grundlegende Fächer - je nach Schulform - einrichten
// TODO Kursarten - je nach Schulform - einrichten
// TODO K_EinschulgungsArt normal, vorzeitig und zurückgestellt
// TODO K_Entlassgrund mit "Schulpflicht endet", "Normales Abschluss", "Ohne Angabe" und "Wechsel zu anderer Schule"
// TODO K-Ort aus der Default-Daten-Tabelle befüllen
// TODO K_Schule mit Schulen aus dem sonstigen Ausland, den Bundesländern und Nachbarländern, Keine Schul und der eigenen

**Comment by JuergenRichter** [comment]
Fächer und Kursarten werden in SchILD3 eingerichtet, sind ja von der gewählten Schulform abhängig.

**Comment by FPfotenhauer** [comment]
Ich würde das schulformabhängig befüllen.
Oder haben wir da in Schild3 einen Button zur Einrichtung?

**Comment by JuergenRichter** [comment]
Nein, wenn in DSchILD3 festgestellt wird, dass kein Eintrag in "EigeneSchule" vorhanden ist, erscheint ja der Auswahldialog zur Einrichtung der Schule. Danach wird das Programm beendet, wenn dann beim nächsten Start festgestellt wird, dass der Fächerkatalog oder der Kurskatalog leer ist, wird dieser mit den Schulform-bezogenen Einträgen gefüllt (die Schulform ist jann ja schon bekannt). Man könnte auch die Tabelle der Gliederungen (EigeneSchule_Schulformen) mit dem Eintrag "Standard für dies Schule" füllen, evtl. Sonderregelungen bei GY (dann auch GY9 als GLiederung rein) und BK (gar keine Gliederung )

**Comment by FPfotenhauer** [comment]
Sie können, wenn es keinen Eintrag im Schema gibt, den Service aufrufen:
[/db/{schema}/schule/init/{schulnummer}](https://svws-nrw.de/debug/index.html#/Server/initSchule)

Ich muss das für den SVWS-Server so oder so einbauen, da könnten Sie dann auch über die API gehen.

**Comment by FPfotenhauer** [comment]
Wir haben den INIT-Service im SVWS-Server jetzt soweit umgesetzt.
Schild3 startet auch mit diesem Schema.
Wir haben bei vielen Schulformen bewusst nicht alle Fächer eingespielt, das sollen die Schulen selbst machen.
