### ISSUE TITLE
Gruppenprozess Individualdaten ändern - Schuljahr ändern funktioniert nicht

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#526]
Ich wollte bei allen Schülern das Schuljahr ändern auf 2022/23 1. Hj. Leider wird der Gruppenprozess nicht umgesetzt und alle SuS verbeiben in 2022/23 2. Hj.

**Comment by JuergenRichter** [comment]
Behoben
