### ISSUE TITLE
Gruppenprozesse: Typwahl des Prozesses ist ausgegraut 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#527]
Version: 3.0.56.9

![image](https://user-images.githubusercontent.com/116796098/221016215-3b5f78db-c251-4fef-8a2c-fa3ba636dd21.png)

Bei "Gruppenprozesse" stehen mir nur die "Allgemeinen" zur Verfügung, die Wahl des Gruppenprozesstyps ist ausgegraut und "Fächer", "Teilleistungen" usw. sind nicht anwählbar. 

Sollte dies Verhalten gewollt sein, bzw. ich kann die anderen Typen aufgrund einer Fehlbedienung nicht anwählen, sollte SchILD erklären, wieso die Felder nicht anwählbar sind.

**Comment by AnneSchueller** [comment]
Wahrscheinlich liegt das auch an der Skalierung. Sind die Daten bei den Schülern auch ausgegraut?
Bei mir wird der Gruppenprozess auch ausgegraut bei einer Monitor Skalierung von 125 %:

Vgl. hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/513

**Comment by FrodBRA** [comment]
In der Tat, das ist der gleiche Effekt: 

* Skalierung 150%: Die Flächen sind grau.
* Skalierung 100%: Die Flächen sind aktiv.

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue mal, damit wir das nicht doppelt haben.
