### ISSUE TITLE
Abschnittswechsel 1. Halbjahr -> 2. versetzt in das 1. Halbjahr des kommenden Schuljahres

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#528]
Verseztung vom 2022/23 1. Hj wird eingestellt -> 2022/23 2. Hj, Klick auf "Halbjahreswechsel durchführen".

Die Schule befindet sich nach dem Neustart von SchILD in 2023/24 1. Hj.

![Versetzung](https://user-images.githubusercontent.com/116796098/221412742-a1138d77-bc4e-4e7a-aa88-b4bf70d2fd15.png)

Version 3.0.56.9

**Comment by FrodBRA** [comment]
Eine Versetzung der SuS findet jedoch nicht statt, diese sind noch in ihren bisherigen Klassen, nur mit dem um ein ganzes Jahr erhöhten Abschnitt. 

Es wird für das 2. Halbjahr 2022/23 kein Lernabschnitt angelegt (für 2. Hj 2023/24 schon).

**Comment by AnneSchueller** [comment]
Ich habe den Halbjahreswechsel und den Schuljahreswechsel mit GS und GY getestet (ebenfalls mit 3.0.56.9). Ich kann das nicht reproduzieren. 
Was mich wundert ist, dass in Deiner Ansicht die Auswahl "2. Basisdaten für Schuljahreswechsel und Abschnittswechsel anlegen" ausgegraut ist, aber 3. bis 5. angehakt ist. Das geht bei mir gar nicht. 3. kann ich nur auswählen, wenn auch 2. ausgewählt ist.

**Comment by FrodBRA** [comment]
Ich kann das nun auch nicht reproduzieren: Ich habe nun ganz stumpf einfach auf der gleichen Datenbasis, nur eben mit dem nun erhöhten Schuljahr, noch einmal einen Wechsel gemacht. Hierbei war lediglich der 1. Wahlblock ausgegraut (was beim Halbjahreswechsel korrekt erscheint), die anderen Optionen standen alle zur Wahl.

Die Versetzung vom 1. Hj 23/24 ins 2. Halbjahr klappte wie erwartet und ohne Probleme.

**Comment by AnneSchueller** [comment]
Dann schließe ich das Issue mal. Ggf. nochmal öffnen wenn das nochmal auftreten sollte.

**Comment by FrodBRA** [comment]
Ich konnte das Problem nun reproduzieren, es scheint an der Datenbank zu liegen und daher sollten wir doch noch einmal darauf schauen.

Ich habe die Schulungsdatenbank GY_2022_23b, über unseren Speicher abrufbar, frisch migriert, der SVWS-Server wurde ebenfalls neu aufgesetzt, und das Problem taucht beim Halbjahreswechsel identisch auf.

@AnneSchueller

**Comment by JuergenRichter** [comment]
Was steht denn nach der Migration in der Tabelle "Schuljahresabschnitte"? Ich habe hier eine Beispiel-GS-Datenbank, wo der aktuelle Abschnitt "2020/21 1. Hj." ist (ao aus der mdb übernommen). Es gibt aber in der Tabelle "Schuljhresabschnitte" auch einen Eintrag für 2022/23 2. Hj. Ich weiß nicht, wie der da reingekommen ist. Ich werde die MDB nochmal neu migrieren, um zu prüfen, ob das durch die Migration geschehen ist.

**Comment by JuergenRichter** [comment]
Der Abschnitt wird wohl durch die Migration angelegt, hier ein Screenshot der Tabelle direkt nach der Migration
![image](https://user-images.githubusercontent.com/61280188/222433900-a2b4566c-9dfa-40f3-8012-e1e0b086b8e0.png)

**Comment by JuergenRichter** [comment]
Noch ein Hinweis zur Erläuterung:
In der Tabelle "Schuljahresabschnitte" ist nach der Migration eine Lücke zwischen 2020/21 1. Hj und 2022/23 2. Hj., d.h. die folgenden Einträge fehlen:
2020/21 2. Hj.
2021/22 1. Hj.
2021/22 2. Hj.
2022/23 1. Hj.
Darauf ist die Versetzung nicht "vorbreitet", es wird derzeit einfach geprüft, ob es einem Schuljahresabschnitt gibt, der zeitlich nach dem aktuell bei der Schule eingetragenen Wert gibt. Im konkreten Fall gibt es diesen, der ist aber falsch. Wir werden das so abändern, dass nicht nur "kommt irgendwann nach dem aktuellen Abschnitt" geprüft wird, sondern "folgt unmittelbar auf aktuellen Abschnitt".

**Comment by FrodBRA** [comment]
Unsere Testdatenbanken sind teils mehr zerspielt, als es bei echten zu erwarten ist.

**Comment by JuergenRichter** [comment]
Zu klären wäre, woher (für den Fall meiner Testdatenbank) der Eintrag "2022/23 2 Hj." herkommt. Ich hab das mal in der MDB geprüft, da gibt es tatsächlich ein Kind, bei dem das als aktuelles Schuljahr eingetragen ist, daher wird wohl auch bei der Migration ein entsprechender Datensatz in der Tabelle "Schuljahresabschnitte" angelegt. Ob das in der Praxis auch vorkommen kann, weiß ich nicht. Wir haben das aber jetzt schon in der Versetzung berücksichtigt, bei mir läuft es nun korrekt ab (auch mit falschem Eintrag in "Schuljahresabschnitte").
