### ISSUE TITLE
Fotoexport exportiert nur das erste Foto

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/Schild3-BetaTest#529]
Ich wollte die Fotos einer Klasse exportieren. Über Verwaltung - Export - Fotos wird für jeden ausgewählten Schüler eine Datei mit dem korrekten Namen angelegt, allerdings befindet sich in jeder Datei immer nur das Foto des ersten ausgewählten Schülers. 

Schild 3.0.56.9
SVWS-Server 0.5.5

**Comment by AnneSchueller** [comment]
Hallo Ulrich,
erstmal vielen Dank fürs Testen.
Ich kann das reproduzieren. Zusätzlich ist mir aufgefallen, dass bei der Auswahl Fotoexport nach ID eine Fehlermeldung erscheint:
![2023-03-03_091421](https://user-images.githubusercontent.com/79116896/222667548-8ae8fe3d-f567-40f6-a003-e09cc8b57ae7.png)

**Comment by JuergenRichter** [comment]
Behoben, Fotos werden nun korrekt exportiert
