### ISSUE TITLE
Fotoexport mit der ID als Dateiname funktioniert nicht.

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/Schild3-BetaTest#530]
Ich möchte Schülerfotos exportieren. Wähle ich Verwaltung - Export - Fotos und anworte auf die Frage, wie die Dateinamen erzeugt werden sollen mit "ID", so erscheint die Fehlermeldung 
_Format '%d' ungültig oder nicht kompatibel mit Argument._

**Comment by JuergenRichter** [comment]
behoben
