### ISSUE TITLE
Klasse fehlt beim Export in Textdateien

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/Schild3-BetaTest#531]
Ich möchte eine Schülerliste als Text-/Exceldatei exportieren. Unter Verwaltung - Export - Als Excel-/Text-Dateien, Datenart Schüler, fehlt mir die Möglichkeit, die Klasse zu exportieren.
![Klasse_fehlt](https://user-images.githubusercontent.com/99047051/222501095-d29b49a6-c24f-4276-9ebb-3f15698c6e06.png)

**Comment by JuergenRichter** [comment]
Es sind noch nicht alle bisher verfügbaren Felder im SVWS-Server verfügbar (der liefert jetzt die entsprechenden Informationen) , die kommen aber noch

**Comment by AnneSchueller** [comment]
Danke für den Hinweis, dann schließe ich das Issue.
