### ISSUE TITLE
Abschaffung von Quartalen

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#532]
# Dieses Issue soll als Diskussionsgrundlage dienen.

## Vorüberlegung
Es hat sich bei der Arbeit an den Oberstufen-Prozessen als extrem ungünstig herausgestellt, dass GY und GE in der Sek1 Quartale haben und in der Oberstufe eigentlich nur Halbjahre. Insgesamt ist die Verwaltung der Quartale historisch gewachsen und kann hier einmal überdacht werden.
Grund ist auch der Umgang mit den Noten aus Quartalen und Halbjahren und den zugehörigen Teilleistungen. Definition eines Abschnitts könnte man auch so sehen, dass in diesen ein Zeugnis (Halbjahr und Schuljahr) gedruckt wird. So gehört dann eine Quartalsnote auch zu einem Abschnitt und Teilleistungen (Klassenarbeiten und Somi würden auch alle zu einem Abschnitt gehören.

## Idee zur Umsetzung bei der Migration

* Abschaffung der Quartale 1 und 3
* Umschlüsselung in allen Tabellen von Abschnitt 4 auf 2 (Abitur, BKAbschluss usw.)
* Schaffung einers Feldes in den Leistungsdaten der Lernabschnitte NotenKrzQt für die Quartalsnote im Abschnitt
* Kopieren der Quartalsnoten 1 und 3 in dieses neue Feld in dann HJ und SJ
* Kopieren aller Teilleistungen aus 1 (nach HJ) und 3 (nach SJ) in die Leistungsdaten des neuen zugehörigen Fach im Abschnitt

## Konsequenzen für Schild3.0

* Reporting muss in den Leistungsdaten der Lernabschnitte das Feld NotenKrzQt eingeführt werden
* Anpassung der Prognose, wenn diese zwischendurch ausgeführt wird, dann muss die neue NotenKrzQt genommen werden

## Anpassung in SVWS-Server (nicht Migration)

* Einführung des Feldes NOtenKrzQt in der Datenbank
* Anpassung der QTNoten im ENM-Json

## Fragestellung zur Klärung

* Umgang mit Fächern, die im Quartal vorkommen aber nicht mehr im HJ
* Lehrerwechsel von Qt zu HJ (wird man wahrscheinlich den HJ Lehrer lassen)
* Was ist mit Trimestern?
* Was machen WBKs? 
* Was passiert bei Förderschulen mit nur einem Abschnitt

## Endüberlegung

Vorteil dieser Vorgehensweise:
Schild3.0 muss minimal angepasst werden. Die migrierten Datenbanken sehen dann wie Halbjahresbetrieb aus. Reports für Lernabschnitte und Teilleistungen funktionierne weiter. Teilleistungen gehören nun zum ganzen Abschnitt für Konferenzübersichten. Es gibt  bei 3 Klassenarbeiten und 2 SomiNoten nicht mehr die Splittung in 1.QT und 1.HJ.

Nachteil:
Es ist ein massiver Eingriff in die Art, wie die Schulen arbeiten und weitere Auswirkungen sind ggf. noch nicht absehbar.

**Comment by Raffenberg** [comment]
Ich befürworte das Vorgehen sehr.

Zu den Fragestelungen:
- Schulen, bei denen Fächer zwischen den Quartalen wechseln, fahren definitiv Sonderkonstellationen. Schild bildet aber nicht den Stundenplan ab, sondern erfasst Noten für Konferenzen und Zeugnisse. Insofern würde ich beim Umschlüsseln pragmatisch festhalten, dass wenn ein Fach in einem Quartal vorkommt, welches im HJ nicht existiert, dass dann das Fach im HJ mit den Daten aus dem Quartal angelegt und nur eine Note im neuen Quartalsnotenfeld erfasst werden
- Bei einem Lehrerwechsel würde ich nur den zuletzt eingetragenen Lehrer verwenden. So würde das bei einem Lehrerwechsel innerhalb eines Halbjahres an GY ebenfalls praktiziert
- Schulen mit nur einem Abschnitt müssen dann halt einmal den Versetzen Knopf p. Halbjahr drücken. Ich habe das mit einer Förderschule einmal durchgespielt. Der Unterschied zwischen nur einem Abschnitt und zwei Abschnitten war quasi nicht existent.

Gibt es Schulen mit Trimestern?
Was wäre die Besonderheit bei BKs?

**Comment by FPfotenhauer** [comment]
> SVWS-Server über die hier verwendete Datenbank irgendwann möglicherweise auch Stundenplanmodule unterstützen soll/könnte

Ja, das wird im SVWS-Server kommen. Zumindest werden wir Stundenpläne speichern können.
Die haben aber, wie du schon schreibst, Gültigkeits Daten. Wir brauchen das für die Klausurterminplanung sowieso.



> Das Problem mit der Oberstufe ließe sich ja über einen Schalter lösen, der angibt, ob die Quartale 1 und 3 als gewertete Lernabschnitte gezählt werde

Hier geht es eher um die ganzen Funktionen rund um die Oberstufe im Blockungs und Klausurplanungsmodul. Die Entwickler haben hier an allen möglichen Stellen immer Schmerzen, ob der Abschnitt 2 nun Halbjahr oder Schuljahr ist, Abschnitt 1 nun 1QT oder 1HJ .... usw. das ist sehr Fehleranfällig und kostet Zeit.

 

> Gibt es Schulen mit Trimestern?
> Was wäre die Besonderheit bei BKs?

Es gibt ein Binnenschiffer BK in Duisburg mit Trimestern! :-)
Aber wir sind ziemlich sicher, dass BKs und WBKs momentan eher im Halbjahresbetrieb sind.

**Comment by FPfotenhauer** [comment]
Das ist aber einer der Punkte für nach v1.0 des SVWS-Server und lässt sich dann auch leicht nachrüsten. Der Vorschlag hört sich aber stark Schulform- bzw. Schulstufen-spezifisch an. Das würden wir dann in einer eigenen Tabelle für GymOb sehen. Für die S I würden wir das vermutlich dann getrennt handhaben.

Aber das werden wir später auf jeden Fall angehen.

**Comment by FrodBRA** [comment]
> Die Teilleistungen können das zwar leisten, sind aber durch deren flexible Benennung schwer in Reports für Beratungsbögen oder Klassenarbeitsdokumentation zu realisieren.

Bei der obigen Diskussion stolperte ich auch schon über eben diesen Punkt.

Ich halte es dringend für geboten, nicht nur die technischen Strukturen zu schaffen, beliebige [X] zu schaffen, die dann frei konfiguriert werden können. In diesem Fall ist [X] = Teilleistungen. 
Wichtig wäre glaube ich, dass SchILD von Haus aus schon fertige Strukturen liefert, die von den Schulen dann genutzt werden können.

D.h. ScHILD unterstützt technisch beliebig frei benennbare Teilleistungen, konfiguriert eine Schule eine gymnasiale Oberstufe, werden automatisch passende Teilleistungen bereitgestellt, die dann in Reports verwendet werden können. D.h. würde jede Oberstufe automatisch die Teilleistungen TL_Somi1, TL_ Somi2 (dann die  Gesamtsominote) und Klausuren TL_Klausur1 bis 5 und eventuell zwei Noten für "Besondere Leistungen" oder was auch immer anbieten. Wer dann im Einzelfall mehr braucht, kann das definieren und auch von Hand in einen Report aufnehmen.

Durch ein Anbieten fester Standards wäre es dann ja so, als würden hard codierte Felder verwendet.

Wäre damit das Problem der Benennung bzw. Verarbeitung in SchILD/Reports gelöst?

**Comment by ThomasBachran** [comment]
> Durch ein Anbieten fester Standards wäre es dann ja so, als würden hard coded Felder verwendet. Unter der Prämisse, dass eine Schulform bestimmte TL_Felder mit fester Bezeichnung besitzt, könnte SchILD auch für weitere Prüfungen auf diese zugreifen kann.

Der Komplex der Teilleistungen soll perspektivisch auch angegangen werden. Wie hier schon angedeutet worden ist sind dann schulformspezifische Lösungen mit geeignetem Defaulting wichtig.

Derzeit geht es erstmal nur darum im Rahmen der Migration die Problematik mit den Lernabschnitten so zu lösen, dass die Implementierung der Algorithmen für die Oberstufe gut handhabbar sind und dass die daraus entstehende Datenbank kompatibel zu Schild 3 bleibt. Ziel ist erstmal eine effiziente Weiterentwicklung zu ermöglichen. Größere Änderungen an Schild 3 sind in **dieser** Phase des Projektes nicht zielführend und nicht beabsichtigt. 

Eine Orientierung an Lernabschnitten, welche mit Zeugnissen enden ist hierzu hilfreich. Daher auch erstmal der Gedanke der moderaten Anpassung mit der Quartalsnote, was sich im Rahmen der Migration umsetzen lässt. Weitergehende Änderungen können dann ggf. später mit Versionen 3.X schrittweise umgesetzt werden. Hierbei werden sicherlich auch die dynamischen Datenquellen für das Reporting (siehe  #436) sein, die derzeit in Entwicklung sind.

**Comment by FPfotenhauer** [comment]
Wie gesagt, werden wir das Problem der Teilleistungen später nach Release 1.0 angehen.
Hier wird man alle Schulformen im Blick haben müssen, vor allem auch BKs.

**Comment by M-Plu** [comment]
Auf Basis dessen, was Thomas schreibt, wäre meine Frage, ob das folgende Procedere viel aufwändiger wäre, als das Einfügen eines Notenfeldes, das später wieder abgeschafft wird.

Es gibt je nach Schulform Termine zur Leistungsmittelung (Zeugnisse). Das wäre die Lernabschnitte, meist Halbjahre. Den Lernabschnitten kann man weitere Leistungen pro Fach zu ordnen (nennen wir sie Teilleistungen). Diese können von den Schulen definiert werden. Entspricht dem Stand von Schild jetzt.

Um dennoch bestimmte schulformspezifische Teilleistungen (SFT) abbilden und darauf schnell zugreifen zu können, könnte man einen Katalog definieren, der diese SFT definiert, also bzw. GE_SekI-Q1, GY_SoMi1 usw., und die Einträge aus dem Katalog ordnet man den schulseitig definierten Teilleistungen zu.

So kann man Reports auf Basis des Kataloges erstellen (Filterkriterium)  und die Schulen können trotzdem frei Teilleistungen nutzen. Algorithmen greifen auf diese Schlüssel zu. Die Migration müsste gut leistbar sein, weil das 1. Quartal dann in eine Teilleistung umgesetzt wird, die einen festen Schüssel hat.

Alte Reports laufen weiter, weil die Teilleistungstabelle nur erweitert werden, bzw. über die SetzeFilter und SetzeSortierung-Funktion leicht angepasst werden können. Bei bestehenden Reports zu den Lernabschnitten muss man unter Umständen eh  Hand anlegen, wenn da feste auf die Abschnitte 2 und 4 zugegriffen wird.

**Comment by FPfotenhauer** [comment]
> Es gibt je nach Schulform Termine zur Leistungsmittelung (Zeugnisse). Das wäre die Lernabschnitte, meist Halbjahre. Den Lernabschnitten kann man weitere Leistungen pro Fach zu ordnen (nennen wir sie Teilleistungen). Diese können von den Schulen definiert werden. Entspricht dem Stand von Schild jetzt.
> 
> Um dennoch bestimmte schulformspezifische Teilleistungen (SFT) abbilden und darauf schnell zugreifen zu können, könnte man einen Katalog definieren, der diese SFT definiert, also bzw. GE_SekI-Q1, GY_SoMi1 usw., und die Einträge aus dem Katalog ordnet man den schulseitig definierten Teilleistungen zu.

Was an "Das werden wir später angehen." ist so schwer zu verstehen? 
Aber wir können die Ideen und Vorschläge aus dem Issue ja für später festhalten.

Wir müssen die Quartalsnoten (die an Gesamtschulen verpflichtend sind) irgendwie archivieren.

**Comment by M-Plu** [comment]
Die Quartalsnoten werden bei mir archiviert in Form einer Teilleistung, falls das nicht klar genug formuliert gewesen sein sollte.

Der Vorschlag würde wahrscheinlich alle Fälle abdecken, vorhandene und zukünftige. Erforderlich: ein Feld in den Teilleistungen und eine Katalogtabelle für die Teilleistungen.

Wenn das jetzt zu viel ist, dann halt nur ein Feld jetzt und etwas anderes später.

**Comment by JuergenRichter** [comment]
ScHILD3 zeigt jetzt bei den Leistungsdaten eine Spalte für die die Quartalsnote an. Wir werden bei den Programmeinstellungen noch eine Option schaffen, die Anzeige steuern zu können

**Comment by JuergenRichter** [comment]
Ich habe jetzt in allen Report-Datenquellen, die Leistungsdaten ausgeben können, auch das Feld "NotenKrzQuartal" eingefügt. Es gibt auch eine Einstelloption für das Ein-/Ausblenden der Quartalsnote.
