### ISSUE TITLE
Art bei Betrieben

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#533]
Die Art des Betriebs wird nicht angezeigt.

![SNAG_2023_03_12_14 29 24](https://user-images.githubusercontent.com/34127980/224547873-2702be2d-a744-4601-92f7-1f65bd13e0c5.png)

**Comment by NBerkenheide** [comment]
Das ist bei mir auch aufgetreten!

**Comment by JuergenRichter** [comment]
Behoben
