### ISSUE TITLE
FHR Berechnung: keine gültige Belegung gefunden

### ISSUE THREAD

**Issue by NBerkenheide** [SVWS-NRW/Schild3-BetaTest#534]
Hallo,

ich habe unsere Datenbank einmal neu migriert. Dabei ist folgender Fehler aufgetaucht:
FHR Berechnung: keine gültige Belegung gefunden. Dies ist bei mehreren SuS aufgetaucht

**Comment by AnneSchueller** [comment]
War das eine Fehlermeldung in der log-Datei? Wurde die DB trotzdem migriert?
Vielleicht könntest du das log mal hier einstellen? (unter C:\ProgramData\SVWS-Server\logs)

**Comment by NBerkenheide** [comment]
Schaue ich morgen (Mittwoch) nach! Wie gesagt, in Schild 2 ist es bei allen Schülern richtig!

**Comment by AnneSchueller** [comment]
Ich schließe das Issue mal. Fall hier erneut Probleme auftreten, bitte nochmal öffnen
