### ISSUE TITLE
Erste Fremdsprache und bisher erreichte Abschlüsse fehlen

### ISSUE THREAD

**Issue by NBerkenheide** [SVWS-NRW/Schild3-BetaTest#535]
![Fremdsprache](https://user-images.githubusercontent.com/124572460/224558005-ec3ab8f7-c1f7-4fcc-8e03-148980d87534.png)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Auch neu berechnete Abschlüsse werde nicht eingetragen.

**Comment by AnneSchueller** [comment]
Das ist die gleiche DB in Schild2 und Schild3
![2023-03-13_105128](https://user-images.githubusercontent.com/79116896/224688885-21f4c5a1-bcb6-4151-9e57-ea260f6be1e5.png)

Sprachenfolge für Uwe (nicht sichtbare Felder sind NULL-Werte)
![2023-03-13_122916](https://user-images.githubusercontent.com/79116896/224689540-52dacc5b-9059-4758-8ad6-60eb11a5e326.png)

Schuelerabgaenge für Uwe
![2023-03-13_122845](https://user-images.githubusercontent.com/79116896/224689578-d5c05325-b10c-4c7f-a78d-c33c4f2da7b5.png)

**Comment by AnneSchueller** [comment]
Wurde behoben
