### ISSUE TITLE
Spalteneinstellung wird nicht gespeichert

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#538]
Im Reiter Reportverwaltung

https://user-images.githubusercontent.com/79116896/224731436-7d25d7e8-0b43-4050-9f20-b0e1d2855756.mp4

**Comment by JuergenRichter** [comment]
Durch die Deaktivierung der "dpi-awareness" in der neuen Version sollte das Problem eigentlich behoben sein. Ich schließe das Issue daher mal, falls es weiterhin auftreten sollte, bitte wieder öffnen.
