### ISSUE TITLE
Störende Balken beim "schnellen" Klicken

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#539]
Erst durch einen Neustart verschwindet der Balken wieder

https://user-images.githubusercontent.com/79116896/224736422-f3890010-a543-4734-b298-e9c6b1a8266c.mp4

**Comment by FrodBRA** [comment]
Version 3.0.56.9

Das passiert bei mir nicht. Ich habe versucht, extrem schnell - auch schneller als im Video - zwischen Fenstern hin und her zu schalten und den UI-Aufbau dabei zu stören, aber die Oberfläche übersteht das alles ohne Probleme. 

Sowohl auf FullHD wie 4K bekomme ich keine Probleme erzeugt.

Vermutung: Das könnte etwas mit der Rechnerperformance zu tun haben? Das Layout baut sich im Video teilweise sehr sichtbar auf, bei mir aber deutlich (!) schneller als hier im Video. Möglicherweise hat das was mit dem Aufbau des Fensters zu tun, d.h. wenn bestimmte Elemente noch nicht vollständig geladen und angeordnet sind, bevor andere nachgeladen werden, kann es zu bleibenden Artefakten kommen. (Der von mir verwendete Rechner ist recht schnell.)

Wenn ich das Video auf halber Geschwindigkeit laufen lasse, scheinen die Balken dort zu entstehen, wo beim Laden Scrollbalken über dem noch unfertigen UI aufpoppen, die dann aufgezogen werden und verschwinden, jedoch ihre Spur hinterlassen.

Läuft dein SchILD hier auf einem eher schnellen oder eher langsamen Rechner?

**Comment by AnneSchueller** [comment]
Weitere Tests haben ergeben, dass das Problem bei mir nur dann auftritt, wenn ich mit zwei Monitoren arbeite. Der gleiche Rechner mit nur einem Monitor zeigt keine Probleme beim schnellen Wechsel von Reitern. Dort baut sich dann die Oberfläche auch zügig auf.

**Comment by FrodBRA** [comment]
An der reinen Präsenz von zwei Monitoren liegt es nicht - das ist auch mein Setup. 

Was möglicherweise für eine mit den zusätzlichen Pixeln überforderte Office- oder Laptop-Grafikkarte oder ein Treiberproblem sprechen würde?

**Comment by JuergenRichter** [comment]
Durch die Deaktivierung der "dpi-awareness" in der neuen Version sollte das Problem eigentlich behoben sein. Ich schließe das Issue daher mal, falls es weiterhin auftreten sollte, bitte wieder öffnen.
