### ISSUE TITLE
Link zum falschen Wiki: Verwaltung-Online-Dokumentation aufrufen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#540]
Die Schaltfläche im Ribbon "Online-Dokumentation" aufrufen unter Verwaltung muss mit dem neuen Wiki verknüpft werden:
https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php

Momentan ist die Schaltfläche mit dem alten WIki verknüpft.

**Comment by JuergenRichter** [comment]
Behoben
