### ISSUE TITLE
Katalog K_Einschulungsart

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#541]
Ich wollte gerade noch den Service INIT-Schema etwas weiter befüllen.

Da bin ich über folgenden Katalog gestolpert:
```
// K_EinschulgungsArt normal, vorzeitig und zurückgestellt
        Vector<DTOEinschulungsart> einschulungsart = new Vector<>();
        einschulungsart.add(new DTOEinschulungsart(1L, "normal"));
        einschulungsart.add(new DTOEinschulungsart(2L, "vorzeitig"));
        einschulungsart.add(new DTOEinschulungsart(3L, "zurückgestellt"));
```

Der ist zwar in der DB, aber ich finde den nicht in der Oberfläche.
Die Daten sind ja auch redundant mit den Statistikangaben.
Kann es sein, dass diser Katalog gar nicht mehr benötigt wird?

**Comment by JuergenRichter** [comment]
Hier die Hintergründe: Ursprünglich war die Einschulungsart keine statistik-relevante Information, es gab einen Katalog (K_Einschulungsart), den die Schulen selbst pflegen konnten (und der mit den Werten "normal", "vorzeitig" und "zurückgestellt" vorbelegt war). Im Rahmen einer Änderung der Statistik wurde dann auch die Einschulungsart relevant, was entsprechende Kürzel voraussetzte, die dann durch eine Tabelle in der Statkue.mdb bereitgestellt wurden. Die BWBKs und BKs, die keine Einschulungsart an die Statistik liefern müssen, haben sich dann aber beschwert, dass die "schuleigenen" Einträge nicht mehr zur Verfügung standen, daher wurde für diese Schulformen die Eingabe von schuleigenen Einschulkungsarten wieder freigegeben.

**Comment by JuergenRichter** [comment]
Ich habe gerade gesehen, dass die Auswahl bei den SuS gar nicht zur Verfügung steht. Durch die geänderte Oberflächengestaltung gibt es nämlich jetzt für die BKs einen eigenen Bereich (Individualdaten II>>Berufskolleg), nicht aber für die WBKs. Zu klären wäre daher:
-Soll die Option der "schuleigenen Einschulungsarten" erhalten bleiben?
-Wenn ja, soll es für die WBKs auch einen eigenen Bereich auf "Individualdaten II" geben?

**Comment by FrodBRA** [comment]
@FPfotenhauer 

Die offenen Fragen wären zu klären.
