### ISSUE TITLE
RichText-Feld "dm pipelines" bei aktiviertem Mail Merge sind nicht alphabetisch geordnet 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#542]
Version 3.0.59.9

Wird Mail Merge in einem RichText-Feld aktiviert, sind die dmpipelines nicht alphabetisch geordnet.

Die Felder in den pipelines sind es dann. 

![RTF Mail merge](https://user-images.githubusercontent.com/116796098/225739375-f61d6552-605d-4936-a346-ec6fd54d068a.png)

**Comment by JuergenRichter** [comment]
Behoben. Das lag a einer neuen Version des ReportBuilders. Dort wird im Code beim Aufbau der Liste der Datenquellen diese nicht sortiert (aus welchem Grund auch immer), daher muss man nach jedem Update hier selbst "Hand anlegen". War diesmal vergessen worden, ist nun aber geschehen.
