### ISSUE TITLE
UI Fehler: Nach Klick auf Lehrkräfte werden die LK-Individualdaten bei "Schüler" angezeigt [3.0.60.9]

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#544]
Version 3.0.60.9

1. SchILD frisch gestartet
2. Klick auf Lehrkräfte
3. Klick zurück auf Schüler

➔ Die Individualdaten von der Lehrkraft werden bei Schüler in deren Fenster angezeigt. 

Der Fehler bleibt bis zu einem Neustart erhalten, ein Anwählen anderer Reiter bringt die Schüler-Seite nicht zurück.

Eine komplette Neuinstallation des SVWS-Servers mit frischer Datenbankmigration und von SchILD3 wurden vorgenommen.

![UI1](https://user-images.githubusercontent.com/116796098/227143110-f2eb58c9-f431-4a7a-9691-5e9f0ad30e4e.png)

![UI2](https://user-images.githubusercontent.com/116796098/227143131-2ee21326-451b-43ae-9f3c-d23975a65593.png)

**Comment by FrodBRA** [comment]
Geht auch kaputt, wenn ich VON der Reportverwaltung komme. Dann wird diese rechts des Schülercontainers gezeigt.

Scheint somit am Wechsel ZU "Schüler" zu liegen?

**Comment by JuergenRichter** [comment]
Danke für die Hinweise. Wir sind gerade dabei, größere Änderungen bei den "Aufräumarbeiten" nach einem Wechsel der Tabs umzusetzen. Dabei ist die "Lehrerseite" übersehen worden (einla erzeugt, wird sie nicht wieder freigegeben). Das ist nun korrigiert.
