### ISSUE TITLE
Export in Excel/Text: Felder zu aktuellem Abschnitt (z.B. "Klasse") nicht verfügbar [3.0.60.9]

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#545]
Version 30.0.60.9

Beim Export scheinen zu den Individualdaten gehörende aktuelle Abschnittsdaten zu fehlen - mir sind "Klasse" und "Jahrgang" aufgefallen. Diese tauchen in der Datenart "Schüler" weder bei bei den Individualdaten noch bei den Zeugnisdaten als Auswahl auf.

Im Screenshot ist die unsichtbare "Klasse" markiert. 

![ExportAbschnitt](https://user-images.githubusercontent.com/116796098/227145762-9fe468a2-fdaa-4bbb-a40f-6fa9b748476a.png)

**Comment by AnneSchueller** [comment]
Hier fehlen auch Religionsab-/anmeldung und Klassenlehrerdaten.

**Comment by JuergenRichter** [comment]
Es werden noch nicht alle Definitionen für die Ausgabe über den SVWS-Server geliefert, kommt aber.

**Comment by AnneSchueller** [comment]
Werden die fehlenden Angaben mittlerweile über den SVWS-Server geliefert?

**Comment by FrodBRA** [comment]
SchILD: 3.0.76.11
SVWS: 0.7.5

Nein.

**Comment by FrodBRA** [comment]
SchILD: 3.0.80.9
SVWS: 0.8.8

Nein.

**Comment by FrodBRA** [comment]
@AnneSchueller @FPfotenhauer 
Wäre es möglich, das hier auf "hohe Priorität" zu setzen und in den Milestone aufzunehmen? Ich kann mir nicht vorstellen, SchILD zu schulen, ohne dass Jahrgang/Klasse (usw. schülerbezogen) exportiert werden können.

Der Erfahrung nach werden solche Felder von sehr vielen Schulen, gerade kleinen Systemen, aber auch an großen Systemen von Abteilungen, Sportfestveranstaltern, Prowo-Leuten, Ausflugsorganisatoren (usw. usw.) in sehr vielen Kontexten für die Weiterverarbeitung in Excel verwendet.

**Comment by JuergenRichter** [comment]
Ich habe die Liste für den Export soeben ergänzt, werde ich gleich an das "SVWS-Server-Team" weiterleiten. Das müsste dann aber in eine neue Version des SVWS-Servers integriert werden.

**Comment by FPfotenhauer** [comment]
Sollte jetzt drin sein.
