### ISSUE TITLE
Export in Excel/Text mit Zeugnisdaten -> Fehler: "svwsdb.prueford_optionen does not exist" [3.0.60.9]

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#546]
Version 3.0.60.9

Beim Export mit aktivierten Zeugnisdaten fehlt meiner Datenbank (svwsdb) .prueford_optionen.

Der Export bricht mit einem Fehler ab.

Ein Export ohne Zeugnisdaten funktioniert. 

Es wurden der SVWS-Server und SchILD3 neu installiert, die DB wurde ebenfalls frisch migriert.

![ExportDBFehler](https://user-images.githubusercontent.com/116796098/227146809-d849a492-9fd7-40a9-8a0e-d645439bb89e.png)

**Comment by JuergenRichter** [comment]
Die Tabelle gibt es nicht mehr, der Inhalt wird jetzt vom SVWS-Server geliefert. Das ist nun angepasst.
