### ISSUE TITLE
Export in Excel/Text: Geschlechter "divers" und "ohne Angabe" werden im Export als "w" ausgegeben [3.0.60.9]

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#547]
Version 3.0.60.9

Getestet mit dem Export -> Excel/Text.

Im Exportfenster können auch nur "m" und "w" konfiguriert werden, Felder für die Veränderung von "divers" und "keine Angabe" stehen nicht zur Verfügung. 

[In der Schnittstellendatei werden die neuen Optionen als 5 und 6 codiert, die klassischen Geschlechter sind m und w.]

**Comment by JuergenRichter** [comment]
Die "Regeln" für den Export werden ja nun auch vom SVWS-Server geliefert. Ich werde die CSv-Datei, die die Regeln enthält (und im SVWS-Server irgenwie geladen wird) ergänzen und Herrn Pfotenhauer zukommen lassen. Dazu ist dann aber eine neue Version des SVWS-Servers notwendig.

**Comment by JuergenRichter** [comment]
War doch ein Fehler im Code, nun behoben
