### ISSUE TITLE
Übernahme von "Vor Aufnahme besuchte Schule" über den Pfeil in "Alle bisher besuchten Schulen": Fehler, Eintrag existiert vermutlich schon. [3.0.60.9]

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#549]
Version 3.0.60.9

Ich habe einen Realschuleintrag vorgenommen.

Die Liste mit "Alle bisher besuchten Schulen" ist leer. 

Beim "die Schule mit dem Pfeil zu übernehmen" kommt es zu der Fehlermeldung.

Nachdem die Fehlermeldung weggeklickt ist, bleibt der Eintrag auch leer (d.h. die im Screenshot zu sehende Zeile taucht nur so lange auf, wie die Fehlermeldung zu sehen ist.

Der Fehler tritt auch auf, wenn ich einfach auf einen Schülereintrag gehe, in dem lediglich die Grundschule konfiguriert wurde und versuche, diese mit dem Pfeil zu übernehmen.

![Schulwechsel](https://user-images.githubusercontent.com/116796098/227436669-6045012d-f89b-4ca2-ae48-7527a7ec7a55.png)

**Comment by JuergenRichter** [comment]
Behoben
