### ISSUE TITLE
Einen Eintrag in "Alle bisher besuchten Schulen" anzulegen erzeugt einen Fehler: Feld Beschreibung wurde nicht gefunden. [3.0.60.9]

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#550]
Version 3.0.60.9

Erzeuge ich einen Eintrag in Schüler -> Schulbesuch -> Alle bisher besuchten Schulen kommt es zu einem Fehler. 

Siehe Screenshot.

Klicke ich den Fehler weg, erscheint ein Fenster, in dem Daten eingegeben werden können (dieses scheint aber unvollständig, da ich keine Schulnummer eingeben kann und die Dropdown-Menü teilweise nicht funktionieren (kann nur GY als Schulform wählen und anderes; da ich nicht weiß, ob die Fehler nicht zusammenhängen, erzeuge ich dafür aktuell kein neues Issue).

![Schulwechsel2](https://user-images.githubusercontent.com/116796098/227437538-dfb7bcb6-0733-4678-a4fb-11dfc1287fdf.png)

**Comment by JuergenRichter** [comment]
Behoben
