### ISSUE TITLE
Code im Report wieder Binär

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#552]
Wir hatten vor einiger zeit den Code innerhalb eines Reports von Binär auf ASCII umgestellt, so dass dieser auch in einem Texteditor gelesen und z.B. über suchen/ersetzen verändert werden kann . So zumindest der Plan.

Der Code wird allerdings willkürlich umgebrochen und ist voller Steuerzeichen, so dass diese Darstellung keinerlei Vorteil bringt. Als Nachteil bleibt damit die fehlende Kompatibilität zu Schild2. Sobald ein Report in Schild3 geöffnet und gespeichert wird, ist er in Schild2 nicht mehr zu gebrauchen.

Ich würde deshalb dafür plädieren, die Umstellung wieder rückgängig zu machen, um in der Übergangszeit Kompatibilitätsfehler auszuschließen.

Hier ein Beispiel des Text-Codes:

<img width="774" alt="code" src="https://user-images.githubusercontent.com/48889965/227865271-37a628aa-91dc-4e16-9926-1c91e8464831.png">

**Comment by Raffenberg** [comment]
Ich hole dieses Issued nochmal hoch. Das sollte im Reportdesigner nur eine einfache Einstellungsänderung sein.
Für die Rückwärtskompatibilität ist das aber wichtig. Ansonsten müssen wir zwei Report-Sätze für Schild2 und Schild3 pflegen. Das ist nicht leistbar.

**Comment by JuergenRichter** [comment]
Ich muss da mal beim Hersteller vom ReportBuilder nachfragen.

**Comment by JuergenRichter** [comment]
Ich habe nun eine Rückmeldung vom Hersteller:
"There is a public class method TraCodeModule.SetLegacyStorage. Call at app startup. "
Das werde ich mal einbauen.

**Comment by JuergenRichter** [comment]
Funktioniert, ich schließe das Issue.
