### ISSUE TITLE
Haken "Neu Zugewandert" in Individualdaten II -> Migrationshintergrund kann nicht gesetzt werden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#553]
Version 3.0.60.9
SVWS: 0.57

Ein Klick auf die leere Box füllt den Haken nicht.

Wenn ein irgendwo sonst gemachter Eintrag das Setzen verhindert, sollte es eine Fehlermeldung geben.

![Einwanderung](https://user-images.githubusercontent.com/116796098/228771734-98454925-30e0-4c07-97b7-d91b1473ac02.png)

**Comment by JuergenRichter** [comment]
Da fehlte die Datenbankanbindung, nun korrigiert
