### ISSUE TITLE
Frage zu "Checkboxen" in Tabellen

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#554]
Bei der in SchILD2 verwendeten Komponente für die Tabellendarstellung wird ja bei logischen Feldern eine Änderung durch einen Doppelklick in der entsprechenden Checkbox gemacht. Bei der in SchILD3 verwendeten Komponente ist das anders, hier reicht ein einfacher Klick. Da ist m.E. die Gefahr groß, dass dabei ein Häkchen aus Versehen gesetzt oder entfernt wird, weil man zufälligerweise in die entsprechende Zelle klickt. Grundsätzlich ist es kein großer Aufwand, das auch so zu programmieren, dass die Änderung nur durch einen Doppelklick erfolgt (wie bisher). Ich stelle das mal zur Diskussion.

**Comment by Raffenberg** [comment]
Prinzipiell bin ich ein Freund von Einzelklicks. Hierzu ist aber ein gewisses Design Voraussetzung, welches auf Einfachklicks optimiert wurde. Der Abbau der schwebenden Fenster ist ein Beispiel dafür. Nach meinem Dafürhalten haben wir mit dem neuen Design an den meisten Stellen eine solche Voraussetzung geschaffen, zumal die User in vielen vergleichbaren Programmen nur noch Einzelklicks machen müssen. Prinzipiell würde ich aber bei allen Feldern das gleiche Klickverhalten empfehlen, so z.B. auch bei den Mahnhäkchen. Unterschiedliche Klick-Verhalten erhöhen meiner Meinung nach Bedienerfehler.

**Comment by AnneSchueller** [comment]
Aufgrund der Bediengeschwindigkeit tendiere ich auch zu Einzelklicks, aber das ist sicherlich auch Geschmacksache.
