### ISSUE TITLE
"Email an alle Lehrkräfte des ausgewählten Schülers senden" über Rechte Maustaste im Schülercontainer führt zu Fehler: #42S22 unkown column 'A.Jahr' in 'where clause'

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#555]
Version 3.0.60.9
SVWS 0.57

"Email an alle Lehrkräfte des ausgewählten Schülers senden" über Rechte Maustaste im Schülercontainer führt zu Fehler: #42S22 unkown column 'A.Jahr' in 'where clause'

![SchILD_Mailbug1](https://user-images.githubusercontent.com/116796098/229170323-075193d6-6775-4590-9083-da1aff81f199.png)

![SchILD_Mailbug2](https://user-images.githubusercontent.com/116796098/229170376-5c43d6f1-e395-4b76-b932-3983f2710f4e.png)

**Comment by JuergenRichter** [comment]
behoben
