### ISSUE TITLE
Auswahl-Filter

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#556]
Bei Schild 2 ist standardmäßig beim Filter I der Status "Aktiv" aktiviert. Bei Schild 3.0.60.9 ist das nicht der Fall. Trotzdem sucht Schild3.0 in sämtlichen Kategorien. Meiner Meinung nach wäre das praktikabel, wie bei Schild 2 den Status "Aktiv" zu aktivieren.

**Comment by AnneSchueller** [comment]
Das würde ich auch bevorzugen. 
Bei der Auswahl von "externe wie aktive Schüler behandeln" bei den Einstellungen wäre es m.E. sinnvoll, wenn dann auch aktive und externe Schüler in der Filtereinstellung als Standard ausgewählt ist.
