### ISSUE TITLE
Dropdown Menü Wahl der "Klasse" im Schülercontainer erzeugt viele Einträge pro Klassen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#559]
Version: 3.0.60.9
SVWS: 0.57

Im Dropdown-Menü zur Wahl der Klasse werden für jede Klasse sehr viele Einträge erzeugt, die alle gleichzeitig ausgewählt werden.

![Klassenwahl](https://user-images.githubusercontent.com/116796098/231105996-0c246dcd-3d3b-4eab-922b-68c6410f184e.png)

**Comment by JuergenRichter** [comment]
Ist schon behoben
