### ISSUE TITLE
Unter akt. Quartal -> Leistungsdaten -> Halbjahr auswählen bleibt das Listenfenster starr, Halbjahr nicht vollständig lesbar

### ISSUE THREAD

**Issue by ADV-Burmeister** [SVWS-NRW/Schild3-BetaTest#56]
Die Spalte, in der die Halbjahre oder Quartale aufgelistet werden, bleibt starr und kann nicht seitlich vergrößert werden, so dass die einzelnen Quartale/Halbjahre nicht gut ablesbar sind.
![grafik](https://user-images.githubusercontent.com/75778386/102055358-0b3ba800-3deb-11eb-9544-ad0c84e99703.png)

Schöne Grüße

ADV-Fachberater 
Holger Burmeister

**Comment by FPfotenhauer** [comment]
Das sieht aber nicht nach der aktuellen Version aus.
In der ist dort schon ein Schieber umgesetzt, der aber bei mir nicht funktioniert.
Man kann zwar "schieben", aber die Position geht imme rwiede rin den Ursprung zurück.

**Comment by JuergenRichter** [comment]
Dass die Position des Schiebers sich nicht verändern lässt, kann ich nicht reproduzieren, bei mir klappt es. Welche Einstellungen sind denn bei den Layoutoptionen der "Individuellen Einstellungen" gemacht?

**Comment by ADV-Burmeister** [comment]
Anscheinend hatte ich noch eine ältere Beta-Version erwischt. Habe alles neu installiert und unter Schild 3.0.8.1 läuft es.
