### ISSUE TITLE
Gruppenprozess "Abschnittsdaten löschen" löscht stattdessen die Schüler komplett

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#560]
Version: 3.0.60.9
SVWS: 0.57

Siehe Titel. Der Abschnitt wir zwar wie gewünscht gelöscht - aber es sind auch die Schüler nach der Ausführung des Gruppenprozesses komplett gelöscht.

![GPBug1](https://user-images.githubusercontent.com/116796098/231107481-abc14515-56c4-4d0b-97e7-18c22383d1e3.png)

![GPBug2](https://user-images.githubusercontent.com/116796098/231107493-749adde1-9a2a-44c3-b3bc-6b6f75dc3330.png)

![GPBug3](https://user-images.githubusercontent.com/116796098/231107500-133c2d7e-9397-4cac-9a38-2943c22183f8.png)

**Comment by JuergenRichter** [comment]
Frage: War "2022/23 1.Hj." der "aktuelle" Abschnitt?

**Comment by JuergenRichter** [comment]
Dazu eine Erläuterung: Die Angaben z.B. zu Jahrgang und Klasse wurden in SchILD2 an zwei Stellen gespeichert:
-Bei den "Stammdaten" der SuS
-Bei den "Lernabschnittsdaten"
Bei einer Änderungen an einer Stelle wurde diese an der anderen Stelle ebenfalls umgesetzt. Wenn in SchILD2 die aktuellen Lernabschnittsdaten gelöscht wurden, waren die Angaben zu akt. Abschnitt immer noch bei den Stammdaten vorhanden.

In Schild3 ist es aber so, dass alle "zeitabhängigen" Angaben (z.B. zu Jahrgang und Klasse) nur noch in den Lernabschnittsdaten gespeichert werden. Wenn man also die aktuellen Lernabschnittsdaten löscht, geht damit auch die Information verloren, in welcher Klasse und in welchem Jahrgang die SuS sind (z.b. waren, wenn man die Lernabschnittsdaten eines vergangenen Abschnitts löscht). Es stellt sich mir daher die Frage, ob der Gruppenprozess nicht mehr schaden kann als Nutzen bringt. Evtl. sollte man ihn nur auf zukünftige Abschnitte beschränken, wenn z.B. ein vorzeitig durchgeführter Abschnittswechsel (für die Planung des neuen Abschnittes) rückgängig gemacht werden soll.
Stelle ich mal zur Diskussion.

Übrigens: Die SuS sind natürlich noch da, nur halt ohne Jahrgang und Klasse.

**Comment by FrodBRA** [comment]
Ja, 22/23 1. JH: der letzte in der DB und der aktuelle der Schule.

Der Gruppenprozess hat so einen eher eingeschränkten Nutzen und birgt eher eine sehr große Gefahr. Auch in dem vorgeschlagenen Fall, dass ein vorzeitiger Abschnittswechsel zurückgedreht werden soll, würde ja im Fall, dass die Schule auch schon im neuen Abschnitt ist, wieder alles gelöscht werden.

D.h. man bräuchte einen neuen Gruppenprozess, mit dem sich ein vorheriger Abschnitt als "aktuell" setzen lässt und Jahrgang/Klasse aus diesem übernimmt, um dann alle neueren zu löschen? Das würde ja den Nutzen "Es gibt einen anschließenden Abschnitt zu viel und der soll entfernt werden" umsetzen?

**Comment by FrodBRA** [comment]
Vorschlag für den Hinweis:

> Achtung: Entfernt dieser Gruppenprozess einen Abschnitt, wird die Zuordnung der Schüler zu ihren Klassen und Jahrgängen entfernt. Wird der "aktuelle Abschnitt" entfernt, werden die Schüler ohne Klasse und Jahrgang sein.

**Comment by AnneSchueller** [comment]
Das Löschen zukünftiger (nicht aktueller) Abschnitte klappt auf jeden Fall. 

Ich würde es befürworten, wenn der GP für aktuelle Abschnitte ausgegraut ist und nur auf zukünftige Abschnitte angewendet werden kann oder kommt das Szenario vor, dass man gruppenweise einen aktuellen Abschnitt löschen möchte?

**Comment by JuergenRichter** [comment]
Ich kann mir auch nicht vorstellen, dass der Gruppenprozess für den aktuellen (oder einen vergangenen) Abschnitt Sinn macht. Mein Vorschlag: 
-Die Beschriftung wird umgeändert z.B. in "Zukünftige Abschnittsdaten löschen"
-Der Prozess steht nur zur Verfügiung, wenn es überhaut solche Daten gibt
-Für die Auswahl stehen nur zukünftige Abschnitte zur Verfügung (das dürfte i.d.R. nur einer sein)
-Es kommt trotzdem ein Hinweis, dass evtl. schon für den Folgeabschnitt eingtragene Klassen/Jahrgangszuordnungen verloren gehen.

**Comment by Raffenberg** [comment]
Bei der Versetzung vor den Sommerferien nimmt man schon mal SuS mit ins nächste Halbjahr, die die Schule dann doch verlassen. Man muss diese SuS dann händisch auf Abgänger Setzen und für ASDPC den akt. Abschnitt löschen. Sonst kommt es da zu Problemen.
Gleiches entdeckt man auch gerne im Oktober für SuS, die im ersten Halbjahr nach einen Abschnitt angelegt bekommen haben, aber da auch die Schule schon verlassen hatten.
Vergangene zwei Abschnitte zu löschen ist deshalb immer mal notwendig.
Generell würde ich den Benutzer hier nicht einschränken wollen. Er soll ruhig jeglichen Abschnitt löschen dürfen.

**Comment by Raffenberg** [comment]
Nicht unbedingt. Was ist mit Schülern, die nach einem Jahr o.ä. wieder an die Schule zurückkehren und eine berechtigte Lücke in der Laufbahn haben. Was, wenn diese Lücke erst im Nachgang durch den Gruppenprozess "erzeugt" wird. Ich würde die Schuljahresabschnitts_ID nur dann anfassen, wenn der aktuelle (letzte) Lernabschnitt gelöscht wird.

In der Praxis war bisher das Vorgehen z.B. so:
Ein Schüler hat einen Lernabschnitt in der 9A 1.Hj. Dieser soll gelöscht werden. Man stellt momentan zunächst unter Individualdaten I die Klasse 8A 2. Hj ein und löscht danach den Lernabschnitt 9A 1.Hj. Anschließend bekommt der Schüler den Status Abgänger.

**Comment by FrodBRA** [comment]
> Ein Schüler hat einen Lernabschnitt in der 9A 1.Hj. Dieser soll gelöscht werden. Man stellt momentan zunächst unter Individualdaten I die Klasse 8A 2. Hj ein und löscht danach den Lernabschnitt 9A 1.Hj. Anschließend bekommt der Schüler den Status Abgänger.

Genau das geht, so wie ich das verstanden hatte, ja nicht mehr. Es gibt keine gesondert in den Individualdaten I gespeicherte Klasse mehr, sondern die wird automatisch aus dem aktuellen Lernabschnitt geholt. Löscht man diesen, ist die Klasse auch in den Schülerdaten nicht mehr vorhanden.

Oder war hier mein Verständnis des Problems nicht korrekt?

**Comment by Raffenberg** [comment]
Ich wollte nur darauf hinweisen, dass es mehr Szenarien gibt, den aktuellen oder den zurückliegenden Abschnitt für die Statistik zu löschen, als man denkt.

In Schild3 muss das äquivalent zu handhaben sein.

**Comment by JuergenRichter** [comment]
Die Klassen, in der der Schüler in den einzelnen Halbjahren war, sind ja immer noch vorhanden. Es muss nur bei den Stammdaten des Schülers ein gültiger Bezug auf einen "Schuljahresabschnitt" vorhanden sein, für den es auch einen Lernabschnittsdatensatz gibt.
Beispiel:
Es wird für einen Schüler ein Lernabschnitt gelöscht (z.B. der für den "Schuljahresabschnitt" 2022/23 1. Hj. Wenn beim Schüler aber als aktueller Schuljahresabschnitt ebenfalls 2022/23 1.Hj eingetragen ist, wird über den internen Automatismus wieder für diesen Schüler ein neuer Lernabschnitt für 2020/23 1. Hj. angelegt. Deshalb meinte ich, dass bei Löschen eines Lernabschnittes beim den Stammdaten ein anderer Schuljahresabschnitt eingetragen wird (zu dem es einen Lernabschnitt gibt). Ein Möglichkeit wäre, den vorherigen Schuljahresabschnitt 2021/22 2. Hj. einzutrgen (bzw. dessen ID).

**Comment by JuergenRichter** [comment]
Nochmal zum Verständnis:
Sowohl bei den Stammdaten der SuS als auch bei den Lernabschnittsdaten gibt es ein Feld "Schuljahresabschnitts_ID". Der Inhalt gibt an, in welchem Halbjahr sich der Schüler befindet und welcher Lernabschnitt daher der aktuell gültige ist. Wenn der altuelle Lernabschnitt gelöscht wird, müsste m.E. auch der Eintrag "Schuljahresabschnitts_ID" bei den Stammdaten geändert werden. Andernfalls kommt wird immer wieder ein neuer Lernabschnitt (für die betreffende "Schuljahresabschnitts_ID") angelegt, der Anwedner hat dann den Eindruck, dass das Löschen nicht funktioniert.

**Comment by Raffenberg** [comment]
Nach meinem dafürhalten ist das ein konseqeuntes Vorgehen und sollte so umgesetzt werden.

**Comment by JuergenRichter** [comment]
Habe ich jetzt so umgesetzt:
Wenn ein Lernabschnitt auf dem Karteireiter "Akt. Halbjahr" gelöscht werden soll, wird geprüft, ob dies der aus Sicht des Schülers aktuelle Abschnitt ist. Wenn das nicht der Fall ist, kann der Abschnitt gelöscht werden, wenn es aber der aktuelle ist, kommt eine Meldung, dass der Abschnitt nicht gelöscht werden kann. Man muss dann dem Schüler  einem anderen Schuljahr/Abschnitt zuweisen.

Beim Löschen über Gruppenprozess wird wie oben beschrieben vorgegangen

**Comment by AnneSchueller** [comment]
Funktioniert
