### ISSUE TITLE
Wahl von "Merkmal" im Gruppenprozess "Vermerke/Merkmale löschen" führt zu Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#561]
Version: 3.0.60.9
SVWS: 0.57

Der im Titel genannte Gruppenprozess lässt mich bei der Wahl von "Vermerk" im unteren Dropdown-Menü eine Vemerkart wählen.

Wähle ich "Merkmal" führt ein Klick auf das untere Dropdown-Menü zu einem Fehler: qrEigeneSchule_Merkmale: Das Feld 'LangtextLookup' wurde nicht gefunden.

![GP Merkmal](https://user-images.githubusercontent.com/116796098/231166195-580cea82-4032-4eaf-91df-a746ab2a7d96.png)

**Comment by JuergenRichter** [comment]
Behoben
