### ISSUE TITLE
Frage zu Verkehrssprachen

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#563]
Die Verkehrssprachen werden ja jetzt vom SVWS-Server geliefert. Dort gibt es nun zwei Kürzel-Felder:
kuerzel (3-stellig)
iso2 (2-stellig), das ist das in Schild2 verwendete System

Derzeit wird in Schild3 versehentlich das Feld "kuerzel" verwendet, was aber dazu führt, dass keine Verkehrssprachen angezeigt werden (die aus schild2 übernommenen Kürzel haben ja nur 2 Stellen).

Man kann das so ändern, dass Schild3 auch iso2 verwendet. Es gibt im Katalog aber viele Einträge, bei denen iso2 leer ist. Das gibt Probleme bei der Darstellung, wenn nämlich in einem Datensatz aus Schild2 das Feld für die Verkehrssprache leer ist, wird in Schild3 immer "Abron" angezeigt (das ist der erste Eintrag in der vom SVWS-Server gelieferten Liste, bei dem iso2 leer ist). Folgende Optionen gibt es:
-Schild3 verwendet "kuerzel", bei der Migration wird auf "kuerzel" umgeschlüsselt
-Schild3 verwendet "iso2", es werden aber nur Einträge in den Katalog aufgenommen, bei denen iso2 nicht leer ist.

Wenn "kuerzel" verwendet wird, stehen mehr Einträge zur Verfügung.

**Comment by JuergenRichter** [comment]
Ich habe jetzt erst mal die zweite Option umgesetzt ( es werden aber nur Einträge in den Katalog aufgenommen, bei denen iso2 nicht leer ist).

**Comment by AnneSchueller** [comment]
In meiner Datenbank sind auch nur bei den Sprachen null-Werte bei iso2, die in Schild2 nicht gepflegt werden.

Mir ist aufgefallen, dass in Schild2 die Sprache "Tamilisch" existiert, diese aber im SVWS-Server unter der Bezeichnung "Tamil" läuft. Laut google ist beides richtig; die Frage wäre nur, ob das bei der Migration Probleme geben könnte?
