### ISSUE TITLE
Akt Halbjahr -> Leistungsdaten: Kurs nicht löschbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#564]
Version 3.0.60.9
SVWS: 0.5.7

Ich kann eine fehlerhaft eingetragene Kursart nicht löschen.

Im Beispiel hat der Schüler der Q1 das Fach GE, als Kurs wurde durch "Dicke Finger" F6 1 gewählt. Dieser Kurs kann durch markieren und Entf oder Backspace oder auch über Wahl aus dem Dropdown-Menü nicht mehr entfernt werden.

![KursnichtLbar](https://user-images.githubusercontent.com/116796098/231387604-d1b6e96d-4968-4fc5-9d50-4e99f571639e.png)

**Comment by JuergenRichter** [comment]
Es gibt für die Drop-Down-Listen in den Tabellen eine Eigenschaft "LimitTextToListValues". Diese Eigenschaft ist hier auf "true" gesetzt, d.h. man kann nur existierende Einträge wählen. Das ist im konkreten Fall natürlich kontraproduktiv. In anderen Fällen (z.B. beim Fach) sollte es aber nicht möglich sein, einen Zelleninhalt zu löschen. Die Frage ist: Bei welchen Spalten mach das Löschen eines Zelleninhaltes Sinn, bei welchen nicht?

Hinweis: Wenn "LimitTextToListValues" auf false gesetzt ist, bedeutet das, dass man zwar irgend einen Text eintippen kann, dieser wird aber nur gespeichert, wenn die zugrunde liegende "Lookup-Liste" diesen Wert (also z.B. Kurs) auch tatsächlich enthält. Es besteht also keine Gefahr, dass ungültige Werte eingegeben werden können, das Löschen des Feldinhaltes wird aber ermöglicht.
