### ISSUE TITLE
Akt. Halbjahr -> Leistungsdaten: Fach nicht eintragbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#565]
Version: 3.0.60.9
SVWS: 0.5.7

Das Eintragen von Fächern ist mitunter sehr hakelig und funktioniert nicht wie erwartet. Versuche ich ein Fach direkt einzutragen, klappt das nicht, da die Wahl des Dropdown-Menüs nicht übernommen wird. 

![Fach1](https://user-images.githubusercontent.com/116796098/231391843-45c38e58-9b05-4dc4-9bf6-f77c382967ae.png)

![Fach2](https://user-images.githubusercontent.com/116796098/231391856-cfd86472-0041-49ca-8f86-eed157039dde.png)

Nebenbeobachtung: Geht das Dropdown-Menü auf, kann ich darin nicht tippen (z.B. um direkt zu "GE" zu springen).

**Comment by AnneSchueller** [comment]
@FrodBRA : Kann es sein, dass du hier eine DB benutzt, die noch mit einer früheren Version migriert wurde?
Ich beobachte das Problem nur bei "alten" DBs (dort kann ich teilweise gar keine Fächer eintragen oder es kommt zu einer Fehlermeldung)
Bei einer neu migrierten DB habe ich keine Probleme.

**Comment by FrodBRA** [comment]
Manche von diesen Problemen scheinen auch sporadisch aufzutauchen und ich konnte nichts eintragen, nach einigem Herumgeklicke - das ich nicht reproduzieren kann - ging es dann doch.

Ich habe mit 3.0.60.9 und SVWS 0.5.7 migriert. Was besseres haben wir nicht in der FB Cloud.

Ist das eine "frühere Version"? Falls nein, werde ich alles noch einmal komplett neu aufsetzen.

**Comment by AnneSchueller** [comment]
Das ist auf jeden Fall die aktuelle Version.
Ich habe gerade herausgefunden, dass man dort nur dann Eintragungen vornehmen kann, wenn dort ein '*' vor dem Fach steht:
![2023-04-17_123737](https://user-images.githubusercontent.com/79116896/232460930-47b1b5e0-35e3-44fb-b0c7-9b4418f13314.png)

Also man muss vorab auf jeden Fall auf das "+"-Zeichen klicken. 
Funktioniert es damit?

**Comment by JuergenRichter** [comment]
"Also man muss vorab auf jeden Fall auf das "+"-Zeichen klicken."
Wie schon oben beschrieben, ist das ja auch nicht anders, wenn schon Fächer vorhanden sind. Da muss auch der +-Schalter betätigt werden.

**Comment by FrodBRA** [comment]
Ich habe mit 3.0.69.9 noch ein paar Fächer hinzugefügt. Ein Problem konnte ich nicht mehr feststellen. 

Sollte das Issue geschlossen werden und sofern jemand einen neuen Fehler findet, kann ein neues geschrieben werden?

**Comment by AnneSchueller** [comment]
Ja genau. Danke, dass du das nochmal geprüft hast.
