### ISSUE TITLE
Änderungswunsch/Diskussion: Defaultwerte für "Email-Versand" sollten modernen Regeln entsprechen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#568]
![Email](https://user-images.githubusercontent.com/116796098/231480658-973d1fcf-c2f8-4a85-89d3-ce37a6aa87a3.png)

Es sollte m.E. nach die Standardeinstellung sein,
* Mails per BCC zu verschicken
* Bei Lehrern dienstliche Adressen zu bevorzugen
* Bei Schülern dienstliche Adressen zu bevorzugen

**Comment by AnneSchueller** [comment]
Das sehe ich genauso. Hier würde ich die Texte so lassen und nur den Haken als Default-Wert setzen.

**Comment by JuergenRichter** [comment]
Ist umgesetzt, funktioniert mit den neuen Defaults aber nur bei frisch migrierten Datenbanken. Sobald der entsprechende Eintrag in der Datenbank vorhanden ist, wird die Einstellung aus der Datenbank gelesen.
