### ISSUE TITLE
schwarzes Fenster bei Reporteinstellungen

### ISSUE THREAD

**Issue by JTorspecken** [SVWS-NRW/Schild3-BetaTest#57]
![grafik](https://user-images.githubusercontent.com/61317409/102378320-f9622c80-3fc5-11eb-9304-d9f1f6c955a8.png)
Dieser große schwarze Block ist irritierend. Eigentlich hätte ich da die Einstellungen zu den Pfaden für Reorts erwartet. Oder sind diese nicht mehr vorgesehen? Dann müsste das Feld weg.

**Comment by JTorspecken** [comment]
Entschuldigung. War schon bei den abgeschlossenen Themen.

**Comment by FPfotenhauer** [comment]
In meiner Umgebung ist da kein schwarzer Block.

**Comment by JTorspecken** [comment]
Wo könnte denn der Unterschjed sein?

**Comment by FPfotenhauer** [comment]
Auflösung?
Skalierung in Schild3?
Skalierung unter Windows?

**Comment by FPfotenhauer** [comment]
Kann ich das Ticket schließen?

**Comment by JTorspecken** [comment]
Ich habe noch keine Ursache gefunden. Es ist noch immer schwarz.--Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 23.12.20, 13:01 schrieb Frank Pfotenhauer <notifications@github.com>:

   
  Kann ich das Ticket schließen?
