### ISSUE TITLE
Neuaufnahme - Halbjahr wählen

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#570]
Wenn ich einen neuen Datensatz per Einfügen anlege, so kann man bei den ersten Datensätzen immer nur das aktuelle Halbjahr auswählen. 
![S3_Neuaufnahme](https://user-images.githubusercontent.com/130543126/231499761-ef46ba8a-a928-4171-a26c-2cfb063c44b6.png)

Nach einem Neustart ist das Problem behoben.

_Testumgebungen:
Desktop (WIN10) , Surface 6 Pro (WIN10), SchILD v3.0.60, SVWS v0.5.7_

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Zusätzlich kommt bei mir beim zweiten Einfügen nicht mehr die Nachfrage obwohl ich den Haken bei "Nicht mehr nachfragen" nicht gesetzt habe.

**Comment by JuergenRichter** [comment]
Gibt es denn in der Datenbank in der Tabelle "Schuljahresabschnitte" einen Eintrag für das nächste Halbjahr (aus "Sicht" der Schule)?

**Comment by JuergenRichter** [comment]
Das mit dem Nachfragen ist jetzt behoben, man kann jetzt optional auch den Jahrgang für die Neuaufnahme auswählen.
![image](https://user-images.githubusercontent.com/61280188/232020814-2f2b3a75-6dde-4512-af09-f23b2d01e649.png)

**Comment by AnneSchueller** [comment]
Nachdem ich nun auch dieses Problem (bei beiden Auswahlmöglichkeiten steht das gleiche Schuljahr) nicht mehr reproduzieren konnte, habe ich erneut eine DB migriert und festgestellt, dass das Phänomen nur dann auftaucht, wenn eine neu migrierte DB das erste mal gestartet wird.

**Comment by pemichalski** [comment]
Das Problem mit der Anzeige der Halbjahre besteht auch in Version 3.0.64.9:

<img width="611" alt="Halbjahr" src="https://user-images.githubusercontent.com/130543126/233625150-bf1c402b-964c-4da1-ae89-f964d617769a.png">

**Comment by JuergenRichter** [comment]
Ist ein Anzeigeproblem, siehe https://github.com/SVWS-NRW/Schild3-BetaTest/issues/571#issuecomment-1517672312

**Comment by JuergenRichter** [comment]
Wegen der identischen Schuljahre: Ich kann das bei mir nicht reproduzieren. Wurde das in einer ganz frisch migrierten Datenbank gemacht? 
Also: 
Datenbank migriert
SchILD gestartet
Neueingabe gemacht?

**Comment by pemichalski** [comment]
> Wegen der identischen Schuljahre: Ich kann das bei mir nicht reproduzieren. Wurde das in einer ganz frisch migrierten Datenbank gemacht? Also: Datenbank migriert SchILD gestartet Neueingabe gemacht?

Ja. Nach einem weiteren Neustart ist das Problem behoben.

**Comment by JuergenRichter** [comment]
Dann werde ich mal meine Datenbank neu migrieren und das testen.

**Comment by JuergenRichter** [comment]
Ist behoben,
