### ISSUE TITLE
Neuaufnahme - Statistikjahrgang und Klasse können nicht eingetragen werden

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#571]
Bei einer Neuaufnahme können der Statistikjahrgang und die Klasse weder händisch noch per Gruppenprozess eingetragen werden. 
Der Gruppenprozess läuft zwar ohne Fehlermeldung durch, liefert allerdings keine Ergebnisse.
Stößt man den Gruppenprozess ein weiteres Mal an, so liefert SchILD die folgende Fehlermeldung:

![S3_Neuaufnahme _Gruppenprozesspng](https://user-images.githubusercontent.com/130543126/231519655-e5157458-4212-4b54-8bf3-63174925475a.png)

**Comment by AnneSchueller** [comment]
Ergänzung: Auch nach Eintragen des Jahrgangs über den Reiter "aktuelles Halbjahr" lässt sich die Klasse nicht auswählen.

**Comment by JuergenRichter** [comment]
Wurde die Neuaufnahme in SchILD3 gemacht oder handelst es sich um SuS, die in SchILD2 den Status "Neuaufnahme" hatten und dann nach SchILD3 migriert wurden?

**Comment by JuergenRichter** [comment]
Sind denn überhaupt schon "Basisdaten für Schuljahreswechsel..." vorhanden. In SchILD3 ist es ja nicht mehr so, dass man einfach ein Schuljahr auswählen kann. Es müssen erst Einträge in bestimmten Tabellen (Schuljahresabschnitte, Klassen usw.) gemacht werden. Dafür gibt es bei "Verwaltung>>Schule>>Schuljahreswechsel" die Option 2: 
![image](https://user-images.githubusercontent.com/61280188/232001526-40a2b90e-add1-46b2-8051-3dc3e09142af.png)
Wenn diese nicht ausgegraut ist, bedeutet das, dass die Basisdaten für den nächsten Abschnitt noch nicht vorhanden sind.,

**Comment by pemichalski** [comment]
@JuergenRichter: Ich habe die SuS in Schild 3 entsprechend der Vorgehensweise aus Schild 2 neu angelegt. 
@AnneSchueller Mit welcher Datenbank hast du denn getestet?

**Comment by AnneSchueller** [comment]
ich habe das gerade nochmal getestet (Spieldatenbank Gym_22_23)
Ich kann die Klassen sowohl unter akt. HJ also auch mit dem Gruppenprozess eintragen.

**Comment by pemichalski** [comment]
In der Datenbank GY_2022_23b (Schulungsdatenbank aus der Fachberatercloud) funktioniert der händische Eintrag im aktuellen Halbjahr nicht. Der Eintrag per Gruppenprozess klappt.

**Comment by AnneSchueller** [comment]
Problem mit der neuen Version:

https://user-images.githubusercontent.com/79116896/233599401-48a46cc7-0df7-4bfa-90fd-b61bd549effd.mp4

**Comment by JuergenRichter** [comment]
Das ist ein Aktualisierungsproblem. Der Jahrgang wird in der Datenbank gespiechert, aber noch nicht angezeigt. Bei der Neuaufnahme finden folgende Schriite statt:
1. Neuer Schülerdatensatz wird gespeichert und neu geladen (um die ID zu ermitteln)
2. Anschließen wird eine Schuljahresabschnitt angelegt (mit der neuen ID)
3. Danach muss der Schülerdatensatz noch mal geladen werden (um den Jahrgang aus dem Schuljahresabschnitt zu holen)

Schritt 3 ist bisher nicht umgesetzt gewesen, kann aber manuell über den Schalter "Aktualisieren" gemacht werden. Ich habe das nun ergänzt, der Jahgang wird dann korrekt angezeigt.

**Comment by AnneSchueller** [comment]
Ich überlege gerade, ob es für den Anwender nicht hilfreich wäre, wenn man optional in dem Neuaufnahme-Fenster auch die Klasse auswählen kann? Dann müsste man anschließend nicht auf den Reiter "aktuelles Halbjahr" wechseln, um die Klasse nachzutragen.

**Comment by JuergenRichter** [comment]
Wäre grundsätzlich kein Problem.

**Comment by JuergenRichter** [comment]
Habe ich mal umgesetzt, legen in Kürze Update auf Github.

**Comment by AnneSchueller** [comment]
Klappt soweit, außer für Status "Aktiv". Das ist in einem anderen Issue
