### ISSUE TITLE
Menü "Sortierreihenfolge ändern" - Pfeile zum Ändern der Reihenfolge vertauscht 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#572]
Im Menüfenster "Sortier-Reihenfolge ändern" wurde die Funktionalität der Pfeile zum Ändern der Reihenfolge vertauscht: der Pfeil, der nach unten zeigt, sorgt beispielsweise  dafür, dass eine Datenart nach oben verschoben wird. 

![Sortierreihenfolge_ändern_Pfeile_vertauscht_2](https://user-images.githubusercontent.com/130543126/231531962-56f548a1-91a5-470c-8897-7f799e3ea179.png)
Zudem sollte die Überschrift des Menüs in "Sortierreihenfolge ändern" geändert werden.

_Testumgebung:
Desktop (WIN10) , SchILD v3.0.60, SVWS v0.5.7_

**Comment by FrodBRA** [comment]
Das wurde schon reportet und sollte, m.E. nach in einer der neuen Versionen gefixt sein.

**Comment by AnneSchueller** [comment]
Ja stimmt, das wurde hier schon gepostet:
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/548
Danke für den Hinweis.
