### ISSUE TITLE
Schnellfilter (Schild 2 Layout) - einzelne Klassen werden mehrfach angezeigt 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#573]
Im Schnellfilter Klasse (SchILD 2 Layout)  werden die einzelnen Klassen bzw. Jahrgangsstufen mehrfach angezeigt:
Test-DB: GY_2022_23a
![Schnellfilter-Anzeige](https://user-images.githubusercontent.com/130543126/231584675-2cd16b8b-47ac-418f-94df-759617615977.png)
Test-DB: GS_2022_23
![Schnellfilter-Anzeige_GS](https://user-images.githubusercontent.com/130543126/231686310-6e465712-2818-4a7a-b1ad-fbf0dd319e5d.png)

**Comment by AnneSchueller** [comment]
Ergänzung:
Klickt man nach dem Start von Schild3 auf Auswahl und dann wieder zurück auf Schüler, so ist die Auswahl wieder korrekt

**Comment by JuergenRichter** [comment]
Ist schon behoben
