### ISSUE TITLE
Gruppenprozess Wiedervorlage - Wechsel zwischen Bereichen führt zu einer Zugriffsverletzung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#574]
Wenn man im Bereich Gruppenprozesse den Gruppenprozess "Eintrag in die Wiedervorlage machen" auswählt und anschließend in den Bereich Schüler wechselt, kommt es bei einem erneuten Wechsel in den Bereich Gruppenprozesse zu einer Zugriffsverletzung.
Dabei ist es egal, ob der Gruppenprozess angestoßen wurde oder nicht.

![Gruppenprozess wechsel](https://user-images.githubusercontent.com/130543126/231705479-0cfd4c59-8778-44be-8ecd-e42e910094a6.png)
![Gruppenprozess wechsel_Fehlermeldung](https://user-images.githubusercontent.com/130543126/231705500-ad504d51-c5e5-45e3-99d8-aef112f5a248.png)

Test-DBs:
GY_2022_23a
GS_2022_23

**Comment by JuergenRichter** [comment]
Behoben
