### ISSUE TITLE
Gruppenprozess Lernabschnitt individuell anlegen/bearbeiten fehlt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#575]
siehe Titel

**Comment by JuergenRichter** [comment]
Der Gruppenprozess fehlt mit Absicht, und zwar aus folgendem Grund (siehe dazu auch https://github.com/SVWS-NRW/Schild3-BetaTest/issues/576):

Im Gegensatz zu Schild2 sollte es eigentlich zu jedem Schülerdatensatz mindestens einen Lernabschnittsdatensatz geben. In Schild2 wurde ein Lernabschnitte nur für SuS mit Status "Aktiv" angelegt (das hatte was mit der Statistik zu tun), entweder automatisch (beim Scrollen durch die Schülermenge) oder über die beiden Gruppenprozesse "Lernabschnitte mit Standardangaben angelegen" oder "Lernabschnitt individuell anlegen...".

In SchILD3 ist das anders: Wenn in SchILD3 ein neuer Schülerdatensatz angelegt wird, so wird beim Speichern auch automatisch ein Lernabschnitt für den "Schuljahresabschnitt" (d.h. Schuljahr/Halbjahr) angelegt, der beim Anlegen des Schülerdatensatzes gewählt wurde (unabhängig vom Status des Schülers). Daher sind keine Gruppenprozesse notwendig, Änderung in den Lernabschnittsdaten (z.B. Klasse, Jahrgang) sind durch den Gruppenprozess "Individualdaten ändern" abgedeckt. Sofer ers hier noch Probleme gibt, werden diese behoben.

Es gibt aber wohl noch ein Problem bei der Migration von SuS mit Status "Neuaufnahme", diese haben ja in SchILD2 keinen Lernabschnittsdatensatz, derzeit wird bei der Migration auch keiner angelegt (siehe https://github.com/SVWS-NRW/Schild3-BetaTest/issues/576). Das sollte m.E. aber bei der Migration angepasst werden, dafür einen (ansonsten nutzlosen) Gruppenprozess in SchILD3 zu erstellen, macht m.E. keinen Sinn.
