### ISSUE TITLE
Gruppenprozesse - Individualdaten ändern - zweimalige Ausführung führt zu einer Zugriffsverletzung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#577]
Ähnliches Muster wie in Issue #574 : 
wenn man den Gruppenprozess **Individualdaten ändern** für eine Schülergruppe ausgeführt hat und danach einen weiteren Gruppenprozess anstößt, kommt es zu einer Zugriffsverletzung:

![Gruppenprozess_individualdaten_ändern](https://user-images.githubusercontent.com/130543126/231982598-86724c7c-6282-4d57-b0b6-e4b91718e1a5.png)

![Gruppenprozess_individualdaten_ändern_Fehlermeldung](https://user-images.githubusercontent.com/130543126/231982623-fe6143d7-a67a-4189-9da5-4c612c6247b9.png)

**Comment by AnneSchueller** [comment]
Ergänzung: Ebenfalls erhalte ich Zugriffsverletzungen, wenn ich Zwischen den Optionen Individualdaten ändern -> Sprachenfolge zuweisen ->Individualdaten ändern switche (ohne einen GP auszuführen)
[GP_Zugriffsverletzung.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11231564/GP_Zugriffsverletzung.txt)

**Comment by JuergenRichter** [comment]
Das hat was mit den "Aufräumprozessen" zu tun. In der aktuellen Version (noch nicht veröffentlicht) tritt das bei mir nicht mehr auf. Ich werde heute nochmal eine aktuelle Programmdatei zur Verfügung stellen.
