### ISSUE TITLE
Verwaltung-> Einstellungen -> Benutzeroberfläche -> Wechsel des Stils führt zum Absturz bzw. Fehlermeldung 

### ISSUE THREAD

**Issue by spechtg** [SVWS-NRW/Schild3-BetaTest#579]
Der Wechsel der Benutzeroberfläche von Luna zu Silver führt zum Absturz von Schild.
Der Wechsel von Luna zu Light bringt die Fehlermeldung: Stil "Light" nicht gefunden. Ein Neustart wird abgefragt mit dem Ergebnis, dass beim Starten die selbe Fehlermeldung folgt, der Stil jedoch geändert wurde (wirkt aber eher wie Silver). Ab jetzt ist ein Zurück zu Luna nicht mehr möglich.

**Comment by AnneSchueller** [comment]
Der Wechsel zu Silver funktioniert bei mir; die Fehlermeldung beim Wechsel zu Stil Light kann ich reproduzieren.

**Comment by JuergenRichter** [comment]
Ist behoben, war eine Folge des Wechsels der Ribbon-Komponente
