### ISSUE TITLE
Export für Logineo

### ISSUE THREAD

**Issue by ElaPaul** [SVWS-NRW/Schild3-BetaTest#58]
![grafik](https://user-images.githubusercontent.com/76162003/102483822-9627d700-4065-11eb-82c5-46d8fd7a8d18.png)

Ich vermisse den Export für Logineo

**Comment by FPfotenhauer** [comment]
Der Export wird gerade uprogrammiert, so dass er nicht mehr als DLL genutzt werden muss.
Wenn das fertig ist, wird er dort erscheinen.
