### ISSUE TITLE
Frage zu "Filter auf markierte Schüler"

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#580]
Ich habe mal eine Frage zur Filterung auf markierte Schüler:
Im Gegensatz zu SchILD2 gibt es ja in Schild3 keine "dauerhafte" Markierung mehr (in Schild2 über Doppelklick und Fettschrift). Man kann zwar über die Häkchen in der Schülerauswahl mehrere Datensätze markieren, die Markierung wird aber nicht dauerhaft gespeichert. Für die Filterung auf die markierten Datensätze gibt es folgende Optionen:

1. Die Filterung auf markierte Datensätze wird genauso behandelt wie andere Filterungen, das bedeutet konkret
-Die Option "Filterung auf markierte Schüler" ist erst mal ausgegraut
-Wenn ein Häkchen gesetzt wird, wird die Option aktiv, wenn alle Häkchen wieder entfernt werden, wird auch die Option deaktiviert
-Wenn "Filterung auf markierte Schüler" ausgeführt wird, wird auf diese SuS gefiltert, die Option "Filterung auf markierte Schüler" ist dann wieder ausgegraut
-Das kann dann auch wiederholt werden, d.h. aus der Teilmenge der markierten SuS kann eine weitere "Unterteilmenge" gebildet werden
-Die Filterung wird wieder aufgehoben, indem man auf "Standard-Filter" klickt

Bei dieser Abfolge muss man also (wie bei allen anderen "individuellen" Filtern) wieder auf die "Standard-Auswahl" zurück, um eine erneute Filterung durchzuführen 

2. Die Filterung auf markierte Datensätze merkt sich die vorherige Filterung 
-Die Option "Filterung auf markierte Schüler" ist von Anfang an aktiv
-Wenn sie ausgeführt wird, wird auf die markierten SuS gefiltert, wenn keine markiert sind, wird halt eine leere Datenmenge geliefert 
-Wenn sie erneut ausgeführt wird, wird die Filterung auf die markierten Datensätze wieder zurückgenommen, es wird dann der Filter verwendet, der vor der Filterung auf die markierten Datensätze aktiv war.
-Das bedeutet aber auch, dass keine Wiederholung des Filters auf markierte SuS möglich ist (wie Version 1), da das erneute Ausführen ja wieder den Hauptfilter aktiviert ("toggle-Funktion").

Dieses Vorgehen ist etwas flexibler, wenn man z.B. in einer Klasse (d.h. Hauptfilter auf die Klasse) bei mehreren "Teilmegen" irgendwas machen will (z.B. selektiv einen Report drucken). Dann kann man nach Abarbeitung einer Teilmenge wieder (durch Deaktivierung der Filterung aus die Markierung) wieder zum "Hauptfilter" (=Klasse) zurückgehen und die nächste Teilmenge markieren. Nachteil ist, dass die Verwaltung des ganzen deutlich aufwändiger ist, insbesondere, wenn der "Hauptfilter" nicht nur eine Klassen, sondern ein komplexer Filter ist.

Ich stelle diese Optionen mal zur Diskussion.

**Comment by AnneSchueller** [comment]
Ich fände eine Mischung aus beiden optimal:

__Auswahl markierter Schüler nochmals durch markieren filtern__
Wenn man auf markierte Schüler filtert, wäre es toll, wenn man von dieser Menge nochmal per Haken Schüler auswählen kann, die dann durch erneutes Klicken auf "Markierte Schüler" ausgewählt werden (also wie in Variante 1 beschrieben). Dies wäre auch intuitiv. Dass man bei erneutem Drücken auf "Filter auf markierte Schüler" zur letzten Filtereinstellung zurückkehrt nutzen dann die meisten wahrscheinlich aus Unwissenheit nicht.

__Letzte Filterung Speichern__
Die Idee, dass man irgendwie zur letzten Filterung zurück kommt (Variante 2) finde ich allerdings sehr charmant und wäre für die Schulen auf jeden Fall ein hilfreiches Feature. 
***Ich stelle mal zur Diskussion, ob man hier ein zusätzlichen Button "letzte Filterung laden" oder ähnliches einpflegt***
Ich kann den Aufwand, der dahinter steckt nicht abschätzen; hier sollte natürlich der Kosten/Nutzen Faktor berücksichtigt werden

**Comment by JuergenRichter** [comment]
Der Aufwand ist vermutlich doch geringer als ich zuerst gedacht hatte. Ich würde folgendes vorschlagen, damit beide Optionen kombiniert werden können:

-Der "Filter auf markierte Schüler" funktioniert so wie in meiner Option 1 beschrieben
-Zusätzlich gibt es einen Schalter "Vorherige Filterbedingung verwenden", diese ist nur aktiv, wenn auf markierte SuS gefiltert ist. Dieser Schalter bewirkt, dass die Filterung auf markierte SuS aufgehoben wird, aber eine evtl. zuvor eingestellte Filterung auf Klasse wieder verwendet wird
-Weiterhin gibt es ja die Option "Standard-Filter", wenn man schnell wieder auf die Standard-Ansicht umschalten will

**Comment by AnneSchueller** [comment]
Das finde ich eine gute Lösung.

**Comment by JuergenRichter** [comment]
Zur "Beständigkeit": Diese ist kurz, d.h. bei der nächsten Filterung sind die Häkchen wieder weg. Das muss aus folgenden Gründen auch so sein:
Intern wird der "Häkchenstatus" in zwei Listen geführt: Die eine ist eine Eigenschaft der Grid-Komponente, diese speichert salopp gesagt die Nummern der Zeilen, bei denen die Häkchen gesetzt sind. Für eine Abfrage werden aber die Schüler-IDs benötig, daher gibt es eine zweite Liste, in der diese verwaltet werden. Beide Listen müssen unbedingt synchron verwaltet werden, andernfalls kann folgendes passieren:
Es wird z.B. auf Klasse 10a gefiltert und bei zwei das Häkchen gesetzt, danach wird für diese beiden Datensätze ein Report gedruckt. Danach wird auf Klasse 10b gefiltert, drei andere SuS markiert und ebenfalls was gedruckt. Wenn beim Filtern die beiden Listen nicht geleert werden, hätte das zur Folge, dass beim zweiten Druckvorgang fünf Seiten ausgeben werden. In diesem Fall wären das zwei überflüssige Seiten. Wenn man aber "Drucken" durch "Gruppenprozess auf markierte SuS" ersetzt, kann das zu nicht gewollten Änderungen führen. Daher müssen beide Listen synchron geführt werden, was die Kurzlebigkeit zur Folge hat.
Wenn man was langlebigeres haben will (für die Dauer der Sitzung) würde ich folgendes vorschlagen:
-Es wird eine weitere interne Liste geführt (nennen wir sie "temporäre Liste"), ein Eintrag (Schüler-ID) in diese wird wie bei SchILD2 über einen Doppelklick ausgeführt (erneuter Doppelklick entfernt einen Eintrag), ein solcher Datensatz wird dann wieder in Fettschrift dargestellt.
-Die Filteroption auf markierte Datensätze wird durch "aus temporäre Liste filtern" ersetzt, d.h. eine Filterung auf markierte (mit Häkchen versehene) Datensätze gibt es nicht mehr, da m.E. nicht notwendig (sowohl beim Drucken al auch bei Gruppenprozessen gibt es ja Optionen, das nur auf die markierten Datensätze zu beschränken)
-Der jeweils aktuell Inhalt temporäre Liste bleibt wären der Sitzung erhalten, ist also vergleichbar mit einer "individuellen Schülerliste", nur dass der Inhalt nicht in der Datenbank gespeichert wird (deshalb "temporär")

**Comment by AnneSchueller** [comment]
**Reduzierung der Schüler im Container**
Dies ließe sich mit dem Vorschlag von Herrn Richter gut umsetzen (zweiter Button mit "Vorherige Filtereinstellung verwenden" und zusätzlich die Option den "Filter auf markierte Schüler" ein zweites mal anzuwenden)  

Bei meiner Überlegung hatte ich tatsächlich nicht berücksichtigt, dass bei GP und Reportdruck eine Reduzierung von Schülern im Container gar nicht notwendig ist.
Allerdings wäre diese Option für den Export - so wie er aktuell realisiert ist - hilfreich. Dieser wird derzeit immer auf die im Schülercontainer aufgelisteten Schüler ausgeführt.
Alternativ könnte man überlegen, ob man bei dem Export ebenfalls nochmal Schüler auswählen kann, so wie es auch bei den GP und bei den Reports realisiert wurde. Das hätte auch den Vorteil, dass man nicht nochmal auf "Auswahl" zurückswitschen muss, wenn man merkt, dass die Filtereinstellung falsch ist.

**Temporäre Schülerliste**
Aus meinen Moderationen weiß ich, dass die Schulen die dauerhafte Markierung in Schild2 lieben und ganz traurig sind, wenn ich berichte, dass es diese Funktion in Schild3 nicht mehr in der Form geben wird. 
Allerdings gibt es auch immer große Missverständnisse wann ausgewählt und wann markiert werden muss. 
@Raffenberg Vielleicht macht hier ein Brainstorming am Montag nochmal Sinn

**Comment by JuergenRichter** [comment]
"Allerdings gibt es auch immer große Missverständnisse wann ausgewählt und wann markiert werden muss."
Aus disem Grunde würde ich das ja auch sprachlich trennen:
-Markierte Schüler: Häkchen gesetzt
-Temporäre Liste: Fettschrift
Beim Export könnte man ja ähnlich vorgehen wie bei den Gruppenprozessen: Wenn es SuS gibt, bei denen das Häkchen gesetzt ist, wird die Option angeboten, ob man alle in der Auswahl oder nur die markierten verwenden will.

**Comment by AnneSchueller** [comment]
Wenn ich das jetzt richtig verstehe:
Beim Export würden dann die SuS vorerst angezeigt, die sich im Schülercontainer befinden. Zusätzlich hat man dann hier die Möglichkeit nochmal mit dem Häkchen einzelnen Schüler auszuwählen und nur für diese den Export zu starten?

Bezüglich der temporären Liste mache ich mir nochmal Gedanken. Das praktische an den markierten Schülern ist, dass man in einem Rutsch schnell viele Schüler markiert hat. Da brächte man dann ggf. auch so etwas wie "markierte Schüler in temporäre Liste übernehmen" oder ähnliches. 
Ich überlege auch nochmal, für welche Szenarien eine temporäre Liste sinnvoll ist.

**Comment by JuergenRichter** [comment]
Ich habe für das Brainstorming mal eine Testversion von SchILD3 auf unseren Server gelegt, bei der das mit der "temporären Liste" umgesetzt ist.

"Da brächte man dann ggf. auch so etwas wie "markierte Schüler in temporäre Liste übernehmen" oder ähnliches." 
Das gibt es in der Version (über rechte Maustaste), bitte dort auch mal prüfen, ob die Beschriftungen der Menüpunkte passend sind.

**Comment by Raffenberg** [comment]
Wir sollten das wirklich am Montag diskutieren und geben dann hier Rückmeldung.

**Comment by JuergenRichter** [comment]
Ich habe die Testversion auf dem Server nochmals aktualisiert, da war noch ein kleiner Fehler beim Filtern auf die temporäre Liste drin. Außerdem ist da jetzt testweise die von mir im Github-Issue erwähnte andere Sortierung der Noten drin.

 

Mit freundlichen Grüßen aus Bornheim

Jürgen Richter

 

 




Wasser und Umwelt

ribeka GmbH

Johann-Philipp-Reis-Str. 9
53332 Bornheim
Tel.: +49(0)2222-990600
Fax: +49(0)2222-990601
 <http://www.ribeka.com/> www.ribeka.com



Geschäftsführer: Dr. Jürgen Richter, Erich Berger
Amtsgericht Bonn HRB 8423

 

Von: Raffenberg ***@***.***> 
Gesendet: Donnerstag, 20. April 2023 13:28
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: JuergenRichter ***@***.***>; State change ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Frage zu "Filter auf markierte Schüler" (Issue #580)

 

Wir sollten das wirklich am Montag diskutieren und geben dann hier Rückmeldung.

**Comment by Raffenberg** [comment]
Hallo Herr Richter,
wir haben das Thema der Markierung nochmals diskutiert. Wir sind der Meinung, dass das Setzen der Häkchen (Auswählen) die gleiche Funktionalität wie das Markieren eines Schülers haben soll und damit diese ablöst. Die Markierung der SuS ließ eigentlich keine Wünsche offen, musste halt nur immer manuell demarkiert werden. Das halten wir aber für den einfachsten und besten Weg.
Damit müssten die Häkchen dann auch einen Neustart von Schild überleben.
Schön wäre es zudem, wenn sich der Export auch nur auf SuS beziehen könnte, die  markiert sind, damit man die SuS nicht zwingend mit der Pinnadel auswäheln muss. Das ist aber kein muss, sondern wäre nur optional, wenn das einfach umzusetzen ist.

Momentan kann man die Häkchen sehr leicht massenhaft setzen, indem man den ersten SuS markiert und dann die Maus bei gedrückter Maustaste nach unten zieht. Es wäre schön, wenn diese Funktionalität erhalten bliebe.
