### ISSUE TITLE
Schüler - Schwarze Balken im Reiter Laufbahninfo

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#581]
Im Reiter Laufbahninfo des Bereichs Schüler werden als erster Eintrag bei den Vermerken, Sprachenfolgen, Sprachprüfungen und erreichten Abschlüssen schwarze Balken angezeigt. 

![Vermerke_Balken](https://user-images.githubusercontent.com/130543126/233003163-0902299c-9c40-420f-ac5f-75257e8d645a.png)

**Comment by JuergenRichter** [comment]
Das Problem konnte ich gestern unter der folgenden Umgebung auch feststellen:
SchILD wurde auf einem "Remote-Server" gestartet, und zwar nicht über eine Remote-Desktop-Verbindung, sondern über einen Web-Zugang. Nur dann trat das Problem auf. Als Ursache haben sich falsche Registry-Einträge für die Spaltenbreiten herausgestellt, warum die nur beim Web-Zugriff auftraten (bei Remote-Desktop funktionierte es einwandfrei), konnte noch nicht geklärt werden. Wir haben das aber nun so gelöst, dass bei Laden der Spaltenbreiten aus der Registry geprüft wird, ob ein Wert einen gewissen minimalen oder maximalen Wert überschreitet. Wenn das der Fall ist, werden Defualt-Werte verwendet. Danach trat das Problem unter den beschriebenen Bedingungen nicht mehr auf.

**Comment by JuergenRichter** [comment]
Ich schließe das Thema mal, wenn es weiterhin auftaucht, bitte wieder öffnen.

**Comment by Raffenberg** [comment]
In der Version 3.0.67.9 sind bei mir immer noch schwarze Balken enthalten. Zu sehen sind diese unter
Schüler -> Individualdaten II -> Besondere Merkmale
Schüler -> Erziehungsberechtigte -> Erziehungsberechtigte
Schüler -> Erziehungsberechtigte -> Telefonnumnmern
Schüler -> Schulbescuh -> Alle bisher besuchten Schulen
Schüler -> Weitere Adressen -> Adressen
Schüler -> Aktuelles Halbjahr ->Leistungsdaten -> Fächer
Schüler -> Aktuelles Halbjahr -> Fehlzeiten
Schüler -> Laufbahninfo -> Überall!
Schüler -> Fördermaßnahmen
Schüler -> Einwilligungen

**Comment by JuergenRichter** [comment]
Bitte mal den Registry-Editor (regedit.exe) starten, dort den Eintrag "HKEY_CURRENT_USER\Software\SchILD3000\frm_Hauptformular" öffnen.
Dort bitte mal die Einträge "grdErz_..." prüfen. Was für Werte stehen da in der Spalte "Daten" (die Werte in Klammern sind die Dezimalwerte)
