### ISSUE TITLE
Problem bei Noteneingabe

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#582]
Wenn in SchILD3 Noten in der Oberstufe (oder in der SekI bei Einstellung "erweiterteNoten in Sek I") eingegeben werden, wird bei einer Eingabe von „2“ in der Notenliste auf den ersten Eintrag gesprungen, der mit „2“ beginnt. Das ist bei der Sortierung, die für die Notenliste verwendet wird, aber der Eintrag 2+. Es ist dann nicht möglich, über die Tastatur eine „2“ auszuwählen, das geht nur durch Aufklappen der Liste, dort kann dann „2“ gewählt werden (für alle anderen Noten mit Tendenzen gilt das genauso). Das ist aber unbequem. In SchILD2 konnte das durch einen Trick vermieden werden. Da in SchILD3 ein anderes Grid-Objekt verwendet wird, geht das hier aber nicht. Eine mögliche Lösung wäre es, wenn der SVWS-Server (der ja die Notenliste liefert) neben der vorhandenen Sortierung auch eine weitere Sortierung liefern könnte, die dann wie folgt wäre
1
1+
1-
2
2+
2-
Usw.
 
Das würde dann dazu führen, dass bei Eingabe von „2“ auch auf „2“ in der Notenliste gesprungen wird (weil es der erste Wert ist, der mit „2“ beginnt), die Eingabe von „2-„ oder „2+“ über die Tastatur wäre aber auch kein Problem. Als Alternative könnte man auch gar keine Liste hinterlegen, dann müsste aber eine Prüfung nach der Eingabe erfolgen, ob die Eingabe gültig ist. Das wäre aber aufwändiger.

**Comment by JuergenRichter** [comment]
Ich habe testweise die Notenliste nach dem Notenkürzel sortiert. Dann funktioniert die Eingabe über die Tastatur. Allerdings erscheint die "Minus-Note" vor der "Plus-Note". Wenn das kein Problem ist, wird kein zusätzliches Sortierfeld vom SVWS-Server benötigt.

![image](https://user-images.githubusercontent.com/61280188/233349356-72cdb4ad-8ae3-43c8-b718-9c08125b06b3.png)

**Comment by AnneSchueller** [comment]
Erst minus dann plus finde ich sehr ungewohnt.
Optimal ist sicherlich 

2
2+
2-
usw.

Wenn das nicht realisiert werden kann durch Anpassung des SVWS-Servers, fände ich die aktuelle Variante schöner. Aber das ist sicherlich Geschmackssache.

**Comment by FPfotenhauer** [comment]
Ob jetzt + oder -  zuerst kommt, ist sicherlich egal, es ist ja so oder so nicht die "korrekte" Sortierung.

**Comment by FPfotenhauer** [comment]
Kann man bei der Schnelleingabe in der Komponente  nicht "best hit" statt "first hit" auswählen?

**Comment by JuergenRichter** [comment]
Prüfe ich
