### ISSUE TITLE
Beim Start - Passworteingabe und Löschfristen-Check - taucht SchILD nicht in der Taskleiste auf

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#583]
Version 3.0.65.9

Beim Start taucht SchILD nicht in der Startleiste auf. Das ist insofern für den Workflow ungeschickt, da SchILD beim Start ein paar Sekunden braucht und dann hinter anderen Fenstern verschwindet und nicht ersichtlich ist, ob es tatsächlich gestartet ist. 

Eventuell werden auch mehrere SchILD Instanzen gestartet, die dann alle hinter der täglichen Unordnung verschwinden.

Entweder müssen die verdeckten Fenster bei der Suche minimiert werden oder man muss über Alt+Tab durchschalten.

Wäre es möglich, dass SchILD direkt beim Start einen Eintrag in der Taskleiste bekommt?

![NoTask](https://user-images.githubusercontent.com/116796098/233611452-08f8a853-2096-4f1b-a77e-c1ce53e99285.png)

**Comment by JuergenRichter** [comment]
Eintrag in der taskliste sollte jetzt direkt beim Start erscheinen

**Comment by FrodBRA** [comment]
Mit 3.0.71.9 getestet. SchILD taucht ab Start und durchgehend bis zur Verwendbarkeit in der Taskleiste auf

Issue geschlossen.
