### ISSUE TITLE
Darstellungsfehler bei hohen Auflösungen/Skalierung: In Kopfzeilen werden zweizweilige Einträge oben und unten abgeschnitten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#584]
Version3.0.65.9

Siehe Titel und Screenshot

![Zweizeilig](https://user-images.githubusercontent.com/116796098/233612667-79f2dd61-8dc2-4eaa-9eea-74eee40e7887.png)

**Comment by AnneSchueller** [comment]
Das Problem habe ich bei mir nicht, da werden die Einträge in einer Zeile geschrieben
@JuergenRichter : kann das daran liegen, dass hier nur die schild3.exe getauscht wurde, aber nicht die anderen Dateien, (beispielsweise die Schild_Icons.db3, die bei dem internen Update mit dabei war?)

**Comment by JuergenRichter** [comment]
Nein, ich vermute, dass liegt irgendwie daran, dass die Grafiktreiber die Länge von Texten unterschiedlich "interpretieren". Ich werde mal die Höhe der Schalter etwas großzügiger gestalten, damit das noch passt. 

@FrodBRA: Wird der Schalter "Verzeichnis in der Dokumentenverwaltung aktualisieren" korrekt angezeigt (dazu muss die Dokumentenverwaltung bei den Einstellungen aktiviert sein). Dieser Schalter ist schon etwas höher, da der Text recht lang ist.

https://github.com/SVWS-NRW/Schild3-BetaTest/issues/584#issuecomment-1517622557

**Comment by FrodBRA** [comment]
@JuergenRichter 

Dieser Schalter hier - oder gibt es noch einen anderen, der hier gemeint ist?

![Zweizeilig2](https://user-images.githubusercontent.com/116796098/233617586-0e902464-76b2-40c2-91f0-f6b25feda381.png)

**Comment by JuergenRichter** [comment]
Es muss nur das Häkchen "Dokumentenverwaltung verwenden" aktiviert sein, dann sollte bei den Schülern der Schalter "Verzeichnis in der Dokumentenverwaltung aktualisieren"  erscheinen (nach Neustart).

**Comment by JuergenRichter** [comment]
Ich meine aber den Schalter auf dem Reiter "Schüler" (wie bei meinem Screenshot weiter oben).

**Comment by JuergenRichter** [comment]
Ich kann das bei hoher Skalierung reproduzieren. Ich hab nun die Breite der Schaltflächen etwas erhöht (Platz ist ja genug da), dann passt es.

**Comment by FrodBRA** [comment]
![Zweizeilig4](https://user-images.githubusercontent.com/116796098/233630691-e6cc650f-4fc5-464b-91f4-cdf654d595e4.png)

(Diese Antwort scheint mittlerweile hinfällig) 

Diese Schaltfläche ist sogar dreizeilig?

**Comment by AnneSchueller** [comment]
Wenn das nun angepasst ist, schließe ich das Issue mal.
