### ISSUE TITLE
SchILD 3 beta Installer - Fehlermeldung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#585]
Der SchILD 3 Installer der Beta Version vom 21.04.23 bricht die Installation unter Windows 11 mit der folgenden Fehlermeldung ab:
<img width="664" alt="Schild 3 beta" src="https://user-images.githubusercontent.com/130543126/233621243-b6203bff-d3f6-48ba-b46c-298d2900cf20.png">

**Comment by FrodBRA** [comment]
Du hast die Datei aber auch in das Verzeichnis von SchILD3 gelegt, oder? Im Schreenshot liegt sie noch im Download-Verzeichnis.

Meine SchILD-Version läuft gerade mit der Datei (Windows 10), die ich über die letzte installierte aus der FB-Cloud mit Installer kopiert hatte.
