### ISSUE TITLE
Verwaltung - Benutzerverwaltung öffnet sich nach Wechsel des Untermenüs nicht mehr

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#587]
Das Untermenü _Benutzerverwaltung_ des Menüs _Benutzer_ im Bereich Verwaltung öffnet sich nicht mehr, falls man nach dem Aufruf des Menüs zu einem der anderen Untermenüs _Kennwort ändern_ oder _Aktuellen Datenbankbenutzer zeigen_ wechselt. Eine Eingabe des Passworts ist zwar möglich, aber das Menü wird nicht angezeigt. 
Wechselt man in das Menü _Schule_ und anschließend wieder in das Menü _Benutzer_, so wird die Benutzerverwaltung ganz normal angezeigt. Ein Wechsel zu einem anderen Menü innerhalb des Bereichs Verwaltung behebt das Problem nicht.

**Comment by pemichalski** [comment]
In der Version 3.0.66.9 besteht das Problem weiterhin.

**Comment by pemichalski** [comment]
Update: In der Version 3.0.67.9 besteht das Problem ebenfalls.

**Comment by JuergenRichter** [comment]
Ist jetzt behoben
