### ISSUE TITLE
Gym: Prüfungsordnung nicht von G8 zu G9 änderbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#588]
Version 3.0.65.9

In der DB handelt es sich um ein Gymnasium, dass die Gliederungen G8 und G9 hat. Bei dem betreffenden Eintrag wurde in Akt. Halbjahr die Gliederung auf G9 gestellt. Ich kann die APO nicht auf G9 umstellen, im Dropdown-Menü steht sie nicht zur Verfügung.

Die betreffende Person ist ein Wechsler und kam nach der 10 in SK zu dieser Schule in die EF.

Auch in den Statistikjahrgängen hatte ich die EF auf G9 gestellt, die APO ist weiterhin nicht änderbar.

(Ich bin nicht 100% sicher, dass es sich um einen Bug handelt; falls nicht, bleibt mir auch zu unklar, wie Gliederung/APO genau umgestellt werden können.)

![PO SII](https://user-images.githubusercontent.com/116796098/233841990-9611c4d4-9d71-4c7b-a13b-3c274ad007d9.png)

Eventuell ist dies mit https://github.com/SVWS-NRW/Schild3-BetaTest/issues/589 verbunden. Und auch mit https://github.com/SVWS-NRW/Schild3-BetaTest/issues/590

**Comment by AnneSchueller** [comment]
@FPfotenhauer: Fehlt der Eintrag beim Server?

**Comment by JuergenRichter** [comment]
Welche Gliederungen sind denn bei der Schule eingestellt?

**Comment by FrodBRA** [comment]
***
G8
G9

**Comment by AnneSchueller** [comment]
Wenn ich das richtig im Kopf habe, bleiben die Bezeichnungen EF, Q1 und Q2 aus Sicht der Statistik auch bei G9 erhalten, oder @FPfotenhauer

**Comment by JuergenRichter** [comment]
Kann es sein, dass der SVWS-Server die falschen Angaben liefert? Ich habe das mal in der SwaggerUI ausprobiert und mir die Prüfungsordnungen liefern lassen, hier die Einträge für die Oberstufe am Gymnasium

 ```
{
    "PO_Schulform": "GY",
    "PO_Krz": "APO-GOSt(C)10/G9",
    "PO_Name": "APO-GOSt(C)10/G9",
    "PO_SGL": "-***-G01-GY*-**_GY8_**-",
    "PO_MinJahrgang": 0,
    "PO_MaxJahrgang": 20,
    "PO_Jahrgaenge": "**_-11-12-13-_**",
    "gueltigVon": null,
    "gueltigBis": null
  }
{
    "PO_Schulform": "GY",
    "PO_Krz": "APO-GOSt(B)10/G8",
    "PO_Name": "APO-GOSt(B)10/G8",
    "PO_SGL": "-***-G01-GY*-**_GY9_**-GY8-",
    "PO_MinJahrgang": 0,
    "PO_MaxJahrgang": 10,
    "PO_Jahrgaenge": "-EF-Q1-Q2-",
    "gueltigVon": null,
    "gueltigBis": null
  }
```

**Comment by AnneSchueller** [comment]
Da stimme ich zu. 
Die Bezeichnungen bleiben bei EF, Q1 und Q2.  
@ThomasBachran : Wird hier noch was ergänzt?

**Comment by ThomasBachran** [comment]
Die Unterscheidung Apo Gost B und C gibt es in der Form nicht mehr. Die Prüfungsordnung ist die APO-Gost als Fortführung der APO-Gost (B). Die Jahrgangsbezeichnungn EF, Q1 und Q2 bleiben bestehen. Der Zusatz "/G8" ist sowieso nicht gut, da es auch in der "G8-Zeit" G9-Gymnasien gegeben hat und es wird auch weiterhin G8-Gymnasien geben.

Die Angaben der Prüfungsordnung stammen aus der Schild-Intern und wurden vor einigen Tagen von Herrn Pfotenhauer aktualisiert.

**Comment by AnneSchueller** [comment]
Danke für die Infos. Dann schließe ich das Issue.
