### ISSUE TITLE
In der Sprachenfolge sind keine beliebigen Jahrgänge eintragbar (z.B. wenn man von SK Jg 10 zu einem G8-Gym geht)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#589]
Version 3.0.65.9
SVWS: 0.5.7

Die DB ist ein Gymnasium in der Gliederung G8. 

Eine Person kam von der SK, Jahrgangsstufe 10 und geht nun im Gymnasium in die EF. 

In der Sprachenfolge sind an der SK fertig belegte Fremdsprachen (z.B. F von 8 bis 10) nicht eintragbar, da der Jahrgang 10 nicht zur Verfügung steht.

![SF_1](https://user-images.githubusercontent.com/116796098/233842169-74727f19-719e-4595-ba2f-904d7f06a4e1.png)

Eventuell ist dies mit https://github.com/SVWS-NRW/Schild3-BetaTest/issues/588 verbunden.

**Comment by JuergenRichter** [comment]
Erledigt
