### ISSUE TITLE
Schwebende Fenster ("weitere Funktionen")

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#59]
Wäre es nicht sinnvoll, auch die schwebenden Fenster der "weiteren Funktionen" als Option fest in das Individualdaten I Frame integrieren zu lassen. Von Vorteil wäre dann auch, dass die Fenster beim Programmstart wieder eingeblendet werden und wie gesagt im Frame positioniert werden. Platz ist genug da. Evtl. könnte das Fenster mit einer Nadel zum fixieren versehen werden.
![image](https://user-images.githubusercontent.com/75179015/102718616-5ec95c80-42e9-11eb-9177-2d4c760b566f.png)

**Comment by JuergenRichter** [comment]
Die Informationen würde man dann aber nur auf dem Karteireiter "Individualdaten I" sehen, bei z.B. den Leistungsdaten wäre die Informationen dann nicht sichtbar. In einem anderen Post wurde das aber (bezogen auf die Fotos) aber gerade gewünscht.

**Comment by Kluesenerm** [comment]
Stimmt. Bei den Fotos sehe ich das auch so. Wir zeigen diese immer bei Konferenzen mit an (wir nutzen nicht das Konferenzmodul). Vielleicht könnte man eine Option (Pinnadel) zum Fixieren einbauen? Dann hätte man die Option und fixierte Fenster wären auch beim Neustart wieder angedockt.

**Comment by FPfotenhauer** [comment]
Momentan lassen wir die Funktion und warten auf Rückmeldung der User.
Ggf. werden wir die Positionen und Größen für den User "merken".
