### ISSUE TITLE
Export von Schnittstellendateien führt zu SQL-Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#591]
Version 3.0.65.9
SVWS: 0.5.7

![Schnitstelle Export](https://user-images.githubusercontent.com/116796098/233851116-04ade6bb-86fc-4de9-a606-e91dee83799e.png)

Soweit wurden Daten geschrieben:

![Schnitstelle Export2](https://user-images.githubusercontent.com/116796098/233851177-f84feb01-8671-4f06-b0c5-5cd0375a8f13.png)

**Comment by JuergenRichter** [comment]
Es scheint die Option "Lehrkräfte: Daten zu lernplattformen" zu sein.

**Comment by JuergenRichter** [comment]
Fehler bei Export von "Lehrkräfte: Daten zu Lernplattformen" behoben

**Comment by JuergenRichter** [comment]
Ich habe mit der Version 3.0.67 (heute auf Github geladen) den Schnittstellenexport mal durchgespielt, da traten keine Fehler mehr auf. Allerdings ist meine Testdatenbank nicht in allen Datenarten gut gefüllt, bitte mal mit unterschiedlichen Datenarten testen.

**Comment by FrodBRA** [comment]
Mit 3.0.71.9 getestet, der Export lief durch. Die Schnittstellendaten sahen nach einer sehr groben Stichprobe von der Struktur her ok aus.

Geschlossen.
