### ISSUE TITLE
Nach dem "Import" von "Excel-Notendateien" schließt sich das Fenster "Import" nicht.

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#592]
Version 3.0.65.9

Dies ist nur ein kleines Detail, doch das Verhalten dieses Fensters weicht vom übrigen Verhalten ab, daher schreibe ich das Issue.

Es gibt nach dem Import von Excel-Notendateien keine Rückmeldung, ob der Import durchgeführt wurde und das Fenster schließt sich nicht und muss manuell geschlossen werden.

**Comment by AnneSchueller** [comment]
+ Rechtschreibfehler im Importfenster "Imprtieren"

**Comment by JuergenRichter** [comment]
Rechtschreibfehler behoben

**Comment by JuergenRichter** [comment]
Ich greife das Thema mal auf: Soll sich das Fenster automatisch schließen? Es könnte ja auch sein, dass der Anwender anschießend weitere Dateien importieren will (z.B. aus einem anderen Verzeichnis).

**Comment by FrodBRA** [comment]
Kommt somit auf "Kann so oder so nützlich sein" herunter und ohne Daten, welcher Usecase überwiegt, ist auche eine fundierte Entscheidung nicht möglich - daher wäre hier wohl der Weg des geringsten Aufwands zu wählen... 

Da Annes Rechtschreibfehler behoben ist, würde ich hier schließen?
