### ISSUE TITLE
Shortcuts - Der Aufruf der Shortcuts Strg+n und Strg+i für den Import/Export von Notendateien funktionieren noch nicht

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#595]
Der Shortcut _**Strg + n**_ zum für den Aufruf des Notenmodulexports scheint falsch belegt zu sein und führt zu einem
Fehler (siehe auch #350 bzw. #594 ):

![Strg n](https://user-images.githubusercontent.com/130543126/234123570-e3c6d858-d160-4de1-b82f-e3158b193f9c.png)

@AnneSchueller @JuergenRichter : Soll ich Issue #594 und Issue #595 zu einem Issue zusammenfassen? Es scheint dasselbe Problem (enm Zugriff) zu Grunde zu liegen.

**Comment by AnneSchueller** [comment]
Die Shortcuts kannte ich noch gar nicht. ;-) 
Das angepasste ENM ist gerade noch in Arbeit, daher würde ich das Issue erstmal zurückstellen.

Ich würde dann https://github.com/SVWS-NRW/Schild3-BetaTest/issues/594 schließen und die Überschrift hier anpassen. 
Ich hoffe, das ist ok so.

**Comment by pemichalski** [comment]
> Ich hoffe, das ist ok so.
Absolut. ;)

**Comment by AnneSchueller** [comment]
Funktioniert jetzt
