### ISSUE TITLE
UI Darstellung beim ersten Start 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#597]
Nach einer Neuinstallation werden der Schnellfilterbereich und der Container beim ersten Start nicht breit genug dargestellt, so dass die Schrift an einigen Stellen abgeschnitten wird. Dieses Problem tritt sowohl bei einem WQHD, einem QHD und einem Full-HD Monitor auf.

![Skalierung nach Neustart](https://user-images.githubusercontent.com/130543126/234506162-2ef8fef4-5354-40d6-af09-6b3cb3b83c3a.png)

**Comment by AnneSchueller** [comment]
Wird das denn richtig dargestellt wenn du die Fenstergröße manuell anpasst?
War das hier ein Schild3 Update oder eine Neuinstallation? Wenn ich das richtig im Kopf habe, sollte die Größeneinstellung nach einem Update erhalten bleiben und nur nach der Neuinstallation muss das einmalig an einigen Stellen angepasst werden.

**Comment by pemichalski** [comment]
Das Problem tritt nur nach einer Neuinstallation auf. Sobald man die Fensterbreite einmal angepasst hat, gib es keine weiteren Probleme mehr.

**Comment by AnneSchueller** [comment]
Diese Anpassungen müssen tatsächlich anfangs einmal gemacht werden. Das betrifft beispielsweise auch einige Spaltenbreiten in den Katalogen.
