### ISSUE TITLE
Schüler - voreingestellte Sortierreihenfolge sollte der Standardsortierung entsprechen (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#598]
Nach einer Neuinstallation von SchILD 3.0.66.9 und dem SVWS-Server ist bei der  voreingestellte  Sortierreihenfolge lediglich die Datenart Name angegeben. In der Version 3.0.65.9 waren es nach einer kompletten Neuinstallation Klasse und Name.
Hier sollte die Default-Einstellung der Standardsortierreihenfolge (->Button) entsprechen: 
1. Klasse, 
2. Name, 
3. Vorname. 

<img width="581" alt="2023-04-27-Sortierung" src="https://user-images.githubusercontent.com/130543126/234853622-133850d5-805f-45f7-817c-9293b8775a95.png">

**Comment by AnneSchueller** [comment]
Ich kann das nicht reproduzieren. Ich habe die SVWS Version 0.5.7.
Schild3 deinstalliert; neu installiert und auch nochmal neu migriert.
Die Sortiereinstellung ist in Schild3 genauso wie sie auch in Schild2 eingestellt war. 
Welche Sortier-Reihenfolge hat denn die migrierte DB in Schild2 gehabt?

**Comment by pemichalski** [comment]
@AnneSchueller Meinen Fehler kann mit der neuen Version 3.0.67.9 nicht mehr reproduzieren. Hier erhält man in der Tat die Sortierreihenfolge, die man in Schild 2 hatte.

**Comment by AnneSchueller** [comment]
Danke für die Rückmeldung. Vielleicht hatten wir da doch irgendwo verschiedene Versionen. Wenn es jetzt läuft schließe ich das Issue mal.
