### ISSUE TITLE
Installation von SchILD-NRW 3

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#599]
Beim Erstellen des Installationswikis sind mir ein paar Inkonsistenzen aufgefallen:

1. Alle Fenster sollten den Titel "Setup - SchILD-NRW 3" tragen. Zumindest meine ich, dass dies der offizielle Name ist, auf den wir uns geeinigt hatten.
2. Im ersten Fenster "Ziel-Ordner" muss es dann im Text auch mehrfach "SchILD-NRW 3" heißen.
3. Im Fenster "Wählen Sie ein Arbeitsverzeichnis" werden einige Umlaute krypisch dargestellt.
4. Der Startmenüordner und der Programmname sollte "SchILD-NRW 3" lauten.
5. In dem Fenster zur Einstellung der Konfigurationsdatei würde ich ebenfalls eine Umbenennung vorschlagen. Anstatt "Konfigurationsdatei" würde ich in Analogie zur Dateiendung von "Verbindungsdatei für SchILD-NRW 3" sprechen.

Bei den einzelnen Datenfeldern im gleichen Konfigurationsfenster habe ich ein paar Verständnisprobleme mit den Überschriften:
- "URL für SVWS-Server": müsste es hier nicht "URL für SVWS-Client" heißen?
- "Port": Sollte man dann hier nicht von "URL-Port" oder "SSL-Port" oder "TCP-Port" oder "https-Port" sprechen?

**Comment by AnneSchueller** [comment]
Zu 1, 2 und 4: Schild-NRW 3 habe ich auch als offizielle Bezeichnung im Kopf. Daher denke ich auch, dass sämtliche Bezeichnungen in den Installations-Fenstern angepasst werden sollten  (auch beim Start von Schild steht Schild3.0 auf dem Hinweisfenster)

Zu 3: Die kryptischen Umlaute habe ich auch. Ich bin mir sicher, dass das neu ist. 

Zu 5: Verbindungsdatei für SchILD-NRW 3 oder Verbindungsdatei zum SVWS-Server oder Verbindungsdatei von SChild NRW 3 zum SVWS-Server?

Bei der Erstinstallation ist hier immer noch das Standardverzeichnis falsch:
![VerzeichnisFehlt](https://user-images.githubusercontent.com/79116896/235753742-f1d2b012-ca2a-44c0-a8a8-cda38dc2ab2b.png)

**Comment by FPfotenhauer** [comment]
Ich habe das geändert, was ich ändern konnte.
Ab der Version 3.0.70 bitte mal testen.
