### ISSUE TITLE
Feld UpdateSprachenfolge wird noch erwartet

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#6]
Ausgangslage: SVWS Server 0.0.30 installiert und damit bestehende Schild 2.0 von MS-SQL nach MS-SQL migriert. Schild 3.0.4.3 installiert OHNE Migration. Mit DB-Config-Tool sdbcfg erzeugt und SchILD gestartet.

Fehler: Schild 3 meldet nach dem Start, dass das Feld UpdateSprachenfolge aus qryEigeneSchule nicht gefunden wird.

Ursache: Schild 3.0.4.3 erwartet noch das Feld UpdateSprachenfolge in der Tabelle EigenSchule, das es in der SVWS-Server-DB nicht mehr gibt.

**Comment by FPfotenhauer** [comment]
Ich habe gerade eine Schild3.exe in die Cloud gelegt, die dieses Problem behebt.
