### ISSUE TITLE
Schuljahre in der Laufbahnübersicht fehlen bei Wechsel des Themes

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#60]
Beim Wechsel der Interface und Icon Themes kann es passieren, dass in den Laufbahninfos die Schulhalbjahre nicht mehr angezeigt werden:
![image](https://user-images.githubusercontent.com/75179015/102718787-59b8dd00-42ea-11eb-81b3-459dff3fc254.png)

**Comment by FPfotenhauer** [comment]
Ich würde das wechseln der Themes mit einem Neustart verbinden.

**Comment by JuergenRichter** [comment]
Bei Wechsel von Thema oder Iconset erfolgt jetzt eine Abfrage, ob das Programm beendet werden soll.
