### ISSUE TITLE
Geschwister suchen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#603]
Unter Individualdaten I / Weitere Funktionen läuft die Funktion "Geschwister suchen" nicht.

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren.

[Geschwistersuche.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11367496/Geschwistersuche.txt)

**Comment by JuergenRichter** [comment]
Behoben
