### ISSUE TITLE
Unterricht löschen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#605]
Wenn ich bei der Statistikvorbereitung über den Reiter "Lehrkräfte" / "Zeitabhängige Daten" / Schaltfläche "Unterricht zeigen" Unterricht bei einem Kollgen lösche, sieht das so aus, als ob er gelöscht werden würde. Es öffnet sich auch das Fenster mit der Nachfrage. Wenn ich OK klicke, wird der Unterricht im Fenster gelöscht und das Fenster schließt sich. Wenn ich mir den Unterricht erneut zeigen lasse, ist er aber wieder da.

**Comment by JuergenRichter** [comment]
Behoben
