### ISSUE TITLE
DB-Fehler bei Export "Jahrgang und Nationalität"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#606]
Version 3.0.67.9
SVWS 0.6.2

Beim Export von Jahrgang und Nationalität kommt es zu einem Fehler mit einem DB-Feld: 
[Siehe Screenshot]

![JagNaT](https://user-images.githubusercontent.com/116796098/235696856-408d13f4-4dba-48c2-ab62-3084b6fc7aad.png)

**Comment by JuergenRichter** [comment]
Behoben
