### ISSUE TITLE
Abfragefenster im Reporteditor (mehrzeilig?) teils unlesbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#608]
Version 3.0.67.9
SVWS 0.6.2

Beim Druck eines Zeugnisformulars war eines der Abfragefenster nicht für mehrzeilige (?) Inhalte ausgelegt. 

Es handelt sich um Anlage04 der gymn. Oberstufe (Abgangszeugnis); der Abschluss ist nicht korrekt gesetzt. Darum soll es gar nicht gehen: die Fenster im Reportexplorer kommen nicht mit den Inhalten, die an sie übergeben werden können, zurecht.

![Bargle](https://user-images.githubusercontent.com/116796098/235710396-fd154a8d-8cdc-45f1-ae44-2fc3dbbc20a4.png)

![Bargle2](https://user-images.githubusercontent.com/116796098/235710537-e137ca11-93c3-46f6-92d6-137810e58ceb.png)

**Comment by JuergenRichter** [comment]
Welche Funktion wird da aufgerufen?

**Comment by FrodBRA** [comment]
```
      iOption := SelectOption('Abschluss und Berechtigung festelegen für: ' + ZeugnisVornameNachnameDruck, 
                              'Mittlerer Schuabschluss;' +                          // 0 
                              'Erweiteter Erster Schulabschluss;' +                 // 1
                              'Erster Schulabschluss;' +                            // 2 
                              'KEINEN Abschluss vermerken;',                        // 3
                              ';');
```

Reicht das?
Es handelt sich bei Gymn Obst Zeugnissen um Anlage 4, "Berechnungen -> Programme", dann "Haupt: schueler: procedure AbschlussErmitteln.

**Comment by JuergenRichter** [comment]
Das reicht

**Comment by JuergenRichter** [comment]
Die Funktio ist überarbeitet worden, bitte im nächsten Update mal tesen. Bei mir funktioniert es einwandfrei.

**Comment by FrodBRA** [comment]
Das Problem tritt in dem Report nicht mehr auf und es wird eine ordentliche Bullet-Point-Auswahlliste angezeigt.

**Comment by AnneSchueller** [comment]
Bei mir klappt das ebenfalls problemlos
