### ISSUE TITLE
Zugriffsverletzung bei Neustart nach Export der Daten für die Statistik 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#610]
Führt man einen Export der Daten für die Statistik durch (Verwaltung -> Statistik für IT.NRW-> Daten exportieren), so tritt das in #609 beschriebene Problem ebenfalls auf. Ein weiterer Aufruf führt zum erfolgreichen Export von sim.txt, uvd.txt, lid.txt und abi.txt. 
Beendet man das Programm anschließend, so tritt nach einem Neustart die folgende Zugriffsverletzung auf:

![Fehler nach Gesamtprüfung](https://user-images.githubusercontent.com/130543126/235763500-0f0e6752-d642-4bcc-b118-46e4368e3947.png)

![Fehler Neustart](https://user-images.githubusercontent.com/130543126/235763514-79c23d02-c669-481e-85f8-dc72d56ffd66.png)

**Comment by JuergenRichter** [comment]
Siehe auch https://github.com/SVWS-NRW/Schild3-BetaTest/issues/610
