### ISSUE TITLE
Große Schriftgrößen bei Windows-Skalierung in Report-Programmierumgebung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#611]
Version 3.0.67.9

Die Schriftgrößen in den Subreport-Tabs und dem Programmier-Fenster sind sehr groß skaliert.

![RepEditProgrammierSchritgr](https://user-images.githubusercontent.com/116796098/235886629-06abee1e-3e63-45eb-b0ae-e7a9e17f2d2b.png)

**Comment by JuergenRichter** [comment]
Bitte mal die Bildschirmeinstellung angeben

**Comment by FrodBRA** [comment]
3840x2160 Pixel, 150% Skalierung (entsprechend der Windows-Empfehlung).

Zweiter Monitor mit 1920*1080 daneben.

**Comment by AnneSchueller** [comment]
Bei einer Skalierung von 150 sieht das bei mir ähnlich aus (mit nur einem Bildschirm)

**Comment by JuergenRichter** [comment]
Welche Skalierung ist denn im ReportDesigner eingestellt?

![image](https://user-images.githubusercontent.com/61280188/236473744-d259adc3-e3da-4194-bc33-d3eff3ba5762.png)

**Comment by AnneSchueller** [comment]
Die Einstellung der Skalierung unter "Entwurf" hat bei mir keinen Effekt auf die Schriftgröße im Programmiereditor (analog wie in Schild2)

**Comment by JuergenRichter** [comment]
Ich kann das teilweise reproduzieren:
Monitor 1920 x 1080, Skalierung 150% (Systemempfehlung 100%): Editor-Schriftart zu groß
Monitor 3840 x 2160, Skalierung 250% (Systemempfehlung 150%): Editor-Schriftart OK
Ich habe mal beim Hersteller nachgefragt.

**Comment by JuergenRichter** [comment]
Ich habe das an den Hersteller des ReportBuilders weitergeleitet, habe auch schon eine Lösung erhalten.

**Comment by JuergenRichter** [comment]
Lösung funktioniert bei mir, schließe das Thema erst mal.
