### ISSUE TITLE
Lehrkräfte (Excel Export) - Skalierung des Fensters

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#612]
Version 3.0.67.9
Betriebssystem: Windows 11
Auflösung Monitor: QHD

Der Zoomfaktor des Vorschaufensters des Excel-Exports der Lehrkräfte ist bei einer empfohlen Skalierung von 150% zu klein:
<img width="704" alt="Skalierung_Excel-Export" src="https://user-images.githubusercontent.com/130543126/236413219-22c9dce5-4f8b-48b0-90c8-77f59c7a068f.png">

**Comment by JuergenRichter** [comment]
Behoben
