### ISSUE TITLE
Mailversand aus Reporting: Klick auf "Erzieher-Adresse verwenden" führt zu SQL-Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#613]
Version 3.0.67.9
SVWS: 0.6.2

Siehe Titel und Screenshot. 

![Mailrep](https://user-images.githubusercontent.com/116796098/236769224-b1a82372-2b31-4e2e-a290-4235168f46e8.png)

**Comment by JuergenRichter** [comment]
siehe #614
