### ISSUE TITLE
Mailversand aus Reporting: Mailfenster zur Bedienung bleibt unklar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#614]
Version 3.0.67.9

Die Bedienung des Fensters "Mailversand aus Reporting" lässt noch Fragen offen und wirkt nicht intuitiv bedienbar:

* Was bedeutet in der Kopfzeile "Achtung: Bitte AbsEnderadresse eintragen"? Ist das das Feld "Empfänger"? Ein anderes Feld in SchILD? Falls ja, sollte ein Fehler generiert werden.

![Mailrep](https://user-images.githubusercontent.com/116796098/236771664-dca33833-042d-4296-b8ff-c83a427fb140.png)

* Wird ein Mailversand an eine "ganze Gruppe" generiert, wie werden die Reports jeweils an alle Personen verschickt? Lässt sich deren Mail automatisch übernehmen?

**Comment by AnneSchueller** [comment]
Dieser Hinweis steht auch schon in Schild2. Ich glaube das hängt damit zusammen, dass man bei dieser Option unter Schildzentral eine noreply Mail verschickt, sodass ggf im Nachrichtentext eine Absenderadresse stehen sollte, wenn man eine Rückmeldung erwartet (ist aber nur eine Vermutung)

Wenn man für Gruppen druckt, gibt es die Option "Erzieheradresse übernehmen" gar nicht. Interessant wäre es zu testen, was passiert, wenn man einen Erzieher-Serienbrief schreibt. 
Das Versenden per Mail klappt bei mir allerdings nicht. Ich habe meine Mailadresse bei den Schüler- und Erzieherdaten hinterlegt. Es sieht auch zunächst so aus, als ob etwas versendet wird, allerdings kommen diese Mails nicht an wenn ich als Serienmail verschicke. Verschicke ich an mehrere Schüler eine Mail (nicht Serienmail) dann kommt diese nur bei dem ersten Schüler an.

Anfangs hatte ich auch öfter diese Problem: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/615
Das kann ich aber irgendwie nicht mehr reproduzieren.

**Comment by JuergenRichter** [comment]
Die Fehlermeldung ist behoben.
Die Meldung in der Überschrift kommt dann, wenn bei den individuellen Programmeinstellungen keine Mail-Adresse hinterlegt ist. Der Text ist jetzt etwas ausführlicher:

![image](https://user-images.githubusercontent.com/61280188/237058856-63ce9ed9-d1ed-4b4a-b0f4-480de9ff7953.png)

**Comment by JuergenRichter** [comment]
Die bei de Einstellungen eingetragene Mail-Adresse wurde nicht korrekt übegeben, ist nun korrigiert. Bei mir funktioniert es nun.
