### ISSUE TITLE
Mailversand aus Reporting: Report wird nicht generiert und angehängt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#615]
Version 3.0.67.9
SVWS 0.6.2

Generiere ich einen Report per "Als Email versenden", wird der Report nicht generiert und angehängt.

Siehe Screenshot.

![Mailrep2](https://user-images.githubusercontent.com/116796098/236773381-1af1e467-3f2a-4ebf-a2bf-b8287f7c1551.png)

C:\Users[...] ist auch nicht mit SVWS-Arbeitsverzeichnis. Ist das eine mögliche Ursache?

Das Problem tritt auch mit ganz einfachen Reports auf, der Fehler liegt also nicht am komplexen Zeugnis.

**Comment by JuergenRichter** [comment]
"C:\Users[...] ist auch nicht mit SVWS-Arbeitsverzeichnis. Ist das eine mögliche Ursache?"
Nein, die PDF-Dateien, die für den E-Mail-Versand erzeugt werden, werden wie folgt zwischengespeichert:
C:\Users\<Benutzername>\Documents\SchILD-Mailanhaenge\<Name der Vorlage>.pdf

Bitte mal prüfen, ob das Verzeichnis "...\Documents\SchILD-Mailanhaenge" existiert. Es sollte eigentlich von SchILD automatsich angelegt werden, sofern es nicht vorhanden ist.

**Comment by JuergenRichter** [comment]
Der Ordner wird im Winddows-Explorer z.B. so angezeigt:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/ef149976-0148-47de-a0c3-2f0818afc961)

Wenn man da aber reinklickt, ändert sich das:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/57821670-fb1e-45a0-9514-e6c07cb561d8)

Ich habe aber gerade festgestellt, dass der Ordner bisher nur bei der Option "Als Serienmail versenden" automatisch angelegt wird. Bei mir war der Ordner vorhanden, da ich vorher mal diese Option gewählt habe. Der Ordner wird nun aber auch bei der Option "Als E-Mail versenden" angelegt.
