### ISSUE TITLE
Export ➜ ZK-Daten erzeugt eine Datei, die "ZP10-Export.txt" heißt (Inkonsistenz?)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#616]
Version 3.0.67.9

Obwohl beliebige Jahrgänge exportiert werden können, wird eine Datei erzeugt, die _ZP10-Export.txt_ heißt.

**Comment by AnneSchueller** [comment]
Heißen die nicht eh bald wieder ZP10 am Gymnasium?
Oder gibt es hier noch andere Zentrale Klausuren, die exportiert werden sollten?
Evtl. ist es sinnvoll, dies nur für die Jahrgänge zuzulassen, die auch Daten für den Export bereithalten?

**Comment by FrodBRA** [comment]
Da der Punkt in SchILD mittlerweile auch ZP10-Daten heißt, kann das Issue geschlossen werden.
