### ISSUE TITLE
Gruppenprozess von SchILD2 "Zeugnisse drucken und Schüler ausschulen" fehlt in SchILD3

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#617]
Version 3.0.67.9

Der im Titel genannte GP wird nicht aufgeführt. 

Möglicherweise könnte es sinnvoll sein, eine Option "anschließend ausschulen" an "Zugeordnete Zeugnisformulare drucken" anzudocken, die dann die Ausschul-Optionen startet?

**Comment by JuergenRichter** [comment]
Ist wohl übersehen worden, wird wieder aktiviert.

**Comment by FrodBRA** [comment]
3.0.71.9: Ich finde den Gruppenprozess nicht. Eventuell bin ich auch nur blöd, wo soll er auftauchen bzw. ist er an irgendeine Bedingung gekoppelt?

Ich habe auch exklusiv die Q2 ausgewählt, ohne dass der Gruppenprozess erscheint.

**Comment by AnneSchueller** [comment]
Mein mir erscheint er auch noch nicht unter Noten/Zeugnisvorbereitung.
@JuergenRichter Ist der GP in der aktuellen Version noch deaktiviert?

**Comment by AnneSchueller** [comment]
@JuergenRichter : Können wir den GP für das nächste Update mit einbinden?
Fehlt noch in Version 3.0.74.10

**Comment by AnneSchueller** [comment]
Die Umsetzung ist etwas irreführend. 
In Schild2 war die Option ein einziger Prozess. Man landete automatisch im Reportexplorer, konnte das Zeugnis drucken und anschließend mit "fertigstellen" die Schüler ausschulen.

Nun muss man nach der Auswahl im GP eigenständig in den Reportexplorer wechseln. Die Zeugnisse drucken und anschließend erneut auf den Reiter GP wechseln, in die Kategorie Noten/Zeugnisvorbereitung wechseln, den GP ausführen, die Einstellungen erneut einstellen (Abschluss, Entlassdatum und co) und dann auf ausführen klicken.

Ich schlage vor, den GP umzubenennen in "Schüler ausschulen" mit dem Hinweis, dass die Zeugnisse vorab gedruckt sein müssen. 
Wie sind hier die Meinungen?

**Comment by JuergenRichter** [comment]
Bisher (SchILD2) war der Ablauf im Fenster "Angaben zur Auschulung festlegen..." beim Klick auf "Zeugnisse drucken" wie folgt:

1) Für die ausgewählten SuS wurden (mit Ausnahme des Status) die "Ausschulungsabgaben" (Entlassdatum, Art des Abschlusses) gespeichert

2) Der Reportexplorer wurde als "modales Fenster" aufgerufen, dort konnte dann das Zeugnisformular ausgewählt und der Druckvorgang gestartet werden. ("modal" bedeutet dabei, dass der Reportexplorer für nachfolgende Schritte explizit geschlossen werden musste)

3) Durch den "modalen Aufruf" kam das Programm danach wieder in das Fenster  "Angaben zur Auschulung festlegen..." zurück, dort konnte dann der Schalter "Fertigstellen" aktiviert werden, über den dann der gewählten Status bei den SuS eingetragen wurde

Dadurch, dass der Reportexplorer jetzt nicht mehr "modal" aufgerufen werden kann (ist ja in die Oberfläche des Hauptfensters intergriert) muss der Vorgang nun wie folgt ablaufen

1) Für die ausgewählten SuS werden alle "Ausschulungsabgaben" (auch der Status!) gespeichert, es wird aber nicht neu gefiltert (was dazu führen würde, dass keine SuS angezeigt würden, da der Status dann ja ein anderer wäre als in den Filterbedingungen)

2) Es erscheint der Hinweis, in die Reportverwaltung zu wechseln und die Zeugnisse zu drucken. Damit ist der Vorgang dann abgeschlossen, die "Ausschulungsangaben"sind ja schon alle gespeichert. Da SchILD3 aber nicht erkennen kann, wann der Anwender mit dem Zeugnisdruck fertig ist (es gibt ja kein "modales Ergebnis" mehr), kann auch keine automatische Aktion folgen. Wenn der Benutzer aber wieder den Standardfilter aufruft, sollten die zuvor bearbeiteten  SuS nicht mehr erscheinen (weil sich der Status ja geändert hat).
