### ISSUE TITLE
Gruppenprozess "Zugeordnete Zeugnisformulare drucken" bietet keine Ablage in das Zeugnisverzeichnis an

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#619]
Version 3.0.67.9

Im normalen Druck aus dem Reportexplorer wird eine Archivierung bei aktivierter Zeugnisarchivierung ins Zeugnisarchiv angeboten. 

Vom Gruppenprozess "Zugeordnete Zeugnisformulare drucken" aus gestartet, wird nur die Dokumentenverwaltung angeboten.

![ZugeordZF](https://user-images.githubusercontent.com/116796098/236894201-f828d74d-9d12-46e1-b720-34ffbfdbe904.png)

**Comment by JuergenRichter** [comment]
Behoben
