### ISSUE TITLE
Versetzungs- und Abschlussberechnung unter akt. Halbjahr zu sehr versteckt.

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#62]
Ich persönlich finden den Schalter "Optionen" für die Versetzungs- und Abschlussberechnung ungeschickt. Ich musste zuerst suchen:
![image](https://user-images.githubusercontent.com/75179015/103020255-5e7acc80-4548-11eb-930d-106d0bcb2e51.png)

**Comment by JuergenRichter** [comment]
Ist nun anders gelöst
