### ISSUE TITLE
"Status"-Auswahl im Filter I enthält zweimal den Eintrag "Ehemalige"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#621]
Version 3.0.67.9
SVWS 0.6.2

![Ehemalige](https://user-images.githubusercontent.com/116796098/237028623-34a72cb9-4003-4e2f-8514-31129c1deed7.png)

**Comment by JuergenRichter** [comment]
Behoben
