### ISSUE TITLE
Filter im Fenster "Gruppenweise Zeugnisausgabe" kann nicht deaktiviert werden

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#622]
Hat man im GP "zugeordnete Zeugnisformulare drucken" einmal auf eine Gruppe gefiltert, kann dieser Filter nicht zurückgestellt werden oder eine andere Gruppe gefiltert werden.

**Comment by JuergenRichter** [comment]
Behoben

**Comment by JuergenRichter** [comment]
Einen Eintrag bei Gruppe kann man nun über "Entf"-Taste löschen
