### ISSUE TITLE
LuPO3 - Fächer: "Gültig in" nicht änderbar bei den unzulässigen/geforderten Fachkombinationen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#624]
In der Fächermaske kann man unzulässige Fachkombinationen und geforderte Fachkombinationen anlegen. Man kann die Haken bei "Gültig in" jedoch nicht ändern.

**Comment by ThomasBachran** [comment]
@Raffenberg: Sollte behoben sein. Kannst du das morgen mal auf dem nightly prüfen und dann das Issue ggf. schließen?

**Comment by Raffenberg** [comment]
@ThomasBachran : Funktioniert jetzt.
