### ISSUE TITLE
LuPO3: Änderungen an der Fächertabelle --> Wechsel zur Schüleransicht nicht möglich

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#625]
Wenn ich in der Fächertabelle bei den Belegungen klicke, kann ich anschließend nicht zur Schüleransicht wechseln. Ich muss den Browser refreshen.

**Comment by ThomasBachran** [comment]
@Raffenberg : Diesen Bug kann ich aktuell auf dem nightly nicht nachvollziehen. Kannst du überprüfen, ob er noch besteht? Ggf. müsstest du mir für die erfolgreiche Reproduktion des Fehlers die genauere Klick-Abfolge nach dem letzten Refresh des Tabs bschreiben.

**Comment by Raffenberg** [comment]
@ThomasBachran : Ich lann das auch im aktuellen nightly noch nachvollziehe. 

Beispiel:
Ich gehe auf Oberstufe - Fächer, entferne dort bei KR die Wählbarkeit in EF.1 bis Q1.2, ich klicke auf Schüler. 
Es passiert dann nichts. Die Ansicht bleibt auf der Fächeransicht.

**Comment by ThomasBachran** [comment]
Ich kann es mit der Beschreibung nicht nachvollziehen. 

Allerdings konnte ich es reproduzieren, wenn ich zuvor bei Schülern der Stufe die Laufbahnplanung aufgerufen hatte, dann die Fächertabelle angepasst habe und anschließend wieder zu Schüler zurückgekehrt bin. Kannst du mal prüfen, ob bei dir der Fehler auch auftritt, wenn du im Schüler-Bereich auf Individualdaten bist.

**Comment by Raffenberg** [comment]
Stimmt. Das ist der eigentliche Auslöser. 
SuS Laufbahnplanung aufrufen - Wechsel zu Oberstufe - Fächer - kein Wechsel zu SuS mehr möglich.

**Comment by ThomasBachran** [comment]
@Raffenberg: Das Problem sollte behoben sein. Bitte morgen auch prüfen.

**Comment by Raffenberg** [comment]
@hmt @ThomasBachran 
Bei mir tritt der Fehler nicht mehr auf. Es dauert zwar etwas, bi der Wechsel vollzogen ist, aber es klappt.
Ich schließe mal das Issue
