### ISSUE TITLE
LuPO3: Defekte Anzeige von Fachkombinationsregeln in der Laufbahnplanung

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#628]
Wenn ich Fachkombinationsrfegel anlege, werden diese folgendermaßen in der Laufbahnplanung angezeigt:

KU als GK erlaubt kein {"bezeichnung":"Informatik","biliSprache":null,"id":193,"istFremdSpracheNeuEinsetzend":false,"istFremdsprache":false,"istMoeglichAbiGK":true,"istMoeglichAbiLK":true,"istMoeglichEF1":true,"istMoeglichEF2":true,"istMoeglichQ11":true,"istMoeglichQ12":true,"istMoeglichQ21":true,"istMoeglichQ22":true,"kuerzel":"IF","kuerzelAnzeige":"IF","projektKursLeitfach1ID":null,"projektKursLeitfach1Kuerzel":null,"projektKursLeitfach2ID":null,"projektKursLeitfach2Kuerzel":null,"sortierung":290,"wochenstundenQualifikationsphase":3} als GK
CH als null erfordert {"bezeichnung":"Physik","biliSprache":null,"id":128,"istFremdSpracheNeuEinsetzend":false,"istFremdsprache":false,"istMoeglichAbiGK":true,"istMoeglichAbiLK":true,"istMoeglichEF1":true,"istMoeglichEF2":true,"istMoeglichQ11":true,"istMoeglichQ12":true,"istMoeglichQ21":true,"istMoeglichQ22":true,"kuerzel":"PH","kuerzelAnzeige":"PH","projektKursLeitfach1ID":null,"projektKursLeitfach1Kuerzel":null,"projektKursLeitfach2ID":null,"projektKursLeitfach2Kuerzel":null,"sortierung":280,"wochenstundenQualifikationsphase":3} als null
D als PJK erfordert {"bezeichnung":"Englisch","biliSprache":null,"id":17,"istFremdSpracheNeuEinsetzend":false,"istFremdsprache":true,"istMoeglichAbiGK":true,"istMoeglichAbiLK":true,"istMoeglichEF1":true,"istMoeglichEF2":true,"istMoeglichQ11":true,"istMoeglichQ12":true,"istMoeglichQ21":true,"istMoeglichQ22":true,"kuerzel":"E","kuerzelAnzeige":"E","projektKursLeitfach1ID":null,"projektKursLeitfach1Kuerzel":null,"projektKursLeitfach2ID":null,"projektKursLeitfach2Kuerzel":null,"sortierung":20,"wochenstundenQualifikationsphase":3} als VTF

**Comment by hmt** [comment]
Zur besseren Lesbarkeit:

Wenn ich Fachkombinationsrfegel anlege, werden diese folgendermaßen in der Laufbahnplanung angezeigt:

KU als GK erlaubt kein 
```json
{
  "bezeichnung": "Informatik",
  "biliSprache": null,
  "id": 193,
  "istFremdSpracheNeuEinsetzend": false,
  "istFremdsprache": false,
  "istMoeglichAbiGK": true,
  "istMoeglichAbiLK": true,
  "istMoeglichEF1": true,
  "istMoeglichEF2": true,
  "istMoeglichQ11": true,
  "istMoeglichQ12": true,
  "istMoeglichQ21": true,
  "istMoeglichQ22": true,
  "kuerzel": "IF",
  "kuerzelAnzeige": "IF",
  "projektKursLeitfach1ID": null,
  "projektKursLeitfach1Kuerzel": null,
  "projektKursLeitfach2ID": null,
  "projektKursLeitfach2Kuerzel": null,
  "sortierung": 290,
  "wochenstundenQualifikationsphase": 3
}
```
 als GK
CH als null erfordert 
```json
{
  "bezeichnung": "Physik",
  "biliSprache": null,
  "id": 128,
  "istFremdSpracheNeuEinsetzend": false,
  "istFremdsprache": false,
  "istMoeglichAbiGK": true,
  "istMoeglichAbiLK": true,
  "istMoeglichEF1": true,
  "istMoeglichEF2": true,
  "istMoeglichQ11": true,
  "istMoeglichQ12": true,
  "istMoeglichQ21": true,
  "istMoeglichQ22": true,
  "kuerzel": "PH",
  "kuerzelAnzeige": "PH",
  "projektKursLeitfach1ID": null,
  "projektKursLeitfach1Kuerzel": null,
  "projektKursLeitfach2ID": null,
  "projektKursLeitfach2Kuerzel": null,
  "sortierung": 280,
  "wochenstundenQualifikationsphase": 3
}
```
 als null
D als PJK erfordert 
```json
{
  "bezeichnung": "Englisch",
  "biliSprache": null,
  "id": 17,
  "istFremdSpracheNeuEinsetzend": false,
  "istFremdsprache": true,
  "istMoeglichAbiGK": true,
  "istMoeglichAbiLK": true,
  "istMoeglichEF1": true,
  "istMoeglichEF2": true,
  "istMoeglichQ11": true,
  "istMoeglichQ12": true,
  "istMoeglichQ21": true,
  "istMoeglichQ22": true,
  "kuerzel": "E",
  "kuerzelAnzeige": "E",
  "projektKursLeitfach1ID": null,
  "projektKursLeitfach1Kuerzel": null,
  "projektKursLeitfach2ID": null,
  "projektKursLeitfach2Kuerzel": null,
  "sortierung": 20,
  "wochenstundenQualifikationsphase": 3
}
```
 als VTF

**Comment by Raffenberg** [comment]
Ja. Ich habe es gerade getestet.

**Comment by ThomasBachran** [comment]
Ich konnte es auch noachstellen.

**Comment by ThomasBachran** [comment]
@Raffenberg: Sollte jetzt behoben sein und kann dann morgen von dir geprüft werden.

**Comment by Raffenberg** [comment]
@ThomasBachran : Die Anzeige ist nun lesbar, aber leider nicht korrekt. "erlaubt kein" und "erfordert" sind in der Schülerlaufbahn vertauscht.

<img width="296" alt="Fachkombi0" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/674a8d44-a0d0-469f-bed6-25b768254a01">

<img width="547" alt="Fachkombi1" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/0beed199-dc9b-43dd-9195-e497be42b815">

**Comment by ThomasBachran** [comment]
Habe ich jetzt getauscht...

**Comment by Raffenberg** [comment]
@ThomasBachran : Funktioniert nun.
