### ISSUE TITLE
LuPO3: Anzeige von Fachkombinationsregeln

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#629]
Ich kenne Schulen, welche sehr viele Fachkombinationsregeln anlegen. Wenn diese alle auf dem Laufbahnreiter angezeigt werden, wird die Ansicht ggf. unübersichtlich.

Vielleicht wäre es gut, wenn man irgendwo eine zentrale Einstellung, z.B. bei der Fächertabelle für Lupo3, markieren könnte, mit der man regeln kann, dass Fachkombinationsregeln bei einem Schüler nur dann angezeigt werden, wenn dieser eines der beiden relevanten Fächer belegt hat. So können die Schulen steuern, ob immer eine Anzeige kommt, oder nur bei Bedarf.

Die Ausrufezeichen bei Fächerprofilen in der Laugbahntabelle sind chick.

**Comment by ThomasBachran** [comment]
Bernd hat sich hierzu etwas einfallen lassen. Bitte schau dir das morgen mal auf dem nightly an.

**Comment by Raffenberg** [comment]
OK.

**Comment by Raffenberg** [comment]
Ich finde das sehr gut gelöst.

Verbesserung:
Wenn die Fehlermeldungen eingeklappt sind, signalisiert der kleine farbige Kreis, ob ein Belegungsfehler vorliegt. 

Bei den geforderten Fächerkombinationen erscheint in der Laufbahntabelle ein rotes Ausrufezeichen mit Signalwirkung, welches deutlich auf eine fehlende Wahl hinweist. Bei den nicht erlaubten Fächerkombinationen fehlt eine entsprechendes Signal (z.B. ein Warndreieck). Damit kann man eine unzulängliche Belegung kaum erkennen.

**Comment by ThomasBachran** [comment]
Ich habe jetzt das Signal auch bei den nicht erlaubten Fächerkombinationen eingeblendet. Kannst du dir das anschauen?

**Comment by Raffenberg** [comment]
@ThomasBachran : Das Signal funktioniert perfekt.

Momentan wird neben der Überschrift "Informationen zu Fachkombinationsregeln" im roten Kreis anscheinend die Anzahl der Regeln statisch und rot angezeigt. Zumindest ändert sich diese Anzeige nicht mehr. Hier müsste die Anzahl der Fehlerhaft belegten Regeln angezeigt werden (grüner Kreis mit 0, wenn keine Regel verletzt wird).

<img width="234" alt="fachkombinationsfehler" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/f2f3ddba-982a-4cab-b789-76d4e6bc19a1">

**Comment by Raffenberg** [comment]
Die roten Kreise scheinen nun die korrekten Zahlen zu tragen. Einen grünen Kreis mit Häkchen, wenn keine Fachkombinationsregeln verletzt werden, fände ich noch gut. Bei allen anderen Prüfungen erscheint das so.
![fachkombinationsregeln](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/1a789d10-88ec-40b7-a789-dec0bbb0e7d1)

**Comment by hmt** [comment]
Gute Idee, habe ich so umgesetzt
