### ISSUE TITLE
Ende der Anschlussförderung (kleiner Fehler im Layout)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#63]
Das Fenster schließt unter Individualdaten II nicht richtig ab:
![image](https://user-images.githubusercontent.com/75179015/103020894-95051700-4549-11eb-802a-3bb586a0e20d.png)

**Comment by FPfotenhauer** [comment]
Wird auch ein 120% Problem sein.
