### ISSUE TITLE
LuPO3: Hochschreiben als Kernfunktion fehlt

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#630]
Die Kernfunktion von LuPO ist ja das hochschreiben. Während der 1. Beratung findet eine Wahl ausschließ für die EF.1 statt. Ausgehend von dieser Wahl wird dann hochgeschrieben. In der Hochschreibung werden dann nur noch Änderungen herbeigeführt.

Ich fände hier zwei Auswahlreiter "von" und "bis" und eine Schaltfläche "Hochschreiben" gut.
Es wäre gut, wenn "von" in Abhängigkeit des Schuljahres auf einem sinnvollen Wert stehen würde. Bis kann eigentlich immer auf Q2.2 stehen.

Hochgeschrieben würden dann Schrittweise von EF.1-EF.2-Q1.1-Q1.2-Q1.2-Q2.2

1. Wahlen in Vertiefungskursen werden nicht hochgeschrieben
2. s wird mit s hochgeschrieben. Nur von Q2.1 nach Q2.2 wird s zu m
3. m wird mit m hochgeschrieben
4. LK wird mit LK hochgeschrieben
5. leere Felder werden leer hochgeschrieben und löschen ggf. dort wahlen
6. In der Fächertabelle kann die Lage der Zusatzkurse definiert werden. Ist das Fach nicht als s oder m in dem Halbjahr vor der Definition belegt, so wird es automatisch beim Hochschreiben als ZK belegt. Beispiel: Der ZK liegt in Q2.1 und Q2.2. Wenn in Q1.2 das Fach nicht belegt wurde, wird das Fach beim Hochschreiben als ZK belegt.
7. Diese Belegung darf dann nur ein weiteres Mal hochgeschrieben werden und danach muss die Hochschreibung leer bleiben (wenn ZK in Q1.1 und Q1.2 oder Q1.2 und Q2.1.
8. Ein PJK darf nur ein einziges Mal hochgeschrieben werden. Folgespalten bleiben auch hier leer

**Comment by ThomasBachran** [comment]
Diese Funktion werden wir leider nicht sofort umsetzen können. Eine Umsetzung dieser Funktion ist geplant, nachdem andere grundlegendere Arbeiten abgeschlossen sind. Da diese Funktionalität auf der Agenda steht, schließe ich das Issue hier.
