### ISSUE TITLE
LuPO3: Löschen einer geplanten Laufbahn

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#631]
Damit in der Beratungssituation schnell eine gänzlich andere Laufbahn durchgesprochen werden kann, ist die Gegenfunktion zum Hochschreiben genauso wichtig: Das Löschen "von" "bis". in allen Zeilen.

Löschbar sollten hier natürlich nur die Halbjahre sein, die noch nicht absolviert wurden.

**Comment by ThomasBachran** [comment]
In der Leiste unterhalb der Tabs gibt es den Knopf zurücksetzen. Der sollte die beschriebene Funktion ersetzen.

@Raffenberg : Kannst du dir die Funktion mal genauer anschauen und dann hier schreiben, wie man diese ggf. verbessern könnte, um den oben beschriebenen Anforderungen gerecht zu werden - oder ob die Funktion nicht erstmal schon so genügt. Das Löschen "von" "bis" halte ich hier nicht für zwingend notwendig, da nur Halbjahre berücksichtigt werden, deren Fachwahlen noch nicht in den Leistungsdaten persistiert sind, so dass hier eine Vereinfachung der Funktionalität vorliegt.

**Comment by Raffenberg** [comment]
Den Zurücksetzen-Knopf hatte ich übersehen. Wenn nur Wahlen gelöscht werden, die in den Leistungsdaten noch nicht persistiert sind, sollte das als Angebot ersteinmal reichen.

Hinweis: Bei den Erstebratungen (EF.1 bis Q2.2) haben die Beratungslehrer in Lupo2 oftmals nur die Daten EF.2 bis Q2.2 gelöscht, um in der EF.1 nicht alles vollständig neu einklicken zu müssen. In den Folgeberatungen der höheren Jahrgangsstufen ist das eigentlich nicht mehr notwendig. Dieser Komfort steht dann nicht mehr zur Verfügung auf Kosten weniger Klicks. Kann man erst mal so ausprobieren.

Ich habe eine Frage zum persistieren von Wahlen:

Szenario:
- ein Schüler wähtl in Lupo BI GKS
- Kurse werden geblockt
- Leistungsdaten werden bei den Schülern geschrieben (und damit persistiert)
- In der ersten Woche des Schuljahres entscheidet sich der Schüler, von GKS auf GKM zu wechseln (Alternativ LK-Wechseln in Q1.1, alternativ Fehleingabe durch den OKO, die korrigiert werden muss).

Ist das Berücksichtigt?

**Comment by ThomasBachran** [comment]
@Raffenberg: Noch nicht in allen Facetten. Hier ist es sinnvoll die einzelnen Möglichkeiten durchzugehen und jeweils eigene Issues aufzumachen. 

Bei der Laufbahnplanung sollten die persistierten Leistungsdaten gegenüber der "alten" Planung Vorrang haben und automatisch angezeigt werden. Hier wäre ich dir dankbar, wenn du das mal überprüfen könntest, ob die aktuelle Umsetzung so wirklich funktioniert.

Das Zusammenspiel mit den Blockungen und persistierten Leistungsdaten ist ein Aspekt, den wir noch genauer betrachten und testen müssen. Das würde ich gerne mit dir angehen, wenn wir die Laufbahnplanung in der ersten Version zufriedenstellend am Laufen haben.
