### ISSUE TITLE
LuPO3: Automatische Auswahl des Prüfungsalgorithmus der Laufbahn "EF.1" und "EF.1 bis Q2.2"

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#632]
Durch die Kernfunktion des Hochschreibens beginnt der Beratungsprozess mit einer Wahl in der EF.1. Folglich muss auch nur der Algorithmis der EF fehlerhafte Belegungen anzeigen. Hierdurch wird die Ansicht der Fehlermeldungen deutlich kürzer!

Erst nach dem Hochschreiben ist eine Fehleranzeige der gesamten Laufbahn notwendig.

In Lupo2 gibt es deshalb als Standardeinstellung ein Häkchenfeld, welches "automatisch setzen" heißt. Hat der Schüler keine Wahlen in EF.2 bis Q2.2, so wird nur die EF.1 Laufbahnprüfung durchgeführt. Existiert nur eine einzige Belegung in EF.2 bis Q2.2, so wird die Gesamtlaufbahnprüfung durchgeführt. 

Dieses Konzept hat sich überall etabliert. 

Die momentanen Schaltflächen scheinen global zu wirken, was auch gut so ist. Die Schaltflächen bleiben auch wichtig, weil der Beratungslehrer sich so z.B. nur die Laufbahnfehler der EF.1 anzeigen lassen kann, auch wenn schon Belegungen in den Folgehalbjahren vorhanden sind.

**Comment by ThomasBachran** [comment]
Ich kann mir hier unterschiedliche Workflows vorstellen. Meiner scheint sich z.B. deutlich von dem oben beschriebenen zu unterscheiden. Ich kenne auch andere Beratungslehrer die ein anderes Vorgehen haben. Insgesamt ist mir aufgrund meiner anderen Arbeitsweise nicht klar, wie du dir die Umsetzung des Häkchens "automatisch setzen" vorstellst. Ich habe ihn selbst nicht benutzt. 

Ich beschreibe daher einfach mal, wie ich eine solche Funktion verstehen würde:
- Neben der Überschrift `Belegprüfungsergebnisse` gibt es drei und nicht zwei Optionen zur Auswahl:
  - EF.1: Belegprüfung nur für EF.1
  - Gesamt: Belegprüfung für die Gesamtlaufbahn
  - Automatisch: Belegprüfung orientiert sich an der bisherigen Eingabe der Laufbahnplanungsdaten. Ist nur die EF.1 eingegeben, so findet eine EF.1-Prüfung statt, ansonsten eine Gesamtprüfung
- Zusätzlich sollte die ausgewählten Option Abiturjahrgangs-spezifisch für den angemeldeten Benutzer in der Konfiguration in Abhängigkeit vom angemeldeten Benutzer gespeichert werden, so dass diese Einstellung wiederhergestellt wird.

Ermöglicht eine Umsetzung dieser Punkte den von dir gewünschten Workflow? (Die Funktion des Hochschreibens betrachte ich an dieser Stelle zunächst nicht)

**Comment by Raffenberg** [comment]
So wäre es perfekt und würde auch ohne den Prozess des Hochschreibens passen.

**Comment by Raffenberg** [comment]
@ThomasBachran : Die automatische Umstellung funktioniert sehr gut. Es fehlt nach meinem Empfinden noch ein optischer Hinweis, welcher Algorithmus gerade verwendet wird.

Vorschlag: 
Es gibt momentan die Überschrift "Laufbahnfehler". Diese verschwindet, wenn kein Laufbahnfehler mehr vorhanden ist.
Man könnte die Überschrift umbenennen in "Laufbahnfehler EF.1" und "Laufbahnfehler Gesamtlaufbahn" oder ähnlich. Diese würde ich zudem dann niemals ausblenden, auch wenn alle es keine Fehler mehr gibt. Neben der Überschrift bleibt der kleine Kreis erhalten und wird grün mit einer 0 als Inhalt.

**Comment by Raffenberg** [comment]
Die Anzeige der ausgewählten Laufbahnprüfung scheint jetzt schon als Überschrift eingebaut zu sein. Allerdings ist die Anzeige nicht immer korrekt:

In der Laufbahnplanung selbst kommt es nach Umstellung im manuellen Prüfungsmodus vor, dass die Überschrift nicht wechselt, oder gar nicht angezeigt wird (s. Screenshots).

Falsche Überschrift
![laufbahnueberschrift1](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/429a8462-687e-466f-b818-40f881e52053)

Fehlende Überschrift
![laufbahnueberschrift2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/8de8801a-f3b1-45ee-95b6-31111a7659e6)

**Comment by ThomasBachran** [comment]
@Raffenberg : Das sollte in der nächsten Version behoben sein.
