### ISSUE TITLE
LuPO3: Belegung Exportieren führt zu einer Fehlermeldung

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#634]
Die Schaltpfläche Exportieren führt zu einer Fehlermeldung. Ich konnte deshalb nicht testen, ob als Dateiname ein Name vorgeschlagen wird, der schon Kerndaten enthält: "Nachname Vorname Klasse".

Das hat aber schon einmal tadellos funktionert.

**Comment by ThomasBachran** [comment]
Die Fehlermeldung sollte nicht mehr erscheinen. Kann dann morgen geprüft werden.

**Comment by Raffenberg** [comment]
@ThomasBachran : Der Export lässt sich wieder durchführen.

Der Exportname der Datei ist für Menschen schlecht zu handhaben. Der Benuter sucht bei einem Import in der Regel nach Klasse und Nachname (Sortierung im Dateiexplorer). Wenn die Klassenbezeichnung ab EF identisch ist, geht die Sortierung im Dateiexplorer automatisch auf den Nachnamen über. Insofern wäre mein Verbesserungsvorschlag:

"Laufbahn_Klasse_Nachname_Vorname_ID.lp"

**Comment by ThomasBachran** [comment]
Ich habe den Namen nach dem folgenden Schema angelegt: "Laufbahn_2026_EF_Mustermann_Max_4711.lp".

**Comment by Raffenberg** [comment]
s. Issue #636

**Comment by Raffenberg** [comment]
Ich bringe die Meldung nochmal nach Oben, da die Klassenbezeichnung statt der Jahrgangsbezeichnung im Dateinamen hilfreich wäre.

**Comment by FPfotenhauer** [comment]
Können wir das Issue schließen?

**Comment by ThomasBachran** [comment]
Die Umsetzung erfolgt in näherer Zukunft weiter über die Jahrgangsbezeichnung. Andere Aspekte haben hier eine höhere Priorität. Der Vorschlag mit der Klassenbezeichnung kann ggf. später aufgegriffen werden.

Einen Gruppenprozess gibt es zur Zeit noch nicht.
