### ISSUE TITLE
LuPO3: Anzahl der Kurse Gesamt

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#635]
In dem Feld "Anzahl der Kurse" Gesamt werden die anrechnnungsfähigen Kurse angezeigt. Hier gibt es eine Besonderheit, die dazu fürht, dass ggf. belegte Kurse nicht mitgezählt werden dürfen. Dies ist bei der Kurszählung relevant.

Die Besonderheit trifft bei einer Kombination von MU, VO und IN auf:
APO-GOSt 11.2.4 zu Absatz 2 Nummer 4

Dies betrifft ebenfalls die Kurse VO, IN und LI
APO-GOSt §28 (8)

Die Zählung der Wochenstunden ist hiervon nicht betroffen.

**Comment by ThomasBachran** [comment]
@Raffenberg: Der Speziallfall ist im Belegungsalgorithmus bei der Zählen der Wochenstunden und in der GUI noch nicht berücksichtigt. Kannst du hierfür auch Testfälle erzeugen?

**Comment by Raffenberg** [comment]
Mache ich.

**Comment by ThomasBachran** [comment]
@Raffenberg: Die Anzeige der anrechenbaren Kurse war bisher auch insgesamt fehlerhaft... Ich habe das so angepasst, dass jetzt die Zählung von der Belegprüfung wiederverwendet wird. Somit sollte bei der Anzeige jetzt alles berücksichtigt werden, was die Belegprügung kann. Der oben genannte Spezialfall gehört aber noch nicht dazu...

**Comment by ThomasBachran** [comment]
@Raffenberg: Der Spezialfall ist jetzt umgesetzt und kann bereits überprüft werden. Kannst du hierfür auch Testfälle erzeugen?

**Comment by FPfotenhauer** [comment]
Können wir das Issue schließen?

**Comment by Raffenberg** [comment]
Momentan zeigt die Gesamtsumme noch die Summe der belegten Kurse an. Wenn die Summe der anrechenbaren Kurse angezeigt werden soll. ist die Anzeige falsch. Die Summe der anrechenbaren Kurse ist aber relevant, weshalb ich hier dafür plädieren würde, das wie beim bisherigen Lupo zu handhaben. Sonst hat ein Schüler ggf. bei der Zulassung nicht genügend Kurse.

Bei der Gesamtsumme G werden zunächst die Kurse aus  MU/LI/IP/VI ausgelassen.

Zwischenschritt:
2. Summe A: Bilde die Summe der Kurse LI. Ist Summe A > 2, so ist Summe A = 2
3. Summe B: Bilde die Summe der Kurse LI/VP/IP. Ist die Summe B > 2, so ist die Summe B = 2
4. Summe C: Bilde die Summe der Kurse aus MU

Summe E:
Ist MU als AB1 oder AB2 belegt, so ist Summe E = Summe C + Summe A
Ist MU als AB3 oder AB4 belegt, so ist Summe E = Summe C + Summe B
Ist MU als GK belegt, so ist die Summe E = Summe C + Summe B. Ist Summe E > 5, so ist Summe E = 5
Wurde MU nicht belegt, so ist die Summe E = Summe B

Summe E wird dann auf die Gesamtsumme G hinzuaddiert.

Erläuterung:
Bei Belegung eines Musik LKs dürfen keine Kurse IP und VP angerechnet werden. Es dürfen aber bis zu zwei Kurse LI angerechnet werden
Bei Belegung von Musik als AB3 oder AB4 dürfen maximal zwei Kurse IP/VP/LI angerechnet werden.
Bei Belegung eines Musik GKs dürfen maximal zwei Kurse IP/VP/LI angerechnet werden. Die Gesamtsumme darf 5 nicht überschreiten
Bei Nichtbelegung von Musik dürfen maximal zwei Kurse LI/IP/VP angerechnet werden.

Ich kann Testfälle hierfür generieren, nur weiß ich nicht genau, inwiefern die Gesamtsumme gegengeprüft wird. Momentan wird die Gesamtsumme ja auch noch nicht korrekt berechnet, so dass diese auch in den testfällen fehlerhaft wäre.

**Comment by Raffenberg** [comment]
Zusatz. Mir sind gerade erst die Hinweise aufgefallen. Die sind super, lesen sich aber komisch.

Hier ist ein "nicht" zuviel:
"Bei der Wahl eines Musik-Leistungskurse sind vokal- und instrumentalpraktische Kurse nicht in der Qualifikationsphase nicht anrechenbar."

Hier ist ein "Kurse" zuviel.
"In der Qualifikationsphase sind, wenn Musik nicht als Abiturfach gewählt wird, maximal 5 Kurse Musik-Kurse (Musik, vokal- oder instrumentalpraktischer Grundkurs) anrechenbar."

Alternativvorschlag:
"Wenn Musik nicht als Abiturfach gewählt wird, sind maximal 5 musische Kurse (Musik, vokal- oder instrumentalpraktischer Grundkurs) anrechenbar."

Hier scheint auch ein Kurs zuviel:
Bei der Wahl eines Musik-Grundkurses als Abiturfach sind maximal 6 Kurse Musik-Kurse (Musik, vokal- oder instrumentalpraktischer Grundkurs) in der Qualifikationsphase anrechenbar.

Alternativvorschlag:
"Bei der Wahl eines Musik-Grundkurses als Abiturfach sind maximal 6 musische Kurse (Musik, vokal- oder instrumentalpraktischer Grundkurs) in der Qualifikationsphase anrechenbar."

**Comment by Raffenberg** [comment]
@ThomasBachran 
Hier die Testdaten.

[Testdaten MU-KU-LI-VP-IP.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13543034/Testdaten.MU-KU-LI-VP-IP.zip)

**Comment by Raffenberg** [comment]
Ich dachte, die benötigst Du nicht.
Ich habe immer den gleichen Schüler aus der Klasse 9 genommen (Abi 2022).
[Testdaten MU-KU-LI-VP-IP_Restdaten.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13549395/Testdaten.MU-KU-LI-VP-IP_Restdaten.zip)
