### ISSUE TITLE
LuPO: Name des Wahlbogens (PDF) und Gruppenprozess

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#636]
Wenn ich auf Wahlbogen herunterladen klicke, so wird immer der Dateiname "Wahlbogen.pdf" verwendet. Ich würde mir hier folgende Dateibezeichnung wünschen: "Klasse Nachname Vorname Datum".

Viele Schulen beraten die SuS zunächst und drucken keine Wahlbögen aus. Erst nach dem Beratungsprozess werden diese in einem Rutsch ausgedruckt und dann in den Klassen verteilt. Deshalb ist die Klassenweise Sortierung wichtig. Hier wäre ein entsprechender Gruppenprozess gut.

**Comment by ThomasBachran** [comment]
Eine Umsetzung sollte schon über das Schild-3 Reporting möglich sein. Zu einem späteren Zeitpunkt kann dennoch eine direkte Umsetzung in der GUI erfolgen. Eine Plazierung sollte dann unter `Oberstufe`-`Laufbahnplanung` erfolgen, da es ja einen ganzen Abiturjahrgang betrifft.

**Comment by M-Plu** [comment]
Hallo Jens, schau mal in dieses Issue #436. Da sind schon Beispielreports drin, ein Wahlbogen und eine Fehlerübersicht.

**Comment by Raffenberg** [comment]
Für den Ausdruck über einen Gruppenprozess aus Schild heraus ist der Weg über Schild tatsächlich gangbarer.

Wenn ich umgekehrt sofortige Ausdrucke nach der Beratung machen möchte, würde jeweils eine PDF erstellt, welche ich dann ausdrucke. Zum zwecke der Dokumentation wäre hier eine bessere Namensgebung trotzdem hilfreich.

Wenn das Dokument aus Schild mit dem Dokument aus dem SVWS-Client identisch ist, könnte man natürlich im Nachgang eine PDF-Dokumentation drucken. Dann wäre eine differenzierte Dateinnamensgebung nicht ganz so wichtig.

**Comment by ThomasBachran** [comment]
Ich habe den Namen für das PDF an den Namen des Backups angepasst.

**Comment by Raffenberg** [comment]
@ThomasBachran : Klappt (fast) perfekt. Mir ist durch Deine Beswchreibung im Issue #634 nicht aufgefallen, dass Du den Jahrgang verwendest und nicht die Klasse. Ich würde hier aber tatsächlich die Klasse empfehlen, so dass bei der Erstberatung in Kl. 9 noch besser differenziert werden kann. Ab EF ist die Bezeichnung ja dann identisch.

@M-Plu : Deine Reports habe ich mir noch nicht angesehen, hole ich aber bald nach. Ich bin gespannt.

**Comment by FPfotenhauer** [comment]
Der gesamte PDF-Druck befindet sich zur Zeit in Arbeit.
