### ISSUE TITLE
LuPO3: Ändern des Halbjahres bei den ZKs

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#637]
Wenn ich z.B. den SW-ZK in der Fächermatrix von Q2.1/Q2.2 auf Q1.1/Q1.2 ändere, so werden bereits erfolgte Belegungen in der Laufbahnplanung nicht als Fehlerhaft hervorgehoben. Hier müsste ein Ausrufezeichen o.ä. und ggf. eine Fehlermeldung erscheinen.

**Comment by Raffenberg** [comment]
@ThomasBachran 
@hmt 
Die Fehlermeldung erfolgt nun über die Ausrufezeichen. Das ist optisch richtig gut.

Ich würde trotzdem hier zusätzlich eine Belegungsfehlermeldung auf der rechten Seite anregen, so wie es bei jedem anderen Belegungsfehler auch gemacht wird. Damit das einheitlich geschieht.

**Comment by hmt** [comment]
ist in Arbeit.

**Comment by ThomasBachran** [comment]
@Raffenberg: Die Belegungsfehlermeldungen sind seit gestern drinnen. Kannst du das testen und dieses Issue dann ggf. schließen?

**Comment by Raffenberg** [comment]
Funktioniert!
