### ISSUE TITLE
LuPO3: Zusatzkurs in Q1.1/Q1.2 mit anschließender Wahl eines Gurndkurses / zweier Grundkurse

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#638]
Wenn ich folgende Wahl einklicke, erfolgt keine Fehlermeldung. Da in Lupo2 die Zusatzkurse nur in der Q2.1 und Q2.2 eingerichtet werden konnten, gibt es hierzu auch keine entsprechende Prüfroutine.

EF.1 | EF.2 | Q1.1 | Q1.2 | Q2.1 | Q2.2
m |   | ZK | ZK | m |   |

Gleiches wird auch in anderen Konstellationen gelten (ZK in Q1.2 und Q2.1 mit GK-Wahl in Q2.2).

**Comment by ThomasBachran** [comment]
@Raffenberg : Kannst du für die ZK-Beleg-Prüfung ein Paar Testfälle erstellen, so dass wir nach der Umsetzung die Korrektheit des Prüfalgorithmus nach Anpassungen beim Algorithmus immer miprüfen können?

**Comment by Raffenberg** [comment]
In Lupo2 kann ich die nicht nachbauen. Ich schaue mir an, ob ich die sofort in Eclipse ergänzen kann.

**Comment by ThomasBachran** [comment]
@Raffenberg: Die Testdaten wurden zwar generiert, aber wir werden wohl nicht darum kommen auch Testfälle von Hand anzupassen, da sich die Fälle in LuPO nicht eingeben lassen. Ich würde daher einfach ein weiteres Set von Testfällen anlegen und die JSONs von Hand anpassen.

**Comment by ThomasBachran** [comment]
@Raffenberg: Ich habe die Belegprüfung jetzt erweitert. Die Zusatzkurse werden jetzt wie oben geprüft. Außerdem existieren jetzt auch Fehlercodes, wenn der Beginn eines Zusatzkurses falsch gesetzt ist, ein ZK belegt wurde, obwohl er nicht angeboten wird und wenn eine Fachkombination verletzt wurde. Dadurch erscheinen die Laufbahnfehler jetzt auch auf der Übersichtsseite des Jahrgangs.

Könntest du dann JSON-Testdaten anlegen, bei dem die Zusatzkurse früher gelegt sind? Wenn du mir die schickst, dann kann diese in die automatischen Tests integrieren...

**Comment by Raffenberg** [comment]
Die Fehlerüberprüfung funktioniert bei meinen Tests sehr gut.

JSON Daten stelle ich noch zur Verfügung.
