### ISSUE TITLE
Wechsel zur aufnehmenden Schule

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#639]
Wenn ich unterhalb des Reiters "Auswahl" auf "Weitere Daten" klicke und unter Wechsel zu aufnehmenden Schule den Namen der Schule anklicke, kommt eine Fehlermeldung. Wenn ich die mit ok bestätige, geht es weiter. Allerdings ist das Fenster nicht optimal angeordnet.
![Schild Fehler 10a](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/d3a23ebb-2208-42c7-8b5b-0abb0c2519e6)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren:

[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11474945/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Behoben
