### ISSUE TITLE
SchiLD-Bild beim Passworteingabe unten abgeschnitten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#640]
Version 3.0.68.9

Bei der Anzeige des Datenschutzhinweises sieht das Startbild komplett aus.

Während der Passworteingabe ist es unten abgeschnitten, das Fenster ist zu klein für den Inhalt.

![Start](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/49612f4e-d21f-489c-b3f1-70d854f61be0)

**Comment by JuergenRichter** [comment]
Behoben
