### ISSUE TITLE
Einstellungen "Fächer, Noten": Fehlstunden SII passt nicht ins Fenster (eventuell Skalierungsproblem) 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#641]
Version 3.0.68.9

Das Fenster in "Fächer, Noten" ist zu klein, das Dropdown-Menü zu den Fehlstunden SII rutscht aus dem bereitgestellten Feld.

Eventuell handelt es sich um ein Bildschirm-Skalierungsproblem (4K@150% in Windows). 

![EinstNoten](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/caa7a5ef-efbd-4a32-afdb-af0c08c023f1)

**Comment by AnneSchueller** [comment]
Mit Skalierung 150% habe ich das gleiche Problem.

Bei einer Skalierung von 100% passt das Fenster. Allerdings sind die Felder unterhalb unabhängig von der Skalierung zu kurz:

![2023-05-16_181048](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/81867db9-9d52-4d8e-9bb1-cd18399836b6)
