### ISSUE TITLE
Laufbahnplanung: Schwierigkeiten, die Zeile mit dem Auge zu halten

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#642]
@ThomasBachran : Ich kann nicht genau sagen, woran es liegt, aber mir fällt immer wieder schwer, die Wahl innerhalb eines Faches zu sichten oder ändern. Ich suche z.B. die Belegung in Biologie und blicke nach links zur Bezeichnung. Da die Spalten recht breit sind, muss sich mein Auge dann nach rechts bewegen. Hier hat das Auge wenig, woran es sich "festhalten" kann. Oftmals verlierte ich dann die Zeile und muss nochmals schauen. Mir ist das erst heute richtig bewusst geworden, habe allerdings schon seit einigen Tagen damit zu kämpfen.

Vergrößern des Zoomfaktors schafft irgendwie keine Abhilfe.

Ich glaube, dass das mit zwei Faktoren zu tun hat:

1. die dunkelgraue Farbe in den Spalten "Sprache". Sie wirkt wie eine optische Barriere und lässt die Gitternetzlinien als optische Leitlinien verschwinden. Hier verliert mein Auge am meisten die Orientierung. Hier würde ich ohnehin empfehlen, in dieser Spalte einfach nichts auszugrauen, sondern die Leitfarben der Aufgabenbereiche zu nehmen. Ich denke, dass das irritiert und nicht notwendig ist. Ich weiß, im Originalprogramm ist das auch so, aber da sind die Gitternetzlinien dicker, so dass sich das nicht auf das Auge auswirkt. Aber auch da habe ich das ausgrauen nicht für notwendig gehalten.
2. die Breite aller Spalten rechts neben der Spalte "Fach" bei Vollbilddarstellung. Diese sind gemessen am benötigten Inhalt recht breit, so dass das Auge weit wandern muss und auch die Wahlen Von EF.1 bis Q2.2 schlecht in "einen Blick" bekommt. Schiebe ich das Fenster so weit wie möglich zusammen, wird der Eindruck deutlich besser, allerdings wird dann der Fehlerbereich recht klein. Im Originalprogramm ist und bleibt die Darstellung auch schmal. Ich würde hier eine feste Maximalbreite empfehlen, die möglichst schmal ist.

Vollbild:
<img width="831" alt="Optik breit" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/c331782a-7d4c-4911-8014-ec61cfd0cf98">

Fensterdarstellung schmal
<img width="517" alt="Optik schmal" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/1c30e250-2b4e-4024-9169-6663be15f322">

Originalprogramm:
<img width="507" alt="Optik original" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/5962e660-6a22-4b1d-b551-ee23069f6c07">

**Comment by hmt** [comment]
Würde ein leichtes Hervorheben beim Überfahren einer Zeile mit der Maus helfen?

**Comment by Raffenberg** [comment]
@hmt : Das ist schwer zu beantworten. Kann ich schwer einschätzen.

Es gibt zwei Ebenen: Der Beratungslehrer klickt in der Regel die Laufbahnen ein. Er arbeitet mit der Maus, wodurch das hervorheben der Zeile hilfreich sein kann. In der Regel beginnt dieser in der ersten Spalte durch einklicken der Wahlen in der EF.1. Damit befindet sich die Spalte auch noch nahe an den Fachbezeichnunngen. Wenn er die folgenden Halbjahre einklickt, hat er zusätzlich die schon getätigten Wahlen als Anhaltspunkt. In den Folgehalbjahren müssen die Beratungslehrer Umwahlen einklicken. An dieser Stelle finden in der Regel leichte Anpassungen der Wahl an, so dass z.B. in der Q1.1 änderungen am LK in zwei Fächern eingeklickt werden müssen. Hier muss man also nach zwei Fächern ausschau halten. Hier steigt das von mir beschriebene Problem. Die Spalte ist weiter weg und ich muss nach zwei Zeilen ausschau halten. Trotzdem wird hier die Maus benutzt, so dass die Hervorhebung bestimmt hilfreich ist.

Der Oberstufenkoordinator macht in der Regel eine Sichtprüfung der Wahlen und setzt sich meist auch mit der Gesamtplanung auseinander. Dies ist meist nur eine Sichtkontrolle. Durch die große Erfahrung gültiger Wahlen erfolgt diese dann meist auf einen Blick und in schneller Schülerabfolge. Hier wird das von mir beschriebene Problem dann ggf. deutlicher und die Hervorhebung würde nicht helfen.

Da sich das individuelle Vorgehen an den einzelnen Schulen aber stark unterscheiden kann, kann auch die Empfindung des Problem unterschiedlich ausfallen. In meiner Empfindung bremst es meinen Workflow herunter. Deshalb wäre hier ggf. die Meinung anderer interessant, die auch mit den Beratungsprozessen in der Oberstufe zu tun haben.

LG
Jens

**Comment by hmt** [comment]
ich kann das nachvollziehen. Interessant wäre also eine Möglichkeit, vielleicht per Knopfdruck die Ansicht oder den Kontrast der Ansicht zu erhöhen, z.B. durch weniger dunkle Sperrfelder und dickere Linien zwischen den Zeilen.

Nur so ein Versuch: 
<img width="1211" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/1246495/fcef536e-eccf-40a0-9056-c6be1eca948c">

Eventuell Spaltenbreite reduzieren, Text etwas dicker machen.

**Comment by hmt** [comment]
mir gefällt übrigens dieses grau sowieso besser als das dunkle...

**Comment by ThomasBachran** [comment]
- Das hellere Grau gefällt mir auch besser. Noch besser würde mir Weiß gefallen. Wir sollten Sport eine ganz andere Farbe geben, als dies früher üblich war. Dann hätten wir Weiß für den Hintergrund wieder frei. Welche Farbe könntet ihr euch für Sport vorstellen? RGB-Werte?
- Die Spaltenbreite ist hier für WStd., Folge, abJg, EF.1, EF.2, Q1.1, Q1.2 und Q2.2 und Abiturfach im Verhältnis zur Bezeichnung des Faches zu groß
- Die Aufteilung zwischen der Tabelle und dem rechten Fehlerbereich ist auch ungünstig gewählt. Hier sollte der rechte Bereich einen größeren Anteil haben. Für die Tabelle sollte aber eine geeignete Mindestgröße gesetzt werden.
- Die weißen Trennlinien aus der Vorschlagsgrafik oben empfinde ich als störend. Bei einem weißen Hintergrund dürften die ursprünglichen Trennlinien auch besser erkennbar sein.

@hmt: Kannst du mal die Ideen ausprobieren?

**Comment by ThomasBachran** [comment]
Ich habe ein paar Ideen mal ausprobiert und eingecheckt. Das sieht jetzt mMn schon deutlich besser aus. Für Sport habe ich die Farbe angepasst, was auch Vorteile bei der Darstellung bei der Umwahl in der Kursblockung hat.

Die beiden Aspekte oben bin ich noch nicht angegangen.

@Raffenberg: Verbessert das schon ein wenig die Übersichtlichkeit?

**Comment by Raffenberg** [comment]
Ich finde die Idee, die Fabren nur leicht grau abzutönen richtig gut. Interessanterweise hilft das auch sofort bei dem ursprünglichen Problem.

Sport, VTF und PJK mal als Ideenvorschlag anders eingefärbt (trennschärfer, weg vom dunkelgrau, kontrast)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/e1da8dc0-0a20-4b98-b043-ab8118809c12)

**Comment by Raffenberg** [comment]
Ich schließe das hier mal, weil die Darstellung schon besser ist. Schmalere Spalte bei breiten Monitoren und würden das Problem nochmals reduzieren.
