### ISSUE TITLE
Gruppenprozess "Teilleistungen individuell zuordnen" bei nicht gesetztem Fach/Kursart -> Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#643]
Version 3.0.68.9

Es gibt beim im Titel genannten GP einen Fehler, wenn Fach und Kursart leer gelassen wurden:

![GPTL](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/acb22f6c-323e-4510-962f-d4b12a585881)

**Comment by AnneSchueller** [comment]
Das führte auch bei Schild2 zu einer Fehlermeldung. Vielleicht könnte man hier eine Fehlermeldung erscheinen lassen, dass das Fach fehlt.

[fehlendesFach.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11515835/fehlendesFach.txt)

**Comment by JuergenRichter** [comment]
Behoben
