### ISSUE TITLE
Schulnummer in "Schulbesuch" -> "Vor der Aufnahme besuchte Schule" lässt sich nicht ausfüllen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#645]
Version 3.0.68.9

Die Schulnummer für "Vor der Aufnahme besuchte Schule" lässt sich nicht ausfüllen. Weder manuell noch per Dropdownmenü.

Vorgeschlagenes Verhalten: 
Schulnummer* und Name der Schule* füllen sich jeweils im Wechsel automatisch aus (d.h. eine Angabe der SNR füllt den Namen und andersrum).

![SNRVorherigeSchule](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/26df178e-4550-48c0-bbd1-bd89287aae9b)

**Comment by AnneSchueller** [comment]
Aktuell ist ja das Verhalten für die Auswahl der Schulform/Schule genauso realisiert wie auch in Schild2. 
An dieser Stelle die Schulnummer einzugeben, sodass sich die anderen Felder automatisch füllen, wäre sicherlich komfortabel.

**Comment by FrodBRA** [comment]
Auch in SchILD2 lässt sich keine Schulnummer eingeben?

Dieses Issue ist: 
1. Keine Schulnummer eingebbar.
2. Es wäre schön, wenn sich die Felder gegenseitig befüllen.

Ist das Verhalten gewünscht, dass die Schulnummer zwangsweise frei bleibt? Wozu ist das Feld dann da?

**Comment by AnneSchueller** [comment]
In Schild2 ist das etwas unscheinbar. Da ist die Schulnummer nicht in einem Eingabefeld sondern klein unter dem Schulnamen als Label.

Wie ist das denn passiert, dass bei dir dort keine Schulnummer ist? War das nach der Migration schon so oder hast du die neu hinzugefügt?
Wenn ich über "..." oder über das "+" Zeichen eine Schule hinzufüge, wird immer die eingetragene Schulnummer in das Feld geschrieben.
Fehlt die Schulnummer evtl. bei dir im Katalog?

**Comment by FrodBRA** [comment]
Du kannst das Issue schließen. Ich habe eine "Andere Schule" zum Katalog hinzugefügt und konnte die Schule direkt auswählen, nur die Schulnummer tauchte nicht auf.

Nach einem Neustart von SchILD ist das Verhalten in der Tat wie gewünscht: Ein Auswählen der Schule trägt automatisch die Schulnummer mit ein.
