### ISSUE TITLE
Schild 3 Auswahl-Filter

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#646]
Wenn ich in der aktuellen Version unter Auswahl/ Weitere Daten/ Vermerke nach einer Vermerkart filtere lässt sich dieser Eintrag nach erfolgreicher Filterung nicht mit der rechten Maustaste "Eintrag löschen" aus dem unteren Feld entfernen.

**Comment by AnneSchueller** [comment]
Die Option "Eintrag löschen" ist m.E. auch nur dafür gedacht, dass man vor der Filterung falsch gesetzte Filtereinträge wieder löschen kann. 
Hat man erst einmal gefiltert, muss man erst den Button "Zurücksetzen" betätigen.

**Comment by JuergenRichter** [comment]
Behoben
