### ISSUE TITLE
Schild 3 Fehlermeldung Reiter Lehrer/Schüler

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#648]
Wenn ich, nachdem ich den Reiter Lehrer geöffnet hatte, den Reiter Schüler öffne, kommen die folgenden Fehlermeldungen:
![schildfehler1002](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/0aecd422-2b58-4f9d-be8c-eacb5d0c2ecb)

**Comment by AnneSchueller** [comment]
Das kann ich nicht reproduzieren. Warst du bei den Lehrern auf einem bestimmten Unterreiter oder hast irgendwas bestimmtes angepasst? Vielleicht könntest du mal das Fehlerprotokoll mit einstellen
(Klick auf Copy to Clipboard; dann sollte sich im Ordner Documents eine Datei schild.el befinden. Hier einfach aus .el .txt machen, dann kann man die hochladen)

**Comment by JuergenRichter** [comment]
Behoben
