### ISSUE TITLE
Auswahl -> "Vorhandene Filterdefinitionen bearbeiten" dient nur zum "löschen"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#649]
Version 3.0.69.9

Das Menüband in "Auswahl" bietet an, "Vorhandene Filterdefinitionen bearbeiten", hinter diesem Feld verbirgt sich aber nur ein Fenster, welches das reine Löschen zulässt. 

Der Knopf ist auch entsprechend benannt, der Kopf des Fensters kündigt "Bearbeiten" an.

Die Funktion "Bearbeiten" sollte sowohl das bearbeiten und speichern als auch das löschen zur Verfügung stellen.

![AuswahlLöschen](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/30100bb2-4d0a-4db7-94da-d8245e4a1ae8)

**Comment by AnneSchueller** [comment]
Das ist so aus Schild2 übernommen. Gemeint ist hier die Liste der Filterdefinitionen bearbeiten.

**Comment by FrodBRA** [comment]
Aber es steht nach wie vor "Filterdefinitionen bearbeiten" im Fenster und im Knopf. Das kündigt etwas anderes an, als gemeint ist, zumindest bin ich intuitiv davon ausgegangen, dass ich Filter bearbeiten darf.

Sollten die Knöpfe neu benannt werden?

**Comment by AnneSchueller** [comment]
Hast du einen guten Namensvorschlag? 
Wir waren tatsächlich auch bei Schild2 in den Fortbildungen immer irritiert, warum der Button so heißt. 
"Vorhandene Filter löschen und umbenennen" wäre zu lang. Oder nur "Vorhandene Filter löschen"?

**Comment by FrodBRA** [comment]
Mein Vorschlag wäre knapp "Filter löschen". Mit etwas mehr Platz geht auch "Filterdefinitionen löschen". Dann ist es eindeutig.

Nicht-vorhandene Filter kann man nicht löschen, daher müsste man das nicht reinzuschreiben.

**Comment by FrodBRA** [comment]
Identisch zu Issue https://github.com/SVWS-NRW/Schild3-BetaTest/issues/113

Die Überlegung, wie mit dem Button umzugehen ist, lässt sich dort führen. Damit kann dieses Issue geschlossen werden.
