### ISSUE TITLE
Export: Externes Notenmodul -> Schließen nicht sichtbar

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#65]
Bei einer Skalierung von 120% ist das Feld Schließen beim Export-Externes Notenmodul nicht richtig sichtbar:
![image](https://user-images.githubusercontent.com/75179015/103021406-5facf900-454a-11eb-8f8a-a0dbf886bf7d.png)

**Comment by FPfotenhauer** [comment]
Können wir bitte ein Issue Skalierungsprobleme bei 120% aufmachen und dort alle Sachen sammeln?
Das würd eich dann der Firma Ribeka zuweisen.
