### ISSUE TITLE
Kopfzeilen in "Benutzerverwaltung" und "Aktuelle Datenbanknutzer zeigen" sind bei Windows-Skalierung >100% sehr groß

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#650]
Version 3.0.69.9

Siehe Titel

**Comment by AnneSchueller** [comment]
Welche genau meinst du?

In den Spalten die Textfelder Benutzername, Name, Admin, usw?

![2023-05-23_195253](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/af74eb42-82a8-4d12-b480-f8022042910e)

**Comment by FrodBRA** [comment]
Die Kopfzeilen, ja.

**Comment by AnneSchueller** [comment]
Erscheinen die denn bei dir größer? In meiner Ansicht sehen die Kopfzeilen eigentlich ganz gut aus.

**Comment by FrodBRA** [comment]
![Ben1](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/66a05e8e-3c3c-447f-9bdc-c023a5da2445)

![Ben2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/c37ff150-a2a5-4a8d-9c65-81016af4d7b3)

**Comment by AnneSchueller** [comment]
Seltsam, dass die Schrift bei dir so groß ist.

**Comment by AnneSchueller** [comment]
Wurde hier was angepasst?
@FrodBRA : Könntest du das nochmal testen?

**Comment by JuergenRichter** [comment]
Sollte im nächsten Update behoben sein

**Comment by FrodBRA** [comment]
3.0.74.10: Das Problem besteht nach wie vor.

**Comment by AnneSchueller** [comment]
@FrodBRA Es gibt eine neue Schild3-Version:
https://github.com/SVWS-NRW/Schild3-BetaTest/releases

Es kann sein, dass die Anpassung erst in dieser Version sichtbar ist.

**Comment by FrodBRA** [comment]
Die neueste Version dort ist die 3.0.74.10.

**Comment by AnneSchueller** [comment]
hm... in meiner Ansicht kann man bereits die 3.0.75 runterladen mit dem Kommentar "Bugfixes und Fensterpositionen korrigiert."

**Comment by FrodBRA** [comment]
Nicht für die einfache Landbevölkerung. ;)

![NotForPeasents](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/f7347568-1080-4db4-85ec-1ace31e3a895)

**Comment by FrodBRA** [comment]
Version 3.0.76.11

Sieht jetzt wie in den anderen Fenstern aus.

Geschlossen.
