### ISSUE TITLE
Laufbahnplanung: Ergebnisse mit Fehlern zeigen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#651]
Auf der Seite mit den Laufbahnfehlern (Oberstufe, Laufbahnplanung) scheinen die Auswahlfelder EF und Gesamt nicht mehr zu funktionieren. Mir werden zunächst Fehler amgezeigt, ohne dass eines der Auswahlhäkchen markiert ist. Sobald ich eines Auswähle, ändert isch die Anzahl der gemeldeten Feler und die Anzahl der Schüler. Danach kann ich die Auswahlhäkchen ändern, ohne dass ein Effekt auftritt.

Die Auswahl "Automatisch" ist nach meinem Dafürhalten hier nicht zielführend. Zumindest müsste an der Überschrift "Laufbahnfehler" erkennbar sein, aus welcher Prüfung der Fehler resultiert ("Laufbahnfehler EF", "Laufbahnfelher Gesamt").

**Comment by ThomasBachran** [comment]
Automatisch ist hier wirklich nicht hilfreich. Es sollte nur Gesamt und EF.1 wählbar sein. Außerdem sollte die Einstellung getrennt von der Schüler-Laufbahnplanungs-Einstellung in der Konfiguration gespeichert werden.

**Comment by hmt** [comment]
ist schon alles drin mit dem Commit von heute morgen

**Comment by hmt** [comment]
ich kann nicht schließen, bin ich kein Admin?

**Comment by Raffenberg** [comment]
Ich teste das morgen und schliese dann das Issue.
