### ISSUE TITLE
Laufbahnplanung: Bezeichnung kommt zweifach vor

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#653]
Bei den letzten Issues habe ich gemerkt, dass es schwierig ist zu beschreiben, wo man sich gerade befindet, wenn die Bezeichnung die gleiche ist.
Es gibt zum einen die "Laufbahnplanung" bei den Schülern und zum anderen die "Laufbahnplanung" unter Oberstufe. Ich würde vorschlagen, letztere Überschrift umzubenennen z.B. in "Laufbahnübersicht" o.ä.

**Comment by ThomasBachran** [comment]
"Laufbahnübersicht" trifft es aber nicht wirklich... Das wäre dann eher eine "Laufbahnplanungsübersicht" oder ähnlich.  Das ist mir dann aber auch wieder zu lang. Da sollte uns noch etwas besser einfallen.

**Comment by Raffenberg** [comment]
Bilanz
Planungsbilanz
Planungsergebnisse
Wahlbilanz
Wahlergebnisse
Planungsresultate
Resultate
Planungsanalyse
Wahlanalyse

**Comment by FPfotenhauer** [comment]
Die Laufbahnplanung unter Oberstufe ist mit der Laufbahnplanung der Schüler verknüpft, deshal die gleiche Bezeichnung.

**Comment by hmt** [comment]
Wir schreiben meist eindeutig Schüler/Laufbahnplanung oder Gost/Laufbahnplanung. Oder Oberstufe/Laufbahnplanung. Das ist zusammen mit der App-Bezeichnung in der Regel der einfachste Weg, um an die fraglichen Komponenten zu gelangen. Gleiches gilt ja auch für den Stundenplan, der in fast allen Apps vorkommt.
