### ISSUE TITLE
LuPO Export fehlt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#656]
Version 3.0.69.9

SchILD3 unterstützt bislang keinen Export für LuPO.

![LuPO](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/20352be0-2bc2-4473-bd80-5af3aad5e463)

**Comment by FPfotenhauer** [comment]
Das wird in Zukunft vom SVWS Client übernommen.
