### ISSUE TITLE
Auswahl ➜ Weitere Daten ➜ Sprachenfolge: Dropdown-Menü "Fach" reagiert nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#657]
Version 3.0.69.9
SVWS 0.6.5

Der Schüler hat das Fach "Englisch" und die Sprachenfolge ist auch korrekt gesetzt. Ein Klick in Auswahl ➜ Weitere Daten ➜ Sprachenfolge auf das Dropdownmenü "Fach" eröffnet keine Auswahlmöglichkeiten.

Sollten hier nicht alle möglichen Sprachen zur Auswahl angeboten werden? Im Katalog "Unterrichts-Fächer" sind diverse Fächer als Fremdsprache korrekt gesetzt.

**Comment by FrodBRA** [comment]
Nachtrag: Reagiert das Fach nicht, kann ich auch keine Jahrgänge und Abschnitte (Start, Ende) eintragen.

**Comment by JuergenRichter** [comment]
Behoben
