### ISSUE TITLE
"Notenliste zeigen" fehlt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#658]
Version 3.0.69.9

Das Feature "Notenliste zeigen" aus SchILD2 (Extras -> Notenliste zeigen) fehlt in SchILD3. 

Dem (leeren) Wiki-Artikel nach ist es für Verwaltung -> Hilfe angedacht.

Erweiterungsvorschlag: Eine eventuelle neue Notenliste sollte auch die entsprechenden "Punkte" der Oberstufe (15 bis 0) rechts von der textlichen Beschreibung mit enthalten.

**Comment by AnneSchueller** [comment]
Die Frage wäre, ob eine Notenliste an dieser Stelle sinnvoll ist. Evtl. könnte man das auch unter akt. Halbjahr/Leistungsdaten. neben dem Info-Button ergänzen?

**Comment by FrodBRA** [comment]
Lieber neben dem Info-Button, denn dort braucht man sie.

**Comment by JuergenRichter** [comment]
Ist jetzt vorhanden. 
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9cb0066b-cf7c-41b9-b8ce-7235ae422786)
