### ISSUE TITLE
Verbesserungsvorschlag: "Eine nicht gemahnte 5 oder 6 bei Versetzungs-/Abschlussberechnung ignorieren" sollte sich jahrgangsweise anwählen lassen 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#659]

**Comment by AnneSchueller** [comment]
Diese Option müsste man dann bei verschiedenen Jahrgängen je nach Berechnung (Abschluss oder Versetzung) dennoch umstellen. M.E. wäre es dann einfacher das einmal für die Abschlussberechnungen zentral umzustellen. Oder habe ich gerade einen Denkfehler?

**Comment by FrodBRA** [comment]
Daran hatte ich gestern auch noch gedacht.
