### ISSUE TITLE
Statistikprüfung führt zu Absturz

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#66]
Ich kann die Statistikprüfung starten, aber das Programm stürzt nach langer Wartezeit ab:
Weiterbildungskolleg mit 580 Schülern
Core I7 und Installation auf SSD

**Comment by FPfotenhauer** [comment]
In Schild2.0 geht das aber?

**Comment by Kluesenerm** [comment]
Funktioniert ohne Probleme und die Daten liegen nicht einmal auf der SSD. Schild 2.0 ist gefühlt 10* schneller als Schild 3.0.

**Comment by FPfotenhauer** [comment]
Ja. Schild3.0 ist echt langsam, wir müssen bald alle I9 und Samsung Evos beantragen.

Bei mir läuft die Statistikprüfung durch.
Bitte mal die DB anonymisieren und zur Verfügung stellen.

**Comment by FPfotenhauer** [comment]
Die Statistik.dll wird momentan ja gar nicht vom Schild3-Installer registriert.
Sie kann also nur funktionieren, wenn Schild2.0 installiert ist.

Dass das im Moment noch nicht korrekt funktioniert, wundert mich erstmal nicht.

**Comment by JuergenRichter** [comment]
Ich habe den Statistik-Export für die gleiche Datenbank (Gesamtschul-DB von Herrn Pfotenhauer) mit SchILD2 und SchILD3 gestoppt (auf dem selben Rechner)
SchILD2 (MDB): 29 Sekunden
SchILD3 (MariaDB): 11 Sekunden

SchILD3 ist hier also deutlich schneller.

Was nach dem Export passiert (Gesamtprüfung der Daten), darauf haben wir keinen Einfluss mehr. Da in beiden Fällen aber auf die gleichen Verfahren verwendet werden (StatistikDB ist ja eine MDB) sollten hier keine großen Unterschiede auftreten.

Bitte mit der Version 3.0.10 (in Kürze) nochmal testen.

**Comment by JuergenRichter** [comment]
Ich mache das mal zu, falls mit Version 3.0.11. weiter Probleme auftreten sollten, bitte wieder öffnen
