### ISSUE TITLE
Menü Sortierreihenfolge festlegen - Text abgeschnitten

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#660]
Version 3.0.69.9
Im Menü Sortierreihenfolge ändern ist der Eintrag _Nr. der aufnehmenden Schule_ abgeschnitten.
Auflösung des Monitors QHD (2560x1440), Skalierung: getestet mit 150% und 100% (empfohlen).
Betriebssystem: Windows 10

![Sortierreihenfolge_ändern_text-abgeschnitten](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/bb27cc53-bad1-4b25-84dd-3efd5c35c83c)

**Comment by JuergenRichter** [comment]
Fenster ist jetzt breiter
