### ISSUE TITLE
Menü Sortierreihenfolge festlegen - Doppelpfeil rechts sollte entfernt werden (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#661]
Version 3.0.69.9
Der Doppelpfeil nach rechts, mit dem man im Menü _Sortierreihenfolge ändern_ sämtliche Datenarten in das rechte Fenster verschieben kann, ist meines Erachtens sinnfrei: es kommt im Schulalltag nie vor, dass sämtliche Datenarten in die Sortierung einbezogen werden. Aus diesem Grund sollte der Button entfernt werden.

![Sortierreihenfolge_ändern_pfeil](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/601dd050-50ae-40fc-83b2-62b468d0b0e9)

**Comment by AnneSchueller** [comment]
Ja, das stimmt. Kann von mir aus raus.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
