### ISSUE TITLE
Titel des Menüs "Sortier-Reihenfolge festlegen" ändern (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#663]
Der Titel des Menüfensters _Sortier-Reihenfolge festlegen_ sollte genau so benannt werden wie der Button (_Sortierung_), der das Menü aufruft.
"Sortierreihenfolge festlegen" könnte man dann als Überschrift über die Pfeile nach unten und nach oben setzen, da an dieser Stelle die Sortierreihenfolge geändert werden kann:
![Sortierreihenfolge_ändern_Layout](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/47c4591e-2ea5-4e8e-af6a-bbfa4bd00718)

**Comment by JuergenRichter** [comment]
Ist umgesetzt
