### ISSUE TITLE
Datenquelle "Foerdermassnahmen": Aufruf im Reporting führt zu Fehler "#42000 Query was empty" 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#665]
Version 3.0.69.9

**Comment by JuergenRichter** [comment]
War denn im Feld "Anzeige" was ausgewählt?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/c51423bb-9c3b-4a4a-812b-edfe032b801c)

**Comment by AnneSchueller** [comment]
Report -> Neu
Datenquelle auf Schueler belassen
Neues DBText -> Datenquelle Foedermaßnahmen.

![2023-06-23_123035](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/bedcff74-af67-4df5-95e2-4f2145ba38fb)

**Comment by JuergenRichter** [comment]
"Datenquelle auf Schueler belassen"

Das ist falsch, die Datenquelle "Foedermaßnahmen" ist keine Unterdatenquelle zu "Schueler". Es gab aber auch in er Abfrage für diese DQ einen Fehler, der ist nun behoben.
