### ISSUE TITLE
Datumswahlfenster in "Lehrkräfte" sind zu groß skaliert (Windows-Skalierung bei hohen Auflösungen?)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#666]
Version 3.0.69.9

Siehe Titel und Screenshot. 

Der Effekt tritt bei mehreren Datumsfeldern auf.

![LKDatum](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/3d122aa7-441d-4e75-97f6-1590b05f55ed)

**Comment by AnneSchueller** [comment]
Das kann ich bei den Lehrern reproduzieren. Mit 100% Skalierung gibt es keine Probleme, nur mit 150%. 

Die Datumsauswahl unter Schüler/ind Daten I/Aufnahmedatum macht keine Schwierigkeiten bei einer größeren Skalierung.

**Comment by JuergenRichter** [comment]
Es werden jetzt die gleichen Komponenten wie bei den SuS verwendet.
