### ISSUE TITLE
Schülersuche: Schalter "Suche ausführen" scheint nichts zu tun

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#667]
Version 3.0.69.9

Wird eine Schülersuche ausgeführt, funktioniert die Suche bei der Eingabe in Felder wie erwartet.

Werden anschließend Haken umgesetzt, zum Beispiel den bei "Nur aktive Schüler suchen" und auf "Suche ausführen" geklickt, scheint sich nichts zu tun.

Wird wieder ein Eingabefeld verändert, wird die Suche während der Eingabe mit den nun gesetzten Haken korrekt ausgeführt.

Der Knopf "Suche ausführen" hat damit keine mir ersichtliche Funktion.

![SucheNix](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/07597a81-bd61-4333-ace6-b4277ba482c3)

**Comment by JuergenRichter** [comment]
Suchdialog wurde nochmal überarbeitet
