### ISSUE TITLE
Zwei Abitur-Gruppenprozesse fehlen: 1. "Zusatzdaten (Latinum...) eingeben" und 2. "Abitur-Jahr setzen (für Statistik)"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#669]
Version 3.0.69.9

**Comment by JuergenRichter** [comment]
Gruppenprozess für Latinum usw. ist jetzt umgesetzt, da die Verwaltung dieser Information nun aber etwas anders geschieht, musste dass wie folget angepasst werden:

-Zuerst muss die Sprache gewählt werden
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/17501d71-ad84-48ee-b469-b6f70ce90c5d)

-Dann werden die SuS angezeigt, die das Fach **in der Sprachenfolge** haben
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/de7b9296-6570-4e22-99c1-fa7146c5a4fd)

-Dann kann eingegeben werden

**Comment by JuergenRichter** [comment]
Der Gruppenprozess "Abitur-Jahr" setzen kommt auch noch

**Comment by JuergenRichter** [comment]
Ist umgesetzt
