### ISSUE TITLE
Kleiner Tippfehler Schild-Chat (Beta)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#67]
Port ist wahrscheinlich gemeint. Nicht POrt:
![image](https://user-images.githubusercontent.com/75179015/103022167-b7982f80-454b-11eb-91e7-1888921f3621.png)

**Comment by FPfotenhauer** [comment]
Musste leider zunächst entfernt werden.
Wird zu einem späteren Zeitpunkt wieder aktiviert.
