### ISSUE TITLE
Akt. Halbjahr -> Leistungsdaten "Fächer kopieren" und "Einfügen" schlägt ohne Angabe von Gründen fehl

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#671]
Version 3.0.69.9
SVWS 0.6.5

Markiert man Fächer (auch ein einzelnes) und klickt auf "Fächer kopieren", erscheint eine Erfolgsmeldung.

Sollen Fächer in einem (leeren) Folgeabschnitt eingefügt werden, schlägt das Einfügen mit der Meldung fehl, "es konnten keine Fächer kopiert werden".

Ich habe in der Oberstufe mit Kursen getestet, aber zumindest die Fächer sollten ja herumkopiert werden können.

**Comment by AnneSchueller** [comment]
Bei Copy And Paste von einem Schüler zum nächsten funktioniert alles.
Wie hast du denn den Abschnitt angelegt? War das nach der Hochschulung?

**Comment by FrodBRA** [comment]
Der Abschnitt wurde beim Halbjahreswechsel angelegt.

Ich habe dann manuell bei einem Schüler Fächer eingetragen und habe versucht, diese in einen anderen Schülerdatensatz zu kopieren.

**Comment by AnneSchueller** [comment]
Dann schließe ich mal das Issue. Falls das nochmal auftritt, einfach nochmal öffnen.
