### ISSUE TITLE
Unterrichtsfächer "Fach" in "Details" setzen führt zu Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#672]
Version 3.0.69.9
SVWS 0.6.5

Wird die ASD-Bezeichnung in "Unterrichtsfächer" des Faches gesetzt, gibt es folgenden Fehler:

![UF_Fehler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/c6222f94-4f3d-454e-a7ee-e36e5121eb2a)

(Tritt auf, wenn ich korrekt Englisch setze, testweise versuche ich es mit Deutsch, das geht auch nicht.)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Das Problem tritt immer dann auf, wenn ich auf + zum Hinzufügen klicken, ich dann in das Feld ASD Bezeichnung wechsele und dann automatisch irgendein Fach ausgewählt wird. Die Leerzeile auf der linken Seite verschwindet dann.

[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11623977/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Behoben
