### ISSUE TITLE
Gruppenprozess "Abitur" -> "Mdl. Prüfungen A1 - A3 festlegen" startet die Eingabe nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#673]
Version 3.0.69.9
SVWS 0.6.5

Startet man den Gruppenprozess, wird das Protokoll angezeigt. Im Anschluss öffnet sich aber kein Fenster, um (Bestehens- und Freiwillige) Prüfungen tatsächlich einzugeben.

**Comment by AnneSchueller** [comment]
Ich habe das gerade nochmal mit dem GP von Schild2 verglichen. Der Prozess bestimmt nur Bestehensprüfungen und setzt entsprechend den Haken, wo mündliche Prüfungen anstehen. Das funktioniert in Schild3
