### ISSUE TITLE
Schüler -> Abitur: der Haken bei "Zulassungsberechnung automatisch" scheint nichts zu tun

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#676]
Version 3.0.69.9

Klickt man in Schüler -> Abitur auf "Leisungsdaten holen", werden die Leistungsdaten geholt und obwohl der Haken bei "Zulassungsberechnung automatisch" nicht gesetzt ist, wird automatisch die Markierung der Kurse durchgeführt und die Abiturzulassungsberechnung ebenfalls angeschlossen.

Wird der Haken gesetzt, ist das Verhalten identisch.

![SchILD_Schüler_Abitur_KurseMarkieren](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/efe9a153-b522-44b7-8812-52ded154662a)

**Comment by AnneSchueller** [comment]
Ehrlich gesagt weiß ich gar nicht, wofür der Haken ist. In Schild2 ist das ähnlich.
Kennst du die Hintergründe?

**Comment by AnneSchueller** [comment]
Durch Auswahl von "Leistungsdaten holen" werden automatisch die Kurse markiert und die Zulassung berechnet.

Die Frage wäre, ob man dann nicht die Button "Kurse algorithmisch markieren" und "Zulassung berechnen" rausschmeißt und den Button "Leistungsdaten holen" umbenennt in "Leistungsdaten holen und Zulassungsberechnung"?

Der Haken Zulassungsberechnung automatisch kann dann raus

Da ich selbst damit nie real arbeite möchte ich diese Entscheidung nicht treffen. 
Wenn die Button allerdings so bleiben, würde ich bei "LD holen" noch keine Markierung und Berechnung vornehmen.
@Raffenberg : Wie wäre deine Meinung?

**Comment by FrodBRA** [comment]
Ich würde die Kleinschrittigkeit behalten. 

Im Zweifel lassen sich so fehlerhafte oder nicht optimale Wahl des Markierungsalgorithmus überschreiben und basierend auf einer manuellen Veränderung die Zulassungsberechnung durchführen.

Der Haken macht Sinn, scheint aber nicht zu funktionieren. Er sollte per Standard gesetzt sein, denn i.d.R. möchte man für korrekt vorliegende Leistungsdaten ja direkt eine Markierung und Berechnung durchführen.

**Comment by AnneSchueller** [comment]
Da hast du Recht. Das mit dem händischen Nachtragen würde dann nicht mehr klappen.

**Comment by JuergenRichter** [comment]
Der Haken spielt dann eine Rolle, wenn die Markierungen händisch aktiviert bzw.  deaktiviert werden (über Doppelklick).

**Comment by AnneSchueller** [comment]
Also wenn ich das jetzt richtig verstanden habe:
Ist der Haken aktiviert (also Zulassung automatisch berechnen) und ich markiere Kurse händisch, so wird nach jeder Markierung die Zulassung geprüft.

**Comment by JuergenRichter** [comment]
So sollte es sein.
