### ISSUE TITLE
Schüler -> Abitur: Fehler im Dropdown-Menü für Abiturprüfungspunkte (Eintrag AT)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#677]
Version 3.0.69.9
Das Dropdownmenü lässt den Eintrag "AT" zu, wählt man diesen an, gibt es eine Fehlermeldung 

> 'AT' ist kein gültiger Integerwert für 'Prf.~Pkt.'

**Comment by JuergenRichter** [comment]
In SchILD2 gibt es übrigens die gleiche Fehlermeldung, ist wohl noch nie verwendet worden. Ich nehmen AT aus der Liste raus
