### ISSUE TITLE
Schüler -> Abitur: Dropdown-Menü Prüfungspunkte bedient sich unintuitiv mit Fehlerquellen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#678]
Version 3.0.69.9

Das Dropdown-Menü für die Prüfungspunkte benimmt sich etwas hakelig.

Möchte man "1 Punkt" eingeben, springt der Eintrag auf "15".

Wählt man über die Liste 1 Punkte (oder jede andere einstellige Zahl), springt der Wert auf "01" (oder "06" für eine Eingabe von "6"). 

Gibt man aber "01" ein, springt der Wert auf "00" (das gilt für alle einstelligen Zahlen).

Vorschlag: Das Dropdown-Menü sollte durch ein reines Eingabefeld ersetzt werden, das bei Angaben von nicht-Ints oder Ints außerhalb von 0 bis 15 eine Fehlerbox anzeigt und den Wert nicht übernimmt.

**Comment by JuergenRichter** [comment]
Ich habe mal testweise die Werte in umgekehrter Reihenfolge (0 zuerst, 15 zuletzt) geordnet, außerdem die Option "AutoDropDown" deaktiviert. Dann funktioniert die manuelle Eingabe recht gut, ohne dass die Gefahr besteht, eine falsche Punktzahl einzutragen
