### ISSUE TITLE
Schüler -> Abitur: Fehlermeldung bei nicht-bestandenem Abitur mit noch offenen mündlichen Prüfungen sollte klarer sein

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#679]
Version 3.0.69.9

Sind die Prüfungsleistungen im Abitur nicht ausreichend zum Bestehen, meldet SchILD bei einem Klick auf "Gesamtergebnis berechnen" die folgende Fehlerbox

> Abiturleistungen unvollständig

Hier bezieht sich die Unvstollständigkeit auf noch offene mündliche Prüfungen, die auch eventuell erst nach zum Bestehen nicht-ausreichenden Leistungen in vorherigen Nachprüfungen anliegen.

Die Textbox könnte die Information erhalten, dass noch mündliche Prüfungen offen sind.

Wunsch: Grundsätzlich wäre bei der Fehlermeldung "Abiturleistungen unvollständig" ein Hinweis hilfreich, welches konkrete Kriterium verletzt wurde, das die Meldung ausgelöst hat.

**Comment by JuergenRichter** [comment]
Es werden nun "sprechendere" Meldungen ausgegeben

**Comment by FrodBRA** [comment]
Die Textbox ist einzeilig. Es wird angezeigt "Abiturleistungen unvollständig:", der Doppelpunkt impliziert, dass noch etwas folgen soll, das aufgrund der einzeiligen Textboxhöhe abgeschnitten ist.

![AB_Leistungen_Unvollständig](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/1a806235-49c6-4949-b253-3edf96bb3330)

**Comment by AnneSchueller** [comment]
ggf. hier später mal die Fehlermeldungen anpassen. Läuft aber bei meinen Tests, sofern alle Daten richtig eingegeben sind.

**Comment by FrodBRA** [comment]
Ein wenig Gefrickel ist zumutbar und das Verhalten gleicht SchILD2. Um hier die Issues weiter unter Kontrolle zu halten, würde ich diese Issues erst einmal schließen. Bei Bedarf können wir ein neues Erstellen.

@AnneSchueller Falls du das nicht so siehst, bitte wieder öffnen.
