### ISSUE TITLE
Suchen und Filter in den Katalogen funktionieren nicht

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#68]
In den Katalogen haben die Icons "Suchen" und "Filter" bei mir keine Funktion.
![image](https://user-images.githubusercontent.com/75179015/103023238-e0212900-454d-11eb-822a-9ca576690b95.png)

**Comment by FPfotenhauer** [comment]
Wo ist dieses Ribbon genau zu finden?

**Comment by Kluesenerm** [comment]
Schulen in NRW und andere Schulen und Schulformen.

**Comment by FPfotenhauer** [comment]
Sieht bei mir anders aus.
Aber auch bei mir sind die Funktionen nicht korrekt gegeben. Suchen klappt z.B. in Staatsangehörigkeiten, abe rnicht un SchulenNRW.

![SNAG_2020_12_24_15 08 09](https://user-images.githubusercontent.com/34127980/103093226-fa184580-45f9-11eb-8d2a-72482a3df0b2.png)

**Comment by JuergenRichter** [comment]
Ist nun anders gelöst, ich schließe das mal.
