### ISSUE TITLE
Schüler -> Abitur: Berechnung der Prüfungsabiturpunkte (Feld "Zw. St.") ist fehlerhaft; die Berechnung wirkt auch nicht zuverlässig

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#681]
Version 3.0.69.9
SVWS 0.6.5

Gibt man Prüfungsergebnisse im Abitur ein und klickt auf "Gesamtergebnis berechnen" ist das angezeigte Ergebnis in "Zw. St." manchmal fehlerhaft!

Dieses "manchmal" scheint aufzutreten, wenn Ergebnisse eingetragen werden, dann wird berechnet, dann werden korrigierte Ergebnisse eingetragen und neu berechnet. Die Spalte "Zw. St." aktualisiert sich teilweise, teilweise nicht.

"Ges. Erg" scheint bis hierher korrekt zu sein und die Ergebnisse fließen im Block II ein. Ich habe bislang noch nicht mit zusätzlich eingetragenen Nachprüfungen getestet. 

WEITERHIN: Wenn man (die) Prüfungsergebnisse entfernt und auf "Ges. Erg. berechnen" klickt, wird "Zw. St." nicht aktualisiert, ebenso werden "Ges. Erg." und der Block II nicht aktualisiert, so dass die Abiturprüfung u.U. trotz nicht vorhandener Prüfungsergebnisse bestanden bleibt!

**Comment by JuergenRichter** [comment]
Bei Änderungen in der Spalte "Prf. Pkt." wird jetzt (wie bei SchILD2) der Inhalt der Spalte "Zw. St." gelöscht.

**Comment by FrodBRA** [comment]
3.0.71.9: Die Löschung funktioniert, ebenso wirkt der Reiter "Abitur" nun vollständig.

Geschlossen.
