### ISSUE TITLE
GP Abitur->Leistungsdaten holen erzeugt Fehlermeldung

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#682]
[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11652119/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Laut Code kann das aber vorkommen, wenn keine Daten für den Abiturbereich gefunden werden. Kann man abfangen, trotzdem wäre es hilfreich, wenn ich mal die Datenbank (als mdb) bekommen könnte.

**Comment by AnneSchueller** [comment]
Da ich mit der DB in Schild3 relativ viel rumexperimentiert habe, bin ich mir nicht sicher, ob die Original-MDB hier weiterhilft.

Das Problem tritt nur auf, wenn ich die Q2 filtere und dann direkt "Leistungsdaten holen" anstoße. Hier mal ein Video dazu:

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/d72d95fe-1e0c-4fc0-9cf9-5874cf962a01

Wenn ich danach die Markierung entferne, läuft der Prozess ohne Fehlermeldung.
Wenn ich dann Jg 8 filtere und dann wieder auf Q2 erhalte ich erneut eine Fehlermeldung.

**Comment by AnneSchueller** [comment]
Das Problem besteht immer noch (mit einer anderen Datenbank getestet). Wir werden ja mit Gymnasien starten, daher wäre hier eine zeitnahe Korrektur bzw. zielführende Fehlermeldung wichtig.
ich habe hier die DB hochgeladen:
https://membox.nrw.de/index.php/s/GQKyMVFSmwc2mpv
Passwort schild

**Comment by JuergenRichter** [comment]
Habe die Datenbank heruntergeladen, werde das zeitnah testen.

**Comment by JuergenRichter** [comment]
Ich konnte den Fehler reproduzieren. Nachdem der Vorgang "architektonisch" etwas umgebaut wurde, funktioniert es nun einwandfrei (und viel schneller als zuvor).

**Comment by FrodBRA** [comment]
@AnneSchueller Ist der Fehler bei dir auch verschwunden?

**Comment by AnneSchueller** [comment]
Mit meiner aktuellen Abitur DB tritt der Fehler nicht mehr auf.
Danke für die Erinnerung :-)
