### ISSUE TITLE
Markierung geht verloren

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#683]
Beim Wechsel von Gruppenprozessen auf einen anderen Reiter geht die Markierung der SuS verloren

**Comment by AnneSchueller** [comment]
Immer noch in Version 3.0.74.10

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren, vielleicht gehe ich auch anders vor. Wäre es möglich, mal ein kurzes Video zu posten?

**Comment by JuergenRichter** [comment]
Ich habe die Logik bei dem Thema "Markieren, Gruppenprozesse" nochmal überarbeitet. Bitte im nächsten Update genauer prüfen.
