### ISSUE TITLE
In Schule -> Weitere Angaben eingetragene "Merkmale" stehen in den ID II nicht zur Auswahl

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#686]
Version 3.0.69.9

Ich habe in der Schule unter Weitere Angaben Merkmale eingetragen (an einem Test-Gym), etwa 13+ oder "Arbeitssprache in der Gym. Oberstufe Englisch).

Diese Merkmale stehen unter Individualdaten II -> Besondere Merkmale nicht zur Auswahl.

Hier kann ich nur "Ganztagsschule" wählen.

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Auch mit einer Grundschuldatenbank.

![2023-06-06_205522](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/711453f3-af62-4d1a-bc3a-0686bc3f3191)

![2023-06-06_205505](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/5ae3141e-029e-4614-8ece-6e83c22dfe9c)

**Comment by JuergenRichter** [comment]
Behoben, die neu eingegebenen Datensätze müssen aber (mit dem neuen Update) nochmal gelöscht und erneut eingegeben werden.
