### ISSUE TITLE
Export -> ZK-Daten erzeugt diverse Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#687]
Version 3.0.69.9
SVWS 0.6.5

Export > ZK-Daten erzeugt diverse Fehler

Wähle ich die EF an, bekomme ich einen E/A-Fehler 32, ansonsten habe ich einen SQL-Fehler:

![ZK](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/76d53af2-f050-449c-b151-a8f345b0dad1)

Teilweise habe ich auch den Eindruck, dass Fehler kommen, wenn nicht alle notwendigen Daten gesetzt sind, etwa, wenn der Jahrgang offengelassen wurde.

**Comment by AnneSchueller** [comment]
Ich kann die Fehlermeldung nicht reproduzieren. Bei mir klappt der Export. Funktioniert der Export mit der analogen DB in Schild2?
Könntest du evtl mal auf "Copy to Clipboard" klicken, die generierte Fehlerdatei schild3.el im Ordner Documents umbenennen in schild3.txt und diese Datei hier anhängen?

Mit diesem Fehlerprotokoll kann Herr Richter die Fehlerquelle schneller finden und prüfen woran es liegt.

**Comment by FrodBRA** [comment]
Die Datenbank, mit der dieser Fehler unterlief, liegt mir nicht mehr vor, da sehr viele andere wichtigere Aspekte weiterbearbeitet wurden.

Ich schlag vor, das Issue zu diesem Zeitpunkt zu schließen und bei einem erneuten Auftreten systematisch zu testen.

**Comment by FrodBRA** [comment]
Vorerst geschlossen
