### ISSUE TITLE
Infobutton im Abiturreiter

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#688]
In Schild2 gibt es eine Button "i" zum Öffnen von Erläuterungen zu den Abkürzungen.
Könnte man den in Schild3 noch einpflegen?

**Comment by JuergenRichter** [comment]
Ist umgesetzt, aber etwas anders als bisher (andere Grid-Komponente)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/3159a3a5-28b6-45a1-8b61-c339ca78936f)
