### ISSUE TITLE
Vergrößerung von Fenstern

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#689]
Wäre es möglich, dass man hier manuell das Fenster (roter Kasten rechts) größer ziehen kann, wie auf der linken Seite (roter Kasten links)?
Das hin und her scrollen, um das Gesamtergebnis zu sehen ist lästig.

![2023-06-09_100254](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/a220cb08-b2b2-4c0c-a5a7-1fc6b65003a0)

**Comment by JuergenRichter** [comment]
Ist umgesetzt, aber nicht mit "Splitter". Ich habe jetzt die Abiturtabelle und die Auswertung so angepasst, dass der gesamte zur Verfügung stehende Platz ausgenutzt wird,

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/ed262c38-5324-426a-9d5e-dd0b41285e29)
