### ISSUE TITLE
Encodingfehler im Installer 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#691]
Version 3.0.69.9

Encodingfehler im Installer: 

![EncErr](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/837cb435-d4f8-4fab-a655-aa738b21fa16)

**Comment by JuergenRichter** [comment]
Das ist nicht meine "Baustelle"

**Comment by FPfotenhauer** [comment]
Behoben. Ich habe die 3.0.69-EXE in der FB-Cloud ausgetauscht.
