### ISSUE TITLE
Grundschule: Formatfehler und Tippfehler in Schule -> Weitere Angaben -> "Zurückgestellte Kinder"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#692]
Version 3.0.69.9

1. Der Text passt teilweise nicht in den vorgesehenen Platz.
2. Tippfehler in "zurückgstTelt". 

![GSFehler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/53efc50f-449e-4bc3-8e37-116e32450b23)

**Comment by JuergenRichter** [comment]
Behoben
