### ISSUE TITLE
Menü Sortierreihenfolge festlegen - Radiobutton "Sortierung Klasse" bleibt in der zuletzt gewählten Einstellung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#695]
Will man die Art der Sortierung  verschiedener Sortierparameter im Fenster 'Sortierreihenfolge festlegen´ ändern, so bleibt der Radiobitton nach dem Wechsel des Parameters in der zuletzt getroffenen Einstellung:
wählt man beispielsweise für einen Eintrag als Sortierung "absteigend" aus und klickt danach auf einen anderen Eintrag, dessen Sortierung "aufsteigend" ist, so bleibt der Radiobutton in der Einstellung "absteigend". Will man auch dem zweiten Eintrag die Sortierung "absteigend" zuweisen, so muss man den Radiobutton zunächst auf "aufsteigend" und danach wieder auf "absteigend" setzen, damit die Einstellung angenommen wird.

  
![Sortierreihenfolge_ändern_Radiobutton](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/ccf8a854-2f21-4250-9f4d-caaa2c2aafa7)

**Comment by AnneSchueller** [comment]
Ähnliches Problem: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/662

**Comment by JuergenRichter** [comment]
Behoben

**Comment by FrodBRA** [comment]
Test mit 3.0.71.9: Der Fehler trat bei mir nicht wieder auf.

**Comment by AnneSchueller** [comment]
Das Verschwinden des Button taucht auch bei mir nicht mehr auf, aber:

Klickt man auf Klasse -> absteigend
Anschließend auf Name
Der Radiobutton bleibt dann auf absteigend stehen, obwohl Name aufsteigend sortiert werden soll.

![2023-08-21_145116](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/b02ced5a-38d6-4d42-90c1-5bdc36f4b4bb)

**Comment by JuergenRichter** [comment]
Behoben
