### ISSUE TITLE
Menü Sortierreihenfolge festlegen - Fehler bei Wechsel der Reihenfolge nach Wahl der Standardsortierung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#696]
Wird im Menüfenster _Sortierreihenfolge festlegen_ die Standardsortierung mit Hilfe des Buttons _Standard-Sortierung-Wählen_ wiederhergestellt, kommt es nach der Änderung des Reihgenfolgeattributes zu einer Fehlermeldung, falls man die Auswahl zuvor nicht mit dem Button _Übernehmen_ bestätigt hat.

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/7bb18193-5708-46d9-b8ea-42ffd9550e31

![Fehler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/34cd8f74-6569-4778-8a68-69fa850a9dd6)

**Comment by AnneSchueller** [comment]
[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11721893/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Behoben
