### ISSUE TITLE
Funktion aus SchILD2 „Extras>>Fächer in Leistungsdaten neu sortieren“ fehlt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#698]
Version 3.0.69.9

Die Funktion, mit der die benutzerdefinierte Reihenfolge der Fächer aus "Kataloge" > "Unterrichtsfächer" in schon zugeordnete Leistungsdaten übernommen wird, fehlt in SchILD3.

Zu prüfen, ob eventuell auch die Reihenfolge in den Stundentafel aktualisiert werden muss.

**Comment by AnneSchueller** [comment]
Die Option findet man unter Gruppenprozess/Fächer
Bei den Schülerleistungsdaten klappt alles (akt. HJ und Übersicht)
Sortiert man Fächer im Katalog um, ist vor dem GP ein Neustart notwendig.

Die Sortierung bei den Stundentafeln produziert einen Fehler:

[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11738855/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Fehler beim Sortieren der Stundentafelfächer behoben
