### ISSUE TITLE
"Schnellfilter": Anmerkungen und Fehler

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#7]
Das aktuelle Konzept des Schnellfilters in Schild mit dem TreeDropDown ist aus meiner Sicht für die Schulpraxis ungeeignet und sollte unbedingt überdacht werden.

Nur ein Beispiel: man möchte auf die Jahrgangsstufen 07, 08, 09 filtern. Dafür muss man nun das Dropdown öffnen, herunterscrollen, den Knoten Jahrgangsstufe öffnen, die Stufen einzeln anklicken. Im alten System konnte man mit dem Klick ins Jahrgangsstufenfeld und der Tastatur direkt filtern. Das geht um Längen schneller.

Natürlich kann man in SchILD 3 auch die Jahrgänge eintippen, zumindest, wenn schon einer ausgewählt wurde (FEHLER: ist kein Eintrag gecheckt, kann man nichts eingeben).

Daher wäre hier die Überlegung, ob man nicht zu den alten Comboboxen zurückkehrt und so statt einer langen Liste mit mehreren MainNodes wieder pro Node eine Liste hat in die man direkt etwas eintippen kann.

**Comment by WLey-49** [comment]
Diese meinung zum Filter unterstütze ich voll und ganz!

**Comment by FPfotenhauer** [comment]
Ich fände es gut, wenn sich hier mehrere Fachberater mal beteiligen würden.
Aus meiner Sicht macht der neue Filter bei sehr kleinen Schulen Sinn, abe rich habe auch bei großen BKs schon gesehen, wie unhandlich das wird, wenn man viele Klassen und Jahrgänge hat.

**Comment by JuergenRichter** [comment]
Man könnte aber auch beide Verfahren alternativ (bei den individuellen Einstellugen) zur Verfügung stellen.

**Comment by WLey-49** [comment]
Das wäre eine sehr gute Lösung.

**Comment by AlexanderDedy** [comment]
Ich habe heute mal meine BK Datenbank migriert und mir ist aufgefallen, dass bei den Fachklassen jetzt die Bezeichnungen fehlen! In einem BK mit 27 verschiedenen Fachklassen wäre das praktisch nutzlos (selbst ich kenne nicht alle auswendig) und wird aber sehr oft gebraucht!
Bei den TreeDropDown bin ich zwiegespalten. Bei 170 Klassen ist das eine ewige suche... Allerdings ist die einfache Art mehrere Klassen aus verschiedenen Bereichen zu filtern sehr nützlich. Ich fände ich eine Kombination oder Wahlmöglichkeit sehr hilfreich. 
Vermisst habe ich die direkte Eingabemöglichkeit einer Klasse!!! Immer wenn ein KuK ein Anliegen hat ist die erste Frage: Klasse? - hier könnte ich mir aber auch ein Schortcut (strg+k) vorstellen. by the way (strg+f) funktioniert auch nicht mehr! oder kann man das einstellen?
![Bildschirmfoto 2020-12-01 um 14 43 55](https://user-images.githubusercontent.com/75326793/100768532-4907fc00-33fb-11eb-8baf-4f6b61a29bb4.png)

**Comment by M-Plu** [comment]
Aus meiner Sicht sollte es wie bisher ein Dropdown pro Eintrag geben. Innerhalb dieses DropDowns kann man dann die Auswahl per Checkbox ermöglichen. Das wäre dann ideale Lösung bezogen auf die Geschwindigkeit und Übersicht. 

Natürlich sollte dann wie bisher die direkte Eingabe per Tastatur möglich sein, wenn man das Dropdown nicht aufklappt.

Wenn man etwas konfigurierbar machen möchte, dann die Felder die in der Schnellauswahl eingeblendet werden. Z. B. wird so etwas wie Schulgliederung am Gymnasium eigentlich nie benötigt, da es an den Jahrgang gebunden ist. Auf die Art kann sich der Benutzer seine häufigsten Filterfelder dort ablegen.

**Comment by JuergenRichter** [comment]
Die zusätzliche/alternative Anzeige der Fachklassenbezeichnungen sollte kein Problem sein. Eine direkte Eingabe z.B. bei den Klassen ist übrigens auch möglich. Dazu in der baumstruktur "Klassen" anklicken, dann wird dort eim Eingabefeld sichtbar, da kann man  z.B. "10*" eintippen, um doe Klassen 10A, 10b... anzuzeigen.

**Comment by M-Plu** [comment]
Die Eingabe ist allerdings wenig intuitiv, weil der Benutzer sie nicht sieht (bis er klickt) und bei der letzten Version von Schild 3, die ich getestet habe, war die Eingabe nur möglich, wenn mind. eine Klasse angekreuzt war.

**Comment by WLey-49** [comment]
Der Filter"baum" sollte auch mit "Return" geschlossen werden, nicht nur mit Klick auf das Filtersymbol.

**Comment by JuergenRichter** [comment]
Wir haben jetzt bei den individuellen Einstellungen eine Option "Schnellfilter aus SchILD2 verwenden" geschaffen, aktualisierte Version kommt vorauss. morgen

**Comment by JuergenRichter** [comment]
Bei Benutzung des neuen Schnellfilters klappt die Baumstruktur nun bei Eingabe von "Return" ein.

**Comment by AlexanderDedy** [comment]
Die Suche mit * z.b. BFS20* funktioniert leider nicht und wird oft gebraucht um z.B. alle Klassen einer bestimmten Jahrgangs schnell auszuwählen.

**Comment by JuergenRichter** [comment]
BFS20 (ohne *) sollte aber alle Klassen fett markiere, die mit BSF20 beginnen. Wenn man eine davon anklickt, werden alle markiert

**Comment by AlexanderDedy** [comment]
Gesehen! Es wäre aber gut, wenn die anderen Klassen ggf ausgeblendet werden... Wenn ich bei uns VAT eingebe, muss ich mich durch 160 Klassen arbeiten um am Ende eine anzuwählen... mit VAT* + Return wäre es einfacher (vielleicht beides ermöglichen)

**Comment by FPfotenhauer** [comment]
Ist umgesetzt.
