### ISSUE TITLE
Schülerauswahl (Felder werden durch Layout nicht angezeigt)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#70]
In der Schülerauswahl lässt sich nicht erkennen, welcher Bildungsgang angewählt wird:
![image](https://user-images.githubusercontent.com/75179015/103211031-6a2f1000-4907-11eb-9524-6a1ae60d8d01.png)

**Comment by JuergenRichter** [comment]
Das sollte in 3.0.10 jetzt so aussehen:
![2021-02-17 18_00_26-625554336 - AnyDesk](https://user-images.githubusercontent.com/61280188/108240174-e0ebcb00-714a-11eb-8ac0-8c5b84a62d8e.png)

**Comment by JuergenRichter** [comment]
Ich schließe das mal, falls es mit der Version 3.0.10 weiter Probleme gibt, bitte mal die Schulform und die bei der Schule eingetragenen Gliederungen mitteilen.
