### ISSUE TITLE
Fachbezogene Floskeln: Filterung auf "Niveau" nicht möglich

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#701]
Version 3.0.69.9

Die Filterung auf das "Niveau" bei Fachbezogenen Floskeln ist nicht möglich.

Wird eine Fachbezogene Floskel unter "Schüler -> Leistungsdaten" eingegeben, tauchen die Floskeln auf. Wird auf das Niveau gefiltert, ist über das Dropdown Menü ein Wert "1" bis "10" anzuwählen. Die Floskel mit dem Niveau "01" verschwindet aus dem Filter.

Möglicher Fehler: Gibt man eine Floskel mit dem Niveau "1" ein, wird daraus "01" (evtl. ein String?). Vermutung: Floskeln werden anders gespeichert (Datentyp?) als der Filter bei der Eingabe erwartet. (Auch eine Floskel mit dem Niveau "10" lässt sich nicht Filtern). 

Hier müsste eindeutig geklärt sein, welche Werte eingebeben und auf welche gefiltert werden kann.

**Comment by JuergenRichter** [comment]
Problem ist behoben. Es lag an einem Groß/Kleinschreibungsproblem ("Fach", "FACH"), dass die Niveaus nicht korrekt ermittelt wurden.
Bei Fach-Floskeln werden für die Niveaustufen nun die Einträge angeboten, die im Floskelkatalog zugewiesen wurden. Die Niveaustufen können von der Schule frei vergeben werden (z-B. A,B,C oder 01,02,03...). Bei der Floskeleingabe für ein fach werden nun alle für dieses Fach im Kataloge vergebenen Niveaus zur Auswahl angeboten.
