### ISSUE TITLE
Fehlerhafte Darstellung in Akt. Halbjahr -> Bemerkungen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#702]
Version 3.0.69.9

![BemFehler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/2590bd93-6ebd-4bf0-84ed-2b7010a604f3)

**Comment by AnneSchueller** [comment]
Hier auch mal meine Ansicht:

![2023-06-19_093718](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/a1f0ebf9-0e9e-40c8-beb8-f17fbcc17200)

**Comment by FrodBRA** [comment]
Den Fehler hatte ich auch, konnte ihn aber nicht reproduzieren.

Manchmal verschieben sich die Fenster ineinander und es braucht einen Neustart, um das Problem zu beheben. Teilweise wird es erst normal gerendert, kehre ich dann auf diese Ansicht zurück, ist sie so wie im Screenshot.

**Comment by JuergenRichter** [comment]
Behoben
