### ISSUE TITLE
Ankreuzkompetenzen: Akt. Halbjahr -> "Kompetenzen für Ankreuz..." sind die Kompetenzfelder zu klein, um damit zu arbeiten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#703]
Version 3.0.69.9

Die Felder, in denen individuell Ankreuzkompetenzen angekreuzt werden, sind von der Größe her nicht benutzbar.

Sie lassen sich nicht vergrößern.

Hier sollte eine größere Standardansicht verwendet werden, die von Höhe und Breite alle Einträge zulässt. Idealerweise sollten auch mehrzeilige Kompetenzen voll angezeigt werden.
![AKzuKlein](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/114342db-0a01-4e89-8c0e-cc4f1a539a1e)

**Comment by AnneSchueller** [comment]
@FrodBRA Ich kann das bei mir die Spaltenbreite manuell ändern.

Sofern das mit dem Layout-Element möglich ist, wäre ein automatischer Zeilenumbruch wünschenswert.

**Comment by FrodBRA** [comment]
Das manuelle Ändern bei einer mit fixer Größe gesetzten Textbox stößt bei unseren Benutzern auf kein Verständnis, soviel wird in der Schulungen auf jeden Fall deutlich. Hier sollte die Voreinstellung unbedingt ohne weiteren Eingriff zum Fenster passen.

Ich schlage auch vor, das Feld der Kompetenzbeschreibung auch so länger zu setzen.

"Zweizeilig" ist eine gute Idee hilft mitunter bei der schmalen Voreinstellung nicht. Gerade wenn man noch Unterkategorien setzt, passen die Beschreibungen auf keinen Fall und bei genutzten Unterkategorien muss das Textfeld weiter gezogen werden, als das ganze Fenster an Platz überhaupt bereitstellt.

Hier ist gut zu sehen, dass das Fenster generell zu klein ist und bei der Verwendung von Unterkategorien nahezu unbenutzbar wird:

![AKzuKlein2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/db533551-9988-4382-9b9d-936f13580a3d)

**Comment by JuergenRichter** [comment]
Es gibt bei der Grid-Komponente eine Eigenschaft "RowSizing". Damit kann man (ähnlich wie bei der Spaltenbreite) die Höhe der Zeilen einstellen. Beispiel

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/37c3e434-89fc-4d43-bd68-1688218fa231)

**Comment by AnneSchueller** [comment]
Das sieht besser aus. Wobei die Default-Breite vom dem Kompetenzfenster m.E. größer gewählt werden kann. 
Aber das hat erstmal keine Priorität

**Comment by JuergenRichter** [comment]
Die Breite der "Untertabelle" (mit den Kompetenzbeschreibungen) richtet sich nach der Breite der übergeordneten Tabelle (Fach). Wenn man also die Spalte "Fach" breiter zieht, hat auch die Untertabelle mehr Platz.

**Comment by JuergenRichter** [comment]
Ist jetzt auch für die "übergeordnete" Tabelle und für die Tabelle der "normalen" Leistungsdaten umgesetzt.
