### ISSUE TITLE
Ankreuzkompetenzen: Akt. Halbjahr -> "Kompetenzen für Ankreuzk..." unklar, was die höchste und niedrigste Stufe ist

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#704]
Version 3.0.69.9

Die Kompetenzen sind von 1 bis 5 nummeriert. Es ist auf den ersten Blick nicht ersichtlich und nicht eindeutig ersichtlich, welche die höchste und niedrigste Stufe ist.

Ist "1" besser oder "5"? Das hängt davon ab, wie diese definiert wurden. Hier wäre es vermutlich sinnvoll, die definierten (auch mehrzeiligen) Bezeichner aufzunehmen.

Es ist auch nicht davon auszugehen, dass die Person, die den Katalog pflegt bzw. dort nachsehen kann, auch die Person ist, welche die Kompetenzbewertung vornimmt. 

![AKzuKlein](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/23b3b98f-ffb4-4a61-bff9-26e531002457)

**Comment by FrodBRA** [comment]
Die definierten Stufen in der Kopfzeile unter de Reitern anzuzeigen, notfalls zweizeilig, wäre in der Praxis eine gute Lösung.

**Comment by JuergenRichter** [comment]
Ist schon behoben

**Comment by JuergenRichter** [comment]
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/d6a96a6b-167b-4611-b085-8233f15bcc36)
