### ISSUE TITLE
SQL Fehler bei Hinzufügen eines Schülers

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#706]
Version 3.0.69.9

In der vorliegenden DB gibt es einen Fehler (mit Lehrerdaten) beim Hinzufügen eines neuen Schülers:

![NeuerSchüler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/10bbf526-3368-4732-b0d2-68f95e0bb78b)

**Comment by AnneSchueller** [comment]
Das kann ich hier nicht reproduzieren.
Hast du nach dem Öffnen von Schild3 unmittelbar auf Schüler hinzufügen geklickt? 
Hilfreich ist es immer, wenn auch das Protokoll mit angehängt wird. Dieses wird durch Auswahl von Copy to Clipboard generiert.

**Comment by JuergenRichter** [comment]
Kann ich auch nicht reproduzieren.

**Comment by FrodBRA** [comment]
Ich kann das ebenfalls nicht mehr reproduzieren. Das muss an der DB gelegen haben oder war ein einmaliger Glitch. Die Meldung deutet ja auch darauf hin, dass es sich eigentlich um ein Problem bei/mit Lehrkraftdaten zu tun hat.

Ich schlage vor, den Report zu schließen und bei einem Wiederauftreten systematisch zu prüfen.

**Comment by FrodBRA** [comment]
Bei Neuauftreten wiederaufzunehmen. Vorerst geschlossen.
