### ISSUE TITLE
"Online Supportprogramm starten" ist über "Hilfe" aus SchILD direkt nicht möglich.

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#708]
Version 3.0.69.9

Falls dieses Feature gewünscht ist, sollte eine Schaltfläche die gewählte Remote-Desktop Lösung öffnen.

(Ansonsten würde ich den Wikieintrag so schreiben, dass das Starten über den Windows-Explorer erfolgt.)

**Comment by JuergenRichter** [comment]
Den Menüpunkt gibt es:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/26dfc6a6-f54e-42c1-9290-151cff91e949)
Es wird geprüft, ob es die Datei "\Onlinesupport\TeamViewerQS.exe" gibt. Wenn das der Fall ist, wird der Punkt angezeigt.
Ich habe aber festgestellt, dass im Quellcode beim Verzeichnis ein Schreibfehler war:
\Onlinesupp**0**rt statt \Onlinesupport
Ist nun korrigiert.

**Comment by FrodBRA** [comment]
Das erklärt es.

Mein von SchILD 3.0.69.9 angelegtes Verzeichnis heißt "OnlineSupport". Ist das große "S" ein Problem?

**Comment by JuergenRichter** [comment]
Nein, in "Support" stand statt einem "o" eine "0" (Null). Sie können folgendes tun:
-Ein Verzeichnis \Onlinesupp0rt anlegen
-Aus dem Verzeichnis \Onlinesupport die Teamviewer-Datei in das neue Verzeichnis kopieren.
-Dann sollte eigentlich der Menüpunkt erscheinen.

Mit dem nächsten Update kann das Verzeichnis wieder gelöscht werden.
