### ISSUE TITLE
"Versionsgeschichte zeigen" über "Hilfe" nicht aufrufbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#709]
Version 3.0.69.9

SchILD3 sieht einen Knopf hierfür derzeit über "Hilfe" nicht vor.

Falls dieses Feature nicht gewünscht ist, entfernen wir den geplanten Wiki-Artikel.

**Comment by JuergenRichter** [comment]
Welcher Link wäre das denn?

**Comment by AnneSchueller** [comment]
https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Versionsgeschichte_von_SchILD-NRW

**Comment by JuergenRichter** [comment]
Ist umgesetzt
