### ISSUE TITLE
Schnellfilter Ansicht

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#71]
Wenn man mit einer BK-Datenbank auf die alte Schnellfilter-Ansicht umschaltet, so stimmen die Positionen nicht.
Auch bei den anderen Schulformen sieht es nicht ganz optimal aus.

![SNAG_2021_01_01_17 11 47](https://user-images.githubusercontent.com/34127980/103442227-a12d5a80-4c54-11eb-85a0-b6b661f2a0d2.png)

![SNAG_2021_01_01_17 11 16](https://user-images.githubusercontent.com/34127980/103442229-a4c0e180-4c54-11eb-8a20-7f008b976eb4.png)

**Comment by JuergenRichter** [comment]
Ist in Version 3.0.9 korrigiert

**Comment by JuergenRichter** [comment]
Ich schließe das mal, falls noch Probleme auftreten, wieder öffnen
