### ISSUE TITLE
Abschlussberechnung in Schild3

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#710]
Laufen nur die Abschlussberechnungen für Gesamtschulen über den Server?
Die Einträge unter akt. HJ. bleiben nach Berechnung leer (Gymnasium)
Das aufgeploppte Fenster zeigt noch FOR statt MSA.

Sollten die Methodennamen ggf. angepasst werden?
![2023-06-20_225815](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/2a1c4b65-51b2-4835-bd12-ff940b1cc0f4)

**Comment by FPfotenhauer** [comment]
Schild3 berechnet momentan noch alle Abschlüsse selbst.
Die Namen der Endpunkte kann man nicht einfach umbenennen.
