### ISSUE TITLE
Version Schild3 und SVWS-Server

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#711]
Wir benötigen eine Funktion, die beim Start von Schild3 die Version des Servers ausliest. So einen Endpunkt gibt es bereits.
Das SVWS-Server Team sollte dann festlegen können, mit welcher Version vom SVWS-Server dann Schild3 startet.

Vorschlag wäre, eine Textdatei mit der zulässigen Versionsnummer im Schild3 Programmverszeichnis.
Das "-SNAPSHOT" könnte dann ignoriert werden, bei Developer-Systemen.

Das hat zwar den Nachteil, dass User selbst dort manipulieren können, aber Fachberater könnten dort dann auch Entwicklersysteme simulieren.

{
	"version": "0.6.11-SNAPSHOT"
}

**Comment by JuergenRichter** [comment]
Verstehe ich das so richtig?
-SchILD3 ermittelt über API-Aufruf die Version des SVWS-Servers
-Dann wird aus der Textdatei ausgelesen, welche SVWS-Server-Verison die SchILD3-Version mindestens benötigt
-Wenn die die vorliegende Version des SVWS-Servers niedriger ist als die aus der Textdatei, kommt ein Hinweis bzw. startet das Programm nicht

**Comment by FPfotenhauer** [comment]
Ja. Und vielleicht auch ob die SVWS-Server-Version zu neu ist! Wir machen schließlich auch DB-Anpassungen. Zwar nur im Notfall, aber das kann ja vorkommen. Das würden wir ja mit Ihnen absprechen.

**Comment by FPfotenhauer** [comment]
Soll ich mal eine Beispieldatei ins Programmverzeichnis legen (einchecken)?

**Comment by JuergenRichter** [comment]
Wenn die Datei wie im obigen Beispiel aufgebaut ist, kann ich mir die auch selbst erstellen. Ich vermute, dass die Datei UTF-8 kodiert sein soll?


{
"version": "0.6.11-SNAPSHOT"
}

**Comment by FPfotenhauer** [comment]
{
"server_version": "0.6.11"
}

Dateiname wird sein: server.json

**Comment by JuergenRichter** [comment]
Ist umgesetzt
