### ISSUE TITLE
Datenbankmigration: SchuelerLernabschnittsdaten.Folgeklasse wird nicht migriert

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#712]
### Migrate 1.0.16.9
Die Spalte Folgeklasse_ID in der Tabelle SchuelerLernabschnittsdaten ist nach der Migration leer.

In der neuen Datenbank wird die ID der Klasse abgelegt. In der alten 2.0 Datenbank steht dort das Kürzel.
Hier müsste also ein Lookup der ID stattfinden.

**Comment by ThomasBachran** [comment]
Zunächst müssen wir klären ob das Verhalten in diesem Fall ein Fehler ist oder beabsichtigt ist. In der Klassentabelle ist immer ein Default-Wert für die Folge-Klasse angegeben. 

1. Entspricht der Eintrag in den SchuelerLernabschnittsdaten diesem Default-Wert, so wird der Eintrag bei dem Lernabschnitt nicht übernommen - er ist redundant. Schild 3 sollte in diesem Fall aber den Default-Wert anzeigen. Ist dies der Fall?
2. Ist noch ein Folgeabschnitt angelegt, so existiert in der Klassentabelle auch noch keine Klasse und es kann keine ID zugeordnet werden. Daher ist sie nach der Migration zunächst leer. Es müsste also bei der Migration ein zusätzlicher Lernabschnitt angelegt werden. Handelt es sich um diesen Fall
3. Ist ein Folgeabschnitt in der Tabelle Schuljahresabschnitt und damit in der Tabelle Klassen angelegt, so müsste die Folge-Klassen-ID gesetzt sein. Das müsste also insbesondere bei vergangegen Abschnitten der Fallse in
4. Der Eintrag ist inkonsistent und ist auch in Schild 2 nicht in der Versetzungstabelle enthalten

@EwaldReinhardt : Wie ist das in diesem Fall einzuordnen?

**Comment by ThomasBachran** [comment]
@EwaldReinhardt: Den Fall 2 aus dem letzten Kommentar habe ich soeben implementiert. In dem nächsten Release müsste er dann in der Migration beachtet werden.

**Comment by EwaldReinhardt** [comment]
Mir ist das aufgefallen, da ich bei der Schuljahreswechsel in Schild2 Fehler und bestimmte Verhalten hatte, die ich unter Schild3 prüfen wollte. Wir hatten bei den Folgeklassen entsprechend die Werte alle eingetragen, die dann aber leider nach der Migration fehlten.

### zu Punkt1:
In Schild3 wird extra ein Punkt angeboten, dass der Eintrag entsprechend vorgenommen wird, wenn er leer ist.
Dann kann das auch gleich bei der Migration übernommen werden.
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/7831e1c5-a374-4fd3-94ac-2317f7cda394)
Auch wenn es nicht eingetragen ist, wird bei Aktion 3 die Folgeklasse aus der Tabelle Klassen eingetragen.
Nach der Aktion 1 sind beim nächsten Aufruf automatisch die Aktionen 3, 4 und 5 aktiviert. Sonst nur 3.

### zu Punkt2: 
Für die zukünftigen Abschnitte fehlt der Eintrag, wie erläutert.

Trotzdem sind zuviele Einträge in der Tabelle Klassen erzeugt worden:
Grundsätzlich gibt es BKs, die in der Klassenbezeichnung das Einschulungsjahr kodieren und die Schüler in ihrer Laufbahn in der gleichen Klasse verbleiben. HBF11=Einschulung 2021  HBF21=Einschulung 2022 etc. Die Klassenbezeichnungen wiederholen sich also alle 10 Jahre. Die Klasse HBF11 (Höhere BerufsFachschule 2021 1. Zug) existiert daher nur in den Jahren 20[0-9][12], da der Bildungsgang 2-jährig ist. Daher macht es keinen Sinn, für alle Schuljahresabschnitte einen Eintrag in der Klassentabelle zu generieren. Man sieht zum Beispiel im folgenden Bild, dass die Werte alle gleich sind, da auch kein **Klassenlehrer** an der Stelle abgelegt ist.
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/3e453525-4d63-49e1-99a6-8a2db0468944)

Die gültigen Halbjahre liefert für die Schild3-DB:

> select distinct K.Klasse , SA.Jahr, SA.Abschnitt 
> FROM bkt.schuelerlernabschnittsdaten SLAD
> inner join Klassen k 
>   on k.id = slad.Klassen_ID 
> inner join schuljahresabschnitte sa 
>   on sa.ID = slad.Schuljahresabschnitts_ID 
> order by 1,2,3

(Anmerkung zur Tabelle: sollten die Spalten FKlasse und VKlasse nicht FKs auf Klassen.ID sein. Sonst ist das ja nicht eindeutig, bzw. es können Namen eingetragen werden, die nicht vorhanden sind.)
### zu Punkt3:
Ja, bei alten Abschnitten sind Folgeklassen_IDs gesetzt, wenn es vom Wert in der Klassentabelle abweicht. (War in Schild3 schwer zu erkennen, da Schild3 das Eingabefeld zuerst immer leer war. Erst als ich einmal das Dropdown von Folgeklasse aktiviert hatte (im Reiter akt. Halbjahr) wurde der Wert angezeigt.) 
### zu Punkt4:
Der Fall ist bei mir nicht aufgetreten.

### Anmerkung zu Tabellen
- Tabelle Schuljahresabschnitte 
Hier wäre es schön, wenn die ältesten Abschnitte die kleinste ID haben, damit die Reihenfolge mit der Reihenfolge der ID übereinstimmt.
- Tabelle Schuelerlernabschnittsdaten
Hier könnte es zu Inkonsistenzen kommen, wenn 
SLAD.Schulerjahresabschnitts_ID <> Klassen[SLAD.Klassen_ID].Schuljahresabschnitts_ID

@ThomasBachran: Ist das nachvollziehbar? Soll ich unsere Datenbank anonymisiert bereit stellen?

**Comment by FPfotenhauer** [comment]
zu Punkt 1:
Die Punkte 1 und 3 können aus meiner Sicht eigentlich entfallen. Wenn Folgeklasse leer, dann gilt die Default-Folgeklasse aus der KLassen-Tabelle. Wenn Abschnitt beim Schüler nihct vorhanden, wird aber benötigt, dann wird der Abschnitt automatisch mit Defaultwerten angelegt. @JuergenRichter Wie sehen Sie das?

zu Punkt 2:
Die Klassenlehrer sind jetzt in der Tabelle "Klassenlehrer". Was kommt dort bei dir an? @EwaldReinhardt 

zu Punkt 3:
Wir können keine FolgeklassenIDs speichern, weil es diese IDs u.U. noch nicht gibt. Hie rist ein UC auf der KLassenbezeichnung.
In Schild3 könnte es sich hie rnoch um einen Darstellungfehler handeln.

@EwaldReinhardt Die DB wäre sehr hilfreich.

Anmerkung zu den Tabellen:
Das wird bei der Migration über Trigger gelöst und nicht ohne Weiteres umsetzbar.

**Comment by JuergenRichter** [comment]
@JuergenRichter Wie sehen Sie das?
Der Bezug zwischen der Tabelle "Schueler" und "SchuelerLernabschnittsdaten" wird ja (zusätzlich zur Schüler-ID) über die "Schuljahresabschnitts-ID" hergestellt. Wenn es für die Schuljahresabschnitts-ID, die in der Tabelle Schueler eingetragen ist, keinen passenden Datensatz in SchuelerLernabschnittsdaten gibt, wird dieser angelegt. Angaben z.B. zu Klasse und Jahrgang können dabei aber nicht angelegt werden, da diese ja gar nicht (anders als in SchILD2) bekannt sind.

**Comment by EwaldReinhardt** [comment]
zu Punkt 2:
Die Klassenlehrer sind jetzt in der Tabelle "Klassenlehrer". Was kommt dort bei dir an? 
In der Tabelle Klassenlehrer kommen die Lehrer an.
Da scheint aber auch nicht alles richtig zu sein. Ich mache ein neues Item #714 auf.

**Comment by FPfotenhauer** [comment]
@JuergenRichter 
Ich würde das gerne etwas konkreter klären.
Kann man bei dem Punkt 1 Folgeklasse automatisch füllen, wenn leer auch auf dem Standpunkt stehen, mann lässt sie in der DB beim SchuelerLernabschnitt einfach leer. Bei der Versetzung wird bei leer dann einfach der Defaultwert in der Klassentabelle genommen. So müsste man nur Abweichungen in der DB vom Default eintragen. Man könnte sogar bei LEER einfach den Default anzeigen!

**Comment by FPfotenhauer** [comment]
Ich würde das Issue gerne schließen.
Den Vorschlag, dass die Folgeklasse leer bleiben darf und dann der Default aus der Klassentabelle genommen wird, soll bitt eumgestezt werden. (Kann sogar sein, dass das schon so ist.)

**Comment by JuergenRichter** [comment]
"Kann sogar sein, dass das schon so ist"
Bei der Versetzung ist das so. Meine vorherige Bemerkung bezog sich auf den folgenden Fall:
Wenn SchILD3 feststellt, dass es für einen Schüler keinen aktuellen (aus Sicht des Schüler, d.h. zu dessen "Schuljahresabschnitts_ID") Lernabschnitt gibt, dann wird ein solcher angelegt (mit der Schuljahresabschnitts_ID des Schülerdatensatzes). Der Jahrgang oder die Klasse, die bei diesem Abschnitt eingetragen werden soll, ist aber nicht bekannt (steht ja nicht mehr beim Schüler), muss also vom Benutzer eingegeben werden.
Das hat nichts mit der Versetzung zu tun, sonden wird z.B. auch geprüft, wenn man einen Schülerdatensatz auswählt.

Aus meiner Sicht kann das Issue geschlossen werden.
