### ISSUE TITLE
Update SVWS-Server

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#713]
### Serverupdate auf 0.6.10
Unmittelbar vor dem Update konnte ich über localhost den Client aufrufen und DBs öffenen.

Ich wollte das SVWS-Update über die bereits bestehende Version drüber installieren und gleichzeitig aus Schild2 eine neue DB migrieren.
Auswahl der Schild2-DB und Root-Passwort-Eingabe hat funktioniert. Anschließend habe ich folgende Fehlermeldung erhalten:

![2023-06-30_093526](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/4567d730-4a67-4cc4-ace1-afa75be4c7bb)

Nach Klicken auf "Nein" war zwar die neue Version installiert, allerdings war der Server über localhost nicht mehr erreichbar.
Ein Blick in die Dienste zeigte, dass ich nun erst wieder den SVWS-Java-Service manuell starten muss... 
**Kann es sein, dass der Dienst bei dem Update beendet wird?**

[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11914382/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/11914386/svws_server_service.wrapper.log)

**Comment by FPfotenhauer** [comment]
Bitte alle DBs neu migrieren. das Datenbankschema ist noch nicht fest.
Das Error-Log fehlt, da steht wahrscheinlich drin, wo es genallt hat.
