### ISSUE TITLE
Datenbankmigration: Zuviele Einträge in der Tabelle Klassenlehrer

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#714]
## Zuviele Einträge in der Tabelle Klassenlehrer
Spin off von #712 

Ich habe folgende Abfrage durchgeführt um mir einen Überblick über die Einträge zu verschaffen:
> select kl.*, k.Klasse, concat( sa.Jahr, '#', sa.Abschnitt ) as Halbjahr, l.Kuerzel, l.Nachname
> from Klassenlehrer kl
> inner join k_lehrer l
>   on l.id = kl.Lehrer_ID 
> inner join klassen k 
>   on k.id = kl.klassen_ID
> inner join schuljahresabschnitte sa 
>   on sa.id = k.Schuljahresabschnitts_ID 
> order by k.klasse, Halbjahr

Im Ergebnis scheinen z.B. die rot markierten Einträge zuviel zu sein:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/2bb3f028-d2b8-41f1-9045-fe7b193ab105)
Ungewöhnlich ist auch, dass das Halbjahr 2022#1 in der Auflistung fehlt.
In der Schild2-Datenbank vor der Migration habe ich bei der Abfrage
> select distinct Klasse, Jahr, Abschnitt 
> from schuelerlernabschnittsdaten
> where klasse = 'BMA91'
> order by 1, 2, 3

dieses Ergebnis:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/2d24b778-878a-4203-be61-5e34ca4c2628)

Es gibt Schüler, die mal in der BMA91 waren und im Jahr 2022#2 noch an der Schule waren.
Aber ein Paar (BMA91,2022#2) habe ich da nicht gesehen.
SchülerIDs sind: 40927 und 40771

Ich mutmaße mal, dass einfach für das aktuelle Halbjahr die Einträge aus der Tabelle Versetzung ergänzt werden.
Sinnvoll ist das bei unserer Datenbank allerdings nicht. Die Klasse ist auch als nicht sichtbar markiert, da sie zur
Zeit nicht existiert.

**Comment by FPfotenhauer** [comment]
@EwaldReinhardt : Es wird prinzipiell imme rnur eine Kopie der Klassenversetzungtabelle auch für vergangene Abschnitte erzeugt.
Wenn man unsichtbare Klassen im aktuellen Abschnitte nicht haben möchte, dann muss man die löschen.
Wir können bei der Migration nicht entscheiden, ob eine unsichtbare KLasse für später noch aufgehoben werden soll oder nicht.

Mit diesem SQL-Befehl sieht man wo Lehrerdaten aus den Lernabschnitten hergestelt wurden:
select schuljahresabschnitte.jahr, schuljahresabschnitte.Abschnitt, klassenlehrer.Lehrer_ID, klassen.* from klassen 
join schuljahresabschnitte on Klassen.Schuljahresabschnitts_ID = schuljahresabschnitte.ID 
left join klassenlehrer on klassenlehrer.Klassen_ID = Klassen.ID 
where klassen.Klasse = 'BMA91'
order by schuljahresabschnitte.jahr, schuljahresabschnitte.Abschnitt;

Da wo die LehrerID=NULL ist, gibt es auch keine Einträge bei Schülern.
Im Aktuellen Abschnitt wird der Default aus der Versetzungstabelle übernommen. (Sollte ja aktuell sein.)

Man wird hie rnicht um "Aufräumarbeiten" herumkommen. Zukünftig kann man so arbeiten, dass man keine unnötigen Klassen im Abschnitt mitführt.

**Comment by EwaldReinhardt** [comment]
Das Aufräumen funktioniert aber nicht:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/afab303e-16a9-427c-8f0c-7e6a222f08fe)
Es bleibt also nur die Klassenlehrer aus der Versetzungstabelle zu löschen.
Es gibt den FK SCHUELER_VERSETZUNGSCHUELER :
ALTER TABLE [Schueler] ADD CONSTRAINT SCHUELER_VERSETZUNGSCHUELER FOREIGN KEY ([Klasse]) REFERENCES [Versetzung]([Klasse]);

@FPfotenhauer Wird es denn im Betrieb auch so sein, dass für alle Klassen für jeden Schuljahresabschnitt Einträge in den Tabellen Klassen und Klassenlehrer vorhanden sein müssen auch wenn die Klasse in dem Abschnitt nicht existent ist?

**Comment by FPfotenhauer** [comment]
Das ist keine Meldung des DBMS. Ich kann die Klassen in dem Abschnitt ohne Schüler löschen.
Das sollte in Schild3 auch ermöglicht werden.

**Comment by EwaldReinhardt** [comment]
Ich hatte das so verstanden, dass vor der Migration aufgeräumt wird.
Und mein Post bezog sich auf die Schild2-DB vor der Migration.
Und da kann auch innerhalb Access nicht gelöscht werden, wegen des FK.

Das innerhalb der Oberfläche von Schild3 zu korrigieren ist zur Zeit sehr viel Klickarbeit,
da eine Übersicht der Zeitabschnitte pro Klasse nicht vorgesehen ist.
