### ISSUE TITLE
Fehlermeldung bei Katalog Ankreuzkompetenzen

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#716]
Ich habe mich in der aktuellen Version in den Katalogen von unten (angefangen bei Peronengruppen) nach oben durchgeklickt. Bei Ankreuzkompetenzen kommt die angehängte Fehlermeldung. Beim Klick auf OK schließt sich Schild.
![Schildfehler_11](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/ac86923b-f5d6-460f-be92-76a0d47f9917)

**Comment by AnneSchueller** [comment]
Hallo Jens,

hast du hier mit der neusten Schild-Version 3.0.70.9 getestet?
Ich  kann das nicht reproduzieren. (GY und HS getestet)

Wenn das Problem noch besteht, wäre es super wenn du das gesamte Fehlerprotokoll einmal anhängen könntest. Wenn du beim Fehlerfenster die Auswahl "Copy to Clipboard" unten rechts aktivierst, wird das Protokoll als "Schild30.el" im Ordner Documents abgespeichert. Nach Umbenennung in schild30.txt kann es hier hochgeladen werden.

**Comment by AnneSchueller** [comment]
Vielen Dank für die Bereitstellung des Fehlerprotokolls. 

@JuergenRichter : Kann man hieraus schließen, wo es hakt?

**Comment by JuergenRichter** [comment]
Werde ich prüfen

**Comment by JeVaske** [comment]
Ich teste gerade Schild (v3.0.73) und  SVWS-Server (win64-installer-0.7.1.exe). Da taucht das Problem nicht mehr auf. Issue kann meiner Meinung nach geschlossen werden.

**Comment by AnneSchueller** [comment]
Danke für die Rückmeldung. Ich schließe das Issue.
