### ISSUE TITLE
Migrationsfehler durch manipulierte MDB

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#717]
Ich hatte kürzlich den Fall, dass in mehreren MDBs (alle aus der gleichen Kommune) die Struktur der Tabelle "K_Ortsteil" möglicherweise manipuliert worden war. Normalerweise ist in dieser Tabelle ein eindeutiger Index auf dem Feld "Bezeichnung". In der mir vorliegenden MDB fehlte dieser, so dass Doppeleingaben möglich und auch tatsächlich vorhanden waren.

Ich habe das mal in einer Test-DB nachgespielt, hier Beispieldatensätze:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/804a2a4b-9402-40ff-ae8f-4baef4cb304d)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/80314114-bdd9-436d-878a-f6688d349090)

Die Migration bricht dann wegen der doppelten Werte ab.

```
Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.1.v202302241130): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: (conn=53) Duplicate entry 'Deutz' for key 'K_Ortsteil_UC1'
Error Code: 1062
Call: ALTER TABLE K_Ortsteil ADD CONSTRAINT K_Ortsteil_UC1 UNIQUE (Bezeichnung)
Query: DataModifyQuery(sql="ALTER TABLE K_Ortsteil ADD CONSTRAINT K_Ortsteil_UC1 UNIQUE (Bezeichnung)")

```

**Comment by FPfotenhauer** [comment]
@ThomasBachran  Spllen wir das bei der Migration "abfangen"?

**Comment by ThomasBachran** [comment]
Da es sich hier um eine Manipulation der MDB handelt, muss dies auch manuell korrigiert werden. Das Verhalten bei der Migration halt ich hier für angemessen.
