### ISSUE TITLE
SVWS-Server startet nicht, wenn Schema extern gelöscht wird

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#718]
Mir ist heute folgendes aufgefallen:
-Ein ursprünglich mit MigrateDB.exe und Aufruf der entsprechenden API-Funktion des SVWS-Servers erstelltes Schema wurde über ein Datenbankverwaltungsprogramm (im konkreten Fall HeidiSQL) gelöscht
-Beim nächsten Neustart des Rechners wurde dann der SVWS-Server nicht gestartet, auch ein manuelles Starten schlug fehl
-Ursache war, dass in der svwsconfig.json noch ein Eintrag auf das zuvor gelöschte Schema enthalten war. Nachdem der Eintrag manuell in der Datei gelöscht wurde, konnte auch der SVWS-Server wieder gestartet werden

Ich könnte mir vorstellen, dass so ein Szenario durchaus in der Praxis vorkommen kann. Es wäre m.E. gut, wenn der SVWS-Server etwas "toleranter" wäre in Bezug auf die Existenz der in der svwsconfig.json gespeicherten Schema-Angaben.

**Comment by FPfotenhauer** [comment]
Schema müssen über die API gelöscht werden.
Wenn jemand das per Hand macht, muss er auch per Hand die svwsconfig.json anpassen.

Wir stellen im Client so oder so eine Funktion zur Datenbankverwaltung zur Verfügung.
M.W. kann das auch in Schild3 schon angeboten werden unter "Verwaltung".
