### ISSUE TITLE
Problem mit Docker-Container

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#719]
Ich habe mal einige Tests mit dem Docker-Container gemacht. Ich habe dazu die .env-Datei wie folgt angepasst:

INIT_SCRIPTS_DIR=/etc/app/svws/init-scripts
TESTDB_PASSWORD=W1eaR55?rbk
MariaDB_ROOT_PASSWORD=[root-kennwort]
MariaDB_DATABASE=docker-test
MariaDB_HOST=192.168.2.222:3306
MariaDB_USER=ribeka
MariaDB_PASSWORD=W1eaR55?rbk
MARIADB_DATA_DIR=/var/lib/mysql/data
MARIADB_LOG_DIR=/var/lib/mysql/log
SVWS_TLS_KEYSTORE_PATH=/etc/app/svws/conf/keystore
SVWS_TLS_KEYSTORE_PASSWORD=W1eaR55?om
SVWS_TLS_KEY_ALIAS=test

Statt [root-password] steht da natürlich mein richtiges Kennwort. Wenn ich den Container in Docker Desktop starte, wird ein Protokoll erstellt, in dem die Zeile 
"docker-svws-1 | Internal Exception: net.ucanaccess.jdbc.UcanaccessSQLException: UCAExc:::5.0.1 Password authentication failed."
auftaucht. Welches Kennwort ist hier gemeint? Das "root-Kennwort"? Das ist aber definitiv das richtige in der .env-Datei.

Eine Verbindung mit dem Benutzer "ribeka" funktioniert aber, im Protokoll erscheint
"docker-svws-1 |     - Datenbank-Verbindung erfolgreich aufgebaut (driver='MARIA_DB', schema='docker-test', location='192.168.2.222:3306', user='ribeka')"

In der Folge wird zwar ein Schema "docker-test" angelegt und auch ein Benutzer "ribeka", das Schema ist aber leer:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/b8acb7c8-59f7-4059-9372-f1bebc3f1f39)

Ich habe das Protokoll mal angefügt.
[Docker_Protokoll.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12181273/Docker_Protokoll.txt)

**Comment by FPfotenhauer** [comment]
Woher ist denn diese .env-Datei?
Ich glaube das TESTDB_PASSWORD sollte das ACCESS-Kennwort sein.

**Comment by JuergenRichter** [comment]
Danke, jetzt funktioniert es. Es muss tatsächlich das Access-Kennwort bei TESTDB_PASSWORD eingetragen werden. Außerdem muss der Start wohl explizit über "In Terminal öffnen" und dann "docker compose up" erfolgen. Der Start über Docker Desktop funktioniert scheinbar nur, wenn der Container vorher nicht gestartet war. Wenn man nachträglich Änderungen an der .env-Datei macht, scheint Docker Desktop das nicht mitzubekommen.

**Comment by JuergenRichter** [comment]
Frage: Beim Start des Containers wird ja immer eine Test-Datenbank (Access) heruntergeladen und in das Schema, das in der .env-Datei steht, migriert (bzw. das Schema neu angelegt). Lässt sich das abstellen, d.h. dass das vorhandene Schema nicht überschrieben wird?

**Comment by FPfotenhauer** [comment]
Ja, die Scripte sind für unsere CI-Pipeline geschrieben, damit automatische Tests ablaufen können.
Die Scripte für einen produktiv-Docker ertsellen wir nach meinem Urlaub.
Man kann imPrinzip die Migration komplett herausnehmen und nur ein "Schema-Init" machen.

**Comment by JuergenRichter** [comment]
Danke, probiere ich aus.
