### ISSUE TITLE
Reiter BKAbschluss

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#72]
Der Reiter BK-Abschluss ist so nicht nutzbar.

![SNAG_2021_01_01_17 14 52](https://user-images.githubusercontent.com/34127980/103442263-ef425e00-4c54-11eb-9e69-64937c8ad775.png)

**Comment by JuergenRichter** [comment]
Ist in Version 3.0.9 geändert (ähnlich wie beim Abiturreiter)

**Comment by JuergenRichter** [comment]
Ich schließe das mal, falls die neue Umsetzung Probleme macht, bitte wieder öffnen
