### ISSUE TITLE
Fenster schaltet beim Umstellen der Reiter nicht vollständig auf den neuen Inhalt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#721]
Version 3.0.70.9

Ich war in der "Reportverwaltung" und schaltete zurück auf "Schüler". 

Die Schülerinhalte rechts vom Container wurden nicht eingeblendet, es blieb auf "Reportverwaltung" stehen.

Ist es möglich, dass die UI beim Umschalten der Reiter über eine hierfür dedizierte Funktion einen sauberen Wechsel erzwingt?

![UmschaltenKaputt](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/b5f5c377-3d5a-48eb-8032-a16218e951e7)

**Comment by JuergenRichter** [comment]
Ist schon behoben.

**Comment by FrodBRA** [comment]
Funktioniert in 3.0.71.9

Geschlossen
