### ISSUE TITLE
Ankreuzkompetenzen: Mehrere Stufen gleichzeitig setzbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#722]
Version 3.0.70.9

Beim setzen von Kompetenzstufen von Ankreuzkompetenzen sind mehrere Stufen gleichzeitig ankreuzbar.

![MehrereKompetenzstufenSetzbar](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/c69e01da-25fb-4a8d-890d-ddc354f7ec24)

**Comment by JuergenRichter** [comment]
Das ist in SchILD2 derzeit auch möglich weil es möglicherweise Schulen gibt, die damit ein "von-bis" markieren wollen. Ich habe bisher von den Kommunen, in denen Ankreuzzeugnisse schon bei einer größeren Anzahl von Grundschulen eingesetzt werden, keine "Beschwerden" deswegen bekommen.

**Comment by FrodBRA** [comment]
Sofern dies ein absichtliches Feature ist, sollte es belassen werden.
