### ISSUE TITLE
Probleme mit DBImage bei Reports

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#723]
Wenn ich das Schullogo in einem Report hinzufüge, bekomme ich eine Fehlermeldung. Dies tritt auch bei sämtlichen Zeugnisreports auf, die das Schullogo einbinden (Unabhängig ob png oder jpg)

[SchILD30_jpg.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12227068/SchILD30_jpg.txt)

**Comment by FrodBRA** [comment]
Dies tritt bei mir ebenso auf.

**Comment by JuergenRichter** [comment]
Das liegt an der Eigenschaft "Grafikart>>Auto detect"
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/556df927-13c0-4ea9-9e9a-f7a8e41c5561)
Die Grafiken werden ja jetzt nicht mehr im "Originalformat" (z.B. jpg) in der Datenbank gespeichert, sondern MIME-kodiert und zur Laufzeit erst in das ursprüngliche Format umgewandelt. Wenn man aber z.B. als Grafikart das urspüngliche Forma einstellt, funktioniert es. 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9fa79ea4-79d6-4e45-9546-9c85bf7a3cbe)

Ich muss mal prüfen, ob man die Grafikart zur Laufzeit aus den MIME-Daten ermitteln kann. Grundsätzlich sollten m.E. für das Logo nur jpg oder png-Grafiken verwendet werden, für die Schülerfotos (wo das Problem im Prinzip auch auftreten dürfte) nur jpg.

**Comment by JuergenRichter** [comment]
Es ist jetzt eine "Ermittlungsroutine  für die Grafikart" drin. Bei mir funktioniert das, bitte mit der nächsten Version mal testen.

**Comment by FrodBRA** [comment]
Bei mir funktioniert die Ausgabe ebenfalls.

@AnneSchueller @Raffenberg 

JEDOCH: Die Formulare für Ankreuzzeugnisse werfen den Fehler noch immer. Ich konnte beim Testen nicht herausbekommen, woran das liegt. Der dynamisch geladene Kopf läuft auch alleine (es ist kein Problem mit dem Kopf), entfernt man den Kopf aus den Zeugnis, bleibt der Fehler erhalten (es ist also kein Problem mit transitivem Laden von Subreports). Ich konnte bei meiner Suche durch den Report auch nicht direkt eine andere Grafik finden.

Hier müsste noch einmal das Team für Zeugnisreports auf die Suche mit einer aktuellen Version von SchILD3 geschickt werden, ob es sich um ein Problem SchILD/dem Reportbaukasten oder dem Zeugnisformular handelt (oder beides zusammen?) und ob ein gleiches Fehlerverhalten in anderen (Zeugnis-)Formularen ebenfalls aufritt.

**Comment by AnneSchueller** [comment]
Deaktiviert man die Option "ParentDataPipeline" funktionieren die GS-Zeugnisse:
![2023-08-21_151804](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/62769503-9d71-4e54-9a81-514d59005089)

Ich schließe das Issue daher mal
