### ISSUE TITLE
Ortsteil_ID bei Betrieben

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#724]
Tabelle K_AllgAdresse
Feld Ortsteil_ID

Steht ab der Version SVWS-Server 0.6.12 zur Verfügung.
Dieses Feld wird bei der Migration gefüllt.

Somit ist das einheitlich bei Schülern, Erziehern und Betrieben.

Das sollte bei der nächsten Version beachtet werden.

**Comment by JuergenRichter** [comment]
Ist die Version 0.6.12 schon verfügbar?

**Comment by FPfotenhauer** [comment]
Wir arbeiten momentan noch an unserem Release-Prozess.
Sobald der nächste Woche funktioniert, werden wir eine Version zur Verfügung stellen.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
