### ISSUE TITLE
Namensfelder in Schild3 unterscheiden sich von denen im SVWS-Client

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#725]
Im SVWS-Client gibt es auf dem Reiter Individualdaten I folgende Namensfelder:

- Nachname
- Zusatz
- Rufname
- Alle Vornamen

Das sollte in Schild3 ebenfalls auf diese Bezeichnung angepasst werden. Zusatz nimmt dann z.B. Doktortitel auf. In Schild3 ist der Zusatz nur über drei Punkte ... zu erreichen. Ich würde hier ein direkt zugängliches Feld befürworten und gänzlich an der Stelle auf die drei Punkte verzichten.

**Comment by JuergenRichter** [comment]
Ein Doktortitel dürfte bei SuS ja eher die Ausnahme sein. In SchILD wird über den Svhalter mit den 3 Punkten ein "Zusatz zum Nachname" eingetragen. Das ist irgend wann mal auf Anforderungen der Schulen entstanden die solche Zusätze wie "Freiherr von" o.ä. separat speichern wollten. Von mir aus kann man das ganz weglassen, dann müssten bei der Migration aber die vorhandene getrennten Feldinhalte zusammengesetzt werden.
Beispiel: 
Name = Posemuckel
Zusatz = Freiher von
ergibt als name "Freiherr von Posemuckel".

**Comment by Raffenberg** [comment]
@JuergenRichter 
@ThomasBachran 

> Ein Doktortitel dürfte bei SuS ja eher die Ausnahme sein.
Das stimmt natürlich. Da hatte ich gar nicht drüber nachgedacht. Dann dürften im SVWS-Client bei den Schülern im Datenfeld Zusätze auch keine Titel gemeint sein. Dann gilt folgendes:

Damit man dieses Problem ein für alle mal in den Griff bekommt, sollten wir bei Schülern konsequent nur Rufname, Alle Vornamen, Nachname und Geburtsname erfassen. Bei den Erziehern Vorname, Nachname und Titel. Mehr nicht. Bei der Migration würde ich auch konsequent alles andere abrasieren.

Wenn wir das jetzt nicht umsetzen, bereitet uns das wieder jahrelang Kopfzerbrechen.

Begründung:
Ich würde mich hier am Personalausweis und an der VO-DV I halten. Dort wird das genauso genannt.
Im deutschen gibt es nur einen Nachnamen und einen Vornamen!!! Keine Zusätzte!!! Zusätze sind ein fiktives Konstrukt, welches lediglich bei der Sortierung in Listen herangezogen wurde (Beispiel: In Telefonbüchern wurde "von der Leyen" unter "Leyen" aufgelistet und "von der" stand dann hinter dem Vornamen). 
Das Problem ist, dass wenn Schulen anfangen, den Nachnamen und Vornamen zu zergliedern, man keine Chance mehr hat mit einer eindeutigen Regel diesen Namen und Vornamen wieder korrekt zusammenzusetzen. Dementsprechend sollten wir die Möglichkeit der Zergliederung erst gar nicht anbieten. Die fiktiven Namenszusätze können nämlich vor oder nach einem Nachnamen stehen.
Nochmal: Im deutschen gibt es NUR einen Vornamen und einen Nachnamen. 

Beispiel:
Vorname: Ursula
Nachname: von der Leyen

**Comment by JuergenRichter** [comment]
Da rennen Sie bei mir offene Türen ein.

**Comment by AnneSchueller** [comment]
Seltsamerweise sind die Infos von "Zusatz" aus Schild2 zwar in Schild3 auch unter "Zusatz" aber nicht im SVWS-Client zu sehen. Was genau passiert mit "Zusatz" bei der Migration?

Ursprünglich war das Feld "Zusatz" ja auch gar nicht für "von der" o.ä. vorgesehen wenn ich das richtig im Kopf habe. 
Meiner Meinung nach auf jeden Fall raus damit. 
Für die Migration wäre hier eine Auflistung von betroffenen Daten im Fehlerprotokoll sinnvoll.

**Comment by FrodBRA** [comment]
Das gibt eventuell Ärger mit Eltern, die auf diesen "Titel" wert legen; gerade auf Zeugnissen. Es ist schön, dass das im Deutschen eigentlich nicht gibt - wenn SchILD aber der einzige Fall im Leben der Leute ist, der hier auf diesem Hügel den Kampf führen will, sind Unruhen zu erwarten.

Ist das eventuell informatisch lösbar, indem etwa im Nachnamen auf "von ", "der von ", "van ", "van de ", "de " usw. gefiltert wird  (wenn der Name damit beginnt; mit passenden Whitespaces, wenn das zusammen geschrieben ist, gehört es zum Namen), um bei Listensortierungen ignoriert zu werden. So viele Zusätze, die 90% oder 95% der Fälle abdecken, dürfte es gar nicht geben?

Denn wenn man es NICHT bei der Eingabe filtert, werden die Sekretariate das ohnehin einfach mit zum Nachnamen schreiben und am Zustand ändert sich nichts.

Will man eine wirklich saubere Lösung, müsste man ja auch ausländische Zusätze sauber raustrennen, wie "O'" aus "O'Malley" oder den "Mc" als "McAllister" oder auch die italienischen de, della, del, dello usw, ebenso die Portigisen mit DeSantos, De Santos oder De'Santos.

Mein Vorschlage: Nur das Nachnamensfeld zulassen, die Schulen können eingeben, was sie wollen (was sie tun werden, egal, was als Politik ausgebeben wird- und ob man bei der Eingabe filtert oder bei der Sortierung ist egal, wobei letztes keine Elternforderungen erzeugt), und die häufigsten "von " und "van " werden bei der Sortierung ignoriert.

**Comment by JuergenRichter** [comment]
"und die häufigsten "von " und "van " werden bei der Sortierung ignoriert."
Wie soll das gehen?

**Comment by FrodBRA** [comment]
Die Implementierung die mir eingefallen, die am saubersten ist, ist vermutlich etwas aufwendig, würde aber das Problem lösen:

Es müsste die mitgelieferte Sortierfunktion durch eine eigene ersetzt werden, in der vor jedem Eintrag, der zu sortieren wäre, per Regexp oder string-Funktion auf eine Liste zu ignorierender Strings zu Beginn des Strings gefiltert wird.

Dann wird dieser Vor-string angeschnitten und die Sortierung findet nur mit dem Rest statt.

Eventuell müsste mit einer Kopie der zu sortierenden Liste gearbeitet werden, in der die Verbotenen Vorsilben aus den Strings geschnitten werden. Diese wird sortiert. Dann wird hinterher über die IDs dieser Liste die originale Liste in der richtigen Reihenfolge ausgegeben.

Diese Lösung wäre unabhängig von Eingaben der Schulen.

Das Problem wäre natürlich, dass man auch "von +  Name" ebenfalls auf "von + ADELSTITEL + Name" prüfen müsste. So viele sind es auch nicht, aber der rechnerische Aufwand steigt. Ich hatte bei meinem Vorschlag angenommen, dass sich das Problem nicht stellt, da die Schüler ja i.d.R. den Titel noch nicht führen. Nun denke ich, dass diese Annahme falsch war und es vermutlich sehr wohl auch "Graf von" und "Freiherr von" geben dürfte. 

---

Eine Möglichkeit, nicht bei jeder Sortierung zu filtern wäre, dass nur bei der **Eingabe** nach obigen Schema geprüft wird, dann gerne auf eine große Liste, und der Name nicht als "Freiherr von Steinburg" gespeichert wird, sondern einfach ohne weiteres Zutun als "Steinburg, Freiherr von" umgespeichert wird.

Diese Funktion könnte auch als Gruppenprozess über eine große Schülermenge angestoßen werden, zum Beispiel nach einem Import von Namen.

In diesem Fall wäre zur Laufzeit später aufgerufener Funktionen nichts weiter zu tun.

Grenzfall: Wenn aus den Namen Emailadressen werden, müsste der ", Freiherr von" wieder entfernt werden. Gibt es weitere Grenzfälle?

**Comment by JuergenRichter** [comment]
Das hört sich jetzt aber m.E. für die paar Sonderfälle, die das betreffen dürfte, ziemlich aufwändig an. Dann kann man es auch so lassen, wie es derzeit ist, das scheint ja zur allseitigen Zufriedenheit zu funktionieren (habe zumindest keine Beschwerden gehört).

**Comment by Raffenberg** [comment]
@FrodBRA 
Ich verstehe den Einwand nicht. Nochmal:

1. Es gibt keine Zusätze, nur Nachnamen (Ausweis, VO-DV I). Ich kenne auch keine einzige Internetseite, auf der ein Eingabefeld "Zusatz zum Nachnamen" existiert.
2. Wieso soll es Ärger mit Eltern geben? Der Zusatz ist Bestandteil des Nachnamens und somit im System.
3. Die Zeugnisse werden dann immer korrekt gedruckt. Es fallen alle vorherigen Fehlerquellen weg.
4. Wir sind kein Telefonbuch. Es ist unerheblich, ob "von der Borch" unter V oder unter B einsortiert wird.
5. Wir sind dabei ein Problem zu heilen, und nicht ein neues Problem zu schaffen. Es soll endlich einfach werden.
6. "Freiherr von Steinburg" ist der Nachname!

**Comment by FrodBRA** [comment]
Dann hatte ich in der Tat das konkrete Ziel mit seinen Einzelteilen falsch verstanden.

Das Feld "Zusatz" kann gerne weg, das führt ohnehin nur zu Inkonsistenzen. Wenn die Sortierung egal ist, spielt alles weitere auch keine Rolle.

**Comment by JuergenRichter** [comment]
> Dann hatte ich in der Tat das konkrete Ziel mit seinen Einzelteilen falsch verstanden.
> 
> Das Feld "Zusatz" kann gerne weg, das führt ohnehin nur zu Inkonsistenzen. Wenn die Sortierung egal ist, spielt alles weitere auch keine Rolle.

Es handelt sich um das Feld "ZusatzNachname", das Feld "Zusatz" speichert weitere (besser: alle) Vornamen. Evtl. sollte es daher auch in "AlleVornamen" geändert werden.

**Comment by FPfotenhauer** [comment]
In der kommenden Version des SVWS-Server (0.6.18 oder höher) sind die Felder Schueler.Zusatznachname und SchuelerErzieherAdr.ZusatzName1  und 2 entfernt.
Bei der Migration werden die Zusätze mit einem Leerzeichen vor den Nachnamen gesetzt.

Wenn da sin Schild3 angepasst ist, bitte das Issue schließen.

**Comment by AnneSchueller** [comment]
Hier ist was durcheinander gekommen
Vesion

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/24902096-c899-4285-ad3b-4d391751303e)

**Comment by JuergenRichter** [comment]
Sorry, bin in der Zeile verrutscht, wird kurzfristig korrigiert.

**Comment by JuergenRichter** [comment]
Ist korrigiert, schließe das Issue erst mal
