### ISSUE TITLE
Akt. Halbjahr -> Leistungsdaten -> "Fächer kopieren" schlägt ohne Angabe von Gründen fehl, wenn die Kurse nicht existieren

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#726]
Version 3.0.70.9

Ich markiere und kopiere in der Q1 und versuche diese, in der Q2 einzufügen.

Es erscheint der Dialog "Es konnten keine Fächer eingefügt werden". 

Es ist zuerst unklar, was hier geschieht. Mir wird dann klar, dass das Kopieren fehlschlägt, da in der Q2 die passenden Kurse nicht existieren. Nehme ich in der Q1 diese Informationen raus, lässt sich das Fach in der Q2 problemfrei einfügen.

Dies Problem trat auf beim Versuch, eine Belegung der Q1 von Hand in die Q2 zu übertragen.

Tilge ich in der Q1 alle Kurse, lässt sich der komplette Fächerblock kopieren.

Hier könnte 
1. eine entsprechende Meldung angezeigt werden und/oder
2.  die Kopierfunktion sollte statt nichts zu tun zumindest die reinen Fächer eintragen (ohne Kurs, Lehrkraft).

Eventuell lässt sich das Problem auch umgehen, indem zwei Kopierfunktionen zur Verfügung gestellt werden:
"Fächer kopieren" kopiert nur die Fächer, ganz gleich von Kursen usw.
"Fächer und Kurse kopieren" versucht alles zu kopieren und schlägt entsprechend dem aktuellen Verhalten beim Kopieren über Jahrgangsgrenzen hinweg fehl.

**Comment by JuergenRichter** [comment]
Normalerweise werden Kurse durchaus automatisch angelegt, hängt aber von einigen Faktoren ab.
Fragen dazu:
"Ich markiere und kopiere in der Q1 und versuche diese, in der Q2 einzufügen."

1. Wurde beim gleichen Schüler kopiert? Also z.B. von einer früheren Q1 in die aktuelle Q2?

2. Oder "von Schüler zu Schüler", also von einem Schüler, der aktuell in der Q1 ist in einen anderen, der ebenfalls aktuell in der Q2 ist?

Wenn 1): Welche Fortschreibungsart ist denn beim Kurs der Q1 eingetragen? Wenn da "Keine" steht, ist das Verhalten m.E, korrekt, ja ja explizit gesagt wird, dass der Kurs und die Belegung nicht hochgestuft werden soll.

**Comment by AnneSchueller** [comment]
Mit meiner Spieldatenbank funktionierte das kopieren von Fächern von Schüler A aus Q1 nach Schüler B aus Q2.

Aber seltsamerweise hatte Schüler B danach drei grüne Mahnungen, die ich mir nicht erklären kann.

**Comment by FrodBRA** [comment]
Es wurde zum gleichen Schüler kopiert. (Q1 -> Q2)

Beide Fälle sollten aber auch möglich sein (A in Q1, B in Q2) bzw. das Fehlschlagen sollte mit einem sprechenden Fehler erklärt werden.

In diesem Fall ist die Fortschreibungsart in der Tat "keine". In diesem Fall würde ich dafür sein, dennoch die reinen Fächer zu kopieren und mit einer Textbox drauf hinweisen, dass die Kurse wegen der Fortschreibungsart nicht übernommen wurden. Immerhin habe ich durch "Markieren -> kopieren -> einfügen" manuell einen Wunsch geäußert, dessen Erfüllung nach der UI möglich sein sollte.

Der typische Anwendungsfall ist, dass man in einem Einzelfall, z.B. ein später dazukommender Schüler, überhaupt die ganzen Fächer schnell irgendwoher bekommen möchte und den Rest dann halt nachträgt.

**Comment by AnneSchueller** [comment]
Ach da hatte ich zu oberflächlich gelesen.... von Q1 aus einem vergangenen Abschnitt nach Q2 werden in meiner Spieldatenbank die Kurse ohne Fortschreibungsart ebenfalls nicht übernommen, was auch so sein sollte. 

Wenn man für diesen Fall nur die Fächer übernimmt ohne Kurseintrag, hat man m.E. nichts gewonnen, da man dann im Nachgang noch den entsprechenden Kurs eintragen muss.
Dann kann man auch direkt den Kurs hier manuell hinzufügen, das ist der gleiche Arbeitsaufwand.

Evtl. könnte man einen Hinweis hinzuzufügen:
"Es wurden x Fächer erfolgreich eingefügt.
Kurse ohne Fortschreibungsart wurden ignoriert."

**Comment by JuergenRichter** [comment]
Die zum Kopieren verwendete Routine wird auch beim Abschnittswechsel verwendet, da muss auf jeden Fall die Fortschreibungsart berücksichtigt werden. Vorschlag:
Beim ""Einzelkopieren" (wie im beschriebenen Beispiel, und nur dort) von einem Abschnitt in den anderen wird wie folgt vorgegangen:
-Die Fortschreibungsart des Kurses wird ignoriert
-Wenn der Kurs aus dem "Quellabschnitt" auch im "Zielabschnitt" existiert (anhand der Bezeichnung, des Faches und des Jahrganges) wird die entsprechende Kurs-ID beim neu angelegt Datensatz eingetragen. 
-Wenn der Kurs nicht existiert, wird ohne Kurszuordnung kopiert (d.h. der Kurs wird nicht automatisch angelegt)

**Comment by AnneSchueller** [comment]
Ich wäre dafür, dass wir das so lassen wie es ist. 
Das könnte sonst ein Durcheinander geben:
- Wenn es ein Fach nicht gibt in der Q2, hat der Schüler das Fach dann trotzdem plötzlich
- Vielleicht hat der Schüler auch den Kurs gewechselt und ist dann in dem Falschen drin

Ich denke die alte Variante ist diesbezüglich nicht so fehleranfällig

**Comment by Raffenberg** [comment]
Ich würde das auch so lassen. Die Probleme existieren ja nur, wenn man Fächer aus der niedrigeren Stufe zur höheren Stufe bei einem einzelnen Schüler transferiert, oder umgekehrt. Dabei muss ja die Fortschreibungsart berücksichtigt werden. Alles andere ergibt für mich keinen Sinn.

Bei den typischen Anwendungsfällen, bei denen ein Schüler hinzukommt, bedient man sich ja bei einem anderen Schüler aus dem gleichen Jahrgang. Dabei werden ja auch alle Kurse unabhängig von der Fortschreibungsart kopiert.
