### ISSUE TITLE
Akt Halbjahr -> Leistungsdaten -> "Abifach" sollte ausgegraut und nicht bearbeitbar sein, da AB1, 2, 3 und 4 über die "Kursart" gesetzt werden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#727]
Version 3.0.70.9

Siehe Titel.

Die Spalte "Abifach" wird automatisch basierend auf der Kursart gesetzt und ein manuelles Bearbeiten ist auch gar nicht möglich. Daher sollten die Hintergründe ausgegraut werden und  Dropdown-Menüs zum Bearbeiten deaktiviert werden.

**Comment by JuergenRichter** [comment]
Ich habe die Spalte jetzt auf "ReadOnly" gesetzt, eine Auswahl gibt es nicht mehr. Das mit dem Ausgrauen ist nicht so eingfach, das die Farben der Komponenten ja über das ausgewählte Thema definiert werden.

**Comment by FrodBRA** [comment]
Readonly reicht nach m.E. vollkommen.
