### ISSUE TITLE
Gesamtprüfung der Daten für die Statistik: Fehler: [Install-order]\Keytabs\asdtabs.mdb nicht gefunden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#728]
Version 3.0.70.9

Derzeit wird bei der Installation von SchILD-NRW3 keine asdtabs.mdb mitgeliefert.

Die Gesamtprüfung der Daten ist somit nicht durchführbar.

Kopiere ich die Daten von SchILD2, läuft die Prüfung korrekt durch.

**Comment by AnneSchueller** [comment]
@FPfotenhauer Hier bin ich gar nicht auf dem aktuellsten Stand, ob die Statistik über diesen Button anfangs laufen soll oder ob das im SVWS-Server dann implementiert ist.

**Comment by AnneSchueller** [comment]
Ich gehe mal davon aus, dass die Gesamtprüfung der Statistik auch über die Schild3 Oberfläche laufen soll?
Dann müsste die oben genannte Datei mit ausgeliefert werden. 
Könnte man das für das nächste Update schonmal umsetzen? Das wäre ja etwas, was definitiv laufen muss vor dem Release und auch ausgiebig getestet werden müsste.

**Comment by JuergenRichter** [comment]
Das Erstellen des Setups (mit der ASDTabs.mdb) ist aber nicht meine "Baustelle". Ich weiß auch nicht, ob die Statistik-DLLs im Setup enthalten sind und ob diese auch registriert werden.

**Comment by JuergenRichter** [comment]
In meiner Testumgebung (wo ich die ASDTabs.mdb manuell reingesetzt habe) funktioniert die Statistik einwandfrei

**Comment by AnneSchueller** [comment]
Ja stimmt. Da war ich zu schnell. Hat bei mir jetzt auch geklappt. 
Dann schließe ich das Issue
