### ISSUE TITLE
Auswahl -> "Schüler mit Statistikfehlern anzeigen" funktioniert nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#729]
Version: 3.0.70.9
SVWS: 0.6.11

Nachdem ich eine Statistikprüfung - mit der asdtabs von SchILD2 - durchlaufen lies, wurden 154 Fehler gefunden. Diese werden im pdf-Fehlerprotokoll korrekt aufgeführt.

Im Anschluss führt "Auswahl -> Schüler mit Statistikfehlern" zur Meldung, es lägen keine entsprechenden Schüler vor.

Die von SchILD2 bekannte Auswahl der Schüler mit einer Anzeige der Fehler zum Abarbeiten funktioniert somit noch nicht.

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren, bei mir klappt die Anzeige:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/5e62ea5d-8f34-4461-8992-0bd0058eff81)

**Comment by JuergenRichter** [comment]
Auffällig ist allerdings, das in der Fehlerliste mehr Fehler erscheinen als Lehrkräfte fehlen.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/486004c4-9482-4a47-99b8-35e17e16d53a)

**Comment by JuergenRichter** [comment]
In der Tabelle VW_PLAUSIFEHLER der StatistikDB.mdb steht das aber tatsächlich so drin:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/df7f9673-3b9e-450e-8b6d-f5037dd5647d)

**Comment by JuergenRichter** [comment]
"edit: Mir fiel noch auf, dass das Feld "ERLEDIGT" (Spalte) bei mir nicht existiert. Ist das normal?"
Nein, das Feld sollte existieren. Normalerweise sollte das autom. angelegt werden, warum das wohl nicht erfolgt ist, muss ich prüfen. Ich habe mal eine Vorlage angehängt, in der das Feld enthalten ist, bitte damit mal prüfen.
[StatistikDB.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12309685/StatistikDB.zip)

**Comment by JuergenRichter** [comment]
Allerdings erklärt das fehlende Feld nicht, warum die Tabelle VW_PLAUSIFEHLER leer ist. Die Tabelle wird ja von der ASDStatistik.dll bei der Prüfung gefüllt, da ist es aber unerheblich, ob das Feld existiert. Das Feld wird nur in SchILD verwendet, um einen Eintrag als "erledigt" markieren zu können und dann alle erledigten Fälle löschen zu können.

"Könnte es sein, dass das daran liegt, dass ich mit mehreren DBs arbeite und die Statistikprüfung nicht mit der Standard-Schema/Standard-Zugang erzeugt wurde (svwsadmin)? So ein Fehler wäre zumindest immer meine erste Vermutung..."
Die erzeugte StatistikDB.mdb wird bei jedem Aufruf von Statistik-Funktionen neu angelegt (aus \Vorlagen kopiert). Der Inhalt stellt immer den Zustand der letzten Statistik-Prüfung dar. Wenn man also eine Prüfung mit einer Schule macht, bei der Fehler gefunden wurden und anschließend das gleiche mit eine "gut geführte Schule" (ohne Statistik-Fehler) macht, stellt der Inhalt der StatistikDB.mdb diese zuletzt ausgeführte Prüfung dar.

**Comment by JuergenRichter** [comment]
Ich habe jetzt mal die Statistik bei mir geprüft. Das funktioniert m.E. korrekt. Ich habe aber Probleme mit der Interpretation des Fehlerprotokolles.
Hie mal die Leistungsdaten eines Kindes:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/83a742d4-92dd-4f98-a72d-0e68b97068e1)

Diese werden wie folgt in die StatistikDB.mdb geschrieben:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cc0ad186-1c45-4875-8f42-3cc1fcddbfef)

Dass da nur vier Datensätze drin sind, ist korrekt, da ja bei den Fächern GS, RS und LE die Wochenstunden auf 0 gesetzt sind (die Lehrerstunden sind damit im Fach D enthalten).
Trotzdem scheinbar vollständiger Eingabe erscheinen vier Fehlermeldungen (die auch so im PDF enthalten sind)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/a4cb8936-afc5-4615-b573-5156602e2971)

Ich konnte mir das erst nicht erklären, bin dann aber auf die Ursache gestoßen: Die Lehrertabelle in der StatistikDB.mdb war leer, und das kam daher, dass in der Datenbank keine aktuellen "Lehrerabschnittsdaten" enthalten waren. Diese werden aber automatisch angelegt, wenn man mal in die Verwaltung der Lehrkräfte wechselt. Nach einem erneuten Export  war die Fehlerzahl von >1000 auf 7 gesunken!

Ich schließe dieses Issue daher erst mal.
