### ISSUE TITLE
Programm beenden

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#73]
In den individuellen Einstellungen gibt es die Option "Bei Programmende immer nachfragen".

Im BackstageMenü Verwaltung gibt es diesen Menüpunkt "Programm beenden", wo dann nochmals "Wirklich?" bestätigt werden muss.

Sehe das nur ich so, dass das etwas viel des Guten ist?

![SNAG_2021_01_01_17 29 53](https://user-images.githubusercontent.com/34127980/103442532-40ebe800-4c57-11eb-8c85-13b8ce928175.png)

**Comment by WLey-49** [comment]
Ich halte die zusätzliche Frage auch für unnötig, denn ein Klick auf "Programm beenden" kann hier eigentlich nicht zufällig gemacht werden.

**Comment by JuergenRichter** [comment]
Das ist in 3.0.11 nun anders gelöst. Bei den Programmeinstellungen gibt es eine Option "Bei Programmende nachfragen". Wenn die aktiviert ist, erfolgt eine Abfrage "Programm beenden", aber nur, wenn man das Programm über den "x"-Schalter oben rechts schließt.
