### ISSUE TITLE
Abiturreiter: Leistungsdaten holen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#730]
Beim Klicken auf "Leistungsdaten holen" im Abiturreiter verschwinden die Noten für Q1.1 und Q2.1.

**Comment by FrodBRA** [comment]
Das habe ich auch beobachtet.

**Comment by JuergenRichter** [comment]
Wo verschwinden die? Auf dem Abiturreiter oder in den jeweiligen Halbjahren?
