### ISSUE TITLE
Datensicherung usw.

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#731]
Ich habe jetzt für die Datensicherung und das Zurückspielen die folgenden Optionen vorgesehen. Bitte mal kommentieren, ob die Benennungen so in Ordnung sind:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/2f369329-8958-4393-995d-bd0b190d12bd)

Derzeit ist das noch ohne Funktion, sobald der SVES-Server das ermöglicht, sollten sich die Funktionen aber recht schnell umsetzen lassen.
Die entsprechenden Berechtigungen gibt es ja schon in der Benutzerverwaltung:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/394d56c4-364c-4b2f-82be-5a11e75f84f8)

Die Frage wäre, ob man eine Unterscheidung machen muss zwischen "Aus Sicherung zurückspielen (in aktuelles Schema)" und "Aus Sicherung zurückspielen (in neues Schema)".

**Comment by AnneSchueller** [comment]
Ich würde (auch im Hinblick auf die Fachberaterarbeit) hier beide Optionen anbieten. 
Zusätzlich wäre noch ein Option sinnvoll, ein neues Schema zu erstellen. Einmal über die Schulnummer einer Schule und zum anderen mittels einer Migration einer Schild2 DB:

![2023-08-11_104501](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/c505ee62-4d5c-4fb3-8e54-53e71f82b991)
 
Bezüglich der Bezeichnung mache ich mir nochmal Gedanken. Ich könnte mir vorstellen, dass die User mit "Datenbank sichern" mehr anfangen können als mit "Schema sichern". Auch wenn hier nur das Schema gemeint ist. 
Das könnte man aber auch ggf. später noch ändern.

**Comment by Raffenberg** [comment]
Nach meinem Verständnis ist

- die "MariaDB" ein Datenbankmanagementsystem
- ein "Datenbankschema" die Definition, wie die Daten innerhalb der relationalen Datenbank organisiert werden, also eigentlich der existierende SQL-Befehl, der die eigentliche leere Datenbank baut
- eine "Datenbank" das Ergebnis eines ausgeführten Schemas, also die strukurierten Tabelle mit oder ohne Daten

In dieser Definition wird nach meinem Empfinden das Wort Schema an vielen Stellen fälschlich und verwirrend benutzt, da ein Schema niemals angelegt wird, da es schon im SVWS-Server vorgehalten wird. Was wir anlegen sind leere Datenbanken.

Insofern würde ich folgende Menüpunkte und Begriffe zur Diskussion stellen:

1. Datenbank exportieren
2. Datenbank importieren
3. Datenbank anlegen
4. Datenbank löschen
5. Datenbank aus Schild2 migieren

Wenn 1. angeklickt wird, soll in einem Auswahlfenster  "Welche Datenbank soll exportiert werden" eine existierende Datenbank ausgewählt werden, sofern mehr als eine existiert.

Wenn 2 gewählt wird, erscheint ein Auswahlfenster "In welche Datenbank soll importiert werden?", in welchem die bestehenden Datenbanken aufgelistet werden und ausgewählt werden können. Zudem steht dort der Menüpunkt "neue Datenbank" zur Auswahl, der man dann einen Namen geben kann. 

Bei Klick auf 3 muss eine Schulnummer aus dem Katalog ausgewählt und ein Datenbankname vergeben werden, um dann eine leere Datenbank anzulegen.

Bei Klick auf 4 erscheint das Auswahlfenster "Welche Datenbank soll gelöscht werden"

Bei klick auf 5 passiert im Wesentlichen das gleiche, wie bei 2, nur dass das Auswahlfenster "In welche Datenbank soll migriert werden" erscheint.

Im SVWS-Anmeldedialog erscheint kein Auswahlfenster, sonder rechts daneben erscheinen denn die zusätzlich auszuwählenden Optionen. Das ist natürlich schöner. Vielleicht ginge das in Schild auch.

Alle Prozesse, die dann im Hintergrund ablaufen (Schema aufrufen und leere Datenbank einrichten, Daten importieren/mifrieren, Con-Datei anlegen etc.), muss der User ja nicht mitbekommen.

Damit sich dies wie ein roter Faden durch die Programme zieht, müsste dies auch so im SVWS-Server und bei der Installationsroutine des SVWS-Servers umgesetzt werden. Hier ist auch von Schema die Rede, obwohl "leere Datenbank" gemeint ist.

Das Thema tangiert natürlich auch das SVWS-Server-Team

**Comment by JuergenRichter** [comment]
Anmerkungen:
"Wenn 1. angeklickt wird, soll in einem Auswahlfenster "Welche Datenbank soll exportiert werden" eine existierende Datenbank ausgewählt werden, sofern mehr als eine existiert."
Ist die Auswahl der Datenbank notwendig? I.d.R. wird man doch die Datenbank sichern wollen, mit der man arbeitet (war in SchILD2 ja auch so), weil man mal schnell den Ist-Zustand sichern möchte, bevor man z.B. einen Gruppenprozes startet.

**Comment by Raffenberg** [comment]
Habe ich auch überlegt. Viele Sekretärinnen sichern die Datenbank routinemäßig morgens wegen der Erinnerung beim Start. Wenn die Schule nur eine Datenbank hat, benötigt man auch keine Abfrage. Wenn die Schule aber zwei Datenbanken hat, würde sie diese ggf. beide sichern wollen, ohne Schild erneut starten zu müssen. Ist aber eher ein theoretischer Gedankengang. Kann man auch gerne vereinfachen. Ich denke auch, dass es in den allermeisten Fällen um eine Sicherung der aktiven Datenbank geht.

**Comment by JuergenRichter** [comment]
Ich würde auch vorschlagen, das bei den Programmeinstellungen ein "Sicherungsverzeichnis" definiert werden kann. Dann werden die Sicherungen immer in dieses Verzeichnis geschrieben, auch der Name der Sicherung (SQLite) sollte standardisiert werden (z.B. "<Name der Datenba>_<Datum>_<Uhrzeit>.sqlite".
Dann kann amn die Sicherung mit einem Mausklick machen.

**Comment by Raffenberg** [comment]
Das hört sich sinnvoll an.

**Comment by FPfotenhauer** [comment]
Das haben wir schon korrigiert. In der nächsten Version wird das wieder funktionieren.

**Comment by JuergenRichter** [comment]
Funktioniert jetzt auch in SchILD3

**Comment by JuergenRichter** [comment]
Kurz zur Philosophie:

Es gibt nun folgende Optionen (noch nicht alle umgesetzt):
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/b4a13ce7-23a8-417f-a1a9-9fb4cc475106)

Alle Optionen sind natürlich an die Einstellungen in der Benutzerverwaltung gekoppelt.

"Datenbank sichern": Hiermit kann mit einem Mausklick eine Sicherung erfolgen. Dazu muss aber bei den Programmeinstellungen ein Sicherungsverzeichnis definiert sein.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9b2114a8-9d24-4180-b67b-2b9d76428231)

Die Sicherungsdatei erhält den Namen der Datenbank plus Angaben zum Datum/Uhrzeit.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/960086bc-d1ee-4348-b081-a4dc73ab81d2)

Bei den Wiederherstellungsoptionen (und Löschen) muss grundsätzlich erst mal das root-Kennwort eingegeben werden. Es wird dann damit eine Verbindung zum SVWS-Server hegestellt, wenn das misslingt, bricht der Vorgang ab.

Wenn die Option "Wiederherstellen" oder "Migration" gewählt wird, erscheint das folgende Fenster:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/7e5f40ea-4817-4ba5-a9f9-4b6f5d25792e)

Dort kann die Importdatei gewählt werden. Wenn die Option "In neue Datenbank" verwendet wird, können die Angaben zur neuen Datenbank eingetragen werden (hier fehlt noch die Angabe des Datenbanknamens, kommt noch).
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/12a6b4df-0702-46b2-8e05-a8e15dc3f0fd)

Beim Migrieren aus einer MDB läuft das ähnlich ab, nur dass statt eine SQLite-Datei eben eine MDB gewählt wird.

**Comment by JuergenRichter** [comment]
Ich habe jetzt das Wiederherstellen aus eine SQlite-Datei auch umgesetzt. Hat im ersten Test funktioniert. Wenn als Zieldatenbank die derzeit im Programm geöffnete Datenbank verwendet wird, kommt noch folgender Hinweis:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/a1bc6b88-af00-453f-9091-66d6ac0b086a)

Derzeit wird noch nicht geprüft, ob es für die Zieldatenbank noch laufende Prozesse beim MariaDB-Server gibt. Das kann man aber ermitteln, kommt noch.

**Comment by JuergenRichter** [comment]
Aktualisierte Programmdatei liegt auf Github. Darin ist auch eine Datei StatistikDB.mdb enthalten, die nun das Feld "ERLEDIGT" in der Tabelle VW_PLAUSIFEHLER enthält.

**Comment by JuergenRichter** [comment]
Es ist jetzt auch die Migration aus einer MDB umgesetzt

**Comment by JuergenRichter** [comment]
Datenbank löschen ist auch umgesetzt

**Comment by JuergenRichter** [comment]
Ich schließe das Issue erst mal
