### ISSUE TITLE
GP vor Aufnahme besuchter Schulen --> Liste der besuchten Schulen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#732]
Es kam der Wunsch einen GP zu installieren, um die Daten aus "Vor der Aufnahme besuchte Schule" nach unten in die Liste der besuchten Schulen einzutragen.
Dies macht auch m.E. Sinn.
Könnten wir das in Schild3 einbauen?

**Comment by JuergenRichter** [comment]
Das sollte kein Problem sein.
