### ISSUE TITLE
Umstellung App Einstelungen auf API

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#733]
Ich hab egerade die SVWS-Server 0.6.17 zur Verfügung gestellt.
Schild3 wird damit aber nicht starten, weil wir diese Tabllen umbenannt haben.

  - [x] Umbenennung `SVWS_DB_Version` --> `Schema_Version`, Java-Sub-Package ab jetzt `schema`
  - [x] Umbenennung `SVWS_DB_AutoInkremente` --> `Schema_AutoInkremente`, Java-Sub-Package ab jetzt `schema`
  - [x] Umbenennung `SVWS_Core_Type_Versionen` --> `Schema_Core_Type_Versionen`, Java-Sub-Package ab jetzt `schema`
  - [x] Umbenennung `SVWS_Client_Konfiguration_Global` --> `Client_Konfiguration_Global`, Java-Sub-Package ab jetzt `client`
  - [x] Umbenennung `SVWS_Client_Konfiguration_Benutzer` --> `Client_Konfiguration_Benutzer`, Java-Sub-Package ab jetzt `client`

Auf mindestens die SVWS_Client_Konfiguration_Global greift Schild3 direkt zu.
Die Speicherung soll aber bitte auf API umgestellt werden, die Services sind imScreenshot zu sehen:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/34127980/90eb9a59-e68e-444e-ac26-56cb3e4f0b68)

**Comment by JuergenRichter** [comment]
Muss bei den Benutzereinträgen eine Angabe zum Benutzer definiert werden?

**Comment by FPfotenhauer** [comment]
Es wird der angemeldete Benutzer genommen.

**Comment by FPfotenhauer** [comment]
Sollen wir noch dazu "delete"-Services ergänzen? Fällt uns gerade auf.

**Comment by JuergenRichter** [comment]
ES gibt bisher nur einen Fall, wo das benötigt wird: Wenn der Benutzer SuS markiert hat, wird beim Beenden gefragt, ob diese gespeichert werden sollen (als komma-separierte Liste der IDs). Wenn das verneint wird, wurde bisher der entsprechende Datensatz in der Datenbank gelöscht. Kann man aber auch erst mal dadurch lösen, dass einfach ein Leerstring gespeichert wird.

**Comment by JuergenRichter** [comment]
Ich habe gerade das Schreiben eines benutzerbezogenen Eintrages in der Swagger-UI ausprobiert. Die Parameter sind im Screenshot zu sehen

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/006f557b-0a11-4904-bf46-c2f6d17cdb6b)

Bei "Execute" bekomme ich aber eine Fehlermeldung 204

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/329230ea-2c9f-4a44-be60-59450bb71be9)

**Comment by JuergenRichter** [comment]
Ich habe geeade mal den GET-Befehl ausgeführt, das ist der Wert nun zu sehen, hat sich damit wohl erledigt

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cf5329c6-cbb9-474d-9615-0c0d9c33fd18)

**Comment by JuergenRichter** [comment]
Dazu eine Frage:
In der SWagger-UI steht beim PUT-Befehl, dass bei der Antwort "200" der Befehl erfolgreich geschrieben wurde. Müsste dass dann stattdessen "204" heißen?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/48ad2d57-f4a8-46a9-b92a-ea980d085c0c)

**Comment by JuergenRichter** [comment]
Die Verwaltung der Einstellungen über die API ist umgesetzt. Dazu aber noch eine Frage: Ich bekomme beim Speichern von Angaben, die ein "/" enthalten (Verzeichnis der Dokumentenverwaltung und für die Zeugnis-PDF-Ausgabe sowie die Angaben zur Dateimaske für die Dokumentenverwaltung) eine Fehlermeldung "400 Bad request". Wie muss für den SVWS-Server eine Verzeichnisangabe formatiert werden?

**Comment by FPfotenhauer** [comment]
Den 204 haben wir jetzt korrigiert. Danke für die Rückmeldung.
