### ISSUE TITLE
Import -> ZP10-Daten schlägt fehl 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#734]
SchILD: 3.0.70.9
SVWS 0.6.1.1

Beim Versuch, ZP10-Daten zu importieren, werden die Daten nicht zu den Schülern geschrieben und es gibt nach einem Klick auf "Öffnen" keine weitere Meldung.

"Irgendetwas" passiert jedoch, denn lese ich die Namen mit Anführungszeichen " umschlossen ein, wird ein Fehler gemeldet, diese Namen (mit den Anführungszeichen vorne und hinten) seien nicht gefunden. 

Ich habe mit im Reiter existierenden Fächern und einem leeren Reiter getestet. Weiterhin sind die gleichen Vornoten eingetragen.

Hier ist ein Beispiel der Importdatei, die Schüler mit den Geburtsdaten existieren ("Englisch" ist noch E5, da das in der Testdatenbank ebenso ist; auch andere Inhalte wurden nicht übernommen). Ist überhaupt die Kopfzeile korrekt? Die habe ich irgendwo im Forum gefunden (https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?f=12&t=419).

Name;Vorname;Geb-Datum;Fach;Abschlussnote;Vornote;Note schr. Prüfung;Note mündl. Prüfung
Appelius;Leon;05.12.2006;D;3;2;4;3
Appelius;Leon;05.12.2006;E5;1;1;1;
Appelius;Leon;05.12.2006;M;3;4;2;
Beckmann;Karolin;26.09.2006;D;1;3;1;1
Beckmann;Karolin;26.09.2006;E5;2;2;3;2
Beckmann;Karolin;26.09.2006;M;3;1;5;2

**Comment by JuergenRichter** [comment]
Ist behoben
