### ISSUE TITLE
Filtern im Container "Jahrgang", "Klasse" und "Kurs": Höhe der Dropdown-Menüs auf "1 Eintrag" beschränkt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#736]
Version 3.0.71.9
SVWS 0.6.17

Im Schülercontainer stehen im Dropdown-Menü nur die jeweils ersten Einträge bei "Klasse" (10a), "Jahrgang" (5) und "Kurs" (die erste AG) zur Auswahl zur Verfügung.

Die gleiche DB wurde auch in 3.0.70.9 verwendet.

**Comment by FrodBRA** [comment]
Nachtrag: Die Höhe der Dropdown-Menüs ist bei Start auf "1 Eintrag" gesetzt.

Dieser Fehler tritt auch bei weiteren Dropdown-Menüs auf, Stichprobenartig bei "sehr vielen", daher nehme ich gerade an bei "allen".

**Comment by AnneSchueller** [comment]
Die manuelle Größeneinstellung der Drop-Down Menus werden nicht gespeichert und sind bei einem Neustart verschwunden. In Schild2 konnte man die Anzahl der Einträge im Drop-Down Menu unter Einstellungen anpassen. 

Optimal fände  ich es, wenn die Standardeinstellung anfangs maximal 10 oder 20 Einträge zulässt und die manuellen Anpassungen dann gespeichert würden, sodass diese bei einem Neustart erhalten bleiben.
Alternativ könnte man auch wieder eine Einstellungsmöglichkeit der Anzahl der Einträge über die Einstellungen anbieten. Ich habe das allerdings noch nie groß verändert. Hatte diese Option etwas mit kleineren Bildschirmen o.ä. zu tun? 
Von mir aus könnte man das auch weg lassen und die Startwerte geeignet wählen

**Comment by FrodBRA** [comment]
Ich stimme Anne zu, dass SchILD3 das Verhalten von SchILD2 wieder umsetzen sollte, wo ein Minimalwert für die Initialisierung von Dropdown-Längen festgelegt werden konnte.

**Comment by AnneSchueller** [comment]
Ist in der aktuellen Version behoben
