### ISSUE TITLE
Mehrere Logineos? Falls korrekt -> Tippfehler "Loginio"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#737]
3.0.71.9

Der Eintrag zum Export scheint mehrere Einträge für "Logineo" zu enthalten. Ist dies korrekt?

Die Oberflächen für beide Exporte sehen jedenfalls unterschiedlich aus.

Falls das hier korrekt ist, sollte eine Erklärung vorliegen, wann "Logineo" und wann "Loginio LMS" zu verwenden ist.

In allen Fällen tritt in "Loginio LMS" ein Tippfehler auf.

![Loginio](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/43baedd9-5f03-491c-8bd0-20fa3c340496)

**Comment by AnneSchueller** [comment]
Für die Logineo Plattform gibt es tatsächlich zwei verschiedene Exporte. Genaueres weiß ich nicht, aber in Schild2 sind die genauso und da es keine Beschwerden gab, sollten wir auch beide gleichermaßen wieder anbieten.

Aber der Rechtschreibfehler sollte weg.

**Comment by JuergenRichter** [comment]
Tippfehler ist behoben
