### ISSUE TITLE
"Datenbank sichern" schlägt fehl

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#738]
3.0.71.9
SVWS 0.6.17

Da die anderen DB-Funktionen ein Fenster "Kommt noch" anzeigen, habe ich dieses einfach mal getestet. Falls "DB Sichern" noch nicht supportet wird, bitte das Issue einfach schließen.

Nachdem ein Sicherungsverzeichnis gesetzt wurde, scheitert das Sichern der Datenbank an einer Zeitüberschreitung:

----

[DB_Sichern_Timeout.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12387638/DB_Sichern_Timeout.txt)

**Comment by AnneSchueller** [comment]
Hallo Felix,
ich habe auch erst getestet und dann erst gesehen, dass Herr Richter diesen Fehler bereits gemeldet hat. Das liegt am SVWS-Server. 

In der nächsten Version vom SVWS-Server ist das behoben.
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/731#issuecomment-1674968815

**Comment by JuergenRichter** [comment]
Mit der Version 0.6.17 des SVWS-Servers funktioniert das bei mir aber

**Comment by JuergenRichter** [comment]
Der Timeout ist jetzt auf 2 Std. gesetzt, das sollte reichen.

**Comment by AnneSchueller** [comment]
Wenn ich das in der Swagger-Umgebung (angemeldet als root) teste, erhalte ich ein Anmeldefenster. Also hier: 

![2023-08-22_091319](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/503cdd8d-ea58-4346-a875-c9e3aa02533a)

Das ist ja sicherlich auch die Methode, die von Schild aufgerufen wird.

Egal was ich hier eingebe, es erfolgt keine Sicherung (Version 0.6.17). 
Woran kann das liegen?

Bei der Datensicherung mit Schild3 erhalte ich die gleiche Fehlermeldung wie Herr Frodermann.
Das liegt dann evtl. auch an dem Fehlschlagen bei der Anmeldung?

**Comment by JuergenRichter** [comment]
Haben Sie es mal mit einer ganz kleinen Datenbank (Grundschule) getestet. Ich habe in der Zwischenzeit das Timeout hochgesetzt.

**Comment by JuergenRichter** [comment]
In der SwaggerUI muss der SchILD-Benutzer angegeben werden! Dann klappt es bei mir auch.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/ddd91171-c4ac-46af-9104-5592594ded2d)

**Comment by JuergenRichter** [comment]
Ich hab testweise nach der Anpassung des Timeouts mal eine große Gesamtschul-DB gesichert und auch wieder zurückgespielt. Klappt beides einwandfrei. Ich werde morgen eine neue Version zur Verfügung stellen.
