### ISSUE TITLE
Verwaltung - Einstellungen -> die Menüs zu den Menüpunkten Globale Einstellungen und Allgemeines stimmen überein

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#739]
Im Reiter Verwaltung wird im Menü Einstellungen bei der Auswahl der Menüpunkte _Globale Einstellungen_ und _Allgemeines_  dasselbe Menü angezeigt.

**Comment by AnneSchueller** [comment]
@JuergenRichter Ich habe in Kopf, dass sich das an dieser Stelle nicht so einfach ändern lässt, dass die Oberkategorie automatisch den Inhalt der ersten Unterkategorie abbildet?

**Comment by AnneSchueller** [comment]
Ich speichere das Issue für später
