### ISSUE TITLE
Anlegen eines neuen Abschnittes funktioniert nicht

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#74]
Ich habe von Walter Schrewe für Kurs42-V4 die Möglichkeit der Anbindung an eine Maria-DB erhalten. Ein Export der Blockung (für das kommende Schuljahr) nach Schild (Version 3.0.8.1) funktioniert. Die Kurse sind vorhanden, kommen aber nicht bei den Schülern an. Dies liegt offensichtlich daran, dass kein neuer Lernabschnitt angelegt wurde.
Dies ist auch per Hand nicht möglich. man kann beim ersten Mal alle Einträge vornehmen (siehe Bild in der Anlage), aber es wird nicht übernommen. Beim nächsten Mal bleibt der Klick auf "+" wirkungslos.
![neuer Lernabschnitt](https://user-images.githubusercontent.com/62895389/104368067-e470ae80-551b-11eb-9ccc-863960507fc5.JPG)

**Comment by JuergenRichter** [comment]
In Version 3.0.10 behoben
