### ISSUE TITLE
Schüler -> Spalten im Container werden nicht angezeigt.

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#740]
Im Container wird die Spalte 'Klasse' nicht angezeigt, obwohl sie im Menü Verwaltung - Einstellungen - Individuelle Einstellungen ausgewählt wurde. 
Schild Version 3.0.71.9
SVWS-Server: 0.6.17
![Container](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/7f6dbb1f-cc33-4453-8ff0-5cd89a74a31f)

**Comment by FrodBRA** [comment]
Bei mir wird die Klasse per Default angezeigt.

Hast du den Container in der Breite verschoben und dennoch ist nichts zu sehen?

**Comment by pemichalski** [comment]
@FrodBRA Auch bei einer Änderung der Breite wird keine Klassenspalte angezeigt.

**Comment by AnneSchueller** [comment]
Aktuell funktioniert das ja nicht mit dem Anpassen der Spaltenansicht
(siehe https://github.com/SVWS-NRW/Schild3-BetaTest/issues/735)

Das hängt bestimmt irgendwie zusammen.
Wie war die Ansicht bei der Migration?

**Comment by pemichalski** [comment]
@AnneSchueller Nach einer kompletten Neuinstallation und neuen Migration waren zwar Name und Klasse eingestellt, aber es wurden nur die Namen angezeigt.

**Comment by AnneSchueller** [comment]
Kannst du mal die logs hochladen oder per Mail schicken? Ist das einer unserer Spieldatenbanken?
Wenn du beide logs zur Hand hast (also Win 11 und Win 10) wäre das super.

Unter ProgramData/SVWS-Server/logs und dann die Datei svws_server_service.out.log

**Comment by JuergenRichter** [comment]
Bitte mit der Version 3.0.72 nochmal probieren

**Comment by AnneSchueller** [comment]
@FrodBRA , @pemichalski 
Könnte das evtl. einer von euch nochmal mit der aktuellen Version testen? Bei mir funktioniert das einwandfrei.

**Comment by Raffenberg** [comment]
@FrodBRA 
Die neuen Versionen sind nur noch hier Git, jeweils unter Releases.

**Comment by FrodBRA** [comment]
3.0.73.10: Das funktioniert.

1. "Klasse" wird nach der Neuinstallation angezeigt
2. "Klasse" in den Einstellungen abgewählt, "Status" angewählt
3. "Klasse" wird nicht mehr angezeigt, dafür Status.
4. Einstellungen: "Klasse" wieder angewählt, "Status"
5. Die Anzeige ist wie erwartet.

Das scheint somit zu funktionieren.

**Comment by AnneSchueller** [comment]
Danke fürs erneute Testen. Dann schließe ich das Issue
