### ISSUE TITLE
Skalierungsproblem in Schule -> Allgemeine Angaben (minimal)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#741]
Version 3.0.71.9

Der Text zur Änderung der Adresse passt nicht ins Feld (vermutlich ein Skalierungsproblem mit hoher Auflösung).

![EinstellungenSkalierungweiter](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/541afe5b-5fc6-41ec-9cb7-6262888d6e3b)

**Comment by AnneSchueller** [comment]
Das sieht bei meiner Test-DB genauso aus.
