### ISSUE TITLE
Filter I - Sprachenfolge kein Fach wählbar

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#742]
## Schildversion 3.0.69.9
Im FilterI / weitere Daten lässt sich bei der Sprachenfolge kein Fachwählen.

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/df892290-e8c2-49ea-a732-8c2da6ddb61e)

Das rot markierte Dropdown hat keine Einträge!

**Comment by AnneSchueller** [comment]
Liegt das evtl nur am fehlenden Dropdownmenu? Kannst du das nach untern aufziehen oder mit der Pfeiltaste navigieren?

In meiner Test-DB sind hier sämtliche Sprachen aufgelistet

**Comment by JuergenRichter** [comment]
Welche Schulform?

**Comment by AnneSchueller** [comment]
In meiner BK-DB sind die Fächer in der Sprachenfolge unter Filter I vorhanden

**Comment by AnneSchueller** [comment]
Hallo Ewald,
ich kann es nicht reproduzieren, auch nicht mit einer BK-DB. Tritt das bei dir immer noch auf? Könntest du mir die Schild2 DB, bei der das auftritt mal zur Verfügung stellen?

**Comment by EwaldReinhardt** [comment]
Ich glaube, das hing mit der Version zusammen und nicht mit der DB.
Bei mir ist es jetzt auf jeden Fall i.O.
