### ISSUE TITLE
Menu Auswahl - Ribbon

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#743]
- [ ]  Im Ribbon sind zwei Einträge ohne Icon:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/5ba5f813-d6ca-4bc8-a8ea-366afd5bba21)

- [ ]  Vorhandene Filterdefinition laden:
Von der Bezeichnung her würde ich erwarten, dass der Filter I mit dem gewälten Filter wieder hergestellt ist,
so dass man ihn ggfs. ändern könnte. (Was schön wäre)
Ansonsten würde ich den Eintrag in "Vorhandene Filterdefinition _anwenden_" umbenennen.
- [ ] Vorhandene Filterdefinition bearbeiten 
Ist eher "Vorhandene Filterdefinitionen _verwalten_", da hier gelöscht und maximal die Benennung geändert werden kann. Die Filtereinstellungen selbst können auch hier nicht geändert werden.

**Comment by AnneSchueller** [comment]
Zu 1: 
Bei mir sind alle Icons da. Welche individuellen Einstellungen für die Benutzeroberfläche hast du gewählt? 

Zu 2: 
Das würde ich aufgrund vom Kosten-Nutzen Faktor erstmal so lassen und ggf. später nochmal anpassen.
Aktuell ist das ja erstmal aus Schild 2 genauso übernommen worden.

Zu 3:
Über den Namen wurde glaube ich schonmal diskutiert. Ich finde das Wort "bearbeiten" auch nicht treffend und würde "verwalten" bevorzugen.

**Comment by JuergenRichter** [comment]
Die Icons werden aus der Datei \Keytabs\Schild_Icons.db3 geholt. Darin kann (ohne dass Änderungen im Programm notwendig sind) die Beschriftung und das Icon von "Actions" geändert werden. Dazu wird aber das Programm "Schild3_ActionHandler.exe" benötigt.
Im vorliegenden Fall vermute ich, dass die besagte Datei nicht aktuell ist.

**Comment by EwaldReinhardt** [comment]
Die Datei hat das Datum 20.06.2023 und ist 1.475.584 Bytes groß.
[Schild_Icons.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12416083/Schild_Icons.zip)

**Comment by AnneSchueller** [comment]
@JuergenRichter 
Könnten Sie das Programm Schild3_ActionHandler einmal auf dem Server hochladen? Ich hatte es mir dort mal runtergeladen, finde es aber nicht mehr.

**Comment by JuergenRichter** [comment]
Liegt auf dem Server, da ist auch eine aktuelle Datei "Schild_icons.db3" (in \Keytabs legen)

**Comment by AnneSchueller** [comment]
Ich habe mir das mal angesehen. Es gibt immer 2 Icon IDs. Bei den fehlenden ist bei der oberen ID der Eintrag leer:

![2023-09-05_143014](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/3300fdcc-8106-4d55-a943-4e48ec59381a)

**Comment by AnneSchueller** [comment]
Die Icons für bestimmte Button fehlen nach wie vor. Betroffen sind:

**Auswahl/Vorhandene Filterdefinition bearbeiten** 
Hier gibt es in der DB zwei Einträge. Der erste davon ist leer.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/ff97a18d-87ca-4f4a-b8aa-956d115d472e)


**Auswahl/Schüler ohne Fächer**
Analog wie oben:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/ace0b0c6-4735-4699-aab8-c775ef910031)


**Schüler/Filter auf markierte Schüler aufheben:**
Hier ist gar kein Bild vorhanden

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/bf239274-ba1e-42d9-9a37-f3f8020bc184)

**Comment by JuergenRichter** [comment]
Da muss jemand entscheiden, welches Icon (aus den von SchILD3 verwendeten Icon-Sammlungen) da thematisch passt. Ich habe mal die in SchILD3 verwendeten Icons auf unseren Server gelegt (SchILD3_IconSets.zip)

**Comment by AnneSchueller** [comment]
Hier mal ein Vorschlag:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/a7e15d2d-f0f0-4a81-a0e0-f482f7b38de2)



![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/09d336c7-6fc2-45fc-825f-58514a31dda4)



[Icons.docx](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13686084/Icons.docx)

**Comment by JuergenRichter** [comment]
Ist umgesetzt. Dazu aber folgender Hinweis:
Das Icon "document_check_edit.png" gibt es (aus welchen Gründen auch immer) nicht in der "O-Collection" (schwarz-weiß). Ich habe daher das Icon "document_information.png" gewählt.
Und eine Frage: Was ist konkret mit "Icon Schüler Standardauswahl = Icon von Auswahl (Schueler Standardauswahl)" gemeint?

**Comment by AnneSchueller** [comment]
Das hatte ich zu salopp formuliert...

Unter Schüler/Standardauswahl ist ein anderes Icon als unter Auswahl/Standardauswahl.

Gemeint ist aber bei beiden Button das gleiche (alle Schüler wieder laden). Tendenziell würde ich dann auch das gleiche Icon erwarten. Wobei man hier auch begründen kann, dass das Filterzeichen bei Auswahl/Standardauswahl deshalb zusätzlich beim Icon dabei ist, weil man sich im Reiter Auswahl befindet. 
Also kann eigentlich auch so bleiben. 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/1c8948ea-ba7e-4803-9b5b-45e266705efb)

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/29a04dd5-5a2f-4b8f-9a5d-56a3ef18d287)
