### ISSUE TITLE
Filter I - Feld Filter benennen ??

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#744]
#### Schildversion 3.0.69.9

Wozu dient das Feld Filter benennen?
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/cd650652-1d72-457f-b25c-2e4266b9a664)
Es wird weder verwendet um den Dateinamen bei Speichern in Datei oder den Filternamen bei Speichern vorzubelegen.
Kann das weg?

**Comment by AnneSchueller** [comment]
@JuergenRichter 
Das Feld scheint mir auch überflüssig. Zumindest hatte das Feld keine Auswirkungen bei meinen Tests. (auch nicht in Schild2)

**Comment by JuergenRichter** [comment]
Das dient nur zur Anzeige. Man kann damit der Filterbedingung einen "Namen" geben, der wird dann im Hauptfenster unten angezeigt. 
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/18e03a2c-5014-4c38-b255-65d3872fe792)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/2c96cb31-1893-47b0-8d03-8f7e4bb101be)

**Comment by AnneSchueller** [comment]
Danke für die Info.  Können wir auch drin lassen.
