### ISSUE TITLE
Migration -> Fehler bei der Migration der DB bei der Installation 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#745]
Wird eine Datenbank im Rahmen der Installation des SVWS Servers migriert, so werden die Connection-Files nichts angelegt.
Eine Migration der DB mit MigrateDB funktioniert ohne Probleme.
Schild Version 3.0.71.9
SVWS-Server: 0.6.17
Betriebssysteme: WIN 10 Pro, WIN 11 Pro (V22H2) - mit Adminrechten auf beiden Rechnern.   
<img width="569" alt="Connectionfiles" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/31272a59-b70f-4af6-ac15-3a20c0f6f15d">

**Comment by FrodBRA** [comment]
Die Connection Files werden mit der Installation von SchILD3 angelegt bzw. nach deren Abschluss wird die SchILD_DBConfig.exe mit passenden Parametern gestartet. 

Migrierst du ohne SchILD3 neu zu installieren, also über den SVWS-Server-Installer oder die MigreateDB.exe (als Admin zu starten), musst du die SchILD_DBConfig.exe aufrufen, um die Connection Files zu schreiben.

Wird eine zweite Datenbank angelegt, ist über MigrateDB.exe zu gehen, eine erneute Server-Installation mit neuer Migration funktionierte manchmal, dann gab es aber viele Probleme.

Diese Hinweise könnten eventuell in die Installer als Infobox aufgenommen werden.
