### ISSUE TITLE
Fächer global ändern

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#746]
Beim Prozess Fach global ändern kommt folgende Fehlermeldung:

![SNAG_2023_08_23_11 06 18](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/34127980/d33586da-3229-4ff6-9a4c-cc1e0115010e)

**Comment by JuergenRichter** [comment]
Behoben
