### ISSUE TITLE
Anwendung läuft bereits Schild2 vs Schild3

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#747]
Seit dem letzten Update von Schild3 3.0.71.9 kommt für Schild2 und Schild3 immer der Hinweis, dass die Anwendung bereits läuft, wenn man entweder

- Schild2 startet und schild3 geöffnet hat oder
- Schild3 startet und schild2 geöffnet hat.

Ist das beabsichtigt?

**Comment by JuergenRichter** [comment]
Das ist wohl schon immer so, da beide Anwendungen für die Eigenschaft "Application.Title" den Eintrag "SchILD-NRW" haben. Das wird dann vom System als die gleiche Anwendung angesehen. Werde ich ändern.

**Comment by JuergenRichter** [comment]
Unter welcher Bezeichnung soll denn SchILD3 z.B. im Taskmanager erscheinen?

**Comment by AnneSchueller** [comment]
Ich finde "Schulverwaltungsprogramm für NRW" (wie es aktuell ist) schon treffend. 
Ich nehme das mal mit in unsere Besprechungsrunde.

**Comment by JuergenRichter** [comment]
Die Anwendung hat jetzt die Eigenschaft "Application.Title='SchILD-NRW 3". Dadurch sind das nun auch aus Sicht des Systems zwei unterschiedliche Anwendungen
