### ISSUE TITLE
Umbenennung Filter I --> Filter

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#748]
Vielleicht für manchen Anwender anfangs verwirrend, aber wenn wir nur noch einen Filter haben könnte man diesen auch Filter statt Filter I nennen.

**Comment by JuergenRichter** [comment]
Nur "Filter" finde ich jetzt aber auch etwas nichtssagend. "Schülerfilter"?

**Comment by AnneSchueller** [comment]
Wenn es optisch passt wäre "Schülerfilter" gut. Ansonsten nur Filter.

**Comment by JuergenRichter** [comment]
Ist geschehen. Der Eintrag steht in der Datei Schild_Icons.db3 (in \Keytabs) und kann über das Programm Schild3_ActionHandler.exe bearbeitet werden.

**Comment by AnneSchueller** [comment]
Das Programm Schild3_ActionHandler.exe kann ich nicht öffnen. Gibt es da einen Trick? Ich erhalte immer die Fehlermeldung "Unable to open Database"

**Comment by AnneSchueller** [comment]
Danke hat geklappt
