### ISSUE TITLE
SQLite-Datenbank und SVWS-Server

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#749]
Ich habe heute mal versucht, in SchILD3 eine Verbindung zu einer durch einer Sicherung erzeugten SQLite-Datenbank herzustellen. Das war ja z.B. für Schulungen mal so gedacht. Ich habe dazu eine .con-Datei erstellt, die folgende Zeilen enthält.

[SchILDconnection]
ProviderName=SQLITE
ProviderType=SQLITE
Database=C:\SVWS-Arbeitsverzeichnis\Sicherungen\svwsdb-ge_24082023_1445.sqlite
Direct=1
SVWSServerURL=localhost:443

In SchILD3 klappt die Verbindung damit auch grundsätzlich, das Problem ist der SVWS-Server. Dieser benötigt ja für alle Aufrufe die Angabe eines Datenbankservers (z.B. localhost) und eines Schemas. Diese Angaben gibt es bei einer SQLite-Datenbank aber gar nicht, weshalb bei allen API-Aufrufen zum SVWS-Server jede Menge Fehler gemeldet werden.

**Comment by FPfotenhauer** [comment]
Wir sollten SQL aus der DBConfig herausnehmen.
Ich probiere das mit dem SVWS-Server mal aus, würde aber keine großen Ressourcen darauf verschwenden.

**Comment by JuergenRichter** [comment]
"Wir sollten SQL aus der DBConfig herausnehmen."
Ist schon geschehen.
