### ISSUE TITLE
Migration -> Fehler bei der Migration der DB bei der Installation

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#750]
Issue #745 neu:
Wird eine Datenbank im Rahmen der Installation des SVWS Servers migriert, so werden die Connection-Files nichts angelegt.
Das Problem kann per _SchILD_DBConfig.exe_ gelöst werden. Bei der Migration der DB mit MigrateDB werden die Connection Files ebenfalls ohne Probleme angelegt.
Es wurde im Rahmen der Installation zuerst der SVWS Server und danach Schild 3 installiert. Vorher wurden delete_services ausgeführt und die verblebenden Komponenten gelöscht.

Schild Version 3.0.71.9
SVWS-Server: 0.6.17
Betriebssysteme: WIN 10 Home, WIN 10 Pro, WIN 11 Pro (V22H2) - mit Adminrechten auf allen Rechnern.
Das Problem trat ebenfalls bei @FrodBRA auf. 

<img width="569" alt="262299728-31272a59-b70f-4af6-ac15-3a20c0f6f15d" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/f72782b6-6ed8-4062-98c1-d5d46856247d">

**Comment by AnneSchueller** [comment]
Schild 3.0.73
SVWS-Server: 0.7.0

Mit dieser Version wird das SVWS-Arbeitsverzeichnis unter C durch die Installation von Schild3 gespeichert, allerdings muss der Default Link noch angepasst werden:

![2023-09-01_102132](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/2b93e344-3afe-42f2-9bd5-3c60549129ff)

**Comment by FPfotenhauer** [comment]
Das Schild_ConfigDB.exe müsste das doch aus der Admin.ini auslesen.
Wenn da nichts drin ist, dann ist das der Default.

**Comment by JuergenRichter** [comment]
Bitte mal folgendes prüfen:
-Befindet sich in dem Verzeichnis, in dem das Programm "SchILD_DBConfi.exe" (normalerweise das Programmverzeichnis von SchILD3) eine Datei "Admin.ini"
-Wenn ja: Ist in dieser Datei ein Eintrag 
[Administration]
GroupDir=<SVWS-Arbeitsverzeichnis>

<SVWS-Arbeitsverzeichnis> steht dabei für das bei der Installtion gewählte Arbeitsverzeichnis

Wenn Hier keine Verzeichnis steht (oder die Datei Admin.ini fehlt), wird das Programmverzeichnis verwendet. as würde dann auch zum gezeigten Screenshot passen.

**Comment by AnneSchueller** [comment]
In der Admin.ini steht das richtig drin. Die Schild_DBConfig funktioniert auch richtig.

Das Problem tritt nur bei der Erstinstallation von Schild3 auf

**Comment by FrodBRA** [comment]
Das Problem hatte ich in der Tat auf meinem Hauptrechner nicht, nur bei der absoluten Erstinstallation auf meinem Laptop erschien das gleiche Fehlerbild.

**Comment by JuergenRichter** [comment]
Kann es sein, dass das Setup-Programm für SchILD3 die Datei Admin.ini (bzw. den Eintrag "GroupDir=") erst schreibt, nachdem Schild_DBConfig aufgerufen wurde?

**Comment by FPfotenhauer** [comment]
Also die DBConfig wird im AfterInstall event aufgerufen.
Da sollte die da sein.

**Comment by FrodBRA** [comment]
Ich habe gerade SchILD3 3.0.73 installiert: DBConfig wird auf meinem Rechner nicht gestartet. Ich hatte den Ordner Connection-Files geleert, aber nicht gelöscht.

Keine Neuinstallation: Ich habe die Installation im Anschluss einfach noch mal als "Als Admin instllieren" angestoßen, der Installer lief ohne weitere Nachfragen über meine Standardordner drüber, auch hier wurde das Event nicht aufgerufen.

Kann es sein, dass das Event nur aufgerufen wird, wenn noch kein vorheriger Ordner/Registry-Eintrag/eine bestimmte Datei existierte bzw. der Installer merkt, dass irgendeine Registry-Eintrag/Datei/Ordner noch existiert und nimmt damit an, dass es sich um ein Update handelt und startet sinnvollerweise DBconfig nicht?

**Comment by FPfotenhauer** [comment]
Sollte jetzt alles funktionieren.
