### ISSUE TITLE
Reportverwaltung: Markierung von z.B. Jg im Filter und drücken "Entf" versucht den zuletzt angewählten Report zu löschen

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#751]
3.0.71.9

1. Filtern auf eine Schülergruppe
2. Reportverwaltung, eine Reportdatei durch Anwahl aktiv haben
3. Markieren der Filterbedingung und drücken von Entf, um diese zu entfernen

Der Fokus liegt nun nicht auf dem gerade markierten Jahrgang, sondern ist auf der Datei verblieben.

Damit entfernt das "Entf" nicht die Zeichen im Filter, sondern stößt die Löschroutine der Reportdatei an.

**Comment by JuergenRichter** [comment]
Behoben
