### ISSUE TITLE
Farbschema der Icons kann nicht umgestellt werden

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#752]
3.0.71.9
SVWS 0.6.17

Das Farbschema der Icons kann nicht umgestellt werden. Nach einem Neustart bleibt das vorherige Farbschema erhalten.

**Comment by JuergenRichter** [comment]
Korrigiert

**Comment by AnneSchueller** [comment]
Funktioniert.
Beim Ändern von Symbolfarbe und Stil muss man Schild 2 mal neu starten. Etwas unschön, aber macht man wahrscheinlich auch nur anfangs einmal.

**Comment by JuergenRichter** [comment]
Das mit dem zweimal starten ist schon behoben.
