### ISSUE TITLE
Farbschema der Icons Ändern: "Neustarten -> Ok" führt nicht zu einem Neustart von SchILD, sondern nur zum Beenden

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#753]
SchILD muss anschließend manuell tatsächlich gestartet werden.

Version 3.0.71.9

**Comment by AnneSchueller** [comment]
@JuergenRichter : Das ist in der nächsten Version bereits geändert oder?
Dann gerne schließen
