### ISSUE TITLE
Vorschlag - Reduktion auf ein Theme

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#754]
Die Anzahl der Themes und Icon Sets könnte im Zuge einer Komplexitätsreduktion auf zwei Themes (Luna und ein Dark Theme) und jeweils ein Iconset für beide Themes reduziert werden.

Eigentlich reicht sogar ein Theme (Luna) mit einem Iconset.

Was haltet ihr davon?

**Comment by AnneSchueller** [comment]
Das würde ich hier erstmal so lassen. Das mit dem Dark Theme ist glaube ich auch nicht ganz trivial. Herr Blomeyer hat das im PM2 versucht zu realisieren. Da gab es viele Darstellungsfehler. Aber auf jeden Fall ein Nice to Have für später mal.
