### ISSUE TITLE
Verwaltung - Schule - Allgemeine Angaben -> Dropdownmenü wird bei neuem Datensatz nicht angezeigt

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#755]
Legt man unter _Verwaltung - Schule - Allgemeine Angaben_ im Bereich _Gliederungen_ einen neuen Datensatz an, so wird das Dropdown Menü rechts nicht automatisch angezeigt. 

![Dropdown_Schule](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/8d023334-46af-4255-be5e-bd8ebd433970)

**Comment by JuergenRichter** [comment]
Das ist bei anderen Fäälen aber auch nicht anders:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/c5c4c4e3-de01-41e1-b3dc-62e8d34e0cb9)

Ich muss mal prüfen, ob man das global einstellen kann.
