### ISSUE TITLE
Verwaltung - Schule - Halbjahreswechsel -> Skalierung des Datumswahlfenster bei hoher Auflösung 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#756]
Siehe Screenshot. Das Problem trat bereits in #666 auf. 
Testumgebung: Surface 6 Pro, Windows 10 Pro
Im Fall von Full HD wird das Datumswahlfenster ordnungsgemäß angezeigt. 
Eventuell betriff dies auch weitere Datumwahlfenster.

![Datumswahlfenster](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/48c06068-207d-4ec4-8546-b433f6ce9c0c)

**Comment by pemichalski** [comment]
Weitere Betroffene Fenster (Verwaltung - Schule - Halbjahreswechsel):

![Fenster I](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/c987b2f4-f4b2-496b-8bdd-37433648a079)

![Fenster ii](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/932292f5-b4db-4157-92b7-1d2840b29c1f)

**Comment by AnneSchueller** [comment]
Bei meinem Full HD Monitor, habe ich einen leichten Abschnitt der Zahlen.
![2023-09-01_104403](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/bfe6e7a5-89c5-4f71-b51e-7ec29ee0cf1c)


Surface-Bildschirme sind definitiv zu klein für SChild3
