### ISSUE TITLE
Neustart bei Abschnittswechsel

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#757]
Ist es möglich das Verhalten von SchILD 2, bei einem Abschnittswechsel keinen Neustart durchführen zu müssen, ebenfalls in SchILD 3 umzusetzen?

**Comment by FrodBRA** [comment]
Ich möchte einen Knopf "SchILD neu initialisieren" vorschlagen, der in "Verwaltung" und "Kataloge" angezeigt wird und welcher im laufenden Betrieb ebenfalls die Kataloge neu einliest. Hier könnten dann auch die generellen Schuldaten/Einstellungen usw. erneut geladen werden, inklusive des aktuellen Abschnitts.

Den Vorschlag hier halte ich für sich genommen nicht so wichtig, dass Katalogänderungen (mitunter?) ohne Meldung einen Neustart erfordern, halte ich bezüglich der effektiven Nutzung im Alltag für verbesserungsfähig. Dieser Knopf würde dann aber auch solche Usecases hier mit abdecken.

**Comment by AnneSchueller** [comment]
Bei welcher Kataloganpassung klappt das denn nicht? 
Die Katalogeinträge, die ich jetzt getestet habe, sind alle unmittelbar nach dem Anlegen auch auswählbar.

@JuergenRichter Was passiert denn genau bei "automatische Prozesse durchführen"?

m.E. würde hier ein weiterer Knopf eher Verwirrung stiften.
Wenn wir zum Testen mit Schild3 arbeiten gibt es dort u.U. viele Anpassungen oder man testet eine Hochschulung mehrfach, sodass der Neustart für das Testen etwas nervt. Im Realbetrieb in Schulen macht man das aber nicht so oft. Daher denke ich, dass hier ein Neustart nicht stört und das so bleiben kann.

**Comment by AnneSchueller** [comment]
Wir belassen es erstmal dabei, dass nach einem Abschnittswechsel ein Neustart zum Laden aller Daten notwendig ist.
Dies ist in SchILD2 übrigens auch so, nur dass kein Hinweis erscheint. Beispielsweise fehlen dann auch erstmal die Kurse und müssen neu geladen werden.
