### ISSUE TITLE
SchILD 2 Shortcuts übernehmen

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#758]
Der Shortcut 'Strg + f' öffnet das Suchfenster des Containers. In SchILD 2 rief dieser Shortcut das Menü _Suchen_ auf. Besteht die Möglichkeit, die ursprüngliche Funktionalität beizubehalten und für die Suche im Container einen anderen, bislang noch nicht verwendeten Shortcut zu setzen?

**Comment by JuergenRichter** [comment]
Shortcuts sind in Arbeit

**Comment by FrodBRA** [comment]
Verwandtes Issue:

https://github.com/SVWS-NRW/Schild3-BetaTest/issues/596

**Comment by AnneSchueller** [comment]
Schließe ich wegen Doppelung
