### ISSUE TITLE
Kataloge - Spaltenbreite sollte benutzbare Werte skaliert werden

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#759]
Unter der Prämisse, dass die minimale Auflösung ein Full HD Monitor ist, sollte die Spaltenreite in sämtlichen Bereichen bei der Initialisierung auf benutzbare Werte skaliert werden.

Es sollte beachtet werden, dass ein großer Teil der Benutzer nicht technikaffin ist.

Momentan sind sämtliche Einträge im Reiter Kataloge abgeschnitten:
 
![Spalten](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/3167c3a5-0ba5-42e3-8da7-70699ac03f61)

**Comment by HHayen** [comment]
Das wäre wirklich wichtig! Unterstütze ich.

**Comment by pemichalski** [comment]
Im Fenster Schuljahreswechsel ist die Spalte Versetzungsvermerk ebenfalls abgeschnitten.

![Schuljahreswechsel_spalte](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/d0f57bd9-081d-4516-b257-a30348de6e00)

**Comment by FrodBRA** [comment]
Dem stimme ich absolut zu. Wir müssen unbedingt bedenken, dass ein sehr großer Teil das komplette Gegenteil von "computeraffin" ist und denen ist ein "du musst da händisch überall noch nachbessern" nicht vermittelbar ist.

Ebenfalls möchte ich zu bedenken geben, dass bei 4000 SchILD-Installationen und im Schnitt 15 Nutzern, auch über die ersten Jahre verteilt, und bei ca. 20 Tabellen tatsächlich über die Zeit mehr als 1.000.000 Tabellen händisch angepasst werden müssen. Über die erwartete Lebenszeit von SchILD handelt sich sogar noch um viele weitere händische Operationen, die von Nicht-Computeraffinen in einer Welt, die mehr und mehr von UI-Entlastung dominiert wird, vorgenommen werden müssen. 

Das sollte informatisch mit einem passend gewählten Auslieferungszustand entlastet werden.

**Comment by AnneSchueller** [comment]
@JuergenRichter 
Wäre es möglich, hier mal etwas auszutesten?
Die viel zu klein gewählte Standard-Spaltenbreite fällt bereits jetzt schon vielen Usern immer wieder sehr negativ auf.

**Comment by JuergenRichter** [comment]
Ich habe da nun noch eine Änderung gemacht. Das Problem dürfte im wesentlichen "Standard-Kataloge" (z.B. Orte, Ortsteile, Konfessionen usw.) betreffen. Das sind solche, die keine "eigene" Darstellung haben, sondern alle das gleiche Anzeigefenster verwenden, mit je nach Katalog variierender Spaltenzahl, Datentyp und Feldlänge. Die Frage ist auch, was in solchen Fällen eine "sinnvolle" Spaltenbreite ist. Ich berechne das jetzt wie folgt:
-Zuerst wird die Spaltenbreite so eingestellt, dass die Überschriften komplett sichtbar sind
-Anschließend werden die Dateninhalte jeder Zeile analysiert, falls notwendig, wird die Spaltenbreite vergrößert, damit der Inhalt vollständig sichtbar ist. Das kann in bestimmten Fällen natürlich dazu führen, dass eine Spalte recht breit wird.

Das ganz wird aber nur gemacht, wenn es in der Registry noch keinen Eintrag für den betreffenden Katalog gibt. Sobald ein Katalog einmal angezeigt wird, speichert das Programm beim Schließen die Spaltenbreiten auf die Werte, die der Benutzer eingestellt hat (oder die durch obigen Algorithmus ermittelt wurden). Um daher mit der neuen Programmversion das Verhalten zu testen, ist es notwendig, die vorhandenen Einträge in der Registry zu löschen, entweder über regedit.exe (Schlüssel ist HKEY_CURRENT_USER\Software\Schild3000) oder in den Programmeinstellungen von SchILD:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/2ea2a3e7-8723-4637-b9a7-29d9f34db33c)

Update kommt in Kürze, bitte mal testen.

**Comment by AnneSchueller** [comment]
Hier mal eine Rückmeldung zur Spaltenbreite:
Die Spaltenbreite für die Kataloge Allgemeine Kataloge Erzieherarten bis Haltestellen sind von der Defaulbreite super. (Bis auch die Förderschwerpunkte)

Die Spaltenbreite Kindergärten bis Andere Schulen und Schulnummern sind bei mir auch gut dargestellt.  Teilweise sind die Namen abgeschnitten, aber das finde ich nicht schlimm, da die teilweise ziemlich lang sind und sonst die Spalten ganz rechts aus dem Bildschirm verschwinden würden. 

Das speichern der individuellen Spaltenbreiten klappt bei mir nicht. Die Spaltenbreite springt immer wieder zurück (siehe Video)
Das passiert nur bei den allgemeinen Katalogen. Die Einstellungen der Schulbezogenen Kataloge werden richtig gespeichert.

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/4f4d315a-3f95-4e3d-b90a-5def5a323884

**Comment by JuergenRichter** [comment]
Behoben.
