### ISSUE TITLE
Platz für 3. Klassenlehrer?

### ISSUE THREAD

**Issue by ADV-Burmeister** [SVWS-NRW/Schild3-BetaTest#76]
In der Schulwirklichkeit ist es so, dass in Schulen mit Förderkindern oft eine Förderlehrkraft die Aufgabe eines 3. Klassenlehrers übernimmt, zum Beispiel auch um dann in Schild die Förderzeugnisse und die FBLE-Einträge und Bemerkungen zu korrigieren und zu betreuen.
Es wäre meiner Meinung nach sinnvoll (und Kollegen fragen immer wieder danach), dies auch in Schild abzubilden, damit zusätzlich eine dritte Lehrkraft vollen Zugriff auf eine Klasse erhält.
Platz wäre ja da.

![grafik](https://user-images.githubusercontent.com/75778386/104598019-59f09200-5676-11eb-96f5-59f9b932677a.png)

**Comment by FPfotenhauer** [comment]
Muss nur noch von Schild2.0 "rüber" geholt werden.

**Comment by ADV-Burmeister** [comment]
In Schild 2.0 habe ich auch nur Platz für 2 Klassenlehrer gesehen.
![grafik](https://user-images.githubusercontent.com/75778386/104602230-780cc100-567b-11eb-909e-3b76c1c60451.png)

**Comment by FPfotenhauer** [comment]
Die Sonderpädagogen werden über den Gruppenprozess eingetragen.
Über die Klassen-/Versetzungstabelle könnte man direkt reden, wenn das nach Schild3.0 geholt wird.

![SNAG_2021_01_14_15 33 44](https://user-images.githubusercontent.com/34127980/104604727-f5393580-567d-11eb-8901-16bf022836db.png)

**Comment by ADV-Burmeister** [comment]
Okay, jetzt verstehe ich, was du meinst

**Comment by FPfotenhauer** [comment]
Der Sonderpädagoge bekommt nun auch eine Notendatei.

**Comment by JuergenRichter** [comment]
Ist auch in SchILD3 umgesetzt
