### ISSUE TITLE
Wechsel von Kataloge - Klassengruppen/ Abteilungen zum Reiter Schüler führt zu einer fehlerhaften Darstellung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#760]
Wechselt man von Kataloge - Klassengruppen/ Abteilungen zum Reiter Schüler führt zu einer fehlerhaften Darstellung. Schüler zeigt weiterhin den Katalog.
Schild Version 3.0.71.9
SVWS-Server: 0.6.17

![Wechsel](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/6410b06b-f207-4d92-8dfd-3e9b65b4fcf4)

**Comment by JuergenRichter** [comment]
Kann ich in der Version 3.0.72.9 nicht reproduzieren
