### ISSUE TITLE
Suche Statistik-Nr

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#761]
Suchfunktion über Statistik-Nr. ist ohne Funktion:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/84628225/72c0064a-0651-4172-835b-5cb27d0e08e3)

**Comment by JuergenRichter** [comment]
Das Feld für die "Statistik-Nr." (bei der es sich um die Schüler-ID handelt, haben wir nun auch umbenannt) hat eine gewisse Sonderfunktion. Hier macht es nämlich keinen Sinn, bei jeder Tasteneingabe (wie optional bei den anderen Feldern) zu filtern, da ja konkret genau ein Datensatz gefunden werden soll. Wir haben daher noch einen Schalter "Suche starten" hinzugefügt, um 
den Suchprozess aktiv starten zu können. 
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/631c19ca-4242-4f1f-8d5f-b2137f7f7281)

**Comment by HHayen** [comment]
Danke!

**Comment by AnneSchueller** [comment]
Gibt man beim Vornamen einen Buchstaben ein, so kann man keinen zweiten Buchstaben eingeben. Man muss erst wieder mit der Maus in das Feld "Vorname" klicken. Analog, Straße und Name.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/4b3de62f-fb60-4caf-a7a9-a0b4dfb5db4e)

**Comment by JuergenRichter** [comment]
Behoben
