### ISSUE TITLE
Filtercontainer wird abgeschnitten nach Filterung

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#762]
Wenn ich einen Kurs oder einen Klasse filtere, wird der Filtercontainer abgeschnitten.
![abgeschnittene_filter](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/5e5c5aea-5611-4b74-8ab2-b9cfd6038c6c)

Wenn ich den Filter löse, ist die Darstellung wieder korrekt. Das lösen des Filters funktioniert schnell, allerdings erscheint dann der Berechnungs-Mauszeiger für wenige Sekunden, als würden noch weitere intensive Berechnungen ausgeführt.

PC: Surface
2736 x 1824 px
175%

**Comment by AnneSchueller** [comment]
Wurde hier was korrigiert? Bei mir funktioniert das mit der aktuellen Version 3.0.73.10 sowohl bei Schueler als auch bei GP einwandfrei.

**Comment by JuergenRichter** [comment]
@Raffenberg 
Bitte mal einen Screenshot des "Filtercontainers" (in korrekter Ansicht) zeigen. Ist da evtl. die Dropdownliste für die Teilstandorte sichtbar?

**Comment by Raffenberg** [comment]
@JuergenRichter 
Teilstandorte sind nicht sichtbar. Das Problem tritt bei Benutzung eines beliebigen Filters Klasse, Jahrgang, Kurs, Gliederung, Abteilung auf.
![vor der Filterung](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/a78f1246-3f47-4548-937d-0000dc9ecb28)
![nach der Filterung Klasse](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/03e7b9b6-88d6-4671-97c2-2b5cc141b48b)

**Comment by AnneSchueller** [comment]
Laut Tests aus diesem Issue:

"Dann tritt der Fehler ausschließlich bei höheren Auflösungen ab QHD auf.  Bei 1920*1080 klappts"

Siehe hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/782

**Comment by JuergenRichter** [comment]
Ich hab da noch etwas angepasst. Bei mir funktioniert es jetzt sowohl auf einem HD-Monitor als auch auf einem 4K-Monitor ohne Probleme.

**Comment by Raffenberg** [comment]
Bei mir tritt das Problem immer noch auf (3.0.74)

![Filter](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/60efea5e-e31a-490c-b852-c0cba0e03e13)


Standard in den Sekretariaten sollten momentan 21 bis 24-Zoll Monitore sein. Damit bewegen wir uns wahrscheinlich zwischen den drei Standardauflösungen in 16:9 an:
1980x1080
2560*1440
3840x2160

Bei uns sind z.B. die Monitore von Dell beliebt, die in 16:9, aber auch in 16:10 ausgeliefert werden.

**Comment by JuergenRichter** [comment]
Bei allen der genannten Auflösungen funktioniert es bei mir. Habe es auch mit verschiedenen Auflösungen probiert, auch da keine Probleme. Bitte mit der nächsten Version nochmal testen.

**Comment by FrodBRA** [comment]
Könnte das eine Eigenschaft von Surfaces sein (Treiber?) bzw. der ungewöhnlichen Auflösung, so dass die notwendige Größe der Box nicht hinkommt?

**Comment by AnneSchueller** [comment]
Ich habe das jetzt auch mal mit meinem Surface getestet und habe keine Probleme mit der Darstellung des Filtercontainers.
Wenn ich das richtig verstanden habe, sind im nächsten Update nochmal Anpassungen bezüglich des Layouts vorgenommen wurden. Das sollte dann nochmal getestet werden.

**Comment by Raffenberg** [comment]
Beim Filtern verspringt der Bereich nicht mehr. Allerdings ist die Darstellung des Filters "Abteilungen" auf einem FullHD-Monitor abgeschnitten. Vor dem Hintergrund, dass immer mehr FullHD-Monitore Einzug in Verwaltungen haben, sollte hier noch nachgebessert werden.

Wichtig: Wenn Schild auf einem Primärmonitor mit normaler Auflösung gestartet wird, ist die Darstellung richtig. Dies trifft auch dann zu, wenn das Fenster von Schild auf einen Full-HD-Monitor verschoben wird.

Wenn Schild auf einem Full-HD-Monitor startet, bleibt der Filtercontainer abgeschnitten (s. Bild)

![1](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/58168b9b-576c-429d-b953-492d2e9e76a8)

**Comment by JuergenRichter** [comment]
"Wichtig: Wenn Schild auf einem Primärmonitor mit normaler Auflösung gestartet wird, ist die Darstellung richtig. Dies trifft auch dann zu, wenn das Fenster von Schild auf einen Full-HD-Monitor verschoben wird.

Wenn Schild auf einem Full-HD-Monitor startet, bleibt der Filtercontainer abgeschnitten (s. Bild)"

Das war der entscheidende Hinweis, jetzt klappt es bei mir auch mit dieser Konstellation.

**Comment by AnneSchueller** [comment]
Das Problem besteht weiterhin. Mir ist aufgefallen, dass das auf meinem Surface nur dann abgeschnitten ist, wenn ich LUNA eingestellt habe. Vorher hatte ich "Light" eingestellt.
Version 3.0.7.8

**Comment by Raffenberg** [comment]
Ich hole das Issue nochmals nach vorne. Auch in der neusten version werden bei mir Filtercontainer immer noch abgeschnitten. Der eine Monitor hat eine UHD-Auflösung, der andere 2120x1440 (125%).

Sowohl in Luna, als auch bei den anderen Stilen.

Es fällt auch immer auf, dass die Eingabefelder unten abgeschnitten sind. Es fehlt der unetere Rand, was garantiert darauf zurückzuführen ist, dass die Überschriften in die vorhergehenden Felder ragen.

![Filter](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/a8a987f8-3262-48d0-87c1-4af0a9012b72)

![Filter Silver](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/06691ebb-9ef2-41d4-b444-c7c90d610a0f)

So sollte es aussehen:
![Eingabefelder](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/9ec5de96-47a4-48e7-a0f7-8edfadbfe227)

**Comment by FrodBRA** [comment]
Tritt so in 3.0.85.10 nicht mehr auf.

@AnneSchueller

**Comment by Raffenberg** [comment]
Bei mir funktioniert das jetzt auch.
