### ISSUE TITLE
Schuljahreswechsel - Schrift bei höherer Auflösung als Full HD zu klein

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#763]
Beim Schuljahreswechsel ist die Schrift bei Systemen mit einer höheren Auflösung als Full HD im oberen Bereich zu klein.

![Schuljahreswechsel_schrift](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/12e33549-313f-43f5-96da-d69198bfb111)

**Comment by AnneSchueller** [comment]
@JuergenRichter Wurde hier bereits etwas korrigiert?
Bei mir erscheint die Schrift in der gleichen Größe wie bei den Schülern (Skallierung 100 % Full HD)
Version 3.0.73.10

**Comment by JuergenRichter** [comment]
Ich habe das nun bei mir auf einem 4K-Monitor mit unterschiedlichen Skalierungen ausprobiert, kann es nicht reproduzieren.
Ich schließe dieses Issue erst mal
