### ISSUE TITLE
Ribbon Überarbeitung

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#764]
Ist es möglich, das Ribbon so zu überarbeiten, dass der Button Standardauswahl in Schüler, Auswahl und Gruppenprozesse überall links an der gleichen Stelle groß erscheint?

**Comment by AnneSchueller** [comment]
Aufwendige Änderungen am Layout würde ich an dieser Stelle erstmal ganz hinten anstellen. Ich gehe auch davon aus, dass die User eher auf den Filter klicken, um an die  Standard-Auswahl zu kommen

**Comment by AnneSchueller** [comment]
Ggf später
