### ISSUE TITLE
Fensterbereich "Aktuelle Schülerauswahl" im Reiter Gruppenprozesse

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#765]
Der Fensterbereich "Aktuelle Schülerauswahl" sollte auch im Reiter Gruppenprozesse zur Verfügung stehen.

**Comment by JuergenRichter** [comment]
Bei mir ist das der Fall:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/6df8b878-8720-4b88-8a7e-0e49bb92dfcf)

**Comment by AnneSchueller** [comment]
Beim Switch von Auswahl nach GP fehlt diese:

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/e9871738-4f59-49c5-b06a-d8a871ea3d96

**Comment by JuergenRichter** [comment]
Das Programm reagiert nun wie folgt:

-Wenn Auf den Karteireiter "Auswahl" gewechselt wird, dort dann aber keine Filterung aktiviert wird und anschließend auf den Reiter "Gruppenprozesse" gewechselt wird, wird dabei der Bereich "Aktuelle Schülerauswahl" (bzw. die alternative Filteroption, wenn der "Schnellfilter SchILD2" nicht aktiviert ist) angezeigt.

-Wenn aber auf dem Karteireiter "Auswahl" gewechselt wird, dort eine Filterung ausgeführt wird und man dann auf den Reiter Gruppenprozess wechselt, wird der Bereich "Aktuelle Schülerauswahl" **nicht** angezeigt (nur das grüne Trichtersymobol). Der Grund ist ja, dass nun ja ein "individueller Filter" aktiv ist (also nicht die "Standardfilterung", die bei "Aktuelle Schülerauswahl" eingestellt und angezeigt wird). Um den Bereich "Aktuelle Schülerauswahl" wieder sichtbar zu machen, muss erst der individuelle Filter deaktiviert werden (z.B. über grünes Trichtersymbol).

**Comment by AnneSchueller** [comment]
Genau der erste Punkt funktioniert aktuell nicht. Das ist der Fall in den ersten 5 Sekunden vom Video. Obwohl hier keine Schüler gefiltert werden bei der Auswahl ist eine Schülerauswahl beim Switch auf Gruppenprozesse nicht mehr möglich.

Zum zweiten Fall: Ist ein Filter aktiviert und man klickt beim Reiter Gruppenprozess auf das Trichterzeichen, werden zwar wieder alle Schüler aktiviert, aber die Schülerauswahl fehlt dann. 

Weiter führt der erneute Wechsel auf den Reiter Auswahl dazu, dass ein zuvor erstellter Filter gelöscht wird. Das ist manchmal sehr ärgerlich. Das sollte nur bei "Standard-Auswahl" bzw. Klick auf grünen Trichter passieren.
