### ISSUE TITLE
Verwaltung - Benutzer - Benutzerverwaltung -> Button für den Befehl "Neuen Nutzer anlegen" 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#767]
Ist es möglich in _Verwaltung - Benutzer - Benutzerverwaltung_  einen Button für den Befehl "Neuen Nutzer anlegen" 
hinzuzufügen?

**Comment by JuergenRichter** [comment]
Eigentlich ist die "Philosophie" an dieser Stelle, Funktionen, die einen Datensatz betreffen, über die rechte Maustaste zur Verfügung zu stellen
