### ISSUE TITLE
Verwaltung - Benutzer - Benutzerverwaltung -> Anlegen eines neuen Benutzers führ zu Fehler

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#768]
Legt man in _Verwaltung - Benutzer - Benutzerverwaltung_ einen neuen Benutzer an, so führt ein anschließender Wechsel in ein anderes  Menü (z.B. Import) oder in einen anderen Reiter (z.B. Auswahl) zu einem Fehler.

![zugriff_nutzer_import](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/9379e43f-93bb-4b4f-9553-9ee218bf1624)

![zugriff_nutzer_import_ii](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/b048abcd-b6e3-425d-ac6b-ee7e50edb687)

**Comment by AnneSchueller** [comment]
[SchILD30 (2).txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12497517/SchILD30.2.txt)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Welche Benutzerart wurde denn verwendet?
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cdaed263-175a-4af9-9a9b-e466f64b9764)

**Comment by JuergenRichter** [comment]
Nachtrag: Wenn ich den gleichen Benutzernamen nochmals verwende, kommt eine Fehlermeldung "#23000Duplicate entry <Benutzername> for key 'Credentials_UC1'"

**Comment by JuergenRichter** [comment]
Es ist jetzt eine Prüfung vorhanden, ob ein Benutzer schon existiert.

**Comment by AnneSchueller** [comment]
Klappt bei mir jetzt auch ohne Fehlermeldung
