### ISSUE TITLE
Feld Bildungsgang

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#77]
In der aktuellesten Versioen des SVWS-Schema wurde das Feld "Bildungsgang bei den Lernabschnittsdaten entfernt.
Offensichlich wird darauf aber zugegriffen.

![SNAG_2021_01_14_15 37 04](https://user-images.githubusercontent.com/34127980/104605271-92946980-567e-11eb-8e98-0821ccd52164.png)

**Comment by JuergenRichter** [comment]
Werde morgen ein Update bereitstellen, wo das Feld raus ist
