### ISSUE TITLE
Fehlermeldung Mismatch SVWS-Version verdreht

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#770]
### Schildversion 3.0.73

in der server.json im Installationsverzeichnis steht 0.7.0 als Version.
Die aktuell installierte SVWS-Server Version ist 0.7.1
Die folgende Fehlermeldung passt dann nicht:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/709b31c9-3294-4c12-9a00-cf931579d4e9)
Die Werte im roten und orangenen Rechteck sind vertauscht.

#### die Fehlermeldung muss lauten:
Die vorliegende Version **0.7.1** vom SVWS-Server ist eine andere als die von Schild3 erwartete Version **0.7.0**. Dies kann zu Problemen führen.

**Comment by JuergenRichter** [comment]
Behoben
