### ISSUE TITLE
Ausgrauung der Optionen bei Schuljahreswechsel unklar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#771]
3.0.73.10

Beim Versuch, einen Schuljahreswechsel vorzunehmen, sind die wesentlichen Optionen nicht anwählbar.

Mir ist der Grund für die Ausgrauung nicht klar. Übersehe ich einen Grund?

Es sollte eine Angabe geben, wieso bestimmte Optionen nicht zur Verfügung stehen.

![SJW unklar](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/692ca038-89f0-4e92-a5ea-d7c9592102ee)

**Comment by AnneSchueller** [comment]
1. hat ja zunächst gar nichts mit der Hochschulung zu tun oder? Das könnte man auch als GP realisieren. Wenn ich das richtig verstehe wähle ich erst 1.  Klicke dann auf weiter. Und starte dann die Hochschulung erneut mit der Vergewisserung, dass nun bei jedem Schüler auch eine Folgeklasse steht.

Bei 2. bis 5. sind diejenigen Felder ausgegraut, die nicht durchgeführt werden können, weil sie schon vorhanden sind:
Nach Ausführen von 2. gibt es bereits einen neuen Abschnitt für die Schule:
![2023-09-08_145541](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/1151032b-b874-46a7-a127-b822d05dd404)


Bei Deinem Bild oben, ist bereits alles angelegt, die Schüler sind bereits im neuen Abschnitt, nur die Schule noch nicht (hier müsstest du eigentlich alles lila-farbige Schüler vorfinden.

Hilfereich für die Ausgrauung wäre, wenn noch ein entsprechender Hinweis da wäre, z.B. hinter der Überschrift
2. Basisdaten...anlegen  (Sind bereits angelegt) oder unmittelbar dadrunter "Dieser Schritt wurde bereits durchgeführt"


Was mir in dem Zusammenhang noch auffällt:

Klickt man auf den GP/Lernabschnitte /Versetzung öffnet sich das gleiche Fenster. Wenn man jetzt Folgeklassen automatisch einträgt ,macht man das dann direkt für alle SuS und nicht für die im Container. Der Workflow ist etwas verwirrend m.E.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/be11dc33-c143-4aea-bfea-1f0576bbf710)

**Comment by JuergenRichter** [comment]
Siehe auch #780
