### ISSUE TITLE
Verwaltung Werkzeuge

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#772]
Wenn ich in der aktuellen Version [Schild (v3.0.73) und SVWS-Server (win64-installer-0.7.1.exe)] unter Verwaltung/Werkzeuge die SQL-Eingabe angeklickt habe und danach eine andere Schaltfläche unter Verwaltung (z.B. Einstellungen) aktiviere, kommt diese Fehlöermeldung:
![Foto2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/b23ca7cf-ef07-4e2c-be4c-9b263c87611a)

**Comment by JeVaske** [comment]
[SchILD30.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12535990/SchILD30.zip)

**Comment by AnneSchueller** [comment]
Kann ich reproduzieren. 

Wahrscheinlich ähnliche Ursache wie hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/774

**Comment by JuergenRichter** [comment]
Behoben
