### ISSUE TITLE
Fensterposition bei Programmstart

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#773]
Beim Start von Schild3 merkt sich das Programm die letzte Fensterposition nicht. Ich versetze das Programm eigentlich immer in den Modus "Maximieren". Schild startet jedoch immer als Fenster und immer nach links verschoben. Dabei ist es egal, ob ich die Fensterposition anpasse.

Wenn ich die Fenstergröße ändere, scheint sich Schild die Größe **_und Position_** zu merken. Noch immer startet Schild im Fenstermodus, jedoch nun mit korrekter Position.
![Fensterstart](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/1bbf34d5-369f-4c0c-8366-091ca97a456d)

**Comment by JuergenRichter** [comment]
Ist nun umgesetzt
