### ISSUE TITLE
Export für den Schulträger

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#774]
Wenn ich in der aktuellen Version [Schild (v3.0.73) und SVWS-Server (win64-installer-0.7.1.exe)] unter Verwaltung /Export auf "Für Schulträger" klicke, kommt die folgende Fehlermeldung:
![Foto3](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/4a038d40-b0f0-467a-80db-409c2e02cdbd)
[SchILD30.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12536182/SchILD30.zip)

**Comment by FrodBRA** [comment]
Das konnte ich so nicht reproduzieren. 

Ist der Fehler auch nach einem Neustart von SchILD wieder aufgetreten? Da scheint etwas mit der UI schief zu laufen?

**Comment by AnneSchueller** [comment]
Ich kann das  reproduzieren. Der Fehler tritt auf, wenn man bei den Exporten hin und her schaltet:


Uploading Video_2023-09-07_094502.mp4…

**Comment by JuergenRichter** [comment]
Die Vorgänge wurden überarbeitet, bitte mit dem nächsten Update testen.
