### ISSUE TITLE
Verwaltung Datenbank Benutzerrechte

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#776]
Ich habe einen Benutzer der Gruppe Schulleitung mit Rechten "SQLite importieren", "SQLite exportieren" und "Schema erstellen und migrieren" angelegt.

Unter Verwaltung->Datenbank werden Menüpunkte ausgegraut, obwohl die Kompetenz vergeben wurde
![VerwaltungDatenbank](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/01ee02ee-d7c6-4eda-b101-e7196cec10de)

Die aktive Menüpunkte können zwar ausgeführt werden, führen aber in eine Fehlermeldung
![DatenbankSichern](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/88ea23bf-6302-4307-9948-bc1d1313a099)

Faktisch kann momentan das Datenbankhandling nur als Admin vornehmen.

**Comment by JuergenRichter** [comment]
Die ausgegrauten Optionen sind derzeit nur verfügbar, wenn man Admin-Berechtigung hat. Ich war davon ausgegangen, dass diese Optionen (da sie root-Berechtigung erfordern)  auch nur vom Admin ausgeführt werden dürfen.

Die Fehlermeldung 403 kommt ja vom SVWS-Server. Ich vermute daher, dass dieser intern prüft, ob der Benutzer Admin-Berechtigung hat. Sofern der Aufruf beim SVWS-Server für diese Funktionen nur mit Admin-Berechtigung möglich ist, kann man sich im Grunde auch die Optionen "SQLite importieren", "SQLite exportieren" und "Schema erstellen und migrieren" bei den Berechtigungen sparen.

**Comment by Raffenberg** [comment]
Prinzipiell fände ich es schon gut, wenn eine Datenbank von einem Standarduser gesichert werden kann.

Bei allem anderen kann man auf dem Standpunkt stehen, dass das nur ein Admin darf, gleichwenn momentan wahrscheinlich viele Normaluser auch eine Datenbank wieder herstellen können.

@ThomasBachran 
Hier sollte dann ein Abgleich zwischen den Berechtigungen in Schild (sind die dann noch notwendig?) und dem SVWS-Server stattfinden.

**Comment by JuergenRichter** [comment]
SchILD wertete z.Zt. die folgende Berechtigung aus:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/33bb27ff-c136-4934-ac43-b7c2cdde1bf2)

Daneben gibt es noch diese
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cea34dad-ee9a-4e1f-9f2e-6800062302b3)

Ein Eintrag ist m.E. überflüssig (

**Comment by JuergenRichter** [comment]
Korrektur: SchILD wertet bereits "Datenbank-Management>>SQL exportieren" aus,

**Comment by ThomasBachran** [comment]
Die Berechtigungen wurden zwar vorbereitet, aber bisher im SVWS-Server noch nicht verwendet. Das wird sich mit dem nächsten Release des SVWS-Server ändern. Dort wird auch der Import-/Export-Prozess leicht überarbeitet sein.

@JuergenRichter : Es gelten jetzt folgende Berechtigungen für die folgenden API-Aufrufe:
- "Datenbank-Management"/"SQLite exportieren (Backup erstellen)"
  - `/db/{schema}/export/sqlite`
- "Datenbank-Management"/"SQLite importieren (Backup einspielen)"
  - `/db/{schema}/import/sqlite`
- "Datenbank-Management"/"Schema erstellen und migrieren"
  - `/db/{schema}/migrate/mdb`
  - `/db/{schema}/migrate/mariadb`
  - `/db/{schema}/migrate/mariadb/{schulnummer}`
  - `/db/{schema}/migrate/mssql`
  - `/db/{schema}/migrate/mssql/{schulnummer}`
  - `/db/{schema}/migrate/mysql`
  - `/db/{schema}/migrate/mysql/{schulnummer}`

**Comment by JuergenRichter** [comment]
Frage: Wird bei einem Einspilen eines Backups in ein vorhandenes Schema weiterhin die "root-Anmeldung" beim SVWS-Server benötigt?

**Comment by FPfotenhauer** [comment]
Bei den o.g. Services nicht. da der svwsuser ja bereits existier, dann kann das mit AdminRechten in Schild gemacht werden.

**Comment by FrodBRA** [comment]
@Raffenberg 

Hat sich das Problem nun erledigt? Den anderen Ausführungen nach hier sollte dem ja so sein.

**Comment by AnneSchueller** [comment]
Das funktioniert mittlerweile.
