### ISSUE TITLE
Benutzerverwaltung Kennwortfenster ist winzig

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#777]
Wenn ich einen neuen Benutzer über das Kontextmenü anlege und anschließend ein Kennwort setze, erscheint ein Kennwortfenster mit winzigen EIngabefeldern und Überschriften (Der Screenshot ist vergrößert). Dieses wird anscheinend noch nicht entsprechend der Auflösung des PCs skaliert.

Surface Laptop
Auflösung: 2736x1824
Skalierung: 200%

![Kennwortfenster](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/99309194-0313-4661-9e47-6ef79a69c56e)

**Comment by JuergenRichter** [comment]
Behoben
