### ISSUE TITLE
Filter 1/Individualdaten --> Anmeldedatum

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#778]
In Schild2 hatten wir das auf Wunsch von vielen Schulen mit in den Filter aufgenommen. 
Es wäre gut, wenn wir das auch in Schild3 den Usern zur Verfügung stellen:

![2023-09-07_083852](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/547122fe-a20b-4d2d-965b-f1d29c316d84)

**Comment by JuergenRichter** [comment]
Ist jetzt vorhanden
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/fa7b0f10-733a-4776-8162-d295b8d6589c)
