### ISSUE TITLE
ZP - 10 Beschriftung ist falsch

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#78]
Bei der Wahl des ZP-10-Karteireiters wird unter Optionen "BK-Abschluss" angezeigt. Das ist sicherlich falsch ;)
![image](https://user-images.githubusercontent.com/75179015/104810110-f50e7680-57f2-11eb-8dee-0c542f516429.png)

Ich persönlich finde die alte Lösung mit der sofortigen Auswahlmöglichkeit der Optionen deutlich anwenderfreundlicher. Warum sollte ein neuer Nutzer unter Optionen die Prozesse suchen? Alternativ wäre genügen Platz vorhanden, die Prozesse auch direkt anzeigen zu lassen.
![image](https://user-images.githubusercontent.com/75179015/104810237-8847ac00-57f3-11eb-9edb-3b08a4f80b04.png)

**Comment by JuergenRichter** [comment]
Ist in Version 3.0.9 nun wieder ähnlich wie in SchILd2 gelöst
