### ISSUE TITLE
Hochschulung

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#780]
Wenn man erst Schritte 2-4 durchführt, kann man im Nachgang nicht mehr Schritt 5 ausführen. Der "Weiter" Button ist ausgegraut. 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/6c0709f2-6edc-4eb0-a83d-9932b8a8eed3)

**Comment by JuergenRichter** [comment]
Ist korrigiert. Dabei wurde die "Logik" der Häkchen auch etwas geändert, damit der Anwender sieht, welche Schritte schon durchgeführt wurden:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/8db72be5-3307-4fda-b3d0-defba07e86d4)

Wenn ein Häkchen gesetzt , aber ausgegraut ist, bedeutet das, dass die entsprechende Aktion schon ausgeführt wurde. Im obigen Beispiel ist also die eigentliche Hochschulung schon weitestgehend umgesetzt worden, es fehlt nur noch die Option, die Schule "als Organisation" in das neue Schuljahr zu setzen. Die SuS sind schon im neuen Schuljahr, das sieht man an der Farbe:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/bfe753b7-31d0-4a45-a397-f4a71fa89a6c)
