### ISSUE TITLE
Gruppenprozess funktioniert nicht

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#781]
GP Hauptförderschwerpunkt führt zur Fehlermeldung und wird nicht durchgeführt (analog weitere GP)

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/68461813-28c2-4b0a-8bcd-ea1bfc5d65fc

Die Fehlermeldung kommt nur wenn man die GP für explizit ausgewählte SuS vornimmt
[foerder.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12560335/foerder.txt)

**Comment by AnneSchueller** [comment]
@AnneSchueller : Nach Korrektur auch das hier kontrollieren: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/684

**Comment by JuergenRichter** [comment]
Behoben
