### ISSUE TITLE
"Aktuelle Schülerauswahl" nach Einsatz von Schnellfilter abgeschnitten

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#782]
Schild: 
Sobald man einen Schnellfilter anwendet, wird der Bereich "Aktuelle Schülerauswahl" unten abgeschnitten.
SchILD-NRW Version 3.0.73.10
SVWS-Server Version: 0.7.0

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/32135da4-aad8-46c0-982b-837be6ac9d86

**Comment by JeVaske** [comment]
[Schild (v3.0.73) und SVWS-Server (win64-installer-0.7.1.exe)] Ist bei mir nicht der Fall.

**Comment by pemichalski** [comment]
> [Schild (v3.0.73) und SVWS-Server (win64-installer-0.7.1.exe)] Ist bei mir nicht der Fall.

@JeVaske Welche Auflösung hat dein Monitor?

**Comment by JeVaske** [comment]
1920*1080

**Comment by pemichalski** [comment]
> 1920*1080

Dann tritt der Fehler ausschließlich bei höheren Auflösungen ab QHD auf.

**Comment by AnneSchueller** [comment]
Schließe ich wegen Doppelung hier:
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/762
