### ISSUE TITLE
GP Individualdaten ändern/Schulbesuch

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#783]
Der GP Individualdaten ändern/ Schulbesuch dann Klick auf Pulldown-Menü Versetzung erzeugt eine Fehlermeldung.
![Foto4](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/afd07f64-3eef-4857-8e70-1c60471c81e1)

Es wäre sinnvoll, wenn auch hier ein Hinweis ähnlich wie bei Entlassjahrgang käme:
![Foto5](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/da49ab3d-8dd3-4ff2-9463-45437c591186)

**Comment by AnneSchueller** [comment]
Mit Version 3.0.74.10 reproduzierbar. Ein Hinweis wäre auf jeden Fall sinnvoll.

[SchILD30.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/12576353/SchILD30.txt)

**Comment by JuergenRichter** [comment]
Behoben, Hinweis kommt jetzt auch
