### ISSUE TITLE
Umstellung WechselNr auf "0"

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#785]
![SNAG-0005](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/34127980/30240d88-e4a1-4511-8676-cb4e4bab3aab)

**Comment by JuergenRichter** [comment]
Behoben

**Comment by JuergenRichter** [comment]
Ich habe gerade festgestellt, dass wir uns durch die "0" (anstelle von NULL) das Problemeingefangen haben, dass die Sortierung der Lernabschnitte nicht mehr stimmt:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/4b82507f-b73e-4b4f-b3da-f99a6892e067)

Der Screenshot zeigt, dass der Lernabschnitt "vor dem Wechsel" nun nach dem aktuellen Abschnitt kommt. Das liegt daran, dass der Lernabschnitt "vor dem Wechsel" nun die "Wechselnr=1", der neue (aktuelle) Datensatz aber "Wechselnr=0" hat. 
Bei der bisherigen Regelung, dass der aktuelle Abschnitt den Eintrag "Wechselnr=NULL" bekommen hat, konnte die korrekte Sortierung im SQL-Befehl wie folgt erzielt werden

SELECT * FROM SchuelerLernabschnittsdaten LA
LEFT JOIN Schuljahresabschnitte SJA ON LA.Schuljahresabschnitts_ID=SJA.ID 
WHERE Schueler_ID=:SID AND Hochrechnung >= 0
ORDER BY SJA.Jahr, SJA.Abschnitt, **-LA.WechselNr desc**

Das funktioniert jetzt nicht mehr (siehe Screenshot). Wenn man aber die Sortierung wie folgt ändert, funktioniert es wieder
ORDER BY SJA.Jahr, SJA.Abschnitt, **LA.ID**

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/7943bb0d-9618-441f-9645-2a07dc68ddf0)

Das setzt dann aber voraus, dass die ID des neuen Datensatzes immer höher ist als die des "bisherigen" Datensatzes. Ich gehe mal davon aus, dass so sein wird (die IDS werden ja über die Datenbank per Trigger vergeben), wollte aber sicherheitshalber darauf hinweisen.

**Comment by ThomasBachran** [comment]
@JuergenRichter : Das Feld WechselNr ist derzeit wir folgt festgelegt:  
- Wird für Wiederholungen im Laufenden Schuljahres-Abschnitt genutzt
- 0=aktueller/neuester Lernabschnitt
- 1=vor dem ersten Wechsel
- 2=vor dem zweiten Wechsel 
- usw

**Comment by JuergenRichter** [comment]
Die Bedeutung ist mir schon klar. Das beschriebene Problem (was sich aber m.E. umgehen lässt) betrifft die Sortierung. Bei der bisherigen Vorgehensweise (aktueller Lerabschnitt hat Wechselnr NULL) konnte eine korrekte Sortierung durch 

ORDER BY SJA.Jahr, SJA.Abschnitt, -LA.WechselNr desc

bewirkt werden. Bei einem Schüler, der zweimal  einen Rücktritt in einem Abschnitt gemacht hatte, wurden die Datensätze dadurch wie folgt sortiert (dargestellt Jahr, Abschnitt und Wechselnr)

2023   1   1 ("vor erstem Wechsel")
2023   1   2 ("vor zweitem Wechsel")
2023   1   NULL (aktueller Abschnitt)

Durch die Änderung wird das nun so sortiert (bei gleicher "Order by"-Klausel)

2023   1   0 (aktueller Abschnitt)
2023   1   1 ("vor erstem Wechsel")
2023   1   2 ("vor zweitem Wechsel")

Wenn man das "Minus" bei "Order by" weglässt, ist das Ergebnis wie folgt:
2023   1   2 ("vor zweitem Wechsel")
2023   1   1 ("vor erstem Wechsel")
2023   1   0 (aktueller Abschnitt)

Korrekt aber wäre das:
2023   1   1 ("vor erstem Wechsel")
2023   1   2 ("vor zweitem Wechsel")
2023   1   0 (aktueller Abschnitt)

Unter derAnnahme, dass für die IDs folgendes gilt
ID aktuell > ID vor zweitem Wechsel > ID vor erstem Wechsel
(wogegen m.E. nichts spricht) erhält man die korrekte Reihenfolge, wenn man die ID statt der Wechselnr. in die Sortierung aufnimmt.

**Comment by FPfotenhauer** [comment]
Das die IDs aufsteigend sind, können wir nicht garantieren.
Wir sortieren die Abschnitte erst in der Applikation, also nicht über das SQL-Statement.
Wenn das nicht anders geht, dann würde ich einfach das "Minus" weglassen.
So häufig sind die Fälle mit 2 und mehr Wechseln nicht. M.M.

**Comment by ThomasBachran** [comment]
@JuergenRichter : Das lässt sich ggf. auch mit einem CASE lösen. Probieren sie mal folgendes:
``` SQL
SELECT * FROM SchuelerLernabschnittsdaten LA
LEFT JOIN Schuljahresabschnitte SJA ON LA.Schuljahresabschnitts_ID=SJA.ID
WHERE Schueler_ID=:SID AND Hochrechnung >= 0
ORDER BY SJA.Jahr, SJA.Abschnitt, CASE WHEN LA.WechselNr = 0 THEN 32767 ELSE LA.WechselNr END
```

**Comment by JuergenRichter** [comment]
Danke, probiere ich aus

**Comment by JuergenRichter** [comment]
Funktioniert
