### ISSUE TITLE
Bereich mit aktueller Schülerauswahl und Container nach Wechsel in den Bereich Kataloge abgeschnitten

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#786]
SchILD-NRW Version 3.0.73.10
SVWS-Server Version: 0.7.0
Auflösung: QHD

Die Breite des linken Bereichs mit aktueller Schülerauswahl und Container wird nach einem Wechsel in den Reiter Kataloge an die Breite der dortigen Menüleiste angepasst. Wechselt man von dort zurück in den Reiter Schüler, so ist der Bereich in der Breite abgeschnitten.

Update: 
Das Problem trat nach einer Neuinstallation auf. Das Menü links im Bereich Kataloge war ebenfalls abgeschnitten. 
Besteht die Möglichkeit, die Breite des linken Bereichs in den Reitern Schüler, Auswahl, Gruppenprozesse und Reportverwaltung unabhängig von der Breiten der einzelnen Reiter Verwaltung, Lehrkräfte und Kataloge zu setzen? 

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/b69a05ac-b255-440a-b237-3de2a85a8ffd

**Comment by JuergenRichter** [comment]
Behoben
