### ISSUE TITLE
Ankreuzkompetenzen werden nicht geladen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#787]
Neu hinzugefügte Ankreuzkompetenzen werden nicht übernommen:

Uploading Video_2023-09-12_112152.mp4…

**Comment by JuergenRichter** [comment]
Kann das Video lieder nicht sehen.

**Comment by AnneSchueller** [comment]
https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/3125ce86-e294-45ae-ae0a-a538b420650c

**Comment by JuergenRichter** [comment]
Behoben, beim Speichern einer neuen Kompetenzbeschreibung wurde versehentlich die Eigenschaft "IstASV" gesetzt. Dadurch wurden der neue Eintrag nicht korrekt eingefügt.
