### ISSUE TITLE
Neuer Filter

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#79]
Die Schulgliederung kann nicht gefiltert werden (der Haken wird nicht rot) und die Reihenfolge ist gegenüber Schild 2 vertauscht. Hat das einen Grund?
Filter-Zurücksetzen ist mit Doppelklick auf das Filtersymbol möglich. Das wirkt aber irgendwie nicht günstig platziert. War in Schild 2.0 besser. Der Schild 2.0 Filter sollte auf jeden Fall als Standard eingestellt sein. Der neue Filter als Option.
Schild 3.0:
![image](https://user-images.githubusercontent.com/75179015/106059544-26404e00-60f3-11eb-97a7-11a2d49626a2.png)
 
Schild 2.0:
![image](https://user-images.githubusercontent.com/75179015/106059570-2fc9b600-60f3-11eb-8a77-2e85781238ab.png)

**Comment by JuergenRichter** [comment]
In 3.0.11. behoben
