### ISSUE TITLE
Schild3 lässt sich nicht schließen ohne Server

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#790]
Wenn der Kontakt zum SVWS-Server verloren geht, dann lässt sich Schild3 nicht mehr schließen.
Man landet in einer Fehlerschleife und muss über den Taskmanager gehen.

**Comment by JuergenRichter** [comment]
"Wenn der Kontakt zum SVWS-Server verloren geht, "
Bedeutet das, dass der Kontakt während der Sitzung verloren geht. Oder ist der SVWS-Server schon beim Start nicht zu erreichen?

**Comment by FPfotenhauer** [comment]
Wenn der Kontakt während der Sitzung verloren geht.

**Comment by JuergenRichter** [comment]
Behoben
