### ISSUE TITLE
Farben der Fächer unter akt. Halbjahr

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#792]
Bei mir werden keine Fächerfarben auf dem Reiter Akt. Halbjahr angezeigt, wenn welche hinterlegt sind. 
![faecherfarben](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/d356aa5a-e5d0-4023-bb9d-cf24025ee57a)

Auf dem Reiter Übersciht klappt es hingegen.
![faecherfarben2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/543d80db-92f3-41f5-bcd9-3cba240eebda)

**Comment by JuergenRichter** [comment]
War ebenfalls eine Auswirkung der Umstellung auf die REST-Aufrufe, ist nun korrigiert.
