### ISSUE TITLE
Schüler - Individualdaten I - Wert im Feld Schulbesuchsjahre lässt sich nicht manuell ändern 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#794]
SchILD-NRW Version 3.0.74.10
SVWS-Server Version: 0.7.2

Der Wert im Feld Schulbesuchsjahre lässt sich nicht (wie im Wiki beschrieben) manuell ändern, sondern nur per GP.

**Comment by Raffenberg** [comment]
Der sollte sich gar nicht ändern lassen, meiner Meinung nach.

**Comment by AnneSchueller** [comment]
Gibt es hier denn schonmal Ausnahmen, bei denen man das individuell anpassen muss?
Sonst kann das auch aus dem GP raus.

**Comment by pemichalski** [comment]
@Raffenberg 
Im SchILD 3 Wiki heißt es:
 _"Im Feld Schulbesuchsjahre kann man manuell die eingetragene Zahl verändern. Sollte dort also aus irgendeinem Grund ein anderer Wert stehen, als z.B. in der Schulbescheinigung gewünscht, so kann dies einfach "übertippt" werden. Eine falscher Wert deutet aber darauf hin, dass das eingetragene Einschulungsjahr nicht korrekt ist und gegebenenfalls korrigiert werden muss."_

Das SchILD 2 Wiki sagt dazu:
_"Obwohl das Datenfeld für die Schulbesuchsjahre ausgegraut ist, weil hier ein berechneter Wert steht, kann man dort manuell die Schulbesuchsjahre verändern. Sollte dort also aus irgendeinem Grund ein anderer Wert stehen, als z.B. in der Schulbescheinigung gewünscht, so kann dies einfach "übertippt" werden."_

Sprich: bislang war die Funktionalität da. 

@AnneSchueller Ich kann morgen gerne einmal bei uns im Sekretariat nachfragen, ob und wann die Möglichkeit zur Änderung der Schulbesuchsjahre genutzt wird.

**Comment by pemichalski** [comment]
Rücksprache mit unserem Sekretariat ergab, dass es beispielsweise bei Schulbescheinigungen für die SuS aus den internationalen Klassen durchaus sinnvoll sein kann, die Schulbesuchsjahre manuell anpassen zu können.

**Comment by AnneSchueller** [comment]
Ich sehe ebenfalls das Problem, dass man durch die Neuberechnung dann händisch eingetragene Werte wieder überschreibt. Vielleicht sollte dann hier das Einschulungsjahr händisch angepasst werden.

Konsequenterweise würde ich dann sogar den GP für das setzten der Schulbesuchsjahre rausnehmen.

**Comment by pemichalski** [comment]
Den Gruppenprozess würde ich für den Fall beibehalten, dass man im laufenden Schuljahr eine Gruppe von SuS neu aufnimmt, für welche die Schulbesuchsjahre neu berechnet werden sollen. 
Oder würdet ihr die Berechnung der Schulbesuchsjahre als Prozess einfügen, der automatisch aufgerufen wird, sobald bei einem Datensatz ein Einschulungsjahr eigegeben wird?

**Comment by AnneSchueller** [comment]
Also ich meinte nicht den GP "Schulbesuchsjahre neu berechnen" (der sollte drin bleiben) sondern unter Individualdaten I das Feld, in dem man die Schulbesuchsjahre setzen kann.

**Comment by FrodBRA** [comment]
Ich bin gegen ein "Übertippen", gibt es nicht automatische Prozesse, die die SBJ berechnen? 

Würde man über die Jahre - z.B. zur Einschulung - hier und da Korrekturen vornehmen, würde dieses "Hier und da" in den Einzelfällen ja überschrieben werden. 

Was wäre denn überhaupt ein Einzelfall, bei dem ein Übertippen notwendig würde?

- Alle Fälle, in denen man "X Jahre" setzen würde, könnte man ja auch das demnach passende Einschulungsjahr setzen und alles ist in Ordnung.
- Andere Fälle, etwa, dass wer aus dem Ausland oder irgendwelchen Spezialarrangements kommt und weniger/mehr SBJ hat, als das Schulsystem so gemeinhin annimmt, kann man ja nicht einfach überschreiben, indem man eine falsche Zahl der SBJ reinlügt?

Hier wäre ja eher ein Schalter interessant, dass SBJ für die diese nutzenden Algorithmen als "passt schon" angenommen werden: gibt es hierzu überhaupt Sachverhalte in so umfangreichem Ausmaß, dass man etwas tun müsse? 

Zu Peters Beispiel von oben: WENN ein Überschreiben möglich wird, dann sollte auch ein Haken gesetzt werden "bei automatischer Berechnung ignorieren", so dass diese neuen Werte zukünftig nicht überschrieben werden. In diesem Fall sollte auf diesen Haken auch gefiltert werden können.

**Comment by AnneSchueller** [comment]
Ich glaube wir meinen das gleiche...

Man setzt das Einschulungsjahr und über GP werden die Schulbesuchsjahre richtig berechnet. 
Wenn jemand aus einem anderen Land mit 4 in die Schule gekommen ist, trägt man das auch entsprechend unter Einschulungsjahr ein und der GP rechnet die Schulbesuchsjahre korrekt aus.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/6881f45b-5f98-47d0-8f4a-6309b024ba53)

Nach dem GP...
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/7e5494d2-0526-42cc-b09b-e79f111183a9)

Dass das automatisch ohne GP funktioniert kann man später mal überlegen.

**Comment by JuergenRichter** [comment]
Die Schulbesuchsjahre werden ja nun nicht mehr bei den Stammdaten verwaltet (wie in SchILD2) sondern bei den Lernabschnitten. Daher kann man diese Angabe auch nicht auf "Individualdaten I" verändern (wie auch die Klasse). Es wurde aber vergessen, eine Eingabemöglichkeit auf dem Karteireiter "Akt. Halbjahr" zu schaffen. das wird nachgeholt.

**Comment by JuergenRichter** [comment]
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9c190da8-f9ca-44a6-b0bb-8f949c3a794e)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/ec7e3db5-34f8-45cf-9289-2b4653c35587)
