### ISSUE TITLE
Report-Schnellzugriff

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#795]
Der Report-Schnellzugriff kann zwar per Häkchen aktiviert werden und der Zugriff taucht dann auch beim Wechsel in eine andere Verwaltungsrubrik auf, aber es kann kein Schnellzugriff eingerichtet werden, da in dem Menü Verwaltung -> Einstellungen -> Reporteinstellungen nicht wie in der Wiki angegeben das Menü zum Eintragen existiert.

**Comment by Raphael-Kemna** [comment]
Ergänzend: Schildversion 3.0.74.10

**Comment by JuergenRichter** [comment]
Behoben, war eine Auswirkung der Umstellung auf die REST-Aufrufe beim Laden/Speichern der Konfiguration.
