### ISSUE TITLE
Mahnung per Report

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#797]
Schild-Version 3.0.74.10
Wenn bei einem Schüler eine Mahnung gesetzt wurde, so wird beim Aufruf des Reports unter Serienbriefs "Serienbrief Mahnung gefährdete Versetzung @Eltern.rtm" eine Fehlermeldung:
![Mahnung](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/145453339/8e2eca64-5e55-44f2-a8f4-e63058fcb6b3)

**Comment by AnneSchueller** [comment]
Es liegt an dieser Zeile. Die Fehlermeldung tritt immer dann auf, wenn noch kein Mahndatum eingetragen ist.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/207a5017-f4b3-428b-9666-8f0a4390105b)

Ich konnte die Funktion "nurMonat(...)" nicht bearbeiten. 
@JuergenRichter Woran kann das liegen?
