### ISSUE TITLE
Vorschlag: Name statt Benutzername

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#798]
Nachdem ich mich ja jetzt einloggen kann, ist mir folgendes aufgefallen:
Bei den Schüler wird ja oben angezeigt "letzte Änderung: MM.DD.YYYY durch xyz".

Hier wäre es schöner, wenn dort statt des Logins, der eigentlich Name stehen würde.

Sicher gibt es noch andere Stellen, wo das angepasst werden könnte/sollte.

**Comment by AnneSchueller** [comment]
Das ist wahrscheinlich Geschmackssachen ob hier das Kürzel oder der Name erscheint. Ich würde das an dieser Stelle erstmal lassen

**Comment by FrodBRA** [comment]
Das würde ich ebenfalls nicht verändern, so lange es wesentliche größere Probleme zu lösen gilt. Beides transportiert am Ende die identische Information. Ich schlage vor, das Thema vorerst zu schließen, zu einem späteren Zeitpunkt könnte dann ein Schalter ein "Einstellungen" eingebaut werden, bei dem sich zwischen "Kürzel", "Name" und "Name (Kürzel)" umstellen ließe. Damit könnte man sich die individuelle Vorliebe einstellen.

(Das Datum einer Änderung erscheint bei mir dem korrekten deutschen Standard entsprechend als DD.MM.YYYY.)
