### ISSUE TITLE
Gobale Einstellungen werden nicht übernommen

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#799]
Bei einer DB Migration werden die Programmeinstellungen unter "Globale Einstellungen" nicht übernommen, obwohl sie in der Datenbank vorhanden sind.
Beispiel: In Schild-NRW2 ist der Mailversand über SMTP eingerichtet. Schild-NRW3 steht aber auf "Mailprogramm verwenden" und die SMTP Felder sind leer.

**Comment by JuergenRichter** [comment]
Ist schon behoben, war eine Auswirkung der Umstellung auf die API-Befehle beim Laden/Speichern der Einstellungen

**Comment by kroerig** [comment]
Ich muss das Issue wiedereröffnen. In Version 3.0.78.14 werden die Einstellungen nicht übernommen.
