### ISSUE TITLE
Leistungsübersicht

### ISSUE THREAD

**Issue by me-rfb2000** [SVWS-NRW/Schild3-BetaTest#8]
In der Leistungsübersicht sind die Überschiften doppelt-> 2018/19-1  2018/19-1 
                                                                                           05                    05
                                                                                           05c (LE)           05c (LE)

UND das bei allen Abschnitten

**Comment by FPfotenhauer** [comment]
Außerdem wird m.E. ein (zwei?) Schieberegler benötigt, damit man die Übersicht an das Fenster besser anpassen kann.

![SNAG_2020_11_25_16 24 04](https://user-images.githubusercontent.com/34127980/100247594-c5519980-2f3a-11eb-9573-478f57ffa3c6.png)

**Comment by JuergenRichter** [comment]
Das mit den doppelten Überschriften ist in Arbeit.
Bei der Darstellung der Leistungsübersicht war versehentlich das "Alignment" auf "Left", ist nun korrigiert auf "Client", d.h. der gesamte Platz rechts neben der "Laufbahnübersicht" wird genutzt.

**Comment by me-rfb2000** [comment]
So haben die allgemeinen Angaben ausgesehen. Nach einem Neustart war es wieder in Ordnung. Benutzt man den Schieberegler dann:
![grafik](https://user-images.githubusercontent.com/73750717/100253827-e36ec800-2f41-11eb-9a86-7fda8675fd38.png)
