### ISSUE TITLE
Kennwort ändern in SchILD lässt sich nicht abbrechen

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#800]
Ist mir gerade durch #791 aufgefallen:

Will man den "Kennwort ändern" Dialog über Abbrechen verlassen, landet man in einer Endlosschleife zwischen den Dialogen "Kennwort eingeben" und "Das alte Kennwort" ist falsch. Nur der Klick auf das X hilft.

**Comment by JuergenRichter** [comment]
Behoben
