### ISSUE TITLE
Verwaltung - Einstellungen - Individuelle Einstellungen - Schnellfilter Layout kann nicht umgestellt werden

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#801]
SchILD-NRW Version 3.0.75.10
SVWS-Server Version: 0.7.2

Das Schnellfilter Layout  (Verwaltung - Einstellungen - Individuelle Einstellungen) lässt sich in meinem Fall nicht mehr von SchILD 2 auf  SchILD 3 umstellen. 
Falls das so vorgesehen ist, so sollte die Checkbox "Schnellfilter aus SchILD2 verwenden" im Menü "Individuelle Einstellungen" entfernt werden.

**Comment by JuergenRichter** [comment]
Das liegt daran, dass die Verwaltung der Einstellungen auf API-Aufrufe umgstellt wurde, das hatte zur Folge, dass die Einstellungen nicht korrekt gespeichert wurden. Ist aber schon behoben, neue Version kommt vorauss. diese Woche.
