### ISSUE TITLE
Verwaltung - Einstellungen - Individuelle Einstellungen - Wechsel des Schnellfilter Layouts führt zum Verlust von Datenfeldern 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#802]
SchILD-NRW Version 3.0.75.10
SVWS-Server Version: 0.7.2

Wenn ich den Haken vor der Checkbox "Schnellfilter aus SchILD 2 verwenden" (Verwaltung - Einstellungen - Individuelle Einstellungen) entferne, so führt dies im Kartenreiter "Schüler" im Bereich "Zusatzdaten" zum Verlust von Datenfeldern wie  z.B. "Haltestelle" oder "Fahrschüler".

![SchILD 2 Layout Verlust von Datenfeldern](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/cc6e8ba4-0995-41d1-aa3c-55f27019ca03)

**Comment by FrodBRA** [comment]
Ich möchte vorschlagen, dass nur eine Variante von Filter/Auswahl sauber geplant und umgesetzt wird.

Das reduziert Komplexität, da nicht zwei oder mehr Varianten erzeugt und getestet werden muss, es kann auch nicht zwischen mehreren Varianten umgestellt werden - so lässt sich diese eine Variante auch entsprechend geradeaus testen, warten und schulen.

(Gleiches gilt meiner Meinung nach auch für optionale UIs etc.)

**Comment by AnneSchueller** [comment]
Das nehme ich mal mit in die nächste Besprechung mit Jens und Frank.

**Comment by JuergenRichter** [comment]
Das mit den verschwindenden Datenfeldern kann ich nicht reproduzieren.

**Comment by AnneSchueller** [comment]
Funktioniert mit der neuen Version. Zusatzdaten bleiben sichtbar.
Ich schließe das Issue erstmal
