### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/Schild3-BetaTest#806]
Fehlermeldung nach Anklicken von "Datenbank sichern": Schild3 Version 3.0.76.11

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/84628225/c2e07476-47d6-4f07-bcdd-a4456b526e94)
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/84628225/f0f58eba-cbc0-4dab-811a-617bbe179d25)

**Comment by AnneSchueller** [comment]
Das kann ich nicht reproduzieren.
Hast du unter Einstellungen/globale Einstellungen ein gültiges nicht schreibgeschütztes Sicherungsverzeichnis eingegeben?
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/2d830db5-5458-4b5e-a89f-a583a823516d)

**Comment by HHayen** [comment]
Nein, das Irritierende war, dass die Meldung, dass ein solches Verzeichnis nicht eingetragen ist, nur beim ERSTEN Aufruf von "Datenbank sichern" erschien, danach nicht mehr.
Weiterhin wurde ja trotz Nichteintrag versucht in C:\ zu schreiben, was ja möglich sein müssten, da c:\ bei mir ohne besondere Rechte zur Verfügung steht. 
Eintrag eines anderen Ordners hat aber dann funktioniert.

**Comment by HHayen** [comment]
btW: An anderen Stellen der DB-Zugriffe wird das root-PW abgefragt. Hier wäre ebenfalls eine sofortige Fehlermeldung gut, wenn das PW falsch eingetragen ist. Ansonsten kommt es erst Minuten später nach dem jeweils gewählten Prozess zur Meldung "......" denied.

**Comment by JuergenRichter** [comment]
> Ich finde a) der Pfad sollte sinnvoll vorbelegt sein, z.B. das Schild-Arbeitsverzeichnis, wo eh alle Benutzer Schreibrechte haben müssen. 
Ist bereits umgesetzt

> b) warum ist hier das root-Passwort erforderlich?
Für bestimmte Aktionen muss eine Anmeldung beim SVWS-Server mit root-Berechnung erfolgen. Dazu zählt auch das Zurückspielen einer Datenbank, da dabei das Schema neu angelegt wird. Ob das auch ohne root-Berechtigung möglich sein soll, muss dann im SVWS-Server umgesetzt werden.

> btW: An anderen Stellen der DB-Zugriffe wird das root-PW abgefragt. Hier wäre ebenfalls eine sofortige Fehlermeldung gut, wenn das PW falsch eingetragen ist.
Werde ich prüfen.

**Comment by FPfotenhauer** [comment]
Für das Einspielen eines SQLite-Backups benötigt man keine root-Rechte (Schild-Admin reicht).
Wenn man allerdings ein neues Schema anlegen will, dann benötigt man diese!

**Comment by JuergenRichter** [comment]
Dann muss ich das beim Einspielen des SQL-Backups noch anpassen. Für folgende Operationen ist aber eine root-Berechtigung notwendig:
-Datenbank neu anlegen
-Datenbank löschen
-Datenbank aus MDB erzeugen

**Comment by kroerig** [comment]
Datenbanken neu anlegen, löschen oder migrieren, macht man ja nicht täglich.

Was aber durchaus vorkommen kann, ist, dass der Schild-Admin vor Aktionen, bei denen er sich nicht sicher ist, ob sie das gewünschte Ergebnis liefern, ein SQLite-Backup erstellt. Dieses sollte dann ohne DB-Root-Rechte möglich sein. Es wird dann ja nur das Schema geleert, aber nicht gelöscht. Richtig?

**Comment by JuergenRichter** [comment]
Ich habe jetzt nochmal nachgeschaut: Derzeit wird auch beim Import einer SQLite-Datei eine root-Berechtigung erwartet, weil SchILD3 über den folgenden Befehl prüft, ob es noch laufende Prozesse gibt, die auf die Datenbank zugreifen:

SELECT COUNT(ID) AS Anzahl FROM information_schema.processlist where db=<Schemaname>

Für diese Abfrage ist aber eine root-Berechtigung notwendig. Wenn diese Abfrage mehr als einen Prozess findet kommt folgender Hinweis:

"Es wurden ... laufende Prozesse gefunden, die auf die Datenbank zugreifen. Trotzdem fortfahren?"

Diese Prüfung ist nicht möglich, wenn kein root-Zugriff besteht.

Außerdem könnte das Zurückspielen aus der SQLite-Datei ja auch in eine andere Datenbank als die derzeit verwendete Datenbank erfolgen (für die dann aber evtl. andere Anmeldeparameter benötigt werden als die der aktuell verwendeten Datenbank). Dann müsste ebenfalls eine Anmeldung mit einem Benutzer dieser Datenbank erfolgen. 

Ich habe nun mal die Abfrage des root-Kennwortes beim Zurückspielen deaktiviert, d.h. der Vorgang wird mit dem aktuell angemeldeten Benutzer ausgeführt. Dann bekomme ich aber folgenden Fehlermeldung:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/f25e3dcf-4fdc-440b-83aa-d6a663869a67)

Wenn ich die root-Abfrage wieder aktiviere, funktioniert das Einspielen.

**Comment by JuergenRichter** [comment]
Ich habe gerade festgestellt, dass derzeit in SchILD die folgende URL aufgerufen wird (und diese habe ich auch in der SwaggerUI verwendet)

https://localhost/api/schema/root/import/sqlite/schema

Es gibt aber auch noch

https://localhost/db/schema/import/sqlite

Das ist dann wohl die richtige.

**Comment by JuergenRichter** [comment]
Ich würde folgendes vorschlagen:
Die bisherige Option "Datenbank wiederherstellen" wird wie folgt geändert:
Eine SQLite-Sicherung kann nur in die aktuelle Datenbank eingespielt werden (mit https://localhost/db/schema/import/sqlite). Außer für die Auswahl der SQLite-Datei wird keine weitere Auswahloption angeboten. Es wird keine root-Berechtigung benötigt, eine Prüfung auf andere Prozesse, die auf die Datenbank zugreifen, ist daher nicht möglich.

Es wird eine zusätzliche Option geschaffen "Datenbank importieren (aus SQLite-Datei)"
Dabei kann eine SQlite-Datei in eine beliebige vorhandene Datenbank (einschl. der aktuellen) oder in eine neue Datenbank importiert werden (entspricht also der bisherigen Option). Dazu wird eine root-Berechtigung benötigt, damit ist dann auch eine Prüfung auf laufende Prozesse möglich.

**Comment by FPfotenhauer** [comment]
Können wir so machen!

**Comment by JuergenRichter** [comment]
Sorry, habe aus Versehen den Kommentar von kroerig überschrieben. Kann man das rückgängig machen?

**Comment by JuergenRichter** [comment]
Ist nun wie oben beschrieben umgesetzt:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cf70b192-bc30-4463-9c94-8480184b23e3)

Für den Punkt "Datenbank sichern" und "Datenbank wiederherstellen" wird keine root-Anmeldung benötigt, für die anderen Punkte ist eine root-Berechtigung notwendig.

**Comment by kroerig** [comment]
> > Also ich kann dieses Query problemlos als der Datenbankbenutzer des SVWS-Servers ausführen.
> 
> Stimmt, auf die Idee war ich noch gar nicht gekommen.

Hm, ich fürchte nein. Was hatte ich denn geschrieben?

Also, einmal die Sache mit dem Query nach bestehenden Sessions für die DB, die man gerade überschreiben möchte. Das geht ohne 'root'-Rechte mit dem Datenbankbenutzer.

Von den Berechtigungen her, vergibt der SVWS beim Anlagen der Datenbank nach meiner Ansicht zu viele Rechte:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/981ba26a-e293-404d-80ce-7d7d83e29d5b)
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/8b13c496-cba3-4455-9326-db241ba234e2)

Die GRANT OPTION ist auf jeden Fall mal zuviel. Und das globle Recht selbst Benutzer anlegen zu dürfen erschließt sich mir auch nicht.

Ich stelle mir auch gerade die Frage, ob es schickt ist, die Datenbankverwaltung in dem Client zu haben oder ob es nicht bessere wäre die Funktionen in ein separates DB-Admin-Tool auszulagern. Bei ein Einzelplatzinstallation macht das keinen Unterscheid, da sind die Benutzer mit Adminrechten in SchILD vermutlich identisch dem Datenbankadmin.
Bei einer Serverinstallation aber macht es i.d.R. schon einen Unterschied. Nur weil man Admin in der Software ist bedeutet das nicht, dass man auch Admin des Servers und der Datenbank ist und mit letzterer alles machen können sollte.
Insb. dann, wenn es sich um eine gehostete Installation z.B. im städt. Rechenzentum handelt.
Wenn aber Admin-Benutzer Menüpunkte sehen, die sie als "Admin" nicht ausführen können, dann weckt das i.d.R. Begehrlichkeiten: "Ich bin Admin, ich will das können".

**Comment by FPfotenhauer** [comment]
Ein separater WebClient für diese Funktionen ist gerade in Arbeit.
Dieser kann dann nur für Datenbankadmins freigeschaltet werden.

**Comment by kroerig** [comment]
Mit den Berechtigungen, die der Benutzer hat, darf er sogar seine eigene Datenbank löschen. Mit einem SQL Client klappt das auch.

**Comment by FPfotenhauer** [comment]
Das Verhalten werden wir so akzeptieren. Die drop-Berechtigung schließt bei MariaDB das löschen des eigenen Schemas ein.
Wenn jemand mit diesem User in einen SQL-Client geht, dann muss er wissen, was er tut.
In der API fangen wir das ja ab.
