### ISSUE TITLE
Abiturreiter: Besonderheiten fehlen (Latinum usw.)

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#807]
Ich finde im Abiturreiter die Besonderheiten nicht:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/88cf2ec4-f51d-4464-81eb-dce23c5ec995)

**Comment by JuergenRichter** [comment]
Das ist jetzt auf dem Karteireiter "Laufbahninfo" bei den Sprachenfolgen. Das war extra geändert worden, damit man auch dann schon die entsprechenden Eingaben machen kann, wenn noch keine Daten in den Abiturbereich geholt wurden.

**Comment by AnneSchueller** [comment]
Ich habs gerade gesehen. 
Ich hatte das auch irgendwie im Kopf, dass wir da schonmal ein Issue zu hatten. 
Ich schließe das wieder.
