### ISSUE TITLE
Projektkursthema holen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#808]
Wenn ich keinen GP übersehen habe, ist es im Nachgang nicht möglich, das Thema des Projektkurses einzeln zu holen?
Das ist sehr ärgerlich, wenn man alle Abiturdaten eingetragen hat und feststellt, dass das Thema vom Projektkurs vergessen wurde.

Könnte man hier (und auch bei dem Abiturgruppenprozess) einen Button einbauen mit "Projektkursthema holen"?

In Schild2 gab es im Abiturreiter ein Infobutton, dass das Projektkursthema unter den Fachbezogenen Bemerkungen eingetragen werden muss. Diesen Hinweis könnte man anzeigen lassen, wenn man auch "Thema holen" klickt, dort aber kein Eintrag vermerkt ist.

**Comment by JuergenRichter** [comment]
Das Feld für das Thema des Projektkurses auf dem Karteireiter "Abitur" ist z.Zt. auf "read only" gesetzt. Eine einfache Lösung wäre natürlich, das beschreibbar zu machen.

**Comment by JuergenRichter** [comment]
Es gibt jetzt einen Schalter auf dem Karteireiter "Abitur" und einen Gruppenprozess:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/24ea97ef-fadc-4f9b-90ee-40f184137156)

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/409112cf-ee96-4b1c-8ca3-4f4d2bb2fd08)

**Comment by AnneSchueller** [comment]
Die Lösung finde ich super.
Danke für die schnelle Umsetzung
