### ISSUE TITLE
Kataloge nach Migration leer

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#809]
Mir ist gerade aufgefallen, dass die Kataloge `Erzieher-Arten`, `Fahrschüler-Arten` und `Entlassungsbemerkungen` nach einer Migration leer sind.

**Comment by FPfotenhauer** [comment]
Nach mehreren Vesuchen mit verschiedenen Datenabnken kann ich das nicht reproduzieren.

**Comment by kroerig** [comment]
Ich habe es gerade nochmal probiert. Die Masken sind leer und die Tabellen sind es auch.
MariaDB -> MariaDB

**Comment by FPfotenhauer** [comment]
Ich kann das hier nicht nachvollziehen. Kann aber in dem Schild3-Dump von Ihenn sehen, dass die Kataloge tatsächlich leer sind.
Gibt es im Migrationslog einen HInweis bei der Stelle, wo z.B. die Fahrschülerarten migriert werden?

**Comment by kroerig** [comment]
```
svws_1     |           Tabelle K_ErzieherArt:
svws_1     |             - Lese Datensätze: [FEHLER] - Kann die Datensätze nicht einlesen - Überspringe die Tabelle
svws_1     |             
svws_1     |             Tabelle K_ErzieherFunktion:
svws_1     |               - Lese Datensätze: [FEHLER] - Kann die Datensätze nicht einlesen - Überspringe die Tabelle
svws_1     |               
svws_1     |               Tabelle K_FahrschuelerArt:
svws_1     |                 - Lese Datensätze: [FEHLER] - Kann die Datensätze nicht einlesen - Überspringe die Tabelle
```
Aber warum?

**Comment by FPfotenhauer** [comment]
Gibt es einen Unterschied in den Eigenschaften der Tabellen zu den anderen Katalogen?

**Comment by kroerig** [comment]
Ich sehe keine. Soll ich nach etwas bestimmten suchen?
Würde es helfen während einer Migration mal ein Query-Log mitlaufen zu lassen? Oder kennt der SVWS einen Debugmodus, wo er die Queries protokolliert?

Aber wenn bei der Migration solche Fehler auftreten, warum meldet die Schnittstellen dann `success` und "Migration erfolgreich"?

**Comment by FPfotenhauer** [comment]
Welche Spalten hat die Tabelle K_ErzieherArt?
Bitte auch Groß/KleinSchreibung beachten.
Kann es sein, dass es hier klappt, weil ich ein Windows-System habe?
Ich kann das morgen mal unter Linux testen.

**Comment by FPfotenhauer** [comment]
Es sieht nun so aus, als wäre das ein sehr alter Fehler im MySQL-Script für Schild-NRW2.0.
Dort ist K_Erzieherart mit kleinem "a" in Access und MS-SQL ist es mit großem "A".

Kann man das ggf. von Schild2 korrigieren lassen?

**Comment by JuergenRichter** [comment]
> Dort ist K_Erzieherart mit kleinem "a" in Access und MS-SQL ist es mit großem "A".

Ich vermute, dass nicht "MS-SQL" gemeint ist, sondern "MySQL"? Ist in der SchILD2-MySQL-DB die Tabelle als "K_ErzieherArt" benannt?

> Kann man das ggf. von Schild2 korrigieren lassen

Man könnte dann in SchILD2 im Rahmen einer Anpassung einen Befehl "RENAME TABLE K_ErzieherArt ZTO K_Erzeiherart" ausführen. Würde das das Problem beheben?

**Comment by JuergenRichter** [comment]
Es muss natürlich heißen
RENAME TABLE K_ErzieherArt TO K_Erzieherart

**Comment by JuergenRichter** [comment]
Hallo Herr Wilkening,

 

ich kümmere mich kurzfristig darum. 

 

Mit freundlichen Grüßen aus Bornheim

Jürgen Richter

 

 




Wasser und Umwelt

ribeka GmbH

Johann-Philipp-Reis-Str. 9
53332 Bornheim
Tel.: +49(0)2222-990600
Fax: +49(0)2222-990601
 <http://www.ribeka.com/> www.ribeka.com



Geschäftsführer: Dr. Jürgen Richter, Erich Berger
Amtsgericht Bonn HRB 8423

 

Von: Frank Pfotenhauer ***@***.***> 
Gesendet: Dienstag, 17. Oktober 2023 09:31
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: JuergenRichter ***@***.***>; Assign ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Kataloge nach Migration leer (Issue #809)

 

Assigned #809 <https://github.com/SVWS-NRW/Schild3-BetaTest/issues/809>  to @JuergenRichter <https://github.com/JuergenRichter> .

**Comment by kroerig** [comment]
> Es muss natürlich heißen RENAME TABLE K_ErzieherArt TO K_Erzieherart

Anders herum. Das Migrationsscript sucht ja nach `K_ErzieherArt`, in Schild2 aber heißt die Tabelle `K_Erzieherart`

Ich kann die aber mal in der QuellDB anpassen.

**Comment by FPfotenhauer** [comment]
@Raffenberg Kannst du das bitte im MySQL-Script korrigirern und in der Installationsanleitung neu hochladen?
Es sind die drei Tabellen, die oben genannt werden.

**Comment by kroerig** [comment]
Das sieht besser aus:

```
    "          Tabelle K_ErzieherArt:",
    "            - Lese Datensätze: 8 Datensätze eingelesen (Freier Speicher: 0.16G/0.58G/0.6G)",
    "            - Schreibe 8 Datensätze: ",
    "              Datensätze 0-7 erfolgreich geschrieben. (Freier Speicher: 0.16G/0.58G/0.6G)",
    "            8 Datensätze geschrieben, 0 fehlerhafte Datensätze übersprungen.",
    "          Tabelle K_ErzieherFunktion:",
    "            - Lese Datensätze: 5 Datensätze eingelesen (Freier Speicher: 0.16G/0.58G/0.6G)",
    "            - Schreibe 5 Datensätze: ",
    "              Datensätze 0-4 erfolgreich geschrieben. (Freier Speicher: 0.16G/0.58G/0.6G)",
    "            5 Datensätze geschrieben, 0 fehlerhafte Datensätze übersprungen.",
    "          Tabelle K_FahrschuelerArt:",
    "            - Lese Datensätze: 9 Datensätze eingelesen (Freier Speicher: 0.16G/0.58G/0.6G)",
    "            - Schreibe 9 Datensätze: ",
    "              Datensätze 0-8 erfolgreich geschrieben. (Freier Speicher: 0.16G/0.58G/0.6G)",
    "            9 Datensätze geschrieben, 0 fehlerhafte Datensätze übersprungen.",
```

Ich sehe aber bei der Migration noch weiter Fehler. Mach dafür ein neues Issue auf.

**Comment by FPfotenhauer** [comment]
Dann wäre es schön, wenn Schild2 das korrigiert.

**Comment by FPfotenhauer** [comment]
Ja. Danke.

**Comment by kroerig** [comment]
Die weitern Fehler: https://github.com/SVWS-NRW/SVWS-Server/issues/27

**Comment by JuergenRichter** [comment]
Das scheint aber auf den ersten Blick nichts mit Tabellennamen zu tun zu haben

**Comment by kroerig** [comment]
Nein, deswegen ja neu.

**Comment by kroerig** [comment]
> Ich habe leider keine Linux-MySQL-DB hier, um zu testen, ob der Befehl funktionieren würde (evtl. gibt es ein Problem wegen eines ForeignKeys)
Ja. SchILD 2 startet nach der Änderung nicht mehr:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/ebd6d4b7-3e69-4678-bcaf-ba400a1b6094)

**Comment by JuergenRichter** [comment]
Das war zu vermuten, da die Tabelle ja umbennant wurde. Es muss nun die entsprechende Abfrage auf die geänderte Schreibweise in SchILD2 angepasst werden (unter Windows spilet das keine Rolle). Mir ging es auch nur darum, ob das Umbennen mit den SQL-Befehlen funktioniert. Ich hatte befürchtet, dass man dazu vorher evtl. einige ForeignKeys löschen müsste (und diese anschließen wieder aufbauen müsste), das scheint aber nicht der Fall zu sein.

**Comment by kroerig** [comment]
Also ich hatte beim Umbennen über DBeaver jetzt keine Fehlermeldung und der führte auch nur das SQL Statement aus.
Wann haben Sie die Anpassungen in SchILD 2 drin? Dann kann ich damit gegentesten.

**Comment by AnneSchueller** [comment]
Wie sieht es mit diesen Tabellen aus?

K_Adressart --> K_AdressArt
K_Beschaeftigungsart--> K_BeschaeftigungsArt
K_Einschulungsart --> K_EinschulungsArt 
K_Entlassgrund--> K_EntlassGrund
K_KlassenOrgform --> K_KlassenOrgForm
K_Telefonart -->K_TelefonArt
K_Vermerkart --> K_VermerkArt

Auch diese unterscheiden sich in der Groß- und Kleinschreibung von den Tabellen meiner MDBs

**Comment by kroerig** [comment]
Ich verstehe eh nicht, warum man in normale Wörter einen Großbuchstaben einbaut. Bei zusammengesetzten oder gekürzten  Begriffen wie `KlassenOrgForm` OK, aber `Entlassgrund` ist anschließend.

Diese Tabellen sind mir zwar im Log nicht aufgefallen, aber ja: K_Entlassgrund hat in der Quelle Daten, im Ziel aber nicht. Ich schaue mal nach, ob das Log hier auch Fehler meldet.

**Comment by kroerig** [comment]
So, die Meldung `Lese Datensätze: [FEHLER] - Kann die Datensätze nicht einlesen - Überspringe die Tabelle` erhalte ich bei folgenden Tabellen (in der Reihenfolge des Logs):

K_BeschaeftigungsArt
K_EinschulungsArt
K_EntlassGrund
K_TelefonArt
K_BeschaeftigungsArt
K_EinschulungsArt
K_EntlassGrund
K_TelefonArt

Kein Fehler bei
K_Vermerkart

Ich benenne die o.g. auch mal um. Danke @AnneSchueller

**Comment by kroerig** [comment]
> Es sieht nun so aus, als wäre das ein sehr alter Fehler im MySQL-Script für Schild-NRW2.0. Dort ist K_Erzieherart mit kleinem "a" in Access und MS-SQL ist es mit großem "A".
> 
> Kann man das ggf. von Schild2 korrigieren lassen?

Ist das so geschickt, das jetzt in Schild2 zu korrigeren? Welche Auswirkungen hat das noch? Reports, Datenex- und importe.
Wäre es nicht vllt. geschickt, jetzt da wir wissen welche Tabellen es betritt, das bei der Migration abzufangen?

btw: Wer außer mir betreibt und testet die Datenbank(migration) eigentlich unter Linux?

**Comment by JuergenRichter** [comment]
Sin die folgenden Befehle dann vollständig?

RENAME TABLE K_Erzieherart TO K_ErzieherArt
RENAME TABLE K_ErzieherFunktion TO K_ErzieherFunktion
RENAME TABLE K_Fahrschuelerart TO K_FahrschuelerArt
RENAME TABLE K_Beschaeftigungsart TO K_BeschaeftigungsArt
RENAME TABLE K_Einschulungsart To K_EinschulungsArt
RENAME TABLE K_Entlassgrund TO K_EntlassGrund
RENAME TABLE K_Telefonart TO K_TelefonArt
RENAME TABLE K_Beschaeftigungsart TO K_BeschaeftigungsArt

**Comment by AnneSchueller** [comment]
Mich wundert es, dass keine Fehlermeldung kommt beim Lesen von Daten aus 
K_Vermerkart
K_Adressart

Diese beiden Spalten sind im neuen Script ebenfalls angepasst. Also:
RENAME TABLE K_Vermerkart To K_VermerkArt
RENAME TABLE K_Adressart To K_AdressArt

Hier ist noch ein Schreibfehler:
RENAME TABLE K_ErzieherFunktion TO K_ErzieherFunktion
-->
RENAME TABLE K_Erzieherfunktion TO K_ErzieherFunktion

**Comment by FPfotenhauer** [comment]
K_Vermerkart
K_Adressart

Werden bei uns so geschrieben.
Das könnte "knallen" wenn man das ändert.

**Comment by FPfotenhauer** [comment]
Nach Rücksprache bitte K_Vermerkart und K_Adressart nicht ändert!

**Comment by kroerig** [comment]
Also ich wäre dafür die Tabellen in SchiLD2 jetzt so zulassen und die "Lesefehler" im Migrationsscript abzufangen. Wenn das Script feststellt, dass es `K_ErzieherArt` nicht lesen kann, dann muss es einen zweiten Versuch mit `K_Erzieherart` starten und **abbrechen**, wenn ein Import nicht funktioniert und nicht einfach überspringen.
Mir sind die leeren Felder in SchILD3 ja auch nur per Zufall aufgefallen.

Es sei dann @JuergenRichter kann ausschließen dass durch eine Änderung der Tabellennamen in Schild2 in den Schulen jetzt irgendwas komplett gegen die Wand fährt, weil danach z.B. Reports nicht mehr funktionieren. Nicht nur die, die SchILD mitliefert, sondern auch eigene.

**Comment by FPfotenhauer** [comment]
Wir können das momentan nicht dynamisch erfassen.
Bitte alle Kataloge mit Schild2 anpassen. 
Die beiden Ausnahmen K_Vermerkart und K_Adressart nicht!
Diese Unstimmigkeit können wir später angehen, wenn die DBs migriert sind.

@JuergenRichter Wenn wir eine Schild2-Version bekommen, können wir das ja an unseren DBs testen.
@Raffenberg Falls du diese beiden Kataloge im Script angepasst hast, diese bitte rückgängig machen.

**Comment by Raffenberg** [comment]
Ist im Script wieder entsprechend korrigiert.

**Comment by JuergenRichter** [comment]
Ich habe sowohl die RENAME TABLE-Befehle als auch die weiteren notwendigen Anpassungen umgesetzt. Die entsprechende Programmversion wird in Kürze zur Verfügung gstellt. Da ich keine MySQL-DB unter Linux habe, kann ich das aber selbst nicht testen.

**Comment by kroerig** [comment]
@JuergenRichter Wenn Sie mir das Update vorab geben, kann ich das bei mir mal installieren.
Sie müssten mir nur sagen, welche Schritte ich testen muss.

**Comment by JuergenRichter** [comment]
Testversion liegt hier:
www.download.ribeka.com/Software/SchILD/Schild-NRW/SCHILD2000.zip

Bei mir (unter Windows) gab es aber eine Fehlermeldung beim Umbenennen:
z.B.
RENAME TABLE K_Erzieherart TO K_ErzieherArt
Da kam der Fehler, dass "k_erzieherart" schon existiert. 

Da ich nicht einschätzen kann, ob das ein Windows-Problem ist der ob der ODBC-Treiber (über den ja die Verbindung hergestellt wird) da irgendwie reinfunkt, habe ich das nun bei allen Tabellen wie folgt gelöst (wieder Beispiel)
RENAME TABLE K_Erzieherart TO _K_ErzieherArt
RENAME TABLE _K_ErzieherArt TO K_ErzieherArt

Damit hat es dann funktioniert.

Zum Testen muss man nur das Programm starten, dass sollte der Hinweis kommen, dass neue Tabellen und Felder angelegt werden. Wenn anschließend das Programm ohne Fehler bis zum Hauptfenster durchläuft, sollte alles in Ordnung sein.

**Comment by kroerig** [comment]
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/c18041da-e367-4901-8a33-3012a96d4ff0)
Da ist wohl noch was falsch.

**Comment by kroerig** [comment]
> Bei mir (unter Windows) gab es aber eine Fehlermeldung beim Umbenennen:
> z.B.
> RENAME TABLE K_Erzieherart TO K_ErzieherArt
> Da kam der Fehler, dass "k_erzieherart" schon existiert.

Ja, weil Windows im Dateisystem nicht zwischen Groß- und Kleinschreibung wirklich unterscheidet.

**Comment by JuergenRichter** [comment]
> Da ist wohl noch was falsch.

Da habe ich wohl eine Stelle übersehen. Morgen kommt eine neue Version.

**Comment by kroerig** [comment]
Sie könnten auch z.B. mit einem `select @@version_compile_os;` abfragen, ob es sich um eine Linux-Installation handelt und die Änderungen nur dann ausführen.

| @@version_compile_os |
|----------------------|
| debian-linux-gnu     |

1 row in set (0,001 sec)

Und die _K_ Tabellen müssten noch wieder weg.

**Comment by JuergenRichter** [comment]
> RENAME TABLE K_Erzieherart TO K_ErzieherArt

Danke, probiere ich aus

**Comment by JuergenRichter** [comment]
> > Zum Testen muss man nur das Programm starten, dann sollte der Hinweis kommen, dass neue Tabellen und Felder angelegt werden. Wenn anschließend das Programm ohne Fehler bis zum Hauptfenster durchläuft, sollte alles in Ordnung sein.
> 
> Später kann da nichts mehr kommen? Was ist mit Reports, die auf diese Tabellen zugreifen? Und LuPO und Kurs42 Importe?

LuPO benutzt die Tabelle nicht, Kurs42 vermutlich auch nicht. In den Reportdatenquellen sollten eigentlich auch alle Namen ersetzt worden sein. Wenn die Tabellen aber in Reports mit eigenen Datenquellen verwendet werden (ist mir aber bisher nicht aufgefallen) muss die betreffende Abfrage angepasst werden.

**Comment by JuergenRichter** [comment]
Können Sie mal das Fehlerprotokoll hier ablegen?

**Comment by kroerig** [comment]
Kurs42 kam mir nur in den Sinn, weil sich das auch schon wegen der Groß- Kleinschreibung schwungvoll auf die Nase gelegt hat. Finde nur gerade den Eintrag im Forum nicht wieder.

**Comment by kroerig** [comment]
> Können Sie mal das Fehlerprotokoll hier ablegen?

Ich komme den Fehler nicht mehr...

**Comment by kroerig** [comment]
ah, Moment. Der Dump löscht beim Import nicht alles weg.

**Comment by kroerig** [comment]
So, mit frischer Datenbank-Kopie:

```
EurekaLog 6.1.04

Application:
---------------------------------------------------------------------------
  1.1 Start Date      : Mon, 23 Oct 2023 20:59:46 +0200
  1.2 Name/Description: SCHILD2000.exe - (Schulverwaltungsprogramm für NRW)
  1.3 Version Number  : 2.0.31.2
  1.4 Parameters      : 
  1.5 Compilation Date: Mon, 23 Oct 2023 17:42:33 +0200
  1.6 Up Time         : 25 seconds

Exception:
------------------------------------------------------------------------------------------------------------------------------------------------------
  2.1 Date          : Mon, 23 Oct 2023 21:00:11 +0200
  2.2 Address       : 007199F6
  2.3 Module Name   : SCHILD2000.exe - (Schulverwaltungsprogramm für NRW)
  2.4 Module Version: 2.0.31.2
  2.5 Type          : EOleException
  2.6 Message       : [MySQL][ODBC 5.1 Driver][mysqld-5.5.5-10.6.12-MariaDB-0ubuntu0.22.04.1]Table 'schild_nrw_test.K_Erzieherfunktion' doesn't exist.
  2.7 ID            : 7C86
  2.8 Count         : 1
  2.9 Status        : New
  2.10 Note         : 

Active Controls:
---------------------------------
  4.1 Form Class   : TApplication
  4.2 Form Text    : SchILD-NRW
  4.3 Control Class: TApplication
  4.4 Control Text : 

Operating System:
----------------------------------------------
  6.1 Type    : Microsoft Windows 6.2 (64 bit)
  6.2 Build # : 9200
  6.3 Update  : 
  6.4 Language: German
  6.5 Charset : 0
```

**Comment by JuergenRichter** [comment]
Das ist leider nicht das ganze Protokoll. Bitte wie folgt vorgehen:
-Wenn die Fehlermeldungerscheit, das Häkchen "Copy to clipboard" aktivieren, dann den Schalter "Details"  
-Dan wird das Protokoll in die Zwischenablage kopiert, diese per Strg-V in einer Texdatei speichern und hier hochladen.

Ich werde allerdings in Kürze  eine Version mit der von Ihnen beschriebenen OS-Kontrolle hochladen. Da entfällt dann das Umbenennen mit dem vorgestellten "_".

**Comment by JuergenRichter** [comment]
So, aktualisierte Programmdatei liegt bereit:
www.download.ribeka.com/Software/SchILD/Schild-NRW/SCHILD2000.zip

**Comment by kroerig** [comment]
[EurekaLog 6.1.04.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13113767/EurekaLog.6.1.04.txt)

Gleicher Fehler wie oben: `Table 'schild_nrw_test.K_Erzieherfunktion' doesn't exist.`

Das Umbenennen in der DB hat funktioniert:
```

K_Adressart
K_AllgAdresse
K_Ankreuzdaten
K_Ankreuzfloskeln
K_BeschaeftigungsArt
K_Datenschutz
K_EinschulungsArt
K_Einzelleistungen
K_EntlassGrund
K_ErzieherArt
K_ErzieherFunktion
K_FahrschuelerArt
K_Foerderschwerpunkt
K_Haltestelle
K_Kindergarten
K_KlassenOrgform
K_Lehrer
K_Ort
K_Ortsteil
K_Religion
K_Schule
K_Schulfunktionen
K_Schwerpunkt
K_Sportbefreiung
K_Staat
K_TelefonArt
K_Verkehrssprachen
K_Vermerkart
K_Zertifikate
```

**Comment by kroerig** [comment]
> Wenn die Tabellen aber in Reports mit eigenen Datenquellen verwendet werden (ist mir aber bisher nicht aufgefallen) muss die betreffende Abfrage angepasst werden.

Das muss aber **dick und fett** in den Release-Notes stehen (die eh keiner liest), sonst läuft das Forum heiß.

**Comment by kroerig** [comment]
> Sie könnten auch z.B. mit einem `select @@version_compile_os;` abfragen, ob es sich um eine Linux-Installation handelt und die Änderungen nur dann ausführen.
> @@version_compile_os
> debian-linux-gnu
> 
> 1 row in set (0,001 sec)
> 
Der Rückgabewert muss nicht immer genau diesem entspechen. Das ist jetzt ein Ubuntu Linux. Unter SuSE oder CentOS kann der anders aussehen. Aber das Wort "Linux" bzw. "linux" sollte enthalten sein.

**Comment by JuergenRichter** [comment]
Genau so mache ich es, wenn das Ergebnis nicht mit "Win" beginnt (Groß-/Kleinschreibung wird ignoriert) wird Linux angenommen.

Ich habe den Fehler jetzt auch gefunden. Es gab eine Abfrage in einem Formular, wo im Tabellenname ein Umbruch war. Das wurde dann beim Suchen nach "K_Erzieherfunktion" nicht gefunden.

      'SELECT SF.ID, KF.Bezeichnung'#13#10'FROM SchuelerErzFunktion SF, K_Erz' +
      'ieherfunktion KF'#13#10'WHERE KF.ID=SF.Funktion_ID AND'#13#10'SF.Person=1 AN' +
      'D SF.Erzieher_ID=:ID'

Aktualisierte Datei folgt in Kürze.

**Comment by JuergenRichter** [comment]
www.download.ribeka.com/Software/SchILD/Schild-NRW/SCHILD2000.zip

**Comment by kroerig** [comment]
So, Schild startet ohne Fehler. Die Kataloge lassen sich auch öffnen.

**Comment by kroerig** [comment]
Ich habe die von SchILD2 angepasst Datenbank gerade mal nach SchILD3 migriert. Der Prozess lief fehlerfrei durch und die Daten in den Katalogen sind auch alle da.

Allerdings kommt beim Start von SchiLD2 jetzt jedes Mal die Meldung:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/133c77c8-e6b1-4f69-8216-8b04f9f13b54)

**Comment by JuergenRichter** [comment]
Ist behoben

**Comment by kroerig** [comment]
Dann kann diese Version vermutlich an die Anwender raus.
Sind da noch inhaltliche Änderungen enthalten oder nur diese Sache?

**Comment by kroerig** [comment]
Wann steht die neue Schild2 Version zum allgemeinen Download bereit?

**Comment by JuergenRichter** [comment]
Voraussichtlich morgen.
