### ISSUE TITLE
Die Funktion Rücktritt scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by hagege** [SVWS-NRW/Schild3-BetaTest#81]
SchILD Version 3.0.10.3
Wenn man bei einem Schüler auf das Icon "Rücktritt" klickt, erscheint zwar nach der Abfrage "Rücktritt ausführen?" der Dialog zur Eingabe der Klasse. Wenn man die nachfolgende Bestätigung "Rücktritt ausgeführt..." mit Klick auf OK bestätigt, erscheint der Schüler weiterhin in der vorherigen Klasse.

**Comment by JuergenRichter** [comment]
Ist in 3.0.10 behoben.
Es lag am Feld "Entlassdatum", das wird beim Wechsel in das Feld "Wechseldateum von letzter Schule" eingetragen. Wenn "Entlassdatum" leer war, kam es zu dem beschriebenen Problem. Access hat ein leeres Datumsfeld wohl akzeptiert, MariaDB aber nicht.
