### ISSUE TITLE
Datenbank: Anzahl der Abschnitte und Jahrgangsstufen pro Jahr

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#810]
Wir lassen ja nach der Migration nur noch Halbjahresbetrieb zu.
Das Feld Anzahl der Abschnitte würde ich dann gerne als "depricated" markieren.
Können Sie bitte einmal prüfen, ob das im Code sehr oft vorkommt und ob wir das einfach auf "2" setzen können.

Es gibt auch zusätzlich das Feld "Anzahl der Jahrgangsstufen pro Jahr".
Wo wird das verwendet? Und wozu ist das eingeführt worden. Falls das benötigt wird, würden wir das gerne dokumentieren wozu.

**Comment by JuergenRichter** [comment]
Das Feld "Anzahl der Jahrgangsstufen pro Jahr" wird für WBKs benötigt (diese haben dort einen Wert von 2 ). Die haben ja einen Semesterbetrieb, jeder Abschnittswechsel hat dann auch einen Jahrgangswechsel zur Folge. Falls ausnahmslos alle WBKs so arbeiten aber keine anderen Schulen (weiß ich aber nicht), könnte man das Feld auch entfernen, dann wird die interne Variable bei den WBKs auf 2 gesetzt, sonst auf 1.

**Comment by JuergenRichter** [comment]
> Können Sie bitte einmal prüfen, ob das im Code sehr oft vorkommt und ob wir das einfach auf "2" setzen können.

Das dürfte vermutlich nur an einer Stelle verwendet werden, nämlich dann, wenn die entsprechende Eigenschaft beim "Schulobjekt" befüllt wird. Da kann man das dann einfach auf 2 setzen. Wird im nächsten Update umgesetzt.

**Comment by Kluesenerm** [comment]
Hallo zusammen,
ich habe einmal bei einigen WBKs nachgefragt, ob es dort einen "Quartalsbetrieb" gibt. Quartalsbetrieb gibt es nicht. 

Wir haben folgende Einstellungen bei uns (siehe Bild):
![image004](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/8130fcdd-1115-4ec7-bcf1-acb0770068c1)

Anzahl Jahrgangsstufen pro Jahr: 2
Anzahl Abschnitte pro Jahrgangsstufe: 1

Nach jedem Semester (Halbjahr) findet bei uns ein Versetzungsdurchgang statt. Also ein Schuljahreswechsel von Wintersemester auf Sommersemester u.s.w.

Gegen eine "harte" Kodierung würde ich mich auch aussprechen.

**Comment by FPfotenhauer** [comment]
Ich habe dann jetzt von wirklich vielen Schulen, die Rückmeldung, dass es immer ein Schuljahr und zwei Abschnitte gibt.
Was soll denn da jetzt noch einstellbar sein? Und vor allem wozu?

**Comment by FrodBRA** [comment]
Und über (vermeintlichen?) Nutzen hinaus wäre auch gegenüberzustellen: Welche neuen Probleme werden durch die Konfigurierbarkeit erzeugt?

**Comment by JuergenRichter** [comment]
Sollen die Felder (bzw. Eingabemöglichkeiten) weg?

**Comment by FPfotenhauer** [comment]
Bitte erstmal "ausgrauen".
