### ISSUE TITLE
Wunsch: Versionsnummer in Programm- oder Statuszeile anzeigen

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#811]
Um schnell mal eben die installierte Version herauszufinden, wäre es hilfreich, wenn diese auf einen Blick ersichtlich ist.
So muss man immer erst auf "Verwaltung" klicken und ggf. vorher noch ein paar Fenster schließen, bis man das auch darf.

**Comment by AnneSchueller** [comment]
Da auch nicht wöchentlich neue Update kommen, muss das m.E. nicht zwingend direkt ersichtlich sein. Beim Starten von SchILD3 wird übrigens auch immer die Versionsnummer angezeigt.
Ich schließe das Issue erstmal. Evtl. kann man das mal zu einem späteren Zeitpunkt einbauen.
