### ISSUE TITLE
Verbesserungsvorschlag: Gruppenprozesse - Individualdaten ändern - Sortierung der Schuljahre umkehren

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#812]
Im Bereich "Individualdaten I" des GPs "Individualdaten ändern" sind im Pulldownmenü "Schuljahr" die Werte nach Jahren aufsteigend sortiert (siehe Screenshot). Da in der Regel mit dem aktuellen oder dem kommenden Abschnitt gearbeitet wird, sollte die Sortierung umgekehrt werden.   

![Schuljahr_Sortierung](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/f4da2c8a-d455-439c-a81c-8ad2632b9a66)

**Comment by kroerig** [comment]
Bei längeren Listen wäre es hilfreich, wenn man diese im Dropdown durchsuchen könnte:
Also, man kann in ein Suchfeld am oberen Rand tippen und die Liste reduziert sich auf die passenden Einträge.

**Comment by JuergenRichter** [comment]
Ich habe die Sortierung jetzt in folgenden Fällen auf "desc" geändert:
-Karteireiter "Akt. Halbjahr"
-"Schülerfilter" (ehemals Filter I)
-Gruppenprozess "Individualdaten ändern"
-Klassen-Bearbeitung (Auswahlliste)

Wenn noch jemandem weitere Punkte auffallen, bitte melden

**Comment by AnneSchueller** [comment]
Zum Suchfeld: 
bei den meisten Dropdown Listen springt man automatisch an die entsprechende Position, sobald man den Anfangsbuchstaben eingibt. Die Schulen wissen ja, was in den einzelnen Feldern eingegeben werden soll, sodass weitere Suchfelder m.E. überflüssig wären.
