### ISSUE TITLE
Datenbank Sicherungen: Standardverzeichnis liegt im Server-Daten-Verzeichnis, es sollte besser im SVWS-Arbeitsverzeichnis liegen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#814]
Version 3.0.76.11

Derzeit werden bei nicht gesetzten Verzeichnis für Sicherungen diese im "SVWS-Server-Daten-Verzeichnis\temp\" abgelegt.

Auf dieses Verzeichnis soll nach meinen Verständnis für die normalen Nutzer von SchILD - auch Admins - kein Windows-Zugriff bestehen.

Ich schlage daher vor, dass Sicherungen als Standard im Ordner "[SVWS-Arbeitsverzeichnis]\Sicherungen" abgelegt werden. Zumindest sofern nichts dagegen spricht, dass die Datenbanken - wenn auch verschlüsselt - wieder "normalen" Nutzern zugänglich werden.

**Comment by AnneSchueller** [comment]
Meinst du die normale DB-Sicherung unter Verwaltung/Datenbank/Sichern?
Bei mir funktioniert das nur, wenn ich selbst vorher ein Verzeichnis angebe, in dem das gespeichert werden soll.

**Comment by FrodBRA** [comment]
Ja, bei mir war der String leer - und dann wurde wie geschrieben in besagtes Verzeichnis geschrieben.

Aber wie dem auch sei: In dieses Verzeichnis gehören Daten, die von (manchen) Nutzern genutzt werden sollen, nicht unbedingt. Der Standard sollte auch so auf das SVWS-Arbeitsverzeichnis zeigen.

**Comment by JuergenRichter** [comment]
"Derzeit werden bei nicht gesetzten Verzeichnis für Sicherungen diese im "SVWS-Server-Daten-Verzeichnis\temp" abgelegt."

Das "kommt" nicht von SchILD, das "SVWS-Server-Daten-Verzeichnis" kennt SchILD überhaupt nicht. Ich ich vermute aber, dass das vom SVWS-Server selbst kommt (die Sicherung läuft ja über den SVWS-Server). Wenn der kein Verzeichnis genannt bekommt, nimmt er halt dieses. 
SchILD prüft nun beim Start, ob ein gültiges Verzeichnis bei den Einstellungen eingetragen ist, wenn keines oder ein ungültiges gefunden wird, erfolgt die Sicherung in den Unterordner \Sicherungen im Arbeistverzeichnis.
