### ISSUE TITLE
Verwaltung - Halbjahreswechsel - Abschnittswechsel - Text ragt über den Rand 

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#815]
Version: 3.0.75.10
Auflösung: QHD

Im Menü _Verwaltung - Halbjahreswechsel - Abschnittswechsel_  ragt der Text bei Punkt 5 über den unteren Rand des Panels (siehe auch #697).

![Abschnittswechsel](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/a263e739-d455-4133-a0e3-5140464ddce5)

**Comment by AnneSchueller** [comment]
Kannst du das Fenster denn noch vergrößern? 
Bei meiner Ansicht ist das ganz drauf. Welche Bildschirmgröße hast du?

**Comment by pemichalski** [comment]
Version: 3.0.76.11
Auflösung: QHD, WQHD

@AnneSchueller Ich habe es auf einem 34 Zoll WQHD und einem 27 Zoll QHD Monitor getestet. 
Wenn ich das Fenster vergrößere passt alles. 

Dabei ist mir aufgefallen, dass der Text in der darunterliegenden Komponente sichtbar ist (siehe Screenshot unten). Kann man das ändern?
Und kann man die Größe des Fensters per Default so setzen, dass der komplette Text ab Full HD angezeigt wird?

![Abschnittswechsel_Komponente](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/d31fd81f-ffff-4b30-bff9-29a7384316b8)
