### ISSUE TITLE
Verbesserungsvorschlag - Menügruppe "Suchen, filtern und sortieren" im Reiter Gruppenprozesse   

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#816]
Ist es möglich, im Reiter Gruppenprozesse die Menügruppe "Suchen, filtern und sortieren" oder zumindest die Buttons "Filter auf markierte Schüler setzen", "Filter auf markierte Schüler aufheben" und "Standard-Auswahl" anzeigen zu lassen? In diesem Fall muss man nicht in Kartenreiter Schüler zurück wechseln, wenn man einen Fehler bei der Auswahl der Gruppe gemacht hat und diesen korrigieren will, wodurch die Bedienung wesentlich komfortabler wird.

**Comment by AnneSchueller** [comment]
Das ist mir auch schon an einigen Stellen aufgefallen, dass man in manchen Situationen die Reiter wechseln muss, um Einstellungen zu tätigen, die in Schild2 direkt auswählbar waren.
Aber die Frage wäre, welches Feature ist so wichtig, dass es dort auf dem Reiter Gruppenprozess auftauchen darf und welches nicht. 

Ich würde davon jetzt erstmal absehen.

**Comment by JuergenRichter** [comment]
Prüfe ich, sollte aber machbar sein.
