### ISSUE TITLE
Verwaltung - Verwaltung - Schule - Allgemeine Angaben - Text abgeschnitten

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#818]
Version: 3.0.76.11
Auflösung: QHD, WQHD  

Im Bereich _Verwaltung - Verwaltung - Schule - Allgemeine Angaben_  ist der Text unter dem Feld Web-Adresse bei sämtlichen Skalierungen (ausprobiert für 100% bis 200%) abgeschnitten.

![Verwaltung_Text_abgeschnitten](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/51b5658f-9287-4614-b832-c16914895fc0)

**Comment by AnneSchueller** [comment]
Ich kann das bei mir nicht reproduzieren. 
@JuergenRichter: Woran kann das liegen? Können hierfür noch veraltete Registry-Einträge Ursache sein?

**Comment by pemichalski** [comment]
> Ich kann das bei mir nicht reproduzieren. 

@AnneSchueller Mit welcher Auflösung arbeitest du?

**Comment by AnneSchueller** [comment]
Auflösung FullHD, Skalierung 100 %, Format 21:9

**Comment by FrodBRA** [comment]
Ist bei mir auch so. 4k (3840x2160), Skalierung 150%.

**Comment by pemichalski** [comment]
@AnneSchueller Dann tritt der Fehler bei Auflösungen größer als FullHD (1920x1080) auf. 
@Felix: bei 2k (WQHD und QHD) ist der Text bei sämtlichen Skalierungen abgeschnitten.

**Comment by AnneSchueller** [comment]
@JuergenRichter : Könnten Sie das nochmal prüfen?
Ähnliches Problem wurde hier beschrieben: https (Textüberlappung im Hochschulfenster)://github.com/SVWS-NRW/Schild3-BetaTest/issues/815

**Comment by JuergenRichter** [comment]
Ich habe da jetzt mehr Platz bereitgestellt. Bitte in der nächsten Version mal testen.
