### ISSUE TITLE
Überflüssige DB Felder

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#819]
Zur Zeit haben wir die folgenden Felder sowohl in K_Lehrer als auch in LehrerAbschnittsdaten:

    Rechtsverhaeltnis
    Beschaeftigungsart
    Einsatzstatus
    PflichtstdSoll
    UnterrichtsStd
    MehrleistungStd
    EntlastungStd
    AnrechnungStd
    RestStd

Kannst du mir sagen, ob diese Felder in K_Lehrer noch genutzt werden oder ggf. auch entfernt werden können, da sie Abschnittsweise gespeichert werden?

Eine weitere Frage: Die folgenden Felder können vermutlich entfernt werden, oder? Sie sind zumindest als Deprecated beschrieben...

    SchILDweb_FL
    SchILDweb_KL
    SchILDweb_Config
    KennwortTools
    Antwort1
    Antwort2
    KennwortToolsAktuell

Und wie sieht es mit den XNM-Feldern aus? (Also werden die noch für etwas anderes benötigt als XNM?)

    XNMPassword
    XNMPassword2

Und mit dem GS-Modul?

    LPassword
    PWAktuell

**Comment by JuergenRichter** [comment]
Zu den "Lehrerfeldern":
Diese werden z.Zt. noch verwendet. Sie stellen den jeweils "aktuellen" Zustand dar, werden bei Aktualisierung in der "Abschnittsfeldern" des akt. Abschnittes auf die "Stammdaten" (in K_Lehrer) übertragen. Grund ist, dass es Reports gibt, die auf diese Felder (bei K_Lehrer) zugreifen. Das könnte aber auch durch berechnete Felder (wie es derzeit bei den Schülerdaten auch schon gemacht wird) ersetzt werden. Ich werde die besagten Felder aus dem Programmcode rausnehmen und durch berechnete ersetzen.

**Comment by FPfotenhauer** [comment]
Was ist denn mit den anderen Feldern?
Wir würden gerne so viel wie möglich aufräumen.

**Comment by kroerig** [comment]
Sind die nicht auch z.T. für die Statistik über ASDPC relevant?

Ich erinnere mich, dass ich jahrelang gepredigt habe, dass die Stammdaten der Lehrer sauber in SchILD und Untis gepflegt werden sollen damit man nachher in ASDPC nicht alles von Hand nacharbeiten muss.

**Comment by JuergenRichter** [comment]
Die Daten werden für die Statistik aus der Tabelle "LehrerAbschnittsdaten" geholt. Da sollen die Felder ja auch verbleiben, sie sollen nur aus der Tabelle K_Lehrer raus.

Ich habe die Felder "Rechstverhaeltnis" bis "RestStd" (Tabelle K_Lehrer) im Code entfernt. Testweise habe ich die Felder dann auch in einer Datenbank gelöscht, bei den ersten Tests mit dieser Datenbank sind keine Fehler aufgetreten.

**Comment by JuergenRichter** [comment]
Zu den folgenden Feldern:

`SchILDweb_FL
SchILDweb_KL
SchILDweb_Config
Antwort1
Antwort2`

Diese werden nicht mehr verwendet.

Die beiden Felder 
`KennwortTools
KennwortToolsAktuell`

werden aber noch verwendet, dort wird das Kennwort (Feld KennwortTools) für das GS-Modul gespeichert. Das Feld "KennwortToolsAktuell" speichert, ob das Kennwort das  (vom Programm generierte) Initialkennwort ist, oder ob es sich schon um ein vom Benutzer individuell eingegebenes Kennwort handelt.

Zu den Feldern

`XNMPassword
XNMPassword2`

müsste sich Herr Blomeyer äußern.

Die Felder

`LPassword
PWAktuell`

werden nicht verwendet.

**Comment by kroerig** [comment]
> Zu den Feldern
> 
> `XNMPassword XNMPassword2`
> 
> müsste sich Herr Blomeyer äußern.

Da wir hier XNM nutzen habe ich mal einen Blick in die Datenbank geworden. Es stehen Werte in den Feldern.

**Comment by FPfotenhauer** [comment]
Ja, aber XNM wird in Schild3 nicht mehr zur Verfügung stehen, deshalb können wir die Felder herausnehmen.

**Comment by ThomasBachran** [comment]
Dann bleiben also `KennwortTools` und `KennwortToolsAktuell` bestehen.
