### ISSUE TITLE
Neuaufnahme mit großen Problemen

### ISSUE THREAD

**Issue by WLey-49** [SVWS-NRW/Schild3-BetaTest#82]
1. Bei den Neuaufnahmen springt der Cursor nach TAB-Eingabe "wild" über die Eingabefelder.
2. Entlassjahrgang kann nicht eingegeben werden
3. 
![Entlassjahrgang](https://user-images.githubusercontent.com/62895389/107145450-c8590500-6941-11eb-8556-dd3381c4675a.JPG)

3. Nach Wechsel auf Karteikarte "Akt. Halbjahr" kommt folgende Fehlermeldung bzgl. Speicherung:

![Speicherung](https://user-images.githubusercontent.com/62895389/107145462-de66c580-6941-11eb-80c0-951fa2af1a2c.JPG)

**Comment by JuergenRichter** [comment]
Die Tab-Reihenfolge wurde in Version 3.0.10 auf allen Karteireitern überprüft und korrigiert. Der Fehler "Jahrgang wurde nicht gefunden" ist auch behoben. Der Fehler "Bildungsgang" doesn't have a default value" liegt daran, dass diese Feld noch im Datenbankschema enthalten ist, aber durch SchILD (da nicht mehr benötigt) nicht befüllt wird. Wenn man das Feld manuell aus dem Schema entfernt, tritt der Fehler nicht mehr auf. Für die Anpassung des DB-Schemas wird aber eine neue Version des svws-Servers benötigt.

Noch ein Hinweis zur Dateneingabe: Ab der Version 3.0.10 erfolgt die Eingabe von Adressen immer so, dass zuerst der Ort (bzw. die PLZ) eingegeben wird, erst dann die Straße. Grund ist, dass demnächst alle Straßen in NRW als Katalog zur Verfügung stehen werden. Da aber Straßennamen in vielen Fällen mehrfach vorkommen (Beispiel "Aachener Str." kommt in NRW über 40 mal vor) muss der Katalog für die Auswahl auf die betreffende Kommune gefiltert werden, daher muss diese vor der Straßenauswahl eingegeben werden.
An folgenden Stellen wird das relevant sein:
Schüleradressen
Adressen von Erziehungsberechtigten
Lehreradressen
Betreibsadressen

**Comment by FPfotenhauer** [comment]
Das Feld Bildungsgang ist in der aktuellen SVWS-Server-Version 0.0.35 nicht mehr enthalten.
Es kann höchstens sein, dass das Schema mit einer alten Version erzeugt wurde und keine neue Migration gemacht wurde.
