### ISSUE TITLE
Teilleistungen funktionieren nicht richtig!

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#820]
Version 3.0.76.11
SVWS 0.7.5

In meiner Datenbank besteht ein Problem mit Teilleistungen:

- Das Feld "Teilleistungen" ist mitunter gesperrt "Bearbeitung nicht möglich" und ich weiß nicht warum. 
- Dann geht es bei Schülern doch, bei denen es vorher nicht ging. Ich kann Teilleistungen anlegen, aber auch nicht in allen Fächern.
- Wenn obiges geht, ist die Kopfzeile des Teilleistungsfeld, das mit "+" und "-" usw. ausgegraut und die Schaltflächen sind nicht bedienbar. In der Kopfzeile der TL-Box steht aber "TL anlegen und bearbeiten", was durch ein Klick in die Felder möglich ist. Da das "-" ausgegraut ist, kann ich keine TL entfernen.
- Das Hinzufügen von TL per Gruppenprozess funktioniert nicht. Sowohl der GP "Aus Vorlage zuweisen" wie auch "Individuell zuweisen" laufen durch, aber ohne dass in den Leistungsdaten die TL eingetragen werden (wie oben geschrieben: bei manchen Fächern scheint das zu gehen, aber nicht konsistent).

**Comment by JuergenRichter** [comment]
"Das Feld "Teilleistungen" ist mitunter gesperrt "Bearbeitung nicht möglich" und ich weiß nicht warum."

Welche Berechtigungen hat der jeweilige SchILD-Benutzer:
-Klassenlehrer?
-Fachlehrer?
-Admin?

**Comment by AnneSchueller** [comment]
Ich habe auch mit meiner Gymnasialdatenbank getestet:

- Teilleistungen anlegen klappt 
- Teilleistungen per GP zuweisen klappt
- Teilleistungen per GP und individuell eintragen klappt
- Teilleistungen von einem Fach zum anderen kopieren klappt.

Nur als Admin getestet.
Falls es an den von Herrn Richter genannten Berechtigungen nicht liegt, kannst du mir ja mal Angaben zur Schulform, Fach, Kursart schicken. Dann teste ich damit nochmal.

**Comment by FrodBRA** [comment]
Ich melde mich bei diesen Arbeiten immer nur als Admin an.

Bei der DB handelt es sich unsere DB für die ASDPC-Schulungen, es ist eine Gesamtschule. 

In allen Fächern kann ich keine TL anlegen, alles "Bearbeiten nicht möglich".

Teilweise war aber das Anlegen schon möglich gewesen, im Wiki habe ich die ZP10-Artikel mit der DB erzeugt, nur... funktioniert das Anlegen von TL nicht zuverlässig.

Wird bei der Anlage noch irgendwas angefragt oder müsste man im einfachsten Fall bei Fächern einfach individuell hinzufügen können, sofern man die Recht besitzt?

**Comment by FrodBRA** [comment]
Ich meine die tatsächlichen individuellen Teilleistungen in den Leistungsdaten der Schüler des aktuellen Abschnitts.

Diese können teils nicht angelegt und ausgefüllt werden, weder individuell noch über GPs.

Die TL sind im Katalog angelegt.

**Comment by AnneSchueller** [comment]
Sind die Teilleistungen denn auch bei den Fächern hinterlegt?
Also hier:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/9846bc98-955a-4a9c-929e-431ed60daeec)

**Comment by FrodBRA** [comment]
Ja. Für den GP ist das relevant.

Ich teste später mit anderen DBs noch mal.
