### ISSUE TITLE
In Gruppenprozesse -> Lernabschnitte/Versetzung "fehlen" GPs aus SchiLD2 (Lernabschnitte handhaben/Versetzungsvermerk setzen)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#823]
Version 3.0.76.11

In Gruppenprozesse -> Lernabschnitte/Versetzung "fehlen" die gleich aufgelisteten Gruppenprozesse. Hier wäre zu klären, ob sie wirklich fehlen, ob sie benötigt werden und falls nicht, wo die Felder ansonsten zu setzen sind:

- Lernanschnitte individuell anlegen/bearbeiten
- Lernabschnitt mit Standardangaben anlegen
- Versetzungsvermerk setzen

Sollte eine komplexere Diskussion zu einem GP notwendig werden, verlagere ich diese in ein eigenes Issue.

**Comment by AnneSchueller** [comment]
Punkt 1 und 2 werden in Schild 3 nicht mehr benötigt (siehe hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/575)

"Versetzungsvermerk" kann unter Individualdaten bearbeiten/Lernabschnitte gesetzt werden (falls du hier was anderes meinst, gerne nochmal das Issue öffnen)
