### ISSUE TITLE
Gruppenprozess "Kurse zuweisen (mehrere Kurse)" aus SchILD2 fehlt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#824]
Version 3.0.76.11

Ist der GP aus SchILD2 "Kurse zuweisen (mehrere Kurse)" nicht mehr benötigt? Wird die Funktionalität komplett von einem anderen ersetzt?

**Comment by AnneSchueller** [comment]
Ja genau. Die Einzelzuweisung wurde rausgeschmissen.
