### ISSUE TITLE
Neuaufnahme an Grundschulen

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#827]
Einem unserer Tester ist heute folgendes aufgefallen:
Wenn eine Grundschule zum jetzigen Zeitpunkt (2. Hj.) Neuaufnahmen macht, so werden diese i.d.R. für das 1. Hj. des Folgejahres gemacht. Dies ist derzeit aber nicht möglich, da SchILD3 derzeit nur die Anlage eines Folgeabschnittes ermöglicht (also z.B. 2023/ 24 2. Hj.). Für die Grundschulen wird aber der übernächste Abschnitt (aus heutiger Sicht also 2024/25 1. Hj.) benötigt.

Folgender Vorschlag:

Bei der Neueingabe (im 2. Hj.) wird nach "Grundschule" (und evtl. Förderschule) und allen anderen Schulformen unterschieden.
Bei der Grundschule stehen dann die folgenden Optionen zur Verfügung

1. Anmeldung für das laufenden Halbjahr (2023/24 1. Hj.)

2. Anmeldung für das nächste Halbjahr (2023/24 2. Hj.)

3. Anmeldung für das übernächste Halbjahr (2024/25 1. Hj.)

Wenn Option 2 gewählt wird, prüft das Programm, ob die "Basisdaten" (z.B. Eintrag bei den Schuljahresabschnitten, Klassen usw) für 2023/24 2. Hj. schon existieren, wenn nicht, werden diese automatisch angelegt.
Wenn Option 3 gewählt wird, prüft das Programm ebenfalls, ob die "Basisdaten" für 2023/24 2. Hj. schon existieren, wenn nicht, werden diese automatisch angelegt. Zusätzlich wird geprüft, ob die "Basisdaten" für 2024/25 1. Hj. schon existieren, wenn nicht, werden diese ebenfalls automatisch angelegt.

Erfolgt die Anmeldung aber im 2. Hj. so stehen nur die Optionen 1 und 2 zur Verfügung (mit geänderten Angaben)

1. Anmeldung für das laufenden Halbjahr (2023/24 2. Hj.)

2. Anmeldung für das nächste Halbjahr (2024/25 1. Hj.)

Bei den weiterführenden Schulen steht Option 3 grundsätzlich nicht zur Verfügung.

**Comment by AnneSchueller** [comment]
Stimmt, bei Grundschulen laufen die Neuanmeldungen im ersten Halbjahr. Ihren Vorschlag finde ich gut.

**Comment by JuergenRichter** [comment]
Bei Grundschulen sieht das jetzt so aus:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9cd7019d-254a-4c2d-bb54-651d5f23760b)

Beim Klick auf die Optionen für den nächsten bzw. übernächsten Abschnitt wird jeweils geprüft, ob es auch eine entsprechenden Eintrag in der Tabelle "Schuljahresabschnitte" gibt, wenn nicht, wird er angelegt. Außerdem wird geprüft, ob es auch "Abschnittsdaten" (z.B. Einträge in Klassentabelle) für die zugehörige "Schuljahresabschnitts_ID" gibt. Wenn nicht, werden diese auch automatisch (auf Basis der Daten des akt. Abschnittes) angelegt.

**Comment by JuergenRichter** [comment]
Das ist jetzt so umgesetzt, bitte mit dem nächsten Update mal testen. Ich schließe das Issue erst mal.

**Comment by AnneSchueller** [comment]
Ich öffne das nochmal. Sonst vergesse ich, das zu testen.

**Comment by FrodBRA** [comment]
3.0.77.13

Ich habe es getestet und konnte je einen Schüler in dieses Halbjahr (1.), das nächste (2.) und das kommende erste aufnehmen.

Die S waren dann in der Neuaufnahme mit den jeweiligen Lernabschnitten als Erstabschnitt.

Scheint zu funktionieren.
