### ISSUE TITLE
FSP auf dem Abschlusszeugnis

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#828]
Für SchILD2 gab es schonmal den Wunsch, irgendwo festzuhalten, ob der FSP auf dem Abschlusszeugnis vermerkt werden soll oder nicht.
Wäre das etwas, was in SchILD3 eingepflegt werden sollte?

**Comment by JuergenRichter** [comment]
Die Förderschwerpunkte sind doch aber in der Datenquelle "Schueler" enthalten.

**Comment by JuergenRichter** [comment]
OK, habe das falsch verstanden, es geht um die Entscheidung, ob der FSp auf dem Zeugnis erscheinen soll. Wenn dafür ein neues Feld benötigt wird, muss das vom SVES-Server erstellt werden.

**Comment by AnneSchueller** [comment]
Ja genau, das meinte ich. Auf Wunsch der Eltern kann die Angabe zum FSP auf Abschlusszeugnissen entfallen.
Wenn es hier ein zusätzliches Feld gäbe, könnte man das auch für die Zeugnisse benutzen.

**Comment by AnneSchueller** [comment]
Der Wunsch der Schulen zielte nur auf die Dokumentation ab, sodass nach einer Abfrage ein Häkchen gesetzt ist oder eben nicht.  Können sie natürlich auch weiterhin mit Vermerken o.ä. realisieren.
