### ISSUE TITLE
Filtern nach einem Abschluss: mehrfache Auflistung gleicher Abschlüsse

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#829]
Unter Auswahl/Filter/Abschluss kann der Anwender gleiche Abschlüsse mehrfach wählen.
Die Einträge kommen vom SVWS-Server oder?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/75f142a9-7f34-4986-8b2e-d05dc8b715f1)

**Comment by JuergenRichter** [comment]
Ja, hier sollte die Liste z.B. durch eine zwingende Angabe der Prüfungsordnung reduziert werden. Außerdem sollte in der Liste weitere Spalten für Jahrgänge usw. erscheinen, damit man sieht, um welchen Eintrag es sich konkret handelt.

**Comment by JuergenRichter** [comment]
Ich habe jetzt eine eigene Datenquelle für die Auswahl geschaffen, in der die Einträge (pro Prüfungsordnung) nur noch einmal auftauchen, diese Liste wird nach Prüfungsordnung und "Abschlussoption" sortiert:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/89f0502c-eb0d-49c3-be73-8d41ee6becf9)

**Comment by FPfotenhauer** [comment]
Welche Rückmeldung wird hier von mir erwartet? 
Das ist mir leider nicht ganz klar.

**Comment by AnneSchueller** [comment]
Die Zuweisung galt der Frage (s.o.) "Die Einträge kommen vom SVWS-Server oder?"
Mir war nicht ganz klar, ob hier Handlungsbedarf bezüglich der SVWS-Server-Einträge besteht.
Mit Hinzunahme der Prüfungsordnung ist die Auswahl nun eindeutig.
