### ISSUE TITLE
Filter zurücksetzten im Reiter Reportverwaltung

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#830]
- Filter einstellen unter Auswahl/Filter 1 oder mit Filter auf markierte Schüler
- Trichter erscheint in Rot 
- Zum Reiter Reportverwaltung wechseln
- Auf roten Trichter klicken, um Auswahl aufzuheben

Schüler sind dann alle wieder im Container, aber Trichter bleibt rot und Schnellauswahl nicht möglich:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/fd071912-044d-47a4-ba6e-8effcd2c813b)

**Comment by JuergenRichter** [comment]
Behoben
