### ISSUE TITLE
RAP-Funktionen

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#831]
Werden in Schild3 alle RAP-Funktionen zur Verfügung stehen und funktionieren?
https://wiki.svws.nrw.de/mediawiki/index.php?title=RAP-Funktionen

Wir haben ja z.B. keine Quartale mehr. Damit dürfte die Funktion SetQuartalsnotenInUebersicht zumindest wirkungslos sein.
Gibt es ggf. Funktionen, die wir nicht mehr benötigen?

**Comment by JuergenRichter** [comment]
Ich prüfe das mal. Es gibt zwei Optionen:

1. Die vorhandenen Funktionen werden im Rahmen der Umstellung komplett entfernt
Dann würden sich aber vorhandene Reports, die diese Funktionen nutzen (und die bisher auch in SchILD3 funktioniert haben) nicht mehr starten lassen
2. Die vorhandenen Funktionen bleiben erhalten, haben aber keine Auswirkung mehr
Das würde aber bedeuten, dass man nutzlose Funktionen weiter zur Verfügung stellt

Ich persönlich würde für Option 1 stimmen, schließlich stehen ja auch alte Reportkomponenten (z.B. RotatedLabel) nicht mehr zur Verfügung. Dann lieber jetzt "tabula rasa" machen.

**Comment by FrodBRA** [comment]
Die Gelegenheit, einen sauberen Schnitt zu machen, sollte genutzt werden.

**Comment by Raffenberg** [comment]
Ich finde das Thema nicht ganz so einfach. Wir haben ja verschiedene Kategorien von Funktionen:
1. Funktionen die einen Zugriff auf Daten erst ermöglichen (SetAbitur)
2. Funktionen, die Daten filtern (z.B. FilterLaufbahnJahr)
3. Funktionen, die Delphi-Anweisungen zur Verfügung stellen (z.B. FileExists, SelectFromList)
4. Funktionen, die man früher mal brauchte, aber eigentlich nicht nötig sein sollten (GeschlechtToString)
5. ...

Die können wir ja nicht alle einfach so entfernen. Hier muss man schon besonnen jede Funktion abwägen. Manche kann man durch eigene Programmierungen abfangen, für andere gibt es keine alternative, andere sind schon jetzt nicht mehr notwendig.

**Comment by JuergenRichter** [comment]
Mein Vorschlag bezog sich erst mal nur auf die Funktionen, die was mit Quartalen zu tun haben.

**Comment by Raffenberg** [comment]
Da spricht aus meiner Sicht nichts gegen.

**Comment by JuergenRichter** [comment]
Es gibt eigentlich nur Funktion, die speziell für Quartale verwendet wird:

procedure SetQuartalsNotenInUebersicht( MitQuArtalNoten: Boolean);

**Comment by JuergenRichter** [comment]
Die Prozedur "SetQuartalsNotenInUebersicht( MitQuArtalNoten: Boolean);" ist jetzt raus.
