### ISSUE TITLE
Wo ist Version 3.0.77

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#832]
Im aktuellen Release des SVWS steht: nur mit Schild-NRW 3.0.77 und aufwärts. Aber wo ist diese Version?

**Comment by FPfotenhauer** [comment]
Lieber @kroerig.
Bitte auch bedenken, dass wir alle nur Menschen sind.
Wir laden die Versionen immer so schnell wie möglich hoch, sobald diese zur Verfügung stehen.

**Comment by kroerig** [comment]
Die letzten Versionen wurden zeitgleich veröffentlicht. Was ja auch Sinn macht, denn die beiden Programme sind ja von einander abhängig.
