### ISSUE TITLE
Offizieller Zeugnisreport bricht wegen "Ungültige Graphic" (nach wie vor) ab

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#833]
Version 3.0.76.11

Vorschlag zum Fix: Die in SchILD3 mitgelieferte Reportgeneration muss mit allen Grafiken laufen. D.h. wenn eine Grafik nicht vom Reporting unterstützt wird, fällt das schon in den Einstellungen auf. Sie lässt sich a) nicht setzen bzw. b) erzeugt, sofern sie schon eingestellt wurde, einen Hinweis in den Einstellungen, dass bitte ein unterstütztes Format zu wählen ist.

Bei dem betreffenden Report handelt es sich um GS-AnkreuzZeugnis.rtm. Die Grafik ist ein NRW-Wappen aus unserer A1-Schulungsdatenbank, dürfte als nichts zu ausgefallenes sein (vermutlich ein recht altes .jpg?)

(Genau diese Grafik bekomme ich nicht aus der Datenbank exportiert. Geht das irgendwie, dann würde ich die anhängen.)

**Comment by JuergenRichter** [comment]
Ich habe folgende Beobachtung gemacht: Wenn man die Vorlage (konkret "Zeugnis_Kopf_GS.rtm") im ReportDesigner öffnet und wieder speichert (ohen etwas zu ändern) funktioniert es danach. Die Ursache dürfte irgendwo in den "Tiefen des ReportBuilders" in Verbindung mit der Speichern der Grafiken als Base64 zu tun haben (wobei "on-the-fly" in das originäre Format (z.B. JPG) umgewandelt wird.

Dazu möchte ich aber folgendes anmerken: Die Verwendung von JPG-Dateien als Schullogo sollte vermieden werden. Das JPG-Format ist für Fotos (also vollflächige Grafiken) entwickelt worden, die Schulen haben aber oft eher monochrome Logos mit höherem Weißanteil. Bei der Speicherung als JPG führt das dann oft zu unschönen Artefakten. Da wird dann oft der ReportBuilder für verantwortlich gemacht, der dafür aber gar nichts kann. Schullogos sollten besser als PNG-Dateien verwendet werden.

**Comment by FrodBRA** [comment]
Das kann ich in der Tat reproduzieren. Nach dem Speichern und Neuladen tritt der Fehler nicht mehr auf und der Report wird korrekt generiert.

Der Unterschied von jpg und png geht ja noch weiter, alle klaren Linien und Farbflächen erzeugen als jpg Artefakte. 

SchILD3 betreffend würde ich das Issue damit schließen.

@AnneSchueller @Raffenberg 
Hier wäre dann aber für euch und das Zeugnisteam noch weiterer Handlungsbedarf (der dann aber auf anderem Wege zu besprechen wäre):
1. Die Zeugnisvorlagen sind entsprechend einmal mit SchILD3 zu speichern und neu (für SchILD3) hochzuladen. hier unter Beachtung der Tatsache, dass nach aktuellem Kenntnisstand die Kompatibilität zu SchILD2 gestört wird.
2. Der Bericht holt sich die Datei aus dem Verzeichnis, in dem sie liegt. Nicht aus dem Ordner "Header_Footer". Ist das beabsichtigt?

**Comment by JuergenRichter** [comment]
Zu 2: Ja, damit ist immer eine eindeutige Zuordnung des "Deckblattes" zum eigentlichen Report gewährleistet.

**Comment by JuergenRichter** [comment]
Zu Kompatibilität mit SchILD2: Habe ich natürlich auch getestet (nach Speichern in SchILD3). Da kommt zwar ein Hinweis auf eine nicht vorhandene Eigenschaft:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9bc70b09-a88a-4cdd-a3d1-8ec8753c06fb)

Man kann das aber ignorieren, der Report funktioniert trotzdem. Wenn man einmal in SchILD2 den Report (Zeugnis_Kopf_GS.rtm) im Designer öffnen und wieder speichert, erscheint die Meldung danach auch nicht mehr. Diesen Preis muss man leider bezahlen.
