### ISSUE TITLE
Schaltfläche "Auf Updates prüfen"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#835]
Version 3.0.76.11

Ich gehe davon aus, dass ein Feature "Auf Updates prüfen" vorgesehen ist, es für eine tatsächliche Implementation aber natürlich noch zu früh ist.

Wäre es möglich, schon einen Platzhalter für diese Funktion unter "Hilfe" zu bekommen, somit könnte ich das schon ins Wiki einpflegen. Die Schaltfläche könnte derzeit auch einen reinen Link auf die /releases/ hier enthalten.

Bei grober Vermessenheit meinerseits wäre dieses Issue zu schließen. ;)

**Comment by FrodBRA** [comment]
An die Abhängigkeit des SVWS-Servers dachte ich auch schon:

Die Funktion müsste dann zusätzlich zu SchILD-NRW auch auf eine neue Version des SVWS-Servers prüfen. Und hier wäre noch der Schritt einzufügen, dass bei Notwendigkeit eines neuen SVWS-Servers dieser auch gleich mit "verarbeitet" wird. Etwa als automatischer Download oder als reiner Link auf beide Programme.

Weiterhin kann es später gut sein, dass SchILD geupdated wird, der SVWS-Server aber noch nicht und problemfrei mit einer neueren Version von SchILD-NRW zusammenarbeitet. Ebenso kann es sein, dass der SVWS-Server ein Update bekommt, SchILD aber noch nicht, die alte Version aber nach wie vor kompatibel und vorgesehen ist.

Das kommt mir aber nicht wie ein unlösbares Problem vor.

Diese beiden Programme müssen nun immer in gegenseitiger Abstimmung geprüft und geupdated werden - was nach meinem Ermessen eine automatisierte Prüfung eben beider Software in gegenseitiger Abhängigkeit mit automatischen Download/Verweis auf die zu downloadenden Komponenten noch viel wichtiger als bei einem Standalone-Programm macht.

**Comment by kroerig** [comment]
Mich persönlich nervt es immer, wenn Software mir ständig mitteilt, dass es eine neue Version gibt. Wenn es sicherheitskritisch ist OK, aber nicht weil neue Funktionen hingekommen sind oder ein paar Fehler korrigiert wurden (die mich ggf. noch nichtmal betreffen).
SchILD 2 blendet ja jetzt beim Start einen Hinweis (leider für alle Nutzer) ein, wenn eine neue Version vorliegt. Ich bin immer ein Fan davon, wenn es von einem Hersteller eine Maillingliste o.ä. gibt, wo ich mich freiwillig einschreiben kann und dann informiert werden, wenn es etwas sicherheitskritisches oder im Fall von SchILD auch regulatorisches gibt, was ein Update erfordert.

Denn sonst gilt bei mir: Ich muss nicht jedes Update mitnehmen, wenn mich die Änderungen darin nicht betreffen.

Updateprüfungen aus Programmen selbst heraus, verleiten Anwender gerne dazu diese auch durchführen zu wollen. Aber nur, weill man Admin-Rechte im Programm hat, heißt das noch lange nicht, dass man auch das Recht hat neue Software zu installieren.

> Weiterhin kann es später gut sein, dass SchILD geupdated wird, der SVWS-Server aber noch nicht und problemfrei und so vorgesehen mit einer neueren Version von SchILD-NRW zusammenarbeitet. Ebenso kann es sein, dass der SVWS-Server ein Update bekommt, SchILD aber noch nicht, die alte Version aber nach wie vor kompatibel und vorgesehen ist.

Bei PHP nutzt man dafür gerne Composer. Der versucht aus einer Liste von Abhänigkeiten die bestmögliche Kombination zu ermitteln. Sofern es eine Lösung gibt.

Aber wie Sie schon schreiben, es kann sein, dass es über eine längere Zeit kein Update des SVWS-Servers gibt, aber immer wieder für SchILD3. Irgendwann kommt ein Update für den SVWS und das dürfte dann vermutlich zwingend auch ein SchILD Update erfordern, denn dann dürfte es Änderungen an der API gegeben haben, die SchILD3 ebenfalls umsetzen muss.

Da wäre dann auch die Frage: Nutzt das Projekt _semantic versioning_, und bleiben alte APIs erhalten oder sind Änderungen an der API immer BC-breaks?

**Comment by FrodBRA** [comment]
1. Du bist nicht die arme Grundschulsekretärin, die ab nun SchILD3 und den SVWS Server koordiniert updaten muss. Vielleicht werden sogar zwei Grundschulen im Wechsel betreut. Meinungsteil: Die nicht technisch affine Benutzergruppe, die SchILD als Software nutzt, um die eigentliche Arbeit zu erledigen und kein Interesse an "solchem Computerzeug" hat, muss entlastet werden. Auch wenn das auf Kosten individueller Computer-Ideologie informatisch-affiner Nutzergruppen gehen mag.
2. SchILD2 hat wie alle moderne Software genau diese Funktion. Ein Verzicht wäre ein Rückschritt.
3.  Eventuell sollte sich die "Update-Nachricht" wie auch die Informationen zur neuesten Version beim Start für fortgeschrittene Nutzer deaktivieren lassen. Der Default sollte sein, dass diese Informationen angezeigt werden.

**Comment by FPfotenhauer** [comment]
Letztendlich wird man sich hier in Ruhe Gedanken machen müssen.
Das Schild3-Update besteht ja eigentlich nur aus einem Dateiaustausch.
Da muss man mal schauen, wie man das ggf. eleganter hinbekommen kann bei Einzelinstallationen.

Wichtig wird sein, dass wir nächstes Jahr feste Kombinationen aus SVWS-Server und Schild3 anbieten.
Das wird uns aber natürlich etwas Felxibilität nehmen. Das merkt man ja jetzt schon, wenn Schild3 erst mit der aktuellen Version des SVWS-Servers getestet werden muss und umgekehrt.

**Comment by kroerig** [comment]
> 1. Sie sind nicht die "arme Grundschulsekretärin", die ab nun SchILD3 und den SVWS Server koordiniert updaten muss.

Die "arme Grundschulsekretärin" sollte sich darum gar nicht kümmern müssen. Das ist Aufgabe des Schulträgers. Entweder vor Ort, wenn die Schule SchILD auf einem lokalen PC einsetzt oder er hat eine Softwareverteilung. Im besten Fall aber arbeiten Grundschulen IMHO auf einer zentralen Plattform.
