### ISSUE TITLE
"Statistikrelevante Felder" sind nicht eingefärbt, sondern mit "*" markiert

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#836]
Version 3.0.76.11

In der "Luna"-Oberfläche sind statistikrelevante Felder nicht mehr eingefärbt. Die Einfärbung war in SchILD2 sehr gut zu sehen, meiner Sicht nach deutlich besser als der nun verwendete "*".

Hier wäre eine konfigurierbare Einfärbung wieder schön.

edit: Hierbei ist mir nur aufgefallen: Es gibt keine Markierung mehr für die MUSS Felder, die notwendig sind, um den Datensatz überhaupt zu speichern (Nachname, Status). Gibt es dieses Kriterium nicht mehr?

----

Weiterhin wäre dies eine Gelegenheit, noch einmal darüber nachzudenken, ob überhaupt mehrere Benutzeroberflächen angeboten werden sollen - bei ernsthafter Reduzierungsabsicht wäre diese Überlegung auszulagern: 

- Sollen es tatsächlich drei Optionen sein?
- Reicht nicht eine? 
- Wenn mehrere, eine "normale" und ein "Colorblind Mode" mehr Sinn, der dann auch dem (einem? ;)) aktuellen Forschungsstand zu Farb-Fehlsichtigkeiten entspricht.

**Comment by Raffenberg** [comment]
Ich kann mich dem nur anschließen. Die Sternchen sind optisch sehr schwer zu erfassen. Ich vermisse die farbigen Überschriften sehr.

Die Themes würde ich nicht nochmal anfassen. Da geht zuviel wertvolle Zeit drauf.

**Comment by FrodBRA** [comment]
Wenn es beim Sternchen bleiben sollte, würde ich dafür plädieren einmal auszuprobieren, wie es aussieht, dass normale Felder "nicht fett" und und die statistikrelevanten "fett mit Sternchen" gedruckt werden.

Grundsätzlich wäre ich aber mit Priorität ebenfalls für eine Einfärbung der statistikrelevanten Feldbezeichnungen mit einer Konfigurationsmöglichkeit (Individuelle Einstellungen) für die Farbe (im Stil Luna könnt grün komisch aussehen, hier müsste man testen). 

Bei einer gewählten Einfärbung könnte das Sternchen dann automatisch von der Zeichenkette abgeschnitten werden.

**Comment by JuergenRichter** [comment]
Die Farben der Komponenzten sind durch das gewählte Thema vorgegeben. Ob man (was die Schriftfarbe in bestimmten Fällen betrifft) das Thema "übertölpeln" kann, mus sich prüfen.

**Comment by Raffenberg** [comment]
Ich habe Lina, Silverund Light aktiviert. Bei keinem der Themes gab es eine farbige Überschrift.

IOn Schild2 konnte man die Überschriftfarbe noch definieren. Das finde ich in Schild 3 nicht mehr. Kann es sein, dass in dieser unsichtbaren Standarddefinition die Farbe schwarz hinterlegt ist?

**Comment by FrodBRA** [comment]
@Raffenberg 
Ich hatte das so verstanden, dass es eine einzige Komponente "Überschrift" gibt, die eben nur eine einzige Definition hat.

> Die Farben der Komponenzten sind durch das gewählte Thema vorgegeben.

Eventuell müsste für "statistikrelevante Überschriften" eine neue Komponente definiert werden - oder was nach meinem Verständnis Herr Richter meinte, dass irgendwie auf zu "überformatierende" Überschriften gefiltert werden muss (bzw. ob sie mit einem Sternchen endet), um ein neues Format einzuschummeln (evtl. per Regexp + Stringreplace, wo die Überschrift zur Laufzeit mit Farb-Steuercodes versehen wird). Irgendwie sowas.

**Comment by JuergenRichter** [comment]
So in etwa ist es

**Comment by JuergenRichter** [comment]
Ich habe jetzt mal etwas recherchiert. Es gibt die Möglichkeit, die durch das jeweilige Thema vorgegebene Schriftfarbe von z.B. Label-Elementen zu überschreiben. Ich stelle das hier mal zur Diskussion, ob das wieder so wie in SchILD2 (benutzerdefinierbare "Statistik-Farbe") umgesetzt werden soll.

**Comment by FrodBRA** [comment]
Ich fände das Verhalten wie in SchILD2 sehr gut.

**Comment by AnneSchueller** [comment]
Ich wäre auch dafür,

**Comment by JuergenRichter** [comment]
Es gibt nun eine Einstellmöglichkeit für die Statistik-Farbe
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/11c4490e-274a-41e9-97a6-855090cdb7b9)

Die Anzeige funktioniert im Hauptfenster bei Label- und Checkbox-Objekten:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/da6a194e-92dc-4d90-9bed-09b6c1b40259)

Die Überschriften in Tabellen konnte ich aber noch nicht "übereden":
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/de2b3fa6-7f72-4cb4-a16b-a010eaf56610)

**Comment by FrodBRA** [comment]
Das ist toll! Besonders die Defaultfärbung passt gut zum neuen Einhorn-Thema von SchILD, das ja ganz bestimmt kommen soll (oder man kann ja noch was als Default setzen, das besser zum Standardthema passt). ;)

Falls das zu viel Gefrickel oder eine Quelle für weitere Bugs wird: Von mir aus könnte ich auf eine weitere Einfärbung der Tabellenüberschriften verzichten, diese sind nach meiner Wahrnehmung im Gegensatz zu den eher im "Fließtext" - auch im Wechsel bezüglich ihrer jeweiligen Statistikrelevanz - auftauchenden Feldüberschriften klar als besternt oder unbesternt zu erkennen.

Mir bleibt nur noch diese Frage: Gibt es noch MUSS-Felder wie in SchILD2 (Nachname, Geburtsdatum, Status) und sollen die gesondert gekennzeichnet werden?

**Comment by JuergenRichter** [comment]
" Besonders die Defaultfärbung passt gut zum neuen Einhorn-Thema von SchILD,"
das ist natürlich nicht der Default, der is erst mal schwarz. ;)

**Comment by FrodBRA** [comment]
Ich hielte es für sehr sinnvoll, dass der Default nicht schwarz ist, sondern im Auslieferungszustand schon eingefärbt ist. Es sollte jede Möglichkeit zur visuellen Entlastung und vorausschauenden Fehlervermeidung direkt genutzt werden. Gerade die Leute, die nicht erst die Einstellungen nach so etwas durchsuchen, könnten diese Hilfe sehr brauchen. 

Es hilft auch bei Schulungen sagen zu können, die "bunten Felder sind statistikrelevant", anstatt den Umweg über "wenn die Einstellungen hier und so und so sind, dann werden die statistikrelevanten Felder auch bunt".

Ein Blauton, der zu "Luna" passt wäre möglich?

**Comment by FPfotenhauer** [comment]
Das ist eine Funktion, die nicht mit uns abgesprochen wurde.
Bitte den Default zunächst so lassen.
