### ISSUE TITLE
Installationsprobleme

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#837]
Ich habe mehrfach vergeblich versucht, die Server-Version 0.7.8 und Schild 3.0.76 zu installieren. Soweit ich das nachvollziehen kann, handelt es sich dabei um die aktuellen Dateien. Ich bekomme während des Startvorgangs von Schild3, nachdem ich informiert wurde, dass die Server-Version (0.7.8) nicht vom Programm erwartet wird, die folgende Fehlermeldung (s.u.). Vorher spielte dieser Hinweis nie eine Rolle. Deshalb bin ich irritiert, ob das nun anders ist. 
![Schild102](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/f399d924-1309-47c3-89d7-6f824a3212eb)
[SchILD30 (2).zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13412753/SchILD30.2.zip)

**Comment by Raffenberg** [comment]
Hallo Jens,
in den Releases zum Server steht "nur mit Schild-NRW 3.0.77 und aufwärts". Solange die Schild-Beta 3.0.77 noch nicht kompiliert wurde, kann der neuste Server nur Stand-Alone getestet werden.

**Comment by AnneSchueller** [comment]
Wenn ich das richtig verstanden habe, hast du nun beide Programme (Schild3 und SVWS-Server) auf den neusten Stand gebracht?

Die DB hast du nicht neu migriert oder? Es kann sein, dass die Version, mit der du die DB migriert hattest so alt ist (Vor September 2023), dass nochmal neu migriert werden muss. Ab der SVWS-Version 0.7.0 ist eine neu-Migration nicht mehr notwendig.

**Comment by JeVaske** [comment]
Doch, ich hatte neu migriert. Das funktionierte alles tadellos. Ich hatte mir nur die Releasenotes nicht durchgelesen. Dauert die Veröffentlichung von Schild 3.0.77 noch lange?

**Comment by AnneSchueller** [comment]
Die neue Version steht nun zum Download bereit.
