### ISSUE TITLE
Installationen Versionen

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#838]
Hallo,

ich kann aktuell nur die Kombination SVWS-Server Version und Setup_SchILD3_v3.0.74 laufen lassen, alles andere lässt sich nicht erfolgreich verbinden.
Gibt es eine lauffähige und getestete Versionskombination von beiden Programmen?

Zudem kann der Installationspfad des SVWS-Servers nicht auf ein Netzlaufwerk gelegt werden bzw. dann funktioniert der Dienst nicht, da der Pfad nicht gefunden wird, egal ob man ein gemappted Laufwerg angibt oder den UNC-Pfad.

Liebe Grüße
Raphael

**Comment by AnneSchueller** [comment]
Hallo Raphael,

ich arbeite aktuell mit Schild 3.0.76 und dem SVWS-Server 0.7.7.
Die harmonieren trotz einer Warnung. 
Bald wird auch Schild 3.0.77 rauskommen, sodass auch SVWS 0.7.8. damit läuft.

**Comment by FrodBRA** [comment]
Der Download findet sich hier: https://github.com/SVWS-NRW/Schild3-BetaTest/releases

https://github.com/SVWS-NRW/SVWS-Server/releases

Bei mir läuft SchILD 3.0.76.11 mit SVWS 0.7.5.

**Comment by AnneSchueller** [comment]
Die neue Version von Schild3 steht nun zum Download bereit. Ich schließe das Issue daher mal. Sollte es hier noch Probleme geben, dann ggf. nochmal öffnen.
