### ISSUE TITLE
Schild 3 - Gruppenprozess auch für individualisierte Individualfelder / Import-Möglichkeit aus CSV-Datei

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#839]
Hallo,

bisher ist es nicht möglich, einen Gruppenprozess für Indivualfelder durchzuführen, die individuell sind, z.B. die Externe ID. Ich habe bei unserer Schild 2.0-Datenbank aus Versehen durch einen Import (Extern.Import.exe) alle Externe ID-Felder mit Werten gefüllt, die ich wieder gerne löschen möchte.
Aktuell habe ich sie nur durch ein Zeichen "-" füllen können, der Import funktionierte aber nicht mit "".

In Schild 3 ist diese Möglichkeit wohl nicht mehr vorhanden, wieso nicht?

Liebe Grüße

Raphael

**Comment by AnneSchueller** [comment]
Für diesen Fall könnte man über den Schild-Schnittstellenimport die Schueler Zusatzdaten importieren. Dort ist das Feld externe ID dabei.
Alternativ würde hier evtl. auch ein SQL-Befehl nutzen (Das geht übrigens auch in Schild2; auch mit null-Ersetzungen)

Das Programm ExternImport.exe ist ein separates Programm, das aktuell nur noch als Blackbox verwendet wird. Mit und mit soll alles in die Oberfläche implementiert werden, sodass die externen Programme immer mehr reduziert werden.
