### ISSUE TITLE
Verwaltung -> Export -> IServ-Export kein Eintrag für Lernplattform möglich

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#840]
Hallo,

in der Verwaltung -> Export -> IServ-Export ist kein Eintrag bei "Welche Lernplattform ist "IServ"?
Einzig lauffähige Version bei uns: Schild 3.0.74

Liebe Grüße

Raphael Kemna

**Comment by FrodBRA** [comment]
Wurde die Lernplattform unter Kataloge -> Lernplattformen angelegt? Nur die hier existierenden Lernplattformen können im Exportfenster angewählt werden.

Bei einer angelegten Lernplattform kann diese (Version 3.0.76.11) im Export ausgewählt werden.

**Comment by AnneSchueller** [comment]
Ich habe gerade die Migration getestet. Die Lernplattformen werden mit aus Schild2 einwandfrei migriert.

**Comment by FrodBRA** [comment]
@Raphael-Kemna 
Ist das Problem noch zu reproduzieren? Falls ja läge eventuell ein Fehler bei der Datenbankmigration vor?

**Comment by Raphael-Kemna** [comment]
Vielen Dank für die Info,
ich kam nur noch nicht dazu, mir dies anzusehen, habe es nun aber testen können und es funktioniert alles.
Damit ist das "Problem" behoben. Danke.
LG

**Comment by AnneSchueller** [comment]
@Raphael-Kemna 
Vielen Dank fürs erneute Testen :-)
Damit schließe ich das Issue.
