### ISSUE TITLE
Dokumentenverwaltung

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#841]
Hallo,

nach Aktivieren der Dokumentenverwaltung kann das Anlegen für die Schüler nur einmal erfolgen, danach wird nur bei Auswahl eines Schülers das Verzeichnis neu angelegt, aber nicht über diesen Menüpunkt in der Verwaltung, obwohl man den Hinweis bekommt, dass die Verzeichnisse angelegt werden sollen.
So ist eine Korrektur bzw. jährliche Anlage für die Jahresweise Ablage nicht möglich.

Lieeb Grüße

Raphael Kemna
Version 3.0.74

**Comment by AnneSchueller** [comment]
Man muss tatsächlich hier die Schüler einmal anklicken, damit die Ordner sichtbar werden. Auch automatische Prozesse helfen nicht. 
Das ist natürlich ungünstig, wenn man externe Dateien bei Schülern hinterlegen möchte. 
@JuergenRichter : kann man das anpassen?

**Comment by JuergenRichter** [comment]
Wenn die Dokumentenverwaltung eingerichtet wird, erhalten die SuS "ihr eigenes Verzeichnis", das (mit den dann aktuellen Einstellungen für die Maske) auch in der Datenbank (Tabelle Schueler) gespeichert wird. Das bleibt auch so, wenn später irgendwann mal die Einstellungen geändert werden. Sonst könnte folgendes passieren:

-In dem bestehenden Verzeichnis bei einem Schüler befinden sich diverse Dokumentente
-Bei den Einstellungen werden dann die Angaben zum Dokumentenverzeichnis geändert. Wenn damit auch das beim Schüler gespeicherte Verzeichnis geändert wird, "verschwinden" die vorhandenen Dokumente aus der Ansicht. Sie sind natürlich immer noch da, aber u.U. weiß niemand mehr wo.

Daher gilt (auch schon in SchILD2): Ein einmal beim Schüler hinterlegtes Dokumentenverzeichnis wird bei einer Änderung in den Einstellungen nicht "angefasst". Der Vorgang des Anlegens hat dann nur Auswirkungen auf solche SuS, die noch keinen "persönlichen" Eintrag  haben. Für die Anpasung an die neue Struktur gibt es den Gruppenprozess "Dokumentenverzeichnisse aktualisieren". Ich habe hier aber nun auch noch einen Hinweis eingebaut, dass bei diesem Gruppenprozess die bisherigen (individuellen) Einstellungen überschrieben werden und dass daher Dokumente, die in den bisherigen Verzeichnissen liegen, im Progrmm nicht mehr angezeigt werden können.

**Comment by AnneSchueller** [comment]
Danke für die Rückmeldung.
Beim erneuten Test mit einer DB, die bisher noch keine Einträge in der Tabelle Schüler/Dokumentenverzeichnis hat, funktioniert alles.
