### ISSUE TITLE
Klassenleitung wird nicht automatisch aktualisiert

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#842]
SVWS-Server: 0.7.5 und Schild 3.0.76
Mir ist aufgefallen, dass unter dem Reiter "Akt. Halbjahr/ Allgemeine Angaben" die Namen der Klassenleitung nicht automatisch aktualisiert wird, sobald man eine Klasse gefiltert hat und einen Schülernamen anklickt. Die Aktualisierung geschieht erst, wenn man unter "Halbjahr wählen" auf einen vergangenen Abschnitt klickt und danach wieder auf den aktuellen. In der Jahrgangsstufe 5 kann man sich derzeit keine Klassenleitung anzeigen lassen, weil man nicht zwischen den Halbjahren hin und her klicken kann.

**Comment by AnneSchueller** [comment]
Das kann ich nicht reproduzieren. (SVWS 0.7.8, Schild 3.0.77)

Hier mal ein kurzes Video dazu. Oder ist hier was anderes gemeint?

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/b76405a7-2af8-4634-8de0-23389ab3fd26

**Comment by JeVaske** [comment]
Es ist anders gemeint: Ich starte Schild2, dann
1. filtere ich die Klasse 10A und gehe auf Akt. Halbjahr/Allgemeine Angaben-->Im Feld Klassenleitung steht nichts, es ist weiß, also ohne Inhalt.
2. Ich klicke auf 2023/24 1. Hj --> Das Feld Klassenleitung ist immer noch weiß
3. Ich klicke auf 2022/23 2. Hj --> Das Feld Klassenleitung ist erstmals gefüllt. Dort steht dann z.B. Paul Müller und Werner Meier
4. Ich filtere die Klasse 9a und gehe auf Akt. Halbjahr/Allgemeine Angaben-->Dort stehen immmer noch Paul Müller und Werner Meier
5. Um die Klassenleiter zu aktualisieren, muss ich jetzt auf 2022/23 2. Hj. und dann auf 2023/24. 1. Hj klicken, damit die Klassenlehrer sich aktualisieren.
Vielleicht wird das Problem mit Schild 3.0.77 behoben. Ich werde es so schnell wie möglich testen

**Comment by JeVaske** [comment]
SVWS-Server: 0.7.9 und Schild 3.0.78
Mit der aktuellen Installation funktioniert es bei mir auch.
