### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#845]
Server 0.7.9, Schild 3.0.78
Wenn man in der Leistungsübersicht (Schüler/Übersicht) auf das "i" klickt, muss im Infotext das Wort "abgeschlossenes" klein geschrieben werden. 
![Schildfehler 002](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/80f9eb7c-00bd-4be2-b7e6-ba8cbe7786a4)

**Comment by JuergenRichter** [comment]
Behoben
