### ISSUE TITLE
Laufbahninfo/ Sprachenfolge

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#846]
Server 0.7.9, Schild 3.0.78
Unter Laufbahninfo/Sprachenfolge irritiert mich Folgendes:
1.  Die Bezeichnung in der Spalte "Folge" sollte eventuell wie in Schild2 als "Reihenfolge" bezeichnet werden.
2. In der Spalte "Folge" ist die Bezeichnungen "1. Fremdsprache", hier nicht angeklickt, rechtsbündig. Alle anderen Bezeichnungen sind linksbündig. Insofern würde ich eine einheitliche Formatierung vorziehen. Wenn man z.B. "2. Fremdsprache" (s. Bild grün) anklickt, rutscht der Begriff nach links. Das irritiert zusätzlich.
3. Bei Schild2 werden in der Spalte Fremdsprache die internen Kürzel für die Fächer (hier: E5 und E7) verwendet. Bei Schild3 wird die ASD-Bezeichnung (E, F) verwendet. Hier sollte wie bei Schild2 das interne Kürzel verwendet werden.

**Comment by AnneSchueller** [comment]
Zu 1: Wenn das vom Platz her passt...
Zu 2: linksbündig fände ich auch besser
Zu 3: Das ist so beabsichtigt. Die Daten werden vom SVWS-Server ausgelesen. Hier sind nur die atomaren Angaben für die Sprachen. Mit dem Anfangsjahrgang ist das ja eindeutig.

**Comment by AnneSchueller** [comment]
Siehe https://github.com/SVWS-NRW/Schild3-BetaTest/issues/847
