### ISSUE TITLE
Feld in Schüler zum Eintragen der Ankreuzzkompetenzen ist zu schmal

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#849]
Version 3.0.77.13

Der zum Bearbeiten der individuellen Ankreuzkompetenzen ist zu schmal, damit kann nicht gearbeitet werden. Schon normale Kompetenzen sind nicht lesbar, wurden aber Unterkategorien definiert, kann die Kompetenz gar nicht mehr erraten werden, ohne dauernd zu scrollen.

Das Fenster kann lediglich in der Höhe angepasst werden, nicht in der Breite.

Das Feld sollte die Breite der Fensterkomponente haben.

![AKKZuSchmalpng](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/9cc9f2c1-00c2-459c-8fb8-974a7c2ea87d)

**Comment by AnneSchueller** [comment]
Funktioniert das denn, wenn du das Fenster zwischen Kompetenzbeschreibung und der "1" breiter ziehst?
Bei mir klappt das. Die Einstellung wird gespeichert, sodass auch beim Wechsel zu den fachbezogenen Kompetenzen und auch nach einem Neustart von Schild die Fenstergröße erhalten bleibt.

**Comment by FrodBRA** [comment]
Das vergrößert nur die Spalte mit den Beschreibungen, schiebt dabei aber die Checkboxen nach rechts raus.
Längere Kompetenzbeschreibungen passen noch immer nicht.

Zur Arbeit muss dauernd hin- und hergescrollt werden.

Meinung: eine Benutzung in der Praxis ist so unzumutbar und auch fehleranfällig. Und das, obwohl rechts noch genug Platz wäre. 

Sieht das bei dir anders aus, d.h. hast du mehr Platz in der Breite?
![AKKZuSchmalpng 2png](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/36a106dc-5f6d-4711-9f0d-c7720a5009e8)

**Comment by FrodBRA** [comment]
Dopplung mit https://github.com/SVWS-NRW/Schild3-BetaTest/issues/703

Die dort genannte Lösung funktioniert.
