### ISSUE TITLE
Scrollbalken unter Werkzeuge kann nicht zum Verschieben angeklickt werden

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#85]
Bei Zoom 120 lässt sich der Scrollbalken unter dem Punkt Verwaltung / Werkzeuge nur mit dem Scrollrad der Maus benutzen. Wenn er zum Verschieben angeklickt wird, wird der Menüpunkt aufgerufen und es ist kein Verschieben möglich.

**Comment by FPfotenhauer** [comment]
Hat sich erledigt.
