### ISSUE TITLE
Operation bei geschlossener Datenmenge nicht ausführbar.

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#852]
Fehler beim Beenden von SchILD:
[fehler.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13536826/fehler.txt)

**Comment by AnneSchueller** [comment]
Ich kann das nicht reproduzieren.

Haben Sie Schild über "Programm beenden" beendet oder auf "x" geklickt? 
Wenn zweiteres: Aus welchem Reiter heraus wurde Schild geschlossen?

**Comment by AnneSchueller** [comment]
Das wird es sicherlich sein. Ähnliches Verhalten habe ich auch mit anderen Fehlern schonmal festgestellt.
Ich schließe das Issue daher mal.

**Comment by kroerig** [comment]
So, ich konnte den Fehler erneut produzieren:

Ich habe in den Einstellzungen einen Wert geändert (siehe https://github.com/SVWS-NRW/Schild3-BetaTest/issues/851). Da es keinen Speichern Button gibt, dann einfach mal im Menü links auf "Schule" geklickt. Dann wieder zurück auf Einstellungen. Dann auf das X zum Beenden des Programms. -> Fehlermeldung

Und jetzt kann ich anwählen, was ich will. Nur noch diese Meldung und keine Daten mehr. Ich mache noch einen kleinen Screencast.
Bitte Issue wieder eröffnen.

**Comment by kroerig** [comment]
https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/2c20bf03-1de0-441a-89ea-0ae8ce32fdd9

**Comment by AnneSchueller** [comment]
Stimmt. Mit dieser Klickfolge erhalte ich die gleiche Fehlermeldung. Danke fürs erneute Testen.

**Comment by JuergenRichter** [comment]
Behoben
