### ISSUE TITLE
Lupo3: Fehlermeldung zuviel

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#855]
Wenn ich einen Wechsel von EF Kunst nach Q1 Literatur mache, ist die Laufbahn korrekt:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/32db856a-3efc-41a0-af56-c7cf0ebb4516)

Wenn ich zu einer der genehmigten Schulen gehöre, die auch in der Q2 Literatur fortführen, kommt es zu zwei fehlermeldungen, von denen eine nicht korrekt ist. Zudem ergibt der Hinweistext keinen Sinn:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/bed79e02-f3e2-47e3-914f-ddb103eda41e)

**Comment by ThomasBachran** [comment]
Die Belegprüfung wurde in diesem Zusammenhang überarbeitet und gibt jetzt bessere Fehlermeldungen. Dies kann man mit dem nächsten Pre-Release des SVWS-Servers testen.
