### ISSUE TITLE
Lupo3: Klickzyklus der Fächer LI, IP, VP und nicht Abifächern AB3/4

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#856]
Im Klickzyklus von LI, IP, VP und definierten Nichtabiturfächern (kein AB3/4) darf s nicht vorkommen. Das weckt falsche Eindrücke und wird zu Nachfragen führen. 

Hinweis:
In der Regel kommt hier als Nichtabiturfach ohnehin nur Sport in Frage.
Das Schriftlichkeit bei Nichtabiturfächern verboten ist, findet man nicht in der APO-GOSt. Damals war das aber so mit dem MSB abgestimmt. Lupo2 hat das nie angeboten. Damit hat das auch nie jemand angezweifelt.

**Comment by ThomasBachran** [comment]
Ich übernehme diesen Vorschlag in unsere Issue für den SVWS-Server und schließe das Issue hier.

**Comment by ThomasBachran** [comment]
Wurde bearbeitet und die Anpassung steht mit der nächsten SVWS-Server-Version zur Verfügung
