### ISSUE TITLE
Fehlerhafter Import WBK

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#858]
Im WBK werden nicht alle Semester der Studierenden importiert. Die Sommersemester fehlen leider.
![image001](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/6d3f37d1-7781-46b1-a71d-82547f9d82d2)

**Comment by AnneSchueller** [comment]
Mit unserer Spieldatenbank tritt das gleiche Problem auf. Ich lege die DB zusammen mit dem Migrationsprotokoll in unsere Cloud in den Ordner "Austauschordner Schuldaten/WBK"

**Comment by FPfotenhauer** [comment]
Das liegt an der Einstellung AnzahlAbschnitteProJahr=1 und Anzahl JahrgangsstufenProJahr=2.
Wir würden gerne die Anzahl der AbschnitteProJahr auch auf 2 setzen.
Die Programme Schild3 und SVWS-Server müssten dann für die Schulform WBK damit klar kommen, das beim Halbjahreswechsel auch der Statistikjahrgang hochgezählt wird.

@JuergenRichter Wäre das aus Ihrer Sicht ok?
@Kluesenerm Habe ich noch einen Denkfehler oder wäre das machbar? Wir wollen gerne einheitlich bei allen Schulen sein.

**Comment by JuergenRichter** [comment]
"Das liegt an der Einstellung AnzahlAbschnitteProJahr=1"

Das Feld heißt aber nicht "AnzahlAbschnitteProJahr" sondern nur "AnzahlAbschnitte", im Programm hat es die Überschrift "Anz. Abschnitte pro Jahrg.-Stufe". Bei WBKs steht da tatsächlich i.d.R. eine "1" drin, was bedeutet, dass bei denen ein Jahrgang einen Abschnitt hat. Da dann aber auch (in allen mir bekannten Fällen) im Feld "AnzJGS_Jahr" (Anz. Jahrgangsstufen pro Jahr") eine "2" steht, bedeutet das dann, dass bei WBKs das Schuljahr in zwei Jahrgangsstufen unterteilt ist, und das jedes dieser Jahrgangsstufen einen Abschnitt hat (also ein Halbjahr). Das bedeutet, dass bei WBKs jeder Halbjahreswechsel mit einem Jahrgangswechsel einher geht. In ScHILD3 sind die genannten Felder derzeit "stillgelegt", bei WBKs wird grundsätzlich angenommen, dass bei einem Halbjahreswechsel auch ein Jahrgangswechsel stattfindet, bei allen anderen Schulformen nicht. Die Migration könnte m.E. die Angaben in der MDB ignorieren und einfach die Lernabschnitte so übernehmen wie sie sind.

**Comment by Kluesenerm** [comment]
WBKs arbeiten im Semesterbetrieb. Daher ist bei uns jeder Halbjahreswechsel im Prinzip auch ein Schuljahreswechsel mit Versetzung. Ich kann, wie oben beschrieben, aber keine Änderungen zum Testen vornehmen, weil die Felder in Schild 3 ausgegraut sind. 
<img width="172" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/fbc40543-33b0-4f1d-a1c7-581528b14f30">

(hier die aktuellen Einstellungen bei Schild 2.0:
<img width="285" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/63be3541-49fd-4737-b121-82b746eb51b8">

**Comment by JuergenRichter** [comment]
Die Anzeige der Feldinhalte geschieht derzeit auch nur noch "aus historischen Gründen". Intern wird bei WBKs immer mit den in Ihrem Screenshot gezeigten Einstellungen gearbeitet. Deshalb sind die Einstellungen auch gesperrt, da eine Änderung keine Auswirkung hätte.
Wenn ich das recht verstanden habe, hängt das beschriebene Problem doch aber mit der Migration zusammen. Man könnte daher in SchILD2 (!) mal die Einstellungen ändern und dann nochmals die Migration durchführen. Erst wenn diese korrekt funktioniert, macht es m.E. Sinn, einen Versetzungstest in SchILD3 zu machen.

**Comment by ThomasBachran** [comment]
@JuergenRichter : Das bedeutet also, dass wir bei der Migration einfach Anzahl Abschnitte pro Jahr = 2 annehmen und Schild 3 auch keine Probleme damit hat, wenn das Feld "AnzahlAbschnitte" bei der Migration auf 2 gesetzt wird, weil Schild 3 gar nicht mehr darauf zurückgreift?

Dann werden wir das dann in der nächsten Version des SVWS-Servers so umsetzen. Bei unserer Testdatenbank lief die Migration damit auch so durch, dass die Lernabschnitte korrekt übernommen werden.

**Comment by JuergenRichter** [comment]
Ja, so ist es

**Comment by Kluesenerm** [comment]
Nur kurz zur Info für Frank:
Wenn ich bei Anzahl Jg-Stufen eine 1 und bei Anz. Abschnitte eine 1 in Schild 2.0 setze, kann ich die Schule nicht in das Sommersemester 2023/2024 übertragen:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/f883be3f-50f0-40c2-a1f3-bc6edbd25e96)

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/174fb294-18a4-48c6-8377-cb07f1de9317)

**Comment by ThomasBachran** [comment]
Die Einstellungen brauchen in Schild 2 auch nicht angepasst zu werden. Das wird die Migration in der nächsten Version des SVWS-Servers dann automatisiert machen. Wenn man das Verhalten in Schild3 testen möchte könnte man höchstens in Schild 2 beide Werte auf 2 setzen und dann direkt migrieren. Das dürfte ein ähnliches Verhalten ergeben. Allerdings sollte man dann nicht so in Schild 2 weiterarbeiten. Zumindest ist mir nicht klar, welche Auswirkungen dass dann hätte.

**Comment by FPfotenhauer** [comment]
In der Version 0.8.3 kann die Migration nochmal getestet werden. Bei uns ist das Problem da behoben.

**Comment by AnneSchueller** [comment]
Bei meiner Test DB sind jetzt in Schild auch keine Probleme diesbezüglich mehr aufgetreten.
