### ISSUE TITLE
Filter (Bedienung und INFO)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#859]
Um eine Abfrage zu "negieren" muss in der aktuellen Version die rechte Maustaste benutzt werden. Das INFO-Fenster mit dem Hinweis auf Doppelkick stimmt nicht mehr.

Hinweis: Das Filtern ist meiner Ansicht nach sehr unfreundlich für Benutzer. Um z.B. nach einem Ort oder einer Nationalität zur Filter, genügt nicht einfach nur ein Klick in das Feld um dann den Filterbegriff einzugeben.  Es muss zuerst die Auswahl über das kleine Dreieck geöffnet werden, erst danach lassen sich z.B. Filterbegriffe eintragen.

**Comment by AnneSchueller** [comment]
In meiner Version klappt das mit dem Doppelklick noch. Also erst auswählen und dann der Doppelklick.

Ich stimme auf jeden Fall zu, das eine Sucheingabe über die Tastatur insbesondere bei langen Auswahllisten wie z.B. der Ort sehr benutzerfreundlich wäre. 
Ich schiebe das aber erstmal in die "Nice to hace" Kategorie.

**Comment by JuergenRichter** [comment]
Ich habe die "Comboboxen mit Checklist" um einige Eigenschaften erweitert:
-Wenn man einen Buchstaben eintippt, geht die Liste automatisch auf und springt zu dem ersten Eintrag, der mit dem eingegebenen Text übereinstimmt
-Über "Esc" kann man die Liste wieder schließen
-Wenn man bei aufgeklappter Liste die "Enter"-Taste drückt, wird das Häkchen beim ausgewählten Eintrag aktiviert bzw. deaktiviert (je nach Zustand)
-Mit den Pfeiltasten kann man sich in der Liste bewegen
-Über die "Entf"-Taste können alle Häkchen zurückgesetzt werden.

**Comment by AnneSchueller** [comment]
Das hört sich super an. Dann schließe ich das Issue.
