### ISSUE TITLE
Fehlende Option in der Versetzungstabelle  und Fehler bei der Migration

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#860]
Zur Berechnung des richtigen Abschlussdatums müssen wir an den WBKs in der Regel in jedem Semester neue Eintragungen in der Klassen und Versetzungstabelle vornehmen. Wir nutzen dafür immer unsere interne Anleitung. Dabei ist wichtig, ob der Kurs in einem Sommersemester begonnen hat:
<img width="246" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/501e3331-3478-4cf5-a4b5-4f8a6a407faa">

<img width="380" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/4f65006b-1d32-4930-997f-64cc807c697f">

Aktuell ist die Möglichkeit noch vorhanden:
<img width="489" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/880f3050-45a6-4dbd-9b65-d003018d8cb3">

In Schild 3.0 fehlt die Option:
<img width="234" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/662136c6-ef15-40f2-ade9-847eaaeb7f3b">

**Außerdem wurden beim Import die Restabschnitte nicht übertragen!**

**Comment by AnneSchueller** [comment]
Du meinst mit fehlende Option den Eintrag, ob SuS zum SS begonnen haben oder? 
Das ist doch das unterste Auswahlfeld in Schild3, was auch in deinem Screenshot sichtbar ist.

Die Restabschnitte fehlen hier tatsächlich. In der Tabelle Klasse ist hierfür auch gar kein Feld vorgesehen. Soll das an dieser Stelle berechnet werden aus der Info zum Semesterstart?

**Comment by JuergenRichter** [comment]
Es gibt bei den Klassen keine Restabschnitte mehr, das wird über die Jahrgänge geregelt. Es wird aber die Einstellung "Schüler der Klasse haben zu einem Sommersemester begonnen" berücksichtigt.
