### ISSUE TITLE
Anzeige "Vorschau Schule" bei den WBKs

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#862]
In der Anzeige der Vorschau der Schule steht 1. Semester. Kann die Bezeichnung nicht aus den Angaben zu den Abschnitten genommen werden:
<img width="561" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/68098a5b-edbd-4841-8289-f1019c3d7d0f">

Z.B. WS oder SoSe für Wintersemester und Sommersemester
<img width="318" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/698f1eaa-8568-45f8-aa47-231670f48085">

**Comment by JuergenRichter** [comment]
Vorschlag: Wir geben bei WBKs die Kürzel zusätzlich in Klammern an:
1. Semester (WS)

**Comment by AnneSchueller** [comment]
Finde ich gut.
@Kluesenerm: Was meinst du?

**Comment by JuergenRichter** [comment]
Ist umgesetzt
