### ISSUE TITLE
Schnellzugriff konfigurieren

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#863]
Alle Kolleginnen und Kollegen nutzen bei uns Schild. Daher ist der Schnellzugriff ein zentrales Element zum Drucken von Listen für die Kolleginnen. Ich kann den Schnellzugriff zwar einschalten, aber nicht konfigurieren. Außerdem wäre eine Erweiterung auf 20 Elemente wünschenswert.

**Comment by JuergenRichter** [comment]
Der Report-Schnellzugriff kann doch von den Nutzern nun selbst konfiguriert werden, die Einstellungen werden personenbezogen gespeichert. Es können aber nur solche Reports zugeordnet werden, die sich im Ordner \SchILD-Reports\Standard\Schnellzugriff befinden.

**Comment by AnneSchueller** [comment]
Ich kann die Reports zuweisen und diese werden auch in der Schnellansicht sichtbar. Aber nach einem Neustart von Schild kann  ich diese nicht drucken. Ein Klick hier bleibt ergebnislos:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/c551c405-b38f-4d86-805e-1d9f5b8a42bc)

**Comment by FrodBRA** [comment]
> Es können aber nur solche Reports zugeordnet werden, die sich im Ordner \SchILD-Reports\Standard\Schnellzugriff befinden.

Macht das Sinn?  Der Schnellzugriff ist nach meinem Ermessen nach gerade dafür da, schnell auf Reports zuzugreifen, die sonst irgendwo in der Struktur liegen.

Müssen diese nun in einem bestimmten Ordner liegen, wird für alle anderen eine konsistente Ordnerstruktur gestört. 

Zum Bespiel würde das Sekretariat oder die Abteilung 8-10 bestimmte Reports immer wieder brauchen und diese in den Schnellzugriff packen, andere Leute würden die Reports aber eher in den Ordner "Sekretariat" oder eben "Abteilung 8-10" vermuten. Die liegen aber nun in "Schnellzugriff" und damit ist keine konsistente Ordnerstruktur aufbaubar - oder noch schlimmer, Reports würden nun in zwei unterschiedlichen Versionen an zwei Orten liegen. Dazu kommt, dass im Ordner "Schnellzugriff" nun 30, 40 oder auch mehr Reports liegen, da alle Teilnehmer, die sich welche setzen wollen, ihre Reports komplett unsortiert dort ablegen müssen.

**Comment by JuergenRichter** [comment]
Durch die Beschränkung auf den Ordner "Schnellzugriff" wird erreicht, dass nur "erlaubte" Vorlagen in den Schnellzugriff übernommen werden könnemn. Damit soll verhindert werden, dass "jeder Hinz und Kunz" z.B. ein Abschlusszeugnis drucken kann.

**Comment by FrodBRA** [comment]
Das finde ich grundsätzlich nachvollziehbar, jedoch überwiegen die von mir angeführten Argumente in Bezug auf die generell Organisation der Reporte nach meiner Interpretation diese sehr deutlich.

Die Frage nach einem Rechtemanagement auf der Reportebene wäre ja eine viel größere. Hier über den Schnellzugriff einzugreifen erscheint mir dafür aber eher ungeeignet.

Was hier überlegt werden könnte ist ein "Zeugnisverzeichnis" (mit dann frei anlegbaren Unterordnern) vorzusehen, das - wie auch immer - gesondert geschützt wird.

Diese Debatte erscheint mir grundsätzlicher Natur bezüglich der generellen Ausrichtung des Reporting. Wird ein Rechtemanagement in Bezug auf Zeugnisse und auch die Ablage von Dokumenten im Zeugnisverzeichnis benötigt?

@AnneSchueller @Raffenberg @FPfotenhauer

**Comment by AnneSchueller** [comment]
Ich sehe das ähnlich wie Herr Frodermann:

Ich vermute, dass die Schulen im Reportverzeichnis für einzelne Arbeitsbereiche wie beispielsweise "Mittelstufe" Unterordner anlegen werden. Möchte der Mittelstufenkoordinator nun zusätzlich den Schnellfilter benutzen, würde im Ordner Schnellzugriff wahrscheinlich eine Kopie des Reports hinterlegt werden, was beim Anpassen von Reports zu Inkonsistenzen führen könnte.

**Comment by kroerig** [comment]
Ja, so ist es hier auch. Für jeden Organisationsbereich gibt es einen Order (mit div. Unterordnern) mit den zugehörigen Reports.

Ich finde ich die Idee mit dem zusätzlichen Ordner für den Schnellzugriff auch ungeschickt. Im Schnellzugriff sollte man Reports hinterlegen, die man selbst häufig braucht; egal wo im Dateisystem sie sich befinden. Und nicht die, die der Admin für würdig erachtet.

**Comment by FrodBRA** [comment]
Was war hier soweit das Ergebnis der Debatte?

Wurde der Schnellzugriff so erweitert, dass wieder alle Reports, auf die ein Nutzer Windows-Freigabe-Zugriff hat angewählt werden können?

@JuergenRichter

**Comment by FrodBRA** [comment]
Wo sind Reports für den Schnellzugriff zuweisbar? Ich habe einen Report in Standard/Schnellzugriff geschoben, finde aber gerade gar nicht, wo ich das auswählen kann.

Davon abgesehen sollte nach m.E. die Beschränkung auf den Ordner "Schnellzugriff" aufgehoben werden.

Die Zuweisung ist jetzt individuell benutzergebunden, korrekt?

**Comment by AnneSchueller** [comment]
Hier kann das ausgewählt werden, sofern die Einstellung "Schnellzugriff ermöglichen" ausgewählt ist:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/d57d780f-c18b-483f-9637-06792f779370)

Ich fände es auch absolut sinnvoll, den Schnellzugriff auf den gesamten Report-Ordner zu erweitern um redundante Reports zu vermeiden.

**Comment by FrodBRA** [comment]
Danke.

(Wäre voll smart gewesen, in den passenden Wiki-Artikel zu gucken ;))

**Comment by AnneSchueller** [comment]
Ich sehe dort keine Sicherheitsprobleme. Über den Reportexplorer gelangt der User ja so oder so auch an andere Reports. Den Zugriff/Bearbeitung kann auch zusätzlich über die Benutzerverwaltung geregelt werden.
m.E. kann das so umgesetzt werden.

**Comment by JuergenRichter** [comment]
Das Problem mit den Umlauten ist behoben, auch können jetzt aus jedem Verzeichnis Vorlagen dem Schnellzugriff hinzugefügt werden. Ich schließe das Issue daher.
