### ISSUE TITLE
"Scrollrad" um Farbe in "Einstellungen -> Ind. Einst." -> Farbe für statistikrelevante Felder führt zu Zugriffsverletzung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#864]
Version 3.0.78.14

Beim Scrollen mit dem Mausrad im Dropdown-Menü zu "Farbe für statistikrelevante Felder" wird eine Zugriffsverletzung erzeugt. SchILD läuft im Anschluss korrekt weiter.

Das Scrollen per Balken funktioniert.

PS zur Schreibweise: "statistik-relevante" sollte "statistikrelevante" ohne Bindestrich sein.

**Comment by AnneSchueller** [comment]
[Statistikfarben_scrollen.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13665482/Statistikfarben_scrollen.txt)

**Comment by JuergenRichter** [comment]
Behoben
