### ISSUE TITLE
Fehlermeldung beim Klick auf "Programm beenden"

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#865]
Klick auf Verwaltung/Programm beenden erzeugt Fehlermeldung:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/494090af-f159-4b83-a24b-bd654c2346b8)

[SchILD30_Prog_Beenden.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13682985/SchILD30_Prog_Beenden.txt)

Programm wird anschließend nicht beendet.

**Comment by JuergenRichter** [comment]
Schon behoben
