### ISSUE TITLE
SVWS v0.8.3 Installation - Umlaute werden nicht richtig dargestellt

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#866]
Bei der Installation des SVWS Servers in der Version 0.8.3 werden die Umlaute nicht richtig dargestellt. Ich habe noch einmal die Version 0.7.9 installiert: dort werden alle Umlaute richtig angezeigt.

![Umlaut](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/5a5bf025-60c2-487c-aa3f-6432f1fc4153)

![Umlaut_passt](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/670ff54c-13f0-4938-b1be-4851a6d60a0c)

**Comment by FPfotenhauer** [comment]
Haben wir schon auf dem Schirm. Da wurde wohl beim Umzug in das Mono-Repository einiges auf UTF8 umgewandelt.
