### ISSUE TITLE
Verbesserungsvorschlag - Schüler - Sortierung - die Begriffe im Auswahlfenster sollten alphabetisch geordnet sein

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#867]
Ist es möglich, im Menü Sortierung (Kartenreiter Schüler) die Begriffe im linken Fenster alphabetisch geordnet anzeigen zu lassen? 

![alphabetisch](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/30cc1e17-b10e-48af-8eac-ea2cae04f99e)

**Comment by JuergenRichter** [comment]
Sieht jetzt so aus:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/88121eec-1e09-4984-80fc-2a2a776a6f90)
