### ISSUE TITLE
Keine Serververbindung seit Update von Schild u. SVWS-Server

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#868]
Schild-Version 3.0.79.14 vom 15.12.23
SVWS-Version: v0.8.3

Seit dem Update kann ich Schild nicht mehr starten. Der SVWS-Java Service wird immer beendet. Ein Neustart führt nicht zum Erfolg. Den Client kann ich auch nicht mehr starten. Eine neue Migration funktioniert ebenfalls nicht (mit migrateDB.exe).
Woran könnte das liegen?

[svws_server_service.err.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13689500/svws_server_service.err.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13689501/svws_server_service.out.log)
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13689502/svws_server_service.wrapper.log)
[2023_12_15.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13689503/2023_12_15.request.log)
[2023_12_14.request.log](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13689504/2023_12_14.request.log)

**Comment by FPfotenhauer** [comment]
Da steht access denied for user "Test".
Was steht denn da in deiner svwsconfig.json und stimmen User und Passwort?

**Comment by AnneSchueller** [comment]
Ich konnte den Fehler nicht finden. Nach Neuinstallation funktioniert es wieder.
