### ISSUE TITLE
Skalierungsfehler Gruppenprozesse und Auswahl: "Datumswahlfeld"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#869]
Version 3.0.78.14

Unter dem Reiter "Individualdaten ändern" kommt es bei allen Datumswahlfeldern zu Skalierungsfehlern (hohe Auflösung in Windows, Skalierung >100%).

![Riesenkalender](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/9c207826-072f-4adf-9db8-d636f96680e1)

Dies betrifft alle Datumswahlfelder in 
* Individual-Daten I
* Lernabschnitte
* Schulbesuch

Die Datumswahlfelder im Reiter "Auswahl" sind auch alle zu groß skaliert und müssen überarbeitet werden.

Hierbei viel mir auf, dass unterschiedliche Typen von Datumswahlfelder verwendet werden, z.B. sieht das für "Deutschförderung" in "Individual-Daten II" anders aus (und funktioniert). Eventuell sollte hier eine Anpassung aller Datumsfelder stattfinden.

**Comment by AnneSchueller** [comment]
An meinem Rechner sieht das mit Version 3.0.79 gut aus. Ich meine, dass wir das schonmal als Issue formuliert hatten, vielleicht wurde hier etwas geändert? 
Könntest du das evlt. nochmal mit der Folgeversion testen und das Issue ggf. schließen?

**Comment by FrodBRA** [comment]
3.0.79.14: sieht noch aus wie im Screenshot aus v 3.0.78.14

3840x2160, Skalierung 150%

**Comment by JuergenRichter** [comment]
Die betreffenden Komponenten wurden durch andere ("skalierungsfeste") ersetzt.
