### ISSUE TITLE
Bindestriche "Individual-Daten" -> "Individualdaten"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#870]
3.0.78.14

Nach meinem Sprachgefühl und den im Duden aufgeführten Richtlinien sind die Bindestriche in den Reitern "Individual-Daten" nicht zu setzen:

https://www.duden.de/sprachwissen/rechtschreibregeln/bindestrich

Eine Entfernung würde auch die Felder in "Auswahl" betreffen.

Die Schreibweise in Gruppenprozesse "Individualdaten ändern" ist korrekt, die Schreibweise in den Reitern in diesem Prozess nicht.

**Comment by JuergenRichter** [comment]
Behoben
