### ISSUE TITLE
Statistikrelevante Felder in "Lehrkräfte" sind nicht durch einen Stern gekenneichnet

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#871]
3.0.78.14

Die statistikrelevanten Felder in "Lehrkräfte" sind per Standard nicht mit einem "*" gekennzeichnet und sind wie die nicht-statistikrelevanten "Fettdruck in schwarz".

Die Felder sind SchILD aber durchaus bekannt, färbt man sie individuell ein, werden die statistikrelevanten Felder korrekt hervorgehoben.

**Comment by JuergenRichter** [comment]
Behoben
