### ISSUE TITLE
Skalierungsfehler Lehrkräfte -> Zeitabhängige Daten -> Pflichtstunden soll (in 45 Minuten Einheiten)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#872]
3.0.78.14

Das oben genannte Feld passt nicht zweizeilig in die Bereich bei hoher Skalierung

**Comment by AnneSchueller** [comment]
Bei einer Skalierung von 150 wird das bei meinem Bildschirm zwar abgeschnitten (ca. 1/4 der Schrift fehlt unten) , aber man kann es noch lesen. Daher habe ich die Priorität nun erstmal auf niedrig gesetzt.

**Comment by Kluesenerm** [comment]
In Münster erhalten alle Schulleitungen VPN-Geräte. Auflösung ist dort 1920x 1080 und ich müsste eigentlich mit der vom System empfohlenen Textgröße 150% arbeiten. Es gibt eine Vielzahl von Fenstern (z.B. Klassen und Versetzungstabelle das Fenster aktuell ausgewählte Klasse;  Unterrichtsfächer -> Details; Lehrkräfte -> Basisdaten) bei denen Felder abgeschnitten sind oder gar nicht erst angezeigt werden. Bei einer Textgröße von 100% wird auf dem Laptop zwar alles dargestellt, aber dann benötige ich trotz Bildschirmarbeitsplatzbrille eine Lupe.

**Comment by FrodBRA** [comment]
Können Sie bitte ein paar Screenshots posten? Hier scheint noch mehr vorzugehen, denn SchILD-NRW 3 in FullHD bei 100% sollte eigentlich gut aussehen. Eventuell müsste hier auch die tatsächlich eingestellte Auflösung noch einmal in Windows überprüft werden.

Die für FullHD von Windows empfohlene Skalierung ist zuerst einmal nur 100%, das lief bislang auch ohne Probleme. Erst bei einer höheren Auflösung, dies gilt auch für 4k-Auflkösung (3840*2160), empfiehlt Windows erst 150%, das sollte bei FullHD nicht notwendig sein.

**Comment by Kluesenerm** [comment]
Die empfohlene Auflösung hängt bei Windows vom Endgerät ab. Bei den VPN-Geräten der Stadt-Münster ist es z.B. 150%. 
Ich habe zum Vergleich einmal meinen Macbook mit im Bild, damit die Schriftgröße bei 100% bei diesen Notebooks ersichtlich wird:
![IMG_2602](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/be49f2ea-f25d-4167-ae57-7ffcb0336ae9)

**Comment by Kluesenerm** [comment]
Hier ein Screenshot bei Empfohlenen Einstellungen auf dem Laptop. MIt den Einstellungen ist der Laptop auch in allen anderen Programmen (Outlook, Word , ...) sehr gut zu benutzen. Nur nicht mit SchILD:
<img width="937" alt="Anmerkung 2023-12-28 105114" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/8d11fb7e-d9c2-4030-9f2e-97c8779f3c98">

**Comment by Kluesenerm** [comment]
So sieht die Seite Individualdaten I aus. Hier ist sicherlich viel zu optimieren. Es gibt über der Karteikarte des Schülers eine große Freifläche, die dynamisch nach aufgerufener Karteikarte verändert werden müsste. Die "Ribbonleiste" sollte evtl. als Option ausklappbar gestaltet werden:

<img width="960" alt="Anmerkung 2023-12-28 110429" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/99c5aa7c-42fb-47a3-9de6-094611024e8a">

**Comment by FrodBRA** [comment]
Das Erscheinungsbild ist jedenfalls normal und nicht auf einen Fehler zurückzuführen. Ob hier noch etwas angepasst werden soll oder kann, vermag ich nicht zu sagen, das muss an die Entwicklung kommentieren.

Soweit ich das hier spontan, als Laie und mit größeren Bildschirmdiagonalen direkt im Vergleich beurteilen kann, verhalten sich die Schriftgrößen meinem Word/Outlook/Windows komplett analog zu dem Erscheinungsbild von SchILD-NRW 3. Der Text in der Ribbonleiste meines Outlooks ist absolut identisch zu SchILD (sieht wie Arial/Calibri in Standardgröße aus). Die Schaltflächenbeschriftungen in Word sind sogar noch kleiner, ebenso sind die Schriften in der Taskleiste komplett vergleichbar, ebenso habe ich gerade ein paar weitere Windows-Programme geöffnet und sehe hier kein besonderes Verhalten von SchILD. Aber wie gesagt: Ich bin hier keine Autorität.

Die Frage ist letztendlich auch eine der Arbeitsplatzergonomie, ein SchILD-Arbeitsplatz sollte meiner Auffassung nach auch mit einem für entspanntes Arbeiten ausreichend großen Monitor ausgestattet sein. Davon abgesehen profitieren auch Word und Outlook von modernen Ergonomiestandards entsprechenden Monitoren.

Sofern sich das Problem nicht durch für die Arbeit angemessene Monitore bzw. die Hilfen von Windows selbst angehen lässt, wäre SchILD in der Tat noch mit einer Skalierung von 150% in FullHD zu testen.

Hier besteht so wie ich das übersehe in der grundsätzlichen Frage nach der UI ein viel weiteres Spektrum an Themen und Diskussionen, dass ich glaube, dieses - an sich ja sehr kleine und bald zu schließendes - Issue stellt einen deutlich zu kleinen Rahmen bereit.

**Comment by AnneSchueller** [comment]
In dem Beispiel oben (Kataloge-> Klassen/Versetzungstabellen Bereich "Aktuell ausgewählte Klasse") wäre eine Anpassung m.E, notwendig. Beim WBK werden hier 2 weitere Zeilen abgebildet, sodass der Platz dann nicht mehr ausreicht.
@JuergenRichter : Gäbe es hier die Möglichkeit, ggf. einen Scrollbalken einzufügen?

**Comment by FrodBRA** [comment]
Das besagte Feld ist ja schon zuvor mit Fehlern aufgefallen und es in der täglichen Arbeit dazu gedacht, eine Schnellübersicht zu bieten. Scollbalken würden das Problem sicher nicht besser machen.

Wäre es möglich, das Layout der Feldinhalte so anzupassen, dass alle theoretisch möglichen in Kombination erscheinenden Inhalte hinein passen?
