### ISSUE TITLE
SVWS Server erstellt kein Zertifikat

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/Schild3-BetaTest#873]
Einen schönen 3. Advent in die Runde!

Nach einer Einladung unseres Fachberaters, SchILD3 an einem Einzelplatz zu testen, habe ich mich heute an der Installation des SVWS-Servers versucht. 
Nach dem Download der beiden Dateien win64-installer-0.8.3.exe und Setup_SchILD3_v3.0.79.exe habe ich den win64-Installer auf meinerm Windows11-Laptop gestartet. Leider tritt bei mir ein ähnliches Problem wir in Issue #480 auf (https://github.com/SVWS-NRW/Schild3-BetaTest/issues/480), Screenshots der Fehlermeldungen anbei.

Wie auch bei #480 wird bei mir das Dokumente-Verzeichnis von Standardspeicherort auf c:\Users\<Benutzername>\Documents auf ein anderes Laufwerk gemapt, falls das ein zusätzlicher Hinweis sein könnte. Außerdem habe ich noch folgenden Eintrag in der Datei keystore.log gefunden:
"Keytool-Fehler: java.lang.RuntimeException: java.io.IOException: DNSName components must consist of letters, digits, and hyphens"

Falls ich noch mit weiteren Logs aushelfen soll, gerne - ich würde die Installation dann nochmals starten, aktuell habe ich alles wieder deinstalliert. [Wo genau ist eigentlich die Batch-Datei zu finden, die alles löschen soll, was bei der Installation angelegt wurde?]

Danke und Gruß
Wichard Johannsen 

![Screenshot 2023-12-17 142656](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/154081487/a2f5a6b5-9507-4a9b-88d1-28f00dff775f)

Nach Klick auf OK:
![Screenshot 2023-12-17 142841](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/154081487/3851e6e9-07ac-4e6b-9fdb-3467ec1df6d4)

**Comment by FrodBRA** [comment]
>  [Wo genau ist eigentlich die Batch-Datei zu finden, die alles löschen soll, was bei der Installation angelegt wurde?]

Die ist meiner Kenntnis nach nicht öffentlich verfügbar? Hier der Inhalt as Copy&Paste zur schnelle Übersicht und Selbsthilfe, außerdem wird das Attachment .bat (korrekterweise) von git hier nicht erlaubt:
```
sc stop svws_server_service
sc stop svws_server_mariadb

timeout /T 5

sc delete svws_server_service
sc delete svws_server_mariadb

reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\SVWSServer" /va  /f
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\SVWS Server_is1" /va /f
reg delete "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\SchILD-NRW3_is1" /va /f
reg delete "HKEY_CURRENT_USER\Software\Schild3000" /va /f

timeout /T 8

rmdir /S /Q "C:\ProgramData\SVWS-Server" 
rmdir /S /Q "C:\Programme\SVWS-Server"
rmdir /S /Q "C:\Program Files (x86)\SchILD-NRW3"
del /F /Q "C:\SVWS-Arbeitsverzeichnis\Connection-Files\*.con"

pause
```

**Comment by FPfotenhauer** [comment]
Was wurde denn für das Zertifikat eingegeben?
Können Sie einfach mal was simples ohne Umlaute oder Sonderzeichen eingeben?

**Comment by FPfotenhauer** [comment]
Nachtrag: Ist der Rechner irgendwie in einer Domäne, die Sonderzeichen oder Umlaute enthält?

**Comment by WJohannsen** [comment]
Als Name hatte ich hier einfach nur SVWS angegeben. Gerätename ist ThinkBook_Jh, der Rechner nutzt ein Microsoft-Konto, Arbeitsgruppe ist WORKGROUP, nicht mit einer Domäne verbunden. System: Windows 11 Pro 23H2 auf einem AMD Ryzen 5.

**Comment by FPfotenhauer** [comment]
Ok. Dann müsen wir mal schauen, ob der Gerätename da irgendwie reinspielt.

**Comment by WJohannsen** [comment]
Update dazu: Ich habe meinen Rechner umbenannt in ThinkBookJh - nun wird das Zertifikat erzeugt.

**Comment by FPfotenhauer** [comment]
Danke für die Rückmelduing.
Ja, ein Unterstrich im Hostnamen ist nicht erlaubt.
Hatten Sie den leer gelassen?

**Comment by FPfotenhauer** [comment]
Sollte in der Versiom 0.8.4 behoben sein.

**Comment by FrodBRA** [comment]
"Behoben" heißt, dass Unterstriche in Zertifikaten erlaubt sind - oder dass der Gerätename eingesetzt wird?

**Comment by FPfotenhauer** [comment]
Unterstriche im DNS-Namen sind nicht zulässig.
Wir versuchen das abzufangen.
Bei der Installation von Windows 11 wird darauf übrigens hingewiesen, wenn der Gerätename abgefragt wird.

**Comment by WJohannsen** [comment]
Vielleicht zur Klarstellung: Im Zertifikatsnamen haben ich nur "SVWS" eingetragen, keinen Unterstrich.
Mein Rechner hieß seit Erstinstallation "ThinkBook_Jh" (mit Unterstrich), das wurde aber meiner Erinnerung nach bis zum Zeitpunkt des Fehlers in der Installation nicht abgefragt. An einen Hinweis bei der Ersteinrichtung des PCs, dass ein Unterstrich im Computernamen nicht zulässig sei, kann ich mich ehrlich gesagt nicht erinnern - allerdings war das Windows vorinstalliert, den Namen habe ich allerdings eingetragen.
