### ISSUE TITLE
Statistik: Gesamprüfung der Daten.

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#874]
Beim Start der Gesamtprüfung kommt bei mir folgender Fehler:

[Eureka.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13786928/Eureka.txt)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren, funktioniert bei mir einwandfrei. Bitte mal folgendes prüfen:

- Ist in der Datei "Schild-Programmverzeichnis\Vorlagen\StatistikDB.mdb" in der Tabelle VW_PLAUSIFEHLER das Feld "ERLEDIGT" enthalten?

- Falls nicht, sollte es eigentlich vom Programm angelegt werden. Dann bitte die Datei "SVWS-Arbeitsverzeichnis\Statistik\SratistikDB.mdb" prüfen, ob da in der Tabelle VW_PLAUSIFEHLER das Feld "ERLEDIGT" enthalten ist.

Grundsätzlich ist es m.E. aber besser, wenn schon in der "Vorlage" das Feld vorhanden ist (d.h. vom Programm nicht angelegt werden muss). Hier die entsprechende Datei:
[StatistikDB.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13809187/StatistikDB.zip)
Diese müsste dann in das Setup integriert werden.

**Comment by AnneSchueller** [comment]
Die Fehlermeldung konnte ich reproduzieren. In meiner StatistikDB fehlte die Tabelle VW_PLAUSIFEHLER.

Mit dem Speichern der oben angehängten StatistikDB in den Ordner Vorlagen klappt die Gesamtprüfung.

**Comment by JuergenRichter** [comment]
Ich habe mal in der Vorlage für SchILD2 nachgeschaut, da ist ebenfalls keine Tabelle VW_PLAUSIFEHLER drin. Ich vermute, dass diese Tabelle erst dort bei der Verwendung durch die IT-NRW-Module angelegt wird. Dabei wird aber nicht das Feld "ERLEDIGT" angelegt, dass aber in SchILD benötigt wird, damit dort eingetragen werden kann, ob ein Fehler abgearbeitet wurde. Dieses Feld wird daher in SchILD2 automatisch angelegt. Um letzteres in ScHILD3 zu vermeiden, wurde  die Tabelle VW_PLAUSIFEHLER in die Vorlagendatei eingefügt. Man muss daher darauf achten, dass die korrekte Datei im Setup enthalten ist.

**Comment by FPfotenhauer** [comment]
Ich habe die neue Vorlage in den Installer aufgenommen.
