### ISSUE TITLE
Installer bricht ab

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#875]
Auf einem 32bit Windows 10 bricht der Installer ab und löscht die kopierten Dateien wieder.
SchILD3 ist eine 32bit Software (installiert sich auch in den richtigen x86-Programme-Ordner)

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/878c8ef1-bfed-410f-ac9d-dbae6f7a2b95)

**Comment by FPfotenhauer** [comment]
Wir gehen von 64BIt-Systemen aus.

**Comment by kroerig** [comment]
Was aber falsch ist, wenn es eine 32bit Software ist. Die hat im 64bit Bereich einer Registry nicht zu suchen.
Die über das ZIP-File entpackte Version läuft ja unter 32bit.
