### ISSUE TITLE
Darstellung nach dem erste Start

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#876]
Beim ersten Start von SchILD stimmen die Maße der Inhaltsfelder nicht.
Scrollbalken sollte erst erscheinen, wenn der User das Fenster/den Bereich absichtlich unter das Mindestmaß verkleinert.
Ich habe absichtlich einen vollen Screenshot erstellt.

Auflösung: Full HD ohne Skalierung.

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/54fee4e1-cbd4-4ec6-8265-0bcf06d7669c)

**Comment by AnneSchueller** [comment]
Das Setzen der Startwerte bezüglich Spaltenbreiten wurde bereits mehrfach diskutiert. Ich stimme in diesem Fall zu, dass die Anfangswerte hier nicht optimal sind und einmalig nach der Installation angepasst werden müssten.
@JuergenRichter: Wäre hier eine Anpassung für die Startwerte bezüglich des Schülercontainers ohne Weiteres möglich?

**Comment by kroerig** [comment]
Gerade Version 3.0.81.9 installiert:
Irgendwie sieht das merkwürdig aus. Die Inhalte sind verschoben.

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/5148795/841ef6c6-a03a-42b4-8dcb-4d700bcc1e01)

**Comment by JuergenRichter** [comment]
Bitte nochmal mit der heute bereitgestellten Version 3.0.82 probieren.

**Comment by kroerig** [comment]
nein, gar nichts. Auch ein ändern des Farbschemas mit anschließendem Neustart des Programms ändert daran nichts.

**Comment by kroerig** [comment]
> Bitte nochmal mit der heute bereitgestellten Version 3.0.82 probieren.

Da waren sie schneller. Ich werde es probieren.

**Comment by kroerig** [comment]
Wo ist denn die Version? Github kennt das Release nicht. Da gibt es nur die 3.0.81

**Comment by kroerig** [comment]
Das sieht besser aus.
