### ISSUE TITLE
Farbe für statistikrelavante Felder wird nur im Kartenreiter Lehrer aktualisiert

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#877]
Schild Version: 0.79.14
SVWS-Server: 0.8.7
Wenn man die Farbe für die statistikrelevanten Felder verändert, so sind die Änderungen im Kartenreiter Lehrer sofort sichtbar. Im Kartenreiter Schüler werden die Überschriften der statistikrelevanten Felder jedoch so lange in der zuletzt eingestellten Farbe angezeigt, bis man einen Neustart gemacht hat oder im Kartenreiter Verwaltung im Abschnitt Schule das Menü Allgemeine Angaben geöffnet hat.

**Comment by JuergenRichter** [comment]
Behoben
