### ISSUE TITLE
Vorschlag: Dynamischer Link zum SVWS- Client

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/Schild3-BetaTest#878]
Für alle Aktionen, die mit Kursen u.ä. zutun haben, muss man ja demnächst den SVWS-Client verwenden. Das Ergebnis sieht man dann ja auch in SchILD. Hier fände ich es praktisch direkt über einen Link (z.B im Reiter Abitur und/oder im Kasten "aktueller Schüler") von SchILD zum SVWS Client wechseln zu können.

Und zwar am besten so, dass automatisch der entsprechende Schülerdatensatz aufgerufen wird und man sich nicht erneut anmelden muss.
Elegent wäre auch, wenn der SVWS-Client sich einfach als Brower-Frame in SchILD öffen würde. Dann gibt es keinen so großen Medienbruch.

**Comment by FPfotenhauer** [comment]
zu 1. Bitte hier keine Aktionen durchführen, die aufgrund der knappen Resourcen andere Bereiche aufhalten.

zu 2. Das würde den Eindruck erwecken, dass hier etwas "zusammenwachsen", soll, was m.E. nicht gewünscht ist.

**Comment by kroerig** [comment]
Der Vorschlag stammt aus der Praxis. Ich kenne es von anderen Migrationsprojekten wo genau so vorgegangen wurde. Funktionen, die im Desktop Client weggefallen sind wurden durch Browseraufrufe ersetzt.
Immer dann, wenn Funktionsblöcke in der neuen Software umgesetzt waren wurden sie in der alten im Menü bzw. an den entsprechenden Stellen durch einen Browserlink ersetzt.

Ein SSO scheint der SVWS-Client nicht zu unterstützen. Ein einfacher Link zum den SVWS sollte @JuergenRichter sicher hinbekommen.

**Comment by FrodBRA** [comment]
@AnneSchueller So wie ich die Projektentwicklungen verstehe, ist eine derartige Wechselbeziehung derzeit nicht vorgesehen und wir können das Issue erstmal schließen?
