### ISSUE TITLE
Verbesserungsvorschlag - Schüler - schlechte Lesbarkeit der ausgegrauten Felder beheben

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#879]
Schild Version: 0.79.14
SVWS-Server: 0.8.7

Ausgegraute Felder wie etwa im Reiter Individualdaten I im Bereich "Aktuelle Laufbahn" sind sehr schlecht lesbar. Ist es im Hinblick auf die Barrierefreiheit möglich, eine kontrastreichere Darstellung für gesperrte Felder einzustellen? 

![Ausgegraute Felde](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/18206291-d220-49b0-965a-ea39af5138ff)

**Comment by JuergenRichter** [comment]
Die Frage ist, wie wir kennzeichnen können, dass die Felder "read-only" sind (und der Benutzer sich nicht wundert, dass keine Eingabe möglich ist).

**Comment by AnneSchueller** [comment]
Evtl. könnte man die Überschrift in Schwarz lassen (Oder ein ganz dunkles grau) und  nur die Textfeldeingaben in grau? Diese vielleicht noch in einem dunklerem grau?

**Comment by JuergenRichter** [comment]
Ich teste das mal

**Comment by pemichalski** [comment]
Wie wäre es mit einem Schloss-Icon am linken oder rechten Rand des jeweiligen Feldes? Ich habe probeweise einen Screenshot gebastelt. Falls Bedarf besteht, kann ich gerne eine vernünftige Variante als Vektorgrafik (oder in jedem anderen gewünschten Format) erstellen. Das Schloss müsste dann etwas kleiner sein.

![Geperrte_Felder](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/737fba9f-d5db-48bc-93a6-e56f54134f34)

**Comment by pemichalski** [comment]
@JuergenRichter Mir ist beim Erstellen des Screenshots aufgefallen, dass der Einzug im Feld Schulbesuchsjahre rechtsbündig ist. In allen anderen Feldern ist der Einzug linksbündig. Ist das so gewollt?

**Comment by JuergenRichter** [comment]
Das wird defaultmäßig nach dem Feldtyp gesetzt:
Text: linksbündig
Zahl: rechtsbündig
Kann man aber auch ändern

**Comment by pemichalski** [comment]
> Das wird defaultmäßig nach dem Feldtyp gesetzt: Text: linksbündig Zahl: rechtsbündig Kann man aber auch ändern

Meiner Meinung nach sollte es überall gleich sein. 
Im Reiter Individualdaten 2 betrifft es die Felder Einschulung und EP-Jahre. Oder soll ich ein neues Issue dafür aufmachen.

**Comment by AnneSchueller** [comment]
Zur Bündigkeit:
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/882

Die Idee mit dem Schloss finde ich sehr charmant, wenn sich das ohne Probleme umsetzen lässt. Wenn das allerdings dazu führen könnte, dass die Darstellung je nach Monitoreinstellung verrutscht oder aus dem Bild verschwindet, das Schloss halb abgeschnitten ist usw. würde ich eine "einfachere" Lösung auf jeden Fall vorziehen.

**Comment by kroerig** [comment]
Das Schloss würde ich nicht in das Feld setzen sondern hinter die Feldbeschreibung. Da ist die Gefahr geringer, dass es durch Verkleinern oder Vergrößern verdeckt wird.

Alternativ könnte man auch den Mauszeiger, wenn er über einem gesperrten Feld ist in ein "Verbotsschild" ändern. Das haben ich letztens in eine Web-App gesehen.

**Comment by FrodBRA** [comment]
Ich schließe mich dem Vorschlag an, das Schloss hinter die Überschrift zu setzen. 

Sollte dies möglich sein, würde ich den Inhalt darunter dann gar nicht in den "Eingabetextboxen", sondern nur direkt als Zeichenkette auf dem Programmhintergrund ausgeben. Ohne "Eingabetextbox" ist vollkommen klar, dass diese Information dort an dieser Stelle nur ausgegeben wird und nicht verändert werden kann.

**Comment by kroerig** [comment]
dann braucht es kein Schloss. Aber es könnte ja durchaus sein, dass man die Daten an der Stelle ändern könnte. Nur der Benutzer darf es nicht. Dann signalisiert das Schloss "Eingabefeld gesperrt".

**Comment by kroerig** [comment]
Analog zu SchILD3 sollte diese Anpassung dann auch im SVWS Client stattfinden.

**Comment by JuergenRichter** [comment]
Wegen dem Schloss-Symbol. Da sollte in SchILD3 das Symbol aus der zugehörigen Icon-Collection verwendet werden, da gibt es zwei, eckig (lock.png) und rund (lock2.png). Welches sollen wir nehmen?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/0ca4eb12-5e56-4a43-9eed-8f6a4ec0646d)

**Comment by JuergenRichter** [comment]
"dann gar nicht in den "Eingabetextboxen", sondern nur direkt als Zeichenkette auf dem Programmhintergrund ausgeben."

Das hatten wir schon mal. Das sieht aber merkwürdig aus, wenn ein Feldinhalt leer ist, dann steht da eine Überschrift scheinbar nutzlos herum.

**Comment by AnneSchueller** [comment]
Zum testen fände ich lock.png hinter der Feldbeschreibung gut.

**Comment by JuergenRichter** [comment]
"Das mit den leeren Feldern verstehe ich nicht ganz. Da würde die Überschrift auch ohne Schloss nutzlos herumstehen. Aber vielleicht meine ich auch das falsche."
Mit dem Rahmen sieht man aber, dass da was stehen könnte, wenn da gar nichts zu sehen ist, sieht das komisch aus.

**Comment by FrodBRA** [comment]
Wollte man das so darstellen, könnte man einfach bei einem leeren String "kein Eintrag" in Dunkelgrau oder kursiv setzen.

**Comment by kroerig** [comment]
Für mich bedeutet ein Schloss in einem Eingabefeld immer, dass das Feld zum Bearbeiten gesperrt ist. Nicht, dass es "nur Lesen ist".
Ich klicke dann immer auf das Symbol in der Erwartung die Bearbeiten-Funktion damit freischalten zu können. So ist das bei vieler Software, mit der ich regelmäßig arbeite.

Dann wäre ich wieder bei "grauer Hintergrund". Das ist die übliche Darstellung für nicht beschreibbare Felder. Schwarze Schrift auf mittelgrauem Hintergrund. Für die Barrierearmheit muss nur der Kontast hoch genug sein,.

BTW: warum besteht das Iconset aus PNGs? Die skalieren nicht verlustfrei.

**Comment by JuergenRichter** [comment]
Hier mal die Version mit grauem Hintergrund
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/52c9b766-7a8a-4909-9d3c-08868b3a7c06)

**Comment by JuergenRichter** [comment]
Es gibt j noch den folgenden Fall:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/c71f6861-de02-442f-a1b3-760c13b394c2)

Da müsste eine Lösung für die Checkboxen gefunden werden, oder man ersetzt das durch "Ja/nein" und stellt das auch mit grauem Hintergrund dar.

**Comment by kroerig** [comment]
Wenn die Schrift hier normal ist, dann lassen sich auch die Checkboxen ausgrauen.

**Comment by Raffenberg** [comment]
Ich würde die Schrift so wie im letzten Vorschlag einfach nur grau setzen. Ggf. etwas dunkler, so dass man es etwas besser lesen kann. In der Regel findet man diese Umsetzung doch überall und ist das so gewohnt. Das würde auch das Problem mit den Checkboxen lösen. Icons würde ich nicht setzen.

Bei den Schulbesuchsjahren konnte man ja bisher den berechneten Wert immer überschreiben. Ich lann das gerade nicht testen. Wenn das in Schild3 noch immer so ist, würde ich da eher ein "Calculated" Icon anheften. Wenn man auf das Icon klickt, werden die Schulbesuchsjahre neu berechnet. Man kann das aber auch einfach so lassen.

Beispiel für ein Icon
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/48889965/aaae302d-22b2-4be9-8a75-6c3eea169cf0)
 
Neben dem Iconset gibt es auch noch Icons gratis hier als SVG und PNG: https://fontawesome.com/search
Bei nutzung müsste man nur irgendwo eine Namensnennung hinterlegen (Infos zum Programm etc.)

**Comment by kroerig** [comment]
> Ich würde die Schrift so wie im letzten Vorschlag einfach nur grau setzen. Ggf. etwas dunkler, so dass man es etwas besser lesen kann. In der Regel findet man diese Umsetzung doch überall und ist das so gewohnt. Das würde auch das Problem mit den Checkboxen lösen. Icons würde ich nicht setzen.

Aktuell ist der Text aus meiner Sicht zu hell. Ich kenne es nur so, dass gesperrte Elemente grau interlegt werden, die Schriftfarbe aber bleibt gleich.

Wenn es im Barrierefreiheit geht: https://www.linkedin.com/in/nina-gerling

**Comment by kroerig** [comment]
Das muss dann im SVWS aber genauso umgesetzt werden, damit die UX hier nicht unterbrochen wird.

**Comment by JuergenRichter** [comment]
So könnte man es umsetzen
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/402f458d-d9f2-4596-b56d-7bf5515541d3)

Ich habe versucht, das "Checkboxquadrat" auch grau zu hinterlegen, das funktioniert aber nicht

**Comment by JuergenRichter** [comment]
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/0f4d10ce-37db-42bc-ae37-f5d17aa802d8)

**Comment by Raffenberg** [comment]
So finde ich das gut

**Comment by kroerig** [comment]
Ja, so ist dann auch klar: weiße Fehler können beschrieben werden, graue nicht.

**Comment by JuergenRichter** [comment]
Hier die (hoffentlich) finale Version:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/06f87c35-8cdc-4960-bef0-85e225bc38b7)

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/eb8274b6-170f-43b6-ac1f-ff1ace2ad8a1)

**Comment by AnneSchueller** [comment]
Da hatte ich das Issue zu voreilig geschlossen...
Die finale Version finde ich auch gut.
