### ISSUE TITLE
Förderschwerpunkte

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#88]
Auf den Seiten Individualseite II und Aktuelles Halbjahr wird der Förderschwerpunkt und der weitere Förderschwerpunkt dargestellt.
Die eingabe beim weiteren Förderschwerpunkt hat schon immer zu Verwirrung geführt, da ausschließlich bestimmte Kombinationen mit dem Hauptförderschwerpunkt für die Statistik möglich sind. Das Feld weiterer Förderschwerpunkt kann entweder frei bleiben oder es können die Förderschwerpunkte Lernen oder Geistige Entwicklung eingegeben werden. Das macht deutlich, dass an dieser Stelle der Bildungsgang für das Kind abgefragt wird. Wenn das Kind im Bildungsgang GS, HS, RS oder GYM gefördert wird, bleibt das Feld leer. Wenn das Kind im Bildungsgang Lernen gefördert wird muss der Förderschwerpunkt Lernen eingegeben werden und im Bildungsgang Geistige Entwicklung der Förderschwerpunkt Geistige Entwicklung.
Vielleicht kann die Verwirrung beseitigt werden, wenn das Feld >weiterer Förderschwerpunkt< deshalb die Bezeichnung >Bildungsgang< bekommt.

**Comment by FPfotenhauer** [comment]
Leider wünschen sich die Schulen, dass man dort einen zweiten FSP eintragen kann.
Aus diesem Grund wird dort auch bei der Statitsik ignoriert, wenn dort falsche Kombinationen eingetragen werden.
Es werden nur gültige Kombis exportiert.
