### ISSUE TITLE
WBK Feld SommerSem

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#880]
Brauchen wir bei den Klassen das Feld "SommerSem" für das WBK noch?

**Comment by ThomasBachran** [comment]
Die Klassentabelle ist ja mittlerweile Schuljahresabschnittsbezogen. Damit wäre das Feld dann ggf. redundant.

**Comment by JuergenRichter** [comment]
Ja, das wird noch für die Berechnung des voraussichtlichen Abschlussdatums benötigt. Das wird ja grundsätzlich erst mal aus den Restabschnitten bei den Jahrgängen ermittelt, bei den WBKs wird aber zusätzlich die Information benötigt, ob die SuS zum Sommer- oder Wintersemester begonnen haben.

**Comment by Kluesenerm** [comment]
Das ist korrekt. Diese Feld wird für die Berechnung für das Ende des Schulbesuches benötigt. 
Wir müssen aktuell nach folgender Tabelle die Eintragungen für unsere Semester nach jedem Semesterwechsel (also jedes Halbjahr) korrigieren:
<img width="300" alt="Bildschirmfoto 2024-01-04 um 09 58 57" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/267b005d-3082-4171-b48e-7f571e219e9f">

**Comment by FPfotenhauer** [comment]
Das können wir aber jetzt, wo die Klassentabelle abschnittsbezogen gespeichert wird automatisch "mitnehmen".

**Comment by JuergenRichter** [comment]
Setze ich um

**Comment by JuergenRichter** [comment]
Ich habe mal nachgeschaut: Das Feld "SommerSem" (bzw. dessen Inhalt) sollte in SchILD3 eigentlich jetzt schon beim Hochschreiben übernommen werden.

**Comment by Kluesenerm** [comment]
Ja, wenn ich die Frage richtig verstanden habe. Das sieht man auch oben in unserer Tabelle.

**Comment by JuergenRichter** [comment]
Toggle-Prozess ist umgesetzt
