### ISSUE TITLE
Feld KoopKlasse

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#881]
Hat das Feld "KoopKLasse" in der Tabelle Klassen eine Auswirkung in Schild-NRW?
Oder ist das ein reines Feld für die Statistik?

**Comment by FPfotenhauer** [comment]
Nachtrag. Laut IT.NRW kann das Merkmal entfallen, es wurde 2018 aus der sim.txt entfernt.
Wir würde es dann auch entfernen.

**Comment by JuergenRichter** [comment]
Das Feld wird in SchILD nicht benötigt.

**Comment by JuergenRichter** [comment]
Ich habe gerade gesehen, dass das Feld in der aktuellen SchILD-Version doch noch verwendet wird, u.a. wird es in die StatistikDB exportiert. Ich kann das im nächsten Update aber rausnehmen.

**Comment by FPfotenhauer** [comment]
Danke.

**Comment by JuergenRichter** [comment]
Feld ist nun in SchILD3 raus.
