### ISSUE TITLE
Bündigkeit von Textfeldern

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#882]
Für die meisten Bereiche finde ich einheitlich linksbündig übersichtlicher... 
Schüler-> Individualdaten I (Schulbesuchsjahre)
Schüler -> Individualdaten II 
Auswahl -> Individualdaten II
Auswahl -> Lernabschnitt/Leistungsdaten
Bei der Stundenzusammenfassung der Lehrkräfte finde ich die Rechtsbündigkeit passend.

**Comment by JuergenRichter** [comment]
Ich habe das mal ausprobiert, ob man Zahlenfelder linksbündig darstellen kann. Leider lassen sich die Darstellungskomponenten nicht so leicht "übertölpeln". Ich probiere es aber weiter.

**Comment by JuergenRichter** [comment]
Für Felder, die nur zur Anzeige benutz werden, könnte man das machen.
