### ISSUE TITLE
Übergangsempfehlung JG 5 fehlt ab Klasse 8 und höher

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#883]
Mir ist aufgefallen, dass in Schild3 die Übergangsempfehlungen der Grundschulen ab JG 8 und höher nicht angezeigt werden, wenn es sich um eine Gymnasial- bzw. eingeschränkte Gymnasialempfehlung handelt. Durch Jens Raffenbergs Hilfe habe ich erfahren, dass in der Spalte "Kurztext" der Tabelle "SchuelerUebergangsempfehlung5Jg" der Datenbank asdtabs am 6.1.2021 die Gezeichnungen Gy und R/Gy in "GY", "R/GY" (mit großem Y!) geändert wurden. Leider wurde das bei den derzeit aktuellen Jahrgängen ab JG 8 und höher nicht aktualisiert. Bei Schild2 funktioniert das Pulldownmenü der Übergangsempfehlung wahrscheinlich deshalb nicht so, wie es sein sollte (siehe Bild).
![Schildfehler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/07f995a0-4a69-4572-a7dd-41c590463495)
Bei Schild3 werden wie gesagt die Übergangsempfehlungen ab JG 8 und höher (Einschulung vor 6.1.2021) gar nicht angezeigt, obwohl die Eintragungen in der Maria-DB vorhanden sind.
Meiner Meinung nach wäre die sauberste Lösung ein Update von Schild2, bei dem sämtliche Eintragungen der Übergangsempfehlungen mit kleinem Ypsilon (Gy und R/Gy) durch ein großes Ypsilon ersetzt werden. Das hätte auch den Vorteil, dass das Schild2-Pulldownmenü vernünftig funktionieren würde und auch Reports, die auf die Übergangsempfehlungen zurückgreifen, würden fehlerfrei arbeiten. Das Ganze ist mir nämlich aufgefallen, weil ein Report, den ich erstellt hatte, die Gymnasialempfehlungen ab JG 8 nicht auflistete. Siehe auch hier: 
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=6272

**Comment by ThomasBachran** [comment]
@AnneSchueller : Kannst du mir hierzu weitere Informationen liefern, welchen Bezug das zum SVWS-Server hat? Liegen hier fehlerhafte Einträge in der SVWS-DB vor?

**Comment by Raffenberg** [comment]
@ThomasBachran 
Hallo Thomas,
in der ehemaligen ASDTABS.mdb erden die Übergangsempfehlungen groß geschrieben. Alte Einträge aus den Schild-Datenbanken wurden aber in Kleinbuchstaben gespeichert. Nach meinem Dafürhalten wäre eine praktikable lösung, bei der Migration in den SVWS-Server die Inhalte der Spalten Uebergangsempfehlung und ErsteSchulform und LSSchulform und LSSchulformSIM in Großbuchstaben umzuwandeln. Dann sollte auch in Schild3 alles passen.

**Comment by AnneSchueller** [comment]
Problem: In Schild2 DBs gibt es bei der Übergangsempfehlung Einträge, bei denen Groß- und Kleinschreibung vermischt sind:
JG < 08 => G**y** 
JG >= 08 => G**Y**  

Das wird analog migriert, sodass man folgende Einträge in der mariaDB findet:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/c0b73de0-2d0f-45f7-a163-9d154b64c1f8)


Vorschlag: Bei der Migration werden alle Einträge in GY (bzw. R/GY, umgewandelt.

Diese inkonsistente Schreibweise von GY vs Gy bzw. R/GY vs. R/Gy findet man in sämtlichen DBs. Ich vermute dass es hier mal eine Anpassung gab.

**Comment by ThomasBachran** [comment]
Danke. Jetzt konnte ich nachvollziehen, was hier los ist. Ich kann das bei der Migration anpassen.

**Comment by ThomasBachran** [comment]
@Raffenberg , @AnneSchueller : Wichtig ist dann aber auch, dass Schild 3 das immer in Großbuchstaben schreibt...

**Comment by Raffenberg** [comment]
@AnneSchueller @ThomasBachran @JuergenRichter 
Momentan ist das zumindest der Fall, da dort die vorgegebenen Daten aus der ASDTABS verwendet werden. Wahrscheinlich werden diese Angaben aber in Schild3 fest in den Serverdaten verdrahtet und von Schild3 dort abgerufen?

**Comment by JuergenRichter** [comment]
Das kommt daher, dass in der Tabelle "SchuelerUebergangsempfehlung5Jg" in der Statkue.mdb das früher als "Gy" bzw. "R/Gy" geschrieben wurde, in der aktuellen Version aber "GY", "R/GY". Dadurch hat man gemischte Einträge bei den SuS.

**Comment by ThomasBachran** [comment]
Die vier Fehler `Uebergangsempfehlung_JG5`, `ErsteSchulform_SI`, `LSSchulform` und `LSSchulformSIM` der Tabelle `Schueler` werden jetzt wie oben beschrieben bei der Migration auf Großschreibung angepasst. Die angepasste Migration wird dann mit dem nächsten Pre-Release des SVWS-Servers zur Verfügung stehen.

**Comment by ThomasBachran** [comment]
@AnneSchueller : Ich habe dich hier nochmal zugewiesen, falls noch an anderer Stelle Anpassungen gemacht werden müssen. Wenn nicht, dann kannst du das Issue gerne schließen.

**Comment by AnneSchueller** [comment]
In der Tabelle SchuelerAbgaenge Spalte AbgangsSchulform findet man noch die Kürzel GE usw. 
Bei meinen Test-DBs sind die Einträge hier bereits alle in Großbuchstaben.
