### ISSUE TITLE
Kursblockung: Vorgehensweise und weitere Features

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/Schild3-BetaTest#884]
Hallo zusammen,

ich teste gerade die Kursblockung (SVWS-Ver. 0.8.7). Wer kann mir sagen, welche Features (Regeln, Automatisches Blocken der GKs, ...) da noch kommen? Es fehlt ja noch so einiges im Vergleich zu Kurs42_to_CNF...
Zusätzlich würde mich die Vorgehensweise interessieren, wie man die Kollisionen und Kursdifferenzen weiter runterrechnen kann (im manuellen Modus).

<img width="697" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/71388959/3591f564-2b5d-45e8-9c9e-ad979f671103">

**Comment by NielsWL** [comment]
Zusätzlich bekomme ich nach dem Import von LuPO-Daten folgenden Fehler, wenn ich eine neue Blockung anlegen möchte:

Error: Fetch failed for POST: /db/svwsdb/gost/abiturjahrgang/2027/1/blockungen/new
    at _S.postTextBased (https://localhost/assets/index.js:5:25989)
    at async _S.createGostAbiturjahrgangBlockung (https://localhost/assets/index.js:5:977821)
    at async https://localhost/assets/index.js:12:382870

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/71388959/162d291f-0400-442e-96f4-a12c3f953e81)

**Comment by hmt** [comment]
Hier ist die Antwort des Servers interessanter, die man im Netzwerktab der Entwicklerkonsole angezeigt bekommt.

**Comment by FPfotenhauer** [comment]
Ich schließe das Issue hier.
Das "ausführliche" Blocken ist in Version 0.8.9 drin.
Die Importfehler sind gefixt.
Die Diskussion kann im SVWS-Server-Repo weitergeführt werden.
