### ISSUE TITLE
Versionierungsanzeige unklar

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#885]
Wir haben aktuell den Server 0.8.7 aufgespielt. Aber an mehreren Stellen werden mir andere Versionsnummern des Servers angezeigt:
![Versionen](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/f313f3eb-2071-4b1d-a803-8d879cd5b31e)

**Comment by FPfotenhauer** [comment]
Links ist die Version von Swagger.
In deer Mitte sagt Schild, dass er eine andere Version des Servers erwartet. Wird in der server.json im Hauptverzeichnis gesteuert.
Rechts ist die Version des SVWS-Servers, die auch korrekt im Webclient angezeigt wird.
