### ISSUE TITLE
Gruppenprozesse -> BK-Abschluss "Prüfungsnoten eintragen" 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#886]
Version 3.0.79.14

Klicke ich auf den GP in BK-Abschluss "Prüfungsnoten berechen" wird ein Fehler erzeugt:

![BK GP Bug](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/0c79d915-7de5-4f72-b588-e95628fca2e0)

Das Fenster, das sich dann öffnet, heißt auch "Prüfungsnoten ZP 10 eingeben", entsprechend der Fehlermeldung "_qryZP10"...

Hier das log: 

[Buglog BK Abschluss GP.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13921064/Buglog.BK.Abschluss.GP.txt)

**Comment by JuergenRichter** [comment]
Behoben

**Comment by JuergenRichter** [comment]
Frage zu diesem Punkt: Werden bei der Noteneingabe an dieser Stelle auch Tendenznoten benötigt?

**Comment by FrodBRA** [comment]
@EwaldReinhardt

Werden hier die Tendenznoten benötigt, was sagt die Praxis?

**Comment by EwaldReinhardt** [comment]
Die Prüfungsordnung gibt das nicht her.
Alle Kollegs, die ich gestern gefragt habe, arbeiten nur mit Noten ohne Tendenzen.
