### ISSUE TITLE
Sommersemester am WBK fehlen immer noch. (Server 0.8.7 und Schild v3.0.79)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#887]
Ich kann das geschlossen Ticket leider nicht mehr öffnen. Daher hier der Hinweis noch einmal:
Ich habe auf den neuen Server 0.8.7 die aktuelle DB neu migriert. Der Fehler mit den fehlenden Sommersemestern am WBK besteht in Schild immer noch (LINUX-Installer für den Server). Den SVWS-Server können wir wie an andere Stelle beschrieben in Münster nicht aufrufen. Er stürzt in Münster an beiden im Test beteiligten Schulen ab.

**Comment by FPfotenhauer** [comment]
Wenn, wie vermutet, der Server das Update nicht korrekt erhalten hat, dann kann der Fehler nicht korrigiert sein.
Ich würde vorschlagen zunächst die unklare Versionsanzeige zu beheben und dann zu kontrollieren, ob das Problem behoben ist.

**Comment by FPfotenhauer** [comment]
Bitte nochmal melden. Die Probleme bei der Installation sind ja nun gefunden.
Danach sollte die Migration funktionieren.

**Comment by Kluesenerm** [comment]
Semester sind da! Du kannst den Punkt schließen! 
LG Martin
