### ISSUE TITLE
Anstelle des Fensters wird die Größe der Statusleiste verändert

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#889]
Situation: SchILD 3.0.79.14 unter Windows 11

Ich starte Schild, will die Größe des Fensters anpassen und es verändert sich nur die Größe der Statusleiste.
Was auffällt ist, dass die Statusleiste nicht komplett bis zum unteren Fensterrand geht (s. Bild). 
Vergrößert man die Statusleiste bis zum unteren Fensterrand, verändert man anschließend nur noch die Fenstergröße.

![FehlerStatusleiste](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/326f8983-f591-4539-a1b6-4676160b8679)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Die Statusleiste hat auch die Eigenschaft "Alignment=Bottom", sollte sich also eigentlich über die gesamte Unterkante des Fensters erstrecken.

**Comment by tpre** [comment]
Benutzen Sie Windows 10 oder 11?
Hier nochmal ein Screenshot des gesamten Fenstersvon der aktuellen Schild3Beta unter Windows 11 .
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/79703d0f-870b-4508-b8cc-14f50c37626c)

**Comment by JuergenRichter** [comment]
Aber in dem Screenshot sieht es doch so aus, dass die Statusleiste den gesamten unteren Rand einnimmt.

**Comment by tpre** [comment]
Es geht nur um die Statusleiste. WIe man auf dem zweiten Screenshot eigentlich gut sehen kann, geht die Statusleiste nicht bis an den unteren Bildschirmrand. Rechts das gepunktete Dreieck müsste ganz unten rechts in der Ecke sein, ist es aber nicht.

**Comment by JuergenRichter** [comment]
OK, verstanden. War mir auch schon aufgefallen, ist im heutigen Update korrigiert. Die Leiste, die im Screenshot unterhalb der Statuszeile erscheint, ist ein Fortschrittsbalken, der z.B. den Fortschritt bei Gruppenprozessen anzeigt.

**Comment by AnneSchueller** [comment]
Dann schließe ich das, wenn das in der neuen Version korrigiert ist.

**Comment by tpre** [comment]
@JuergenRichter @AnneSchueller Leider kann ich das Issue nicht wieder öffnen. Der Fehler mit der Statusleiste ist immer noch da, nur das man jetzt noch weniger von der Statusleiste sieht.

**Comment by tpre** [comment]
Ist vielleicht nicht wichtig, aber kann es sein, dass das Problem mit dem Rand unten auch in dneren Fenstern zu finden ist?
Mir fällt jedenfalls auch ein Rand in den anfänglichen Splash-Screens auf:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/f5ae5319-e64b-4813-ad79-4263d13757fb)
und auch hier (Warum verändert sich der Rahmen des Spash-Screens eigentlich? Es sollte doch immer so aussehen, wie auf dem folgenden Bild, oder?
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/56e3a133-7fed-44ce-81b9-d7e048f08511)

**Comment by AnneSchueller** [comment]
@tpre Ist denn mit der neuen Version das Problem mit der Status-Leiste  behoben?

Die Startfenster sehen bei mir auch minimal verschieden aus:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/3482b430-59ff-4dcb-a8c3-5075d69b30c6)


Das würde ich jetzt aber erstmal von der Priorität her nach hinten setzen, sofern es nicht mit einer schnellen Anpassung behoben werden kann.

**Comment by JuergenRichter** [comment]
Also am Splash-Screen ist definitiv nichts geändert worden. Ist evtl. zwischenzeitig mal ein Windows-Update gelaufen?

**Comment by tpre** [comment]
@AnneSchueller Das Problem mit der Statusleiste ist nicht behoben, wie ich geschrieben habe.

**Comment by AnneSchueller** [comment]
@JuergenRichter : Ich hatte kein Update. Wahrscheinlich war die Breite des Fensters vom ersten zum zweiten Startbild immer schon minimal anders und es ist mir noch nie aufgefallen. (das finde ich an dieser Stelle auch nicht störend)

@tpre Es gab gestern nochmal ein SchILD-Update. Bezog sich dein Post bereits auf die neue SchILD-Version 3.0.80.9? 
Das Update wurde gestern Nachmittag nochmal aktualisiert.

**Comment by tpre** [comment]
@AnneSchueller: Ich meine ja. Mittlerweile läuft bei mir leider gar nichts mehr. Die Installation des SVWS-Servers 0.8.8 schlägt fehl, da die DB nicht installiert wird, obwohl der Installer das sagt.

**Comment by JuergenRichter** [comment]
Kann es sein, dass was mit der Grafikkarte zu tun hat? Bei mir sieht das so aus 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/f9417c0b-a2e8-4a19-ace3-1b48ab30cf6d)

**Comment by tpre** [comment]
So, ich habe nochmal alles neu installiert und jetzt ist alles so, wie es sein soll. Die Statusleiste ist ganz unten und alles passt.
