### ISSUE TITLE
halb verdecktes Ankreuzfeld in Individualdaten I

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#89]
Bei den Aktuellen Laufbahndaten im Reiter Individualdaten I gibt es ganz unten ein Ankreuzfeld ohne Beschreibung unter >ist Duplikat<, das nur halb zu sehen ist.
"Ist das Kunst oder kann das weg?"

**Comment by FPfotenhauer** [comment]
![SNAG_2021_02_10_18 22 53](https://user-images.githubusercontent.com/34127980/107546767-03bb3400-6bcd-11eb-8d78-890b4770b702.png)

**Comment by JuergenRichter** [comment]
Welche Schulform?

**Comment by ADV-Fendel** [comment]
Ich habe zum Ausprobieren die Spieldatenbank einer Grundschule genommen.

**Comment by ADV-Fendel** [comment]
[halb verdecktes Feld.pdf](https://github.com/SVWS-NRW/Schild3-BetaTest/files/5996754/halb.verdecktes.Feld.pdf)

**Comment by JuergenRichter** [comment]
In der Version 3.0.10 kann ich das (auch mit einer Grundschule) nicht mehr reproduzieren. Ich mache das Thema daher erst mal zu.
