### ISSUE TITLE
Meldung über Datumsinkonsistenzen bei Beispiel-DB mit resultierender Unbedienbarkeit von Schild

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#890]
Situation: SchILD 3.0.79.14, SVWS-Server 0.8.7 mit Beispiel-DB BK-Test-Daten-01.mdb

Ich starte den Schild und immer wieder bekam ich nach ein wenig "Rumklicken" irgendwann das u.a. Fenster angezeigt. Was ist leider nicht mehr reproduzieren konnte, nachdem ich beschloss den Fehler zu melden ;-)

Aber ich konnte den Fehler auf andere Art erzeugen:
1. Schild starten
2. Die erste Schülerin ist bereits angewählt mit folgenden Daten:
     Anmeldedatum 24.03.2022, 
     Aufnahmedatum: 01.08.2022 und 
     Entlassung von eigener Schule am 01.01.2000  (Fehler!)
     Entlassung von vorheriger Schule 31.07.2022
4. Ändert man das Aufnahmedatum auf den 01.03.2022, passiert erstaunlicherweise nichts. Die Änderung wird hingenommen.
5. Nach Anwahl eines anderen Reiters, erscheint das Fenster (mit mehr Fehlern, als ich verursacht haben sollte)
6. Änderung des Aufnahmedatums zurück auf den 01.08.2022
7. Nach Anwahl eines anderen Reiters, erscheint das Fenster. Ein Wechseln des Reiters ist nicht möglich, das Programm ist damit unbedienbar, was so nicht passieren sollte.

Verbesserungsvorschlag: Fehler direkt nach Eingabe anzeigen und dem Fehlerfenster einen OK-Button hinzufügen.

Schaut man weiter stellt man fest, dass sämtliche Schüler den 01.01.2000 als Entlassdatum eingetragen haben. 
Ist dieser Fehler in der/den Test-DB(s) enthalten oder entsteht dieser Fehler beim Import der Test-DB?
Mittlerweile habe ich nachgeschaut: Der Fehler ist in der MDB-Datei bereits enthalten.  Interessanterweise bei vielen, aber nicht bei allen Schülern. 

![Inkonsistenzen_Dateumsangaben](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/fee2d654-c1a4-427a-b268-cc01dbe68849)

**Comment by JuergenRichter** [comment]
Die nicht vorhandenen Schalter "Ignorieren" und "Abbrechen" (deren Fehlen letztlich zur "Unbedienbarkeit" geführt haben, sind nun sichtbar.
