### ISSUE TITLE
mtblLaender: Das Feld "gueltigVon" wurde nicht gefunden!

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#891]
Ich bin gerade dabei mir ein paar Linux-Skripte zu basteln. Eines davon soll nachträglich eine der Beispiel-Datenbanken importieren. Warum? Weil ich gerne mehr als eine Beispiel-DB verfügbar hätte und weil ich das Install-Skript an dieser Stelle verbesserungswürdig finde.
Ich habe mich dabei am install-Skript des SVWS-Servers für Linux orientiert und importiere die DB genau wie dort. Wenn ich mit so einer importierten DB Schild starte kommt dieser Fehler. Die gleiche über das Install-Skript importierte DB hingegen läuft problemlos. Die Einstellungen nehme ich aus der .env-Datei. Nur benenne ich die DB so, wie die MDB-Datei heißt.

Die Fehlermeldung ist eine alte, wie ich gesehen habe. Habe ich etwas übersehen?

Anbei das Skript
```
#!/bin/bash

if [ "$1" == '' ]; then
  echo "Als Parameter wird eine .mdb-Datei erwartet!"
  exit 1
fi

if [ ! -f $1 ]; then
  echo "Die Datei $1 existiert nicht"
  exit 1
fi

if [ ! $(file -b --mime-type "$1") == application/x-msaccess ]; then
  echo "Die Datei $1 ist keine Access Datenbank!"
  exit 1
fi

if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
else
  echo "Die .env-Datei ist zwingend notwendig und fehlt leider!"
  exit 1
fi

cd $APP_PATH

MariaDB_DATABASE=$(basename $1 .mdb)

# Importiere die Datenbank(en) mittels der MigrateDB Klasse
echo "Importiere Datenbank: $1 ..."
java -cp "svws-server-app-*.jar:${APP_PATH}/app/*:${APP_PATH}/app/lib/*" de.svws_nrw.db.utils.app.MigrateDB -j -r -1 -sd "MDB" \
       -sl "$1" -sp "${TESTDB_PASSWORD}" \
       -td "MARIA_DB" \
       -tl ${MariaDB_HOST} \
       -ts ${MariaDB_DATABASE} \
       -tu ${MariaDB_USER} \
       -tp ${MariaDB_PASSWORD} \
       -tr ${MariaDB_ROOT_PASSWORD}

```

**Comment by tpre** [comment]
Manchmal bedenkt man nicht alles. Nach dem Neustart des SVWS-Servers klappts plötzlich. Vielleicht war das ja trotzdem für irgendwen hilfreich.

**Comment by tpre** [comment]
Wenn es nicht hilfreich ist, dann gerne schließen. Ich hatte es wieder geöffnet, damit andere das finden. Als closed issue ist das aus den Augen.
Könnt ihr mir dem Skript etwas anfangen?

**Comment by FPfotenhauer** [comment]
Wir schließen die Issues gerne, weil wir dann wissen, dass das erledigt ist.
Das Script können andere fachberater sicherlich in Testumgebungen gut benutzen.
Mehrere Datenbanken kann man über den AdminClient ja nun auch sehr bequem verwalten....
