### ISSUE TITLE
Schüler -> "BK-Abschluss" und BK-Gruppenprozesse + BK-Orientierungsdiskussion

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#892]
Version 3.0.79.14

Der Reiter "Schüler -> BK-Abschluss" wirkt noch unfertig. 

"Leistungsdaten holen" funktioniert noch.

- Klicke ich aber auf "Zulassung prüfen" wird im Protokoll nur was zum FHR geschrieben. Für den FHR gibt es im BK aber noch den normalen Reiter "FHR".
- Das Feld "Zulassung" wird nicht ausgefüllt (Ja, nein) 
- Im Reiter "BK-Abschluss" gibt es kein Feld "Abschluss berechnen" wie in den Gruppenprozessen.

Die Reihenfolge der Gruppenprozesse wirkt seltsam: Sollte man nicht erst die Zulassung prüfen und dann "Prüfungsnoten aus Teilleistungen" holen?

Klicke ich auf "Prüfungsnoten eingeben" erscheint erst ein Fehler, dann ein Fenster, das aber noch nach der NP 10 benannt ist.

Klicke ich dann auf "Abschluss berechnen", wirkt das Protokoll nicht aussagekräftig und führt wieder nur den FHR an.

Den Rest hatte ich im Hinblick auf die bisherigen Fehler dann noch nicht getestet.

Das wirkt noch etwas nach einem Prototypen und daher würde ich darum bitten, dass zuerst einmal der Schüler -> BK-Reiter und die GPs durch Ribeka geprüft werden und erst wenn das noch einmal überprüft wurde wir ins Betatesten und "Dokumentation verfassen" gehen.

---

Hier wären noch Fragen an Leute, die sich mit dem BK bzw. dem Ablauf in SchILD 2 auskennen: 
- Was soll "Abschluss prüfen" genau tun, d.h. welche Abschlüsse werden hier vergeben und
- Welche Rollen spielen hier die Prüfungen
- wie spielen "BK-Abschluss", "FHR" und "Abitur" hier am BK mit ihren unterschiedlichen Reitern zusammen?

**Comment by JuergenRichter** [comment]
Am BK gibt es den FHR in unterschiedlichen "Ausprägungen":

1. In der gymnasialen Oberstufe, vergleichbar mit dem Gymnasium (auf Karteireiter FHR)
2. Im Rahmen einer Ausbildung, bei der man als "allgemeinbildenden Abschluss" die FHR bekommen kann (auf Karteireiter BK-Abschluss)

"das aber noch nach der NP 10 benannt ist."
Das ist ein Folgefehler, da wird normalerweise eine andere Überschrift ausgegeben (die Fehlerursache ist schon behoben).
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/04238d8c-8c23-4427-bcef-e5cdd5af6dc8)

**Comment by tpre** [comment]
Ich bin erst noch auf dem Wege zum BK-Spezialisten ;-)
Wenn ich nicht ganz falsch liege, dann gibt es 2-jährige Bildungsgänge (nach Anlage C (C03), die nur den schulischen Teil der FHR machen. Die müssen dann ein zusätzliches Praktikum (oder eine Ausbildung) im Anschluss auf eigene Initiative machen, ein die volle FHR zu bekommen. Die 3-jährigen Bildungsgänge nach Anlage C (C01), Technische Assistenten), machen die volle FHR und einen Berufsabschluss.
In Schild 2 ist bei C03 der Reiter BK-Abschluss noch eingeblendet, obwohl die C03er keinen Berufsabschluss machen.

**Comment by JuergenRichter** [comment]
Bei "abschluss-bezogenen" Gruppenprozessen hängt es von der jeweiligen Auswahl ab, ob ein Gruppenprozess sinnvoll ist oder nicht. Bei der Gliederung A01 gibt es z.B. keine "Zulassungsberechnung", daher ist es in gewisser Hinsicht in der Verantwortung des Anwenders, je nach Auswahl einen "sinnvollen" Gruppenprozess zu starten. Alternativ müsste man bei jedem Schüler in der Auswahl prüfen, welche Gliederung vorliegt und einen Gruppenprozess nur dann anbieten, wenn dieser auch für alle SuS der Auswahl sinnvoll ist. Dazu müsste aber mal jemand definieren, welche Gruppenprozesse für welche Gliederung verfügbar sein sollen.

**Comment by tpre** [comment]
Ich würde mich da anbieten und das gerne für die Anlagen am BK ermitteln!

**Comment by FrodBRA** [comment]
Ich freue mich natürlich über weitere Informationen, um im Wiki zumindest grobe Orientierungen anbieten zu können. 

Ebenso halte ich es für sinnvoll, wenn SchILD über gute Informationen in den Protokolldateien ausgibt.

Mir sind (weitere) Expertenmeinungen also immer willkommen.

Hier müsste eventuell auch @FPfotenhauer angeben/vorgeben, in welcher Tiefe SchILD3 das komplexe BK abbilden soll bzw. automatisch behandelt und auch, wo eventuell der Aufwand und die schuljahresaktuelle Pflege den vorgesehenen Rahmen übersteigt.

**Comment by JuergenRichter** [comment]
Der Aufwand wäre gar nicht mal so groß, es müsste nur jemand, der genaue Kenntnisse über alle BK-Gliederungen hat, mal konkret sagen, welche Gruppenprozesse unter welchen Bedingungen sinnvoll angezeigt werden sollen.

**Comment by FrodBRA** [comment]
In den E-Mails im Vorfeld zu diesem Issue hatte @AnneSchueller schon angedacht, dass wir eventuell mit einer Handvoll bislang einbezogener Personen + Leuten, die sich auskennen, eine Videorunde machen, um in der Übersicht das BK erklärt zu bekommen. Damit könnten wir eine solide Entscheidung in Bezug auf die Abbildung der Abläufe/Abschlüsse in SchILD 3 und die Dokumentation im Wiki zu treffen.

Soll das einer der nächsten Schritte werden?

**Comment by tpre** [comment]
Ich habe mich mal schlau gemacht: 

Man könnte grundsätzlich die Gliederung der Anlagen ausdünnen auf aktuell gültige Gliederungen. Dann wird die Liste ein Stückchen kürzer. Es gibt aktuell nur die folgenden Gliederungen (Quelle: https://schulverwaltungsprogramme.msb.nrw.de/download/Berufskolleg.pdf)

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/b5a9fef4-0b3e-4e5d-9da5-9a6ec3068845)

Spannenderweise widersprechen sich manche Angaben auf den offiziellen Seiten auch gegenseitig. So kann man in Anlage E oft auch einen FHR bekommen, was in dem o.g. Pdf nicht aufgeführt ist.

Wenn man das auf Schild abbilden will, so muss man da jeweils nochmal genau schauen, was man am Ende des Bildungsgangs tatsächlich bekommt. In Anlage E ist der FHR nur ein Kommentar mit Durchschnittsnote auf den Zeugnis. Es gibt also nur ein Zeugnis. In D02 gibt es auch nur ein Zeugnis. Den Rest weiß ich noch nicht.

Nur bei den Gliederungen mit FHR oder AHR hat man am Ende noch Prüfungen, so dass man dort entsprechend Vornoten, vorl. Prüfungsnoten, Nachprüfungsnoten und Prüfungsnoten hat.
In den anderen Fällen gibt es nur ein oder zwei "normale" Zeugnisse, wenn ich das so richtig sehe.

**Comment by FPfotenhauer** [comment]
Ich würde hier gerne eine grundsätzliche Sache sagen:
In Schild3 soll zunächste der Funktionsumfang von Schild2 zur Verfügung stehen und natürlich möglichst fehlerfrei bedienbar sein.

Im SVWS-Client werden wir die Ansichten und Funktionen (auch Berechnungen) zum BK grundlegend erneuern.
Dazu wurde auch eine Arbeitsgruppe gebildet. @FrodBRA hier kannst du dich auch gut einmal mit @EwaldReinhardt unterhalten.
Er koordiniert die Erneuerungen des BK-Bereichs.

**Comment by FrodBRA** [comment]
Auch @EwaldReinhardt

Zu den Abschlussprüfungen: @JuergenRichter Ich sehe das richtig, dass sich die Abschlussprüfung lediglich die jeweils gesetzte Prüfungsordnung anschaut und damit wird das sehr komplexe System aus Sicht der Prüfung wieder recht einfach und eindeutig. Korrekt?

Beim Weiteren hier geht es mir weniger um Implementationen _in_ SchILD, sondern um die Dokumentation _für_ SchILD.

Zu den Gliederungen: @tpre Ich halte so ein pdf nicht für zuverlässig genug, für solche Informationen müssen wir wohl selbst in die APO schauen. 

Zum FHR: Den gibt es am BK als FHRs (schulischer Teil FHR, dieser heißt an Gym/Ges nur FHR und wird als Reiter "FHR" auch am BK aufgezeigt) und als "vollen" FHR (der hier jetzt FHR heißt); sehe ich das korrekt? Am BK wären hier somit beide Reiter, FHR und BK-Abschluss zu beachten). 

Sind die Infos im Dokument "Zeugnisformulare am BK" korrekt und aktuell? Dieses Dokument wäre für mich dann sehr wertvoll. https://www.svws.nrw.de/download/schild-reports/zeugnisformulare
(Direktlink: https://www.svws.nrw.de/system/files/media/document/file/infos_zeugnisformulare_bk.docx )

**Comment by JuergenRichter** [comment]
Ich werde heute eine aktualisierte Version mit einigen Korrekturen im BK-Bereich bereitstellen.

**Comment by EwaldReinhardt** [comment]
Der Reiter FHR wird nur für Schüler des beruflichen Gymnasiums eingeblendet.
Hier wird für Schüler, die den Bildungsgang vorzeitig verlassen, die FHR (nur der schulische Teil) aus den
Kursnoten der Grund- und Leistungskurse von zwei aufeinanderfolgenden Halbjahren gemäß Prüfungsordnung berechnet. 
Sind die Schüler in die 12 versetzt erhalten sie immer die auf weniger Bundesländer eingeschränkte FHRs, wobei sich die Durchschnittsnote der FHR aus dem Versetzungszeugnis nach 12 ergibt.

**Comment by FrodBRA** [comment]
Was wird in "Bk-Abschluss" bei "Themen der Abschlussarbeiten" unten eingetragen? Gehe ich recht in der Annahme, dass das ein String ist, der dann (bei Bedarf) einfach so auf dem Zeugnis landet?

**Comment by FrodBRA** [comment]
Bezüglich der Reihenfolge der Reiter:

Sollte nicht "Zulassung prüfen" vor "Note aus Teilleistungen holen" stehen, da eine Zulassung ja i.d.R. vor der Prüfung und damit dem Eintrag der TL stattfindet (gleiches gilt für die Reihenfolge der Gruppenprozesse).

Falls ich etwas falsch verstehe, bitte ich um Belehrung. ;)

**Comment by EwaldReinhardt** [comment]
Den Button "Note aus Teilleistungen holen" benötigt man mehrmals.
Zur Zulassungsprüfung benötigt man auf jeden Fall die Vornoten, die ich
nicht unbedingt als Halbjahresnote eintragen würde.
Hier mal der Text aus der APO-BK

> Anl. D § 12 (3) Der allgemeine Prüfungsausschuss stellt die Vornoten für alle Fächer
> auf Grund der Leistungsnachweise des laufenden Schuljahres
> unter angemessener Berücksichtigung der Entwicklung der Schülerin
> oder des Schülers in diesem Zeitraum fest. Die Vornote wird von
> der Fachlehrerin oder dem Fachlehrer vorgeschlagen und ist auf Verlangen
> eines Mitglieds des allgemeinen Prüfungsausschusses zu begründen.

Die Vornote spiegelt das gesamte Schuljahr wieder.
Im Halbjahresreiter könnte die Halbjahresnote ordentlich dokumentiert werden.
Die Vornote (der Vorschlag des Lehrers) wird unter einer entsprechenden Teilleistung erfasst.
Diese ist Voraussetzung für die Zulassungsberechnung.
Auch die Abschlussnote wird vorgeschlagen und kann genauso über die Teilleistung zugeführt werden.

> Anl. D § 14 (3) Auf der Grundlage der Vornote und der schriftlichen Prüfung legt
> die Fachlehrerin oder der Fachlehrer die vorläufige Abschlussnote
> fest.

**Comment by JuergenRichter** [comment]
Kann man bei Bedarf ergänzen.

**Comment by FrodBRA** [comment]
Wo? In den Einstellungen?

Ich kann beliebige TL definieren, aber nicht in BK-Abschluss auswählen, dass da nun eine "Vornote" aus einer TL geholt werden soll.

**Comment by EwaldReinhardt** [comment]
> Danke sehr schon einmal hierfür. Das ist wertvolle Information! Ich sehe aber gerade, dass die "Vornote" in BK-Abschluss gar nicht über eine TL befüllbar ist, hier steht nur die Option "mündliche" bzw. "schriftliche" Note zur Verfügung.
> 
> Ist das so gewollt?

Man kann doch die verfügbaren Teilleistungen selbst definieren unter Kataloge/Teilleistungsarten.

**Comment by FrodBRA** [comment]
(siehe vorheriger Kommentar, ich bekomme die TL nicht in die "Vornote" - oder holt der sich die automatisch, wenn es eine TL "Vornote" gibt?)

**Comment by EwaldReinhardt** [comment]
Es kann sein, dass die Teilleistung Vornote auch einem Fach zugewiesen sein muss bei dem entsprechenden Schüler,
damit die Teilleistungsart angezeigt wird. Das wäre auch sinnvoll so.
Es gibt auch einen Gruppenprozess, der die Teilleistungsarten zuweist

**Comment by EwaldReinhardt** [comment]
Bei mir kann ich das auswählen:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/63a3cd68-62fe-4051-a93c-9b23e71ac40b)

**Comment by EwaldReinhardt** [comment]
Ich prüfe das auch mal.
Zu dem Feld Themen der Abschlussarbeiten kann ich nur sagen, dass wir den nie genutzt haben.
Die Abschlussarbeiten haben wir als Fach eingetragen. Hier wird eine Note eingetragen und in 
die Fachbemerkung wird das Thema eingetragen.
Einzige Situation, die sinnvoll sein könnte, ist das Berufspraktische Jahr, in dem keine Schule stattfindet und auch **eine** Projektarbeit geschrieben wird. 
Das kann man aber auch anders lösen. @FrodBRA siehe Zeugniseinstellungen Doku, die ich dir geschickt hatte.
Ich werde nächste Woche Mittwoch in der BK-Gruppe man nachfragen, ob das irgendein BK nutzt.
Dort sind alle Arten von BKs da.

**Comment by FrodBRA** [comment]
> Bei mir kann ich das auswählen: [...]

Ok, bei passender Wahl einer Klasse kann ich das auch. Sorry, da hätte ich auch drauf kommen können.

**Comment by FrodBRA** [comment]
Was konkret (knapp reicht) sind die Schwerpunkte, die im Katalog Schwerpunkte gesetzt werden?

**Comment by JuergenRichter** [comment]
Das Feld "Thema der Abschlussarbeit" ist irgendwann mal explizipt von BKs gewünscht worden.

**Comment by FrodBRA** [comment]
Dann gehe ich davon aus, dass das auch genutzt wird, wenn ich das prominent genug in die Dokumentation schreibe. ;)

Hat jemand eine BK-Datenbank, die "echt genug" ist, um mal zu schauen, ob das mit Zeugnisformularen so funktioniert? Meine Test-DB bräuchte noch viel zu viel Arbeit, um das "mal eben" zu testen?

**Comment by AnneSchueller** [comment]
@FrodBRA : Ich schicke dir einen Downloadlink

**Comment by FrodBRA** [comment]
Aus purer Faulheit frage ich, bevor ich selbst nachgucke. ;)

Ist wem bekannt, in welcher Anlage Abschlussarbeiten ausgebenen werden.

(Nur, wenn das schon bekannt ist, sonst gucke ich selbst)

**Comment by FrodBRA** [comment]
Manchmal steht in BK-Abschluss "Abschlussnote", dann verändert sich das Feld wieder zu "vorl. Abschlussnote".

Woran liegt das? Bei einer BK-DB habe ich zwei Klassen AHM1 und AHM2, in einer gibt es die "Abschlussnoten", in der anderen die "Vorläufige Note"?

Sind beide dennoch über den gleichen GP ("vorläufige Abschlussnote berechnen" heißt der) berechenbar?

**Comment by EwaldReinhardt** [comment]
Ich habe schon die APO-BK durchgeschaut. Ich habe kein Formular gefunden, das eine Abschlussarbeit ausweist.
In der Fachschule sind das die Examen1 - n, die eine Note haben und mit Thema auf dem Zeugnis ausgewiesen werden.
Ich frage am Mittwoch, ob das jemand nutzt.

**Comment by EwaldReinhardt** [comment]
Zu den Schwerpunkten:
Hier werden Schwerpunkte von Bildungsgängen eingepflegt:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/424b5b40-3904-4114-916d-43cfd12a106b)

Das kommt in manchen Bildungsgängen vor:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/d3accacd-8c0c-44d6-8825-f51511963461)

Eingetragen wird es hier:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/1cd41d1a-8536-49da-89f7-e9ad4a35b6db)

**Comment by EwaldReinhardt** [comment]
> Danke sehr soweit schonmal.
> 
> In der Abschlussberechung: Was sind "AB" und "BA"?
> 
> Meine Vermutung ist, dass "AB" ein "nach der Prüfungsordnung vorgesehene Schul-Abschluss" ist? "BA" dürfte der "berufliche Abschluss" sein?

Ich weiß nicht genau wo das steht in der Abschlussberechung:
BA steht für Berufsabschluss, der in der Kammer erreicht wird. Es gibt eine Regelung, dass der Berufsabschluss zum Ausgleich für die FHR herangezogen werden kann:
APO-BK, Allg. Teil §17 (4):
`(4) Die Fachhochschulreifeprüfung ist bestanden, wenn in allen Fächern mindestens ausreichende Leistungen erzielt werden oder wenn die Leistungen nur in einem Fach „mangelhaft“ sind und durch eine mindestens befriedigende Leistung in einem anderen Fach oder der Berufsabschlussprüfung ausgeglichen werden. Eine ungenügende Leistung kann nicht ausgeglichen werden.`
Mit der Verwaltungsvorschrift:
`17.5.2 Ist die Berufsabschlussprüfung mit einer mindestens befriedigenden Leistung bestanden worden und gemäß [§ 17](https://bass.schul-welt.de/3129.htm#13-33nr1.1p17_AnlageA) Absatz 4 Anlage A zum Ausgleich einer mangelhaften Leistung herangezogen worden, ist diese bei der Berechnung der Durchschnittsnote zu berücksichtigen. Dabei ist das arithmetische Mittel der Gesamtnote der Berufsabschlussprüfung und der mangelhaften Leistung heranzuziehen.`

Das AB könnte auch für allgemeinbildend stehen. Aber ich weiß nicht welches AB du meinst.

**Comment by FrodBRA** [comment]
![SchILD_Schüler_BK-Abschluss_AbschlussBerechnen](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/07055a66-4da8-41c1-8306-1c639dc23a05)

**Comment by EwaldReinhardt** [comment]
Das soll wahrscheinlich für Allgemeinbildend stehen.
Ich habe gerade (allerdings nicht auf der aktuellen Version) drauf geschaut und
werde heute dazu ein Issue aufmachen.

**Comment by FrodBRA** [comment]
Ich nehme an, dass die "Zertifikate" aus dem Katalog irgendwo verwendet werden können, ich konnte gerade aber nicht finden, wo sie gesetzt werden.

Gibt es diesen Katalog/Zertifikate generell nur am BK?

**Comment by EwaldReinhardt** [comment]
`APO-BK allg. Teil § 9 (3) Über berufliche Qualifikationen, die nicht im Abschlusszeugnis
bescheinigt werden, und über Zusatzqualifikationen werden Zertifikate
erteilt, auf Antrag auch über nicht weitergeführte Ausbildungsabschnitte.`

```
`Anl. D § 58 (2) In einer zweiten Fremdsprache werden Kenntnisse nachgewiesen
durch
```
`...
`
```
c) Erwerb eines Fremdsprachenzertifikates auf dem Niveau B 1 gemäß
der Rahmenvereinbarung der Kultusministerkonferenz vom 20.
November 1998 über die Zertifizierung von Fremdsprachenkenntnissen
in der beruflichen Bildung.`
```

Zertifikate als Nachweis wie auch die an der Schule erworbenen könnten dort abgelegt werden.

**Comment by FrodBRA** [comment]
Das Issue würde ich erst einmal schließen, wir sind denke ich orientiert und die Wikiartikel stehen soweit. Dafür wird das Issue hier aber etwas unübersichtlich.

Viele der tatsächlichen "Issues" sind gelöst.
