### ISSUE TITLE
Rechtschreibfehler (Umlaute)

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#893]
Bei Verwaltung -> Export -> Als Excel-/Text-Dateien -> Datenart Lehrer
sind einige Umlaute falsch formatiert (Beschäftigungsart, nicht-unterrichtliche Tätigkeiten). Bei Fächer ist es richtig.

**Comment by JuergenRichter** [comment]
Die zur Verfügung stehenden Angaben werden vom SVWS-Server geliefert, man müsste also dort schauen.

**Comment by AnneSchueller** [comment]
@ThomasBachran 

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/d512f020-3043-485e-8361-001ef6b41944)


![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/7094ba14-0bbe-4354-87e3-2e40b57bc7db)

**Comment by ThomasBachran** [comment]
@AnneSchueller : Die Fehler sind jetzt bei uns im Repository behoben und werden beim nächsten Release behoben sein.
