### ISSUE TITLE
Export-Möglichkeiten nicht für alle Felder vorhanden

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/Schild3-BetaTest#894]
Bei Verwaltung -> Export -> Als Excel-/Text-Dateien -> Datenart Lehrer
gibt es nicht die Möglichkeit, "Schulinterne Funktionen" zu exportieren.
Dies ist für uns interessant, um damit schulinterne Gruppen bei IServ anzulegen.

Alternantiv oder zusätzlich sollte auch die Möglichkeit bestehen, Personengruppen exportieren zu können, evtl. auf importieren zu können.

LG
Raphael Kemna, Moderator Bez-Reg. Köln, Raum Aachen

**Comment by AnneSchueller** [comment]
Welches Feld in SchILD meinst du mit "Schulinterne Funktionen"
Personengruppe, Benutzergruppe... 

@JuergenRichter : Ließe sich das mit der Personengruppe leicht umsetzen? Das sind ja keine atomaren Werte.
Hier wäre auch ein Export im Reiter Personengruppe sinnvoll (analog zu SchILD2)

@JuergenRichter : An dieser Stelle fehlt noch der Export des Initialkennworts. Das gibt es ja noch nicht so lange.

**Comment by JuergenRichter** [comment]
Ich werde mal die in SchILD3 vorhandenen Optionen mit denen aus SchILD2 vergleichen und die Angaben entsprechend ergänzen. Das muss dann aber in den SVWS-Server integriert werden

**Comment by AnneSchueller** [comment]
In der Swagger UI habe ich dazu nichts gefunden....

**Comment by JuergenRichter** [comment]
Die Optionen werden über die folgende URL gelifert:
https://{server}/db/{schema}/schild3/export/csv

**Comment by FrodBRA** [comment]
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/545

Ich verbinde die Issues über weitere, vom SVWS-Server zu liefernde Exportmöglichkeiten.

**Comment by Raphael-Kemna** [comment]
> Welches Feld in SchILD meinst du mit "Schulinterne Funktionen" Personengruppe, Benutzergruppe...
> 
> @JuergenRichter : Ließe sich das mit der Personengruppe leicht umsetzen? Das sind ja keine atomaren Werte. Hier wäre auch ein Export im Reiter Personengruppe sinnvoll (analog zu SchILD2)
> 
> @JuergenRichter : An dieser Stelle fehlt noch der Export des Initialkennworts. Das gibt es ja noch nicht so lange.

Hallo Anne,
ich meine den Reiter bei Lehrkräfte -> Zeitabhängige Daten -> Schulinterne Funktionen.

Danke für's Einbinden!

Liebe Grüße
Raphael

**Comment by JuergenRichter** [comment]
"An dieser Stelle fehlt noch der Export des Initialkennworts. Das gibt es ja noch nicht so lange."

Welches Initialkennwort ist denn gemeint?

**Comment by AnneSchueller** [comment]
Da fällt mir ein... Das brauchen wir wahrscheinlich gar nicht mehr. 
Gemeint war das Kennwort für die GS-Notendatei. Aber wenn das auch über das ENM läuft ist das obsolet.

**Comment by JuergenRichter** [comment]
M.E. ist das nicht obsolet. Für das ENM wird doch sicher auch ein Initial-Kennwort vergeben werden müssen.

**Comment by JuergenRichter** [comment]
"Alternantiv oder zusätzlich sollte auch die Möglichkeit bestehen, Personengruppen exportieren zu können, evtl. auf importieren zu können."
Wird in Kürze im "Schnittstellenformat SchILD-NRW" möglich sein.

**Comment by JuergenRichter** [comment]
Siehe auch #545

**Comment by JuergenRichter** [comment]
Fehlt denn hier noch was?

**Comment by AnneSchueller** [comment]
Nur die DSGVO-Einwilligungen fehlen in Schild3.

**Comment by Raphael-Kemna** [comment]
Wenn ich im Export "nicht-unterrichtliche Tätigkeiten" auswähle und exportiere, dann taucht in der Datei in der Spalte als Überschift nur "ID" auf und als Inhalt #42S22Unknown column 'A.Jahr' in 'order clause'.
Ebenso wird bei Mehrleistungsstunden und Minderleistungsstunden auch nur "ID" als Spaltenüberschrift angegeben.
Ferner fehlt mir noch die Exportfunktion für "Schulinterne Funktionen".
:-)

**Comment by JuergenRichter** [comment]
> Nur die DSGVO-Einwilligungen fehlen in Schild3.

Liegt hier ein Missverständnis vor? Bei dem Issue geht es ja um die verfügbaren Felder bei "Export>>Als Excel-/Text-Dateien". Da gibt es aber auch in SchILD2 keinen Export der DSGVO-Einwilligungen. Diese fehlen aber tatsächlich beim "Export im Schnittstellen-Format SchILD-NRW". Das wird noch nachgeholt.

**Comment by JuergenRichter** [comment]
> Wenn ich im Export "nicht-unterrichtliche Tätigkeiten" auswähle und exportiere, dann taucht in der Datei in der Spalte als Überschift nur "ID" auf und als Inhalt #42S22Unknown column 'A.Jahr' in 'order clause'. Ebenso wird bei Mehrleistungsstunden und Minderleistungsstunden auch nur "ID" als Spaltenüberschrift angegeben. Ferner fehlt mir noch die Exportfunktion für "Schulinterne Funktionen". :-)

Wegen der "nicht-unterrichtlichen Tätigkeit": Hier liegt ein Fehler in der entsprechenden Abfrage vor. Da diese aber jetzt vom SVWS-Server geliefert wird, müsste das auch dort angepasst werden. Dazu ist bei dem Eintrag für den "Anzeigetext "nicht-unterrichtliche Tätigkeit" der Inhalt von "LookupSQLText" wie folgt zu ersetzen:

falsche Abfrage
select A.AnrechnungStd from LehrerAbschnittsdaten A where A.Lehrer_ID=% order by A.Jahr desc, A.Abschnitt desc

korrekte Abfrage
select LA..AnrechnungStd from LehrerAbschnittsdaten LA, EigeneSchule ES where LA.Lehrer_ID=% AND LA.Schuljahresabschnitts_ID=ES.Schuljahresabschnitts_ID

Wegen der gewünschten schulinternen Funktionen schicke ich nochmal eine CSV-Datei zu.

**Comment by AnneSchueller** [comment]
@JuergenRichter : Da habe ich in der falschen Export-Option geschaut....

Ich erstelle ein entsprechendes Issue für den SVWS-Server bezüglich der Abfrage

**Comment by AnneSchueller** [comment]
Beim Export der nicht unterrichtlichen Tätigkeiten erhält man für jede Lehrkraft folgendes:
![image](https://github.com/user-attachments/assets/322221c2-9f98-4708-bf75-15afb8c6fddb)

Beim Eintrag der Nicht unterrichtlichen Tätigkeiten erhält man eine Fehlermeldung:
[export_log.txt](https://github.com/user-attachments/files/16707029/export_log.txt)

**Comment by Raphael-Kemna** [comment]
Beim Export des 'MasernImpfnachweis'es tritt ein Fehler auf, wahrscheinlich für den SVWS was.
![grafik](https://github.com/user-attachments/assets/db99ff27-4e4c-4a9b-aa1e-238a2f2c2f48)

In der Excel-Datei ist dann bei Spalte F (Anwahl aller Individualdaten): 
#42S22Unknown column   'A.Jahr' in 'order clause'

Der Rest sieht gut aus bzgl. der Kopfzeile.
Die "Beschäftigungsart" ist von der Ausgabe her falsch: "Das Feld 'Beschaeftigungsart' wurde nicht gefunden"
Ebenso "nicht-unterrichtliche Tätigkeit": #42S22Unknown column 'A.AnrechnungStd' in 'field list'

Schild 3.0.91, SVWS 0.9.2

LG Raphael

**Comment by AnneSchueller** [comment]
@JuergenRichter das Feld MasernImpfnachweis kann aus dem Lehrerexport raus, das gibt es ja nicht mehr.

![image](https://github.com/user-attachments/assets/4dc542e3-ede2-4dbf-a725-7192a528d4c4)

Das mit der Ausgabe der Beschäftigungsart kann ich reproduzieren:
![image](https://github.com/user-attachments/assets/e71e1b31-5642-4234-911f-7b21624940cb)

**Comment by JuergenRichter** [comment]
Die verfügbaren Felder werden vom SVWS-Server geliefert, da müsste das Feld "Masernimpfnachweis" bei den Lehrerdaten raus.

**Comment by JuergenRichter** [comment]
Wegen des Exportes der nicht unterrichtlichen Tätigkeiten:
Da ist ein Fehler im SVWS-Server:
Bei der Datenart "Lehrer", Feld "nicht-unterrichtliche Tätigkeit" muss der SQK-Befehl lauten:
select LA.AnrechnungStd from LehrerAbschnittsdaten LA, EigeneSchule ES where LA.Lehrer_ID=% AND LA.Schuljahresabschnitts_ID=ES.Schuljahresabschnitts_ID

derzeit liefert der SVES-Server folgendes:
select **A.AnrechnungStd** from LehrerAbschnittsdaten LA, EigeneSchule ES where LA.Lehrer_ID=% AND LA.Schuljahresabschnitts_ID=ES.Schuljahresabschnitts_ID

**Comment by JuergenRichter** [comment]
Bei "Beschäftigungsart" ist auch ein Fehler, hier muss der SQL-Befehl wie folgt lauten:
select LA.Beschaeftigungsart from LehrerAbschnittsdaten LA, EigeneSchule ES where LA.Lehrer_ID=% AND LA.Schuljahresabschnitts_ID=ES.Schuljahresabschnitts_ID

**Comment by AnneSchueller** [comment]
Die SQL-Befehle sind im kommenden Update im SVWS-Server korrigiert.
