### ISSUE TITLE
SchILD3.0.80 gibt im Startbildschirm an, es sei noch 3.0.9.14

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#895]
Siehe Titel.

Ich eröffne das Issue nur um sicherzugehen, dass in Setup_SchILD3_v.3.0.80 auch wirklich die 80 steckt und nicht aus Versehen die 79 noch mal verpackt wurde.

"Kompliliert am" ist der 17.01.

**Comment by FPfotenhauer** [comment]
Danke. War mein Fehler.
Ich habe die Setups ausgetauscht.
