### ISSUE TITLE
Start SchILD3 (v. 3.0.80) schlägt fehl

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#896]
![Bug3 0 80start](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/9adcd736-47f4-499d-a7c7-06a3f189f9a4)

Log kann ich bei Bedarf nachreichen.

Installation wurde frisch mit V 3.0.80 und SVWS 0.8.8 vorgenommen, die DB wurde neu migriert.

Eventuell mit https://github.com/SVWS-NRW/Schild3-BetaTest/issues/895 verbunden?

**Comment by FPfotenhauer** [comment]
Das lag an der falschen Version im Setup.
