### ISSUE TITLE
SchILD3 hängt sich beim Starten auf (BK DB?)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#897]
Version 3.0.80.9
SVWS 0.8.8

SchILD3 bleibt beim Starten hängen. Nachdem die Passworteingabe passiert ist, bleibt das Programm hängen, in Windows wird dies nach einiger Zeit mit "keine Rückmeldung" angezeigt.

Ich habe Datenbanken für GS, GY und ein BK migriert. Das Problem tritt nur mit der BK DB auf, die anderen beiden starten.

Die BK-DB lief mit der vorherigen Version.

Unter X:\SVWS-Server-Data\Logs werden hierzu keine Logs erzeugt, es scheint sich also SchILD aufzuhängen, ohne Beteiligung des Servers.

**Comment by tpre** [comment]
Also unter Linux habe mit dem SVWS-Server auch so meine Probleme. Ich kann die DBs nicht migrieren, da der Server immer mit der Fehlermeldung
`Exception in thread "main" java.lang.NoSuchFieldError: Class de.svws_nrw.db.schema.Schema does not have member field 'de.svws_nrw.db.schema.tabellen.Tabelle_Schema_Revision tab_Schema_Revision'` 
die Migration abbricht.
Starte ich Schild und wähle die erzeugte Standard-DB, so erscheint ein Fenster mit der Meldung:
`42S02Table svwsdb.V_BenutzerDetails doesn't exist`

**Comment by FrodBRA** [comment]
Kannst du das bitte als eigenes Issue eröffnen?

Die Migration als solche scheint grundsätzlich in Ordnung zu sein, die läuft (unter Windows) jedenfalls problemfrei durch.

**Comment by AnneSchueller** [comment]
Ich kann das Problem von @FrodBRA  bestätigen. Allerdings läuft bei mir auch die Gy nicht in SchILD3

Im Client kann ich beide DBs starten. 
Die .con Dateien sehen richtig aus. 
Das Copy to Clipboard funktioniert nicht. Bzw. finde ich die Fehlerdatei nicht

@FrodBRA Wie hast du denn die DBs migriert, die bei dir laufen? Mit migrateDB.exe?

**Comment by FrodBRA** [comment]
Die GS habe ich bei der Neuinstallation mit über den Installer aus einer MDB migriert, die BK und GY direkt aus SchILD (Datenbank -> migirieren aus mdb).

**Comment by AnneSchueller** [comment]
Wenn ich DBs über den Client migriere, kann ich diese mit Schild3 öffnen.
Migriere ich die gleiche DB über migrateDB klappt das nicht.

Kann das daran liegen, dass ich bei migrateDB kein Passwort für die mdb angeben muss?

**Comment by FrodBRA** [comment]
Von SchILD aus ist auch kein Passwort notwendig.

Hier wäre noch zu klären, ob es sich um das gleiche Problem handelt. Läuft bei dir ein BK? Was ist, wenn du eine andere Art der Migration mit der gleichen DB durchführst?

(Morgen mehr)

**Comment by FrodBRA** [comment]
Habe die BK nun mit der MigrateDB noch einmal migriert. Gleicher Fehler, SchILD hängt sich beim Start auf.

Jetzt bekomme ich einen Fehler:

![Fehler Start BK](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/07e52534-5eb8-48f4-bd4d-2ed74b59541a)

[BK Error.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13973643/BK.Error.txt)

**Comment by JuergenRichter** [comment]
Wäre es möglich, die Datenbank (also die von SchILD2) mal zu bekommen?

**Comment by JuergenRichter** [comment]
Laut dem Protokoll tritt der Feher beim Laden der Programmeinstellungen auf, das ist also "DB-spezifisch", daher wäre es günstig, mal so eine DB zu bekommen.

**Comment by AnneSchueller** [comment]
Ich schicke Ihnen einen Download-Link

@FrodBRA : wohin wird das Copy to Clipboard gespeichert?

**Comment by FrodBRA** [comment]
Ich nutze immer Strg-V zum Einfügen in eine Datei.

**Comment by FrodBRA** [comment]
@JuergenRichter An welche E-Mailadresse soll mein BK gehen? (Das sind gepackt nur ca. 7 MB)

**Comment by JuergenRichter** [comment]
juergen.richter@ribeka.com

**Comment by JuergenRichter** [comment]
Ich habe die Datei mal geöffnet. Auffällig ist, dass der Inhalt des Feldes "Einstellungen" in der Tabelle "EigeneSchule" leer ist. Das ist ungewöhnlich und kommt vermutlich daher, dass die Datenbank frisch anonymisiert wurde, wobei die Einstellungen gelöscht werden. Dieser Fall tritt in der Praxis aber eigentlich nicht auf, daher konnte ich den Fehler bisher auch nicht reproduzieren. Ich werde das jetzt aber berückisichtigen.

**Comment by FrodBRA** [comment]
Das ist in der Tat eine anonymisierte Fachberatungs- und Test-Datenbank.

**Comment by AnneSchueller** [comment]
Vor dem Update, konnte ich die anonymisierten DBs nach der Migration öffnen.

@JuergenRichter: Dann können wir das Issue schließen oder?

**Comment by JuergenRichter** [comment]
Ja, bei der Migration werden jetzt aber die Einstellung an eine andere Stelle geschrieben, dazu musste der Vorgang geändert werden.

**Comment by JuergenRichter** [comment]
Das Ja bezog sich auf " konnte ich die anonymisierten DBs nach der Migration öffnen."

Ich habe jetzt aber den Fall "aus SchILD2 übernommene Einstellungen sind leer" abgefangen.
