### ISSUE TITLE
Fehlermeldung in MigrateDB.exe bei fehlendem Schema-Admin Benutzernamen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#899]
Wurde beim Benutzernamen kein "Schema"-Admin bzw. "SVWS"-Admin eingetragen, fragt die MigrateDB.exe nach einem "Schild"-Admin.

Diese Meldung ist explizit falsch, hier muss auch nach dem SVWS-Admin gefragt werden.

Lässt man das SVWS-Passwort-Feld frei, ist die Fehlermeldung korrekt und es wird nach dem SVWS-Passwort gefragt.

Version 3.0.80.9

![FalscherAdmin](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/85fd11f8-57fc-48e9-9eff-3b614967e8b7)

**Comment by FrodBRA** [comment]
(Da steht auch "einen Benutzernamen den den...", das wäre dann gleich mitzukorrigieren.)

**Comment by JuergenRichter** [comment]
Behoben

**Comment by JuergenRichter** [comment]
Es wird jetzt "Bitte geben Sie einen Benutzernamen für das Datenbankschema ein" ausgegeben, das passt besser zu den Überschriften

**Comment by Raffenberg** [comment]
Der Begriff Benutzername ist aber dann doppelt besetzt und verwirrend.

**Comment by JuergenRichter** [comment]
So sieht es jetzt aus:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/6b5eb350-7a9d-45f7-9700-d449ad195ca0)

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/35bb0002-5843-4ca6-af3e-b8496fd29e38)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/55a9c7b2-d656-4ded-a2a5-55f564b46285)

**Comment by JuergenRichter** [comment]
Ich habe die Überschrift "Kennwort" noch in "Kennwort für Datenbankschema" geändert.
