### ISSUE TITLE
rote Pfeile bei Auswahl überflüssig

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#90]
Im Bereich >Auswahl< wird im rechten Bereich der Umgang mit dem roten Pfeil erklärt. Bei vielen Mehrfachauswahlfeldern gibt es aber keinen roten Pfeil mehr, weil man in der Pull-Down-Liste direkt auch mehrfach auswählen kann. Es gibt nur 3 rote Pfeile (Besondere Merkmale, Vermerkart, Lernabschnitt/Leistungsdaten). Dadurch ist die Erklärung zum roten Pfeil irritierend. Vielleicht können die 3 Felder mit den roten Pfeilen so verändert werden, wie die anderen Mehrfachauswahlfelder. Dann kann die Erklärung zum roten Pfeil gelöscht werden.

**Comment by JuergenRichter** [comment]
Der Hinweis ist nun rausgenommen. Da, wo noch ein roter Pfeil existiert (nur bei Vermerken und Merkmalen) ist dieser aber notwendig.
