### ISSUE TITLE
Migration läuft ewig, wird aber nicht abgeschlossen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#900]
Version 3.0.80.9
SVWS 0.8.8

Bei einer meiner DBs, eine GES, lässt sich die Migration anstoßen, sie läuft, wird aber nicht abgeschlossen sondern läuft und läuft.

Migrationen laufen bei mir sehr schnell durch und auch diese DB habe ich in einem "normalen" Zeitrahmen von 1 bis vielleicht maximal 3 Minuten migriert. Diese Migration läuft schon nun seit deutlich über ~~20~~ 30 Minuten.

Im Ressourcenmonitor ist auch zu sehen, dass hier nicht aktiv irgendwas migriert wird.

Genau die gleiche DB habe ich in der Vergangenheit schon oft migriert.

Kann ich irgendwo sehen, was die Migration vermeintlich tut?

Ich kann die betreffende DB zum Selbsttesten verschicken.

**Comment by FrodBRA** [comment]
CPU zeigt kein Migrationsmuster bei der GES-Migration (links):

![Falsche Migration](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/d98edeb8-d578-4890-ba92-9cfe4580c5d2)

**Comment by AnneSchueller** [comment]
In der log Datei kannst du das verfolgen.
Im Ordner C:\ProgramData\SVWS-Server\logs
Datei ....out.log

**Comment by FrodBRA** [comment]
Meine neue Migration läuft noch - und tatsächlich füllt sich das log sehr, sehr langsam mit Umschreibungen der Quartale/Leistungsdaten, in dem die Schule früher war. 

Die Migration wird hierdurch viel, viel langsamer als sie es mit einer der 0.7.x-Versionen des SVWS-Servers war. Ob man hier noch mal reingucken möchte, weiß ich nicht. Die Migration läuft nun wieder seit ca. 30 Minuten und seit 25 davon werden nur noch Quartale zu Halbjahren umgeschrieben.

**Comment by FrodBRA** [comment]
Hat jetzt gut 45 Minuten gedauert, ist aber durch.

Normale Migrationen dauern an sich nicht länger als fünf Minuten.

Diese Blöcke hier:
```
- Schuljahres-Abschnitt 41 (Schuljahr 2020/21, 1. Halbjahr, Quartal 1):
              - Übertragen der Leistungsdaten und der Teilleistungen der zugehörigen Schüler-Lernabschnitte in den jeweiligen Folgeabschnitt (ID des Folge-Schuljahresabschnitts: 16)...
              - Verschiebe die Kurse in das zweite Quartal des Halbjahres, welche im zweiten Quartal nicht entsprechend angelegt wurden...
              - Entferne die Schülerlernabschnitte, dessen Leistungsdaten gerade in das 2. Quartal übertragen wurden...
              - Entferne die Kurszuordnung bei Schülerleistungsdaten, wo der Schüler ansonsten einem Kurs doppelt zugeordnet wäre (Fehlerkorrektur von unstimmigen Leistungsdaten)...
              - Korrigiere die Kurszuordnung bei den übertragenen Leistungsdaten, welche noch Kurszuordnungen zu Kursen in dem übertragenen Schuljahresabschnitt haben...
```

Davon gibt es 60 Stück, die haben den größten Teil der Zeit in Anspruch genommen - und zugebenermaßen wurden auch Schuljahre migriert, die eigentlich schon aus der Löschfrist herausfallen.

Das war in den vorherigen Versionen des SVWS-Servers nicht so, @FPfotenhauer Soll hier noch was gemacht werden? Falls nicht - also falls es sich nicht um einen neuen Fehler handelt, der die lange Dauer zur Folge hat - würde ich  den Hinweis in die Dokumentation aufnehmen, dass bei einem vorherigen Quartalsbetrieb das Migrieren halt ungewöhnlich lange dauern kann.

**Comment by FPfotenhauer** [comment]
Das ist kein Fehler, das ist die Umwandlung des Quartalsbetriebs.
Wir haben da schon mehrfach versucht das zu optimieren. 
Es dauert halt einfach.
