### ISSUE TITLE
Migrationsabbruch unter Linux

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#901]
Hier nochmal die Installationsproblematik unter Linux seit dem Update:

Also unter Linux habe mit dem SVWS-Server auch so meine Probleme. Ich kann die DBs nicht migrieren, da der Server immer mit der Fehlermeldung
Exception in thread "main" java.lang.NoSuchFieldError: Class de.svws_nrw.db.schema.Schema does not have member field 'de.svws_nrw.db.schema.tabellen.Tabelle_Schema_Revision tab_Schema_Revision'
die Migration abbricht.
Starte ich Schild und wähle die erzeugte Standard-DB, so erscheint ein Fenster mit der Meldung:
42S02Table svwsdb.V_BenutzerDetails doesn't exist

**Comment by AnneSchueller** [comment]
@tpre: 
War das eine anonymisierte DB?
War das die SVWS-Serverversion 0.8.8?
Hast du eine out.log-Datei?

**Comment by tpre** [comment]
Das sind die TestMDBs . SVWS-Server 0.8.8. Jch habe direkt keine out.log gesehen. Wo finde ich die?

**Comment by AnneSchueller** [comment]
Kannst du denn das Admin-Tool öffnen?:
https://localhost/admin

Unter Windows liegen die log-Dateien hier:
C:\ProgramData\SVWS-Server\logs
Hilft das weiter?

**Comment by FrodBRA** [comment]
Die Datei heißt svws_server_service.out.log.

**Comment by FPfotenhauer** [comment]
Wurde der Installer als Neuinstallation ausgeführt?
Oder als Update?

Wenn man das Update ausführt muss man ```./install-0.8.8.sh --update``` ausführen.
Außerdem muss man vorher in der .env Datei die Versionsnummer im Download link anpassen.
Das zweite werden wir ändern, das vergisst man zu schnell.

**Comment by FPfotenhauer** [comment]
Im nächten Release ist die Download-URL aus der .env datei entfernt.
Die braucht man dann nicht mehr anpassen.
Außerdem werden wir noch eine Abfrage einbauen, ob ein SVWS-Server läuft.
Das "--update" wird dann nicht mehr "vergessen".

**Comment by tpre** [comment]
Ich habe alles Mögliche probiert und bin auch am Anfang eigentlich recht zielgerichtet vorgegangen, auch --update hatte ich zuerst probiert, wie auch das Anpassen der URL in der install...sh . Vielleicht entstand das Problem, weil ich am Anfang der neue tar-Archiv heruntergeladen habe, wo der Build-Prozess noch nicht abgeschlossen war, was mir hinterher aufgefallen war, als die entsprechende Mail kam. Deshalb musste ich mir das install-Skript auch anpassen, da das zu diesem Zeitpunkt noch nicht zum Download zur Verfügung stand.
Ich hatte zwischendurch mariadb deinstalliert und wieder neu installiert. Erst als ich alle Dateien (/opt/app/* und /etc/app/*) gelöscht habe, hat es wieder funktioniert.

Ich denke wir können das hier dicht machen.
