### ISSUE TITLE
Schild3 startet nicht mit der default-DB des SVWS-Servers

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#902]
Hängt evtl. mit dem Issue https://github.com/SVWS-NRW/Schild3-BetaTest/issues/897 zusammen!?

Installiert ist ein SVWS-Server 0.8.8 unter Windows und SVWS-Client als auch SVWS-Admin funktionieren.

Startet man Schild 3.0.80.9 und wählt diesen SVWS-Server, so erscheint zunächst der SQL-Cursor und bleibt eine Weile, dann kommt der animierte runde Cursor und bleibt lange. Als ich dann das Programm über rechte Maustaste->Fenster schließen beenden wollte kam ein Fehlerdialog wie im o.g. Issue. Die Datenbank die geöffnet werden soll, ist die leere beim ersten Aufruf des SVWS-Clients erzeugt wird.

Das Eureka-Log (per Copy to Clipboard, eine Datei wurde nicht erzeugt) ist hier:

[EurekaLog 7.11.1.7 update 1 RC 7 B4.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/13993977/EurekaLog.7.11.1.7.update.1.RC.7.B4.txt)

Das gleiche Schild3 hat aber keine Probleme eine der Test-DB migriert auf einem SVWS-Server unter Linux übers Netzwerk zu öffnen.

**Comment by FPfotenhauer** [comment]
Das sollte in der nächsten Version mit erledigt sein. Das hängt tatsächlich mit #897 zusammen.
