### ISSUE TITLE
BK: qryEinschulungsArtAlt: Operation bei geschlossener Datenmenge nicht ausführbar

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#906]
Version 3.0.81.9

Beim Schließen von SchILD:

![BK](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/77cc9053-ebf6-4fa8-9779-821a061c44fc)

[BK.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14052457/BK.txt)

(wieder eine anonymisierte DB)

**Comment by JuergenRichter** [comment]
Behoben
