### ISSUE TITLE
Layout Karteireiter Erziehungsberechtigte

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#907]
Es werden unter dem Karteireiter Erziehungsberechtigte nur zwei Erzieher angezeigt. Es gibt aber sehr häufig auch noch betreuende Personen oder ähnliches. Es müssten auf jeden Fall immer alle "Erzieher" angezeigt werden. In diesem Fall fehlen zum Beispiel die Ansprechpartner der Wohngruppe.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/85374abb-37b4-4de4-954e-5e8b2f0f4b42)

**Comment by Raffenberg** [comment]
Ich stimme dem zu. Hier sollten 4 Personenarten zu sehen sein, ohne das gescrollt werden muss.

**Comment by JuergenRichter** [comment]
Ich habe jetzt einen "Splitter" eingebaut, mit dem man die Höhe des "Erzieherbereiches" (auf Kosten des "Telefonbereiches" vergrößern kann:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/bde4dde1-52a7-41f3-9d5f-007d40b5f264)

Die Einstellung "merkt" sich das Programm auch.
