### ISSUE TITLE
Karteireiter Erziehungsberechtigte / Telefonnummern: "Gesperrt"

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#908]
Bei den Telefonnummern gibt es die Option "gesperrt". Es ist sicherlich "für die Weitergabe gesperrt" gemeint. Das ist aber unklar. Es könnte auch so verstanden werden, dass die Telefonanlage die Nummer nicht anwählt oder aktuell nicht angerufen werden soll.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/aba32f1f-110d-4d7e-85cc-3704557ff58a)

**Comment by AnneSchueller** [comment]
Ich denke auch, dass dies dem analogen Feld "für Weitergabe gesperrt" aus Schild2 entspricht und das hier nicht ganz klar wird.
Allerdings frage ich mich, ob die Weitergabe von Nummern nicht prinzipiell immer gesperrt ist.
Das Feld spiegelt dann eher sowas wie "Streng vertraulich" oder so wieder. 
Oder war es ursprünglich so gedacht, dass der Haken hier standardmäßig gesetzt ist und die Schulen diesen nur nach Genehmigung der Weitergabe entfernen?

**Comment by JuergenRichter** [comment]
Die Überschrift kann man ändern. Wenn ein Eintrag gesperrt ist, wird er z.B. auch nicht in der "Telefon-Datenquelle" für Reports berücksichtigt.

**Comment by AnneSchueller** [comment]
Würde das vom Platz her denn passen, wenn man das Feld analog zu dem Feld in SChild2 umbenennt in
"Für Weitergabe gesperrt"

**Comment by FrodBRA** [comment]
Hier besteht das Problem: in SchILD2 was dieses Feld meiner Erinnerung nach nirgends abrufbar, d.h. in der Datenquelle über die Telennummern nicht enthalten. Ist das nun anders?

**Comment by JuergenRichter** [comment]
In Schild waren solche Telefonnumern gar nicht in die Datenquelle vorhanden, daher braucht man das Feld dort auch nicht

**Comment by FrodBRA** [comment]
Wenn das bei SchILD3 ebenso ist, kann ich das dokumentieren.

**Comment by AnneSchueller** [comment]
Ich hatte hier bereits einen Hinweis im Wiki hinzugefügt. Das kann natürlich gerne noch ergänzt werden.
