### ISSUE TITLE
Fehlermeldung beim Hinzufügen eines Faches

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#909]
Ich wollte für eine Schülerin aus der Q2 ein Fach in der EF.2 hinzufügen:

1. Klick auf "+" (Fach hinzufügen)
2. Kurs PH-GK1 ausgewählt (Der Kurs erschien im Drop-Down Menu
3. Mit Haken bestätigt
4. Fehlermeldung:

[fehlermeldung.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14064439/fehlermeldung.txt)

Hinweis: 
Zuvor wurde Physik in EF.1 hinzugefügt
Andere Kurs lassen sich in EF.2 ohne weiteres einfügen

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/1029e907-d708-4509-9a7e-9f61691f28bb)

**Comment by AnneSchueller** [comment]
Ergänzung:
Nach Betätigen von "automatische Prozesse ausführen" klappt alles.
Könnte man das abfangen, dass es auch ohne automatische Prozesse geht?

**Comment by JuergenRichter** [comment]
Ich hatte einen ähnlichen Fehler auch schon mal, den ich mir absolut nicht erklären konnte. Ich hatte damals den Verdacht, dass die Ursache irgendwie in der Datenbank zu suchen ist. Es gibt dort ja einen Trigger, der automatisch einen Einrag in der Tabelle "Kurs_Schueler" macht. Kann es sein, dass der heir "dazwischenfunkt"?

**Comment by JuergenRichter** [comment]
Zumindest würde der Text in der Fehlermeldung

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/81bd352c-83d6-40c3-bff8-d99d05cb3a68)

zu der Struktur des Primärschlüssels in der Tabelle passen:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/7ee99fee-f9a9-4f69-8445-b7ed6dc70381)

**Comment by JuergenRichter** [comment]
Es kann aber auch sein, dass bei der Eingabe eines Kursunterrichtes in einem vergangenen Abschnitt auf die Kurseinträge des aktuellen Abschnittes zugegriffen werden. Das führt dann dazu, dass es tatsächlich in "Kurs_Schueler" zu einem doppelten Eintrag kommt, wenn der betreffende Kursunterricht schon mit der gewählten Kurs-ID existiert (nämlich im aktuellen Abschnitt). Ich werde das prüfen.

**Comment by AnneSchueller** [comment]
Das passiert bei meiner DB nur mit dem Kurs PH-GKxx
Bei dem Fach PH klappt alles
Beim Kurs BI-GK1 klappt es auch.

**Comment by JuergenRichter** [comment]
Ich habe folgendes festgestellt:

Wenn man die "Kurs-Dropdownliste" bei den Leistungsdaten explizit aufklappt (über das Pfeilsymbol rechts im Eingabefeld) werden die Kurse auf das betreffende Halbjahr gefiltert, dann funktioniert es. Wenn man aber direkt in das Feld tippt, wird zwar auch die Liste aufgeklappt, es erfolgt aber keine Filterung, d.h. es werden die Kurse des akt. Halbjahres angezeigt. Könnte das die Ursache sein, das es mal funktioniert, mal nicht?

**Comment by AnneSchueller** [comment]
Tatsache...
Wenn ich über das Dropdown-Menü gehe, gibts auch beim Physikkurs keine Probleme.
Kann man das abfangen, sodass bereits beim Reinklicken in das Kursfeld die Halbjahreskurse geladen werden?

**Comment by JuergenRichter** [comment]
Dafür suche ich gerade eine Möglichkeit.

**Comment by AnneSchueller** [comment]
Fehlermeldung ist noch vorhanden in 3.0.82.9

**Comment by JuergenRichter** [comment]
Bei mir klappt es.

**Comment by AnneSchueller** [comment]
Bei mir jetzt auch
