### ISSUE TITLE
Reiter Kataloge unübersichtlich

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#91]
Wenn ich den Reiter Kataloge anwähle, wird direkt der Katalog Staatsangehörigkeiten aufgerufe. Es ist aber nicht sichtbar, dass ich in diesem Katalog bin. Es ist auch nicht direkt nachvollziehbar, wie ich einen anderen Katalog auswählen kann.
Meineserachtens wärer es sinnvoller, dass ein Auswahlfenster geöffnet wird in dem ich den gesuchten Katalog auswählen kann.
Außerdem ist das Bild für den Bereich Allgemeines (ein Dreieck wie ein Abspielbutton) nicht passent.

**Comment by FPfotenhauer** [comment]
Das Konzept sieht vor, dass modale Fenster möglichst vermieden werden sollen.

**Comment by FPfotenhauer** [comment]
Wurde komplett überarbeitet.
