### ISSUE TITLE
Inkonsistenzen Schild3 vs SVWS-Client durch Löschen von Fächern

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#910]
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/0d7a05e9-bd81-4bde-9f83-6993dcdf8571)

Ich habe in Schild3 S0 gelöscht. Im Client bleibt das erhalten. Analog beim Löschen anderer Fächer.
Physik habe ich hinzugefügt über Schild3 in der EF. Dies ist nun auch im Client sichtbar. Es ist definitiv die gleiche Datenbank.

**Comment by JuergenRichter** [comment]
Wenn in SchILD eine Eintrag bei den Leistungsdaten gelöscht wird, so sollte dieser auch explizit physikalsich gelöscht sein (müsste mich irren, wenn das nicht so wäre). Auch ist die "Datenbank-Connection" auf "AutoCommit" gestellt, d.h. bei einem DELETE sollte autom. auch ein COMMIT erfolgen.
Frage: Ist denn in der Datenbank das Fach S0 beim Schüler noch vorhanden?

**Comment by JuergenRichter** [comment]
Frage: Ich kenne jetzt die Oberstufenplanung im SVWS-Server nicht, aber werden denn die Daten dort aus der Tabelle "SchuelerLeistungsdaten" geholt? Oder aus "SchuelerAbifaecher"? Oder einem anderen Bereich?

**Comment by AnneSchueller** [comment]
In den Leistungsdaten ist das Fach definitiv gelöscht.
In der Tabelle gost_schueler_fachwahlen ist es noch da:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/cf91e4f4-5336-4808-90ba-6c83cf6a37d1)

**Comment by JuergenRichter** [comment]
Das ist in SchILD2 derzeit aber auch nicht anders. Wenn ich da z.B. ein Fach in den Q2-Leistungsdaten lösche, ist es weiterhin in SchuelerAbiturfaecher vorhanden (sofern die Daten schon geholt wurden).

**Comment by Raffenberg** [comment]
Du müsste Thomas wahrscheinlich einen Blick drauf werfen. Wie genau die Datensätze "Leistungsdaten" und "Lupo-Planungsdaten" hier in den Tabellen aufgebaut sind, weiß ich auch nicht.

**Comment by FrodBRA** [comment]
Hat das damit zu tun, dass SchILD "Kataloge" im laufenden Betrieb nicht mehr/nicht immer neu einliest? Bislang war das kein so großes Problem, wenn nun diese Arbeiten auch in einem anderen Client vorgenommen werden, müsste SchILD auch eine Möglichkeit haben (automatisch?) den kompletten Datenbestand zu refreshen. Ich meine zumindest, dass wir hierüber in einem anderen Kontext schon einmal diskutiert hatten?

**Comment by FPfotenhauer** [comment]
Wir reden hier aber von den Laufbahndaten, die müssen anders gespeichert werden als die Leistungsdaten, da zu dem Zeitpunkt, wo die Planungen gemacht werden, die Kurse ja noch gar nicht existieren.

Im Grunde muss jemand, der ein Fach in den Leistungsdaten bei einem Oberstufenschüler löscht, auch die Laufbahn anpassen.

Schild3 müsste das löschen entweder verweigern, wenn Laufbahndaten vorhanden sind oder die Laufbahn anpassen.
Da würde ich eher zum ersten tendieren. Oder einen Hinweis geben?

**Comment by AnneSchueller** [comment]
Das Problem war folgendes:
1) Migration einer MDB
2) Abiturjahrgang Anlegen 
3) Laufbahnen sichten und Fehlbelegung im aktuellen HJ festgestellt
4) Änderungen über SchILD3 vorgenommen 
Eine Änderung bei den Laufbahndaten, sowie Löschen und neu Anlegen war nicht mehr möglich. 

Ich habe das gerade mit einer anderen DB nochmal getestet. Dort klappt die Anpassung in der Laufbahnplanung auch für vorangegangene Abschnitte.
Warum das mit der anderen DB nicht klappt, kann ich mir nicht erklären.
Ich schließe  das Issue mal und beobachte das Problem weiter .

**Comment by ThomasBachran** [comment]
Ein Fehler konnte identifiziert werden. Hat ein Schüler einen Lernabschnitt wiederholt, so wurde eine Fachwahl nicht korrekt entfernt werden, wenn diese Fachwahl in dem wiederholten Lernabschnitt noch vorhanden war. Dieser Bug wurde jetzt behoben. Außerdem wird in der Laufbahnplanung jetzt gekennzeichnet, wenn in Lernabschnitten mit Leistungsdaten eine Diskrepanz zwischen Laufbahnplanung und Fachwahlen besteht. Mit dem nächsten Pre-Release des SVWS-Server kann nochmal getestet werden, ob hier weitere Inkonsistenzen bestehen sollten.
