### ISSUE TITLE
Import von E-Mail Adressen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/Schild3-BetaTest#911]
Insbesondere am Anfang des Schuljahres sollen mindestens von der neuen JgSt. 5 die von der Schule vergebenen EMail-Adressen (vorname.nachname@...) nach Schild importiert werden. Bei uns zusätzlich auch noch die von uns vergebenen EMail-Adressen der Eltern (vorname.nachname.eltern@...).
Die EMail Adressen werden von uns über eine Excel-Datei erstellt, wo Umlaute, weitere Vornamen, evt. Doppelnamen eliminiert werden. In der Excel-Datei sind Schild-ID, Nachname, Vorname, Geb-Datum, Klasse, usw. vorhanden. Von dort aus kann ich eine CSV-Datei erstellen, wo z.B. die Schild-ID und die beiden EMail-Adressen enthalten sind.
Gibt es eine Möglichkeit, diese Adressen über diese CSV-Datei direkt zu importieren? Bisher musste ich sehr umständlich die dat-Dateien exportieren, verändern und reimportieren. Das wäre schön, wenn das einfacher ginge.

**Comment by AnneSchueller** [comment]
Bisher gab es in Schild2 immer ein externes Importprogramm. 
War ein ähnlicher Import (allerdings ohne externes Programm) ursprünglich auch bei SchILD3 geplant?
Wie sieht das hier mit der Umsetzbarkeit aus?

**Comment by Raffenberg** [comment]
Das ist aber eine neue größere Baustelle, die wir jetzt erst einmal nicht aufmachen sollten. Der Import über dat-Dateien ist ja möglich.

**Comment by AnneSchueller** [comment]
Ja das ist definitiv eine größere Baustelle und daher erstmal auch ein "Nice to Have"-Milestone. Hier müsste man auch mal recherchieren, was Schulen flächendeckend für Importe benötigen. Wenn bestimmte Importe für viele Schulen nützlich sind, könnte man mal darüber nachdenken, das irgendwann hinzuzufügen. Ich gebe zu, dass der Import von Mailadressen über die dat-Dateien nicht unbedingt komfortabel sind. 

Meine Frage zielte erstmal nur auf die Umsetzbarkeit ab.

**Comment by AnneSchueller** [comment]
"Neue" Exportmöglichkeiten werden später ggf. über den SVWS-Server bereitgestellt.
Daher schließe ich das Issue mal.
