### ISSUE TITLE
Datenquellen im Report-Designer sind nicht alphabetisch sortiert

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#912]
SchILD: 3.0.81.9
SVWS: 0.8.8

Ich nehme an, dass das vom SVWS-Server kommt?

Eventuell könnte eine alphabetische Sortierung in SchILD grundsätzlich für alle Datenquellen und Datenfelder durchgeführt werden?

**Comment by JuergenRichter** [comment]
Behoben
