### ISSUE TITLE
Fehler BK: Gruppenprozess "Vorläufige Abschlussnoten berechnen"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#913]
SchILD 3.0.81.9

Beim Klick auf GP "Vorläufige Abschlussnoten berechnen" im BK-Abschluss gibt es diesen Fehler:

![BKAbschlussGP](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/52413c8d-3ee4-401d-8b9b-ce72d8214e5b)

[BkAbschlusGP.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14083055/BkAbschlusGP.txt)

Es handelt sich um eine anonymisierte BK DB.

**Comment by JuergenRichter** [comment]
Behoben
