### ISSUE TITLE
Fachklasse im Schnellfilter nicht auswählbar

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#914]
Nach Auswahl einer Fachklasse kann der graue Haken nicht geklickt werden:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/766815a0-6bef-4bd3-bb17-fb4fe2ec0715)

**Comment by JuergenRichter** [comment]
Behoben
