### ISSUE TITLE
Filter auf Fachklasse (BK) funktioniert nicht

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#915]
Der Filter auf Fachklasse funktioniert nicht.
Wenn ein Bildungsgang gewählt wird, wird der Haken nicht rot:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/4994265d-de9d-4f8a-a685-7dfc9fb5201c)

Wenn man eine Klasse auswählt und wieder entfernt, bleibt der Haken rot,
aber es wird der folgende Fehler produziert:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/1963ff1f-53b3-4718-9b18-643f3ccdf08e)

Der Fehlerreport: 
[FilterFehler.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14084724/FilterFehler.txt)

**Comment by JuergenRichter** [comment]
Ist auch schon korrigiert
