### ISSUE TITLE
Rendering von IndividualdatenI nicht gut

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#916]
Die Seite wird nur suboptimal dargestellt (rote Rechtecke), Platz wäre da (grüne Rechtecke):
Was mir gerade noch aufgefallen ist, das der Text oben (Normalklass**e)** nicht ausgeschrieben ist.
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/b6f8d9f2-6cbc-49aa-9788-9eca41ee5e6c)

**Comment by AnneSchueller** [comment]
Hallo Ewald,
kannst du hier noch ein paar Infos schreiben, mit welcher Auflösung und Betriebssystem du arbeitest?
Ein Fachberater hat mir ein ähnliches Problem per Mail beschrieben, welches ich allerdings nicht reproduzieren konnte.  
Er schilderte, dass die Darstellung richtig war nach einer Umstellung auf HD, einem Neustart von Schild und anschließend wieder zurück auf 4K.
Das Problem trat hier jedoch nur auf, wenn Fotos importiert waren:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/24da7c9a-166c-4548-b4bd-75558e7878a8)

**Comment by FrodBRA** [comment]
Eventuell sollten wir auch mal Grafikchips sammeln, mit denen die Probleme auftreten, denn grundsätzlich sollte die UI mittlerweile recht sauber sein.

Einige der Renderfehler treten bei mir auch auf, i.e. der mit dem Schwerpunkt. Das ist ein Skalierungsfehler. Die anderen nicht.

Hier müssten wir auch testweise mal Auflösungen unter dem Minimum fahren - nicht um das zu fixen, sondern um zu wissen, wie dann auftretende Fehler aussehen. Ich kann mir durchaus vorstellen, dass Schulen mit "Alt-Laptops" als Nebenstelle SchILD betreiben werden.

**Comment by EwaldReinhardt** [comment]
Das ganze hängt damit zusammen, welche Höhe (Größe nicht Position) das Programmfenster hat.
Wenn die Elemente aus dem Reiter alle voll sichtbar sind und der obere Abstand (wieso ist oberhalb eigentlich dieser
Abstand und nicht unterhalb?) auch etwas da ist, wird nach einem Neustart die Anzeige fehlerhaft.
Im Vollbildmodus auf HD-Auflösung sollte der Fehler im Vollbildmodus !beim Start! auftreten.
Ich habe das mit verschiedenen Auflösungen:
Hier mit 3840*1365 über RDP:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/00f5447f-647c-4ade-a9a2-f59cfbf1a2c1)

**Comment by FrodBRA** [comment]
> RDP

Könnte das der Schuldige sein? Dass über RDP Auflösungen falsch übergeben werden, wenn der Host eine andere fährt, kann ich mir sehr gut vorstellen.

@EwaldReinhardt Tritt der Fehler auch auf, wenn du SchILD nativ startest (nicht über RDP).

**Comment by EwaldReinhardt** [comment]
@FrodBRA ich meine, dass ich es auch direkt auf dem Laptop so gesehen habe. Muss ich mir zuhause auf meinem Rechner nochmal anschauen.

**Comment by JuergenRichter** [comment]
Das sollte in der in Kürze erscheinenden neuen Version behoben sein.

**Comment by EwaldReinhardt** [comment]
Das Problem scheint nicht mehr zu bestehen in der Version 3.0.8.10
