### ISSUE TITLE
Rendering Reiter Akt. Halbjahr schlecht gerendert abhängig von Theme-Einstellung

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#917]
Korrektur: Mit dem Theme besteht kein Zusammenhang!
Der Bereich Allgemeine Angaben I nur abgeschnitten dargestellt wenn:

1. Das Programm ist beim Starten nicht sehr groß
2. Bevor das Fenster vergrößert wird wechselt man auf den Tab akt. Halbjahr.
3. Wenn jetzt das Fenster vergrößert wird, wird der Bereich nicht mehr komplett dargestellt,
was sich auch nicht mehr heilen lässt ohne neue zu starten.

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/5f3b147b-c339-43fd-ad25-37732159ece5)

**Comment by FrodBRA** [comment]
Das ist aber soweit in Ordnung, oder?

SchILD-NRW hat eine Mindestgröße der Fenster, um sinnvoll zu arbeiten. Wird es zu klein initialisiert, sind die Fenster zu vergrößern und dann funktioniert es nach einem Neustart.

Ich würde vorschlagen, dass SchILD-NRW beim Start mit auf jeden Fall der notwendigen Mindestgröße für eine korrekte Darstellung initialisiert wird. Falls das mit dem verwendeten Bildschirm nicht passt, muss man eben einen mit den Mindestanforderungen entsprechender Auflösung verwenden.

**Comment by AnneSchueller** [comment]
Das funktioniert mittlerweile. Auch wenn man mit einem kleinen Fenster startet und das Programm im akt. HJ vergrößert.
