### ISSUE TITLE
Fehlende Anzeige des Langtextes Fachklasse im Katalog Versetzungstabelle

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#918]
Im roten Kasten soll doch der Name der Fachklasse dargestellt werden. Fehlt aber!
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/7ebc7729-8f9c-4948-a0a4-59050a7b22a9)

**Comment by JuergenRichter** [comment]
Erledigt
