### ISSUE TITLE
Reiter Schüler -> Abitur: Textbox für Facharbeitsthema passt nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#920]
3.0.81.9

![UI Abitur](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/84baf926-4284-4232-8fd1-3a00f5d54d3c)

**Comment by AnneSchueller** [comment]
@FrodBRA: Könntest du noch ein paar Infos zu deinem Bildschirm schreiben?
Bei mir passt das Feld (2560 x 1080; Skalierung 100%; Breiter Bildschirm)

**Comment by AnneSchueller** [comment]
Wahrscheinlich analog zu hier (4k, 150%)
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/921

**Comment by FrodBRA** [comment]
Standard 4k (3.840 x 2.160) @150%

**Comment by Raffenberg** [comment]
Ich habe an verschiedenen PCs verschiedene Auflösungen getestet. Ich erhalte nur dann eine normale Verteilung der Elemente in Schild, wenn ich die Skalierung auf 100% setze.

Bei recht normalen PCs mit Full-HD ist dieser Skalierungsfaktor zu klein für unsere Sekretärinnen. Die 24 Zoll Monitore mit Full-HD scheinen mittlerweile Standard in Verwaltungen zu sein, zumindest, was ich so mitbekomme. Die neueren Monitore in dieser Größe haben schon eine Auflösung von 2560 × 1440px mit von Windows empfohlener Skalierung von 125% und genutzer von 150%. Bei UHD sind es empfohlene 150% und genutzte 175%.

So oder so kommen wir nach meinem Dafürhalten um eine Anpassung nicht rum. Momentan kann man mit Schild arbeiten, langfristig müsste aber eine Lösung gefunden werden.

**Comment by JuergenRichter** [comment]
Ich werde das Layout mal intensiv auf meinen 4K-Monitor mi 150% testen.

**Comment by JuergenRichter** [comment]
Das Problem "Thema der Facharbeit" ist behoben (trat nur am BK auf), dabei wurde auch die Überschrift "Projektkurs" in "Facharbeit" geändert (am BK).
