### ISSUE TITLE
Skalierungsfehler (4k, 150%): Sammelissue

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#921]
~~3.0.81.9~~
3.0.82.9

Skalierungsfehler in "Aktuelle Schülerauswahl" und "Aktuelle Laufbahndaten".

![SkalierungBK1](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/9968f811-5ff1-4043-962c-99d8ee340861)

**Comment by FrodBRA** [comment]
3.82.0.9

- Die Fehler in "Aktuelle Schülerauswahl" sind  in 3.0.82.9 noch enthalten (beide).

- In "Aktuelle Laufbahndaten" passt bei einem Gymnasium der Eintrag "Prüfungsordnung" nicht", ebenso passt die "Private E-Mail-Adresse nicht".

![SkalierungGy](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/e26815e3-a5b2-4c3c-9b45-3b9d632489ce)

**Comment by FrodBRA** [comment]
In meinem Gy sind auch die anderen Dropdown-Felder in "Aktuelle Schülerauswahl" betroffen: (sieht man im Screenshot oben schon, hier noch einmal in größer):

![SkalierungGy2](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/49990fcb-78a4-49e0-a59e-4be7726cc1da)

**Comment by AnneSchueller** [comment]
Analoge Probleme beim Schnellfilter
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/762

**Comment by FrodBRA** [comment]
Ich schließe das Issue einmal, da mit der neuen Version noch Änderungen kamen und mir nicht mehr klar ist, was neu und was alt ist. 

Ich werde bei Gelegenheit noch mal durchgehen und neue Issues reporten, die dann aber nur jeweils einen Fehler enthalten.
