### ISSUE TITLE
Fehlende UI in Kataloge -> Zertifikate

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#922]
3.0.81.9

Im Katalog "Zertifikate" fehlt die UI, um Zertifikate zu bearbeiten. (das "+" und "-", Festlegung der Reihenfolge usw.)

Es lässt sich daher nur ein Zertifikat anlegen und bearbeiten.

![UI Katalog Zertifikate](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/0b9ebf87-3ef3-4721-a361-214ceac5b884)

**Comment by AnneSchueller** [comment]
Das kann ich nicht reproduzieren. Hängt wahrscheinlich auch mit dem Bildschirm zusammen.
Bei mir sind die Pfeile zum Verschieben auch sichtbar und funktionieren.
Vgl.  https://github.com/SVWS-NRW/Schild3-BetaTest/issues/920

**Comment by FrodBRA** [comment]
Falls das ein Skalierungsproblem ist: 3840 * 2160 @150%

**Comment by JuergenRichter** [comment]
Ist nun behoben, siehe auch #928
