### ISSUE TITLE
Kleine Tippfehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#923]
3.0.81.9

Es finden sich noch einige wenige, aber durchaus prominente Tippfehler:

- "aktueller Schüler" ist im Gegensatz zu anderen Zeilenanfängen klein geschrieben
- "voraus. Abschluss" dito -> "Voraus. Abschluss"
- Bei 1. und "2. Staatsangehörigkeit" fehlt das Leerzeichen nach "1." und "2."

![Tippfehler](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/9bf51a6c-9c01-4d0f-840b-ca07f2958ead)

**Comment by JuergenRichter** [comment]
Behoben
