### ISSUE TITLE
Statistik Gesamtprüfung

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#924]
Bei der Gesamtprüfung der Statistik bekomme ich die folgende Fehlermeldung:
![Fehler1](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/78501680/01de0431-7bcf-402c-8451-0f945d44211f)

**Comment by FrodBRA** [comment]
Das liegt daran, dass SchILD3 die Statistik derzeit noch nicht offiziell unterstützt und die asdtabs.mdb nicht mitgeliefert wird.

Wenn du die aktuelle asdtabs aus SchILD2 in SchILD3 einkopierst, funktioniert alles wie erwartet.

@AnneSchueller Das Issue ist bis zum offiziellen Start der Statistiksupports zu schließen?

**Comment by FrodBRA** [comment]
Das kann ich bestätigen: Ich hatte mit 3.0.81.9 (derzeit 82.9) frisch installiert, die Keytabs fehlt mir auch.

Sie wurde mit der 81.9 nicht installiert und mit der 82.9 auch nicht als "aktualisiert" nachgetragen.

**Comment by FPfotenhauer** [comment]
Die Datei liegt im Ordner LDS.
Da sie ja nur von der Statistik.dll genutzt wird, finde icih den Ort besser.
@JuergenRichter Wollen Sie den Pfad ändern, sonst bitte kurz schreiben, dann setze ich die in den anderen Ordner.

**Comment by JuergenRichter** [comment]
Ich kann den Pfad ändern, ist kein Problem,

**Comment by FrodBRA** [comment]
Sofern die Änderung umgesetzt wurde, bitte ich um eine kurze Nachricht (oder das Issue einfach schließen), dann schreibe ich nach einem Test mit der dann aktuellen Version die Dokumentation um.
