### ISSUE TITLE
Schüler -> BK-Abschluss "Variables Feld" links der Leistungsdaten unten abgeschnitten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#926]
3.0.81.9

Im "Variablen Feld" in dem "Zulassung", "Abschlüsse" usw. angezeigt werden, ist mir aufgefallen, dass manche Felder unten grafisch mit dem "Rand und Schatten" geschlossen sind, andere Felder ganz unten nicht.

Da ich nicht weiß, ob das nur ein Darstellungsfehler ist oder ob etwas abgeschnitten ist, reporte ich das als Issue zur Prüfung und eventuellem fixen (grafisch oder funktional).

![Bk_Abschluss Abschnit und Dropdown](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/b8495471-c66f-443c-b978-630bc3bb5e7f)

**Comment by AnneSchueller** [comment]
Bei mir ist bei Notendurchschnitt auch ein Schatten

**Comment by JuergenRichter** [comment]
Layout wurde überarbeitet

**Comment by AnneSchueller** [comment]
@FrodBRA Ist das mit der neuen Version noch aktuell?

**Comment by FrodBRA** [comment]
3.0.82.9

Ja, das ist noch aktuell. Das Bild hat sich nun so verändert, dass die Boxen alle etwas ineinander rutschen:

![FelderBK](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/9cb0bbae-7e8b-435f-a75d-9ff61b698bcc)

**Comment by FrodBRA** [comment]
3.0.85.10: Sieht ok aus.
