### ISSUE TITLE
Schüler -> BK-Abschluss Dropdown-Menü "Aktueller Gesamtabschluss" lässt nichts auswählen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#927]
3.0.81.9

Das Dropdown-Menü im BK-Abschluss "Aktueller Gesamtabschluss" - optional angezeigt - zeigt keine Einträge zu Auswahl. 

Ist das so gewollt, d.h. das Feld wird nur automatisch befüllt bzw. in den Klassen, in denen ich getestet habe, liegen hier keine Einträge an, oder ist das ein Fehler, der zu reparieren wäre?

![Bk_Abschluss Abschnit und Dropdown](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/e4b16d9f-3123-4bc6-84cf-efb37b2734dc)

**Comment by AnneSchueller** [comment]
Hier sollte wahrscheinlich die Daten vorerst zur Auswahl stehen, die in Schild2 in der Schildintern sind?
@EwaldReinhardt: Die Umstellung auf die Swagger-UI erfogt meines Wissens nach erst später. Ist das richtig?

**Comment by EwaldReinhardt** [comment]
Ich denke, dass es hier um die Gliederung C01 geht. 
Das kann ich nicht sagen, da ich nicht weiß, was mit aktueller Gesamtabschluss gemeint ist.
Wenn es die Komination aus allgemeinbildend und berufsbildend gemeint ist, sollte diese sich aus
Abschluss FHR und Abschluss BA ergeben und gar nicht auswählbar sein.

Es wäre hier immer schön, wenn die Note der praktischen Prüfung auch über den gleichen Weg ins System kommen
kann, wie die anderen Noten der Abschlussprüfungen. (Stichwort Noten aus Teilleistungsnoten übernehmen)
Die Schüler in dieser Gliederung bekommen ja zwei Zeugnisse, die sich aufgrund unterschiedlicher Prüfungsfächer in den Fachnoten unterscheiden können.

**Comment by FrodBRA** [comment]
In der DB taucht so ein Feld bei der Gliederung auf (Stichprobenmäßig bin ich durchgegangen)
- A01
- C06
- E02
- C01

**Comment by AnneSchueller** [comment]
Hier mal einen Auszug über die Auswahl in SchILD2. Die Praktische Prüfung kann man ja ähnlich wie die Noten beim Abitur über den Gruppenprozess eintragen. Wäre das nicht ausreichend? Das machen doch sicherlich auch Koordinatoren, die direkten SchILD Zugriff haben.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/98e0786e-7800-4ef4-a73b-9b790116775f)

**Comment by EwaldReinhardt** [comment]
Ja, das ist wie bei den anderen Prüfungsnoten auch.
Wenn man das aber über Teilleistungen über SchildWeb abbilden will, ist bei der praktischen Prüfung dieser Weg nicht möglich. 

Ein Unterschied bei Schild3 zum Gesamtabschluss. Das Feld ist identisch mit dem aus deinem Screenshot. Heißt, wenn ich im Reiter BK-Abschluss den Eintrag ändere, ändert er sich auch unter Schulabschluss und vice versa. Das scheint in Schild3 nicht mehr so zu sein.

Die Frage ist, ob sich die Felder Abschluss-FHR, Abschluss-BA und aktueller Gesamtabschluss widersprechen können.

**Comment by AnneSchueller** [comment]
Ich habe nochmal bei einem C01-Spezialisten nachgefragt:
Widersprechen können sich die Felder nicht.

Allerdings gibt es bei FHR zwei Möglichkeiten: FHR (voll) und FHRsT (wenn der BA nicht bestanden wurde). 

Bisher waren die Felder bei "Zulassung" und "Abschluss" immer nur mit "ja" oder "nein" belegt. FHR und FHRsT konnten also nur über den Gesamtabschluss unterschieden werden. Die Ergebnisse von dort landen auch im Akt. Halbj. und bei "Schulbesuch".

Das Feld "Aktueller Gesamtabschluss" ist also die Addition der beiden anderen Felder. (Wie in der Statistik, wo am BK z.B. 0F usw verwendet wird.)

**Comment by EwaldReinhardt** [comment]
wenn FHR = Ja wurde die FHR-Prüfung bestanden.
Ob schulischer Teil oder komplett ergibt sich aus dem Wert in Berufsabschluss.
Die Kombi FHR=FHRs und BA=JA ist somit nicht zulässig!

Mein Kommentar ging in die Richtung, dass eine Auswahl (angedeutet durch das Drop-Down-Widget) möglich ist.
Würden sich dann die Felder automatisch anpassen, so dass sie widerspruchsfrei sind.
