### ISSUE TITLE
Zuordnung von Zertifikaten zu Schülern nicht mehr möglich

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#928]
In Schild2 konnte man hier Zertifkate zuordnen:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/3a1d1136-8a6c-4fa3-b34b-f17d479d9583)

Diese Möglichkeit scheint es in Schild3 nicht mehr zu geben.

**Comment by JuergenRichter** [comment]
Wird die Datei auch erzeugt? Habe nämlich bei mir noch einen Fehler entdeckt, der das verhinderte, ist nun aber korrigiert.

**Comment by EwaldReinhardt** [comment]
> Wird die Datei auch erzeugt?

Verstehe die Frage nicht? Welche Datei soll erzeugt werden?

**Comment by JuergenRichter** [comment]
Sorry, falsches Posting, bitte ignorieren.

**Comment by JuergenRichter** [comment]
So, nun richtige Antwort:
Das Thema "Zertifikate" wird derzeit von der Datenbank noch nicht unterstützt. Es gibt zwar ein Feld "Zertifikate" in der Tabelle SchuelerLernabschnittsdaten, da steht aber "DEPRECATED: Hier war mal geplant, Texte für Zertifikate einzugeben"

Es fehlt also noch eine Tabelle der Art "SchuelerZertifikate"
ID : bigint
Abschnitt_ID: bigint
ZertifikatKrz oder Zertifikat_ID: Verweis auf Tabelle K_Zertifikate
evtl. weitere Informationen

**Comment by FrodBRA** [comment]
@AnneSchueller @FPfotenhauer @Raffenberg 

Hier stellt sich mir die Frage, ob Zertifikate supportet werden sollen. Ein Support würde bedeuten, SchILD bzw. der SVWS-Server müssten folgende Unterstützung anbieten
- Den Katalog
- Eine Möglichkeit, Zertifikate bei Schülern zu setzen
- Zertifikate auszugeben, für SchILD würde dies über eine Datenquelle laufen

Wie werden Zertifikate bei der Migration gehandhabt, aktuell würde es ja bedeuten, dass vorhandene Zertifikate einfach nicht migriert werden.

Geht aus vergangenen Migrationen hervor, ob Schulen das Feature überhaupt nutzen (d.h. gibt es ein Log über Tabellen/Daten, die nicht mit migriert wurden und daher verfallen würden?)

Falls das Feature auch zukünftig nicht unterstützt werden soll, wäre der Katalog zu entfernen und diese Issues könnten geschlossen werden.

**Comment by EwaldReinhardt** [comment]
Ich kopiere das aus #892 mal hierhin:

`APO-BK allg. Teil § 9 (3) Über berufliche Qualifikationen, die nicht im Abschlusszeugnis bescheinigt werden, und über Zusatzqualifikationen werden Zertifikate erteilt, auf Antrag auch über nicht weitergeführte Ausbildungsabschnitte.
`

```
Anl. D § 58 (2) In einer zweiten Fremdsprache werden Kenntnisse nachgewiesen
durch
...
c) Erwerb eines Fremdsprachenzertifikates auf dem Niveau B 1 gemäß
der Rahmenvereinbarung der Kultusministerkonferenz vom 20.
November 1998 über die Zertifizierung von Fremdsprachenkenntnissen
in der beruflichen Bildung.
```
Zertifikate als Nachweis wie auch die an der Schule erworbenen könnten dort abgelegt werden.
Wahrscheinlich ist es eher für die erworbenen Zertifikate gedacht.

Ich werde das mit in die BK-AG nehmen, ob und welche Anforderungen da bestehen.

**Comment by FrodBRA** [comment]
Demnach sind Zertifikate vom Server und SchILD3 zu unterstützen.

Ich werde damit diesen Bereich als Todo im Plan behalten.

**Comment by FrodBRA** [comment]
Derzeit ist in 3.0.82.9 der Katalog nicht aufrufbar.

Sollten die Zertifikate gesetzt werden können, über welche Datenquelle können Sie dann ausgegeben werden?

**Comment by AnneSchueller** [comment]
Der Katalog Zertifikate wird richtig migriert:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/2d356961-a236-4766-9704-86a6773c575e)

Die zugeordneten Zertifikate werden ebenfalls richtig migriert und stehen in der Tabelle Schülerlernabschnittsdaten:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/af85a8b1-8034-4f5c-a2c0-00c475e084e8)

Hier fehlen lediglich die Auswahlmöglichkeiten in SChILD
Also einmal unter Kataloge und
unter Schüler akt. Abschnitt

**Comment by JuergenRichter** [comment]
Die Frage ist, ob das so bleiben soll. Im Kommentar zu dem FEld steht  "DEPRECATED: Hier war mal geplant, Texte für Zertifikate einzugeben". Wenn das Feld auf absehbare Zeit erhalten bleibt, können wir das auch erst mal weiter verwenden.

**Comment by EwaldReinhardt** [comment]
In der Schild2-Datenbank gibt es auch die Tabellen `EigeneSchule_Zertifikate` und `EigeneSchule_Zertifikatsfaecher`. Wofür diese da sind oder wo diese in Schild verwaltet werden weiß ich nicht.
Die Tabelle K_Zertifikate hat Anne beschrieben. Im ReportExplorer bekommt man nur die Kürzel angezeigt.
Ein einfacher Zugriff über eine Pipeline an die Bezeichnung scheint nicht vorhanden zu sein.


Für ein bestimmtes Zertifikat würde eher ein eigener Report erstellt.
Für diese Zusatzqualifikation Digitale Fertigungsprozesse gibt es Muster
von anderen Partnern. Zertifikate können auch die Schulen ausstellen, die die
Zusatzqualikation durchführen.
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/3f124b85-3a84-448d-bbbd-ffeba835e77a)

Das BKT Lüdenscheid stellt auch Zertifkate für SAP-Kurse aus. Hier wäre ggfs. ein Zeugnisbereich Zertifikat
sinnvoll, zu dem dann entsprechende "Fächer" zugeordnet werden, so dass Inhalte wie auf dem rechten Zertifkat
einfach umzusetzen wären.

**Comment by AnneSchueller** [comment]
@EwaldReinhardt Das wäre aber sicherlich eine Neuerung, die im SVWS-Server später umgesetzt werden könnte (daher wahrscheinlich auch der Kommentar "DEPRECATED")
In SchILD3 soll erstmal alles wie in SchILD2 abgebildet werden bezüglich BKs.

**Comment by FPfotenhauer** [comment]
Nutzt denn irgendjemand dieses Feature in Schild2?

**Comment by AnneSchueller** [comment]
Ich hatte bei einem BK-Fachberater/Moderator einmal nachgefragt. 
Er kannte keine Schule, die dieses Feld nutzt.

**Comment by JuergenRichter** [comment]
Ich habe jetzt trotzdem die Zertifikate wieder nutzbar gemacht.  ES gibt dazu nun auch eine Datenquelle "SchuelerZertifikate"

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/a2b57137-c5b1-4433-8a09-d321fcc9a490)
