### ISSUE TITLE
Aufruf eines Dokumentenablage-Ordners von SchILD aus führt zu Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#930]
3.081.9

Das Verzeichnis existiert, rufe ich Schüler -> Dokumentenverwaltung auf, gibt es einen Fehler.

![DokuVer](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/a403970e-1d81-458b-bf69-6ef1542b6dd9)

[DokuVer.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14103059/DokuVer.txt)

**Comment by AnneSchueller** [comment]
Da ist ein \ zu viel oder?
C:\SVWS-Arbeitsverzeichnis**\\**Dokumentenverwaltung

**Comment by JuergenRichter** [comment]
Da ist bei der "Erstgenerierung" des Verzeichnisnamens ein "\" zuviel angehängt worden (ist jetzt korrigiert). Das kann man aber nachträglich bei den Einstellungen ändern, dann sollte es funktionieren.

**Comment by AnneSchueller** [comment]
Nach der Änderung klappt alles.

Bei Einstellungen/Dokumentenverwaltung einfach über das Ordnersymbol den richtigen Speicherort auswählen:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/7c1cc2e7-453f-4b16-813d-689e5ef1f1aa)

**Comment by JuergenRichter** [comment]
Wird die pdf-Datei auch erzeugt? Habe nämlich bei mir noch einen Fehler entdeckt, der das verhinderte, ist nun aber korrigiert.

**Comment by AnneSchueller** [comment]
Also bei mir hat es auch schon mit der Version 3.081.9 geklappt. Zumindest mit dem Schülerstammblatt.

**Comment by FrodBRA** [comment]
Eventuell lässt SchILD im "Ordner setzen"-Bereich den Slash zu und dann steht der - oder halt auch nicht?

Hier müsste SchILD intelligent selbst den korrekten Pfad erzeugen, egal welche Backslashes nun gesetzt sind oder auch nicht bzw. auf Mehrfach-Backslashes filtern und alle bis auf einen einzelnen entfernen.
