### ISSUE TITLE
Die eingestellten Spaltenbreiten werden nicht immer gespeichert

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#934]
3.0.82.9

Die Spaltenbreiten werden beim Verlassen mitunter nicht gespeichert, hier im Fall Kataloge -> Kurse beobachtet. Andere Spaltenbreiten scheinen schon korrekt gespeichert zu werden.

Ich kann nicht alle möglichen Spalten auf korrektes Speicherverhalten überprüfen. Hier würde ich vorschlagen, dass Ribeka-intern, eventuell über einen Freelancer, einmal systematisch alle (!) Spaltenbreiten auf korrektes Speicherverhalten zu testen, indem alle Spalten unlesbar klein geschoben werden und man dann schaut, welche Spalten nach einem Neustart noch immer "unlesbar klein" sind und eventuell auftretende Probleme fixen. 

Hierbei könnten im Anschluss dann direkt auch sinnvolle Standardwerte gesetzt werden und dann im Anschluss alle Spalten auf korrekte Skalierung überprüft werden.

**Comment by JuergenRichter** [comment]
Speicherung der Spaltenbreite bei den Kurse ist nun umgesetzt.
