### ISSUE TITLE
Kataloge - Klassen-/Versetzungstabelle - TAB Probleme

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#935]
SchILD-Version: 0.81.9
SVWS-Server: 0.8.8

In Kataloge - Klassen-/ Versetzungstabelle ist die Reihenfolge der Felder bei der Benutzung der Tabulator Taste falsch (siehe Video).

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/f088e63c-1b33-4d22-88e7-24bae3186c29

**Comment by JuergenRichter** [comment]
Behoben
