### ISSUE TITLE
Beim Anlegen eines neuen Schülers wird im neu angelegten Schüler-Lernabschnitt das Feld ASDJahrgang nicht gesetzt

### ISSUE THREAD

**Issue by ThomasBachran** [SVWS-NRW/Schild3-BetaTest#936]
Wird ein neuer Schüler angelegt, so wird für diesen ein neuer Schüler-Lernabschnitt angelegt und das Feld Jahrgang_ID gesetzt. Das Feld ASDJahrgang bleibt allerdings NULL, obwohl diese Information direkt mitgesetzt werden sollte.

**Comment by JuergenRichter** [comment]
Behoben
