### ISSUE TITLE
Beim Anlegen eines neuen Schülers wird im neu angelegten Schüler-Lernabschnitt das Feld ASDSchulgliederung nicht gesetzt

### ISSUE THREAD

**Issue by ThomasBachran** [SVWS-NRW/Schild3-BetaTest#937]
Beim Anlegen eines neuen Schülers wird im neu angelegten Schüler-Lernabschnitt das Feld ASDSchulgliederung nicht gesetzt. Hier sollte je nach Schulform ein Default-Wert eingetragen werden.

**Comment by JuergenRichter** [comment]
Falls an der Schule nur eine Gliederung vorkommt, wird diese automatisch eingetragen.
