### ISSUE TITLE
Sortierung und Anzeige (Anzahl) der Vermerke in den Laufbahninformationen

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#938]
Wir nutzen für eine Vielzahl von Eintragungen verschiedene Vermerke. Es werden bei uns aktuell maximal 8 Vermerke angezeigt und dabei auch noch der älteste Eintrag zuerst. Hier wäre eine Anpassung der Anzeige auf mehr Einträge absolut sinnvoll.  Außerdem sollte die Sortierreihenfolge anpassbar sein. Optionen wie alphabetisch, neueste zuerst und eigene Sortierung wäre vielleicht sinnvoll. 
In der Version  3.0.81.9 funktioniert bei uns außerdem auch nicht die benutzerdefinierte Reihenfolge im Katalog der Vermerke. Bei einem wiederholten Aufruf des Kataloges stimmt die Reihenfolge nicht.

**Comment by AnneSchueller** [comment]
Hallo Martin,
die Vermerke werden derzeit nochmal ein weinig überarbeitet. Wahrscheinlich wird für diese ein separater Reiter angelegt, was dann zum einen die Übersicht erleichtert für Schulen, die wir ihr eine Vielzahl von Vermerken nutzen. Zum anderen würde so auch der Reiter Laufbahn "entlastet" werden.

Daher schließe ich das Issue erstmal.
