### ISSUE TITLE
Fehler beim Filter in den Vermerkarten

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#939]
Ich habe gerade versucht folgendes Problem aus Schild 2 in Schild3 nachzuvollziehen:
Wir haben ein Problem mit dem Filter von Vermerken. Bei uns gibt es mehrere Vermerke, bei denen das Datum wichtig ist. Wenn ich jetzt z.B. einen Vermerk iPDAD-Ausgabe mit Datum 01.02.2024 filtern möchte, werden die Schüler mehrfach angezeigt. Das Problem liegt darin, das alle Vermerke mit 01.02.2024 ebenfalls erfasst werden. Hat also ein Schüler drei Vermerke mit Datum 01.02.2024 wird er dreimal angezeigt. Selbst beim Listendruck.

Bei Schild 3 tritt folgendes Problem auf:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/656d01e8-1209-48ce-ba74-2e7f4c3bddb7)

Oder aber der Filter funktioniert noch mit Vermerkart (Bild 1), bricht dann aber bei der Eingabe des Datum komplett ab und zeigt alle Schüler an:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/f700d328-1350-4046-bf49-7697db3e5406)

**Comment by FrodBRA** [comment]
Kann ich bestätigen

**Comment by JuergenRichter** [comment]
Das Filtern auf Vermerke wurde nochmal grundlegend überarbeitet.

**Comment by AnneSchueller** [comment]
Wenn man nun nur nach einem Datum filtert bei den Vermerken kommt es zu folgender Fehlermeldung:

[vermerke.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14312456/vermerke.txt)

**Comment by AnneSchueller** [comment]
Analoge Fehlermeldung, wenn man nach einem Teilstring im Vermerktext filtert

**Comment by JuergenRichter** [comment]
Das habe ich auch schon entdeckt, ist auch schon behoben (aber noch nicht veröffentlicht).

**Comment by JuergenRichter** [comment]
Ich schließe dieses Issue mal, falls es nochmal auftreten sollte, bitte neu eröffnen.
