### ISSUE TITLE
Skalierungsfehler: Schülerfilter -> Weitere Daten ->  Vermerke Datumsauswahlfeld (Ab)

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#940]
3.0.82.9

"bis" nicht getestet. Vermutlich auch.

edit: Alle Datumsfelder im Schülerfilter sind zu groß skaliert.

**Comment by JuergenRichter** [comment]
Es werden nun andere Komponenten für die Datumsauswahl im Filterfenster verwendet, die korrekt skaliert werden.
