### ISSUE TITLE
Statistik: Schild3 und Schild2 gleiche DLL

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#943]
Wenn auf einem Rechner Schild2 und Schild3 installiert sind, dann sollte man sich darüber im klaren sein, dass nur eine Statistik.dll verwendet werden kann. Es "gewinnt die DLL, die als letztes registriert wurde.

Da die Statistik.dll in Schild2 und Schild3 auf gleichem Stand verwendet wird, ist das kein Problem.
Man muss dies nur beachten. Die ASDTABS.mdb muss aber bei beiden Versionen aktuell und am richtigen Ort sein.

Das ist auf jeden Fall ein Punkt der den Fachberater*innen kommuniziert werden muss.

**Comment by FrodBRA** [comment]
Das steht jetzt im Wiki:

https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Troubleshooting_Installation#Statistik.dll-Konflikte_bei_parelleler_Installation_von_SchILD-NRW2

**Comment by FPfotenhauer** [comment]
Super. Ich schreibe das auch in den nächsten FB-Newsletter.
