### ISSUE TITLE
Statistik: Teilstandorte in Schild3

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#944]
Die Teilstandorte werden bei der Migration in die neue Tabelle Klassen migriert.
In Schild3 unter Kataloge wird dort nicht das Merkmal angezeigt, sondern das Kürzel.
Daher bleibt das bei vielen DBs bei mir leer.

Bei ersten Tests mit der sim.txt zeigt sich, dass das Merkmal des Teilstandorts dann auch nicht in der sim.txt ankommt.

Wir sollten das Verhalten zu erst in Ruhe analysieren, falls es kein eindeutiger Bug ist.

**Comment by JuergenRichter** [comment]
Ich habe das jetzt so gelöst, dass als Info das Adress-Merkmal und (wenn vorhanden) das Kürzel angezeigt wird

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/b5c7db8c-6f9c-4781-be21-1db90d59bbf0)

**Comment by FPfotenhauer** [comment]
Wird denn das Ardress-Mermal (Buchstabe) in die StatistikDB.mdb geschrieben?
Ich habe bei einem Vergleich der sim.txt mal die von Schild2 und Schild3 (nach Migration) vergleichen.
Bei der sim.txt aus Schild3 fehlte in vielen Fällen das "A".

**Comment by JuergenRichter** [comment]
Ich habe das gerade mal getestet, die Teilstandorte werden korrekt in die Tabelle SDB_TEILSTANORTE geschrieben. Was die ASDStatistik.dll dann damit macht, weiß ich nicht.

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/b7ae68fe-d924-4efd-b8e7-f65ba8ee9cbc)

**Comment by FPfotenhauer** [comment]
Wurde die mit Schild3 erstellt?
Die fehlen in der Klasse, in der sim.txt wird das ja zu jedem Schüler ausgegeben.
Kann es sein, dass da noch etwas wegen der Umstellung der Klassentabelle angepasst werden muss?
Können Sie auch einmal in der SDB_Klassen schauen?

**Comment by JuergenRichter** [comment]
Eine Tabelle SDB_Klassen gibt es gar nicht. Die Information zum Teilstandort steht in der Tabelle SDB_SCHUELER

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/9d765817-6fc9-4e96-a033-c4015551b48b)

**Comment by JuergenRichter** [comment]
Aber werden die Teilstandorte überhaupt von der SIM.TXT berücksichtigt? Ich meine mich zu erinnern, dass die in SchILD hinterlegten Teilstandorte von IT-NRW gar nicht verwendet werden.

**Comment by FPfotenhauer** [comment]
Es betrifft nur Teilstandorte von Abgänger. Daher nicht relevant.
