### ISSUE TITLE
Statistik: Speicherort der Statistik-Dateien

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#945]
Die Datei ASDStatistik.dll benötigt folgende Dateien:

ASDTabs.mdb
schulver.mdb

Diese Dateien werden bisher im Verzeichnis \Keytabs unterhalb des Programmverzeichnisses erwartet. Es wäre zu überlegen, diese Dateien stattdessen im Verzeichnis \LDS zu speichern, damit dort alle statistik-relevanten Dateien liegen. Das müsste dann so im Installer umgesetzt werden und auch im Programmcode.

Dazu noch folgender Vorschlag: Man könnte dabei auch den (historisch bedingen) Namen "LDS" (stand mal für "Landesamt für Datenverarbeitung und Statistik") umbenennen in "IT-NRW", damit klar ist, dass die darin enthaltenen Dateien von IT-NRW stammen.

**Comment by Raffenberg** [comment]
Fände ich gut.

Mit freundlichen Grüßen
Jens Raffenberg
________________________________
Fachberater für
Schulsoftware NRW
Mobil 015773591422
Büro 02051-41968-36
***@***.***

von meinem Mobiltelefon
________________________________
From: JuergenRichter ***@***.***>
Sent: Tuesday, February 13, 2024 9:38:00 AM
To: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SVWS-NRW/Schild3-BetaTest] Statistik: Speicherort der Statistik-Dateien (Issue #945)


Die Datei ASDStatistik.dll benötigt folgende Dateien:

ASDTabs.mdb
schulver.mdb

Diese Dateien werden bisher im Verzeichnis \Keytabs unterhalb des Programmverzeichnisses erwartet. Es wäre zu überlegen, diese Dateien stattdessen im Verzeichnis \LDS zu speichern, damit dort alle statistik-relevanten Dateien liegen. Das müsste dann so im Installer umgesetzt werden und auch im Programmcode.

Dazu noch folgender Vorschlag: Man könnte dabei auch den (historisch bedingen) Namen "LDS" (stand mal für "Landesamt für Datenverarbeitung und Statistik") umbenennen in "IT-NRW", damit klar ist, dass die darin enthaltenen Dateien von IT-NRW stammen.

**Comment by FPfotenhauer** [comment]
Dann müssen aber alle Schild3-Installationen die schon bestehen, das anpassen!
Aber ich kann das in die Release-Notes schreiben.

Ich ändere das gleich im Installer.

**Comment by JuergenRichter** [comment]
Ich habe das jetzt sowohl beim Statistitik-Export als auch bei "Hilfe bei Problemen" angepasst auf das Verzeichnis "IT-NRW"

**Comment by FPfotenhauer** [comment]
Ich habe das im Installer geändert, bitte testen.
Auf dem FTP-Server habe ich mal eine geänderte Setup abgelegt.
Die Schild3.exe darin, hat aber noch die alten Pfade.
Sobald ich die neue Version habe, baue ich ein Setup.

**Comment by FPfotenhauer** [comment]
Wir haben hier nur über die ASDTABS.MDB gesprochen. In der neuen Version wird aber auch von der Schulver.MDB im Ordner IT-NRW gesprochen. Da die Schulver in einem Repository liegt, was "Keytabs" heißt, weil dort auch noch die Sachen drin liegen, die in Schild2 verwendet werden, würde ich das sehr ungerne ändern.

In der Versionsgeschichte ist die Rede von 3.0.83 in der EXE wird mir aber aber 3.0.84 angezeigt.
Können wir das noch klären, bevor ich das Relase mache?

**Comment by JuergenRichter** [comment]
Ich hatte im ersten Beitrag aber auch die Schulver.mdb erwähnt. Diese wird von SchILD3 nicht mehr verwendet, da die Daten ja nun vom SVWS-Server geliefert werden. Im SchILD3-Umfeld wird die Datei aber von der ASDStatistik.dll benötigt (um zu prüfen, ob die Schule eine "echte" Schulnummer hat). Daher dachte ich, dass die Schulver.mdb auch gut in das IT-NRW-Verzeichnis passen würde. Es ist aber auch möglich, die ASDTabs.mdb und die Schulver.mdb an getrennten Orten zu verwalten, es gibt in der DLL dazu zwei Prozeduren "ASDTABSConnectionStringUebergeben" und "SCHULVERConnectionStringUebergeben".

**Comment by FPfotenhauer** [comment]
Ok. Danke. Dann verschiebe ich die Schulver auch in IT-NRW und mache die Versionsnummer 3.0.84 fertig.
