### ISSUE TITLE
Schüler -> Dokumentenverwaltung: Klick auf den "Pfeil" öffnet den Windows-Explorer

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#947]
Version 3.0.82.9

Klickt man auf den kleinen "Pfeil" um die Dateien in Schüler -> Dokumentenverwaltung aufzuklappen, geschieht dies, aber es öffnet sich zusätzlich auch der Windows-Explorer. Das führt das Aufklappen etwas ad absurdum, wenn die Dokumente direkt aus SchILD ohne den Explorer öffnen möchte.

Vorschlag:
- Ein Klick auf den Pfeil klappt nur die Dateiliste im SchILD-Explorer auf.
- Ein klick auf den Ordner selbst klappt die Liste aus und öffnet den Windows-Explorer.

Weiterer Fehler: Aktuell klappt ein Klick auf den Pfeil die Liste nicht wieder zusammen.

(Im Bild: Der Rote Pfeil passiert aktuell und soll nicht passieren, der grüne passiert und soll passieren)

![Dokver](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/45f3a722-f84e-4b7c-96a2-15b716888023)

**Comment by AnneSchueller** [comment]
Das kann ich so nicht reproduzieren. (Neuere Version 3.0.83.10)
Das Zusammenklappen funktioniert bei mir.
Der Windows-Explorer öffnet sich nur beim Doppelklick. Allerdings auch bei einem Doppelklick auf das Dreieck (roter Pfeil). Aber das liegt evtl. auch an dem PC-Einstellungen? Ich habe an meinem Rechner die Einstellung derart, dass ich immer Doppelklicke um in Ordner zu wechseln.
Wenn das einfach anzupassen ist, würde ich es begrüßen, wenn nur ein Klick bzw. Doppelklick auf den Ordner (grüner Pfeil) den Windows-Explorer öffnet

**Comment by JuergenRichter** [comment]
Die Komponenten, die zur Anzeige des schülerbezogenen Dokumentenverzeichnisses verwendet wird, ist eine "Instanz" des Windows-Explorers. Diese verhält sich erst mal so, wie man das bei den Systemeinstellungen definiert hat. Es gibt aber ein Ereignsi "OnDblClick", das ausgeführt wird, wenn man einen Doppelklick auf einen Eintrag ausführt. Da wird unterschieden, ob es sich beim ausgewählten Eintrag um ein Verzeichnis oder eine Datei handelt. Bei einem Verzeichnis wird der Windows-Explorer separat ausgeführt, bei einer Datei wird diese mit dem Programm geöffnet, das im System für die Dateierweiterung definiert ist. Man könnte nun den "Verzeichnis-Doppelklick" unterbinden, das würde aber verhindern, das das Verzeichnis separat geöffnet wird, obwohl der Benutzer genau das möchte (um z.B. irgendwelche Arbeiten im Verzeichnis zu machen, die über die Instanz in SchILD3 nicht möglich sind). Im übrigen ist das Verhalten hier genau so wie in SchILD2, da hat es meines Wissens bisher auch keine Probleme gegeben.

**Comment by JuergenRichter** [comment]
Ich habe das nochmal nachgespielt: Das "Pfeil-runter" bzw. "Pfiel-rechts"-Symbol funktioniert bei mir wie erwartet. Wenn man aber ganz schnell hintereinander erst das "Pfeil rechts" und dann "Pfeil runter" Symbol anklickt, ist das für die Komponente wie ein Doppelklick, dann wird auch das entsprechende Ereignis ausgeführt.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/af9b056e-b17f-4b74-b136-3c9cefc819cc)

**Comment by FrodBRA** [comment]
In SchILD2:
- Ein Einfachklick auf den Pfeil öffnet die Liste mit den Dateien
- Ein weiterer Einfachklick klappt die Liste zusammen
- Ein Einfachklick auf den Ordner tut nichts (wie in Windows)
- Ein Doppelklick auf den Ordner öffnet den Ordner (wie in Windows)

In SchILD3:
- Ein Einfachklick auf den Pfeil tut nichts, weder zum öffnen noch schließen
- Ein Doppelklick öffnet den Ordner und klappt den Pfeil aus
- Das oben stimmt nicht ganz, klicke ich weiter (langsam), passiert manchmal nichts, manchmal öffnet und schließt sich die Liste und manchmal poppt der Ordner auf (sowohl beim Öffnen und Schließen). Häufig passiert einfach gar nichts und der Versuch, die Liste einzuklappen artet in wildes Geklicke aus.

Das Verhalten wirkt chaotisch und definitiv nicht so sauber wie in SchILD2.

Ich habe in Windows keine Einstellungen hierzu vorgenommen, das Windows-Verhalten ist beim Standard belassen.

**Comment by JuergenRichter** [comment]
Ich kann das Problem in ähnlicher Weise auf meinem 4K-Monitor reproduzieren, auf einem 1980 x 1080 Monitor funktioniert es einwandfrei.

**Comment by JuergenRichter** [comment]
Ich habe gerade folgendes festgestellt: 
Wenn man beim 4K-Monitor nicht auf das Pfeilsymbol, sondern auf die Linie klickt, die das Symbol mit dem Verzeichnisnamen verbindet, funktioniert es wie geplant.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/fe0dd6e4-ffd7-48c1-a6d0-6032c36c855d)

**Comment by FrodBRA** [comment]
Das funktioniert.

**Comment by FrodBRA** [comment]
Geschlossen
