### ISSUE TITLE
"Gruppenprozesse" speichert die Spaltenbreite von "Aktuelle Schülerauswahl" (der Container) nicht

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#948]
Version 3.0.82.9

siehe Titel

**Comment by AnneSchueller** [comment]
Kurze Nachfrage: Du meinst folgende Situation:

- Wechsel in Reiter GP
- z.B. Jg 06 im Schnellfilter auswählen
- Wechsel in einen anderen Reiter

Beim Wechsel zum Schüler wird der Aktuelle Schülerauswahl gespeichert.
Beim Wechsel in Filter nicht (das sollte m.E. auch so sein, da sich der Schülerfilter zunächst auf alle SuS bezieht)

**Comment by FrodBRA** [comment]
Ich meine die Spaltenbreiten. Sorry, das fehlt: Gehe zu GP. Verschiebe die Spaltenbreite des Schülercontainers. Gehe woanders hin. Gehe zurück. Spaltenbreite ist wieder der zu schmale Defaultwert.

**Comment by FrodBRA** [comment]
In 3.0.84.10 reproduzierbar

**Comment by FrodBRA** [comment]
Möglicherweise verwandt mit https://github.com/SVWS-NRW/Schild3-BetaTest/issues/949, da auch dort die Containerbreite nicht gespeichert wird.

**Comment by AnneSchueller** [comment]
Ich habe jetzt hier ziemlich lange hin und hergeklickt. Gelegentlich änderte sich die Spaltenbreite bei GP. Ich kann leider keine Regelmäßigkeit entdecken. Meistens bleibt die Spaltenbreite bei mir korrekt eingestellt.

Frage: Wenn ich hier die Spaltenbreite ändere, gehe ich davon aus, dass diese sich analog auch in den anderen Reitern anpasst, die die gleiche Darstellung haben, oder?  Dies betrifft Gruppenprozesse, Reportverwaltung, Schüler.

Mit welcher Schulform hast du getestet?

**Comment by AnneSchueller** [comment]
Können wir das so realisieren:

Breite des Schülercontainers ist immer wie die aktuelle Einstellung in dem jeweiligen Reiter (Oder gibt es hier Argumente, die dagegen sprechen?

Konkret:
Verändert man die Spaltenbreite des Containers in Reiter A (z.B. wie hier Gruppenprozesse), so verändert sich die Spaltenbreite des Containers analog in allen anderen Reitern (z.B. dann auch in Schüler, Reportverwaltung, usw)
@JuergenRichter : Das scheint bei Gruppenprozessen nicht richtig zu funktionieren:


https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/67d7ee99-07c6-4861-947a-cac2992f71fe
