### ISSUE TITLE
"Lehrkräfte" speichert die Breite der Lehrkraftauswahl nicht 

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#949]
Version 3.0.82.9

Siehe Titel

**Comment by AnneSchueller** [comment]
Hier hatte ich mit der alten Version auch Probleme.... Ich glaube dort wurde etwas angepasst. Zumindest läuft das bei mir jetzt.

**Comment by FrodBRA** [comment]
Es gibt noch keine neue Version für mich. Ich teste später.

**Comment by FrodBRA** [comment]
In 3.0.84.10 reproduzierbar.

Die Spalten im Container selbst werden gespeichert. Die Containerbreite selbst aber nicht.

Issue bitte wieder öffnen.

**Comment by AnneSchueller** [comment]
Stimmt, ich hatte die Spaltenbreite im Container getestet....

**Comment by JuergenRichter** [comment]
Behoben
