### ISSUE TITLE
Doppelte Einträge bei individuellen Einstellungen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#95]
Unter Verwaltung --> Einstellungen --> individuelle Einstellungen kann man unten die sichtbaren Spalten bei Schüleransicht-Tabellen anpassen. 
Wenn man auf der linken Seite in einen anderen Reiter wechselt (z.B. auf Werkzeuge) und anschließend wieder die individuellen Einstellungen anklickt, werden die Kontrollkästchen doppelt aufgelistet. Also nach dem "weitere Förderschwerpunkte" werden wieder Name usw. aufgelistet. Wiederholt man den Vorgang, so werden die Kontrollkästchen nochmal angehängt, also dreimal aufgelistet. u.s.w.
![DoppelteEintraege](https://user-images.githubusercontent.com/79116896/108074248-47002180-7069-11eb-9780-50c790ff6ccf.png)
![DoppelteEintraege2](https://user-images.githubusercontent.com/79116896/108074516-93e3f800-7069-11eb-9131-26970232dd2c.png)

**Comment by JuergenRichter** [comment]
In Version 3.0.10 behoben
