### ISSUE TITLE
Neuanlegen eines Schülers

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/Schild3-BetaTest#950]
Beim Anlegen eines neuen Schülers für das kommende Schuljahr werden mit der Version 3.0.84.10 die Klasse und Jahrgangsstufe nicht übernommen, obwohl diese eingestellt sind. Mit der vorherigen Version funktionierte es noch.

<img width="334" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/71388959/88f6f8d7-f850-4b4f-85b6-e5588881eec7">

<img width="679" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/71388959/43d3fc15-ebc1-4a01-aa5b-21b3e6575fa9">

**Comment by AnneSchueller** [comment]
Ich schließe mal das Issue aufgrund von Zusammengehörigkeit mit
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/951
