### ISSUE TITLE
Neuanlegen eines Schülers (2. Fehler)

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/Schild3-BetaTest#951]
Beim Anlegen eines neuen Schülers erhalte ich folgende Fehlermeldung (Version 3.0.84.10). Auch das ging in der vorherigen Version problemlos.

In den Einstellungen ist das Editieren freigeschaltet.

<img width="479" alt="image" src="https://github.com/SVWS-NRW/Schild3-BetaTest/assets/71388959/b14e1ceb-0883-42e9-ac60-e3182f0a520b">

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren:

[neuaufnahme.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14340744/neuaufnahme.txt)

**Comment by JuergenRichter** [comment]
Behoben
