### ISSUE TITLE
Sortierung Reiter "Abitur" falsch

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#953]
Nach einer frischen Migration erscheinen die Fächer auf dem Reiter Abitur nicht in der Sortierung der Schule, weder der Sek-I noch der Sek-II. Ein Muster ist nicht erkennbar, auch bei Einbeziehung der Daten aus der DB nicht.

**Comment by JuergenRichter** [comment]
Ich habe ma in einer meiner Datenbanken nachgeschaut, da ist das Feld nicht befüllt. Ist wohl bei der der Migration nicht berücksichtigt worden.

**Comment by M-Plu** [comment]
Auch bei mir ist das Fach FSortierung NULL. Ich leite das weiter.

**Comment by ThomasBachran** [comment]
@JuergenRichter : Das ist korrekt. Das Feld FSortierung wird bei der Migration zur Zeit nicht berücksichtigt. Hier hatten wir vor längerer Zeit gesagt, dass die Werte dieser Sortierung auch an anderer Stelle vorliegen (die Spalte wird ja von anderer Stelle beim Übertragen befüllt)  und damit in dieser Tabelle redundant sind. Daher hatten wir im SVWS-Server markiert, dass es nicht mit migriert wird.

Ich würde Sie daher bitten im Abiturreiter auf die Sortierung zurückzugreifen, welche die Fach-Sortierung der Tabelle beim Übertrag der Leistungsdaten befüllt. Wenn dies noch an anderen Stellen, z.B. für Reports genutzt wird, dann müsste das dort natürlich auch entsprechend berücksichtigt werden.

Ist das so für Sie umsetzbar?

**Comment by JuergenRichter** [comment]
Ist umsetztbar.
