### ISSUE TITLE
Kontextmenü Reiter Abitur fehlt

### ISSUE THREAD

**Issue by M-Plu** [SVWS-NRW/Schild3-BetaTest#954]
Auf dem Reiter Abitur konnte man bisher im Kontextmenü der Notenpunkte im Grid festlegen, ob der Eintrag auf dem Abiturzeugnis erscheinen soll oder nicht. Dort gibt es aktuell kein Kontextmenü mehr.

**Comment by JuergenRichter** [comment]
Prüfe ich

**Comment by JuergenRichter** [comment]
Ist umgesetzt
