### ISSUE TITLE
Import über Schnittstelle funktioniert nicht

### ISSUE THREAD

**Issue by JeVaske** [SVWS-NRW/Schild3-BetaTest#955]
Versionen: Schild 3.0.84.10 SVWS-Server: 0.8.10
Ich habe gerade versucht, die Schülerdaten, die mir über Schüler-Online geliefert wurden, über die Schnittstelle zu importieren. Bei Schild_2 funktionierte das einwandfrei. Schild_3 kam folgende (von mir anonymisierte und verkürzte) Fehlermeldung:
Schüler-Basisdaten (für Nachname, Vorname): ###22007Incorrect date value: '45505' for column `svwsdb`.`schueler`.`Aufnahmedatum` at row 1:
insert into Schueler (Geschlecht,Status,Ort_ID,Strassenname,HausNr,StaatKrz,Religion_ID,Aufnahmedatum,Schuljahresabschnitts_ID,LSSchulnr,LSSchulform,LSSchulformSIM,LSSchulentlassdatum,LSJahrgang,LSEntlassart,JahrZuzug,GeburtslandSchueler,GeburtslandMutter,GeburtslandVater,Migrationshintergrund,Duplikat,MasernImpfnachweis,Name,Geburtsdatum,ID,GU_ID,Vorname) values …
Schüler-Basisdaten (für Nachname, Vorname): ###23000Cannot add or update a child row: a foreign key constraint fails (`svwsdb`.`schuelerlernabschnittsdaten`, CONSTRAINT `SchuelerLernabschnittsdaten_Schueler_FK` FOREIGN KEY (`Schueler_ID`) REFERENCES `schueler` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE):
insert into SchuelerLernabschnittsdaten (Jahrgang_ID,ASDJahrgang,Klassen_ID,Schueler_

**Comment by JuergenRichter** [comment]
Die Fehlermeldung schient darauf hinzudeuten, dass mit dem Feld "Aufnahmedatum" was nicht stimmt. Wäre es möglich, mal den kompletten SQL-String zu bekommen, der ausgegeben wird (insbesondere der Teil nach "values"), die Namesangaben können ja unkenntlich gemacht werden.

**Comment by JeVaske** [comment]
Hier der komplette String. Die Eingaben xxx und yyy habe ich zur Anonymisierung eingefügt.
Schüler-Basisdaten (für xxx, yyy): Falsche Verkehrssprache (ar) in Zeile 2
Schüler-Basisdaten (für xxx, yyy): ###22007Incorrect date value: '45505' for column `svwsdb`.`schueler`.`Aufnahmedatum` at row 1:
insert into Schueler (Geschlecht,Status,Ort_ID,Strassenname,HausNr,StaatKrz,Religion_ID,Aufnahmedatum,Schuljahresabschnitts_ID,LSSchulnr,LSSchulform,LSSchulformSIM,LSSchulentlassdatum,LSJahrgang,LSEntlassart,JahrZuzug,GeburtslandSchueler,GeburtslandMutter,GeburtslandVater,Migrationshintergrund,Duplikat,MasernImpfnachweis,Name,Geburtsdatum,ID,GU_ID,Vorname) values (3,0,290,Straße.','hausnummer','xxx',17,45505,38,'163053','R','R',45504,'10','G',2016,xxx,'xxx','xxx','-','-','-',xxx,39112,3771,'{FFDA86BF-6BE4-4FD1-8A6E-853BA6E66514}',yyyy)

**Comment by JuergenRichter** [comment]
Behoben
