### ISSUE TITLE
[BK] "Werkzeuge -> Duplikate abgleichen -> Abgleich" führt zu Fehler

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#957]
3.0.84.10
SVWS: 0.8.10

Ich habe versucht, ein Duplikat mit einem Original abzugleichen. 

Es kommt zum Fehler:

![BK Dupli](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/25ee233f-56dc-42d1-a34b-33e9c53e73e3)

[BKWerkzeugDuplikat.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14375408/BKWerkzeugDuplikat.txt)

**Comment by AnneSchueller** [comment]
Ich kann das nicht reproduzieren, da meine BK-DB keine Duplikate enthält und die Funktion "Schüler duplizieren" nicht funktioniert.
War das ein Duplikat, das mit migriert wurde?

**Comment by FrodBRA** [comment]
Der Fehler hängt an den eingetragenen Daten. Die im Screenshot werfen einen Fehler, ein einfacheres Setup führte zu einem erfolgreichen Abgleich.

Ich hatte "Irgendwas" eingetragen, eventuell versuche ich eine verbotene Kombination einzutragen. Das müssten wir testen bzw. mal genauer anschauen.

**Comment by AnneSchueller** [comment]
Sobald die Duplikate in meiner DB entsprechende Eintragungen wie bei dir im Screenshot aufweisen, kann der besagte Button nicht mehr gedrückt werden... Kannst du das noch reproduzieren, wie du diese erstellt hast?

**Comment by FrodBRA** [comment]
>  Kannst du das noch reproduzieren, wie du diese erstellt hast?

Der Affe hat einfach willkürlich eine Klasse im neuen Lernabschnitt angeklickt, den Rest hast SchILD ausgefüllt.

**Comment by AnneSchueller** [comment]
Ich schlage vor, dass das Issue erstmal geschlossen wird, Jochens Anmerkungen (siehe Mail) eingearbeitet werden und wir danach nochmal testen und ggf. wieder öffnen.
