### ISSUE TITLE
Unter Verwaltung haben diverse Seiten keinen Inhalt bzw. zeigen leere Seiten

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#959]
Version 3.0.84.10

Auf meinem Surface unter Windows 11 (10.0.22631 Build 22631) sind unter Verwaltung alle Seiten leer, bis auf Schule une Einstellungen.
Ein Klick auf Werkzeuge lässt den SQL-Warte-Cursor scheinen, präsentiert dann aber auch eine leere Seite.

Unter Windows 11 (20.0.22621 Build 22621) in meiner VM sind alle Seiten mit Inhalt sichtbar.

**Comment by AnneSchueller** [comment]
Das Problem von leeren Seiten bei der Verwaltung ist bisher noch nicht aufgetaucht. 
Gab es bei der Migration evtl. Auffälligkeiten in der Log-Datei?
Wurde auf  beiden Systemen die gleiche DB migriert? Gleiche Schild-Version und SVWS-Server-Version?

**Comment by FrodBRA** [comment]
Eventuell Windows 11? In dem Issue zur Reportverwaltung ohne Datumslink wird auch Windows 11 verwendet (so lange das nur ein Verdacht ist, verlinke ich die Issues noch nicht).

Ich nutze Win 10.

@JuergenRichter Haben Sie eine Win11 Testmaschine?

**Comment by JuergenRichter** [comment]
Ja, der Entwicklungsrechner hat Win11

**Comment by JuergenRichter** [comment]
Was bedeutet denn "leer"? Wird gar nichts angezeigt oder sind Eingabefelder, die einen Inhalt haben sollten, leer?

**Comment by AnneSchueller** [comment]
Ich nutze auch Win11 und Win10...

**Comment by tpre** [comment]
> Was bedeutet denn "leer"? Wird gar nichts angezeigt oder sind Eingabefelder, die einen Inhalt haben sollten, leer?

Die Seiten sind leer, d.h. da steht gar nichts.

Ich nutze zwei verschiedene Installation, die auch für den gleichen SVWS-Server, d.h. auf die gleiche DB zugreifen können. Ich bin gerade nicht zu Hause, aber ich meine, dass ich auf beiden die gleiche DB von gleichen SVWS-Server öffne. Beim einen ist alles sichtbar, beim anderen ist alles leer.
Kann es sein, dass das irgendwie Altlasten sind von vorherigen Installationen? Ich hatte auf dem einen Rechner auch eine andere Farbdarstellung, obwohl ich händisch nie was geändert hatte. Ich werde mal alles deinstallieren, säubern und neu installieren.

**Comment by Raffenberg** [comment]
Bitte einmal die ZIP-Datei eintpacken und dann die Batch-Datei über das Kontextmenü als Administrator ausführen. Die Batch-Datei deinstalliert Schild3, den SVWS-Server und sämtliche Reste in der registry. Danach alles neu installieren.

[Delete SVWS-Server and SchILD-NRW 3.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14407940/Delete.SVWS-Server.and.SchILD-NRW.3.zip)

**Comment by tpre** [comment]
Dann habe ich nochmal beide Schild-Installationen parallel gestartet und verglichen. Dabei ist mir aufgefallen, dass das Untermenü in der 2. Spalte auf der Seite Schule auf dem einen Rechner fehlte, auf dem anderen aber angezeigt wurde. Da wo es fehlte, war auch kein Slider sichtbar. Ich konnte mit der Maus trotzdem die Spalte mit dem Untermenü breiter ziehen und sichtbar machen. Ungewöhnlich. Verstehen tue ich das nicht. Was auch immer der Grund war, ich kann es nicht mehr reproduzieren. Das kommt leider immer wieder vor. Ich erhalte Fehlermeldungen, die ich dann nicht mehr reproduzieren kann.

**Comment by tpre** [comment]
Ein Beispiel für seltsames Verhalten der Oberfläche ist im folgenden Issue reproduzierbar dokumentiert: [https://github.com/SVWS-NRW/Schild3-BetaTest/issues/964](url)

**Comment by AnneSchueller** [comment]
Der Link scheint nicht korrekt zu sein. Evtl. ein Zahlendreher?

**Comment by AnneSchueller** [comment]
Ich schließe dieses Issue mal, da das "seltsame Verhalten" in dem anderen Issue bereits dokumentiert ist.
