### ISSUE TITLE
Einstellung "Bei Schülern bevorzugt schulische Mailadresse verwenden" funktioniert nicht bei Reportversand

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#96]
Aktiviert man die Auswahl "Bei Schülern bevorzugt schulische Mailadresse verwenden" funktioniert das zwar wenn man über die Schülertabellen den Schülern Mails versenden möchte. Soll jedoch eine pdf-Datei, die mittels eines Report erzeugt wurde, per Mail an den Schüler verschickt werden, wird bei "Schüleradresse übernehmen" immer die private Mailadresse ausgewählt. Es wäre wünschenswert, dass auch in diesem Fall die schulische Mailadresse verwendet wird.
![privateMail](https://user-images.githubusercontent.com/79116896/108096556-61de9000-7081-11eb-8e96-f7fcb587db35.png)

**Comment by Emil1957** [comment]
Problem ist in Version 3.0.10 behoben. Bisher wurde auch nur eine E-Mail-Adresse der Erziehungsberechtigten (über Schalter "Erzieher-Adresse übernehmen") übergeben, falls aber beide Personen eigene Mailadressen haben, werden nun beide verwendet.
