### ISSUE TITLE
Beim Drucken eines Zeugnisses Fehler "Ungültige Graphik"

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#961]
Schild-Version: 3.0.84.10. SVWS-Server: 0.8.10

Ich habe eine Schild2-DB nach Schild3 migriert und die BK-Zeugnisse installiert. Den SubReport Zeugnis-Kopf.rtm habe ich kopiert. 
Drucke ich nun ein Zeugnis, kommt der folgede sehr unspezifische Fehlerdialog:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/2390a890-154a-48fd-aa6f-3652b3b70d93)
In Zeugnis-Kopf.rtm wird das Schullogo eingebunden. Öffne ich den Report im Editor und lösche Zeugnis-Kopf.rtm aus dem Zeugnis gibt es keinen Fehler in der Vorschau. Öffne ich Zeugnis-Kopf.rtm separat im Editor gibt es auch keinen Fehler in der Vorschau und das Schullogo wird angezeigt. Öffne ich das Zeugnis, gibt es aber einen Fehler im Editor in der Vorschau.
Was läuft hier falsch?

**Comment by FrodBRA** [comment]
Das hatten wir schon einmal, was für eine Datei ist das denn, die dort eingebunden ist?

**Comment by tpre** [comment]
Das ist eine PNG-Grafik.

**Comment by AnneSchueller** [comment]
Klappt das, wenn man ParentDataPipeline im Report aktiviert?
Bei den GS-Zeugnissen hatten wir ein ähnliches Problem:
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/723

**Comment by tpre** [comment]
@AnneSchueller Das war die Lösung.

Genauer für die Nachwelt: Man muss die Eigenschaft ParentDataPipeline der Grafik im Report-Editor ausschalten. In meinem Fall war es das Schullogo im SubReport Zeugnis_Kopf.rtm.

**Comment by AnneSchueller** [comment]
Danke für die Rückmeldung. Dann schließe ich das Issue
