### ISSUE TITLE
Jahrgang und Gliederung von Duplikaten entfernen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#963]
Da duplizierte SuS am BK einer neuen Klasse zugeordnet werden, aus der sich dann der Jahrgang und Gliederung ergibt, sollte Jahrgang und Gliederung beim Duplikat entfernt werden.
Derzeit wird in Schild3 nur die Klasse entfernt.

**Comment by JuergenRichter** [comment]
Ist umgesetzt
