### ISSUE TITLE
Fehler beim vertikalen Slider unter Verwaltung

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/Schild3-BetaTest#964]
Ein Beispiel für seltsames Verhalten der Oberfläche ist folgendes:
Der Slider, der eigentlich rechts von Aktuelle Schülerauswahl sein sollte, 
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/9b603c9e-d902-44a2-ba52-41d68819ff0d)

ist plötzlich, wenn man auf der Seite Verwaltung den Slider so verschiebt, dass die 2. Spalte nicht mehr sichtbar ist, 

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/965b45a7-4fdc-444e-b521-cd8bc317921b)

am linken Fensterrand und verliert seine Funktion.

![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/984cc24f-8625-4baa-809b-ed4a0799199f)

**Comment by AnneSchueller** [comment]
Der Slider erscheint nur, wenn die Spaltenbreite zu klein gewählt wird. Ich bin mir aber nicht ganz sicher, ob das in der offiziellen Version bereits eingebaut ist. Hier gab es hinsichtlich Slider/Platzeinsparung einige Anpassungen.
Wenn ich die Reiter Wechsel, bleiben die Slider wie in der Schüler Ansicht. Die Funktionalität bleibt hierbei erhalten (Oder habe ich das falsch verstanden?) Hier mal ein Video dazu:

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/0251fba1-ac26-4d25-b3da-479f5cc7cced

**Comment by tpre** [comment]
In dem Video ist ein anderer Slider gemeint. Ich habe mal ein eigenes Video erstellt. Ist vielleicht in solchen Fällen besser, als sich mit Worten einen abzubrechen ;-)

https://github.com/SVWS-NRW/Schild3-BetaTest/assets/23186227/ad1a1c11-4987-4fc7-9243-b605b2cdcd71

**Comment by AnneSchueller** [comment]
Jetzt sehe ich es. Gemeint ist der Slider am linken Rand:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/5b20ac47-ac81-4dad-80a7-b6e942616ad2)

**Comment by FrodBRA** [comment]
Das sieht ja schon fast mutwillig aus. ;)

Eine Lösung wäre, minimale Spaltenbreiten zu setzen?

**Comment by JuergenRichter** [comment]
Ich habe die ganze Verwaltung der unterschiedlichen Objekte auf der linken Fensterseite (Schülerauswahl, Verwaltungsoptionen, Katalogliste usw.) nochmal überarbeitet, bei mir funktioniert es jetzt wie gewünscht. Bitte im nächsten Update mal testen.

**Comment by AnneSchueller** [comment]
Getestet mit 3.0.85.10
