### ISSUE TITLE
Klassenleitung nach Migration von Access in einigen Klassen falsch

### ISSUE THREAD

**Issue by Sait-Suktan** [SVWS-NRW/Schild3-BetaTest#965]
(Ich hoffe, Fehlermeldungen von nicht-Fachberatern sind hier überhaupt erwünscht. So steht es im Schild-Wiki, anders hier auf Github. Sonst bitte kurze Rückmeldung.) 

Nach der Migration, die ohne Fehler durchlief, wurden bei einigen Klassen und Jahrgangsstufen in den _Allgemeinen Angaben_ unter _akt. Halbjahr_ zu viele Klassenleitungen (insg. bis zu 4) eingetragen. Die tatsächlichen stehen bei den Ziffern 1 und/oder 2, aber in unserer Q1, EF, 9c, 8d und 8b werden zusätzlich die Klassenleitungen der gleichnamigen Klassen oder Stufen aus dem Vorjahr eingetragen, bei den anderen hingegen nicht.

**Comment by FPfotenhauer** [comment]
Das dürfte daran liegen, das es irgendwo noch Schüler gibt, die die alten Klassenleitungen haben.
Die Migration trägt "stumpf" alle Klassenlehrer ein, die vorkommen.

**Comment by Sait-Suktan** [comment]
Das hatte ich schon vermutet und in mind. einer Klasse extra nachgeschaut. Mir war aber kein falscher Eintrag unter akt. Halbjahr aufgefallen. Ich könnte mal in die DB schauen…Am 27.02.2024 um 09:17 schrieb Frank Pfotenhauer ***@***.***>:﻿
Das dürfte daran liegen, das es irgendwo noch Schüler gibt, die die alten Klassenleitungen haben.
Die Migration trägt "stumpf" alle Klassenlehrer ein, die vorkommen.

**Comment by FPfotenhauer** [comment]
Ist das eine DB mit Quartalen?

**Comment by Sait-Suktan** [comment]
Nein, wir laufen im Halbjahresbetrieb.Am 06.03.2024 um 15:24 schrieb Frank Pfotenhauer ***@***.***>:﻿
Ist das eine DB mit Quartalen?

**Comment by Raffenberg** [comment]
Können wir mal in die anonymisierte DB einen Blick werfen? Das Anonymisierungstool gibt es als Tool im Downloadbereich von svws.nrw.de

**Comment by Sait-Suktan** [comment]
Hallo Herr Raffenberg,

 

leider erhalte ich beim Versand der anonymisierten DB eine Fehlermeldung, da selbst die gezippte DB (8MB) zu groß ist für GitHub. 
Daher nun dieser Link auf mein oneDrive-Konto: 
Schild2000n.zip <https://1drv.ms/u/s!AqwuQoyydWAth8YJN7t4ZENGfWF6Iw?e=dWG5rh> 

Er läuft am Dienstag ab.

Beste Grüße



 

Von: Raffenberg ***@***.***> 
Gesendet: Donnerstag, 7. März 2024 06:45
An: SVWS-NRW/Schild3-BetaTest ***@***.***>
Cc: Sait-Suktan ***@***.***>; Author ***@***.***>
Betreff: Re: [SVWS-NRW/Schild3-BetaTest] Klassenleitung nach Migration von Access in einigen Klassen falsch (Issue #965)

 

Können wir mal in die anonymisierte DB einen Blick werfen? Das Anonymisierungstool gibt es als Tool im Downloadbereich von svws.nrw.de

**Comment by AnneSchueller** [comment]
Ich habe mir die DB einmal angesehen.
Es gibt für den aktuellen Abschnitt 2023.1 einen Schüler, der bereits einen Lernabschnitt hat, aber in Abgang gesetzt wurde.
Dieser Schüler hat keinen Klassenlehrer-Eintrag.
Bei der Migration wird erst der Klassenlehrer aus der Versetzungstabelle eingetragen.
Anschließend werden weitere Klassenlehrer aus den Abschnittsdaten (also das was unter akt HJ. steht) eingetragen
@ThomasBachran: Für den Fall, dass beim Schüler kein Eintrag vorhanden ist, wird der vorangegangene Abschnitt für den Klassenlehrer eingetragen? Das wären im MIgrationsprotokoll wahrscheinlich die 15 Einträge, die im Anschluss nochmal erfolgen?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/3438a4b2-68ee-4a12-8a28-723c6690a9ae)

**Comment by FPfotenhauer** [comment]
Nun ja. Wir bauen ja eine historische Klassentabelle auf.
Da werden wir nicht drum herum kommen, auch die Abgänger zu berücksichtigen.

Man kann die Klassentabelle für den aktuellen Abschnit doch einmal korrigieren nach der Migration.
Danach ist man das los. Wie bereits erwähnt, ist das bisher immer ein Hinweis, dass irgendwo noch etwas falsches eingetragen ist.
