### ISSUE TITLE
Mausrad-Scrollen in der Leistungsübersicht fehlerhaft

### ISSUE THREAD

**Issue by Sait-Suktan** [SVWS-NRW/Schild3-BetaTest#966]
Will ich bei einem Schüler mit vielen Fächern in der Übersicht über die einzelnen Halbjahresergebnisse mit dem Mausrad nach unten scrollen, hängt die Ansicht in den meisten Fällen für ca. 1-2 Sekunden. Dann wird gescrollt, um direkt wieder zu hängen. 
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/161251858/8e9c90ed-69a9-4aa4-a729-7be1eba6a2e4)

**Comment by AnneSchueller** [comment]
Das kann ich reproduzieren. Ich vermute, dass der Cursor anfangs auf der ersten Zeile steht. Beim Scrollen wandert er dann zeilenweise runter und erst wenn die Zeile, die außerhalb der Oberfläche liegt, erreicht ist, wandert das Bild runter.

Am Layout dieses Reiters wird derzeit noch gearbeitet mit dem Ziel, dass möglichst alle relevanten Fächer direkt auf der Oberfläche sichtbar sind und ein Scrollen überflüssig wird (zumindest bei den gängigen Monitoren)
Daher schließe ich das Issue vorerst.
