### ISSUE TITLE
Spaltenbereite im Dropdown-Menu der akt. Schülerauswahl

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#967]
Insbesondere am BK wäre das Anpassen der Spaltenbreite sinnvoll, da teilweise Einträge abgeschnitten sind

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/fb89ba0e-f269-4069-b626-212658f96d02)

**Comment by JuergenRichter** [comment]
Die Drop-Downliste ist nun auf "Sizeable" gesetzt (rechts unten)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/0846eee4-6606-4373-af62-80be59955e56)
