### ISSUE TITLE
Statistik: Keine Klassenlehrer im akt. Abschnitt

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/Schild3-BetaTest#969]
Wenn man die Statistik-Gesamtprüfung von Schild2 mit Schild3 nach der Migration vergleicht.
So kommt der Fehler "Klassenlehrer im akt. Abschnitt fehlt" bei allen oder fast allen Schülern.

Wir holen uns nun die Klassenlehrer ja anders aus der KlassenTabelle.
Muss dort noch das Befüllen der StatistikDB angepasst werden?

**Comment by JuergenRichter** [comment]
Hier mal ein Screenshot aus der StatistikDB.mdb:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/cfc154ca-1527-45ae-86f4-ff4f72420f24)

**Comment by FPfotenhauer** [comment]
Wir haben den Fehler gefunden.
Es trat bei einer Datenbank auf, in der der Quartalsmodus "entfernt" wurde.
