### ISSUE TITLE
Feld für aktuellen Schüler beibehalten

### ISSUE THREAD

**Issue by ADV-Fendel** [SVWS-NRW/Schild3-BetaTest#97]
Im Bereich Schüler gibt es unter den Reitern Individualseite I und II das Feld aktueller Schüler. Dieses Feld verschwindet bei den übrigen Reitern. Ich denke, es wäre sinnvoll, dass dieses Feld unter allen Reitern sichtbar bleibt.
Die übrigen Angaben (interne ID und letzte Änderungen) in diesem Feld finde ich an dieser Stelle nicht sinnvoll. Vielleicht könnte im unteren Bereich dafür ein Feld eingerichtet werden.

**Comment by ADV-Fendel** [comment]
Das Feld Aktueller Schüler ist beim erstaufruf des Programmes nicht sichtbar. Erst wenn ich auf die Individualseite II wechsel wird es sichtbar. Außerdem möchte ich noch einmal bekräftigen, dass es gut wäre, wenn ich immer und bei allen Reitern sehen könnte, um welchen aktuellen Schüler es sich handelt.

**Comment by FPfotenhauer** [comment]
Auf dem Reiter "Akt. Halbjahr" würd eich das eher als störend empfinden.

**Comment by FPfotenhauer** [comment]
Nach einer Umfrage teilen sich die Meinungen 50:50.
Ggf. machen wir das einstellbar.
