### ISSUE TITLE
In der Ribbonleiste "Reports" fehlen Icons

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#972]
Version 3.0.85.10

**Comment by FrodBRA** [comment]
Bei mir fehlt auch noch ein Icon bei:
- Verwaltung -> Online- Supportprogramm starten
- Schüler -> Filter auf markierte Schüler aufheben

Ansonsten: Die Icons in "Reportverwaltung" sind bei mir alle da.

**Comment by JuergenRichter** [comment]
Bitte maö prüfen, welches Datum die Datei "Schild_Icons.db3" hat. In dieser Datei sind die "Ereignisdefinitionen" hinterlegt. Das steht zu jedem "Ereignis" (z.B. Online-Supportprogramm starten) drin, welches Icon (in Abhängigkeit vom gewählten Icon-Thema) und welche Schalter-Beschriftung erscheinen soll. Die aktuelle Datei hat das  Datum 27.02.2024.

**Comment by AnneSchueller** [comment]
Die Überschrift, die ich gewählt habe ist wahrscheinlich irreführend.
Ich meinte nicht nur das Icon, sondern den gesamten Button:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/0ba4590c-0c2e-4597-81af-54d58347c3a7)

Früher:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/9a62164b-a70b-4863-a45f-862625b0479e)

**Comment by JuergenRichter** [comment]
Jetzt weiß ich was gemeint ist. Ich habe die Icons auf der linken Seite aus Platzgründen (5 Icon = 3 Spalten) erst mal ausgeblendet. Ich vermute mal, dass die meisten Anwender die fehlenden Icons sowieso eher über die rechte Maustaste aktivieren werden (da gibt es sie ja noch), weil der "Mausweg" von der Listenanzeige der Reportvorlagen bis in die obere like Ecke doch recht unkonfortabel ist.
Bei Bedarf können die Icons aber wieder eingeblendet werden.
