### ISSUE TITLE
Skalierungsfehler Ribbon "Auswahl": Problem mit zweizeiligen Inhalten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#973]
3.0.85.10

"Schülerfilter" wird das "r" auf die zweite Zeile geschoben
"Vorhandene Filterdefinitionen bearbeiten" passt nicht mehr.

![Ribbon](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/31c295d7-ba95-44c2-ad61-7dbafd4f8b9a)

**Comment by AnneSchueller** [comment]
Das kann ich nicht reproduzieren...
Ist das die Version, die ich Dir am 11.3. geschickt habe?

**Comment by AnneSchueller** [comment]
@Raffenberg : sieht das bei Dir ähnlich aus, wie bei Felix?
Ich kann das nach wie vor nicht reproduzieren.
@FrodBRA : Welche Skalierung hast du eingestellt?

**Comment by Raffenberg** [comment]
Ich kann das bei mir nicht nachstellen. Die Anzeigen waren bei mehreren Auflösungen immer korrekt.

Was haltet ihr davon, die Ribbon-Texte kürzer zu halten? Der Ribbon für sich ist ja sprechend, die Kategorie abermals, somit alle Buttons in Abhängigkeit kürzbar. Zudem lernt man das ja auch fix. Beispiel: Wenn ich den Ribbon "Auswahl" aktiviere, will ich ja was auswählen. In der Sektion "weitere Filteroptionen" finde ich den Button "Schülergruppe auswählen". Mit ist ja klar, dass ich unter "Auswahl" etwas auswählen will. Folglich reicht "Schülergruppe". So wird das auch in Office-Programmen gehandhabt. Dadurch würden ggf. auch Ansichtsprobleme mit zweizeiligen Ribbonbeschreibungen wegfallen.

Ich weiß, das ist ein dickeres Brett, sollte aber unproblematisch umzusetzen sein und schafft ggf. Klarheit und Platz.

Verwaltung:
Sektion "Hilfe":
- Info
- Wiki
- Fernwartung
- Forum
- Notenliste
- Versionsgeschichte

Lehrkräfte
Sektion "Bearbeitung"
- Einfügen
- Bearbeiten
- Übernehmen
- Löschen
- Aktualisieren
- Abbrechen
Sektion "Aktionen"
- Import
- Export
- UVD berechnen
Sektion "Filteroptionen"
- Sichtbare
- Alle
- Statistikfehler

Schüler
Sektion "Bearbeitung"
- Einfügen
- Bearbeiten
- Übernehmen
- Löschen
- Aktualisieren
- Abbrechen
- Sektion "Suchen, filtern und sortieren"
- Standard
- Markierte
- Zurücksetzen
- Sortierung
- Suchen
Umbenennen der Sektion "Andere Funktionen" in "Aktionen" und schmaler machen
- Wiedervorlage
Sektion "Drucken"
- Schulbescheinigung
- Stammblatt
- Standard-Formulare

Auswahl
Sektion "Standard-Filteroptionen"
- Standard
- Schülerfilter (was macht die Schaltfläche eigentlich?)
Sektion "Weitere Filteroptionen" (hier würde ich das W groß schreiben)
- Schülergruppe
- Markierte
- Fehlende Einträge
- Statistikfehler
- Papierkorb
- Ohne Fächer
- Filter laden
- Filter bearbeiten
- Geschwister

Gruppenprozesse
- alles so lassen

Reportverwaltung
Neue Sektion "Aktualisieren". Dort dann
- Verzeichnisbaum
- Druckerliste
Neue Sektion "Info". Dort dann
- Standardformulare
- Datenquellen
- den Rest so lassen 

Was meint ihr?

**Comment by FrodBRA** [comment]
@AnneSchueller 4k (3840*2160), 150%.

@Raffenberg Ich bin absolut für eine Verkürzung der Texte

**Comment by Raffenberg** [comment]
@JuergenRichter In der oben genannten Auflösung kann ich das Anzeigeproblem bestätigen.

**Comment by FrodBRA** [comment]
Wir müssen auch für höhere Skalierungen testen, da SchILD von Haus aus keine größeren Schriftarten mehr anbietet und Leute mit schlechterer Sicht damit in Bezug auf Windows aber auch auf SchILD über Windows-Funktionen gehen müssen und werden.

Die Erfahrung in Schulungen zeigt, dass viele Leute in der Praxis SchILD2 mit SchILD-2-Skalierungen von 125% oder 150% betrieben haben. Beide sind größer, als die 150%-Skalierung von Windows in 4K, die eher dem Verhältnis von FullHD@100 entspricht. 

SchILD3 muss somit auch mit Windows-Skalierungen von FullHD@(>100%) und höheren Auflösungen über der (Empfohlen)en Skalierung betrieben werden können - 150% ist für 4K  in Windows die empfohlene Einstellung.

Daher ist die Verkürzung der Text, so vermute ich, sogar notwendig.

**Comment by Raffenberg** [comment]
Ich habe aus dem Grund eigentlich immer mit 1920x1080 bei 125% und 4K bei 175% getestet. Bei 175% tritt der Fehler nicht auf.
Bei den empfohlenen Auflösungen 1920x1080 bei 100% und 4K bei 150% teste ich meist nicht, da Full HD bei 100% in der Vergangenheit immer gut aussah und mir 4K bei 150% schon für mich zu klein ist. Deshalb ist mir da der Fehler durchgegangen.

Vielleicht wäre auch jetzt ein guter Zeitpunkt, die Oberfläche in allen Auflösungen nochmals zu testen. Ich würde das dann bei Full HD machen. @Felix kannst Du dann das Programm mal in 4K durchgehen? Hat jemand einen Monitor mit der Auflösung 2560x1440?

**Comment by FrodBRA** [comment]
4K in 100%, 150% und 200% sieht in Ordnung aus.

Bei 150% sind nur die reporteten Issues aufgefallen.

**Comment by AnneSchueller** [comment]
Textverkürzungen finde ich gut. Die Vorschläge von Herrn Raffenberg finde ich auch gut.

Bei den Lehrkräften Sektion "Filteroptionen" fände ich "Mit Statistikfehlern" besser als nur "Statistikfehler"
Analog bei den Schülern Sektion "Weitere Filteroptionen" "Mit Statistikfehlern"

Im Reiter Schüler fände ich es gut, wenn
Filter auf markierte Schüler und Filter auf markierte Schüler aufheben (kurz Markierte und zurücksetzen) unmittelbar untereinander angeordnet wären, da sich das zurücksetzen hier nur auf die Markierten bezieht

In der Reportverwaltung sollte m.E. die Sektion "Bearbeitung" wieder ergänzt werden.

vgl hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/972#issuecomment-1992353163

Wenn das vom Platz nicht passt, kann man das evtl nur auf "Neu" und "Bearbeiten" beschränken.

**Comment by JuergenRichter** [comment]
Ist jetzt wie vorgeschlagen umgesetzt, ich schließe das Issue
