### ISSUE TITLE
Schüler - Schulbesuch - kein Eintrag im Feld Schulnummer möglich

### ISSUE THREAD

**Issue by pemichalski** [SVWS-NRW/Schild3-BetaTest#977]
Im Kartenreiter "Schüler" ist es im Reiter "Schulbesuch" nicht möglich, einen Eintrag im Feld "Schulnummer" vorzunehmen.
Dementsprechend sollte es ausgegraut werden. 
Alternativ könnte hier die Eingabe der Schulnummer ermöglicht werden, wodurch das Feld "Name der Schule" dann automatisch ausgefüllt wird.

![Schulnummer](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/130543126/dc0886aa-0bd7-43f9-be0e-1df22cfe2e33)

**Comment by AnneSchueller** [comment]
Das Feld sollte ausgegraut werden, analog zu den Felder unter Individualdaten Schulbesuchsjahre und co.

Das Eintragen der Schulnummer wurde hier schonmal diskutiert. M.E. sollte das Vorgehen erstmal so bleiben.
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/645

**Comment by JuergenRichter** [comment]
Ist jetzt ausgegraut
