### ISSUE TITLE
Basisreportsammlung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#978]
- Klassenliste Geburtgstagsliste @KL: Nach Vorschau beim Schließen
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/116796098/8926f034-fcfa-4a32-8f12-77ff6a893562)

Gleiches beim "Schülerliste Geburtstagsliste"

Ansonsten laufen alle bei mir vorliegenden Reports ohne Probleme.

**Comment by AnneSchueller** [comment]
Die Fehlermeldung erscheint beim Schließen und liegt an diesem Befehl:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/b094d2f6-d5ef-4af1-b973-f6c4c2d2ce7c)

Kommentiert man diesen aus, erhält man keine Fehlermeldung.

**Comment by JuergenRichter** [comment]
Behoben
