### ISSUE TITLE
Karteireiter Vermerke

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#979]
Ich finde den neuen Karteireiter Vermerke wirklich gut, allerdings gibt es einen Nachteil, wenn die Vermerke wie bei uns sehr stark inklusive der Vermerkbemerkungen genutzt werden. Aktuell muss nur einmal auf den Vermerk geklickt werden und der gesamte Inhalt der Vermerkbemerkung wird sichtbar. Das geht sehr schnell.
Jetzt wird zwar ein Teil der Bemerkung bereits angezeigt, aber bei ausführlichen Bemerkungen ist ein Doppelklick notwendig. Kann nicht die Zellenhöhe auf Wunsch oder beim einfachen Klicken auf den Vermerk dynamisch sein? Wäre für uns eine sehr gutes Feature.
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/a2cd7194-a9e0-4bc2-89b2-1b3184b3a5af)

**Comment by JuergenRichter** [comment]
Ich habe bei der Tabelle mal die Eigenschaft "RowSizingAllowed" gesetzt, damit kann man die Zeilenhöhe anpassen.

**Comment by JuergenRichter** [comment]
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/f40efb65-5ea2-4959-a474-c91757f63b81)
