### ISSUE TITLE
Darstellungsfehler Karteireiter Abitur (Laptop)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#980]
Im Karteireiter Abitur kann ich die weiteren Angaben nicht erkennen. (Hinweis: Außerdem stimmt die Zulassungsberechnungen nicht. Mache dafür einen neuen Eintrag)
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/edd10fd4-4cbd-4974-878b-8ac086dac3e8)

**Comment by FrodBRA** [comment]
Welche Auflösung nutzt der Laptop?

**Comment by JuergenRichter** [comment]
Ist das Problem noch aktuell? Wir haben ja einige Layoutänderungen gemacht, die u.a. mehr Platz zur Verfügung stellen sollten?

**Comment by AnneSchueller** [comment]
Bei mir passt das jetzt auch auf meinem kleinen Surface...
Ich schließe das daher mal.
