### ISSUE TITLE
Darstellung des Kalenders im Filter Vermerke und Fehlermeldung

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/Schild3-BetaTest#982]
Auf meinem Laptop wird der Kalender im Filter der Vermerke wie folgt dargestellt:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/72dabdae-ec7d-4332-987a-f7d112fb2bbe)

Außerdem erhalte ich folgende Fehlermeldung (der SVWS-Server ist noch nicht auf dem aktuellsten Stand, falls sich da etwas geändert hat kann der Eintrag gelöscht werden):
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/75179015/1aa290a7-610f-4f32-b1f6-c3e774d82468)

**Comment by JuergenRichter** [comment]
Beide Probleme sind schon behoben, eine neue Version wird demnächst zur Verfügung gestellt. Ich schließe das Issue daher erst mal.
