### ISSUE TITLE
Schuljahresabschnitts-ID wird bei Hochschulung nicht ersetzt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/Schild3-BetaTest#984]
Nach der Hochschulung steht in der Tabelle schueler noch die alter Schuljahresabschnitts-ID.
In der Tabelle "eigene Schule" ist die Ersetzung korrekt.

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren, bei mir steht bei allen SuS, die im neuen Abschnitt den Status "Aktiv" haben, nach dem Wechsel auch in der Tabelle "schueler" die korrekte Schuljahresabschnitts_ID. Ich habe das sowohl mit dem Halbjahreswechsel als auch mit dem Schuljahreswechsel probiert.

**Comment by JuergenRichter** [comment]
Im übrigen müsste das auch sofort auffallen, da ja allen aktiven SuS, bei denen die Schuljahresabschnitts_ID von der der Schule abweicht, pink markiert werden (wie in SchILD2).

Hier mal manuell bei einem Datensatz erzwungen:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/26dbfc35-1ac1-4ea5-ae82-bc295b3239e2)

**Comment by AnneSchueller** [comment]
In Schild3 stimmt auch alles, allerdings werden die SuS im Client nicht hochgeschult. Hier ist das entsprechende Issue im SVWS-Git:

https://github.com/SVWS-NRW/SVWS-Server/issues/158

**Comment by JuergenRichter** [comment]
> In Schild3 stimmt auch alles

Aber was hat dann SchILD3 dann mit dem Problem zu tun?

> allerdings werden die SuS im Client nicht hochgeschult.

Wenn in der Datenbank aber alles stimmt: Woher holt sich der Client denn die Informationen? Oder ist da evtl. noch was im Cache?

**Comment by JuergenRichter** [comment]
Noch ein Hinweis:

> Nach der Hochschulung steht in der Tabelle schueler noch die alter Schuljahresabschnitts-ID.

Bei SuS, die z.B. den Status "Abschluss" oder "Abgänger" haben,  kann (und muss!) das natürlich so sein. Bei diesen SuS ändert sich die Angabe bei Schuljahresabschnitts_ID beim Abschnitts- oder Schuljahreswechsel  nicht. Bei denen verweist der Eintrag auf den Abschnitt, in dem sie zuletzt an der Schule waren.

**Comment by AnneSchueller** [comment]
Nach erneutem Test: Der Fehler ist in der Tabelle client_configuration_benutzer:

Die Daten werden nicht angepasst nach der Hochschulung:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/79116896/a20d5eb1-8376-4303-b95d-d4260704e45f)

**Comment by AnneSchueller** [comment]
@FPfotenhauer : Oder muss das über den Client angepasst werden?

**Comment by AnneSchueller** [comment]
Klappt mit der neuen Version nach einem Neustart vom Client
