### ISSUE TITLE
Tabelle EigeneSchule_Kursart wird bei Migration nicht übernommen

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/Schild3-BetaTest#985]
Ich habe heute eine Test-MDB migriert (Gymnasium) und musste anschließend feststellen, dass die Tabelle EigeneSchule_Kursart nicht migriert wurde. Bei einer anderen Schule (Grundschule) hat es einwandfrei funktioniert. Ich habe die MDB mal beigefügt.
[GY_2023-24.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/14997861/GY_2023-24.zip)

**Comment by AnneSchueller** [comment]
Das liegt daran, dass die Schulnummer aus der Tabelle eigeneSchule nicht mit der Schulnummer übereinstimmt, die in der Tabelle EigeneSchule_Kursart vermerkt ist. Im Log kommt diese Fehlermeldung:
"Entferne ungültigen Datensatz, da die Schulnummer der Kursarten nicht mit der Schulnummer aus EigeneSchule übereinstimmt. Die Quell-Datenbank sollte überprüft werden."
 
 Nach Anpassung der Schulnummer funktioniert die Migration der Kursarten.
