### ISSUE TITLE
Gruppenprozess Mahnungen drucken filtert falsch

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#987]
Wenn ich auf Mahnungen drucken klicke, wird noch falsch gefiltert.

Im 1. Halbjahr müssen alle SuS mit Mahnhäkchen im ersten Halbjahr gefiltert werden. Die Pipeline Warnungen wird mit allen Fächern gefüllt, unabhängig davon, ob ein Datum hinterlegt ist, oder nicht (es sei denn, der zweite Haken ist aktiviert "Nur Mahnungen ausgeben, bei denen...")
Im 2. Halbjahr müssen alle SuS mit Mahnhäkchen im zweiten Halbjahr gefiltert werden. Hierzu muss genau geprüft werden, ob das Mahnhäkchen kein Datum trägt, oder ein Datum >= März und <= Juli. Hochgeschriebene Mahnhäkchen aus dem ersten Halbjahr > Juli und < März müssen unberücksichtigt bleiben. Nach der Filterung muss die Pipeline Warnungen jedoch mit allen gemahnten Fächern befüllt werden, also auch mit den hochgeschriebenen aus dem ersten Halbjahr. Der Report gibt diese zwar nicht aus, benötigt diese aber zur Analyse.

Momentan werden z.B. noch SuS gefiltert, die im 2. Halbjahr nur hochgeschriebene Mahnhäkchen aus dem ersten Halbjahr eingetragen haben (entweder aufgrund von Epochalfächern oder aufgrund von Defiziten auf dem Halbjahreszeugnis.

**Comment by JuergenRichter** [comment]
Wird denn im 1. Hj. korrekt gefiltert?

**Comment by JuergenRichter** [comment]
Mir ist noch nicht ganz klar, was die Häkchen für Auswirkungen haben sollen:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/b4a22086-98e0-4a1b-a4f4-40f084be6beb)

Was bedeutet "Mahnungen für den Serienbrief filtern?"
Soll dann nach den o.a. Regeln gefiltert werden? Welchen Sinn hat dann die andere Option "Nur Mahnungen ausgeben, bei denen das Mahndatum noch nicht gesetzt ist".

Wenn die sich gegenseitig ausschließen, wäre es nicht besser, das z.B. so zu gestalten?

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/4d916b79-43cc-4f4c-bf87-1525dd05ffab)

**Comment by Raffenberg** [comment]
Im Ersten Halbjahr wird stumpf auf alle gemahnten Fächer gefiltert und diese werden auch an die Pipeline Warnungen übergeben. Hierbei ist es irrelevant, ob ein Mahndatum gesetzt ist, oder nicht.

Der Gruppenprozess ist schon so in Ordnung. Das zweite Häkchen sehe ich eher als eine einschränkende Filteroption. So kann man auf SuS filtern, die noch keinen Mahnbrief erhalten haben, oder wo nachträglich eine Mahnung dazu gekommen ist. trotzdem muss dann auch bei diesen neu gemahnten SuS die Pipeline mit allen gemahnten Fächern aus dem ersten und zweiten Halbjahr gefüllt werden. Mann könnte das Häkchen allerdings nach rechts einrücken, so dass man diese Eingrenzung auch optisch sieht.

Schwieriger wird es bei den Datumsfeldern. Besser wäre es, wenn der Mahndatumsbereich einen eigenen Radiobutton erhalten würde, der mit dem ersten Mahnhäkchen gekoppelt wird (also in einen Radiobutton umgewandelt wird). Hierdurch hat man entweder die Möglichkeit, Mahnbriefe zu drucken (mit weiteren Einschränkungen durch das zweite Häkchenfeld) ODER eine Übersichtsliste mit z.B. allen gemahnten SuS und Fächern für die Klassen- und Schulleitungen.

Beispiel: Zuerst werden die aktuellen Mahnbriefe des zweiten Halbjahres gedruck, indem der erste Radiobutten aktiviert ist (Standardeinstellung). Nach dem Druck der Mahnbriefe undsetzen der Mahndaten wird nu der zweite Radiobutten ausgewählt und ein Zweitraum des Gesamten Schuljahres als von ... bis ... eingestellt. Auf diese Weise kann man eine Schülerliste drucken, die alle gemahnten Fächer mit Mahndatum des ganzen Schuljahres auflistet. Diese würde dann auch gemahnte Epochenfächer aus dem ersten Halbjahr enthalten, die ja in das zweite Halbjahr mitgeschleppt wurden.

Der Mahnbrief benötigt zwar nur die Schülermenge, die Mahnungen im zweiten Jahr hinzubekommen haben, aber innerhalb dieser Schülermenge alle gemahnten Fächer, also auch die des ersten Halbjahres. Der Serienbrief gibt die gemahnten Fächer aus dem ersten Halbjahr zwar nicht aus, benötigt diese aber für den korrekten Satzbau, da hier ein Wort -auch- ein und ausgeblendet wird.

Noch eine Anmerkung. Wenn der Gruppenprozess korrekt filtert kann man auch auf einen Report mit Pipeline Leistungsdaten ausweichen, den wir auch schon in Schild 2 nutzen. Streng genommen muss man dann nicht über die Pipeline Warnungen gehen. Das ist auch für die manuelle Auswahl eines Schülers viel einfacher, ohne über den Gruppenprozess drucken zu müssen. Das macht vieles für den Endanwender einfacher.

Wir können aber auch gerne über das Vorgehen telefonieren, weil das nicht ganz banal ist.

**Comment by JuergenRichter** [comment]
Ein Telefongespräch wäre nicht schlecht. Geht es bei Ihnen morgen gegen 13:00?

**Comment by JuergenRichter** [comment]
Können Sie mich anrufen? Ich habe Ihre Nummer nicht.
