### ISSUE TITLE
Schnellfilter Icon-Aktivierung

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#989]
Wenn eine Klasse im Schnellfilter ausgewählt wird, wird der Haken aktiv und rot dargestellt.
Das Filter-Icon ist auch aktiv. Wenn das geclickt wird, ohne dass vorher der Haken geclickt wurde,
wird der Haken deaktiviert und die Auswahl bleibt in Klasse bestehen. 
Hier zu sehen.
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/f96c5e93-ff7f-4711-b6d2-b3a192cb9add)
Jetzt muss erst eine andere Klasse gewählt werden, damit der Haken aktiviert wird.

Eine mögliche Lösung wäre, dass das grüne Filtericon nicht auf clicks reagiert (die Standardfilterung ist ja noch richtig dargestellt).

**Comment by AnneSchueller** [comment]
Alternativ könnte die Klasse BMA21 in dem Fall aus dem Feld Klasse verschwinden, da man ja wieder die Standard-Auswahl geklickt hat. Dann wäre das das gleiche Verhalten wie beim Klick auf die Standard-Auswahl, wenn der Trichter gelb ist.

**Comment by JuergenRichter** [comment]
Ist umgesetzt

**Comment by AnneSchueller** [comment]
Funktioniert.
