### ISSUE TITLE
Datenbankpipeline in Pipeline nicht besetzt - Serienbrief Erzieher

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/Schild3-BetaTest#992]
Wenn ich den Serienbrief Erzieher verwende, werden für folgenden Datenfelder keine Werte ausgegeben:

- Schueler['Zusatz']
- SchuelerKlasse['LTitel']
- SchuelerKlasse['StvLTitel']
- EigeneSchule['SchulleiterTitel']
- EigeneSchule['StvSchulleiterTitel']

**Comment by Raffenberg** [comment]
Anbei die Serienbriefe mit Platzhalter-rtf zum testen.

[Serienbriefe.zip](https://github.com/SVWS-NRW/Schild3-BetaTest/files/15038056/Serienbriefe.zip)

**Comment by JuergenRichter** [comment]
Kann ich nicht reproduzieren. Ich habe die Felder mal in den Report eingefügt:

![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/0a16c271-3a9c-4294-83d5-280392f3a469)

**Comment by Raffenberg** [comment]
Hallo Herr Richter,
tatsächlich. Hier hat auch anscheinend das Anonymisierungstool zugeschlagen.
