### ISSUE TITLE
Abitur: Kurse Markieren findet Datenbankfeld nicht:

### ISSUE THREAD

**Issue by EwaldReinhardt** [SVWS-NRW/Schild3-BetaTest#993]
Version 3.0.84.10 / 0.8.10

Nach der Migration zu Schild3 lässt sich die Abiturberechnung nicht mehr richtig ausführen:
Das Markieren der Kurse schlägt mit folgender Fehlermeldung fehl:
![grafik](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/44644567/317f0d91-4c3b-4376-a28c-44dc4c6d43fa)
[FehlerAbiMarkieren.txt](https://github.com/SVWS-NRW/Schild3-BetaTest/files/15040618/FehlerAbiMarkieren.txt)

**Comment by AnneSchueller** [comment]
Ist das eine BK DB?
Ich kann das nicht reproduzieren.

**Comment by EwaldReinhardt** [comment]
Ja, das ist eine BK Datenbank.
Habe auch in ein komplett neues Schema migriert.

**Comment by JuergenRichter** [comment]
Behoben
