### ISSUE TITLE
Mahndatum setzen/ändern/löschen + gefährliches Verhalten führt zu unabsichtlicher Löschung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#996]
Version 3.0.85.10

Schüler > Akt. Halbjahr > Leistungsdaten 

1. Klickt man mit der rechten Maustaste auf den Mahnungshaken, öffnet sich ein Texteingabefeld, kein Datumswahlfeld. **Vorschlag: Es wird ein Datumsfeld verwendet.**

2. Wurde ein Mahndatum gesetzt und ruft man dieses Feld auf, wird das Datum hierbei nicht angezeigt. **Vorschlag: Der gesetzte Wert wird angezeigt.**

4. Das Verhalten, dass das Mahndatum unten angezeigt wird, wenn man die Zeile des Fachs aktiviert ist sehr gefährlich, denn klickt man den Mahnungshaken an, wird dieser sofort entfernt - und damit wird das Mahndatum gelöscht. **Vorschlag: Ein Doppelklick setzt und entfernt den Haken, ein Einfachklick wählt nur die Zeile.**

**Comment by Raffenberg** [comment]
Das ist mir auch aufgefallen. Auch bei den Epochalhaken. Mir ist das mehrmals passiert, dass ich unabsichtlich Häkchen durch einen Einfachklick entfernt habe.

Ich unterstütze den Doppelklick sehr.

**Comment by FrodBRA** [comment]
Ich bin sogar für "Hohe Priorität": das ist ein gefährliches Verhalten des Programms, das schnell zu Fehlern führt, und damit eventuell zu Mehrfachmahnungen oder zu einer Unnachvollziehbarkeit, was nun denn an die Eltern gemahnt wurde und was nicht, was formal unschön wirkt.

**Comment by JuergenRichter** [comment]
Ich hatte vor einiger Zeit schon mal zur Diskussion gestellt, wie "Häkchenfelder" gesetzt werden sollen (das Verhalten ist bei den neuen Grid-Komponenten ein anderes als bei den alten). Ich meine mich zu erinnern, das damals für "Einfachklick" votiert wurde.

**Comment by Raffenberg** [comment]
Das kann tatsächlich sein. In der Anwendung habe ich hier aber auch oft unabsichtlich Häkchen weggenommen, weshalb ich doch deutlich für den Doppelklick votieren würde. Alles andere wäre fatal, weil man die zeile anklicken muss, um das Mahndatum zu sehen. Mir ist das mehrmals passiert.

**Comment by JuergenRichter** [comment]
Ich habe das jetzt erst mal für das Hauptfenster so gelöst, dass ein Einfachklick in "Checkbox-Spalten" keine Auswirkung hat, ein Änderung ist per Doppelklick möglich.
