### ISSUE TITLE
GP "Mahndatum drucken": Falscher Text

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/Schild3-BetaTest#997]
3.0.85.10

Im GP "Mahnungen drucken" steht, dass auf die "zu mahnenden SuS gefiltert" würde, dann würde der "Reportexplorer gestartet". Genau das passiert in SchILD 3 aber nicht mehr, der Reportexplorer ist mit der nun ausgewählten Schülermenge im Container manuell zu starten. 

Wurden Veränderungen durchgeführt und es soll nun direkt gemahnt (per Report) werden, ist der Reportexplorer unbedingt zu starten, damit die Schülermenge nicht verloren geht.

**Comment by JuergenRichter** [comment]
Neuer Text:
![image](https://github.com/SVWS-NRW/Schild3-BetaTest/assets/61280188/ac5ffea5-35a5-4ae2-aa60-3c7e18857778)

**Comment by FrodBRA** [comment]
Tippfehler: "und drucken Sie die diesen" -> "und drucken Sie diesen". 

Ich würde auch das erste "und" durch ein "," ersetzen. "in die Reportverwaltung, wählen Sie den gewünschten"
